### ISSUE TITLE
wrong scaling of distribution - distplot

### ISSUE THREAD

**Issue by roscha** [mwaskom/seaborn#1000]
Hi, 

I encountered an issue with the scaling of distribution or the normalization. (norm_hist true or false)
If I plot the normalized distribution or not, I obtain the same figure [which is this one](https://1drv.ms/b/s!ApPwUjpLIL5sioEnMq54vy-UGJm9Fw).

With plt.hist, I obtain a more convincing figure with a [count up 1500](https://1drv.ms/b/s!ApPwUjpLIL5sioEl-ipuDb999bptyw).

knowing that the grey curve contain all my feature and all others curves are a subset of them, they can only by smaller that the grey curve [like in the matplotlib figure](https://1drv.ms/b/s!ApPwUjpLIL5sioEmTV-uiuYoKGQ5zg) if I don't normalize histogram. 
In both case I adjust the number of bins to have the same size of bin between curve : 0.02

I already notice previously a problem with the scaling. Can it be due to the model fitted ? And linked to the fact that the normalization option doesn't work ?

I hope this is helpful (because the figure is really nice, it's a shame, I can't use it)

Roselyne

**Comment by mwaskom** [comment]
Why do you think the normalization option "doesn't work"?

**Comment by mmagnuski** [comment]
@roscha - you are probably referring to the fact that each histogram is normalized separately, right? (and bear in mind that y shows density then, not count, as your ylabel suggests)

**Comment by mmagnuski** [comment]
BTW: @mwaskom, it's your 1000th issue! :tada: :cocktail: :smile:

**Comment by roscha** [comment]
(I know congratulation ! especially because only 60 of them are still open :O ) so you don't have the possibility to have "not normalized" histograms ? so what is the norm_hist option is doing ? I thought it was to define if you want a "count" or a "density"

Or do I have to scale it back ? So to answer you, I am interested in the not normalized histograms

**Comment by mwaskom** [comment]
From the docs:

```
norm_hist : bool, optional
If True, the histogram height shows a density rather than a count. This is implied if a KDE or fitted density is plotted.
```

You are plotting a density, therefore the histogram has to be normalized.

**Comment by roscha** [comment]
... I see
this makes sense,
thanks you
so the fitting step needs a normalized histogram, that's the point, right ?
but I guess you could have the option of the fitted curve with the count and not only the density. by reversing the normalization after fitting the curve and scale it back. 

I will go for something like accessing the curve and scale it back then :)

:+1: no big fun for this 1000th issue ;)
thank you for your help
