### ISSUE TITLE
distplot(data, cumulative=True)

### ISSUE THREAD

**Issue by mikolchon** [mwaskom/seaborn#1002]
Hi, is there a way to do what the title suggests? Suppose I want to plot a cumulative histogram + its CDF:

```
import numpy as np
import pandas as pd
import seaborn as sns
s = pd.Series(np.random.normal(size=1000))
```

I can plot the cumulative histogram using pandas with `s.hist(cumulative=True, normed=1)`, and I can plot the kde fit using seaborn with `sns.kdeplot(s, cumulative=True)`, but why not implementing something like `distplot(s, cumulative=True)`?

**Comment by mwaskom** [comment]
> Hi, is there a way to do what the title suggests?

No, there isn't, sorry.

**Comment by eikevons** [comment]
Actually, you can do something like `distplot(s, hist_kws={'cumulative': True}, kde_kws={'cumulative': True})`.
