### ISSUE TITLE
Precision for Pearson's R in jointplot

### ISSUE THREAD

**Issue by wfbradley** [mwaskom/seaborn#1003]
By default, jointplot prints Pearson's R in the upper right hand corner of a jointplot.  I think it prints this to two decimal places of precision.

Suppose a set of data has a Pearson's R value of 0.997.  Then jointplot will print
    pearsonr=1
I think it should print
    pearsonr=1.00
so that a viewer is (hopefully) not misled into thinking the correlation is perfect.  I'm attaching an image of a (clearly not perfectly correlated) data set along with the "=1" issue.

![screen shot 2016-09-02 at 1 43 50 pm](https://cloud.githubusercontent.com/assets/6954765/18212945/e3408620-7113-11e6-9eb4-0e157c98e1b6.png)

**Comment by mwaskom** [comment]
You can pass a different template if you want but your issue is with the rules for python string formatting with `g` type which are outside of my control.

**Comment by wfbradley** [comment]
It's not straightforward to do something like this?
```
In [1]: print '%.2f'%.997
1.00
```

**Comment by mwaskom** [comment]
Pick your corner case:

```python
python -c 'print("{:.2f}".format(.0001))'
0.00
```

**Comment by wfbradley** [comment]
But isn't "0.00" the desired output?  As opposed to "0", where somebody looking at the plot wouldn't know the precision?

**Comment by mwaskom** [comment]
No, because what happens now is:

```python
python -c 'print("{:.2g}".format(.0001))'
0.0001
```

**Comment by mwaskom** [comment]
If you are going to insist on arguing with me about it, please actually look at the code so you know how it is working.
