### ISSUE TITLE
tsplot color argument not treated correctly with ordered pandas categoricals?

### ISSUE THREAD

**Issue by nwilming** [mwaskom/seaborn#1004]
First of all: Really fantastic work. Thanks a lot!

When using a dictionary to assign colors to conditions with tsplot, it seems that the color assigment breaks when the condition arugment is a pandas series of type categorical with ordered=True.

Example:

```
import seaborn as sns
import pandas as pd

df = pd.DataFrame({'time':[1,2,3,4,5,6, 1,2,3,4,5,6, 1,2,3,4,5,6, 1,2,3,4,5,6], 
                   'value':[1,1,1,1,1,1, 3,3,3,3,3,3, 2,2,2,2,2,2, 4,4,4,4,4,4], 
                   'condition':[1,1,1,1,1,1, 3,3,3,3,3,3, 2,2,2,2,2,2, 4,4,4,4,4,4]})
df['unit'] = 1

df.loc[:, 'condition'] = df.condition.astype('category', ordered=True)
colors = {1:'r', 2:'g', 3:'k', 4:'c'}

sns.tsplot(data=df, time='time', unit='unit', value='value', condition='condition', color=colors)
ylim((0, 5))
```

I would expect that condition 2 is colored green and condition 3 is colored black, but I get the following plot:

![index](https://cloud.githubusercontent.com/assets/623604/18244021/333899a0-735e-11e6-88d7-f51c9189e9d0.png)

In this plot condition 2 and 3 are confudesd. Changing the categorical to non-ordered fixes the issues. This also seems to depend on the ordering of the data - ordering the conditions in ascending order fixes the issue as well. 

I'm on seaborn 0.6.0.

**Comment by mwaskom** [comment]
Hm I am not sure off the top of my head but it doesn't surprise me that it isn't working right because `tsplot` is older and poorly written. It predates pandas categoricals and might not know exactly how to work with them.

**Comment by mwaskom** [comment]
Closed with tsplot deprecation.
