### ISSUE TITLE
Violins out of alignment

### ISSUE THREAD

**Issue by naught101** [mwaskom/seaborn#1007]
Example:

```{python}
metric_df.head()
#           metric variable     value   name      site  rank
# 1379     overlap      NEE  0.303737  S_lin  Howlandm   3.0
# 275    extreme_5       Qh  1.000000  S_lin     Bugac   4.0
# 1471         nme       Qh  0.930607  S_lin  Hyytiala   3.0
# 276   extreme_95       Qh  0.934291  S_lin     Bugac   3.0
# 278     kurtosis       Qh  1.000000  S_lin     Bugac   4.0

sns.violinplot(y="value", x="name", col='variable', hue="name", data=metric_df, orient='v')
```
![figure_1](https://cloud.githubusercontent.com/assets/167164/18373633/24a714b0-7689-11e6-83ea-0b22e1b48cb9.png)

the outer violins are especially badly aligned, and that makes it impossible to overlay other plots and have them line up, for example:

```{python}
sns.stripplot(y="value", x="name", hue="name", data=metric_df, orient='v', jitter=True, ax=gca())
```

![figure_1-1](https://cloud.githubusercontent.com/assets/167164/18373650/6d0bc6d8-7689-11e6-88fe-aa9bdd4bf31a.png)

This is with python 3.4.5, seaborn 0.7.1.

**Comment by mwaskom** [comment]
Yes, don't use hue, as it offsets them.

**Comment by naught101** [comment]
That seems.. counter intuitive. Is it not a bug? It's not mentioned in the docs, that I can see..

**Comment by mmagnuski** [comment]
I don't find it counter intuitive - by default your violins get colored according to split by x and the palette you use. If you want to subset the violins according to some other variable you use hue (and then color differentiates subcategories within each x category). Under this model setting x and hue to the same variable does not make sense.

**Comment by mwaskom** [comment]
It is reasonable to be a little surprised that `hue` also moves things along the categorical axis but that is the way that all of the relevant functions currently work (`boxplot`, `violinplot`, and `barplot`). It is documented in the sense that it is the behavior you can see in every example. Were this not to happen, different hue levels would be plotted on top of each other. This make sense for the scatterplot functions but seems at best rarely useful for the three functions mentioned above so I did not bother with the complexity of making it optional.

FWIW a violinplot does not look like a particularly good choice for the distribution that your data is taking in that example, so you might want to explore other options.

**Comment by naught101** [comment]
Ah, I see. I'm splitting the data twice, by using `x` *and* `hue` with the same variable. Yeah, fair enough.

I think it would probably be a good idea to note the offset in the docs for the `hue` argument to each of those functions - it's not immediately obvious from the examples. Also, it seems that `hue` requires an `x` (or `y`, with `orient='h'`) to actually work:

![figure_1](https://cloud.githubusercontent.com/assets/167164/18459209/00243daa-79ab-11e6-91cc-d615474419f8.png)

This should perhaps also be noted in the docs.

Yeah, I know these plots aren't suitable for my data - I was exploring, hoping my distributions would look a bit more normal than that...
