### ISSUE TITLE
Swarmplot points overlap with higher DPI values

### ISSUE THREAD

**Issue by luispedro** [mwaskom/seaborn#1008]
If I use `swarmplot` with default DPI value, then it works as expected:

```
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np

data = np.random.rand(100)
data = np.vstack([np.zeros_like(data), data])
data[0,50:] = 1

fig, ax = plt.subplots()
sns.swarmplot(x=data[0], y=data[1], size=20, ax=ax)
fig.savefig("swarm.png")
```

![swarm](https://cloud.githubusercontent.com/assets/79334/18416691/b3fe9ba4-781b-11e6-90d7-793d8e0199a7.png)

However, larger DPI values lead to overlapping dots:

```
fig, ax = plt.subplots(dpi=150)
sns.swarmplot(x=data[0], y=data[1], size=20, ax=ax)
fig.savefig("swarm150.png")
```

![swarm150](https://cloud.githubusercontent.com/assets/79334/18416703/df002fc0-781b-11e6-954f-ea93ba798680.png)

The higher the DPI value, the worse it gets:

```
fig, ax = plt.subplots(dpi=300)
sns.swarmplot(x=data[0], y=data[1], size=20, ax=ax)
fig.savefig("swarm300.png")
```

![swarm300](https://cloud.githubusercontent.com/assets/79334/18416705/ec3d10cc-781b-11e6-86a1-113f3d00bc75.png)

Thank you!

**Comment by mmagnuski** [comment]
Doing `plt.savefig('swarmplot.png', dpi=350)` looks good on my machine (but initiating subplots with high dpi looks just as your examples). Does it work for you?

**Comment by luispedro** [comment]
Yes, that works. Thanks.

**Comment by mwaskom** [comment]
`swarmplot` uses some trickery to work properly so it is not too surprising that it is brittle. But I don't think anything in my code is assuming a particular DPI. The relevant function is here: https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L1285 It would be interesting to test whether `ax.transData` is handling a different DPI properly outside of the context of seaborn.

**Comment by luispedro** [comment]
After looking at that code, here is my guess: `beeswarm` does its work in display coordinates (i.e., pixel coordinates). The size of the points is specified in points, though, and the number of pixels per point is changed by changing the figure DPI. The bug is then that the size of the points need to be scaled from points to pixels.

As I said, this is a guess, I'm not familiar enough with seaborn/matplotlib to be sure.

**Comment by mwaskom** [comment]
That's a good point, I don't think it's accounting for DPI when it chooses the offset based on the point size. I suppose the fact that it works with the default DPI is an accident. That's a good start for fixing it, but as there's a good workaround (setting the DPI when saving the figure) it's going to be a low priority.
