### ISSUE TITLE
The solution of display chinese in seaborn plot

### ISSUE THREAD

**Issue by githubzhanglei** [mwaskom/seaborn#1009]
As #829 and #592 said, the reason is  "seaborn override default fonts specified in matplotlibrc configs".
Thus, you can set the default seaborn font style after import the seaborn as follows:

`import seaborn as sns`
`sns.set_style("darkgrid",{"font.sans-serif":['simhei', 'Arial']})
`

The simhei is the chinese font,  and make sure the simhei.ttf already in your "Lib\site-packages\matplotlib\mpl-data\fonts\ttf" folder. 

This method just change the seaborn font setting temporarily, however I do not know how to do that permanently.

**Comment by Elgins** [comment]
Hi, I tried this code, my enviroment is Anaconda3 and Python3.5, but it seems not work, 中文依旧显示乱码啊啊啊啊啊啊， 咋搞啊 ，我日， 我吧代码加进去了， 我也确保了那个文件夹有黑体字体文件， 我的matplolib是正常的， 可是依旧显示乱码， 咋搞啊， 求大神指点一二

**Comment by githubzhanglei** [comment]
Hi Elgins, I don't know anything about the Python3, :-)

**Comment by cqcn1991** [comment]
Thanks @githubzhanglei , it works fine under python 3, here is my result
![qq](https://cloud.githubusercontent.com/assets/2425141/20952035/71c5a560-bc64-11e6-8b32-5f84763be34c.png)

**Comment by viblo** [comment]
@cqcn1991 When I try that I get this warning
```
/home/blomqvist/miniconda3/envs/notebook3/lib/python3.5/site-packages/matplotlib/font_manager.py:1288: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
```

**Comment by cqcn1991** [comment]
@viblo Seems like you are not under windows? Maybe you don't have 'SimHei' at all. Try changing it to a font that's available in your computer.

**Comment by viblo** [comment]
@cqcn1991 Right, Im on Ubuntu. I now got it to work, by using "Droid Sans Fallback" as my font. Thanks for the help!

I still think it would be good if seaborn could default to a good font by default so each user doesnt have to do this by themselves.

**Comment by Starrry22** [comment]
> 
> 
> Hi, I tried this code, my enviroment is Anaconda3 and Python3.5, but it seems not work, 中文依旧显示乱码啊啊啊啊啊啊， 咋搞啊 ，我日， 我吧代码加进去了， 我也确保了那个文件夹有黑体字体文件， 我的matplolib是正常的， 可是依旧显示乱码， 咋搞啊， 求大神指点一二

请问这个问题解决了吗？我也不行。。。

**Comment by Qiuzhuang** [comment]
If still seeing error after putting SimHei.ttf into site-packages/matplotlib/mpl-data/fonts/ttf, you might try to clear font cache. For centos, just go to ~/.cache/matplotlib and remove cached font list file.

**Comment by zhuchangzhan** [comment]
download the font from https://fontsforyou.com/en/fonts/29390-simsun.font
To get it working on mac, click to install it, 
but don't install it for "User", you need to install it for "Computer"

**Comment by YaooXu** [comment]
> If still seeing error after putting SimHei.ttf into site-packages/matplotlib/mpl-data/fonts/ttf, you might try to clear font cache. For centos, just go to ~/.cache/matplotlib and remove cached font list file.

It works, thanks!

**Comment by XAKK** [comment]
This approach works on Ubuntu:
1. install a font that support Chinese
2. add following codes in your Python script:
`import seaborn as sns
sns.set(font="MiSans,MiSans Normal")`
[reference](https://www.cnblogs.com/lambyte/p/16264548.html)
