### ISSUE TITLE
regplot and xscale('log') don't get along without xlim

### ISSUE THREAD

**Issue by yoavram** [mwaskom/seaborn#1012]
Hi, 
When running:
```py
sns.regplot('r', 'in_final_rate', data, ci=None, x_ci=None, logistic=True)
plt.xscale('log')
```
I get a malformed x-axis.
However, if I add `xlim()`:
```py
sns.regplot('r', 'in_final_rate', data, ci=None, x_ci=None, logistic=True)
plt.xlim(1e-4, 1e-1)
plt.xscale('log')
```
Then it looks fine.

See notebook in [this gist](https://gist.github.com/yoavram/a74d013f8819cdcaac072b95ef9ce1d8), which also includes a data file.

**Comment by mwaskom** [comment]
I don't have time to download the data (but thanks for sharing it!) but my quick guess is that the regression line is including 0 which is messing up the log axis. Try drawing with `truncate=True` so the model won't extrapolate beyond the data limits?

**Comment by mwaskom** [comment]
(But thanks for making a fully reproducible example — I'll take a closer look later if that doesn't work).

**Comment by yoavram** [comment]
Yes, the data does contain zeros for the x-axis variable.
Thanks.

**Comment by mwaskom** [comment]
Yeah, I'm not sure if there's a better way to handle that in matplotlib than just re-setting the axis limits after scaling, but log(0) does seem to screw it up. Can I close?

**Comment by maahl** [comment]
Hi,

I had the same issue today. After some time, i managed to get the following minimal working example:
```python
#! /usr/bin/env python3

import matplotlib.pyplot as plt
import pandas as pd
import seaborn


data = pd.DataFrame({
        'a': [10, 1000],
        'b': [10, 100]
})
plot = seaborn.regplot('a', 'b', data=data, truncate=True)
plot.set(xscale='log', yscale='log')                               
plt.show()
```
Which gives me the following output:
![min_test_case](https://user-images.githubusercontent.com/2880719/38891783-a60a3054-4285-11e8-95c5-3e4ea3277d00.png)

The `truncate` parameter does not change the output for me.
Manually setting the plot bounds (`xlim`) is a workaround.

**Comment by mwaskom** [comment]
This is not the same as the original issue (which was trying to take the log of a non-positive number) but rather has to do with a change in matplotlib that needs to be addressed. Two additional (and easier) workarounds are:

1. Set the axis scale before plotting:

```python
f, ax = plt.subplots()
ax.set(xscale='log', yscale='log')
ans.regplot('a', 'b', data=data, truncate=True, ax=ax)
```

2. Turn axis autoscaling back on after plotting:

```python
ax = sns.regplot('a', 'b', data=data, truncate=True)
ax.set_xlim(auto=True)
ax.set(xscale='log', yscale='log')
```

**Comment by maahl** [comment]
Ah, sorry for the confusion!
Thanks for the tips :)

**Comment by zherebetskyy** [comment]
The log-plot usually looks better if 
- the borders are set starting from some value (say 1) 
- the values of arguments have to be positive 

Something like this should work
``` python
import matplotlib.pyplot as plt 
import seaborn as sns
x_column = 'col1' 
y_column = 'col2'
fg = sns.FacetGrid(data=pdf_clean[(pdf_clean['col1']>1) & (pdf_clean['col2']>1)], hue='col3', size=5, aspect=1.41, palette='muted')
fg.map(plt.scatter, x_column, y_column, alpha=.8).add_legend()`
axes = fg.axes
axes[0,0].set_xlim(1,)
axes[0,0].set_ylim(1,)
fg.set(xscale="log", yscale="log")
