### ISSUE TITLE
feature request: adding labels to categorical plots

### ISSUE THREAD

**Issue by kennmyers** [mwaskom/seaborn#1013]
Something I've encountered a few times was trying to add categorical labels to a pointplot without using hue. At first I couldn't understand why I could pass label it as a parameter but it would throw a warning if I tried to display multiple pointplots on the same figure and then set the location of the labels. 

```
plt.title("")
plt.xlabel("")
plt.ylabel("")
sns.pointplot(x = df["x"], y=df["y1"], label="1")
sns.pointplot(x = df["x"], y=df["y2"],label="2")
sns.pointplot(x = df["x"], y=df["y3"],label="3")
plt.legend(loc="best")
```

<img src="http://i.imgur.com/3qNU6eQ.png">

with error:

```
.conda/envs/py35/lib/python3.5/site-packages/matplotlib/axes/_axes.py:519: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "
```

I can understand why this wouldn't be a feature since it can cause problems with other overlapping plots such as violin plots. However, it feels really limiting to not be able to overlap plots in this manner when it works for regplots:

```
plt.title("")
plt.xlabel("")
plt.ylabel("")
sns.regplot(x = df["x"], y=df["y1"], label="1")
sns.regplot(x = df["x"], y=df["y2"],label="2")
sns.regplot(x = df["x"], y=df["y3"],label="3")
plt.legend(loc="best")
```

<img src="http://i.imgur.com/6E4CD2b.png">

I think it should be an optional feature to allow people to overlap categorical plots in the way regplots allow, but to try and force them to the currently used format for other plots that can't be overlapped (like the violin plots I mentioned).

**Comment by mwaskom** [comment]
Is there a compelling reason not to put your data into tidy format and use `hue`?

**Comment by kennmyers** [comment]
Laziness, not wanting to write extra lines of code to rework a dataframe for one new plot, not wanting to double memory use by creating a new dataframe just for one plot.

If it would be easier can we just have the option to connect the dots on the point plot since I can already remove the regression lines?

**Comment by mwaskom** [comment]
It sounds like seaborn isn't really going to be neccessary for you can you can get everything you want with `plt.plot`?

**Comment by kennmyers** [comment]
Sorry for not responding, yeah I've pretty much resorted to plt.plot for most things
