### ISSUE TITLE
Violin plot not plotting on numeric axis

### ISSUE THREAD

**Issue by philastrophist** [mwaskom/seaborn#1014]
When using violinplot on a pre-defined axis with artists, violinplot removes previous data
```
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

fig, ax = plt.subplots()
wavelengths = [1,2,3,4,5]
observations = np.random.normal(size=(100, len(wavelengths)))
d = pd.DataFrame(columns=wavelengths, data=observations)
print d
sns.violinplot(d, ax=ax, inner='quartiles')
ax.errorbar([1], [10], 1, fmt='bo', color='k', markersize=10)
print ax.get_xlim()
plt.show()
```
The plotted errorbar is shifted to 2 instead of 1 since apparently `violinplot` renames the axis labels. This is not helpful. The `violinplot` should position each violin and not rename the axis labels when column names are numerical.

**Comment by mwaskom** [comment]
Sorry but that's just the way it works.

**Comment by philastrophist** [comment]
Erm. But that's ridiculous. The matplotlib version has the `positions` argument. Surely it makes sense to use that.

**Comment by mwaskom** [comment]
I'm not sure why you think that is a constructive approach to discussing this issue, but you are mistaken.
