### ISSUE TITLE
Seaborn creator, why did u change the font of matplotlib以至于无法显示中文！！

### ISSUE THREAD

**Issue by Elgins** [mwaskom/seaborn#1015]
Sun, I try this code to solve my problem that Chinese cannot display normally on the graph
sns.set_style("darkgrid", {"font.sans-serif": ['Vera']})
Vera is my rename Chinese font, But I didnot work!!!!!!!!!!!!!
Why!!!!!!My matplotlib is worked very fine.!!!!
Can u give me a solution or tell me why did you change the default setting of matplolib?!!!!

**Comment by mmagnuski** [comment]
Even if this is part of US conspiracy against China, I think you could have used a little less exclamation marks. :)
