### ISSUE TITLE
Feature Request: Mosaic Plots

### ISSUE THREAD

**Issue by Dawny33** [mwaskom/seaborn#1016]
Please introduce Mosaic Plots, which is a good way to plot categorical variables against each other.

**Comment by mmagnuski** [comment]
possibly related: #762

**Comment by mwaskom** [comment]
No thanks.

**Comment by Dawny33** [comment]
Mosaic Plots are different (definitely not like the ones mentioned in that issue). They are very handy while plotting categorical variables against each other.

Example: [Statsmodels implementation](http://statsmodels.sourceforge.net/devel/generated/statsmodels.graphics.mosaicplot.mosaic.html)

**Comment by DSLituiev** [comment]
I would also appreciate to have it here. Can make a pull req if there is interest.
