### ISSUE TITLE
tsplot drops data if DataFrame index is not range(len(df))

### ISSUE THREAD

**Issue by dstuck** [mwaskom/seaborn#1019]
If no condition is passed, condition is set to a Series of ones the same length as data, but the index is not necessarily the same.

This code doesn't fail:
```python
gammas = sns.load_dataset("gammas")
ax = sns.tsplot(time="timepoint", value="BOLD signal",
                unit="subject", data=gammas.query('ROI=="AG"'))
```
but secretly drops data with index > len(gammas.query('ROI=="AG"'))
Compare to the correct output from:
```python
gammas = sns.load_dataset("gammas")
ax = sns.tsplot(time="timepoint", value="BOLD signal",
                unit="subject", data=gammas.query('ROI=="AG"').reset_index())
```

Should be a quick fix from:
`condition = pd.Series(np.ones(len(data)))`
to:
`condition = pd.Series(np.ones(len(data)), index=data.index)`

**Comment by mwaskom** [comment]
Just to clarify, in the title of the issue do you mean if the index is *not* `range(len(df))`?

**Comment by dstuck** [comment]
Exactly! Sorry about that!

**Comment by mwaskom** [comment]
Got it, thanks for catching!
