### ISSUE TITLE
Equivalent bw parametr for violin and kde plots

### ISSUE THREAD

**Issue by medphisiker** [mwaskom/seaborn#1022]
Hello,
In kdeplot() we have parametr bw
In this case bw is scalar factor scalar for kernel density estimation.
In violinplot() we also have parametr bw
In this case bw is scalar factor scalar for kernel density estimation. But the actual kernel size will be determined by multiplying the scale factor by the standard deviation of the data !

And when I plot kde and violin plot from my data 

# Set up the matplotlib figure
fig = plt.figure()
ax1 = fig.add_subplot(2, 1, 1)
ax2 = fig.add_subplot(2, 1, 2)

# Draw a kdeplot and violinplot 
sns.kdeplot(data, bw = 0.1, ax=ax1)
sns.violinplot(data, bw = 0.1, ax=ax2)

I get diffrent results with same bw parametr !

![figure_1](https://cloud.githubusercontent.com/assets/4876436/18827987/103ade60-8419-11e6-993b-f703fd210e4c.png)

But if I use
sns.kdeplot(data, bw = 0.1 * statistics.stdev(data), ax=ax1)
instead
sns.kdeplot(data, bw = 0.1, ax=ax1)
I get the same results as mention in the violin_plot docs. 
![figure_1_1](https://cloud.githubusercontent.com/assets/4876436/18828000/24069f74-8419-11e6-80e5-0f6a31116576.png)
But I want to have opportunity to get violin plot with scale factor = bw, not scale factor = bw * Standart_Deviation_of_dataset.
It will be very conviniet if there is were additition parametr.
For example bw_multiply_by_st_dev, if True scale factor = bw*Standart_Deviation_of_dataset,
else scale factor = bw.

So 
sns.kdeplot( ...,bw = 0.1,....)
sns.violinplot(..., bw =0.1, bw_multiply_by_st_dev = False , ...)
will get the same result.

**Comment by medphisiker** [comment]
realised by myself.

**Comment by mmagnuski** [comment]
@medphisiker what do you mean, I don't see your PR? I think it would be nice to have `bw` work the same in violinplot and kdeplot. Not sure if @mwaskom agrees, but if you've got a working implementation - why not submit a PR?

**Comment by medphisiker** [comment]
Hello, excuse me what your mean by "PR" ? =)
Excuse me I'am new to github. 
I made new parametr True_bw for violinplot and it works for me for now. Also I made 
sns.stripplot  with two hue parametr =)
#For example:
sns.stripplot (y = 'point', x = x, size= 5, hue= 'Name', hue2='VKF_A', data=d, orient='h', split=1, palette=sns.color_palette(flatui), width = 0.5)
#Gives this plot
we have category1 by hue parametr and colorize them by hue2 parametr
hue present by marker type and hue2 by color =)
![text4561-6](https://cloud.githubusercontent.com/assets/4876436/19137626/a9173650-8bb8-11e6-9ebc-d5149c395882.png)
#for this data
![image](https://cloud.githubusercontent.com/assets/4876436/19137754/8659521e-8bb9-11e6-8ffe-38e0828a3a6c.png)

**Comment by medphisiker** [comment]
It works well and stabe for me and for now, but my code some hacky for all seaborn's API. I think that I write normal code compatible with now days version of seaborn and made Pull request =) But I'am new to github and it can take time. But I will work for this.

**Comment by medphisiker** [comment]
You can discus necessity of this in my Issue "New Fetures for Seaborn: equivalent bw parametr for violin and kde plots, width of sripplot and swarmplot as parametr and two hues for stripplot"
