### ISSUE TITLE
An additional parameter to control self.width parametr for violinplot, stripplot and swarm plot

### ISSUE THREAD

**Issue by medphisiker** [mwaskom/seaborn#1023]
Hello,
Possible it will be convinient to have an additional parameter to control self.width parametr for violinplot, stripplot and swarm plot
For example
sns.stripplot(data=d, orient='h', split=1, width = 0.2)
will be plot with width = 0.2 instead self.width = 0.8 as default
![1](https://cloud.githubusercontent.com/assets/4876436/18860446/d988021e-84c0-11e6-8cc0-81682f4644c4.png)

I add this parametr to this function for myself but by directly transfer new width parametr from stripplot(width) to _StripPlotter(width)  and set self.width = width.
It seems to me that there must be a more elegant method using _CategoricalPlotter class. =)

**Comment by mmagnuski** [comment]
This would be nice to have too...

**Comment by medphisiker** [comment]
Hello,
please see my 'Equivalent bw parametr for violin and kde plots' issue I give all my cooment in that.

**Comment by RoelantStegmann** [comment]
Would be great!
