### ISSUE TITLE
Facet grid hue order

### ISSUE THREAD

**Issue by CalvinLeather** [mwaskom/seaborn#1024]
Let's say I'm using FacetGrid to plot data. I want to color-code a condition variable, so I pass the variable to the FacetGrid's map function as hue. Unfortunately, matplotlib redoes the color-to-variable mapping for each facet, resulting in the hues being mixed up and the `add_legend' legend not being accurate for some facets.

Sample code to recreate the issue is below. See how in the attached image, both points at (5,5) are turquoise, but are in different treatments.
![image](https://cloud.githubusercontent.com/assets/6288302/18892266/c6727b08-84bd-11e6-95ac-9db2e5f3f32c.png)
```
import pandas as pd
import numpy as np
import seaborn as sns

data = np.transpose([[1, 1, 1, 1, 2, 2, 2, 2], ['a', 'b', 'b', 'b', 'b', 'a', 'b', 'b'], [5,6,7,8,5,6,7,8], [5,6,7,8,5,6,7,8]])
df = pd.DataFrame(data)
df.columns = ['subject', 'treatment', 'measurement1', 'measurement2']

g = sns.FacetGrid(df, col='subject', col_wrap = 4, palette="Set2", margin_titles=True);
g= g.map(sns.stripplot, "measurement1", "measurement2","treatment", palette="Set2").add_legend();
```

I suppose one could get around this by sorting the dataframe along the condition variable, but you still run into issues this way, for example, in the example given, if there was a third treatment (perhaps 'aa') which only a subset of subjects were in.

I wasn't able to find mention of this in a past issue, is it something you all are aware of?

**Comment by mwaskom** [comment]
If you want to use `FacetGrid` with a categorical plotting function, you should use `factorplot`, which sets the order consistently across facets for exactly this reason. Otherwise you can use the `order` keyword argument.
