### ISSUE TITLE
Heatmap: Specifying number of ticks or tick locations in cmap

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [mwaskom/seaborn#1028]
First off, thanks so much @mwaskom  for this great library. We use it constantly at my work place!

Q. I could not find an option to change the ticks locations (or the number of ticks) **for the colormap** in a `heatmap`. That is, I'm not talking about the x or y axis, but the ticks in the cmap itself.

Any suggestions on how to do it?

E.g. for:
``` python
# Draw the heatmap with the mask and correct aspect ratio
g = sns.heatmap(corr, mask=mask, cmap=cmap, vmax=1,
                square=True, linewidths=.5, cbar_kws={"shrink": .9}, ax=ax)
```

**Comment by mwaskom** [comment]
I'm not sure what you mean by ticks "in the colormap". Do you mean on the color *bar*?

**Comment by amelio-vazquez-reina** [comment]
Sorry, that's right, Color bar!

**Comment by mwaskom** [comment]
You can use the `ticks` colorbar keyword argument (requires version 0.7.1+):

```python
x = np.random.rand(10, 10)
sns.heatmap(x, cbar_kws=dict(ticks=[.2, .5, .6]))
```
![image](https://cloud.githubusercontent.com/assets/315810/18966898/1c36f43a-8651-11e6-950c-53b35d73e7cf.png)

**Comment by allanj** [comment]
@mwaskom what's the `cmap` in your reply?

**Comment by brianpenghe** [comment]
@mwaskom but what if I want to label certain ticks on the x and y axes??

**Comment by andt88** [comment]
plot = sns.heatmap(plot_df, cmap='coolwarm', norm=log_norm, cbar_kws={'label': 'label', 'ticks': [0.1, 1, 2, 5]})

**Comment by andt88** [comment]
> @mwaskom but what if I want to label certain ticks on the x and y axes??

For this you can use:
plot = sns.heatmap(data)
plot.set_xticklabels([a,b,c])
plot.set_yticklabels([1,2,3])

**Comment by brianpenghe** [comment]
> > @mwaskom but what if I want to label certain ticks on the x and y axes??
> 
> For this you can use:
> plot = sns.heatmap(data)
> plot.set_xticklabels([a,b,c])
> plot.set_yticklabels([1,2,3])

What if it's a clustermap?
I've got this error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-231-0d37fde8dd95> in <module>
----> 1 test2.set_yticklabels([1,2,3])

AttributeError: 'ClusterGrid' object has no attribute 'set_yticklabels'
```

**Comment by brianpenghe** [comment]
> > @mwaskom but what if I want to label certain ticks on the x and y axes??
> 
> For this you can use:
> plot = sns.heatmap(data)
> plot.set_xticklabels([a,b,c])
> plot.set_yticklabels([1,2,3])

Thanks a lot!

**Comment by andt88** [comment]
When I pass the norm argument, it seems that the ticks keyword is ignored.
plot = sns.heatmap(plot_df, cmap='coolwarm', norm=LogNorm(vmin=0, vmax=10), cbar_kws={'label': 'label', 'ticks': [0.1, 1, 2, 5]})

I am using seaborn 0.10.0

**Comment by nightm4re94** [comment]
I have the same issue as @andt88 : With a logarithmic norm, the "ticks" keyword gets ignored entirely.
This is the code that produces my heatmap:
``` python
log_norm = LogNorm(vmin=1, vmax=1e7)
hm = sb.heatmap(data=matrix_df, xticklabels=10, yticklabels=10, cmap=heatmap_colors, norm=log_norm, cbar=True, cbar_kws={"label": lbl_cycle_count, "shrink": 1}, vmin=1, vmax=1e7)
hm.set_yticklabels(hm.get_yticklabels(), rotation=0)
hm.set_xticklabels(hm.get_xticklabels(), rotation=90)
```
