### ISSUE TITLE
countplot does not have option for the ordering of the x values

### ISSUE THREAD

**Issue by napsternxg** [mwaskom/seaborn#1029]
The count plot function does not have any way to order the values.  The default ordering of x is incorrect.

I used the following code:
```
ax = sns.countplot(x=("PhdDecade", "first"),
                 data=df_faculty, color="grey")
for p in ax.patches:
    height = p.get_height()
    ax.text(p.get_x()+0.25, height+ 3, 'n=%.0f'%(height))
```

![image](https://cloud.githubusercontent.com/assets/112678/18998994/be4534da-8700-11e6-8161-d39a804831fc.png)

Seaborn version: 0.7.0

**Comment by mwaskom** [comment]
Perhaps try the `order` parameter ?

**Comment by mwaskom** [comment]
Alternately, the default is to plot the values in the order they appear in the DataFrame. While you do not say what is "incorrect" about the plot you've made, I assume you mean you want the decades to be ordered chronologically, which you could accomplish by sorting the dataframe on the decade variable before plotting.

**Comment by tommylees112** [comment]
I also want to order the data by descending order and don't want to change the underlying data. Is this not possible?

**Comment by adicostil** [comment]
try this, should be desc by counts
```python
ax = sns.countplot(x=("PhdDecade", "first"),
                 data=df_faculty, color="grey", order=df_faculty['PhdDecade'].value_counts().index)
```
if you need asc 
```
order=reversed(df_faculty['PhdDecade'].value_counts().index)
```

**Comment by fahmoreira** [comment]
> try this, should be desc by counts
> 
> ```python
> ax = sns.countplot(x=("PhdDecade", "first"),
>                  data=df_faculty, color="grey", order=df_faculty['PhdDecade'].value_counts().index)
> ```
> 
> if you need asc
> 
> ```
> order=reversed(df_faculty['PhdDecade'].value_counts().index)
> ```

Thank you!

**Comment by JRSami** [comment]
Also, might try:

df_faculty['PhdDecade'] = pd.Categorical(df_faculty['PhdDecade'], categories = ['1950's','1960's','1970's','1980's','1990's','2000's','2010's'], ordered = True)
