### ISSUE TITLE
Categorical Heatmap

### ISSUE THREAD

**Issue by inodb** [mwaskom/seaborn#1031]
Make it possible to pass a categorical heatmap to `sns.heatmap`.

I was able to plot a categorical heatmap with a little work, see my StackOverflow question: http://stackoverflow.com/questions/36227475/heatmap-like-plot-but-for-categorical-variables-in-seaborn.

It seems a little complex though for what I think is a pretty common use case of `sns.heatmap`. If you could give some pointers, I'm happy to take a stab at this.

Also, thanks so much for your work on seaborn, it's awesome.

**Comment by mwaskom** [comment]
There was some work on this in #629 but it stalled out. I am ambivalent about the idea in general.

**Comment by mpschr** [comment]
Hi, I want to plot a categorical heatmap as well. Categorical heatmaps are quite common, for example when plotting occurrences of many events of different qualities for many samples and features (e.g. multi-genomics approaches: SNPs/Fusions/Copy Numbers etc. One would like to have the different events (categories) to have different colors.

An example:
![image](https://user-images.githubusercontent.com/1090105/28466248-1f4f0f22-6e2c-11e7-8e21-c783a50dfcd9.png)
Ref.: Nature 507, 315–322 (20 March 2014) doi:10.1038/nature12965

**Comment by fzesch** [comment]
I would really love to have this feature and to me the reasons why the concerning PR is rejected is really not clear. Somebody already did the work (PR 629), people could use this feature (me too!), why block it?

**Comment by mwaskom** [comment]
Because the PR was incomplete and it's my prerogative what I merge into the software that I provide support for.

**Comment by mpschr** [comment]
Is there an official TO-do or nice-to have list? I'd definitely put this there as this feature would be a great project for a summer-of-code or another student project.

**Comment by mwaskom** [comment]
This feels like something that could be easily built on top of seaborn/matplotlib as a separate focused package, so if someone wants to work on it as a project they maintain, they certainly should.

**Comment by mpschr** [comment]
Seems like someone took this to heart: https://github.com/schlegelp/catheat
In any case, it would also make perfect sense to have it within the seaborn library, as there is even a specific doc chapter on categorical data: However, what if one of the main variables you are interested in is categorical?

I know I know - I could also do it... when I find the time ;)
