### ISSUE TITLE
Turn off share axis in PairGrid

### ISSUE THREAD

**Issue by jfear** [mwaskom/seaborn#1032]
I was wondering if there is an easy way to turn off sharex and sharey after making a PairGrid object? 

I would like to plot a Bland-Altman style plot (lower triangle) along with just pairwise scatter plots (upper triangle). The Bland-Altman plot is doing some transformations so the xlim and ylim will be different. 

Thanks for any advice.

**Comment by mwaskom** [comment]
There's no easy way, sorry, shared axes are central to the idea of the pair grid.

**Comment by jfear** [comment]
Thanks for the quick response.

**Comment by mwaskom** [comment]
With that said, `PairGrid` should probably take a subplot_kws dictionary anyway, which would provide a way to do this.

**Comment by tsk0806** [comment]
I found an awkward way to do.

```
g = sns.PairGrid(df)
numdata = 5
for i in range(numdata):
    for j in range(numdata):
        for k in range(numdata):
            for l in range(numdata):
               g.axes[i, j].get_shared_x_axes().remove(g.axes[k, l])
               g.axes[i, j].get_shared_y_axes().remove(g.axes[k, l])
```
