### ISSUE TITLE
Legend placement differs between notebook and script based plots

### ISSUE THREAD

**Issue by tweeter0830** [mwaskom/seaborn#1033]
The following commands generate different plots when I'm in a notebook vs when I plot from a script.
` 
  import seaborn as sns
  sns.set(context='poster', style="ticks", color_codes=True)
  iris = sns.load_dataset("iris")
  g = sns.pairplot(iris, hue="species")

  sns.plt.show() <- only needed from the script
`

In a notebook, it generates a plot as seen here:
https://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.pairplot.html
![image](https://cloud.githubusercontent.com/assets/1314240/19085719/31743dee-8a20-11e6-9694-5c203eeabc15.png)

From a script, it generates the following:
![figure_1-4](https://cloud.githubusercontent.com/assets/1314240/19085660/f1c48bea-8a1f-11e6-9d46-04f7d9664379.png)

Notice that the legend is placed annoyingly in the middle of the plot.
Is there a way around this behavior?

I'm on Ubuntu running in a virtualenv with the latest seaborn and matplotlib from pip.
This happens on both the TkAgg backend.

**Comment by mwaskom** [comment]
There is, as far as I am aware, a bug in some matplotlib backends that prevents calling tight_layout and the necessary commands to put the legend outside of the main axes. I tried looking into it at one point but was unable to come up with a good solution for fixing it. I do encounter this issue in my usual work, so presumably you should be able to find a backend that works for you in  a script.
