### ISSUE TITLE
Install Requirements

### ISSUE THREAD

**Issue by MinchinWeb** [mwaskom/seaborn#1035]
I'm install `seaborn` off of PyPI and I found it did not automatically install `scipy`, which is a requirement. I'm running Python 3.5.2 on Windows 10x64 in a vituralenv.

Looking through the [setup.py](https://github.com/mwaskom/seaborn/blob/master/setup.py#L39-L62), I notice that `scipy` (and others) are conditionally added to the install requirement. I think what is happening is this check is performed on your machine when you package `seaborn`, rather than on my computer when I install it. Is there any reason why not to always require `scipy` et al?

**Comment by mwaskom** [comment]
See https://github.com/mwaskom/seaborn/issues/169
