### ISSUE TITLE
matplotlib plots in notebook look different after using Seaborn

### ISSUE THREAD

**Issue by dgua** [mwaskom/seaborn#1037]
I have been fighting with this issue for months and I have not been able to find a solution. I apologize if this isn't the right place. I have searched for a few hours on stackoverflow etc. for some solutions, but was unable to find one. 

The problem: After making some Seaborn plots, something changes and my matplotlib plots look different. Specifically, they look larger. 

I am using Jupyter notebook 4.2.1:
Python 2.7.12 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:43:17) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)]

My code for importing matplotlib:
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
%config InlineBackend.figure_format='retina' # or 'svg'

At a certain point in my notebook I import Seaborn with this code:
import seaborn.apionly as sns; sns.set()
sns.set_context("notebook",font_scale=1.0)

after creating a few Seaborn plots, I try to restore the original settings with:
sns.reset_orig()
mpl = reload(mpl)

The second line reloads my matplotlib rc settings, which however does not impact the issue at hand (that is, the result is the same with or without that line). In other words, matplotlib rc settings seem to be the same as before. 

After this, all matplotlib plots look different. Simple plots just look larger. More complicated ones with subplots show text annotation in a slightly wrong position.

The only solution that works is to restart the Kernel from the notebook Kernel menu. 

I would like to see this *very annoying* issue fixed. Please let me know how I can help and thank you in advance.

**Comment by mwaskom** [comment]
Could you perhaps generate an actual script that exactly triggers the problem, so I don't have to sit around making plots wondering if I am seeing the same behavior as you?

It would also be helpful to know important details e.g. what version of seaborn and matplotlib you are using.

**Comment by dgua** [comment]
Michael,
attached please find a minimal Jupyter notebook that shows the problem. 
(I was not able to find the Seaborn version...)
[Seaborn bug.ipynb.zip](https://github.com/mwaskom/seaborn/files/517446/Seaborn.bug.ipynb.zip)

**Comment by mwaskom** [comment]
`seaborn.__version__` ...

**Comment by mwaskom** [comment]
Your problem is actually in the call to `reload(mpl)`. It has nothing to do with seaborn. The Jupyter notebook sets the `savefig.dpi` parameter to 72, rather than the matplotlib default of 100. If you inspect the value of this parameter at various points in your code, you will find that it is set back to 72 after you call `sns.reset_orig`, which sets the rcParams back to what their values at the time seaborn was imported, but then it changes to 100 when you reload `mpl`.

FWIW, before being pretty rude and demanding in your issue report, it would be good in the future to double check that you fully understand what you are doing and that you have provided all of the relevant information in the original issue. That avoids wasting people's time.

**Comment by dgua** [comment]
1. If you had read my post carefully, you would have seen that reload(mpl) has no effect on this problem. Please see attached updated notebook where that line is disabled

2. You are correct that savefig.dpi changes at various points in the notebook. However, resetting it to 72 as it was at the beginning, DOES NOT produce the same plot as before using Seaborn. There is something else at play

3. seaborn.__version__ does not work, at least not in the notebook. As you can see, it produces an error (I apologize if I am missing something obvious here)

4. 
> FWIW, before being pretty rude and demanding in your issue report,...

I am sorry if I offended you. I re-read my OP and I don't find it rude. I pointed out a problem, said that I would like to see it fixed, and I offered my help with reproducing/debugging the issue. I also provided you with an example showing the issue. 

If you do a web search you will find that several other people report the same issue, so I am pretty sure it's not just me. FWIW, one of my colleagues refuses to use Seaborn in his scripts precisely because of this problem (he does not use Jupyter notebook, only Spyder, so this is not confined to just the notebook). 

[Seaborn bug.ipynb.zip](https://github.com/mwaskom/seaborn/files/517835/Seaborn.bug.ipynb.zip)

**Comment by dgua** [comment]
Sorry, the system here botched `seaborn.__version__`

**Comment by mwaskom** [comment]
In your notebook you are importing `seaborn.apionly as sns`. So `sns` is not `seaborn`, it is `seaborn.apionly`.
