### ISSUE TITLE
Docs don't build on Python 2

### ISSUE THREAD

**Issue by jvkersch** [mwaskom/seaborn#1039]
In Python 2 `exec` is a keyword, so calling it like a function as on https://github.com/mwaskom/seaborn/blob/master/doc/sphinxext/plot_generator.py#L26 fails.

**Comment by mwaskom** [comment]
Do you mean python 3?

**Comment by jvkersch** [comment]
@mwaskom No, I meant Python 2. I tried to build the docs locally (on Python 2) since the documentation website seems to be offline (#1041), but Sphinx crashed with a SyntaxError when running `make html`. The reason is that particular construction that I highlighted in the PR description, which is only valid in Python 3.

**Comment by jvkersch** [comment]
Traceback:
```
$ python --version
Python 2.7.11 -- Enthought, Inc. (x86_64)
(clean)14:05:34-jvkersch ~/src/seaborn/doc (master)
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.5

Exception occurred:
  File "/Users/jvkersch/.edm/envs/clean/lib/python2.7/site-packages/sphinx/application.py", line 431, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/Users/jvkersch/src/seaborn/doc/sphinxext/plot_generator.py", line 26
    exec(compile(open(filename, "rb").read(), filename, 'exec'), globals, locals))
       ^
SyntaxError: invalid syntax
The full traceback has been saved in /var/folders/cp/tsh44ltd0mz1cmtzqbw785f00000gn/T/sphinx-err-nXzsGw.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

**Comment by mwaskom** [comment]
Then I am a bit confused because I regularly build the docs on Python 2.

**Comment by mwaskom** [comment]
Oh except I might not have done so since merging this: https://github.com/mwaskom/seaborn/pull/950 Sigh.

**Comment by mwaskom** [comment]
Closed with #1040 (which I also haven't tested because I am busy right now so I hope it works!)

**Comment by jvkersch** [comment]
@mwaskom If you want, I can try adding the docs build to Travis (under Python 2 and 3).

**Comment by mwaskom** [comment]
I used to do that, but then got irritated at how long the build took :)
