### ISSUE TITLE
docs down

### ISSUE THREAD

**Issue by nateGeorge** [mwaskom/seaborn#1043]
Perhaps it's just me, but the docs are inaccessible:

![image](https://cloud.githubusercontent.com/assets/10804060/19324315/2bb9f3c6-907e-11e6-8b88-ba607c943908.png)

http://stanford.edu/~mwaskom/software/seaborn/

Maybe github pages would be more reliable?

**Comment by mwaskom** [comment]
#958

**Comment by nateGeorge** [comment]
I see
https://seaborn.github.io/

**Comment by mwaskom** [comment]
Can you keep the discussion on the other issue please? Thanks.

**Comment by nateGeorge** [comment]
Ok
