### ISSUE TITLE
Unable to access documentation

### ISSUE THREAD

**Issue by fourpartswater** [mwaskom/seaborn#1046]
Hi, 

When I try to access 

https://stanford.edu/~mwaskom/software/seaborn/

I get:

Access forbidden

The page you requested is not accessible. This may either be due to the server not having permission to access this directory, or a server error. If you are the administrator for this site, please check the permissions on this directory and file a HelpSU if you need help. If you are a user, please contact the administrators for this site, or HelpSU if you think the error is due to a server problem.

Nice software! 

Peter

**Comment by JWarmenhoven** [comment]
I understand that Michael has left Stanford so his content on their webservers is not accessible anymore. But it is being worked on I believe.

https://twitter.com/michaelwaskom/status/785847444760387584

**Comment by mwaskom** [comment]
#958
