### ISSUE TITLE
Seaborn website: "Access Forbidden"

### ISSUE THREAD

**Issue by peter-d** [mwaskom/seaborn#1047]
Navigating to http://stanford.edu/~mwaskom/software/seaborn/ (the link from the top of the github page) results in:

![image](https://cloud.githubusercontent.com/assets/2284375/19348449/49586720-914e-11e6-88ce-e069429b063b.png)

Happens both on our corporate network as well as on my mobile data, so seems like something is misconfigured on the server...

**Comment by ededovic** [comment]
Same issue for me. 
The only workaround at the moment is to use Google's cached pages.

**Comment by mwaskom** [comment]
#958
