### ISSUE TITLE
Seaborn website is unreachable

### ISSUE THREAD

**Issue by rostyboost** [mwaskom/seaborn#1049]
Right now (Thu Oct 13 19:46:29 UTC 2016) Seaborn [homepage](http://stanford.edu/~mwaskom/software/seaborn/) is unreachable:
![screen shot 2016-10-13 at 12 45 16 pm](https://cloud.githubusercontent.com/assets/5135135/19364417/f92f3e0a-9142-11e6-96fd-a073f3335d62.png)

**Comment by mwaskom** [comment]
#958
