### ISSUE TITLE
Example gallery link permission denied

### ISSUE THREAD

**Issue by mverleg** [mwaskom/seaborn#1050]
The link in "The documentation has an example gallery with short scripts showing how to use different parts of the package."

http://stanford.edu/%7Emwaskom/software/seaborn/examples/index.html

    Access forbidden
    The page you requested is not accessible. This may either be due to the server not having permission to access this directory, or a server error. ...

A similar link with similar error also appears near the top on Google results on "seaborn" for me.

**Comment by mwaskom** [comment]
#958
