### ISSUE TITLE
Stanford Documentation: Access Forbidden

### ISSUE THREAD

**Issue by hydrosquall** [mwaskom/seaborn#1051]
Currently, it looks like the online documentation links have been down for a couple days. Is the documentation down for maintenance / mirrored at any other locations?

- [Docs](http://stanford.edu/~mwaskom/software/seaborn/)
- [Dev Docs](http://stanford.edu/~mwaskom/software/seaborn-dev/)

Screenshot taken just now:

![seaborn_error](https://cloud.githubusercontent.com/assets/9020979/19365085/fd5e0f26-915e-11e6-9adc-a1903c40453f.PNG)

**Comment by mwaskom** [comment]
#958
