### ISSUE TITLE
Feature request: Include alternative definitions for calculating the whiskers in boxplots

### ISSUE THREAD

**Issue by Khris777** [mwaskom/seaborn#1053]
Right now whiskers are only calculated by multiples of the interquartile range with 1.5 as default value (Tukey-Boxplot).

There are alternative definitions though, most importantly one where the whiskers are calculated such that their range encompasses 95% of all data points with the remaining 2.5% of the data points on each side defined as outliers, that is it uses 2.5% quantils for definition of outliers. Other values like 2%, 5%, 9% also seem to be used. I think this definition is really helpful and I would love to see it added.

Another possible one would be the use of the standard deviation, or multiples of it, yet another simply takes the absolute min and max values of the data including all outliers.

**Comment by mwaskom** [comment]
The boxplot statistics are computed by matplotlib. You can pass arguments to the `plt.boxplot` function, or ask them if you want different functionality.
