### ISSUE TITLE
Seaborn documentation is down

### ISSUE THREAD

**Issue by Gilles86** [mwaskom/seaborn#1055]
For 2 days now I get an access error for the default Seaborn documentation at the Stanford servers:
"The directory you requested is not accessible. This may either be due to the server not having permission to access this directory, or a server error. If you are the administrator for this site, please check the permissions on this directory and file a HelpSU if you need help. If you are a user, please contact the administrators for this site, or HelpSU if you think the error is due to a server problem."

https://stanford.edu/~mwaskom/software/seaborn/

**Comment by mwaskom** [comment]
#958
