### ISSUE TITLE
Handle versioned docs better

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#1056]
As the docs have moved to seaborn.github.io and incoming links to the Stanford site are broken, it would be a good time to implement a system for versioning the docs (at the very least into stable/dev, but ideally with archival versions too).

This package was mentioned on twitter for helping a push from Travis to a devel site: https://drdoctr.github.io/doctr/

**Comment by ariddell** [comment]
The README still mentions pydata. Neither pydata nor github.io are working for me right now.
