### ISSUE TITLE
Make pointplot's linewidth more easily configurable

### ISSUE THREAD

**Issue by jphalip** [mwaskom/seaborn#1058]
Certain plots like `barplot` and `boxplot` make it easy to control the line width thanks to their `linewidth` parameter. Unfortunately `pointplot` is missing that functionality and relies only on matplotlib's global `lines.linewidth` setting.

To get around this limitation one has to use a context manager:

``` python
with plt.rc_context({'lines.linewidth': 0.8}):
    sns.pointplot(data['day'], data['price'])
```

It'd be much cleaner if one could directly pass a `linewidth` parameter to `pointplot`.

**Comment by mwaskom** [comment]
There's also `scale`

**Comment by tortarantola** [comment]
The scale argument doesn't seem to change the error bars.

**Comment by mwaskom** [comment]
That's because someone added an `errwidth` parameter but apparently forgot to document it :/
