### ISSUE TITLE
segmentation fault in clustermap if array contains NaN or inf

### ISSUE THREAD

**Issue by ryneches** [mwaskom/seaborn#1061]
The following code results in a segmentation fault if fastcluster is not installed :

````python
import numpy
import seaborn
a = [ [ 1,2,3,numpy.inf ], 
      [ 1,2,3,numpy.inf ], 
      [ 1,2,3,numpy.inf ], 
      [ 1,2,3,numpy.inf ] ]
seaborn.clustermap( a )
````

Most (all?) distance metrics in `scipy.distance.pdist` will fail produce valid output if the matrix contains `inf` or `nan`, but someone should probably raise an exception somewhere before things devolve badly enough to take down the interpreter.

**Comment by mwaskom** [comment]
Duplicate of #449
