### ISSUE TITLE
Add color palette to 1-hue pointplot

### ISSUE THREAD

**Issue by TheChymera** [mwaskom/seaborn#1064]
I would like to customize the color of a 1-hue pointplot, but I am noticing that whenever I add a color palette, the individual x-axis points get different colors. This is obviously not what I want, since I do not assign the x value to the `hue` attribute. This works as expected with multiple hues. 

What I am guessing happens here, is that the function just assumes there have to be multiple hues if one changes the color palette. But that shouldn't be the case. The one-color default behavior is also picked from a color palette, and one should be able to change that without changing the behavior of the rest of the function. I have tried passing it a 1-item color palette, and that won't work either.

Please find the example code and figures below: 

```import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

df = pd.DataFrame(np.random.randint(0,100,size=(100, 1)), columns=["val"])
df["cond"] = np.random.choice(["t1","t2","t3","t4"],100)
df["unit"] = np.random.choice(["u1","u2","u3","u4"],100)

f, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2,2)
sns.pointplot(x="cond", y="val", data=df, ci=68.3, legend_out=False, ax=ax1)
sns.pointplot(x="cond", y="val", data=df, ci=68.3, legend_out=False, palette=sns.color_palette(["#000000", "#E69F00", "#56B4E9", "#009E73","#F0E442", "#0072B2", "#D55E00", "#CC79A7"]), ax=ax2)
sns.pointplot(x="cond", y="val", hue="unit", data=df, ci=68.3, legend_out=False, ax=ax3)
sns.pointplot(x="cond", y="val", hue="unit", data=df, ci=68.3, legend_out=False, palette=sns.color_palette(["#000000", "#E69F00", "#56B4E9", "#009E73","#F0E442", "#0072B2", "#D55E00", "#CC79A7"]), ax=ax4)
plt.show()
```

![figure_1-1](https://cloud.githubusercontent.com/assets/950524/20007760/0db0d598-a29e-11e6-98e8-cb0ed547599b.png)

**Comment by mwaskom** [comment]
Sorry I don't understand the issue here? There is a palette applied across the `x` variable, isn't that what you're asking for?

**Comment by TheChymera** [comment]
Well, as seen in the last 2 figures, in all other cases the palette is applied across the `hue` variable. How can I apply a palette across the `hue` variable when there is only one hue?

**Comment by mwaskom** [comment]
You're not using `hue` in the top row of plots.

**Comment by mwaskom** [comment]
BTW you don't need to call `sns.color_palette` on the list you are passing to `palette`. It gets called internally.

**Comment by mwaskom** [comment]
Maybe the answer to your question is the `color` parameter, as seen in the documentation and examples [here](http://seaborn.pydata.org/generated/seaborn.pointplot.html)?

**Comment by TheChymera** [comment]
That worked out. Thanks.
