### ISSUE TITLE
Is is possible to assign a special axes to a factorplot?

### ISSUE THREAD

**Issue by kain88-de** [mwaskom/seaborn#1065]
I would like to create a figure with two separate factor plots. I guessed I could just pass a axes argument to the factorplot to assign it a special axis.

```python
f, (ax1, ax2) = plt.subplots(1, 2)

g = sns.factorplot(ax=ax1, data=d1, ...)
g = sns.factorplot(ax=ax2, data=df2, ...)
```

That works to some extend. It does plot into the assigned axes but it also creates two new empty figures.

**Comment by mwaskom** [comment]
No. See http://stackoverflow.com/questions/23969619/plotting-with-seaborn-using-the-matplotlib-object-oriented-interface for more.
