### ISSUE TITLE
Pairplot does not raise an error when passed a Pandas series

### ISSUE THREAD

**Issue by jaypeedevlin** [mwaskom/seaborn#1067]
I came across this issue when someone who I was teaching pairgrid mangled the syntax and passed three pandas series' as the first three variables to `pairplot()`.

The issue is that rather than raising an error, the code seems to get caught up and eventually times out.

**Version Info:**

Seaborn `0.7.1`
Matplotlib `1.5.3`
Plotting in Jupyter Notebook using `%matplotlib inline`

**To reproduce:**

```
import seaborn as sns
import pandas as pd
import numpy as np

s = pd.Series(np.random.randint(0,100,size=100))
sns.pairplot(s)
sns.plt.show()
```

**Comment by mwaskom** [comment]
Closed by #1227
