### ISSUE TITLE
Pass different scatter_kws to each facet in lmplot when using col/row

### ISSUE THREAD

**Issue by cmardiros** [mwaskom/seaborn#1070]
I'd like each facet to use a different scatter_kws in lmplot. Is this possible? I am creating a custom colors array mapped to values to highlight outliers. This works well for the unfacetted plot (see below) but obviously the size of the array doesn't match the data points in each facet.

[https://www.evernote.com/shard/s146/sh/3d7f90b3-74de-4cd8-aea2-63dc28827ac9/b1cec029534f258e/res/a014620f-c356-402d-8f61-500d1d8e4785/skitch.png](url)

Any suggestions? Perhaps a pointer on how to change this after the plot has been drawn?

Thanks

**Comment by mwaskom** [comment]
That URL is broken and I can't help you without seeing the code you're using. I'd suggest making a reproducible example and posting to stackoverflow.

**Comment by mmagnuski** [comment]
@mwaskom - the url will work if you copy paste it to the adress bar, but it's only an image - no code 😿

**Comment by cmardiros** [comment]
My apologies. Here is the Stackoverflow question with reproducible example:

http://stackoverflow.com/questions/40829475/how-to-pass-different-scatter-kwargs-to-facets-in-lmplot-in-seaborn
