### ISSUE TITLE
Rugplot with labels is showing one legend per entry

### ISSUE THREAD

**Issue by mickours** [mwaskom/seaborn#1071]
I'm using the rugplot to add some information in a graph (when load == 0 ) and I want to add a legend for it so I wrote this:
```python
sns.rugplot(u.load[u.load == 0].index, ax=ax, color='r, label="Reset event (load == 0)")
```
It works perfectly, but the graph legend show one entry per rug line instead of only one. Also the line in the legend is horizontal instead of vertical.

![capture du 2016-12-02 17-18-08](https://cloud.githubusercontent.com/assets/837312/20841232/541655dc-b8b3-11e6-8da5-32098d317901.png)

**Comment by mwaskom** [comment]
This is expected behavior in that `rugplot` draws a bunch of regular lines and passes kwargs through to them. You'll need to make a proxy artist to get a correct legend entry, something like

```python
x = np.random.randn(50)
ax = sns.rugplot(x)
ax.scatter([], [], marker="|", linewidth=2, s=100, label="a label")
ax.legend()
```

**Comment by mickours** [comment]
IMHO, as the label args is not relevant in this case the ``rugplot`` function should handle this instead of doing it outside, no?
