### ISSUE TITLE
Unable to change properties of whiskers and caps in pointplot

### ISSUE THREAD

**Issue by lepmik** [mwaskom/seaborn#1072]
Hi I would like to change some properties in pointplot, if I understand the docs correctly it should be possible to pass keyword arguments to matplotlib boxplot i.e
```python
sns.poinplot(df, **{'whiskerprops': {'color':'k', 'lw': 1}})
```
That does not seem to work, do you have another method or workaround?

**Comment by mwaskom** [comment]
The `pointplot` is not a `boxplot`. What made you think that approach would work? Look at the API documentation for pointplot` for an example of how to add caps.

**Comment by lepmik** [comment]
Well the idea came from miss reading the docs, sorry about that. However, the issue is not how to add caps, it's to change the color and line width of the caps and "whiskers".

**Comment by mwaskom** [comment]
You can change the width of the error bars with the `errwidth` parameter. There's no way to change the color separately from that of the points. But also keep in mind that the error bars on a pointplot are *not* showing the same thing as the whiskers in a boxplot.
