### ISSUE TITLE
Use seaborn with custom matplotlib styles

### ISSUE THREAD

**Issue by TheChymera** [mwaskom/seaborn#1073]
Stackoverflow answers [here](http://stackoverflow.com/questions/25393936/how-can-i-use-seaborn-without-changing-the-matplotlib-defaults) and [here](http://stackoverflow.com/questions/33099348/seaborn-configuration-hides-default-matplotlib), and the docsting [here](http://seaborn.pydata.org/generated/seaborn.reset_orig.html) (and I assume many other places) incorrectly point out that using `import seaborn.apionly as sns` or `sns.reset_orig()` can prevent seaborn from rewriting custom rc parameters.
In truth, this seems to just revert to the matplotlib defaults.

Ideally I would like to get the results provided by the following code, without having to insert a call to my custom parameters in between the seaborn import and the plot call

```
import matplotlib.pyplot as plt

import seaborn as sns
sns.set(style="ticks")
plt.style.use(u'ggplot')

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.show()
```

**None** of the following alternatives produce a comparable result:

I.
```
import matplotlib.pyplot as plt

plt.style.use(u'ggplot')
import seaborn.apionly as sns
sns.set(style="ticks")

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.show()
```

II.
```
import matplotlib.pyplot as plt

plt.style.use(u'ggplot')
import seaborn as sns
sns.reset_orig()
sns.set(style="ticks")

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.show()
```

III.
```
import matplotlib.pyplot as plt

import seaborn as sns
sns.set(style="ticks")

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.style.use(u'ggplot')
plt.show()
```

IV.
```
import matplotlib.pyplot as plt

import seaborn.apionly as sns
sns.set(style="ticks")

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.style.use(u'ggplot')
plt.show()
```

Can you help me out? I write wrappers for my plotting functions which I call from PythonTeX or other analysis scripts. To continue using the initial code sequence I would need to  mess up my API for all functions that somewhere use any module that imports seaborn, and pass them matplotlibrc as an argument all the way down.

It would be really great if seaborn had the option to play nice and not touch matplotlibrc.

**Comment by mwaskom** [comment]
In every sample, you are calling `sns.set()`. That is what is applying the seaborn styles. Don't call `sns.set` if you don't want to use the seaborn styles.

**Comment by TheChymera** [comment]
@mwaskom 

Sadly, that does not seem to address the issue. I now have the following code, the results of which I would like to reproduce without defining my styles after the seaborn import:

```
import matplotlib.pyplot as plt

import seaborn.apionly as sns
plt.style.use(u'ggplot')

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.show()
```

**None** of the following attempts accomplish this:

I.
```
import matplotlib.pyplot as plt

plt.style.use(u'ggplot')
import seaborn as sns

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.show()
```

II.
```
import matplotlib.pyplot as plt

plt.style.use(u'ggplot')
import seaborn.apionly as sns

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.show()
```

III.
```
import matplotlib.pyplot as plt

plt.style.use(u'ggplot')
import seaborn as sns
sns.reset_orig()

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.show()
```

IV.
```
import matplotlib.pyplot as plt

import seaborn as sns

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.style.use(u'ggplot')
plt.show()
```

Again, it seems seaborn doesn't conserve the matplotlibrc but rather introduces some sort of matplotlib default.

**Comment by TheChymera** [comment]
I have gone on to debug this. The following shows that `seaborn.apionly` does indeed just apply some defaults:

```
import matplotlib as mpl
import matplotlib.pyplot as plt
from copy import deepcopy

print(mpl.rcParams["axes.facecolor"])
plt.style.use(u'ggplot')
print(mpl.rcParams["axes.facecolor"])
import seaborn.apionly as sns
print(mpl.rcParams["axes.facecolor"])

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.style.use(u'ggplot')
plt.show()
```

The following, though, shows that even if the matplotlibrc values were to be deepcopied and then restored, the seaborn plotting function would not apply them:

```
import matplotlib as mpl
import matplotlib.pyplot as plt
from copy import deepcopy

print(mpl.rcParams["axes.facecolor"])
plt.style.use(u'ggplot')
print(mpl.rcParams["axes.facecolor"])
a = deepcopy(mpl.rcParams)
import seaborn.apionly as sns
# plt.style.use(u'ggplot')
mpl.rcParams = a
print(mpl.rcParams["axes.facecolor"])

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.show()
```

It is very strange that the code above fails to apply the ggplot style, while the code below succeeds.

```
import matplotlib as mpl
import matplotlib.pyplot as plt
from copy import deepcopy

print(mpl.rcParams["axes.facecolor"])
plt.style.use(u'ggplot')
print(mpl.rcParams["axes.facecolor"])
a = deepcopy(mpl.rcParams)
import seaborn.apionly as sns
plt.style.use(u'ggplot')
mpl.rcParams = a
print(mpl.rcParams["axes.facecolor"])

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", size=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.show()
```

So not only does seaborn seem to not conserve the rcParams, but in addition to that, there seems to be more to this than just the rcParams. But what?

**Comment by mmagnuski** [comment]
@TheChymera you need to update to seaborn 7.1

**Comment by mwaskom** [comment]
Yes you problem need to upgrade, but if that doesn't solve you problem you must actually show the plots you're getting. How am I supposed to help diagnose what's causing the problems you're seeing if I can't see them too?

**Comment by TheChymera** [comment]
The above examples are self-contained. Are you getting identical plots for any of the conditions where I am not?

**Comment by mwaskom** [comment]
I do not know if I am getting identical plots to you because I cannot see your plots!

**Comment by TheChymera** [comment]
The code for the plots I want to reproduce is attached, as are the code variants which have failed to produce identical plots. Do these bits of code produce identical plots on your machine?

**Comment by mmagnuski** [comment]
@TheChymera do you sill have the problems after ensuring you are on seaborn 0.7.1?

**Comment by TheChymera** [comment]
@mmagnuski I need to version bump it in Portage first. Might take a while. Do you run `0.7.1`? If so, have you tried to run my examples, and can you tell me which pair of two code snippets produces identical plots on your machine?

**Comment by mmagnuski** [comment]
@TheChymera Yes, I was able to replicate your problems on `0.7.0` but not after upgrading to `0.7.1`.
One of the things that changed in `0.7.1` is that seaborn saves the matplotlib rc params at import and in `apionly` applies them back in the end.

**Comment by TheChymera** [comment]
@mmagnuski thank you so much for the pointer. Indeed, the version bump fixed this. As a positive side-effect of my run-in with this bug, I have now added `=dev-python/seaborn-0.7.1` to the Gentoo package tree.
