### ISSUE TITLE
Adding space between boxes in grouped boxplot

### ISSUE THREAD

**Issue by agamemnonc** [mwaskom/seaborn#1076]
Is there an easy way, either through seaboard or matplotlib directly, to add some space between boxes in a grouped box plot?

For example, add a bit of space between pink and green boxes in this [example](http://seaborn.pydata.org/examples/grouped_boxplot.html).

**Comment by mwaskom** [comment]
I don't think so, sorry.

**Comment by phobson** [comment]
@agamemnonc you can make the boxes narrower using `width`:

```python
# Draw a nested boxplot to show bills by day and sex
sns.boxplot(x="day", y="total_bill", hue="sex", data=tips, palette="PRGn", width=0.2)
sns.despine(offset=10, trim=True)
```

![boxes](https://cloud.githubusercontent.com/assets/1163939/21155795/5fd80f00-c128-11e6-8354-3d5343182c73.png)

**Comment by mwaskom** [comment]
Yes, good point — I had assumed @agamemnonc meant between the boxes in each group.

**Comment by phobson** [comment]
re-reading the question, I think that's the safer assumption

**Comment by agamemnonc** [comment]
Indeed, I meant space between the boxes within the same group

**Comment by satyausc** [comment]
Is there still a solution for adding space between the boxes within the group?

**Comment by rmartins-net** [comment]
Any update about this question ?

**Comment by aqzlpm11** [comment]
I fount a solution [here](https://stackoverflow.com/questions/56838187/how-to-create-spacing-between-same-subgroup-in-seaborn-boxplot).

> ``` python
> import numpy as np
> from matplotlib.patches import PathPatch
> 
> def adjust_box_widths(g, fac):
>     """
>     Adjust the widths of a seaborn-generated boxplot.
>     """
> 
>     # iterating through Axes instances
>     for ax in g.axes:
> 
>         # iterating through axes artists:
>         for c in ax.get_children():
> 
>             # searching for PathPatches
>             if isinstance(c, PathPatch):
>                 # getting current width of box:
>                 p = c.get_path()
>                 verts = p.vertices
>                 verts_sub = verts[:-1]
>                 xmin = np.min(verts_sub[:, 0])
>                 xmax = np.max(verts_sub[:, 0])
>                 xmid = 0.5*(xmin+xmax)
>                 xhalf = 0.5*(xmax - xmin)
> 
>                 # setting new width of box
>                 xmin_new = xmid-fac*xhalf
>                 xmax_new = xmid+fac*xhalf
>                 verts_sub[verts_sub[:, 0] == xmin, 0] = xmin_new
>                 verts_sub[verts_sub[:, 0] == xmax, 0] = xmax_new
> 
>                 # setting new width of median line
>                 for l in ax.lines:
>                     if np.all(l.get_xdata() == [xmin, xmax]):
>                         l.set_xdata([xmin_new, xmax_new])
> ```
> For example
> ``` python
> fig = plt.figure(figsize=(15, 13))
> bp = sns.boxplot(#insert data and everything)
> adjust_box_widths(fig, 0.9)
> ```

**Comment by GiliR4t1qbit** [comment]
It would be great if `seaborn` had an internal solution for this... How about re-opening the issue? (not sure why it was closed?)

**Comment by brandonlind** [comment]
@aqzlpm11 or anyone else know of a solution for boxenplot - specifically sns.catplot(..., kind='boxen')? TIA
