### ISSUE TITLE
ValueError when trying to specify colours to a regplot

### ISSUE THREAD

**Issue by spinicist** [mwaskom/seaborn#1079]
Hello,
I am having the same problem described here: http://stackoverflow.com/questions/40141445/matplotlib-seaborn-valueerror-supply-a-c-kwarg-or-a-color-kwarg-but-not
I enquired in the Matplotlib gitter and they suspect that they have changed something in a bugfix release that has broken Seaborn.

I am running Matplotlib 1.5.3, Seaborn 0.7.1.

Thanks in advance.

**Comment by phobson** [comment]
@spinicist what's unsatisfactory about the accepted answer to the SO question?

**Comment by spinicist** [comment]
Sorry for the delay in responding. It doesn't work for me. The following call:
`sb.regplot('zscore',rois[i],csv,ax=ax[i],color='r',scatter=True,scatter_kws={'c':sb.color_palette()},line_kws={'linewidth':0.4})`
gives the same error as mentioned on SO:
`ValueError: Supply a 'c' kwarg or a 'color' kwarg but not both; they differ but their functionalities overlap.`

**Comment by mwaskom** [comment]
You should do `fit_reg=False` in `regplot` and then draw the scatterplot using `ax.scatter`.

**Comment by spinicist** [comment]
Thanks, that's what I ended up doing (which is why I took so long to respond as I had something that vaguely worked). It's a shame it can't be done in one call anymore.
