### ISSUE TITLE
It would be awesome if box- and violinplot accept an alpha value

### ISSUE THREAD

**Issue by habi** [mwaskom/seaborn#1080]
Sometimes I would like to make very subdued box- or violinplots.
It would be nice if they would accept an alpha-value as for example `barplot` does.

`violinplot` just does nothing with the parameter, while `boxplot` fails with a `TypeError` about the `unexpected keyword argument 'alpha'`.

![clipboard01](https://cloud.githubusercontent.com/assets/1651235/21185670/f02cc9b2-c211-11e6-90a8-a80a0b82b03a.png)

**Comment by habi** [comment]
Sorry, forgot to mention:
- seaborn version 0.7.1
- matplotlib version 1.5.3
- running in Jupypter under Python '3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]'

**Comment by mwaskom** [comment]
It may be awesome, but there are enough complexities that it isn't going to happen; sorry. See also #979

**Comment by habi** [comment]
OK. I just found it strange that `barplot` accepts alpha and the other two don't. I'll use the workaround mentioned in the other issue, thanks.

**Comment by mwaskom** [comment]
If you look at the function signature you'll see that `alpha` isn't a parameter of `barplot`. But `barplot` passes its kwargs to the underlying matplotlib function `plt.bar`. The underlying matplotlib function for `boxplot` doesn't do anything with an alpha parameter and there's no single underlying matplotlib function for `violinplot`, hence the behavior that you see.
