### ISSUE TITLE
pairplot fails with hue when number of items in a category is exactly 3

### ISSUE THREAD

**Issue by ppuggioni** [mwaskom/seaborn#1083]
See title :)

reproducible example:
```
data = {
    'code': ['apple']*3 + ['pear'],
    'x1': [0.1, 0.2, 0.15, 0.5],
    'y1': [0.2, 0.1, 0.4, 0.3]
}
data = pd.DataFrame(data)
sns.pairplot(data, hue='code')
```

the color of the apple dots is in greyscale and not blue as it should. The reason is deep inside matplotlib. When a palette is passed to the scatter function, if the number of points equals exactly the number of colors, the palette is flattened.

From matplotlib.axes._axes.scatter:

> fundamentally, scatter works with 1-D arrays; `x`, `y`, `s`,
        and `c` may be input as 2-D arrays, but within scatter
        they will be flattened. The exception is `c`, which
        will be flattened only if its size matches the size of `x`
        and `y`.

Unfortunately, if the number of items in a category is 3, the palette is flattened and they come up in a greyscale.

Good luck :)

**Comment by ppuggioni** [comment]
#840 Just realised it has been already discussed

**Comment by mwaskom** [comment]
I believe this may be fixed in matplotlib 2.1 (potentially "by accident" https://github.com/matplotlib/matplotlib/issues/8658).

**Comment by MaozGelbart** [comment]
This can be reopened as the following example triggers the old faulty color mapping (for groups of size=4) using matplotlib=3.2.1 (currently most recent version):
```python
import seaborn as sns
import pandas as pd

data = {
    'code': ['apple']*4 ,
    'x1': [0.1, 0.2, 0.15, 0.5],
    'y1': [0.2, 0.1, 0.4, 0.3]
}
data = pd.DataFrame(data)
sns.pairplot(data, hue='code')
```
![1083](https://user-images.githubusercontent.com/13831112/82115541-0f77e800-976c-11ea-9f9f-ba3c7473360a.png)
Meanwhile, to avoid this, downgrading matplotlib to 3.1.2 should do the work. 
xref [https://github.com/matplotlib/matplotlib/issues/17423](https://github.com/matplotlib/matplotlib/issues/17423) for the relevant issue on matplotlib.

**Comment by mwaskom** [comment]
Scatter doing weird things with the `c` parameter is truly the bug that will never die.

**Comment by mwaskom** [comment]
Re-closing in favor of #2076 since it's not a `pairplot` issue.
