### ISSUE TITLE
Change style of regplot

### ISSUE THREAD

**Issue by KaiSteinert** [mwaskom/seaborn#1084]
Hello, I'm trying to change the style of regplot with:

`import seaborn as sns; sns.set(style="whitegrid", color_codes=True)`

`ax = sns.regplot(x='Word count', y='Duration', data=data, label=label)`

But the plot remains with a gray background.

Thanks in advance.

**Comment by mwaskom** [comment]
Well I guess something has gone wrong but without more information it's impossible to say what it might be.
