### ISSUE TITLE
in heatmap, xticks and yticks change when robust==True

### ISSUE THREAD

**Issue by mosha5581** [mwaskom/seaborn#1086]
Hello,

I'm plotting a heatmap following http://seaborn.pydata.org/generated/seaborn.heatmap.html

My X and Y values range from 1 to 55, however the resulting heatmap xticks and yticks sho 0-35. 
When I plot the same data using pcolormesh directly, the ticks are correct. I have attached a snapshot of both
![matplotlib](https://cloud.githubusercontent.com/assets/1418364/21735446/f93f3c64-d437-11e6-92be-47e52f18f555.png)
![seaborn](https://cloud.githubusercontent.com/assets/1418364/21735447/f941bcfa-d437-11e6-90ab-eea153f4d5ad.png)

**Comment by mwaskom** [comment]
I can't help without seeing your code
