### ISSUE TITLE
dropna parameter not working with pairplot?

### ISSUE THREAD

**Issue by fizix00** [mwaskom/seaborn#1087]
I have a dataframe called `returns` that has `NaN` values in the first row.

When I do `sns.pairplot(returns[1:])` or `sns.pairplot(data=returns.dropna())`, there's no problem. However, when I try `sns.pairplot(data=returns, dropna=True)`, I get the following error: `ValueError: max must be larger than min in range parameter.`

As far as I can tell, all three approaches should've yielded the same result.

**Comment by mwaskom** [comment]
No, unfortunately it doesn't. `pairplot` doesn't currently work well with dataframes that have heterogeneous missing data. There was some work on it but it stalled out.
