### ISSUE TITLE
factor plot with continuous factor 

### ISSUE THREAD

**Issue by chananshgong** [mwaskom/seaborn#1089]
Say you have a binary response variable y and an independent variable x which is continuous. 
You would like to plot y as a function of x, but in order for the plot to be meaningful (and not just values of zeros and ones) you would like to plot the conditional mean over x. If x was categorical, it would be easy, as factorplot already supports that. What I suggest it to support the case of continuous x by bucketing the data according to dectiles or other arbitrary quantiles. These could be per group (e.g. hue, or col) or for the entire population. 
I would be happy to contribute this functionality with some help from the community.

**Comment by mwaskom** [comment]
This is easy to do already with `pandas.cut` (or `pandas.qcut`).

**Comment by chananshgong** [comment]
First, qcut is not stable when the quantiles values  are not unique (e.g. you have 80% zeros), but that's besides the point. The point is that seaborn is there to make data exploration easy and sometimes you would like to plot the relationship between column x and y in a dataframe, when x is continuous, without having to code a lot. That's the idea of seaborn. I think that "continuous factor plot" is a handy tool.
