### ISSUE TITLE
Background gradients don't work with Github's Notebook renderer

### ISSUE THREAD

**Issue by chewbranca** [mwaskom/seaborn#1090]
Not sure if this is the appropriate place for this issue, but I figured folks here might have a grasp on the problem. The issue I'm seeing is that the background gradient styles are disappearing when you render a cached notebook using Github's default notebook render.

Using the examples from [1] I've created a gist [2] with the sample dataframe and background gradient demo. You can clearly see in [1] that there's no background gradient, yet if we render this same gist through Jupyter's "gist" notebook renderer [3] we can see that the background gradient colors are rendered as expected.

Any ideas on the problem here? or ideas of how to work around this so gradient colors are displayed in Github's notebook renderer?

[1] http://pandas.pydata.org/pandas-docs/stable/style.html
[2] https://gist.github.com/chewbranca/55c094c0b921e1066a859ee38399b084
[3] http://nbviewer.jupyter.org/gist/chewbranca/55c094c0b921e1066a859ee38399b084

**Comment by mwaskom** [comment]
I don't think this is the right place for this. Seaborn is only being used to generate a list of colors in those examples, it has nothing to do with rendering the html so the colors are used properly. Sorry, I don't have any idea what the problem might be.

**Comment by TomAugspurger** [comment]
Github disables CSS and javascript in their rendered notebooks as a security measure.

**Comment by chewbranca** [comment]
Thanks @mwaskom.

@TomAugspurger ahhh that makes sense, bit unfortunate though. Interestingly, some of the Seaborn style changes still come through, for instance the plot backgrounds. Taking a look at the raw data in [1] it appears that those styles remain because it's an inline png.

I did a quick experiment and inline styles do work, which you can see in [2]. It looks like the various inline id attributes are removed, like `id="T_f449da21_d6a3_11e6_8914_acbc32c50aad"`, but the inline style attributes stick around. So a potential workaround here would be embed the styles inline in the html table rather than as a `style` block alongside the table output. This is a bit ugly, but given that the block of style is just using IDs for everything along the lines of `#T_f449da21_d6a3_11e6_8914_acbc32c50aadrow0_col0 { background-color:  #e5ffe5; }` it doesn't seem terrible to just inline those. Thoughts?


[1] https://gist.github.com/chewbranca/3473a220c1a23854424a6f4183783f9f
[2] https://gist.github.com/chewbranca/8745f3a348666f8c71ea5b0f685f6129

**Comment by chewbranca** [comment]
And here's an example of the inline styling working with the gradients: https://gist.github.com/chewbranca/5568b8a554a737ed506b867ccf291f84
