### ISSUE TITLE
regplot without scatter doesn't plot properly

### ISSUE THREAD

**Issue by sammosummo** [mwaskom/seaborn#1091]
Is the following behavior intentional? Logically I expected the regression line to be the same in both plots.

```python
import seaborn as sns
import matplotlib.pyplot as plt


tips = sns.load_dataset("tips")
plt.subplot(211)
sns.regplot(x="total_bill", y="tip", data=tips, scatter=True)
plt.subplot(212)
sns.regplot(x="total_bill", y="tip", data=tips, scatter=False)
plt.savefig('test.png')
```
![test](https://cloud.githubusercontent.com/assets/9464950/21814679/13eebc5e-d728-11e6-8743-452567fefb2b.png)

**Comment by mwaskom** [comment]
Why do you think the regression line is different? It looks the same to me.

**Comment by sammosummo** [comment]
Hm, you are right they are the same. Sorry, I was trying (and failed) to make a minimal example of an problem I was having, obviously though this isn't it.
