### ISSUE TITLE
xticks rotation fails on factorplot

### ISSUE THREAD

**Issue by ggrrll** [mwaskom/seaborn#1099]
Hi, 

(I don't know if it's better to post this question on stack-overflow, anyway...)

When I try to plot `factorplot` and try to rotate the xticks labels with `plt.xticks(rotation=60)` only the last (sub)plot has the xticks correctly rotated — as you can see in the attached screenshot.

Is it a bug ?

Thanks for helping.

<img width="489" alt="rotation_issue" src="https://cloud.githubusercontent.com/assets/15370425/22208719/2a4869d0-e184-11e6-9bcf-811b0ecf54a7.png">

**Comment by mwaskom** [comment]
I can't help you without a reproducible example.

**Comment by mwaskom** [comment]
Actually nevermind, the mistake is very obvious. `plt.xticks` only operates on the active subplot. You need to read up about the object-oriented matplotlib interface. In fact I believe there is almost an identical question somewhere on stackoverflow.

**Comment by ggrrll** [comment]
yeah sorry - this [post](http://stackoverflow.com/questions/26540035/rotate-label-text-in-seaborn-factorplot) solved indeed the issue
