### ISSUE TITLE
Minor gridlines not configured automatically

### ISSUE THREAD

**Issue by 8one6** [mwaskom/seaborn#110]
See:
http://stackoverflow.com/questions/21923463/add-minor-gridlines-to-matplotlib-plot-using-seaborn/

The following code produces code without any minor gridlines.

```
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn

x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x)

fig, ax = plt.subplots(1, 1)
ax.scatter(x, y)

ax.grid(b=True, which='major')
ax.grid(b=True, which='minor')
```

To get the gridlines to show up, I wound up doing:

```
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sbn

x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x)

fig, ax = plt.subplots(1, 1)

ax.scatter(x, y)

ax.get_xaxis().set_minor_locator(mpl.ticker.AutoMinorLocator())
ax.get_yaxis().set_minor_locator(mpl.ticker.AutoMinorLocator())

ax.grid(b=True, which='major', color='w', linewidth=1.0)
ax.grid(b=True, which='minor', color='w', linewidth=0.5)
```

Is it possible to have this done in a more seamless way?

**Comment by sleepyhollo** [comment]
@mwaskom Seems like seaborn does not even plot minor gridlines. Did not want to open an issue before asking here first. Any intention on including this? if you are too busy, I may spend some time looking into it.

**Comment by mwaskom** [comment]
I believe it remains impossible to a) enable minor grids or b) configure their linewidth through the matplotlib rcParam system.

**Comment by sleepyhollo** [comment]
I am asking again because of your comment to[this](https://stackoverflow.com/a/21924612/10755836) answer in stackoverflow.

Just to be clear, I am just interested in (a). i.e. having the ability to add minor gridlines to my seaborn plots. I will try to look into the seaborn source tomorrow and see why its impossible to add minor grids.

P.S. @mwaskom thanks for this wonderful library ❤️

**Comment by mwaskom** [comment]
Right — look at the dates. That question prompted this issue, where it was determined that it wasn't really possible. AFAIK that remains true.

**Comment by sleepyhollo** [comment]
woops. my bad. should have read the issue first.

**Comment by sleepyhollo** [comment]
I tried looking around the code a little, but it will take me a lot more time to figure stuff out. Meanwhile I plan on looking up issues in the matplotlib github repo for the incorporation of grid parameters in the `rcParams`. I am beginner programmer so all this a little overwhelming, but I am hoping to persevere. Besides this I have a number of questions for you:
1. do you have any design documentation for seaborn that I can look into to get a quick overview of how you designed its architecture?
1. Is creating a seaborn function to add (minor) grids an option? or perhaps this can go in the constructors for the basic seaborn plot types (not too sure about this one as I didnt fully figure out how seaborn works yet)
1. How are the major grid lines added for some of the seaborn plots (e.g. [lineplots](https://seaborn.pydata.org/examples/wide_data_lineplot.html) and [scatterplots](https://seaborn.pydata.org/examples/different_scatter_variables.html))? Skimmed over the definition of the `ScatterPlotter` object, but couldnt find it.
1. I see that the dataframe plot method in pandas allows for a grid kwarg which draws gridlines. Did not look up the pandas implementation yet, but i think they call the `Axes.grid()` method on the axes as is required by matplotlib for drawing grids. is it an idea to add this option as a kwarg for the seaborn plotters?
