### ISSUE TITLE
distplot crashes when bins argument not set, due to _freedman_diaconis_bins calculation

### ISSUE THREAD

**Issue by lendup-cody** [mwaskom/seaborn#1105]
I found that I was unable to use sns.distplot(a) with a float array, and dug in more to understand. 
Upon further examination, it looks like in line 728 of numpy's function_base.py, inside numpy.histogram, the function fails if bins is set to a float value, with an error indicating that a dtype float64 cannot be used as an index. 

If you look inside the distplot code that calls np.histogram, (distributions.py, line 206), you can see that the code calls the `bins = min(_freedman_diaconis_bins(a), 50)`
I ran this method independently on an array of floats, and found that it returns a float value. This is then passed into numpy.histogram, causing the error to be thrown. 

This can be avoided by the primary caller by just setting an explicit (integer) bins argument, but this default should probably be set to convert the result of _freedman_diaconis_bins() to an integer.

**Comment by mwaskom** [comment]
Can you please provide a reproducible example and the version you are using? This sounds like something I have fixed before.

**Comment by lendup-cody** [comment]
Upgrading did indeed solve the problem. Example posted below just for completeness. 

`In [5]: a = [4.5, 6.7, 8.9]

In [6]: sns.distplot(a)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-0af416dacc9c> in <module>()
----> 1 sns.distplot(a)

/Users/cwild/Environments/mainEnv/lib/python2.7/site-packages/seaborn/distributions.pyc in distplot(a, bins, hist, kde, rug, fit, hist_kws, kde_kws, rug_kws, fit_kws, color, vertical, norm_hist, axlabel, label, ax)
    210         hist_color = hist_kws.pop("color", color)
    211         ax.hist(a, bins, orientation=orientation,
--> 212                 color=hist_color, **hist_kws)
    213         if hist_color != color:
    214             hist_kws["color"] = hist_color

/Users/cwild/Environments/mainEnv/lib/python2.7/site-packages/matplotlib/axes/_axes.pyc in hist(self, x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, **kwargs)
   5676             # this will automatically overwrite bins,
   5677             # so that each histogram uses the same bins
-> 5678             m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
   5679             m = m.astype(float)  # causes problems later if it's an int
   5680             if mlast is None:

/Users/cwild/Environments/mainEnv/lib/python2.7/site-packages/numpy/lib/function_base.pyc in histogram(a, bins, range, normed, weights, density)
    726
    727         # Initialize empty histogram
--> 728         n = np.zeros(bins, ntype)
    729         # Pre-compute histogram scaling factor
    730         norm = bins / (mx - mn)

TypeError: 'numpy.float64' object cannot be interpreted as an index`
