### ISSUE TITLE
Logistic regression with constant

### ISSUE THREAD

**Issue by stepelu** [mwaskom/seaborn#1106]
It seems that there is no way to produce plots of logistic regression with the inclusion of a constant term.

As a short term solution I modified `fit_statsmodels()` in `linearmodels.py` with the following code:
`reg_func = lambda _x, _y: model(_y, add_constant(_x), **kwargs).fit().predict(grid)`
where `add_constant()` comes from `statsmodels.tools.tools`, but it would be nice if an option could be included in `lmplot()` to achieve this result.

As an aside, I would also find really helpful if the parameters of the fitted model could be returned / displayed.

**Comment by mwaskom** [comment]
There is a constant in the model by default: https://github.com/mwaskom/seaborn/blob/master/seaborn/linearmodels.py#L247
