### ISSUE TITLE
No minus symbol for negative tick labels when saving as PDF 

### ISSUE THREAD

**Issue by Auerilas** [mwaskom/seaborn#1107]
I ran into a bug that only occurs when using seaborn. If I make a plot with negative y tick labels, I can save it as a pdf and it works fine:

```
import matplotlib.pyplot as plt
plt.plot([-1,1], [-1,1])
plt.savefig('~/Desktop/test1.pdf')
```
[test1.pdf](https://github.com/mwaskom/seaborn/files/736192/test1.pdf)

But if I import seaborn, the negative symbols on the y-axis disappear:

```
import seaborn as sns
plt.savefig('~/Desktop/test1_sns.pdf')
```

[test1_sns.pdf](https://github.com/mwaskom/seaborn/files/736193/test1_sns.pdf)

Saving as PNG works fine

`plt.savefig('~/Desktop/test1_sns_png.png')`

![test1_sns_png](https://cloud.githubusercontent.com/assets/9372234/22386408/309090fc-e494-11e6-90d8-342ac25f4ca4.png)

I just upgraded to matplotlib 2.0.0, but this error occured in graphs created before that. I'm using Python 3.5.2 on Linux Mint 18.1 (based on Ubuntu 16.04LTS)

**Comment by mwaskom** [comment]
I'm almost certain I've heard of this before, either here or on Stackoverflow, but I don't remember what the resolution was. If you search around you might find it before I can.

**Comment by mwaskom** [comment]
I changed the title because unless I'm missing something the minus sign is missing on the x axis tick labels too.

**Comment by mwaskom** [comment]
FWIW I don't see this on OSX so it's some interaction with the font seaborn is setting (which will vary a bit based on what you have availible — possibly not Arial on Linux) and the matplotlib PDF writer, which may also vary across systems (?).

**Comment by Auerilas** [comment]
Yup it's a font issue. If I change the default font in matplotlib from DejaVu Sans to Arial, I get the same issue. It has something to do with trying to use Arial on Linux (which isn't installed by default). Is there anyway to make seaborn use DejaVu Sans by default (which is also now the default font in matplotlib 2.0.0 and, for what is worth, kind of nice)?

**Comment by Auerilas** [comment]
I was able to fix it by going into rcmod.py within the seaborn site-packages library and changing the following:

```
"font.sans-serif": ["DejaVu Sans", "Arial", "Liberation Sans",
                                "Bitstream Vera Sans", "sans-serif"],
```

Now seaborn modifies the rcparams to use DejaVu Sans by default, just like matplotlib 2.0.0, which works for me!

**Comment by mwaskom** [comment]
"Default" fonts are a real headache, and DejaVu Sans isn't availible on OSX. I suppose it should at least be added to the seaborn sans-serif definition. Potentially it could take priority over Arial — I actually don't have very strong opinions on fonts other than that the old matplotlib default was very ugly. And a lot of journals require (or at least ask for) Helvetica/Arial.

The easiest way to use it with seaborn would be `sns.set(font="DejaVu Sans")` I suppose.

**Comment by sbanerjee23** [comment]
This is still a frustrating issue for me. I use a wrapper function that uses both seaborn contexts and then explicitly sets some mpl rcparams. I've tried a lot of things but I cannot get pdfs to save using an Arial font while keeping negative tick labels. Any advice would be much appreciated.

**Comment by mwaskom** [comment]
@sbanerjee23 I appreciate that venting your frustrations can feel nice, but if you actually read the thread you’ll learn that the problem is outside the scope of seaborn and that you should ask elsewhere.

**Comment by Imperssonator** [comment]
I'm having a similar issue in matplotlib 3.0.0, generating figures with the 'Agg' backend. I'd really like to know what Unicode character MPL is using for the negative signs, so I could just check if my fonts have that character.

**Comment by dvdhfnr** [comment]
A workaround is to save the figure as 'eps' and then convert it afterwards to 'pdf'. 
This keeps the '-' sign.
