### ISSUE TITLE
FacetGrid subplot figures extend beyond subplot margins

### ISSUE THREAD

**Issue by mxndrwgrdnr** [mwaskom/seaborn#1114]
I'm using sns.FacetGrid() to facet wrap a group of matplotlib plots of data in a Pandas dataframe. The code works fine except that the subplot figures always extend beyond the bounds of subplot axes. I figured out a workaround (the last line of the code here, presently commented out), but it throws an annoying error that I'd like to get rid of. Any ideas? Seems like you should be able to manually set the margins of the subplots in FacetGrid. I've attached the data I'm using as well.
[rent_data.csv.zip](https://github.com/mwaskom/seaborn/files/752699/rent_data.csv.zip)

```from matplotlib import pyplot as plt
import matplotlib.cm as cm, matplotlib.font_manager as fm
import pandas as pd

df = pd.read_csv("rent_data.csv",parse_dates=[2])

sns.color_palette("bright")
sns.set(font_scale=1.5)
sns.set_style("white")
g=sns.FacetGrid(df, col="region",col_wrap=4,size=3,sharey=True,aspect=1.2)
g.map(plt.plot, "week", "rent_per_sqft", color='k',marker='o',mfc='r',alpha=1)

g.set_xticklabels(rotation=30,fontsize=10)
g.set_titles("{col_name}")
g.set_xlabels("")
g.set_ylabels("")
plt.subplots_adjust(top=0.9)
g.fig.suptitle('Avg. Rent/Sqft by Week',fontproperties=title_font,fontsize=30)

# g.map(plt.margins(0.05, 0.15))

**Comment by mxndrwgrdnr** [comment]
In case the code doesn't work for you, here are the plots produced with and without the last line of code:
![test2](https://cloud.githubusercontent.com/assets/1395651/22623170/5cc710b6-eb05-11e6-9ea7-39287b96f11c.png)
![test](https://cloud.githubusercontent.com/assets/1395651/22623171/5cca5956-eb05-11e6-9e33-f6b29aa93ec1.png)

**Comment by phobson** [comment]
> subplot figures always extend beyond the bounds of subplot axes

Could you explain this? Are you saying that problem is the white space (margins) in the figure?

If so, try `g.savefig('facet.png', bbox_inches='tight')`

**Comment by phobson** [comment]
If you want to squeeze the axes closer together, you should do:

`g.fig.subplots_adjust(...)` called globally (i.e., not mapped to each axes)
http://matplotlib.org/api/figure_api.html#matplotlib.figure.Figure.subplots_adjust

**Comment by mwaskom** [comment]
You should read the facet grid tutorial and examples to understand how to use FacetGrid.map and why you are seeing an error the way you are using it.

Independently, `plt.margins` changes in the margins on the "active" axes. Because you're sharing axes this actually changes all of them; otherwise you can call `ax.margins` on each axes object. If that doesn't make sense, you should read up on the difference between the matplotlib imperative and object-oriented interfaces.

**Comment by mxndrwgrdnr** [comment]
Thanks, I figured out a workaround with this:
`for ax in g.axes:
    ax.margins(0.05, 0.15)`
Is there a more elegant solution you had in mind?

**Comment by mwaskom** [comment]
you could do `g.set(xmargin=0.05, ymargin=0.15)` but you have to do it before calling `g.map`.

By the way I don't think your code actually works as written because `g.axes` is always a two dimensional array but `for ax in g.axes.flat: ...` will work.

**Comment by mxndrwgrdnr** [comment]
Interesting. When I call `g.axes`, I get a 1-d array of `matplotlib.axes._subplots.AxesSubplot` objects. The `.flat` syntax produces the same results. Another consideration is that when I use the `g.set()` syntax, mpl and requires me to explicitly set the `ylim` as well in order to avoid negative values on the y-axis, while `g.axes` does not.

**Comment by mwaskom** [comment]
Are you sure you're calling `g.axes` and not `g.fig.axes` (where `g` is a `FacetGrid` object)?

I don't understand your second point.

**Comment by mxndrwgrdnr** [comment]
No, not calling g.fig.axes. Here is my code that runs fine and produces the desired output:

```
from matplotlib import pyplot as plt
import matplotlib.cm as cm, matplotlib.font_manager as fm
import pandas as pd 
%matplotlib inline

df = pd.read_csv("rent_data.csv",parse_dates=[2])

sns.color_palette("bright")
sns.set(font_scale=1.5)
sns.set_style("white")
g=sns.FacetGrid(df, col="region",col_wrap=4,size=3,sharey=True,aspect=1.2)
g.map(plt.plot, "week", "rent_per_sqft", 
      color='k',
      lw=1.25,
      marker='.', 
      mfc='r',
      markevery=[0,-1],
      ms=10)

for ax in g.axes:
    ax.margins(0.05, 0.15)

g.set_xticklabels(rotation=30,fontsize=10)
g.set_titles("{col_name}")
g.set_xlabels("")
g.set_ylabels("")
```

The second point was just suggesting that g.set() is maybe not the most flexible solution here, since it (seemingly) requires explicit setting of hard axis limits.

**Comment by mwaskom** [comment]
Ah right `g.axes` is one-dimensional when `col_wrap` is used.

**Comment by mwaskom** [comment]
I still don't understand your second point. Perhaps you could provide a demonstration of your issue. This works fine for me:

```
tips = sns.load_dataset("tips").groupby("size").mean().reset_index()
g = sns.FacetGrid(tips)
g.set(xmargin=.5, ymargin=.1)
g.map(plt.plot, "size", "tip", marker="o")
```
![image](https://cloud.githubusercontent.com/assets/315810/22661863/ef3eb97e-ec74-11e6-95aa-ccda3063a6e1.png)

**Comment by mxndrwgrdnr** [comment]
Eh, it's not a big issue. It's just that unless I explictly set the `ylim` when calling `g.set()`, I get negative values on the y axis

```
sns.color_palette("bright")
sns.set(font_scale=1.5)
sns.set_style("white")
g=sns.FacetGrid(df, col="region",col_wrap=4,size=3,sharey=True,aspect=1.2)
g.set(xmargin=0.05, ymargin=0.15)
g.map(plt.plot, "week", "rent_per_sqft", 
      color='k',
      lw=1.25,
      marker='.', 
      mfc='r',
      markevery=[-1],
      ms=10)
```
![example](https://cloud.githubusercontent.com/assets/1395651/22662109/b3163192-ec5c-11e6-9b74-625ac99a179d.png)

**Comment by mwaskom** [comment]
Yes; you are adding margins around your data and then ticks are being drawn to accommodate those margins.

**Comment by mxndrwgrdnr** [comment]
Yeah, I understand why its happening. I think that just makes `g.axes` a better solution here. Anyways, thanks for the help. Big fan of your work.
