### ISSUE TITLE
Dodge

### ISSUE THREAD

**Issue by stub68** [mwaskom/seaborn#1115]
This new keyword looks like it might fix a problem where I am trying to overlay a strip plot and a violin plot.  The 'x' values are further subdivided into 'hue'. This seemed to work in the past, then started to offset strip plot from violin (perhaps after a version update). Anyway, I have just tried to install the development version pip install using "git+git://github.com/mwaskom/seaborn.git#egg=seaborn", but it doesn't work for me. Is there another way to install? Thank you.

**Comment by phobson** [comment]
@stub68 what was the full command that you used? Your question isn't clear if you tried:
`git+git://github.com/mwaskom/seaborn.git#egg=seaborn`

or

`pip install git+git://github.com/mwaskom/seaborn.git#egg=seaborn`

In either case, the URL you supplied downloads the source via SSH. Do you have a valid SSH key on your system and registered with github? If not, try:

`pip install git+https://github.com/mwaskom/seaborn.git`

**Comment by mwaskom** [comment]
And you could always clone the repository then install from the local source.

**Comment by stub68** [comment]
Thanks for the reply. I wasn't aware of the SSH requirement, so that is likely the issue. Ill try the alternatives.

**Comment by mwaskom** [comment]
Thanks for catching that the docs were recommending the ssh protocol, @phobson; I've changed them to https.
