### ISSUE TITLE
Extend facetgrid (and similars) to accept categories defined by functions

### ISSUE THREAD

**Issue by wiso** [mwaskom/seaborn#1117]
Presently the facetgrid accept:

row, col, hue : strings
Variables that define subsets of the data, which will be drawn on separate facets in the grid.

Suppose I want to use a variable that it is not a column of my dataset, but that it can be computed starting from that. What I need to do now is to add a new column to my dataset and then use the name of this new column as argument.

Suppose I want to set the hue depending on the column 'column1' which is of type string, but I want to ignore the case. What about something like this:

    hue = lambda x: x['column1'].capitalize()

In addition it would be nice to add the possibility to use ranges. Suppose I want to set hue depending on column 'column2' which is of type float. Here I want to define categories depending on some binning as in pandas.Cut. As before I would like to avoid to add a column to my dataframe just to do a plot.

**Comment by TomAugspurger** [comment]
I use `DataFrame.assign` for this

```python
sns.factorplot('x', 'y', hue='hue', data=df.assign(hue=lambda x: x['column1'].capitalize())
```

so  ~10 characters longer that your version, which isn't too bad.

**Comment by wiso** [comment]
right, but I would like to avoid to duplicate my dataset every time I do a plot. Suppose for example I need to add a column for hue, one for x, one for ...

**Comment by mwaskom** [comment]
I think it's much better for seaborn to plot the data you have and to leave the data munging to pandas.
