### ISSUE TITLE
Horizontal lines with pointplot

### ISSUE THREAD

**Issue by jerome-white** [mwaskom/seaborn#1120]
I have a series of windows that I'd like to plot as stacked horizontal lines. From what I can tell, pointplot is the best way to go.

In the case of a single line, Seaborn sort of gives me what I want:
```
df = pd.DataFrame([{'x': 1, 'y': 1}, {'x': 4, 'y': 1}])
ax = sns.pointplot(data=df, x='x', y='y', hue='y', ci=None)
```
![1](https://cloud.githubusercontent.com/assets/6140840/23105434/a7cf7784-f6f8-11e6-9e5d-d933918dc08a.png)
While I'm satisfied with the horizontal line, I actually want it to be at y=1. Ignoring that, however, when I move on to two lines
```
df = pd.DataFrame([{'x': 1, 'y': 1}, {'x': 4, 'y': 1}, {'x': 3, 'y': 2}, {'x': 8, 'y': 2}])
sns.pointplot(data=df, x='x', y='y', hue='y', ci=None)
```
![2](https://cloud.githubusercontent.com/assets/6140840/23105450/d7e4d590-f6f8-11e6-8794-890eb2a867ab.png)
the y-axis problem is corrected, but I lose the connecting lines completely. In this case I am expecting there to be a line for each hue (two horizontal lines in total).

As a last attempt, I treat each plot as a separate drawing to same axis:
```
df = pd.DataFrame([{'x': 1, 'y': 1}, {'x': 4, 'y': 1}])
ax = sns.pointplot(data=df, x='x', y='y', hue='y', ci=None)
df = pd.DataFrame([{'x': 2, 'y': 2}, {'x': 8, 'y': 2}])
sns.pointplot(data=df, x='x', y='y', hue='y', ci=None, ax=ax)
```
![3](https://cloud.githubusercontent.com/assets/6140840/23105457/f1e7a0b2-f6f8-11e6-95d0-a4b528889281.png)
In this case, I get the two horizontal lines as expected, but both are aligned to the x-value of the second data frame; the first data frame should appear to the left of the first.

Am I doing something wrong? Is pointplot the correct approach to solving this problem?

Library|Version
---|---
Python | 3.5.2
Seaborn | 0.7.1
Pandas | 0.18.1
Matplotlib | 1.5.1

**Comment by mwaskom** [comment]
You want the second version but using only 2 x values. However you would probably find it easier to use matplotlib functions directly.
