### ISSUE TITLE
load_dataset is not working

### ISSUE THREAD

**Issue by fmv1992** [mwaskom/seaborn#1121]
Hi,

I'm trying to load the example of :
http://seaborn.pydata.org/generated/seaborn.jointplot.html#seaborn.jointplot:
```
>>> import numpy as np, pandas as pd; np.random.seed(0)
>>> import seaborn as sns; sns.set(style="white", color_codes=True)
>>> tips = sns.load_dataset("tips")
>>> g = sns.jointplot(x="total_bill", y="tip", data=tips)
```

However I get  `EmptyDataError: No columns to parse from file`.

First I inspected the link and realized it pointed nowhere so I updated from (https://github.com/mwaskom/seaborn/blob/master/seaborn/utils.py#L423):
`path = "https://github.com/mwaskom/seaborn-data/raw/master/{0}.csv"`
to:
`path = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/{0}.csv"`

But this was not enough to solve the problem.

Then I proceeded to try it on a clean interactive session and managed it just fine:
```
>>> import pandas as pd
pd.read>>> pd.read_csv('https://raw.githubusercontent.com/mwaskom/-data/master/tips.csv')
     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
```
Now I am confused and not sure if this is a seaborn issue, pandas issue or whatever.

I'm glad to get directions to do a PR myself.

**Comment by mwaskom** [comment]
Maybe you (or github, I guess) were having a network issue? I just tried and didn't have any problems.

**Comment by mwaskom** [comment]
It does look like github changed the url format for raw data,but also that they have a redirect set up.

**Comment by fmv1992** [comment]
Ok, thanks : )

**Comment by mwaskom** [comment]
Reopening as it would be good to change the target URL to the new version, even though it works right now.
