### ISSUE TITLE
splitting violinplot in categories with hue removes gray outline

### ISSUE THREAD

**Issue by tino-michael** [mwaskom/seaborn#1122]
This causes, if `split=True` is set, that the right violin will draw quite a bit over the centre to the left (see left-most violin in the bottom subplot).
```
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

a = np.random.randint(3, size=200)
b = np.random.rand(200)
c = np.random.randint(2, size=200)

plt.figure()
plt.subplot(311)
ax = sns.violinplot(x=a, y=b, hue=None, inner="quartile")

plt.subplot(312)
ax = sns.violinplot(x=a, y=b, hue=c, inner="quartile")

plt.subplot(313)
ax = sns.violinplot(x=a, y=b, hue=c, inner="quartile", split=True)

plt.show()
```

![bug_report](https://cloud.githubusercontent.com/assets/18286015/23310369/9dec04ea-fab2-11e6-9606-88c81c792aa0.png)

**Comment by mwaskom** [comment]
I can replicate this locally, but as you can see it was not the case the last time the [docs were built](http://seaborn.pydata.org/generated/seaborn.violinplot.html).

My guess would be something breaking with matplotlib 2.0, as I don't think the violinplot code itself has been touched recently.

What version of matplotlib are you using?

**Comment by mwaskom** [comment]
And what version of seaborn?

**Comment by mwaskom** [comment]
OK I think the answer is that this is a known matplotlib. There was a workaround submitted as a patch in https://github.com/mwaskom/seaborn/pull/782 but I guess it didn't cover the `hue != None` case.

**Comment by tino-michael** [comment]
it was
seaborn:          0.7.1-py36_0 

the default that came with ```conda install seaborn```

**Comment by mwaskom** [comment]
Does #1123 work for you?
