### ISSUE TITLE
wrong Y scale with pairgrid 

### ISSUE THREAD

**Issue by oneunreadmail** [mwaskom/seaborn#1124]
Following code scales Y axis with small values wrong in half of cases:
```
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.DataFrame(np.random.randn(100,4), columns=list('ABCD'))
df.A = df.A/1e6
df.B = df.B/1e3
df.D = df.D*1e3

sns.pairplot(df, vars=["A", "B", "C", "D"])
```
![image](https://cloud.githubusercontent.com/assets/18742441/23334247/06f81d44-fbac-11e6-877f-b06dac456f46.png)

`sns.PairGrid(df).map(plt.scatter)` will autoscale both axes wrong in every case for small values:
![image](https://cloud.githubusercontent.com/assets/18742441/23334240/f1e0444a-fbab-11e6-8125-27e7641b2593.png)

Probably this goes to plt.scatter, because `plt.scatter([-1e-6, 1e-6], [-1e-6, 1e-6])` won't autoscale right. 
![image](https://cloud.githubusercontent.com/assets/18742441/23334260/1cb05b24-fbac-11e6-8436-664fb98fa58d.png)

#862 is about exactly this, however, I'm still puzzled with half-normal pairplot behavior, seems it should return diag-symmetrical plots even with wrong autoscale in scatter function.

**Comment by mwaskom** [comment]
> I'm still puzzled with half-normal pairplot behavior, seems it should return diag-symmetrical plots even with wrong autoscale in scatter function.

This is probably because the histogram on the diag axes is setting the proper scaling of the x axes?

**Comment by oneunreadmail** [comment]
> Yeah, you're probably right. Does it happen inside plt as well? This means, it can't (shouldn't) be fixed in seaborn?

**Comment by mwaskom** [comment]
Yes, I don't understand exactly what the issue with autoscaling is, but this is a problem at the matplotlib layer.

**Comment by StevenLi-DS** [comment]
I have an issue with `distplot` and `kdeplot` in PairGrid in `0.9.0`
```python
import seaborn as sns
import pandas as pd
df = sns.load_dataset('tips')
sns.PairGrid(df.dropna())\
   .map_lower(sns.regplot, scatter_kws={'s': 0.5})\
   .map_upper(sns.kdeplot, shade=True)\
   .map_diag(sns.kdeplot)
```
![download](https://user-images.githubusercontent.com/33796896/53144755-86273500-356b-11e9-82ad-28511379c4ec.png)

But using `distplot` alone will produce 
```python
sns.distplot(df.total_bill)
```
![download](https://user-images.githubusercontent.com/33796896/53144771-9808d800-356b-11e9-9ade-b63ea9e88048.png)

Is there any way to solve this issue?

**Comment by thomascarreau** [comment]
You want

`sns.PairGrid(df.dropna(), diag_sharey=False)`

to solve the issue.

**Comment by naresh-patra** [comment]
> You want
> 
> `sns.PairGrid(df.dropna(), diag_sharey=False)`
> 
> to solve the issue.

Still this is not working.
The problem is y-axis of each diagnal plot is common to y-axis of same row.
Is there any way to make the diagnal's y-axis as probability density ?

**Comment by naresh-patra** [comment]
> I have an issue with `distplot` and `kdeplot` in PairGrid with `0.9.0`
> 
> ```python
> import seaborn as sns
> import pandas as pd
> df = sns.load_dataset('tips')
> sns.PairGrid(df.dropna())\
>    .map_lower(sns.regplot, scatter_kws={'s': 0.5})\
>    .map_upper(sns.kdeplot, shade=True)\
>    .map_diag(sns.kdeplot)
> ```
> 
> ![download](https://user-images.githubusercontent.com/33796896/53144755-86273500-356b-11e9-82ad-28511379c4ec.png)
> 
> But using `distplot` alone will produce
> 
> ```python
> sns.distplot(df.total_bill)
> ```
> 
> ![download](https://user-images.githubusercontent.com/33796896/53144771-9808d800-356b-11e9-9ade-b63ea9e88048.png)
> 
> Is there any way to solve this issue?

I am Facing same problem Bro. is there any way to control this (y-axis) in all diagnal plots? That means y-axis labels should probability density!

**Comment by naresh-patra** [comment]
> Yes, I don't understand exactly what the issue with autoscaling is, but this is a problem at the matplotlib layer.

I am facing same problem. Is there any way to control the y-axis of each diagnal plot of seaborn.pairgrid plot?

**Comment by lucky-lou** [comment]
`sns.PairGrid(df diag_sharey=False)`

worked for me

Thanks @thomascarreau
