### ISSUE TITLE
Mention Seaborn DOI / how to cite in documentation

### ISSUE THREAD

**Issue by fabianrost84** [mwaskom/seaborn#1127]
I was just looking for a way to cite Seaborn. I finally found the DOI in the README, but I was expecting it on http://seaborn.pydata.org/. Maybe you could add it there as well?

**Comment by zillurbmb51** [comment]
Hi fabian,
How can I find the readme file for doi to cite seaborn? Or can you share it here?
Thank in advance.
Best Regards
Zillur
