### ISSUE TITLE
Factorplot not working properly

### ISSUE THREAD

**Issue by napsternxg** [mwaskom/seaborn#1128]
I am using the sns factorplot and am not able to get the categories in the correct columns, when there is just one element per group. 

Code:
```python
import numpy as np
import pandas as pd
import seaborn as sns

size_n = 100
df_t = pd.DataFrame({
        "A": np.random.randint(0,4,size=(size_n,)),
        "B": np.random.randint(0,3,size=(size_n,)),
        "C": np.random.randn(size_n),
    })

g = sns.factorplot(y="C", x="A",
                   col="B",
                   color='k',
                   col_wrap=1,
                   size=5,
                   aspect=3,
                   share_y=False,
                   #kind="bar",
            data=df_t
                  )

print sns.__version__ # 0.7.1
print np.__version__ # 1.11.2
print pd.__version__ # 0.19.0
```

![image](https://cloud.githubusercontent.com/assets/112678/23442526/9f253900-fdee-11e6-9130-7513a0258b18.png)

Am I doing something wrong here?

**Comment by mwaskom** [comment]
There is some issue with `col_wrap=1` but figuring it out has always been a very low priority because the right way to make this plot anyway is to use `row`.
