### ISSUE TITLE
Feature request: support functions in FacetGrid.set_titles

### ISSUE THREAD

**Issue by tchajed** [mwaskom/seaborn#1130]
I use FacetGrids with either many columns or long categorical variable names, which causes the titles to become problematically long. For example, with many booleans, even using just "True" and "False" without the  column name is fairly long.

Currently [FacetGrid.set_titles](https://seaborn.pydata.org/generated/seaborn.FacetGrid.html#seaborn.FacetGrid) requires a template passed to string.format, which doesn't support functions within the template to change how values are printed (though a custom object could overwrite `__str__`). The feature that I'd like is that if a function is passed to `set_titles` it is passed the row and col values and names. The current implementation is essentially this with the function set to `string.format`.

I could implement this if there's interest.

**Comment by tchajed** [comment]
Here's an example of how I might use it (apologies for incomplete code):

`fg.set_titles(lambda col_var=None col_name=None: col_var if col_name else "!" + col_var)`

which for a boolean `parallel` would produce `parallel` and `!parallel` for `True` and `False`.

**Comment by bluecarrot16** [comment]
I would be interested in this feature!

**Comment by estaub** [comment]
I suspect it might be fine with folks if a normal custom string formatter (i.e., an object with a format method taking a {'col_var':} dict worked.  To make that play, I think you just have to put a guard around the `utils.to_utf8` calls.

**Comment by mwaskom** [comment]
Closing for now as I think it's easy enough to accomplish what you want to do here by looping over the `g.axes_dict` object and calling `ax.set_title`. It's two lines instead of one, but also one line with a complicated lambda is often not optimal either.
