### ISSUE TITLE
distplot() is not working under lastest numpy&statsmodels

### ISSUE THREAD

**Issue by airme** [mwaskom/seaborn#1131]
when numpy is 1.11.3, distplot() is not working,
but under numpy 1.11.1, it's working with warning:

> Woking\path\lib\site-packages\statsmodels\nonparametric\kdetools.py:20: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
> y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j

**Comment by mwaskom** [comment]
Duplicate of https://github.com/mwaskom/seaborn/issues/1103; this is fixed in statsmodels I believe.
