### ISSUE TITLE
Downloading intersphinx inventory with Sphinx is blocked

### ISSUE THREAD

**Issue by janmedlock** [mwaskom/seaborn#1133]
My apologies if this has been covered elsewhere: I didn't find any other relevant bugs (although I did see the bugs on moving the domain) or stackoverflow discussions.

Adding the intersphinx mapping `{'seaborn': ('https://seaborn.pydata.org/', None)}` gives the error
```
WARNING: intersphinx inventory 'https://seaborn.pydata.org/objects.inv' not fetchable due to <class 'urllib.error.HTTPError'>: HTTP Error 403: Forbidden
```
The URL [https://seaborn.pydata.org/objects.inv](https://seaborn.pydata.org/objects.inv) works fine with chrome, with wget, and with curl.  ('https' -> 'http' makes no difference in either Sphinx or the other tools.)

But, using Python's urllib gives the 403 error.  Changing the User-agent string in urllib to 'Mozilla/5.0' makes the download work.  Changing the User-agent string in wget to 'Python-urllib/3.5' (or 'Python-urllib' or 'Python-urllib{}'.format(anything)) gives the 403 error.  (Changing the url to 'https://seaborn.pydata.org/' with the urllib User-agent also gives the 403 error.)  So it seems there's a webserver policy blocking urllib.  This seems to be seaborn.pydata.org specific, as I have no problems with pandas.pydata.org.

I'd appreciate the policy being lifted so intersphinx works without having to hack the User-agent string.

Thanks.

**Comment by mwaskom** [comment]
I don't control the pydata.org server (and actually the docs are technically hosted at seaborn.github.io) so unfortunately I have no idea what to change to help you here.

**Comment by mwaskom** [comment]
All of the files in the site are here: https://github.com/seaborn/seaborn.github.io

**Comment by janmedlock** [comment]
Trying http://seaborn.github.io/ gives a redirect (301) to http://seaborn.pydata.org/:
```
$ wget http://seaborn.github.io/
--2017-03-07 14:05:06--  http://seaborn.github.io/
Resolving seaborn.github.io (seaborn.github.io)... 151.101.52.133
Connecting to seaborn.github.io (seaborn.github.io)|151.101.52.133|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://seaborn.pydata.org/ [following]
--2017-03-07 14:05:06--  http://seaborn.pydata.org/
Resolving seaborn.pydata.org (seaborn.pydata.org)... 104.24.104.183, 104.24.105.183, 2400:cb00:2048:1::6818:69b7, ...
Connecting to seaborn.pydata.org (seaborn.pydata.org)|104.24.104.183|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html              [ <=>                ]  10.20K  --.-KB/s    in 0s      

2017-03-07 14:05:06 (45.1 MB/s) - ‘index.html’ saved [10445]

```

https://github.com/seaborn/seaborn.github.io/raw/master/ works.

Thanks for the help.  I'd encourage you to see if anyone suggests a fix, because that github URL is not at all obvious compared to https://seaborn.pydata.org/, and the objects.inv file is actually there, just oddly blocked.
