### ISSUE TITLE
[0.7.1] - VisibleDeprecationWarning when plotting distplot as per tutorial

### ISSUE THREAD

**Issue by anshbansal** [mwaskom/seaborn#1135]
I was going through http://seaborn.pydata.org/tutorial/distributions.html and ran upto the following in a terminal

```
x = np.random.normal(size=100)
sns.distplot(x);
```

Then I got

```
/home/aseem/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kdetools.py:20: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j
<matplotlib.axes._subplots.AxesSubplot object at 0x7fe67de506d8>
```

My environment
* I have anaconda 4.3.0 installed which has seaborn 0.7.1
* Ubuntu 14.04 64-bit

**Comment by mwaskom** [comment]
As you can see from the warning text, the warning is being triggered by statmodels code that seaborn calls. Nothing to do on the seaborn side (though I am pretty sure that code has been updated in the latest statsmodels).

**Comment by anshbansal** [comment]
@mwaskom I thought that it was seaborn calling it with incorrect parameters. But if that is not the case then you are right nothing to be done here.
