### ISSUE TITLE
plotting a dataframe with no rows should throw a specific ValueError

### ISSUE THREAD

**Issue by mojones** [mwaskom/seaborn#1136]
I've been teaching pandas/seaborn to novices this week and noticed the following quite a few times - minimal example:

```python
import pandas as pd
import seaborn as sns

df = pd.DataFrame({
    'fruit' : ['apple', 'apple', 'banana', 'banana'], 
    'number' : [5,6,7,8]
})

# show distribution of numbers for apple
sns.distplot(df[df['fruit'] == 'apple']['number'])

# accidentally make a typo
sns.distplot(df[df['fruit'] == 'aple']['number'])

ZeroDivisionError                         Traceback (most recent call last)
...
```

Accidentally filtering a dataframe to produce no rows (either via a typo as above or something more complex) leads to a `ZeroDivisionError`, and the hapless student starts digging through the dataframe to find zero values or missing data. Would it be possible to check the number of rows in the input dataframe before starting the plot, and raise a `ValueError` with a more helpful message?

**Comment by mwaskom** [comment]
Closed in #1267
