### ISSUE TITLE
Default palette for boxplot should be categorical not sequential

### ISSUE THREAD

**Issue by mojones** [mwaskom/seaborn#1138]
Making a boxplot with default values:

```python
import random
df = pd.DataFrame(
{
    'foo' : [random.choice('abcdefghij') for _ in range(100)],
    'bar' : [random.random() for _ in range(100)]
}
)
df

sns.boxplot(
    data=df,
    x='foo',
    y='bar'
)
```

results in a plot with a sequential palette:

![selection_013](https://cloud.githubusercontent.com/assets/893512/24049892/2cfee8aa-0b25-11e7-8f1b-39d567309a69.png)

I think that we expect box plots to contain categorical data, so it makes more sense to pick a categorical palette by default.

**Comment by mwaskom** [comment]
I don't agree.
