### ISSUE TITLE
Categorical plots do not align pandas Series on index

### ISSUE THREAD

**Issue by deto** [mwaskom/seaborn#1139]
Today I encountered a bit of behavior that was unexpected to me in the box plot.  If I input Series to x, y, and hue, I would expect that the order of elements should not matter provided the series can all be aligned with the same index. 

This seems to be true with just x and y.  But when involving hue, the ordering seems to matter.

**Seaborn Version: 0.7.1**

Some code to reproduce:
```python
# Define variables
index =         ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8']
x = pd.Series(   ['A',  'A',  'A',  'A',  'B',  'B',  'B',  'B'], index=index)
y = pd.Series(   [  1,    2,    5,    6,   10,   11,   15,   16], index=index)
hue = pd.Series( ['C',  'C',  'D',  'D',  'C',  'C',  'D',  'D'], index=index)

# Original Plot
plt.figure()
sns.boxplot(x=x, y=y, hue=hue)
```
![image](https://cloud.githubusercontent.com/assets/551879/24084490/41fa11b0-0ca8-11e7-9228-192fe3b0cefd.png)

```python
# Scramble x
plt.figure()
x_s = x[['x3', 'x7', 'x1', 'x4', 'x5', 'x6', 'x2', 'x8']]
sns.boxplot(x=x_s, y=y, hue=hue)
```
![image](https://cloud.githubusercontent.com/assets/551879/24084496/5bd85678-0ca8-11e7-98fe-a5f495586352.png)

If `x` is out of order with respect to `y` and `hue`, it's aligned as expected.

```python
# Scramble y
plt.figure()
y_s = y[['x3', 'x7', 'x1', 'x4', 'x5', 'x6', 'x2', 'x8']]
sns.boxplot(x=x, y=y_s, hue=hue)
```
![image](https://cloud.githubusercontent.com/assets/551879/24084498/6407de72-0ca8-11e7-8ef5-181905111047.png)

However if `y` and `hue` aren't in the same order, the indices are not used correctly to align.

```python
# Scramble hue
plt.figure()
hue_s = hue[['x3', 'x7', 'x1', 'x4', 'x5', 'x6', 'x2', 'x8']]
sns.boxplot(x=x, y=y, hue=hue_s)
```
![image](https://cloud.githubusercontent.com/assets/551879/24084499/732615b8-0ca8-11e7-8962-21c56cf93968.png)

Here we see the same thing by scrambling the order of `hue`

**Comment by mwaskom** [comment]
That is works at all is not entirely intentional. I suppose I can see why you would expect it to, although I've always personally found pandas row index alignment behavior more surprising than helpful and try to write code that works with positional alignment of vectors. It would be nice to support, although doing so would involve adding quite a bit more complexity to what is already a rather complex amount of input processing.

**Comment by deto** [comment]
Yes - it looks like a whole bunch of different input scenarios are handled
in the _CategoricalPlotter constructor!

However, I believe this would only require modification in the specific
case contained in lines 193-224 of categorical.py - and the _group_longform
function which looks like it's only called in that area as well.  Looks
like the main issue is that when 'y' is grouped by 'x' - the result is cast
to a numpy array and so all indexing is lost before hue is grouped in.

Would you be amenable to a pull request that addresses this? I feel like,
as I did, many other people would assume that indices are being used when
provided.  My use case for this is that often I'll load numeric data from
one matrix, (gene expression data), and then load meta-data for each of
columns (samples) from another table.  It's nice to be able to do:

```python

sns.boxplot(x=meta.Genotype, y=tpm.loc['SomeGene'], hue=meta.Stimulus)

```

without having to worry about whether the things are aligned.  Alternately,
I know I could always join them into a dataframe first and use the data
argument, but this would save a step.

**Comment by mwaskom** [comment]
I am not opposed to supporting this but I am wary of claims that it is going to be a simple change in one function. There have been problems in the past when seemingly simple changes have had surprising effects especially when contributors have not carefully spent time understanding how everything works (ultimately a sign that the original codebase itself is too complex/poorly modularized, but still that's where we are).  I could be persuaded to merge a simple change, but there would be a high bar for demonstrating that it does not break anything. Unfortunately I do not have much bandwidth for providing guidance.
