### ISSUE TITLE
saving regplot with savefig cuts off part of the saved plot

### ISSUE THREAD

**Issue by aweller** [mwaskom/seaborn#114]
This code:

sns.regplot("x2, "y", df)
savefig("title.png", dpi=300)

creates a great inline plot in an ipython notebook, but the png saved to disk has the wrong size, which cutts off the left side of the graph (i.e. the yaxis):

![deamination_cpg_ratio_total_snps](https://f.cloud.github.com/assets/3388972/2269579/657a1244-9edc-11e3-97d3-2a2dbaae9afd.png)

I am using Enthought Canopy on Win7, seaborn is ("seaborn-0.2.0-py2.7").

**Comment by Teodormz** [comment]
Doesn't work for my complex graph:
g = sns.FacetGrid(df, row='a', col='b', sharey = False, margin_titles=True)
bins = np.linspace(0, 1, 50)
g.map(plt.hist, 'c', bins=bins, lw=0.5, alpha=0.6)
I have a grid of 11x11 graphs, and the description of the rows on the right of the graphs doesn't sho up when I do savefig

**Comment by farahanams** [comment]
is this  bug fixed?

**Comment by MarineF** [comment]
I experiment the same issue when rotating the x tick labels, the labels disappear partially and the x label disappears completely. Any solution?

**Comment by ca-scribner** [comment]
This still exists for me as well.  #470 suggests using bbox_inches='tight', which did fix the problem for me as well.
