### ISSUE TITLE
Addition of new options to palplot()

### ISSUE THREAD

**Issue by apcamargo** [mwaskom/seaborn#1141]
The addition of a 'title' and 'titlesize' arguments makes it possible to add a title to a palette plotted with palplot() and change it's size.

**Comment by mwaskom** [comment]
You can change matplotlib figure sizes and add titles after plotting. I don't think this needs to be a parameter to palplot, which is really mostly meant for documentation anyway.

**Comment by BeyondTheProof** [comment]
@apcamargo You may want to just use the heatmap function, as it's much more versatile. I also had the same issue, except I wanted to play with its size, but couldn't figure out how.

**Comment by jolespin** [comment]
Can palplot return that matplotlib ax?
