### ISSUE TITLE
Add bootstrapping to scipy.stats

### ISSUE THREAD

**Issue by beojan** [mwaskom/seaborn#1142]
Is there any possibility of adding the bootstrapping code from seaborn into scipy.stats? There used to be a scikits-bootstrap, but this hasn't been maintained for a while. It also generates all the resamples at once, which causes memory issues.

**Comment by mwaskom** [comment]
I'm not sure why scipy core never incorporated the scikits-bootstrap code, but presumably you'd at least need someone committed to maintaining the code in scipy. I'm not opposed to my code being used in scipy (it's BSD licensed so anyone should feel free), but I'm not going to take on that responsibility.

The seaborn bootstrapping code is also pretty focused and lightweight and not really tested for how it scales to datasets beyond the size that matplotlib does poorly with. I imagine that scipy core would want more flexibility and performance in any code that becomes part of the core library.

Anyway, point is, I'm not going to stop anyone from incorporating the seaborn bootstrapping code into scipy, but I won't be taking the initiative to do so.
