### ISSUE TITLE
No lines separating bins in distplot

### ISSUE THREAD

**Issue by miguelcorrea** [mwaskom/seaborn#1143]
For some reason, the lines that would normally separate the bins in the histogram do not appear anymore. The histogram appears as a continuous block instead. Furthermore, I've had this issue with different machines.

The following code is enough to show the problem:
`
x = np.random.randn(1000);
sns.distplot(x)
`
![hist_example](https://cloud.githubusercontent.com/assets/11046487/24259480/4a501afc-0ff1-11e7-99a5-4ebb118d6900.png)

I am running matplotlib 2.0.0 and seaborn 0.7.1 .

**Comment by mwaskom** [comment]
This is a result of default rcParams changes in matplotlib 2.0.0. I don't know which one off the top of my head, but probably something about patch edge colors.

**Comment by miguelcorrea** [comment]
Thanks, that was exactly it!

**Comment by arisolt** [comment]
So what is the required kwarg to bring them back? :)
