### ISSUE TITLE
Bland-Altmann plot

### ISSUE THREAD

**Issue by puntopasta** [mwaskom/seaborn#1148]
As one of the most used statistical visualizations in the medical field, it can aid a lot when communicating results with a clinical stakeholder. I feel that for that reason it deserves an implementation in seaborn. 

[A good implementation in Matlab](https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/45049/versions/8/screenshot.png) 

For background on the methodology:
[Altman, Douglas G., and J. Martin Bland. "Measurement in medicine: the analysis of method comparison studies." The statistician (1983): 307-317.](https://pdfs.semanticscholar.org/0299/29987c1321e6880234bf0492689a7a379e38.pdf)

Or try the [wikipedia page](https://en.wikipedia.org/wiki/Bland%E2%80%93Altman_plot)

**Comment by mwaskom** [comment]
I don't think this is a good fit for seaborn, as I don't see any way to implement the plot within the current seaborn API. It seems best fit within a more specialized package.

**Comment by soupault** [comment]
Hello @mwaskom . Would you reconsider adding this feature? I agree with @puntopasta that it is a quite common tool in clinical research. I think it would be really nice to have B-A plotting provided by `seaborn` as the other implementations (directly from `statsmodels`, https://github.com/raphaelvallat/pingouin) are not flexible enough in terms of configuration capabilities.
If you are interested, I can make a PR.
