### ISSUE TITLE
FacetGrid unable to deal with empty cells in 3d-confusion matrix

### ISSUE THREAD

**Issue by kthneighbor** [mwaskom/seaborn#1151]
As shown in the screenshot, FacetGrid erroneously moves countplot's columns towards the leftmost position on the subplot's x-axis whenever any of countplot's lowest-value columns are empty. As the (correct) sns.factorplot right above the faulty FacetGrid illustrates, this error occurs for the subplots t_s_len = 1 and t_s_len = 2 (where no data point has a yr_diff value of -1).

![screenshot from 2017-04-05 17-19-48](https://cloud.githubusercontent.com/assets/1872375/24712781/19fadb66-1a24-11e7-9341-9be31d03e750.png)

**Comment by mwaskom** [comment]
You need to use `order` or Categorical variables (but I would use `factorplot` anyway).

**Comment by Unode** [comment]
@mwaskom Could you perhaps add some documentation or a warning to the code on this usage? It may not be obvious to a newcomer that this behavior exists and they will be as confused/surprised as @kthneighbor and me were.

The documentation for `FacetGrid` also provides [examples](http://seaborn.pydata.org/generated/seaborn.FacetGrid.html) which make use of `sns.boxplot`. This was how I ended up hitting this behavior. The same is true for the [grid guide](http://seaborn.pydata.org/tutorial/axis_grids.html).
As is other users will likely bump into this same problem.

**Comment by mwaskom** [comment]
http://seaborn.pydata.org/tutorial/categorical.html#drawing-multi-panel-categorical-plots

> It is important to note that you could also make this plot by using boxplot() and FacetGrid directly. However, special care must be taken to ensure that the order of the categorical variables is enforced in each facet, either by using data with a Categorical datatype or by passing order and hue_order.
