### ISSUE TITLE
barplot. Parameter "orient" doesn't work.

### ISSUE THREAD

**Issue by victordek** [mwaskom/seaborn#1155]
I tried to use **orient** param in **barplot** and faced an error:

> unsupported operand type(s) for /: 'str' and 'int'

An example code to reproduce the error:
```
import seaborn as sns
sns.barplot (x=[1, 2, 3, 4, 5, 6, 7], y=[c for c in 'qwertyu'], orient="v")
```

I tried to use integer for **orient** and code worked without any error nor any affect by **orient** param.

seaborn 0.7.1
matplotlib 2.0.0
numpy 1.12.1

**Comment by victordek** [comment]
Full error traceback:
(numpy 1.12.1)

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-1-ac20dac11408> in <module>()
>       1 import seaborn as sns
> ----> 2 sns.barplot (x=[1, 2, 3, 4, 5, 6, 7], y=[c for c in 'qwertyu'], orient="v")
> 
> /home/victordek/anaconda3/lib/python3.6/site-packages/seaborn/categorical.py in barplot(x, y, hue, data, order, hue_order, estimator, ci, n_boot, units, orient, color, palette, saturation, errcolor, errwidth, capsize, ax, **kwargs)
>    2897                           estimator, ci, n_boot, units,
>    2898                           orient, color, palette, saturation,
> -> 2899                           errcolor, errwidth, capsize)
>    2900 
>    2901     if ax is None:
> 
> /home/victordek/anaconda3/lib/python3.6/site-packages/seaborn/categorical.py in __init__(self, x, y, hue, data, order, hue_order, estimator, ci, n_boot, units, orient, color, palette, saturation, errcolor, errwidth, capsize)
>    1543                                  order, hue_order, units)
>    1544         self.establish_colors(color, palette, saturation)
> -> 1545         self.estimate_statistic(estimator, ci, n_boot)
>    1546 
>    1547         self.errcolor = errcolor
> 
> /home/victordek/anaconda3/lib/python3.6/site-packages/seaborn/categorical.py in estimate_statistic(self, estimator, ci, n_boot)
>    1438                     statistic.append(np.nan)
>    1439                 else:
> -> 1440                     statistic.append(estimator(stat_data))
>    1441 
>    1442                 # Get a confidence interval for this estimate
> 
> /home/victordek/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py in mean(a, axis, dtype, out, keepdims)
>    2887 
>    2888     return _methods._mean(a, axis=axis, dtype=dtype,
> -> 2889                           out=out, **kwargs)
>    2890 
>    2891 
> 
> /home/victordek/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py in _mean(a, axis, dtype, out, keepdims)
>      80             ret = ret.dtype.type(ret / rcount)
>      81     else:
> ---> 82         ret = ret / rcount
>      83 
>      84     return ret
> 
> TypeError: unsupported operand type(s) for /: 'str' and 'int'

**Comment by mwaskom** [comment]
You can't make a vertically oriented plot if the y variable is categorical.
