### ISSUE TITLE
Datetime in tsplot index (with suggestion for solution)

### ISSUE THREAD

**Issue by siomekg** [mwaskom/seaborn#1164]
This issue has appeared several times, both in this issues section and in StackOverflow.
All date information is lost, and people go through hullahops with the formatting of ticks in the x axis to fix it up.

I believe the problem is in timeseries.py line 280:
        x = df_c.columns.values.astype(np.float) 

If there is no coercion to np.float, the datetime64 will handle all the magic in the underlying matplotlib routines,  and it does not affect at all the bootstrapping for confidence regions, or central estimation.   

I could not see why the cast to float is important, but at this point I just have a narrow vision to my particular application.  In any case if there are cases where casting to float is, we can test  if the time column is a datetime:
    if df2.columns.values.dtype.name == 'datetime64[ns]': #  or check the beg of the str to 'datetime'?
        x = df_c.columns.values
    else:
        x = df_c.columns.values.astype(np.float) 

It is a bit tricky for me here in my work environment to change, test, and patch,  but I wrote a smaller purpose method and taking of the astype(np.float) did the trick to me. 

Thanks!
Siome

**Comment by phobson** [comment]
suggest closing per https://github.com/mwaskom/seaborn/issues/1078#issuecomment-313790934

**Comment by mwaskom** [comment]
Good point. Closing due to tsplot deprecation. Also because this is not so straightforward and wouldn't work for all of the error styles (particularly the bootstrap KDE) which is the main reason seemingly "simple" solutions to handling datetimes haven't been implemented.
