### ISSUE TITLE
Jitter `violinplot` inner points by drawing offset from the estimated density

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#117]
This seems like an obvious idea and not hard to implement.

**Comment by mwaskom** [comment]
I couldn't quite figure out a way to get this to work, but I'm gonna close because `stripplot` in #410 and forthcoming `swarmplot` will get very close.

**Comment by ryanpeach** [comment]
stripplot has the issue where it doesn't overlay perfectly if you use x, y, AND hue all at once.
