### ISSUE TITLE
Problem in color ordering of tab10 palette

### ISSUE THREAD

**Issue by lincolnfrias** [mwaskom/seaborn#1170]
When trying to use the tab10 palette from matplotlib, the default color order is not always respected.  

    import matplotlib.pyplot as plt
    import seaborn as sns
    
    sns.palplot(sns.color_palette("tab10")
![image](https://cloud.githubusercontent.com/assets/11890487/25761654/f2ca6958-31b1-11e7-86c2-087183e78fc4.png)

But it gets the order right with ten colors.
    
    sns.palplot(sns.color_palette("tab10", n_colors=10))

![image](https://cloud.githubusercontent.com/assets/11890487/25761711/305b387e-31b2-11e7-9554-ec9b00755ad1.png)

Calling the colormap using matplotlib also gets the original order.

    x = plt.cm.get_cmap('tab10')
    sns.palplot(x.colors)

![image](https://cloud.githubusercontent.com/assets/11890487/25761744/49c5298c-31b2-11e7-8b37-aca41598246e.png)

Is this a normal behavior?

**Comment by mwaskom** [comment]
It's normal in the sense that seaborn has to special-case the qualitative colormaps to index them properly and the `tab10` palette was never added to the list of special cases.

**Comment by lincolnfrias** [comment]
Thanks for clarifying this @mwaskom. 
So, I am closing this issue.

**Comment by mwaskom** [comment]
That doesn't mean it shouldn't be added! It just hasn't been yet.
