### ISSUE TITLE
swarmplot silently overlaps points when overloaded

### ISSUE THREAD

**Issue by jpeacock29** [mwaskom/seaborn#1175]
When too many points are provided to swarmplot, it will silently overlap some of them without making this evident to the user. For example,

    seaborn.swarmplot(100*[4] + 75*[3] + 50*[2] + 25*[1] + 10*[0] + 1*[-1])

should produce a triangular plot, but the values with too many points get overlapped and effectively cut off. It's difficult to see the overlapping has taken place and there's no warning. The documentation notes swarmplots "does not scale as well to large numbers of observations [...] in terms of the ability to show all the points," but I don't think this is sufficient. This should fail or at least warn the users rather than showing a deceptive graph.

MPL 2.01; Seaborn 0.7.1

**Comment by mwaskom** [comment]
I certainly don't think it should fail, which would be a giant pain, and I do not like to use warnings to convey this kind of information.

In my opinion, it's the user's responsibility to understand their data and whether the kind of plot they are making is appropriate.

**Comment by jpeacock29** [comment]
In the current configuration it is difficult to even know the plot was inappropriate because the overlapping points are barely visible. This seems particularly problematic given that a swarmplot is explicitly designed to prevent overlaps. How's one to know exactly how many points can fit on a particular plot? I can understand not throwing an error, but why are you opposed to a warning?
