### ISSUE TITLE
Swarmplot is slow. 

### ISSUE THREAD

**Issue by zfrenchee** [mwaskom/seaborn#1176]
I'm trying to plot about 4000 points, takes about 20 minutes on a macbook pro. Violin plot on the same data takes no perceptible time. Why is swarmplot slow?

**Comment by mwaskom** [comment]
Because swarmplot and violinplot are ... not doing the same thing?

**Comment by zfrenchee** [comment]
@mwaskom Is there a reason swarmplot *should* be so slow?

**Comment by mwaskom** [comment]
The second line of the [documentation](http://seaborn.pydata.org/generated/seaborn.swarmplot.html) says

> This function is similar to stripplot(), but the points are adjusted (only along the categorical axis) so that they don’t overlap. This gives a better representation of the distribution of values, although it does not scale as well to large numbers of observations (both in terms of the ability to show all the points and in terms of the computation needed to arrange them).

**Comment by alegolas79** [comment]
I know this is an post but @mwaskom  you have to consider few things in support of @zfrenchee question.
I swarmplot ~4,000 rows: it takes 30 seconds -> | 1/4 [00:14<00:44, 14.86s/it]
i swarmplot ~10,000 rows: it takes 22 minutes.

**Comment by mmagnuski** [comment]
@alegolas79 If you really have to plot thousands of points with swarmplot you can take a look at: [`_SwarmPlotter`](https://github.com/mwaskom/seaborn/blob/fe172c44777f87159e9e2b00e919bbd055d6f696/seaborn/categorical.py#L1209). You can try speeding it up for example by trying to use numba (there are some normal python loops with lists and append in _SwarmPlotter - something that numba should be good in optimizing). One you are successful you may create a separate repo/gist demonstrating the speed differences. Even if this is not accepted in seaborn (would require soft dependency on numba, which would increase maintenance load) other visitors to this issue would benefit.

**Comment by rajgurubhosale** [comment]
what if there is too much points can we assume 1 point for lets assume in one case 50 ?  then plot them will this is approch ? can we make it fast then?
