### ISSUE TITLE
clustermap should not put None as label for color series

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#1177]
```python
x = pd.DataFrame(np.random.randn(10, 10))
c = pd.Series(np.linspace(0, 1, 10).astype(str))
sns.clustermap(x, col_colors=c)
```

![image](https://cloud.githubusercontent.com/assets/315810/25953718/2c167ce0-3632-11e7-9e12-3f4ba12f93c9.png)

@jrderuiter I think that a Series with a label of `None` should not have a label, do you agree?

**Comment by jrderuiter** [comment]
I agree, the none is not really informative.
