### ISSUE TITLE
kdeplot doesn't coerce list into numpy array

### ISSUE THREAD

**Issue by pyeguy** [mwaskom/seaborn#1186]
if you pass a list of data to `kdeplot` you get

```python
    575         ax = plt.gca()
    576 
--> 577     data = data.astype(np.float64)
    578     if data2 is not None:
    579         data2 = data2.astype(np.float64)

AttributeError: 'list' object has no attribute 'astype'
```
seems like it should try to call `np.array(data)` and check that `data.ndim == 1`

**Comment by mmagnuski** [comment]
Probably better to use `np.asarray(data)` so that inputs that are already arrays are not copied.

**Comment by mwaskom** [comment]
> seems like it should try to call np.array(data) and check that data.ndim == 1

Maybe the function should accept lists but if you read farther in the code (as you should) you will discover that it is more complicated than that.

**Comment by pyeguy** [comment]
a little more complicated.. submitted PR  #1188 to add list support
