### ISSUE TITLE
Seaborn appears to set the marker edge width to below 0.1 in matplotlib

### ISSUE THREAD

**Issue by AshleySetter** [mwaskom/seaborn#1193]
When I import seaborn into a python session it appears to reset the default marker edge width to below 0.1 such that non-filled markers e.g. 'x' do not show up.

If I do the following:

```
import numpy as np
import matplotlib.pyplot as plt
plt.plot(np.arange(0, 100), np.random.rand(100), 'x')
plt.show()
```
I get the expected plot:

![plotwithmatplotlib](https://cloud.githubusercontent.com/assets/14869658/26631987/a90d3b7a-4605-11e7-8f9c-8a39b7a32944.png)

However If i import seaborn in the same session:
```
import numpy as np
import matplotlib.pyplot as plt
import seaborn
plt.plot(np.arange(0, 100), np.random.rand(100), 'x')
plt.show()
```
I get the following:

![plotwithseaborn](https://cloud.githubusercontent.com/assets/14869658/26632033/e032d13c-4605-11e7-85d7-ad7252e6724d.png)

**Comment by mwaskom** [comment]
Yes... https://github.com/mwaskom/seaborn/blob/master/seaborn/rcmod.py#L363

**Comment by AshleySetter** [comment]
Is there a particular reason it is set to 0?

**Comment by mwaskom** [comment]
As with any other aspect of the default styles, the answer is because that was my aesthetic preference.

**Comment by AshleySetter** [comment]
Ahh, fair enough, I just thought it was an odd choice as it breaks the plotting code of anyone using non-filled markers with matplotlib's default marker edge width when they import seaborn. I know a few people have been effected by this and turned off from using seaborn by it. If a value of 0.15 was used by default, for example, then non-filled markers would still show up when plotted - meaning people can still see their plots when seaborn is imported - and it wouldn't effect the default appearance of filled markers too much. 

But I realise the package author's preference takes precedence in this case. Maybe a comment in the documentation would help people solve this issue when it occurs? I've helped several people with this issue so it seems worthy of comment.

**Comment by mwaskom** [comment]
Yes, if you search this repo, you will find ample discussion of the issue.

**Comment by mwaskom** [comment]
> Maybe a comment in the documentation would help people solve this issue when it occurs?

http://seaborn.pydata.org/installing.html?highlight=markeredgewidth#known-issues

Just because something is written in the documentation doesn't mean everyone is going to read it ...

**Comment by AshleySetter** [comment]
True, it's very clearly stated in the documentation as you say. I didn't come across that. It's a shame that that the documentation isn't better indexed by search engines like google.

**Comment by mwaskom** [comment]
http://seaborn.pydata.org/search.html?q=markers+invisible&check_keywords=yes&area=default
