### ISSUE TITLE
Horizontal barplot fails if y variable can be coerced to numeric

### ISSUE THREAD

**Issue by gkunter** [mwaskom/seaborn#1197]
If the variable on the vertical axis can be coerced to numeric values, `barplot()` fails with a `TypeError`. If the same data frame is plotted with the same variable on the horizontal axis, the error doesn't occur. The error also does not occur if the variable is changed so that it cannot be coerced to numeric values any more. 

**Version information**: Seaborn 0.7.1, Pandas 0.20.2, Numpy 1.13.0
 
**Reproducible test**:

```
df = pd.DataFrame({"Date": ["0000", "2000", "2005", "2010"], 
                   "Frequency": pd.np.random.uniform(0, 10, 4).astype(int)})

# Vertical barplot works:
sns.barplot(x="Date", y="Frequency", data=df)

# Horizontal barplot fails:
sns.barplot(x="Frequency", y="Date", data=df)
```

This fails when calling the estimator in `estimate_statistic()`

```
/home/xxx/anaconda3/lib/python3.5/site-packages/seaborn/categorical.py in estimate_statistic(self, estimator, ci, n_boot)
   1438                     statistic.append(np.nan)
   1439                 else:
-> 1440                     statistic.append(estimator(stat_data)
```
>  TypeError: unsupported operand type(s) for /: 'str' and 'int'

This issue appears to be caused by `_CategoricalPlotter.infer_orient()`, which returns the same orientation 'v' with both variable orders:

```
sns.categorical._CategoricalPlotter().infer_orient(x=df.Date, y=df.Frequency)
'v'

sns.categorical._CategoricalPlotter().infer_orient(x=df.Frequency, y=df.Date)
'v'
```

Apparently, the `y` variable is interpreted as a numeric dtype. Consequently, `barplot()` calls the estimator on this variable even though it contains categorical data.

If the variable on the y axis is modified so that it's clearly categorical, the error doesn't occur:
```
df2 = pd.DataFrame({"Date": ["X_0000", "2000", "2005", "2010"], 
                   "Frequency": pd.np.random.uniform(0, 10, 4).astype(int)})

# Vertical barplot works:
sns.barplot(x="Date", y="Frequency", data=df2)

# Horizontal barplot works:
sns.barplot(x="Frequency", y="Date", data=df2)

sns.categorical._CategoricalPlotter().infer_orient(x=df2.Date, y=df2.Frequency)
'v'

sns.categorical._CategoricalPlotter().infer_orient(x=df2.Frequency, y=df2.Date)
'h'
```

**Comment by mwaskom** [comment]
It's not that unusual to get a column in a DataFrame that has an `object` dtype but is actually full of numbers. Your case is a little weird I guess in that you have numbers but they are actually stored as strings, not numerics in object blocks. You can force horizontal orientation with `orient="h"`.

**Comment by gkunter** [comment]
In the database that produces these data frames, the values in the `Date` series are actually a shorthand notation for '2000–2004', '2005–2009', '2010–2014' ('0000' signifies a missing value), so the `object` dtype  seems to be more appropriate than a numeric dtype after all. 

But thanks for the quick response – the `orient="h"` argument fixes the error in my program. I just wasn't expecting that horizontal and vertical barplots differ in how they interpret the variables that are submitted as arguments.

**Comment by mwaskom** [comment]
I expect that this is a rare edge case and I worry about any unintended consequences of making the automatic orientation detection more complicated so, given that it's possible to work around it by explicitly specifying the orientation, I'm going to close without changing anything.

**Comment by bweigel** [comment]
Ran into the same problem with a y-variable that was a german zip-code (they can have a leading 0, which makes numeric coercion problematic).  Thanks for the `orient="h"` tip. However, I noticed that my ordering changed and I had to make it explicit again with `order=...`.
