### ISSUE TITLE
UnboundLocalError: local variable 'x' referenced before assignment

### ISSUE THREAD

**Issue by srodriguex** [mwaskom/seaborn#1198]
I saw that [issue 957](https://github.com/mwaskom/seaborn/issues/957) is about the same error but it's closed. The last comment in that issue says it's fixed in dev, but not in 0.7.1.

Well, I'm trying to use [hypertools](http://hypertools.readthedocs.io/) library, which uses `seaborn` internally. I upgrade the `seaborn` version to 0.8.dev, and reindex the `pandas` dataframe passed to the function `hypertools.tools.describe_pca()` but I've got the same error:

```
/Users/<username>/.virtualenvs/py3/lib/python3.5/site-packages/seaborn/timeseries.py in tsplot(data, time, unit, condition, value, err_style, ci, interpolate, color, estimator, n_boot, err_palette, err_kws, legend, ax, **kwargs)
    329 
    330     # Pad the sides of the plot only when not interpolating
--> 331     ax.set_xlim(x.min(), x.max())
    332     x_diff = x[1] - x[0]
    333     if not interpolate:

UnboundLocalError: local variable 'x' referenced before assignment

```
For your information, I'm using `seaborn` version 0.8.dev, `pandas` 0.19.1 and `numpy` 1.13.0.

**Comment by mwaskom** [comment]
The example in #957 works for me. Do you have a reproducible example?

**Comment by srodriguex** [comment]
Yes.

Please, refer to [this link](https://gist.github.com/srodriguex/520f7c816b9a80d516999d6dc846d142) to open a that Notebook that demonstrates the problem. The Notebook contains an example from `hypertools` library that works fine with some data, and my use with my data that generates the error.

Looking around it seems the variable `x` in line 331 of timeseries.py file really looks referenced before an assignment. The assign of `x` variable occurs in line 280, inside a for.

Thanks for your support!

**Comment by mwaskom** [comment]
Can you try to come up with an example that doesn't require me to install another package?

**Comment by srodriguex** [comment]
Fortunately no. I've been using seaborn a long time and this is the first time I've got this kind of error. I see it may not be seaborn faults by itself, but the the other library, hypertools. The latter may be not setting up the variables properly in order to execute the `for` loop in line 277 of timeseries.py file, thus not assigning the `x` variable and getting the Python error.
