### ISSUE TITLE
can not auto scale x-axis and y-axis when ploting two figure in one rwo

### ISSUE THREAD

**Issue by 176coding** [mwaskom/seaborn#1199]
just like the image showing: the second figure can not auto scale, but when I just plot the second figure, it works.

![_20170609194243](https://user-images.githubusercontent.com/9864284/26974041-20602b86-4d4c-11e7-8b44-7c09109d9326.png)

![_20170609194559](https://user-images.githubusercontent.com/9864284/26974264-16393d72-4d4d-11e7-855e-fb89db79fca0.png)

**Comment by mwaskom** [comment]
Please create a reproducible example of the problem, but I suspect this is an issue at the matplotlib layer.

**Comment by mwaskom** [comment]
Closing for lack of reproducible example.
