### ISSUE TITLE
The function "distplot" maybe should support "log" parameter

### ISSUE THREAD

**Issue by phantom0301** [mwaskom/seaborn#1202]
When i want to draw a hist pic that y-axis value is log（value）. I couldn't use distplot to complete it directly.

So i think maybe we can add parameter "log“ in the function distplot just like this

def distplot(......,log=False):
...
    if hist:
    ...
    ax.hist(...,log=True or False)
    ...
...

**Comment by mmagnuski** [comment]
What kind of difficulities are you facing? What happens when you set y to log scale like below?
```python
ax= sns.distplot(some_fancy_data)
ax.set_yscale('log')
```

**Comment by mwaskom** [comment]
use `hist_kws`

**Comment by ccario83** [comment]
`ax.set_yscale('log')` is a good solution, but will fail for histogram bins with 0 count.
`sns.distplot(..., hist_kws={'log':True})` does not, however.

**Comment by Murilo-Perrone** [comment]
Neither method worked for me...
For `ax.set_yscale('log')` I got:
```
AttributeError: 'FacetGrid' object has no attribute 'set_yscale'
```
For `, hist_kws={'log':True}` I got:
```
AttributeError: 'Rectangle' object has no property 'hist_kws'
```
For `, log_scale=True` I got:
```
ValueError: autodetected range of [-inf, 2.0170333392987803] is not finite
```
What worked for me was:
```py
g = sns.displot(array)
g.set(yscale="log")
```
reference: https://github.com/mwaskom/seaborn/issues/2502
