### ISSUE TITLE
Reference and Zenodo DOI?

### ISSUE THREAD

**Issue by brorfred** [mwaskom/seaborn#1203]
Do you have a preferred citation for seaborn, and if not could you make a zenodo DOI? 

https://guides.github.com/activities/citable-code/

Best,

Bror Jonsson

**Comment by mwaskom** [comment]
![screenshot 2017-06-20 10 14 52](https://user-images.githubusercontent.com/315810/27337783-6f2031e6-55a1-11e7-80b5-a5e1c189134c.png)
