### ISSUE TITLE
Requirements should provide minimum versions

### ISSUE THREAD

**Issue by LLrsokl** [mwaskom/seaborn#1205]
pip-installing seaborn, or anything that requires seaborn, will force-install the latest version of all of its requirements. This can do things like delete mkl-optimized numpy and replace it with vanilla numpy.

It would be very helpful for the required packages to have minimum versions - or even approximate minimum versions - specified.

**Comment by mwaskom** [comment]
> pip-installing seaborn, or anything that requires seaborn, will force-install the latest version of all of its requirements.

I don't believe this is true. Seaborn explicitly only installs dependencies that do not exist: https://github.com/mwaskom/seaborn/blob/master/setup.py#L66

**Comment by mwaskom** [comment]
I'm also not sure it's true that declaring minimum versions will stop pip from force updating everything when you do `pip install -U <package>`.

By the way on newer pips you can do `pip install -U --no-deps <package>` to avoid this behavior...

**Comment by LLrsokl** [comment]
Oh awesome. I didn't know about `pip install -U --no-deps <package>`!
