### ISSUE TITLE
clustermap: access the reordered row/column indices

### ISSUE THREAD

**Issue by schustischuster** [mwaskom/seaborn#1207]
First thanks for the nice visualization library. Clustermaps look really great. I was trying to access the reordered row and column indices, but clustergrid.dendrogram_row.reordered_ind and clustergrid.dendrogram_col.reordered_ind are not working. I tried both sns.clustergrid.dendrogram_row.reordered_ind and clustergrid.dendrogram_row.reordered_ind, leading to error messages: "AttributeError: module 'seaborn' has no attribute 'clustergrid'" and "NameError: name 'clustergrid' is not defined", respectively. How should this function be used properly? An example on http://seaborn.pydata.org/generated/seaborn.clustermap.html would be helpful. Thanks again!

**Comment by mwaskom** [comment]
`clustergrid` is the object returned by the `clustermap` function. It has useful attributes, including the ones you are looking for.

**Comment by scottgigante** [comment]
For anyone landing on this page looking for an answer to the question:

> To access the reordered row indices, use: clustergrid.dendrogram_row.reordered_ind
> Column indices, use: clustergrid.dendrogram_col.reordered_ind

**Comment by GitwellAnyohub** [comment]
what an absolute garbage response from @mwaskom thanks for giving an actual answer @scottgigante

**Comment by SofiyaLo** [comment]
I've spent a lot of time trying to figure this out, but instead of writing clustergrid, you need to try your_clustermap_name.dendrogram_row.reordered_ind

**Comment by NewmanAHuman** [comment]
@SofiyaLo   THANK YOU  :) :) :)
