### ISSUE TITLE
markers option in stripplot

### ISSUE THREAD

**Issue by rgpdx** [mwaskom/seaborn#1210]
Is there a way to have the markers option where in addition to hue we can also have a list of markers passed onto stripplot so different types of markers may be used? Something like this -

>>> ax =  sns.stripplot("day", "total_bill", "smoker", data=tips,
...                    palette="Set2", size=20, marker=["D", "^"],
...                    edgecolor="gray", alpha=.25)

**Comment by mwaskom** [comment]
No there isn't, sorry. The scatter points for the different colors are all part of the same collection and therefore must have the same marker shape (a matplotlib constraint). If they were drawn in different collections, each hue level would obscure those before it, which is suboptimal.
