### ISSUE TITLE
Using seaborn clustermap with mpld3

### ISSUE THREAD

**Issue by anniepyim** [mwaskom/seaborn#1223]
I am trying to make an interactive clustermap with seaborn and mpld3
The issue is, I will have to pass a collection object (in my case, the Mesh of the heatmap) to mpld3
Currently the **Mesh** object is drawn within the object **_HeatMapper**, with the func **def plot()**

```
class _HeatMapper(object):

   ...some other codes...

   def plot(self, ax, cax, kws):
        """Draw the heatmap on the provided Axes."""
        # Remove all the Axes spines
        despine(ax=ax, left=True, bottom=True)
        
        # Draw the heatmap
        mesh = ax.pcolormesh(self.plot_data, vmin=self.vmin, vmax=self.vmax,
                             cmap=self.cmap, **kws)
```

Is there anyway to return this **Mesh** object so I could pass it to mpld3?
For instance, by making the mesh a **self.property** that could be retrieved?

Of course then the **_HeatMapper** object has to be returned in someway too
Is it possible to return the **_HeatMapper** object with the **def heatmap()**
like how the **_DendrogramPlotter** is returned with **def dendrogram()**?

**Comment by mwaskom** [comment]
No, this isn't possible, sorry.
