### ISSUE TITLE
Legend shows text but no colors in pointplot

### ISSUE THREAD

**Issue by aryamccarthy** [mwaskom/seaborn#1224]
Consider the difference in output between these two blocks—the only difference is `markers=""`. It's a rough example, but the problem is clear. Just because there's no marker doesn't mean that there aren't differentiable lines.

```python
import seaborn.apionly as sns
data = sns.load_dataset('iris')
sns.pointplot('sepal_length', 'sepal_width', hue='petal_width', data=data, ci=None, markers="")
```

<img width="389" alt="unknown-2" src="https://user-images.githubusercontent.com/5395205/27893566-15a5c400-61cc-11e7-92ee-d54e67d4a051.png">

```python
import seaborn.apionly as sns
data = sns.load_dataset('iris')
sns.pointplot('sepal_length', 'sepal_width', hue='petal_width', data=data, ci=None)
```
<img width="389" alt="unknown-3" src="https://user-images.githubusercontent.com/5395205/27893584-33384e52-61cc-11e7-8fd0-1cbfb8e6889d.png">

**Comment by mwaskom** [comment]
Well... it is called "pointplot"...

**Comment by mwaskom** [comment]
I'm not sure exactly what you're doing, but based on the example here, I am not sure that pointplot is the tool you want to be using anyway.

**Comment by aryamccarthy** [comment]
You're not wrong, but there's arguably a better default in this case. And this will come up when someone wants to recreate `plt.plot` with your pandas-friendly API. Consider a simpler, more useful example:

```python
tips = sns.load_dataset("tips")
ax = sns.pointplot(x="time", y="total_bill", data=tips, hue="smoker", 
                   markers="")
```

<img width="385" alt="unknown-4" src="https://user-images.githubusercontent.com/5395205/27911114-8609fb48-621d-11e7-8d90-42d4758462f1.png">

There's no way to discern between the 'yes' and 'no'.  But there could be.

```python
def add_legend_for_empty_markers(data, hue, palette=None, ax=None):
    palette = palette or sns.color_palette("Set1")  # TODO: Get current palette
    ax = ax or plt.gca()
    
    handles = []  # I assume nothing else was going into the legend.
    # Made-up logic to match responses to colors. Works; fragile.
    for response, color in zip(set(data[hue].values), palette[1::3]):
        handles.append(mlines.Line2D([], [], color=color, marker="", label=response))
    ax.legend(handles=handles, title=hue)

markers=""
ax = sns.pointplot(x="time", y="total_bill", data=tips, hue="smoker", 
                   markers=markers)
if markers=="":
    add_legend_for_empty_markers(tips, "smoker", ax=ax)
```
<img width="385" alt="unknown-5" src="https://user-images.githubusercontent.com/5395205/27912182-8d108cfa-6221-11e7-8d93-7c9f042d6e2e.png">

I'm not comfortable submitting this as a pull request because of the palette handling. But this does legend with empty markers clearer.

**Comment by mwaskom** [comment]
> And this will come up when someone wants to recreate plt.plot with your pandas-friendly API

Someone who is trying to do this would be making a mistake. `pointplot` is *not* simply equivalent to `plt.plot` with a "pandas friendly API".

I'm going to close as the point of `pointplot` is to show points, not lines.
