### ISSUE TITLE
Version mismatch gh vs. pypi

### ISSUE THREAD

**Issue by croth1** [mwaskom/seaborn#1232]
The latest version here at github is tagged as 0.8.0, following your previous versioning scheme. On pypi the version number is 0.8 - which is giving me a bit of a headache when trying to package the latest version.

Is 0.8.0 the correct version and if so, will you change the pypi version?

**Comment by mwaskom** [comment]
Unfortunately I don't believe it's possible to change the pypi version, sorry if that causes problems. There will probably be an 0.8.1 soon, you can just hold off on 0.8.0 if you want.

**Comment by croth1** [comment]
As there's no easy solution to fix this issue, I will go ahead and close it - after all it is quite easy to work around the versioning problem.

**Comment by mwaskom** [comment]
It's very annoying ... unless I'm missing something, the PyPi folks disabled the ability to edit package metadata on the old version of the PyPi site before implementing that ability on the new version...
