### ISSUE TITLE
lmplot: Using hue variable scrambles data sorting

### ISSUE THREAD

**Issue by carderne** [mwaskom/seaborn#1234]
I'm using lmplot with hue for the category and 'scatter_kws' to set the marker size based on another country variable.

```
size = df['size_var']
sns.lmplot(data=df, x='x_var', y='y_var', hue='hue_var', fit_reg=True, scatter_kws={"s": size})
```

The marker sizes end up not correlating with the correct points, so I assume some sorting has happened to the data in the background, while the `size` list remains static. I got around this by using a for loop and `regplot`.

This doesn't happen if I set `hue=False`.

**Comment by mwaskom** [comment]
Please provide a reproducible example so I can understand the problem you are having.

**Comment by carderne** [comment]
```
import pandas as pd
import seaborn as sns

df = pd.DataFrame()
df['x'] = [50, 70, 10, 12, 75]
df['y'] = [50, 60, 30, 20, 50]
df['size'] = [100000, 1000, 10000, 20000, 200]
df['category'] = [1, 2, 1, 1, 3]

fg = sns.lmplot(data=df, x='x', y='y', #hue='category',
                scatter_kws={'s': df['size']}, size=20, legend=False)
fg.set(xlim=[0,100], ylim=[0,100])
```

By un-commenting `hue`, you will see that the sizes of the points are completely scrambled.

**Comment by mwaskom** [comment]
OK I see; `lmplot` plots each hue level separately and passes the whole `scatter_kws` dict in each time it calls `plt.scatter`, so this isn't expected to work, sorry.

**Comment by carderne** [comment]
Thanks, appreciate the feedback.
