### ISSUE TITLE
module object has no attribute plt in seaborn

### ISSUE THREAD

**Issue by ShownX** [mwaskom/seaborn#1239]

**Comment by mwaskom** [comment]
Were you expecting it to?

**Comment by qbilius** [comment]
Reasons to have `seaborn.plt`:
- Because it used to have it until version 0.8.
- Because it is more convenient to only import seaborn and do `seaborn.plt.show` rather than importing pyplot just to see your plots.

**Comment by mwaskom** [comment]
Did you also use to use `sns.np` when you wanted `numpy`? Referencing packages that happen to exist in the namespace of other packages is very bad practice and certainly not something I am going to encourage.
