### ISSUE TITLE
PairGrid with hue not working correctly with stripplot / swarmplot

### ISSUE THREAD

**Issue by javidcf** [mwaskom/seaborn#1242]
I have a data frame with columns `f1`, `f2`, `f3` (integers) and `value` (float), and I was trying to get this plot:

![pairgrid_good](https://user-images.githubusercontent.com/1098280/28463686-9e103484-6e19-11e7-9b31-488befee1e50.png)

All the `f*` features plotted against each other with strip plots with jitter (or swarm plots), and a color indicating the `value`. So I used a code like this:

```
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(0, 5, size=(100, 3)), columns=["f1", "f2", "f3"])
df["value"] = np.random.rand(len(df))

g = sns.PairGrid(df, vars=df.columns[:-1], hue="value", palette=sns.light_palette("red", len(df)), hue_order=sorted(df["value"]))
g.map(sns.stripplot, jitter=True, size=3)

plt.show()
```

But instead I got this:

![pairgrid_bad](https://user-images.githubusercontent.com/1098280/28463712-bc75805a-6e19-11e7-8654-b2d862505144.png)

However, changing the `PairGrid` definition to:

```
g = sns.PairGrid(df, vars=df.columns[:-1])
g.map(sns.stripplot, jitter=True, size=3, hue=df["value"], palette=sns.light_palette("red", len(df)), hue_order=sorted(df["value"]))
```

Does produce the desired output. I think that `hue` is mean to be used mainly for categorical or discrete values, but still I don't see why it shouldn't work as I expected in this case. The issue seems to be the same using either strip plots or swarm plots.

Tested with seaborn 0.8.

**Comment by mwaskom** [comment]
You need to use `order`. In any case I'm not certain that `stripplot` is the right choice here, maybe you just want a scatterplot?

**Comment by javidcf** [comment]
@mwaskom Thanks for your answer. Yes, I _do_ want a scatter plot, but I need the jitter (or the swarm functionality), because I have many pair-wise overlapping points (I guess I _could_ just add random noise to my data...). Still, I don't understand how I'm supposed to use `order` for this. `PairGrid` doesn't have that argument, so you mean as a keyword argument to `map`? That doesn't seem right, because the order is different for each plot. Also, I assumed numeric features would be correctly ordered by default, as it happens when `PairGrid` doesn't get a `hue`; I don't understand why adding this parameter changes the behavior.
