### ISSUE TITLE
swarmplot points overlap if changing DPI

### ISSUE THREAD

**Issue by DizietAsahi** [mwaskom/seaborn#1243]
If specifying a high dpi at Figure creation time, the points in a swarmplot become more and more overlapping.

Example:
```
for my_dpi in [50,80,100,150,200]:
    fig, ax = plt.subplots(dpi=my_dpi)
    a = np.random.normal(size=(100,))
    sns.swarmplot(a, orient='v')
    plt.show()
```
![download](https://user-images.githubusercontent.com/13396853/28477827-186c24b8-6e56-11e7-9484-8dac84a621b3.png)
![download 1](https://user-images.githubusercontent.com/13396853/28477830-1b132086-6e56-11e7-87de-a64b75c8c206.png)
![download 2](https://user-images.githubusercontent.com/13396853/28477832-1dafbffc-6e56-11e7-902b-cf5050f826e8.png)
![download 3](https://user-images.githubusercontent.com/13396853/28477835-20360a56-6e56-11e7-8755-868e641c18b8.png)
![download 4](https://user-images.githubusercontent.com/13396853/28477836-2301d21a-6e56-11e7-8b24-87556b59c508.png)

**Comment by mwaskom** [comment]
What version? This sounds like an exact duplicate of #1008 which was fixed in 0.8.0.

**Comment by DizietAsahi** [comment]
My apologies, I've done a search for `dpi` but somehow did not look in closed tickets.
I'm running 0.7.1 here, so will upgrade to fix the issue.

**Comment by mwaskom** [comment]
No worries, your detailed examples made it easy to see the similarities to the previous issue.
