### ISSUE TITLE
sns.clustermap(cbar=False) doesn't work. 

### ISSUE THREAD

**Issue by zfrenchee** [mwaskom/seaborn#1246]
### seaborn.clustermap docs: 

> **kwargs** : *other keyword arguments*
> All other keyword arguments are passed to sns.heatmap

### seaborn.heatmap docs: 

> **cbar** : *boolean, optional*
> Whether to draw a colorbar.

`sns.heatmap(cbar=False)` behaves as expected, `sns.clustermap(cbar=False)` does not.

**Comment by mwaskom** [comment]
#891
