### ISSUE TITLE
Barplot with orient='horizontal' throws an error

### ISSUE THREAD

**Issue by devforfu** [mwaskom/seaborn#1248]
Not sure if that is a feature or bug, but the following code works as expected:
```python
import pandas as pd
import seaborn as sns

imp_df = pd.DataFrame([
    {'feature': 'first', 'importance': 0.5},
    {'feature': 'second', 'importance': 0.25},
    {'feature': 'third', 'importance': 0.125},
    {'feature': 'fourth', 'importance': 0.125},
])

sns.barplot(x='feature', y='importance', data=imp_df)
```

I though that it is possible to switch orientation like this:
```python
sns.barplot(x='feature', y='importance', data=imp_df, orient='h')
```

But it throws an error instead:
```
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

I know that it is possible to just switch column names for `x` and `y` to get required result. But nevertheless, the error was kind of surprising from my point of view so reporting it here just in case.

**Comment by mwaskom** [comment]
Swap your assignments of `x` and `y`.
