### ISSUE TITLE
pointplot for repeated measures data

### ISSUE THREAD

**Issue by cbrnr** [mwaskom/seaborn#1249]
The documentation of `sns.pointplot` mentions a `units` argument, which should be set if there is a repeated measures design. I'm not sure I understand exactly what needs to be specified here (and maybe my data is also not in the correct format), so I thought I'd better double-check and ask.

My data frame looks as follows. The `id` column specifies the subject (35 levels), the `cond` column encodes the condition (2 levels), and the `roi` column encodes the region of interest (where the value was measured, 8 levels). Finally, there is a `value` column which contains the actual values. So in total, there are 560 rows and 4 columns.

Now both `cond` and `roi` were measured within subjects. I thought it would be important to set the `units` argument correctly so that the confidence intervals are properly estimated (they should get smaller in a repeated measures design IIRC). However, I can only set this argument to the name of one column, and even if I do this (e.g. set `units="cond"`), I see no difference between the plot where `units` is not set at all.

How do I properly create a point plot where the confidence intervals properly account for repeated measures data?

**Comment by mwaskom** [comment]
It's very hard to understand the structure of a dataset from a prose description of it, but `units` should be the variable within with repeated measures are nested. For your design it's probably whatever variable identifies your subjects.

**Comment by cbrnr** [comment]
Thanks @mwaskom, so it should be the `id` column. It doesn't seem to make any difference though, the plot looks identical to the one where I don't set `units`. Would my question be clearer if I shared the data?

**Comment by mwaskom** [comment]
It will matter only to the extent that there are within-unit correlations.

**Comment by cbrnr** [comment]
Then I don't understand how to use this argument correctly. Here's some example data:

```
 id group value
 1  A     30
 2  A     35
 3  A     45
 4  A     40
 5  A     50
 6  A     35
 7  A     55
 8  A     25
 9  A     30
 10 A     45
 11 A     40
 12 A     50
 1  B     40
 2  B     35
 3  B     50
 4  B     55
 5  B     65
 6  B     55
 7  B     50
 8  B     35
 9  B     30
 10 B     50
 11 B     60
 12 B     39
```

And here's the code (copy the data to the clipboard first):

```
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_clipboard()
fig, ax = plt.subplots(1, 2)
sns.pointplot(x="group", y="value", data=data, ax=ax[0])
sns.pointplot(x="group", y="value", data=data, units="id", ax=ax[1])
```

Here's the resulting figure:
![figure_1](https://user-images.githubusercontent.com/4377312/28577600-7c72530c-7157-11e7-9b3b-85b4a01b0a14.png)

There are within-subject differences, which result in non-overlapping 95% error bars if you account for them (i.e. in a repeated measures design). This is not reflected in the plots, which basically look identical.

**Comment by mwaskom** [comment]
You only have one observation per subject/group, so there can't be within-subject correlations.

**Comment by cbrnr** [comment]
OK, that's what this argument does then. But is there a way to account for differences between subjects in a within design then? If each subject is in both groups, we can apply a paired t-test, which removes subject variability (and makes the error bars smaller). Both figures show error bars as computed with an independent t-test more or less (forget about the bootstrap here).

**Comment by mwaskom** [comment]
There are some methods, such as that proposed by Loftus for removing the within subject grand mean before computing condition-specific standard errors. That can be accomplished by transforming the data before plotting. But I would say to just plot the datapoints. If all the subjects have similar slopes despite varying intercepts, it will be obvious.

**Comment by cbrnr** [comment]
Alright, thanks!
