### ISSUE TITLE
wish: add option for edge color (gray) to violinplots and similar

### ISSUE THREAD

**Issue by oivulf** [mwaskom/seaborn#1252]
Dear developers of Seaborn,
at the moment the color of lines surrounding violinplots is computed.
I would much prefer if it could be passed to violinplots, possibly as code does now for hue.
This would allow for example having white violinplots with black edges, as in sample attached.
[prova.pdf](https://github.com/mwaskom/seaborn/files/1185856/prova.pdf)

**Comment by mwaskom** [comment]
You can always change the color of things after plotting if you access the artists directly:

```
ax = sns.violinplot(x="day", y="total_bill", data=tips, color="w")
plt.setp(ax.collections, edgecolor="k")
```

![image](https://user-images.githubusercontent.com/315810/28755917-7d6945b6-7532-11e7-882a-bbf327773cbf.png)
