### ISSUE TITLE
Grid above objects

### ISSUE THREAD

**Issue by Phlya** [mwaskom/seaborn#1254]
Hi, I think this a bug: grid is drawn above the violinplot (the same with boxplot, haven't tested other plots) if using default matplotlib style, but not with seaborn whitegrid style.

```
import matplotlib.pyplot as plt
import seaborn as sns
d = sns.load_dataset('tips')
sns.set_style('whitegrid')
plt.figure()
sns.violinplot('size', 'total_bill', data=d)
plt.show()
```
![image](https://user-images.githubusercontent.com/2895034/28786384-fd564c54-7610-11e7-8d4c-129fed1a04ce.png)
```
sns.reset_defaults()
plt.figure()
sns.violinplot('size', 'total_bill', data=d)
plt.grid(axis='y')
plt.show()
```
![image](https://user-images.githubusercontent.com/2895034/28786396-04714822-7611-11e7-8926-51aebda0863a.png)

The weird thing is, if I specify zorder=100 for the violinplot and zorder=0 for the grid it doesn't help!

I'm using seaborn 0.8 from pypi and the latest matpotlib 2.0.2 (in jupyter notebook with the notebook backend).

**Comment by mwaskom** [comment]
That's just how the matplotlib defaults work. It's why the seaborn grid styles set the `'axes.axisbelow'` parameter.

**Comment by Phlya** [comment]
OK, I see. Perhaps I will raise with the matplotlib devs then, this is really not one expects as a default, I think...
