### ISSUE TITLE
distplot([1]) fails with TypeError: len() of unsized object

### ISSUE THREAD

**Issue by asmeurer** [mwaskom/seaborn#1256]
```pytb
>>> sns.distplot([1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 208, in distplot
    bins = min(_freedman_diaconis_bins(a), 50)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 29, in _freedman_diaconis_bins
    h = 2 * iqr(a) / (len(a) ** (1 / 3))
TypeError: len() of unsized object
```

As a workaround I can use `distplot([1]*2)`, although this also results in a warning about the KDE

```pytb
/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kde.py:494: RuntimeWarning: invalid value encountered in true_divide
  binned = fast_linbin(X,a,b,gridsize)/(delta*nobs)
/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kdetools.py:34: RuntimeWarning: invalid value encountered in double_scalars
  FAC1 = 2*(np.pi*bw/RANGE)**2
```

The KDE warning is probably correct if unhelpful (can't do a KDE for a single data point), but the histogram ought to work.

**Comment by mwaskom** [comment]
It's not obvious what the histogram bins should be for a single observation. matplotlib does 10 .1 sized bins from `val - .5` to `val + .5`. I'm not sure this makes more sense than an error.

Another workaround would be to pass the bin edges you want to use.

**Comment by mwaskom** [comment]
(That said, an error is a pain in the butt in the context of a `FacetGrid`)

**Comment by asmeurer** [comment]
Also if it is an error the error message could be more helpful.
