### ISSUE TITLE
Setting limits in regplot messes with line of best fit

### ISSUE THREAD

**Issue by Lioscro** [mwaskom/seaborn#1258]
Hi, all.
I was using seaborn.regplot when I observed some strange behavior with the line of best fit.
I am currently using Python 3.6.2, Seaborn 0.8, and Matplotlib 2.0.2.

When I set the x and y limits using plt.xlim and plt.ylim before the sns.regplot call, the line of best fit does not plot as intended. On the other hand, when setting the limits after the regplot call, the line plots correctly.
Here is the dataset I am using: [sim3.txt](https://github.com/mwaskom/seaborn/files/1215972/sim3.txt)

```python
# Graphics
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import rc
import matplotlib.dates as mdates
rc = {'lines.linewidth': 2, 
      'axes.labelsize': 18, 
      'axes.titlesize': 18, 
      'axes.facecolor': 'DFDFE5'}
sns.set_context('notebook', rc=rc)
sns.set_style("dark")
mpl.rcParams['xtick.labelsize'] = 16 
mpl.rcParams['ytick.labelsize'] = 16 
mpl.rcParams['legend.fontsize'] = 14

df = pd.read_csv('sim3.txt') # read data

# plot
fig, ax = plt.subplots()
sns.regplot(data=df, x='corr_p', y='p_t (one)', scatter_kws={'s': 20, 'alpha':1},
            line_kws={'ls':'--', 'lw':1, 'color':'red', 'label': 'best fit line'}, ax=ax)

plt.xlim(10**-6, 1) # called after sns.regplot
plt.ylim(10**-6, 1)

plt.legend()
plt.xscale('log')
plt.yscale('log')
plt.xticks([0.000001, 0.001, 1])
plt.yticks([0.000001, 0.001, 1])
plt.xlabel(r'$p$-value, bootstrapped')
plt.ylabel(r'$p$-value, t-test')
```

The above code yields the correct plot:
![correct_plot](https://user-images.githubusercontent.com/1281521/29186534-a7d3f89a-7dc1-11e7-82e3-710453430d9f.png)

However, when the xlim and ylim arguments are moved to before the regplot call, as below,
```python
# plot
fig, ax = plt.subplots()
plt.xlim(10**-6, 1) # called before sns.regplot
plt.ylim(10**-6, 1)
sns.regplot(data=df, x='corr_p', y='p_t (one)', scatter_kws={'s': 20, 'alpha':1},
            line_kws={'ls':'--', 'lw':1, 'color':'red', 'label': 'best fit line'}, ax=ax)

plt.legend()
plt.xscale('log')
plt.yscale('log')
plt.xticks([0.000001, 0.001, 1])
plt.yticks([0.000001, 0.001, 1])
plt.xlabel(r'$p$-value, bootstrapped')
plt.ylabel(r'$p$-value, t-test')
```
![incorrect_1](https://user-images.githubusercontent.com/1281521/29186645-f89df460-7dc1-11e7-9df9-e539799e8111.png)
and when robust=True,
![incorrect_2](https://user-images.githubusercontent.com/1281521/29186670-0f54a866-7dc2-11e7-87f7-284922c8b908.png)

**Comment by mwaskom** [comment]
I think the answer is that it's a rounding error somewhere that is being magnified due to the many extremely small values in the dataset. I'm not exactly sure, but one suggestion would be to fit the regression line to the log data. (BTW the first plot doesn't look crazy in the way the second one does, but it doesn't actually look like a good regression fit to the scatterplot. You're also cutting off a lot of your datapoints!)

**Comment by mwaskom** [comment]
Also the difference between setting the limits before and after the plot goes away when you set `truncate=True`, which makes sense.

**Comment by mwaskom** [comment]
Here's another way of looking at your data:

![image](https://user-images.githubusercontent.com/315810/29188680-dbbf808c-7de1-11e7-915d-9594f014b627.png)

I can't explain exactly what's happening with the regression, but I think it's safe to say this dataset violates the assumptions of ordinary least squares.

**Comment by Lioscro** [comment]
That sounds reasonable.
Thank you!
