### ISSUE TITLE
Documentation needs higher contrast for text

### ISSUE THREAD

**Issue by unnamedplay-r** [mwaskom/seaborn#1259]
I absolutely love this library for my plotting, but the change in website documentation is killing me at the moment. Each time I visit, I have to manually change the font to a darker setting.

Can we change the font color to something more accessible?

**Comment by mwaskom** [comment]
Uh oh, sorry about that. It's a bootswatch theme used through sphinx-bootstrap, which means it's not super easy to customize, though I can look into it.

**Comment by mwaskom** [comment]
Instead of manually changing the font color, is it easier to read if you increase the font size? (A little easier in most browsers).

**Comment by unnamedplay-r** [comment]
@mwaskom no stress, it's a slight pain point. And ugh - you're right, what an oversight. I'm so used to refraining from zooming when reading as it tends to destroy the formatting for websites; looks like seaborn's docs gracefully scales into mobile view.

But never the less the contrast ratio between smaller sized medium gray fonts and a background fails on full compliant web accessibility tests (and my eyes!). You can see the failure to AAA standards [here](http://webaim.org/resources/contrastchecker/?fcolor=666666&bcolor=ffffff).

**Comment by mwaskom** [comment]
You may also want to kick the issue up to the main bootswatch repository: https://github.com/thomaspark/bootswatch/. The theme seaborn currently uses is "paper". It's likely a problem for other sites too so it might be good to have it fixed centrally.

**Comment by unnamedplay-r** [comment]
Good thinking, I'll shoot them a note.
