### ISSUE TITLE
Seaborn version 0.8 missing seaborn.plt

### ISSUE THREAD

**Issue by hawkeyej** [mwaskom/seaborn#1260]
Seaborn version 0.8 is missing seaborn.plt, it was in 0.7.1

Using "import matplotlib.pyplot as plt" and then using plt does not produce the same results.

**Comment by mwaskom** [comment]
Duplicate of #1239 

Don't access libraries as sub-modules in libraries that import them. It's bad practice.

**Comment by hawkeyej** [comment]
Accessing matplotlib.pyplot directly produces different results. So am I stuck with ugly graphs or should I look for an alternative to seaborn?

I'd like to continue to produce attractive graphs with seaborn.

**Comment by TomAugspurger** [comment]
Might want to check the first item here: http://seaborn.pydata.org/whatsnew.html#v0-8-0-july-2017

**Comment by hawkeyej** [comment]
With seaborn imported as sns, I do already have this in my code:
```python
sns.set_context("notebook", font_scale=1.1, rc={"lines.linewidth": 3.5})
```

**Comment by hawkeyej** [comment]
Ok, it seems that it's not the missing seaborn.plt that's the problem. I modified the code to call matplotlib.pyplot directly and I still get a big difference in the style of my graph. With 0.7.1, the style is fine. With 0.8.0, the style does not get applied.

**Comment by mwaskom** [comment]
Read the line that @TomAugspurger directed you to more carefully.

**Comment by hawkeyej** [comment]
Thanks for your patience. I get it now.

**Comment by direvius** [comment]
@mwaskom changing api without deprecation warning it is bad practice
