### ISSUE TITLE
Add function for categorical scatterplot?

### ISSUE THREAD

**Issue by amueller** [mwaskom/seaborn#1264]
I was wondering if you'd consider adding a function for a scatterplot that uses categories for hues, like a single entry of a pairplot.
It's a bit tricky to do that with matplotlib, as ``plt.scatter`` doesn't easily allow creating a legend, and controlling the colormap is also a bit tricky.
Or maybe there's already a way to do that with seaborn I'm not aware of?

**Comment by amueller** [comment]
I guess it could be achieved with
```python
g = sns.PairGrid(df, x_vars=["varx"], y_vars=["vary"], hue='hue')
g = g.map(plt.scatter)
```
but that seems a bit complicated?

**Comment by mwaskom** [comment]
You can do it with `FacetGrid` more easily.

**Comment by mwaskom** [comment]
Or `lmplot` with `fit_reg=False` (same thing).

**Comment by mwaskom** [comment]
There's not an axes level function to do it. I've thought about adding one but haven't had the time/motivation in a while, so it's probably not going to happen.

**Comment by amueller** [comment]
Might send you a PR then (after jupytercon)

**Comment by mwaskom** [comment]
I'm closing for now as this is already on my private list of todos. To get merged it would have to be a pretty substantial undertaking — there are enough issues that spiral out of the basic idea (e.g. will there also be support for categorical marker shape? what about continuous marker size? should there be dual support for continuous and categorical color mapping?) that I'm against adding a thin prototype that might constrain later flexibility.

**Comment by amueller** [comment]
Fair. I'm a bit sad that this functionality with seems pretty essential is not easily available. But it is indeed not that simple an interface. matplotlib decides to basically only support continuous colors / sizes etc, which makes it reasonably simple but also not very useful for categorical data. Doing both seems like it might be complicated.

**Comment by mwaskom** [comment]
Well like I said it's not complete unavailable because you can get it from `lmplot`*; what's missing is the flexibility to plot it onto an arbitrary axes.

*With the additional caveat that each category will be layered so for dense scatterplots it will misrepresent the distribution of categories.
