### ISSUE TITLE
Bug in PairGrid diagonal with hue for non-hist plots

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#1265]
See StackOverflow report: https://stackoverflow.com/questions/45862882/why-are-no-colors-shown-in-kde-subplots-in-seaborn-pairplot

I think this was added here: https://github.com/mwaskom/seaborn/commit/db7c397d5dc22047d8f336b63c5869342da94419

The problem is that by assigning to `color` in the for loop, it's no longer `None` and doesn't pull from the palette for later categories...

**Comment by marcelflygare** [comment]
Thanks for taking care of my query
