### ISSUE TITLE
ImportError: No module named 'scipy.cluster'

### ISSUE THREAD

**Issue by KaifangXu103** [mwaskom/seaborn#1266]
import seaborn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Anaconda3\lib\site-packages\seaborn\__init__.py", line 13, in <module>
    from .matrix import *
  File "F:\Anaconda3\lib\site-packages\seaborn\matrix.py", line 12, in <module>
    from scipy.cluster import hierarchy
ImportError: No module named 'scipy.cluster'

**Comment by mwaskom** [comment]
You don't have scipy installed or there is a problem with your scipy installation.

**Comment by brianpenghe** [comment]
I have the same problem

**Comment by brianpenghe** [comment]
> import seaborn
> Traceback (most recent call last):
> File "", line 1, in 
> File "F:\Anaconda3\lib\site-packages\seaborn__init__.py", line 13, in 
> from .matrix import *
> File "F:\Anaconda3\lib\site-packages\seaborn\matrix.py", line 12, in 
> from scipy.cluster import hierarchy
> ImportError: No module named 'scipy.cluster'

Run this:
sudo apt-get install python-scipy

And then restart your python
