### ISSUE TITLE
factorplot does not sort entries alpha-numerically by default

### ISSUE THREAD

**Issue by maartenmennes** [mwaskom/seaborn#1274]
Hello,

It appears that factorplot does not resort to alpha-numerical sorting by default, requiring the need to add the 'order' argument to get things sorted properly.

default sorting:
![image](https://user-images.githubusercontent.com/1139180/30153431-e73cd7da-93b6-11e7-9f95-c96c162bbe2a.png)

with order argument:
![image](https://user-images.githubusercontent.com/1139180/30153453-f945f33a-93b6-11e7-91c1-05ed225272f0.png)

I can see why one would need an order argument, but I expected that to be in order to get things not alpha-numerically sorted ;)

**Comment by mwaskom** [comment]
No, there was a very long thread about this decision (#361) in which it was decided that respecting dataframe order for stringy variables was less surprising than sorting. So you could use `order=`, or do `sns.factorplot(x="subject", ..., data=df.sort_values("subject"))`

**Comment by mwaskom** [comment]
][';l[]lllllllllllllllllllllllllllllllllllllllppp;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;''''''''''p]]]]]]]]k;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;lkkkkkkkkk;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

**Comment by mwaskom** [comment]
Oops, sorry, that comment is brought to you by my dog.

**Comment by maartenmennes** [comment]
ah, ok, thanks for the clarification. 

Must say you have a very opinionated dog though... no need for him/her to rub it in that my question was already discussed previously 😄
