### ISSUE TITLE
Feature Request: Allow for average dot inside violinplot (instead of median)

### ISSUE THREAD

**Issue by niemasd** [mwaskom/seaborn#1275]
Self-explanatory: I love the violinplot, but the dataset I'm working with is exponentially distributed, so the median is 70% of the mean, yet I have a theoretical line at the mean, and the median dot is misleading and makes it look like our results are off. It would be nice if I could have an option to change the white dot to be the mean instead of the average using an argument (e.g. as one of the options of `inner`)

**Comment by mwaskom** [comment]
The box style plots the median because that's the definition of a boxplot. You can always turn it off and add a point at the mean.
