### ISSUE TITLE
picker event

### ISSUE THREAD

**Issue by LKDbigpig214** [mwaskom/seaborn#1276]
I am trying to use seaborn to enable the picking, but it doesn't have the parameter. So I edit the _PointPlotter, add parameter picker to ax.plot() ,and it worked. So I suggest to add this parameter to other functions. My English is poor, wish you could understand what I say. Thank you!

**Comment by mwaskom** [comment]
I've previously made the decision that the costs of added complexity in explicitly supporting matplotlib's interactive functionality are too great. If something happens to work, that's good, if not, users will have to drop down to using matplotlib directly.
