### ISSUE TITLE
jointplot() p-values

### ISSUE THREAD

**Issue by CommonClimate** [mwaskom/seaborn#1277]
the p-values for the slope of regression lines in jointplot() is often incredibly low (e.g., on [this page](http://seaborn.pydata.org/generated/seaborn.jointplot.html), of order 1e^{-34}. I would argue that on a computer with numerical precision `eps` it is meaningless to quote numbers below `eps`. Second, most people only care about p-values being below some threshold, say 1e^{-3}. Would it be possible to display p-values in a more intelligent manner, e.g. the actual value until that threshold, and "p < threshold" below that? By default I recommend the threshold to be 1e^{-3}, though it should be customizable. Thanks for considering.

**Comment by mwaskom** [comment]
The p value that is shown is the one returned by the annotation function that is provided to the `JointGrid`, by default `scipy.stats.pearson`. If you would like different formatting, you can pass a different annotation function and template.

**Comment by CommonClimate** [comment]
OK. I'll take this up with SciPy, then. Thanks for your wonderful work with Seaborn. It's changing the way I teach data analysis!
