### ISSUE TITLE
Feature Request: Strip, bar, factorplots with multiple categorical index layers

### ISSUE THREAD

**Issue by kdebrab** [mwaskom/seaborn#1280]
The proposal is that when one provides a list to the categorical index x or y, the corresponding columns of the dataframe are used as some sort of multiindex label. For an example of how this would look like, see https://stackoverflow.com/a/43999896 or https://stackoverflow.com/a/19242176.

I see two main advantages compared to using factorplots (compare https://stackoverflow.com/a/43999896 with https://stackoverflow.com/a/31860747):
* Visually more appealing, less clutter (especially in case of multiple "facets" with factorplot)
* More than 2 levels are easily supported (see e.g. https://stackoverflow.com/questions/19184484)

**Comment by mwaskom** [comment]
Sorry, but this is not going to happen.
