### ISSUE TITLE
Feature Request: Option for hexcolor code in sns.color_palette

### ISSUE THREAD

**Issue by jolespin** [mwaskom/seaborn#1281]
Some tools don't take RGB values and it would be useful if there was a hexcolor code option in color_palette. 

```python
sns.color_palette(n_colors=3, rgb=False)
```

Would be equivalent to:
```python
from matplotlib.colors import rgb2hex
[*map(rgb2hex, sns.color_palette(n_colors=3)]
```

Thoughts?

**Comment by mwaskom** [comment]
What's unsatisfactory about

```
sns.color_palette().as_hex()
```

which already works?

**Comment by jolespin** [comment]
Oh I didn't notice that was an option.   Thanks
