### ISSUE TITLE
Clustermap row_color legend

### ISSUE THREAD

**Issue by btyukodi** [mwaskom/seaborn#1282]
I found the following solution to add a row color legend to a clustermap:

https://stackoverflow.com/questions/27988846/how-to-express-classes-on-the-axis-of-a-heatmap-in-seaborn

I have two related questions:
1. how to move the legend to the bottom of the clustermap?
2. if the index of the dataframe representing row_color has a a name, it appears as a label under the colored row. How to increase the fontsize of that label?

Thank you.

**Comment by mwaskom** [comment]
These questions should be asked on stackoverflow, as the original question was.
