### ISSUE TITLE
Feature request: allow hue-dodged swarmplots to be colored based on additional categorical factor

### ISSUE THREAD

**Issue by surchs** [mwaskom/seaborn#1287]
Hi,

I try to overlay a swarmplot on grouped boxplots [as per the docs](http://seaborn.pydata.org/tutorial/categorical.html). 
An example would be:
```
import numpy as np
import pandas as pd
import seaborn as sbn
import matplotlib as mpl
import matplotlib.pyplot as plt

titanic = sbn.load_dataset("titanic")
sbn.boxplot(x='embark_town', y='age', hue='alive', data=titanic)
sbn.boxplot(x='embark_town', y='age', hue='alive', data=titanic)
sbn.swarmplot(x='embark_town', y='age', hue='alive', data=titanic, dodge=True,
             palette=sbn.color_palette(['black', 'red']))
```
![image](https://user-images.githubusercontent.com/1302022/30867710-b71a18d0-a2aa-11e7-95de-4f911103fd01.png)

What I'd like to do in this example is color points in each split swarmplot based on a fourth category, e.g. 'Sex'. I don't think this is currently possible. I can opt not to split the swarm and set 'Sex' as the hue argument but then I am lumping the 'alive' levels together

```
sbn.swarmplot(x='embark_town', y='age', hue='sex', data=titanic, dodge=False,
             palette=sbn.color_palette(['black', 'red']))
```
![image](https://user-images.githubusercontent.com/1302022/30867755-cdd09798-a2aa-11e7-8ca1-e7294ecdafbb.png)

I could think of two ways of solving this problem:
1. An additional hue-argument that controls the face color of swarm points while the original hue argument controls the position of swarm points (if dodge is `True`)
2. Provide a way to specify the category positions. [Currently they are hard-coded to [1, ..., number_of_categories]](https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L1392). If the user could specify x-axis positions for each category (possibly given that `order!=None`) one could create the functionality with a dummy coded category that takes care of the subset coloring.

Would either of these be within the scope of seaborn?

**Comment by mwaskom** [comment]
> Would either of these be within the scope of seaborn?

Sorry, but no. There no clean way to add this.

On your end, I would suggest using `factorplot` to draw the boxplots with x=alive, col=embark_town, and hue=sex, then layer the swarmplot on top of it. If you play with the aspect ratio and despine, you'll get a figure that looks almost identical and has the additional layer you want.
