### ISSUE TITLE
Adding tutorial resources

### ISSUE THREAD

**Issue by knathanieltucker** [mwaskom/seaborn#1291]
A bit of an unorthodox issue, but I was wondering if you had a place to contribute/list external resources, like a set of [youtube tutorials](https://www.youtube.com/watch?v=fWuPIGVPo7o&list=PLgJhDSE2ZLxYlhQx0UfVlnF1F7OWF-9rp)

I am a data scientist and I teach part time at General Assembly and University of San Francisco Data Institute, and I use seaboard pretty extensively in my classes. The tutorials have helped out people before especially for more audio/visual people to learn.

Let me know what you think?

**Comment by mwaskom** [comment]
No, I don't promote external tutorials. While I'm sure the people who make them are well intentioned, the ones I've looked at inevitably have what I would consider inaccuracies or at least teach suboptimal ways of doing things. I would not want to have to vet them, nor would I want to point people towards a tutorial that I feel has flaws.

FWIW, I don't doubt that there are students who have found youtube tutorials helpful or interesting, but I would be remiss not to point out that there is essentially [no scientific evidence](http://steinhardtapps.es.its.nyu.edu/create/courses/2174/reading/Pashler_et_al_PSPI_9_3.pdf) that learning styles actually exist.
