### ISSUE TITLE
When saving a tsplot as .eps to file the error transparency seems to break

### ISSUE THREAD

**Issue by CiaranWelsh** [mwaskom/seaborn#1293]
**.eps**
Here is my plot when saved as .eps
![image](https://user-images.githubusercontent.com/19502680/31121169-0b9a6d5e-a82f-11e7-9f1e-08c0283993ed.png)

**.png**
The same code was run but saving to .png
![smad4c](https://user-images.githubusercontent.com/19502680/31121217-389963d2-a82f-11e7-8cc6-adbe837abb3d.png)

**Comment by mwaskom** [comment]
Yes, eps doesn't have any support for transparency in general. Nothing seaborn can do about that unfortunately.

If you do `ax.set_rasterized(True)` it will convert the axes to a bitmap, which will preserve "transparency" (really just blending of object colors with the background into a single array, but the axes labels look bad. It may be possible to improve how they look and get a plot that you want, but it would be outside the scope of seaborn.

If you're trying to put the plots in a latex document, I've always found things work fine with .pdf format images.
