### ISSUE TITLE
Swarmplot points overlap with wider y limit

### ISSUE THREAD

**Issue by ChihHsuLin** [mwaskom/seaborn#1294]
Is it possible to avoid overlapping when the y limit range increases?
```
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np

data = np.random.rand(100)
data = np.vstack([np.zeros_like(data), data])
data[0,50:] = 1

fig, ax = plt.subplots()
sns.swarmplot(x=data[0], y=data[1], size=10, ax=ax)
fig.savefig("swarm.png")
```
![swarm](https://user-images.githubusercontent.com/10701574/31136141-e993ea7a-a82c-11e7-8e00-8825d4d2329d.png)

```
fig, ax = plt.subplots()
sns.swarmplot(x=data[0], y=data[1], size=10, ax=ax)
ax.set_ylim([-2, 5])
fig.savefig("swarm2.png")
```
![swarm2](https://user-images.githubusercontent.com/10701574/31136140-e993e1ce-a82c-11e7-89e5-6b4d6f946cc2.png)

**Comment by mwaskom** [comment]
Yes; set the limit first.

**Comment by ChihHsuLin** [comment]
Thank you. It's much easier than what I thought.

**Comment by mjlm** [comment]
> Yes; set the limit first.

This isn't always possible. Sometimes I need to make axis-specific adjustments for which the plot already needs to exist, so that I have access to the axes objects. How can I re-adjust the swarm markers to not overlap when the plot already exists>
