### ISSUE TITLE
pointplot can't be used in a PairGrid with hue

### ISSUE THREAD

**Issue by NklasF** [mwaskom/seaborn#1295]
I have modified the PairGrid example so that each x variable is additionally split by whether the person is alone or not. For that I used the hue parameter but when I call the `add_legend` method it only displays the legend without color-markers.

    import seaborn as sns

    sns.set(style="whitegrid")

    titanic = sns.load_dataset("titanic")

    g = sns.PairGrid(titanic, y_vars="survived", x_vars=["class", "sex", "who"], 
                              hue="alone", 
                              size=5,aspect=.5)

    g.map(sns.pointplot)
    g.add_legend()

    g.set(ylim=(0, 1))
    sns.despine(fig=g.fig, left=True)
    g.savefig("output.png")

The output file shows the result.

![output](https://user-images.githubusercontent.com/32548562/31237275-c84a725a-a9f6-11e7-9fe0-dab822ee406b.png)

But of course I want the legend to be displayed properly.

**Comment by mwaskom** [comment]
Its not actually an issue in PairGrid — what's going on is that `pointplot` doesn't add any legend data when it's called without `hue`.

**Comment by NklasF** [comment]
So it is impossible to achieve what I want or is there another solution?

**Comment by mwaskom** [comment]
Anything's possible. In your case I would do

```python
f, axes = plt.subplots(1, 3, figsize=(7.5, 5), sharey=True)
for x, ax in zip(["class", "sex", "who"], axes):
    sns.pointplot(x=x, y="survived", hue="alone", data=titanic, ax=ax)
for ax in axes[1:]:
    ax.set(ylabel="")
    ax.legend_ = None
sns.despine(left=True)
f.tight_layout()
```

**Comment by NklasF** [comment]
Thanks! This works perfectly.
