### ISSUE TITLE
Olgyay Bioclimatic Chart

### ISSUE THREAD

**Issue by balsamshallal** [mwaskom/seaborn#1302]
I was wondering if anyone has drawn the Olgyay bioclimatic chart by using python codes or functions. I'm trying to do that but I do not know how to do it by accurate methods. I have already drawn it by using its figure from some related studies, which it is not an accurate way to get this chart, as it could be seen in the attached photo. so I'm looking for any help on this issue. any advice would be highly appreciated.

**Comment by mwaskom** [comment]
I'm not sure what that is. In any case, it's not a plot that exists in seaborn.
