### ISSUE TITLE
No module 'seaborn.colors'

### ISSUE THREAD

**Issue by beojan** [mwaskom/seaborn#1303]
When importing seaborn:

```
/usr/lib/python3.6/site-packages/seaborn/__init__.py in <module>()
      4 
      5 # Import seaborn objects
----> 6 from .rcmod import *
      7 from .utils import *
      8 from .palettes import *

/usr/lib/python3.6/site-packages/seaborn/rcmod.py in <module>()
      3 import functools
      4 import matplotlib as mpl
----> 5 from . import palettes, _orig_rc_params
      6 
      7 

/usr/lib/python3.6/site-packages/seaborn/palettes.py in <module>()
     11 
     12 from .utils import desaturate, set_hls_values, get_color_cycle
---> 13 from .colors import xkcd_rgb, crayons
     14 
     15 

ModuleNotFoundError: No module named 'seaborn.colors'
```

**Comment by mwaskom** [comment]
What version of seaborn, how did you install it, etc?

**Comment by beojan** [comment]
Current git master, installed with pip.

**Comment by mwaskom** [comment]
I can't replicate this locally and I don't see it replicated on [travis](https://travis-ci.org/mwaskom/seaborn/branches).

Try removing and reinstalling?

**Comment by beojan** [comment]
I tried that. It seems the colors directory doesn't get copied.
It works if I manually copy `seaborn/colors` into `/usr/lib/python3.6/site-packages/seaborn/seaborn/colors`.

**Comment by mwaskom** [comment]
#1304

**Comment by mwaskom** [comment]
FWIW it would have been easier/faster to track down had you been more specific about exactly what you were doing: saying "installed with pip" doesn't discriminate between editable install (which works) and site-packages install (which doesn't).
