### ISSUE TITLE
lmplot drops points with hue `np.nan`

### ISSUE THREAD

**Issue by mnagel** [mwaskom/seaborn#1305]
Please consider the following example of two simple lmplots:

```
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

df = pd.DataFrame(
    {
        "x": [1, 2, 3, 4],
        "y": [1, 2, 3, 4],
        "hue": [1, 2, np.nan, 4],
    }
)

sns.lmplot(x="x", y="y", hue=None, data=df, fit_reg=False)
sns.lmplot(x="x", y="y", hue="hue", data=df, fit_reg=False)
plt.show()

```

![image](https://user-images.githubusercontent.com/961159/31721919-f62d8490-b41a-11e7-94d5-5ce53c5749d2.png)

The datapoint at `x=3` with `hue=np.nan` is (of course) part of the first lmplot, but missing from the lmplot with hue.

I naively expected such points to show up in the graph with their own color for nan-ed values. To reword, when adding `hue=...` I expected to get a superset of information in the plot, but in reality some information was lost.

I assume everything is working as intended, but can this behavior please be documented in the lmplot API -- or is this "obvious" within the seaborn mindset and I am just too new to seaborn?

**Comment by mwaskom** [comment]
It's more of a pandas convention than anything else, as `nan` values in pandas signify "missing". Also it's not quite correct to group all "nan" values into one bin, because in Python `np.nan == np.nan` evaluates to False.
