### ISSUE TITLE
NameError: name 'channel' is not defined

### ISSUE THREAD

**Issue by Metainferno** [mwaskom/seaborn#1307]
I'm trying to use seaborn module to get innitated int he world of ML with the help of ML. I've been trying to use VS2017 and until here, everything is OK. The problem comes when I run the code and when the interpreter arrives at the import line of seaborn, it crashes. The error is the next one:

 
![crashscreenshot](https://user-images.githubusercontent.com/8862406/31796225-001df2dc-b529-11e7-8725-b0f9615459ab.png)

I looked for in the seaborn module folder with the help of bash on windows and the command: __grep -rnw ./ -e "channel"__ but just appear some channel in block comments. I don't understand at all what is happening.

**Comment by mwaskom** [comment]
>  I don't understand at all what is happening.

I don't either. I also don't understand exactly what I'm looking at (i.e what this IDE is). Typically there would be a more detailed error message showing exactly where the error is coming from (in your case, it should be a line using the term "channel". I bet if you find that, it will answer your question. (Maybe "ver detailes"?).

**Comment by Metainferno** [comment]
This is VS2017, and it has installed Anaconda 5.0.0 and Python 3.6.3. And the detailed explanation It hink that doesn't explain anything, or at least I don't understand it:

> NameError esception.
  Message= name 'channel' is not defined
  Stack -->
D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py:2585 in _DebuggerOutput.name
C:\Anaconda3\lib\site-packages\IPython\utils\io.py:41 in IOStream.\_\_init\_\_
C:\Anaconda3\lib\site-packages\IPython\utils\io.py:96 in \<module\>
C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:61 in \<module\>
C:\Anaconda3\lib\site-packages\IPython\terminal\embed.py:15 in \<module\>
C:\Anaconda3\lib\site-packages\IPython\__init__.py:55 in \<module\>
C:\Anaconda3\lib\site-packages\ipywidgets\__init__.py:23 in \<module\>
C:\Anaconda3\lib\site-packages\seaborn\widgets.py:8 in \<module\>
C:\Anaconda3\lib\site-packages\seaborn\__init__.py:16 in \<module\>
D:\Projects\TitanicML\TitanicML\TitanicML.py:7 in \<module\>

**Comment by mwaskom** [comment]
That looks like the error is being raised from `D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py:2585 in DebuggerOutput.name`. It's happening when seaborn tries to import `ipywidgets`. Something seems to be broken either in Visual Studio, or your IPython installation, or how they talk to each other. I'm not sure which.

**Comment by mwaskom** [comment]
Closing as this looks like an issue in the guts of visualstudio.

**Comment by zer0nop** [comment]
https://github.com/Microsoft/PTVS/pull/3259/files

I think they have a bug here. I replaced the body of the `name` property of `_DebuggerOutput` and that fixed it for me.

```
    @property
    def name(self):
        return '<' + self.channel + '>'
```
