### ISSUE TITLE
Heatmap with custom center doesn't preserve vmin/vmax

### ISSUE THREAD

**Issue by dlmackin** [mwaskom/seaborn#1309]
When I set a non-default value for center on a heatmap I expected the ends of the range to stay mapped to the same colours, 

For example, here's some data with a range from -10 to 30:

```
uniform_data = np.random.randint(low=-10, high=30, size=(10, 12))
sns.heatmap(uniform_data, cmap="PuOr", annot=True)
```
![image](https://user-images.githubusercontent.com/1126755/31864539-81701a72-b72c-11e7-9282-baa98b7ff491.png)

I would like to be able to set the center to 0 and have values -10 and 30 remain mapped to the ends of the colour map, like this:

![image](https://user-images.githubusercontent.com/1126755/31864541-8974f238-b72c-11e7-9909-d3411c55dfc5.png)

Instead, I get colours mapped to a range of -30 to 30:

```
sns.heatmap(uniform_data, cmap="PuOr", annot=True, center=0)
# Adding explicit vmin/vmax doesn't help:
# sns.heatmap(uniform_data, cmap="PuOr", annot=True, center=0, vmin=-10, vmax=30)
```
![image](https://user-images.githubusercontent.com/1126755/31864543-8d7502d8-b72c-11e7-9466-d5505b79b39c.png)

This seems to be because the normalization step in  [_determine_cmap_params](https://github.com/mwaskom/seaborn/blob/0beede57152ce80ce1d4ef5d0c0f1cb61d118375/seaborn/matrix.py#L227) can only do a linear interpolation between 2 points. I made the second example using a custom colour map normalizer, like this:

```
class MidpointNormalize(matplotlib.colors.Normalize):
    def __init__(self, vmin=None, vmax=None, midpoint=None, clip=False):
        self.midpoint = midpoint
        matplotlib.colors.Normalize.__init__(self, vmin, vmax, clip)

    def __call__(self, value, clip=None):
        x, y = [self.vmin, self.midpoint, self.vmax], [0, 0.5, 1]
        return np.ma.masked_array(np.interp(value, x, y))

sns.heatmap(uniform_data, cmap="PuOr", annot=True, norm=MidpointNormalize(midpoint=0))
```

If this behaviour makes sense generally and not just for me, I can make a pull request updating the normalization code in [_determine_cmap_params](https://github.com/mwaskom/seaborn/blob/0beede57152ce80ce1d4ef5d0c0f1cb61d118375/seaborn/matrix.py#L227) to do the same.

**Comment by mwaskom** [comment]
I think the current behavior is correct. seaborn isn't going to stop you from doing what you want to do (with a custom normalizer), but it's not going to support it, either.

**Comment by dlmackin** [comment]
Thanks for the reply. I'm not sure I agree -- specifically that `sns.heatmap(data, center=0, vmin=-10, vmax=30)` doesn't respect the vmin parameter feels like a bug to me, and was confusing when I encountered it. That said it's not my call obviously :)

**Comment by mwaskom** [comment]
It respects the vmin parameter in that values below the argument will have the same color, which will be the "minimum" value shown in the colorbar. Wanting a nonlinear color mapping is a different idea, and not one I think is particularly well advised.
