### ISSUE TITLE
new waffleplot api?

### ISSUE THREAD

**Issue by shapiromatron** [mwaskom/seaborn#1310]
I've created  notebook as a strawman for creating waffle plots:
https://github.com/shapiromatron/shapiromatron.github.io/blob/master/notebooks/waffleplot-strawman.ipynb

These aren't as statistically robust as other visuals in seaborn, but they are pretty frequently used in journalism. I'm trying to find the appropriate "home" for these plots, and thought it might be best to propose uptake into the current leader for easy-to-use plots in python. 

If I fixed the API and fleshed out, would you be interested in accepting a PR?

**Comment by mwaskom** [comment]
They look cool but, like many 'infoviz' approaches, are not really a good fit for seaborn. Since your current implementation seems to depend only on numpy/matplotlib, I'd encourage you to wrap it up into a package and put it in PyPI. I expect people will be interested.

**Comment by shapiromatron** [comment]
@mwaskom rather than rolling my own package, any ideas on other more `infoviz` libraries in the python-space? That's what makes seaborn so great, you instantly get access to 20+ plots.

**Comment by mwaskom** [comment]
It's not really my area, unfortunately. I think these tools tend to target the more interactive plotting engines (bokeh, plotly) so I hear less about them. Something like this would probably fit in `bokeh.charts`.

**Comment by shapiromatron** [comment]
Thanks; I'll shop this around a little more, even though I think a static (non-JS) version would be valuable, since they're generally used in static reports which is way I targeted your package.  Great work with seaborn, I use it whenever I can!

**Comment by shapiromatron** [comment]
Not to push it too hard, added a second example w/ a different flavor, more of a stacked-bar chart: https://github.com/shapiromatron/shapiromatron.github.io/blob/master/notebooks/waffleplot-strawman.ipynb
