### ISSUE TITLE
How can I plot distplot given a distribution?

### ISSUE THREAD

**Issue by hu6360567** [mwaskom/seaborn#1311]
Hi,
    I've got a discrete distribution as below.

| Value | Probability |
|-------|-------------|
| 1     | 0.1         |
| 2     | 0.2         |
| 3     | 0.3         |
| 4     | 0.4         |

    Then, How can I plot multiple distributions with distplot or violinplot?
    I've learnt that I can create a sample as below,
```python
np.random.choice(np.arange(values),p=probabilites,size=200)
```
    It doesn't work very well if the size of values and variance are large.

    For example, 2 times of sampling same distribution. 
    They have obvious differences. 
    Also, within one figure, distributions are similar with an offset.
![image](https://user-images.githubusercontent.com/1241597/31992683-81d24192-b9ad-11e7-949f-8d595e36652b.png)
![image](https://user-images.githubusercontent.com/1241597/31992704-90619a32-b9ad-11e7-9b83-fe93f98e013d.png)

    Can I directly plot by using probabilities?

**Comment by mwaskom** [comment]
Not in seaborn, sorry.
