### ISSUE TITLE
lvplot outliers cannot be altered

### ISSUE THREAD

**Issue by miseiler** [mwaskom/seaborn#1320]
Unlike boxplots, which have access to both fliersize by default and flierprops for fine-grained control, lvplot outliers cannot be visually altered from seaborn.lvplot

**Comment by mwaskom** [comment]
Can you be more specific about what your'e trying to do?

**Comment by miseiler** [comment]
Specifically, this line (and similar) in _LVPlotter from seaborn/categorical.py:
`ax.scatter(outliers, np.repeat(x, len(outliers)),marker='d', c=color, **kws)`

I'd like to, for example, alter the outlier attributes by passing a flierprops dict or (better yet) to have the option to alter them myself later a la matplotlib.boxplot where 'fliers' is an accessible property.

**Comment by mwaskom** [comment]
You haven't said what you want to alter.

**Comment by mwaskom** [comment]
You can always alter things in matplotlib after plotting with seaborn. They will end up in the `axes.collections`.

**Comment by cgevans** [comment]
The major issue here, at least for me, is that the marker can't be altered, which seriously hinders my ability to, eg, have overlaid lvplots.  To the best of my understanding, there is no reasonable way to change the markers through axes.collections.

**Comment by cgevans** [comment]
At the moment, I'm using [this commit](https://github.com/cgevans/seaborn/commit/dc8053b1597d538ee4bc98c7ed81bec6da942953) as a fix, but it's not necessarily the ideal solution.
