### ISSUE TITLE
pip installing seaborn 0.8.1 does not include its dependencies; but 0.8.0 does

### ISSUE THREAD

**Issue by tomioueda** [mwaskom/seaborn#1322]
I tried the following on a clean python env:

`$ pip install seaborn --user
Collecting seaborn
Installing collected packages: seaborn
Successfully installed seaborn-0.8.1`

Then in another:

`$ pip install seaborn==0.8.0 --user
Collecting seaborn==0.8.0
Collecting pandas (from seaborn==0.8.0)
  Using cached pandas-0.21.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied: python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pandas->seaborn==0.8.0)
Collecting numpy>=1.9.0 (from pandas->seaborn==0.8.0)
  Using cached numpy-1.13.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied: pytz>=2011k in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pandas->seaborn==0.8.0)
Installing collected packages: numpy, pandas, seaborn
  Found existing installation: seaborn 0.8.1
    Uninstalling seaborn-0.8.1:
      Successfully uninstalled seaborn-0.8.1
Successfully installed numpy-1.13.3 pandas-0.21.0 seaborn-0.8`

Is seaborn 0.8.1 intentionally not installing its dependencies?

**Comment by mwaskom** [comment]
Nothing relevant changed in the setup.py between those verisons: https://github.com/mwaskom/seaborn/compare/v0.8.0...v0.8.1#diff-2eeaed663bd0d25b7e608891384b7298

I also can't replicate the behavior you see. So...I don't know.
