### ISSUE TITLE
TypeError: invalid type promotion with datetime coordinate

### ISSUE THREAD

**Issue by kdebrab** [mwaskom/seaborn#1325]
With pandas 0.21.0, the following fails (whereas it works fine with pandas 0.20.3):
```python
import pandas as pd
import seaborn as sns

index = pd.date_range('2017-06-01', periods=16)
df = pd.DataFrame(index=index, columns=['a', 'b', 'c'])
df.iloc[:2, 0] = '1000'
df.iloc[[2, 3, 6, 8, 10, 12, 14, 15], 1] = '1000'
df.iloc[[4, 5, 9, 13], 2] = '1000'
df.iloc[[7, 11], 1] = '1001'
df.index.name = 'Datetime'
df.columns.name = 'Element'
df = df.stack().rename('Event').reset_index()
df['Event / Element'] = df['Event'] + ' / ' + df['Element']
sns.stripplot(x='Datetime', y='Event / Element', hue='Element', data=df, orient='h')
```
The reason is that pandas no longer registers the matplotlib converter for datetimes on import.

The fix is to explicitly register the converters before plotting:
```python
from pandas.tseries import converter
converter.register()
```
The same fix has been implemented in xarray for a similar issue: https://github.com/pydata/xarray/issues/1661.

I reported this to pandas as https://github.com/pandas-dev/pandas/issues/18212.

**Comment by mwaskom** [comment]
My understanding is that this is a bug in pandas?

**Comment by kdebrab** [comment]
I'm not so sure: see https://github.com/matplotlib/matplotlib/issues/9610#issuecomment-343247007. It seems like they won't change it back anytime soon...

So, my impression is that in order to get seaborn plots with pandas datetime working again, the preferred option is to register the converter inside seaborn, similarly to what has been done in xarray.

**Comment by mwaskom** [comment]
It sounds like the correct path forward is to have this handled inside matplotlib itself (and it looks like the momentum is in that direction). I'm not sure it makes sense to do it in the seaborn layer.

**Comment by TomAugspurger** [comment]
Agreed, this is something to be worked out between pandas and matpltolib. Seaborn is an innocent bystander.

**Comment by mwaskom** [comment]
For future reference, looks like matplotlib handled this here: https://github.com/matplotlib/matplotlib/pull/9779
