### ISSUE TITLE
Faster pcolormesh plotting

### ISSUE THREAD

**Issue by gpratt** [mwaskom/seaborn#1327]
Hello, 

I've really enjoyed the heatmap code in seaborn, it makes plotting a dream.  However, I'm making publication quality figures, and need to do a bit of editing in illustrator after the matplotlib figures have been made.  When I made even a reasonably sized heatmap Illustrator just can't open the thing.  

Doing some digging it looks like pcolormesh blows up file sizes.  It looks like recently pcolorfast has been added to matplotlib.  I've been prototyping that out outside of seaborn, and it looks like we might be able to use it inside of seaborn.  

Happy to do the legwork / pull request on this, but before diving in, I just wanted to check if there are any reasons you might have to not switch over from mesh to fast.  

Thanks,

**Comment by mwaskom** [comment]
If it's a recent addition in matplotlib, it can't be used in seaborn, which needs to maintain compatibility with older versions. 

Are you saving to PDF or eps? If so, you probably want to do rasterized=True in your heatmap (and save with a high dpi).
