### ISSUE TITLE
seaborn.distplot() yaxis not automatically rescaling

### ISSUE THREAD

**Issue by tsherwen** [mwaskom/seaborn#1329]
When doing batches of plots using Seaborn, sometimes it is unavoidable that data is provided without an increasing maximum frequency value in the PDF. When this happens the created plot yaxis cuts off data. However, sns.distplot() is fine if data is provided with increasing maximum. Is this behaviour an issue?

I've posted an example/more detail as a question on stackoverflow:
https://stackoverflow.com/questions/47352929/can-a-seaborn-distplot-yaxis-be-automatically-rescaled

**Comment by mwaskom** [comment]
See https://github.com/mwaskom/seaborn/pull/1272
