### ISSUE TITLE
Barplot edgecolor argument applies to the first patch

### ISSUE THREAD

**Issue by maximtrp** [mwaskom/seaborn#1330]
I've updated matplotlib to the latest version (2.1.0) and noticed a bug in `seaborn.barplot()` function behaviour. Earlier, I was able to set the edgecolors and linewidths of all patches. Now, `linewidth` argument changes only the first patch or group of patches (when using `hue`). 

Code to reproduce (from tutorial):
```
tips = sn.load_dataset("tips")
ax = sn.barplot("day", "total_bill", data=tips, linewidth=2, facecolor=(1, 1, 1, 0),errcolor=".2", edgecolor=".2")
```

Screenshots:
https://imgur.com/a/ZfSeE
https://imgur.com/a/yRpAd

Versions of components:
Matplotlib 2.1.0
Seaborn 0.8.1

**Comment by mwaskom** [comment]
Thanks for reporting. Can you take a look through recent matplotlib prs and try to figure out what changed?

**Comment by maximtrp** [comment]
Sorry. Not a bug of seaborn package. It is related to matplotlib bar() method. I've already submitted an issue to its repository.
