### ISSUE TITLE
Facetting boxplot with hue gives an error: unexpected keyword argument 'label'

### ISSUE THREAD

**Issue by DominikMueller64** [mwaskom/seaborn#1334]
An example:

    %matplotlib inline
    tips = sns.load_dataset("tips")
    g = sns.FacetGrid(data=tips, col='time', hue='sex')
    # g.map_dataframe(sns.pointplot, x='day', y='tip')   # works!
    g.map_dataframe(sns.boxplot, x='day', y='tip')

This gives the error:
    
    TypeError: boxplot() got an unexpected keyword argument 'label'

I'm using version 0.8.1 of seaborn and 2.1.0 of matplotlib.

**Comment by mwaskom** [comment]
In both cases, you should be passing the hue variable to the function, not to the FacetGrid.

**Comment by DominikMueller64** [comment]
I was following the examples in the [documentation](http://seaborn.pydata.org/generated/seaborn.FacetGrid.html#seaborn.FacetGrid) of FacetGrid, were hue is always given to `FacetGrid`.  There seems to be a lack of understanding of the interface on my part.

**Comment by mwaskom** [comment]
I appreciate that it’s not obvious but that is the answer. Actually the even easier thing to do would be to use `factorplot`, which will take care of setting up the FacetGrid for you.
