### ISSUE TITLE
Swarmplot online docs uses "dodge" in example for "split" keyword

### ISSUE THREAD

**Issue by tamir-dingjan** [mwaskom/seaborn#1336]
The  [online docs page for swarmplot](https://seaborn.pydata.org/generated/seaborn.swarmplot.html#) uses "dodge" in an example of the behaviour of "split".

Copied from the doc page:

> **_Split_** each level of the hue variable along the categorical axis:
> 
> > ax = sns.swarmplot(x="day", y="total_bill", hue="smoker",
> ...                    data=tips, palette="Set2", **_dodge_**=True)

**Comment by mwaskom** [comment]
Duplicate of https://github.com/mwaskom/seaborn/issues/1278
