### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by fred2008** [mwaskom/seaborn#1339]
When I use kdeplot , there is error of:
**ValueError:** zero-size array to reduction operation minimum which has no identity

**The terminal operation & error message is as follows :**

--  x2
array([ 100.  ,  100.  ,  100.  ,   83.33,   98.68,  100.  ,  100.  ,
        100.  ,   99.03,  100.  ,   75.  ,  100.  ,  100.  ,  100.  ,
        100.  ,  100.  ,  100.  ,  100.  ,  100.  ,  100.  ,  100.  ,
        100.  ,   75.  ,  100.  ,   96.  ])
--  y2
array([ 100.  ,  100.  ,  100.  ,   83.33,   98.68,  100.  ,  100.  ,
        100.  ,   99.03,  100.  ,   50.  ,  100.  ,  100.  ,  100.  ,
        100.  ,  100.  ,  100.  ,  100.  ,  100.  ,  100.  ,   98.36,
        100.  ,   75.  ,  100.  ,  100.  ])
--  sns.kdeplot(data=x2, data2=y2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zy/miniconda2/lib/python2.7/site-packages/seaborn/distributions.py", line 638, in kdeplot
    cbar, cbar_ax, cbar_kws, ax, **kwargs)
  File "/home/zy/miniconda2/lib/python2.7/site-packages/seaborn/distributions.py", line 388, in _bivariate_kdeplot
    cset = contour_func(xx, yy, z, n_levels, **kwargs)
  File "/home/zy/miniconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1898, in inner
    return func(ax, *args, **kwargs)
  File "/home/zy/miniconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5825, in contour
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "/home/zy/miniconda2/lib/python2.7/site-packages/matplotlib/contour.py", line 865, in __init__
    self._process_levels()
  File "/home/zy/miniconda2/lib/python2.7/site-packages/matplotlib/contour.py", line 1199, in _process_levels
    self.vmin = np.amin(self.levels)
  File "/home/zy/miniconda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2372, in amin
    out=out, **kwargs)
  File "/home/zy/miniconda2/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
**ValueError**: zero-size array to reduction operation minimum which has no identity

**Comment by mwaskom** [comment]
I would need more information to diagnose the error (a reproducible example and the versions of the relevant libraries on your system), but I can say that it is apparent that the dataset you're using is extremely non-gaussian. The error is ultimately arising from the fact that it dramatically violates the assumptions of gaussian kernel density estimation, which shouldn't be used here.

**Comment by fred2008** [comment]
Hi, @mwaskom 
        Appreciate for your reply. 
        seaborn.kdeplot can just be used for gaussion variable ?
        can you give me some advice to visualize unknow 2-variable dense ? The demo of seaborn always use random.normal to generate data, but not the real data? For example , the location of hospital (represent by x, y ), how to make a dense plot of it  to show which area the hospital is sufficient ?

**Comment by mwaskom** [comment]
> seaborn.kdeplot can just be used for gaussion variable ?

The kdeplot fits a Gaussian kernel density estimate to your data. When using a statistical model to visualize your data, you have to ask whether the data satisfy the assumptions of your model. It's not much different than thinking about whether you should show a linear regression when you know that there is a highly nonlinear relationship between your variables. So even without the error, you would likely have generated a plot that is misleading about what the actual structure of your data is.

The actual problem can be attributed to the fact that, in violating the assumptions of the Gaussian KDE, you've also violated the assumptions of the reference rule used to automatically select the bandwidth (see the distributions tutorial in the seaborn docs if you don't know what that is). If you drop into the debugger and poke around, you can see that your data has caused the reference rule inside statsmodels to produce use `nan` as the bandwith. This causes the density array to be an array of `nan`, which crashes matplotlib.

One way around this is to specify a bandwidth. For example, you can do

```
sns.kdeplot(data=x2, data2=y2, cut=2, bw=.5, shade_lowest=False)
```

and it will generate a plot:

![image](https://user-images.githubusercontent.com/315810/33673834-e0d932c4-da7b-11e7-8969-4b661f57044d.png)

However, by adding a scatterplot with your data, you can see that the gaussian density estimate doesn't correspond at all to the data:

```
sns.kdeplot(data=x2, data2=y2, cut=2, bw=.5, shade_lowest=False)
plt.scatter(x2, y2)
```

![image](https://user-images.githubusercontent.com/315810/33673885-03880872-da7c-11e7-8341-d098898277b1.png)

My advice is to try a different approach.
