### ISSUE TITLE
Can I use jointplot in a facetgrid?

### ISSUE THREAD

**Issue by xguse** [mwaskom/seaborn#1341]
I would really love to do this with some data I am working with but it always plots the empty grid and then produces separate plots sequentially.

Is there a way I can pass jointgrid the axe or subplot that I want each iteration to draw on?

This is whats going on now:

![](https://i.imgur.com/IwU8eYz.png)

**Comment by mwaskom** [comment]
No, you cannot, because `jointplot` involves multiple axes.
