### ISSUE TITLE
Allow hues in strip and swarm plots if there is no grouping variable

### ISSUE THREAD

**Issue by gkunter** [mwaskom/seaborn#1343]
The default behavior of `_CategoricalPlotter.establish_variables()` if only a data variable, but no grouping variable is submitted is  to ignore any hue parameter. This corresponds to the condition described as "Option 2a: We are plotting a single set of data". The following code illustrates this default behavior:

```
import seaborn as sns
tips = sns.load_dataset("tips")
sns.swarmplot(x="total_bill", hue="sex", data=tips)
```

![image](https://user-images.githubusercontent.com/12086562/33669121-e04f9282-daa1-11e7-8145-2b30bd6cc7d2.png)

To me, this behavior was unexpected, as the API documentation doesn't mention that hues are only available in combination with grouping. Still, I think it would be a useful addition to allow for different hues even if no grouping variable is specified, for at least two reasons:

- In contrast to grouping using `sex` as a grouping variable, the output would be more compact
- The shape of the swarm plot wouldn't change if different hue variables are used, which might facilitate comparisons between these variables

I've added this feature to my fork by changing [lines 174](https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L174) to [lines 180](https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L180)  of `categorical.py` so that a `hue` variable becomes the single element of `plot_hues`. Now, `sns.swarmplot(x="total_bill", hue="sex", data=tips)` produces this output: 

![image](https://user-images.githubusercontent.com/12086562/33669022-988b09f4-daa1-11e7-825c-bd01c9842761.png)

As it is, this addition applies to all descendants of `_CategoricalPlotter`, i.e. it's not restricted to strip and swarm plots, but changes the current behavior also of e.g. box, violin, and bar plots. If that's not a desired behavior, the change may only be applied to the `establish_variables()` method of `_SwarmPlotter` and `_StripPlotter`. 

My changes don't break any of the tests from `test_categorical.py`. I have to admit that I don't understand the testing framework well enough to come up with my own tests, but as the current behavior is to simply ignore the `hue` argument if only either `x` or `y` is provided, I'd think that this addition runs only little risk of breaking existing code (which is probably a horrible case of "famous last words"). 

All this boils down to this: Is this a welcome change of the current behavior? And if so, what do I have to do next with the changes in my fork – simply open a pull request?

**Comment by mwaskom** [comment]
I'm fairly averse to changing something this deep in the guts of the categorical plotters without a really compelling reason, just because there's a high potential for unintended consequences given that the rest of the code was written assuming that hue subsets exist only when there is a categorical grouping variable.

BTW this works:

```python
tips = sns.load_dataset("tips")
sns.swarmplot(x="total_bill", y=[""] * len(tips), hue="sex", data=tips)
```
![image](https://user-images.githubusercontent.com/315810/33674153-b48959dc-da7c-11e7-8642-0034b0f80163.png)

**Comment by gkunter** [comment]
Thanks for the trick with the dummy grouping variable, which is what I'll probably use in the future. And I totally understand your arguments against this change.
