### ISSUE TITLE
FacetGrid has separate xticks for each graph in kde_joyplot.py example

### ISSUE THREAD

**Issue by markberger** [mwaskom/seaborn#1344]
I'm running seaborn 0.8.1 with matplotlib 2.1.0, and I'm working from the [kde_joyplot.py](https://seaborn.pydata.org/examples/kde_joyplot.html) example. When I recreate this example, the xticks are inserted for each density plot instead of being shared along the bottom:

![download](https://user-images.githubusercontent.com/965436/33844866-7f7dd4a6-de56-11e7-80b2-a52e12d42781.png)

I haven't been able to figure out how to turn off all the xticks expect for the bottom set. It would be nice to fix the example such that the there are only 1 set of xticks.

**Comment by mwaskom** [comment]
This is https://github.com/matplotlib/matplotlib/issues/9664
