### ISSUE TITLE
bar plot in log scale

### ISSUE THREAD

**Issue by MarziehLenjaniNew** [mwaskom/seaborn#1345]
previous versions of seaborn could plot bar plot while y axis is in log scale but the new versions can not. you can try the following code.

import seaborn as sns
sns.set_style("whitegrid")
tips = sns.load_dataset("tips")
ax = sns.barplot(x="day", y="total_bill", data=tips)
ax.set_yscale('log')

**Comment by mwaskom** [comment]
This works fine for me. I'll need more information about what's happening on your end before I can help..

**Comment by MarziehLenjaniNew** [comment]
When I comment out the last line (ax.set_yscale('log')) I get this picture
![bargraph](https://user-images.githubusercontent.com/30010475/33856171-44f01d28-de95-11e7-815d-59bb0212c4b0.png)

but When I uncomment the last line I get this graph
![barplotlog](https://user-images.githubusercontent.com/30010475/33856247-8266744a-de95-11e7-92d0-bd2aae586ba9.png)

**Comment by mwaskom** [comment]
I think this is a bug in matplotlib. Search on their github, there was some issue where they changed how the bars were defined to include 0, but then that caused problems with log axes. It worked for me on matplotlib 2.0.2 ... I forget if the bug is on an earlier or later version.

**Comment by MarziehLenjaniNew** [comment]
Yes, you are right. I downgraded my matplotlib and it worked. Thank you.
