### ISSUE TITLE
Feature request: make factorplot able to accept axes without creating a FacetGrid object

### ISSUE THREAD

**Issue by lethargi** [mwaskom/seaborn#1346]
Right now calling `seaborn.factorplot` with the `ax` keyword argument produces the factor plot in the specified grid. but it also creates the `FacetGrid` in a new figure. It would be nice if `factorplot` would recognize that an axes has been given an not create the new figure.

**Comment by mwaskom** [comment]
Sorry, the only reason this "works" is because it's passing additional kwargs down to the underlying seaborn function that has an `ax` kwarg. You should use that function if you want to plot on a specific axes.
