### ISSUE TITLE
Could we set width parameter for stripplot as well?

### ISSUE THREAD

**Issue by bli25wisc** [mwaskom/seaborn#1348]
I want to plot boxplots and stripplots together. To make the box plots thinner, I set width = 0.3. However, I could not set width for stripplots (the width is hard coded as 0.8). As a result, the stripplots and boxplots are separated.

Thanks!
Bo

**Comment by mwaskom** [comment]
I can't help you without a reproducible example that shows what you're doing. This might be a better question for stackoverflow.
