### ISSUE TITLE
axis on the joinplot marginals

### ISSUE THREAD

**Issue by rbpisupati** [mwaskom/seaborn#1350]
Hi, 

Can you help me how to also provide axis on marginal histogram plots (to see the bar heights in the histogram). Here is my code and the output.

` lims_plt = (-0.05,1.05) `
`p = sns.JointGrid(x = r_permeth[1:1000], y = c_permeth[1:1000], xlim = lims_plt, ylim = lims_plt)`
`p = p.plot_joint(sns.kdeplot, cmap="BuPu" )`
`p.ax_joint.plot(lims_plt, lims_plt, ':k')`
`_ = p.ax_marg_x.hist(p.x, bins = np.arange(0, 1.1, 0.05))`
`_ = p.ax_marg_y.hist(p.y, bins = np.arange(0, 1.1, 0.05), orientation="horizontal")`

I tried adding in the ax = True to this, `p = p.plot_marginals(sns.distplot, kde=False, ax = True)`. But didnt seem to take it.

![jointplot](https://user-images.githubusercontent.com/11807889/34208064-337a8390-e58d-11e7-9b65-d9e74b9d5437.png)

Thank you in advance,

Rahul

**Comment by mwaskom** [comment]
I’d suggest you ask on StackOverflow, the github issues are for bug reports
