### ISSUE TITLE
stripplot orientation is throwing a value error

### ISSUE THREAD

**Issue by arunkumar413** [mwaskom/seaborn#1351]
The orientation parameter 'h' is throwing a value error : ValueError: could not convert string to float:

Here is the complete output of the error and the below is the screenshot

_ValueError                                Traceback (most recent call last)
<ipython-input-70-3c8a30ea37f8> in <module>()
----> 1 sns.stripplot(x='account', y="Feb",data= sales, orient="h")

/usr/lib/python3/dist-packages/seaborn/categorical.py in stripplot(x, y, hue, data, order, hue_order, jitter, split, orient, color, palette, size, edgecolor, linewidth, ax, **kwargs)
   2559                        linewidth=linewidth))
   2560 
-> 2561     plotter.plot(ax, kwargs)
   2562     return ax
   2563 

/usr/lib/python3/dist-packages/seaborn/categorical.py in plot(self, ax, kws)
   1169     def plot(self, ax, kws):
   1170         """Make the plot."""
-> 1171         self.draw_stripplot(ax, kws)
   1172         self.add_legend_data(ax)
   1173         self.annotate_axes(ax)

/usr/lib/python3/dist-packages/seaborn/categorical.py in draw_stripplot(self, ax, kws)
   1149                     ax.scatter(cat_pos, strip_data, **kws)
   1150                 else:
-> 1151                     ax.scatter(strip_data, cat_pos, **kws)
   1152 
   1153             else:

/usr/lib/python3/dist-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1892                     warnings.warn(msg % (label_namer, func.__name__),
   1893                                   RuntimeWarning, stacklevel=2)
-> 1894             return func(ax, *args, **kwargs)
   1895         pre_doc = inner.__doc__
   1896         if pre_doc is None:

/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, **kwargs)
   4055                 self.set_ymargin(0.05)
   4056 
-> 4057         self.add_collection(collection)
   4058         self.autoscale_view()
   4059 

/usr/lib/python3/dist-packages/matplotlib/axes/_base.py in add_collection(self, collection, autolim)
   1754 
   1755         if autolim:
-> 1756             self.update_datalim(collection.get_datalim(self.transData))
   1757 
   1758         collection._remove_method = lambda h: self.collections.remove(h)

/usr/lib/python3/dist-packages/matplotlib/collections.py in get_datalim(self, transData)
    217             transOffset = transOffset.get_affine()
    218 
--> 219         offsets = np.asanyarray(offsets, np.float_)
    220         if np.ma.isMaskedArray(offsets):
    221             offsets = offsets.filled(np.nan)

/usr/lib/python3/dist-packages/numpy/core/numeric.py in asanyarray(a, dtype, order)
    581 
    582     """
--> 583     return array(a, dtype, copy=False, order=order, subok=True)
    584 
    585 

ValueError: could not convert string to float: 'Blue Inc'

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

/usr/local/lib/python3.5/dist-packages/IPython/core/pylabtools.py in <lambda>(fig)
    236 
    237     if 'png' in formats:
--> 238         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    239     if 'retina' in formats or 'png2x' in formats:
    240         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

/usr/local/lib/python3.5/dist-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    120 
    121     bytes_io = BytesIO()
--> 122     fig.canvas.print_figure(bytes_io, **kw)
    123     data = bytes_io.getvalue()
    124     if fmt == 'svg':

/usr/lib/python3/dist-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2190                     orientation=orientation,
   2191                     dryrun=True,
-> 2192                     **kwargs)
   2193                 renderer = self.figure._cachedRenderer
   2194                 bbox_inches = self.figure.get_tightbbox(renderer)

/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, *args, **kwargs)
    543 
    544     def print_png(self, filename_or_obj, *args, **kwargs):
--> 545         FigureCanvasAgg.draw(self)
    546         renderer = self.get_renderer()
    547         original_dpi = renderer.dpi

/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py in draw(self)
    462 
    463         try:
--> 464             self.figure.draw(self.renderer)
    465         finally:
    466             RendererAgg.lock.release()

/usr/lib/python3/dist-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     61     def draw_wrapper(artist, renderer, *args, **kwargs):
     62         before(artist, renderer)
---> 63         draw(artist, renderer, *args, **kwargs)
     64         after(artist, renderer)
     65 

/usr/lib/python3/dist-packages/matplotlib/figure.py in draw(self, renderer)
   1141 
   1142             mimage._draw_list_compositing_images(
-> 1143                 renderer, self, dsu, self.suppressComposite)
   1144 
   1145             renderer.close_group('figure')

/usr/lib/python3/dist-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, dsu, suppress_composite)
    137     if not_composite or not has_images:
    138         for zorder, a in dsu:
--> 139             a.draw(renderer)
    140     else:
    141         # Composite any adjacent images together

/usr/lib/python3/dist-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     61     def draw_wrapper(artist, renderer, *args, **kwargs):
     62         before(artist, renderer)
---> 63         draw(artist, renderer, *args, **kwargs)
     64         after(artist, renderer)
     65 

/usr/lib/python3/dist-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2407             renderer.stop_rasterizing()
   2408 
-> 2409         mimage._draw_list_compositing_images(renderer, self, dsu)
   2410 
   2411         renderer.close_group('axes')

/usr/lib/python3/dist-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, dsu, suppress_composite)
    137     if not_composite or not has_images:
    138         for zorder, a in dsu:
--> 139             a.draw(renderer)
    140     else:
    141         # Composite any adjacent images together

/usr/lib/python3/dist-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     61     def draw_wrapper(artist, renderer, *args, **kwargs):
     62         before(artist, renderer)
---> 63         draw(artist, renderer, *args, **kwargs)
     64         after(artist, renderer)
     65 

/usr/lib/python3/dist-packages/matplotlib/collections.py in draw(self, renderer)
    872     def draw(self, renderer):
    873         self.set_sizes(self._sizes, self.figure.dpi)
--> 874         Collection.draw(self, renderer)
    875 
    876 

/usr/lib/python3/dist-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     61     def draw_wrapper(artist, renderer, *args, **kwargs):
     62         before(artist, renderer)
---> 63         draw(artist, renderer, *args, **kwargs)
     64         after(artist, renderer)
     65 

/usr/lib/python3/dist-packages/matplotlib/collections.py in draw(self, renderer)
    286         self.update_scalarmappable()
    287 
--> 288         transform, transOffset, offsets, paths = self._prepare_points()
    289 
    290         gc = renderer.new_gc()

/usr/lib/python3/dist-packages/matplotlib/collections.py in _prepare_points(self)
    259                 offsets = list(zip(xs, ys))
    260 
--> 261         offsets = np.asanyarray(offsets, np.float_)
    262         offsets.shape = (-1, 2)             # Make it Nx2
    263 

/usr/lib/python3/dist-packages/numpy/core/numeric.py in asanyarray(a, dtype, order)
    581 
    582     """
--> 583     return array(a, dtype, copy=False, order=order, subok=True)
    584 
    585 

ValueError: could not convert string to float: 'Blue Inc'_

![stripplot](https://user-images.githubusercontent.com/7776779/34295060-547529d8-e731-11e7-8924-4f7d8d4ba949.png)

**Comment by arunkumar413** [comment]
Also by defult the stipplot is showing up as horizontal.

**Comment by mwaskom** [comment]
You can’t draw a horizontal plot if your x variable is categorical.
