### ISSUE TITLE
list as input in jointplot

### ISSUE THREAD

**Issue by Pompelmo** [mwaskom/seaborn#1352]
**Not blocking error, and maybe intended, but just FYI.**
I wanted to use jointplot with two list and gives error when dropna=True.

Example code:
```import seaborn as sns
a = [1,2,3]
b = [4,5,6]
sns.jointplot(a, b)
```

produce the error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-4-86833c44289b> in <module>()
----> 1 sns.jointplot(a, b)

~/python3.5/site-packages/seaborn/axisgrid.py in jointplot(x, y, data, kind, stat_func, color, size, ratio, space, dropna, xlim, ylim, joint_kws, marginal_kws, annot_kws, **kwargs)
   2239     grid = JointGrid(x, y, data, dropna=dropna,
   2240                      size=size, ratio=ratio, space=space,
-> 2241                      xlim=xlim, ylim=ylim)
   2242 
   2243     # Plot the data using the grid

~/python3.5/site-packages/seaborn/axisgrid.py in __init__(self, x, y, data, size, ratio, space, dropna, xlim, ylim)
   1686         if dropna:
   1687             not_na = pd.notnull(x) & pd.notnull(y)
-> 1688             x = x[not_na]
   1689             y = y[not_na]
   1690 

TypeError: only integer scalar arrays can be converted to a scalar index
```

I guess the problem is that it doesn't convert the lists in np arrays, indeed

```sns.jointplot(np.array(a), np.array(b))```
and ```sns.jointplot(a, b, dropna=False)```

work correctly.

versions:
```
python 3.5.2
matplotlib 2.1.0
seaborn 0.8.1
```

Many thanks
Caterina

**Comment by ravimakhija** [comment]
It seems as if list inputs should indeed be permitted, given that they are accepted elsewhere in the seaborn library (such as for `lvplot` and `rugplot`) and also since they are converted to numpy.ndarray objects anyway after the error-causing code. 

I have added a pull request (#1356) that addresses this issue by converting the x and y parameters to numpy.ndarray objects earlier.
