### ISSUE TITLE
Barplot does not draw edges on all bars

### ISSUE THREAD

**Issue by Auerilas** [mwaskom/seaborn#1353]
Hi, I have a weird bug where setting edgecolor in a bar plot only draws edges on the first bar. For example:

```
import seaborn as sns
import matplotlib.pyplot as plt
tips = sns.load_dataset("tips")
ax = sns.barplot("day", "total_bill", data=tips,
    linewidth=2.5, facecolor=(1, 1, 1, 0),
    errcolor=".2", edgecolor=".2")
plt.show()
```
![figure_1](https://user-images.githubusercontent.com/9372234/34392619-89f25b44-eb0a-11e7-8c55-12910497b39f.png)

Running matplotlib 2.1, seaborn 0.8.1, and python 3.5.4

Thoughts?

**Comment by mwaskom** [comment]
I can't reproduce with matplotlib 2.1.1. Maybe a bug they fixed between 2.1.0 and 2.1.1?

**Comment by mwaskom** [comment]
Good dog, by the way.

**Comment by Auerilas** [comment]
Yup, updating to 2.1.1 fixed it. Easy enough.

Thanks! Mine spends a lot of time sitting on my laptop too.
