### ISSUE TITLE
Apply context/style to already existing figures

### ISSUE THREAD

**Issue by sotte** [mwaskom/seaborn#1355]
This is a feature request to apply styles/contexts to an already existing figure.
(I you think that seaborn does not need this feature, just close the issue. No problem :))

Often I want to store the same plot with different styles/contexts (`poster`, `paper`, whatever).
`sns.set_context('paper')` is great to change the overall style of a figure.
It would be even better if one could apply a style after the fig was created.
So I could create a plot, maybe display it in a jupyter notebook, and then store a poster and a talk version of the plot on disk. 

The interface for this could look something like this:
```
fig, ax = plt.subplots()
# create awesome plot ...

with sns.apply_context(fig, 'paper') as f:
    f.savefig('state_of_the_art__paper.png')

with sns.apply_context(fig, 'poster') as f:
    f.savefig('state_of_the_art__poster.png')
```

What do you think?

**Comment by mwaskom** [comment]
I don't think this is really possible. For seaborn to do this, it would need to reach down and modify attributes on matplotlib artists that have been previously added to the Axes. But once the artists have been added by some function that creates them, I don't think there's any way to know whether they inherited their properties from the rcParams or whether they were specified by the user during creation. Supporting this would require matplotlib to work a different way than it does.

In your case, why not do

```python
for context in ["paper", "poster"]:
    with sns.plotting_context(context):
        f, ax = plt.subplots()

    # Make the plot ...

    f.savefig(f"state_of_the_art_{context}.png")
```

It's only a slight rearrangement of things.

**Comment by sotte** [comment]
I was afraid that that would be the case.
The solution you propose is pretty much the workaround I use. It feels a bit clumsy but it works.

Thanks!
