### ISSUE TITLE
Logit scale is broken

### ISSUE THREAD

**Issue by willvousden** [mwaskom/seaborn#1357]
Matplotlib has (slightly buggy) support for a [logit ](https://en.wikipedia.org/wiki/Logit) scale, but this doesn't seem to work in Seaborn, even using a workaround for the bug in MPL.

I expect the following code to produce some bars, but instead I see a blank set of axes:

```
import matplotlib.pyplot as pp
import numpy as np
import pandas as pd
import seaborn as sb

from matplotlib.ticker import NullFormatter
from scipy.special import logit, expit

# Labels A to Z, and values drawn from a logit-normal distribution.
labels = list(map(chr, range(ord('A'), ord('Z') + 1)))
data = expit(np.random.randn(len(labels)) * 10)
frame = pd.DataFrame({'label': labels,
                      'value': data})

f, a = pp.subplots()
sb.barplot(data=frame, x='label', y='value', ax=a)

# MPL bug with logit scale:
# https://stackoverflow.com/questions/43553735
# https://github.com/matplotlib/matplotlib/issues/6789
a.set_yscale('logit')
a.spines['left']._adjust_location()
a.yaxis.set_minor_formatter(NullFormatter())

pp.show(f)
```

![logit_scale](https://user-images.githubusercontent.com/152388/34886895-83f1f312-f7bc-11e7-9738-f50bb5ea5b09.png)

Without setting the scale to `logit`, it works as expected:

![linear_scale](https://user-images.githubusercontent.com/152388/34886913-8da73e6c-f7bc-11e7-8bea-f9305420540c.png)

I realise that MPL's implementation of this scale is a bit buggy (see https://github.com/matplotlib/matplotlib/issues/6789), but even with the workaround, it doesn't seem to work in Seaborn.

Is this a consequence of the bug in MPL, or is it an independent bug in Seaborn?  This is under MPL 2.0.0 and Seaborn 0.8.1, running on Python 2.7, and using the Qt4Agg backend.

**Comment by mwaskom** [comment]
This doesn't work either:

```python
f, ax = plt.subplots()
ax.bar(np.arange(10), np.linspace(0, 1, 10))
ax.set_yscale('logit')
```

So I'm guessing not seaborn related.

**Comment by willvousden** [comment]
I should've tried that before creating the issue! Thanks.
