### ISSUE TITLE
How to plot double y axis in FacetGrid?

### ISSUE THREAD

**Issue by hu6360567** [mwaskom/seaborn#1359]
I've created a function for map_DataFrame, however, the 2nd yaxis shows tick labels on every subplot, and `add_legend` cannot show 2nd line.
![image](https://user-images.githubusercontent.com/1241597/34968326-95206aa8-faa3-11e7-87db-7767c3129dba.png)

**Comment by mwaskom** [comment]
I'd recommend making a complete and self-contained example and asking on StackOverflow.
