### ISSUE TITLE
seaborn.set() does not control heatmap colorbar ticklabel font

### ISSUE THREAD

**Issue by CharlesSiqiLiang** [mwaskom/seaborn#1363]
I encountered a problem when trying to customize the aesthetics of a heatmap using seaborn.set(). I activated text rendering by LaTeX and set Helvetica as the font. The x- and y-labels and ticklabels were changed to Helvetica as expected. However, the font of the ticklabels of the colorbar remained unchanged.

Seaborn version: 0.8
Python version: 3.6.2

```python
import numpy as np
import seaborn as sns

sns.set(rc={'text.usetex':True, 'font.family':'sans-serif', 'font.sans-serif':'Helvetica'})

matrix = np.random.random((20, 20)) # Randomly generated data
ax = sns.heatmap(matrix, cmap='Greens')

ax.set_xlabel('The x-axis', labelpad=8)
ax.set_ylabel('The y-axis', labelpad=8)
```
![seaborn_1](https://user-images.githubusercontent.com/16009282/35411548-2bd0b30a-01e7-11e8-9ea5-7f7349257321.png)

I also tried setting the font argument of seaborn.set() and setting the font from matplotlib.rc(), but neither of them worked.

```python
import matplotlib as mpl

sns.set(rc={'text.usetex':True, 'font.family':'sans-serif', 'font.sans-serif':'Helvetica'}, font='Helvetica')
mpl.rc('font',**{'family':'sans-serif','sans-serif':'Helvetica'})

matrix = np.random.random((20, 20))
ax = sns.heatmap(matrix, cmap='Greens')

ax.set_xlabel('The x-axis', labelpad=8)
ax.set_ylabel('The y-axis', labelpad=8)
```

![seaborn_2](https://user-images.githubusercontent.com/16009282/35411792-0eb22f14-01e8-11e8-864b-d2a7b1400ac3.png)

Is there a way to control the font of the ticklables of the colorbar?

**Comment by mwaskom** [comment]
I think two things are happening:

First, when `text.usetex` is `True`, the axes (including the colorbar axes) are initialized with tex tick labels, but the `ax.set_*` functions add basic text; you can see this yourself by doing

```
f, ax = plt.subplots()
ax.pcolormesh(matrix)
ax.set_xticks([5, 10])
ax.set_xticklabels([5, 10])
ax.set_xlabel("The x label")
```

I'm not really sure if this is intended behavior in matplotlib or not, but it seems unrelated from whether seaborn is correctly passing the values you give for the relevant `rcParams`.

The second issue is that I'm not sure you're successfully getting latex to use Helvetica. I think the labels for the main heatmap are Arial, the seaborn default, which can be very difficult to distinguish from Helvetica. In the past I've found that getting matplotlib to use Helvetica ranges somewhere between difficult and impossible, but I'm not too knowledgable about the ins and outs of fonts.
