### ISSUE TITLE
pairplot: all samples plotted as being 0 on y-axis

### ISSUE THREAD

**Issue by pirius** [mwaskom/seaborn#1369]
Hi, I've just run into a situation where `pairplot` yields this:

![pairplot](https://user-images.githubusercontent.com/1210249/35808677-42271472-0a8f-11e8-9917-e7285ad643d2.png)
while a corresponding `pandas.scatter_matrix` yields this:
![scatter_matrix](https://user-images.githubusercontent.com/1210249/35808702-527e9f34-0a8f-11e8-8fd9-3aedce224c1d.png)
The reproducible example below which produces the figures above uses custom data (csv attached: [bug.txt](https://github.com/mwaskom/seaborn/files/1695417/bug.txt)) because I guess this behavior somehow has to do with the small values in the example:
```python
import pandas as pd
import seaborn as sns; sns.set(style="ticks", color_codes=True)
data = pd.read_csv('bug.txt') # is csv but needs .txt extension for github
pd.plotting.scatter_matrix(data) # seems to be OK
sns.pairplot(data) # all samples shown as 0 on y-axis
```

Used versions:
```
sns.__version__
'0.8.1'
pd.__version__
'0.22.0'
matplotlib.__version__
'2.1.2'
```

**Comment by mwaskom** [comment]
I think this is a known bug in matplotlib: https://github.com/matplotlib/matplotlib/issues/9979

**Comment by pirius** [comment]
Sounds reasonable and is also visible with the data from above using e.g. `plt.scatter(data['a'], data['b'])` (or any other two columns of it). Interesting that this only seems to affect the y-axis in seaborn's pairplot, though.

**Comment by mwaskom** [comment]
That's because the x axis is shared with the diagonal facets, and `plt.hist` sets the limits properly, which propagates out the scatterplots.

**Comment by pirius** [comment]
Ack. Should anyone else run into this: a quick-fix until the issue is fixed in matplotlib is to just set seaborn's ylim by hand , e.g. as:
```python
g = sns.pairplot(data)
g.set(ylim=(data.min().min(),data.max().max()))
```

**Comment by tmchartrand** [comment]
I know this is closed, but a more universal solution is to use PairGrid and the basic matplotlib plot function. This lets you retain auto scaling while avoiding the bug in matplotlib's scatter().

In fact, I assume it would be possible to replace all of seaborn's calls to scatter() with equivalent calls to plot(), which could fix this issue on the seaborn side entirely.

**Comment by MainzerKaiser** [comment]
Neither the workaround via PairGrid, nor the ylim command helped.
g.set(ylim=(data.min().min(),data.max().max()))

This command applies the min and max values of one plot to all the plots. How is it possible to apply the command for each plot individually?

**Comment by jbae11** [comment]
I came up with this sort of hacky way of doing it, hopefully it helps.
```
def better_scatter(x, y, **kwargs):
    plt.scatter(x, y, **kwargs)
    margin = (max(y) - min(y)) * 0.1
    plt.ylim(min(y) - margin, max(y) + margin)

g = sns.PairGrid(pp_data)
g = g.map_diag(plt.hist)
g = g.map_offdiag(better_scatter)
```
