### ISSUE TITLE
color_palette doesn't use full range of colors

### ISSUE THREAD

**Issue by mathause** [mwaskom/seaborn#1372]
When getting colors with `sns.color_palette` you are not using the full range of colors. Is there a reason for this?

I could not find anything in the [docs](https://seaborn.pydata.org/generated/seaborn.mpl_palette.html#seaborn.mpl_palette)

What seaborn does:
``` python
import seaborn as sns
pal = sns.color_palette('Greys', n_colors=3)
pal
```
Returns
    0.85, ...
    0.58, ...
    0.31, ...

What I would expect:
``` python
import pyplot as plt
cmap = plt.get_cmap('Greys')
colors_i = np.linspace(0, 1., 5)
cmap(colors_i)l
```
Returns
    1.00, ...
    0.58, ...
    0.00, ...

The relevant code is here:
https://github.com/mwaskom/seaborn/blob/0beede57152ce80ce1d4ef5d0c0f1cb61d118375/seaborn/palettes.py#L411

**Comment by mathause** [comment]
to be more precise - it is in `sns.mpl_palette`

**Comment by mwaskom** [comment]
Yes this is by design. The idea is that you’re using that function to color things like lines and points that will be drawn on a white or light gray background. If the full color range were used, some of the points would be invisible!
