### ISSUE TITLE
KDE Plot Inconsistant API

### ISSUE THREAD

**Issue by Jollyhrothgar** [mwaskom/seaborn#1374]
Consider the following scenario:
<pre>
<code>
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.DataFrame({'x':np.random.random(100), 'y':np.random.random(100)})

# code works as expected:
fig, ax = plt.subplots(figsize=(10,10))
sns.kdeplot(df, ax=ax) # generates warning
plt.show()

# code does not work as expected
fig, ax = plt.subplots(figsize=(10,10))
sns.kdeplot(x=df['x'], y=df['y'], ax=ax) # raises a "data is expected as first named arguement" error
</code>
</pre>
Since kdeplot explicitly supports bivariate distributions, would not an 'x=' 'y=' kwarg make sense?

**Comment by mwaskom** [comment]
Well, yes, the arguments are not called `x` and `y`. The function predates any other functions with that API. The error you see is part of a graduate transition to the API you mention.

People complain when things are inconsistent, and they complain when you change things to achieve consistency...

**Comment by Jollyhrothgar** [comment]
Thanks for clarifying, really appreciate the work, makes my job ten times easier. 

Cheers!
