### ISSUE TITLE
JointPlot setting y-axis limit causes glitch

### ISSUE THREAD

**Issue by mbhall88** [mwaskom/seaborn#1376]
I've looked around everywhere for an answer to this but can't seem to see people raising it.  
When plotting a jointplot and setting the y-axis to a specific limit, the interior of the plot goes "strange" for lack of better wording.  

```py
def length_vs_qual_plot(read_lengths, mean_quality_scores, kind='hex', log_length=False):
    xlabel = 'Read Length (bp)'
    ylabel = 'Quality (Phred) score'
    title = 'Read length vs. read quality'
    size = 9.5
    x = np.array(read_len)
    y = np.array(mean_qual)
    if log_length:
        x = np.log2(x)
    
    p = sns.jointplot(x=x, y=y, kind=kind, size=size, ylim=(0, 50))
    p.set_axis_labels(xlabel=xlabel, ylabel=ylabel)
    p.fig.set_dpi(300)
    return p

p = length_vs_qual_plot(read_len, mean_qual, kind='kde', log_length=False)
```

![image](https://user-images.githubusercontent.com/20403931/36332776-71bbe110-136b-11e8-9b22-f526bfa0ec6b.png)

I am assuming it is not desirable to have the streak in the plot background like this?

**Comment by mwaskom** [comment]
There's nothing strange or unexpected here. By changing the axis limits, you're revealing part of the axes where the kde doesn't have a fit/prediction. You probably want to pass `joint_kws=dict(shade_lowest=True)`.

**Comment by mbhall88** [comment]
Passing joint_kws=dict(shade_lowest=False) gave me the look I was after. Cheers.
