### ISSUE TITLE
Pairplot kind='reg' truncates displayed data

### ISSUE THREAD

**Issue by jotdeh** [mwaskom/seaborn#1381]
I get truncated plots with `pairplot(kind='reg')`, but not with `lmplot`. Is this a bug? Can I get pairplot to produce the same as lmplot, but on a grid for different variables / columns?

With lmplot I can produce the following:
```
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df = pd.DataFrame(data={'col1':[1,2,3,4], 'col2': [2,3,4,5], 'col3': [4,5,6,7], 'cat':['a','a','b','b']})
sns.lmplot(data=df,x='col1',y='col2',hue='cat')
```
![image](https://user-images.githubusercontent.com/32191302/36727654-63004f7a-1bbe-11e8-8c21-a1f1811676ad.png)

But with pairplot, I get truncated plots:
```
g = sns.pairplot(df, kind='reg', hue='cat', x_vars=['col1','col2','col3'],
                     y_vars=['col1','col2'])
```
![image](https://user-images.githubusercontent.com/32191302/36727476-a63cd1f6-1bbd-11e8-85fb-3db82f12940a.png)

Changing the limits 
`g.set(xlim=(0,8))`
reveals
![image](https://user-images.githubusercontent.com/32191302/36727576-10a52b74-1bbe-11e8-82d5-38f0f2b965e6.png)

Using the default kind ('scatter') shows all data with correct limits
```
g = sns.pairplot(df, kind='scatter', hue='cat', x_vars=['col1','col2','col3'],
                     y_vars=['col1','col2'])
```
Produces
![image](https://user-images.githubusercontent.com/32191302/36727430-80633e7a-1bbd-11e8-8e8a-55fe46ebce17.png)

Any idea what is going on?

**Comment by mwaskom** [comment]
I think this has to do with the fact that regplot sets the xlim of the plot (to match the extent of the regression line/CI) but matplotlib recently changed the `set_xlim` default so that further autoscaling is disabled unless you tell it not to be.

I'll look into that but int he meantime you could do

```python
g = sns.pairplot(df, hue='cat',
                 x_vars=['col1','col2','col3'],
                 y_vars=['col1','col2'])
g.map(sns.regplot)
```

![image](https://user-images.githubusercontent.com/315810/37163827-c3637cf2-22c6-11e8-8f7c-3606e60b8c79.png)

**Comment by jotdeh** [comment]
That works, thanks @mwaskom!
