### ISSUE TITLE
Countplot produces wrong output when sharing x axis across subplots

### ISSUE THREAD

**Issue by roecla** [mwaskom/seaborn#1385]
When sharing the x axis across several subplots, the countplot puts the bars in the wrong places according to the ticks when not all arrays have the same unique values.

Here's a MWE:
```
s1 = [3.,  3.,  4.,  5.,  6.]
s2 = [5.,  5.,  6.,  6.,  7.]
fig, axes = plt.subplots(1, 2, figsize=(12, 3), sharex=True, sharey=False)
sns.countplot(s1, ax=axes[0])
sns.countplot(s2, ax=axes[1])
plt.show()
```

The result is this:
![countplot_problem1](https://user-images.githubusercontent.com/9567321/37045113-771fb8c2-2165-11e8-9411-85a93fa96090.png)

There are two problems with this graph:
Firstly, 3 and 4 show up in s1 but don't appear on the x axis.
Secondly, the bars in the left subplot are wrong. There's only one 5 no 7 in s1. Instead seaborn seems to put the bars for 3, 4, and 5 at the places of 5, 6, and 7. 

Versions: seaborn: 0.8.1, matplotlib 2.0.0, backend: Qt5Agg

**Comment by mwaskom** [comment]
If you want to use shared quantitative axes, you need to give `countplot` information about all the levels of the category to show. You can do this by using pandas objects with a categorical datatype and category names or by using the `order` kwarg.
