### ISSUE TITLE
seaborn 0.8 heatmap does not show all y labels

### ISSUE THREAD

**Issue by OPBobOP** [mwaskom/seaborn#1387]
I do lots of heatmaps with seaborn and since seaborn 0.8.0 some y labels do not show up. With small heatmaps it seems to work fine, but with a high number of y label (22 and higher in my example) there is a problem. Here are examples with 20 and 22 y labels with seaborn 8.0.0.
`import pandas as pd`
`import numpy as np`
`import seaborn as sns`
`test=pd.DataFrame(np.random.rand(20,6))`
`ax = sns.heatmap(test, cbar_kws={"shrink": .5})`
`fig = ax.get_figure()`
`fig.set_size_inches(8, 14)`

![sns_0 8 0_20_labels](https://user-images.githubusercontent.com/37376716/37417821-9c81027e-2787-11e8-9970-51bd58816361.png)

`test=pd.DataFrame(np.random.rand(22,6))`
`ax = sns.heatmap(test, cbar_kws={"shrink": .5})`
`fig = ax.get_figure()`
`fig.set_size_inches(8, 14)`

![sns_0 8 0_22_labels](https://user-images.githubusercontent.com/37376716/37417830-a109e720-2787-11e8-8695-3a7b0785c662.png)

In seaborn 0.7.1, it is working correctly.
`test=pd.DataFrame(np.random.rand(22,6))`
`ax = sns.heatmap(test, cbar_kws={"shrink": .5})`
`fig = ax.get_figure()`
`fig.set_size_inches(8, 14)`

![sns_0 7 1_22_labels](https://user-images.githubusercontent.com/37376716/37418153-eee4357c-2787-11e8-8b3b-37305638c89d.png)

I'm using matplotlib 2.0.2

**Comment by mwaskom** [comment]
Always helpful to read the [release notes](http://seaborn.pydata.org/whatsnew.html#v0-8-0-july-2017) when you update versions:

> Added "auto" as a (default) option for tick labels in heatmap() and clustermap(). This will try to estimate how many ticks can be labeled without the text objects overlapping, which should improve performance for larger matrices.

**Comment by OPBobOP** [comment]
Thanks for the answer. This "auto" option is clearly not optimal since there is still a lot of space left to label each row in my example.

**Comment by mwaskom** [comment]
That's because you're changing the size of the Axes after you draw the heatmap...
