### ISSUE TITLE
Academic publication?

### ISSUE THREAD

**Issue by DamienIrving** [mwaskom/seaborn#1389]
@mwaskom I'm writing an academic paper at the moment and was disappointed to find that there is no paper about Seaborn that I can cite in my methods section to give you the academic credit you deserve for all the hard work involved. Have you thought about publishing with [JORS](https://openresearchsoftware.metajnl.com/) or [JOSS](https://joss.theoj.org/)?

**Comment by mwaskom** [comment]
No, there no paper. There are dois linked to each version, though ... check the release notes page on the docs.

**Comment by mwaskom** [comment]
i.e. here: http://seaborn.pydata.org/whatsnew.html
