### ISSUE TITLE
UserWarning matplotlib: The 'normed' kwarg is deprecated

### ISSUE THREAD

**Issue by tandriamil** [mwaskom/seaborn#1392]
Hi,

I got a warning when plotting a distribution, it seems to be caused by the matplotlib wrapper used by seaborn.

> /home/[...]/venv/lib/python3.5/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
>   warnings.warn("The 'normed' kwarg is deprecated, and has been "

I have **matplotlib 2.2.2** and **seaborn 0.8.1**, thanks.

**Comment by mwaskom** [comment]
Already fixed with #1380

**Comment by russtoku** [comment]
Hi,

I'm seeing the same warning using matplotlib 2.2.2 and seaborn 0.8.1 from conda 4.5.0.

> [...]/miniconda3/envs/jup3/lib/python3.6/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.

**Comment by russtoku** [comment]
Sorry, but it appears that the seaborn 0.8.1 package from conda 4.5.0 is lacking this patch. In line 214 of seaborn/distributions.py, I changed "normed" to "norm_hist" and the warning message is gone. Thanks!

**Comment by tandriamil** [comment]
It seems that the warning was already patched but no stable release incorporates it yet

**Comment by Aquapisces** [comment]
I also get the warning using python 2.7.14, matplotlib-2.2.2 and seaborn 0.8.1...
c:\python27\lib\site-packages\matplotlib\axes\_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.

**Comment by mangolzy** [comment]
I also get the warning using python 2.7.12, matplotlib-2.2.2 and seaborn 0.8.1...
c:\python27\lib\site-packages\matplotlib\axes_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.

**Comment by tandriamil** [comment]
Guys, this warning is already patched but as I said, no stable release contains it yet. Look at the comment of @russtoku for a temporary manual patch until the official release  ;)

**Comment by mwaskom** [comment]
Following up to mention that 0.9 has been released with this fix included.
