### ISSUE TITLE
FacetGrid.map fails if the function does not have a __module__ attribute

### ISSUE THREAD

**Issue by brunobeltran** [mwaskom/seaborn#1398]
Many callables the user might want to map onto FacetGrids will fail to have a `__module__` attribute. For example, `functools.partial` returns an object of type `functools.partial`, not a regular function.

Here's a dumb, but simple broken example:
```python
import seaborn as sns
import matplotlib.pyplot as plt
import functools

df = sns.load_dataset('anscombe')
g = sns.FacetGrid(df, row='dataset')
p = functools.partial(plt.scatter, color='r')
g.map(p, 'x', 'y')
```

This code will raise, at line 726 in axisgrid.py, `AttributeError: 'functools.partial' object has no attribute '__module__'`. A more realistic example might look like
```python 
p = functools.partial(custom_function_with_many_options, option1='value1')
g.map(p, 'x', 'y')
```

I see a few solutions here, where only the final one doesn't feel hack-y:
1. If we want to explicitly deal with objects of type `functools.partial`, we can simply add a check for that type.
```python
if type(func) == functools.partial:
    if func.func.__module__.startswith('matplotlib'
```
The only pro here is that this continues the originally intended behavior of treating matplotlib functions specially. The downside is of course the rabbit hole this opens of deciding how carefully to try to check that a function "belongs" to matplotlib in some sense. And the functools import.

2. If we want to throw our hands up in the air and only treat the matplotlib functions as special if you don't do any black magic to them, we can simply add a `if hasattr(func, '__module__') and` guard to the current check for matplotlib functions. Flipped pro/cons from option 1.

3. Request users avoid `functools.partial` with `g.map`. While not totally unreasonable (functools.partial is pretty brittle in my experience), this seems like the worst abstraction leak of the three options to me. 

4. Guard the [v.values for v in plot_args] logic with a new kwarg that the user has to explicitly request, so that we're not in charge of guessing if a function "actually" belongs to matplotlib. This seems like the most sane to me. 

Maybe by default, e.g. `numpify_args=None`, can fallback to using the behavior suggested in option 2 above to try to guess if a function is from matplotlib. This way, we preserve our good default behavior, while also explicitly documenting (albeit in a kinda roundabout way) that this behavior can cause a problem and providing an easy switch to fix it. 

I felt that option 4 seemed the most sane, so I have submitted a quick PR with that implements it, but am open to feedback and can re-submit as needed. I'm especially interested in adding a more sane docstring comment that describes when numpify_args might be valuable; i.e. what matplotlib functions fail without it.

**Comment by mwaskom** [comment]
Out of curiosity, what is a real world case where you'd actually benefit from using a partial function?

**Comment by brunobeltran** [comment]
My response last night would have been: basically anytime you have a plotting function that you want to curry. I tend to use `functools.partial` instead of `lambda`-based currying because it's robust to pickling and can therefore be broadcast using `multiprocessing`. 

Of course, the tone of your questions prompted me to actually read the `FacetGrid.map` code again and realize that for *most* situations where you need currying, you could just pass the desired kwargs you want to curry to the `FacetGrid.map` function. And for the remaining use case where you have to curry a function with a signature like:
```python
def plotter(other_data, x, y):
```
you actually can't even use functools.partial anyway
```python
f = functools.partial(plotter, other_data=df)
f(x,y) # TypeError: plotter() got multiple values for argument other_data
f = lambda x,y: plotter(df, x, y)
f(x,y) # works
```
And since `lambda` functions will have the `__module__` attribute, this bug should never have surfaced for me.

So you were right actually, there does not seem to be a situation where using `functools.partial` is the Right Thing to do. However, I wonder if that's a good enough excuse for raising an error in the case when the plotting function doesn't have a __module__. Do you have any thoughts on how you would prefer to see this fixed? I can imagine that you'd be reticent to add a kwarg to `map` just to cover the strange corner case where the user is passing a function that doesn't have __module__ but calls a matplotlib function. I'm trying to figure out when else that would happen, but as I read more about __module__, I only get more and more surprised that functools would return a function that doesn't have __module__ defined.

In the morning light it's clear that what would actually help the most people is for me to expand on the documentation of the methods of e.g. `FacetGrid`. The documentation-by-example is excellent, but the single-line "Methods" descriptions at the bottom of the pages might benefit from linking to a page or having an expandable div that goes into more detail on that method's operation so that users don't have to infer it by skimming all the relevant examples. I, for one, totally missed that you can pass extra kwargs to the `map` method until I read its code, because all the examples only take matplotlib-based kwargs, so I assumed that the method was doing more magic behind the scene, not just forwarding kwargs to the function passed.

I can open a new issue to chat about how we might do this if you want to keep things more organized and you are open to the idea of expanding the documentation.

**Comment by mwaskom** [comment]
The docstring for `FacetGrid.map` has this information; idk why the sphinx autodoc doesn't make it available though:

```
Signature: sns.FacetGrid.map(self, func, *args, **kwargs)
Docstring:
Apply a plotting function to each facet's subset of the data.

Parameters
----------
func : callable
    A plotting function that takes data and keyword arguments. It
    must plot to the currently active matplotlib Axes and take a
    `color` keyword argument. If faceting on the `hue` dimension,
    it must also take a `label` keyword argument.
args : strings
    Column names in self.data that identify variables with data to
    plot. The data for each variable is passed to `func` in the
    order the variables are specified in the call.
kwargs : keyword arguments
    All keyword arguments are passed to the plotting function.

Returns
-------
self : object
    Returns self.
```

**Comment by brunobeltran** [comment]
I'll dig into the Sphinx theme that's being used to see if there's a slick way to add it. 

In the meantime, this is still a bug, albeit an awful corner-case one that shouldn't be hit by most regular users, did you want to just add a `hasattr` check to the two if statements in `FacetGrid.map` that use `func.__module__`? I can modify my PR to do that real quick or you can just do it directly if it's easier. 

Then at least the function doesn't outright break on a seemingly valid input.
