### ISSUE TITLE
Odd behaviour with pandas 

### ISSUE THREAD

**Issue by grofte** [mwaskom/seaborn#1401]
Using the UCI HAR Dataset from this paper: 
[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. A Public Domain Dataset for Human Activity Recognition Using Smartphones. 21th European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning, ESANN 2013. Bruges, Belgium 24-26 April 2013. 
```python
import seaborn as sns
import pandas as pd
train_X = pd.read_csv("./train/X_train.txt", delim_whitespace=True, header=None)
train_y = pd.read_csv("./train/y_train.txt", delim_whitespace=True, header=None)
with open('./features.txt') as file: 
    header = []
    for line in file:
        header.append(line.strip().split()[1])
train_X.columns = header
train_X['labels'] = train_y
train_X['labels'] = train_X['labels'].astype('category')
sns.set_style("whitegrid")
```
then this fails with a `cannot label index with a null key` message from pandas 
```python
ax = sns.boxplot(x="labels", y="tBodyAcc-mean()-X", data=train_X)
```
while this works 
```python
ax = sns.boxplot(x=train_X["labels"], y=train_X["tBodyAcc-mean()-X"])
```

The failing code is the same as the one written in the documentation and if I load the "tips" dataset everything works exactly the same as in the documentation. But I can not for the life of me see what the difference is between my DataFrame and "tips" loaded from seaborn.

**Comment by mwaskom** [comment]
I can’t help without the dataset

**Comment by mwaskom** [comment]
I don't understand exactly what's happening with pandas, but the problem is that you have duplicate names in your header. However, those names correspond to columns with distinct data. Are you sure you're parsing the header information correctly?

**Comment by grofte** [comment]
You're right. They do not seem to have added x, y, z to the Fourier
transform energy bands for some reason.
But why does that affect plotting a completely different column?

**Comment by mwaskom** [comment]
As I said, I don't really know ... but pandas does behave strangely sometimes when there are duplicates in an index.

**Comment by grofte** [comment]
Thanks though! I appreciate it =]
