### ISSUE TITLE
Shifting a colormap in Seaborn heatmap.

### ISSUE THREAD

**Issue by KeironO** [mwaskom/seaborn#1403]
Hey there,

I was wondering if there is any way of shifting a colormap's midpoint to a non-standard scale? (Ergo 0, 1, 100 - as opposed to 0, 50, 100).

Thanks,

Keiron

**Comment by mwaskom** [comment]
I don't really understand the question, but you can alter matplotlib colormaps in many ways. You probably want to make a clear example and ask on Stackoverflow.
