### ISSUE TITLE
Palette widgets fail in JupyterLab

### ISSUE THREAD

**Issue by QuentinAndre** [mwaskom/seaborn#1408]
Very simple issue: using the Palette Widgets function (i.e. `sns.choose_x_palette()`) returns an error when called from Jupyter Lab.

Sample code: 

    import seaborn as sns
    sns.choose_light_palette()

Output:
`Error displaying widget`

Versions:
JupyterLab = '0.31.12'
Seaborn  = '0.8.1'

**Comment by mwaskom** [comment]
Not so simple because it provides very little information about what the problem is! Is that really the only output? Does jupyterlab claim to support widgets? I don’t use it.

**Comment by mwaskom** [comment]
Cool, thanks for providing that link. Hopefully they get eveything up and running soon.
