### ISSUE TITLE
factoplot sizing improvement

### ISSUE THREAD

**Issue by mikkokotila** [mwaskom/seaborn#1410]
Is there a way to somehow programmatically get a standard sizing for factorplot regardless of the number of items in the list. I can see how it's done manually through trial and error, but it seems that either I'm missing the current logic of size/aspect, or it's flawed. 

For example, if I have 2 items, 4/2 will give same look (proportions) as 1/10 for 40 items. Trying lengths between 2 and 40, seems to suggest that there is no consistency in the way it's handled right now. Or did I miss something? 

A quick workaround would be to allow using figsize but this does not seem to work anymore.

**Comment by mwaskom** [comment]
I don't really understand what you're asking. Might be good to make a reproducible example and ask on stackoverflow.

**Comment by mikkokotila** [comment]
Thanks for speedy response! I think the best way to put it is: 

If I have 40 items and do size=10 and aspect=1, I don't get the same output in terms of figure size as I get with 20 items  and size=10 and aspect=2. 

According to manual "aspect * size gives the width of each facet in inches". This does not seem to be the case. The other issue is with few items, for example when I have 2 items, logically I would need to pick size=0.5 and aspect=20 which of course does not make sense (and is not possible). The end result is that it seems that there is no systematic way to get the exact same proportions/size regardless of the number of items.

**Comment by mikkokotila** [comment]
To add, the use case is where there is no need to manually set the size / aspect, and regardless of the dataset, the "look and feel" of the output is the same.

**Comment by mwaskom** [comment]
Again, if you're not going to bother to make a reproducible example that I can run and understand and compare to figures you are sharing, it's not a good use of my time to try to imagine what you might be seeing.

**Comment by mikkokotila** [comment]
Did not mean to give the indication that I did not bother to provide example if that was needed. Consider the below example:  

```
import numpy as np
import pandas as pd
import seaborn as sns

%matplotlib inline

# create the dummy data
y = np.random.randint(50,100, size=50)
x = np.arange(50)
df = pd.DataFrame({'x': x, 'y': y})

for items in [2,5,10,20,50]:
    
    sns.factorplot(x='x',
                   y='y',
                   data=df.head(items),
                   kind='bar',
                   size=4,
                   aspect=2,
                   orient='h')
```
As a result, we have 5 plots that look totally different. What I would like to do, is have them all size vertically (height) to the extent the number of items requires it. The desired end result being: 

1) width remains the same
2) thickness of each bar remains the same 

I want to be able to do this precisely, and without manual trial and error.

If you prefer this to go to slackoverflow, I'm happy to do it.

**Comment by mwaskom** [comment]
The size and aspect parameters correspond to the axes in the grid, not to the elements that are drawn onto them. This has always been the case despite your claim that something "does not work anymore".

When I run your example, it makes plots that are the same size with bars that are different widths, and behaves exactly as I would expect it to. It sounds like you want to do some kind of additional customization, so if you can't figure it out yourself, you should indeed ask on stackoverflow.

**Comment by mikkokotila** [comment]
What "does not work" anymore, is the figsize parameter from mpl, which based on slackoverflow comments seems to have worked before as an override to size and aspect inside factorplot(). 

Ok great, that's what I also thought, this is "working as expected". Does that have to do with the fact that factorplot is not so much intended to be used for creating a single figure, but multiple figures in a grid i.e the size / aspect parameters rational is optimized towards that?

**Comment by mikkokotila** [comment]
In case somebody ends up here looking for solutions, here is a quick and dirty way to get very close to precision, to the extent that at least serves my aim. 

```
# choose these first
width = 12                   # larger the wider
thickness = 1               # smaller the thicker

# compute the values
value = items + 2.5          # overcomes the issues with very few items 
size = value / thickness
aspect = (width / size)

# draw the plot
sns.factorplot(x='x',
               y='y',
               data=df.head(items),
               kind='bar',
               size=size,
               aspect=aspect,
               orient='h');
```
