### ISSUE TITLE
bivariate kdeplot ignores "bw" when scipy is used

### ISSUE THREAD

**Issue by cpankow** [mwaskom/seaborn#1411]
Context: https://github.com/mwaskom/seaborn/blob/master/seaborn/distributions.py#L452

Not sure if this was intentional or not, but when the `scipy.stats` kde backend chosen, the `bw` argument is never passed to the kde via `bw_method`. Happy to write a PR, but this is a one line fix, if it's desirable.

**Comment by mwaskom** [comment]
When that code was written, scipy didn't support specified bandwidths for bivariate kdes. Has that changed?

**Comment by mwaskom** [comment]
Maybe I am thinking of it not supported different bandwidths for the two dimensions.

**Comment by cpankow** [comment]
I think that's still correct, that is, that it won't take bandwidths for individual dimensions, but a global bandwidth is still respected for any set of dimensions, as far as I know.

**Comment by mwaskom** [comment]
Yes looking at the code more closely this looks like an oversight.
