### ISSUE TITLE
Failure on import

### ISSUE THREAD

**Issue by ArdenB** [mwaskom/seaborn#1413]
I've installed seaborn using both pip and conda and i get the same error regardless
In [1]: import seaborn
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-085c0287ecb5> in <module>()
----> 1 import seaborn

/home/arden/miniconda/lib/python2.7/site-packages/seaborn/__init__.py in <module>()
      4 
      5 # Import seaborn objects
----> 6 from .rcmod import *
      7 from .utils import *
      8 from .palettes import *

/home/arden/miniconda/lib/python2.7/site-packages/seaborn/rcmod.py in <module>()
      6 import matplotlib as mpl
      7 
----> 8 from . import palettes, _orig_rc_params
      9 
     10 

/home/arden/miniconda/lib/python2.7/site-packages/seaborn/palettes.py in <module>()
     10 from .external.six.moves import range
     11 
---> 12 from .utils import desaturate, set_hls_values, get_color_cycle
     13 from .xkcd_rgb import xkcd_rgb
     14 from .crayons import crayons

/home/arden/miniconda/lib/python2.7/site-packages/seaborn/utils.py in <module>()
      5 
      6 import numpy as np
----> 7 from scipy import stats
      8 import pandas as pd
      9 import matplotlib as mpl

/home/arden/miniconda/lib/python2.7/site-packages/scipy/stats/__init__.py in <module>()
    346 from __future__ import division, print_function, absolute_import
    347 
--> 348 from .stats import *
    349 from .distributions import *
    350 from .morestats import *

/home/arden/miniconda/lib/python2.7/site-packages/scipy/stats/stats.py in <module>()
    175 import scipy.special as special
    176 import scipy.linalg as linalg
--> 177 from . import distributions
    178 from . import mstats_basic
    179 from ._distn_infrastructure import _lazywhere

/home/arden/miniconda/lib/python2.7/site-packages/scipy/stats/distributions.py in <module>()
      8 from __future__ import division, print_function, absolute_import
      9 
---> 10 from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
     11                                     rv_frozen)
     12 

/home/arden/miniconda/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py in <module>()
     14 import warnings
     15 
---> 16 from scipy.misc import doccer
     17 from ._distr_params import distcont, distdiscrete
     18 from scipy._lib._util import check_random_state, _lazywhere, _lazyselect

/home/arden/miniconda/lib/python2.7/site-packages/scipy/misc/__init__.py in <module>()
     63 
     64 try:
---> 65     from .pilutil import *
     66     from . import pilutil
     67     __all__ += pilutil.__all__

/home/arden/miniconda/lib/python2.7/site-packages/scipy/misc/pilutil.py in <module>()
     19     from PIL import Image, ImageFilter
     20 except ImportError:
---> 21     import Image
     22     import ImageFilter
     23 

/home/arden/miniconda/lib/python2.7/site-packages/PIL/Image.py in <module>()
     25 #
     26 
---> 27 from . import VERSION, PILLOW_VERSION, _plugins
     28 
     29 import logging

ValueError: Attempted relative import in non-package

**Comment by mwaskom** [comment]
This looks like a problem with your PIL installation, not anything to do with seaborn.
