### ISSUE TITLE
What dose y axes represent in kdeplot, is probability?

### ISSUE THREAD

**Issue by zihaozhu93** [mwaskom/seaborn#1414]
At first I thought the y axes represents the probability ,but when the input data x varies from 0 to 1, something different, i'm confused. 
ax1 = sns.kdeplot([0.1,0.2,0.21,0.3,0.31,0.32,0.41,0.42,0.42,0.43])
ax2 = sns.kdeplot([1,2,3,4,5])
![image](https://user-images.githubusercontent.com/20263795/39102913-5f2f90e4-46da-11e8-90b8-af9decf19f1e.png)

**Comment by mwaskom** [comment]
https://en.wikipedia.org/wiki/Kernel_density_estimation
