### ISSUE TITLE
[New feature request] ci = 'se' for categorical plots

### ISSUE THREAD

**Issue by agamemnonc** [mwaskom/seaborn#1427]
This is a new feature request, which should be very straightforward to implement. 

Now that the `ci` parameter supports showing `sd`, it would be also handy to include the option to show `se`, i.e., [standard error](https://en.wikipedia.org/wiki/Standard_error#Estimate) as well. This would be just a division of the standard deviation by $\sqrt(n)$. 

I would be happy to implement this and submit a PR if people are happy with this addition.

**Comment by mwaskom** [comment]
You can show standard error with a 68% confidence interval.

**Comment by mwaskom** [comment]
Thanks for the link to wikipedia. I'd suggest you read down to the "assumptions and usage" section.

If you have normally distributed data, then the 68% confidence interval will correspond to the standard error of the mean. In the case of bootstrapping, this will only be approximate and dependent on the number of bootstrap samples.

If you do not have normally distributed data, then the standard error of the mean will be useless, and the bootstrap confidence interval will give you much more informative error bars.

**Comment by mwaskom** [comment]
Here, convince yourself:

```python
f, ax = plt.subplots(figsize=(12, 3))
n = 100
for i in range(50):

    x = i, i
    
    a = np.random.randn(n)
    ci = sns.utils.ci(sns.algorithms.bootstrap(a), 68)
    ax.plot(x, ci, color="r")

    m = a.mean()
    se = a.std() / np.sqrt(n)
    ax.plot(x, [m - se, m + se], "o", color="k")
```

![image](https://user-images.githubusercontent.com/315810/39935949-e09698c0-5518-11e8-8090-5cf9c8647711.png)

**Comment by agamemnonc** [comment]
I am afraid you are right. I was thinking of computing standard error of median, but like you said it doesn't make sense for non-normal distributions. 

I am closing this now and thanks for clarifying.
