### ISSUE TITLE
Link to tutorials in API docs

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#1429]
The docstring for each function should link to the relevant tutorial page to make it more discoverable.

**Comment by mvinoba** [comment]
I'm interested in working at this but I'm not sure where this session would fit in the docstring, is between `See Also` and `Examples` good? And what numpydoc's sessions should we use? Is `Notes` good? 

For example, in `distributions.py`, something like:

    See Also
    --------
    kdeplot : Show a univariate or bivariate distribution with a kernel
              density estimate.
    rugplot : Draw small vertical lines to show each observation in a
              distribution.

    Notes
    -----
    Relevant tutorial : `Plotting univariate distributions <http://seaborn.pydata.org/tutorial/distributions.html#plotting-univariate-distributions>`_

    Examples
    --------

**Comment by mwaskom** [comment]
This is more of a note to self for the next time I take a pass through the docs, thanks!
