### ISSUE TITLE
"No" is not an actionable error message

### ISSUE THREAD

**Issue by chrisfosterelli** [mwaskom/seaborn#1435]
When providing the "jet" color palette, the library raises `ValueError: No.`. It's not clear to the programmer what the issue is as the error is non-descriptive and unactionable, although upon reviewing the source to see it singles out `jet` and the documentation for the much cleaner explanation of the philosophical argument for not using this palette it becomes more clear.

Perhaps this could be improved to 1) allow the developer to choose an arguably bad palette if they want with a warning, or 2) provide more descriptive error which includes a link to the much better explanation in the documentation.

**Comment by mwaskom** [comment]
No.

**Comment by klanderson** [comment]
```
import matplotlib.cm as cm
sns.scatterplot(
    ...
    palette=cm.jet,
)
```
