### ISSUE TITLE
Violin plot displace previously plotted data

### ISSUE THREAD

**Issue by glyg** [mwaskom/seaborn#1438]
HI,

When making a violinplot on top of matplotlib scatter plot of the same data, the scatter plot is strangely shifted to the right.
Here is an example reproducing the issue:

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# Get flu data from google
ggle = pd.read_csv('https://www.google.org/flutrends/about/data/flu/fr/data.txt',
                    skiprows=10, index_col=0)
ggle.index = pd.to_datetime(ggle.index, format='%Y-%m-%d')

monthly = ggle.groupby(ggle.index.month).mean()

fig, ax = plt.subplots()
for name, column in monthly.iteritems():
    ax.plot(monthly.index, column, 'o-', alpha=0.4)
    
sns.violinplot(data=monthly.T, ax=ax)
ax.set(xlabel='Month')
ax.legend(labels=[])
fig.set_size_inches(12, 7)
```
Here is the graph without the violinplot:

![wo_seaborn](https://user-images.githubusercontent.com/1426279/40437502-cf58c6cc-5eb5-11e8-8156-b472b4ae55e7.png)

Here it is with the violinplot:

![with_seaborn](https://user-images.githubusercontent.com/1426279/40437519-d74fbc8c-5eb5-11e8-955e-f09f0a4910b1.png)

Here is what the data looks like:

![monthly](https://user-images.githubusercontent.com/1426279/40437635-27a493d8-5eb6-11e8-9384-c59e4d4e0648.png)

And some version infos:
- python : 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)  [GCC 7.2.0]
- seaborn : 0.8.1
- matplotlib : 2.2.2
- pandas : 0.22.0

I assume it comes from treating the index as an array of ints or as an array of labels...

Note that if I do e.g. a swarmplot from seaborn, the problem isn't there.

Thanks for your work,

Best,
Guillaume

**Comment by mwaskom** [comment]
`violinplot` and other categorical functions always treat the grouping variable as discrete, even when the labels are numeric, and they place the elements at 0-based positions on what's called the "categorical axis" (you can convince yourself by looking at `ax.get_xticks()` vs. `ax.get_xticklabels()`.

Combining plots with numeric variables and categorical variables can be done, but it must be done with care.

As the matplotlib categorical datatype machinery gets a little bit more mature (it was developed after all the seaborn categorical functions were written), it may be possible to hook into that and better avoid situations like this. For the time being, I'm not sure that there's any way for the seaborn functions to know that there is data on the axes that is intended to be drawn in numeric coordinates.

So if you want to use `ax.plot` you'll need to make your month index 0-based, or you could use seaborn functions, e.g.:

```python
for name, column in monthly.iteritems():
    sns.pointplot(monthly.index, column, scale=.5)
```

Or reformat the data to long-form and skip the for-loop:

```python
monthly = (ggle
 .groupby(ggle.index.month.rename("Month"))
 .mean()
 .reset_index()
 .melt("Month", var_name="France place", value_name="Number of flu")
)
sns.pointplot(x="Month", y="Number of flu", hue="France place", data=monthly, scale=.5)
sns.violinplot(x="Month", y="Number of flu", data=monthly, scale="width")
```
