### ISSUE TITLE
Where can I find data_sets of those samples.

### ISSUE THREAD

**Issue by MatthewP-Newbee** [mwaskom/seaborn#1439]
Hi,
Seaborn examples always start with sns.load_dataset(). Here is my question, Where can I find those load_dataset? I want to know the structure of original data, so that I can understand how seaborn perform datas. Thanks.

**Comment by mvinoba** [comment]
`seaborn.load_dataset` loads datasets available at https://github.com/mwaskom/seaborn-data. This information is well documented on `load_dataset` docstring and can be found on [StackOverflow](https://stackoverflow.com/a/30337377/5103802).

**Comment by mwaskom** [comment]
Thanks @mvinoba
