### ISSUE TITLE
seaborn.clustermap truncate_mode

### ISSUE THREAD

**Issue by schwemro** [mwaskom/seaborn#1442]
Are their palns to include `truncate_mode` as keyword argument in the near future? It would be great if one can visualise also a truncated dendrogram using a clustermap :)

Using the turncate_mode returns following error message:

`AttributeError: Unknown property truncate_mode`

**Comment by mwaskom** [comment]
No idea what that is, sorry.

**Comment by schwemro** [comment]
You might check the scipy documentation of the dendrogram:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.dendrogram.html#scipy.cluster.hierarchy.dendrogram

Have a look at the parameter `truncate_mode`.

**Comment by mwaskom** [comment]
> You might check the scipy documentation of the dendrogram

Yes but I'm very busy, and the person making a feature request should be the one taking the time/effort to include all the relevant information.

No plans to add this, sorry.
