### ISSUE TITLE
Suggestion for gallery addition: scatter + correlation with PairGrid

### ISSUE THREAD

**Issue by joelostblom** [mwaskom/seaborn#1444]
I have recently found the `pairs.panels` plot in the [`psych` R package](http://www.personality-project.org/r/psych/), which I think is quite useful when eyeballing pairwise relationships. It is easy to create a similar plot with `PairGrid`, would you be interested in including something like this to the sample gallery or elsewhere in the docs if I submit a PR?

**Psych's pairs.panels**
![image](https://user-images.githubusercontent.com/4560057/40943817-7ee684d0-6820-11e8-9b88-2ea908ddfe25.png)

---

**Car crashes**
![image](https://user-images.githubusercontent.com/4560057/40894711-7e3c9f44-6779-11e8-8e35-bb3fed7aeaf5.png)

---

**Planets**
![image](https://user-images.githubusercontent.com/4560057/40943630-d87fde66-681f-11e8-9fbb-f566565c3341.png)

---

**Custom array**
![image](https://user-images.githubusercontent.com/4560057/40943098-0336d332-681e-11e8-96c5-c2c50cc4ac55.png)

---

**Code for planets figure**

```python
import matplotlib.pyplot as plt
import seaborn as sns

def corrdot(*args, **kwargs):
    corr_r = args[0].corr(args[1], 'spearman')
    # Axes
    ax = plt.gca()
    ax.axis('off')
    x_min, x_max = ax.get_xlim()
    x_centroid = x_min + (x_max - x_min) / 2
    y_min, y_max = ax.get_ylim()
    y_centroid = y_min + (y_max - y_min) / 2
    # Plot args
    cmap = plt.cm.Reds if corr_r >= 0 else plt.cm.Blues
    marker_size = abs(corr_r) * 10000
    marker_color = cmap(int(abs(corr_r) * 255))
    ax.scatter(x_centroid, y_centroid, marker='o', s=marker_size, c=marker_color, alpha=0.6)
    corr_text = str(round(corr_r, 2)).replace('-0', '-').lstrip('0')
    ax.annotate(corr_text, [x_centroid, y_centroid,], ha='center', va='center', fontsize=20)

sns.set_context('notebook', font_scale=1.4)
planets = sns.load_dataset('planets')
g = sns.PairGrid(planets, aspect=1.4, diag_sharey=False)
g.map_lower(sns.scatterplot, alpha=0.4)
g.map_diag(sns.distplot, color='black', hist=False)
g.map_upper(corrdot)
```

**Comment by mwaskom** [comment]
Frankly, I have a pretty deep aversion to using a whole plot just to show a number as text. The relationships are very clear from the plot!

This would be fine as a StackOverflow answer (IIRC I've written a very similar one at some point) but not really something I want to encourage in the official gallery.

**Comment by joelostblom** [comment]
Makes sense, there are certainly more informative and space effective plots that can be added. I still think this could be a good alternative and add some information compared to the default mirrored scatterplot, so I will check if there are related questions on SO instead as you suggested. Closing this.

**Comment by mwaskom** [comment]
PS small suggestion for a shorter custom function: use the axes transform to place the texts and use the colormapping built into `scatter`:

```python
import matplotlib.pyplot as plt
import seaborn as sns

def corrdot(*args, **kwargs):
    corr_r = args[0].corr(args[1], 'spearman')
    corr_text = f"{corr_r:2.2f}".replace("0.", ".")
    ax = plt.gca()
    ax.set_axis_off()
    marker_size = abs(corr_r) * 10000
    ax.scatter(.5, .5, marker_size, corr_r, alpha=0.6, cmap="vlag", vmin=-1, vmax=1, transform=ax.transAxes)
    ax.annotate(corr_text, [.5, .5,],  xycoords="axes fraction", ha='center', va='center', fontsize=20)

planets = sns.load_dataset('planets')
g = sns.PairGrid(planets, aspect=1.4, diag_sharey=False)
g.map_lower(plt.scatter, alpha=0.4)
g.map_diag(sns.distplot, color='black', hist=False)
g.map_upper(corrdot)
```

**Comment by joelostblom** [comment]
That's great, thank you!

**Comment by mwaskom** [comment]
It should be simply to also use the transform to scale the marker size into axes coordinates to so r of -1 or 1 takes up the whole smallest axes ... but I couldn't figure it out in ~20 seconds of effort.
