### ISSUE TITLE
Repeated VisibleDeprecationWarning when (pandas) plotting with categorical index

### ISSUE THREAD

**Issue by soxofaan** [mwaskom/seaborn#1446]
When I plot some pandas data with categorical index, with `seaborn` imported, I get repeated and persistent warnings like this:

> VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

example:
![screen shot 2018-06-05 at 14 46 31](https://user-images.githubusercontent.com/44946/40976745-5907add4-68cf-11e8-8592-39daa2e6449b.png)

When I don't do the `seaborn` import, I just get one warning, which goes away when I re-execute the cell:
![screen shot 2018-06-05 at 14 46 47](https://user-images.githubusercontent.com/44946/40976748-5bdb330a-68cf-11e8-86bc-57eeaf104ab4.png)

Used versions:
- pandas: 0.23.0
- python: 2.7.15.final.0
- numpy: 1.11.3
- IPython: 5.7.0
- seaborn: 0.8.1
- matplotlib: 2.0.2

**Comment by mwaskom** [comment]
What happens if you have matplotlib imported instead of seaborn?

**Comment by soxofaan** [comment]
I had a a quick look, and this a (bit simplified) traceback of where the warning is triggered:

```
File "<ipython-input-3-de3f706d00c5>", line 1, in <module>
    x.plot()
  File "pandas/plotting/_core.py", line 2741, in __call__
    **kwds)
  File "pandas/plotting/_core.py", line 2002, in plot_series
    **kwds)
  File "pandas/plotting/_core.py", line 1804, in _plot
    plot_obj.generate()
  File "pandas/plotting/_core.py", line 266, in generate
    self._post_plot_logic_common(ax, self.data)
  File "pandas/plotting/_core.py", line 401, in _post_plot_logic_common
    xticklabels = [get_label(x) for x in ax.get_xticks()]
  File "pandas/plotting/_core.py", line 395, in get_label
    return pprint_thing(data.index[i])
  File "pandas/core/indexes/base.py", line 2071, in __getitem__
    traceback.print_stack()
pandas/core/indexes/base.py:2072: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return getitem(key)
```

the values of `key` passed to `getitem` that trigger the warning are these:
```
-0.20000000000000001
0.0
0.20000000000000001
0.40000000000000008
0.60000000000000009
0.80000000000000004
1.0000000000000002
1.2000000000000002
```

**Comment by soxofaan** [comment]
> What happens if you have matplotlib imported instead of seaborn?
it's the same as the second screenshot of my original post: just one warning that disappears when the cell is re-executed

**Comment by mwaskom** [comment]
To be clear did you just import `matplotlib` or `matplotlib.pyplot`?

**Comment by soxofaan** [comment]
doesn't seem to make a difference: `import matplotlib` or `import matplotlib.pyplot` give same results: one warning that disappears on re-execution

**Comment by mwaskom** [comment]
Weird! Really no idea then, sorry.

**Comment by mwaskom** [comment]
Actually, last idea: what if you reverse the order of the imports?

**Comment by soxofaan** [comment]
I also tried playing with the order, but does not make difference

**Comment by soxofaan** [comment]
getting somewhere:
![untitled1 2018-06-05 15-37-53](https://user-images.githubusercontent.com/44946/40979632-9ced9d4a-68d6-11e8-847c-3784bb3ae5c6.jpg)

**Comment by soxofaan** [comment]
Found it, the culprit is in statsmodels package, not seaborn itself.

Problem goes away when I disable the following line from https://github.com/statsmodels/statsmodels/commit/2c0a583d2ed69a6ee6c86f51862a9bd4c23005e3 :

```
warnings.simplefilter('always', category=UserWarning)
```

**Comment by soxofaan** [comment]
created statsmodels issue: https://github.com/statsmodels/statsmodels/issues/4711

**Comment by mwaskom** [comment]
Nice sleuthing!

**Comment by soxofaan** [comment]
FYI, my current workaround to suppress repetitive user warnings in Jupyter notebooks is to add this to the notebook:

```python
import warnings
warnings.simplefilter('once', category=UserWarning)
```
