### ISSUE TITLE
Using lmplot with fit_reg=False for scatter plots is unintuitive

### ISSUE THREAD

**Issue by kasuteru** [mwaskom/seaborn#1452]
**Problem description:**

As a newcomer to seaborn, I was quite surprised that seaborn apparently didn't handle scatterplots. After a minute of googling, I found out that I have to do a regression plot and turn the fitting of the actual regression model off. In my opinion, this is pretty unintuitive.

**Proposed fix:**

My proposed fix would be to simply have an a seaborn.scatter() or seaborn.scatterplot() method that maps to regplot with fit_reg=False. This would be really easy to implement and make seaborn more easy to understand as a newcomer or if reading code someone else wrote. Surprisingly, seaborn is currently one of the few plotting libraries in Python that support coloring scatterplots by nominal data out-of-the-box (bokeh and matplotlib don't!), so it would be nice if it actually was called scatterplot :-)

**Comment by kasuteru** [comment]
No comment about this? Would you merge it into the main branch if I implemented it myself? It does seem like a very minor, non-breaking change.

**Comment by mwaskom** [comment]
i guess your "minute of googling" did not turn up https://github.com/mwaskom/seaborn/pull/1436

**Comment by kasuteru** [comment]
In fact it did not... Seeing as this is a fairly recent change and as of now, is not even documented in the [API](https://seaborn.pydata.org/api.html). Currently, [the first google result for "seaborn scatterplot" ](https://python-graph-gallery.com/40-basic-scatterplot-seaborn/) has the following to say:

> Using seaborn, scatterplots are made using the regplot() function. 

All the other results on the first page of Google say the same or mention lmplot(). I even searched on github before posting this, but admit that I did not remove the is:issue filter that filtered out #1436. 

... Anyways, nice to know it is there now, and thanks for your work on seaborn, it has proven really useful.

**Comment by mwaskom** [comment]
Unfortunately I can't control what claims people make or what google chooses to emphasize...

My answer would have been what is in the [introductory notes](http://seaborn.pydata.org/introduction.html):

> Seaborn should be thought of as a complement to matplotlib, not a replacement for it. When using seaborn, it is likely that you will often invoke matplotlib functions directly to draw simpler plots already available through the pyplot namespace.
