### ISSUE TITLE
Boxplot hatches

### ISSUE THREAD

**Issue by agamemnonc** [mwaskom/seaborn#1456]
Is there a way to add hatches in boxes produced with seaborn boxplot?  I am thinking of something similar to [this](https://stackoverflow.com/questions/35467188/is-it-possible-to-add-hatches-to-each-individual-bar-in-seaborn-barplot/35477440), but for boxplots.

Many thanks

**Comment by mwaskom** [comment]
Have you tried that approach and found it not to work? This might be a better question for StackOverflow. There's no user-facing seaborn API for varying the hatches.

**Comment by agamemnonc** [comment]
Yes, I tried it and it didn't work. 

I will try stackoverflow, thanks anyway!

**Comment by mwaskom** [comment]
What didn't work?

**Comment by mwaskom** [comment]
This works for me?

```python
ax = sns.boxplot(x="day", y="total_bill", data=tips)
hatches = ["/", "o", "*", "\\"]
for hatch, patch in zip(hatches, ax.artists):
    patch.set_hatch(hatch)
```
![image](https://user-images.githubusercontent.com/315810/41420417-542165ea-6fc2-11e8-9d57-82905a7e72b2.png)
