### ISSUE TITLE
seaborn doesn't use figsize from matplotlib style

### ISSUE THREAD

**Issue by neighthan** [mwaskom/seaborn#1457]
I'm using a very simple style file `notebook.mplstyle`:

```
font.size: 20
figure.figsize: 10, 10
```

When I run the following code (in a Jupyter notebook)

```python
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

plt.style.use('notebook')

x = np.array([1,2,3])
y = np.array([4,5,6])

ax = sns.jointplot(x, y)
```

the font size on the plot is indeed larger, but the figure size is not. I can even check that

```python
import matplotlib as mpl
mpl.rcParams['figure.figsize']  # [10.0, 10.0]
```

Is there a way that I can get `seaborn` to respect the figure size from my style file? Or is the issue that the joint plot is composed of multiple plots and so sizing it doesn't work as well?

I have `sns.__version__` 0.8.1.

**Comment by mwaskom** [comment]
> Or is the issue that the joint plot is composed of multiple plots and so sizing it doesn't work as well?

It's this. `jointplot` and other seaborn functions that draw multi-panel figures have their own way of controlling the figure size (and default value) so that you always get a reasonably proportioned plot when you call them. Unfortunately there's no way to change that default globally.
