### ISSUE TITLE
Feature Request: Including y-errors in bootstrapping 

### ISSUE THREAD

**Issue by jrcooper91** [mwaskom/seaborn#1461]
After reading through the source/documentation, I am not seeing a clear way to include y-errors for bootstrapping using regplot, especially for those that are not standard errors/jitter (which doesn't influence fitting anyways). Of course, it is not a problem to overplot them visually, but my errors are large enough that it would influence the CI limits and it has been deemed necessary to use them. 

Excellent otherwise!

**Comment by mwaskom** [comment]
I'm sorry but it's not quite clear what you're asking for.

**Comment by jrcooper91** [comment]
Apologies for that. What I mean is the regression fitting x,y, and y errors. Right now it just takes x,y in regplot. For the example attached, I am looking to resample from x, and y(+/-), rather than just the x,y points. I hope that is more clear.
<img width="484" alt="screen shot 2018-06-18 at 18 11 03" src="https://user-images.githubusercontent.com/31331976/41548519-d652c51c-72e8-11e8-8b74-2f65490c53c3.png">
.

**Comment by mwaskom** [comment]
It sounds like you're doing something more complicated than is supported by seaborn (which is for general purpose visualization, not domain-specific modeling) and so you'll have to implement it yourself, sorry.
