### ISSUE TITLE
Decrease coupling between analytics and plotting code

### ISSUE THREAD

**Issue by jeffbaumes** [mwaskom/seaborn#1462]
Seaborn performs great analytics, but some of the information around regression and confidence intervals are deeply tied to the plotting code. They exist inside plotter classes that require a matplotlib plotting object. Separation could be beneficial for easy access to the underlying regression/confidence intervals for inspection and further analysis. Its specific value to me would be enabling alternate backends like the [Altair/Vega backend](https://github.com/Kitware/seaborn_altair) I am playing around with.

I've done a quick mockup of pulling out the [regression functions](https://github.com/mwaskom/seaborn/blob/master/seaborn/regression.py#L176-L291) from seaborn into utility methods is in [this gist](https://gist.github.com/jeffbaumes/83bd453ed70af48352d4329136ad4a84).

The maintainers may not want utilities like this to be part of the API surface, and I can work around the issue, but it could be a code organization improvement to consider.

**Comment by mwaskom** [comment]
>  They exist inside plotter classes that require a matplotlib plotting object.

Is this true? It's been a while since I looked at the older code, but the way things usually work is that you don't need a matplotlib axes to instantiate the plotters and use their methods.

That said, the plotters are private objects for a reason...

**Comment by mwaskom** [comment]
```python
x, y = np.random.randn(2, 100)
p = sns.regression._RegressionPlotter(x, y)
x, y, ci = p.fit_regression(x_range=(-3, 3))
```

**Comment by jeffbaumes** [comment]
Thanks! I had assumed too much. I thought the axes were needed since it was an argument, but looks like it's not needed if you manually pass the range.
