### ISSUE TITLE
clustermap does not work with SVG backend

### ISSUE THREAD

**Issue by zachary822** [mwaskom/seaborn#1463]
```python
import matplotlib
matplotlib.use('SVG')
import seaborn as sns
import numpy as np
sns.clusermap(np.random.rand(10, 10))
```

This snippet is enough to reproduce the error.

`AttributeError: 'FigureCanvasSVG' object has no attribute 'get_renderer'`

matplotlib==2.2.2
seaborn==0.8.1

**Comment by mwaskom** [comment]
I think this was fixed just yesterday: https://github.com/mwaskom/seaborn/pull/1460
