### ISSUE TITLE
AttributeError:  'get_renderer'

### ISSUE THREAD

**Issue by Yaser218** [mwaskom/seaborn#1473]
Hi, 

I installed seaborn package. when I run the following:

import numpy as np; np.random.seed(0)
import seaborn as sns; sns.set()
uniform_data = np.random.rand(10, 12)
print uniform_data
ax = sns.heatmap(uniform_data)

I got an error : AttributeError: 'FigureCanvasMac' object has no attribute 'get_renderer'. I have downloaded all the dependency packages.

What causes this error? 
Thank you

**Comment by mwaskom** [comment]
Closing as matplotlib issue.
