### ISSUE TITLE
Change marker style in regplot

### ISSUE THREAD

**Issue by armartin** [mwaskom/seaborn#1478]
I would like to plot a scatterplot with two annotations, showing one with color and one with point shape. I am able to pass unique colors and sizes with `scatter_kws`, but my marker annotation doesn't seem to do anything. The first few rows of my data frame called `downsampled2` looks like this:

chr | pos | a1 | a2 | rsid | nCompleteSamples | AC | ytx | beta | se | ... | chr_sort | log10p | snps | annotation | index | shape | chr_y | to_add | plot_pos | color
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 768448 | G | A | rs12562034 | 356530 | 75415.000 | 161304.00 | 0.004410 | 0.002227 | ... | 0 | 1.322109 | NaN | 1 | NaN | x | 0 | -15791.0 | 752657.0 | #a6cee3
1 | 777232 | C | T | rs112618790 | 356530 | 68048.500 | 145569.00 | 0.004784 | 0.002359 | ... | 0 | 1.370763 | NaN | 1 | NaN | x | 0 | -15791.0 | 761441.0 | #a6cee3
1 | 791853 | G | A | rs6684487 | 356530 | 67516.400 | 144484.00 | 0.005301 | 0.002372 | ... | 0 | 1.594771 | NaN | 1 | NaN | x | 0 | -15791.0 | 776062.0 | #a6cee3
1 | 814045 | C | T | rs28483835 | 356530 | 70522.100 | 150965.00 | 0.004735 | 0.002373 | ... | 0 | 1.336983 | NaN | 1 | NaN | x | 0 | -15791.0 | 798254.0 | #a6cee3
1 | 821843 | C | T | rs544157053 | 356530 | 869.643 | 1826.26 | -0.045066 | 0.020089 | ... | 0 | 1.604239 | NaN | 1 | NaN | x | 0 | -15791.0 | 806052.0 | #a6cee3

Most importantly, there are 3 different values in the color column and 2 different values (`x` or `o`) in the shape column. I'm trying to plot my data with something like this, which is really close to what I want:

```fig = sns.regplot(x='plot_pos', y='log10p', data=downsampled2, fit_reg=False, ax=ax,
scatter_kws={'facecolors': downsampled2['color'], 'edgecolors': downsampled2['color'], 's': 10, 'marker': downsampled2['shape']})
```

However, I only get the default shape:
![example](https://www.dropbox.com/s/5dze1h5cvyfeqm7/example.png?dl=1)

Am I missing something unique to the marker shape? I really appreciate any help!

**Comment by mwaskom** [comment]
This is a limitation in matplotlib ... each call to `scatter` can only draw points with a single color.

There's a function in the development version of seaborn that will get around this, though: https://github.com/mwaskom/seaborn/pull/1436

**Comment by armartin** [comment]
👍 I'll follow that thread. Thanks!
