### ISSUE TITLE
Jointplot with colors according to classes

### ISSUE THREAD

**Issue by seralouk** [mwaskom/seaborn#1486]
Hello,

I would like to ask how it is possible to plot a jointplot with colors according to classes.

Some data and code can be found here: https://stackoverflow.com/questions/51210955/seaborn-jointplot-colors-for-each-point-according-to-class

**Comment by mwaskom** [comment]
Please don't duplicate questions in multiple channels.

**Comment by azrdev** [comment]
Having this in the `jointplot` wrapper would be a very useful addition, IMHO, and was already discussed in (at least) #861 and #365
