### ISSUE TITLE
 UserWarning: The following kwargs were not used by contour: 'label', 'color'   s)

### ISSUE THREAD

**Issue by WrongProvider** [mwaskom/seaborn#1489]
Hi, I got this warning when running this code:
`irisg = sns.PairGrid(iris)
irisg.map_lower(sns.kdeplot)
plt.show()`

I'm with **Conda 4.55** , **Seaborn 0.81** and **Matplotlib 2.22 **
It still does the kdeplot.

**Comment by mwaskom** [comment]
This is a basically innocuous warning. `PairGrid` always passes `color` and `label` parameters but the `plt.contour` function used internally by 2D kdeplots doesn't know what to do with them. This was improved recently in https://github.com/mwaskom/seaborn/pull/1474
