### ISSUE TITLE
[Feature request] Support `lineplot` with error bands of list of scaled standard deviations

### ISSUE THREAD

**Issue by zuoxingdong** [mwaskom/seaborn#1492]
In the context of research, e.g. we collect data with 10 random seeds, it is very nice to use `lineplot` to draw uncertainty bands. 

However, we often need to have a few more shaded uncertainty bands to plot, for example
1. darker shaded area with +- 0.5* standard deviation
2. medium translucent shaded area with +- 1* standard deviation
3. lighter shaded area with +- 2* standard deviation

What has been supported for now is we can either set up `ci` values as percentage of confidence interval or using `ci="sd"` to draw +- 1 standard deviation. 

It will be much easier to support things like `ci=[(0.5, "sd"), (1.0, "sd"), (2.0, "sd")]` and transparency automatically adjusted for each bands.

**Comment by mwaskom** [comment]
#2407 added the ability to draw errorbars with a parameterized (scaled) standard deviation errorbar  e.g. 

```python
fmri = sns.load_dataset("fmri")
sns.lineplot(data=fmri, x="timepoint", y="signal", errorbar=("sd", 2))
```

Adding multiple errorbars within a single function call ended up feeling like it added too much complexity at this stage. However, it is of course possible to achieve by calling `lineplot` multiple times e.g.

```python
fmri = sns.load_dataset("fmri")
sns.lineplot(data=fmri, x="timepoint", y="signal", errorbar=("sd", 1), color="C0")
sns.lineplot(data=fmri, x="timepoint", y="signal", errorbar=("sd", 2), color="C0", ls="")
```

matplotlib's alpha blending is not perfect, but I think this works well enough for most cases. It's possible that multiple errorbars will get revisited in the future if the architecture changes enough to make it more straightforward to add, but I am going to close this issue for now.
