### ISSUE TITLE
How to draw rounded rectangles when using violinplot?

### ISSUE THREAD

**Issue by pressureless** [mwaskom/seaborn#1497]
I want to get a violinplot picture like this.
![rounded](https://user-images.githubusercontent.com/8511053/42761897-6ff8c16c-8941-11e8-8972-34df02b7cac0.png)
But when I ran the code, what I really got was this.
![normal](https://user-images.githubusercontent.com/8511053/42762008-b9e559b6-8941-11e8-8e82-9fbc719b2f5d.png)
At first, I thought there must be a parameter to controll it, but I didn't find any clues by searching the internet. 
Then I thought it would be an out-moded feature which has been discarded now, so I read the API history about violinplot, still get nothing.
Could someone tell me the reason?Thanks a lot.

**Comment by mwaskom** [comment]
An obvious difference between the two plots is that the example you're trying to reproduce has the default seaborn theme set whereas the plot you're making doesn't. The answer will by in the parameters that the theme sets. I think it's the `solid_capstyle="round"` parameter.
