### ISSUE TITLE
Feature request: Annotote select cells in heatmaps

### ISSUE THREAD

**Issue by AllanLRH** [mwaskom/seaborn#1503]
Would be nice to be able to mask out certain coordinates/cells of the heatmap annotation using a Numpy masked array (or another solution), such that there's no labels shown on the masked locations.

As an example, take the plot below:
![index](https://user-images.githubusercontent.com/2641327/42907970-cd6fbd56-8adf-11e8-8689-fe06cf75dd36.png)

The zero-labels are the masked entries in the array passed to the `annot`-keyword. But I guess that I could simply have set those entries to 0 in order to achieve a zero-label, so not showing a label could be a better way to use masked out values? It adds functionality without cluttering the interface of the heatmap function :)

I really enjoy the ease with which I can create high quality figures in Seaborn, but I think annotating every single cell in the heatmap can be a bit overwhelming... When I look at the figure above, I find that I don't really read the annotations, but rather sees them as "noise".
Aditionally a lot of values are very similar — a trait which I suspect a lot of heatmaps share — which I think is the best argument for why annotating every single cell becomes "visual noise".

Hope to hear your thoughts on the matter :)

**Comment by mwaskom** [comment]
I think this is already possible in a slightly unintuitive way by making a fully annotated heatmap then drawing a second unannotated heatmap on top of it using the mask complement so it only draws cells where you don't want to see the annotation.

I'd show an example but you don't provide any example code in your question.
