### ISSUE TITLE
Can't handle more than 6 styles

### ISSUE THREAD

**Issue by mueslo** [mwaskom/seaborn#1511]
Plotting e.g. `sns.lineplot(x="airflow", y="noise", hue="name",  style="name", data=df, markers=True)` with more than 6 different names gives  `ValueError: These `style` levels are missing dashes`.

Expected behaviour: Marker and line style loop cyclically and their sizes have a large least common multiple so the period between recurring styles is large.

**Comment by mwaskom** [comment]
I'm closing in favor of #1513 which is a bit more general and includes a runnable example. Feel free to weigh in there.
