### ISSUE TITLE
relplot error when using str as hue

### ISSUE THREAD

**Issue by Urm3l** [mwaskom/seaborn#1515]
When I am trying to use a string or categorical column within a dataframe as hue within a relplot we get the following error:
`AttributeError: 'str' object has no attribute 'view'`

Minimal example:
```
test_df = pd.DataFrame(
[{"a": 0.0, "b": 1.0, "c": "1", "d": "1"},
 {"a": 0.0, "b": 1.0, "c": "2", "d": "2"}]
)
g = sns.relplot(x="a", y="b", col="c",  hue="d", data=test_df)
```

**Comment by AndreasMittermeier** [comment]
Even when explicitly changing type to category, it throws the same error:
```
test_df = pd.DataFrame(
[{"a": 0.0, "b": 1.0, "c": "1", "d": "1"},
 {"a": 0.0, "b": 1.0, "c": "2", "d": "2"}]
)
test_df.d=test_df.d.astype('category')
g = sns.relplot(x="a", y="b", col="c",  hue="d", data=test_df)
```
`AttributeError: 'str' object has no attribute 'view'`

Plus, when putting int/floats instead of str, you get:
```
test_df = pd.DataFrame(
[{"a": 0.0, "b": 1.0, "c": "1", "d": 1},
 {"a": 0.0, "b": 1.0, "c": "2", "d": 2}]
)
test_df.d=test_df.d.astype('category')
g = sns.relplot(x="a", y="b", col="c",  hue="d", data=test_df)
```
`TypeError: data type not understood`

What works are strings that are NOT just numbers:
```
test_df = pd.DataFrame(
[{"a": 0.0, "b": 1.0, "c": "1", "d": "one"},
 {"a": 0.0, "b": 1.0, "c": "2", "d": "two"}]
)
test_df.d=test_df.d.astype('category')
g = sns.relplot(x="a", y="b", col="c",  hue="d", data=test_df)
```
![test_img_relplot](https://user-images.githubusercontent.com/9657209/43312402-b3f382ce-917c-11e8-9935-793fcbdfe7aa.png)

**Comment by mwaskom** [comment]
I think the problem here is that seaborn is duck typing whether the hue variable is categorical or numeric based on whether it can be converted to float without erroring, but then using the original data for getting the colors. Passing numerics as strings is kind of a weird corner case, but it shouldn't be impossible. There's a similar issue in PairGrid (#1347) and so a good general solution is needed.

I think in the meantime, a workaround would be to provide explicit colors values to the palette (either as a list or dictionary) which should skip the numeric color-mapping code;

```python
test_df = pd.DataFrame(
[{"a": 0.0, "b": 1.0, "c": "1", "d": "1"},
 {"a": 0.0, "b": 1.0, "c": "2", "d": "2"}]
)
g = sns.relplot(x="a", y="b", col="c",  hue="d", palette=["r", "b"], data=test_df)
```

**Comment by ImportanceOfBeingErnest** [comment]
Related: As to why it may be good to have numerical strings: https://stackoverflow.com/questions/51525284/the-hue-parameter-in-seaborn-relplot-skips-an-integer-when-given-numerical-d

**Comment by mwaskom** [comment]
@ImportanceOfBeingErnest that behavior is not a bug, but thanks for updating the original answer which was simply incorrect.

**Comment by ImportanceOfBeingErnest** [comment]
Leaving a note below an incorrect answer helps in such cases.

Anyways, you may not call it bug, but I still think it's better not to [let numpy decide](https://github.com/mwaskom/seaborn/blob/f0349b1a7f1e022cb1da8b94f2e019f04eeed397/seaborn/relational.py#L529) whether the user wants categoricals or not. 

I did [propose something similar](https://github.com/matplotlib/matplotlib/pull/11127) to add to matplotlib, which of course also has the problem of guessing what the user wants, but solves this a bit differently.

**Comment by mwaskom** [comment]
> Leaving a note below an incorrect answer helps in such cases.

I'm pretty busy. I view the optimal solution as people not confidently asserting things that are incorrect.

> Anyways, you may not call it bug, but I still think it's better not to let numpy decide whether the user wants categoricals or not.

I'm not really interested in having an argument with you about this, but it is not uncommon in pandas (i.e. the data library most commonly used with seaborn) to have numeric data stored with an object datatype, for example if you have integers and missing data.

**Comment by benlindsay** [comment]
I came across the same thing with lineplot. Strangely I found that using values of `'0'` and `'1'` for strings in the hue column will get plotted correctly , but using any other combinations of numeric strings throws the `AttributeError: 'str' object has no attribute 'view'` error. I.e. using `'0'` and `'2'` throws the error. Any idea why that might be?

**Comment by mwaskom** [comment]
Yes, "boolean" data are [special-cased](https://github.com/mwaskom/seaborn/blob/master/seaborn/relational.py#L523) to default to categorical treatment, so they avoid the bug where numeric operations are done on string arrays.

**Comment by QuentinAndre** [comment]
Another inconsistent behavior that seems connected to this issue:

Case 1 (will generate a legend for [0, 1, 2]
```
df = pd.DataFrame({"Condition": np.random.choice([1, 2], 100),
                  "ScoreA": np.random.normal(0, 1, 100),
                  "ScoreB": np.random.normal(0, 1, 100)})
sns.relplot(x="ScoreA", y="ScoreB", hue="Condition", data=df)
```

Case 2 (will generate a legend for [0, 1, 2, 3]
```
df = pd.DataFrame({"Condition": np.random.choice([1, 2, 3], 100),
                  "ScoreA": np.random.normal(0, 1, 100),
                  "ScoreB": np.random.normal(0, 1, 100)})
sns.relplot(x="ScoreA", y="ScoreB", hue="Condition", data=df)
```

Case 3 (will generate a legend for [1, 2, 3, 4]
```
df = pd.DataFrame({"Condition": np.random.choice([1, 2, 3, 4], 100),
                  "ScoreA": np.random.normal(0, 1, 100),
                  "ScoreB": np.random.normal(0, 1, 100)})
sns.relplot(x="ScoreA", y="ScoreB", hue="Condition", data=df)
```

**Comment by michaelaye** [comment]
I just had the same, where my hue was the Martian year number, that starts with 28 for Mars Reconnaissance Orbiter data. In my case, I was dealing with data for Martian Years 29 and 30, and was very perplexed that the scatterplot created a year 28 entry despite my dataframe only having values 29 and 30 for the hue column. 
I think it would be really useful if the `hue` parameter would fully support numerical values, but I guess it should be constrained to integers, to avoid floating point issues.

**Comment by rhgatti** [comment]
Hi,
The problem is solved using floating point numbers.
test_df = pd.DataFrame(
[{"a": 0.0, "b": 1.0, "c": "1", "d": 1.0},
 {"a": 0.0, "b": 1.0, "c": "2", "d": 2.0}]
)
g = sns.relplot(x="a", y="b", col="c",  hue="d", data=test_df)

**Comment by danolson1** [comment]
I just ran into the same problem. I had multiple sets of data that were identified by a category, in my case, a date. '11_25_18' Trying to use this in the 'hue' parameter gave an error. When I renamed the category 'exp11_25_18,' the error went away. To me, this feels like a bug.

**Comment by gokceneraslan** [comment]
Reproducible examples:

```python
df = pd.DataFrame({'x': [1,2], 'y': [3,4], 'hue': [10, 20]})
df.hue = df.hue.astype('category')
sns.scatterplot('x', 'y', hue='hue', data=df)
```

`TypeError: data type not understood`

```python
df = pd.DataFrame({'x': [1,2], 'y': [3,4], 'hue': [10, 20]})
df.hue = df.hue.astype(str)
sns.scatterplot('x', 'y', hue='hue', data=df)
```

`AttributeError: 'str' object has no attribute 'view'`

**Comment by ifly6** [comment]
I too am having this problem.

**Comment by teckwanikaran** [comment]
This is my first time ever commenting on an open issue, so please be kind if I am wrong! 

I was facing similar issues, till I referred to this [post](https://stackoverflow.com/questions/26139423/plot-different-color-for-different-categorical-levels-using-matplotlib) on stackoverflow

- Problem: I have about 16 unique numerical str values as id (like: '215' '112233', ...)
- The fix: Use your palette size to be same as the unique numerical str values. 
- example: 
`sns.lineplot(data=df, x='x', y='y', hue='id', palette=sns.color_palette("Set1", 16))`
- or 
`sns.scatterplot(data=df, x='x', y='y', hue='id', palette=sns.color_palette("Set1", 16))`

**Comment by bhattaraiprabhat** [comment]
@teckwanikaran I works!

**Comment by JayMan91** [comment]
I also faced this same issue. it is resolved when I provide a custom palette in the argument.

**Comment by hugadams** [comment]
Another edgecase - I experience the same error when my array values were ints (1,2,3,4,5,nan). 

    AttributeError: 'int' object has no attribute 'view'

Turned out that I was using a Colormap object from matplotlib which worked correctly when my values were floats (ie. 1.0 - 5.0)

      cmap = ListedColormap(sns.color_palette(sns.xkcd_palette(["green", "pistachio", "yellow", "orange", "red"]), 5))

However when changing to int, I dropped the ListedColormap directly

    cmap = sns.color_palette(sns.xkcd_palette(["green", "pistachio", "yellow", "orange", "red"]), 5)

Again, not sure if this is helpful to anyone but I stumbled on this solution from reading the current thread.

**Comment by VincentSch4rf** [comment]
@teckwanikaran thank you very much for sharing this! You saved my day!

I was facing this issue after I first tried to provide a numerical dataset as `hue` input. However, this turned out to produce not actually the expected result. It split the graph into three different categories, although the data provided contained 36 unique numerical values. Also, the three categories were completely "random". They did not represent the input data at all.
What is the intended behaviour for a numerical input?

**Comment by ggaemo** [comment]
So how is this going to be fixed? @teckwanikaran do we have to resort to this temporary fix?

**Comment by teckwanikaran** [comment]
@mwaskom did this fix work? https://github.com/mwaskom/seaborn/commit/ff27ace34f30fabe7d5b58c0f86e59471194c874
can you please address @ggaemo question!

**Comment by chenye** [comment]
Another simple workaround, if you don't want to dive into the technical details, is to modify the categorical values. You can simply add a space, e.g., "2019" --> "2019 ", or add something meaningful, e.g., "2019" --> "year 2019". A simple "apply" would be sufficient.

While this works, I still hope this problem will be truely fixed from the inside of the package.

**Comment by anisayari** [comment]
> post

Thanks @teckwanikaran  !
