### ISSUE TITLE
How about  adding some winsorizing function before plotting? 

### ISSUE THREAD

**Issue by FukoH** [mwaskom/seaborn#1520]
When there are some outliers in the data,the range of axis may become too large,
![image](https://user-images.githubusercontent.com/11989383/43299316-497ee18a-918c-11e8-983b-081d9f1cdb0c.png)
After winsorizing,it looks better:
![image](https://user-images.githubusercontent.com/11989383/43299339-64370106-918c-11e8-8afb-f8306ef9b543.png)

Maybe just something in `scipy.stats.mstats.winsorize ` can help

Maybe new api looks like this,and winsorizing is optionally applied to each hue class or whole data
`sns.boxplot(x='foo',data=data,hue='bar',winsorizing=**kargs)`

**Comment by mwaskom** [comment]
I think this is probably something better handled by the user before plotting, sorry.

You could also try a log scale.
