### ISSUE TITLE
FacetGrid legends are not revealed in MacOSX GUI

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#1527]
They'll be hidden when the window pops up, but will appear if you drag it to adjust the size.

Not a problem with a qt5 gui window (or in the notebook backends).

Also not a problem if saved to png.

**Comment by MaozGelbart** [comment]
Possibly due to [https://github.com/matplotlib/matplotlib/issues/15131](https://github.com/matplotlib/matplotlib/issues/15131). A fix implemented in matplotlib3.3 which will hopefully be released soon.

**Comment by mwaskom** [comment]
Huzzah!

**Comment by MaozGelbart** [comment]
I can reproduce this with matplotlib==3.2.2 but not with matplotlib==3.3.0rc1.

**Comment by mwaskom** [comment]
Great!
