### ISSUE TITLE
Legend not outside for lmplot 

### ISSUE THREAD

**Issue by jadolfbr** [mwaskom/seaborn#1528]
Using lmplot, the legend is not outside of the current figure.  If I turn off the legend and try to do it manually through Python, the figure looks squeezed in some way. 

I have updated Seaborn, Notebook, etc.  

`g = seaborn.lmplot( x="rmsd", y="score_rank", data=ranks, fit_reg=True, hue='experiment-neat', legend_out=True)`

![normal_rank_vs_rmsd_swapped_together](https://user-images.githubusercontent.com/3290052/43615988-fbef1310-967f-11e8-8380-eab243da4f0c.png)

Seaborn Version: .9
Matplotlib Version: 2.2.2
Jupyter Notebook Version: 5.6; ipython 5.8

**Comment by jadolfbr** [comment]
Same behavior for FacetGrid. 

![testing_sea](https://user-images.githubusercontent.com/3290052/43616471-3dcee2fe-9682-11e8-8851-5530c6fbb0ce.png)

**Comment by mwaskom** [comment]
Duplicate of #1527?

To know for sure I'd need to [know what matplotlib backend](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs) you're using.

And I'm not sure what you mean by "If I turn off the legend and try to do it manually through Python, the figure looks squeezed in some way." Hard to understand things without seeing reproducible code I can run myself.

**Comment by jadolfbr** [comment]
I don't think this a duplicate as the legend is there, its just within the plot itself. 
Backend: 'module://ipykernel.pylab.backend_inline'

What I meant by 'If I turn off legend', I mean this:
(Note that the plot looks the same whether I call pyplot or `g.ax`
```
g = seaborn.lmplot( x="rmsd", y="score_rank", data=ranks, fit_reg=True, legend='False', hue='experiment-neat', legend_out=True)

plt.legend(bbox_to_anchor=(1.5, 0), loc='lower right', fontsize=9)
```

![normal_rank_vs_rmsd_swapped_together_bbbox](https://user-images.githubusercontent.com/3290052/43619011-54a1910c-9691-11e8-8735-1888dc8fd5ef.png)

It gets a little odder.  I accidentally typed `legend='False' `when making this example, and it seems to put the legend from seaborn exactly where it should be, but then adds another legend.  If I leave out the call to `pyplot.legend()`, thinking maybe I would get the plot I wanted without the extra legend, the behavior is the same as with `legend=True` (in the original post). 

```
g = seaborn.lmplot( x="rmsd", y="score_rank", data=ranks, fit_reg=True, legend='False', hue='experiment-neat')
plt.legend(bbox_to_anchor=(1.5, 0), loc='lower right', fontsize=9)
```

![normal_rank_vs_rmsd_swapped_together_bbbox](https://user-images.githubusercontent.com/3290052/43619224-5c8dfc10-9692-11e8-9c02-75ecadffe921.png)

**Comment by jadolfbr** [comment]
I will get code that uses one of the inbuilt datasets and see if I can reproduce the problem with it.

**Comment by jadolfbr** [comment]
Using the planets dataset, I get the same issue:

```
f = seaborn.load_dataset("planets")
g = seaborn.lmplot( x="orbital_period", y="year", data=f, fit_reg=True, hue='method', figure_out=True)
```

![normal_rank_vs_rmsd_swapped_together1](https://user-images.githubusercontent.com/3290052/43623447-d9ae73f0-96a6-11e8-8840-6b0530e5b49a.png)

```
g = seaborn.lmplot( x="orbital_period", y="year", data=f, legend='True', fit_reg='True', figure_out=True, hue='method')
g.ax.legend(bbox_to_anchor=(1.5, 0), loc='lower right', fontsize=9)
```

![normal_rank_vs_rmsd_swapped_together2](https://user-images.githubusercontent.com/3290052/43623458-eb46dde6-96a6-11e8-9b9c-9667083a845e.png)

**Comment by mwaskom** [comment]
You must be doing something other than the code you're showing because the labels of the figures with the planets dataset don't correspond to what's in that dataset. Please try to share a *complete, reproducible*  example. That means something I could copy and paste into a fresh kernel and get (or not get) the figure your'e seeing.

By the way, in some of your examples part of the problem is that you're doing `legend='False'` instead of `legend=False`. In Python, a non-empty string will evaluate to `True` in a boolean context.

**Comment by jadolfbr** [comment]
Only difference is that I called to set an x/y label when I copied the code.  Here is a better, cleaner, example:
```
import seaborn
f = seaborn.load_dataset("planets")
g = seaborn.lmplot( x="year", y="orbital_period", data=f, legend=True, fit_reg=False, hue='method', legend_out=True)
```

This gives the following plot:
![normal_rank_vs_rmsd_swapped_together1](https://user-images.githubusercontent.com/3290052/43654561-47fdb23e-9711-11e8-86d6-8119dfc2e964.png)

If you give`legend=True` and then call plt.legend() the legend created by Seaborn moves accordingly.

```
import seaborn
f = seaborn.load_dataset("planets")
g = seaborn.lmplot( x="year", y="orbital_period", data=f, legend=True, fit_reg=False, hue='method', legend_out=True)
g.ax.legend(bbox_to_anchor=(1.5, 0), loc='lower right', fontsize=9)
```

![normal_rank_vs_rmsd_swapped_together2](https://user-images.githubusercontent.com/3290052/43654567-4bdc0626-9711-11e8-88a3-ba3c623fbef8.png)

**Comment by mwaskom** [comment]
> Only difference is that I called to set an x/y label when I copied the code. Here is a better, cleaner, example:

> This gives the following plot:

When I run this example with seaborn 0.9 and matplotlib 2.2.2 with the inline backend I don't reproduce your problem.

But I'd note that the plot you're showing can't literally have been made only with that code. The axes labels are too big and there is a grid, which wouldn't happen by default. So there must be some code you're running that you are not showing me.

Please: create a *fully reproducible example* documenting the problem. I'm sorry if this is coming off as short, but having to repeat this request is not a great use of my time.

**Comment by jadolfbr** [comment]
I'm sorry that you had to repeat this.  I normally code C++ in the Rosetta Software suite.  My intention was not to waste your time.  I forgot that I have a matplotlibrc file that I've been using for a while.  Perhaps that is causing it.  I did check for legend settings just now, and none of them were on. No other code is being called besides `%matplotlib inline`

I've used the rc file to make plots look better in matplotlib in general.  With the new style sheets, I can probably switch to not using them. 
The rc file is here: https://github.com/SchiefLab/Jade/blob/master/database/matplotlib/pretty_matplotlibrc

If you don't want to spend any more time with this, I understand.  I haven't had any other problems in the years I've been using this rc file.  If you can reproduce the behavior with the RC file, that would be great as at least we know that its something funky going on there.  Sorry that you didn't have all of the info in the beginning.  I spend half my year debugging code - so I understand that that was frustrating.  It was not my intention.

**Comment by mwaskom** [comment]
> I forgot that I have a matplotlibrc file that I've been using for a while. Perhaps that is causing it.

Ah, yes. And I could see how that wouldn't have been obvious to you. (One of the reasons I don't like the rc file system and opted for a more explicit approach to theming in seaborn).

That could be the culprit ... I can't think of any rcParams that might be doing this off the top of my head, but it would be useful to know if they exist.

The easiest way to test would be to have you run 

```
import matplotlib as mpl
mpl.rcParams.update(mpl.rcParamsDefault)
```

After you import matplotlib but before plotting with seaborn. If you get the expected plot, then we can try to diff your rcParam file and narrow down what the issue is.

**Comment by jadolfbr** [comment]
That was it.  I ran `mpl.rcParams.update(mil.rcParamsDefault)` and got the expected plot. Looks quite great too.  I think I should probably just stop using that Rc file to begin with - or at least disable it for seaborn plots - but yes, it would be good to know exactly what param is causing this.  Thank you for your patience!  What would be the easiest way to get the diff?

**Comment by mwaskom** [comment]
If your you have  rc params are in effect, this will tell you which ones differ:

```
{k: v for k, v in mpl.rcParams.items() if mpl.rcParamsDefault[k] != v}
```

But I bet the problem can be isolated to the fact that you're setting `figure.autolayout : True`.

**Comment by jadolfbr** [comment]
That was it.  I checked the settings, and then turned that to False:
`mpl.rcParams['figure.autolayout'] = False`

And I get the correct plot.  Thanks again for your help!
