### ISSUE TITLE
catplot run slower than boxplot

### ISSUE THREAD

**Issue by jt120** [mwaskom/seaborn#1529]
I use two method plot box, 
1. sns.catplot(kind='box')
2. sns.boxplot

same data volumn, but catplot run slower than boxplot

version: 0.9.0

**Comment by mwaskom** [comment]
I cannot help you without a complete and reproducible example.

**Comment by mwaskom** [comment]
I'm closing because this is not actionable but I'll reopen if you can produce a reproducible example that demonstrates a significant problem.

**Comment by jt120** [comment]
I think this is the different.

for boxplot, it returns `ax`, and for catplot, it returns `FacetGrid`

code like this 
```
import seaborn as sns
tips = sns.load_dataset('tips')
%timeit -n 10 -r 5 sns.boxplot(x='sex', y='total_bill', data=tips)
# 22.5 ms ± 582 µs per loop (mean ± std. dev. of 5 runs, 10 loops each)

%timeit -n 10 -r 5 sns.catplot(x='sex', y='total_bill', data=tips, kind='box')
#68.3 ms ± 1.54 ms per loop (mean ± std. dev. of 5 runs, 10 loops each)
```

**Comment by mwaskom** [comment]
Yes, nothing surprising here. The catplot test will be making a new figure each time it runs, whereas the boxplot test will make one figure the first time boxplot is called and then plot a large number of boxes onto it.
