### ISSUE TITLE
Change load_dataset cache dir default

### ISSUE THREAD

**Issue by mightyCelu** [mwaskom/seaborn#1530]
The current default for `seaborn.load_dataset`s `data_home` directory, which is used for caching is `$HOME/seaborn-data`. This leads to unwanted pollution of the user's home directory. The calls used in many seaborn examples use only the dataset's name, just from this, it is unclear that by default a cache directory will be created in such a prominent location.

I believe a good alternative location be `$XDG_CACHE_DIR`, which according to the freedesktop specification is supposed to be used for _user-specific non-essential (cached) data_ (see [specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)). If the environment variable is unset, a default of `$HOME/.cache` is recommended.

**Comment by mwaskom** [comment]
I think @jakevdp just copied what scikit-learn does.

**Comment by mightyCelu** [comment]
On Linux I believe it is widely used, at least the major DEs follow it. On my machine the `$HOME/.cache` directory contains about fifty directories of individual applications without me explicitly configuring any of them to use it.

On other platforms there are probably similar directories, a quick search for windows brought me to a [ticket](https://github.com/electron/electron/issues/1404) of the electron project where a similar problem is discussed. It indicates that on Windows `LOCALAPPDATA` is a preferred location.

**Comment by mwaskom** [comment]
The example datasets are not very large so I would like to avoid too much complexity. I'm open to changing where the data goes, but I would like to pick a single alternative.

**Comment by mightyCelu** [comment]
I don't think that there is a one-size-fits-all solution, since seaborn is used in Windows, Mac OSX and Linux, where all of these have different concepts. The only one I can think of is to use a hidden folder.

Of course, the datasets are not large, but imho that doesn't really affect the problem, since it's more about the intransparent creation of a directory.

Also, I believe that the added complexity isn't really too much. I had a look at how Qt handles this, since they specifically aim to ease multiplatform development. They provide a utility which returns a proper path for all platforms. It could be implemented like this:

```
def _get_cache_path():
    """Return a path to a directory to be used for caching application data.
    """
    import sys
    import os

    path = None
    if sys.platform.startswith('linux') or sys.platform.startswith('freebsd'):
        path = os.getenv('XDG_CACHE_HOME', '~/.cache')
    elif sys.platform.startswith('win32') or sys.platform.startswith('cygwin'):
        path = os.getenv('LOCALAPPDATA', '~')
    elif sys.platform.startswith('darwin'):
        path = '~/Library/Caches'

    if not os.path.isdir(path):
        path = '~'

    return os.path.expanduser(os.path.join(path, 'seaborn-data'))
```

**Comment by mwaskom** [comment]
> I don't think that there is a one-size-fits-all solution, since seaborn is used in Windows, Mac OSX and Linux, where all of these have different concepts. The only one I can think of is to use a hidden folder.

If there isn't, it would weigh in favor of keeping the status quo.

> Of course, the datasets are not large, but imho that doesn't really affect the problem, since it's more about the intransparent creation of a directory.

The point is, if the datasets are not large, it's less important that a user who is looking to clear space on their computer would need to find them and remove. So it's ok if they end up in a somewhat obscure place.

**Comment by mightyCelu** [comment]
> The point is, if the datasets are not large, it's less important that a user who is looking to clear space on their computer would need to find them and remove. So it's ok if they end up in a somewhat obscure place.

For me, the argument is less about space that needs to be cleared but rather that it is very easy to inadvertently create these directories at a very visible location. This is how I noticed the behavior in the first place and why I reported it. I believe that the fact that for the major platforms there are official guidelines on where to put such data ([MSDN](https://blogs.msdn.microsoft.com/patricka/2010/03/18/where-should-i-store-my-data-and-configuration-files-if-i-target-multiple-os-versions/), [Apple Developer](https://developer.apple.com/icloud/documentation/data-storage/index.html, Linux).

I get that for such a minor feature one does not want to add too much code which might fail in the future, however I feel that when targeting a platform one should stick to the recommended best practices.

**Comment by mwaskom** [comment]
> For me, the argument is less about space that needs to be cleared but rather that it is very easy to inadvertently create these directories at a very visible location. This is how I noticed the behavior in the first place and why I reported it. 

Yes, we're talking past each other. I agree that defaulting to $HOME is suboptimal. I'm giving an argument for using a consistent, possibly obscure (even hidden) location across file systems rather than trying to pick the "correct" place for every file system. I think `$HOME/.cache/seaborn` is reasonable, although I don't know the details of dealing with hidden files on Windows (or other non-unix systems if they are being used).

**Comment by mightyCelu** [comment]
Afaik using hidden files with Windows involves some magic with setting file attributes.

Which other non-unix systems are there? I currently can't really think of any.

`$HOME/.cache/seaborn` would be the intended location at least for Linux (so that would scratch my itch :-)), it might be a bit unorthodox on Windows, but for OSX I assume that other applications also use that directory.

**Comment by QuLogic** [comment]
If you're okay with another dependency, there are things like [appdirs](https://pypi.org/project/appdirs/) which take care of following all the cross-platform standards for you.

**Comment by flying-sheep** [comment]
The location appdirs provides has the advantage that all OSs know about it and will pop up a little “do you want to clear out cache locations” if your disk space gets low.

So I’d argue those are the only correct locations for cache data on the respective OSs.

**Comment by mwaskom** [comment]
It looks like `appdirs` (thanks @QuLogic) is a single Python module and is MIT licensed, so I would be open to vendoring it and installing the datasets in its preferred cache location.

**Comment by flying-sheep** [comment]
You should use [`platformdirs`](https://github.com/platformdirs/platformdirs#why-this-fork):

> This repository is a friendly fork of the wonderful work started by [ActiveState](https://github.com/ActiveState/appdirs) who created `appdirs`, this package's ancestor.
> 
> Maintaining an open source project is no easy task, particularly from within an organization, and the Python community is indebted to `appdirs` (and to Trent Mick and Jeff Rouse in particular) for creating an incredibly useful simple module, as evidenced by the wide number of users it has attracted over the years.
> 
> Nonetheless, given the number of long-standing open issues and pull requests, and no clear path towards [ensuring that maintenance of the package would continue or grow](https://github.com/ActiveState/appdirs/issues/79), this fork was created.

**Comment by flying-sheep** [comment]
> is a single Python module

Sorry, but basing any decision on if something is a single Python file or not doesn’t seem like a function selecting for code quality or any other measure of relevance …

And why vendor things? Python has a dependency management system for a reason.

**Comment by mwaskom** [comment]
It seems like appdirs solves the very specific problem here so it’s not obvious that stalled development is a problem. 

Also, flying-sheep is now blocked for being rude.
