### ISSUE TITLE
UserWarning matplotlib: The 'normed' kwarg is deprecated

### ISSUE THREAD

**Issue by vikash310** [mwaskom/seaborn#1533]
C:\Users\user\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.

Please suggest!! how to remove such warning?

**Comment by mwaskom** [comment]
Duplicate of https://github.com/mwaskom/seaborn/issues/1392
