### ISSUE TITLE
Bad crop on example thumbnails ot official site

### ISSUE THREAD

**Issue by IvanKargapoltsev** [mwaskom/seaborn#1534]
Hi!

Unfortunately, in most cases I can't understand what expect me after click. Please fix it.
https://seaborn.pydata.org/index.html

![sns](https://user-images.githubusercontent.com/5619581/43729556-4eed7da2-99b1-11e8-90cd-1f8c4acf93ea.png)
![sns2](https://user-images.githubusercontent.com/5619581/43729558-4f22c96c-99b1-11e8-9748-c28c18d40a07.png)

**Comment by mwaskom** [comment]
No thank you.
