### ISSUE TITLE
[Feature request]: Lineplot error bands from multiple lines with different x values

### ISSUE THREAD

**Issue by zuoxingdong** [mwaskom/seaborn#1535]
One common way to use lineplot to generate uncertainty bands is to use multiple lines with different y values with identical x value. 

However, it can be useful in research plots that the logged data for each line has different x values, and we still want to plot its uncertainty bands, which is not directly possible in current lineplot API.

A workaround solution is to do a interpolation to have a line function for each line and then to generate corresponding y values with identical x values. 

It would be very nice that this is done internally, the user can simply give a set of x values and a set of y values. 

e.g.
```
x1 = [1, 2, 3]
y1 = [1.2, 2.3, 3.4]
x2 = [1.5, 2.5, 3.5]
y2 = [2.1, 3.2, 4.3]
sns.lineplot(x=[x1, x2], y=[y1, y2])
```

**Comment by mwaskom** [comment]
This can already be done with the current API, just not the way you're proposing. I'd suggest making a reproducible example and asking on stackoverflow.

**Comment by zuoxingdong** [comment]
@mwaskom Thank you for the information. I shall write a question in stackoverflow because it seems it has not been asked before. Just for a quick idea, do you see which part can make it work with current API ? I also tried with units, but it displays lines individually, the error bands cannot be calculated as estimate must be None when setting units.
