### ISSUE TITLE
Unable to import seaborn library

### ISSUE THREAD

**Issue by mahmad321git** [mwaskom/seaborn#1539]
I am unable to import seaborn library in my jupyter notebook nor in other editer. Other libraries seems to be working fine but when i import the seaborn i get the following error.
 
![again](https://user-images.githubusercontent.com/35655048/43991103-2e80bf7c-9d1a-11e8-9b46-df2f99ac25c7.PNG)

Error: 
![seaborn](https://user-images.githubusercontent.com/35655048/43991065-b0161128-9d19-11e8-9b55-b7181dcb1836.PNG)

Scipy and Seaborn Versions:
![n](https://user-images.githubusercontent.com/35655048/43991078-d798e612-9d19-11e8-80df-c51ff3ef7822.PNG)

**Comment by mwaskom** [comment]
This is a problem importing scipy, not a problem importing seaborn. If you read the ImportError message, it provides a clear solution to the problem.

**Comment by mahmad321git** [comment]
Hi,
thanks @mwaskom  I followed the ImportError message but could not have resolved it.
Here's what i did:
 1 I closed the editor and relaunched it
 2 I open different editor(spyder, ipython) and tried importing the library from there
 3 I updated the conda, scipy, seaborn
Got the same Import error msg after trying the above steps.
I have tried googling it from different resources, read github articles.
https://stackoverflow.com/questions/25279059/python-error-importing-scipy
https://github.com/scipy/scipy/issues/5893
As i am new in learning python,
Is this is the way to solve it? Do you think if its scipy compatibility issue ?  or if i am misunderstood any suggestions or help in solving this problem would be much appreciated.
Much thanks.

Regards,
Ahmad.

**Comment by mahmad321git** [comment]
Hi @mwaskom there was a directory issue relating to this scipy import, there was two scipy directory's bein installed in my computer. I finally was able to resolve it after deleting the ambiguous scipy directory. thanks
