### ISSUE TITLE
Question/Request: Colorbar option for facet grids

### ISSUE THREAD

**Issue by drewejohnson** [mwaskom/seaborn#1545]
This is kind of a re-hash of #582, but I'm curious if there is any intention or support for adding colorbars to `FacetGrid`-based plots. I've used the workaround posted on [StackOverflow](https://stackoverflow.com/a/44642014) with a lot of success, and would be really interested in including this feature directly in the API. 

I've got a decent high-level function that follows from the linked SO post, but mimics some of the behavior of `lmplot`. I could put together a PR if this is something that could benefit the project.

Thanks!

**Comment by mwaskom** [comment]
I don't think it makes sense to change things to support colorbars directly because the hue dimension of the `FacetGrid` is categorical.
