### ISSUE TITLE
Japanese characters not displayed

### ISSUE THREAD

**Issue by tolandwehr** [mwaskom/seaborn#1548]
I'm analyzing a list with a bunch of Jap characters. When trying to plot them, seaborn fails to display them. 

Here the keycode:

```
sns.set_style("white",{"font.rounded-mgenplus-1c-medium":['Arial']})
sns.lmplot( x='竣工年月', y='平成27年まで詰めた堆砂容量_%m4', data=Heisei, fit_reg=False, hue='水系名', legend=False)
plt.yscale('log')
plt.legend(loc='lower right')
plt.show()`
```

As you can see, I tried to use #1009 , but seaborn prefers to ignore this. Nothing changes. Also used #1009 original version, but - again - nothing. Of course "rounded-mgenplus-1c-medium" is installed on the PC and of course it's in the right folder `C:\Users\alias\Anaconda3\envs\tensorflow\Lib\site-packages\matplotlib\mpl-data\fonts\ttf `
There's also a non-Tensorflow environment and, yepp, I put "rounded-mgenplus-1c-medium" also into this. 

I tried once more to use this Japanese [solution ](https://qiita.com/keisuke-nakata/items/2309764d21438645f6b9) by changing two lines of code in seaborn's rcmod.py. However, seaborn then just reports, that it couldn't find "rounded-mgenplus-1c-medium" in the font-folder of matplotlib.

Is there some enhancement to the Japanese solution or sth completely different?

**Comment by mwaskom** [comment]
Not having your dataset, I can't run your code or really help in any practical way. But I don't think you're setting the font right because "font.rounded-mgenplus-1c-medium" is not a valid field in a matplotlib rc dictionary. You may want to make a fully reproducible example and post on stackoverflow.

**Comment by tolandwehr** [comment]
You could've taken any excel list with some Jap characters. It would've been that easy to reproduce.
