### ISSUE TITLE
Wrapping timeseries chart

### ISSUE THREAD

**Issue by brylie** [mwaskom/seaborn#1556]
A Redditor posted a seemingly simple chart design, [asking how to produce the design](https://reddit.com/comments/9cifqe):

![chart design sketch](https://i.redd.it/25ajib1bbyj11.jpg)

Initial responses about how to produce the chart were in three main flavors:
- gantt
- stacked bar
- calendar heatmap

In practice, each of the above chart types present unique challenges for, and may be incapable of rendering, the desired output.

The data structure might be, in effect, an array of two-tuples where each tuple contains a start and end Datetime.

What are some ideas on how this chart could be created with Seaborn?

**Comment by mwaskom** [comment]
Github issues are for bug reports ... I'd suggest asking on StackOverflow.

**Comment by brylie** [comment]
This repository has [issue labels](https://github.com/mwaskom/seaborn/labels) for:

- bug
- feature
- question
- wishlist
- plots

So, the above *question* about *plots* that may be on someone's *wishlist* which might in-turn lead to a *feature* request does not seem to be out of place in the issue tracker.

**Comment by brylie** [comment]
This repository has [issue labels](https://github.com/mwaskom/seaborn/labels) for:

- feature
- question
- wishlist
- plots

So, the above *question* about *plots* that may be on someone's *wishlist* which might in-turn lead to a *feature* request does not seem to be out of place in this issue tracker.

**Comment by mwaskom** [comment]
Too bad.
