### ISSUE TITLE
Docs: Scatterplot Matrix example is not correct

### ISSUE THREAD

**Issue by Roald87** [mwaskom/seaborn#1559]
The [Scatterplot Matrix](https://seaborn.pydata.org/examples/scatterplot_matrix.html) example image is different if you run the code.

I get the following image when I run the example code:
![old](https://user-images.githubusercontent.com/20192767/45166092-879bb580-b1f6-11e8-843d-6fa290a214e4.png)

However, in order to (allmost) recreate the current example image the code should be:

```
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="ticks")

df = sns.load_dataset("iris")
sns.pairplot(
    df, 
    hue="species", 
    diag_kind='kde', 
    diag_kws=dict(shade=True),
    palette='colorblind',
    plot_kws=dict(linewidth=1)
)

plt.show()
```

which gives:
![new](https://user-images.githubusercontent.com/20192767/45166199-be71cb80-b1f6-11e8-9e2b-5a78da13e470.png)

Also some examples on [this](https://seaborn.pydata.org/generated/seaborn.pairplot.html?highlight=pairplot) page seem not to match with the code.

**Comment by mwaskom** [comment]
Your version of seaborn does not match the version that was used to create the docs.
