### ISSUE TITLE
Observation: swarmplot does not play well with matplotlib's AxesGrid

### ISSUE THREAD

**Issue by josesho** [mwaskom/seaborn#1564]
When 2 subplots are created, and a swarmplot plotted on one of them after setting the ylim, the result is as expected.

EDIT: I am using seaborn 0.9.0 and matplotlib 2.2.2.

```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Create dummy data.
np.random.seed(99999)
data_frame = pd.DataFrame({"Control": np.random.randint(0, 100, 30).tolist(),
                           "Test": np.random.randint(0, 100, 30).tolist()})

# Create plot.
sns.set(style='ticks')
f, ax = plt.subplots(2, figsize=(10, 10))
ax_swarm = ax[0]
ax_raw.set_ylim(-10, 110)
sns.swarmplot(data=data_frame, ax=ax_swarm, size=9)
```
![fig1](https://user-images.githubusercontent.com/12838917/45405094-18a9db00-b694-11e8-980c-02dbd4495485.png)

However, when `make_axes_locatable` from ` mpl_toolkits.axes_grid1` is used, the datapoints in the swarmplot become squished.

```python
from mpl_toolkits.axes_grid1 import make_axes_locatable

f, ax_swarm = plt.subplots(1, figsize=(10, 10))

divider = make_axes_locatable(ax_swarm)
ax_extra = divider.append_axes("bottom", size="100%", pad=0.5, sharex=ax_swarm)
ax_swarm.set_ylim(-10, 110)

sns.swarmplot(data=data_frame, ax=ax_swarm, size=9)
```
![fig2](https://user-images.githubusercontent.com/12838917/45405098-1cd5f880-b694-11e8-9d1d-41bd85cc3ea4.png)

Is there any reason for this? (I've rewritten my code to use `plt.subplots` to create the two axes rather than `make_axes_locatable`, but found this curious.)

**Comment by mwaskom** [comment]
http://seaborn.pydata.org/generated/seaborn.swarmplot.html

> Arranging the points properly requires an accurate transformation between data and point coordinates. This means that non-default axis limits must be set before drawing the plot.

**Comment by josesho** [comment]
Understand why you're closing it since I'm not making a PR, but I'm still unclear why the points arrangement goes off when 1) I've appended the axes and 2) set the ylims __before__ I call `sns.swarmplot()`. Am I missing anything?

**Comment by mwaskom** [comment]
I don't really know anything about the toolkit that you're using, but the basic idea is stated in the docs: if the mapping between data and point coordinates changes between drawing the swam plot and showing the figure, the scatter points might overlap or be too spread out.
