### ISSUE TITLE
import error no attribute '_get_configdir'

### ISSUE THREAD

**Issue by nchos88** [mwaskom/seaborn#1574]
Linux Ubuntu 16 
python 3.6

Code
```
import pandas as pd 
import numpy as np 
import seaborn as sns 
#from matplotlib import pyplot as plt 
#%matplotlib inline 
```
Error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-41-09e31073eb4a> in <module>()
      4 import pandas as pd
      5 import numpy as np
----> 6 import seaborn as sns
      7 #from matplotlib import pyplot as plt
      8 #%matplotlib inline

~/miniconda3/envs/gb/lib/python3.6/site-packages/seaborn/__init__.py in <module>()
      4 
      5 # Import seaborn objects
----> 6 from .rcmod import *
      7 from .utils import *
      8 from .palettes import *

~/miniconda3/envs/gb/lib/python3.6/site-packages/seaborn/rcmod.py in <module>()
      3 import functools
      4 import matplotlib as mpl
----> 5 from . import palettes, _orig_rc_params
      6 
      7 

~/miniconda3/envs/gb/lib/python3.6/site-packages/seaborn/palettes.py in <module>()
     10 from .external.six.moves import range
     11 
---> 12 from .utils import desaturate, set_hls_values, get_color_cycle
     13 from .colors import xkcd_rgb, crayons
     14 

~/miniconda3/envs/gb/lib/python3.6/site-packages/seaborn/utils.py in <module>()
      9 import matplotlib as mpl
     10 import matplotlib.colors as mplcol
---> 11 import matplotlib.pyplot as plt
     12 
     13 from .external.six.moves.urllib.request import urlopen, urlretrieve

~/miniconda3/envs/gb/lib/python3.6/site-packages/matplotlib/pyplot.py in <module>()
     30 import matplotlib
     31 import matplotlib.colorbar
---> 32 from matplotlib import style
     33 from matplotlib import _pylab_helpers, interactive
     34 from matplotlib.cbook import dedent, silent_list, is_numlike

~/miniconda3/envs/gb/lib/python3.6/site-packages/matplotlib/style/__init__.py in <module>()
      1 from __future__ import absolute_import
      2 
----> 3 from .core import use, context, available, library, reload_library

~/miniconda3/envs/gb/lib/python3.6/site-packages/matplotlib/style/core.py in <module>()
     29 BASE_LIBRARY_PATH = os.path.join(mpl.get_data_path(), 'stylelib')
     30 # Users may want multiple library paths, so store a list of paths.
---> 31 USER_LIBRARY_PATHS = [os.path.join(mpl._get_configdir(), 'stylelib')]
     32 STYLE_EXTENSION = 'mplstyle'
     33 STYLE_FILE_PATTERN = re.compile(r'([\S]+).%s$' % STYLE_EXTENSION)

AttributeError: module 'matplotlib' has no attribute '_get_configdir'

---------------------------------------------------------------------------
Installed Library 
pip list
Package             Version
------------------- ---------
absl-py             0.5.0
appdirs             1.4.3
asn1crypto          0.24.0
astor               0.7.1
attrs               18.2.0
Automat             0.7.0
backcall            0.1.0
bleach              2.1.4
certifi             2018.8.24
cffi                1.11.5
constantly          15.1.0
cryptography        2.3.1
cycler              0.10.0
decorator           4.3.0
entrypoints         0.2.3
gast                0.2.0
grpcio              1.15.0
h5py                2.8.0
html5lib            1.0.1
hyperlink           18.0.0
idna                2.7
incremental         17.5.0
ipykernel           4.9.0
ipython             6.5.0
ipython-genutils    0.2.0
jedi                0.12.1
Jinja2              2.10
jsonschema          2.6.0
jupyter-client      5.2.3
jupyter-core        4.4.0
jupyterlab          0.34.8
jupyterlab-launcher 0.13.1
kiwisolver          1.0.1
lightgbm            2.1.2
Markdown            3.0.1
MarkupSafe          1.0
matplotlib          3.0.0
mistune             0.8.3
mkl-fft             1.0.6
mkl-random          1.0.1
nb-conda            2.2.1
nb-conda-kernels    2.1.0
nbconvert           5.3.1
nbformat            4.4.0
notebook            5.6.0
numexpr             2.6.8
numpy               1.15.1
pandas              0.23.4
pandocfilters       1.4.2
parso               0.3.1
patsy               0.5.0
pexpect             4.6.0
pickleshare         0.7.4
pip                 18.0
prometheus-client   0.3.1
prompt-toolkit      1.0.15
protobuf            3.6.1
ptyprocess          0.6.0
pyasn1              0.4.4
pyasn1-modules      0.2.2
pycparser           2.18
Pygments            2.2.0
pyOpenSSL           18.0.0
pyparsing           2.2.1
python-dateutil     2.7.3
pytz                2018.5
pyzmq               17.1.2
scikit-learn        0.20.0
scipy               1.1.0
seaborn             0.9.0
Send2Trash          1.5.0
service-identity    17.0.0
setuptools          39.1.0
simplegeneric       0.8.1
six                 1.11.0
statsmodels         0.9.0
tables              3.4.4
tensorboard         1.10.0
tensorflow-gpu      1.10.1
termcolor           1.1.0
terminado           0.8.1
testpath            0.3.1
tornado             5.1
traitlets           4.3.2
Twisted             18.7.0
wcwidth             0.1.7
webencodings        0.5.1
Werkzeug            0.14.1
wheel               0.31.1
xgboost             0.72
zope.interface      4.5.0

**Comment by mwaskom** [comment]
This is a problem with your matplotlib installation, not seaborn.
