### ISSUE TITLE
Adding annotations option (attributes) to barplot and countplot

### ISSUE THREAD

**Issue by jeffysonar** [mwaskom/seaborn#1582]
I propose for adding annotations option (attributes) to barplot and countplot
Lets start with an example
`import pandas as pd`
`import matplotlib.pyplot as plt`
`import seaborn as sns`
`%matplotlib inline`

`df = sns.load_dataset('tips')`

**Plotting a simple barplot**

`splot = sns.barplot(data=df, x = 'sex', y = 'total_bill')`
![default](https://user-images.githubusercontent.com/29709627/46582116-bc9e6080-ca5f-11e8-866f-bf1cfdf59695.jpg)

**Annotating bars**
`plt.figure(figsize=(6, 8))`
`splot = sns.barplot(data=df, x = 'sex', y = 'total_bill', ci = None)`
`for p in splot.patches:`
        `splot.annotate(format(p.get_height(), '.2f'), (p.get_x() + p.get_width() / 2., p.get_height()),  ha = 'center', va = 'center', xytext = (0, 10), textcoords = 'offset points')`

![annotated](https://user-images.githubusercontent.com/29709627/46582143-37677b80-ca60-11e8-9b90-7085d9e41fd6.jpg)

This seems a simple addition. But, someone requiring to add some more highlights by annotating those bar would require to add some more lines of code.

Instead, adding a single attribute would reduce this efforts and make them more expressive !!!!!

**Comment by mwaskom** [comment]
I won’t be adding this, sorry.

**Comment by mwaskom** [comment]
I won’t be adding this, sorry.

**Comment by alberduris** [comment]
I would really like to see this or something like this added.

The annotation on barplots should be simple.

**Comment by ajithmadhav** [comment]
Thanks for the Post. Can you tell me how to annotate if I have a horizontal plot?

**Comment by rafaelscnunes** [comment]
Thanks for the post, very helpful!
