### ISSUE TITLE
catplot & relplot do not use provided ax: two frames appear

### ISSUE THREAD

**Issue by harmbuisman** [mwaskom/seaborn#1583]
catplot:
import seaborn as sns
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=[10,5])
titanic = sns.load_dataset("titanic")
sns.catplot(ax=ax, x="sex", y="survived", hue="class", kind="bar", data=titanic);

<img width="430" alt="seaborn" src="https://user-images.githubusercontent.com/7702207/46608855-620c0f80-cb06-11e8-83c9-72519160c2bc.PNG">

relplot:
fig, ax = plt.subplots(figsize=[10,5])
titanic = sns.load_dataset("titanic")
sns.relplot(ax=ax, x="sex", y="survived", hue="class", data=titanic);
plt.title("This plot is active")

<img width="338" alt="relplot" src="https://user-images.githubusercontent.com/7702207/46609034-e2327500-cb06-11e8-9434-fb410535afb3.PNG">

barplot *does* work as expected:
fig, ax = plt.subplots(figsize=[10,5])
titanic = sns.load_dataset("titanic")
sns.barplot(ax=ax, x="sex", y="survived", hue="class", data=titanic);
plt.title("This plot is active")

<img width="331" alt="barplot" src="https://user-images.githubusercontent.com/7702207/46609041-efe7fa80-cb06-11e8-8447-ba4f27269bb8.PNG">

I am expecting both catplot and relplot to also show exactly one frame instead of two

**Comment by mwaskom** [comment]
http://seaborn.pydata.org/introduction.html#figure-level-and-axes-level-functions

**Comment by Sakib-Ar-Rahman** [comment]
I am just going to add this here referenced from https://github.com/mwaskom/seaborn/issues/1514 in case someone like me stumbles upon this issue when using `catplot` with `subplots`.

> plt.close(2) helps to hide the 2nd empty graph

**Comment by sergiomora03** [comment]
Hi there! 

I'm trying to pass a subplot with a figure-level function from seaborn as a `catplot()` but I can't do it works... And finally, I get this UserWarning: `catplot is a figure-level function and does not accept target axes.` I know that I could use a `barplot()` instead, but what about Facetgrid plots made easy with figure-level function? could you help me? This still working in the near future? Hear me, the subplots needs working with figure-level function in the future... 

Regards! :zap:
