### ISSUE TITLE
violin plot with coloured quartile range.

### ISSUE THREAD

**Issue by hendrikwout** [mwaskom/seaborn#1592]
Dear developer,

Coloring the quartile range in violinplots is becoming more common in scientific publications. But I can't find a way to do this with seaborn. I can only mark the quartiles with dashed lines. 

Any ideas how to make the interquartile range more dark? Here is an sketch of what I'm aining for: 
![image](https://user-images.githubusercontent.com/5902239/47135610-4268aa00-d2b1-11e8-920e-55c6be6416cc.png)

Thanks!
Cheers,
Hendrik

**Comment by mwaskom** [comment]
It’s not an option in seaborn, sorry.
