### ISSUE TITLE
TypeError: 'numpy.int64' object is not iterable

### ISSUE THREAD

**Issue by ralsallaq** [mwaskom/seaborn#1593]
seaborn version 0.9.0
pandas version 0.23.4
numpy version 1.15.2
matplotlib version 2.2.2

import pandas as pd
import numpy as np
from matplotlib import pylab as pl
import seaborn as sbs

df=pd.DataFrame({'col1':np.random.rand(10),'col2':np.random.randint(0,3,10),'col3':np.random.randn(10)})
g=sbs.PairGrid(df, hue='col2')
g.map_diag(pl.hist) #this throws the following TypeError

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-bb061d39bdce> in <module>
----> 1 g.map_diag(pl.hist)

~/anaconda3/lib/python3.6/site-packages/seaborn/axisgrid.py in map_diag(self, func, **kwargs)
   1397                     color = fixed_color
   1398
-> 1399                 func(data_k, label=label_k, color=color, **kwargs)
   1400
   1401             self._clean_axis(ax)

~/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py in hist(x, bins, range, density, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, normed, hold, data, **kwargs)
   3130                       histtype=histtype, align=align, orientation=orientation,
   3131                       rwidth=rwidth, log=log, color=color, label=label,
-> 3132                       stacked=stacked, normed=normed, data=data, **kwargs)
   3133     finally:
   3134         ax._hold = washold

~/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1853                         "the Matplotlib list!)" % (label_namer, func.__name__),
   1854                         RuntimeWarning, stacklevel=2)
-> 1855             return func(ax, *args, **kwargs)
   1856
   1857         inner.__doc__ = _add_data_doc(inner.__doc__,

~/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py in hist(***failed resolving arguments***)
   6711             labels = [label]
   6712         else:
-> 6713             labels = [six.text_type(lab) for lab in label]
   6714
   6715         for patch, lbl in zip_longest(patches, labels, fillvalue=None):

TypeError: 'numpy.int64' object is not iterable

any idea why is it doing so?
Thanks

**Comment by mwaskom** [comment]
Seems like a problem in matplotlib where `plt.hist` can't use a numeric type for the "label" even though other functions can


```python
plt.hist([0, 1], label=0)  # errors
plt.plot([0, 1], label=0)  # works fine
```

**Comment by mwaskom** [comment]
didn't mean to close, although i do think this is a matplotlib issue (might be fixed already, 2.2 is not the latest version)

**Comment by ralsallaq** [comment]
Many thanks for the quick reply. I tried it with 

seaborn version 0.8.1
pandas version 0.23.4
numpy version 1.15.2
matplotlib version 2.2.3

and it works just fine. The strange of the matter that it does not work if I upgrade seaborn to 0.9.0 even if I upgrade matplotlib to 3.0.0

**Comment by ralsallaq** [comment]
Interesting. I never had this problem with matplotlib because I usually set labels as strings never had to use numeric labels, let alone multiple numeric labels. Good to know, thanks.

**Comment by mwaskom** [comment]
Going to close because it's really something that should be handled at the matplotlib layer. I've reported upstream.

**Comment by Ayuu713** [comment]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-114-097b5dcf11a3> in <module>
      6     for element in unique_elements:
      7         # Adding all the translations to a dictionary (translations)
----> 8         translations[element] = translator.translate(element).text
      9 translations

~\Anaconda31\lib\site-packages\googletrans\client.py in translate(self, text, dest, src)
    170 
    171         origin = text
--> 172         data = self._translate(text, dest, src)
    173 
    174         # this code will be updated when the format is changed.

~\Anaconda31\lib\site-packages\googletrans\client.py in _translate(self, text, dest, src)
     73             text = text.decode('utf-8')
     74 
---> 75         token = self.token_acquirer.do(text)
     76         params = utils.build_params(query=text, src=src, dest=dest,
     77                                     token=token)

~\Anaconda31\lib\site-packages\googletrans\gtoken.py in do(self, text)
    199     def do(self, text):
    200         self._update()
--> 201         tk = self.acquire(text)
    202         return tk

~\Anaconda31\lib\site-packages\googletrans\gtoken.py in acquire(self, text)
    144         a = []
    145         # Convert text to ints
--> 146         for i in text:
    147             val = ord(i)
    148             if val < 0x10000:

TypeError: 'numpy.int64' object is not iterable














any one have solution for this
