### ISSUE TITLE
MatplotlibDeprecationWarning triggered on import

### ISSUE THREAD

**Issue by mchwalisz** [mwaskom/seaborn#1594]
Seaborn triggers following `MatplotlibDeprecationWarning examples.directory is deprecated` on import.
From what I understand seaborn touches this configuration with matplotlib `rcParams`, which now triggers a warning.

I don't see any other side-effects yet, it is for not just annoying to see.

Installed versions:
- seaborn [required: Any, installed: 0.9.0]
- matplotlib [required: >=1.4.3, installed: 3.0.0]

Steps to reproduce:
```python   
python
Python 3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import seaborn
/home/me/.local/share/virtualenvs/QbuZIpeN/lib/python3.7/site-packages/matplotlib/__init__.py:886: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))
>>> 
```

**Comment by mwaskom** [comment]
seaborn doesn't do anything with the matplotlib examples so I don't understand why you're seeing that warning. seems like a false alarm on the matplotlib side of things.

**Comment by mchwalisz** [comment]
Quick search https://github.com/mwaskom/seaborn/blob/3eb463a2cd32db196b6e71d1f72d64057804ed76/seaborn/__init__.py#L3 shows that seaborn is copying all the config params. I think it might create a false feedback.

**Comment by mwaskom** [comment]
what's a false feedback? that's just creating a copy of a dictionary I don't see why it should trigger a warning in another package.

**Comment by mchwalisz** [comment]
Sorry for not being clear enough. `seaborn` copies the whole dictionary of `rcParams. Testing it shows that it indeed triggers the `MatplotlibDeprecationWarning` I'm talking about:
```python
Python 3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib as mpl
>>> _orig_rc_params = mpl.rcParams.copy()
/home/chwalisz/.local/share/virtualenvs/ns3-tsch-wifi-QbuZIpeN/lib/python3.7/site-packages/matplotlib/__init__.py:886: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))
```

The only reference to `_orig_rc_params` I found is in 
https://github.com/mwaskom/seaborn/blob/c0a6d850d29b7b8c0e3ecc8a14c76f11880fb9f9/seaborn/rcmod.py#L131

which in turn is **only** used in https://github.com/mwaskom/seaborn/blob/3a3ec75befab52c02650c62772a90f8c23046038/seaborn/apionly.py#L3

which according to documentation is *deprecated* anyway.

I expect the `rcParams.copy()` to be done so early in `__init__.py` is done to store default (or maybe current) settings. Which is imo error prone as somebody can change `rcParams` even before `seaborn` is imported. Also there is already function to reset to default params (`rcmod.reset_defaults`).

**Comment by mwaskom** [comment]
Why would that be "error prone"? The case you mention is exactly the point. matplotlib knows about its own defaults; seaborn tracks what users might have changed before importing seaborn, so that they can get back to that state. It's distinct from resetting to the defaults, which is why there are two functions...

**Comment by MarvinT** [comment]
just for reference, the open matplotlib issue for this is https://github.com/matplotlib/matplotlib/issues/13118
