### ISSUE TITLE
Rotating xticklabels failure in FacetGrid (Seaborn 0.9.0)

### ISSUE THREAD

**Issue by michaelsilverstein** [mwaskom/seaborn#1598]
With previous version of Seaborn, I have been able to use `g.set_xtickslabels(rotation=90)` to rotate the shared x-axis of a FacetGrid; however, now passing the `rotation` argument alone removes the xticklabels. 

The only way I was able to get the function to work properly was to also pass a list of labels: `g.set_xticklabels(labels, rotation=90)`, which is prone to errors. 

I can't tell the source for this behavior, the code suggests that the labels should be grabbed from the axes:
https://github.com/mwaskom/seaborn/blob/f0349b1a7f1e022cb1da8b94f2e019f04eeed397/seaborn/axisgrid.py#L894

**Comment by mwaskom** [comment]
Reproducible example?

**Comment by michaelsilverstein** [comment]
Generate some data
```
n = 5
animals = ['cat','dog','horse']
genders = ['male', 'female']
states = ['MA', 'NY']

df = pd.DataFrame([[a, g, s, np.random.randint(0, 10)] for _ in range(n) for a in animals for g in genders for s in states], columns=['animal', 'gender', 'state','n_friends'])
```

Plot FacetGrid and try to rotate
```
g = sns.FacetGrid(df, 'state')
order = sorted(df.animal.unique())
g.map(sns.barplot, 'animal', 'n_friends', 'gender', palette='Paired', order=order, hue_order=df.gender.unique())
g.set_xticklabels(rotation=90)
plt.show()
```
![image](https://user-images.githubusercontent.com/22639569/47670712-3ff53280-db84-11e8-9bca-79516929f355.png)

Plot FacetGrid with labels provided
```
g = sns.FacetGrid(df, 'state')
order = sorted(df.animal.unique())
g.map(sns.barplot, 'animal', 'n_friends', 'gender', palette='Paired', order=order, hue_order=df.gender.unique())
g.set_xticklabels(order, rotation=90)
plt.show()
```
![image](https://user-images.githubusercontent.com/22639569/47670743-57ccb680-db84-11e8-8c8e-180ca3643929.png)

**Comment by mwaskom** [comment]
The relevant change between v0.8 and v0.9 is likely https://github.com/mwaskom/seaborn/pull/1313

**Comment by michaelsilverstein** [comment]
Maybe the suggested solution should be `plt.xticks(rotation=90)` since that will act on the current axes and doesn't requires passing the list of labels.
```
g = sns.FacetGrid(df, 'state')
order = sorted(df.animal.unique())
g.map(sns.barplot, 'animal', 'n_friends', 'gender', palette='Paired', order=order, hue_order=df.gender.unique())
plt.xticks(rotation=90)
plt.show()
```
![image](https://user-images.githubusercontent.com/22639569/47678283-c49d7c00-db97-11e8-877f-5eb73373b515.png)
