### ISSUE TITLE
Color problem with vector-graphics heatmaps

### ISSUE THREAD

**Issue by Hoeze** [mwaskom/seaborn#1600]
I tried generating a heatmap like this:
```python
set_matplotlib_formats('svg')
ax = sns.heatmap(rounded, cmap="RdBu")
```
However, the resulting figure looks like this:
![grafik](https://user-images.githubusercontent.com/1200058/48008585-46525400-e11a-11e8-9808-37d07bd22134.png)
Instead of this:
![grafik](https://user-images.githubusercontent.com/1200058/48008687-713ca800-e11a-11e8-9cfc-35471bd55d47.png)

The problem with vector graphics can be seen by opening the svg with inkscape:
![grafik](https://user-images.githubusercontent.com/1200058/48009043-28d1ba00-e11b-11e8-8ab6-30773f82d28d.png)

Although some areas should be fully black, there seem to be some white frames around the heatmap rectangles which make the figure look grey instead of black. 

Is there any way to solve this problem?

**Comment by Hoeze** [comment]
Maybe it would be advantageous to use single pixels instead of boxes?
This way a browser also had no bad time when having to display a huge number of boxes.

**Comment by Hoeze** [comment]
Inside tensorflow+tensorboard I'm using a pixel-accurate transformation of this image:
![grafik](https://user-images.githubusercontent.com/1200058/48009459-10ae6a80-e11c-11e8-9fdf-774fd16f2446.png)

**Comment by mwaskom** [comment]
If there’s a problem with the svg writer it would need to be solved in matplotlib but generally for vector graphics heatmaps you’ll want to enable rasterization.

**Comment by Hoeze** [comment]
@mwaskom Thank you very much, I did not know that option.
However, rasterization removes a lot of information from my plot. Is there a possibility to enable **exact rasterization**?
![grafik](https://user-images.githubusercontent.com/1200058/48014305-a9e27e80-e126-11e8-8d52-c5c308d23f32.png)
