### ISSUE TITLE
Lineplot docstring contains mislabeled parameter "err_band"

### ISSUE THREAD

**Issue by mtd91429** [mwaskom/seaborn#1603]
The documentation for the lineplot contains a mislabeled parameter: `err_band`

Given the parameter description, I believe that it should be `err_kws` 

Docstring within Jupyter Notebook:
![image](https://user-images.githubusercontent.com/3360192/48215918-5bfd8e80-e351-11e8-8851-d691af7ee47e.png)

From the Seaborn website:
![image](https://user-images.githubusercontent.com/3360192/48215362-18eeeb80-e350-11e8-9983-d61083ed74c9.png)

**Comment by mtd91429** [comment]
Generated a pull request to fix this small typo

#1604

**Comment by crazyoscarchang** [comment]
The error is also in the docs.

https://seaborn.pydata.org/generated/seaborn.lineplot.html?highlight=lineplot#seaborn.lineplot

**Comment by jakesherman** [comment]
I just noticed this issue today. Using `err_kws` instead of `err_band` fixed it for me.

**Comment by mwaskom** [comment]
Thanks, fixed in #1713
