### ISSUE TITLE
heatmap breaks for larger datasets

### ISSUE THREAD

**Issue by idc9** [mwaskom/seaborn#1605]
`sns.heatmap` breaks for matrices larger than about 60,000 rows.

```python

import seaborn as sns
import numpy as np
%matplotlib inline

# this works fine
X = np.random.normal(size=(50000, 256))
sns.heatmap(X)
```
![screenshot 2018-11-08 16 49 35](https://user-images.githubusercontent.com/906398/48229536-61b99b00-e376-11e8-85bb-ba8eb74727a7.png)

```python
# this breaks for 60000 rows
X = np.random.normal(size=(60000, 256))
sns.heatmap(X)
```
![screenshot 2018-11-08 16 49 47](https://user-images.githubusercontent.com/906398/48229553-68e0a900-e376-11e8-9ebf-5d2bec31bdd0.png)

I am using python 3.6, seaborn 0.9.0, matplotlib 2.1.0  on a mac and in a jupyter notebook.

**Comment by mwaskom** [comment]
This is dependent on parameters used to make the image, e.g. on my system

```python
f, ax = plt.subplots()
X = np.random.normal(size=(60000, 256))
sns.heatmap(X, ax=ax)
f.savefig("test.png")
f.savefig("test_hidpi.png", dpi=200)
```

`test.png` has the issue but `test_hidpi.png` does not. This suggests it is a problem downstream of seaborn.

But consider what you are doing ... there's no real way you can represent 60K rows of data in an image anything close to what you could display on a computer screen or print. So it might not be surprising that things break down in this regime.
