### ISSUE TITLE
AttributeError: module 'seaborn' has no attribute 'relplot'

### ISSUE THREAD

**Issue by ahua92** [mwaskom/seaborn#1608]
Using Jupyter 4.4.1 running on Python 3.5.2

```
AttributeError                            Traceback (most recent call last)
<ipython-input-4-5086873db64c> in <module>()
----> 1 rawx = sns.relplot(x="Timestamp",y="X0",kind="line",data=raw)

AttributeError: module 'seaborn' has no attribute 'relplot'
```

I've updated seaborn to 0.9.0 in both conda and pip.

```
(base) conda update seaborn
Solving environment: done

# All requested packages already installed.
```

**Comment by mwaskom** [comment]
Likely there is a mismatch between what libraries your IPython sees and what versions your conda/pip see. This is an idiosyncratic installation problem and will depend on the details of your setup, so I am afraid I won't be able to give much help.

**Comment by ahua92** [comment]
Uninstalled Python and Anaconda, reinstalled Python 3.7.1 and Anaconda 3, everything is working now.
