### ISSUE TITLE
despine is not removing tickmarks on top and right axis

### ISSUE THREAD

**Issue by maartenmennes** [mwaskom/seaborn#1612]
I've found that despine stopped removing the tickmarks on top and right axis, as per the image below

![image](https://user-images.githubusercontent.com/1139180/48493824-f287ef00-e82c-11e8-8863-70ec92cf9f3e.png)

explicitly setting the tick position to 'left' and 'bottom' fixes that:

![image](https://user-images.githubusercontent.com/1139180/48494098-6b874680-e82d-11e8-8ead-2691edae5f6d.png)

**Comment by mwaskom** [comment]
What would be most useful are the relevant library versions and a self-contained, copy-pastable example demonstrating the issue.

**Comment by maartenmennes** [comment]
Hi Michael,
here you go:

seaborn version 0.9.0
matplotlib version 1.5.1
python 2.7

import seaborn as sns
%matplotlib inline
a = range(0,10)
sns.stripplot(a)
sns.despine()

![image](https://user-images.githubusercontent.com/1139180/48609668-32151f00-e984-11e8-84e9-433ffc63e5be.png)

**Comment by mwaskom** [comment]
seaborn 0.9 takes advantage of the matplotlib 2.0 [improvements for aesthetic control](https://seaborn.pydata.org/whatsnew.html#updates-to-themes-and-palettes), and I think one consequence of that is that the old way of hiding the ticks is no longer supported. I'd suggest upgrading matplotlib or downgrading seaborn, or failing that, hiding the ticks yourself.
