### ISSUE TITLE
Lineplot equivalent of tsplot(err_style="unit_traces") 

### ISSUE THREAD

**Issue by NDolensek** [mwaskom/seaborn#1613]
With tsplot() being deprecated, is it possible to have the new lineplot() behave like tsplot(err_style="unit_traces") - with a stronger mean line and faint lines for each of the samples?

example:
![image](https://user-images.githubusercontent.com/6035683/48520778-289b9200-e872-11e8-89d0-a13459855035.png)

**Comment by mwaskom** [comment]
Yes, but you’d need to call it twice.
