### ISSUE TITLE
Getting Started - Instructions (installing.rst)

### ISSUE THREAD

**Issue by datahaus** [mwaskom/seaborn#1614]
The "Installing and getting started" page needs info about how to get started.
https://seaborn.pydata.org/installing.html

After running "pip install seaborn" I saw that Seaborn was already installed with Anaconda.

I opened a terminal at the reported existing location:
/anaconda3/lib/python2.7/site-packages/seaborn

I assume this is the "root directory of the source distribution."  (If Anaconda's files are not the source distribution mentioned, please clarify in the instructions.)

I ran "make test" as instructed, and received the message:
> make: *** No rule to make target `test'.  Stop.

I also ran "make test" within the Anaconda's Jupyter Notebook terminal. Same message.

Please add more details to the Getting Started instructions.
Let's make this easy enough for a 5th grader to use.

**Comment by mwaskom** [comment]
Sorry, but I don’t have the bandwidth to teach fifth graders how to start using software.

**Comment by datahaus** [comment]
Your Getting Started page flow would benefit from a [Continue to Tutorials](https://seaborn.pydata.org/tutorial.html) page at the bottom.
For other newcomers, I'd recommend this [getting started](https://elitedatascience.com/python-seaborn-tutorial) page. Micheal knows his market, and they aren't interested in making their work look too easy. But the writing is on the wall, kids will one day rule. And by then, we'll probably smash the hands of those trying to ascend the ladder behind us too. Have a nice day, asshole.
