### ISSUE TITLE
stripplot:  IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by freekvh** [mwaskom/seaborn#1616]
Hi,

Ik am able make a boxplot using:

    sns.boxplot(data=metabric_data, x='group', y='activity', hue='histological_type', dodge=True, linewidth=0.5)

However, a stripplot fails (it did not in previous seaborn/mpl versions:

    sns.stripplot(data=metabric_data, x='group', y='activity', hue='histological_type', dodge=True, linewidth=0.5)
    ...
    IndexError: index 0 is out of bounds for axis 0 with size 0

The stripplot does not fail without the "dodge=True" argument. It could be that one of the categories is empty however I am sure that it worked before.

**Comment by mwaskom** [comment]
I can't help without a reproducible example, sorry.

**Comment by freekvh** [comment]
Ok, the data is somewhat sensitive, I shall try to make a small pd.DataFrame that behaves the same...

**Comment by hi-im-ryanli** [comment]
Had the exact same issue - am able to plot `boxplot`, but `stripplot` fails with the same error. 

Sadly I can't share the data as well, but I solved it by removing `nan` in the `hue` column.
```
self.df.dropna(axis=0, subset=[...], how="any", inplace=True)
```

So go ahead and inspect your `hue`, maybe there is some weirdness going on in there.

**Comment by bretttully** [comment]
This might be useful: https://stackoverflow.com/questions/53385592/seaborn-issue-with-catplot -- if one of your hue categories are empty then you'll hit this.

**Comment by normanius** [comment]
I can confirm: @bretttully is correct. Upgrading to matplotlib 3.0.3 (version currently available on pip) fixed the problem for me.

**Comment by mwaskom** [comment]
OK thanks @normanius, I will close as this sounds like a (resolved) matplotlib bug
