### ISSUE TITLE
Issue with heatmaps, mask and colorbar

### ISSUE THREAD

**Issue by lucianolorenti** [mwaskom/seaborn#1617]
Hello. I'm sorry to bother you with this question but 
Is the current behaviour of the heatmap's colorbar expected when a mask is used ?
I mean `vmin` and `vmax`  computed without considering the mask.
```
import numpy as np
import seaborn as sbs
import matplotlib.pyplot as plt
data = np.random.rand(3, 3)
mask = np.full((3,3), False)
mask[0,0] = True
data[0,0] = 10000
sbs.heatmap(data, cbar=True, mask=mask)
plt.show()
```

![figure_1](https://user-images.githubusercontent.com/106397/49086690-e8ee8600-f233-11e8-91d3-1a6df4b54849.png)

**Comment by mwaskom** [comment]
I don’t believe the mask is intended to be used for computing the colormap limits. If your data gave outliers, you could try `robust`
