### ISSUE TITLE
distplot's rug is 1 tick below Y=0 after plot updates

### ISSUE THREAD

**Issue by vanweric** [mwaskom/seaborn#1620]
I'm creating a distplot with a rug, but no kde.  Immediately after the call to distplot, the chart looks correct.  However, anything that draws to those axes causes the rug to drop by one tick below Y=0:

![image](https://user-images.githubusercontent.com/1154288/49308789-1fbfd880-f48e-11e8-93e2-b5890af8a079.png)

It is difficult to reproduce because it is strongly dependent on data and bins.  Small changes toggle the issue on and off.
Here is the smallest code I could get to reproduce the issue:
```
data = np.arange(-.62, -.34, .01)
num_bins = 13
upper = 1.5
lower = -1.5
width = (upper-lower) / num_bins
bins = np.arange(lower, upper, width)

sns.distplot(data, rug=True, kde=False, bins=bins)
plt.plot((0,0),(10,20))
```

I poked at the parameters to see what impacted it.  The following changes to the above code make the issue NOT reproduce:

- Changing num_bins unpredictably "toggles" the issue
- Setting kde=True always fixes it
- Letting distplot choose its own bins always fixes it
- Loose datapoint spacing seems to be better.

I'm using seaborn version 0.9.0, Spyder 3.0.0, Python 2.7.12, and Anaconda 4.2.0

This started by trying to add Pass/Fail coloring to a histogram.  I want to be able to color bins according to whether they pass a criteria, and also force the bins to have edges coincident with these criteria.  The solution I found was separate distplots and manually handle the bins.

Thank You!

**Comment by mwaskom** [comment]
This isn't surprising to me because the rugplot is drawn in axes coordinates: https://github.com/mwaskom/seaborn/blob/master/seaborn/distributions.py#L734.

If you do `ax.set_ylim((0, None), auto=False)` it will clamp the bottom of the plot to 0 while still adapting the top limit for whatever else you put on the plot.

**Comment by vanweric** [comment]
That works, thanks!
