### ISSUE TITLE
ValueError: Filled and line art markers cannot be mixed

### ISSUE THREAD

**Issue by grofte** [mwaskom/seaborn#1624]
Error message  
`ValueError: Filled and line art markers cannot be mixed`   
fails to report which markers are filled and which are unfilled. The markers are not listed on the Seaborn website. They can only be found on the Matplotlib website: https://matplotlib.org/api/markers_api.html where only some of them are listed as filled.  
The error message itself is rather cryptic.   
Solution suggestion: print the filled and unfilled marker characters in two strings along with the error message.

**Comment by mwaskom** [comment]
seaborn is a wrapper for matplotlib. i think the docs are abundantly clear about this. filled vs unfilled markers is one of the very many cases where the answer can be found in the matplotlib docs, not the seaborn docs, for good reason.

**Comment by RobRomijnders** [comment]
See also [this issue](https://github.com/mwaskom/seaborn/issues/1599)

In November 2020, I found these markers to work in scatter plot
`(',', '.', 'o', 'v', '^', '<', '>', '8', 's', 'p', '*', 'h', 'H', 'D', 'd', 'P', 'X')`
