### ISSUE TITLE
Incorrect distplot with norm_hist=True

### ISSUE THREAD

**Issue by mindspawn** [mwaskom/seaborn#1625]
distplot() is returning bars with magnitude > 1. Showing the same data set with seaborn and 
numpy's hist (shows expected distribution and bar magnitudes).

![image](https://user-images.githubusercontent.com/5296802/49758307-78a02580-fc73-11e8-8c1d-41086b033aeb.png)

Attached csv data file to repeat the bug.
[bug.zip](https://github.com/mwaskom/seaborn/files/2664759/bug.zip)

Seaborn 0.9.0
Matplotlib 2.2.3 with backend module://ipykernel.pylab.backend_inline

**Comment by mwaskom** [comment]
norm_hist shows a density, not a pmf
