### ISSUE TITLE
Seaborn not importing after conda update --all

### ISSUE THREAD

**Issue by jmischun** [mwaskom/seaborn#1626]
I ran `conda update --all` over the weekend, and now I receive the following error when I run `import seaborn as sns`:

In [1]: import seaborn
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6f477838ac7f> in <module>
----> 1 import seaborn

~/anaconda3/lib/python3.6/site-packages/seaborn/__init__.py in <module>
      4
      5 # Import seaborn objects
----> 6 from .rcmod import *
      7 from .utils import *
      8 from .palettes import *

~/anaconda3/lib/python3.6/site-packages/seaborn/rcmod.py in <module>
      3 import functools
      4 import matplotlib as mpl
----> 5 from . import palettes, _orig_rc_params
      6
      7

~/anaconda3/lib/python3.6/site-packages/seaborn/palettes.py in <module>
     10 from .external.six.moves import range
     11
---> 12 from .utils import desaturate, set_hls_values, get_color_cycle
     13 from .colors import xkcd_rgb, crayons
     14

~/anaconda3/lib/python3.6/site-packages/seaborn/utils.py in <module>
      5
      6 import numpy as np
----> 7 from scipy import stats
      8 import pandas as pd
      9 import matplotlib as mpl

~/anaconda3/lib/python3.6/site-packages/scipy/stats/__init__.py in <module>
    343 from __future__ import division, print_function, absolute_import
    344
--> 345 from .stats import *
    346 from .distributions import *
    347 from .morestats import *

~/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py in <module>
    167 from scipy._lib.six import callable, string_types
    168 from scipy._lib._version import NumpyVersion
--> 169 import scipy.special as special
    170 import scipy.linalg as linalg
    171 from . import distributions

~/anaconda3/lib/python3.6/site-packages/scipy/special/__init__.py in <module>
    638 from .sf_error import SpecialFunctionWarning, SpecialFunctionError
    639
--> 640 from ._ufuncs import *
    641
    642 from .basic import *

ImportError: dlopen(/Users/jmischun/anaconda3/lib/python3.6/site-packages/scipy/special/_ufuncs.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /Users/jmischun/anaconda3/lib/python3.6/site-packages/scipy/special/_ufuncs.cpython-36m-darwin.so
  Reason: image not found

**Comment by mwaskom** [comment]
Based on the traceback, you can't import scipy. Looks like something went wrong with linked libraries. Unfortunately this doesn't have much to do with seaborn beyond seaborn importing scipy, so I'm afraid I can't offer any help.

**Comment by cj-tww** [comment]
Has this issue been reported to SciPy then?
Have the exact same error.

**Comment by jmischun** [comment]
I didn't report to SciPy because I was experiencing problems with several packages. I had recently updated Xcode and that appeared to be creating the issues. I backed up my system, then removed and reinstalled Anaconda. That resolved all of my issues. I'm extremely new to programming, so I recognize that's a fairly blunt resolution, but it didn't take long and it did work. I hope that helps.
