### ISSUE TITLE
Boxenplot warnings in the example

### ISSUE THREAD

**Issue by hardianlawi** [mwaskom/seaborn#1629]
```
>>> iris = sns.load_dataset("iris")
>>> ax = sns.boxenplot(data=iris, orient="h", palette="Set2")
```

When running the example above, I got the warning message below:

```
'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.
'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.
'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.
'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.
```

It does not return any exception, but I found it irritating as it appears everytime I run the code. I would like to suppress all warning messages as sometimes it could be important, but I do not really understand for this particular.

**Comment by bh-figure** [comment]
Running into the same issue, can't seem to avoid or suppress this warning. I've tried passing colors manually but it still displays the same text every time the plot is run.

**Comment by claresloggett** [comment]
I'm seeing this issue too. It makes boxenplots very hard to use in Jupyter. Currently I don't know a better workaround than suppressing all warnings for that notebook cell.

I'm guessing it might be related to changes in Matplotlib. I can see a similar (now fixed) issue referenced in JuliaPlots: https://github.com/JuliaPlots/Plots.jl/issues/1799

**Comment by jonathan-hourany** [comment]
Same problem here. I wonder if this is related to #1682 somehow. 

My Matplotlib version is 3.0.0

**Comment by Thomsch** [comment]
I'm also experiencing this issue with latest versions of matplotlib and seaborn.

**Comment by rene-rex** [comment]
As a workaround you can reduce the level of the axis logger to error:
```python
from matplotlib.axes._axes import _log as matplotlib_axes_logger
matplotlib_axes_logger.setLevel('ERROR')
```

**Comment by Thomsch** [comment]
Thank you!

**Comment by agent-007-A** [comment]
Thank you rene-rex

**Comment by Benfeitas** [comment]
For those manually setting the colors, it seems [that encasing the color in [brackets]](https://stackoverflow.com/a/52879804/1379826) solves this problem.
