### ISSUE TITLE
bivariate kdeplot useless for scientific presentation

### ISSUE THREAD

**Issue by Jreyno40** [mwaskom/seaborn#1630]
Issue #312 was closed down, but I just wanted to reiterate that this is a problem. Without the contour regions being presented alongside probabilities for their densities, this sort of plot cannot be used as part of official results. I think this is worth exploring.

**Comment by MaozGelbart** [comment]
Hi @Jreyno40 , issue #312 has been resolved in [seaborn 0.8.0](https://seaborn.pydata.org/whatsnew.html#v0-8-0-july-2017) with ``cbar`` keywords (through #1161 ). Is that what you're looking for?
