### ISSUE TITLE
Cannot change color in countplot 

### ISSUE THREAD

**Issue by deniseduma** [mwaskom/seaborn#1631]
I'm trying to simply change the color of the bars in a countplot from grey to something else, but nothing happens, the bars are always grey! Any idea what is going on? Here are the commands:

plt.figure()
ax = sns.countplot(mydata, color="blue", saturation=1)
plt.savefig('myplot.png', dpi=300, format='png', bbox_inches='tight')

Thanks.
Denise

**Comment by mwaskom** [comment]
I cannot reproduce:

```python
tips = sns.load_dataset("tips")
sns.countplot(tips["day"], color="blue", saturation=1)
```
![image](https://user-images.githubusercontent.com/315810/50125819-77a16200-0238-11e9-91e9-d77bed76d5c2.png)

I am going to close but can reopen if you provide a reproducible example that demonstrates a problem in seaborn.

**Comment by deniseduma** [comment]
Hi,

I'm sorry, I forgot to mention, the data I'm trying to plot has ~2800 unique categories (the whole vector has length ~1M) and it turns out countplot works ok if I try to plot only a few entries from my vector, but when I input the whole vector, it just won't change the color from barely visible light grey to anything else! So it seems countplot has a scale issue.

Denise
