### ISSUE TITLE
lineplot is ignoring some ordering parameters

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#1632]
Minimal example of the original issue, which may not be replicable:

```
sns.lineplot(x=[0, 1, 0, 1], y=[0, 1, 0, 2],  style=["a", "a", "b", "b"],
             style_order=["b", "a"], dashes=[(4, 1), (1, 1)])
```

(Legend is correct, however)

---

New issue, showing failure to respect `hue_order` with a numeric hue variable:

```python
sns.lineplot(x=[0, 1, 0, 1], y=[0, 1, 0, 2], hue=[-1, -1, 1, 1],
             legend="full", palette="bwr")
```

```python
sns.lineplot(x=[0, 1, 0, 1], y=[0, 1, 0, 2], hue=[-1, -1, 1, 1],
             hue_order=[1, -1], legend="full", palette="bwr")
```

Both calls produce the following image:

![image](https://user-images.githubusercontent.com/315810/62792771-f71cc380-ba9d-11e9-819c-a8ffce1d9cd4.png)

**Comment by MaozGelbart** [comment]
Could you please elaborate? I tweaked the example a little bit, am not sure I see this behavior on the most recent version with the example dataset::

	import matplotlib.pyplot as plt
	import seaborn as sns; sns.set()

	fmri = sns.load_dataset("fmri")
	fig, axes = plt.subplots(2)
	sns.lineplot(x="timepoint", y="signal", style="event", data=fmri, 
		style_order=["stim", "cue"],  dashes=[(4, 1), (1, 1)], ax=axes[0])
	sns.lineplot(x="timepoint", y="signal", style="event", data=fmri, 
		style_order=["cue", "stim"],  dashes=[(4, 1), (1, 1)], ax=axes[1])              
	plt.show()
 ![1632](https://user-images.githubusercontent.com/13831112/56193130-996cf300-6038-11e9-8eaa-1ed08538a3f4.png)

**Comment by MaozGelbart** [comment]
Referring to the new issue - this is also relevant for ``scatterplot`` and seems by design:
```
hue_order : list, optional

Specified order for the appearance of the hue variable levels, otherwise they are determined from the data. 
Not relevant when the hue variable is numeric.
```
