### ISSUE TITLE
Clustermap, row_colors with pandas.Series don't match by index if pandas.Series index is longer than data index

### ISSUE THREAD

**Issue by glucksfall** [mwaskom/seaborn#1637]
Hello @mwaskom,

Maybe I misunderstand the documentation, but I couldn't replicate the documented behavior for row_colors using a pandas.Series. The docs said that it will match the row_colors index with the data index. However, I should pass a slice of the pandas.Series with only the indexes plotted in the heatmap to correctly match the order. I thought that the match would be correct even if the pandas.Series has more entries.

BTW, you have been done a great job. I use seaborn for 99% of my plots, if not 100%. 

Best regards.

**Comment by mwaskom** [comment]
Can you please show a reproducible example?

**Comment by mwaskom** [comment]
Closing for lack of reproducible example but #1712 addressed a pandas deprecation that may be relevant to this issue.
