### ISSUE TITLE
Clustermap, missing labels if row_colors is a list of pandas.Series

### ISSUE THREAD

**Issue by glucksfall** [mwaskom/seaborn#1638]
Hello,

I found that the labels are missing when using a list of pandas.Series. 

Also, the added column is divided by new colors rows. This could be a concern if the metadata has many categories that the user want to include (like the image in https://github.com/mwaskom/seaborn/issues/1031). Could be one column per row_color?

Best regards.

**Comment by mwaskom** [comment]
Can you please show a reproducible example?

**Comment by glucksfall** [comment]
Sure.

I used the example code here https://seaborn.pydata.org/examples/structured_heatmap.html and the only change is the row_colors (and col_colors) are lists of a pandas.Series
[Untitled.pdf](https://github.com/mwaskom/seaborn/files/2729118/Untitled.pdf)

**Comment by mwaskom** [comment]
Ah, indeed, there's no easy way to control the scale of those axes and the defaults aren't great with lots of annotations. There is a [PR](#1393) that fixes some of this but I haven't been able to finalize it yet. In the meantime I think the only answer is to change the aspect ratio of the whole figure, sorry.
