### ISSUE TITLE
How to show the percentage in a countplot with a "hue" parameter

### ISSUE THREAD

**Issue by Wellington-Noberto** [mwaskom/seaborn#1639]
I've read some related problems but it doesn't seem to have the answer that I'm looking for.
![file](https://user-images.githubusercontent.com/46430006/50743932-35968b00-11fc-11e9-90b4-253b6d855a1f.JPG)
I'd like to show each percentage of occurrence within each hue

**Comment by mwaskom** [comment]
Hi — this kind of question is better suited for stackoverflow, where I'm sure this has come up before.
