### ISSUE TITLE
MatplotlibDeprecationWarning in seaborn.reset_orig()

### ISSUE THREAD

**Issue by koki-sato** [mwaskom/seaborn#1642]
## What

`seaborn.reset_orig()` causes `MatplotlibDeprecationWarning`

```python
>>> import seaborn as sns
>>> sns.__version__
'0.9.0'
>>> sns.mpl.__version__
'3.0.2'
>>> sns.reset_orig()
/Users/xxxx/.anyenv/envs/pyenv/versions/3.6.5/lib/python3.6/site-packages/matplotlib/__init__.py:855: MatplotlibDeprecationWarning:
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))
/Users/xxxx/.anyenv/envs/pyenv/versions/3.6.5/lib/python3.6/site-packages/matplotlib/__init__.py:846: MatplotlibDeprecationWarning:
The text.latex.unicode rcparam was deprecated in Matplotlib 2.2 and will be removed in 3.1.
  "2.2", name=key, obj_type="rcparam", addendum=addendum)
```

It is because `matplotlib.rcParams.copy()` returns dictionary of rcParams and it includes deprecated rcParams like `examples.directory` and `text.latex.unicode`. However, they are included in the default rcParams of matplotlib.

This is a problem caused by matplotlib, but I want seaborn to catch and discard the warnings internally.

**Comment by mhooreman** [comment]
Same issues here, which is systematic those days by pip installing matplotlib and seaborn with default versions.
