### ISSUE TITLE
Feature request: allow non-symmetrical violint plots

### ISSUE THREAD

**Issue by Naereen** [mwaskom/seaborn#1648]
Hi!
I love violinplots, but I always found that it might not be needed to plot them as symmetrical, the information is doubly present for no real reason.
I will send a tiny pull request that adds a key-word argument `nonsymmetrical` to `seaborn.violint`, it can be `False` (the default), or `"left"` or `"right"` (or `"bottom"` or `"top"`) to allow to only plot half of the violin.

Here are two tiny demos, for a single violin or more violins, for horizontal (top/bottom) or vertical (left/right) cases:
![proposal nonsymmetrical violin plots 1](https://user-images.githubusercontent.com/11994719/50970591-1771a900-14e2-11e9-9b49-8ee9346daa1e.png)
![proposal nonsymmetrical violin plots 2](https://user-images.githubusercontent.com/11994719/50970594-19d40300-14e2-11e9-9ca3-fdd4531525cf.png)

**Comment by Naereen** [comment]
It is a very small feature and I think it is useful, when doing violin plots with lots of datasets, it reduces the visual clutter to only plot left/top part of the violin.

**Comment by mwaskom** [comment]
I don't agree that the symmetry is redundant. It facilitates comparison of each violin with its neighbors.

In general I'm opposed to adding too many additional parameters, especially ones that control specific aspects of plot appearance without helping the plots show information any better.

**Comment by Naereen** [comment]
Okay, I understand your point of view.

**Comment by njvack** [comment]
For what it's worth, I'm looking for half-violin plots for [Raincloud plots](https://github.com/RainCloudPlots/RainCloudPlots#python-environment). That package has its own implementation but... it's mainly a copy of your code.

You can jigger seaborn to do half-violins by [adding fake off-scale data to yourset and abusing the `hue` parameter,](https://stackoverflow.com/questions/53872439/half-not-split-violin-plots-in-seaborn) but that's pretty gross.

A more useful alternative, though, might be to add `kind='kde'`to `sns.catplot` — really, a violin plot is just two kdeplots pasted together.

Thoughts?

**Comment by givenx** [comment]
`kind='kde'`to `sns.catplot` would be perfect. We have had multiple requests from our clients to drop the symmetry as it can be off-putting. I think it is more important than you realise, @mwaskom, imho.
