### ISSUE TITLE
couldn't Import seaborn

### ISSUE THREAD

**Issue by Tikam02** [mwaskom/seaborn#1650]
Even after successfully installation seaborn could not imported.
![screenshot from 2019-01-12 01-38-29](https://user-images.githubusercontent.com/10548085/51057223-ec36a900-160a-11e9-8f7c-214a18c3a2be.png)

**Comment by mwaskom** [comment]
You haven't successfully installed seaborn in a place your jupyter notebook kernel can find it. The answer is going to be something specific to your setup. I'd suggest reading through [this blog post](https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/) for debugging issues like these.
