### ISSUE TITLE
catplot() doesn't inherit all matplotlib.rcParams settings

### ISSUE THREAD

**Issue by ncthomas** [mwaskom/seaborn#1652]
catplot() doesn't inherit all matplotlib.rcParams settings, and doesn't work consistently with all settings in an mplstyle file. Reproducible example below - the facecolor of the catplot() will be green with the below code, but the colour scheme will remain as the default.

```
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
from cycler import cycler

titanic = sns.load_dataset("titanic")

mpl.rcParams['axes.facecolor'] = 'green'
mpl.rcParams['axes.prop_cycle'] = cycler('color', ['red', 'orange', 'yellow', 'green'])

g = sns.catplot(x="class", y="survived", hue="sex", data=titanic,
                height=6, kind="bar", palette="muted")
```
 seaborn v0.9.0
matplotlib v3.0.2

**Comment by mwaskom** [comment]
That's because you're specifying a different `palette` when you call `catplot`. If you want to use the default, don't do that.
