### ISSUE TITLE
docs "Bar plots" in "Plotting with categorical data", data should be sorted

### ISSUE THREAD

**Issue by yiran7324** [mwaskom/seaborn#1655]
I came to find in [tutorial](https://seaborn.pydata.org/tutorial/categorical.html#statistical-estimation-within-categories) that Bar plots's (in "Statistical estimation within categories") second chart's code 

```python
sns.catplot(x="deck", kind="count", palette="ch:.25", data=titanic);
```

should be 

```python
sns.catplot(x="deck", kind="count", palette="ch:.25", 
			data=titanic.sort_values("deck"));
```

that can be ordered in alphabetical

![](https://seaborn.pydata.org/_images/categorical_38_0.png)

**Comment by mwaskom** [comment]
The plot in the tutorial is generated from the code that you see and works fine, so I'm not certain what the issue is?
