### ISSUE TITLE
Difference in test suite for Python2 and Python3

### ISSUE THREAD

**Issue by tillea** [mwaskom/seaborn#1656]
Hi,
I've just uploaded version 0.9.0 of seaborn to Debian, but I needed a [dirty hack](https://salsa.debian.org/science-team/seaborn/blob/debian/debian/patches/skip_suspicious_test.patch) to pass the test suite n ot only for Python 2.7 (which is OK) but also for Python 3.7, which otherwise runs into

    =================================== FAILURES ===================================
    _________________________ TestHeatmap.test_cbar_ticks __________________________

    self = <seaborn.tests.test_matrix.TestHeatmap object at 0x7fd9104779e8>

        def test_cbar_ticks(self):
            max_n_ticks = 3
    ....
            locator = mpl.ticker.MaxNLocator(max_n_ticks)
            f, (ax1, ax2) = plt.subplots(2)
            mat.heatmap(self.df_norm, ax=ax1, cbar_ax=ax2,
                        cbar_kws=dict(ticks=locator))
    >       nt.assert_equal(len(ax2.yaxis.get_ticklabels()), max_n_ticks)

    seaborn/tests/test_matrix.py:397:.
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _.
    /usr/lib/python3.7/unittest/case.py:839: in assertEqual
        assertion_func(first, second, msg=msg)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _.

    self = <nose.tools.trivial.Dummy testMethod=nop>, first = 5, second = 3
    msg = '5 != 3'

        def _baseAssertEqual(self, first, second, msg=None):
            """The default assertEqual implementation, not type specific."""
            if not first == second:
                standardMsg = '%s != %s' % _common_shorten_repr(first, second)
                msg = self._formatMessage(msg, standardMsg)
    >           raise self.failureException(msg)
    E           AssertionError: 5 != 3

    /usr/lib/python3.7/unittest/case.py:832: AssertionError

I have no idea why the result is 5 instead of 3 when using Python 3.7.
Kind regards, Andreas.

**Comment by MaozGelbart** [comment]
Is this the same as #1571 ? If so a PR has been proposed to resolve this.

**Comment by mwaskom** [comment]
Thanks, fixed in #1712
