### ISSUE TITLE
relplot ignores x-value categorical order

### ISSUE THREAD

**Issue by kaisengit** [mwaskom/seaborn#1665]
I've got a problem with regplot. Specifically if I assign a categorical order for my x-value:

`
df[exp] = pd.Categorical(
            df[exp],
            categories=sorted(df[exp].unique(), reverse=True),
            ordered=True
        )
`

So I want to reverse the order of my x-values. This works fine with catplot:
`
sns.catplot(data=df, x=exp, y=sum_total, col=level, kind='point', col_wrap=5, ci='sd', sharey=False, hue=domain, sharex=False)
`

However, the order is not preserved when plotting the same with a relplot:
`
sns.relplot(data=df, x=exp, y=sum_total,
                         col=level, kind='line', col_wrap=5, ci='sd',
                         hue=domain, facet_kws={'sharey':False, 'sharex':False})
`

**Comment by mwaskom** [comment]
Everything is working as intended here. `catplot` (as the name suggests) is for plotting categorical variables. `relplot` isn't.

**Comment by kaisengit** [comment]
Fair enough but is there a way to make the kind of lineplot done with relplot also with a catplot (i.e. where the CI is an area around the curve)? Or should I take this question somewhere else?

**Comment by mwaskom** [comment]
matplotlib (at least relatively recent versions) can handle non-numeric data. So it's possible to make the plot you want using relplot, but unlike with catplot, the positioning logic is going to be handled by matplotlib. And matplotlib doesn't "know" about pandas categoricals the way (some) seaborn functions do. So the solution is going to be at the matplotlib layer, but I actually don't know what it is off the top of my head. Maybe just setting the x ticks properly?

**Comment by kaisengit** [comment]
I see, that's a good idea. I'll play around with this. Thank you for your help!
