### ISSUE TITLE
More control over outliers with lmplot(...robust=True)

### ISSUE THREAD

**Issue by danieljfarrell** [mwaskom/seaborn#1666]
With `lmplot(... robust=True)` outliers are de-weighted. Would it be possible to gain more control over this de-weighting so that fewer or more outliers could be removed?

**Comment by mwaskom** [comment]
I'm not sure exactly what you're looking for but if you want to be very specific about what model gets fit I would suggest fitting it yourself with statsmodels. `lmplot` is mostly meant for quick exploratory analysis.
