### ISSUE TITLE
[Feature request] [Swarmplot] Allow hue-dodged swarmplots by shape, not only colour

### ISSUE THREAD

**Issue by nicolazilio** [mwaskom/seaborn#1673]
Hi there,

For those of us who do not want to pay colour charges when publishing results in a journal and have to resort to plotting graphs in black and white, it would be nice to have the option to produce hue-dodged swarmplots by shape, not only colour.

Would that be possible?

**Comment by mwaskom** [comment]
Hi — thanks for the suggestion but this won't really work because the swarming algorithm uses radial distances.
