### ISSUE TITLE
Regression in regplot with x_bins is calculated based on original data not using mean of binned points

### ISSUE THREAD

**Issue by marwan116** [mwaskom/seaborn#1674]
Looking at the source code for seaborn's [regression](https://github.com/mwaskom/seaborn/blob/master/seaborn/regression.py) and testing several regression plots it seems to me that currently seaborn generates the regression line by taking as inputs the original data points (x) even when x_bins is specified.

It would make much more sense in the case when x_bins isn't None for the regression to be produced by taking as inputs the mean of the bins (or x_estimator) and not the original data points - since usually binning is carried out to avoid outliers from severely affecting the regression trend ... 

EDIT:
Going through the documentation - it seems this was a deliberate decision, quoting from the documentation: "This binning only influences how the scatterplot is drawn; the regression is still fit to the original data." 

I am wondering why this makes sense as the chosen default and how to override this behavior?

**Comment by mwaskom** [comment]
> It would make much more sense in the case when x_bins isn't None for the regression to be produced by taking as inputs the mean of the bins (or x_estimator) and not the original data points

I don't agree but you're welcome to write your own library that does this.

**Comment by marwan116** [comment]
thank you for your prompt reply - would be nice if you can elaborate on why
this behavior makes more sense.
