### ISSUE TITLE
Allow specification of degrees of of freedom (ddof) for standard deviation

### ISSUE THREAD

**Issue by kaisengit** [mwaskom/seaborn#1677]
It would be great when using ci='sd' to have an option to set the ddof for the standard deviation. Right now it uses the numpy default of ddof=0 which means that all my sample sd's will be biased. 

For at least less biased sample sd's we'd need ddof=1 (Bessel correction). Also, pandas uses ddof=1 by default, so this behavior is not consistent with pandas.

**Comment by mwaskom** [comment]
Sorry but I'm not going to be adding another parameter for this. If you want a very specific plot you can make it directly in matplotlib. (Also, pandas and numpy having different defaults is really not a seaborn problem...)
