### ISSUE TITLE
line plot ignores markers attribute although matplotlib plots markers

### ISSUE THREAD

**Issue by HeikoSchuett** [mwaskom/seaborn#1680]
I am running matplotlib 3.0.2 and Seaborn 0.9.0 in python 3.7 on MacOs. 
There appears to be a bug in Seaborn which makes its line plot function ignore the markers argument. The matplotlib plot still plots the markers, i.e. this is not the problem and I also set lines.markeredgewidth as was recommended in an earlier issue on missing markers. Still whatever I set markers to, line plot accepts this and ignores it.

See a broken example: Matplotlib plots as it should, but Seaborn shows no markers:

```
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sns.set()
sns.set_context("paper",rc={"lines.linewidth": 2.5,'lines.markeredgewidth': 1,'lines.markersize': 10})

df_test = pd.DataFrame(data={'x':[1,2,3],'y':[4,5,6]})
plt.figure()
plt.plot(df_test['x'],df_test['y'],'o-')
plt.figure()
sns.lineplot(data=df_test,x='x',y='y',markers=['o'])
plt.show()
```

![image](https://user-images.githubusercontent.com/13691026/53176872-f4e0ae80-35bc-11e9-9224-18417d406f50.png)

![image](https://user-images.githubusercontent.com/13691026/53176853-e7c3bf80-35bc-11e9-99e5-911b59380b27.png)

**Comment by mwaskom** [comment]
Hi Heiko! As mentioned [here](http://seaborn.pydata.org/generated/seaborn.lineplot.html#seaborn.lineplot), the `markers` parameter controls what markers are used to differentiate levels of the `style` semantic. In your example, you're not setting a `style` semantic, so the `markers` parameter (properly) has no effect. But you can use the `marker` keyword (note the subtle difference) which is not actually a parameter of the seaborn function, but instead gets passed down to `plt.plot`:

```python
sns.lineplot(data=df_test, x='x', y='y', marker="o")
```
![image](https://user-images.githubusercontent.com/315810/53182315-43934600-35c7-11e9-9288-c31d965741de.png)

**Comment by HeikoSchuett** [comment]
Thanks!
