### ISSUE TITLE
percentile alternatives for pointplot's error bar line

### ISSUE THREAD

**Issue by bramkaarga** [mwaskom/seaborn#1681]
As an alternative to Bootstrapping and using Standard Deviation for pointplot's ci (confidence interval) argument, I think it is also worthwhile to add percentile of the data as another alternative. I hardcoded it myself like this:

elif ci == "percentile":
           perc_lower = np.percentile(stat_data, 25)
           perc_upper = np.percentile(stat_data, 75)
           confint.append((perc_lower , perc_upper ))

My issue was if I use standard deviation, the error bar lines go below 0 and beyond 100 (the value for my data should be between 0-100). The bootstrapping alternative somehow do not yield the results that I wanted. 

This lines of code makes pointplot quite similar to boxplot to some extent though.

**Comment by mwaskom** [comment]
This has come up before and I’m going to pass for now, thanks.
