### ISSUE TITLE
Scatterplot (and possibly others?) fail when specifying a color list manually

### ISSUE THREAD

**Issue by tinloaf** [mwaskom/seaborn#1682]
Matplotlib's scatterplot allows to manually specify the color for each dot. From the documentation of `seaborn.scatterplot`, I see that additional `kwargs` should be passed on to matplotlib's scatterplot, i.e., I should be able to set that color list.

However, here is a minimal example that leads to a crash:
```
import pandas as pd
import seaborn as sns

data = [{"x": x, "y": y} for x in range (0,5) for y in range(0,5)]
df = pd.DataFrame(data)
colors = [ "#000000" ] * len(data)

sns.scatterplot(x="x", y="y", color=colors, data=df)
```

The problem, as far as I can tell, is the magic with which seaborn determines colors in [line 740](https://github.com/mwaskom/seaborn/blob/f0349b1a7f1e022cb1da8b94f2e019f04eeed397/seaborn/relational.py#L740) of `relational.py`. Here, an empty plot is attempted with the `kwargs` passed, which leads to a mismatch in the length of the `c`, `x` and `y` fields.

I'm not sure what the best solution would be. If the empty plot in line 740 is only needed for the colors, one might want to skip it when colors are specified manually?

**Comment by mwaskom** [comment]
I don't get an error when I run your code — I get a plot with black scatter points. And you don't say what the error you see is. But in `plt.scatter`, the `color` parameter and the `c` parameter are similar but not identical — only the latter is intended to be used with a vector of colors, while the former applies the same color to all points. My guess is that you are using a different version of matplotlib that is more strict about that distinction.

**Comment by tinloaf** [comment]
Sorry - the error I'm seeing is:
`ValueError: 'c' argument has 25 elements, which is not acceptable for use with 'x' with size 0, 'y' with size 0.`

This error remains the same if I use the `c` parameter instead of the `color` parameter.

The full backtrace is:
```
ValueError                                Traceback (most recent call last)
<ipython-input-13-2572ec214632> in <module>
----> 1 p = sns.scatterplot(x="x", y="y", c=colors, data=df)

~/.virtualenvs/def/lib/python3.6/site-packages/seaborn/relational.py in scatterplot(x, y, hue, style, size, data, palette, hue_order, hue_norm, sizes, size_order, size_norm, markers, style_order, x_bins, y_bins, units, estimator, ci, n_boot, alpha, x_jitter, y_jitter, legend, ax, **kwargs)
   1339         ax = plt.gca()
   1340 
-> 1341     p.plot(ax, kwargs)
   1342 
   1343     return ax

~/.virtualenvs/def/lib/python3.6/site-packages/seaborn/relational.py in plot(self, ax, kws)
    877         # function will advance the axes property cycle.
    878 
--> 879         scout = ax.scatter([], [], **kws)
    880         s = kws.pop("s", scout.get_sizes())
    881         c = kws.pop("c", scout.get_facecolors())

~/.virtualenvs/def/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1808                         "the Matplotlib list!)" % (label_namer, func.__name__),
   1809                         RuntimeWarning, stacklevel=2)
-> 1810             return func(ax, *args, **kwargs)
   1811 
   1812         inner.__doc__ = _add_data_doc(inner.__doc__,

~/.virtualenvs/def/lib/python3.6/site-packages/matplotlib/axes/_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, **kwargs)
   4243                         "acceptable for use with 'x' with size {xs}, "
   4244                         "'y' with size {ys}."
-> 4245                         .format(nc=n_elem, xs=x.size, ys=y.size)
   4246                     )
   4247                 # Both the mapping *and* the RGBA conversion failed: pretty

ValueError: 'c' argument has 25 elements, which is not acceptable for use with 'x' with size 0, 'y' with size 0.
```

I'm using matplotlib 3.0.2 and Seaborn 0.9.0. You can see a full Jupyter notebook demonstrating the problem here: https://tinloaf.de/~tinloaf/Scratchbook.html

**Comment by mwaskom** [comment]
For some reason the matplotlib developers are constantly changing the `c`/`color` functionality. I think this is an irritating example where they've made an uneccessary (imo) change and broken seaborn.

**Comment by ImportanceOfBeingErnest** [comment]
Concerning the actual use case here, note that 

    plt.scatter(x="x", y="y", color=colors, data=df)

works perfectly fine. And for any usage of `sns.scatterplot` that cannot directly be done via `plt.scatter` (e.g. when using `hue`) using a pass-through argument for `color` wouldn't work for other reasons anyways.


There is a tendency in matplotlib development to error out sooner rather than later on non-sensical input. The reason is an increased number of bug reports about cryptic error messages at drawtime or undesired graphical output, which can all be prevented by disallowing such input from the start. Due the documentation always being clear on the fact that the number of input colors needs to match the coordinate dimensions, this was not considered as an API change which needs a deprecation period.  
Of course if there is any good argument to allow for something like `scatter([], [], c=["red", "green"])`, opening an issue or PR at matplotlib is always possible. (I could imagine that not having access to the actual cycler state might be considered as a valid reason.)

In general maybe establishing CI testing with matplotlib's master branch might be helpful to find out about potential problems soon enough.

**Comment by mwaskom** [comment]
> Due the documentation always being clear on the fact that the number of input colors needs to match the coordinate dimensions, this was not considered as an API change which needs a deprecation period.

Ah, yes, because documentation is the same thing as a functional API...

**Comment by mwaskom** [comment]
>  And for any usage of sns.scatterplot that cannot directly be done via plt.scatter (e.g. when using hue) using a pass-through argument for color wouldn't work for other reasons anyways.

This is quite false. For example:

```python
x = [1, 2, 3]
y = [1, 2, 3]
z = [1, 2, 3]
c = sns.color_palette("deep", 3)
sns.scatterplot(x=x, y=y, style=z, color=c, s=200)
```

cannot be accomplished in a single call to `plt.scatter`.

To say nothing of the fact that your specific suggestion,

```python
plt.scatter(x="x", y="y", color=colors, data=df)
sns.scatterplot(x="x", y="y", color=colors, data=df)
```

does not produce identical outputs (e.g. seaborn labels the axes automatically).

@ImportanceOfBeingErnest I'm always amazed at your ability to confidently assert incorrect claims!

**Comment by ImportanceOfBeingErnest** [comment]
If you read closely none of your examples invalidates what I wrote above. 

And of course one can achieve a scatter plot like the one from the first example with a single call to `scatter`. It's just not very convenient to define the "style" manually. 

In total, you are answering seemingly false claims by actual false claims. Whether that is helpful in any way... I don't know.

**Comment by mwaskom** [comment]
Unfortunately I guess the answer is that this is broken on newer matplotlib versions, and I see no value in trying to convince upstream otherwise; sorry about that.
