### ISSUE TITLE
Use python formatting for heat map

### ISSUE THREAD

**Issue by owlas** [mwaskom/seaborn#1685]
The seaborn heatmap allows the `fmt=` flag to control the annotations on the plot. These are converted into the standard python string formatting context here:

https://github.com/mwaskom/seaborn/blob/f0349b1a7f1e022cb1da8b94f2e019f04eeed397/seaborn/matrix.py#L243

I wondered whether it would be more flexible and consistent to allow the user to specify the python formatting string themselves. e.g. `fmt='{:.2f}'` for the default value. What is the reason that it's not the case?

Possible reasons to change:
 - It is already very well documented (https://docs.python.org/3.4/library/string.html#format-specification-mini-language) so seaborn would not need to document the non-standard formatter. Currently there is no clear guidance.
 - It might clear up confusion with users. Currently it isn't clear that the formatting string is passed into python formatting: [SO1](https://stackoverflow.com/questions/37602885/adding-units-to-heatmap-annotation-in-seaborn) [SO2](https://stackoverflow.com/questions/35946819/possible-to-round-numbers-to-the-hundreds-thousands-etc-using-python-3s-numb) [SO3](https://stackoverflow.com/questions/41164710/how-to-add-text-plus-value-in-python-seaborn-heatmap)
 - It would allow much more control e.g. (`100324`-> `"100.3k"`)

Disadvantages:
 - Perhaps new users not familiar with python will be more confused by the python string formatting syntax
 - It might feel repetitive for the user to have to add curly braces to the argument
 - Would it introduce some complexity in keeping the colorbar consistent with the annotations?

I understand that a lot of thought has been given to designing the seaborn interface. I'm sorry if I've missed something obvious in the current design.

**Comment by mwaskom** [comment]
I don't quite understand how the current implementation is not using "python formatting". That's exactly what it's doing. Do you have an example of something that isn't currently possible?

**Comment by owlas** [comment]
The only thing you can't do is to add characters around the string such as `"{:.1f}k".format(100324 / 1000)" == "100.3k"`.

Otherwise, it might make it more obvious that the code actually accepts python string formatting characters. But this could also be done by updating the doc string:

https://github.com/mwaskom/seaborn/blob/f0349b1a7f1e022cb1da8b94f2e019f04eeed397/seaborn/matrix.py#L368-L369

**Comment by mwaskom** [comment]
Then we agree that seaborn is using “the standard python string for matter” so I am going to close this issue. Thanks!

**Comment by owlas** [comment]
Do you think it would help users to update the doc string to something like:

```python
     fmt : string, optional 
         String format to use when adding annotations. Specified using python [string formatting mini-language](https://docs.python.org/3/library/string.html?highlight=string#formatspec)
```

**Comment by joaopalotti** [comment]
Hi guys, I think a common use case of heat maps is showing floats without leading zeros. This would require something like 
"{:.2f}".format(x).replace("0.", ".").

Would it be possible with the current "fmt" in seaborn?

Thanks

**Comment by mwaskom** [comment]
If you need something fussy, I'd recommend that you define a matrix of string values and pass that into `annot`.

**Comment by joaopalotti** [comment]
Cool! Thanks for the quick reply and suggestion. I will try it out! Thanks

**Comment by tjaqu787** [comment]
(1)(https://docs.python.org/3/library/string.html?highlight=string#formatspec) 
 (2)"Do users know what the default `.2g` does?"  
(1)The docs should be updated to this because (2) No most of us are stunned as heck!!!!

**Comment by binus** [comment]
Just adding another use case: when using `.n%` to format a percentage as long as enabling latex function with matplotlib, the `%` symbol will not be correctly rendered. So just wondering if it is possible to leave this fmt as a general interface, so that I can pass in a **function** (or a matplotlib **Formatter**) to process the custom format? In the matplotlib native implementation, it adds `\%` instead `%` when latex mode is activated.

Some codes for such use case :
```
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
plt.rcParams.update({"text.usetex": True})
heatmap = sns.heatmap(..., annot=True, fmt=".2%")
cbar = ax.collections[0].colorbar
cbar.ax.yaxis.set_major_formatter(PercentFormatter(1, 2))
```
