### ISSUE TITLE
move data organization into the beginning on the introduction page?

### ISSUE THREAD

**Issue by elliewix** [mwaskom/seaborn#1687]
Hi all,

In reference to this page:  https://seaborn.pydata.org/introduction.html

Can the data organization content chunk at the very end but cut and pasted into the beginning of the document?  The organization of datasets are hinted at in the middle of the first example, but really easy to miss.  I'm extremely happy that this discussion was put in there, because it is so often ignored.  But I'd like it to be at the beginning so someone flying through examples on their own data wouldn't hit errors and give up.

I'm happy to propose a change myself for this, but not entirely sure what is the best place to whack on.  Should I propose a change to this file?  https://github.com/mwaskom/seaborn/blob/master/doc/introduction.ipynb

Thanks!

**Comment by mwaskom** [comment]
I’m going to decline this, because a lot of thought already went into the intro. Thanks!
