### ISSUE TITLE
Display value on top of bars in barplot and countplots.

### ISSUE THREAD

**Issue by shiv-1998** [mwaskom/seaborn#1688]
Hello,
I want to make a suggestion that - can we add another argument in the seaborn methods like barplots and countplots through which the value could be displayed on top of the bars, without having to do that manually through coding.

**Comment by mwaskom** [comment]
I'm going to decline on this, thanks!

**Comment by bigfoot31** [comment]
This feature has been requested multiple times on github, has multiple stackoverflow questions and it is not trivial to add labels manually. Can you elaborate as to why you are declining this?
Atleast add a tutorial to the docs.

**Comment by mwaskom** [comment]
I think this is best accomplished with a third-party package.
