### ISSUE TITLE
ImportError: cannot import name 'MapWrapper'

### ISSUE THREAD

**Issue by nric** [mwaskom/seaborn#1690]
Hi all,

when trying to import seaborn I get an error.
Operating system is windows 10, using VS Code connected to a Jupyter Server.
Seaborn version is 0.9.0

>>>import seaborn as sns
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
 in ()
----> 1 import seaborn as sns
      2 sns.pairplot(train_dataset[["MPG", "Cylinders", "Displacement", "Weight"]],diag_kind="kde", hue="Acceleration")

~\Anaconda3\envs\ERG1\lib\site-packages\seaborn\__init__.py in ()
      4 
      5 # Import seaborn objects
----> 6 from .rcmod import *
      7 from .utils import *
      8 from .palettes import *

~\Anaconda3\envs\ERG1\lib\site-packages\seaborn\rcmod.py in ()
      3 import functools
      4 import matplotlib as mpl
----> 5 from . import palettes, _orig_rc_params
      6 
      7 

~\Anaconda3\envs\ERG1\lib\site-packages\seaborn\palettes.py in ()
     10 from .external.six.moves import range
     11 
---> 12 from .utils import desaturate, set_hls_values, get_color_cycle
     13 from .colors import xkcd_rgb, crayons
     14 

~\Anaconda3\envs\ERG1\lib\site-packages\seaborn\utils.py in ()
      5 
      6 import numpy as np
----> 7 from scipy import stats
      8 import pandas as pd
      9 import matplotlib as mpl

~\Anaconda3\envs\ERG1\lib\site-packages\scipy\stats\__init__.py in ()
    365 from __future__ import division, print_function, absolute_import
    366 
--> 367 from .stats import *
    368 from .distributions import *
    369 from .morestats import *

~\Anaconda3\envs\ERG1\lib\site-packages\scipy\stats\stats.py in ()
    171 from scipy._lib._util import _lazywhere
    172 import scipy.special as special
--> 173 from . import distributions
    174 from . import mstats_basic
    175 from ._stats_mstats_common import _find_repeats, linregress, theilslopes, siegelslopes

~\Anaconda3\envs\ERG1\lib\site-packages\scipy\stats\distributions.py in ()
      8 from __future__ import division, print_function, absolute_import
      9 
---> 10 from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
     11                                     rv_frozen)
     12 

~\Anaconda3\envs\ERG1\lib\site-packages\scipy\stats\_distn_infrastructure.py in ()
     22 
     23 # for root finding for discrete distribution ppf, and max likelihood estimation
---> 24 from scipy import optimize
     25 
     26 # for functions of continuous distributions (e.g. moments, entropy, cdf)

~\Anaconda3\envs\ERG1\lib\site-packages\scipy\optimize\__init__.py in ()
    399 from ._linprog import linprog, linprog_verbose_callback
    400 from ._hungarian import linear_sum_assignment
--> 401 from ._differentialevolution import differential_evolution
    402 from ._lsq import least_squares, lsq_linear
    403 from ._constraints import (NonlinearConstraint,

~\Anaconda3\envs\ERG1\lib\site-packages\scipy\optimize\_differentialevolution.py in ()
      9 from scipy.optimize import OptimizeResult, minimize
     10 from scipy.optimize.optimize import _status_message
---> 11 from scipy._lib._util import check_random_state, MapWrapper
     12 from scipy._lib.six import xrange, string_types
     13 

ImportError: cannot import name 'MapWrapper'

### Scipy/Numpy/Python version information:
>>>import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)

Tried to pip install MapWrapper but: Could not find a version that satisfies the requirement mapwrapper (from versions: ) No matching distribution found for mapwrapper

Is there a general compatibility problem with windows or am I missing something here?

Thanks, and have a great day everyone!

**Comment by mwaskom** [comment]
Hi — as you can see if you read down the stack trace, this is a problem with your scipy installation. It only appears related to seaborn because seaborn imports scipy, but I expect that if you tried to import `scipy.stats` directly you'd the same problem. As I don't have any particular insight on how to fix your issue, I'm going to close.
