### ISSUE TITLE
Display already binned data with swarmplot

### ISSUE THREAD

**Issue by reza1615** [mwaskom/seaborn#1691]
Please add a possibility to plot already binned data with swarmplot like weights variable for plt.hist()
which allows users to plot binned data. for more information please see [here](https://stackoverflow.com/questions/55056135/display-already-binned-data-with-seaborn-swarmplot)

**Comment by mwaskom** [comment]
I don't think this would make much sense, but thanks for the suggestion!

**Comment by reza1615** [comment]
Why do you think so?  As a matter of fact, when we have huge data, getting a query makes a performance issue. So we should binning data. presenting that data needs to be supported.
