### ISSUE TITLE
Datetime columns as hue produce an empty scatterplot

### ISSUE THREAD

**Issue by jpweytjens** [mwaskom/seaborn#1693]
Passing a column with dtype `datetime64[ns]` as the hue column for a scatter plot produces an empty plot with only the legend.

## Example
I have a dataframe with the folllowing columns:
```
vdab referentienummer             Int64
vdab id nummer                    Int64
start datum              datetime64[ns]
eind datum               datetime64[ns]
```
The following produces an empty plot
```
sns.scatterplot(x='vdab referentienummer', y='vdab id nummer', hue='start datum', data=vacatures)
```

![empty](https://user-images.githubusercontent.com/34494702/54131140-04ac1f80-4412-11e9-9fd0-1dc1fa977009.png)

while casting to `object` does what I expect.

```
vacatures['start datum'] = vacatures['start datum'].astype('object')
sns.scatterplot(x='vdab referentienummer', y='vdab id nummer', hue='start datum', data=vacatures)
```
![non-empty](https://user-images.githubusercontent.com/34494702/54131150-070e7980-4412-11e9-98e2-bd4850891816.png)

**Comment by mwaskom** [comment]
Can you please share a reproducible example? Thanks.

**Comment by u1z** [comment]
```
import os
import pandas as pd
import seaborn as sns


# load data
home = os.path.join('TXT_DIR', '') # replace with location of txt file
dtypes = {'vdab referentienummer'      : 'Int64',
          'vdab id nummer'             : 'Int64',}
dates = ['start datum', 'eind datum']
vacatures = pd.read_csv(home + 'output.csv', sep=';', dtype=dtypes, parse_dates=dates)

# empty scatterplot
sns.scatterplot(x='vdab referentienummer', y='vdab id nummer', hue='start datum', data=vacatures)

# expected behaviour
vacatures['start datum'] = vacatures['start datum'].astype(object)
sns.scatterplot(x='vdab referentienummer', y='vdab id nummer', hue='start datum', data=vacatures)
```
The data I used can be found here [output.txt](https://github.com/mwaskom/seaborn/files/2955793/output.txt)

**Comment by mwaskom** [comment]
The answer has to do with inconsistencies with when `pd.Timestamp` and `np.datetime64` are and are not exchangeable. I don't know if I would call this a bug in pandas but it is inconvenient:

```python
x = pd.date_range(start="2010", freq="y", periods=5).to_series()
```

```python
>>> x[0]
Timestamp('2010-12-31 00:00:00')
```

```python
>>> x.unique()
array(['2010-12-31T00:00:00.000000000', '2011-12-31T00:00:00.000000000',
       '2012-12-31T00:00:00.000000000', '2013-12-31T00:00:00.000000000',
       '2014-12-31T00:00:00.000000000'], dtype='datetime64[ns]')
```

With the consequence that 

```python
>>> x[0] in x.unique()
False
```

**Comment by mwaskom** [comment]
I am on pandas 0.23.4 and don't have a development environment handy right now so this could be moot.

**Comment by TomAugspurger** [comment]
```
>>> x[0] in x.unique()
False
```

Hasn't changed on pandas master.

I haven't looked closely at the usage, but `x[0] in x.array.unique()` will always be True. However, `array` is new in 0.24.0, so that's likely not an option for seaborn's internals.
