### ISSUE TITLE
Catplot hue parameter incompatible with map function

### ISSUE THREAD

**Issue by kaisengit** [mwaskom/seaborn#1696]
I am not sure if the title really describes my problem well. What I am doing is I am plotting several observations of different variables with a catplot. I am also plotting the standard deviation of these observations. Since I want to plot the number of observations going into the standard deviation I am using  a custom map function. This works fine when not specifying the hue parameter. See my example code here:
```
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


def map_point(x,y, annot, **kwargs):
    zip_y_annotate = list(dict.fromkeys(zip(x,y,annot)))
    x_locs, x_labels = plt.xticks()
    x_labels = [t.get_text() for t in x_labels]
    x_label_loc_dict = dict(zip(x_labels, x_locs))
    x_unique = [e[0] for e in zip_y_annotate]
    y_unique =[e[1] for e in zip_y_annotate]
    annot_unique = [e[2] for e in zip_y_annotate]
    x_pos_valid = [x_label_loc_dict[n] for n in x_unique]
    zip_y_annotate = list(dict.fromkeys(zip(x_pos_valid, y_unique, annot_unique)))
    for x, y, annot in zip_y_annotate:
        plt.annotate(str(annot), xy=(x, y), fontsize=10,
                    color=kwargs.get("color", "k"),
                    bbox=dict(pad=.9, alpha=1, fc='w', color='none'),
                    va='center', ha='center', weight='bold')



ids = 'ABCD'
n_exp = 9
n_obs_max = 10



exp_list = []
id_list = []
for entry in ids:
    for exp in range(n_exp):
        for n in range(np.random.randint(1, n_obs_max+1)):
            id_list.append(entry)
            exp_list.append(exp)
                
vals_dict = {'id': id_list,
             'exp': exp_list,
            'val': np.random.normal(size=len(exp_list))}


df = pd.DataFrame.from_dict(vals_dict, orient='columns')

df['count'] = df.groupby(['exp', 'id'])['val'].transform('count')
df['mean'] = df.groupby(['exp', 'id'])['val'].transform('mean')

fg = sns.catplot(data=df, x='id', y='val', col='exp', kind='point',col_wrap=3, ci='sd', sharey=False, sharex=False)
fg.map(map_point, 'id', 'mean', 'count')

```
This will produce a figure like this: https://imgur.com/a/YefkY4M

As you can see, each point is labeled with the number of observations. Now when I add the hue parameter, i.e.
```
fg = sns.catplot(data=df, x='id', y='val', col='exp', kind='point', hue='exp',col_wrap=3, ci='sd', sharey=False, sharex=False)
fg.map(map_point, 'id', 'mean', 'count')
```
the plot will look like this: https://imgur.com/a/bMkS3oI
Now only the first three subplots are labeled correctly. Starting from the fourth, the labeling moves to the 'background', i.e. it is hidden beneath the lines and the points.
I am testing this inside a brand new conda environment using the most recent packages as of today:
```
matplotlib                3.0.2            py37h5429711_0  
numpy                     1.16.2           py37h7e9f1db_0  
numpy-base                1.16.2           py37hde5b4d6_0  
pandas                    0.24.1           py37he6710b0_0  
seaborn                   0.9.0                    py37_0  
```
The bug also exists when using older matplotlib packages (2.x.x).

**Comment by mwaskom** [comment]
I think you need to just specify a large zorder for your annotation text. `pointplot` increments the z order of each point/errorbar/join-line element when hue is used so they are plotted together, placing later ones above the default text zorder.

**Comment by kaisengit** [comment]
Thank you so much, this was indeed the problem!
