### ISSUE TITLE
DOI out of date

### ISSUE THREAD

**Issue by Phlya** [mwaskom/seaborn#1698]
Hi, the DOI seems to be out of date and points to the previous release, would it be possible to update it please? Thank you.

**Comment by mwaskom** [comment]
zenodo automatically generates a doi for each github release tag. you can always check zenodo.org, but they are also here: http://seaborn.pydata.org/whatsnew.html. so i am not certain what you are referring to?

**Comment by Phlya** [comment]
Right, sorry I wasn't clear. I meant the badge in readme.

**Comment by mwaskom** [comment]
Oh ok, thanks for catching that

**Comment by mwaskom** [comment]
Thanks, fixed in #1725
