### ISSUE TITLE
ZeroDivisionError if feature is missing for category

### ISSUE THREAD

**Issue by amueller** [mwaskom/seaborn#1699]
If a feature is NaN conditional on a particular category, there is a ZeroDivisionError from deep within statsmodels when making a pairplot (or probably any similar facet grid with a kde):

```python
import numpy as np
import seaborn as sns
sns.set(style="ticks")

df = sns.load_dataset("iris")
df.sepal_width[df.species == 'virginica'] = np.NaN
sns.pairplot(df, hue="species")
```
```
ZeroDivisionError: 0.0 cannot be raised to a negative power
```
It would be nicer if this category would just be left out.

**Comment by mwaskom** [comment]
Fixed in #1823
