### ISSUE TITLE
Using units in FacetGrid with lineplot

### ISSUE THREAD

**Issue by mbahin** [mwaskom/seaborn#1701]
I have a problem plotting lineplots in a FacetGrid from pandas DataFrame (using seaborn 0.9.0).

Here is a Minimal, Complete and Verifiable toy dataset for my problem:
```
genes = pd.Series(["Gene1"] * 16 + ["Gene2"] * 16)
conditions = pd.Series(np.tile(np.array(["Condition1"] * 8 + ["Condition2"] * 8), 2))
wellID = pd.Series(np.array(["W1"] * 4 + ["W2"] * 4 + ["W3"] * 4 + ["W4"] * 4 + ["W5"] * 4 + ["W6"] * 4 + ["W7"] * 4 + ["W8"] * 4))
fluo = pd.Series(np.array([np.sort(np.random.logistic(size=4)) for _ in range(8)]).flatten())
cycles = pd.Series(np.tile(np.array([0, 1, 2, 3]), 8))
df = pd.concat([genes, conditions, wellID, cycles, fluo], axis=1)
df.columns = ["Gene", "Condition", "WellID", "Cycle", "Fluo"]
```

It is composed of 2 genes for 2 conditions having each 2 replicates (1 replicate has 1 unique WellID for which there are 4 cycles, 1 measured fluo point per cycle).

I'm able to create the line plot I want isolating one gene with this command:
`sns.lineplot(x="Cycle", y="Fluo", hue="Condition", units="WellID", estimator=None, data=df.loc[df.Gene == "Gene1"])`

I had to use both units and estimator so that I can see the 2 replicates (and not an aggregated curve per Gene/Condition).

Finally, I wanted to use FacetGrid to see this plot for the 2 genes so I did:
```
g = sns.FacetGrid(df, col="Gene", hue="Condition", col_wrap=5)
g.map(sns.lineplot, "Cycle", "Fluo");
```

But then if I had the keywords "units" and "estimator", I have an error saying the "ValueError: Could not interpret input 'WellID'".

I could only display the plots with the 2 replicates aggregated.

**Comment by mwaskom** [comment]
Two quick answers:

1. You could use `FacetGrid.map_dataframe`.
2. You *should* use `relplot` with `kind="line"`.

**Comment by danyalmohammadi** [comment]
`relplot` works just fine in my case. Though, regarding _hue_, I get the following error when one of my columns is string: **AttributeError: 'int' object has no attribute 'view'**
I have tried to convert the whole column to `int`, then, my legend is missing one item and also not correct.
