### ISSUE TITLE
Too many decimal places in legend labs for relplot with hue or size keywords

### ISSUE THREAD

**Issue by mojones** [mwaskom/seaborn#1703]
I ran into this problem with a particular dataset. Calling `replot` with either `hue` or `size` causes extremely long labels in the legend because of what looks like floating point arithmetic in the labeling logic.

Example:

```python
test = pd.DataFrame({
 'foo' :[1,2,3,4,5,6,7],
 'bar' :[4,6,8,3,5,4,6],
    'baz':[0.4, 0.19, 0.35, 0.22, 0.35, 0.31, 0.09]
}
)
sns.relplot(
data=test.head(7),
x='foo',
y='bar',
size='baz')
```
![Selection_006](https://user-images.githubusercontent.com/893512/54830519-8b81b780-4cb0-11e9-8f35-3a531ace9f75.png)

Is there some way that the legend labels could be rounded or otherwise formatted to prevent this?

**Comment by mojones** [comment]
Glancing at other recent issues, I think this is related to https://github.com/mwaskom/seaborn/issues/1653

**Comment by mojones** [comment]
Workaround for anyone else who finds themselves looking at this:

```python
plot =sns.relplot(
data=test.head(7),
x='foo',
y='bar',
size='baz')

leg = plot._legend
for t in leg.texts:
    # truncate label text to 4 characters
    t.set_text(t.get_text()[:4])
```

**Comment by wwang-chcn** [comment]
same problem found on scatterplot
`test = pd.DataFrame({
    'foo': [1,1,1,1,1,
            2,2,2,2,2,
            3,3,3,3,3,],
    'bar': ['A', 'B', 'C', 'D', 'E'] * 3,
    'baz': [
        1.113724, 1.684478, 1.258712, 1.093084, 2.043681, 
        1.373130, 1.486539, 1.325999, 1.428729, 1.688664,
        1.325381, 1.345571, 1.304717, 1.366071, 1.454929]
})

ax = sns.scatterplot(
    x='foo',
    y='bar',
    size='baz',
    hue='baz',
    palette="YlOrRd",
    legend='brief',
    data=test)
ax.legend(loc='lower left',
          bbox_to_anchor=(1, 0),
          ncol=1)`
![Screen Shot 2019-12-17 at 3 28 57 PM](https://user-images.githubusercontent.com/5105121/70974104-f6e2a380-20e1-11ea-8470-95d43be22382.png)

python: 3.7.3
pandas: 0.25.3
matplotlib: 3.1.0
seaborn: 0.9.0

**Comment by asaji** [comment]
Problem still exists. Issue with the truncation fix as above is it shifts the legend rightward

![Screen Shot 2020-01-20 at 11 12 32 AM](https://user-images.githubusercontent.com/1782128/72741522-ce811580-3b75-11ea-846a-f0fd994df3ce.png)

**Comment by mwaskom** [comment]
Please add a reproducible example

**Comment by Izhaki** [comment]
Think I have a similar issue, but with xlabels not legend:

![image](https://user-images.githubusercontent.com/880132/100526532-939e3400-31c1-11eb-9d7c-cb8f6aa8aa15.png)


```python
import scipy.stats as st
import numpy as np
import seaborn as sns
import pandas as pd

params = np.linspace(0, 1, 6)

prob = [np.product(st.bernoulli.pmf(1, p)) for p in params]

print(params)

prior = pd.DataFrame(dict(x=params, Probability=prob))

ax = sns.barplot(
    data=prior, 
    x = "x", 
    y = "Probability",
    );

ax.set_xticklabels(params, rotation='vertical');   
```
