### ISSUE TITLE
Obtain the color of the categories as a dictionary  

### ISSUE THREAD

**Issue by baderAmmoun** [mwaskom/seaborn#1704]
I m  trying to know which color assign to which category and put them in dictionary to use them later  
I use following code to plot
`SInteractions_Graph = sns.swarmplot(x="KPI", y="value", hue="Platform", data=irisS)`
which produce the following chart
![chart](https://user-images.githubusercontent.com/33288847/54884849-0f38d100-4e76-11e9-821c-0bb0d1e71219.jpg)

is there way to do that ?

**Comment by mwaskom** [comment]
I'm not sure exactly what you're asking but as this is a "how to" question I'd recommend making a reproducible example and asking on StackOverflow, thanks!

**Comment by baderAmmoun** [comment]
thank you actually I've asked but I do not get the answer. so I tried here 
But any way I will rephrase what I'm trying to do 
 my aim is after I used hue parameter  to give the  data a color depending on  categories which in my example are  platforms. every platform has a color and this color have been chosen automatically .now I need to know what is a color for every platform in  run-time to use them later in my code
