### ISSUE TITLE
Kdeplot: incorrect bandwidth

### ISSUE THREAD

**Issue by Lijanas** [mwaskom/seaborn#1705]
Hello!
I have some problems with setting the  bandwidth in my KDE plots in Python.

In R, I get the following plot using the Epanechnikov Kernel and a bandwidth of 0.1:
`plot(density(y, bw=0.1, kernel ="epanechnikov"), col="red")`
![Rplot01](https://user-images.githubusercontent.com/48911472/54924278-4e196600-4f0c-11e9-9dfb-e561f11e4bb0.png)

However, if I use the function seaborn.kdeplot() in Python with the same kernel and bandwidth:
`sns.kdeplot(y,kernel = 'epa', bw = 0.1, color = 'red')`
I get a very different result:
![seaborn_kdeplot01](https://user-images.githubusercontent.com/48911472/54924287-52458380-4f0c-11e9-8e14-4c57fea615f6.png)

I use Python 3.7.0 with the packages seaborn 0.9.0, statsmodels 0.9.0 and scipy 1.2.0. As I want a different kernel than the gaussian kernel, seaborn has to compute the kernel with statsmodels, which should interpret the parameter of the bandwidth directly.
However, as you can see, it doesn't.

Any idea what is going on here?

**Comment by mwaskom** [comment]
Well as you note, statsmodels is doing all the computation. So the question would be, if you skip seaborn and fit/plot the density estimate from statsmodels directly, does it look like the R one?

**Comment by Lijanas** [comment]
No, it doesn't. I used the following code and I get just the same result as with the seaborn.function.

`from statsmodels.nonparametric.kde import kdensity` 
`density = kdensity(y, kernel='epa', bw=0.1)`
`plt.plot(density[1],density[0])`

![statsmodels_kdeplot01](https://user-images.githubusercontent.com/48911472/55004230-21cc1b00-4fda-11e9-8cf6-a3ce4755bf58.png)

In the documentation of the function, it says: 
bw : str, float
“scott” - 1.059 * A * nobs ** (-1/5.), where A is min(std(X),IQR/1.34) “silverman” - .9 * A * nobs ** (-1/5.), where A is min(std(X),IQR/1.34) If a float is given, it is the bandwidth.

Do I have to add some other Parameters?

**Comment by mwaskom** [comment]
I don't know really, but it sounds like a question for the statsmodels people.

**Comment by Lijanas** [comment]
Okay, nevertheless thank you.
