### ISSUE TITLE
windrose support

### ISSUE THREAD

**Issue by yt87** [mwaskom/seaborn#1706]
This is a feature enhancement suggestion.

I want to use FacetGrid to plot windroses (package from conda-forge). It almost works, here is my code:
```
def _windrose(wd, ws, **kws):
    ax = plt.gca()
    del kws['color']
    ax.bar(wd, ws, **kws)
    ax.set_legend(loc='lower left', borderaxespad=-4)
    
def plot_windrose(df, row, col, title=''):
    g = sns.FacetGrid(df, row, col, despine=False,
                      sharex=False, sharey=False, height=4,
                      subplot_kws=dict(projection='windrose'))
    g.map(_windrose, 'wdir', 'wspd', normed=True)
    g.fig.subplots_adjust(top=0.965)
    g.fig.suptitle(title, fontsize=15)
```
The only issue is that legend disappears. I solved it by modifying `axisgrid.py`:
```
$ diff axisgrid.py axisgrid.py.orig 
842,843c842
<         if ax.name != 'windrose':
<             self._clean_axis(ax)
---
>         self._clean_axis(ax)
```
I admit the above is not a clean solution. Is it worth consideration?

**Comment by mwaskom** [comment]
You don’t provide an example I can reproduce but what happens if you call `g.add_legend`? I general im not going to add in a special case for this, especially since properly testing it would require a new dependency on an external package.

**Comment by mwaskom** [comment]
Here's an example demonstrating that FacetGrid currently works with functions that add their own legend data, you just need to declare that you want a legend:

```python
def plot(x, y, **kwargs):
    plt.plot(x, y, label="a", **kwargs)
    kwargs["color"] = "k"
    plt.plot(x, y + 1, label="b", **kwargs)

df = sns.load_dataset("tips")
g = sns.FacetGrid(df, col="day")
g.map(plot, "size", "total_bill")
g.add_legend()
```
![image](https://user-images.githubusercontent.com/315810/55096592-9792be00-5090-11e9-848a-e7a1c576be34.png)


This assumes that the legend applies to all facets, which it really ought to, with a FacetGrid, but here's how you would add back your axes-specific legend:

```python
df = sns.load_dataset("tips")
g = sns.FacetGrid(df, col="day")
g.map(plot, "size", "total_bill")
for ax in g.axes.flat:
    ax.legend(loc="lower right")
```
![image](https://user-images.githubusercontent.com/315810/55096703-c14be500-5090-11e9-840c-5e0c16b9c525.png)


As far as I can tell, this solves your issue, so I am going to close.
