### ISSUE TITLE
Mapping onto catplot with kind=box does not center correctly

### ISSUE THREAD

**Issue by kaisengit** [mwaskom/seaborn#1709]
I have an issue with mapping additional information onto a catplot if its type is box (or boxen, violin). For example take my code and the map_point function from this issue report: https://github.com/mwaskom/seaborn/issues/1696

If I use the following code
```
fg = sns.catplot(data=df_var, x='exp', y='val', col='id', kind='point', col_wrap=3, ci='sd', sharey=False, sharex=False, hue='dom', legend=False)
fg.map(map_point, 'exp', 'mean', 'count')
fg.add_legend()
```
I get a nicely labelled catplot: https://imgur.com/a/Q0Bj2Fu
Notice how the labels are perfectly aligned.

Now using the same code but with `type='box'` I get this: https://imgur.com/a/puOSFkg
For some plots the labels are now either offset to the right or to the left.

Note that this is not a problem with my custom map function but a general issue. The same  thing happens when I try to map the underlying observations with a swarmplot: https://imgur.com/a/lBG07fv
Using this code: `fg.map(sns.swarmplot, 'exp', 'val',color=".1", order=sorted(df_var_dom['exp'].unique()))
`

**Comment by mwaskom** [comment]
I think you want `dodge=False`

**Comment by kaisengit** [comment]
That is a bit embarrassing, thank you!
