### ISSUE TITLE
Install seaborn on raspberry pi 3

### ISSUE THREAD

**Issue by cedricgrimault** [mwaskom/seaborn#1710]

**Comment by cedricgrimault** [comment]
Hello.

I am looking for a way to install seaborn on a raspberry pi 3
when i execute this command : 
`pip install seaborn`
I have this return
`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_UbIfb/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i8fh3k-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-_UbIfb/scipy/`



Thanks for your help

**Comment by mwaskom** [comment]
That error indicates you are having a problem installing scipy, which is a dependency of seaborn. Unfortunately, I wouldn’t have any insight into helping solve a problem with installing scipy on your system, sorry!

**Comment by cedricgrimault** [comment]
Hello

I contacted scipy who told me to use conda and not pip for the installation module.
so I executed :
`coda install seaborn` as indicated on the seaborn website
but i have this error message : 
`Error: No packages found in current linux-armv7l channels matching: seaborn`

do you have an idea to install seaborn on raspberry ?

Thanks

**Comment by cedricgrimault** [comment]
Hello.

I still have my installation problem.
Does somebody have an idea ?

Is it possible to delete the tag "Closed" from this ticket?

Thanks a lot for your help ?

**Comment by ixjlyons** [comment]
@cedricgrimault Have you checked if seaborn can be installed with apt? That would be the easiest thing to do if it is indeed being packaged for Raspbian (assuming that's what you're using). In any case, if you can get the dependencies installed (numpy, scipy, pandas, and matplotlib), then `pip install seaborn` should work. That goes for system site-packages or a conda environment. If you already have a conda environment with scipy and pandas installed, try installing seaborn with pip in that environment and see if that works.
