### ISSUE TITLE
xlim does not work properly on kdeplot when used on Facetgrid

### ISSUE THREAD

**Issue by felix-r** [mwaskom/seaborn#1714]
I'm trying to do rigdeline plots like described in this example: https://seaborn.pydata.org/examples/kde_ridgeplot.html 

However, when I try to crop the output with the xlim argument, still the complete kdeplot is drawn and just the axes are cut. This does not happen if I use distplot.

Here my code:

```
#seaborn example
sns.set(style="white", rc={"axes.facecolor": (0, 0, 0, 0)})

# Create the data
rs = np.random.RandomState(1979)
x = rs.randn(500)
g = np.tile(list("ABCDEFGHIJ"), 50)
df = pd.DataFrame(dict(x=x, g=g))
m = df.g.map(ord)
df["x"] += m

# Initialize the FacetGrid object
pal = sns.cubehelix_palette(10, rot=-.25, light=.7)
g = sns.FacetGrid(df, row="g", hue="g", aspect=15, height=.5, palette=pal, xlim=[64,74])

# Draw the densities in a few steps
g.map(sns.kdeplot, "x", clip_on=False, shade=True, alpha=1, lw=1.5, bw=.2)
g.map(sns.kdeplot, "x", clip_on=False, color="w", lw=2, bw=.2)
g.map(plt.axhline, y=0, lw=2, clip_on=False)


# Define and use a simple function to label the plot in axes coordinates
def label(x, color, label):
    ax = plt.gca()
    ax.text(0, .2, label, fontweight="bold", color=color,
            ha="left", va="center", transform=ax.transAxes)

g.map(label, "x")

# Set the subplots to overlap
g.fig.subplots_adjust(hspace=-.25)

# Remove axes details that don't play well with overlap
g.set_titles("")
g.set(yticks=[])
g.despine(bottom=True, left=True)
```
And the output:
![image](https://user-images.githubusercontent.com/19806005/55637361-23a99180-57c5-11e9-881e-91d20b1d37bc.png)

So, the plot should not extend the limits set by xlim but it does. This also happens when I use `g.set(xlim=[64,74])` or set the xlim for the axes individually. 

When I use distplot, instead of kdeplot, I get the following result:
![image](https://user-images.githubusercontent.com/19806005/55637665-e0035780-57c5-11e9-992f-5a85486915f0.png)

OS: Windows10, matplotlib: 3.0.2., seaborn: 0.9.0

**Comment by mwaskom** [comment]
> However, when I try to crop the output with the xlim argument, still the complete kdeplot is drawn and just the axes are cut. This does not happen if I use distplot.

This is expected because of the parameter `clip_on=False`, which shows the plot artists even when they are outside of the axes limits.

**Comment by felix-r** [comment]
Ok, with `clip_on=True` it does what I want. Sorry, my bad.
