### ISSUE TITLE
Disable tight_layout for matplotlib's constrained_layout

### ISSUE THREAD

**Issue by jkrumbiegel** [mwaskom/seaborn#1715]
With facet grids, titles and labels often overlap with each other and have to be manually adjusted using plt.subplots_adjust, basically trying out values until it kind of works. Matplotlib has an (experimental) constrained layout feature which solves these problems. But it gets disabled anytime a tight_layout command is issued. So for it to work with seaborn, I think either tight_layout should be an optional parameter there, or matplotlib needs to disable the disabling of constrained_layout when tight_layout is called. Constrained layout would also be useful for placing margin titles correctly.

**Comment by mwaskom** [comment]
Thanks for bringing this up. Since constrained layout is only available on the latest versions of matplotlib (and is an experimental feature), seaborn cannot use it. For the time being, then, I think `FacetGrid` will continue to use `tight_layout`.
