### ISSUE TITLE
[Feature request]: support FacetGrid.set with function that takes each ax as argument

### ISSUE THREAD

**Issue by zuoxingdong** [mwaskom/seaborn#1717]
As an example of use case:

```python
g.func_set(lambda ax: ax.xaxis.set_tick_formatter(....))
```

**Comment by mwaskom** [comment]
Is this much more useful that looping over `g.axes.flat`?

**Comment by mwaskom** [comment]
My feeling is that needing to use a lambda function makes this cumbersome enough that it doesn't really have advantages of convenience over a more explicit `for` loop, thanks for the suggestion though.
