### ISSUE TITLE
[Feature request][heatmap] Options to add images/plots in the annotation arg of heatmap

### ISSUE THREAD

**Issue by backpropper** [mwaskom/seaborn#1719]
The heatmap in the current state works perfectly. But if there is a way if we can add images or histograms in each cell of the heatmap would actually make it even more informative. Many times, the annotation you want is not a number or a string, so it would be great if we can specify a list/array of custom images/matplotlib plots to be displayed in each cell.

**Comment by mwaskom** [comment]
I'm not sure exactly what you're looking for, but you can certainly layer additional images or plots on to of the heatmap seaborn gives you using normal matplotlib commands (it returns the axes). That's likely your best bet for super customized figures.

**Comment by backpropper** [comment]
A heatmap consists of multiple cells which are colored based on some range of values.
So what I am saying is that is there an option to display a histogram/figure in the middle of each cell of the heatmap? Is it possible using the `annot` argument in the heatmap function?
If not, I would need access to the axis of each cell in the heatmap, is it possible to do so?

**Comment by mwaskom** [comment]
No there is not a separate set of axes per cell in the heat map. The whole thing is drawn on one set of axes.

**Comment by backpropper** [comment]
thanks I figured it out!
