### ISSUE TITLE
Please keep support for passing a 2D dataset for a bivariate plot

### ISSUE THREAD

**Issue by dburkhardt** [mwaskom/seaborn#1721]
In reference to: https://github.com/mwaskom/seaborn/blob/36964d7ffba3683de2117d25f224f8ebef015298/seaborn/distributions.py#L676

Before it's too late, I want to advocate in support of passing a 2D dataset to a bivariate plot. I use this functionality when I'm using the `kdeplot` function as an alternative to a scatter plot. Often I'm working with visualizations of high dimensional datasets in two dimensions. Being able to pass the dataframe containing the dimensionality reduced data to `kdeplot` is super handy. My lab members and I use `kdeplot` and related functions in this way on an almost daily basis.

In fact, when we assembled [a set of plotting functions for biomedical data analysis in our package, `scprep`](https://github.com/KrishnaswamyLab/scprep/tree/master/scprep/plot), we were inspired by this functionality. When we wrote a scatter2d method, it was seaborn that we wanted to imitate.

I tried to find a discussion thread on why this will no longer be supported, but couldn't. Is there a strong reason the functionality will be removed?

I hope you will please reconsider deprecating this useful feature of seaborn functions.

Best,
Dan

**Comment by mwaskom** [comment]
Yes the deprecation is necessary for achieving API consistency across the different functions in the library.

**Comment by mwaskom** [comment]
Sorry if it inconveniences you, but the ship has sailed.
