### ISSUE TITLE
Lineplot excludes x-axis positions with NaN values

### ISSUE THREAD

**Issue by adamerose** [mwaskom/seaborn#1724]
When plotting with sns.lineplot x-axis positions with NaN values get removed, I don't think this is intended behavior? This doesn't happen with sns.pointplot

Example:
![image](https://user-images.githubusercontent.com/10884874/56016359-f3cd2300-5cc9-11e9-92fc-99e7f1055e03.png)

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.close('all')

# Generate example data
x = pd.date_range('2018-01-01','2018-03-01',freq='D').strftime('%Y-%U')
df1 = pd.DataFrame({'x': x, 'y1': [np.nan]*10+list(np.arange(len(x)-10))})
df2 = pd.DataFrame({'x': x, 'y2': [np.nan]*20+list(np.arange(len(x)-20))})

# Pointplot
fig, axes = plt.subplots(2, sharex='all')
fig.suptitle("Pointplot")
ax1, ax2 = axes

sns.barplot(df1['x'], df1['y1'], ax=ax1)
sns.pointplot(df2['x'], df2['y2'], ax=ax2)

# Lineplot
fig, axes = plt.subplots(2, sharex='all')
fig.suptitle("Lineplot")
ax1, ax2 = axes

sns.barplot(df1['x'], df1['y1'], ax=ax1)
sns.lineplot(df2['x'], df2['y2'], ax=ax2)

# Lineplot individual
plt.figure()
sns.lineplot(df2['x'], df2['y2'])
```

**Comment by mwaskom** [comment]
In general, sharing axes between a categorical plot and a relational plot like this is not expected to work.

**Comment by lsiqueirap** [comment]
Plotting two subplots of time-series that share the same x axis won’t work if one of it has NaN values at the beginning or at the end as well. The problem is not sharing axes between categorical and relational plot, but rather the lineplots ignoring NaN values at start/end.

**Comment by mwaskom** [comment]
@lsiqueirap if you have a different issue please provide a reproducible example.  A casual description is not helpful.
