### ISSUE TITLE
Heatmap with center, cmap and mask does not respect cmap.set_bad color

### ISSUE THREAD

**Issue by emilmelnikov** [mwaskom/seaborn#1729]
I want to display some data with a custom center and a custom mask color. However, `center`, `cmap` and `mask` together drop some cmap properties that one can set with `cmap.set_bad` for bad/missing data.

It seems like `_HeatMapper` creates another cmap from the colors of the passed cmap when center is specified: https://github.com/mwaskom/seaborn/blob/b9551aff1e2b020542a5fb610fec468b69b87c6e/seaborn/matrix.py#L230

Demo:
```python
import matplotlib as mpl
import numpy as np
import seaborn as sns


np.random.seed(42)
sns.set(rc={"figure.figsize": (12, 9)})
fig, (ax1, ax2) = mpl.pyplot.subplots(nrows=1, ncols=2)
cmap = mpl.cm.get_cmap("BrBG")
cmap.set_bad("black")

corr = np.corrcoef(np.random.randn(10, 200))
mask = np.zeros_like(corr)
mask[np.triu_indices_from(mask)] = True

heatmap_kwargs = dict(mask=mask, vmin=-0.3, vmax=0.3, square=True, cmap=cmap)
sns.heatmap(corr, ax=ax1, **heatmap_kwargs)
sns.heatmap(corr, ax=ax2, center=0.0, **heatmap_kwargs)

fig.savefig("mwe.png")
```

![mwe](https://user-images.githubusercontent.com/1649961/56371121-ce29a780-61fc-11e9-969c-2b24fc31a4fc.png)

**Comment by mwaskom** [comment]
Hi — good catch, yes, I think that it needs to propagate over the colormap metadata if a colormap object is passed to `cmap`.

**Comment by emilmelnikov** [comment]
> I think that it needs to propagate over the colormap metadata if a colormap object is passed to `cmap`.

I actually wanted to submit a patch right away, but [the colormap metadata is underscore-private](
https://github.com/matplotlib/matplotlib/blob/3ba7b1994f60720f343e3863dd1b24c574cd8351/lib/matplotlib/colors.py#L424).

Do you think it's OK to just use them anyway? I suppose we could also ask for corresponding changes in the matplotlib cmap API.

**Comment by mwaskom** [comment]
No, we shouldn't use private attributes. However, if they're not publicly exposed, it should be possible to work them out by sending in bad, under, and over values and seeing what comes back.

But while the "bad" values are straightforward, it's very unclear what to set the over- and under- values to when the colormap is getting clipped....
