### ISSUE TITLE
color kwarg must have one color per data set. 272242 data sets and 1 colors were provided

### ISSUE THREAD

**Issue by conego** [mwaskom/seaborn#1730]
Hi, 
i dont understand why Seaborn dont plot my data. How i can set the color for all data sets? I thoght Seaborn will do it by itself.

Heres my Code:

%matplotlib inline
import seaborn as sns
sns.set()
g = sns.pairplot(df)

Thanks for Help

regards

**Comment by mwaskom** [comment]
Sorry, I can't help without knowing anything about your data set. I would encourage you to generate a reproducible example and ask on stackoverflow.
