### ISSUE TITLE
Feature request: Radar-boxplot

### ISSUE THREAD

**Issue by caiohamamura** [mwaskom/seaborn#1731]
I was wondering if it would be possible to merge my project inside seaborn, the [radar-boxplot](https://github.com/caiohamamura/radarboxplot-python). I've created this new concept of plot called radar-boxplot which is great for visualizing multivariate classification/clustering data. 

I think both projects could benefit, since I have neither the visibility nor the art skills you guys have to create such beautiful plots with high quality code, whereas the [radar-boxplot](https://github.com/caiohamamura/radarboxplot-python) is a really novel charting concept which could very much benefit the scientific community.

There goes a sample of radar-boxplot:
![Radar-boxplot example with iris](https://github.com/caiohamamura/radarboxplot-python/raw/master/tests/radarboxplot.png?raw=true)

**Comment by mwaskom** [comment]
Hi — thanks for your interest. I think this would not currently be a great fit for an addition to seaborn, but if it's based on matplotlib than you should be able to seamlessly integrate the seaborn style control if that's something you're interested in doing ... seaborn functional (can) change the appearance of all matplotlib plots, not just those drawn by seaborn itself.
