### ISSUE TITLE
Lineplot axes labels

### ISSUE THREAD

**Issue by ggydush** [mwaskom/seaborn#1732]
Using Seaborn 0.9.0, I'm having issues grabbing the axes labels with `sns.lineplot`. The correct number of labels is returned, but the positions are 0 and the text is an empty string.

Here's an example:
```python
test_df = pd.DataFrame({'x': range(0, 10), 'y': range(0, 10)})
g = sns.lineplot(x='x', y='y', data=test_df)
print(list(g.get_xticklabels()))
```
```
[Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, '')]
```

**Comment by mwaskom** [comment]
This is more of a matplotlib lib thing than a seaborn thing:

```python
test_df = pd.DataFrame({'x': range(0, 10), 'y': range(0, 10)})
f, ax = plt.subplots()
ax.plot(test_df["x"], test_df["y"])
print(list(ax.get_yticklabels()))
```
```
[Text(0,0,''), Text(0,0,''), Text(0,0,''), Text(0,0,''), Text(0,0,''), Text(0,0,''), Text(0,0,'')]
```

Broadly, the explanation is that the ticks and their labels aren't assigned until the plot is drawn. You can get them if you force that to happen:

```python
test_df = pd.DataFrame({'x': range(0, 10), 'y': range(0, 10)})
ax = sns.lineplot(x='x', y='y', data=test_df, ci=None)
ax.figure.canvas.draw()
print(list(ax.get_yticklabels()))
```
```
[Text(0,-2,'−2'), Text(0,0,'0'), Text(0,2,'2'), Text(0,4,'4'), Text(0,6,'6'), Text(0,8,'8'), Text(0,10,'10')]
```

**Comment by ggydush** [comment]
It's interesting that using pointplot and other seaborn functions results in the text labels showing up, but understand the limitation! Thanks for the quick response and suggestion!
```python
test_df = pd.DataFrame({'x': range(0, 10), 'y': range(0, 10)})
g = sns.pointplot(x='x', y='y', data=test_df)
print(list(g.get_xticklabels()))
```
```[Text(0, 0, '0'), Text(0, 0, '1'), Text(0, 0, '2'), Text(0, 0, '3'), Text(0, 0, '4'), Text(0, 0, '5'), Text(0, 0, '6'), Text(0, 0, '7'), Text(0, 0, '8'), Text(0, 0, '9')]```

**Comment by mwaskom** [comment]
The difference is that the categorical plots are explicitly setting the tick labels (because the ticks are just drawn at integer positions and then labeled with the category names) whereas the relational plots pass the data through to matplotlib and don't mess with the ticking, meaning that things like dates get properly-formatted labels.
