### ISSUE TITLE
set_style should not over-ride user's font list

### ISSUE THREAD

**Issue by baloe** [mwaskom/seaborn#1733]
I have project-specific configurations in a matplotlibrc file.
I like using seaborn for data visualization and also `sns.set_style("darkgrid")` to get the corresponding aesthetics, but I don't understand why this call changes my font list.

I know, I could do
```
sns.set_style("darkgrid", {'font.sans-serif':'Open Sans'})
```
or even
```
from matplotlib import rcParams
sns.set_style("darkgrid", {'font.sans-serif':rcParams['font.sans-serif']})
```
but these are dirty workarounds.
The former approach has me redundantly specify the font in every single script instead of just respecting the setting made in the project-wide matplotlibrc file while the second approach blows up my code.

Why not just respect the list of fonts provided by matplotlib's `rcParams`? 
If you really can't help imposing your own list of fonts then please provide the option to have a seaborn-specific configuration file like matplotlibrc.

**Comment by mwaskom** [comment]
The fonts are part of the style. If you don't want seaborn's choices applied, then don't call the seaborn `set_style` function...
