### ISSUE TITLE
hexbin plot, PolyCollection and inconsistent facecolor values

### ISSUE THREAD

**Issue by nberliner** [mwaskom/seaborn#1734]
I am trying to change the edgecolor of some hexbin patches in a hexbin plot in a JointGrid. Fiddling around with it to understand how this could work, I encountered a behaviour I cannot understand.

Calling `get_facecolors()` on the underlying PolyCollection returns different results depending on the jupyter notebook cell within which the call is made.

Here's my example (assuming the code is run in a notebook)
```python
import matplotlib
import matplotlib.pyplot as plt

import numpy as np
import seaborn as sns
```

```python
# Define some dummy data
x = np.array([1,1,1,1.5,1.5,2])
y = np.array([1,1,1,1,1,1])
```

```python
g = sns.JointGrid(x=x, y=y, xlim=(1,2), ylim=(0,2))

g = g.plot_joint(plt.hexbin, C=np.ones(x.shape), reduce_C_function=np.sum, extent=[1, 2, 0.5, 1.5],
                 gridsize=3, linewidths=1, edgecolors='face')

# Get the PolyCollection of hexbin patches
polycollection = g.ax_joint.get_children()[0]
assert isinstance(polycollection, matplotlib.collections.PolyCollection)

# I would expect the result to be an array of shape (3,4) but am getting (1,4)
print(polycollection.get_facecolors())
```
Running the above prints a ```(1,4)``` array. In my case it is
```[[0.12156863 0.46666667 0.70588235 1.        ]]```

There are three patches created (and plotted in the figure in the notebook) and I would have expected this to be an array of shape ```(3,4)```.

Surprisingly, when I print the result again in the next notebook cell,
```python
print(polycollection.get_facecolors())
```
the result is as expected of shape ```(3,4)```. In my case it is,
```
[[0.993248 0.906157 0.143936 1.      ]
 [0.127568 0.566949 0.550556 1.      ]
 [0.267004 0.004874 0.329415 1.      ]]
```

What am I missing here?

**Comment by mwaskom** [comment]
I'm not sure, sorry, but this seems like more of a matplotlib question?

**Comment by nberliner** [comment]
Thanks for your quick reply! I get the same issue just using plt.hexbin (should have checked that right away, sorry!) and sent an email to the matplotlib mailinglist.

**Comment by nberliner** [comment]
Just a quick update in case somebody else has a similar problem. It is indeed a matplotlib thing. I needed to call plt.draw() within the Jupyter Notebook cell to populate the polycollection, that is, directly after the g.plot_joint() call and before accessing the polycollection.
