### ISSUE TITLE
AttributeError: module 'seaborn' has no attribute 'scatterplot'

### ISSUE THREAD

**Issue by sheikita** [mwaskom/seaborn#1735]
Hi There,

I was trying to create a scatter plot in Jupyter Notebook.

m = sns.scatterplot(x="WeightLB", y="HeightIn", data=data)

But I am getting the below error. 

![Screen Shot 2019-04-30 at 6 11 31 PM](https://user-images.githubusercontent.com/39015205/57002324-63b92580-6b73-11e9-8961-09d1c3606eec.png)

Thanks!
Sheila

**Comment by mwaskom** [comment]
Almost certainly you are using a version that predates the introduction of that function.

**Comment by praveen-somineni** [comment]
You could try like plotting Reg plot and set fit_reg to false
sns.regplot(x=data["WeightLB"], y=data["HeightIn"], fit_reg=False);

**Comment by wolfiex** [comment]
> Almost certainly you are using a version that predates the introduction of that function.

Yes, but what do you call a scatter plot in previous sns versions?

**Comment by nine-na** [comment]
lineplot is the new scatterplot

**Comment by wolfiex** [comment]
> lineplot is the new scatterplot

Yes but a **line**plot is not a **scatter**plot. That is the problem. There should atleast be a wrapper to provide consistency with the visualisation world.

**Comment by vivekkathula** [comment]
try this 
sns.relplot(x="WeightLB", y="HeightIn", data=data)

**Comment by mwaskom** [comment]
> Yes, but what do you call a scatter plot in previous sns versions?

There was no explicit scatter plot function prior to v0.9.0. As @praveen-somineni suggests. It was possible to draw a scatter plot via `regplot` or `lmplot` with `fit_reg=False`.
