### ISSUE TITLE
catplot crashes when specifying `kind = 'point'`

### ISSUE THREAD

**Issue by francescolosterzo** [mwaskom/seaborn#1737]
I am trying to make a catplot to compare some data with different categorisations.
```
sb.catplot(x='var1', y='var2', hue='id', col='var3', kind='point', data=df_dummy)
```

but I get this error (after a long Traceback):
```
ValueError: 'c' argument has 4 elements, which is not acceptable for use with 'x' with size 0, 'y' with size 0.
```
`var3` has 2 values, so 2 different graphs should come out. The first one is done, the second one appears empty because of the crash.

What I do not understand is the following:
* if I remove the `col` argument, the plot is done with no problems
* if I plot the subsamples corresponding to the two values of `var3` separately, the plots are made with no errors
* if I remove the `kind='point'` argument, the plot is done with no errors (but of course also with no lines connecting the dots, which is what I want).

I am using:
* python 3.7.2
* matplotlib 3.0.3 with backend: module://ipykernel.pylab.backend_inline
* seaborn 0.9.0

here is the full script, including random data generation:
```
import random
import matplotlib.pyplot as plt
import seaborn as sb
import pandas as pd

### generate data
df_dummy = pd.DataFrame()

df_dummy = df_dummy.assign(id = None)
df_dummy = df_dummy.assign(var1 = None)
df_dummy = df_dummy.assign(var2 = None)
df_dummy = df_dummy.assign(var3 = None)

rowcount = 0
idd = 0
for i in range(10):
    for ii in range(4):
        
        var3 = 0
        if idd >=5: var3 = 1
            
        df_dummy.at[rowcount, 'id'] = idd
        df_dummy.at[rowcount, 'var1'] = ii
        df_dummy.at[rowcount, 'var2'] = random.random()
        df_dummy.at[rowcount, 'var3'] = var3
        
    
        rowcount += 1
    idd += 1

### plot
_ = sb.catplot(x='var1', y='var2', hue='id', col='var3', kind='point', data=df_dummy)
```

**Comment by mwaskom** [comment]
The short answer is that matplotlib has introduced a very annoying change that breaks seaborn. My suggestion for now would be to downgrade matplotlib.

**Comment by francescolosterzo** [comment]
to what version?

**Comment by mwaskom** [comment]
I don't know exactly when it was introduced because it pops up sporadically, but I just ran your code without issue on my local setup, which has matplotlib 2.2.

**Comment by mwaskom** [comment]
Having tracked it down a bit I opened a matplotlib issue (https://github.com/matplotlib/matplotlib/issues/14113) but anticipate it will not be welcomed.

As a note for when I have time to implement a change in seaborn, this specific issue can be handled by passing a list of nans rather than an empty list.

**Comment by mwaskom** [comment]
As predicted, trying to get this resolved upstream was a waste of time, so it's just gonna be broken for a while, sorry.
