### ISSUE TITLE
"cannot label index with a null key"

### ISSUE THREAD

**Issue by amlarraz** [mwaskom/seaborn#1739]
Hi,

I had this error when I tried to plot a catplot with my own dataframe (loaded using pandas) using this code:
 ´´´
sns.factorplot(x="column1",y="column2", data=dataset, kind="bar", size = 6, palette = "muted")
´´´
 The error was so weird because if I use **the same code** to draw other dataframe (also using pandas) everything was ok. (FYI the another dataset was the Kaggle Titanic dataset)

So, I've encountered a provisional solution, I've changed the file: 
[https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py](https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py
)
I've replaced lines 145-149:
```
if data is not None:
    x = data.get(x, x)
    y = data.get(y, y)
    hue = data.get(hue, hue)
    units = data.get(units, units)
```
for these other:
```
if data is not None:
    x = data.get(x, x)
    y = data.get(y, y)
    if hue is not None:
        hue = data.get([hue, hue])
   else:
        hue = data.get(hue, hue)
   if units is not None:
        units = data.get([units, units])
   else:
        units = data.get(units, units)
```
I think the base problem Is my dataframe (because all working perfectly using the Titanic dataset) and I know my solution is not elegant, but, someone has another solution??

**Comment by mwaskom** [comment]
Hi, without knowing anything about your dataset it's really impossible to answer, sorry.

**Comment by mwalmsley** [comment]
I had the same problem - for me, this was triggered by trying to use a Dataframe with duplicate columns. Removing the duplicated columns resolved the issue. An explicit check for duplicate columns in Seaborn would be helpful, but probably our job...

**Comment by mwaskom** [comment]
Agreed — when seaborn says it accepts tidy data, that means that surprising things might happen if your dataframe is malformed.
