### ISSUE TITLE
boxplot, catplot, and estimator

### ISSUE THREAD

**Issue by mfenner1** [mwaskom/seaborn#1741]
The following behavior was unexpected for me (seaborn 0.9.0 and matplotlib 2.2.3).  My apologies if I missed some relevant documentation.

```
# setup code
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
tips = sns.load_dataset("tips")
```

```python
sns.barplot(x="day", y="tip", data=tips)
sns.barplot(x="day", y="tip", data=tips, estimator=np.median);
```
As expected, these produced two slightly different graphics using mean for one and median for the other.

```python
sns.boxplot(x="day", y="tip", data=tips, ax=axes[0]);
```

`boxplot` doesn't take `estimator=` so only a median graphic (as expected).

```python
sns.catplot(x="day", y="tip", data=tips, ax=axes[0], kind='box');
# catplot does take estimator ... but ignores it for kind='box'
sns.catplot(x="day", y="tip", data=tips, ax=axes[1], kind='box',
            estimator=np.median);
```
Unexpected:  both calls produce the same figure (using the median as estimate of center).  The call to `boxplot` in `seaborn/categorical.py` passes on `kwargs`, but the matplotlib call for boxplot seems to rely on `usermedians` for alternative centers (I haven't drawn boxplots with `matplotlib` for some time -- I thought it used to take an `estimator=` arg, but I could be wrong). The first call was particularly unexpected because `catplot` has a default argument of `estimator=np.mean`.

So, a few quick thoughts/questions:

1.  I agree with generally using medians and quartiles for these types of graphics.  But, I recently had a need to use the mean.  Could/should `sns.boxplot` provide a way to specify alternative estimate of center?  Then there would a natural argument for `catplot(kind='box')` to pass to.
2.  Perhaps the docs for `catplot` need to provide a bit more detail on how `estimator` is handled?  I'm not sure what to say there, because `catplot` is front-ending a number of other routines.

One follow-on:  I get the distinction seaborn is making between drawing distributions and drawing estimations (as noted in the tutorial for catplot/categoricals).  But, I would propose that while a mean and sd based boxplot is drawing estimations, in a domain with a strong enough claim to normality, the boxplot would be drawing a theoretical (but not necessarily empirical) distribution for that data.  

My handwaving aside, the crux of the matter is the follow question:  what is the recommended course of action for a user that wants to draw a boxplot using mean/sd (or other alternatives) to median/IQR?

Best,
Mark

**Comment by mwaskom** [comment]
> The crux of the matter is the follow question: what is the recommended course of action for a user that wants to draw a boxplot using mean/sd (or other alternatives) to median/IQR?

My response is that this basically would not be a boxplot. That boxplots are a nonparametric visualization — they show data values by plotting the quartiles and through the definition of the whiskers — is central to the definition. There are other ways in seaborn to plot the mean and standard deviation of data; you are welcome to do that, but I am not going to make changes to support using a box glyph to show parametric statistics.

**Comment by mfenner1** [comment]
That's completely fair.  So, if you were personally drawing a box glyph using a center and spread, would you hand spin it from  matplotlib or are there some tools you would leverage from seaborn?
