### ISSUE TITLE
Another example of LinAlgError: singular matrix

### ISSUE THREAD

**Issue by julianofischer** [mwaskom/seaborn#1745]
```
import seaborn as sns
import pandas as pd
df = pd.read_csv('KNN_Project_Data')
sns.pairplot(data=df, hue='TARGET CLASS')
```

I'm sure it is related to #1502 Sorry about that.
However, I can't comment on this issue and I would like to let you know about another failing example.

Thank you for your attention.
[KNN_Project_Data.txt](https://github.com/mwaskom/seaborn/files/3199163/KNN_Project_Data.txt)

**Comment by mwaskom** [comment]
Thanks, but the issue is locked because it's not helpful at this point to collect additional examples of the problem. The cause is understood, the limiting factor is effort in fixing it.
