### ISSUE TITLE
scateerplot ValueError: 'vertices' must be a 2D list or array with shape Nx2

### ISSUE THREAD

**Issue by kadereub** [mwaskom/seaborn#1749]
I think the requirements for the `matplotlib` version needs to be more recent. 

With `matplotlib 2.0.2`  I get the above ValueError when using the `type` parameter in `seaborn.scatterplot`. I upgraded to `matplotlib 3.1.0` and obviously it worked fine. 

Might be worth changing the [install requirements version](https://github.com/mwaskom/seaborn/blob/master/setup.py#L35)

Please see the below SO thread:
https://stackoverflow.com/questions/56282933/seaborn-valueerror-vertices-must-be-a-2d-list-or-array-with-shape-nx2

**Comment by mwaskom** [comment]
Seaborn is tested on the minimally supported version; this may be a bug in a specific version of matplotlib.
