### ISSUE TITLE
Wrong calcul of max of boxplot

### ISSUE THREAD

**Issue by k-sartor** [mwaskom/seaborn#1750]
Hi,
i think there is an issue in the calculs of whisker in box plot.
Normally, the maximum is defined as quartile 3 + IQR *1.5 (1.5 is the default value).
As it can be seen on this figure, the length between Q3 and maximum is shorter:
![Boxplot](https://user-images.githubusercontent.com/14309962/58447578-1cd43680-8105-11e9-88bf-af32c8b3d160.png)
especially for hour 9

Here are the maximum calculed by Q3+1.5*IQR:
Hour	Debit ValueY
0	34.77648407321753
1	28.53732592509024
2	27.113185895194043
3	27.04537429772117
4	27.813966516245515
5	32.71936640060918
6	47.141758103000925
7	82.5195333793998
8	94.1162324627708
9	120.99426707468407
10	109.71409017373654
11	101.50825203350631
12	95.58556659521659
13	102.8645955099278
14	87.47016178361913
15	90.11500922269852
16	87.99010793377707
17	69.72474873646212
18	60.00434577222474
19	55.844901283280684
20	58.919274393614614
21	53.42611465478341
22	49.51536783619137
23	42.57540109149362

**Comment by mwaskom** [comment]
That’s not quite right. The whiskers extend to the most extreme data point within that range, not to the end of the range itself.
