### ISSUE TITLE
fontsize of relplot legend can't be specified.

### ISSUE THREAD

**Issue by kusanagee** [mwaskom/seaborn#1751]
Unlike most matplotlib legends, one cannot adjust the fontsize of the seaborn.relplot facetgrid's legend.

Per the advice in the accepted answer to [How can I change the font size using seaborn FacetGrid?](https://stackoverflow.com/questions/56013313/legend-size-marker-in-relplot-seaborn), I tried:
```
fg = sns.relplot(data=df, kind='line', x='Time', y=signal, hue='role', style='subsignal', dashes=True, linewidth=.5, alpha=.75, ax=None, ci='sd')
plt.setp(fg._legend.get_title(), fontsize=6)
plt.show()
```

But it didn't change the fontsize in the legend. 

It'd be great if one could access and manipulate properties of a matplotlib-legend object from FacetGrid, or if FacetGrid's legend provided deterministically set-able properties like fontsize.

**Comment by MaozGelbart** [comment]
Hi @kusanagee ,

In matplotlib, parameters of visual features may be tweaked by updating the [rcParams](https://matplotlib.org/users/customizing.html#matplotlib-rcparams) dictionary, dictating the appearance of many visual parameters. With seaborn you can update the [plotting context](https://seaborn.pydata.org/generated/seaborn.plotting_context.html) to have the desired legend fontsize just before creating the relplot, see this example:
```python
import seaborn as sns
import matplotlib.pyplot as plt

df=sns.load_dataset("fmri")
with sns.plotting_context(rc={"legend.fontsize":6}):
    g = sns.relplot(data=df, kind='line', x='timepoint', y="signal", hue='event')
    plt.show()
```
I hope this helps.

**Comment by mwaskom** [comment]
Thanks @MaozGelbart
