### ISSUE TITLE
rows/cols of the annotation dataframe are not ordered in clustermap

### ISSUE THREAD

**Issue by gokceneraslan** [mwaskom/seaborn#1752]
I'm trying to annotate a clustermap but seaborn doesn't apply the row/column reordering of the data matrix to the annotation dataframe. 

So I reorder the annotation dataframe myself in a second clustermap call, but there is something wrong:

```python
cm = sns.clustermap(overlap, standard_scale=1, cmap='Reds')
overlap = overlap.iloc[cm.dendrogram_row.reordered_ind, 
                       cm.dendrogram_col.reordered_ind]
sns.clustermap(overlap, standard_scale=1, cmap='Reds', annot=overlap)
```

Here is the output:

![image](https://user-images.githubusercontent.com/1140359/58598878-01c00e80-824c-11e9-874b-ffd2af0df204.png)

Zeros at the bottom right corner do not look correct. Any suggestions? 

Wouldn't it be easier to just reorder rows/cols of the annotation df based on the indices of the data matrix?

**Comment by mwaskom** [comment]
`annot` is not part of the `clustermap` api. It "works" because kwargs are passed through to `heatmap`, but this behavior is not unexpected, if unfortunate. Sorry.

**Comment by gokceneraslan** [comment]
OK, I see. Then would it make sense to keep the bug open as a feature request so that someone can fix it at some point?
