### ISSUE TITLE
FacetGrid produces unremovable borders

### ISSUE THREAD

**Issue by TheChymera** [mwaskom/seaborn#1754]
From [an official example](https://seaborn.pydata.org/examples/kde_ridgeplot.html):

With this script

```
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl

with plt.style.context('style.conf'):

        # Create the data
        rs = np.random.RandomState(1979)
        x = rs.randn(500)
        g = np.tile(list("ABCDEFGHIJ"), 50)
        df = pd.DataFrame(dict(x=x, g=g))
        m = df.g.map(ord)
        df["x"] += m

        max_rois = 10

        # Initialize the FacetGrid object
        pal = sns.cubehelix_palette(10, rot=-.25, light=.7)
        aspect = mpl.rcParams['figure.figsize']
        ratio = aspect[0]/aspect[1]
        g = sns.FacetGrid(df,
                row="g",
                hue="g",
                aspect=max_rois*ratio,
                height=aspect[1]/max_rois,
                palette=pal,
                )

        # Draw the densities in a few steps
        g.map(sns.kdeplot, "x", clip_on=False, shade=True, alpha=1, lw=1.5, bw=.2)
        g.map(sns.kdeplot, "x", clip_on=False, color="w", lw=2, bw=.2)
        g.map(plt.axhline, y=0, lw=2, clip_on=False)


        # Define and use a simple function to label the plot in axes coordinates
        def label(x, color, label):
                ax = plt.gca()
                ax.text(0, .2, label, fontweight="bold", color=color,
                        ha="left", va="center", transform=ax.transAxes)

        g.map(label, "x")

        # Remove axes details that don't play well with overlap
        g.set_titles("")
        g.set(yticks=[])
        g.despine(bottom=True, left=True)
        fig = plt.gcf()
        fig.savefig('figure.pdf')
```

And using this matplotlibrc style:

```
axes.facecolor : 0,0,0,0
figure.subplot.top : 1.0
figure.subplot.bottom : 0.0
figure.subplot.left : 0.0
figure.subplot.right : 1.0
figure.subplot.hspace : 0.0
figure.subplot.wspace : 0.0
figure.figsize : 1.8, 1.8
savefig.pad_inches : 0.0
xtick.major.size : 0.0
ytick.major.size : 0.0
```

I get this image:

![figure](https://user-images.githubusercontent.com/950524/58913717-15241b80-871d-11e9-9d80-3b33fbb522f7.png)

It might be best to click it, so that it is displayed on a black background. Note that it has a border on the left-hand, top, and bottom edges. After some testing it appears this is always present, just not very noticeable at larger sizes.
The matplotlibrc includes all of my attempts to make this go away. I have tried numerous parameter variations and nothing seems to work, but based on consultation of the manual, the ones I list here should get rid of all margins. Any ideas?

The entire minimal self-contained example is available [here](http://chymera.eu/debug/seaborn/facetgrid.tar.xz).

**Comment by mwaskom** [comment]
Sorry but I'm not sure what you mean by "a border"?

**Comment by TheChymera** [comment]
@mwaskom I mean border in the sense of margin or padding. There's a distance from the edge of the graphic to the contents which is left blank on the top, bottom, and left, but not on the right.

**Comment by mwaskom** [comment]
You could change the `subplots_adjust` call to remove the margin:

```python
# Set the subplots to overlap
g.fig.subplots_adjust(0, 0, 1, 1, hspace=-.25)
```

That puts the plot elements flush against the edges of the figure....
