### ISSUE TITLE
Catplot where one variable in categorial and the other is a list of values 

### ISSUE THREAD

**Issue by r-shruthi11** [mwaskom/seaborn#1756]
I have a dataframe that looks like this. Here, the categorical variable is **'Sess'** and the corresponding numerical data are contained in **'numPress'** in the form of lists; that is, for each 'Sess' I have a list of values of numPress that I want to plot using Seaborn's catplot. However when I try `sns.catplot(x='Sess', y='numPress',data=numPressDf)` I get an error `unhashable type: 'list'`
<img width="413" alt="Screen Shot 2019-06-05 at 7 11 40 AM" src="https://user-images.githubusercontent.com/31861615/58952259-373f8d00-8761-11e9-861c-47fc6eeb0832.png">
Ultimately what I would like is for my catplot to have on the x-axis the different **'Sess'** numbers and to have on the y-axis the values in the corresponding **'numPress'** list.

**Comment by mwaskom** [comment]
Hi – sorry, you’ll need to reformat your data frame into a tidy organization.
