### ISSUE TITLE
Altering legend text in nested barplot causes legend to label confidence interval instead of series

### ISSUE THREAD

**Issue by MaxGhenis** [mwaskom/seaborn#1757]
`barplot` labels the legend by the series color, as per the [documentation](https://seaborn.pydata.org/generated/seaborn.barplot.html):
```
import seaborn as sns
tips = sns.load_dataset("tips")
ax = sns.barplot(x="day", y="total_bill", hue="sex", data=tips)
```
![image](https://user-images.githubusercontent.com/6076111/59216295-538c6100-8b89-11e9-9a5e-2d394300315d.png)

But when modifying the legend text with `plt.legend`, the legend uninformatively labels the confidence intervals:
```
import matplotlib.pyplot as plt
ax = sns.barplot(x="day", y="total_bill", hue="sex", data=tips)
plt.legend(['m', 'f'])
plt.show()
```
![image](https://user-images.githubusercontent.com/6076111/59216239-39eb1980-8b89-11e9-8380-ff0bed23f7f9.png)
Is there another way one should be changing the legend text with `barplot`?

I'm on seaborn 0.9.0. and matplotlib 3.1.0.

**Comment by mwaskom** [comment]
If you want to do it this way you'd need to pass the handles to the correct matplotlib objects, instead of letting matplotlib label the first two objects in its queue. Alternatively you could alter the data itself in the function call.
