### ISSUE TITLE
Seaborn cluster map row legend not moving position and cannot rename legend values

### ISSUE THREAD

**Issue by amjass12** [mwaskom/seaborn#1758]
Hi all, 

I have constructed a seaborn.clustermap and need help with some elements of the plot that I am struggling with. Any help would be much appreciated!

The plot I have produced attempts to cluster features together. This works nicely and I have painted the rows as the samples with a row annotation. I need to add a legend for this ribbon and this is where two problems arise. 

1. I cant move the legend to any position in the graph
2. Renaming labels shifts then colors one down. 

The script for plot is as follows:

```
hmOrgan = seaborn.clustermap(NormcountsOrgan, cmap="RdPu", yticklabels=False, xticklabels=False,row_cluster=True,
                             col_cluster=True,row_colors=row_colors, metric="euclidean")


for label in Normcountstransposemetadata["Organ"].unique():
    hmOrgan.ax_row_dendrogram.bar(0, 0, color=my_palette[label],
                            label=label, linewidth=0)

hmOrgan.ax_row_dendrogram.legend(loc="bottom", bbox_to_anchor=(0.47, 0.8),ncol=1)

hmOrgan.fig.suptitle("Top genes: Organs", fontsize=32)
```

Problem 1...Whenever changing the 'loc' argument, what I put in, the legend moves around on the left of the heatmap.. so if i put upper left, it simply moves a few pixels to the left and so on... what i would like to do is move this to the empty space at the bottom of the clustermap. Also, i can only specify ncol=1 in order to make the legend a list, otherwise the rest of the box goes out of the image and i cant bring it back in!

problem 2.. Some of the organ have an underscore in them.. I would like to relabel them to remove them!

For this line of code

`hmOrgan.ax_row_dendrogram.legend(loc="bottom", bbox_to_anchor=(0.47, 0.8),ncol=1)
`
I have added a 'labels' argument to rename the labels. This works fine however, ever color now shifts one position downwards! (screenshot attached). As you can see, the brain label now has a thin line, and the kidney takes on the brown color which should be for the brain!

Any help would be much appreciated! Thank you!!
[output.pdf](https://github.com/mwaskom/seaborn/files/3276320/output.pdf)

[output.pdf](https://github.com/mwaskom/seaborn/files/3276317/output.pdf)

**Comment by mwaskom** [comment]
Hi — I think this kind of question would be better suited for StackOverflow. Thanks!
