### ISSUE TITLE
Scatterplot legend adds extra field when data is numerical

### ISSUE THREAD

**Issue by marinsokol5** [mwaskom/seaborn#1760]
Using Python 3.7 and Seaborn 0.9.0 this is really embarrassing.
 ```
import seaborn as sns
sns.scatterplot(x=[1, 2, 3], y=[1, 2, 3], hue=[3, 4, 5])
 ```

Produces this
![Screenshot from 2019-06-12 21-26-47](https://user-images.githubusercontent.com/30181549/59380179-cf88d380-8d58-11e9-8681-b1ee89f2e2c0.png)

You will notice that there is an extra field in the Legend. Field `2` shouldn't exist by no means.

**Comment by mwaskom** [comment]
http://seaborn.pydata.org/generated/seaborn.scatterplot.html

> legend : “brief”, “full”, or False, optional

> How to draw the legend. If “brief”, numeric hue and size variables will be represented with a sample of evenly spaced values. If “full”, every group will get an entry in the legend. If False, no legend data is added and no legend is drawn.
