### ISSUE TITLE
Relplot example has incorrect plot/legend sizes

### ISSUE THREAD

**Issue by lemonad** [mwaskom/seaborn#1763]
I've been trying to get the plot sizes for `relplot` aligned to the legend sizes with no success.

When I looked closer at the example image for [relplot](https://seaborn.pydata.org/examples/scatter_bubbles.html)

![relplot example](https://seaborn.pydata.org/_images/scatter_bubbles.png)

the same problem seem to be there. The smallest weight is 1613 in the dataset but there's an orange dot to the far left in the plot that's smaller than the dot for 1500 in the legend.

---

Here's a small example using the same dataset:
```
import seaborn as sns
mpg = sns.load_dataset("mpg")
print("min: {:d}, max: {:d}".format(
    np.min(mpg["weight"]), np.max(mpg["weight"])
))
_ = sns.relplot(x="horsepower", y="mpg", size="weight", data=mpg)
```

```min: 1613, max: 5140```

![image](https://user-images.githubusercontent.com/56049/59553348-16aed880-8f94-11e9-94e6-ca0ea055119b.png)

Here it is quite clear that many dots are smaller than the legend dot for `1500` (even though the minimum value is `1613`) and that no dot is as large as the `4500` legend dot (even though the maximum value is `5140`).

**Comment by mwaskom** [comment]
Without looking into this too closely, I think the explanation is that there are (white) lines around the edges of the markers in the plot but not the legend. That causes them (especially on a white background) to look smaller than they are. You can convince yourself of this by setting `linewidth` to 0 or by inspecting the size of the collection elements on the axes and in the legend.

**Comment by lemonad** [comment]
@mwaskom You were quite right, `edgecolor=None` seems to work (I don't think `linewidth=0` does) but using that, one loses the separation between markers.

 In my specific case, I had a plot without overlap (with minimum value `-14` and maximum value `8`)
<img width="321" alt="Screen Shot 2019-06-15 at 20 30 59" src="https://user-images.githubusercontent.com/56049/59555026-9648a180-8fac-11e9-8d05-f6c3bea7b2d3.png">

and in this case, the legend is making it seem like the values are smaller than they really are.

My immediate thought is that the legend should use the same edge color, edge width as the markers. The more I look at the examples on various pages, e.g.
![scatterplot](https://seaborn.pydata.org/_images/seaborn-scatterplot-4.png)

I think that would make sense. Perhaps there are good reasons not to do this that I am not considering?

**Comment by mwaskom** [comment]
Aggregating in #2861 and closing here.
