### ISSUE TITLE
catplot with kind=kde/density

### ISSUE THREAD

**Issue by nathanbraun** [mwaskom/seaborn#1764]
Hi there, I recently have been reading about relplot, catplot and FacetGrid's, looks awesome.

I was wondering if there were any plans to add kind='kde' to catplot.  The closest thing right now is probably the violin plots, but one plot I find myself doing often is overlapping (potentially shaded) densities, which seems like it could be a good candidate for the hue parameter.

Any thoughts?

**Comment by mwaskom** [comment]
Hi, indeed I would say this is redundant with the violin plot option.
