### ISSUE TITLE
learning seaborn sucks

### ISSUE THREAD

**Issue by bionicles** [mwaskom/seaborn#1765]
i wanted to make a simple plot today, and got sucked into seaborn, all i wanted to do was pass it a list of floats and get a plot with a regression line, but then i had to make the plot into a dataframe, so i had to import pandas just for this, then i had to reset index on the dataframe to get an x value, then the x value showed up as a float with too many decimal points, then i updated seaborn with conda and it lost all of my pip packages. fuck, all i wanted was a scatter plot with a moving average, not a lost hour+ of my life

Why can't we just do ... sns.regplot(list_of_floats) and get a plot without so much headache?

**Comment by bionicles** [comment]
```
def compute_moving_average(interval, window_size):
    window = np.ones(int(window_size))/float(window_size)
    return np.convolve(interval, window, 'same')


def make_plot(changes):
    plt.clf()
    x = [i for i in range(len(changes))]
    if len(changes) > 5:
        moving_average = compute_moving_average(changes, 5)
        plt.plot(moving_average, 'r-')
    plt.scatter(x, changes)
    plt.savefig('changes.png')
```
this worked

**Comment by mwaskom** [comment]
Thanks for the feedback!

**Comment by AllenDowney** [comment]
Something like LOWESS might serve your purpose.  I wrote a blog post about it:
https://www.allendowney.com/blog/2019/04/01/local-regression-in-python/

Here's the relevant code:

```
from statsmodels.nonparametric.smoothers_lowess import lowess

def make_lowess(series):
    endog = series.values
    exog = series.index.values

    smooth = lowess(endog, exog)
    index, data = np.transpose(smooth)

    return pd.Series(data, index=pd.to_datetime(index))
```

And the details are in this notebook:
https://nbviewer.jupyter.org/gist/AllenDowney/818f6153ef316aee80467c51faee80f8
