### ISSUE TITLE
Auto Scaling of text in Plot

### ISSUE THREAD

**Issue by kaddynator** [mwaskom/seaborn#1766]
I am trying to plot the heat map using seaborn. I have approximately 60 parameters.

`data = np.random.randn(60, 60)`
`sns.set()`
`sns.heatmap(data, vmax=.8, square=True,fmt='d');`

1. Once I try to plot heatmap, somehow _**I am not able to see all the variable name on the scale**_. Some of the variable names are getting hidden. I wanted to see all the variables in the plot. In the image, on the  y axis we can see that some of the parameters name like 1,2,4,5 are not visible. However, the plot still contains correlation related to the variables.  

2. Secondly, _**The text in the left and bottom of the plot is not getting auto scaled to the width of row in the heatmap**_. In the image, we can see that on the y axis, the font size of variable "0" is not equal to the width of the row corresponding to variable "0"

![download (1)](https://user-images.githubusercontent.com/26765844/60135408-a19b8a00-976f-11e9-9944-f1cf45aa8bc4.png)

Can someone check the issue please.

**Comment by mwaskom** [comment]
Everything is working as expected. Take a look at the docs if you want to control what is happening here.
