### ISSUE TITLE
BarPlot: unsupported operand type(s) for /: 'str' and 'int'

### ISSUE THREAD

**Issue by lhorus** [mwaskom/seaborn#1768]
Considering the following pandas DataFrame:

```
      EC     Count   Policy
0    0.0       0.0  Optimal
1    1.0      12.0  Optimal
2    2.0     428.0  Optimal
3    3.0    4138.0  Optimal
4    4.0   13623.0  Optimal
5    5.0   27196.0  Optimal
6    6.0   39469.0  Optimal
7    7.0   38125.0  Optimal
8    8.0   21897.0  Optimal
9    9.0    4991.0  Optimal
10  10.0     121.0  Optimal
11   0.0      10.0       RL
12   1.0      70.0       RL
13   2.0     641.0       RL
14   3.0    5417.0       RL
15   4.0   16719.0       RL
16   5.0   22029.0       RL
17   6.0   24930.0       RL
18   7.0   34192.0       RL
19   8.0   26950.0       RL
20   9.0   17815.0       RL
21  10.0    1227.0       RL
22   0.0  150000.0   Normal
23   1.0       1.0   Normal
24   2.0       1.0   Normal
25   3.0       1.0   Normal
26   4.0       1.0   Normal
27   5.0       1.0   Normal
28   6.0       1.0   Normal
29   7.0       1.0   Normal
30   8.0       1.0   Normal
31   9.0       1.0   Normal
32  10.0       1.0   Normal
```

Calling Seaborn's BarPlot on it, using

>  ax = sns.barplot(x='EC', y='Count', data= ec_df)

yields an error:

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-171-a7e42a944caa> in <module>
>      21 
>      22 print(ec_df)
> ---> 23 ax = sns.barplot(x='EC', y='Count', data= ec_df)
> 
> ~\Anaconda3\lib\site-packages\seaborn\categorical.py in barplot(x, y, hue, data, order, hue_order, estimator, ci, n_boot, units, orient, color, palette, saturation, errcolor, errwidth, capsize, dodge, ax, **kwargs)
>    3147                           estimator, ci, n_boot, units,
>    3148                           orient, color, palette, saturation,
> -> 3149                           errcolor, errwidth, capsize, dodge)
>    3150 
>    3151     if ax is None:
> 
> ~\Anaconda3\lib\site-packages\seaborn\categorical.py in __init__(self, x, y, hue, data, order, hue_order, estimator, ci, n_boot, units, orient, color, palette, saturation, errcolor, errwidth, capsize, dodge)
>    1607                                  order, hue_order, units)
>    1608         self.establish_colors(color, palette, saturation)
> -> 1609         self.estimate_statistic(estimator, ci, n_boot)
>    1610 
>    1611         self.dodge = dodge
> 
> ~\Anaconda3\lib\site-packages\seaborn\categorical.py in estimate_statistic(self, estimator, ci, n_boot)
>    1491                     statistic.append(np.nan)
>    1492                 else:
> -> 1493                     statistic.append(estimator(stat_data))
>    1494 
>    1495                 # Get a confidence interval for this estimate
> 
> ~\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py in mean(a, axis, dtype, out, keepdims)
>    3116 
>    3117     return _methods._mean(a, axis=axis, dtype=dtype,
> -> 3118                           out=out, **kwargs)
>    3119 
>    3120 
> 
> ~\Anaconda3\lib\site-packages\numpy\core\_methods.py in _mean(a, axis, dtype, out, keepdims)
>      85             ret = ret.dtype.type(ret / rcount)
>      86     else:
> ---> 87         ret = ret / rcount
>      88 
>      89     return ret
> 
> TypeError: unsupported operand type(s) for /: 'str' and 'int'

**Comment by MaozGelbart** [comment]
Hi @lhorus ,
Although it contains numbers, is it possible that ``Count`` is not defined as numeric?

**Comment by lhorus** [comment]
@MaozGelbart ,

Thank you very much. You are absolutely right, I assumed that because I casted the type to float in Numpy (which I use to provide Pandas with the initialized values), Pandas would assume the type as well. My bad for not reading through the documentation properly. 

Thank you.
