### ISSUE TITLE
Pandas datetime heatmap handling

### ISSUE THREAD

**Issue by joseortiz3** [mwaskom/seaborn#1769]
I have an example which may illuminate easy handling of pandas datetimes for seaborn. I was about to post it to another issue but the issue was locked a few seconds before I hit post.

-------------------------------------------------

Actually it may be even easier than I thought:

I have a dataframe called `thing` representing a histogram in time.

I define the following methods:

```python
    def calc_freq(index): 
        return pd.Series(index[1:] - index[:-1]).mean()

    def conv_index_to_bins(index):
        assert index.is_monotonic
        freq = calc_freq(index)
        start = index.min()- freq/2
        end = index.max()+ freq/2
        N = len(index)+1
        if isinstance(index, pd.DatetimeIndex):
            return pd.date_range(start, end, N)
        elif isinstance(index, pd.Float64Index):
            return np.linspace(start, end, N)
        else: 
            raise NotImplementedError('Not sure what to do with index type %s' % type(index))

    def calc_df_mesh(df):
        return np.meshgrid(conv_index_to_bins(df.index),
                           conv_index_to_bins(df.columns))

    def heatmap(df):
        X,Y = calc_df_mesh(df)
        c = plt.pcolormesh(X, Y, df.values.T)
        plt.colorbar(c)
```

call

```
heatmap(thing)
```
And I obtain
![Figure_1](https://user-images.githubusercontent.com/18585219/60459006-da66b380-9bf4-11e9-9d90-3298f0c238a6.png)

rather than with seaborn
![sb](https://user-images.githubusercontent.com/18585219/60459036-efdbdd80-9bf4-11e9-99cd-5931cc88d28c.png)

**Comment by mwaskom** [comment]
Yes, seaborn heatmap is for when the axes have categorical values, so it doesn't use matplotlib's numerical ticker algorithms. Using the existing matplotlib function for the task it is intended for is the right option.

**Comment by joseortiz3** [comment]
If I opened a PR to handle this case would it be rejected?
