### ISSUE TITLE
Automatic rotation of x-ticks

### ISSUE THREAD

**Issue by JurijsNazarovs** [mwaskom/seaborn#1770]
Hello,

I plot the heat map with ticks of form: | or t or d. However, with the same code sometimes heat map plots x-ticks vertically, sometimes horizontally. Is there a way to control, that it is vertically all the time?

Code of setting x-ticks:
```
 ax.set(xticks=x_tick_pos, xticklabels=x_tick_lab,
               yticks=[], yticklabels=[])
```

Images:

![Screen Shot 2019-07-02 at 11 24 41 AM](https://user-images.githubusercontent.com/26803244/60529405-1e70bb80-9cbc-11e9-8a35-591876628056.png)
![Screen Shot 2019-07-02 at 11 24 21 AM](https://user-images.githubusercontent.com/26803244/60529406-1f095200-9cbc-11e9-8eab-0a834ee8bf6d.png)

**Comment by mwaskom** [comment]
`plt.setp(ax.get_xticklabels(), rotation=90)`

**Comment by JurijsNazarovs** [comment]
Thank you!
