### ISSUE TITLE
Flipped y-axis or mixed up hue order in horizontal faceted catplot

### ISSUE THREAD

**Issue by robbibt** [mwaskom/seaborn#1771]
Hi everyone, I'm attempting to plot up data like this into a faceted violin plot with split violins:

```
# Set up faceted data for plotting using catplot
sample_data = pd.DataFrame({'row': np.random.choice(['a', 'b'], 1000),
                            'col': np.random.choice(['c', 'd'], 1000),
                            'hue': np.random.choice(['g', 'h'], 1000),
                            'a': np.random.choice(['e', 'f'], 1000),
                            'b': np.random.randn(1000)})
```

This works fine when I plot a standard vertical faceted plot: all the blue hued violins are on the left, and all the orange violins are on the right:

```
# Plot horizontal catplot             
sns.catplot(x='a', 
            y='b', 
            col='col', 
            row='row', 
            hue='hue', 
            data=sample_data,
            kind='violin', 
            split=True, 
            inner=None,
            height=2,
            aspect=1.5)
```
![Capture](https://user-images.githubusercontent.com/17680388/60630395-44719980-9e3d-11e9-952c-67329b759b43.JPG)

However, when I attempt to plot a horizontal violin plot using the `orient='h'` parameter, the last facet in the plot will always plot "upside-down" compared to the other facets (e.g. orange on top in the first three facets, blue on top in the last facet):

```
# Plot horizontal catplot             
sns.catplot(x='b', 
            y='a', 
            col='col', 
            row='row', 
            hue='hue', 
            data=sample_data,
            orient='h',
            kind='violin', 
            split=True, 
            inner=None,
            height=2,
            aspect=1.5)
```
![Capture2](https://user-images.githubusercontent.com/17680388/60630420-5a7f5a00-9e3d-11e9-84b6-2c69e44a86de.JPG)

I've tried using `hue_order=['h', 'g']` to force the order, but it appears to have no effect on the final facet. What can I do to get all facets to plot in the same order?

**Comment by robbibt** [comment]
Some further testing shows the same issue occurs for both `kind='box'`, `kind=`bar` and `kind=`boxen`, and probably others:
![Capture](https://user-images.githubusercontent.com/17680388/60630629-4d169f80-9e3e-11e9-9a4f-201c297cafae.JPG)

**Comment by robbibt** [comment]
Some further testing on a more complex dataset makes me think that the entire y-axis is actually flipped in the final facet, not just the order of the `hue` variable. In the example below, the right hand facet should resemble the appearance of the left hand facet, but is instead plotted upside down:
![Capture](https://user-images.githubusercontent.com/17680388/60642270-a1d40d80-9e72-11e9-8aaf-b9b5b65223a5.JPG)

**Comment by mwaskom** [comment]
Quite weird. Horizontally oriented categorical plots do invert the y axis so that the order goes from top to bottom rather than bottom to top (as a numerical axis would). But nothing comes to mind immediately as to why this would interact poorly with FacetGrid. What happens when you pass `sharey=False`?

**Comment by robbibt** [comment]
@mwaskom `sharey=False` does clear the issue up:
![Capture](https://user-images.githubusercontent.com/17680388/60689775-5407e580-9f04-11e9-901e-f2a301c3581d.JPG)

**Comment by mwaskom** [comment]
I cannot reproduce this issue locally. What version of matplotlib are you using?

**Comment by mwaskom** [comment]
Someone reported earlier that matplotlib made some changes to axis inversion behavior in the most recent release. I don't know if this reflects new intended behavior or a bug, but there was a bug that was causing [issues with `heatmap`](https://github.com/mwaskom/seaborn/issues/1773) (though very different ones).

**Comment by mwaskom** [comment]
What if you try a real simple matplotlib-only example, something like:

```python
f, axes = plt.subplots(1, 3, sharey=True)
for ax in axes:
    ax.scatter([0, 0], [0, 1], c=[0, 1], s=200, cmap="bwr")
    ax.invert_yaxis()
```

**Comment by robbibt** [comment]
@mwaskom I'm on Matplotlib version 3.1.0, and the simple example above does indeed replicate the problem for me:
![image](https://user-images.githubusercontent.com/17680388/61269817-14ce7400-a7e3-11e9-9b09-cb7867cc4a4b.png)

Does this infer it's a bug in Matplotlib itself?

**Comment by MaozGelbart** [comment]
Hi @robbibt , I reproduced the issue with matplotlib 3.1.0 but not with 3.1.1 or 3.0.3. I guess up/downgrading mpl will fix this issue for you as well.

**Comment by mwaskom** [comment]
Thanks all, as this appears to arise from a bug in a specific minor version of matplotlib, I am going to close.
