### ISSUE TITLE
KDE outliers detection

### ISSUE THREAD

**Issue by JavierLopatin** [mwaskom/seaborn#1774]
Hi guys, 
First of all, congrats on this amazing library! I'm using the 'kdeplot' and I want to detect the outliers or the observations that occur outside the kde contours. For example the one highlighted in red:  

![kdeOutliers](https://user-images.githubusercontent.com/14294585/61125352-e6325f80-a4a9-11e9-85aa-b7e704676357.png)

Any idea how to select this observations?
Cheers,
Javier

**Comment by mwaskom** [comment]
Hi – I'd say that outlier *detection* is outside the bounds of what a visualization library should do. But there are lots of methods you could apply, if you search.
