### ISSUE TITLE
Moving legend changes its content for barplot

### ISSUE THREAD

**Issue by loeweX** [mwaskom/seaborn#1775]
Hello,

When creating a barplot and keeping the legend unchanged, everything works as expected and the legend has the hue as a title:

`sns.barplot(x=x_label, y=y_label, hue=hue_label, data=df) `

![latent_mi](https://user-images.githubusercontent.com/16319903/61136091-3ec22680-a4c3-11e9-8ffb-f2aa1b1d1881.png)

However, when I try moving the legend to a different position, suddenly the title of the legend disappears:

`plt.legend(loc='right')`

![latent_mi](https://user-images.githubusercontent.com/16319903/61136039-1fc39480-a4c3-11e9-89ef-3654cf09990d.png)

I used very similar code with lineplot as well, and there it works without problems. Is there a way to show the title in the legend after moving it?

Thank you!

**Comment by mwaskom** [comment]
You're not moving the legend, you're drawing a new legend. `plt.legend` takes a `title` parameter that you can provide.
