### ISSUE TITLE
Feature Request: Cat's Eye plots

### ISSUE THREAD

**Issue by nickdelgrosso** [mwaskom/seaborn#1776]
Hi,

I recently read Geoff Cumming's "Understanding The New Statistics" and think that his "Cat's eye" plots would make a great contribution to seaborn.  They look basically like cut violin plots, but represent inferential stats (CIs) instead of the data's distribution.  Because of the central limit theorem, they tend to be quite smooth, and according to Cumming's research they produce intuitions that are more accurate.

For me, I'd like to see a default Cat's eye with lines/shading at the estimate, 68%, and 95% points.  Here's an example of what I'd see one looking like:

![Cat's Eye](https://github.com/PyDataMunich/ErrorBarsTalk/blob/master/img/catseye_example.png?raw=true)

This is something I'd like to work on--is it something feature that would be interesting to the Seaborn developers?

**Comment by mwaskom** [comment]
These are interesting, but it's not clear what showing the distribution adds over error bars, and I would worry that there close visual similarity to violinplots would breed confusion.

**Comment by nickdelgrosso** [comment]
Thanks for the response!  It's true that this similarity can be confusing, but the main benefit of this over line error bars is that it emphasizes the "error" nature of the point estimate in a way that more closely resembles the central limit theorem.  People tend to over-weigh the edges of the error bars, and because the bars' amount of overlap implies a lack of statistical significance in hypothesis testing, they will often favor smaller error bars over larger ones (one of the reasons SEMs appear more often than 95%CIs in different fields).  Cat's Eyes emphasize the center of the error distribution, allowing the full uncertainty range to be represented without biasing the reader's interpretation of the distribution.
