### ISSUE TITLE
How can i fix this error?

### ISSUE THREAD

**Issue by kaushik2603** [mwaskom/seaborn#1779]
I have a dataframe called compare. I have to use pairplot for this dataframe.

```
compare=compare.pct_change()
compare.replace([np.inf,-np.inf],np.nan)
compare.dropna(inplace=True,how='any',axis=0)
sns.pairplot(compare)

```
Output expected is pairplot of the dataframe. The error showing is

`ValueError: color kwarg must have one color per data set. 5 data sets and 1 colors were provided`

**Comment by MaozGelbart** [comment]
Hi @kaushik2603 ,
Could you provide a minimal code example (including data) that will allow reproduction of the described issue?
Thanks!

**Comment by kaushik2603** [comment]
> Hi @kaushik2603 ,
> Could you provide a minimal code example (including data) that will allow reproduction of the described issue?
> Thanks!


I have 5 different dataframes and an index dataframe. From wach dataframe i have to select a column 
```
data1=data1['Close Price']
data1.columns=['TITAN']
```
like that for `data1` to `data5` and index dataframe `datai` . After that:
`compare=pd.concat([data1,data2,data3,data4,data5,datai],axis=1)`

**Comment by kaushik2603** [comment]
> Hi @kaushik2603 ,
> Could you provide a minimal code example (including data) that will allow reproduction of the described issue?
> Thanks!

I have 5 different dataframes and an index dataframe. From each dataframe i have to select a column 
```
data1=data1['Close Price']
data1.columns=['TITAN']
```
like that for `data1` to `data5` and index dataframe `datai` .
 After that,
`compare=pd.concat([data1,data2,data3,data4,data5,datai],axis=1)`
