### ISSUE TITLE
Barplot coming out white when setting aesthetics

### ISSUE THREAD

**Issue by xuxue0556** [mwaskom/seaborn#1782]
I summarized my issue in this [StackOverflow question](https://stackoverflow.com/questions/57186663/seaborn-barplot-color-palette-not-working).

Basically, when setting plot aesthetics and using `sns.boxplot` the graph comes out white/not visible.

PS: I will work on a small example and post here soon

**Comment by mwaskom** [comment]
Please don't post duplicate questions in multiple channels.

Your issue is that you are trying to draw too many bars in too little space.
