### ISSUE TITLE
Group numerical categorical values

### ISSUE THREAD

**Issue by darkdragon-001** [mwaskom/seaborn#1783]
I want to group items via `hue` in `scatterplot`.
This column is a (discrete) distance. So let's say only values `[1.0, 2.0, 3.0]` exist. They have the data type `float`. 

Plotting them with seaborn assums numerical data and thus might put the values '0.8, 1.8, 2.8` in the legend. It also uses continuous colors instead of discrete colors. 

Note that `df.groupby()` only gives me these three distinct values.

So I tried converting this data to categorical values. The following approaches didn't work
* `dg['categorical'] = pd.Categorical(dg['distance'])`
* `dg['categorical'] = dg['distance'].apply(str)`

What worked was:
```
def g2c(v):
    return 'test_'+str(v)
dg['categorical'] = dg['distance'].apply(g2c)
```

I think the first two approaches should equally work and therefore, I am submitting a bug report. Especially the data type `Categorical` should be understood by seaborn!

**Comment by mwaskom** [comment]
See https://github.com/mwaskom/seaborn/pull/1575/
