### ISSUE TITLE
Annotations positions out of boxes

### ISSUE THREAD

**Issue by ptynecki** [mwaskom/seaborn#1786]
Python env:

- Python: 3.6.8 x64
- OS: Mac OSX / Linux
- seaborn: 0.9.0
- matplotlib: 3.1.1

The code below is not working as expected.

```python
import seaborn as sns

outcome_labels = ["Test A", "Test B"]

sns.heatmap(
    confusion_matrix(y_test, clf_predict),
    annot=True,
    fmt="d",
    xticklabels=outcome_labels,
    yticklabels=outcome_labels,
)
```

`confusion_matrix` returns:

```python
array([[107,   3],
       [  3,  61]])
```

It generate confusion matrix plot but annotations positions are out of boxes. By default they were centered in Vertical/Horizontal in the past but sth changed after last package update.

![heatmap](https://user-images.githubusercontent.com/228280/62290834-886ab500-b462-11e9-88d7-0e0caa18b550.png)

**Comment by mwaskom** [comment]
This is a matplotlib bug ... there are several duplicate issues you can find if you search.

**Comment by ptynecki** [comment]
@mwaskom 

You've right. After downgrade the matplotlib to 3.1.0 problem doesn't exists.

**Comment by someAdjectiveNoun** [comment]
@ptynecki @mwaskom  Downgrading to matplotlib 3.1.0 did not work with me. The annotations are still out of place in the figures.
