### ISSUE TITLE
Color mismatch using hexadecimal colors

### ISSUE THREAD

**Issue by romquentin** [mwaskom/seaborn#1792]
Hi, 

Using seaborn 0.9.0 and matplotlib 3.0.3, I realized that they were not plotting the same color for the same hex color entry. Checking a hexadecimal colors calculator online, it seems that seaborn is not plotting the correct color.
<img width="639" alt="Screen Shot 2019-08-06 at 6 33 21 PM" src="https://user-images.githubusercontent.com/16289774/62558134-ba23b780-b878-11e9-8772-e83837acb273.png">

To reproduce:

```
import matplotlib.pyplot as plt
import seaborn as sns
color = '#de8f05'

fig, (ax1, ax2) = plt.subplots(2)
ax1.bar(1, 1, color=color)
ax2 = sns.barplot(1, color=color)
plt.show()
```
Thank you for your help!

**Comment by mwaskom** [comment]
`barplot` has a `saturation` parameter.

**Comment by romquentin** [comment]
I see. Thanks!
