### ISSUE TITLE
Feature Request: Bump Charts

### ISSUE THREAD

**Issue by kartikay-bagla** [mwaskom/seaborn#1797]
Bump Charts are generally used to represent rank changes over time. An example would be this:
![image](https://user-images.githubusercontent.com/19384906/62832153-fc1d7680-bc47-11e9-8b32-abb22c9710d7.png)

I managed to create the image below for a presentation:
![image](https://user-images.githubusercontent.com/19384906/62833122-fbd8a780-bc56-11e9-9811-520143e4fdd8.png)

But I would like to see it as a function of seaborn as well. I have a basic code for this as well, but I have no idea as to how do I integrate it with seaborn.

Any guidance would be greatly appreciated.

Edit: I've tried exploring the source on my own, it's not that hard. I'll try to implement it myself and create a pull request.

**Comment by mwaskom** [comment]
Hi — interesting, but I think out of scope for seaborn. I’d encourage you to make a library and put it on pypi, though.
