### ISSUE TITLE
seaborn.distplot bins keyword ignores list of bin edges?

### ISSUE THREAD

**Issue by rjp23** [mwaskom/seaborn#1800]
In matplotlib hist you can specify either the number of bins or the bin edges: https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.hist.html

I want to specify the bin edges, i.e. plt.hist(data, bins=[1500,1600,1700,1800,1900,2000]) and this works fine with hist. 

For distplot, the bin edges are ignored using the same list and instead the bins go to the maximum of my data (which is huge due to 1 outlier).

**Comment by mwaskom** [comment]
Please show a reproducible example of the behavior you describe.

**Comment by rjp23** [comment]
Here's a basic example but I realised the issue is not quite as I described. The histogram is obeying the bin limits but the KDE function (which I assumed would also follow the same bins) is not. That results in the plotted x range not being limited to the range of bins as would be expected.

```
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

a = np.random.rand(100)

plt.hist(a, bins=[0.1,0.2,0.3,0.4])
plt.show()

sns.distplot(a,  bins=[0.1,0.2,0.3,0.4])
plt.show()

```

**Comment by mwaskom** [comment]
You could do

```python
xx = np.random.rand(1000)
bins = np.linspace(0, .5, 21)
sns.distplot(xx, bins=bins, kde_kws=dict(clip=(bins.min(), bins.max())))
```
