### ISSUE TITLE
Plot clustermap/heatmap of data that you have clustered yourself?

### ISSUE THREAD

**Issue by endrebak** [mwaskom/seaborn#1803]
Thanks for the great library.

I want to create beatuiful heatmaps like the ones in produced by clusterplot. Problem is, my data are silly large in the number of rows so using clustermap directly is not feasible. Using scipy and sklearn, I have written code that is able to cluster the data in the rows and produce a dendrogram for the columns.

1) Given a linkage matrix for the columns and a sorted dataframe to be plotted, is there a way to use seaborn to plot something clustermap-like? Hints would be appreciated. 

2) Is this a feature you might be interested in adding?

If you feel this is off-topic, feel free to close. Perhaps it is better suited for SO :)

**Comment by mwaskom** [comment]
Are your looking for 

```
{row,col}_linkage : numpy.array, optional

Precomputed linkage matrix for the rows or columns. See scipy.cluster.hierarchy.linkage for specific formats.
```

From http://seaborn.pydata.org/generated/seaborn.clustermap.html?

**Comment by endrebak** [comment]
Thanks!

I am sorry for creating this issue, for some reason I thought this feature could not possibly exist :)
