### ISSUE TITLE
AttributeError: module 'seaborn' has no attribute 'plot'

### ISSUE THREAD

**Issue by AGHAHUSAIN** [mwaskom/seaborn#1804]
i m getting this problem 

AttributeError: module 'seaborn' has no attribute 'plot'

whats the issue, can anyone help me

**Comment by mwaskom** [comment]
Indeed, seaborn has no function simply called `plot`.

**Comment by roveen001** [comment]
so how does this work `so.Plot(flights["month"], flights["passengers"]).add(so.Bar())` works found here, [](https://seaborn.pydata.org/generated/seaborn.objects.Bar.html?highlight=bar+plot#)

**Comment by rohaan2614** [comment]
from seaborn import objects as so
