### ISSUE TITLE
Jointplot with plt subplots

### ISSUE THREAD

**Issue by Chippasaur** [mwaskom/seaborn#1805]
Hi All, 

For some odd reasons when I use subplots with jointplot, the marginals gets plotted separately outside of the subplots. I was wondering whether their was a way to remove the marginal plots or plot them with the density plot. I would like to keep using the jointplot, as the coloring looks better than the kdeplot.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/22933493/63169921-502abf80-c07b-11e9-933c-42998f27b23b.png">

<img width="548" alt="image" src="https://user-images.githubusercontent.com/22933493/63169974-7ea89a80-c07b-11e9-9067-9890de8cc8c0.png">

**Comment by mwaskom** [comment]
Hi, if you search on stackoverflow you will find an answer here.
