### ISSUE TITLE
Feature Request: Print array with color function

### ISSUE THREAD

**Issue by kolibril13** [mwaskom/seaborn#1806]
I find it really useful to print my numpy arrays with a colormap in the background to indicate regions of high and regions of low values. 
In jupyter notebook it looks like this:
```python
import numpy as np
import seaborn as sns
import pandas as pd

def print_array_with_col(array):
    cm = sns.light_palette("blue", as_cmap=True)
    df=pd.DataFrame(intersection_matrix)
    x=df.style.background_gradient(cmap=cm)
    return display(x)
```
The output looks like this:
![git](https://user-images.githubusercontent.com/44469195/63171004-edb1cf00-c03a-11e9-9c97-f5ed123704dd.png)

This might be useful for other people as well.
`print_array_with_col` could also have optional parameters like min, max, colormaptype, opacity and etc.

I got the idea from here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html

**Comment by mwaskom** [comment]
I think you are looking for heatmap.

**Comment by kolibril13** [comment]
Oh nice, that is great!
