### ISSUE TITLE
Document ClusterGrid

### ISSUE THREAD

**Issue by flying-sheep** [mwaskom/seaborn#1810]
[`clustermap`](https://seaborn.pydata.org/generated/seaborn.clustermap.html#seaborn.clustermap) is documented to return `ClusterGrid` objects and provides some information about what they are:

> **Notes:**
> 
> […]
> 
> To access the reordered row indices, use: `clustergrid.dendrogram_row.reordered_ind`
> 
> Column indices, use: `clustergrid.dendrogram_col.reordered_ind`

Yet they aren’t documented while other classes like [`PairGrid`](https://seaborn.pydata.org/generated/seaborn.PairGrid.html#seaborn.PairGrid) are.

**Comment by mwaskom** [comment]
The difference is that it's not really a user-facing class in the way `FacetGrid` or `PairGrid` are; there's no expected situation where a user would want to set up a visualization using `ClusterGrid` directly. It has a couple of attributes that can be useful, but those are probably best documented in `clustermap`, which is the current solution.

**Comment by juberpatel** [comment]
Hello! Here is an instance where the above reasoning may not hold. I am trying to rotate the x-axis labels and it seems the only way you can do that is by accessing certain ClusterGrid properties.

cg = sns.clustermap(df, metric="correlation")
plt.setp(cg.ax_heatmap.yaxis.get_majorticklabels(), rotation=45)

From: https://stackoverflow.com/questions/34572177/labels-for-clustermap-in-seaborn

It would be nice to have this and similar properties documented.

**Comment by rpeys** [comment]
Another possible use case: I'm trying to access the column annotation colorbar to change the fontsize of those labels, and I assume that could be done by accessing the appropriate part of the clustergrid object. The clustermap documentation doesn't include instructions for altering the fontsize of those labels specifically, as far as I can tell.
