### ISSUE TITLE
Changing the xrange and yrange when only showing X # of confidence levels. 

### ISSUE THREAD

**Issue by sdf94** [mwaskom/seaborn#1812]
When plotting a kdeplot, I expect to be able to use n_levels and confidence level label values to create the appropriate x range or y range. 

I only want to focus on the top 2 confidence intervals in this scenario. 

Here's an example:

> import seaborn as sns
sns.kdeplot(x,y,cmap=sns.light_palette('#ED9583', as_cmap=True), shade=True,legend=True,shade_lowest=False, cbar=True, n_levels=2)
plt.show() 

![image](https://user-images.githubusercontent.com/24729684/63359149-167ae280-c321-11e9-8f5c-fd94ebc00c43.png)

In comparison to creating my own grid and then having to find the max values in the x and y values for the 2nd color level: 

>import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
 import numpy as np
from scipy.stats import kde

>#I first have to create the contour plot myself
nbins=300
k = kde.gaussian_kde([x,y])
xi, yi = np.mgrid[x.min():x.max():nbins * 1j, y.min():y.max():nbins * 1j]
zi = k(np.vstack([xi.flatten(), yi.flatten()]))
temp = pd.DataFrame({'xi' : xi.flatten(),
                                    'yi' : yi.flatten(),
                                    'zi' : zi.flatten()})
f, ax1 = plt.subplots()
cs = ax1.contourf(xi, yi, zi.reshape(xi.shape),n_levels=2,cmap=sns.light_palette('#ED9583', as_cmap=True))

>#Find the new max x and y values using the 2nd confidence level
xmaxval = max(temp[temp['zi'] > cs.levels[2]]['xi'])
ymaxval = max(temp[temp['zi'] > cs.levels[2]]['yi'])

>#Replot the contours using kdeplot
sns.kdeplot(x,y,cmap=sns.light_palette('#ED9583', as_cmap=True),shade=True,legend=True,shade_lowest=False, cbar=True, n_levels=2)
xmin,xmax = min(x), xmaxval
ax.set_xlim(left=xmin, right=xmax)
ax.tick_params(axis='both', which='both', length=0,pad=15)
ymin,ymax = min(y), ymaxval
ax.set_ylim(bottom=ymin, top=ymax)
plt.show()

![image](https://user-images.githubusercontent.com/24729684/63359189-2b577600-c321-11e9-8fac-81e2deca4480.png)

**Comment by mwaskom** [comment]
1) The contour algorithm (and autoscaling of the axes) is implemented in matplotlib.
2) Setting `n_levels` to 2 does not show you two "confidence levels" in any statistically meaningful sense.

**Comment by sdf94** [comment]
Right. But it will include all of the levels, not just the 2 I would want to highlight. 
The contour algorithm therefore does not implement this method.

I also realize that the confidence level would typically not showing case any statistical meaning. However, in my case, I cannot disclose full data context, so it is not obvious that there is a statistically meaningful message.
