### ISSUE TITLE
Feature request : Add option to show the mean in boxenplot

### ISSUE THREAD

**Issue by samuelstjean** [mwaskom/seaborn#1813]
Kind of like in the box plot (even though the option is in matplotlib), it would be useful to have as it shows if outliers drag the mean away from the median for example.

All of the inner functions are custom drawn, but the outliers are made with a scatterplot and the median is hand computed inside, so I'd guess getting the mean value in addition and scatterplotting it if requested would be in the doable.

**Comment by mwaskom** [comment]
I would just layer a point plot on top of the boxen.

**Comment by samuelstjean** [comment]
That was indeed my first idea (a pointplot of the mean it self using map on each subgraph), but I ended up somehow with points not matching/aligned to their respective plots. I guess it might be a too specific request then, no worries.
