### ISSUE TITLE
Range of axes become too large when using hue and kind="reg" together in a pairplot.

### ISSUE THREAD

**Issue by jasonzietz** [mwaskom/seaborn#1814]
Hello!  When I specify kind="reg" and a hue, the ranges of the axes in every plot in my pairplot become incredibly large.  For example, instead of ranging from 0 to 100 on the y-axis and 0 to 30 on the x-axis, the axes are now -100 to 200 and -100 to 100, respectively.  Before/after images included.

![before](https://user-images.githubusercontent.com/431869/63486474-e9374d00-c464-11e9-9e7a-1c81142a907e.png)

![after](https://user-images.githubusercontent.com/431869/63486479-ee949780-c464-11e9-9292-572608dc9671.png)

Thanks!

**Comment by mwaskom** [comment]
I can’t help without a reproducible example

**Comment by jasonzietz** [comment]
[example.csv.zip](https://github.com/mwaskom/seaborn/files/3531202/example.csv.zip)

Ah, good point!  Sorry about that.

Attached is a csv file.  Here is the code I'm running:

example = pd.read_csv("example.csv")
sb.pairplot(example,vars=["C","F","I","J"],hue="M",kind="reg")
sb.pairplot(example,vars=["C","F","I","J"],hue="M")
sb.pairplot(example,vars=["C","F","I","J"],kind="reg")

Thanks!  And thanks for your work on Seaborn!

**Comment by mwaskom** [comment]
Can you check if it works on the current master branch? I think this is a case of a bug in `regplot` that has since been fixed (https://github.com/mwaskom/seaborn/pull/1569)

**Comment by jasonzietz** [comment]
I assume I am -- I'm running 0.9.0.

**Comment by mwaskom** [comment]
The master branch is ahead of 0.9. But actually I think it is a different issue that doesn't have a fix yet. It can be avoided by using `sns.pairplot(..., plot_kws=dict(truncate=True))`

**Comment by jasonzietz** [comment]
Thanks, that helps a bit, but the points are still a bit squished and the trendlines aren't easy to read.  I'm not sure if this helps to figure out the bug, but here are some screenshots.

Thanks again!

![notrends](https://user-images.githubusercontent.com/431869/63614216-bfcf0c00-c59f-11e9-8a7b-c281fa7e90f7.png)


![trends](https://user-images.githubusercontent.com/431869/63614227-c5c4ed00-c59f-11e9-9119-4abf75e93987.png)
