### ISSUE TITLE
Get rid of pyplot internally

### ISSUE THREAD

**Issue by flying-sheep** [mwaskom/seaborn#1815]
`pyplot` is an API for interactive use. It takes longer to import than just importing the parts of matplotlib one needs, because it contains the kitchen sink. Also it modifies matplotlib’s state just by being imported, which is normally really bad form (but as said useful as an interactive API).

seaborn would be available for use in other libraries if it didn’t use pyplot internally. `sns.set()` could then do the initial setup for stateful, interactive use.

**Comment by mwaskom** [comment]
Interesting, but as this isn’t really an actionable issue, I’m going to close it.

**Comment by flying-sheep** [comment]
What do you mean?
