### ISSUE TITLE
sizes in relplot legend are in reverse order with categorical data

### ISSUE THREAD

**Issue by mojones** [mwaskom/seaborn#1817]
Using `relplot` with `size` mapped to a numerical column works as expected; the sizes in the legend go smallest to largest:

```python
test = pd.DataFrame({
 'foo' :[1,2,3,4,5,6,7],
 'bar' :[4,6,8,3,5,4,6],
 'baz' :[1,1,2,2,3,3,3]
}
)
sns.relplot(
data=test,
x='foo',
y='bar',
size='baz',
    sizes=(20,200)
)
```
![image](https://user-images.githubusercontent.com/893512/63938130-fc957a00-ca5b-11e9-8f93-79b2833e83d7.png)

But with categorical data:
```python
test = pd.DataFrame({
 'foo' :[1,2,3,4,5,6,7],
 'bar' :[4,6,8,3,5,4,6],
 'baz' :['small', 'small', 'medium', 'medium', 'large', 'large', 'large']
}
```
the legend sizes go largest to smallest:

![image](https://user-images.githubusercontent.com/893512/63938170-1767ee80-ca5c-11e9-8c13-c6f7f6a6e8c6.png)

Is this intended behaviour? I wondered whether it is something to do with the dype, but I've tried with a category:

```python
test = pd.DataFrame({
 'foo' :[1,2,3,4,5,6,7],
 'bar' :[4,6,8,3,5,4,6],
 'baz' :['small', 'small', 'medium', 'medium', 'large', 'large', 'large']
}
)
    
test['baz'] = test['baz'].astype('category')
sns.relplot(
data=test,
x='foo',
y='bar',
size='baz',
    sizes=(20,200)
)
```

and an ordered category

```python
test = pd.DataFrame({
 'foo' :[1,2,3,4,5,6,7],
 'bar' :[4,6,8,3,5,4,6],
 'baz' :['small', 'small', 'medium', 'medium', 'large', 'large', 'large']
}
)
    
test['baz'] = test['baz'].astype(pd.CategoricalDtype(categories=["small", "medium", "large"],ordered=True))
sns.relplot(
data=test,
x='foo',
y='bar',
size='baz',
    sizes=(20,200)
)
``` 

and neither make a difference. I can make the legend sizes match what I want by setting `size_order`, but they are still in the "wrong" orientation, which will be confusing when mixed in with charts where the legend goes the other way.

**Comment by mwaskom** [comment]
I believe this is intentional, although it is confusing and should be documented better.

The most direct way to control the attributes of categorical semantics is to use a dictionary, e.g.:

```python
sns.relplot(
    data=test,
    x='foo',
    y='bar',
    size='baz',
    sizes={"small": 20, "medium": 100, "large": 200},
)
```
![image](https://user-images.githubusercontent.com/315810/63944970-95b69780-ca40-11e9-95fa-3c6949271b00.png)

**Comment by mojones** [comment]
Thanks for the quick reply; what you're suggesting work perfectly.

**Comment by livyring** [comment]
how do you get a numerical value to be inverted in marker size? I am trying to plot a bubble plot with P values, I want smaller p values (more significant values) to appear as larger bubbles whereas larger p values would appear as smaller bubbles.

**Comment by YuqiLiang1900** [comment]
> how do you get a numerical value to be inverted in marker size? I am trying to plot a bubble plot with P values, I want smaller p values (more significant values) to appear as larger bubbles whereas larger p values would appear as smaller bubbles.

https://community.plotly.com/t/bubble-chart-inverting-the-size-of-markers/39769 I also encountered this problem and I found that this link has a solution to this issue.
