### ISSUE TITLE
Seaborn Python problem

### ISSUE THREAD

**Issue by Muffin2019** [mwaskom/seaborn#1818]
I am using Seaborn and Metplotlib in Python but I keep getting an error on Line 13 

import matplotlib as mpl
_orig_rc_params = mpl.rcParams.copy()

# Import seaborn objects
from .rcmod import *
from .utils import *
from .palettes import *
from .regression import *
from .categorical import *
from .distributions import *
from .timeseries import *
from .maprint(df.shape)trix import * THIS ONE WHEN I TRY TO PLOT
from .miscplot import *
from .axisgrid import *
from .widgets import *
from .xkcd_rgb import xkcd_rgb
from .crayons import crayons
from . import cm

This is the error init__.py", line 13
    from .print(df.shape)trix import *

Can anyone help me please

**Comment by mwaskom** [comment]
It looks like you have added text that corrupted your `seaborn/__init__.py`. I'm not sure how that happened, but removing it will fix the problem.
