### ISSUE TITLE
boxplot with hue argument deviate from center

### ISSUE THREAD

**Issue by Alalalalaki** [mwaskom/seaborn#1821]
For example I have a data like this. I want to boxplot the value by country and want the colors based on continent.
![image](https://user-images.githubusercontent.com/31154974/64067403-f6bdb580-cc62-11e9-9e95-4fc8bd96c8d5.png)

The 'hue` argument works but as one country can only belong to one continent the bar and line deviate from the ticks in x-axis.

![image](https://user-images.githubusercontent.com/31154974/64067455-ab57d700-cc63-11e9-8541-b1983a339495.png)

Is this a situation that I should customize the palette? But in that case I find I also have to customize the legend box which I am not sure how to do.

Thanks.

**Comment by mwaskom** [comment]
Add `dodge=False`.
