### ISSUE TITLE
jointplot with reg can not make the proper regression line

### ISSUE THREAD

**Issue by rifatSDAS** [mwaskom/seaborn#1822]
Hi, I am using jointplot with kind 'reg'. The r2 value and distribution of points cloud are perfect. However, draw the regression line seems like not working well. Any idea or solution for this? I have attached the figure I made and the part of code I used for ploting. For your information, my x and y variables are 2D numpy array. In the figure, I want to draw the regression line like the red line, not like the black line.

`import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

sns.set(style="ticks")
sns.set_context("paper")

def r2(ras1, ras2):
    return stats.pearsonr(ras1, ras2)[0] ** 2
#ras1 and ras2 are geotiff raster files, and I converted them into 2D numpy array
limX = plt.xlim(np.min(ras1), np.max(ras1))
limY = plt.ylim(np.min(ras2), np.max(ras2))

sns.jointplot(ras1, 
                    ras2, 
                    kind = "reg", 
                    color="k", 
                    height=7, 
                    stat_func=r2,
                    xlim=limX,
                    ylim=limY);
# Calculate and plot regression equation
x = ras1
y = ras2
z = np.polyfit(x.flatten(), y.flatten(), 1)
p = np.poly1d(z)
plt.plot(x,p(x),"r--")
plt.title("y=%.4fx+%.4f"%(z[0],z[1]), fontsize=12) 

plt.suptitle("Title", fontsize=16)
plt.xlabel("X", fontsize=12)
plt.ylabel("X", fontsize=12)
plt.tight_layout()`

![image](https://user-images.githubusercontent.com/31696555/64176732-5207c780-ce5e-11e9-9b2d-7418d21d3997.png)

**Comment by mwaskom** [comment]
You haven't provided a reproducible example, andI can't replicate the problem you're seeing. But `x` and `y` in jointplot need to be vectors.

**Comment by mwaskom** [comment]
```python
n = 100
x = np.random.randn(n) + 200
y = 3 * x - 1 + np.random.randn(n) * 2

g = sns.jointplot(x, y, kind="reg")
xx = np.linspace(x.min(), x.max(), 100)
fit = np.polyfit(x.flat, y.flat, 1)
g.ax_joint.plot(xx, np.poly1d(fit)(xx), color="r")
```
![image](https://user-images.githubusercontent.com/315810/64184757-f1669380-ce39-11e9-85f6-bc83184510bb.png)
