### ISSUE TITLE
Feature request: boxenplot wider by point count

### ISSUE THREAD

**Issue by vedal** [mwaskom/seaborn#1827]
In sns.violinplot, setting `scale='count'` resizes width to the relative size of the category being plotted. It would be great if such an option was available for sns.boxenplot, but for the time being the 'scale' parameter here instead scales the boxes relative to _each other_.

**Comment by MaozGelbart** [comment]
Just linking to the related issue opened on ``boxplot`` #1668

**Comment by mwaskom** [comment]
Closing in favor of #1668, I'm not sure if this will get implemented but if it does it should be trivial to add it to both functions.
