### ISSUE TITLE
Re: pairplot, setting height=2 makes the plots very small, but only with my dataframe

### ISSUE THREAD

**Issue by izaakm** [mwaskom/seaborn#1833]
I'm having this problem, and I'm stumped about how to continue to trouble shoot it.

When I set the `height=2` in a pairplot, the plots are smaller than when `height=1`. I also get this warning message:

```
UserWarning: Tight layout not applied. The left and right margins cannot be made large enough to accommodate all axes decorations. 
  fig.tight_layout()
```

```python
# pdist_results is a pandas.DataFrame with a hierarchical index.
plotdata = pdist_results.loc[('otus-clean', 'raw', ['braycurtis', 'dice']), ]
plotdata = plotdata.T  # Now columns are hierarchical.
for height in range(1,5):
    plt.figure()
    sns.pairplot(data=plotdata, height=height, markers='.')
    plt.suptitle('height={h}'.format(h=height))
```

Here's a screenshot of the problem:

![Screenshot 2019-09-10 12 22 09](https://user-images.githubusercontent.com/1505395/64632209-a9f67f00-d3c6-11e9-8185-267d95dba5d2.png)

I've tried creating a minimal example, but I haven't been able to reproduce the problem. For example, this code creates a dataframe similar to mine, but works fine:

```python
idx = pd.MultiIndex.from_product([list('abc'), list('def'), list('ghi')])

dat = np.random.random((len(idx), 1000))
df = pd.DataFrame(dat, index=idx).sort_index()

plotdata = df.loc[('a', 'd', ['h', 'i']),]
plotdata = plotdata.T

for height in range(1,5):
    plt.figure()
    sns.pairplot(data=plotdata, height=height, markers='.')
    plt.suptitle('height={h}'.format(h=height))
```

I also tried extracting the values from my original dataframe and plotting those with `seaborn.pairplot`, and the `height` works as expected.

![montage](https://user-images.githubusercontent.com/1505395/64633536-5cc7dc80-d3c9-11e9-9d5c-594f6e77ff1e.png)

**Do you have any thoughts on why this might be happening? Or how I might continue to trouble shoot this?**

**Comment by MaozGelbart** [comment]
This has to do with very long column names. Here's an reproducible example on a dataframe with a similar code, using matplotlib functions only:
```python
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

idx = pd.MultiIndex.from_product(
    [
        ["longindexname1"],
        ["longindexname2"],
        ["longindexname3", "longindexname4"],
    ]
)
dat = np.random.random((len(idx), 1000))
df = pd.DataFrame(dat, index=idx).sort_index()
plotdata = df.loc[
    (
        "longindexname1",
        "longindexname2",
        ["longindexname3", "longindexname4"],
    ),
]
plotdata = plotdata.T

for height in range(1, 5):

    nrows = ncols = 2
    fig, axes = plt.subplots(
        nrows,
        ncols,
        figsize=(height * nrows, height * ncols),
        sharex="col",
        sharey="row",
        squeeze=False,
    )

    labels = [
        (
            "longindexname1",
            "longindexname2",
            "longindexname3",
        ),
        (
            "longindexname1",
            "longindexname2",
            "longindexname4",
        ),
    ]
    for ax, label in zip([0, 2], labels):
        axes.flat[ax].set_ylabel(label)
    for ax, label in zip([2, 3], labels):
        axes.flat[ax].set_xlabel(label)
    for i in range(4):
        axes.flat[i].scatter(
            plotdata[labels[0]], plotdata[labels[1]]
        )
    fig.tight_layout()
    plt.show()
```

Running the code emits the following warning from the ``fig.tight_layout`` for ``height=1`` and ``height=2``: 
```python
UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations
  fig.tight_layout()
```
However, for ``height=3`` (and ``height=4`` but is less distinguished) ``tight_layout`` is able to resize the axes to fit the long row/column labels, and you can see the size change. My advice is to plot with a large enough height and maintain column names short, or adjust the text size to be smaller.

**Comment by mwaskom** [comment]
Thanks @MaozGelbart I think the answer here is that this example hit a weird corner case of the matplotlib tight_layout algorithm. I don't think there's anything to do here on the seaborn side.
