### ISSUE TITLE
Clustermap first and last row are incompletely rendered (not square)

### ISSUE THREAD

**Issue by mycarta** [mwaskom/seaborn#1834]
With reference to[ this notebook tutorial](https://github.com/mycarta/Data-science-tools-petroleum-exploration-and-production/blob/master/Python/notebooks/Python_data_science_tools%20_petroleum_exploration_production_distance_correlation_and_clustering.ipynb) I wrote, and last updated a month ago, this is a plot of clustermap passing a pre-computed Distance Correlation matrix:

![image](https://user-images.githubusercontent.com/7424763/64877609-ffbd6800-d60e-11e9-80c0-f2fc81a17436.png)

As of this week, it looks like this:
![image](https://user-images.githubusercontent.com/7424763/64877671-1f549080-d60f-11e9-9c03-49190879ec18.png)

with first and last rows of squares chopped off, and the labels not centered but distributed evenly so the first and last align with the heatmap top and bottom.

In both cases I was working with a Python 3.6 virtual environment, but I did a full Anaconda reinstallation in between.

**Comment by mycarta** [comment]
Closing it as this is a `matplotlib` issue: https://github.com/matplotlib/matplotlib/issues/15179#issuecomment-527839714

**Comment by bilalProgTech** [comment]
This works for me

g = sns.clustermap(df.corr(), figsize=(12,8), z_score=1, cbar_kws={"label": "color bar"}, annot=True)
fig = plt.gcf()
plt.gcf().get_axes()[2].set_ylim(bilateral.shape[1]+0.5, -0.5)
print(plt.gcf().get_axes()[1])

**Comment by bilalProgTech** [comment]
This works for me

g = sns.clustermap(df.corr(), figsize=(12,8), z_score=1, cbar_kws={"label": "color bar"}, annot=True)
fig = plt.gcf()
plt.gcf().get_axes()[2].set_ylim(df.shape[1]+0.5, -0.5)
plt.show()

**Comment by mwaskom** [comment]
This has been fixed in matplotlib for some time. Upgrade to 3.1.2 or 3.2.x to avoid.
