### ISSUE TITLE
pairplot, PairGrid, kills spyder session

### ISSUE THREAD

**Issue by quantumkylew** [mwaskom/seaborn#1839]
commands such as 
g=sns.pairplot(dataset);
are killing my spyder session, with just hte error: python quit unexpectedly.
sns.heatmap works fine, and its not the size of the panda's dataset. Any ideas what is going on?

**Comment by mwaskom** [comment]
Really hard to say without knowing anything else about your setup, dataset, console output, etc.

**Comment by quantumkylew** [comment]
turned out to be the number of columns in my dataset... apparently it can't handle for than 5 or so

**Comment by mwaskom** [comment]
That's certainly not generally true, but maybe you have a very large dataset, not enough memory, or some other specific issue. Glad it's figured out.
