### ISSUE TITLE
Pairplot diagonal_kind='hist' doesn't plot a stacked histogram

### ISSUE THREAD

**Issue by arashmath** [mwaskom/seaborn#1840]
Hi. While I was trying to plot a pairplot (with a hue value), I realized that a previous version of seaborn had a stacked histogram for the default mode. But when I tried the same code I found, I got "kde"s on the diagonal, and when I tried diagonal_kind='hist', I got one histogram covering the other one, and not stacked on top of each other. Is there a solution for this matter?
The code was from here:
[Data Science and Machine Learning bootcamp](https://github.com/trapatsas/Python-Data-Science-and-Machine-Learning-Bootcamp/blob/master/Machine%20Learning%20Sections/K-Nearest-Neighbors/K%20Nearest%20Neighbors%20Project.ipynb)
Thanks.

**Comment by mwaskom** [comment]
Hi — Indeed this has been removed.
