### ISSUE TITLE
lineplot error bands for timeseries data

### ISSUE THREAD

**Issue by darkdragon-001** [mwaskom/seaborn#1841]
I would like to use `lineplot` with its nice error bands.Unfortunately this only works when multiple data points are at the _same_ `x` position. I often have measured timeseries data, so `x` is increasing slowly and _never_ the same.

Currently, I worked around this problem by using panda's `df.rolling()`:
```python
# moving average
rolling = df['y'].rolling(30, center=True)
ma = rolling.mean()
plt.plot(df['x'], ma, linewidth=2)
# standard derivation bands
mstd = rolling.std()
plt.fill_between(df['x'], ma-2*mstd, ma+2*mstd, alpha=0.2)
```

It would be nice, if you could add a parameter to `lineplot()` which mimics this behavior.

**Comment by mwaskom** [comment]
Thanks for the suggestion but this is unlikely to integrate well into the current code so I am going to pass.
