### ISSUE TITLE
Calibration curve

### ISSUE THREAD

**Issue by ohadle** [mwaskom/seaborn#1843]
Would be useful to be able to plot a calibration curve, describing how close predicted scores are to probabilities.
Ideally along the lines of this:
https://rdrr.io/github/BavoDC/CalibrationCurves/man/val.prob.ci.2.html

Or this:
https://rdrr.io/cran/rms/man/val.prob.html

But could also start with something like this:
https://scikit-learn.org/stable/modules/generated/sklearn.calibration.calibration_curve.html#sklearn.calibration.calibration_curve

**Comment by mwaskom** [comment]
Thanks for the suggestion but probably belongs in one of the viz packages that are designed to integrate directly with scikit learn.

**Comment by ohadle** [comment]
Got it, thanks!
I do see an issue in yellowbrick now:
https://github.com/DistrictDataLabs/yellowbrick/issues/365

If there's any other relevant libraries I'd be keen to know.

**Comment by mwaskom** [comment]
Yellowbrick was what I had in mind, although I that scikit learn itself is also now looking to add some plotting capabilities that are based directly with their estimator objects.
