### ISSUE TITLE
Feature request: Heatmap with Totals displayed along axes

### ISSUE THREAD

**Issue by rgpdx** [mwaskom/seaborn#1845]
Background
I and possibly many others use the sns.heatmap function with pandas pivot tables. Many times, it is beneficial to use the pd.pivot_table  function with margins = True to give out row and column totals.

I typically never use sns.heatmap with the margins = True from pivot tables because it throws off the colormap and makes it hard to see the variation in the data due to the totals overwhelming the smaller numbers. Using vmin/vmax options is not always a good idea since some row totals are actually equal to the data presented in the heatmap.

Feature request -
It would be nice to have totals displayed on the heatmap similar to how they are displayed on a sns.jointgrid plot as histograms or simply as numbers with their own color mapping which is independent of the colormap used for the data.

**Comment by mwaskom** [comment]
This wouldn’t really work in heatmap, which is an axes-lever function. You actually could combine heatmap and countplot in a joint grid if you want, though.
