### ISSUE TITLE
[Feature Request] Lower triangle parameter for heatmap

### ISSUE THREAD

**Issue by tuliocasagrande** [mwaskom/seaborn#1849]
Hi,

One analysis that I use all the time is to plot the features correlation using heatmap:

```python
corr = np.corrcoef(np.random.randn(10, 200))
sns.heatmap(corr, vmax=.3, square=True)
```
![image](https://user-images.githubusercontent.com/1420513/66272570-c230b100-e841-11e9-95ff-8a65f871314d.png)

However, as the correlation matrix grows, the full heatmap can become cluttered and harder to explain especially to business stakeholders. To improve that, I use the `mask` parameter:

```python
corr = np.corrcoef(np.random.randn(10, 200))
mask = np.zeros_like(corr)
mask[np.triu_indices_from(mask)] = True
sns.heatmap(corr, vmax=.3, square=True, mask=mask)
```

![image](https://user-images.githubusercontent.com/1420513/66272657-0ff9e900-e843-11e9-9383-2e56d2f1847b.png)

I'm wondering if this is a common usage of the `mask` parameter and if it would make sense to add a `lower` parameter that would encapsulate the logic to produce the upper-triangle indices.

In practice, this would add before https://github.com/mwaskom/seaborn/blob/222d54467685b96ec9fabb32a9b382e35c745b1f/seaborn/matrix.py#L112
a snippet similar to this one:

```python
if lower:
    if mask is not None:
        raise ValueError("lower cannot be used with mask.")

    mask = np.zeros_like(data)
    mask[np.triu_indices_from(mask)] = True
```

Thank you for reviewing this proposal!

**Comment by mwaskom** [comment]
It’s probably common, since there is an example that demonstrates it in the docs. I don’t think it needs its own parameter though.
