### ISSUE TITLE
AttributeError: type object 'pandas._libs.lib.Seen' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by ashishpatel26** [mwaskom/seaborn#1852]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-258c8e1c9a07> in <module>
      2 # import multiprocessing as mp
      3 from sklearn import *
----> 4 import seaborn as sns
      5 import time
      6 from tqdm import tqdm

~\.conda\envs\python3.6\lib\site-packages\seaborn\__init__.py in <module>
      4 
      5 # Import seaborn objects
----> 6 from .rcmod import *
      7 from .utils import *
      8 from .palettes import *

~\.conda\envs\python3.6\lib\site-packages\seaborn\rcmod.py in <module>
      3 import functools
      4 import matplotlib as mpl
----> 5 from . import palettes, _orig_rc_params
      6 
      7 

~\.conda\envs\python3.6\lib\site-packages\seaborn\palettes.py in <module>
     10 from .external.six.moves import range
     11 
---> 12 from .utils import desaturate, set_hls_values, get_color_cycle
     13 from .colors import xkcd_rgb, crayons
     14 

~\.conda\envs\python3.6\lib\site-packages\seaborn\utils.py in <module>
      6 import numpy as np
      7 from scipy import stats
----> 8 import pandas as pd
      9 import matplotlib as mpl
     10 import matplotlib.colors as mplcol

~\.conda\envs\python3.6\lib\site-packages\pandas\__init__.py in <module>
     28 
     29 try:
---> 30     from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
     31 except ImportError as e:  # pragma: no cover
     32     # hack but overkill to use re

pandas\_libs\lib.pyx in init pandas._libs.lib()

AttributeError: type object 'pandas._libs.lib.Seen' has no attribute '__reduce_cython__'

**Comment by mwaskom** [comment]
This looks like a broken pandas install, I don’t think it has anything to do with seaborn

**Comment by ashishpatel26** [comment]
My pandas is working fine. I don't know what is this issue. I tried to solve by facing same error again,
