### ISSUE TITLE
URLError: <urlopen error [Errno 11001] getaddrinfo failed>

### ISSUE THREAD

**Issue by shaminder1** [mwaskom/seaborn#1855]
I tried to import the data set but it throws an error.

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

**sns.load_dataset('iris')**

-----Error msg file attached
[Help - Copy.txt](https://github.com/mwaskom/seaborn/files/3738112/Help.-.Copy.txt)

**Comment by mwaskom** [comment]
Can your computer see the internet?

But you don't actually need to download the example data to do any real work with seaborn. That function just exists for examples and bug reports.

**Comment by shaminder1** [comment]
Someone helped me on that,
iris=sns.load_dataset('iris') loads local directory if not get connected to URL !

it could be useful for others.. Solution is
1)find the location of the default cache by using sns.utils.get_data_home() - it is %homedir%\seaborn-data in conda/jupyter/spyder notebook
2) Downloading https://github.com/mwaskom/seaborn-data/ as a zip file and extracting the contents of the enclosed seaborn_data_master directory to "seaborn-data" in home directory.

sns.load_dataset('XXXXX') now works!
Optional : add environment variable named Seaborn_Data, directory will be where you have saved the downloaded data.

**Comment by ademikel** [comment]
This worked.
Thanks
