### ISSUE TITLE
Error when calling regplot *_partial on Series data.

### ISSUE THREAD

**Issue by danlurie** [mwaskom/seaborn#1856]
I have encountered an issue where Seaborn throws an error when passing a Pandas Series into `regplot` while using`*_partial`. The error does not occur if one passes identical data via NumPy arrays or using `Series.values`, or when passing Series to `regplot` without `*_partial`.

Example notebook here: https://nbviewer.jupyter.org/gist/danlurie/7d9431c684885345c84a0f15eabccc06

Update: I'm running Pandas 0.24.2 (forgot to include that in the notebook).

**Comment by mwaskom** [comment]
Thanks, see also https://github.com/mwaskom/seaborn/pull/1755

**Comment by MaozGelbart** [comment]
Closed in #1898 , the above code now works on master.
