### ISSUE TITLE
clustermap clips part of the figure

### ISSUE THREAD

**Issue by javadnoorb** [mwaskom/seaborn#1857]
I'm noticing a new behavior in clustermap. The top and bottom of the figure get clipped. The command used to produce complete squares a few months ago. Here's an example:
![image](https://user-images.githubusercontent.com/26352146/67225950-1f139600-f402-11e9-98cc-2547bda5d4a4.png)

For your records, I ran the following code:
```python
%matplotlib inline
import numpy as np
import seaborn as sns
np.random.seed(98)
x = np.random.rand(10,10)
sns.clustermap(x)
```

It just looks like a bug, so I thought I'd report it.

Thanks.

**Comment by mwaskom** [comment]
It’s a matplotlib big and a duplicate. I’m on my phone right now because traveling but you will find more information if you search.

**Comment by javadnoorb** [comment]
xref #1773
Sorry for the duplicate.
