### ISSUE TITLE
[Feature request] show rug below axis or on top to not hide crucial info

### ISSUE THREAD

**Issue by johann-petrak** [mwaskom/seaborn#1859]
When `rug=True` is specified with `distplot` the dense placement of the rug lines can hide important info from the histogram or kde depending on the distribution of the data. 
For such situations it would be extremely useful to place the rug either below the axis, or on top of the graph or otherwise in a way where it is added instead of overlaid over useful information. 

In this example the rug hides the way how the distribution decreases towards close to zero density, but the rug also shows how the long tail is caused by just a few instances with extreme values. It would be very useful to show both, but with the rug not hiding the very important details:
![distplot_rug](https://user-images.githubusercontent.com/619106/67857875-292b4800-fb18-11e9-81d9-2fdd07386744.png)
![distplot_norug](https://user-images.githubusercontent.com/619106/67857884-2fb9bf80-fb18-11e9-9e7b-ef195d157177.png)

**Comment by mwaskom** [comment]
e.e. 

```
x = np.random.gamma(4, 1, 1000)
ax = sns.distplot(x, kde=False, rug=True)
ax.set_ylim(-.06 * ax.get_ylim()[1])
```
