### ISSUE TITLE
Wrong color in legend when passing both hue and style attributes

### ISSUE THREAD

**Issue by vlbrown** [mwaskom/seaborn#1862]
My code:
```
    sns.scatterplot('x','y', data=pca, style='cluster_id', hue='cluster_id', 
                palette="Set1", alpha=1, s=80)
```
The resulting plot:
<img src="http://wiki.cfcl.com/pub/Vicki/Tmp/SeabornIssue/Screenshot2019-11-04.png">

Note that cluster '2' is represented by red squares but the legend shows black squares.

**Comment by mwaskom** [comment]
Thanks — constructing an example that can be reproduced would be particularly helpful, however.

**Comment by vlbrown** [comment]
```
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

pca = pd.read_csv("Data/pca.csv")

# Plot a scatterplot of the x vs y columns
# Color-code points differently based on cluster ID

sns.set(rc={'figure.figsize':(11.7,8.27)})
sns.set_style('whitegrid')

sns.scatterplot('x','y', data=pca, style='cluster_id', hue='cluster_id', 
                palette="Set1", alpha=1, s=80)
plt.title('PCA-reduced Clusters (2D)')
plt.show()
```

[Data.zip](https://github.com/mwaskom/seaborn/files/3807301/Data.zip)

**Comment by mwaskom** [comment]
The explanation is that the scatterplot legend is getting confused because it is interpreting the hue variable as numeric and is trying to draw a "brief" legend. The easiest way to get a correct legend is to specify that you want a "full" legend:

```
sns.scatterplot('x','y', data=pca, style='cluster_id', hue='cluster_id', 
                palette="Set1", alpha=1, s=80, legend="full")
```
![image](https://user-images.githubusercontent.com/315810/68229983-3a67cf00-ffc6-11e9-9280-8950cec4a20b.png)

But you still have the problem that it's slicing into a categorical colormap with numeric levels. I would fix that by passing a list of colors that you want explicitly:

```
sns.scatterplot('x','y', data=pca, style='cluster_id', hue='cluster_id', 
                palette=sns.color_palette("Set1", 5), alpha=1, s=80)
```
![image](https://user-images.githubusercontent.com/315810/68230015-4b184500-ffc6-11e9-95c8-ec6f2247a94b.png)

**Comment by vlbrown** [comment]
>It's slicing into a categorical colormap with numeric levels.

They may look like numbers, but pandas knows they're categories.

>>  the scatterplot legend is getting confused because it is interpreting the hue variable as numeric and is trying to draw a "brief" legend

How would anyone be expected to know this? The Principal of Least Surprise suggests using the same color and shape in the legend that is use in the plot.


On Nov 5, 2019, at 09:27 , Michael Waskom <notifications@github.com> wrote:

The explanation is that the scatterplot legend is getting confused because it is interpreting the hue variable as numeric and is trying to draw a "brief" legend. The easiest way to get a correct legend is to specify that you want a "full" legend:

sns.scatterplot('x','y', data=pca, style='cluster_id', hue='cluster_id', 
                palette="Set1", alpha=1, s=80, legend="full")
 <https://user-images.githubusercontent.com/315810/68229983-3a67cf00-ffc6-11e9-9280-8950cec4a20b.png>
But you still have the problem that it's slicing into a categorical colormap with numeric levels. I would fix that by passing a list of colors that you want explicitly:

sns.scatterplot('x','y', data=pca, style='cluster_id', hue='cluster_id', 
                palette=sns.color_palette("Set1", 5), alpha=1, s=80)
 <https://user-images.githubusercontent.com/315810/68230015-4b184500-ffc6-11e9-95c8-ec6f2247a94b.png>
