### ISSUE TITLE
Specifying 'c' in scatterplot fails.

### ISSUE THREAD

**Issue by rmatsumiya** [mwaskom/seaborn#1864]
I'd like to plot with non-pandas data in one Axes like:
```python
a = A()
...something...
a.plot([0, 1, 3, 5], [1, 3, 4, 5])
...something...
class A()
    def plot(self, x, y):
         sns.scatterplot(x, y, ax=self.__ax) # self.__ax has already set.
```

Also, changing point color is needed for each calling `A.plot()`.
So, I modified like this:
```python
a = A()
...something...
a.plot([0, 1, 3, 5], [1, 3, 4, 5])
...something...
class A():
    def plot(self, x, y):
         sns.scatterplot(x, y, ax=self.__ax, c=self.nextcolor()) # nextcolor() returns a (random) RGB color code like #f0f0f0.
```

In such cases, matplotlib throws an error `len() of unsized object`.

In my observation, `relational.py` converts `c` into `numpy.ndarray`.
https://github.com/mwaskom/seaborn/blob/222d54467685b96ec9fabb32a9b382e35c745b1f/seaborn/relational.py#L917
Because of this converting, matplotlib deals `c` as a non-string object.

So, I attempted to take a workaround like:
```python
class A():
    def plot(self, x, y):
         sns.scatterplot(x, y, ax=self.__ax, c=[self.nextcolor()] * len(x)) # nextcolor() returns a (random) RGB color code like #f0f0f0.
```

As #1682 , this also throws an error.
```
                        "'c' argument has {nc} elements, which is not "
                        "acceptable for use with 'x' with size {xs}, "
                        "'y' with size {ys}."
                            .format(nc=n_elem, xs=xsize, ys=ysize)
```

**Comment by mwaskom** [comment]
I don’t think the context is fully clear enough from this example, which is not reproducible, but have you tried using `color`? Otherwise this may be more of a stackoverflow question.
