### ISSUE TITLE
sns.pairplot hue parameter: why is it also reordering the values?

### ISSUE THREAD

**Issue by Stemanz** [mwaskom/seaborn#1865]
Hello,

unlike other plots, in `pairplot` the `hue` parameter does more than just applying colors to data, it reorders it.
From the doc, about `hue`:

> Variable in data to map plot aspects to different colors.

It should just be mapping colors to data, and stick to that.
`hue_order` just orders the legend, and I've found no way of telling `pairplot` to just map the colors without reordering the values.

```
data = {
    "hue": ["B", "A", "B", "C", "B", "A", "B", "A", "A", "C", "C", "C"],
    "label": ["label_6", "label_3", "label_7", "label_9", \
              "label_8", "label_1", "label_5", "label_2", \
              "label_4", "label_10", "label_12", "label_11"],
    "value": [6, 9, 18, 23, 121, 220, 269, 318, 554, 984, 1072, 1656]
}
df = pd.DataFrame(data)

#just right
plot = sns.pairplot(df, x_vars=["value"], y_vars=["label"])

#Unexpected behaviour
plot = sns.pairplot(df, x_vars=["value"], y_vars=["label"], hue="hue")
```

![download-2](https://user-images.githubusercontent.com/7668172/68301200-bbdf6000-009f-11ea-9b4a-9bd6bfaa642c.png)
![download-3](https://user-images.githubusercontent.com/7668172/68301218-c4d03180-009f-11ea-8ce2-36e3d4be416b.png)

**Comment by mwaskom** [comment]
Because pairplot draws three separate plots, each in a different color, when you use hue. The earlier plots have no way of knowing that later calls will add more categories. 

You should use PairGrid and scatterplot directly, setting the hue variable on the latter.

**Comment by Stemanz** [comment]
Excellent, thanks!

```python
data = {
    "hue": ["B", "A", "B", "C", "B", "A", "B", "A", "A", "C", "C", "C"],
    "label": ["label_6", "label_3", "label_7", "label_9", \
              "label_8", "label_1", "label_5", "label_2", \
              "label_4", "label_10", "label_12", "label_11"],
    "value": [6, 9, 18, 23, 121, 220, 269, 318, 554, 984, 1072, 1656]
}
df = pd.DataFrame(data)

grid = sns.PairGrid(df, x_vars=["value"], y_vars=["label"])
grid.map(sns.scatterplot, hue=df["hue"])
```
![download-4](https://user-images.githubusercontent.com/7668172/68306546-08c83400-00aa-11ea-8242-27aa133d48bf.png)

**Comment by mwaskom** [comment]
By the way, if you’re not going to plot multiple variables, there’s absolutely no reason to use pairplot/pairgrid at all. But of course I don’t know what your real usecase is ...
