### ISSUE TITLE
Categorical plots silently drop data if `x` is of type pandas.Series (and an index is present)

### ISSUE THREAD

**Issue by mgbckr** [mwaskom/seaborn#1867]
When plotting categorical data (`swarmplot`, `boxplot`) and `x` is a `pandas.Series`, `seaborn` drops/reorders data based on the index of `x`. Here is an example:

```python
import pandas
import numpy
import seaborn
from matplotlib import pyplot as plt
x = pandas.Series([1,1,1,1], index=[0,2,4,6])
y = numpy.array([1,2,3,4])
seaborn.swarmplot(x=x, y=y)
plt.figure()
seaborn.swarmplot(x=x.values, y=y) 
```
![image](https://user-images.githubusercontent.com/1241516/68346541-3e205200-00a9-11ea-901b-51af94fbba05.png)
![image](https://user-images.githubusercontent.com/1241516/68346547-41b3d900-00a9-11ea-8af3-b105e88e3709.png)

As you can see the `2` and `4` are dropped silently by `seaborn`. This is seriously unexpected behavior in my opinion. Here are my thoughts on this:

* In no scenario should `seaborn` just silently discard data. At least a warning should be presented.
* Since `y` has no "intentional" index, the index of `x` should be discarded also.
* If this behavior is intended, a warning or error should be thrown if some of the values in `x` are discarded since `x` and `y` effectively are of different size. This is also true for cases when `x` and `y` both are `pandas.Series`.
* I would prefer a warning in general if any reordering and matching happens, but that may be personal preference.   

Probably related to: #1139

**Comment by mwaskom** [comment]
This likely has a relatively easy fix in seaborn. I would say that as a general rule, though, mixing numpy arrays and pandas objects with non-default indices is a bad idea and likely to hit weird corner cases like you have here (and not just in seaborn).

**Comment by mwaskom** [comment]
Also it is related to #1139 in that what that issue is requesting is behavior that you are describing as "seriously unexpected". So perhaps you can appreciate the complexities of the issue....

**Comment by mgbckr** [comment]
Hi @mwaskom, thanks for your answers :) 

> I would say that as a general rule, though, mixing numpy arrays and pandas objects with non-default indices is a bad idea and likely to hit weird corner cases like you have here (and not just in seaborn).

When you work with `sklearn` and `pandas` at the same time this can simply happen by accident. Generally at least a warning should be issued when mixed types are provided (and that would make a difference). In a typed language we would not have this issue. In an untyped one, we need to be mindful of these things especially when we support two specific frameworks (`numpy` and `pandas`) that should (?) be interchangeable.

>  Also it is related to #1139 in that what that issue is requesting is behavior that you are describing as "seriously unexpected". So perhaps you can appreciate the complexities of the issue....

I totally understand the reasoning of #1139. While I am not a fan, it's definitely reasonable. But in my case 1) I am working with a `numpy` array which does not have an explicit index. And 2), my issue is about **dropping** values. If you give `swarmplot` two numpy arrays with different sizes, it will also complain.
