### ISSUE TITLE
`seaborn.pairplot` doesn't illustrate discriminative power of two features as well as it should

### ISSUE THREAD

**Issue by prinsherbert** [mwaskom/seaborn#1868]
`seaborn.pairplot` uses a z-order w.r.t. the parameter specified as `hue`. This means certain classes end up on top of others. One can set the `plot_csw = {'alpha': ...}` parameter, but it still adds bias for the top hue's to be more prominent and salient.

This way the overlap between different hue's becomes invisible, which is relevant to determine features that discriminate classes well.

Please add an option such that the z-order of all points is random, or consider other options to allow discrimination of hues.

**Comment by mwaskom** [comment]
This request is not possible because it fundamentally misses how the function works. Sorry.
