### ISSUE TITLE
For neuroscience papers, we really need the ci = 'sem' function

### ISSUE THREAD

**Issue by sm000000** [mwaskom/seaborn#1869]
I am a neuroscience researcher. Thank you so much for adding the ci = 'sd' feature in the last update.
If you have time, will you implement more features we need? ?

ci = 'sem' function. sem is the standard error.
In neuroscience papers, most charts are created with sem bars. Therefore, the figure made with seaborn cannot be used in the paper now ...

Since ci = 68 matches SEM only when it is normally distributed, it cannot be used basically.

Would you like to implement ci = 'sem' as soon as possible? ?

**Comment by mwaskom** [comment]
> Would you like to implement ci = 'sem' as soon as possible? ?

Nope.

**Comment by sm000000** [comment]
plz...
