### ISSUE TITLE
Black background color 

### ISSUE THREAD

**Issue by h0rd3** [mwaskom/seaborn#1870]
Greetings.

I'm quite a newbie to seaborn so I 'm having a bunch of problems with saving my graphics in a correct way. The thing which is happening is that I am always getting black background regardless of which parameters I use. However inside the notebook it seems to be ok.

I am using VSCode, writing in a jupyter nootbook .ipynb.

Screenshots are below.

<img width="1369" alt="Screenshot 2019-11-12 at 12 47 27" src="https://user-images.githubusercontent.com/48713543/68660748-d5beee00-054a-11ea-960b-4641c66a2ec1.png">
<img width="1305" alt="Screenshot 2019-11-12 at 12 47 33" src="https://user-images.githubusercontent.com/48713543/68660749-d5beee00-054a-11ea-8c4e-cb725a22185b.png">
<img width="1158" alt="Screenshot 2019-11-12 at 12 47 43" src="https://user-images.githubusercontent.com/48713543/68660750-d5beee00-054a-11ea-8a36-320ad0ea05b2.png">
[picture1.pdf](https://github.com/mwaskom/seaborn/files/3835430/picture1.pdf)

**Comment by mwaskom** [comment]
I don't think I understand. Is this a question about the black background of vscode? It may be a better question for stackoverflow.

**Comment by h0rd3** [comment]
Not sure really about if it should be at stackoverflow.

I see now that the last picture cannot be seen so here it goes.

The question is about the reason why saving a graphic gives me a black background instead of white one and how can this be fixed?

Actually I might have already fixed the problem by adding `plt.style.use(['classic'])` line in the head of the notebook, though I believe this might not be the real solution.

[picture1.pdf](https://github.com/mwaskom/seaborn/files/3836169/picture1.pdf)

**Comment by mwaskom** [comment]
Do you have any evidence that it’s a seaborn problem? What happens if you make a simple matplotlib plot? What happens if you don’t use viscose? If you can generate a simple reproducible example i can try to help; otherwise don’t have access to vscode and would again suggest stackoverflow.

**Comment by h0rd3** [comment]
The situation is slightly different when I am using `matplotlib` itself (basically, `matplotlib.pyplot`), the result is in the first picture.

It seems to be the problem only with the dark theme: in case it is changed to a light one, everything works just fine and white background is chosen. I've used both the custom theme I am using and VSC's official one.

In case I would change VSC for jupyter the situation is slightly the same with the original white theme, everything is white and nice.

 However, in case I change classical theme to another dark one, the .png output is still the same (white and good), while the graphic in the notebook breaks (see the picture).

[github_test.pdf](https://github.com/mwaskom/seaborn/files/3840342/github_test.pdf)

<img width="997" alt="Screenshot 2019-11-13 at 12 21 56" src="https://user-images.githubusercontent.com/48713543/68750325-bc807500-0610-11ea-8471-883f0f8b0114.png">

**Comment by mwaskom** [comment]
OK I understand this to be something about the vscode themes you're applying — again not really anything to do with seaborn itself, so I am going to close.
