### ISSUE TITLE
ValueError: fill value must be in categories

### ISSUE THREAD

**Issue by xrrain** [mwaskom/seaborn#1872]
In the  _preprocess_colors function, there is the code to replace na's with background color as the comment said, using `colors = colors.fillna('white')`, however, if the original colors do not contain the 'white' category, this line would raise the Pandas ValueError:fill value must be in categories in `Pandas 0.25.3`.

**Comment by mwaskom** [comment]
Can you please share a reproducible example that demonstrates the issue? I can't really figure out what you're talking about from this description.

**Comment by MaozGelbart** [comment]
Here's a self-contained example, using ``clustermap()``. This has to do with colors input for row/col colors that are pandas ``category`` dtype:
```python
import seaborn as sns; sns.set(color_codes=True)
iris = sns.load_dataset("iris")
species = iris.pop("species")
row_colors=species.map(dict(zip(species.unique(), "rbg")))
row_colors=row_colors.astype('category')
g = sns.clustermap(iris, row_colors=row_colors)
```

This raises the following error:
```
ValueError: fill value must be in categories
```

**Comment by mwaskom** [comment]
Thanks @MaozGelbart. It would still be helpful to understand the real-world case where the color annotations need to be categorical.

**Comment by brianpenghe** [comment]
Same issue here
