### ISSUE TITLE
JointGrid annotation raises DeprecationWarning but docs don't mention any deprecation

### ISSUE THREAD

**Issue by charlesoblack** [mwaskom/seaborn#1873]
Annotating a JointGrid (e.g.:)

```python
fg = sns.jointplot(x=x, y=y, data=df)
fg = fg.annotate(rsquare, template="{stat}: {val:.2f}", stat="$R^2$", loc="upper left", fontsize=12)
```

raises the following warning:

```
...\python37\lib\site-packages\seaborn\axisgrid.py:1847: UserWarning: JointGrid annotation is deprecated and will be removed in a future release.
  warnings.warn(UserWarning(msg))
```

However, the docs for JointGrid don't mention any deprecation, nor an alternative. Perhaps the alternative should be stated in the warning, too?

Additionally, if it is deprecated, when will it be removed?

**Comment by mwaskom** [comment]
Can’t get everything right.

**Comment by charlesoblack** [comment]
@mwaskom I don't mean to be annoying, but will something be done about this? Also, what is the alternative to `annotate` (if there is any)?

**Comment by millerh1** [comment]
I also have this question.

**Comment by charlesoblack** [comment]
The message was added in 0ef2c2e .... 2 years ago. Could the following lines be combined maybe?

https://github.com/mwaskom/seaborn/blob/3db4d5ac7ff3381bdf56b9727a43bb94ab6607ce/seaborn/axisgrid.py#L1865-L1867

**Comment by mwaskom** [comment]
Folks, the function warns that it’s deprecated, the docstring says it’s deprecated, and the release notes for the relevant version say it was deprecated. I consider this issue resolved.

**Comment by charlesoblack** [comment]
The docs don't mention it's deprecated. This is the relevant part - everyone looks at the docs first, not the release notes. I'd imagine you'd want a congruent library...

**Comment by charlesoblack** [comment]
Additionally, my comment above still raises a good point - what's the alternative to `annotate`?

**Comment by mwaskom** [comment]
I’m locking this issue because repeated assertions that “the docs don’t mention” something when it’s literally the second line of the docstring for the relevant function are bizarre and annoying.
