### ISSUE TITLE
how to make blue bars in front of red in histogram?

### ISSUE THREAD

**Issue by AlissaStuart** [mwaskom/seaborn#1874]
hello,

Is there a code that can bring forward blue bars in this histogram plot? If I remove alpha I can't see blue bars at all.  I'm using Seaborn for this plot

Thank you in advance 

```
g = sns.FacetGrid(df, hue='credit.policy', palette='coolwarm', height =5, aspect=2)
g = g.map(plt.hist, 'fico', alpha=0.8, bins=30).add_legend()
```

![FCO](https://user-images.githubusercontent.com/53910702/69254085-aa0fb980-0b83-11ea-9a38-2cf325a086a7.png)

**Comment by mwaskom** [comment]
Hi — I think this is a better question for StackOverflow, thanks.
