### ISSUE TITLE
sns.heatmap() generated incorrect sized plot in 0.9.0 release

### ISSUE THREAD

**Issue by subhadarship** [mwaskom/seaborn#1875]
```
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

data = np.random.rand(4, 6)
sns.heatmap(data)
plt.show()
```
The above code produces:

![image](https://user-images.githubusercontent.com/35211168/69266017-58bdf500-0b98-11ea-9e39-c79558a57e72.png)

In 0.8.1 release, the same code produces:

![image](https://user-images.githubusercontent.com/35211168/69266185-b0f4f700-0b98-11ea-8f6d-0dae770b7dbc.png)

**Comment by mwaskom** [comment]
This is a duplicate (it is a bug in matplotlib) i am on my phone but you will find several issues with more information if you search.
