### ISSUE TITLE
Docs for older versions

### ISSUE THREAD

**Issue by paulochf** [mwaskom/seaborn#1876]
Does seaborn have doc pages for older versions? I'm looking for 0.8.1 specifically, but I couldn't find it.

Thanks!

**Comment by mwaskom** [comment]
Not online, but you can always clone the repository and build locally.

**Comment by mwaskom** [comment]
(Or just browse the source on github. The tutorials are actually jupyter notebooks and the api documentation is pulled from the docstring on each function object).
