### ISSUE TITLE
Pass 'width' value to barplot

### ISSUE THREAD

**Issue by libmelo** [mwaskom/seaborn#1878]
Recently, when I plotted a bar graph, I passed a 'width' to' barplot' function. 
Such as `sns.barplot(x='len', y="cnt", data=df, color="#6495ED", width=1)`
But it told me I had passed the parameter. Then I found the class '_CategoricalPlotter' in 'categorical.py' assigned a 'width=.8' which was used by '_BarPlotter' of 'barplot'.
I think the 'barplot' could allow us to adjust the width of bar, even though we might not use it in general.
I used a 'if' statement to achieve my goal, but it seems not elegant. So I raised this issue.
seaborn 0.9.0 matplotlib 3.1.1

**Comment by mwaskom** [comment]
Yes, sorry — if you want to be able to customize everything you should use matplotlib directly.
