### ISSUE TITLE
Legend markers overlap with relplot with large markers

### ISSUE THREAD

**Issue by mojones** [mwaskom/seaborn#1880]
Not sure if this is considered expected/correct behaviour, but if so I'd love to know a workaround as i run into this a lot. 

When calling `relplot` with `size` argument, the size of the markers in the legend correctly reflect the size of the markers in the plot. This causes a problem with large sizes though, as the vertical spacing between legend markers isn't increased, leading to them overlapping:

```python
import seaborn as sns
df = sns.load_dataset('mpg')
sns.relplot(
    data = df.sample(50), # fake a sparse dataset
    x = 'mpg',
    y = 'displacement',
    size = 'horsepower',
    sizes = (20, 400)
)
```

![Selection_037](https://user-images.githubusercontent.com/893512/69625922-80510980-103f-11ea-8f21-8f57f1f1a6a2.png)

It feels like there should be some way to fix it by overriding the `labelspacing` legend parameter as described [here](https://matplotlib.org/3.1.1/api/legend_api.html) but I can't figure out how.

**Comment by mwaskom** [comment]
I can see how this might be annoying, but it's not obvious to me that arbitrarily-large spacing of legend entries is always going to be aesthetically preferable. Implementing that would also involve a bit of a hack in translating between coordinate systems. Given that the size dimension has ratio scaling, information is accurately communicated by the width of the element (which is not obscured) and so I am inclined to leave this as it is.

**Comment by mojones** [comment]
For anyone else who stumbles across this, the easiest workaround I've been able to find is to call

```python
sns.set(style='whitegrid', rc = {'legend.labelspacing': 1.2})
```

before plotting, which adds enough vertical spacing to fix the issue:

![Selection_014](https://user-images.githubusercontent.com/893512/69654788-44cd3400-106d-11ea-8511-32f35b3120b0.png)

**Comment by mwaskom** [comment]
Better to avoid interfering with other plots, use a context manager:

```python
with plt.rc_context({"legend.labelspacing": 1.2}):
     ...
```
