### ISSUE TITLE
Load-Dataset give URL error

### ISSUE THREAD

**Issue by rajkajave** [mwaskom/seaborn#1881]
While using load-dataset, give URLError: <urlopen error [WinError 10060].
How to configure proxy environment on windows 10?

**Comment by mwaskom** [comment]
This doesn't give me enough information to help, unfortunately, but I would suggest making a reproducible example and asking on stackoverflow.

**Comment by rajkajave** [comment]
Below error I get while using following command on python 3
tips = sns.load_dataset('tips')

![seaborn](https://user-images.githubusercontent.com/42833248/69711175-9d143c80-1126-11ea-95fe-8e081138641a.JPG)
