### ISSUE TITLE
Heatmap axes clipped (top/bottom) in Matplotlib 3.1.1

### ISSUE THREAD

**Issue by JWarmenhoven** [mwaskom/seaborn#1882]
Seems matplotlib 3.1.1 introduced this issue.

```python
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

sns.set()

# Load the example flights dataset and conver to long-form
flights_long = sns.load_dataset("flights")
flights = flights_long.pivot("month", "year", "passengers")

# Draw a heatmap with the numeric values in each cell
f, ax = plt.subplots(figsize=(9, 6))
sns.heatmap(flights, annot=True, fmt="d", linewidths=.5, ax=ax)

print(mpl.__version__)
```

![image](https://user-images.githubusercontent.com/7450204/69737511-c9cf5080-1134-11ea-8fb1-df784020830d.png)

![image](https://user-images.githubusercontent.com/7450204/69737392-9a204880-1134-11ea-9ba5-14edae253cff.png)

**Comment by mwaskom** [comment]
Yes this is well known  — search and you will find many issues about it.

**Comment by JWarmenhoven** [comment]
Ah, right. 
Apologies for the noise.
