### ISSUE TITLE
PairGrid plots hue category as variable if values are numeric or can be coerced to numeric

### ISSUE THREAD

**Issue by ivirshup** [mwaskom/seaborn#1883]
Here's a small example:

```python
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

iris = sns.load_dataset("iris")

iris["species_numeric"] = (
    iris["species"]
    .astype("category").cat.codes  # int encoding, [0, 1, 2]
)

(
    sns.PairGrid(iris, hue="species_numeric")
    .map_diag(sns.kdeplot)
    .map_offdiag(plt.scatter, s=.5)
)
```

![image](https://user-images.githubusercontent.com/8238804/69910226-bd603600-145b-11ea-8aba-c3e73ef92101.png)

This is maybe reasonable behaviour, but I would like this plot not to have a row/ column for the hue variable. To get around this I've tried inputting the data as categorical and as strings. The same plot will occur as long as `"species_numeric"` is coercible to ints. I.e. defining it in either of these ways will give the same plot as above:

```python
iris["species_numeric"] = (
    iris["species"]
    .astype("category").cat.codes  # int encoding, [0, 1, 2]
    .astype(str)
)

iris["species_numeric"] = (
    iris["species"]
    .astype("category").cat.codes  # int encoding, [0, 1, 2]
    .astype(str)
    .astype("category") # categories are now ["0", "1", "2"]
)
```

**Comment by mwaskom** [comment]
As you discovered in the other issue you commented on, this is intentional.

**Comment by ivirshup** [comment]
Could you please elaborate on why it's intentional? I'm wondering if this is something I could make a PR for, depending on the reasoning.
