### ISSUE TITLE
Feature request: categorical line plot

### ISSUE THREAD

**Issue by romunov** [mwaskom/seaborn#1884]
I have thoroughly enjoyed the functionality of seaborn, but hit a snag of what I thought would be a trivial plot.

I would like to plot a categorical lineplot, where one axis is numeric/date and the second one is categorical. This can be done for a point plot

```
import seaborn as sns

tips = sns.load_dataste('tips')
sns.catplot(x='tip', y='sex', data=tips, jitter=False, kind='strip')
```

![image](https://user-images.githubusercontent.com/544571/69917210-d5d44e80-1463-11ea-91ba-a18537bb24e3.png)

It would be nice if one could plot lines so as to appear points are connected with a line in what I imagine the following manner:

```
sns.catplot(x='tip', y='sex', data=tips, kind='line')
```

The result would be something along the lines of what I plotted with ggplot2 (R):

![image](https://user-images.githubusercontent.com/544571/69917179-8c83ff00-1463-11ea-87f5-f247861a725e.png)

(for a current workaround with `matplotlib` and `numpy` also [this solution on SO](https://stackoverflow.com/questions/59127083/how-can-i-plot-line-graph-with-categorical-and-numeric-datum-axes))

**Comment by mwaskom** [comment]
What additional information is conveyed by the lines here?

**Comment by romunov** [comment]
I guess an additional variable could be mapped to a line to denote certain kinds of "breaks" in the data.

**Comment by mwaskom** [comment]
As more recent matplotlibs have some support for categorical variables, you can get pretty close  with the current API.

```python
import seaborn as sns
tips = sns.load_dataset("tips")
sns.lineplot(x="total_bill", y="day", hue="day",
             estimator=None, marker="o", data=tips)
```

![image](https://user-images.githubusercontent.com/315810/69918410-8b40db00-143f-11ea-8b1e-17f91cdb472e.png)

**Comment by romunov** [comment]
Very good. Care to answer this in my [SO question](https://stackoverflow.com/questions/59127083/how-can-i-plot-line-graph-with-categorical-and-numeric-datum-axes)?
