### ISSUE TITLE
Question: why does plt.scatter does not use the seaborn palette?

### ISSUE THREAD

**Issue by kolibril13** [mwaskom/seaborn#1885]
Hi, I want to use the "dark" palette in a scatterplot:
The palette works fine in plt.plot, but in plt.scatter, I dont get the seaborn palette
![123](https://user-images.githubusercontent.com/44469195/69984884-6ed59900-153a-11ea-868f-b04c01633e35.png)
Any ideas?
Full notebook code is here:
```python
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
from sklearn.datasets import make_blobs
plt.rcParams['figure.dpi'] = 100  
current_palette = sns.color_palette("dark")
plt.figure()
sns.palplot(current_palette)

def sinplot(flip=1):
    x = np.linspace(0, 14, 100)
    for i in range(1, 7):
        plt.plot(x, np.sin(x + i * .5) * (7 - i) * flip)
sns.set_palette("dark")
plt.figure()
sinplot()

X, y_labels = make_blobs(
   n_samples=50, n_features=2,
   centers=5, cluster_std=0.8,
   shuffle=True, random_state=0
)

sns.set_palette("dark")
plt.figure()
plt.scatter(X[:,0], X[:,1], s=50, c= y_labels)
```
Thanks for reading this question! :)

**Comment by mwaskom** [comment]
This is really a matplotlib question, but the answer is that when you provide `plt.scatter` with `c=` it looks colors up in the colormap you provide to`cmap=` or the default in the `image.cmap` of the rc file.
