### ISSUE TITLE
Catplot does not maintain the same order of bars across multiple plot columns

### ISSUE THREAD

**Issue by DiegoEliasCosta** [mwaskom/seaborn#1886]
When using catplot for bar plots with multiple columns and shared y-axis, the bars in each column appear in a different order.

```
titanic = sns.load_dataset("titanic")
sns.catplot(y="class", x="survived", col="sex", kind="bar", data=titanic)
```

While the colors can still be used to identify the right category, I assumed the y-axis should be consistent across different columns.  Am I missing something? 
This can also be related to issue #1702, but I wasn't totally sure whether it boils down to the same problem.

When plotting with `sharey=False`, seaborn plots the chart as expected, but repeating the labels on the y-axis is sometimes not desirable. 

Lib versions:
- seaborn                            0.9.0    
- matplotlib                         3.1.0

**Comment by mwaskom** [comment]
Thanks for the report — I can reproduce it on matplotlib 3.1.0 but not on matplotlib 3.1.1. I believe it's related to a bug they had that appeared when the y axis was inverted (which happens for horizontal categorical plots). Can you try updating your matplotlib?

**Comment by DiegoEliasCosta** [comment]
You are right, I cannot reproduce the issue on either matplotlib 3.1.1 or 3.1.2.
Thanks! That was pretty fast :)

I will close the issue then.

**Comment by mwaskom** [comment]
>  Thanks! That was pretty fast :)

No problem; your clear report made it easy to diagnose.
