### ISSUE TITLE
Seaborn abline/diagonal

### ISSUE THREAD

**Issue by andhamel** [mwaskom/seaborn#1890]
In ggplot, one can simply plot a diagonal using `geom_abline(slope=m,intercept=b)`. 

Does there exist a function like this in Seaborn? For example, if I wanted to add a `y=x` line to my scatterplot, would that be possible?

**Comment by mwaskom** [comment]
No, there doesn't, sorry.

**Comment by mwaskom** [comment]
This now exists in matplotlib: https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.axline.html

**Comment by mwaskom** [comment]
(Or rather, will when matplotlib 3.3 is released).
