### ISSUE TITLE
[Question | Feature Request] Asserting that boostrap only over one column?

### ISSUE THREAD

**Issue by YannDubs** [mwaskom/seaborn#1891]
Imagine I have a a very wide dataframe that I plot using seaborn. The columns correspond different hyperparameters of a ML experiment, some of the those will be used as the style, x, y, hue, col, row, ... arguments

Is there a way to assert that once conditioned on all of the style, x, y, hue, col, row, ... arguments the bootstrapped confidence interval will only be computed over a given column. I.e. there's only that column that has non unique values and has not been conditioned over. Typically in machine learning, that column would be the run index or the seed used.

Of course I could manually check that before plotting by conditioning on all of the columns given as parameter and then check whether the only non unique column is the one I want. But seaborn already conditions on these columns so it would be relatively easy to add such assertion.

This might be too specific for a feature implemented in seaborn but I definitely see how people would want to use that.

Thanks for the awesome library :)

**Comment by YannDubs** [comment]
For completeness here is my current workaround :

```
def _assert_sns_vary_only_col(data, kwargs, col_vary_only):
    """
    Make sure that the only column that has not been conditioned over for plotting and has non
    unique values is `col_vary_only`.
    """
    conditioned_df = data
    for _, col in kwargs.items():
        if col not in data.columns:
            continue
        conditioned_df = conditioned_df[conditioned_df[col] == conditioned_df[col].unique()[0]]

    # make sure only `col_vary_only` varies
    if len(conditioned_df[col_vary_only].unique()) != len(conditioned_df):

        conditioned_df = conditioned_df[
            conditioned_df[col_vary_only] == conditioned_df[col_vary_only].unique()[0]
        ]

        varying_columns = []
        for col in conditioned_df.columns:
            if len(conditioned_df[col].unique()) == len(conditioned_df):
                varying_columns.append(col)

        raise ValueError(
            f"Not only varying {col_vary_only}. At least one of the following varies {varying_columns}."
        )
```

**Comment by mwaskom** [comment]
I agree this is a good thing to check, but I think it should be understood as part of data preprocessing, not something to be handled by the visualization library.

That said, I think you can do the check a lot easier.  e.g.:

```python
df = sns.load_dataset("fmri")
plot_vars = dict(x="timepoint", y="signal", hue="region", style="event")
assert df.groupby(list(plot_vars.values())).subject.value_counts().max() == 1
```

**Comment by YannDubs** [comment]
Awesome thanks 💯 

I agree with you that although very useful, this should be done as part of data preprocessing. Thanks for the simple code example !
