### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by jayenashar** [mwaskom/seaborn#1897]
to reproduce:

```sh
pip install https://github.com/pandas-dev/pandas/archive/master.zip
```

```py
import seaborn
```

<details>
<summary>traceback:</summary>
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-46-52e5c5e254b6> in <module>()
----> 1 import seaborn as sns
      2 cmap_green_0 = sns.light_palette("green", as_cmap=True, reverse=True)
      3 cmap_red_1   = sns.light_palette("red", as_cmap=True)
      4 table_styles = [
      5                 {'selector': 'th', 'props': [('font-size', '0.9px'), ('padding', '0')]},

5 frames

/usr/local/lib/python3.6/dist-packages/seaborn/__init__.py in <module>()
      4 
      5 # Import seaborn objects
----> 6 from .rcmod import *
      7 from .utils import *
      8 from .palettes import *

/usr/local/lib/python3.6/dist-packages/seaborn/rcmod.py in <module>()
      3 import functools
      4 import matplotlib as mpl
----> 5 from . import palettes, _orig_rc_params
      6 
      7 

/usr/local/lib/python3.6/dist-packages/seaborn/palettes.py in <module>()
     10 from .external.six.moves import range
     11 
---> 12 from .utils import desaturate, set_hls_values, get_color_cycle
     13 from .colors import xkcd_rgb, crayons
     14 

/usr/local/lib/python3.6/dist-packages/seaborn/utils.py in <module>()
     15 
     16 from distutils.version import LooseVersion
---> 17 pandas_has_categoricals = LooseVersion(pd.__version__) >= "0.15"
     18 mpl_ge_150 = LooseVersion(mpl.__version__) >= "1.5.0"
     19 

/usr/lib/python3.6/distutils/version.py in __ge__(self, other)
     68 
     69     def __ge__(self, other):
---> 70         c = self._cmp(other)
     71         if c is NotImplemented:
     72             return c

/usr/lib/python3.6/distutils/version.py in _cmp(self, other)
    335         if self.version == other.version:
    336             return 0
--> 337         if self.version < other.version:
    338             return -1
    339         if self.version > other.version:

TypeError: '<' not supported between instances of 'str' and 'int'
</details>

**Comment by mwaskom** [comment]
Does this depend on the development branch of pandas? Is there something they changed? What is `pandas.__version__` in that snapshot?

**Comment by jayenashar** [comment]
i think it depends on any unreleased version of pandas.  [i filed a bug over there as well](https://github.com/pandas-dev/pandas/issues/30333) since `pandas.show_versions()` has the same error.

`pandas.__version__` returns `'0+unknown'`

**Comment by TomAugspurger** [comment]
Most likely caused by trying to `pip install pandas` from a GitHub zip archive, which doesn't work well with versioneer.

**Comment by mwaskom** [comment]
Thanks @TomAugspurger

**Comment by jayenashar** [comment]
as tom mentioned in https://github.com/pandas-dev/pandas/issues/30333#issuecomment-567543239 , `pip install git+https://github.com/pandas-dev/pandas` works
