### ISSUE TITLE
Why can't I overlay a regression line on boxplot?

### ISSUE THREAD

**Issue by JiqianDong** [mwaskom/seaborn#1899]
![image](https://user-images.githubusercontent.com/33066671/71214450-55935300-2283-11ea-81f9-079a05c97b77.png)

See the figure, the overlayed regression line is completely wrong.

**Comment by mwaskom** [comment]
From the [boxplot docs](https://seaborn.pydata.org/generated/seaborn.boxplot.html):

>> This function always treats one of the variables as categorical and draws data at ordinal positions (0, 1, … n) on the relevant axis, even when the data has a numeric or date type.
