### ISSUE TITLE
You can use "fig.autofmt_xdate()" to format dates for relplots but not catplots. Would it be possible to add that same functionality to catplots for consistency? 

### ISSUE THREAD

**Issue by bbennett36** [mwaskom/seaborn#1901]
As the title says, if you want to use dates for the relplot you can easily use them by using fig.autofmt_xdate().  
  
Code from tutorial (https://seaborn.pydata.org/tutorial/relational.html) -  
```
g = sns.relplot(x="time", y="value", kind="line", data=df)
g.fig.autofmt_xdate()  
```
  
However, you can't do this for the catplot for some reason so it's harder to use dates. Would it be possible to add that same functionality to catplots?

**Comment by mwaskom** [comment]
It's not really possible given the way that categorical plots work (and interface with matplotlib), sorry.
