### ISSUE TITLE
no resize with annot=True in heatmap 

### ISSUE THREAD

**Issue by vainaijr** [mwaskom/seaborn#1903]
I get figure like this,
![image](https://user-images.githubusercontent.com/43755000/71552263-c9c8b600-2a3c-11ea-8e96-d57a89d4c293.png)

and there is no option to resize this plot.

**Comment by mwaskom** [comment]
This isn’t a seaborn question, but I’d suggest asking on stackoverflow (with enough information that someone could give you a useful answer).
