### ISSUE TITLE
Issue with setting log scale with kde

### ISSUE THREAD

**Issue by am-thyst** [mwaskom/seaborn#1904]
I have data ranging from 0-100 on the y axis and from 0-10,000 on the x axis & I want to plot this with a log scale. My data is very large, so I'm attempting this with random numbers until I get it right. I try the following code:

```python
import numpy as np
import seaborn as sns
import xarray as xr
from random import randint


cape_list, shear_list =[], []
for x in range(0,300):
	cape_list.append(randint(0,10000))
	shear_list.append(randint(0,100))

sns_plot = sns.kdeplot(cape_list, shear_list, cmap="cubehelix", cbar=False, n_levels=10)
sns_plot.set(xlim=(0, 10000), ylim=(0, 100))
sns_plot.set_xscale('log')
sns_plot.set_yscale('log')
```

and get this:
![test__](https://user-images.githubusercontent.com/41115380/71555022-c0c8ec00-2a1e-11ea-856f-a8dca9e88163.png)

But if I try it without the log axis, I get something like this (below) so I know it's definitely the log scale messing it up. What's going on here - how can I fix it?

![testnolog_](https://user-images.githubusercontent.com/41115380/71555034-ef46c700-2a1e-11ea-9790-bddbf9ea4563.png)

**Comment by mwaskom** [comment]
If you actually have zeros in your data (as you do in the example here) then it will break log scaling. You’ll need to clip the data to a small positive value.

**Comment by am-thyst** [comment]
@mwaskom thank you, I had no idea!
