### ISSUE TITLE
Odd 'squiggle' on kde plot?

### ISSUE THREAD

**Issue by am-thyst** [mwaskom/seaborn#1906]
I've used kdeplot to make a contour plot. I seem to have a weird squiggle in the top right hand corner that doesn't seem to be part of the contours. Is this a bug or am I mistaken? I've never had this before using this function. Could it be my data?

I'd supply the data so this can be replicated, but its far too big in size.

Here's my general code, where x and y are lists of length 28940:

```python
sns_plot = sns.kdeplot(x, y, cmap="cubehelix", cbar=False, n_levels=10)
sns_plot.set(xlim=(1, 10000), ylim=(1, 100))
sns_plot.set_xscale('log')
sns_plot.set_yscale('log')
```

![image](https://user-images.githubusercontent.com/41115380/71561792-352d7a80-2a73-11ea-8be9-2ddb528a0665.png)

**Comment by mwaskom** [comment]
Unfortunately this is not really something that's possible to provide help on without knowing anything about your dataset. In debugging it yourself I'd suggest thinking of questions like: Do you have observations there? If you increase the number of levels, what does the topography look like? What does it look like without log-scaling the axes? (Note that the KDE is still fit to the original data ... you may want to take the log of the data before passing to kdeplot).
