### ISSUE TITLE
Inconsistent distplot() behavior between cumulative=True and cumulative=False

### ISSUE THREAD

**Issue by TheTravellingSalesman** [mwaskom/seaborn#1908]
I noticed what I assume to be a bug in the behavior of `seaborn.distplot()`. 

(Where `sparse_data` is a dataset containing null values):

If you try to plot the PDF of data which contains null values using `seaborn.distplot(sparse_data, hist=False, kde_kws=dict(cumulative=False))`, the resulting plot will display the PDF of the data, excluding the null values.

If you try to plot the CDF of the same data using `seaborn.distplot(sparse_data, hist=False, kde_kws=dict(cumulative=True))`, the resulting plot will display nothing at all, although you'd expect it to plot the CDF of the data, excluding the null values.

Here is a minimal reproducible example:

```
import seaborn as sns
import pandas as pd
df = pd.DataFrame({'feature_1': [1,2,3,None,None,None,4,5,6]})

# this will plot the PDF of the data, ignoring null values
sns.distplot(df['feature_1'], hist=False, kde_kws=dict(cumulative=False))

# this will display an empty plot
sns.distplot(df['feature_1'], hist=False, kde_kws=dict(cumulative=True))
```

The attached .zip file contains the Jupyter-Lab Notebook I used to run this example, and an environment.yml file which can be used to re-create the conda environment I ran this example in.

[seaborn_distplot_bug.zip](https://github.com/mwaskom/seaborn/files/4010540/seaborn_distplot_bug.zip)

**Comment by mwaskom** [comment]
Trying the evaluate the kernel density and CDF using statsmodels directly 

```python
import statsmodels.nonparametric.kde as smnp
kde = smnp.KDEUnivariate(df["feature_1"])
kde.fit()
print(kde.density)
print(kde.cdf)
```

Returns a valid array for the density and an array of nans for the cdf.

There's also a warning printed when the CDF is evaluated:

> IntegrationWarning: The occurrence of roundoff error is detected, which prevents the requested tolerance from being achieved.  The error may be  underestimated.

So the inconsistency, such as it is, arises from statsmodels...

**Comment by TheTravellingSalesman** [comment]
Ah, I see. 

So in summary, the `statsmodels` subdependency of `seaborn` is running into a roundoff error when attempting to fit the KDE for the CDF of the data, which results in an array of NaNs, which `seaborn` plots, which results in a blank plot. 

Thank you for clearing that up. I'll dive into `statsmodels` to find the root of this inconsistent behavior. :-)

**Comment by mwaskom** [comment]
Re-opening because seaborn can remove nans from the array it passes to statsmodels.
