### ISSUE TITLE
The meaning of shading and panels in kde density plot

### ISSUE THREAD

**Issue by zxdawn** [mwaskom/seaborn#1911]
I followed one [example](https://seaborn.pydata.org/tutorial/distributions.html) to plot the density distribution of two arrays.

Here're the code and result of that example:
```
data = np.random.multivariate_normal(mean, cov, 200)
df = pd.DataFrame(data, columns=["x", "y"])
g = sns.jointplot(x="x", y="y", data=df, kind="kde", color="m")
g.plot_joint(plt.scatter, c="w", s=30, linewidth=1, marker="+")
g.ax_joint.collections[0].set_alpha(0)
g.set_axis_labels("$X$", "$Y$");
```

![image](https://user-images.githubusercontent.com/30388627/71780495-37a54c80-2ffe-11ea-9cb5-54742bad6548.png)

One of my manuscript's reviewer came up with this question: "What do the various colors of shading indicate? What are the scales for the horizontal plot at the top and the vertical plot on the side?"

Is it possible to answer that in a scientific way? I can't find the definition in the `seaborn.kdeplot` function.

If any of you can help me with this problem, I would appreciate a lot :)

**Comment by mwaskom** [comment]
I would read through here for a start: https://en.m.wikipedia.org/wiki/Kernel_density_estimation

**Comment by zxdawn** [comment]
@mwaskom Thanks! After learning some pages, I'm still confused of the unit shown in the colorbar:
![image](https://user-images.githubusercontent.com/30388627/71799917-92d44f00-3091-11ea-8b0e-2a5927e87222.png)

This question has been asked [here](https://stats.stackexchange.com/questions/177524/the-meaning-of-kernel-density-estimation) before.
Although it's clear that the darker color means the higher density, what's the exact meaning of these values shown on the colorbar?
