### ISSUE TITLE
Working on Titanic Dataset on Kaggle, getting an error in catplot. Please suggest something? 

### ISSUE THREAD

**Issue by gaganspall86** [mwaskom/seaborn#1916]
Hi I have written following code 
# For data
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

# For visualization
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
from __future__ import division

# Set up the Titanic csv file as a DataFrame
titanic_df = pd.read_csv('E:\Data Analysis and Visualization using Python\Data Projects\Kaggle Titanic Data\\train.csv')
# Let's see a preview of the data
titanic_df.head()
# We could also get overall info for the dataset
titanic_df.info()
# Let's first check gender
sns.catplot('Sex',data=titanic_df)
#After this line I am not getting satisfactory graph 
sns.catplot('Sex',data=titanic_df)
Out[13]: <seaborn.axisgrid.FacetGrid at 0x21896fe45c8>
￼

![Cat_Plot1](https://user-images.githubusercontent.com/54868995/71895431-4bd86f00-310e-11ea-9f40-eb9e6b7bdc6f.jpg)

# Now let's seperate the genders by classes, remember we can use the 'hue' arguement here!
sns.catplot('Pclass',data=titanic_df,hue='Sex')

![Cat_Plot2](https://user-images.githubusercontent.com/54868995/71895451-585cc780-310e-11ea-8694-d020be9ab10c.jpg)

When I did not get any satisfactory images, I thought i need to install seaborn library, but it was already there. 
![seaborn](https://user-images.githubusercontent.com/54868995/71895617-c0131280-310e-11ea-843f-2f27ff8bb31d.jpg)

Please help me with that ......!

**Comment by mwaskom** [comment]
Hi, I think this is a better question for stackoverflow, thanks.
