### ISSUE TITLE
ModuleNotFoundError for tests with numpy 1.18

### ISSUE THREAD

**Issue by toddrme2178** [mwaskom/seaborn#1917]
The unit tests use `numpy.testing.decorators`, which was [removed in numpy 1.18](https://github.com/numpy/numpy/blob/master/doc/source/release/1.18.0-notes.rst):

> The files numpy/testing/decorators.py, numpy/testing/noseclasses.py and numpy/testing/nosetester.py have been removed. They were never meant to be public (all relevant objects are present in the numpy.testing namespace), and importing them has given a deprecation warning since NumPy 1.15.0

**Comment by mwaskom** [comment]
This is the second thing in numpy 1.18 to break where there apparently was a deprecation warning, but it doesn't get shown when the seaborn tests run. Something in the config must be hiding them, but I cannot figure out what it might be.

**Comment by mwaskom** [comment]
Actually, in this case, it's because the offending code was removed a while ago (#1712) ...
