### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by chyzzqo2** [mwaskom/seaborn#1921]
Is there a plan for a new release to pypi soon? It would be nice to get one with the numpy compatibility issue fix.

Thanks

**Comment by mwaskom** [comment]
Don’t be annoying.

**Comment by chyzzqo2** [comment]
Sorry I annoyed you. It was a legitimate question, it's been a while since the last release so i was wondering the plan is for my planning purposes. Sorry if I missed documentation on this but i couldn't find any. I guess I'll switch to installing from git commits for now.
