### ISSUE TITLE
Option to change bin size with continuous variable used as hue in relplot

### ISSUE THREAD

**Issue by soorajachar** [mwaskom/seaborn#1922]
Hello, would it be possible to allow the user to change the bin size seaborn uses when displaying a legend for continuous hues? Seaborn always enforces a 3 bin limit on the number of markers displayed in the legend for relplot when hue is used with a continuous parameter, regardless of the normalization passed to hue_norm. Here is an example the various issues I've encountered with continuous hues: 

Maximum "tip" value is 10, but legend goes to 12.0: 
> ```python
> import seaborn as sns
> import matplotlib.pyplot as plt
> 
> df = sns.load_dataset('tips')
> sns.relplot(data=df,x='total_bill',y='tip',hue='tip',palette='coolwarm')
> plt.show()
![image](https://user-images.githubusercontent.com/49458891/72224129-a164af80-3544-11ea-99ef-cf0d2755c78f.png)

Passing a custom normalization to hue_norm with the upper and lower limits specified seems to shrink the number of bins but doesn't change the upper value of the limit in relplot: 

> ```python
> df = sns.load_dataset('tips')
> norm = plt.Normalize(vmin=0,vmax=10)
> sns.relplot(data=df,x='total_bill',y='tip',hue='tip',palette='coolwarm',hue_norm=norm)
> plt.show()
![image](https://user-images.githubusercontent.com/49458891/72224154-fc96a200-3544-11ea-828e-07c8fb6d12d1.png)

**Comment by mwaskom** [comment]
At the moment, seaborn is delegating the values shown in the legend to a matplotlib locator object and there isn't a lot of ability to control how that works besides asking for no more than a certain number of "nicely spaced" values. Unfortunately, the matpltolib legend is not currently as flexible as one would like and so the solution for creating legend values with a numerical colormap is not ideal.

It is always possible to set `legend=False` and then add a legend yourself, if you need precise control over what is shown.
