### ISSUE TITLE
Nondeterministic regplot due to unset bootstrap random_seed

### ISSUE THREAD

**Issue by karlicoss** [mwaskom/seaborn#1924]
I've had some random non-determinism in my regplot error bands (was particularly annoying as I was keeping plots under git to make sure they are reproducible).

I've tracked it down to [this line](https://github.com/mwaskom/seaborn/blob/065d3c1ed58b029d61913cca8fc315cc985ffc91/seaborn/regression.py#L235), when it calls [bootstrap](https://github.com/mwaskom/seaborn/blob/065d3c1ed58b029d61913cca8fc315cc985ffc91/seaborn/algorithms.py#L32). Bootstrap falls back to numpy random (reads from /dev/urandom, I believe), so currently there is no way to make plots deterministic.

I see two possible solutions here:

1. propagate `random_seed` argument all the way up to `regplot` function. 

2. set `random_seed` argument `bootstrap`, e.g. to 0. If someone genuinely wants nondeterminism, they can pass None explicitly.
   
    Are there any downsides? I've grepped usage in seaborn and it seems that all usages of `bootstrap` would suffer from similar nondeterminism, so that would fix it once and for all.

Happy to open a PR once we figure out what can be done. Thanks!

**Comment by mwaskom** [comment]
I believe there should be a third option which would be to fall back to using the global random state. Other packages (e.g. [`scipy`](https://github.com/scipy/scipy/blob/master/scipy/_lib/_util.py#L173), [`scikit-learn`](https://github.com/scikit-learn/scikit-learn/blob/b194674c4/sklearn/utils/validation.py#L800)) have implemented such behavior, but I just discovered that doing so relies on access to a private numpy object. I have opened an issue on numpy (https://github.com/numpy/numpy/issues/15322) for guidance.

**Comment by karlicoss** [comment]
Good point, thanks. As a workaround at the moment, I'm using something like that:

```python
if sns.algorithms.bootstrap.__module__ == 'seaborn.algorithms':
    # prevents nondeterminism in plots https://github.com/mwaskom/seaborn/issues/1924
    # we only want to do it once
    def bootstrap_hacked(*args, bootstrap_orig = sns.algorithms.bootstrap, **kwargs):
        return bootstrap_orig(*args, random_seed=0, **kwargs)
    
    sns.algorithms.bootstrap = bootstrap_hacked
```

Hacky, but does the trick for me.

**Comment by mwaskom** [comment]
As far as I can gather without losing an entire afternoon reading numpy's technical documentation, they are completely revamping how random number generation works to move away from having any concept of global state, so I guess that's not going to work...

**Comment by karlicoss** [comment]
Yeah, thanks for following up on that!

I guess if seaborn uses its own global generator for now it's okay? Can be changed later to conform to numpy's style when it settles, if necessary. 

Also I guess I can see how having actual preudorandom numbers could be useful for some heavy numeric simulations in numpy, whereas it feels like it just adds noise for Seaborn visualizations, so making it deterministic by default would be okay? Although I'm not a heavy user of either so could be missing something.
