### ISSUE TITLE
Distplot creates spikes

### ISSUE THREAD

**Issue by MarineF** [mwaskom/seaborn#1928]
What is happening with distplot in the b case ?
seaborn version: 0.9.0
matplotlib version: 3.1.1

```
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

a = [1]*28 + [2]*58 + [3]*18 + [4]*6
b = [1]*27 + [2]*58 + [3]*18 + [4]*6

df_a = pd.Series(a, index=np.arange(0, len(a)))
df_b = pd.Series(b, index=np.arange(0, len(b)))

# correct distribution
sns.distplot(df_a)
plt.show()

# distribution with "spikes"`
sns.distplot(df_b)
plt.show()
```

![image](https://user-images.githubusercontent.com/15995906/72452240-8355b400-37bd-11ea-821f-4b88fe7ed065.png)

![image](https://user-images.githubusercontent.com/15995906/72452200-70db7a80-37bd-11ea-9916-0db3a44cd697.png)

**Comment by mwaskom** [comment]
The default bandwidth for the kernel density estimate uses a reference rule that is based on the interquartile range, which differs substantially between your two datasets:

```python
from scipy import stats
print(stats.iqr(a))
print(stats.iqr(b))
```
```
0.75
0.0
```

While you can set a different bandwidth, if you actually have data that take a small number of discrete values, a gaussian kernel density is never going to give a "good" representation of the underlying distribution.
