### ISSUE TITLE
seaborn.countplot orientation

### ISSUE THREAD

**Issue by techshot25** [mwaskom/seaborn#1938]
The `orient` method in countplot does not work. Pass a list like:
`['Rose', 'Teal', 'Teal', 'Orange', 'Orange', 'Orange']` and try to adjust the orientation to see the issue.

**Comment by mwaskom** [comment]
Duplicate of https://github.com/mwaskom/seaborn/issues/654. While the issue was obvious in this case, please provide a reproducible example in any future bug reports.
