### ISSUE TITLE
Unable to add top and right spines

### ISSUE THREAD

**Issue by mlbarnard** [mwaskom/seaborn#1940]
Seaborn v 0.9.0
Matplotlib v 3.1.2
I've never done this before so please let me know if I missed something.

It seems like seaborn is unable to add a top or right spine to a graph.  I'm using example code from the intro and no combination of set_style and set_axes works (even though I can see one calls the other).  In addition, setting style 'white', 'ticks', or 'whitegrid' won't put the spines there either.

```
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

# Set seaborn presets for matplotlib rcparams
sns.set()

sns.set_style(style='whitegrid')
# sns.set_style(rc={'axes.spines.top': True, 'axes.spines.right': True})
tips = sns.load_dataset("tips")
sns.relplot(x="total_bill", y="tip", col="time",
        hue="smoker", style="smoker", size="size",
        data=tips)
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/22847071/72849062-ee96fe80-3c73-11ea-9fe1-a7a3f7a18a63.png)

I tried poking around in the code to figure it out, but I quickly get lost in the matplotlib backend.

**Comment by mwaskom** [comment]
```python
sns.relplot(x="total_bill", y="tip", col="time",
            hue="smoker", style="smoker", size="size",
            facet_kws=dict(despine=False),
            data=tips)
```

![image](https://user-images.githubusercontent.com/315810/72853930-ce217100-3c80-11ea-907d-941cfb12f36f.png)

**Comment by ishakj5035** [comment]
Is there any way for me to permanently set @mwaskom's solution so that every new relplot doesn't need the "facet_kws=dict(despine=False)" argument? I had also incorrectly tried the method @mlbarnard had tried.
