### ISSUE TITLE
multi-plot grids

### ISSUE THREAD

**Issue by cshesse** [mwaskom/seaborn#1946]
I was having issues with `relplot`, and it looks like this is not a normal plotting function, but one that is quite different from, say `lineplot`.  The return type for `lineplot` is `matplotlib.axes._subplots.AxesSubplot` while `relplot` is `seaborn.axisgrid.FacetGrid`.

It looks like `relplot` (and `catplot` and `lmplot`) should be under the "Multi-plot Grids" section of the API instead of being next to other single-plot functions, since how you call them and how you use the return value are not the same as the single-plot functions.

**Comment by mwaskom** [comment]
Thanks for the suggestion but I don’t agree with the proposed reorganization.
