### ISSUE TITLE
retrieve dendrogram label information

### ISSUE THREAD

**Issue by brianpenghe** [mwaskom/seaborn#1947]
It seems that a scipy update triggered multiple changes including but not limited to the default behavior of clustermap()
One big issue I'm hitting is about the .dendrogram_row.linkage and .dendrogram_row.reordered_ind . I'm sure they have changed but can't tell in which way.

Because when I was using scipy's cut_tree to cut .dendrogram_row.linkage the result doesn't look right after I updated to the recent version of scipy.

Any ideas?

**Comment by mwaskom** [comment]
Can you please use some virtual environments to identify the scipy version where there was a change and clearly define the nature of the change? Otherwise it would be very difficult for me to help with this vague description. (I don’t know what does or doesn’t “look right” to you).

**Comment by brianpenghe** [comment]
> Can you please use some virtual environments to identify the scipy version where there was a change and clearly define the nature of the change? Otherwise it would be very difficult for me to help with this vague description. (I don’t know what does or doesn’t “look right” to you).

The old scipy was 1.2.1 and the current one is 1.3.3 

It seems that the order of .dendrogram_row.linkage and .dendrogram_row.reordered_ind do not match now.

Thanks

**Comment by mwaskom** [comment]
Can you please provide some code that I can use to reproduce what you’re doing?

**Comment by brianpenghe** [comment]
> Can you please provide some code that I can use to reproduce what you’re doing?

I think I figured out why. Thanks!

**Comment by mwaskom** [comment]
Ok, good. In the future, please remember that when you open an issue you are making a demand on other people’s time/attention. It will be less frustrating for everyone if you put in the effort to formulate your question in a way that makes it possible to answer it.
