### ISSUE TITLE
Illustrator-editable text in PDFs by default

### ISSUE THREAD

**Issue by swederik** [mwaskom/seaborn#195]
Hello!

I commonly import seaborn when making plots to save some time styling the graphs. One thing I've noticed that I keep having to fix, though it's not a seaborn issue, is the type of font saved by matplotlib inside PDF documents.

So my question is basically, can we stick this code:

```
import matplotlib as mpl
mpl.rcParams['pdf.fonttype'] = 42
```

somewhere so that I can stop putting it in my scripts, import seaborn, and forget about the problem?

Here's an example:

![screenshot 2014-05-11 14 07 57](https://cloud.githubusercontent.com/assets/607793/2938352/eecc154e-d904-11e3-9654-466835606f99.png)

On the left is a PDF of a plot saved in the normal manner. Each piece of text is editable in Adobe Illustrator as as distinct curve. On the right is a PDF saved with the code specified above. The text is fully editable, font and all. Also see http://stackoverflow.com/questions/5956182/cannot-edit-text-in-chart-exported-by-matplotlib-and-opened-in-illustrator

**Comment by soungalo** [comment]
I am running seaborn 0.10.1 (from a Jupyter notebook) and got a non-Illustrator editable PDF. Adding the code mentioned above solved the issue. Any chance there is some regression in newer versions? Or maybe this is somehow related to the Jupyter environment?

**Comment by mwaskom** [comment]
IIRC this got reverted at some point because it makes PDF files much larger, so it wasn't a good parameter to have set as a default.

**Comment by mwaskom** [comment]
https://github.com/mwaskom/seaborn/issues/352
