### ISSUE TITLE
Large gaps in clustermap

### ISSUE THREAD

**Issue by flying-sheep** [mwaskom/seaborn#1953]
Using clustermap’s example in a fresh ipython shell with seaborn 0.10.0 and matplotlib 3.0.3:

```py
import seaborn as sns; sns.set(color_codes=True)
iris = sns.load_dataset("iris")
species = iris.pop("species")
g = sns.clustermap(iris)
g.fig.show()
```

The gap between the column dendrogram and the heatmap would appear a second time when `col_colors=...` is used.

I noticed that it looks as wide as the color bar’s axis labels, so maybe that gap is created in a failed attempt to sync the grid of the color bar and the dendrogram below it?

![grafik](https://user-images.githubusercontent.com/291575/73599404-75d15580-4543-11ea-91a6-dbed384767be.png)

**Comment by mwaskom** [comment]
Here is what this looks like on my system with seaborn 0.10.0 and matplotlib 3.1.1.

In a notebook using inline backend:

![image](https://user-images.githubusercontent.com/315810/73601473-8d531300-4530-11ea-9727-e872028fbcf1.png)

and in the terminal using MacOSX backend:

![image](https://user-images.githubusercontent.com/315810/73601492-c1c6cf00-4530-11ea-9a2c-24e9f0deb44c.png)

I can't replicate what you're seeing. But your suggestion that it may be space attributable to the colorbar ticks could be correct: https://github.com/mwaskom/seaborn/blob/master/seaborn/matrix.py#L1160

The most obvious difference is the matplotlib version do you have an environment with 3.1.2 you could test? If not, any more information about the context in which you're making the plot would be helpful.

**Comment by flying-sheep** [comment]
Ah yes, indeed. We’re currently pinning matplotlib 3.0 because 3.1 has a bug regarding 3d plotting, but of course we can’t expect seaborn to fix old versions of other packages.
