### ISSUE TITLE
cbar_kws ignores 'ticks' keyword when norm argument is passed.

### ISSUE THREAD

**Issue by andt88** [mwaskom/seaborn#1954]
When I pass the norm argument, it seems that the ticks keyword is ignored.

```
from matplotlib.colors import LogNorm
from matplotlib import cm
log_norm = LogNorm(0, 10)
plot_df = pd.DataFrame(np.random.random_sample((20, 4))*10, columns=list('ABCD'))
cmap = cm.coolwarm
plot = sns.heatmap(plot_df, cmap=cmap, norm=log_norm, mask=pd.isna(plot_df), cbar_kws={'label': 'Rf', 'ticks': [0.1, 1, 2, 5]})
plt.savefig('test.png', dpi=600)
plt.clf()
```
Expected behaviour: 0.1, 1, 2, 5 ticks on the colorbar.

![test](https://user-images.githubusercontent.com/36545428/74155929-a71de580-4c15-11ea-98ad-b2a3ec921a55.png)

I am using seaborn 0.10.0

**Comment by mwaskom** [comment]
Can you please share a reproducible example? You can also contribute to solving this problem by finding out if it works properly when you use matplotlib directly.

**Comment by andt88** [comment]
> Can you please share a reproducible example? You can also contribute to solving this problem by finding out if it works properly when you use matplotlib directly.

I confused the cbar ticks with cbar ticklabels. Ticklabels can be set with plot.figure.axes[-1].set_yticklabels([0.1, 1, 2, 5])
