### ISSUE TITLE
lmplot() uses all server CPUs - any method to limit cores?

### ISSUE THREAD

**Issue by mirekphd** [mwaskom/seaborn#1955]
When executing `sns.lmplot()` on a DataFrame with 500k rows and with an x-axis aggregation function (`np.mean()`) seaborn uses all available CPU cores on a 4-CPU server machine (with XXX cores available). We run python in Docker containers without any CPU limits imposed by the orchestrating platform (Openshift). This used to work, because data munging and plotting algos used to be single-threaded, and statistical modeling algos always give us the ability to limit the number of threads (to optimize performance at around 8-32 cores, depending on the algo). We need such a setting in seaborn as well (probably needs to be passed to the underying statistical functions).

The exact code to replicate (on a multi-core machine and using a DataFrame filled with two columns and 500k rows of random numbers):
```
import seaborn as sns
sns.lmplot(x='IntVar1", y='FloatVar1', data=df, x_estimator=np.mean, x_bins=10)
```
Python 3.7. Package versions:
- seaborn: 0.10.0
- matplotlib: 3.1.2
- numpy: 1.18.1
- pandas: 1.0.1

**Comment by mirekphd** [comment]
I have found a hack (see #347) to speed things up by switching off lmplot's confidence intervals (`ci=None`), but this is just masking the core issue of lmplot using all cores without any controls for bootstrapping those confidence intervals.

**Comment by mwaskom** [comment]
seaborn fits the logistic regression with statsmodels so this is really a question for them. In fact, the question has been asked: https://github.com/statsmodels/statsmodels/issues/2914. But the answer seems to be that the multiprocessing is even farther down the stack.

The answer is probably going to involve regulating parallelism in the blas/lapack your numpy is built with, which might involve setting the `OMP_NUM_THREADS` or `MKL_NUM_THREADS` environment variable.

Unfortunately I think this is something seaborn has literally no control over, so I am going to close.

**Comment by mirekphd** [comment]
> seaborn fits the logistic regression with statsmodels so this is really a question for them. 
I agree that it is somewhere in the underlying packages, but not in statsmodels package, which is not required to replicate this bug (unlike when setting e.g. `robust=True`). Try to compute confidence intervals in seaborn (leaving default 'ci=95' for a standard linear regression (not a classifier/logistic one). After uninstalling statsmodels the problem remains:)

**Comment by mirekphd** [comment]
> The answer is probably going to involve regulating parallelism in the blas/lapack your numpy is built with, which might involve setting the `OMP_NUM_THREADS` or `MKL_NUM_THREADS` environment variable.

Excellent idea!

**Comment by mirekphd** [comment]
> The answer is probably going to involve regulating parallelism in the blas/lapack your numpy is built with, which might involve setting the `OMP_NUM_THREADS` or `MKL_NUM_THREADS` environment variable.

I tested it to work!:)

More info
I can now confirm that setting both env vars proposed by @mwaskom (`OMP_NUM_THREADS` and `MKL_NUM_THREADS`) in (containerized) Ubuntu system shell (in my case using `env` in Openshift deployment config templates) prior to running python (or is it prior to just importing seaborn?) will limit the number of threads used by `lmplot()` under some CPU-intensive options (notably 'ci=95'). 

Moreover, these variables limit CPU usage in a well-behaved manner, unlike Openshift (Kubernetes) controller and just like in machine learning algos such as XGBoost: with the specified number of threads being used at 100% and moved around to prevent overheating. The other [similar *_THREADS variables](https://stackoverflow.com/questions/30791550/limit-number-of-threads-in-numpy/53224849#53224849) were not necessary in case of seaborn.

**Comment by mwaskom** [comment]
Glad you figured it out.

> prior to running python (or is it prior to just importing seaborn?)

You need to do it prior to impoting numpy. (Though note that there is a third party [solution](https://github.com/numpy/numpy/issues/11826) for changing the threading configuration after numpy has been imported). And the choice of exactly which environment variable to set does not really have anything to do with seaborn — it should be determined by which linear algebra libraries numpy was built with on your system.

**Comment by GF-Huang** [comment]
How about if I using `adfuller` with `ipyparallel`? `ipyparallel` use multiple `ipython` instance, do I need to set limitation on each `ipython` instance?

**Comment by mwaskom** [comment]
No idea what `adfuller` is, @GF-Huang; pretty sure you're asking in the wrong channel.
