### ISSUE TITLE
xlim in FacetGrid does not apply to all plots

### ISSUE THREAD

**Issue by RMeli** [mwaskom/seaborn#1960]
If I modify the `FacetGrid` construction in the [overlapping densities](https://seaborn.pydata.org/examples/kde_ridgeplot.html) example as follows:

```python
g = sns.FacetGrid(df, row="g", hue="g", aspect=15, height=.5, palette=pal, xlim=(68,74))
```

the `xlim` parameter correctly applies to `plt.axhline` but it does not affect `sns.kdeplot` and the result is the following:

![Figure_1](https://user-images.githubusercontent.com/11348981/74467257-a2189a80-4e90-11ea-85e2-e219ea6064fd.png)

Maybe I misunderstand the intent here, but I expected the `xlim` parameter to be applied to all the plots (resulting in a cut KDE plot).

**Comment by mwaskom** [comment]
The reason they extend is because of `clip_on=False`.

**Comment by RMeli** [comment]
Wooops, I completely missed that... Thanks for the fast reply!
