### ISSUE TITLE
FutureWarning: pandas.util.testing is deprecated.

### ISSUE THREAD

**Issue by andreamoro** [mwaskom/seaborn#1963]
Please see details here:

https://github.com/pandas-dev/pandas/issues/31682

**Comment by MaozGelbart** [comment]
Hi @andreamoro , thanks for reporting. 
Could you provide a code that results with this warning (along with seaborn/pandas versions)? I don't see this on my local setup with seaborn master and pandas==1.0.
I think this should have been resolved a while ago with [https://github.com/mwaskom/seaborn/commit/4d89197e94dd65d0ab80f77fc380ca3307950ba7](https://github.com/mwaskom/seaborn/commit/4d89197e94dd65d0ab80f77fc380ca3307950ba7)

Thanks!

**Comment by andreamoro** [comment]
Hi @MaozGelbart 
please see below screenshot.

It's a simple object referencing the one causing the problem, so I don't know what's the cause.

![image](https://user-images.githubusercontent.com/5256583/74707131-cff33b80-5210-11ea-90ae-581f8e88eb9d.png)

![image](https://user-images.githubusercontent.com/5256583/74707285-48f29300-5211-11ea-882a-fa03091bf7f5.png)

Look forward to hearing from you.

**Comment by MaozGelbart** [comment]
Thanks for elaborating. This warning comes from within statsmodels, which seaborn attempts to import. Try upgrading statsmodels to its latest version, as this should have been fixed by [https://github.com/statsmodels/statsmodels/pull/6394](https://github.com/statsmodels/statsmodels/pull/6394).

**Comment by mwaskom** [comment]
Thanks @MaozGelbart
