### ISSUE TITLE
sns.heatmap top and bottom boxes are cut off (again)

### ISSUE THREAD

**Issue by lchutny** [mwaskom/seaborn#1970]
This is the same as #1773, which is closed. The solution for #1773 says to install matplotlib 3.1.2. Well, I have 3.1.3 and Seaborn 0.10.0, and my heatmap is still cutoff on the edges.

![image](https://user-images.githubusercontent.com/42653356/75121953-764aa100-5656-11ea-8198-5abdf6fab949.png)

**Comment by mwaskom** [comment]
As the original issue was a bug in matplotlib, this is probably best raised with them.

**Comment by mwaskom** [comment]
(Before you do so, I recommend making a reproducible example that demonstrates the issue).

**Comment by mwaskom** [comment]
For what it's worth, I cannot replicate:

```python
import numpy as np
import matplotlib as mpl
import seaborn as sns

x = np.random.randn(10, 10)
sns.heatmap(x)
print(mpl.__version__)
```
```
3.1.3
```

![image](https://user-images.githubusercontent.com/315810/75122467-b9633f00-566b-11ea-8e3e-1fb555b6fc12.png)

**Comment by MaozGelbart** [comment]
Can't replicate as well using random data with ``matplotlib==3.2.0``. @lchutny , could you share a minimal dataset and code that reproduces the phenomena?

**Comment by mwaskom** [comment]
Closing for lack of response but get in touch if you can provide a working example of the issue.
