### ISSUE TITLE
[Swarmplot] Ordering of data points lost in creating swarmplot object  

### ISSUE THREAD

**Issue by mick-d** [mwaskom/seaborn#1975]
Swarmplot is a useful and elegant plot object, however it is impossible to apply some operations on it, like annotating points according to other data (e.g. other columns in the original dataframe if using a dataframe).

This is because the ordering of the points is lost when creating the swarmplot object and there is no way that I found to recover this order directly or indirectly. As an experiment i created a different hue for each data point and it showed clearly that the plotting order of the point was not consistent with the dataframe row ordering (points with the same value will not be plotted according to ascending or descending row indices). So even recovering the datapoints coordinates with `get_offsets()` is not helpful for reverse engineering the indices of the original points.

What would be ideal by far, would be to have a list/array of indices of the original data corresponding to the `get_offsets` values. This way one could immediately find out for each point coordinate its index in the original data. I believe this would be an extremely useful feature.

**Comment by mwaskom** [comment]
Sorry, but that’s the way it works.

**Comment by mick-d** [comment]
Ok, but would a pull request to have a consistent points ordering according to the original data, or even better a method to return the indices of the original data according to the plotted data be considered? This should be useful for quite a few different purposes.
