### ISSUE TITLE
[BUG] AttributeError for lineplot() using despine()

### ISSUE THREAD

**Issue by yanniskatsaros** [mwaskom/seaborn#1978]
## Description
When using `sns.lineplot(...)` with categorical x-values, calling `sns.despine(trim=True)` results in an `AttributeError`.

## Example
For example, using the `flights` dataset and the following short snippet we get the following result:

```python
import matplotlib as mpl
import seaborn as sns

flights = sns.load_dataset('flights')

# only plot the following years for brevity
years = [1958, 1959, 1960]
flights = flights[flights['year'].isin(years)].reset_index(drop=True)

ax = sns.lineplot(
    x='month',
    y='passengers',
    hue='year',
    data=flights,
    linewidth=4,
)

ax.legend(frameon=False)
sns.despine(offset=25, trim=True)
```

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-bd1680471336> in <module>
     15 
     16 ax.legend(frameon=False)
---> 17 sns.despine(offset=50, trim=True)

~\AppData\Local\Continuum\miniconda3\envs\core\lib\site-packages\seaborn\utils.py in despine(fig, ax, top, right, left, bottom, offset, trim)
    264             # clip off the parts of the spines that extend past major ticks
    265             xticks = ax_i.get_xticks()
--> 266             if xticks.size:
    267                 firsttick = np.compress(xticks >= min(ax_i.get_xlim()),
    268                                         xticks)[0]

AttributeError: 'list' object has no attribute 'size'
```

For reference, here is the output plot when calling `sns.despine(offset=25, trim=False)` instead.
![lineplot](https://user-images.githubusercontent.com/32942328/75486487-39421f80-5972-11ea-9f91-a31e48971ac0.png)

## Package Info
`sns.__version__` : `'0.10.0'`
`mpl.__version__`: `'3.1.3'`
`mpl.get_backend()`: `'module://ipykernel.pylab.backend_inline'`

## Comments
I _suspect_ (not really sure though, not intimately familiar with the source code) that this is a quick fix regarding line 265 in `seaborn/utils.py` by changing `xticks = ax_i.get_xticks()` to `xticks = np.array(ax_i.get_xticks())` to ensure that calling the `.size` attribute doesn't fail in case `get_xticks()` returns a `List`. Please let me know if you think that's the issue. If so, i'd be happy to submit a quick PR and add a new test to the `despine()` function as well.

Thanks,
Yanni

**Comment by mwaskom** [comment]
Good catch; to be clear this isn't specific to `lineplot` but will show up anywhere outside of the seaborn categorical plots.

The quick fix you suggest is likely to work, but the best way to know for certain is to write a test case first that demonstrates the error and then to implement a fix in the code that passes the test.

**Comment by yanniskatsaros** [comment]
Thanks for taking care of this @mwaskom, much appreciated!
