### ISSUE TITLE
How do I add data labels to a two-sided bar graph？

### ISSUE THREAD

**Issue by sunrisehang** [mwaskom/seaborn#1980]
My abscissa is discrete data, and it's a two-sided bar graph.So I don't know how to use ax.text().
`sns.barplot(x=x, y=y1,hue=z1,ax=ax1,  palette="cubehelix")`
~~~
Please help me how to add data labels to each bar chart~

**Comment by mwaskom** [comment]
Hi — this is a better question for stackoverflow (and very likely has already been asked there). Thanks!
