### ISSUE TITLE
Project description link points to http://seaborn.pydata.org/ without TLS

### ISSUE THREAD

**Issue by hartwork** [mwaskom/seaborn#1984]
Hi!

While browsing the seaborn docs I noticed the cross-out lock in the address bar...

![seaborn_lack_ssl](https://user-images.githubusercontent.com/1577132/76224728-13dbce00-621c-11ea-843b-28ad2410af22.png)

I find that https://seaborn.pydata.org/ with TLS works fine so I'd suggest to add an "s" to the link in the main project description:

![seaborn_proj_desc](https://user-images.githubusercontent.com/1577132/76224871-1f2ef980-621c-11ea-8466-b271e776b82d.png)

I'm happy to provide a PR for any more https fixes needed in Git once this issue is fixed.

Thanks and best, Sebastian

**Comment by mwaskom** [comment]
Thanks for catching.
