### ISSUE TITLE
Barplot cannot plot errors in combination with hue "hue"

### ISSUE THREAD

**Issue by andt88** [mwaskom/seaborn#1986]
Making a group barplot like this works:
`bars = sns.barplot(x=data['x'], y=data['y'], hue=data[hue])`

When trying to make a group barplot with errorbars, seaborn is not able to assign the error to the corresponding "hue" category.
`bars = sns.barplot(x=data['x'], y=data['y'], yerr=data['error'], hue=data[hue])`

I get the following error:

> ValueError: The lengths of the data (16) and the error 32 do not match

`len(data[data[hue]=='A']['error']) `
`16`

`len(data[data[hue]=='B']['error']) `
`16`

**Comment by mwaskom** [comment]
Yes, this is not unexpected behavior given the current implementation.

**Comment by Yizhang-Li** [comment]
Is there any way to implement this kind of plot?
