### ISSUE TITLE
sns.scatterplot size_norm arg does not seem to work 

### ISSUE THREAD

**Issue by amundv** [mwaskom/seaborn#1993]
Seaborn version: 0.10.0

`size_norm` argument of sns.scatterplot does not work with tuple. However, passing this tuple to `sizes` instead works as intended.

Maybe `sizes` should not accept tuple, and `size_norm` be kept?

**Comment by mwaskom** [comment]
Please provide a reproducible example of the problem, with a clear description of what you expected to happen. It is impossible to understand the issue from this casual description.
