### ISSUE TITLE
boxplot in PairGrid does not follow 'order' for last axes

### ISSUE THREAD

**Issue by yhshin11** [mwaskom/seaborn#1996]
Might be related to #1663, but when I try to setup a `PairGrid` and manually do `boxplot` in each of the axes, `boxplot` seems to ignore the category order.

Code to reproduce:
```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

tips = sns.load_dataset("tips")
data_input = tips
x_vars=['total_bill', 'total_bill', 'total_bill', 'total_bill']
y_vars=['smoker']
g = sns.PairGrid(data_input, x_vars=x_vars, y_vars=y_vars,
            height=5.)

for irow, icol in np.ndindex(g.axes.shape):
    ax = g.axes[irow][icol]
    sns.boxplot(x=x_vars[icol], y=y_vars[irow], hue=y_vars[irow],
                dodge=False,
                data=data_input,
                order=["No", "Yes"],
                orient="h",
                ax=ax)
    
```

Output:
![pairgrid](https://user-images.githubusercontent.com/5031800/76813288-d76f2a00-683a-11ea-9e9c-8e119b9245e5.png)

As you can see the order is flipped only for the last column. Any idea what's going on?

**Comment by yhshin11** [comment]
Same thing happens 1) for categorical variables with more than two levels, and 2) whether or not you specify `order`.

![pairgrid2](https://user-images.githubusercontent.com/5031800/76813514-91669600-683b-11ea-8027-c6948111dcd5.png)

**Comment by mwaskom** [comment]
I believe this is the same issue as described in #1886, which is a bug in a specific version of matplotlib. You forget to say which version of matplotlib (and seaborn) you have, so I can't be sure. But I cannot replicate the issue on latest versions.

**Comment by yhshin11** [comment]
Indeed I was on matplotlib 3.1.0 and seaborn 0.9.0. I updated to matplotlib 3.1.3 and that fixed the weird behavior.

Thanks for the quick response (and the awesome package)!
