### ISSUE TITLE
Feature Request: Order boxplot by median values

### ISSUE THREAD

**Issue by wcneill** [mwaskom/seaborn#1997]
There are some work-arounds for this, but nothing that seems to work consistently across contexts, especially when there is missing data in your data-frame. 

The easiest current way (for small data sets) is to first plot, then take note of the order, and then re-plot using the order keyword argument.

**Comment by mwaskom** [comment]
> The easiest current way (for small data sets) is to first plot, then take note of the order, and then re-plot using the order keyword argument.

This certainly isn't true, it will always be better to get get the order programmatically using pandas than by plotting, looking, and manually noting the order you want.

You make a vague reference to this not working consistently, but I don't see how that can be, and you don't show any code. I suggest making a reproducible xample and asking on stackoverflow if you don't know how.
