### ISSUE TITLE
Inconsistent parameter use for orienting plots horizontally and vertically.

### ISSUE THREAD

**Issue by AdamBebko** [mwaskom/seaborn#2001]
sns.boxplot(heights, orient='v')
sns.violinplot(heights, orient='v')

vs

sns.distplot(heights, vertical=True)

These plots are plotting basically the same thing, but use vastly different interfaces to accomplish vertical orientation. This is very confusing to new users. Even with frequent use I often forget and have to google which is which.

I suggest changing them to match distplot, since remembering True/False is easier than matching a string.

**Comment by mwaskom** [comment]
Sorry,  but it’s not good library practice to just change parameters willy-nilly.
