### ISSUE TITLE
Not able to access scatterplot in seaborn 0.10.0

### ISSUE THREAD

**Issue by srinathsrk76** [mwaskom/seaborn#2002]
I have a virtual environment in which I'm trying to run:
sns.scatterplot(X_embedded[:,0], X_embedded[:,1], palette=palette)
but I end up with
AttributeError: module 'seaborn' has no attribute 'scatterplot'

I have made sure all my dependencies are proper and there's no error due to that. Am I missing anything?

**Comment by mwaskom** [comment]
You must not have updated the dependencies in the environment you’re using. What does `seaborn.__version__` say?

**Comment by srinathsrk76** [comment]
Here's an output of !pip freeze
cycler==0.10.0
joblib==0.14.1
kiwisolver==1.1.0
matplotlib==3.2.1
numpy==1.18.2
pandas==1.0.3
patsy==0.5.1
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
scipy==1.4.1
seaborn==0.10.0
six==1.14.0
statsmodels==0.11.1

**Comment by mwaskom** [comment]
That wasn't my question. What version of seaborn is imported in your python session?

**Comment by srinathsrk76** [comment]
it still says '0.10.0'. Attached screenshot for reference
![image](https://user-images.githubusercontent.com/54982849/77256201-bbccaf00-6c92-11ea-8846-2f2596b9bd7e.png)

**Comment by mwaskom** [comment]
Please show a complete session in which seaborn 0.10 is used and `scatterplot` is not available.

**Comment by mwaskom** [comment]
Closing for lack of response.
