### ISSUE TITLE
Y-axis in kdeplot is greater than 1

### ISSUE THREAD

**Issue by Hailprob** [mwaskom/seaborn#2003]
code: 
sn.kdeplot(data)
![image](https://user-images.githubusercontent.com/22728430/77287572-cf1e5f80-6d10-11ea-91a4-0383615ff963.png)
As far as I know, kde is a kind of probability density estimation, so the y-axis should be smaller than 1.

**Comment by mwaskom** [comment]
https://en.wikipedia.org/wiki/Probability_density_function

**Comment by Hailprob** [comment]
Sorry, I was mistaken, f(x) does not subject to f(x) le 1
