### ISSUE TITLE
Kdeplot: `IQR = 0`  leads to `bw = 0` and to error

### ISSUE THREAD

**Issue by mycarta** [mwaskom/seaborn#2004]
I am referencing a `statsmodels` issue [(#5419, for which I just added a comment)](https://github.com/statsmodels/statsmodels/issues/5419#issuecomment-602699607) because it affects the kde plots in `seaborn` when  `IQR = 0`  leads to `bw = 0`

I wonder if there is a possibility to handle it with `try except`.
It was suggested by someone with clearly a better understanding that I have maybe to "check if IQR is 0 and then perhaps add noise (with some level) so the IQR and SD are similar. If you have SD = 0, then ... then it should just plot point ... maybe"

**Comment by mwaskom** [comment]
Isn’t this a duplicate of #1990?

**Comment by mycarta** [comment]
Ah, yes, it looks like it. I was searching for 'kde' specifically in old issues. Thanks.  Will close and post there as comment.
