### ISSUE TITLE
Parameter "size" not documented in FacetGrid

### ISSUE THREAD

**Issue by Michael-E-Rose** [mwaskom/seaborn#2007]
The [documentation for FacetGrid](https://seaborn.pydata.org/generated/seaborn.FacetGrid.html#seaborn.FacetGrid) lacks the parameter "size".

I thought it would refer to matplotlib's figsize parameter, but that's obviously not the case (at least, I get a cryptic error when I give size the same input I would give to figsize). Therefore it might be good to have that parameter documented.

**Comment by mwaskom** [comment]
`size` is a deprecated parameter. It is accepted for backwards-compatibility but will be removed in a future version. You should see the message:

> UserWarning: The `size` parameter has been renamed to `height`; please update your code. warnings.warn(msg, UserWarning)
