### ISSUE TITLE
Factorplot problem

### ISSUE THREAD

**Issue by emshihab** [mwaskom/seaborn#2008]
![p1](https://user-images.githubusercontent.com/62748262/77766608-2ccbe800-7040-11ea-9181-ff77122a0a31.JPG)
![p2](https://user-images.githubusercontent.com/62748262/77766621-31909c00-7040-11ea-869c-507f7ecf24b2.JPG)
![p3](https://user-images.githubusercontent.com/62748262/77766632-348b8c80-7040-11ea-9b73-52106954bb77.JPG)
![p4](https://user-images.githubusercontent.com/62748262/77766641-36ede680-7040-11ea-9f42-91969166b232.JPG)
Hi everyone,
I need a help. For one problem, I had to use factorplot. But it is now working. What is the problem? I am sharing with you a image file of the coding i did.

Regards,
Ekram

**Comment by mwaskom** [comment]
Calling `factorplot` with only one variable specified used to make it default to `kind="count"` but that behavior was deprecated about 5 years ago. Also, `factorplot` itself was deprecated (renamed to `catplot`) about 2 years ago.
