### ISSUE TITLE
set_color_codes as context

### ISSUE THREAD

**Issue by zerothi** [mwaskom/seaborn#2009]
It would be nice to allow color codes as context
```python
with sns.set_color_codes('deep'):
    ...
with sns.set_color_codes('pale'):
    ...
```
I am currently overlaying different bars (much like [this](https://seaborn.pydata.org/examples/horizontal_barplot.html)).

Additionally it would be nice to grap the current `color_codes`:

```python
old_color_code = sns.get_color_codes()
...
sns.set_color_codes(old_color_code)
```

**Comment by mwaskom** [comment]
This does not exist but in newer matplotlibs you can access the current color cycle with `"C0"`, `"C1"`, `"C2"`, ...

**Comment by zerothi** [comment]
But out of consistency wouldn't it make sense to allow the context? I.e. it is unclear for a seaborn+matplotlib user where the boundary goes between the two :)

**Comment by mwaskom** [comment]
I don't know. I'm trying to help you solve your problem quickly.

**Comment by zerothi** [comment]
Thanks. :)

**Comment by mwaskom** [comment]
Closing as this can be accomplished with `C{N}` codes and the existing palette context managers.
