### ISSUE TITLE
Strange error with facetgrid+heatmap

### ISSUE THREAD

**Issue by Arakkun** [mwaskom/seaborn#2014]
A single row in 4 subplots doesn't show [Here](https://puu.sh/FrXLU/f214c473df.png) (The Problem23 row of the heatmap), yet if I plot that single row, it does show [Here](https://puu.sh/FrXLS/c3dfdca59e.png)

**Comment by mwaskom** [comment]
I'm sorry but I have no idea what you're showing here. I suggest making a reproducible example and asking on StackOverflow.

**Comment by Arakkun** [comment]
I tried making experiments with different data / ordering / etc., but the "problem23 row" of the 4 subplots in the top and middle part doesn't show only in that particular case.
Modifying the order makes the "last row" (now "problem9") of the same subplots like "hidden" [here](https://puu.sh/FrZ8A/fc6f982544.png) 
The same happens with the previous ordering, but directly eliminating the "problems23" row, but in this case the problem is inherited by the now last "problems22" row

This may probably be a bug, based on some kind of auto-hiding or such. This kind of "peculiar" question will never get answers on StackOverflow usually. It is the same as
- [Here is one](https://stackoverflow.com/questions/37931809/seaborn-facetgrid-heatmap-with-row-missing?rq=1)
- [Another one](https://stackoverflow.com/questions/37931809/seaborn-facetgrid-heatmap-with-row-missing)
