### ISSUE TITLE
Why not 'sem'???

### ISSUE THREAD

**Issue by Pusm** [mwaskom/seaborn#2016]
ci=68 and SEM is not same when the distribution of dataset is non-parametric. Therefore, we cannot calculate SEM with seaborn for now. We shouldn't confuse these especially in scientific papers. (Many physiological phenomena is non-parametric...)

Seaborn is definitely great module and I really love it, but this point seems to be a strong drawback...because most scientific paper use SEM (NOT ci=68). 
Unfortunately , we cannot use seaborn in scientific papers when we want to use 'SEM'!

**Comment by mwaskom** [comment]
>  Unfortunately, we cannot use seaborn in scientific papers when we want to use 'SEM'!

OK, then don't.

**Comment by Pusm** [comment]
Everyone knows ci=95 is the best way from the statistical point of view.
But introducing SEM can approach to more people.

Anyway, I respect your decision because this is your app.
