### ISSUE TITLE
Using legend='brief' with scatterplot and hue can give misleading maximum value

### ISSUE THREAD

**Issue by asongtoruin** [mwaskom/seaborn#2021]
Slightly related to #2020, I'm having an issue with the values shown for a `scatterplot` using `hue` for a numeric range. To give an example:

```python
from itertools import product

import matplotlib.pyplot as plt
import matplotlib.patheffects as path_effects
import numpy as np
import seaborn as sns


fig, ax = plt.subplots(figsize=(10,10))

vals = list(product(range(1, 21), range(1, 21)))

sns.scatterplot(
    x=[v[0] for v in vals],
    y=[v[1] for v in vals],
    hue=[v[0] * v[1] for v in vals],
    palette='plasma',
    legend='brief', ax=ax, 
    s=650, ec=None
)

for v in vals:
    text = ax.text(v[0], v[1], v[0]*v[1], va='center', ha='center')
    text.set_path_effects([path_effects.Stroke(linewidth=3, foreground='white', alpha=.5),
                           path_effects.Normal()])

plt.legend(loc='center left', bbox_to_anchor=(1.01, 0.5))
```

Gives us:

![Example scatterplot with hue](https://user-images.githubusercontent.com/20771863/78701485-09862000-78ff-11ea-821d-dbd08da26dd7.png)

With the maximum value shown in the legend of 450, despite the maximum value in the data being 400. As both 150 and 300 are values included in the array, we can compare the colours in the legend to the colours in the graph - and these do appear to match up correctly. So the correct colours are being grabbed for the values, but the maximum value appears misleadingly high.

Is there any way to get the maximum value to be capped at (or closer to) the maximum of the data? I've tried using `hue_norm` too but with no success.

**Comment by mwaskom** [comment]
No, sorry. The current implementation uses matplotlib ticker objects that find "nice" values for the legend but don't aim to explicitly represent the minimum and maximum values in the data. It's always possible to create your own legend entries, however, if you don't like the default.

**Comment by mwaskom** [comment]
I'm going to close this as it is a known limitation of the current implementation, but improvements are planned.

**Comment by asongtoruin** [comment]
Seems sensible to me. Looking forward to seeing what future changes you make - let me know if there's anything I can do to help or test. Thanks for creating one of the most essential Python graphing libraries!
