### ISSUE TITLE
creating a seaborn palette for R/ggplot2

### ISSUE THREAD

**Issue by chr1swallace** [mwaskom/seaborn#2022]
I really love the seaborn colour palette, and have made my own copy for use with ggplot2 in R. I would like to share it on github, but need to ask about naming it. Your license says I can't use the seaborn name without written permission, but not using it seems rude, because I have literally lifted the hexcodes from https://github.com/mwaskom/seaborn/blob/master/seaborn/palettes.py

I am therefore writing to ask whether you would rather I use the name "seaborn_palette" and link to this repo, or create an alternative name and still link to this repo to give credit for the very nice colour choices?

Thanks.

**Comment by mwaskom** [comment]
The third clause of the BSD license is a little ambiguous. In general, I don't think you should read it as applying to situations like this — I think it has more to do with commercial marketing. In any case, I have no specific problem with what you are asking to do. But do keep in mind that there is [more than one](http://seaborn.pydata.org/tutorial/color_palettes.html#qualitative-color-palettes) "seaborn palette".
