### ISSUE TITLE
Incorrect drawing of graphs seaborn.lineplot(time_rows)

### ISSUE THREAD

**Issue by Eugeny1978** [mwaskom/seaborn#2024]
Incorrect drawing of graphs seaborn.lineplot(time_rows)

The reason is a bug when recognizing the date-time in the index.
df.Date_time[1]
>>> Timestamp('2017-08-18 00:00:00')

See attached files.
https://yadi.sk/d/wcA1v1AprETRtQ
https://yadi.sk/d/x8XLZuJ-2K-Flg

But you should remove the date from the data - the curve is drawn correctly.

I work for Jupiter Notebook
Installed versions of packages:
numpy = 1.18.1
scipy = 1.4.1
pandas 1.0.1
matplotlib 3.1.3
statsmodels 0.11.0
![graph_bag](https://user-images.githubusercontent.com/63551632/79073736-d245b380-7cf0-11ea-9f4f-a3352c840349.png)
![graph_correct](https://user-images.githubusercontent.com/63551632/79073740-d376e080-7cf0-11ea-9bcf-90f575b3d384.png)

**Comment by mwaskom** [comment]
I’m sorry, but I don’t really understand this issue. Why do you think seaborn is doing something wrong? Also please share your example as code that can be copied and pasted (not a screenshot) and text files uploaded directly to github (not a sketchy third party site), or else I won’t be able to help.

**Comment by Eugeny1978** [comment]
download attached files:
data:
https://yadi.sk/d/wcA1v1AprETRtQ
code:
https://yadi.sk/d/x8XLZuJ-2K-Flg

**Comment by mwaskom** [comment]
Again, I’m not going to download anything from that website. Files can be dropped directly into a GitHub comment, or even better, pasted in as text.

**Comment by Eugeny1978** [comment]
`import pandas as pd
%matplotlib inline
import seaborn as sns
import matplotlib.pyplot as plt

Names = ['Date_time', 'Open', 'High', 'Low', 'Close', 'Volume']
path_to_file = 'C:/data.csv'

data = pd.read_csv(path_to_file, sep=';', parse_dates=True, names=Names, index_col=0)
data.tail()

# BAG
plt.figure(figsize=(20,7))
sns.set(style="darkgrid")
sns.lineplot(data=data.Close, label='Close')

# If drop dates - plot is correct
df = data.reset_index()
df.tail()

plt.figure(figsize=(20,7))
sns.lineplot(data=df.Close, label='Close')

`
github does not allow me to attach a file *.csv  with data

**Comment by mwaskom** [comment]
You just need to change the extension to `.txt`. e.g., here is the example tips dataset:

[tips.txt](https://github.com/mwaskom/seaborn/files/4466946/tips.txt)

**Comment by Eugeny1978** [comment]
[data.txt](https://github.com/mwaskom/seaborn/files/4468151/data.txt)

**Comment by mwaskom** [comment]
Your index is not defined correctly — or at least, it does not represent monotonically increasing dates:

```
plt.plot(data.index)
```
![image](https://user-images.githubusercontent.com/315810/79120778-b7f7ee00-7d61-11ea-9133-93e18e8c5eee.png)

**Comment by mwaskom** [comment]
Closing as not a seaborn issue.
