### ISSUE TITLE
Add split palette and hatching to violinplot?

### ISSUE THREAD

**Issue by lilyminium** [mwaskom/seaborn#2027]
Hi Seaborn devs,

I modified the violinplot for more flexible palette colouring and hatching when data is split by hue. Would you be interested in adding this functionality to violinplot? If so, I'd be happy to clean it up and make a PR.

Edit: to clarify, there is currently no way to colour by x-axis category when the `hue` keyword is given, and no current way to add hatching to any of the fills. The modifications are two new keywords, `hatch=None` and `split_palette=False`.

![Screenshot 2020-04-16 at 10 54 26 PM](https://user-images.githubusercontent.com/31115101/79458679-7d2dd880-8035-11ea-8545-bd542d47c306.png)

![Screenshot 2020-04-16 at 11 13 07 PM](https://user-images.githubusercontent.com/31115101/79460273-eca4c780-8037-11ea-9f6b-7f8620bae82d.png)

**Comment by mwaskom** [comment]
I would like to have more hatching in seaborn, however, hatches are kind of broken in matplotlib, both in terms of the API for controlling hatches and its implementation in some of the vector backends. I wouldn't want to add more options for hatching until that improves and stabilizes.

I don't think the `split_palette` fits with the semantics of `violinplot` or the way `hue` otherwise works in seaborn, so I would be -1 on that.

**Comment by mwaskom** [comment]
There are many github issues about hatching if you want to read more; here is at least one that I know of because I opened it: https://github.com/matplotlib/matplotlib/issues/11418

**Comment by mwaskom** [comment]
By the way here is a method for adding hatches hacking/extending the violinplot function itself:

```python
import seaborn as sns
import matplotlib as mpl

tips = sns.load_dataset("tips")

ax = sns.violinplot(x="day", y="total_bill", hue="sex", data=tips, split=True)
for i, violin in enumerate(ax.findobj(mpl.collections.PolyCollection)):
    if i % 2:
        violin.set_hatch("//")

ax.legend_.findobj(mpl.patches.Rectangle)[1].set_hatch("///")
```
![image](https://user-images.githubusercontent.com/315810/79461489-3d7ad880-7fc4-11ea-9f27-f642a610fafd.png)

**Comment by lilyminium** [comment]
> I don't think the split_palette fits with the semantics of violinplot or the way hue otherwise works in seaborn, so I would be -1 on that.

True, although it would be an optional keyword set to the current behaviour by default.

> hatches are kind of broken in matplotlib
>I wouldn't want to add more options for hatching until that improves and stabilizes.

Fair enough! That seems to be a no to both changes here, so I'll close the issue.

> here is a method for adding hatches hacking/extending the violinplot function itself

Thanks for that, I did look around for the magic way to get the violin objects but focused on methods that started with `get`. `ax.findobj()` is very useful to know.

**Comment by 666-sudo** [comment]
> By the way here is a method for adding hatches without hacking/extending the violinplot function itself:
> 
> ```python
> import seaborn as sns
> import matplotlib as mpl
> 
> tips = sns.load_dataset("tips")
> 
> ax = sns.violinplot(x="day", y="total_bill", hue="sex", data=tips, split=True)
> for i, violin in enumerate(ax.findobj(mpl.collections.PolyCollection)):
>     if i % 2:
>         violin.set_hatch("//")
> 
> ax.legend_.findobj(mpl.patches.Rectangle)[1].set_hatch("///")
> ```
> 
> ![image](https://user-images.githubusercontent.com/315810/79461489-3d7ad880-7fc4-11ea-9f27-f642a610fafd.png)

This didn't work, but instead I used:
[c for c in ax.get_children() if isinstance(c, matplotlib.patches.Rectangle)][1].set_hatch("//")
