### ISSUE TITLE
TypeError: regplot() got an unexpected keyword argument 'kind'

### ISSUE THREAD

**Issue by PlantDr430** [mwaskom/seaborn#2029]
Hello, I am trying to utilize `regplot()` together with `FacetGrid()` similar to the example provided [here](https://seaborn.pydata.org/generated/seaborn.FacetGrid.html#seaborn.FacetGrid) "Define a custom function that uses a DataFrame object" 

I am still learning, so this might just be a simple slip in my code that I am missing.

I am able to get my data working with a simple lineplot, similar to the example:

```
def dataplot(x, y, **kwargs):
    ax = plt.gca()
    data = kwargs.pop('data')
    data.plot(x=x, y=y, ax=ax, grid=False, **kwargs)

def create_line_graphs(df):
    g = sns.FacetGrid(df, col='Scaffold', col_wrap=4, height=1.5, sharex=False, aspect=2)
    g = g.map_dataframe(dataplot, 'Position on contig (kbp)', 'ρ', color='black', linewidth=0.75)
```

With outputs looking like this:

![Working_line_graph](https://user-images.githubusercontent.com/29610303/79640325-354ea480-814e-11ea-8328-01c6716219e7.PNG)

However, I wanted to try to create a smooth line through `regplot()` and the `kind='line'` parameter. I initial got regplot() working on default settings, with some adjustments to the code:

```
def smoothplot(x, y, **kwargs):
    ax = plt.gca()
    d = kwargs.pop('data')
    sns.regplot(x=x, y=y, data=d, ax=ax, **kwargs)

def create_line_graphs(df):
    g = sns.FacetGrid(df, col='Scaffold', col_wrap=4, height=1.5, sharex=False, aspect=2)
    g = g.map_dataframe(smoothplot, 'Position on contig (kbp)', 'ρ', color='black')
```

Which resulted in:
![regplot_dots](https://user-images.githubusercontent.com/29610303/79640367-878fc580-814e-11ea-9ce7-b46c54cc9f8c.PNG)

Although, when I try to implement kind='line' into the sns.regplot() call:

```
def smoothplot(x, y, **kwargs):
    ax = plt.gca()
    d = kwargs.pop('data')
    sns.regplot(x=x, y=y, data=d, ax=ax, kind='line', **kwargs)

```
I am getting an error:

```
Traceback (most recent call last):
  File "./recombination_landscape.py", line 192, in <module>
    create_line_graphs(data_df)
  File "./recombination_landscape.py", line 179, in create_line_graphs
    g = g.map_dataframe(smoothplot, 'Position on contig (kbp)', 'ρ', color='black')
  File "/usr/local/lib/python3.7/dist-packages/seaborn/axisgrid.py", line 833, in map_dataframe
    self._facet_plot(func, ax, args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/seaborn/axisgrid.py", line 851, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "./recombination_landscape.py", line 175, in smoothplot
    sns.regplot(x=x, y=y, data=d, ax=ax, kind='line', **kwargs)
TypeError: regplot() got an unexpected keyword argument 'kind'
```

Any assistance would be greatly appreciated.

**Comment by VelmuruganKanagaraj** [comment]
Hi Team,

I am tried to execute below comment ,

sns.regplot(x = 'timepoint',y= 'signal', kind ='line', data = fmri).

when i got below error.

TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_3524/4285944037.py in <module>
----> 1 sns.regplot(x = 'timepoint',y= 'signal', kind ='line', data = fmri)

~\anaconda3\lib\site-packages\seaborn\_decorators.py in inner_f(*args, **kwargs)
     44             )
     45         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 46         return f(**kwargs)
     47     return inner_f
     48 

TypeError: regplot() got an unexpected keyword argument 'kind'

Any assistance would be greatly appreciated.
