### ISSUE TITLE
Seaborn version 0.10  pairplot not same as version 0.9.0

### ISSUE THREAD

**Issue by EdWoo88** [mwaskom/seaborn#2031]
Hi,
Recently I installed  Anaconda3-2020.02-Linux-x86_64.sh or pkg on a new system and reported it as anaconda issue, but may just be a seaborn issue with this line of code.
![2020-04-20 12_39_23-pairplot_not_issue_in_jpnb_6_0_thru_6_0_2](https://user-images.githubusercontent.com/6903073/79795928-91115d00-8309-11ea-94e6-6b78f0fbe86d.png)
![pairplot different as of jpnb_6_0_3 on MAC as of 2020-04-20](https://user-images.githubusercontent.com/6903073/79795931-91a9f380-8309-11ea-88a8-349dbb7b6e98.png)

Summary:
 jupyter notebook 6.0.3 uses seaborn 0.10.0 and pairplot appears to drop last column of the dataframe.
it still works on jupyter notebook 6.0.0 thru 6.0.2 with seaborn 0.9.0 and displays the last column of dataframe.

Hope it is clear.

Ed Woo
PS. This is my first bug report, so email me if you need to re-confirm.

**Comment by mwaskom** [comment]
I'm afraid that I'm not completely sure I understand the issue from this description (please don't share screenshots of code, and upload figures directly to github).

Nevertheless, [the release notes](http://seaborn.pydata.org/whatsnew.html#v0-9-1-january-2020) for 0.9.1 say

> In PairGrid, the hue variable is now excluded from the default list of variables that make up the rows and columns of the grid.

Which is probably what you are seeing.

**Comment by EdWoo88** [comment]
Hi Michael,
Sorry to have concerned you.

I initially wanted to try out the new debugger in jpnb 6.0.3 and ran into
that hue column not showing up because anaconda-navigator had already
included seaborn 0.10.0.
From your respond stating seaborn 0.9.1 specifically remove the hue column
from the graph.  I better read new and version  release features, but the
instructor's suggested graph had the hue column displaying and thus the bug
report.

I reverted back to seaborn 0.9.0 to ensure my graph matched the assignment.
I do not know whether it is a good or not good to remove the hue column
since I am only 6 months old using jupyter notebook.   I will read the
release notes next time before complaining.

Thanks for the quick response.
Stay safe.

Ed
