### ISSUE TITLE
Key Error when importing Seaborn 

### ISSUE THREAD

**Issue by rhan9** [mwaskom/seaborn#2039]
I was importing seaborn today and I got the following Key Error: 

*'axes.color_cycle is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'*

So I tried following the suggestions posted here: https://github.com/ralph-group/pymeasure/issues/153, and changed "axes.color_cycle" found in Seaborn's rcmod.py to "axes.prop_cycle", but that didn't work. 

Any ideas why this error is occuring. I used Seaborn yesterday and it was working fine.

**Comment by timmytam13** [comment]
How did you fix this?  I got this error today and I can't figure it out

**Comment by rhan9** [comment]
I fixed the issue by upgrading my Seaborn package. 
It was not up to date. 
Hope this helps!
