### ISSUE TITLE
Feature Request: facet-specific legends

### ISSUE THREAD

**Issue by massimopinto** [mwaskom/seaborn#2043]
After faceting by rows and columns for two variables, and hueing for a third one, some facets might contain only some [hue](url) values.  It makes little sense then to have one _overall_ `FacetGrid` legend and diving through it to find the keys for any specific facet. It may be more practical to have the legend of each facet only to show the `hue` values that appear in that _specific_ facet. 
This was discussed, and resolved, in a [stackoverflow post](https://stackoverflow.com/questions/61503613/a-facet-specific-legend-in-each-facet-of-a-facetgrid-seaborn) but it may be nice to make it a feature, possibly to be chosen with an argument of `.add_legend()` to be passed to the `FacetGrid` object.
![legend_in_facets](https://user-images.githubusercontent.com/15926033/80674135-5057d780-8ab1-11ea-9948-53a3e9a8924d.png)

**Comment by mwaskom** [comment]
My initial response is that I’m -1 on this.

**Comment by massimopinto** [comment]
> My initial response is that I’m -1 on this.

I am not sure whether this falls in the original philosophy of the project. However there may be instances in which having a legend that is specific to each facet might prove useful, as far as communicating results is concerned. If that is any suitable, I am happy to share an example from the kind of graphs that I am packaging for a manuscript to be submitted to a journal

**Comment by massimopinto** [comment]
Thank you @mwaskom, I understand that there is more than one solution to this (the answer by @ParfaitG to my original question on Overflow was also updated to work in a more general case). 
With respect to [#2046](https://github.com/mwaskom/seaborn/pull/2046), I first need to figure out how to deploy `seaborn` after pulling from a branch different from master (such as `facet_grid_convenience`) without upsetting my `conda` installation (now at 0.10.1). Using pip after `git checkout facet_grid_convenience` perhaps?
