### ISSUE TITLE
Colormap a relplot using a third column as a sequence of n numbers does not work using c **kwarg

### ISSUE THREAD

**Issue by jordanvoirin** [mwaskom/seaborn#2044]
It seems that when one uses the 'c' **kwarg to colormap a scatter plot for example, there is an overlap with the 'color' argument that seaborn must input in the matplotlib.pyplot.scatter function.

Indeed, when I use th efollowing line
sns.relplot(x='diff_I1',y='diff_Sw',data=dataWthWork,s=10,c=dataWthWork.diff_T,cmap='hsv')
I get the following error ->
ValueError: Supply a 'c' argument or a 'color' kwarg but not both; they differ but their functionalities overlap.

I had to use the following command:
plt.scatter(dataWthWork['diff_I1'],dataWthWork['diff_Sw'],s=10,c=dataWthWork['diff_T'],cmap='hsv')
instead of the one using the seaborn package.

Hope it serves your development.
Cheers

**Comment by mwaskom** [comment]
Yes, this makes sense.
