### ISSUE TITLE
Heatmap: nan cause "color leak" in other cell

### ISSUE THREAD

**Issue by domi84** [mwaskom/seaborn#2047]
Hello, I tried to search online and here for this issue, but I didn't find anything relevant.
I am trying to plot some heatmap with nan values, in the heatmap some cells are "leaking" in other cells, the lines are not straight anymore

```
import seaborn as sns; sns.set()
ax = sns.heatmap(df)
```
![rect922](https://user-images.githubusercontent.com/1794097/80955257-e3b54380-8df6-11ea-90fb-3fc0a5035966.png)

If I replace them with zeros it is ok.

`
ax = sns.heatmap(df.fillna(0))
`

![zeros](https://user-images.githubusercontent.com/1794097/80955869-f67c4800-8df7-11ea-90ea-844229bae254.png)

Do you have any idea why this is happening?
Any workaround?
Thanks

Some system info:
Windows 10
python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
pandas v 0.23.4
seaborn v 0.10.1
matplotlib v 3.2.1

**Comment by mwaskom** [comment]
I’m not sure why this is happening but rendering artifacts like this are very likely occurring at the matplotlib layer. I bet you could easily reproduce using `plt.pcolormesh` directly.

**Comment by domi84** [comment]
Sorry, I never used matplotlib so took me a while to do it. Yes, I can reproduce it using pcolormesh.
I opened a bug there.
https://github.com/matplotlib/matplotlib/issues/17323

Thanks
