### ISSUE TITLE
Heatmap Won't Accept DataFrame

### ISSUE THREAD

**Issue by domanjeremy** [mwaskom/seaborn#2048]
Heatmaps (and I assume most maps/graphs in seaborn) won't accept a DataFrame created in pandas as an argument, even though the parameters say they do. A np.array can be converted to a pd.DataFrame, and then graph will accept a heatmap; however, pd.DataFrame can't be used for a graph and this causes a Type error. I have tested to make sure every value was a float, and that there were no null values in the DataFrame. I recreated the issue making and found that the size of the DataFrame was not a problem either. I think the documentation should just clarify that the graphs only accept np.arrays, and that a dataframe should be converted to an array using np.to_array

**Comment by mwaskom** [comment]
If you look at the documentation or tests, you will find abundant examples of data frames being used as arguments.

If you need help with a specific issue, I suggest making a reproducible example and asking on stackoverflow.
