### ISSUE TITLE
stripplot has too much jitter and you cannot change it using the jitter parameter

### ISSUE THREAD

**Issue by hwalinga** [mwaskom/seaborn#2049]
Seems this broke over an update of a package. 

These are the versions of my packages on Python 3.7:

```
Package         Version
--------------- -------
cycler          0.10.0 
kiwisolver      1.2.0  
matplotlib      3.2.1  
numpy           1.18.4 
pandas          1.0.3  
pip             18.1   
pkg-resources   0.0.0  
pyparsing       2.4.7  
python-dateutil 2.8.1  
pytz            2020.1 
scipy           1.4.1  
seaborn         0.10.1 
setuptools      40.8.0 
six             1.14.0 
```

When I run the first example from the stripplot I get this. 

![stripplot](https://user-images.githubusercontent.com/13176356/81068185-3cacd680-8ee0-11ea-88bd-2ee98b3e3f4c.png)

So, too much jitter, much more than shown in the docs, and if try to change it with the jitter parameter it does not change.

**Comment by hwalinga** [comment]
Doing some tests I can confirm this breaks in matplotlib 3.2.

**Comment by mwaskom** [comment]
I suspect a similar issue to https://github.com/mwaskom/seaborn/issues/2013

matplotlib made some unexpected changes to how autoscaling works and broke some things, unfortunately.

**Comment by mwaskom** [comment]
It's not identical to #2013 though, because `stripplot` doesn't use the axes transforms the way `swarmplot` does. I haven't narrowed down a pure matplotlib example of the issue yet.

**Comment by mwaskom** [comment]
OK see https://github.com/matplotlib/matplotlib/issues/17331

It's possible this will have to be fixed on the seaborn side, but I don't really understand exactly what matplotlib changed and they didn't, as far as I can tell, document the new behavior in the release notes.

**Comment by hwalinga** [comment]
I followed along on the discussion in matplotlib. 

It seems that the interpretation of auto=None in set_{x,y}lim is the problem. 

I changed this to auto=False and did seems to result in the expected behavior. I tested this in matplotlib version 3.2, 3.1 and 2.1.

**Comment by mwaskom** [comment]
Fixed upstream (https://github.com/matplotlib/matplotlib/pull/17408)

**Comment by mwaskom** [comment]
Matplotlib 3.2.2 is now out and fixes this (and related) issues.
