### ISSUE TITLE
Some categorical plots fail when y is datetime

### ISSUE THREAD

**Issue by MaozGelbart** [mwaskom/seaborn#2056]
Categorical plots are not interchangeable when the dependent variable is np.datetime. Apart from stripplot and swarmplot they all may fail. Consider the following code:
```python
import seaborn as sns
import numpy as np
dates = np.arange('2020-03', '2020-04', dtype='datetime64[D]')
cats = np.repeat("cat", len(dates))
for func in [sns.stripplot, sns.swarmplot, sns.boxplot, sns.boxenplot, sns.violinplot, sns.barplot]:
    try:
         func(cats, dates)
    except Exception as ex:
         print(str(func), type(ex), ex)
```
The above code results with the following lines printed:
```
<function boxplot at 0x7f520e7af598> <class 'numpy.core._exceptions.UFuncTypeError'> ufunc 'add' cannot use operands with types dtype('<M8[ns]') and dtype('<M8[ns]')
<function boxenplot at 0x7f520e7af730> <class 'numpy.core._exceptions.UFuncTypeError'> ufunc 'multiply' cannot use operands with types dtype('<M8[ns]') and dtype('float64')
<function violinplot at 0x7f520e7af620> <class 'TypeError'> invalid type promotion
<function barplot at 0x7f520e7af8c8> <class 'numpy.core._exceptions.UFuncTypeError'> ufunc 'add' cannot use operands with types dtype('<M8[ns]') and dtype('<M8[ns]')
```

The problem is that datetime variable is not identified as categorical and also not identified as non-numeric and therefore specific plotters attempt to perform operations that expect numeric input. Categorical plots docstrings currently don't mention datetime y (only datetime x). 

Probably the easiest fix to maintain consistency between all categorical plots would be changing the following method to identify dates as non-numeric (perhaps using [pandas.api.types.is_numeric_dtype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.types.is_numeric_dtype.html)).
https://github.com/mwaskom/seaborn/blob/562fd90216d5529ab8f26b388168e6ef260d7e6c/seaborn/categorical.py#L330-L335
However this will also disable stripplot and swarmplot with dates.

**Comment by mwaskom** [comment]
Thanks for catching. I don't really work with date time ever, so I have poor intuitions for what should work (and what people expect to work, which is a distinct category).

At least in some cases, pandas seems able to do math on date times:

```
pd.date_range("2010-01-01", periods=200, freq="d").to_series().mean()
```
```
Timestamp('2010-04-10 12:00:00')
```

So should datetime always be considered not_numeric, or should the numeric operations be fixed to work with datetime?

**Comment by MaozGelbart** [comment]
For a broader context, lineplot also fails when y is np.datetime:
```python
dates = np.arange('2020-03', '2020-04', dtype='datetime64[D]')
numbers = np.tile([0,1,2,3],len(dates))[:len(dates)]
for func in [sns.scatterplot, sns.lineplot]:
    try:
         func(numbers, dates)
    except Exception as ex:
         print(str(func), type(ex), ex)
```
Which prints
``<function lineplot at 0x7f41bece9d08> <class 'pandas.core.base.DataError'> No numeric types to aggregate``

However, relational plots treat datetime as categorical (due to a failed float conversion, but this is probably not intentional towards datetime). I'm not interrogating datetime data too much but in most examples I encounter it's the independent variable (but see #1693 for example of datetime hue). 

Perhaps, datetime data should neither be considered numeric nor categorical but "datetimelike"? pandas distinguished these types:
```python
pd.Series(dates).astype(np.float)  # TypeError: cannot astype a datetimelike from [datetime64[ns]] to [float64]
```

**Comment by mwaskom** [comment]
xref #2084

**Comment by mwaskom** [comment]
With #2084 your example prints `<function boxplot at 0x11359e670> <class 'TypeError'> Neither the `x` nor `y` variable appears to be numeric.` for plots that fail but continues to render a plot for `swarmplot` and `stripplot`.

Datetime `hue` variables continue to get a qualitative colormap in the relational plots. I agree that a quantitative mapping makes sense here but that will need special handling downstream.

`lineplot` continues to fail with the same error (which is a little bit easier to understand than what numpy was throwing).

**Comment by MaozGelbart** [comment]
I'll close this as the reason for failures is now clear for the user. Will open a separate issue with an example regarding qualitative colormap when hue is datetime. Thanks!

**Comment by ijks** [comment]
I think I'm having a similar issue: I have a dataframe with a `country` categorical column, and a `created_at` datetime column. Using `catplot(data, kind='swarm', x='country', y='created_at')` works fine, but when I use `kind='violin'`, Seaborn complains with the aforementioned `TypeError: Neither the `x` nor `y` variable appears to be numeric`. I would expect otherwise, because I can still e.g. plot a distribution for all dates using `distplot`, and a violin plot does essentially that, just per category.
