### ISSUE TITLE
Exception thrown in distplot (LinAlgError: singular matrix)

### ISSUE THREAD

**Issue by geromidg** [mwaskom/seaborn#2058]
This is similar to issue #1502 

Minimal example to reproduce in v0.10:
`sns.distplot([1.23456789] * 10)`

However the following seems to work fine:
`sns.distplot([1.234567] * 10)`

**Comment by mwaskom** [comment]
On 0.10.1 I get a warning

> /Users/mwaskom/code/seaborn/seaborn/distributions.py:369: UserWarning: Default bandwidth for data is 0; skipping density estimation.

and a plot (without a density curve)

See https://github.com/mwaskom/seaborn/issues/1990 and https://github.com/mwaskom/seaborn/pull/2040 for more context.
