### ISSUE TITLE
Add Variable Cell Size for Heatmaps?

### ISSUE THREAD

**Issue by sachin-smart** [mwaskom/seaborn#2067]
Hi,

I came across [this article](https://towardsdatascience.com/better-heatmaps-and-correlation-matrix-plots-in-python-41445d0f2bec), which demonstrates what I think is quite a nice/useful way of presenting heatmaps. It uses the value of each cell to determine the size of the shape for that cell (see example below). The author seems to have created a package [heatmapz](https://pypi.org/project/heatmapz/) on the back of this, but it is quite restrictive.

![image](https://user-images.githubusercontent.com/61995745/81501982-1073ca00-92d3-11ea-8e57-78bf840664cd.png)

Given the usefulness of `sns.relplot()`, I would think it makes sense to include a `size` argument in the `sns.heatmap()` function that would allow the user to specify the size of each cell based on some other same-dimension array-like or the array itself. This would allow for uses like the one in the linked post as well as more complex cases where the size can depend on other variables like the annotations or something else.

I am not sure if this is possible / easy, but I think it would be a great addition to the function and package in general. Thank you for the package and for reading this suggestion.

**Comment by mwaskom** [comment]
It's not really possible to make `heatmap` itself make this kind of plot, but it's actually already almost possible with `relplot`/`scatterplot`:

```python
flights = sns.load_dataset("flights")
g = sns.relplot(x="year", y="month",
                hue="passengers", size="passengers",
                sizes=(40, 400), data=flights)
g.ax.invert_yaxis()
```
![image](https://user-images.githubusercontent.com/315810/81503169-2c19a900-92b0-11ea-836f-79d2def69aaf.png)

It's not perfect for a few reasons:

- circles, not squares
- don't get a continuous colorbar
- you need to manually fiddle around with the `sizes` to get a good range

A little bit of manual work can fix most of these issues:

```python
sns.set(style="dark")
flights = sns.load_dataset("flights")
g = sns.relplot(x="year", y="month",
                hue="passengers", size="passengers",
                hue_norm=(100, 600), size_norm=(100, 600),
                palette="mako_r", sizes=(40, 400),
                marker="s", linewidth=0, legend=False,
                aspect=1.25, data=flights)
g.ax.invert_yaxis()
ghost = g.ax.scatter([], [], c=[], vmin=100, vmax=600, cmap="mako_r")
g.fig.colorbar(ghost)
```
![image](https://user-images.githubusercontent.com/315810/81503363-38523600-92b1-11ea-827a-69244c3eee73.png)

This seems easy enough to be useful for most people, but I am in the process of doing some refactoring that would make it easier to add a new function in seaborn for making plots like this, and doing so is on the provisional roadmap (https://github.com/mwaskom/seaborn/issues/2054).

**Comment by sachin-smart** [comment]
That's awesome! I really appreciate the quick reply and thorough explanation.
