### ISSUE TITLE
calculated stats

### ISSUE THREAD

**Issue by razcore-rad** [mwaskom/seaborn#207]
Is there any way to access the stats once the plots are done? Say for example after plotting with `lmplot`. You end up with all sorts of regressions and fancy stuff happening under the hood. Is it possible to access the parameters of these regressions?

If not I think this would make a very nice addition. I'm plotting a linear model now for example and I would like to access the slope, etc. for manually adding this information onto the graph. Because I don't know how to access those things (if there's a way) I'm forced to recalculate everything...

Thanks

**Comment by dhimmel** [comment]
> is there a parameter that will display the stats in the plot?

I agree that these stats embedded as texts are incredibly valuable for visualizations. The danger with the current paradigm is that you accidentally calculate incorrect values when you try to replicate the abstracted analysis. Additionally, much of seaborn's convenience is lost when an entire modeling process must be explicitly coded.

I think that Hadley's workflow mentioned by @mwaskom makes sense for exploratory data science. However, for publication stage graphics I believe the opposite is true: visualization should directly represent the models that statistics are reported for.
