### ISSUE TITLE
Plotting and displaying only specific row labels in heatmap/clustermap

### ISSUE THREAD

**Issue by droricu** [mwaskom/seaborn#2070]
I'm creating a fairly large clustermap (~10k rows), and want to put ylabels only at specific rows.
So far, what I've been able to do is to pass a list to the yticklabels arg, which has None except for the specific rows I want to label. However, executing this line now takes much longer than leaving the arg out (timed it at ~6mins relative to ~2secs without passing anything to yticklabels), and it also draws all of the ticklines which just looks like a dark gray column (see arrow):

![image](https://user-images.githubusercontent.com/42256032/81747600-375e0780-945d-11ea-9460-51ba1e49b9b8.png)

I've managed to get the ticklines to be invisible using this after creating the map with this (cm is the ClusterGrid object):
```
for ticks in cm.ax_heatmap.yaxis.get_major_ticks():
    ticks.tick2line.set_visible(False)
```
But it's still very slow.

Is there a way to label only the set of rows I'm interested, and not draw anything for the other rows?
Here's the behavior I'd like to get:
![image](https://user-images.githubusercontent.com/42256032/81745521-d84ac380-9459-11ea-84ba-3e99b93cc6ff.png)

I'm fairly new to data visualization with python, so I apologize if any information is missing or not presented correctly. Using Seaborn version 0.10.0, matplotlib 3.1.3, and python 3.7.6 (through Jupyter).

Thanks!

**Comment by mwaskom** [comment]
Nothing that's built into seaborn, but the object gives you the information to know where to put specific ticks. So you could do something like

```python
x = pd.DataFrame(np.random.randn(10, 3), index=list("abcdefghij"))

g = sns.clustermap(x, row_colors=sns.color_palette(), yticklabels=False)

reordered_labels = x.index[g.dendrogram_row.reordered_ind].tolist()
use_labels = ["a", "b", "c"]
use_ticks = [reordered_labels.index(label) + .5 for label in use_labels]

g.ax_heatmap.set(yticks=use_ticks, yticklabels=use_labels)
```

The `row_colors` is just to convince myself that things are going in the right place.
