### ISSUE TITLE
Top Half of Seaborn Chart Title Gets Cut Off

### ISSUE THREAD

**Issue by karriebear** [mwaskom/seaborn#2072]
When adding a title to a seaborn chart, the top half of the title is cut off

## Issue
![Figure_1](https://user-images.githubusercontent.com/24946400/81953090-423ba800-95d5-11ea-8aab-fe6b7a708589.png)

## Steps to reproduce
```
import matplotlib.pyplot as plt
import seaborn as sns

mpg = sns.load_dataset("mpg")
sns.relplot(
    x="horsepower",
    y="mpg",
    hue="origin",
    size="weight",
    sizes=(40, 400),
    alpha=0.5,
    palette="muted",
    height=6,
    data=mpg.query("origin == 'usa'")
)
plt.title('MPG vs Weight by Country of Origin')
plt.show()
```

**Comment by mwaskom** [comment]
This is a standard kind of matplotlib gotcha — you're adding a title using `pyplot` without making room for it.

If you are saving the plot, the easiest thing to do is to add `bbox_inches="tight"` to your `savefig` call.

If not, you'll need to adjust the subplots extent so there is room for a title. I would strongly advise using the object oriented interface, so something like

```python
import matplotlib.pyplot as plt
import seaborn as sns

mpg = sns.load_dataset("mpg")
g = sns.relplot(
    x="horsepower",
    y="mpg",
    hue="origin",
    size="weight",
    sizes=(40, 400),
    alpha=0.5,
    palette="muted",
    height=6,
    data=mpg.query("origin == 'usa'")
)
g.fig.subplots_adjust(top=.95)
g.ax.set_title('MPG vs Weight by Country of Origin')
```

**Comment by karriebear** [comment]
Thanks, this does work!

**Comment by mwaskom** [comment]
See also #2073
