### ISSUE TITLE
Changing tick labels in sns.clustermap

### ISSUE THREAD

**Issue by mdastro** [mwaskom/seaborn#2074]
Hi there,

I am trying to customize the labels in clustermap, but I'm having issues. I did the same thing with sns.heatmap which worked fine, but it raises erros in clustermap. 

Here is my code for the heatmap, which is working fine:

```cmap = sns.diverging_palette(240, 10, n=9)
ax = sns.heatmap(data=heatmap_upturn.corr(method='spearman'), cmap=cmap, vmin=-1., vmax=1.)
plt.xticks(ticks=np.arange(0,10,1), labels=[r"$\logM_{\star}}$", 
                                            r"$\left<\log t\right>_{r}$", 
                                            r"$\left<Z/Z_{\odot}\right>$", 
                                            r"sSFR$_{0.1\rm{Gyr}}$", 
                                            r"t$_{\rm{form}}$", 
                                            r"t$_{\rm{last}}$", r"f$_{\rm{burst}}^{2.9\rm{Gyr}}$", 
                                            'FUV-NUV',
                                            'FUV-r',
                                            'NUV-r'])

plt.yticks(ticks=np.arange(0,10,1), labels=[r"$\logM_{\star}}$", 
                                            r"$\left<\log t\right>_{r}$", 
                                            r"$\left<Z/Z_{\odot}\right>$", 
                                            r"sSFR$_{0.1\rm{Gyr}}$", 
                                            r"t$_{\rm{form}}$", 
                                            r"t$_{\rm{last}}$", r"f$_{\rm{burst}}^{2.9\rm{Gyr}}$", 
                                            'FUV-NUV',
                                            'FUV-r',
                                            'NUV-r'])
plt.show()
```

Producing:

![heatmap](https://user-images.githubusercontent.com/10452764/81995903-0ed33a80-9622-11ea-8ce4-4d15ea0a3e5a.png)

Then I try clustermap:

```
ax = sns.clustermap(data=heatmap_upturn.corr(), cmap=cmap)
plt.xticks(ticks=np.arange(0,10,1), labels=[r"$\logM_{\star}}$", 
                                            r"$\left<\log t\right>_{r}$", 
                                            r"$\left<Z/Z_{\odot}\right>$", 
                                            r"sSFR$_{0.1\rm{Gyr}}$", 
                                            r"t$_{\rm{form}}$", 
                                            r"t$_{\rm{last}}$", r"f$_{\rm{burst}}^{2.9\rm{Gyr}}$", 
                                            'FUV-NUV',
                                            'FUV-r',
                                            'NUV-r'])
plt.show()
```
Which is producing the following error:

![Captura de tela de 2020-05-14 20-37-58](https://user-images.githubusercontent.com/10452764/81996192-d54eff00-9622-11ea-9a23-1684bca1d0f6.png)

The labels don't change and I have the error above. I don't really want to change the labels in the colorbar, I just want to change them as I did in the heatmap.

Any suggestions? 

Thanks,

Maria Luiza

PS.: I'm sorry if you already have a similar issue that I haven't seen.

**Comment by mwaskom** [comment]
When you call `plt.xticks` you're using the ["pyplot interface"](https://matplotlib.org/3.2.1/api/index.html#usage-patterns), which as a notion of an "active" axes that gets modified. Instead, you should use the object-oriented interface with the `ax_heatmap` attribute on the object that `clustermap` returns.

Bear in mind that, because the clustermap reorganizes the rows/columns of the heatmap, your ticklabels won't be in an order that matches the plot.

**Comment by mdastro** [comment]
Thanks @mwaskom, I will try that! Yes, I am aware clustermap shuffles the parameters to gather those that are mostly correlated. I'll do it interactively, checking the order it returns.
