### ISSUE TITLE
scatterplot interpreting `color` parameter as a vector of values

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#2076]
```python
import seaborn as sns
sns.scatterplot([1, 2, 3, 4], [1, 2, 3, 4], color=(.2, .5, .8, 1), s=100)
```
![image](https://user-images.githubusercontent.com/315810/82119698-ad5cba00-974e-11ea-898a-7af1b57f285f.png)

This is related to a lot of old issues from when matplotlib changed handling of the `c=` parameter but interestingly it doesn't reproduce in the most obvious straight matplotlib translation

```python
plt.scatter([1, 2, 3, 4], [1, 2, 3, 4], color=(.2, .5, .8, 1), s=100)
```
![image](https://user-images.githubusercontent.com/315810/82119716-cc5b4c00-974e-11ea-921b-6c12fccbe2fc.png)

**Comment by mwaskom** [comment]
OK, here's why. `scatterplot` is essentially doing

```python
f, ax = plt.subplots()
kws = {}
scout = ax.scatter([], [], **kws)
c = kws.pop("c", scout.get_facecolors())

x = y = 1, 2, 3, 4
ax.scatter(x, y, c=c)
```

**Comment by mwaskom** [comment]
`c` is 2D in that case so it should be fine, but matplotlib must have made a change that squeezes the `c` input.

I just confirmed that I don't see the issue on 3.1.2.

**Comment by mwaskom** [comment]
This is a likely candidate for the problematic change: https://github.com/matplotlib/matplotlib/pull/14115

**Comment by mwaskom** [comment]
The docs for `ax.scatter` still say

> If you want to specify the same RGB or RGBA value for all points, use a 2-D array with a single row. 

So I consider this a bug in matplotlib.

**Comment by MaozGelbart** [comment]
See [https://github.com/matplotlib/matplotlib/issues/17423](https://github.com/matplotlib/matplotlib/issues/17423). This is a regression bug on the matplotlib side.

**Comment by mwaskom** [comment]
Oops, thanks, should have checked.

I opened https://github.com/matplotlib/matplotlib/issues/17431 too.

But will close.

**Comment by mwaskom** [comment]
Don't debug before coffee, would be good advice.

**Comment by petulla** [comment]
This also impacts the facetGrid column argument..

**Comment by mwaskom** [comment]
Fixed upstream.
