### ISSUE TITLE
TypeError: lmplot() got an unexpected keyword argument 'color'

### ISSUE THREAD

**Issue by meetpandya4715** [mwaskom/seaborn#2077]
I'm trying to do this in a jupyter notebook.
```
g = sns.FacetGrid(data=tips,col='day',row='sex')
g.map(sns.lmplot,'total_bill','tip')
```
this gives me the below error.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-35-dc3e866fbc45> in <module>
      1 g = sns.FacetGrid(data=tips,col='day',row='sex')
----> 2 g.map(sns.lmplot,'total_bill','tip')

C:\ProgramData\Anaconda3\lib\site-packages\seaborn\axisgrid.py in map(self, func, *args, **kwargs)
    760 
    761             # Draw the plot
--> 762             self._facet_plot(func, ax, plot_args, kwargs)
    763 
    764         # Finalize the annotations and layout

C:\ProgramData\Anaconda3\lib\site-packages\seaborn\axisgrid.py in _facet_plot(self, func, ax, plot_args, plot_kwargs)
    844 
    845         # Draw the plot
--> 846         func(*plot_args, **plot_kwargs)
    847 
    848         # Sort out the supporting information

TypeError: lmplot() got an unexpected keyword argument 'color'
```
as far as I know, sns.lmplot() does not have any argument called 'color'. g.map() somehow passes it by mistake.

**Comment by mwaskom** [comment]
a) it's not "by mistake", note that the [docstring](seaborn.pydata.org/generated/seaborn.FacetGrid.map.html) for `FacetGrid.map` says:

> func: callable
>     A plotting function that takes data and keyword arguments. It must plot to the currently active matplotlib Axes and take a `color` keyword argument. If faceting on the hue dimension, it must also take a `label` keyword argument.

b) `lmplot` already uses `FacetGrid internally, you just need to do

```python
sns.lmplot(data=tips, x="total_bill", y="tip", col="day", row="sex")
```

See other examples here: http://seaborn.pydata.org/generated/seaborn.lmplot.html
