### ISSUE TITLE
boxenplot(x=x, showfliers=False) isn't autoscaling

### ISSUE THREAD

**Issue by MaozGelbart** [mwaskom/seaborn#2085]
Possibly related to #2049. When plotting a boxenplot with a single series and using the new `showfliers=False`, the result is not autoscaled and the plot is centered around the median. Explicit autoscaling after plotting fixes the problem. Consider the following code:
```python
import seaborn as sns; sns.set_style("darkgrid")
import matplotlib.pyplot as plt
fig, axs = plt.subplots(3)
tips = sns.load_dataset("tips")
sns.boxenplot(x=tips["total_bill"], ax=axs[0], showfliers=True)
sns.boxenplot(x=tips["total_bill"], ax=axs[1], showfliers=False)
sns.boxenplot(x=tips["total_bill"], ax=axs[2], showfliers=False)
axs[2].autoscale_view(True)
for i, title in enumerate(["showfliers=True","showfliers=False","showfliers=False with autoscale"]):
    axs[i].set_title(title, loc="left")
plt.tight_layout()
```
Results with:

![boxen_shrink](https://user-images.githubusercontent.com/13831112/82301568-1c414980-99c1-11ea-8b4b-6338832a4f42.png)

**Comment by MaozGelbart** [comment]
This also happens for this figure from the documentation (for the petal_width pink row. No autoscale is triggered there due to lack of `ax.scatter` in the absence of outliers.
![https://seaborn.pydata.org/_images/seaborn-boxenplot-6.png](https://seaborn.pydata.org/_images/seaborn-boxenplot-6.png)

**Comment by mwaskom** [comment]
This one isn't too surprising actually, the boxes are drawn by creating a collection and adding it to the axes which doesn't normally trigger an autoscale, so we need to do it.
