### ISSUE TITLE
Support for RGB values in [0, 255] range

### ISSUE THREAD

**Issue by harabat** [mwaskom/seaborn#2088]
This stems from having to convert colour values between RGB 0-1, RGB 0-255, and hex when trying to keep a single palette while working with multiple visualisation libraries in the same notebook. 

Matplotlib normalises RGB values to [0, 1] range, but this is not the case for other libraries, like Pillow and Plotly for example. Hex has always been sufficient to share colour palettes, but I wonder whether expanding the support to 0-255 would be helpful. This would involve:
- adding an `as_rgb_255()` method to the `_ColorPalette` class in palettes.py (in addition to the `as_hex()` method)
- enabling `palplot()` to process 0-255 RGB values in miscplot.py
- enabling `set_palette()` to process 0-255 RGB values in rcmod.py

I'm happy to have a go if that's something worth doing.

**Comment by mwaskom** [comment]
Do Pillow and Plotly not accept hex codes?

**Comment by harabat** [comment]
They do, hex has always been sufficient for libraries to communicate, it's just that not every library takes 0-1 RGB values. I only ask because it took me a while to find the problem originally, and converting colours to hex is not always as straightforward in other libraries as a `sns.color_palette.as_hex()`. 

Again, this might not be within the scope of Seaborn, but it is my main visualisation library and my limited experience tells me that most other libraries have 0-255 RGB values as their base mode. I'm happy to work on a PR, but I'm also happy if people don't think this is an issue.

**Comment by mwaskom** [comment]
> I only ask because it took me a while to find the problem originally

Can you share an example of the problem you encountered (as code)?

This seems simple enough and I'm not opposed in general I'm just trying to understand the issue a bit more.

**Comment by harabat** [comment]
I was talking about the time it took me to originally find that different libraries preferred different colour codes, not a specific code issue. But here are my workarounds:
- to share a Seaborn colour palette with another library: `palette = sns.color_palette().as_hex()`
- to plot another library's colour palette: `sns.palplot([tuple(i / 255 for i in j) for j in palette])`
- to convert 0-255 RGB colours identified by another library to hex: `[('#%02x%02x%02x' % i) for i in colours]`

**Comment by mwaskom** [comment]
I think for now I'm going to keep seaborn's color palettes tied to matplotlib's definition of color; it's easy for users to work around this by multiplying/dividing by 255 where necessary.
