### ISSUE TITLE
Consider adopting new PyData sphinx theme

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#2093]
https://github.com/pandas-dev/pydata-sphinx-theme

**Comment by mwaskom** [comment]
Blocking issue upstream: https://github.com/pandas-dev/pydata-sphinx-theme/issues/146

**Comment by Anselmoo** [comment]
Dear @mwaskom ,

if you consider updating the **doc theme**, can you please take look on the **search engine**.

For not listed items, the docs are searching forever.

For example: Searching for **title** on [seaborn](https://seaborn.pydata.org/search.html?q=title&check_keywords=yes&area=default)

1. will not stop searching after 10min or more
2. will not show any results

Maybe it's caused to an older version of `mkdocs`??

**Comment by mwaskom** [comment]
Theme is unrelated to search engine. I don't know what's happening there. I also don't know what `mkdocs` is. seaborn uses sphinx.
