### ISSUE TITLE
Embedding seaborn into qt

### ISSUE THREAD

**Issue by diego0020** [mwaskom/seaborn#210]
Hello

I guess the main objective of seaborn is to run it on python notebooks. Nevertheless I see a lot of potential in embedding it into qt in order to create some interactive plots.

Here I have a simple example of what can be done
https://github.com/diego0020/correlation_viewer
<img src="https://github.com/diego0020/correlation_viewer/raw/master/screen_shot.PNG">

Using the axes level functions in this way is easy. However I have not been able to get it to work with higher level functions that create a "FacetGrid" . This is because they always create a new matplotlib figure. Here is an example of the closest I have been able to get
https://gist.github.com/diego0020/735b20e3ba73b1e9aad9
![image](https://cloud.githubusercontent.com/assets/7297450/3105629/ed73dc7c-e674-11e3-8024-b850784364ae.png)

But it doesn't quite work, and is also very hacky. 

If there were a "fig" argument in the FacetGrid constructor, which would make it reuse an existing figure then it would be easy to embed it. However that parameter should be passed along all the way from the high level function (example lmplot).

I could spend some time working on this, but please let me know if you think this is the right path, or if you can think of a better solution.

**Comment by Dimchord** [comment]
The plt.subplots() function accepts the 'num' keyword to select an existing figure. It should be straightforward to implement this in the call to FacetGrid. Can we reopen this issue?
