### ISSUE TITLE
Allow "sd" for `ci` in regression not only for `x_ci`

### ISSUE THREAD

**Issue by Barry1** [mwaskom/seaborn#2105]
For some of my plots - and I think also other one's plots- showing the bands around a regression with the `ci`-width is sometimes not the only good idea. As we can select `sd` for the `x_ci` I suggest to implement it also for the global ci leading to bands with that sd-width. (If this is wanted, I already have my local solution, which I can request for pull; this is only to connect to an issue)
I hope, that this is the right way to contribute - is it @mwaskom ?

As a kind of sub question - we maybe can discuss if the width should be "one sigma" to each side or two or three. This is somehow related to that [Wikipedia Statistical KnowHow](https://en.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule) page.

**Comment by mwaskom** [comment]
I agree this would be useful but I am against further muddling the API by overloading the `ci=` parameter in a new context. I have some plans sketched out for a more general way to parameterize of error bars that would allow things like this (including choosing the sigma level to show).

**Comment by Barry1** [comment]
Hi, that sounds good. Mabye I can help?
Another question? If ci=95 and x_ci=95 - those ranges should somehow
indicate (not exakt because of bootstrapping) the same behaviour, or?
Kind regards
Bastian

Am Do., 28. Mai 2020 um 17:03 Uhr schrieb Michael Waskom <
notifications@github.com>:

**Comment by mwaskom** [comment]
It's not a current priority but will probably become one within this release cycle. Keep your eyes open for an issue or pull request about it. I'm going to close this because I'm not going to act on the specific suggestion.

> Another question? If ci=95 and x_ci=95 - those ranges should somehow indicate (not exakt because of bootstrapping) the same behaviour, or?

They should be close, but you shouldn't expect them to be exactly identical.

**Comment by Barry1** [comment]
I understand the closing.
Bus one last question - I have a (sorry sensitive) huge dataset - 1'500'000
readings in two columns, one is a prediction of the other.
When applying the same ci-values, the uncertainty on the scatter elements
is remarkable, but the band is never to be seen.
Can you give me an hint?
In other words - I'd best like to produce a plot, following the uncertainty
markers of the scatters - as a graph - best would be without the scatter
elements but the middle line and the bands.
Thanks
-- 
Bastian Ebeling
Distelweg 13
25495 Kummerfeld
Telefon: 04101/75504
Handy: 0176/48101293
Fax:   03212/1086862


Am Do., 28. Mai 2020 um 17:15 Uhr schrieb Michael Waskom <
notifications@github.com>:

**Comment by Barry1** [comment]
Here is an example

[image: image.png]


You can see identical ci-values for both Settings, but only
scatter-uncertainty is to be seen.

>

**Comment by mwaskom** [comment]
I appreciate that you might not be able to share your dataset, but it's really quite difficult to give specific advice without a working example. I would encourage you to try and replicate the issue using randomly generated data — which is likely to give you more insight into the nature of what's happening.

**Comment by mwaskom** [comment]
Your picture doesn't show up in the issue thread, by the way. Attaching a picture to an email won't upload it to github.

**Comment by Barry1** [comment]
Hi,

hopefully this gives enough inside:
[image: image.png]


Best regards

Bastian

Am Do., 28. Mai 2020 um 17:27 Uhr schrieb Michael Waskom <
notifications@github.com>:
