### ISSUE TITLE
Parameter for the regression-grid

### ISSUE THREAD

**Issue by Barry1** [mwaskom/seaborn#2106]
If I understand the source correct, the grid for the regression is hard coded with the number of 100 for the points.  
I think adding a named parameter with default 100 might be an option, I'd like to contribute my possible solution for this and therefore created this issue to relate to that for my pull request. Is this wanted @mwaskom ?

**Comment by mwaskom** [comment]
Your understanding is probably correct. Do you have an example of an application where the default caused problems? There's always a cost to adding new parameters.

**Comment by Barry1** [comment]
Hi,
the grid is linspace. So the regression and "uncertainty" bands are lines
based on that grid. In some cases a higher resolution could help to
identify "local" uncertain behaviour. This was my intention for asking.
Best regards


Am Do., 28. Mai 2020 um 16:56 Uhr schrieb Michael Waskom <
notifications@github.com>:

**Comment by mwaskom** [comment]
Do you have an example of one of those cases?

**Comment by mwaskom** [comment]
Because the error bars correspond to bootstrap replicates of the regression line, it's not obvious to me how there could be "local" uncertainties.

**Comment by Barry1** [comment]
The moment, as on work, I do not have an example with me.
My understanding is, the mentioned grid is *only* for the evaluation points
of regression line and band.
This is different fo bootstrapped data for "local analysis" as in x_ci and
so on?

Am Do., 28. Mai 2020 um 17:05 Uhr schrieb Michael Waskom <
notifications@github.com>:

**Comment by Barry1** [comment]
Hi again, with grid I refer to the definition in line
https://github.com/mwaskom/seaborn/blob/master/seaborn/regression.py#L201
An alternative might be, to use the x_bins (linear spaced over the
measurements) by number or by given bins.

Am Do., 28. Mai 2020 um 17:05 Uhr schrieb Michael Waskom <
notifications@github.com>:

**Comment by mwaskom** [comment]
I understand what you mean by the grid. I'm asking for an example of where the ability to change its density would solve some specific problem that you have encountered.

**Comment by Barry1** [comment]
I tried to compile "fast by fast".

based on your tips-data:

'''
seaborn.regplot(x="total_bill",y="tip",data=data,x_bins=numpy.linspace(0,50,10),x_ci=60,ci=60)
'''

For example the uncertainty around 6 and 45 is somehow similar (on the
scatter-elements) - but the width of the band is different.
The band for me seems to be not that precise. Bus this is a rough comment.
For sure you know better.

Am Do., 28. Mai 2020 um 17:12 Uhr schrieb Michael Waskom <
notifications@github.com>:

**Comment by mwaskom** [comment]
The uncertainty around the regression line at x=45 depends on all of the observations in the dataset (and the regression model), whereas the uncertainty around the scatterplot point just depends on that subset of observations. So you shouldn't expect them to be identical. Increasing the resolution of the grid that the regression line is evaluated on won't change that.

You may be interested in [local regression](https://en.wikipedia.org/wiki/Local_regression) which is included in seaborn (`lowess=True`), albeit with a somewhat limited implementation. You can get an enhanced lowess by using statsmodels directly.

**Comment by Barry1** [comment]
Hi and thanks,
I'll give it a try.
Maybe the picture just send also is helpful.

Am Do., 28. Mai 2020 um 17:25 Uhr schrieb Michael Waskom <
notifications@github.com>:

**Comment by mwaskom** [comment]
I'm going to close because I'm not convinced there's a compelling need for this as a new parameter.
