### ISSUE TITLE
default style makes some markers/legend invisible

### ISSUE THREAD

**Issue by tiagoantao** [mwaskom/seaborn#211]
The default style makes some markers/legend invisible, consider the following code:

``` python
import seaborn
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot([1, 2, 3])
ax.plot([1.5, 1.5, 1.5], '.', label='dot')
ax.plot([2, 2, 2], '+', label='plus')
ax.plot([2.5, 2.5, 2.5], 'x', label='x')
ax.legend()
plt.show()
```

The result is this:

![seaborn](https://cloud.githubusercontent.com/assets/34787/3129780/36fecb10-e7ea-11e3-9298-8c4919f34d92.png)

Notice that there is no legend, neither the plus or x cases. The default looks like this:

![default](https://cloud.githubusercontent.com/assets/34787/3129784/54afb908-e7ea-11e3-9211-e75b6f66082f.png)

**Comment by mxmlnkn** [comment]
This weird behavior / bug still persists for me in seaborn 0.7.1. I was frustrated, because I didn't see any plot, but the range was in the expected data value range. Seem like '+' does not work, but 'o' works just fine.
