### ISSUE TITLE
Improve boxenplot examples

### ISSUE THREAD

**Issue by MaozGelbart** [mwaskom/seaborn#2114]
`boxenplot` is well suited to describe large datasets but examples show the `tips` dataset which is not so large. It may be more compelling to showcase `boxenplot` using a larger dataset, such as `diamonds`. See [https://github.com/mwaskom/seaborn/pull/2086#issuecomment-636903972](https://github.com/mwaskom/seaborn/pull/2086#issuecomment-636903972)

**Comment by mwaskom** [comment]
Closed with #2858
