### ISSUE TITLE
Y axis is reverted in the rightmost panel in catplot using orient="h"

### ISSUE THREAD

**Issue by ikuehirata** [mwaskom/seaborn#2115]
In vertically oriented catplot, y axis is always reverted in the rightmost panel.

seaborn 0.10.1
Python 3.7.3
Windows

I created a `DataFrame` as below:
```python
import pandas as pd
concatdf = pd.DataFrame([])
l = list(range(30))
df = pd.DataFrame(l, columns=["value 1"])
df["value 2"] = df["value 1"]
df["category"] = "a"
concatdf = concatdf.append(df)
df = pd.DataFrame(l, columns=["value 1"])
df["value 2"] = df["value 1"]*2
df["category"] = "b"
concatdf = concatdf.append(df)
df = pd.DataFrame(l, columns=["value 1"])
df["value 2"] = df["value 1"]*3
df["category"] = "c"
concatdf = concatdf.append(df)
```
this `concatdf` gives this:
```python
import seaborn as sns
g = sns.catplot(x="value 1", y="value 2", hue="category", data=concatdf)
```
![sandbox1](https://user-images.githubusercontent.com/16083688/83445376-2fd2c280-a44d-11ea-9677-24b67d05c726.png)

Plotting with `columns="category"` with `orient="v"` is fine.
```python
g = sns.catplot(x="value 1", y="value 2", hue="category", data=concatdf,
    row="category",
    sharex=True,
    sharey=False,
    orient="v",
    aspect=3, height=1.7)
```
![sandbox3](https://user-images.githubusercontent.com/16083688/83445425-424cfc00-a44d-11ea-8c60-26ae81cffd95.png)

When I switch `x` and `y`, `sharex` and `sharey`, `orient`, in the rightmost panel, y axis (value 1) is totally reverted:
```python
g = sns.catplot(x="value 2", y="value 1", hue="category", data=concatdf,
    col="category",
    sharex=False,
    sharey=True,
    orient="h",
    aspect=0.3)
```
![sandbox2](https://user-images.githubusercontent.com/16083688/83445399-38c39400-a44d-11ea-89ea-1c4e5d7d5ad2.png)

**Comment by mwaskom** [comment]
Duplicate of #1771?

**Comment by ikuehirata** [comment]
Exactly, thank you! I'll close this issue.
