### ISSUE TITLE
categorical sizes plot now has order reversed

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#2122]
From the relational tutorial, on 0.11.0.dev0:

```python
sns.relplot(x="time", y="firing_rate",
           hue="coherence", size="choice",
           palette=palette,
           kind="line", data=dots);
```

![image](https://user-images.githubusercontent.com/315810/83755000-e2b44380-a63a-11ea-9632-3fcedfaba8d0.png)

**Comment by MaozGelbart** [comment]
This is what I'd expect, given line widths increase with values for numeric mapping.

**Comment by mwaskom** [comment]
@MaozGelbart That does make some sense, but the behavior reflects a change introduced during the refactoring. I think https://github.com/mwaskom/seaborn/blob/v0.10/seaborn/relational.py#L422 is the relevant line that was not correctly propagated.

I think the original mindset was that categorical orders more often have a descending order of importance than an ascending one. But that's perhaps just an ad hoc intuition. (This also reminds me that boolean variables, when treated as categorical, should perhaps default to [True, False] to match that expectation.)

It's possible that it would be better to change the default as an example of removing special cases that decrease predictability. If so, the change should be clearly documented and the examples should be updated where necessary.
