### ISSUE TITLE
Add text in FacetGrid subplots

### ISSUE THREAD

**Issue by pratiman-91** [mwaskom/seaborn#2127]
While generating FacetGrid subplots a text can be added as a subplot number. This will help in the generation of scientific publication-quality plots. For example,

```
import seaborn as sns; sns.set(style="ticks", color_codes=True)
import matplotlib.pyplot as plt
tips = sns.load_dataset("tips")
g = sns.FacetGrid(tips, col="time",  row="smoker")
g = g.map(plt.hist, "total_bill")
```

will generate

![Figure 2020-06-08 104656](https://user-images.githubusercontent.com/31694629/83994906-6e004280-a975-11ea-9cda-73bd42837302.png)
 However, if we add a subplot number using

```
import seaborn as sns; sns.set(style="ticks", color_codes=True)
import matplotlib.pyplot as plt
tips = sns.load_dataset("tips")
g = sns.FacetGrid(tips, col="time",  row="smoker")
g = g.map(plt.hist, "total_bill")

#adding sub plot number
string = ['a','b','c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l']
for i, ax in enumerate(g.axes.flatten()):
    ax.text(0.80, 0.85,'(' + string[i] +')',transform=ax.transAxes, 
            bbox=dict(boxstyle="square", fc="w", ec="k"))
```

we get 
![Figure 2020-06-08 104847](https://user-images.githubusercontent.com/31694629/83994978-a9027600-a975-11ea-9311-3db1112d2539.png)

which can directly be used in the publication and will be a great help.

Let me know what do you think about this.
Thanks

**Comment by mwaskom** [comment]
Hi, thanks for the suggestion. For publication-quality plots, you're probably going to want to have the precise control that `ax.text` or `fig.text` give you, and I'm not sure there's much to be gained by a higher-level (but less flexible) method built into `FacetGrid`.
