### ISSUE TITLE
Percentage tick labels

### ISSUE THREAD

**Issue by aliakbars** [mwaskom/seaborn#2128]
I would like to add a new feature to make it easier to change tick labels from decimal points to percentages. Something like the following figures:

<img width="833" alt="fish" src="https://user-images.githubusercontent.com/7055994/83998525-fd642080-a98a-11ea-9490-ee51b9009a6a.png">

<img width="833" alt="fish-percentage" src="https://user-images.githubusercontent.com/7055994/83998528-01903e00-a98b-11ea-96fc-e7cb3e5a71f2.png">

It can be done through matplotlib in just a few lines of code, but I think it would be useful if we can wrap it into a one-liner. I am willing to implement this if you think that this would be useful.

**Comment by mwaskom** [comment]
Can you share what you expect the "one liner" to look like? You can accomplish this at the matplotlib layer with 

```python
ax.xaxis.set_major_formatter(ticker.PercentFormatter())
```

which is also one line.

**Comment by aliakbars** [comment]
Oh, okay. I did not know that. Thanks. What I've found so far is a two-line solution. Something like

```python
vals = ax.get_yticks()
ax.set_yticklabels(['{:.0%}'.format(val) for val in vals]);
```

However, `ticker.PercentFormatter()` here means one more import, isn't it? Because usually we import `matplotlib` as

```python
import matplotlib.pyplot as plt
```

right? Whereas using `ticker` means you should import it with

```python
import matplotlib as mpl
````

Correct me if I'm wrong.

I was thinking about something similar to `plt.semilogx()` or `sns.despine()`.

**Comment by mwaskom** [comment]
Yes, you need to have the core matplotlib namespace imported.

I think I'm going to pass on this; there's not a compelling case for a new seaborn function when there is an existing matplotlib solution that works well.
