### ISSUE TITLE
labels missing on heatmap

### ISSUE THREAD

**Issue by rcolpo** [mwaskom/seaborn#2131]
When my heatmap has too many elements, some labels start to be missing, probably because all of them can not fit without overlapping. Is it possible to automatically increase the figure size, or decrease the label font size, to make sure all labels are shown and there is no label overlap? 
Also, the color label is over the heatmap. Is it possible to prevent this from happening?

This is the code I'm using:
```
df = pd.DataFrame(heatMapDict).T
cmap = sns.cm.rocket_r
ax = sns.clustermap(df, fmt="d", cmap = cmap)
ax.ax_heatmap.set_yticklabels(ax.ax_heatmap.get_yticklabels(), rotation=0)
```

![heatMap](https://user-images.githubusercontent.com/5889181/84551732-bbcad100-ad0e-11ea-95b6-ae7edbc6e53a.png)

**Comment by mwaskom** [comment]
> When my heatmap has too many elements, some labels start to be missing, probably because all of them can not fit without overlapping.

Yes, that is the default behavior.

> Is it possible to automatically increase the figure size

No, sorry

> or decrease the label font size, to make sure all labels are shown and there is no label overlap?

No, sorry.

You can set the figure size or label font size of course, but it won't change automatically.

**Comment by rcolpo** [comment]
Thank you. 
Is it possible to know the number of labels that will be plotted on the heatmap without manually counting the labels after having the graph plotted?

**Comment by mwaskom** [comment]
I don't think so (it depends on a number of factors, not all of which can be known ahead of time) but you can pass an integer to `xticklabels` which means "plot every `n` label".
