### ISSUE TITLE
Relational plots tests don't compare colors properly

### ISSUE THREAD

**Issue by MaozGelbart** [mwaskom/seaborn#2145]
Attached the relevant part from `colors_equal`:
https://github.com/mwaskom/seaborn/blob/dd40fd6885f9d164d6925f5b4571d69f1c134b4b/seaborn/tests/test_relational.py#L25-L28
The two inner lines are always equal.

**Comment by mwaskom** [comment]
Thanks, good catch. BTW did you know there is as of some recent version a `to_rgb` function in the `mpl.colors` namespace? I learned this recently.

**Comment by MaozGelbart** [comment]
Yes, the `colorConverter` instance is kept for backcompat only. It would probably be a good idea to use the newer (and shorter) version throughout seaborn (perhaps using `to_rgba`?).

**Comment by mwaskom** [comment]
I'm not sure I'd advocate a batch change, as the risk of subtle bugs probably outweighs the benefits of changing existing code, but (much like modernizing nose-based tests) the shorter version should be used going forward, and it's good practice to clean up the tests around where you're working if you are doing things.
