### ISSUE TITLE
distplot with large numbers leads to wrong axis limits

### ISSUE THREAD

**Issue by LeFrit** [mwaskom/seaborn#2150]
```
#%%
import seaborn as sns
import numpy as np

mio = 1000000

#%% Smaller Distribution
sns.distplot(
    np.random.randint(
        30*mio,
        100*mio,
        10000
    )
)

#%% Larger Distribution
sns.distplot(
    np.random.randint(
        300*mio,
        1000*mio,
        10000
    )
)
```

When run separately, the Larger Distribution plot yields the following outcome:

![image](https://user-images.githubusercontent.com/34543332/85847708-33d1d600-b7a8-11ea-9015-33ca2b060005.png)

When both distributions are plotted to the same figure, one can clearly see, that the axis limits are set wrong:

![image](https://user-images.githubusercontent.com/34543332/85847868-7c898f00-b7a8-11ea-9648-ace95c1eaa21.png)

The error was reproducible with the VS Code Python Plugin and run as a regular script in PyCharm.

EDIT: The threshold seems to be at 100 mio.

**Comment by mwaskom** [comment]
Sorry but can you explain what you think is "wrong" here? I can't clearly see it.

**Comment by LeFrit** [comment]
The y-axis limit is wrongly set to 1e-12 and the KDE is missing when only the "Large Distribution" is plotted, as can be seen in the first figure. 

As I see now, my figures are a bit confusing: The "Large Distribution" is orange in the second plot, as it was plotted after the "Smaller Distribution".

**Comment by mwaskom** [comment]
OK. I've reproduced the error in a matplotlib-only example:

```python
import numpy as np
import matplotlib as mpl

mio = 1000000

large = np.random.randint(
        300 * mio,
        1000 * mio,
        10000
    )
plt.hist(large, density=True)
```

I'm not sure what's causing it, but I think it's outside of seaborn's control.

**Comment by mwaskom** [comment]
Here's a simpler example that shows something going wacky with matplotlib's axis autoscaling between `1e-7` and `1e-8`:

```python
ax = plt.figure().subplots()
ax.bar([0], 1e-7, 1)

ax = plt.figure().subplots()
ax.bar([0], 1e-8, 1)
```

**Comment by MaozGelbart** [comment]
> Here's a simpler example that shows something going wacky with matplotlib's axis autoscaling between `1e-7` and `1e-8`


I can reproduce this example on matplotlib==3.2.2, but not on matplotlib==3.3.0rc1.

**Comment by mwaskom** [comment]
Great thanks for checking. Matplotlib has been working out some kinds in autoscalling on collections with small numbers, so I expect that's what this was.

Going to close as both upstream and fixed.
