### ISSUE TITLE
Suggestion: half violinplot half histogram

### ISSUE THREAD

**Issue by mdastro** [mwaskom/seaborn#2152]
Dear seaborners, 

I just stumbled upon a very useful visualization of the violin plot, in which one half is a histogram and the other half is a traditional violinplot. I'm opening this issue just as a suggestion of implementation. 

This is the example I saw:
![Captura de tela de 2020-07-01 13-46-01](https://user-images.githubusercontent.com/10452764/86271495-577b8e80-bba3-11ea-8e8d-8947f803f9ae.png)

Thanks!

**Comment by mwaskom** [comment]
Thanks for the suggestion. I think this is largely handled by the existing functionality for drawing a histogram with a kde curve. It won't give you exactly this plot, but I think a bit too much is going on in that figure anyway.

**Comment by mdastro** [comment]
Well, yes, there are in fact many ways of seeing the same thing. I just particularly liked this way because its not so redundant (as a traditional vionlinplot), you please those people that like histograms, and you also keep it compact. Its very useful if you have a lot of distributions to be seen.

**Comment by mwaskom** [comment]
I think one can get close enough to this now that it's not worth adding a whole different plotting function for it. e.g.:

```python
sns.displot(penguins, y="flipper_length_mm", col="species", aspect=.4, kde=True)
```
![image](https://user-images.githubusercontent.com/315810/90570152-25d37c80-e17d-11ea-81a1-7c39012af555.png)
