### ISSUE TITLE
[FR] include all available dataset names in load_dataset exception

### ISSUE THREAD

**Issue by StevenLi-DS** [mwaskom/seaborn#2154]
Sometimes I can't remember the correct spelling of certain sample dataset name. A typo in `load_dataset` will return an `HTTPError: HTTP Error 404: Not Found`. It would be much more convenient to have a full list of sample dataset names so that users can simply copy and paste them into their code.

Please also consider add this list into the doc: 
https://seaborn.pydata.org/generated/seaborn.load_dataset.html#seaborn.load_dataset

**Comment by mwaskom** [comment]
I would recommend using https://seaborn.pydata.org/generated/seaborn.get_dataset_names.html for this.

**Comment by StevenLi-DS** [comment]
This would be really inconvenient since you have to remember another func name. Many matplotlib functions actually include this kind of info in their error msg. I wish you could reconsider.

**Comment by mwaskom** [comment]
The docstring for `load_dataset` says "Use :func:`get_dataset_names` to see a list of available datasets." So you don't really need to remember the other function, as much as look at the help for the function you're trying to use.

**Comment by StevenLi-DS** [comment]
Oh.. I see. This issue has been bothering me for years and every time I have to google and then go to that github repo to just find a file name... lol. still wish you can add them to the error msg like matplotlib. anyway.

Btw, as a long-term seaborn user, I've seen the data structure prob very often bites other users on SO. Is there any plan to unify the data structure of seaborn (like only `Axes` or `Figure`). Why not just using matplotlib `Figure` for those matrix plot function? It always seems weird to me.

**Comment by mwaskom** [comment]
Thanks for the feedback.
