### ISSUE TITLE
Scatterplot subplot facecolor

### ISSUE THREAD

**Issue by vpapaioannou** [mwaskom/seaborn#2156]
I want to plot a series of subplots using the following code,

`grouped = data.groupby( by = [ 'distance'])`
`rows, cols = len( grouped), 1`
`fig, axs = plt.subplots( rows, cols, figsize = ( 15, 150), subplot_kw = { 'facecolor' : ( 0.8, 0.8, 0.8)})`
``
`for i, ( name, g) in enumerate( grouped):`
`    ax = plt.subplot( rows, cols, i + 1)`
`    cmap = sns.diverging_palette( 145, 280, s=85, l=5, n=len( np.unique( g[ 'p_value'])))`
`    sns.scatterplot( data = g, x = 'x', y = 'y', hue = 'p_value', size = 'p_value'`
                    , sizes = ( 100, 20), palette = cmap, legend = 'brief', ax = ax)`

and for now I am getting a result like this,

![image](https://user-images.githubusercontent.com/6065702/86521379-075c3080-be1e-11ea-9622-400a438ee23e.png)

The first plot shows a plain subplot without any data plot by Seaborn. It can be seen that its face color is gray as expected and desired to be. The second plot, show data plotted by Seaborn and where the `ax` argument is set. Its face color is white and this is problematic in my case. It is so because, I am having kind of heat map and lightly colored mark vanish inside the white face color.

Hence I want to have a gray face color / background for these data to be seen.

I tried all kinds of candidate solutions e.g. `ax.set_facecolor((1.0, 0.47, 0.42))` and plt.rcParams['axes.facecolor'] = 'black'` but they don't work. Still Seaborn enforces the white face color.

When I add a patch, i.e. 
`path_mbb = mplpth.Path( np.vstack( [ mbb, [ mbb[ 0]]]))`
`patch_mbb = patches.PathPatch( path_mbb, facecolor = ( 0.8, 0.8, 0.8)`
`                                   , edgecolor = 'none', alpha = 0.5, lw = 4, ls = '-.')`

it solves the problem  but I don't like it that much a solution and also I need every time to know the exact limits of x/y axes that I would like to avoid and to have automatically set every time.

Please advise.

Thanks,

Vasilis

**Comment by mwaskom** [comment]
I'm afraid I don't understand this issue. `scatterplot` doesn't do anything to modify the facecolor of the axes it's plotted onto. Your code isn't runnable, but here is an example of this working fine:

```
tips = sns.load_dataset("tips")
f, ax = plt.subplots(subplot_kw=dict(facecolor=".9"))
sns.scatterplot(data=tips, x="total_bill", y="tip")
```
![image](https://user-images.githubusercontent.com/315810/86521551-64f17c80-be20-11ea-9a19-1739393e59d3.png)

If you need more help with your specific usecase, I would suggest making a reproducible example and asking on StackOverflow.

**Comment by vpapaioannou** [comment]
Running your code, like this,

`tips = sns.load_dataset("tips")`
`rows, cols = 2, 1`
`f, ax = plt.subplots( rows, cols, figsize = ( 10, 10), subplot_kw=dict(facecolor=".9"))`
`plt.subplot( rows, cols, 1)`
`sns.scatterplot(data=tips, x="total_bill", y="tip")`

I am getting this,

![image](https://user-images.githubusercontent.com/6065702/86541280-9712e500-bed9-11ea-83cc-6255a9bbe1f6.png)

The face color of the first subplot is white and not as specified.

**Comment by vpapaioannou** [comment]
Here is my StackOverflow post, https://stackoverflow.com/questions/62746230/matplotlib-subplot-face-color-with-no-frame.
