### ISSUE TITLE
Unfilled markers new behavior results in empty plots

### ISSUE THREAD

**Issue by MaozGelbart** [mwaskom/seaborn#2159]
Matplotlib 3.3.0rc1 [changed the behavior](https://github.com/matplotlib/matplotlib/pull/17543) of unfilled markers to expose their color via `get_edgecolors()` and properly use linewidth property.  This has a few implications, the most severe is the creation of empty plots:

- For `scatterplot`, if no color is provided, the color is obtained using `PathCollection.get_facecolors()`. With matplotlib 3.3 `get_facecolors()` returns an empty color for unfilled markers, thus relying on this for figuring out the plotted color is problematic. Example code:
  ```
  import seaborn as sns
  tips = sns.load_dataset("tips")
  ax = sns.scatterplot(x="total_bill", y="tip", marker="+", data=tips)
  ```
- This is an issue for `stripplot` and `swarmplot` as well, as they set `linewidth=0` and for unfilled markers this is the element carrying the color, which will result with empty plots if an unfilled marker is provided. Example code:
  ```
  import seaborn as sns
  tips = sns.load_dataset("tips")
  ax = sns.stripplot(x="total_bill", marker="+", data=tips)
  ```
- Notably, the empty marker (`marker=""`) is also unfilled marker so querying for `get_facecolors()[0]` fails some tests that rely on this. Example line (here it fails due to the title-like empty handle artist in the relational legends being an empty unfilled marker):
  [https://github.com/mwaskom/seaborn/blob/79051edcd81af4ce3c3abd06f01eb28478a9a53a/seaborn/tests/test_relational.py#L1350](https://github.com/mwaskom/seaborn/blob/79051edcd81af4ce3c3abd06f01eb28478a9a53a/seaborn/tests/test_relational.py#L1350)

**Comment by mwaskom** [comment]
That's irritating, but I think it actually might fix the problem that limits mixing of filled and unfilled markers?

**Comment by mwaskom** [comment]
If I understand the linked PR correctly, breaking seaborn is an unintended consequence of fixing `fillstyle="none"`?

**Comment by MaozGelbart** [comment]
Actually the linewidth issue may stem from a [different PR](https://github.com/matplotlib/matplotlib/pull/17492), which seems to fix a prior faulty behavior of `ax.scatter`. 


> That's irritating, but I think it actually might fix the problem that limits mixing of filled and unfilled markers?

Yes, maybe!



> If I understand the linked PR correctly, breaking seaborn is an unintended consequence of fixing `fillstyle="none"`?

Unfortunately, seems so.

**Comment by mwaskom** [comment]
> This is an issue for stripplot and swarmplot as well, as they set linewidth=0 and for unfilled markers this is the element carrying the color, which will result with empty plots if an unfilled marker is provided.

I don't think the 3.3.0 changes this actually, it's an issue on released versions (the workaround is just to increase the linewidth — it's not a bug really so much as a gotcha from the default linewidth being 0).

**Comment by tacaswell** [comment]
> That's irritating, but I think it actually might fix the problem that limits mixing of filled and unfilled markers?

I think we need to think a bit more carefully about what "facecolor" means in the case of an unfilled marker.  The internally consistent version is "nothing".  I think the "natural" meaning in "edgecolor", but making that change should be done carefully.  On the otherhand, in the case of filled markers you have 2 colors to play with, in the case of un-filled you only have 1 so at some level there is always going to some impedance miss-match.  Can you open an issue explaining exactly what the source of friction is?

Sorry for the slightly rambling comment.

**Comment by mwaskom** [comment]
I will have to remind myself of the exact details, there is a comment here with some explanation https://github.com/mwaskom/seaborn/blob/master/seaborn/_core.py#L525

The context is that seaborn draws a single scatterplot with multiple markers by drawing one scatterplot and then modifying the paths in the resulting collection.

Thinking about it a little bit, I’m somewhat skeptical this change will enable it. (There’s also a tricky business with the linewidths).

**Comment by tacaswell** [comment]
You may want to sub-class `PathCollection` to over-ride `set_linewidth`, `set_facecolor` and `set_edgecolor` to have the semantics you want based on what you know about the paths.

I could see that moving upstream to Matplotlib, but it may be worth proto-typing it in seaborn.

**Comment by mwaskom** [comment]
Not a bad idea — seaborn actually has managed to avoid any kind of artist subclassing up to this point and does everything through the `Axes` method interface plus some post-hoc artist manipulation.

**Comment by tacaswell** [comment]
The Axes methods are for the most part factory functions then parse the user input, generate some `Artists` instance, and then add them instances to them selves (along with a bit of state like property cycling, aspect ratio, ...).  If "easy path" on those methods don't match the easy path that you need you may be better off directly creating the `Artists` (even without sub-classing) or creating thin sub-classes of the `Artists` (you can do some wild things that way, see https://github.com/networkx/grave) that are more tuned to the actually data you have rather than fitting your data through our API and the patching it up on the way back out.

Sorting out how to scale that sort of thing up is what @story645 is working on through our CZI grant.

**Comment by mwaskom** [comment]
Yeah — it's a self-imposed constraint that may or may not be a good idea. (And a relic of how the original seaborn functions were relatively thin wrappers around existing axes methods).

Seaborn does try to hook into the property cycle (in cases where it's not managing the properties through semantic mapping) although this requires using the axes methods, and it has proven to be an increasing headache that is not obviously worth it. I have been increasingly thinking that having seaborn use artists directly is probably a cleaner architecture, although the transition poses some challenges (e.g. most seaborn functions pass kwargs down to the matplotlib callable and while *most* of the kwargs you would be passing get down to the artist anyway, there may be cases where that is not true).

**Comment by mwaskom** [comment]
Fixed upstream https://github.com/matplotlib/matplotlib/pull/17850
