### ISSUE TITLE
FacetGrid: margin_titles=True clasesh with non-default row_template set up in set_titles

### ISSUE THREAD

**Issue by jpotoniec** [mwaskom/seaborn#2161]
Dear all,
consider the following code:
```
import seaborn as sns
tips = sns.load_dataset("tips")
plot = sns.relplot(x="total_bill", y="tip", row="day", data=tips, facet_kws={'margin_titles': True})
plot.set_titles(None, "{row_name}")
```
What I would expect here is four charts, each denoted with the day of the week on the right-hand side. Instead, I get the picture presented below, where there are clearly two labels on top of each other on the right-hand sides of the charts: one label as requrested, only the day of the week, the other following the default template `{row_var} = {row_name}` and thus containing the name of the variable as well as its value.

I believe the bug arises from calling `set_titles()` without any arguments in `FacetGrid._finalize_grid`. It does work correctly when `margin_titles=False`, because it relies on `Ax.set_title`, which seems to not render the text immediately. For the same reason, it works correctly for columns when `margin_titles=True`. However, the code responsible for annotating rows relies on `Ax.annotate` instead, which seems to perform rendering immediately.

As a temporary workaround it is possible to remove the call to `set_titles()` in `FacetGrid._finalize_grid` in [seaborn/axisgrid.py, currently line 893](../blob/master/seaborn/axisgrid.py#L893), but I assume this call is there on purpose and permanently removing it would break other cases.

![wrong](https://user-images.githubusercontent.com/11078342/87019498-fbcc8900-c1d2-11ea-8bf4-ef67f4c871a6.png)

**Comment by mwaskom** [comment]
I think #2083 fixes this. It looks fine for me on master.

`margin_titles` is basically a hack as matplotlib doesn't offer this functionality through their actual title API. But it works a little bit better now.

**Comment by jpotoniec** [comment]
Ah, I admit I didn't check against the current master. My bad, it indeed works correctly in the development version.

**Comment by mwaskom** [comment]
No worries, it was a long-standing issue....

Be aware that the master branch is undergoing heavy development right now.
