### ISSUE TITLE
perhaps not consistent with new version of numpy

### ISSUE THREAD

**Issue by Teng-Martin-Ma** [mwaskom/seaborn#2162]
My situation is when using lineplot() with numpy and pandas.The warning said
```
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
```
is this warning harmless?

**Comment by mwaskom** [comment]
I would need a complete reproducible example to be able to say, thank you.

**Comment by mwaskom** [comment]
Closing for lack of information, and low probability that this is a seaborn issue per se
