### ISSUE TITLE
Error in PairGrid if despine is False

### ISSUE THREAD

**Issue by gVallverdu** [mwaskom/seaborn#2166]
Hi

I think there is a mistake around line 1403 in `axisgrid.py`  https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L1403

Actually, if `despine` is `False`, `self._despine` is never positionned. This will cause a bug if corner is True line 1506 because you check the `self._despine` attribute.
https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L1506

This works well:

```py
df = pd.DataFrame({k: np.random.random(100) for k in "abc"})
sns.pairplot(data=df, corner=True)
```
And these few lines reproduce the bug:

```py
df = pd.DataFrame({k: np.random.random(100) for k in "abc"})
sns.pairplot(data=df, corner=True, grid_kws=dict(despine=True)
```

I did not have any issue but the situation is the same for the `FacetGrid` class and thus the same bug may appear.

my python version is 3.7.3 and seaborn version is `0.10.1`

**Comment by mwaskom** [comment]
I'm having trouble reproducing. What error do you see?

**Comment by gVallverdu** [comment]
Sorry, I did a mistake.

These lines reproduce the bug, note the `False` in the `grid_kws` parameter of pairplot.

```py
df = pd.DataFrame({k: np.random.random(100) for k in "abc"})
sns.pairplot(data=df, corner=True, grid_kws=dict(despine=False)
```

Here is a notebook with the error: 
https://github.com/gVallverdu/cookbook/blob/master/pairgrid_bug.ipynb

Actually the error comes if you try to plot closed axes with the corner option.
