### ISSUE TITLE
[doc] plt.show() not obvious. Please add to examples

### ISSUE THREAD

**Issue by manuel-91** [mwaskom/seaborn#2174]
Hello, 

I just wanted to try seaborn but failed till I stopped reading the documentation and googled...

Please add this hint somewhere in the docs so that plotting works!

https://stackoverflow.com/questions/26597116/seaborn-plots-not-showing-up

I tried sns.show() but it did not work.

`plt.show()` is needed. Can you please add that in the examples?

**Comment by mwaskom** [comment]
`plt.show()` is only needed in specific contexts: not in notebooks, not in scripts, and not in GUIs.  So I don't think it's necessary to have in the examples.

**Comment by mwaskom** [comment]
In the [Introduction](https://seaborn.pydata.org/introduction.html) to the docs, there is text that says:

> Behind the scenes, seaborn uses matplotlib to draw plots. Many tasks can be accomplished with only seaborn functions, but further customization might require using matplotlib directly. This is explained in more detail below. For interactive work, it’s recommended to use a Jupyter/IPython interface in matplotlib mode, or else you’ll have to call matplotlib.pyplot.show() when you want to see the plot.

**Comment by manuel-91** [comment]
Okay, understood. Thank you for the detailed explanation!
