### ISSUE TITLE
cbar kwarg not working for clustermap 

### ISSUE THREAD

**Issue by jdenavascues** [mwaskom/seaborn#2177]
Hi,

I have been trying to suppress the plotting of a colourbar when using `sns.clustermap` setting `cbar=False`.
The documentation says this function admits the kwargs passed on to `heatmap` but this throws a `TypeError: heatmap() got multiple values for keyword argument 'cbar'`.

As example code, this example works:
[https://seaborn.pydata.org/examples/structured_heatmap.html](https://seaborn.pydata.org/examples/structured_heatmap.html)

```python
import pandas as pd
import seaborn as sns
sns.set()

# Load the brain networks example dataset
df = sns.load_dataset("brain_networks", header=[0, 1, 2], index_col=0)

# Select a subset of the networks
used_networks = [1, 5, 6, 7, 8, 12, 13, 17]
used_columns = (df.columns.get_level_values("network")
                          .astype(int)
                          .isin(used_networks))
df = df.loc[:, used_columns]

# Create a categorical palette to identify the networks
network_pal = sns.husl_palette(8, s=.45)
network_lut = dict(zip(map(str, used_networks), network_pal))

# Convert the palette to vectors that will be drawn on the side of the matrix
networks = df.columns.get_level_values("network")
network_colors = pd.Series(networks, index=df.columns).map(network_lut)

# Draw the full plot
sns.clustermap(df.corr(), center=0, cmap="vlag",
               row_colors=network_colors, col_colors=network_colors,
#                linewidths=.75, figsize=(13, 13))
               linewidths=.75, figsize=(13, 13), cbar=False) #    <------ just adding this causes the error
```
It seems like a very minor problem or perhaps I misunderstood the documentation. I am not a good programmer by any measure so I hope this is not a total waste of time.
Regards,
Joaquin

**Comment by mwaskom** [comment]
`clustermap` just has a slightly different (and non-obvious) API; you can turn the colorbar off in `clustermap` with `cbar_pos=None`.

**Comment by jdenavascues** [comment]
OK thanks!
I assume that then the axis for the cbar will not exist?
