### ISSUE TITLE
PairGrid ax or index error

### ISSUE THREAD

**Issue by alexshen7** [mwaskom/seaborn#2178]
Hi there,

New to Seaborn and Python in general but not too new. My dataframe appears to be fine. When printed it looks like this:

        A  B    C   D  E   F    G   H
0     -2.8%   -1.0%    2.4%   5.6%  -0.1%     6.2%     6.0%        0.2%
1     -0.3%    0.2%    2.7%   5.7%  -0.5%     6.5%     5.9%        0.5%
2     -1.4%   -1.7%    2.7%   5.7%  -0.5%     6.3%     6.2%        0.1%
3     -3.4%   -3.3%    2.7%   5.6%  -0.9%     6.2%     6.0%        0.2%
4     -0.2%   -0.4%    2.2%   5.5%  -1.1%     6.0%     6.1%       -0.1%
..      ...     ...     ...    ...    ...      ...      ...         ...
295   -6.3%   -4.9%    0.3%   3.6%   6.3%     1.5%     1.6%       -0.1%
296  -13.4%  -16.5%    0.3%   3.5%   6.7%     1.1%     0.1%        1.1%
297   -2.1%    1.8%    0.3%   4.4%  14.4%     0.7%     0.1%        0.7%
298   -5.6%   -2.0%   -5.4%  14.7%  27.5%     0.6%     0.1%        0.6%
299   -0.6%    0.1%   -4.7%  13.3%  33.5%     0.7%     0.1%        0.6%

The command line:  g= sns.PairGrid(df) returned these errors:

  File "C:\python\lib\site-packages\seaborn\axisgrid.py", line 1281, in __init__
    self._add_axis_labels()
  File "C:\python\lib\site-packages\seaborn\axisgrid.py", line 1518, in _add_axis_labels
    for ax, label in zip(self.axes[-1, :], self.x_vars):
IndexError: index -1 is out of bounds for axis 0 with size 0

Any advice on how to get rid of the errors and have the grid plot show is highly appreciated.

Thanks,
A.Shen

**Comment by mwaskom** [comment]
The error is not especially helpful, but `PairGrid` removes non-numeric columns by default. It looks like all of your columns are non-numeric, because they show up with a percent sign, indicating that they are encoded as strings in your dataframe. Matplotlib will draw scatterplot with strings but it won't do it they way you expect, so you'll want to convert those to a numeric representation before you use seaborn.

**Comment by alexshen7** [comment]
ahh! Appears to have fixed the prob. Thanks a lot!

I was getting there but not quite yet. Did see someone somewhere online mentioned non-numeric so checked my data to make sure no NAs. Then I started to think maybe it's the headers. Turned it's the % sign.
