### ISSUE TITLE
How to generate sphinx documentation on file basis locally?

### ISSUE THREAD

**Issue by SteveRedka** [mwaskom/seaborn#2180]
I'm trying to add examples to documentation of distribution functions, but I don't want to submit them without checking them first locally.

Currently I generate docs like this:
```bash
cd doc
make htmlhelp
```
However, it doesn't change pictures on pages with changed documentation - it pulls them from a cached place somewhere. Deleting all files that aren't tracked by git works, but generating new ones from scratch takes up to 20 minutes.

**Comment by mwaskom** [comment]
I'm not sure what the precise question is here, but (to my knowledge) you can't use sphinx just to generate a single target file. Sphinx does cache on a file basis, though, so if you remove all target files, it will need to regenerate them all; if you remove one target file, it will just remake that one.

FWIW I would not be generally receptive to PRs that add more examples to the docs just for the sake of having more plots.
