### ISSUE TITLE
Crash with ProcessPoolExecutor

### ISSUE THREAD

**Issue by steel3d** [mwaskom/seaborn#2181]
I can't import seaborn in my script if I want to use ProcessPoolExecutor.map(), or it will crash. If I comment out the import, it finishes successfully. Also works if I import but don't call the map(). Here's my minimal repro:

```
import concurrent.futures
import seaborn as sns

def process(num):
    result = 0;
    for i in range(num):
        result += i**2

if __name__ == '__main__':
    with concurrent.futures.ProcessPoolExecutor() as executor:
        executor.map(process, [500]*100)
    print("Done")
```

**Comment by mwaskom** [comment]
I can't replicate on my system. With your script, I get:

```
[mlw-mbpro Desktop]$ python futures_bug.py
Done
```

What error do you see? What if you test with only matplotlib (and not seaborn) imported? Seaborn is pure Python and doesn't do anything especially complicated so nothing comes to mind about as to what might be happening here.

**Comment by steel3d** [comment]
Sorry, I should have mentioned I'm on windows10 with 16-core 32-thread AMD Threadripper 64GB RAM.
Looks like it's running out of memory trying to import seaborn in all processes.

[seaborn_crash.txt](https://github.com/mwaskom/seaborn/files/5019133/seaborn_crash.txt)

**Comment by mwaskom** [comment]
It's not obvious to me that there's anything seaborn can do here? I think you'll just need better balance the number of processes with the capacity of your machine?

**Comment by mwaskom** [comment]
(With that said, I tested this on a laptop with 16 gb of RAM so that might not be the real problem).

**Comment by steel3d** [comment]
The reason I think it's an issue is that seaborn is the only import that crashes. Doing these other imports instead is no problem:

import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from mayavi import mlab
import concurrent.futures
import itertools
import time

The main difference I see is that each of the 32 python processes uses 1.7GB when importing seaborn alone, instead of 0.8GB with the other imports. This is according to Process Hacker 2. So if there was an opportunity to save RAM on import, it should improve the situation. I can work around this as well now that I know what the problem is.

Strangely, at one point after some modifications I got the script to run, even when reverting to its original form. Then after a few modifications it stopped working again. Probably due to slight differences in windows memory pressure at the time. Other note is that I have the swap file disabled for performance reasons, so when I run out of memory, I run out hard. 1.7GB*32 threads + 10GB baseline in use is 64.4GB. So it seems I'm right on the edge. I think that explains it. 

I think the conclusion is that reducing memory usage on import would be beneficial. 1.7GB seems excessive. What do you think? The working set seems tiny compared to the amount of memory committed.  <100MB.

**Comment by mwaskom** [comment]
Seaborn is, like, 8 python files. I find it implausible that importing it is loading 1GB+ into memory.

**Comment by mwaskom** [comment]
I don't see anything close to that:

```
[mlw-mbpro Desktop]$ cat test.py
from memory_profiler import profile

@profile
def test():
    import seaborn

if __name__ == "__main__":
    test()

[mlw-mbpro Desktop]$ python -m memory_profiler test.py
Filename: test.py

Line #    Mem usage    Increment   Line Contents
================================================
     3     39.0 MiB     39.0 MiB   @profile
     4                             def test():
     5    114.3 MiB     75.3 MiB       import seaborn

```

**Comment by mwaskom** [comment]
When I run your original script and watch memory usage in htop or Activity Monitor, I see a blip of about .05G in memory usage, but it's barely noticeable.

**Comment by steel3d** [comment]
```
from memory_profiler import profile

def process(num):
    result = 0;
    for i in range(num):
        result += i**2

@profile
def main():
    import seaborn as sns
    process(5000000) # do some work so you have time to check memory usage in Process Hacker
    print("Done")

if __name__ == '__main__':
    main()
```

```
Line #    Mem usage    Increment   Line Contents
================================================
     8     33.0 MiB     33.0 MiB   @profile
     9                             def main():
    10    113.1 MiB     80.1 MiB       import seaborn as sns
    11    113.1 MiB      0.0 MiB       process(5000000)
    12    113.1 MiB      0.0 MiB       print("Done")
```

I think importing seaborn in python actually sucks up 1.5GB. With no multiprocessing in the code, if I simply import seaborn, Process Hacker will report 1.5GB private bytes. If I comment out the import, it will report 33MB. @profile only reports 113MB memory usage when the commit size is 1.5GB.

Are you able to test on Windows? Please use Process Hacker 2 or something similar to check memory, or you can enable the Commit Size column in the Details pane of Win10 Task Manager. Or maybe there's some metric you can use for commit size on unix, and maybe it will show up there, too.

**Comment by steel3d** [comment]
Sorry, should have read your message more thoroughly, because the main idea was there. By importing modules independently, I realized that scipy is the big culprit. If I import either scipy module, commit size goes from 800MB to 1.5GB.

```
from memory_profiler import profile

def process(num):
    result = 0;
    for i in range(num):
        result += i**2

@profile
def main():
    import numpy
    import pandas
    import matplotlib
    from scipy import stats
    # from scipy import integrate
    # import seaborn
    process(5000000)
    print("Done")

if __name__ == '__main__':
    main()

```

Sorry for accusing you :) I'll go bark up the scipy tree now. Or rather I'll see if I can find which dependency of it is the worst.

**Comment by steel3d** [comment]
Actually, I'm a python novice and I can't figure out the hierarchical dependencies of scipy. If you know of a simple way to find out, I'd appreciate the info. Thanks! I'd like to avoid blaming the wrong project again :)

**Comment by mwaskom** [comment]
I still can't reproduce anything close to what you're seeing on my system (see updated comment above with each seaborn dependency imported to show its unique contributions). I only have access to Mac and Linux, so maybe something strange is happening on Windows with linking to the compiled libraries that scipy loads? It's worth asking them, I guess.
