### ISSUE TITLE
_univariate_kdeplot check for singular data should compare variance to data magnitude

### ISSUE THREAD

**Issue by StevenSong** [mwaskom/seaborn#2186]
a follow up to #1502 and #1823 , the check in `_univariate_kdeplot` compares `data.var() == 0` but it might be good to use `np.isclose` or similar to compare the two values: https://github.com/mwaskom/seaborn/pull/1823/files#diff-275d8fa79eba7de0a5ee2383be24c16eR281

I have data like:
```
-> if np.nan_to_num(data.var()) == 0:
(Pdb) data
array([0.33333334, 0.33333334, 0.33333334, 0.33333334, 0.33333334,
       0.33333334, 0.33333334, 0.33333334, 0.33333334, 0.33333334])
```

which has a variance that should be 0 but because of floating point precision and the method by which I arrive at the data, has a tiny variance
```
(Pdb) data.var()
3.0814879110195774e-33 
```

the result is that it proceeds onto use `scipy` which leads to the LinAlg error in #1502  - funny enough, it isn't an issue with `statsmodels` but would like to avoid another dependency for my project

it would be really useful if the check in `_univariate_kdeplot` could take into account the magnitude of the variance relative to the data itself

**Comment by mwaskom** [comment]
I don't think it really has anything to do with the magnitude of the data itself and just that the `LinAlgError` is being triggered because scipy is using `np.cov` with weights defaulting to a constant vector (that sums to 1), which is returning exactly 0:

```
x = np.array([0.33333334, 0.33333334, 0.33333334, 0.33333334, 0.33333334])
np.cov(x)
```
```
array(3.42387546e-33)
```

vs.

```
w = np.ones_like(x) / len(x)
np.cov(x, aweights=w)
```
```
array(0.)
```

Probably checking that the variance is "close to 0" is fine ...
