### ISSUE TITLE
bs4 not found when using seaborn.get_dataset_names

### ISSUE THREAD

**Issue by nilnil47** [mwaskom/seaborn#2189]
bs4 is as seaborn dependency, and the get_dataset_names use it

**Comment by mwaskom** [comment]
I guess the question here is "why is it not listed in the setup.py requirements?" and the answer is that it is used only in one rather peripheral function, so it is not a required dependency.

**Comment by mwaskom** [comment]
That said, there's really no reason to use BeautifulSoup here, as the task is very simple: ﻿#2190
