### ISSUE TITLE
[Feature Request] Separate `dendrogram_ratio` for rows and cols via`clustermap`

### ISSUE THREAD

**Issue by jolespin** [mwaskom/seaborn#2191]
I encounter a lot of wide dataframes that I cluster.  Is it possible in future versions to have separate `col_dendrogram_ratio` and `row_dendrogram_ratio` arguments? The reason why is because the col dendrogram is now too squished and the row dendrogram is still too large. 

For backwards compatibility you could add the arguments which would override `dendrogram_ratio`.  If `dendrogram_ratio` was used there could be a `DeprecationWarning` OR just leave it.  

Here's an example:
![image](https://user-images.githubusercontent.com/9061708/89842823-9ea65900-db2b-11ea-9ad4-02ba79c01233.png)

**Comment by mwaskom** [comment]
This is currently possible.

From the [docs](seaborn.pydata.org/generated/seaborn.clustermap.html):

> {dendrogram,colors}_ratio: float, or pair of floats, optional
    Proportion of the figure size devoted to the two marginal elements. If a pair is given, they correspond to (row, col) ratios.

**Comment by jolespin** [comment]
Awesome, my bad I didn't catch this in the docs.
