### ISSUE TITLE
reuse figure with relplot

### ISSUE THREAD

**Issue by franzhaas** [mwaskom/seaborn#2192]
Hello,

Thanks for the great tool!

I tried to use relplot to make multiple line plots in one named figure.

I used this code.:
import matplotlib
import seaborn as sns
sns.load_dataset("tips")
matplotlib.pyplot.figure("foo")
g = sns.relplot(x="total_bill", y="tip", hue="day", data=tips)
matplotlib.pyplot.show()

I expected to find one figure with "foo" in the title and the example, similar to like this example behaves:

fmri = sns.load_dataset("fmri")
ax = sns.lineplot(x="timepoint", y="signal", data=fmri)
matplotlib.pyplot.show()

What do i need to do in order to have the relplot behave like the lineplot with respect to the figure it draws on?

Thanks in advance,
Franz

**Comment by mwaskom** [comment]
[This section of the docs](http://seaborn.pydata.org/introduction.html#figure-level-and-axes-level-functions) should answer your question.
