### ISSUE TITLE
Final removals for 0.12

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#2207]
Final removal as functional parameters

- [x] `JointGrid`/`jointplot` `size` -> `height`
- [x] `FacetGrid` (and downstream functions) `size` -> `height` (possibly still catch and warn, but no longer use)
- [x] `stripplot`/`swarmplot` `split`->`dodge` (could hold off until 0.12)
- [x] `kdeplot` `data2`

Removal from function signature (but handle in `kwargs`):

- [x] Old `kdeplot` parameters
- [x] Old `rugplot` parmaeters

**Comment by MaozGelbart** [comment]
Perhaps `factorplot`?

**Comment by mwaskom** [comment]
I still see occasional stackoverflow questions using (or worse, answers recommending) it. I think for “thin” deprecated object names that just pass to their replacement, it’s fine to leave them around for a while. Perhaps a next stage of deprecation would be to keep the name but error out with an informative exception. There’s some library that adds progressively longer `time.sleep` calls for deprecated functions, which is pretty funny.

**Comment by manfred2020** [comment]
just curious: what was the reason for this change: "stripplot/swarmplot split->dodge"
i think, "split" is by far more understandable and common.
