### ISSUE TITLE
Feature Request: Add group size (number of samples) to boxplots (or categorical plots in general)

### ISSUE THREAD

**Issue by kopytjuk** [mwaskom/seaborn#2227]
A few words about the motivation:

While looking at statistical distributions a common question from other team members is "_how many samples are there in this group?_"

There are some workarounds like [this](https://python-graph-gallery.com/38-show-number-of-observation-on-boxplot/) or [this](https://stackoverflow.com/questions/29286217/is-there-a-good-way-to-display-sample-size-on-grouped-boxplots-using-python-matp) which rely on manually grouping the data (again) and calculate the number of samples.

What do you think about a text label somewhere in the plot, for example (a possible idea):

![image](https://user-images.githubusercontent.com/12762439/91349087-168ba900-e7e5-11ea-87de-45aeffb3f0b7.png)

This feature could be optional, i.e. turned off by default.

I know many people will ask questions like:

- "_why don't you filter groups with few populations before passing to `seaborn`_?" A: sometimes you are not aware about the groups you want to drop beforehand
- "_why don't you pull those group-sizes in parallel to the boxplot?_" - A: One could do this, but it is unhandy ... You still have to map numbers to the boxplots manually ...

In my opinion this feature is relatively straightforward to include, since it is a `box_data.size` in https://github.com/mwaskom/seaborn/blob/f62a4a51f3195be3860d5282e5f3afc4d438d0f3/seaborn/categorical.py#L463

**Comment by mwaskom** [comment]
I am -1 on seaborn functions adding textual annotations to plots. It adds too much complexity. But could be a good task for a downstream library.

The traditional way to show the reliability of the median estimate in a boxplot is to set `notch=True`, which adds a form of error bars. People have also requested a feature that modifies the box width as a function of the number of observations. And I think [combining box plots with strip or swarm plots](http://seaborn.pydata.org/examples/horizontal_boxplot.html) is a great idea, and also communicates this information.
