### ISSUE TITLE
hue_norm should accept 3-tuple and set center of diverging colormap

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#2230]
But should this use the matplotlib `TwoSlopeNorm` or should it trim the range of the colormap like what happens in`heatmap`? Probably the latter. (Could we turn that behavior into a proper Norm object?)

**Comment by ankh6** [comment]
Hey @mwaskom I'd like to make my first contribution here.
Is this issue still opened ? Can you add more clarification on work to be done ?

**Comment by JPvRiel** [comment]
Is it not possible to pass a `matplotlib.colors.TwoSlopeNorm` object, since that bases `matplotlib.colors.Normalize`, and seaborn does accept `matplotlib.colors.Normalize` instead of a tuple?.

E.g.

```python
hue_norm=matplotlib.colors.TwoSlopeNorm(vmin=-1, vcenter=0, vmax=4)
```

**Comment by mwaskom** [comment]
Yes you should be able to pass a `TwoSlopeNorm` object, although I don't think that the behavior of `TwoSlopeNorm` is *generally* what you want with diverging data.

But actually given the way to current legend is created, trimming the colormap like in `heatmap` isn't necessary even if you specify symmetric limits:

```python
x = np.arange(10)
y = np.arange(-3, 7)
sns.relplot(x=x, y=y, s=500, hue=y, palette="icefire", hue_norm=(-7, 7))
```
![image](https://user-images.githubusercontent.com/315810/133927943-2f7a9166-03c0-4c04-9259-4305719f7f98.png)

I think the other benefit here would be that passing a 3-tuple would automatically set the default palette to be diverging (similar to `heatmap` when you set `center=`.

But on reconsideration, I no longer feel that would be worth the effort + API complexity.
