### ISSUE TITLE
Seaborn errors on deprecated version

### ISSUE THREAD

**Issue by willie14** [mwaskom/seaborn#2235]
Hello Sires dev. of seaborn, 

I encountered a problem of the announcement of the deprecated version of Python i used.
I already checked the version of Python i use, and it is 3. Version.
According to my knowledge on Python ,the computer asserts a relation  of seaborn with deprecated Py2.7.

Thus says the error <:

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in ./.local/lib/python2.7/site-packages (0.9.1)
Requirement already satisfied: matplotlib>=1.5.3 in ./.local/lib/python2.7/site-packages (from seaborn) (2.2.5)
Requirement already satisfied: pandas>=0.17.1 in ./.local/lib/python2.7/site-packages (from seaborn) (0.24.2)
Requirement already satisfied: numpy>=1.10.4 in ./.local/lib/python2.7/site-packages (from seaborn) (1.16.6)
Requirement already satisfied: scipy>=0.17.1 in ./.local/lib/python2.7/site-packages (from seaborn) (1.2.3)
Requirement already satisfied: python-dateutil>=2.1 in ./.local/lib/python2.7/site-packages (from matplotlib>=1.5.3->seaborn) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python2.7/site-packages (from matplotlib>=1.5.3->seaborn) (1.1.0)
Requirement already satisfied: six>=1.10 in ./.local/lib/python2.7/site-packages (from matplotlib>=1.5.3->seaborn) (1.14.0)
Requirement already ##

But  i cant get to use your wonderful seaborn package. What should i do to change how my PC work to activate seaborn??

Thanks for any advice.

Regards ,
Wili EkaP

**Comment by mwaskom** [comment]
It is likely that when you have multiple versions of Python installed on your system and when you execute `pip` it uses an older version.

Some people recommend using `python -m pip install <package>` rather than `pip install <package>` to avoid this problem.

As this is not a seaborn issue, I am going to close.
