### ISSUE TITLE
distplot()'s norm_hist=True does not produce relative frequency

### ISSUE THREAD

**Issue by chemicalstatistician** [mwaskom/seaborn#2238]
I ran the following code with the attached dataset, and the resulting plot does not show the relative frequency. 

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
my_data = pd.read_excel('my_data.xlsx', header=None)
sns.distplot(my_data, kde=False, norm_hist=True)
plt.show()

[my_data.xlsx](https://github.com/mwaskom/seaborn/files/5159500/my_data.xlsx)

![distplot](https://user-images.githubusercontent.com/14254091/91920888-3238f880-ec98-11ea-8b8f-020c56bba844.png)

<img width="292" alt="code and output" src="https://user-images.githubusercontent.com/14254091/91920999-6d3b2c00-ec98-11ea-9bfd-7b4f53e3f8e9.PNG">

**Comment by mwaskom** [comment]
What are you expecting it to show?

**Comment by chemicalstatistician** [comment]
I want the y-axis to show the relative frequency. Right now, it shows the absolute frequency.

**Comment by mwaskom** [comment]
Why do you think that?

**Comment by chemicalstatistician** [comment]
......because relative frequency is a proportion, and its maximal value is 1.  

Here is an example of how Seaborn is plotting my desired histogram _correctly_.  Notice that the following y-axis shows a **proportion**, not an absolute count.

![image](https://user-images.githubusercontent.com/14254091/92123182-54cb2e80-edca-11ea-9acd-f53b717f8f8d.png)


Somehow, for my original dataset, it did not plot the relative frequency on the y-axis. Please investigate.

**Comment by mwaskom** [comment]
Are you looking at some documentation for `norm_hist` claim that it shows a "relative frequency"?

**Comment by arose13** [comment]
Hey @chemicalstatistician the confusion is very understandable so here is the explanation.

1. `norm_hist` implies with the argument name that the histogram is _normalised_ which it is not. In this case the docstring gets it right, the density is displayed on the y-axis rather than the count. So if you were 2 run `sns.distplot(random_normal / 10, norm_hist=True)` the values on the y-axis would increase because the density has increased.

2. `norm_hist` is merely being passed to `matplotlib` `hist()` as the _density_ argument (and not the `normed` argument) so it is more transparent that it is computing the density.

Matplotlib hist function can actually normalise your histogram if you use matplotlib directly and set the kwarg `normed=True`.

Perhaps @mwaskom original intention was for `norm_hist` argument to compute the density but considering seaborn's argument name that's probably not true.

I can make a PR myself if you'd like 😄?

**Comment by chemicalstatistician** [comment]
OK - thanks, @arose13. It seems like there is no Python function that plots a histogram of relative frequencies automatically, and I have to divide each absolute frequency by the total count to obtain the relative frequency.

**Comment by mwaskom** [comment]
@arose13 you are on the right track, but wrong in some respects.

First, if you set `norm_hist`, it normalizes the histogram. The confusion here is about *what form* of normalization it uses. The function is doing what its documentation claims, which is normalizing the bars to show a discrete approximation to a probability density function, i.e. the sum of every bar's *area* is equal to 1. I gather that @chemicalstatistician is looking for or expecting normalization such that the sum of every bar's *height* is equal to 1, which would be equivalent to a probability mass function.

(Adding complexity, the term "frequency normalization" is used in some fields to describe a normalization where each bar height is given by `count / binwidth`, which is equal to density normalization except when binwidths are not uniform. This is why I was trying to get @chemicalstatistician  to say more about what precisely he was expecting to happen).

These are all normalization (that is, they let you compare two histograms with different sample sizes), but the interpretation of the y axis changes. Mistaking density for probability is a common source of confusion, but that didn't seem to be exactly what was going on here, so I was, again, trying to understand the nature of the report better.

As for why the parameter has a name that differs from the matplotlib parameter, the answer is that matplotlib (inheriting from numpy) *used to* have `normed=True`, but the parameter name was changed at some point (more information [in this thread](https://github.com/matplotlib/matplotlib/issues/9557)). In older matplotlibs, `normed=True` and `density=True` do the same thing, but I think that the deprecation of `normed` has been completed and it doesn't seem to be present in the current version of matplotlib.

In any case, when seaborn v0.11 gets released, distplot will be deprecated in favor of [histplot](https://github.com/mwaskom/seaborn/pull/2125), which, among other things, has `stat="density"` for the existing behavior and `stat="probability"` for what I understand @chemicalstatistician to be looking for.

And a good lesson for everyone is that you'll get useful answers faster if you are clear about what you're expecting to happen and why you think that's not happening.
