### ISSUE TITLE
Could I use 'split=True' of violinplot with FacetGrid ?

### ISSUE THREAD

**Issue by kotamine** [mwaskom/seaborn#2252]
Say, I want to put this split-violinplot into FacetGrid with col='sex'.

```
sns.violinplot(x="day", y="total_bill", hue="smoker",
                      data=tips, split=True);
```
'hue' gets passed on but it is not using split option correctly.

```
g = sns.FacetGrid(tips, hue='smoker', col='sex')
g.map(sns.violinplot, 'day',"total_bill", split=True);
```

Thanks for your help!

**Comment by kotamine** [comment]
This is with sns.boxplot for a similar task. 
```
sns.boxplot(x="day", y="total_bill", hue='smoker',data=tips)
```
This gives me an error too.
```
g = sns.FacetGrid(tips, hue='smoker', col='sex')
g.map(sns.boxplot,"day", "total_bill")
```

**Comment by mwaskom** [comment]
Yes, but you need to let the plotting function handle the hue mapping, not the `FacetGrid`. Or you could (and should) use `catplot` for this kind of simple plot.

BTW this kind of question is generally better suited for StackOverflow, where it will create a record that will be easier for others to find in the future.

**Comment by kotamine** [comment]
Thank you for your response.  I might have missed, but I did not see any warning about violin-split or boxplot cannot work with FacetGrid. 

`catplot` worked for my case.  At first I was using `catplot` but I could not easily find methods like `.add_legend()`  and `.set_xlabels()` to make minor refinements (I found those later).  Then I came across `FacetGrid`, which I thought was supposed to be a more general approach.  
  
Thanks again.

**Comment by mwaskom** [comment]
Those specific do not receive a warning but the [FacetGrid](http://seaborn.pydata.org/generated/seaborn.FacetGrid.html) docs say:

> It can also represent levels of a third variable with the hue parameter, which plots different subsets of data in different colors. This uses color to resolve elements on a third dimension, but only draws subsets on top of each other and will not tailor the hue parameter for the specific visualization the way that axes-level functions that accept hue will.
