### ISSUE TITLE
Add a `plot_theme` or similar function to complement `set_theme`

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#2254]
Like `axes_style`/`set_style`, this should report all of the parameters currently set in the theme and work as a context manager.

A little trickier because `set()` accepts arbitrary `rcParams` and the other theming functions don't.

Also needs a good name.

**Comment by CatNofishing** [comment]
Good idea,  I'm looking forward to this feature. Also you can use with sns.axes_style("white"), sns.color_palette("pastel") To achieve this function，but it's obviously not convenient and it's not perfect。so please consider achieve this function:
 with sns.plot_theme(style='white',context='talk',palette='deep',rc=None)

**Comment by mwaskom** [comment]
This is easy enough to accomplish by stacking context managers:

```python
with sns.axes_style("whitegrid"), sns.color_palette("Set2"):
    sns.boxplot(tips, x="total_bill", y="time", hue="sex")
```

Not convinced we need an additional function here.
