### ISSUE TITLE
Feature request: Log scale for violin plots

### ISSUE THREAD

**Issue by yannikschaelte** [mwaskom/seaborn#2258]
The `kdeplot` has an option `log_scale`, implying both KDE calculation and plotting happen on log10 scale. It would be nice to have the same feature for violin plots, to circumvent having to manually transform the data, and adjust the axes labels later. Conceptually, this should be quite similar.

If this already exists, my apologies.

**Comment by mwaskom** [comment]
Hi, yes this was not an oversight, but enabling the new functionality in violinplot will be much easier after its internals are refactored, which is on the roadmap for 0.12 (#2112).

I am going to close as the broader project of modernizing the categorical plots is tracked elsewhere.

**Comment by Jbollenbacher** [comment]
Any update on when this feature may be available?

**Comment by pmeier** [comment]
@mwaskom Given that #2112 was closed as "not planned", is there any chance we can re-open this? Happy to help out if that is the only reason to not go for this.

**Comment by aseltmann** [comment]
@mwaskom I want to push that issue as well. You are right that it is possible to achieve that functionality with transforming the data, but there are some hacks involved, which is less than ideal. Right now I have to:
1. log transform the data
2. do violinplot
3. extract the scale position or text of the tick labels and manually 10**(logs) to get the correct ones
Also, if I want to do adjustments like setting `xlim`, there are always hacks involved. Would be great to have that functionality, [I think it is there in R's ggplot2 as well](https://stackoverflow.com/questions/60131839/violin-plot-troubles-in-python-on-log-scale).
