### ISSUE TITLE
Violinplot: Customize line colors

### ISSUE THREAD

**Issue by yannikschaelte** [mwaskom/seaborn#2259]
When plotting a violinplot (in particular with hue split), it would be good to be able to define different line colors. Currently, only the fill color can be specified, lines are always grey I think (?).

Not having filled curves but only the colored lines would be of advantage e.g. when combining with jitter plots, as otherwise the plot gets overly crowded.

**Comment by mwaskom** [comment]
I think there will probably remain only one meaningful color, otherwise that would complicate the concept of semantic hue mapping.

You can decrease the amount of jitter if it’s covering up too much of the plot.
