### ISSUE TITLE
displot's row_order, col_order kwargs are not passed to FacetGrid

### ISSUE THREAD

**Issue by badge** [mwaskom/seaborn#2261]
In [the `displot` source](https://github.com/mwaskom/seaborn/blob/master/seaborn/distributions.py#L2181), the `col_order` and `row_order` kwargs are not passed to `FacetGrid`, so they are silently ignored when given to the function:

```python
import seaborn as sns
penguins = sns.load_dataset("penguins")
sns.displot(
    data=penguins,
    x="flipper_length_mm",
    hue="species",
    col="sex",
    kind="kde",
    col_order=["Female", "Male"]
)
```

Currently, one has to pass the arguments via `facet_kws`:

```python
sns.displot(
    data=penguins,
    x="flipper_length_mm",
    hue="species",
    col="sex",
    kind="kde",
    facet_kws=dict(col_order=["Female", "Male"])
)
```

**Comment by mwaskom** [comment]
Thanks for the report and fix. Current workaround would be to set the col/row variables to an ordered categorical type in your dataframe, and then the facetgrid will use that order.
