### ISSUE TITLE
 'min-mean-max' plot with sns.pointplt()

### ISSUE THREAD

**Issue by MoAliMa** [mwaskom/seaborn#2265]
Hi, 
I want to plot a figure like [Fig.1](https://www.google.com/search?q=min+mean+max+plot&rlz=1C1SQJL_zh-CNCN778CN778&sxsrf=ALeKk02qDJzqygFrHbcc5ryP73M0N256dw:1599738463763&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi9w_aWwt7rAhWlIaYKHcWkBJEQ_AUoAXoECA8QAw&biw=1396&bih=657#imgrc=Sxi1drlsHQpbCM) called 'min-mean-max plot'. However, there is only 'sd'(standard deviation) in [seaborn.pointplot()](https://seaborn.pydata.org/generated/seaborn.pointplot.html).  seaborn can plot very beautiful and publishable figures.  Could you add this code in the 1478 rows of  './seaborn/categorical.py '?

```
if ci == "sd":
    estimate = estimator(stat_data)
    sd = np.std(stat_data)
    confint.append((estimate - sd, estimate + sd))      

elif ci == "minmax":
    estimate = estimator(stat_data)
    num_min, num_max = stat_data.min(), stat_data.max()
    confint.append((num_min, num_max))
```                     

Thanks a lot !

**Comment by mwaskom** [comment]
Thanks for the suggestion. I won't be making this ad hoc change, but proper support for something like this is on the roadmap.

**Comment by MoAliMa** [comment]
Thank you

**Comment by angushendrick** [comment]
Would like to see this too.
