### ISSUE TITLE
jitter not working? 

### ISSUE THREAD

**Issue by scideas** [mwaskom/seaborn#2266]
Hi, first off, thanks for your effort in making this package. 

I need to implement jitter but haven't found any other plotting functions other than seaborn that easily do so. However, for some reason I can't get it to work, despite many great tutorials online. I was wondering if I am doing something wrong? 

sns.scatterplot(x_rank,
y_content,
color='green',
alpha=1,    
s=10,
y_jitter=0.5)

For some reason, no matter how much jitter I add (ranging from 0.01 to 100, nothing changes on the following plot. 
![image](https://user-images.githubusercontent.com/48698173/92738614-b5fe7f00-f341-11ea-942f-83d4361051af.png)

Am I doing something wrong? I'm using both an ubuntu machine and a Mac and both are experiencing the same isssue.

Thanks for your guidance on this.

**Comment by mwaskom** [comment]
Well I don't think you're doing anything wrong but the docs for scatterplot do say

> {x,y}_jitter: booleans or floats
    Currently non-functional.

So I think it's working as advertised :)

**Comment by mwaskom** [comment]
Oops, I forgot that seaborn does support this, in a roundabout way:

```python
xx = np.linspace(0, 4, 100)
yy = np.exp(-xx)
sns.regplot(x=xx, y=yy, y_jitter=.05, fit_reg=False)
```
![image](https://user-images.githubusercontent.com/315810/92773438-9b8ccb80-f36a-11ea-9b19-c2f9fc47698a.png)

**Comment by scideas** [comment]
Awesome- thanks for letting me know about this workaround!

**Comment by richard-thonig** [comment]
I have the same "issue" and think making the x-y-jitter work in the scatterplot would be awesome!

**Comment by efostermoore** [comment]
Came here wondering the same -- please add support for jitter in scatterplot!
