### ISSUE TITLE
potential issue with stat='density' in histplot

### ISSUE THREAD

**Issue by dougollerenshaw** [mwaskom/seaborn#2269]
Thanks for maintaining this great package. I'm excited to see the new histplot function in v0.11.0. But the `stat='density'` parameter isn't acting quite as I'd expect. Is it possible that there's a bug, or am I just using it wrong?

Here's some sample data with very unbalanced labels (1,000 of label 'a', 10,000 of label 'b'):
```
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.concat([
    pd.DataFrame({
        'value':np.random.randn(1000),
        'label':['a']*1000
    }),
    pd.DataFrame({
        'value':np.random.randn(10000),
        'label':['b']*10000
    })
])
```
When I use `histplot` with `stat='density'`, I'd expect the two distributions to be roughly similar (both integrating to 1), but instead the distribution for the class with a higher label count is taller:
```
sns.histplot(
    data=df, 
    x='value',
    hue='label',
    stat='density',
    kde=True
)
```
![image](https://user-images.githubusercontent.com/19944442/92972595-54204100-f437-11ea-8820-85c3ab2f63fb.png)

If I do roughly the same using `distplot`, the resulting plot is as I'd expect:
```
fig,ax=plt.subplots()
sns.distplot(
    df.query('label=="a"')['value'], 
    norm_hist=True,
    ax=ax,
)
sns.distplot(
    df.query('label=="b"')['value'], 
    norm_hist=True,
    ax=ax
)
ax.legend(['a','b'])
```
![image](https://user-images.githubusercontent.com/19944442/92972582-4d91c980-f437-11ea-8b06-7f9bebe4ed88.png)

Am I somehow misunderstanding the expected use of  `stat='density'` in `histplot`?

**Comment by mwaskom** [comment]
Check out `common_norm`:

> common_normbool
    If True and using a normalized statistic, the normalization will apply over the full dataset. Otherwise, normalize each histogram independently.

**Comment by mwaskom** [comment]
Also explained here: https://seaborn.pydata.org/tutorial/distributions.html

**Comment by dougollerenshaw** [comment]
Thank you! Sorry to have missed that in the docs.

With `common_norm=False`, I get exactly what I expected:

```
sns.histplot(
    data=df, 
    x='value',
    hue='label',
    stat='density',
    kde=True,
    common_norm=False,
)
```
![image](https://user-images.githubusercontent.com/19944442/92975136-7ec0c880-f43c-11ea-9f8e-6f7ef39e24db.png)
