### ISSUE TITLE
Hue Error

### ISSUE THREAD

**Issue by SAMANDOLL** [mwaskom/seaborn#2271]
My data have 14 thousand genes in one colum, i don't have x value, how i can give color with hue. i have divided my genes in three category. But hue is not working. Please guide me about this error.

i have only y-axis and Hue colum.

Thanks

**Comment by mwaskom** [comment]
I'm afraid I don't quite understand the challenge you're facing, but I would encourage you to make a reproducible example and ask on StackOverflow or Discourse. Thanks!
