### ISSUE TITLE
Lineplot CI results differ between seaborn v0.10.1 and v0.11.0 when data includes NaN values

### ISSUE THREAD

**Issue by papr** [mwaskom/seaborn#2272]
I noticed that the lineplot CI results differ between seaborn `0.10.1` and `0.11.0` when data includes `NaN` values. Specifically, the CI results contain `NaN` values in the newer seaborn version.

Reading through the release notes, I have not noticed a particular entry that would explain this change in behavior.

## Reproducing the issue
Full example code at the very end.

This example is based on one of the examples in the `lineplot` API documentation. Most importantly, I set 1% of each `event` group to `NaN` before plotting.
```py
fmri = sns.load_dataset("fmri")
sns.lineplot(data=fmri, x="timepoint", y="signal", hue="event", ax=axs[0])

def set_nan(event):
    event.iloc[::100] = np.nan
    return event

fmri.signal = fmri.groupby("event").signal.transform(set_nan)

sns.lineplot(data=fmri, x="timepoint", y="signal", hue="event", ax=axs[1])
```
![ci_with_nan_values_sns_0 10 1](https://user-images.githubusercontent.com/168390/93002582-50c0ae80-f538-11ea-91ed-626776e2a38d.png)
![ci_with_nan_values_sns_0 11 0](https://user-images.githubusercontent.com/168390/93002084-6338e900-f534-11ea-9907-3b3594926e76.png)
![ci_with_nan_values_sns_0 12 0 dev0](https://user-images.githubusercontent.com/168390/93002086-63d17f80-f534-11ea-9fb5-ff92ea5c971d.png)

Full code to reproduce figures:
```py
import numpy as np

import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

fig, axs = plt.subplots(1, 2, figsize=(8, 4))
axs[0].set_title(
    f"seaborn version: {sns.__version__}\n"
    f"matplotlib version: {matplotlib.__version__}\n"
    f"matplotlib backend: {plt.get_backend()}\n\n"
    "Original data"
)
axs[1].set_title("Data including NaN values")

fmri = sns.load_dataset("fmri")
sns.lineplot(data=fmri, x="timepoint", y="signal", hue="event", ax=axs[0])

def set_nan(event):
    event.iloc[::100] = np.nan
    return event

fmri.signal = fmri.groupby("event").signal.transform(set_nan)

sns.lineplot(data=fmri, x="timepoint", y="signal", hue="event", ax=axs[1])

fig.tight_layout()
fig.savefig(f"ci_with_nan_values_sns_{sns.__version__}.png")
```

**Comment by mwaskom** [comment]
Dang, sorry about that. Culprit is #2035 which moved from using an internal wrapper around `scipy.stats.scoreatpercentile` (which is nan-safe by default) to `np.percentile` (which apparently is not).

If dropping nas from your data before passsing to seaborn will be cumbersome, you could work around it by monkey-patching 0.11.0 with

```python
def ci_func(a, which=95, axis=None):
    """Return a percentile range from an array of values."""
    p = 50 - which / 2, 50 + which / 2
    return np.nanpercentile(a, p, axis)

sns.relational.ci_func = ci_func
```

Not an ideal solution but a very easy implementation in this case...

**Comment by papr** [comment]
Thank you for looking into the issue and providing a nice (temporary) workaround!

**Comment by mwaskom** [comment]
Actually this seems to affect the CI computation too so a better workaround would be to use `estimator=np.nanmean`.
