### ISSUE TITLE
Cannot change markersize with kind='reg'

### ISSUE THREAD

**Issue by anishk74** [mwaskom/seaborn#2274]
sns.pairplot(data, kind='reg', plot_kws={'s':3}) 
The statement results in an error :-
TypeError: regplot() got an unexpected keyword argument 's'.

**Comment by mwaskom** [comment]
If you look at the regplot docs, you will see that it does requires specific dictionaries of keyword arguments for the scatter and line components of the plot.

**Comment by anishk74** [comment]
Dear @mwaskom , I am still facing problems with the statement to specify the marker-size in a kind='reg' pairplot. Can you help?

**Comment by anishk74** [comment]
Nested dictionries plot_kws={'scatter_kws':{'s':3}} worked for me.
Thanks.
