### ISSUE TITLE
an api inconsistency with error bars

### ISSUE THREAD

**Issue by neutrinoceros** [mwaskom/seaborn#2275]
## summary

I've noticed that seaborn doesn't understand `yerr` keyword argument in e.g. `sns.barplot` as a valid column key when a dataframe is passed through its `data` keyword argument.
This is inconsistent with both  `sns.barplot`'s `x` and `y` kwargs, as well as matplotlib's own `plt.bar` api, which makes the final error quite confusing: I originally thought there was an issue with how my yerr column's data was formatted, until I tried it out directly with mpl's api. 

## code for reproduction

```python
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame({"a": np.arange(10), "b": np.random.normal(0, 1, 10), "c": np.random.normal(0, 1, 10)})

fig, axes = plt.subplots(nrows = 3)

# bare matplotlib api
axes[0].bar("a", "b", yerr="c", data=df)

# seaborn api, works but kinda clunky
sns.barplot(x="a", y="b", yerr=df["c"], data=df, ax=axes[1])

# seaborn api, directly migrated from bare mpl.
# Fails with an error that may be read as "yerr column is illformatted"
# when it's really just interpreted as a string rather than a column key
sns.barplot(x="a", y="b", yerr="c", data=df, ax=axes[2])
fig.savefig("/tmp/barplot_api.jpg")
```

output
```
ConversionError: Failed to convert value(s) to axis units: 'c'
```
![barplot_api](https://user-images.githubusercontent.com/14075922/93014946-8192f900-f5b5-11ea-8630-a65aff785d65.jpg)

**Comment by mwaskom** [comment]
`yerr` is not part of the seaborn API. Many seaborn functions pass additional kwargs down to the underlying matplotlib function, but they do so literally, without any transformations. That's what's happening here.

Matplotlib functions have a lot of parameters and it's not really feasible for seaborn to try and guess whether the user is passing something to matplotlib that isn't going to make sense. I appreciate how it might cause some confusion in places, but the end result gives a lot more flexibility.

**Comment by neutrinoceros** [comment]
Ah, I was assuming `data`, `x`, and `y` were passed down to matplotlib directly, in which case it would seem trivial to fix this (but I guess this would not have happened at all). I'd like to learn more about seaborn's design so I can maybe contribute actively in the future. May I ask why the `data` kwargs isn't passed to mpl ? :)
