### ISSUE TITLE
fit in distplot

### ISSUE THREAD

**Issue by StevenLi-DS** [mwaskom/seaborn#2276]
I just realized that `distplot` will be DEPRECATED after `0.11.0`.
I have some code that uses `fit` arg and I didn't found any other distribution plot functions can do so.
Will there be axes-level function to achieve this other than `distplot`?

```python
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import norm

data = np.random.normal(0, 1, 200)

fig, ax = plt.subplots()
sns.distplot(data, hist=False, kde=False, fit=norm,
             fit_kws={'color': 'r', 'linewidth': 2.5}, ax=ax)
```
![download](https://user-images.githubusercontent.com/33796896/93028540-8de17b00-f5e2-11ea-8a54-35f416de7707.png)

**Comment by mwaskom** [comment]
There may be some chance of a similar functionality being added (back) to one of the distribution plot functions in the future, but I would say the chance is relatively low.

FWIW, you can achieve your plot with

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

data = np.random.normal(0, 1, 200)
xx = np.linspace(data.min(), data.max(), 100)

fig, ax = plt.subplots()
ax.plot(xx, norm.pdf(xx, *norm.fit(data)), color="r", lw=2.5)
```

which does not seem substantially more complicated than your example.

**Comment by StevenLi-DS** [comment]
Thanks for the quick reply. I really wish you could give it a consideration to add it back at some point.

**Comment by spirosbax** [comment]
Hi, I just want to comment that generating data and then overlaying them on a histogram is really not a viable alternative for the `fit` parameter of `distplot`. Especially when one wants to quickly demonstrate how different `scipy.stats` distributions fit on a histogram.  
E.g. `sns.distplot(y, kde=False, fit=stats.lognorm)` will be 4-5 lines when `distplot` is removed.  
Please consider adding back the same functionality. Thank you for your work.

**Comment by mwaskom** [comment]
>  E.g. sns.distplot(y, kde=False, fit=stats.lognorm) will be 4-5 lines when distplot is removed.

In the example I gave above, it is 2 lines. (And one of the lines is constant for any number of distributions examined). Is there some reason the example code is not sufficient for your usecase?
