### ISSUE TITLE
SEM and custom errorbars on pointplot

### ISSUE THREAD

**Issue by JoeZiminski** [mwaskom/seaborn#2283]
Thank you very much for this excellent resource. For my own use I have added the functionality to also plot standard error of the mean, and custom errorbars for pointplot:

starting line 1477 of categorical.py in the _PointPlotter.estimate_statistic function (shown after sd):
```
                    if ci == "sd":  

                        estimate = estimator(stat_data)
                        sd = np.std(stat_data)
                        confint.append((estimate - sd, estimate + sd))

                    elif ci == "sem":                                                       

                        estimate = estimator(stat_data)
                        sem = np.std(stat_data) / np.sqrt(len(stat_data))
                        confint.append((estimate - sem, estimate + sem))

                    elif ci[0] == 'custom':

                        estimate = estimator(stat_data)
                        ci_ = ci[1][i]
                        confint.append((estimate - ci_, estimate + ci_))
```

At the moment it is a bit ugly, and requires ci to be bassed as a two inputs (one 'custom', the other an array of errorbars). so might lead to issues in its current form. However am happy to work on it if its something youd consider having as part of the package.

Best,
Joe

**Comment by mwaskom** [comment]
I'm -1 on special casing this, but more general support is on the roadmap.

If you want error bars that correspond to the standard error of the mean, you can also show the 68% bootstrap confidence interval.

But 95% CI is always more informative.
