### ISSUE TITLE
boxenplot linewidth bug

### ISSUE THREAD

**Issue by nbara** [mwaskom/seaborn#2285]
I tried changing the linewidth of the boxes' edges with the `linedwidth` parameter, but it doesn't seem to do anything. 

This is actually visible in the documentation:
https://seaborn.pydata.org/generated/seaborn.boxenplot.html#seaborn.boxenplot

The following example specifies a linewidth of 2.5:

```python
ax = sns.boxenplot(x="day", y="total_bill", hue="time", data=tips, linewidth=2.5)
```

which produces the following image:
![image](https://user-images.githubusercontent.com/10333715/93465245-cdfa7380-f8ea-11ea-8051-ce591f4ead12.png)

As you can see the boxes linewidth is unchanged. Instead, the linewidth argument changes the legend boxes.

**Comment by MaozGelbart** [comment]
Yes seems so:
[https://github.com/mwaskom/seaborn/blob/211cabb09bb9228635bdd80f74f7591d36d7b2a7/seaborn/categorical.py#L1816-L1816](https://github.com/mwaskom/seaborn/blob/211cabb09bb9228635bdd80f74f7591d36d7b2a7/seaborn/categorical.py#L1816-L1816)

Until a fix is available, you can manually set it after creating the plot:
```python
[p.set_linewidth(2.5) for p in plt.gcf().findobj(matplotlib.collections.PatchCollection)]
```
