### ISSUE TITLE
Strange results in barplot when plotting value less than 1e-8

### ISSUE THREAD

**Issue by YAMWD** [mwaskom/seaborn#2286]
Hello! I noticed that when plotting values less than 1e-8 using barplot the y axis would be clipped to 1e-12 and shows an extra negative part. 

But other plot like lineplot(I only tested it) worked well.

### **matplotlib**: 3.2.2

# **Reproducing**

```python 
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#test for using seaborn to draw data less than 1e-8
data1 = np.arange(1e-8, 1e-7, 1e-8) #larger than 1e-8 everything's fine
data2 = np.arange(1e-9, 1e-8, 1e-9) #strange clip to less than 1e-12 when plotting values less than 1e-8

DS1 = pd.DataFrame()
DS2 = pd.DataFrame()
for i in range(len(data)):
    df1 = pd.DataFrame({'group index': i, 'std dev': data1[i]}, index = [0])
    df2 = pd.DataFrame({'group index': i, 'std dev': data2[i]}, index = [0])
    DS1 = DS1.append(df1)
    DS2 = DS2.append(df2)

plt.figure()
sns.barplot(x = 'group index', y = 'std dev', data = DS1)

plt.figure()
sns.barplot(x = 'group index', y = 'std dev', data = DS2)
```
# **Output**
![截屏2020-09-17 21 33 55](https://user-images.githubusercontent.com/34256653/93477363-847f4800-f92d-11ea-922e-6407ee9cf8d8.png)

The results are quite confusing to me and I cannot find answer elsewhere. I'll be appreciated if you could tell me if it is a bug or something else.

Thank you!

**Comment by mwaskom** [comment]
I wasn't able to run your exact code (`data` wasn't defined) but running a similar example with the latest versions of matplotlib and seaborn produce the expected plot. I think this is a matplotlib issue that's been reported before if you search around, and I bet you can reproduce it by using `plt.bar` rather than `sns.barplot`.

**Comment by YAMWD** [comment]
Yes I can reproduce it by using plt.bar. It's a bug in matplotlib indeed. Thank you for your nice response!
