### ISSUE TITLE
facet and displot error?

### ISSUE THREAD

**Issue by amazongodman** [mwaskom/seaborn#2288]
```
df = sns.load_dataset("penguins")

g=sns.FacetGrid(df,col='species')
g.map_dataframe(sns.displot,'flipper_length_mm')
```

```
df = sns.load_dataset("penguins")

g=sns.FacetGrid(df,col='species')
g.map(sns.displot,'flipper_length_mm')
```

![image](https://user-images.githubusercontent.com/52575713/93543666-1e2f0f80-f997-11ea-9693-f785ef93504d.png)

how should I fix code??

**Comment by mwaskom** [comment]
This is expected behavior. If it confuses you, I would read this section of the docs: http://seaborn.pydata.org/tutorial/function_overview.html#figure-level-vs-axes-level-functions

**Comment by amazongodman** [comment]
@mwaskom 
thank you. I read that.
"figure level" are not dealing with [ FacetGrid→map ]. (just axes level)
Seaborn is wonderful !

**Comment by mwaskom** [comment]
Yes but I think you missed the point that the FacetGrid is used inside of distplot. You can just do `displot(..., col="species")`. There are several [examples here](https://seaborn.pydata.org/generated/seaborn.displot.html).
