### ISSUE TITLE
Import seaborn as ??

### ISSUE THREAD

**Issue by 8one6** [mwaskom/seaborn#229]
Not an issue, just a question from an enthusiastic user.  You seem to like

```
import seaborn as sns
```

as your import style.  When you type that, what is the voice in your head saying out loud?  I had generally been importing as `sbn` since it "sounded right".

**Comment by 0Antact1** [comment]
Can anyone share what the joke is with sns?

**Comment by vaibhav2304** [comment]
> Not an issue, just a question from an enthusiastic user. You seem to like
> 
> ```
> import seaborn as sns
> ```
> 
> as your import style. When you type that, what is the voice in your head saying out loud? I had generally been importing as `sbn` since it "sounded right".

Official Seaborn website, "sns" can be interpreted as “Seaborn Name Spac
