### ISSUE TITLE
sns.color_palette TypeError: 'ListedColormap' object is not iterable

### ISSUE THREAD

**Issue by francois-a** [mwaskom/seaborn#2290]
Hi,

The following returns an error with v0.11.0 and matplotlib 3.3.2:
```Python
sns.color_palette("Set1", desat=0.8, as_cmap=True)
```
```Python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-88477157fd6b> in <module>
----> 1 sns.color_palette("Set1", desat=0.8, as_cmap=True)

.../site-packages/seaborn/palettes.py in color_palette(palette, n_colors, desat, as_cmap)
    209 
    210     if desat is not None:
--> 211         palette = [desaturate(c, desat) for c in palette]
    212 
    213     if not as_cmap:

TypeError: 'ListedColormap' object is not iterable
```
It works fine with `as_cmap=False`.

**Comment by mwaskom** [comment]
Hm, some corner case in the key handling, but what are you expecting to do with `Set1` as a colormap object? That's a categorical colormap and numeric lookup with it doesn't make much sense.

But anyway, you can get it through matplotlib with `plt.get_cmap("Set1")`.

**Comment by francois-a** [comment]
Thanks -- I wanted to get the hex values from this. I agree, there are other ways to get this, just thought I'd report the error.

**Comment by mwaskom** [comment]
Hex values:

```python
print(sns.color_palette("Set1", desat=0.8).as_hex())
```
```
['#d02e30', '#447dab', '#56a554', '#92569a', '#e67f19', '#ebeb47', '#995935', '#eb8dbe', '#999999']
```

**Comment by francois-a** [comment]
Thanks, I had figured that out -- I had simply encountered this error when first running the function. Closing this for now.
