### ISSUE TITLE
Feature Request: Add ability to turn off bootstrapping for confidence intervals

### ISSUE THREAD

**Issue by mhamilton723** [mwaskom/seaborn#2291]
This bootstrapping is not well documented in the developer docs and can catch folks by surprise. Also many times people are interested in the empirical confidence intervals for things like error bands. Can you add a setting to use these empirical quantiles instead of bootstrapped uncertaities for the measure of center? Thanks!

**Comment by mwaskom** [comment]
Something like this is on the roadmap...
