### ISSUE TITLE
Erroneous zero variance assertion leads to skipping of density estimation in kde/histplots

### ISSUE THREAD

**Issue by ashafti** [mwaskom/seaborn#2294]
I'm running on seaborn 0.11.0, matplotlib 3.1.3, on jupyter notebooks.
I have come across this bug where the data is being mistakenly assumed as zero variance just because it consists of small values, and therefore seaborn skips making kde plots for it. My data is in the 1e-5 range of numbers, and gets a positive zero-variance 
assertion, as the check in line 303 of distributions.py is relying on np.isclose:
https://github.com/mwaskom/seaborn/blob/211cabb09bb9228635bdd80f74f7591d36d7b2a7/seaborn/distributions.py#L303

A simple way to recreate this:
`import seaborn as sns`
`data = [-5e-5,-3e-5,-1e-5,2e-5,4e-5,6e-5]`
`sns.kdeplot(data)`

You should get the zero-variance warning and no plot. Change the e-5 to e-4, and you get a kde plot.
I'm commenting the zero-variance check in the source for now just to get my plots done quickly, but a more robust check should probably replace this.

**Comment by mwaskom** [comment]
Possibly related: https://github.com/numpy/numpy/issues/10161

and indeed

```python
import math, numpy as np
data = [-5e-5,-3e-5,-1e-5,2e-5,4e-5,6e-5]
math.isclose(np.var(data), 0)
```
```
False
```
