### ISSUE TITLE
Unreadable Segment in Docs

### ISSUE THREAD

**Issue by entangledloops** [mwaskom/seaborn#2296]
Not sure if this is the right place to file a bug, but here is a quote taken from [this](http://seaborn.pydata.org/tutorial/color_palettes.html) page:

> But the plot on the right does not a grayscale colormap. Its colorfulness it more interesting, and the subtle hue variation increases the perceptual distance between two values, making small differencess slightly easier to resolve.

Note the missing words(s) in sentence one, the use of "colorfulness", and the misspelling of "differences". Also not clear what "its" applies to in that context---the heatmap or the colormap?

(There is also other minor awkward phrasing and misuse of grammar on that page, but this is the most obvious error.)

**Comment by mwaskom** [comment]
I'm sorry that you are unable to read text with minor typos. But a simple google search would show you  that "colorfulness" is a word.
