### ISSUE TITLE
pointplot add legend argument

### ISSUE THREAD

**Issue by JoElfner** [mwaskom/seaborn#2297]
pointplot is a great tool, but sometimes a legend is not needed when `hue` is set. If adding other explanatory information afterwards, like f.i. mean lines and wanting to add a legend for these parts, the legend labels and handels are already crowded by the pointplot hue labels/handles. 
Thus I propose introducing a `legend` argument in the pointplot API, which simply accepts a bool and defaults to `legend=True`. This argument should be only applicable, if `hue` is set. The implementation could be fairly easy by simply setting `label=hue_level if self.legend else None` in [line 1781](https://github.com/mwaskom/seaborn/blob/211cabb09bb9228635bdd80f74f7591d36d7b2a7/seaborn/categorical.py#L1781) and [line L378](https://github.com/mwaskom/seaborn/blob/211cabb09bb9228635bdd80f74f7591d36d7b2a7/seaborn/categorical.py#L378) to `if self.hue_names is not None and self.legend:`.

This [SO question](https://stackoverflow.com/questions/64042958/remove-legend-handles-and-labels-completely) emerged from pointplot with hue always producing a legend. (Even though the example is using a lineplot).

**Comment by mwaskom** [comment]
Yes this should exist but needs to be added to all categorical plots at the same time, after they are refactored to use the core code.

**Comment by JoElfner** [comment]
Yeah, thanks for closing this right away. So if this *should exist*, a good place would be on the wishlist to avoid forgetting it...

**Comment by mwaskom** [comment]
Thank you for your suggestions on how I should organize my TODO list, however, my approach works for me. Thanks again.

**Comment by JoElfner** [comment]
You are welcome and feel free to contact me, if you need further advice.
Putting aside the sarcasm: My last answer was an indirect way of complaining about your, probably socially not very "competent", way of "answering", resp. simply closing, this issue/feature request. Just a single additional line in your answer and a slightly nicer behaviour could have nudged me to helping with the refactoring...
