### ISSUE TITLE
Error while trying to build documentation locally

### ISSUE THREAD

**Issue by danieltomasz** [mwaskom/seaborn#2298]
I am on macOS Catlina 10.15.5
While I try to build the documentation locally (`make html`)
I am getting an error:
```
running /Users/daniel/Downloads/seaborn-master/examples/logistic_regression.py

Extension error:
Handler <function main at 0x12c3efa60> for event 'builder-inited' threw an exception
make: *** [html] Error 2
```
Unfortunately, sphinx is rather cryptic what this is about.

**Comment by mwaskom** [comment]
I'm not sure, sorry. The doc builds are pinned on a specific version of sphinx. Aside from documenting my workflow for building the docs, I don't have much insight into debugging sphinx issues.

**Comment by danieltomasz** [comment]
Thanks, I will try to build it using exact requirements!

**Comment by mwaskom** [comment]
You can also invoke sphinx directly and I think it has some options for increasing verbosity if you do so, but again I'm not an expert there ... any time I've had to debug some sphinx issue I basically just try random things until it seems to work...

**Comment by mwaskom** [comment]
btw if building locally to look at docs for older versions, that should no longer be necessary: https://seaborn.pydata.org/archive.html

**Comment by danieltomasz** [comment]
I try to build the docset  of  latest seaborn for Dash

**Comment by mwaskom** [comment]
do you just need html files for that? you can get the files for the site here: https://github.com/seaborn/seaborn.github.io

**Comment by danieltomasz** [comment]
Thanks for your help! I was able to use it to build documentation for Dash (meantime I found user-contributed dash docset for latest seaborn )!

I will come back to his issue, I want to build the documentation locally  using sphinx epub theme, this is slightly easiest to navigate inside Dash, but for now, I am closing this
