### ISSUE TITLE
displot

### ISSUE THREAD

**Issue by onaclov2000** [mwaskom/seaborn#2299]
I'll be honest I'm not sure if this is the right place to post this, however I searched for displot in the issues list and don't see it.

The docs appear to say "displot" when they mean to say "distplot" (I think).

When trying to use displot seaborn errors out and says the attribute doesn't exist, however distplot appears to exist.

https://seaborn.pydata.org/generated/seaborn.displot.html

```python
AttributeError: module 'seaborn' has no attribute 'displot'
```

**Comment by mwaskom** [comment]
`displot` is a new function added in version 0.11. There is an older function `distplot`, [that it replaces](https://seaborn.pydata.org/whatsnew.html#deprecations). The similarity in names is regrettable but was chosen carefully as the best course of action.
