### ISSUE TITLE
module 'seaborn' has no attribute 'set_theme'

### ISSUE THREAD

**Issue by WangMengqi32C** [mwaskom/seaborn#2301]
Dear all,

It's a very weird error that the set_theme function cannot be found.
could anybody tell me how to fix it?
![image](https://user-images.githubusercontent.com/37926759/94258132-acbe0680-ff2c-11ea-834e-7a80665d63dd.png)
Thank you in advance

Best regards,
Mengqi

**Comment by mwaskom** [comment]
That function was added in v0.11, and you are likely using an older version. It is actually a (more explicit) alias for the function `seaborn.set`, which can also be used.

**Comment by WangMengqi32C** [comment]
Thank you! @mwaskom

**Comment by hkb111** [comment]
Thank you @mwaskom 
Can updating the seaborn help me to get rid of this error?

**Comment by mwaskom** [comment]
yes, or see my response to this issue...
