### ISSUE TITLE
Access best fit parameters with regplot ?

### ISSUE THREAD

**Issue by neutrinoceros** [mwaskom/seaborn#2303]
`regplot` is extremely useful and versatile. However, I cannot find a proper way to extract the resulting best-fit parameters or display them for further use without replicating its internal operations at the user level.

Since `regplot` returns a `matplotlib.axes.Axis` instance instead of the internal `_RegressionPlot` instance used to perform the regression, I can't think of a satisfying solution to expose the result.

**Comment by mwaskom** [comment]
You should replicate the internal operations — doing so is a single line of statsmodels code, and gives you access to all of the relevant coefficient estimates and inferential statistics (which seaborn does not compute).
