### ISSUE TITLE
Cannot use annotate on JointGrid

### ISSUE THREAD

**Issue by ironerumi** [mwaskom/seaborn#2306]
Hi, it is kind of related to #1873, I'm using seaborn *0.11.0*, when I trying to annotate, 
```
j = sns.jointplot(feat_1, feat_2, data=X_train, kind="kde", color="r", space=0)
j.annotate(stats.pearsonr,frameon=False)
```
the following error occurred
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-52199c4ff320> in <module>
      5 j = sns.jointplot(feat_1, feat_2, data=X_train,
      6                       kind="kde", color="r", space=0)
----> 7 j.annotate(stats.pearsonr,frameon=False)
      8 
      9 graph.x = X_train[feat_1]

AttributeError: 'JointGrid' object has no attribute 'annotate'
```
Is there an alternative to add annotations to JointGrid?
Many thanks!

**Comment by mwaskom** [comment]
Indeed, that method was deprecated (in 0.9) and [removed](http://seaborn.pydata.org/whatsnew.html#deprecations-and-removals) (in 0.11).

You can add arbitrary text to matplotlib figures; use `JointGrid.ax_joint.text` to do so.

**Comment by seralouk** [comment]
How can I get this  (https://stackoverflow.com/questions/31568874/how-to-change-the-line-color-in-seaborn-linear-regression-jointplot)  using the new version ??
