### ISSUE TITLE
Time series heat map - new plot type?

### ISSUE THREAD

**Issue by ecotner** [mwaskom/seaborn#2308]
I brought this proposal to `matplotlib` earlier (https://github.com/matplotlib/matplotlib/issues/18643) but it didn't sound like a good fit. The proposed enhancement was more of a re-casting of one plot type (`hist2d`) to be used in scenarios where a different one (`plot`) is the standard, rather than a new fundamental plot type, and therefore not general enough for inclusion in the library. One contributor recommended seeing if it might fit here in `seaborn` since the API is a little more high-level and aims at building off `matplotlib` without having to slog through the details. I will just copy/paste the proposal here:

### Problem

A while back I was working on a project that involves a bit of time series segmentation/clustering, and found it difficult to visualize my clusters in the "standard" way, which involved simply using `plt.plot` for each series in my data set and setting `alpha` to some really low number. I had tens of thousands of such series, and besides taking a long time to run through the loop of plotting some small subsample (plotting everything this way takes an agonizing amount of time), the other major drawback was that apparently there is a lower limit to `alpha` of `1/256`, below which nothing would show up. Even with the setting this low, layering large numbers of time series on top of each other just leads to a solid slab of color that makes it difficult to visualize. Yet another factor is that time series with large slopes (both positive and negative) contribute more heavily than series with small slopes to the color of the plot.

### Proposed Solution

I came up with what I think is a fairly nice solution, which is instead of plotting the time series as stacked line plots, to plot them as 2D histograms where each bin counts the number of (potentially _interpolated_) points that fall in that region. This has a number of advantages:
1. way faster than stacking line plots because there is only a single artist being drawn
2. much more flexible color scheme; colors are automatically normalized or can be changed to represent a log scale, etc.
2. color scheme is actually indicative of the density of points and does not suffer from the bias of time series with high/low slopes

I managed to save the code and kind of forgot about it until now, I have it in a repo [here](https://github.com/ecotner/visualizations/blob/master/timeseries_heatmap/timeseries_heatmap.py). There is probably a good deal of improvement that can be done, especially with regards to interpolation techniques.

### Additional context and prior art

These are some old plots from over a year ago, so I don't have access to the data anymore, but you can probably recreate something similar with the code from the repo linked above. Here are some comparisons of the heat map method (left) and standard stacked line plot (right) on some randomly generated toy data:

![ts_heatmap_comparison_log_scale](https://user-images.githubusercontent.com/10482181/94981910-22653c00-0504-11eb-9e75-01507bae1b3c.png)

![ts_heatmap_comparison](https://user-images.githubusercontent.com/10482181/94981912-25f8c300-0504-11eb-8c3e-7e5f7174e1c9.png)

An example of same data with different color schemes:

![ts_density_color_schemes](https://user-images.githubusercontent.com/10482181/94981941-8851c380-0504-11eb-9f6d-6dbe2f0769c6.png)

And here are some of the clusters that I was able to find in my data set at the time:

![2019-05-21_cluster_time_series_heatmap](https://user-images.githubusercontent.com/10482181/94982072-948a5080-0505-11eb-9f67-31f6b99584c2.png)

Unfortunately I don't think I'm at liberty to divulge what the data actually represents, but it's monthly data, and you can see that there is a bit of interpolation going on between months in order to give it a more "continuous" look.

So, what do you think? Would this be a helpful new plot type? It's basically built on top of pre-existing plot types, so it is probably not too difficult to implement!

**Comment by mwaskom** [comment]
If I'm understanding correctly, I think that [datashader](https://datashader.org/) already does this?

**Comment by ecotner** [comment]
Oh, I've never heard of `datashader` before; interesting! You're right, it looks like that package already has a utility for [plotting large numbers of timeseries](https://datashader.org/user_guide/Timeseries.html#Plotting-large-numbers-of-time-series-together). I don't suppose you have any appetite to create a similar utility for `seaborn` using just `matplotlib`?

**Comment by ecotner** [comment]
yeah that makes sense
