### ISSUE TITLE
Can the CI value calculated in the chart be marked with specific values?

### ISSUE THREAD

**Issue by antecede** [mwaskom/seaborn#2309]
For example, when CI=95 in Barplot, can the upper and lower limits be marked?
And the mean value calculated by estimator, can it be shown?
The best way to export through a certain way, easy to cite and explain in the paper.
Hopefully these features will be implemented.
Also if you can through the way of assignment to barplot charts indicate the extra CI value (because seaborn CI value calculation and R in certain function results are different, but in the paper by R function computation will be convenient reference and instructions, if seaborn can sort out the corresponding formula, also will be convenient for scientists to use) it would be better.

**Comment by mwaskom** [comment]
I’m not sure what you mean.

**Comment by antecede** [comment]
> Do you mean by adding numbers to the plot?

Yes, add numbers of the upper and lower limits of the error bar.

**Comment by antecede** [comment]
![傲游截图20201007093652](https://user-images.githubusercontent.com/46232487/95277601-c5111800-0880-11eb-855b-f795491d50d8.jpg)
just like this, but the numbers are marked by myself.

**Comment by mwaskom** [comment]
It's a functionality that I believe pretty strongly should live outside of seaborn. If you look on StackOverflow, you'll find good answers for how to do this with matplotlib.

**Comment by antecede** [comment]
> matplotlib

I mean, when I looked at the following source code, CI=95, Seaborn performed this operation using bootstrap method. Is this related to the matplotlib display value?
I also used dir() to look at the available methods, and found nothing related to calculating CI values.
Personal stupidity also look to your guidance.

**Comment by antecede** [comment]
find out  categorical.py and then search for self.confint.
and you will get the CI.
