### ISSUE TITLE
AttributeError : Seaborn

### ISSUE THREAD

**Issue by hkb111** [mwaskom/seaborn#2310]
sns.set_theme(style="ticks")
sns.pairplot(df)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-102-2c212b079315> in <module>
----> 1 sns.set_theme(style="ticks")
      2 sns.pairplot(df)

**AttributeError: module 'seaborn' has no attribute 'set_theme'**

I have got this error while using seaborn.

**Comment by mwaskom** [comment]
Duplicate of #2301
