### ISSUE TITLE
sns.pairplot function have scalling issues in diagonal plots

### ISSUE THREAD

**Issue by xiangshiyin** [mwaskom/seaborn#2314]
* Seaborn version: 0.11.0
* Issue: the scale of the histogram isn't right when I call the function and specify `diag_kind` to be `hist`
* Here are the code I tested:
    * Code 1: produces the right scale in the histograms
    ```python
    import seaborn as sns
    tips = sns.load_dataset('tips')
    sns.pairplot(tips)    
    ```
    * Code 2: when I change the pairplot setting to something below, the scale of the vertical axis shrinks and it's not right any more
    ```python
    sns.pairplot(tips, diag_kind='hist') 
    ```
* According to the documentation (https://seaborn.pydata.org/generated/seaborn.pairplot.html) and the source code (https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L1822). The two code should produce the same histograms. Can anyone take a look? Thanks!

**Comment by mwaskom** [comment]
The relevant line is here: https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L1924
