### ISSUE TITLE
Stripplot plots wrong dates on x axis

### ISSUE THREAD

**Issue by pow4all** [mwaskom/seaborn#2315]
Seaborn version 0.11.0, Matplotlib version 3.3.1, Pandas version 1.1.2

Code which creates weird dates on x axis:

```
# import needed libraries
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns

# create dump dataframe
t = {'Time': ['2020.10.02 14:25:49.725', '2020.10.02 02:25:07.921', '2020.10.01 16:53:40.531']}
df = pd.DataFrame(t)
df['Category'] = ['A', 'B', 'C']

# convert to timestamp
df['Time'] = pd.to_datetime(df['Time'], format='%Y.%m.%d %H:%M:%S.%f')

# create stripplot
fig, ax = plt.subplots()
sns.stripplot(x='Time', y='Category', data=df, ax=ax)
ax.xaxis.set_major_formatter(mdates.DateFormatter('%d.%m.%Y %H:%M'))
plt.show()

```
Which creates a stripplot with dates from January 1st to January 3rd 1970.
What's wrong here?

When x- and y-axis are being switched it works as expected:
```
sns.stripplot(y='Time', x='Category', data=df, ax=ax)
ax.yaxis.set_major_formatter(mdates.DateFormatter('%d.%m.%Y %H:%M'))
```
Also `sns.histplot()` and `sns.lineplot()` work as expected.

**Comment by mwaskom** [comment]
The categorical plots use ordinal positions (0, 1, ...) on the categorical axis and then set string labels (i.e. with a `FixedFormetter`) so if you just change the formatter after plotting, the original date information is no longer present.

**Comment by mwaskom** [comment]
I'm going to close this because while annoying, this is working as expected (and as well as can be currently expected given how these functions and matplotlib ticks work).

**Comment by pow4all** [comment]
Sorry I was busy the last days...

I needed a while but now I think I understand your answer and the way these functions works.
The x-axis is the categorical axis as long as the arguement `orient='v'` (default) is not changed. The orientation of the plot can not be changed by swapping only x- and y- data. But `orient='h'` is also needed.

So everything good, thanks for the answer and this great library.
