### ISSUE TITLE
Categorical variable with numerical classes incorrectly plotted only on y axis

### ISSUE THREAD

**Issue by enricogandini** [mwaskom/seaborn#2317]
Dear All,

I think I may have found a bug in Seaborn categorical plotting functions.
If a DataFrame column contains numbers, and it is explicitely converted to CategoricalDType, it will be correctly treated as categorical by functions such as boxplot only if it is passed to `x` argument.
If it is instead passed to `y` argument of the plotting function, it will be treated as numerical, and the other variable will be treated as categorical (even though the other variable is obviously numerical).

I am using Python 3.7, Matplotlib 3.3.1, Seaborn 0.11, Numpy 1.19.1, and Pandas 1.1.1 .
I am using Matplotlib backend: 'module://ipykernel.pylab.backend_inline'

Reproducible code:
```python

#Create DataFrame with a numerical column, and a categorical column with number as classes.
n_points = 50

df = pd.DataFrame({"value": np.random.rand(n_points),
                   "class": np.random.randint(0, 2, n_points),
                   })

#Explicitely set `class` column to categorical data type.
df["class"] = df["class"].astype("category")

#If `class` column is passed to `x` argument, the plot is correct: column is treated as categorical.
sns.boxplot(data=df,
            x="class",
            y="value",
            );

#BUG: If `class` column is passed to `y` argument, the plot is incorrect: `class` is treated as numerical!
sns.boxplot(data=df,
            x="value",
            y="class",
            );

```

Please take a look at
[bug_categorical_numbers.pdf](https://github.com/mwaskom/seaborn/files/5371402/bug_categorical_numbers.pdf)
 the attached PDF file with the correct and wrong plots.

**Comment by mwaskom** [comment]
The issue is that "binary/boolean" variables (i.e. those with only 0s and 1s) get some special handling depending on the context they're used in — sometimes they're treated as numeric and sometimes as categorical — and currently that has precedence over treating variables with an explicit categorical dtype as categorical. I think that's wrong.

In the meantime, you can force the orientation with `orient="h"`.

**Comment by enricogandini** [comment]
Thanks for your answer!

Yes, using `orient="h"` solves the problem:
```python
#Produces horizontal box plots.
sns.boxplot(data=df,
            y="class",
            x="value",
            orient="h",
            );
```

And this issue only appears if the categorical column with numbers is binary, with only 0 and 1.
If other numbers are present, the plotting functions work well!
```python
df["multi_class"] = np.random.randint(0, 4, n_points)
df["multi_class"] = df["multi_class"].astype("category")

#Just fine!
sns.boxplot(data=df,
            x="multi_class",
            y="value",
            );

#Also just fine!
sns.boxplot(data=df,
            y="multi_class",
            x="value",
            );
```

**Comment by Hope90** [comment]
sns.boxplot(data=df, x='Phi (%)', y="Burial_mean", showmeans=True, orient ="h", palette="seismic")

Im using this code to plot a boxplot.
My X and Y axis are both numerical data.
However, in the plot, my y-axis is converted to categorical groups.
This is to say, that my true y-axis should be 1000~2000, for example.
But the y-axis in the plot is from 1 to 7 (the boxplot group my data).
This is not what I want.
And I don't find a solution to keep my y-axis as it is.
Do you have any idea to solve this problem? To keep the axis as numerical?
Thanks!
