### ISSUE TITLE
Order in "data=" is reversed to the order in Axes.get_lines()

### ISSUE THREAD

**Issue by lzixuan** [mwaskom/seaborn#2318]
I recently tried to customized the legend and linestyles in seaborn graphs using `get_lines().set_xxx`, and found that the list returned by `get_lines()` is reversed to the columns in `data`, for example,
```
penguins = sns.load_dataset("penguins")  
billDf = penguins.filter(like="bill_", axis="columns")  
g = sns.ecdfplot(data=billDf)
```
The two columns in `billDf` are "bill_length_mm" and "bill_depth_mm". In this case `g.get_lines()[0]` corresponds to the second column and `g.get_lines()[1]` corresponds to the first column, which is reversed to the order of `data` and `g.legend_.texts`.

This is a little confusing. Is it an intentional design? I'm using seaborn 0.11.0 with matplotlib 3.1.3. Thanks.

**Comment by mwaskom** [comment]
This is intentional ... the idea is that it felt more intuitive to have the ordering of the elements such that the first category in the legend is on “top” of the plot. But maybe more confusing than helpful...

**Comment by lzixuan** [comment]
Thanks for the reply. It's understandable. I encountered this when I tried to modify the linestyles in an `ecdfplot` and created a new legend myself with `get_lines()` and customized labels. Maybe directly modifying the label texts and linestyles in the initial legend is a more common workaround?

**Comment by mwaskom** [comment]
Either would work and I'm not sure if there's a strong case for one or the other.

**Comment by mwaskom** [comment]
Closing as this is fully expected and easy to adapt to, albeit initially surprising.
