### ISSUE TITLE
weighted kernel density estimation doesnt seem to work

### ISSUE THREAD

**Issue by luistelmocosta** [mwaskom/seaborn#2321]
Hello, I have the following arrays:

```
x_coord = [24.674999999999997,
  54.285000000000004,
  84.315,
  81.58500000000001,
  69.92999999999999,
  80.325,
  74.97000000000001,
  74.865,
  90.19500000000001,
  38.85,
  64.05,
  67.2,
  61.425,
  31.605,
  65.52,
  86.72999999999999,
  61.31999999999999,
  73.815,
  59.21999999999999,
  64.365,
  20.580000000000002,
  48.72,
  76.335,
  66.465,
  66.15,
  81.58500000000001,
  80.745]

y_coord =  [52.7,
  63.852000000000004,
  60.52,
  46.988,
  63.376000000000005,
  33.116,
  50.66,
  40.391999999999996,
  43.996,
  55.964,
  63.24,
  63.376000000000005,
  64.872,
  44.472,
  63.647999999999996,
  56.168,
  65.89200000000001,
  51.74799999999999,
  65.14399999999999,
  64.25999999999999,
  50.048,
  64.804,
  65.688,
  39.916000000000004,
  56.507999999999996,
  37.876000000000005,
  53.108]

weights = [0.0020265490494627836,
  -0.0014322686602204412,
  0.002867157040368752,
  -0.014638859741903633,
  -0.0032172289809662136,
  0.08183101306641648,
  0.0035802965322514167,
  0.0058146202491077895,
  0.050434501258960054,
  -0.0025212105917295415,
  -0.004080343147487328,
  0.0033914283684603024,
  -0.005429858252489959,
  -0.0005305772535393449,
  7.624078982926621e-05,
  -0.004417667261086215,
  -0.0038632514043518,
  -0.0027590421020683292,
  -0.0002216990476137798,
  0.0008887292156925762,
  -0.001602437150386311,
  0.0006995805447187146,
  -0.0012508305471990479,
  0.0012125417784978124,
  0.004637121390552019,
  -0.0010159761867512551,
  -0.006461630433374176]
```

And I am using KDE with weights to plot these values but the wights dont seem to have much of an impact in the result.

```
fig, ax = plt.subplots()
fig.set_size_inches(7, 5)

sns.kdeplot(x_coord, y_coord, shade = True, color = "red", n_levels = 10, \
            weights=weights, \
            shade_lowest=False, \
           zorder=14, alpha=0.2)
```

Result

With weights:

![image](https://user-images.githubusercontent.com/7799750/96156384-e7520800-0f08-11eb-9f30-d53e5c9ab544.png)

Without:

![image](https://user-images.githubusercontent.com/7799750/96156402-efaa4300-0f08-11eb-9442-41614cfab5b4.png)

Any possible reason for this to happen? 

Regards, 

Luís

**Comment by mwaskom** [comment]
When I run your code, I get an error from numpy because there are negative values in your weight vector.

I suspect that you are using an old version of seaborn that predates support for weights. The underlying matplotlib function, `contourf` doesn't raise when it gets unexpected keyword arguments (but it does issue a warning that you should be seeing...)

**Comment by luistelmocosta** [comment]
The only warning I am getting is: 

`FutureWarning: Pass the following variable as a keyword arg: y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.` and I am using `0.11.0` version. 
But I tried with different weights. I generated a random `weights` array using:

`np.random.uniform(low=1, high=15, size=(len(x_coord),))` and I don't see any diference too.

Do you have any suggestion for the weights range, so I can normalize them?

**Comment by mwaskom** [comment]
The weights vector doesn't need to be normalized but it does need to be nonnegative. What version of numpy and scipy do you have?

**Comment by luistelmocosta** [comment]
Nevermind, it actually gives an error. I normalized the values from 0 to 1 and it is working fine. Don't know if it is the best approach but it is looking good.

Thank you for your help :)
