### ISSUE TITLE
seaborn.rcmod not found

### ISSUE THREAD

**Issue by vbucaj** [mwaskom/seaborn#2322]
`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-77512568bfd6> in <module>
      2 import numpy as np
      3 
----> 4 import seaborn as sns
      5 import matplotlib.pyplot as plt
      6 import matplotlib.patches as mpatches

~/.local/lib/python3.6/site-packages/seaborn/__init__.py in <module>
      1 # Import seaborn objects
----> 2 from .rcmod import *  # noqa: F401,F403
      3 from .utils import *  # noqa: F401,F403
      4 from .palettes import *  # noqa: F401,F403
      5 from .relational import *  # noqa: F401,F403

ModuleNotFoundError: No module named seaborn.rcmod`

I suddenly started getting the above error when importing seaborn.

**Comment by mwaskom** [comment]
Also what are you showing there?

**Comment by mwaskom** [comment]
Is it possible that you're created a local file called `seaborn.py`?

**Comment by vbucaj** [comment]
That is the error I get when trying to import seaborn. It is part of a docker image that I have created. It may be some conflict between the version installed from scikit-learn. I'm debugging it now and will update if the issue is resolved. Thanks.

**Comment by mwaskom** [comment]
I'm going to close this for now because it is very likely some specific issue with how you're setting up your image. The versions of seaborn available through github, pypi, and conda are not broken in this fashion. But ping if you have some evidence that there is a general problem...
