### ISSUE TITLE
Changing seaborn plot size

### ISSUE THREAD

**Issue by sarveshggn** [mwaskom/seaborn#2324]
I wanted to change the size of seaborn plot, so I used the following command:  
`
sns.set(rc={'figure.figsize':(11.7,8.27)})
`
Somehow it changed the settings for the whole file. I want to revert back to the original seaborn settings so is there any way for this.

**Comment by mwaskom** [comment]
http://seaborn.pydata.org/tutorial/function_overview.html#specifying-figure-sizes

**Comment by mwaskom** [comment]
This channel is for bug reports, in the future please ask usage questions on stackoverflow or discourse, as outlined [here](http://seaborn.pydata.org/installing.html#getting-help).
