### ISSUE TITLE
In a jointplot, hue and kind='hex' are mutually exclusive

### ISSUE THREAD

**Issue by HagaiHargil** [mwaskom/seaborn#2326]
```python

penguins = sns.load_dataset("penguins")
sns.jointplot(data=penguins, x="bill_length_mm", y="bill_depth_mm", hue="species")  # works
sns.jointplot(
  data=penguins, 
  x="bill_length_mm", 
  y="bill_depth_mm", 
  hue="species", 
  kind='hex'
)  # AttributeError: 'PolyCollection' object has no property 'hue'
```

Seems like the rest of the 'kind's work, and if I remove the 'hue' kwarg the plot works again.

**Comment by mwaskom** [comment]
`JointGrid` doesn't have any code to handle groupling/hue-mapping logic and so hue only works when the underlying axes-level functions support it. This is clearly documented in the [`JointGrid`](https://seaborn.pydata.org/generated/seaborn.JointGrid.html) docstring but may not be in `jointplot`.

**Comment by HagaiHargil** [comment]
Thanks for the quick reply!

I saw it in `JointGrid` some time after posting this issue, and I assumed that it means that `plt.hexbin` has no such logic. Honestly, though, I've been using seaborn and matplotlib for quite some time now (thanks BTW :smile:) and without the context I had from this issue I wouldn't have guessed the _actual_ meaning of that comment, i.e. the inability to use `kind='hex'` or `'reg'` (I think). Moreover, I know that it's technically possible to generate such a plot, albeit manually, and so that's what I did after coming here.

I'd be happy to contribute a 'fix' for future users that might fall into the same trap as I did:

1. Update `jointplot` and `JointGrid`'s docs to reflect the specific kinds of plots that don't work with the `hue` keyword.
2. Improve the error message - I didn't mention it in my submission, but the raised error is somewhere deep inside matplotlib and is not too helpful. I suggest to add a quick check inside seaborn's codebase that verifies that `hue` wasn't supplied with the improper `kind`s.
3. Anything else you may deem necessary.
