### ISSUE TITLE
kdeplot: ValueError: Could not interpret value '' for parameter `hue`

### ISSUE THREAD

**Issue by fteufel** [mwaskom/seaborn#2331]
Hi,

I'm facing a strange problem when trying to use kdeplot on a df.

This works: `sns.histplot(plot_df, x='normalized count', hue='Gentrification Status')`
![image](https://user-images.githubusercontent.com/56223326/96841878-9f713a80-144c-11eb-8cc3-1030101dad09.png)
And strangely, so does this:
`sns.displot(plot_df, x='normalized count', hue='Gentrification Status', kind='kde')`
![image](https://user-images.githubusercontent.com/56223326/96842016-d21b3300-144c-11eb-9ac4-d0a529bdcba3.png)

But when I really just want a kdeplot `sns.kdeplot(plot_df, x='normalized count', hue='Gentrification Status')` this happens:
```ValueError: Could not interpret value `Gentrification Status` for parameter `hue```

I'm totally clueless, any idea what might cause this behaviour?

Traceback
```
/usr/local/lib/python3.6/dist-packages/seaborn/_decorators.py in inner_f(*args, **kwargs)
     44             )
     45         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 46         return f(**kwargs)
     47     return inner_f
     48 

/usr/local/lib/python3.6/dist-packages/seaborn/distributions.py in kdeplot(x, y, shade, vertical, kernel, bw, gridsize, cut, clip, legend, cumulative, shade_lowest, cbar, cbar_ax, cbar_kws, ax, weights, hue, palette, hue_order, hue_norm, multiple, common_norm, common_grid, levels, thresh, bw_method, bw_adjust, log_scale, color, fill, data, data2, **kwargs)
   1698     p = _DistributionPlotter(
   1699         data=data,
-> 1700         variables=_DistributionPlotter.get_semantics(locals()),
   1701     )
   1702 

/usr/local/lib/python3.6/dist-packages/seaborn/distributions.py in __init__(self, data, variables)
    106     ):
    107 
--> 108         super().__init__(data=data, variables=variables)
    109 
    110     @property

/usr/local/lib/python3.6/dist-packages/seaborn/_core.py in __init__(self, data, variables)
    602     def __init__(self, data=None, variables={}):
    603 
--> 604         self.assign_variables(data, variables)
    605 
    606         for var, cls in self._semantic_mappings.items():

/usr/local/lib/python3.6/dist-packages/seaborn/_core.py in assign_variables(self, data, variables)
    666             self.input_format = "long"
    667             plot_data, variables = self._assign_variables_longform(
--> 668                 data, **variables,
    669             )
    670 

/usr/local/lib/python3.6/dist-packages/seaborn/_core.py in _assign_variables_longform(self, data, **kwargs)
    885                     # We don't know what this name means
    886                     err = f"Could not interpret value `{val}` for parameter `{key}`"
--> 887                     raise ValueError(err)
    888 
    889             else:
```

**Comment by MaozGelbart** [comment]
HI @fteufel , consult the [documentation](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) - unlike `displot`, `kdeplot`'s first parameter is the `x` vector, not the dataframe. Therefore the calls are not interchangeable. You should provide the dataframe using the `data` keyword argument.

**Comment by fteufel** [comment]
@MaozGelbart  Thanks a lot, I feel stupid now - looked at the docs a lot but never considered the order of the args. Any reason why it's different here from `histplot` and `ecdfplot`?

**Comment by MaozGelbart** [comment]
@fteufel see [here](https://seaborn.pydata.org/whatsnew.html#required-keyword-arguments).
