### ISSUE TITLE
get_lines() method for kdeplot returns a list of 0 Line2D objects when shade=True

### ISSUE THREAD

**Issue by voropaevv** [mwaskom/seaborn#2333]
### Description
`get_lines()` method for `kdeplot` returns **a list of 0 Line2D objects** when `shade=True`
But when `shade=False`, then the method `get_lines()` returns **a list of 1 Line2D objects**

### Expected Behaviour
`get_lines()` method for `kdeplot` should return a non-zero **list of Line2D objects** for any boolean value of `shade`

### Code Example
```python
import seaborn as sns
some_data = [1, 2, 3, 4, 5]
print(sns.kdeplot(some_data, shade=True).get_lines())
# return <a list of 0 Line2D objects>
```
### Versions
seaborn 0.11.0
matplotlib 3.3.2

**Comment by mwaskom** [comment]
This is intentional – a filled density is drawn with a `PolyCollection` and the "lines" are formed by the edges of the polygon. Mixing lines and polygons in matplotlib causes issues because they are drawn at different z orders.
