### ISSUE TITLE
map_offdiag for pairplot not showing any lines

### ISSUE THREAD

**Issue by jgreener64** [mwaskom/seaborn#2334]
I tried to recreate this example to add off diagonal lines to a pairplot: https://stackoverflow.com/a/48122198/4464887

The code is:
```python
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

def plot_unity(xdata, ydata, **kwargs):
    mn = min(xdata.min(), ydata.min())
    mx = max(xdata.max(), ydata.max())
    points = np.linspace(mn, mx, 100)
    plt.gca().plot(points, points, color='k', marker=None,
            linestyle='--', linewidth=1.0)

ds = sns.load_dataset('iris')
grid = sns.pairplot(ds)
grid.map_offdiag(plot_unity)
plt.savefig('test.png')
```

But the image produced doesn't show the off-diagonal lines present in the linked answer:
![image](https://user-images.githubusercontent.com/6620652/97183604-e2f1de80-1795-11eb-96fe-5c7cc47c8296.png)

Package versions are the latest releases:
Matplotlib 3.3.2
seaborn 0.11.0
Python 3.6.5

I am running on Windows and get the same output from the REPL, iPython and Jupyter Lab.

Thanks for a great library!

**Comment by mwaskom** [comment]
Duplicate of #2307?

**Comment by jgreener64** [comment]
Yes, exact duplicate. Did search briefly but missed that one. Fixed for now by downgrading. Thanks for the quick response.

**Comment by mwaskom** [comment]
Note also the easier workaround in that issue
