### ISSUE TITLE
histplot randomly switches bars without switching labels while using FacetGrid

### ISSUE THREAD

**Issue by alexkataev** [mwaskom/seaborn#2337]
So, I've illustrated the problem with the data from a titanic dataset:

```
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/07_Visualization/Titanic_Desaster/train.csv'
titanic = pd.read_csv(url)
titanic.set_index('PassengerId', inplace=True)
titanic.head(3)
```
<img width="957" alt="Screenshot 2020-10-26 at 22 46 50" src="https://user-images.githubusercontent.com/39487162/97220821-27ed3380-17dd-11eb-9611-52c1384ea661.png">

We want to see what share of males and females died or survived depending on a class level:

```
titanic.groupby(['Pclass', 'Sex', 'Survived'])[['Ticket']].count()
```

<img width="229" alt="Screenshot 2020-10-26 at 22 44 30" src="https://user-images.githubusercontent.com/39487162/97220893-418e7b00-17dd-11eb-8c52-35569b24b0a2.png">

Then we plot that data with `FacetGrid`:

```
g = sns.FacetGrid(data=titanic, col='Pclass', height=4)
g.map_dataframe(sns.histplot, 'Sex', hue='Survived', hue_order=[1, 0], 
                              multiple='stack', palette=['#e5c494', '#4c72b0']);
g.add_legend(labels=['Died', 'Survived'], title='Status');
<...>
```

<img width="945" alt="Screenshot 2020-10-27 at 21 10 04" src="https://user-images.githubusercontent.com/39487162/97345687-6c3f0900-189b-11eb-8918-754f5e3b016e.png">

Now we compare data on our graph with data from the table:

![with-annotations](https://user-images.githubusercontent.com/39487162/97345755-87117d80-189b-11eb-9a0f-daa4fea18276.png)

As you can see, table data match graph data only in the last case (3rd class passengers). For the 1st and 2nd classes the labels 'male' and 'female' should be switched.

**Comment by mwaskom** [comment]
This is basically the situation warned about in the big orange box on the [FacetGrid](https://seaborn.pydata.org/generated/seaborn.FacetGrid.html) docs.

When using `FacetGrid` directly, each axes-level plot is seeing only a subset of the `DataFrame` and so if it has to, e.g. work out the ordering of a categorical variable, it will do that in isolation for each plot.

The easiest thing to do is (as the warning suggests) to use `displot`, which handles the bookkeeping necessary to keep the plots synchronized across facets. If for some reason you refuse to do that, you could (I think) set your `Sex` column to have a categorical datatype with a defined ordering

**Comment by mwaskom** [comment]
closing as this is amply documented, even if not immediately intuitive
