### ISSUE TITLE
zorder of facetgrid .map_dataframe bug

### ISSUE THREAD

**Issue by m-beau** [mwaskom/seaborn#2339]
Hi,

I am trying to overlay two facetgrids representing the same dataset in different manners (more precisely, a pointplot showing the data in the background and the mean in the forefront).

Sadly, for some reason, it seems like the facet grid doesn't care about the order in which the two pointplots are mapped:

```
import seaborn as sns
tips = sns.load_dataset("tips")
tips['sample']=list(tips.index)
g=sns.FacetGrid(tips, col='sex', sharey=False, legend_out=False)
g.map_dataframe(sns.pointplot, x='time', y='total_bill', color='blue')
g.map_dataframe(sns.pointplot, x='time', y='total_bill', hue='sample', palette='gray')
```

and

```
import seaborn as sns
tips = sns.load_dataset("tips")
tips['sample']=list(tips.index)
g=sns.FacetGrid(tips, col='sex', sharey=False, legend_out=False)
g.map_dataframe(sns.pointplot, x='time', y='total_bill', hue='sample', palette='gray')
g.map_dataframe(sns.pointplot, x='time', y='total_bill', color='blue')
```

return exactly the same plot! (even though this is a shitty plot, in my case there would be lines between the gray points in the background - the point is that the order in which the blue and gray data are overlaid doesn't change even they are plotted in a different order.)

**Comment by mwaskom** [comment]
`pointplot` actually sets the zorder of its elements internally to work around a matplotlib issue where the line and point elements otherwise render improperly.

You could handle this by making a new dataframe, essentially by doubling what you have and making a column that gets set as `hue` identifying each observation once and then all of the datapoints that will get aggregated into the mean.

You could also use `lineplot` (which supports categorical x variables).

**Comment by m-beau** [comment]
Thanks a lot for your fast answer!

I can almost get it to work by using lineplot in combination with pointplot indeed:
```
g=sns.FacetGrid(data=corr_df, col='cell_type', palette='gray', legend_out=False, sharey=False)
g.map_dataframe(sns.lineplot, x='period', y='corr', hue='cellij', alpha=0.5, palette='gray')
g.map_dataframe(sns.pointplot, x='period', y='corr', ci='sd')
```
![Screenshot 2020-10-29 at 21 20 44](https://user-images.githubusercontent.com/25953361/97633899-bc99a080-1a2c-11eb-8ce7-faa428d95bf4.png)

But the pointplot scatter dot remains behind the lines from the lineplot. I guess that there is no easy way to work around the pointplot internal zorder is there?

**Comment by mwaskom** [comment]
In order of difficulty:

1) `lineplot` handles the matplotlib zorder kwarg properly so you could draw the individual observations at a zorder of .5 to put them under the aggregate (provided that you don't have a grid, or else it they'll be under that too)

2) you can draw the aggregate data with `lineplot` too by setting `err_style="bars"` and `marker=True`

3) you could dig into the matplotlib objects on the axes and set their z order attribute after seaborn plots them

**Comment by mwaskom** [comment]
FYI, relevant matplotlib issue to track: https://github.com/matplotlib/matplotlib/issues/17247

**Comment by mwaskom** [comment]
going to close this for now as seaborn is doing the best it can given the underlying constraints, i think

**Comment by m-beau** [comment]
Thank you so much, beautiful! You are helping a bunch of fellow
neuroscientists out there, we owe you a lot :)

Le ven. 30 oct. 2020 à 14:43, Michael Waskom <notifications@github.com> a
écrit :
