### ISSUE TITLE
Violinplot ignores hue when only y is specified

### ISSUE THREAD

**Issue by barskern** [mwaskom/seaborn#2340]
# Problem

When only `y` is specified to `violinplot` it does not consider the argument to `hue`.

```python
tips = sns.load_dataset("tips")
sns.violinplot(data=tips, y='total_bill', hue='smoker')
```
![bilde](https://user-images.githubusercontent.com/14995334/97690861-daebb480-1a9d-11eb-9681-f943e401bc0b.png)

# Expected

There should be created two plots, one where smoker is `yes` and one where smoker is `no`.

# Example when `x` is specified

```python
tips = sns.load_dataset("tips")
sns.violinplot(data=tips, x='day', y='total_bill', hue='smoker')
```
![bilde](https://user-images.githubusercontent.com/14995334/97691032-1c7c5f80-1a9e-11eb-9c12-43a710a4901f.png)

**Comment by mwaskom** [comment]
This is "expected" behavior on the seaborn (if not the user) side and is baked into the guts of the categorical plots. The docs describe the use of `hue` as "an additional level of nesting" for this reason. It's something I would like to change, but doing so will require a complete refactoring of the internals.

It is possible to work around it like so:

```python
tips = sns.load_dataset("tips")
sns.violinplot(data=tips, x=[""] * len(tips), y='total_bill', hue='smoker')
```

**Comment by barskern** [comment]
Thank you for the quick reply @mwaskom !

Ah okay, that's understandable. The value of the rewrite is perhaps small aswell, as I couldn't seem to find anyone else having the same issue. I will leave it up to you if you want to close this or leave it as a reminder that the functionality is wanted. 

Thank you for a great project and some beautiful graphs 😄

**Comment by mwaskom** [comment]
I'm going to close for now, but the refactoring is actually on the roadmap, hopefully for 0.12. There's now a pretty robust and very flexible core infrastructure, and it is just a matter of adapting the existing categorical functions to use it. It will provide other benefits beyond breaking the "hue is nested within x" constraint, but that's something that will naturally become possible.

**Comment by bjornasm** [comment]
> ```python
> x=[""] * len(tips)
> ```

Just stumbled upon this - might it be possible to display a warning when trying to plot without specifying x values, but having specified hue?
