### ISSUE TITLE
FacetGrid sharey='col' prevents non-left yticklabels

### ISSUE THREAD

**Issue by aaronspring** [mwaskom/seaborn#2346]
I want to use `FacetGrid` and only `sharey` across `col`umns (not rows). (I am not sure whether this is against the philosophy of faceting.) When doing so, I would expect to see yticklabels in the all rows, but dont find them. Is this a bug or intended?
I dont want to use `sharey=False`, because I want to compare the columns, e.g. having them on the same scale.

```python
import seaborn as sns
sns.__version__
'0.12.0.dev0'
df = sns.load_dataset("titanic")
```
What I get:
```python
sns.catplot(
    data=df, kind="point", sharex=True, sharey='col',
    x="class", y="fare", row='alive', col='sex')
```
![image](https://user-images.githubusercontent.com/12237157/98927219-8c480c80-24d8-11eb-9ccb-01a7f9f5b3a3.png)

What I'd expect:
```python
expected = sns.catplot(
    data=df, kind="point", sharex=True, sharey='col',
    x="class", y="fare", row='alive', col='sex')
for ax in expected.axes.flatten():
    ax.tick_params(labelleft=True)
```
![image](https://user-images.githubusercontent.com/12237157/98927388-c3b6b900-24d8-11eb-8cf3-300ded065a89.png)

What `plt` does:
```python
import matplotlib.pyplot as plt
plt.subplots(ncols=2,nrows=2,sharex=True, sharey='col')
```
![image](https://user-images.githubusercontent.com/12237157/98927452-d6c98900-24d8-11eb-9afd-bf8cdb5669a5.png)

**Comment by mwaskom** [comment]
It's a bug; [this check](https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L464) (and the corresponding one below it) should be more precise.
