### ISSUE TITLE
Stripplot: merge overlapping points when saving as a vector graphics

### ISSUE THREAD

**Issue by jankopanski** [mwaskom/seaborn#2357]
Is there a way to merge overlapping points in a scatterplot when saving it as a PDF file?

I have a couple of datasets. Each of them has several thousand entries. For each, I would like to create a scatterplot and save it as a vector graphics. Then include all of them into a PDF file generated with latex. The issue is that the file size of a single plot is too large. Saving a plot as a raster graphics solves the issue with file size, but then raster stripplots don't scale well. I may sample each dataset, but I would like to keep all outliers. So, for each of them individually, I would need to find a threshold for sampling.

**Comment by mwaskom** [comment]
All of the drawing/rendering/saving operations are handled by matplotlib so this is really a question for them.

I don't think this exact functionality exists (it feels familiar and has maybe been discussed), but you can rasterize specific elements of the graph while keeping everything else in vector format. So if you do `stripplot(..., rasterized=True)` and then set `dpi` to a large value when saving the figure, you may find that it gives a good balance between file size and image resolution.

**Comment by mwaskom** [comment]
> I may sample each dataset, but I would like to keep all outliers. 

BTW seems like you could just reduce the dataset to unique values within each category and you'd have the plot you want? Seems superior to purely random sampling.
