### ISSUE TITLE
xlim in heatmap with annotation not working properly

### ISSUE THREAD

**Issue by CoMartel** [mwaskom/seaborn#2358]
I would like to plot several heatmaps side by side, with annotations.

For this, I use subplots and I can plot each heatmap in its axes using the ax kwarg.

The issue is when I use xlim : it's applied to the heatmap, but not the annotation : 

[![shifted annotation when using xlim][1]][1]

Here is the code : 

    import numpy as np
    import matplotlib.pyplot as plt
    import seaborn as sns

    values = np.random.random((7,24)) # create (7,24) shape array 
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(30,10)) # create 2 columns for subplots
    
    ax1 = sns.heatmap(values, annot=True, ax=ax1) # heatmap with annotation
    
    ax1.set(xlim=(12,22)) # works fine with this line commented
    # ax1.set_xlim(12,22)

    # ax2 = sns.heatmap(values, annot=True, ax=ax2) # second heatmap
    
    plt.show()

And it gets worse with a second heatmap, because the annotation from the second heatmap are ploted on the first heatmap.

Versions :
 - matplotlib 2.2.2 
 - seaborn 0.9.0
 - python 3.6.5

I first asked about it on [Stackoverflow](https://stackoverflow.com/questions/64857244/set-xlim-in-heatmap-with-subplots-and-annotation), and one user reported the same bug on seaborn 0.11

  [1]: https://i.stack.imgur.com/KiM9E.png

**Comment by mwaskom** [comment]
matplotlib text objects are not automatically clipped when they are placed outside of the axes limits; you can turn that on by passing `annot_kws=dict(clip_on=True)` to `heatmap`, though.
