### ISSUE TITLE
Background griddoesn't have the same height at the borders

### ISSUE THREAD

**Issue by savus4** [mwaskom/seaborn#2361]
Hello seaborn-Team!

I found something which is probably a bug, although I am not sure if it belongs here or to matplotlib:

This is a plot which illustrates my problem:
![plot](https://user-images.githubusercontent.com/43091717/99779806-e585f080-2b15-11eb-8ae5-139b4911d31e.png)

I highlighted the issues with two red arrows. As you can see, the background of the background-grid is a bit lower at the border than in the rest of the chart.
I tried exporting it as png and as pdf, the issue stays the same.

Here is a code snippet to reproduce it:
(The styling with Latex is commented out, because the colum name __body_mass_g__ conflicts with it.)
```python
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.set_theme()
# tex_fonts = {
#     # Use LaTeX to write all text
#     "text.usetex": True,
#     "font.family": "DejaVu Sans",
# }
# plt.rcParams.update(tex_fonts)

data = sns.load_dataset("penguins")
# Add in points to show each observation
ax = sns.stripplot(x="body_mass_g", y="sex", data=data,
            size=4, color=".3", linewidth=0)
# Plot the orbital period with horizontal boxes
sns.boxplot(x="body_mass_g", y="sex", data=data,
            whis=[0, 100], width=.6, palette="vlag", ax=ax)

# Tweak the visual presentation
plt.tight_layout()
ax.set(ylabel="")
sns.despine(trim=True, left=True)
plt.show()
```

Seaborn version: 0.11.0
Matplotlib version: 3.1.2
Matplotlib backend: TkAgg

I hope I didn't forget anything. If yes, please just tell me.

**Comment by mwaskom** [comment]
What you are seeing are the axes spines, which are drawn in white but noticeable here because you called despine with trim=True, so they are drawn only between the outer ticks. That line isn’t really necessary when using this style, but if you want to keep it for some reason you should not trim the remaining spines.
