### ISSUE TITLE
distplot -> histplot weights fails with "wide-form data" error

### ISSUE THREAD

**Issue by michaelbrundage** [mwaskom/seaborn#2364]
I have precomputed histogram bin counts that I want to plot with seaborn. With the now-deprecated distplot, this works:

```py
sns.distplot(np.array([1, 2, 3, 4]), kde=False, bins=4,
             hist_kws=dict(weights=np.array([1, 3, 2, 1])))
```

With both `histplot` and `displot`, this fails:

```py
sns.histplot(np.array([1, 2, 3, 4]), kde=False, bins=4,
             weights=np.array([1, 3, 2, 1]))
```

Expected: same as distplot

Actual: ValueError: The following variable cannot be assigned with wide-form data: `weights`

**Comment by mwaskom** [comment]
You would need only do

> sns.histplot(x=np.array([1, 2, 3, 4]), bins=4, weights=np.array([1, 3, 2, 1]))

For this specific application, you may also find the `discrete` keyword useful.

**Comment by michaelbrundage** [comment]
Thanks. Wow, that's subtle -- I just missed the `x=` assignment.

**Comment by Gagan123313** [comment]
alueError: list.remove(x): x not in list
