### ISSUE TITLE
Inconsistency in color_palette function documentation

### ISSUE THREAD

**Issue by ernesto-elsaesser** [mwaskom/seaborn#2372]
The documentation states that 'hsl' is a valid palette identifier: https://github.com/mwaskom/seaborn/blob/607ded2cd65d98a93b09418b1523de71265f360d/seaborn/palettes.py#L99
whereas the code expects 'hls' for the HSL palette: https://github.com/mwaskom/seaborn/blob/607ded2cd65d98a93b09418b1523de71265f360d/seaborn/palettes.py#L164

**Comment by mwaskom** [comment]
Ah yes, I blame Python here ... "hsl" is the more conventional spelling but the `colorsys` module uses `hls` for some reason.
