### ISSUE TITLE
seaborn v 0.11.0 has no attribute lineplot

### ISSUE THREAD

**Issue by SergeyPenza** [mwaskom/seaborn#2374]
Good day:
I am using seaborn **Successfully installed seaborn-0.11.0.** When I am trying to run this:

```
import numpy as np
import pandas as pd
`import` seaborn as sns

class Graph(object):
    
    path = "D:\Works\someBinaryFile"

    def __init__(self):
        super(Graph, self).__init__()

    def plotChart(self):
        data = -32768+np.memmap( self.path, dtype=np.uint16, mode = 'r', offset = 1024, shape =(35000000, ) )
        df = pd.DataFrame(data)
        sns.lineplot('x', 'y', data=df)


if __name__ == "__main__":
    graph = Graph()
    graph.plotChart()
```        

Exception has occurred: AttributeError
module 'seaborn' has no attribute 'lineplot'
  File "C:\Users\...\LargeFile\seaborn.py", line 15, in plotChart
    sns.lineplot('x', 'y', data=df)

**Comment by mwaskom** [comment]
It looks like you've named a local file `seaborn.py`, and that's getting imported when you do `import seaborn as sns`. Change the name of that file and it should work.

**Comment by SergeyPenza** [comment]
Thanks!
