### ISSUE TITLE
How to handle datetime xtick labels in barplot properly?

### ISSUE THREAD

**Issue by ghuname** [mwaskom/seaborn#2381]
If I have a dataframe(s):

```
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

np.random.seed(62919)
df_w = pd.DataFrame({'A': [np.random.randint(15) for _ in range(48)],
                    'B': [np.random.randint(15) for _ in range(48)],
                    'dtime': pd.date_range(start='2020-01-01 08:00:00', freq='30T' ,periods=48)
                   })

df_l = df_w.melt(id_vars='dtime').sort_values('dtime')
df_l.head()
```

that looks like:

![image](https://user-images.githubusercontent.com/15207713/101983311-921d4300-3c7a-11eb-9532-b6664a01bda7.png)

I want to print two bars per time series data point (row). In order to do so I executed:

```
fig, ax = plt.subplots(figsize = (12,6))    
ax = sns.barplot(data = df_l, x = "dtime", y = 'value', ax=ax, hue='variable')
ax.set_xticklabels(ax.get_xticklabels(), rotation=30, ha='right');
```

which resulted with plot like this one:

![image](https://user-images.githubusercontent.com/15207713/101983388-1a9be380-3c7b-11eb-8f80-3c0921759ac2.png)

As you can see xticks labels are not recognized as datetimes.
First two xtick_labels look like:

`ax.get_xticklabels()[:2]`

```
[Text(0, 0, '2020-01-01T08:00:00.000000000'),
 Text(1, 0, '2020-01-01T08:30:00.000000000')]
```

Changing just type of plot from barplot to lineplot situation is completely different:

```
fig, ax = plt.subplots(figsize = (12,6))    
ax = sns.lineplot(data = df_l, x = "dtime", y = 'value', ax=ax, hue='variable')
```

![image](https://user-images.githubusercontent.com/15207713/101983471-82522e80-3c7b-11eb-86da-1278365a9830.png)

Now the first two xtick labels look like:

`ax.get_xticklabels()[:2]`

`[Text(18262.375, 0, '01-01 09'), Text(18262.5, 0, '01-01 12')]`

How to get auto formated xtick labels for the barplot graph in the same way as xtick labels are formated for the lineplot graph?
I have requirement to show multiple bars for a single date time (every 15 minutes, every hour...) at the same figure.
Barplot graph type looks the best for such purpose, but I don't know how to handle xtick labels.

As I workaround I ended up with this solution:

`ax.set_xticklabels(labels=pd.DataFrame(index=df_w.index).join(df_w.dtime[::4]).dtime.dt.strftime('%H:%M').fillna('').values);`

for showing every fourth `%H:%M` which resulted with the graph like this one:

![image](https://user-images.githubusercontent.com/15207713/101983609-6f8c2980-3c7c-11eb-9ce6-605b839483ce.png)

Still, I have an impression that I am misusing seaborn.
I saw that matplotlib has `matplotlib.ticker.MultipleLocator()` that can be used instead of `[::4]` that can simplify the situation a bit.

Please advice, how to handle datetime xtick labels in seaborn barplot properly?

**Comment by mwaskom** [comment]
There's not currently any way to do auto formatting of date ticks in barplot, as there's no facility for interaction in matplotlib between categorical positions and date formatters. This may be something that changes in the future, but for now your best bet is to post-process the ticklabels.

**Comment by ghuname** [comment]
@mwaskom Do you have a suggestion how to set ticklabels like this:

![image](https://user-images.githubusercontent.com/15207713/101987805-9a837700-3c96-11eb-9a85-a898e4cb972c.png)

As you can see there is a vertical white line when at midnight and at that position thick label is in two rows - centered:
00:00
10-Dec

How to get such tick labels?

When you said post-processing ticklabels, you meant that I should use matplotlib in order to manipulate ticklabels at wish?

Furthermore, is it possible to use logic for tick labels from line plot and use it on barplot?

**Comment by mwaskom** [comment]
You'll to look into how the matplotlib date formatter works. I imagine if you ask on stackoverflow someone will cook up a recipe for you. But you'll need to modify the ticklabels directly; the way the categorical plots work, the tick positions are integral and lose the datetime information the auto formatter needs to work.

My unsolicited suggestion would also be that a time series of dodged bars is very hard to read, and I would almost always use a lineplot in this situation anyway...

**Comment by ghuname** [comment]
You are right about how graph should look like, but I have a specific requirement so I have to do it exactly as pairs of barplots with time series x axis.
Thanks for a suggestion. I will try to figure out how to handle xtick labels manually.
Thank you very much for clarifying things.
Best regards.

**Comment by mwaskom** [comment]
BTW this is a hack, but I think I can make the plot you want using `histplot`:

```python
datenum = mpl.dates.date2num(df_l["dtime"])
binwidth = np.diff(datenum)[1]  # requires assumption about dataframe organization
binrange = (datenum.min() - binwidth / 2, datenum.max() + binwidth / 2)

fig, ax = plt.subplots(figsize = (12,6))

ax = sns.histplot(
    data=df_l,
    x="dtime", weights='value', hue='variable',
    multiple="dodge", shrink=.8, binwidth=binwidth, binrange=binrange,
    ax=ax
)
```

I don't know if I'd recommend this approach for general purpose use, but it may be helpful...

**Comment by ghuname** [comment]
Thanks!
