### ISSUE TITLE
Setting seaborn figure size.

### ISSUE THREAD

**Issue by ydennisy** [mwaskom/seaborn#2387]
Hi!

I think I google "how to set seaborn figure size" at least 2 times a day.

Always landing on [the same SO answer](https://stackoverflow.com/questions/31594549/how-do-i-change-the-figure-size-for-a-seaborn-plot), which is good.

But today I thought - wouldn't it be nice to make the API a little simpler and more concise?

`sns.set(rc={'figure.figsize':(10,10)})`

Could become:

`sns.set_figure_size(x, y)`

Would be quite a bit easier to remember 👍

**Comment by mwaskom** [comment]
I'd refer [here](http://seaborn.pydata.org/tutorial/function_overview.html#specifying-figure-sizes) for a better explanation.

I don't think this should have a distinct function.

**Comment by ydennisy** [comment]
hmmm ok well thanks for considering it...

**Comment by mwaskom** [comment]
You're welcome.
