### ISSUE TITLE
Legend problems in FacetGrid

### ISSUE THREAD

**Issue by Rabeez** [mwaskom/seaborn#2390]
I noticed something weird with the automatically generated legend in `relplot` (example is with line but I verified that the same thing happens with scatter as well). The legend data apparently knows about the new line I added but it doesn't show in the plot. 

```python
g = sns.relplot(data=tips, kind='line', 
                x='total_bill', y='tip',
                hue='sex',
                col='sex')

g = g.map(plt.axhline, y=tips['tip'].mean(), 
          color='black', linestyle='dashed', label='Average');

pprint(g._legend_data)
```
> {'Average': <matplotlib.lines.Line2D object at 0x000002251CC41C08>,
   'Female': <matplotlib.lines.Line2D object at 0x000002251CC52C08>,
   'Male': <matplotlib.lines.Line2D object at 0x000002251CCA9DC8>}

![image](https://user-images.githubusercontent.com/9392057/102663325-734f0d00-41a2-11eb-8c8f-d96d2d6cf122.png)

Manually redrawing the legend with this legend data fixes the problem:
```python
# at the end of above code
legend_data = g._legend_data
g.legend.remove()
g.add_legend(legend_data)
```
![image](https://user-images.githubusercontent.com/9392057/102663418-a4c7d880-41a2-11eb-9269-c415896b6ed4.png)

<br><br>
I thought this had something to do with when the legend was auto-genereted so I tried this by making the grid myself

```python
g = sns.FacetGrid(data=tips,
                  hue='sex',
                  col='sex',
                  height=4)

g.map(sns.lineplot, 'total_bill', 'tip')

g.add_legend()

g = g.map(plt.axhline, y=tips['tip'].mean(), color='black', linestyle='dashed', label='Average')
```
![image](https://user-images.githubusercontent.com/9392057/102663558-e9ec0a80-41a2-11eb-909a-c207eb4e3468.png)

Okay, same output as I expected but when I move the legend generation to the end this happens
```python
# end of above code
g = g.map(plt.axhline, y=tips['tip'].mean(), color='black', linestyle='dashed', label='Average');
g.add_legend()
```

![image](https://user-images.githubusercontent.com/9392057/102663647-156ef500-41a3-11eb-9779-2ebd58a38da7.png)

The legend data dict doesn't have the new line but somehow its style has overridden everything here. 

>**Versions:**
seaborn   : 0.11.0
matplotlib: 3.1.2

**Comment by mwaskom** [comment]
I think you want to do it this way:

```python
g = sns.relplot(
    data=tips, kind='line', 
    x='total_bill', y='tip',
    hue='sex',
    col='sex'
)
g.legend.remove()
g.map(plt.axhline, y=tips['tip'].mean(), color='black', linestyle='dashed', label='Average')
g.add_legend()
```

`add_legend` needs to be explicitly called.

Remember not to access private attributed (e.g. `g._legend_data`) in code that can't unexpectedly break in the future.

**Comment by Rabeez** [comment]
Removing the legend before `map` solves the issue in the first case. Curious why this isn't done behind the scenes for every call to map though?

But the second issue (wrong styles in legend after second map) is still here. It seems like the handles legend data are changed after the second map call.

**Comment by mwaskom** [comment]
> Removing the legend before map solves the issue in the first case. Curious why this isn't done behind the scenes for every call to map though?

`.map` doesn't automatically draw the legend, so it wouldn't make sense to automatically remove it. `relplot` is drawing the legend here, and while you can suppress that, putting `legend=False` disables the logic that sets the legend data properly for a later call.

You can also pass your own legend data to `add_legend` if you want to be explicit about what goes in the legend.

> But the second issue (wrong styles in legend after second map) is still here. It seems like the handles legend data are changed after the second map call.

I'm not sure what you mean here. I get this image, which is what I understood you to be looking for:

![image](https://user-images.githubusercontent.com/315810/102667474-75d84500-4157-11eb-87ac-94958084577b.png)

**Comment by Rabeez** [comment]
```python
g = sns.FacetGrid(data=tips,
                  hue='sex',
                  col='sex',
                  height=4)

g.map(sns.lineplot, 'total_bill', 'tip')
g = g.map(plt.axhline, y=tips['tip'].mean(), color='black', linestyle='dashed', label='Average');
g.add_legend()
```

With this I get this 
![image](https://user-images.githubusercontent.com/9392057/102668034-c3cb6800-41ac-11eb-9b26-b3a19b15748c.png)

**Comment by Rabeez** [comment]
> You can also pass your own legend data to `add_legend` if you want to be explicit about what goes in the legend.

What is the *recommended* way to get the handles from the chart if I want to modify the legend? I went with `_legend_data` to do this basically.

**Comment by mwaskom** [comment]
> With this I get this

Ah, yes. Well this is really working properly, even if it's surprising. When you call `.map` the second time, `FacetGrid` updates its legend data with the artists you just added. Because you set `hue` in `FacetGrid`, it's associating the artists that call produced with the internal labels for the hue variable.

Moving the `hue` assignment out of the `FacetGrid` constructor and into `.map` will achieve the same result as the `relplot` example I gave.

> What is the recommended way to get the handles from the chart if I want to modify the legend?

At the moment, the best way is to get them from the matplotlib artist lists.
