### ISSUE TITLE
Unable to import seaborn 

### ISSUE THREAD

**Issue by amr-saber-17** [mwaskom/seaborn#2391]
When I try to import seaborn the following error appears:

''' ImportError                               Traceback (most recent call last)
<ipython-input-1-a84c0541e888> in <module>
----> 1 import seaborn as sns

~\anaconda3\lib\site-packages\seaborn\__init__.py in <module>
      1 # Import seaborn objects
----> 2 from .rcmod import *  # noqa: F401,F403
      3 from .utils import *  # noqa: F401,F403
      4 from .palettes import *  # noqa: F401,F403
      5 from .relational import *  # noqa: F401,F403

~\anaconda3\lib\site-packages\seaborn\rcmod.py in <module>
      5 import matplotlib as mpl
      6 from cycler import cycler
----> 7 from . import palettes
      8 
      9 

~\anaconda3\lib\site-packages\seaborn\palettes.py in <module>
      7 from .external import husl
      8 
----> 9 from .utils import desaturate, get_color_cycle
     10 from .colors import xkcd_rgb, crayons
     11 

~\anaconda3\lib\site-packages\seaborn\utils.py in <module>
      8 
      9 import numpy as np
---> 10 from scipy import stats
     11 import pandas as pd
     12 import matplotlib as mpl

~\anaconda3\lib\site-packages\scipy\stats\__init__.py in <module>
    386 
    387 """
--> 388 from .stats import *
    389 from .distributions import *
    390 from .morestats import *

~\anaconda3\lib\site-packages\scipy\stats\stats.py in <module>
    178 import scipy.special as special
    179 from scipy import linalg
--> 180 from . import distributions
    181 from . import mstats_basic
    182 from ._stats_mstats_common import (_find_repeats, linregress, theilslopes,

~\anaconda3\lib\site-packages\scipy\stats\distributions.py in <module>
      6 #       instead of `git blame -Lxxx,+x`.
      7 #
----> 8 from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
      9                                     rv_frozen)
     10 

~\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py in <module>
     21 
     22 # for root finding for continuous distribution ppf, and max likelihood estimation
---> 23 from scipy import optimize
     24 
     25 # for functions of continuous distributions (e.g. moments, entropy, cdf)

~\anaconda3\lib\site-packages\scipy\optimize\__init__.py in <module>
    385 """
    386 
--> 387 from .optimize import *
    388 from ._minimize import *
    389 from ._root import *

~\anaconda3\lib\site-packages\scipy\optimize\optimize.py in <module>
     34                          line_search_wolfe2 as line_search,
     35                          LineSearchWarning)
---> 36 from ._numdiff import approx_derivative
     37 from scipy._lib._util import getfullargspec_no_self as _getfullargspec
     38 from scipy._lib._util import MapWrapper

~\anaconda3\lib\site-packages\scipy\optimize\_numdiff.py in <module>
      4 from numpy.linalg import norm
      5 
----> 6 from scipy.sparse.linalg import LinearOperator
      7 from ..sparse import issparse, csc_matrix, csr_matrix, coo_matrix, find
      8 from ._group_columns import group_dense, group_sparse

~\anaconda3\lib\site-packages\scipy\sparse\linalg\__init__.py in <module>
    112 from .dsolve import *
    113 from .interface import *
--> 114 from .eigen import *
    115 from .matfuncs import *
    116 from ._onenormest import *

~\anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py in <module>
      7 
      8 """
----> 9 from .arpack import *
     10 from .lobpcg import *
     11 

~\anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py in <module>
     18 
     19 """
---> 20 from .arpack import *

~\anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py in <module>
     41 __all__ = ['eigs', 'eigsh', 'svds', 'ArpackError', 'ArpackNoConvergence']
     42 
---> 43 from . import _arpack
     44 arpack_int = _arpack.timing.nbx.dtype
     45 

ImportError: DLL load failed while importing _arpack: The specified procedure could not be found. '''

**Comment by mwaskom** [comment]
If you read the exception trace, you will see that the the import error is being raised fro scipy.

You will need to consult the scipy installation docs for your system to see how to get your installation working.

**Comment by amr-saber-17** [comment]
But I could not find anyway to solve this **arpack** issue in any forum. So any help is appreciated

**Comment by amr-saber-17** [comment]
@mwaskom  thanks for clarifying the error source, and I was able to solve my issue by uninstalling scipy and reinstall it again. Again thank you very much :)
