### ISSUE TITLE
Feature Request: Add Pareto charts and dot plots

### ISSUE THREAD

**Issue by gdahlm** [mwaskom/seaborn#2400]
For better or worse; TQM, Six Sigma, ISO9000, and other QA models have made people comfortable with Pareto charts.

I am not sure if it was a design decision to exclude them but I know I personally keep a personal lib handy to make them when requested.

It would be nice for them to be in seaborn but I can also understand why they may have been intentionally excluded like pie charts.  Personally, I would argue that if you understand their limitations Pareto charts are a useful tool in some domains.  Primarily when sharing with organization members who are familiar with them but will not spend the time to understand the more advanced and intuitive visualization methods available in seaborn.

While finding spare cycles to refactor my code to the project style may take a little while. Let me know if a pull request would be accepted or if this type of chart has been excluded based on data visualization concerns or is out of scope.

**Comment by mwaskom** [comment]
I'd probably be -1 on a function that does this — I don't think it's a good idea to crowd the library with additional one-off named plots. But I would encourage you to turn your code (either using seaborn or matplotlib directly) into a package and share it on PyPI.

**Comment by gdahlm** [comment]
Not a problem I will close this request.
