### ISSUE TITLE
Documentation in PDF format

### ISSUE THREAD

**Issue by tebeka** [mwaskom/seaborn#2402]
It'll be great to have the documentation in PDF format as well. I'm teaching in a place when they don't always have external internet.

**Comment by tebeka** [comment]
To build the PDF docs I had to add `sphinx.ext.imgconverter` to the extensions in `doc/conf.py`

**Comment by mwaskom** [comment]
I don't expect that pdf docs would render very well ... if you don't have external internet my suggestion would be to build the html site locally and view it in your browser. Instructions for doing so are here: https://github.com/mwaskom/seaborn/tree/master/doc#building-the-seaborn-docs

I guess you'll need the example datasets cached if you want to build when there's no internet available.

**Comment by mwaskom** [comment]
Actually maybe even easier than building locally would just be to clone the docs website: https://github.com/seaborn/seaborn.github.io/

**Comment by mwaskom** [comment]
I wasn't able to get a PDF build working with a little bit of effort, and anyway I suspect the file would be rather large, so I would be disinclined from sharing it publicly via the main website, which is a github repo and subject to space constraints.

But I added a note to the [docs readme](https://github.com/mwaskom/seaborn/blob/master/doc/README.md) mentioning that the website repo is a good source for offline docs, and I additionally tagged each release back to v0.8.0, allowing github to provide a simple zipfile download of the corresponding docs.

If you think a PDF file would be a better approach for your students, you're certainly welcome to build one and share it with them.

**Comment by tebeka** [comment]
Thanks! I'm attaching the generated PDF for ... not really sure :) I don't think it's bad.

[seaborn.pdf](https://github.com/mwaskom/seaborn/files/5746585/seaborn.pdf)

**Comment by mwaskom** [comment]
It looks like this is missing all the content for the user guide/tutorial. Is that deliberate?

**Comment by mwaskom** [comment]
It also doesn't have code/images in the API section, at least for the functions using the [newer system](https://github.com/mwaskom/seaborn/issues/2110).

**Comment by tebeka** [comment]
> It looks like this is missing all the content for the user guide/tutorial. Is that deliberate?

Nope. I ran `make latexpdf` and that's what came out.

**Comment by mwaskom** [comment]
Looks like you missed the step where you build the notebooks: https://github.com/mwaskom/seaborn/tree/master/doc#building-the-seaborn-docs
