### ISSUE TITLE
Different colering for strip and scatter plot when using hue argument

### ISSUE THREAD

**Issue by KevinAStein** [mwaskom/seaborn#2405]
HI,
If I plot the same data with a scatter and a stripplot and use the hue argument to color the points, I get slightly different coloring.

![seaborn](https://user-images.githubusercontent.com/15087000/103220224-06fda780-4920-11eb-8ec5-21840038621f.png)

I intend to add a colorbar to the Plot. It works for the ScatterPlot, but the coloring of the StripPlot is off.

Sample Code
```
import seaborn as sns
from matplotlib.cm import ScalarMappable
import matplotlib.pyplot as plt

#Data
tips = sns.load_dataset("tips")
y_min = min(tips["total_bill"])
y_max = max(tips["total_bill"])

#ScatterPlot
fig = plt.figure(figsize = (6,8))
ax1 = plt.subplot(1,2,1)
g = sns.scatterplot(data=tips, x="sex", y="total_bill", hue="total_bill", palette="viridis", ax = ax1)
g.legend_.remove()
ax1.set_ylim((y_min,y_max))
ax1.set_title('ScatterPlot')

#Stripplot
ax2 = plt.subplot(1,2,2)
g = sns.stripplot(data=tips, x="sex", y="total_bill", hue="total_bill", palette="viridis", ax = ax2)
g.legend_.remove()
ax2.set_ylim((y_min,y_max))
ax2.set_ylabel('')
ax2.set_title('StripPlot')

#Colormap for comparison
cmap = plt.get_cmap("viridis")
norm = plt.Normalize(y_min,y_max)
sm =  ScalarMappable(norm=norm, cmap=cmap)
sm.set_array([])
cbar = fig.colorbar(sm, ax=ax2)
```

**Comment by mwaskom** [comment]
The hue argument in stripplot current only supports a categorical mapping, so each unique value in your data gets a color that is evenly spaced with respect to order, not value.  This will be improved at some point in the future.

**Comment by KevinAStein** [comment]
Thank you for the quick answer, as a remark, I observed the same behavior for the SwarmPlot. There is no inbuilt way to jitter a categorical ScatterPlot yet, right?

**Comment by mwaskom** [comment]
No, but you can kind of hack it together posthoc if you need to; something like

```python
ax = sns.scatterplot(data=tips, x="sex", y="total_bill", hue="total_bill", palette="viridis", legend=False)
pts = ax.collections[0]
pts.set_offsets(pts.get_offsets() + np.c_[np.random.uniform(-.1, .1, len(tips)), np.zeros(len(tips))])
ax.margins(x=.5)
ax.autoscale_view()
```

**Comment by KevinAStein** [comment]
Perfect, thank you again.
