### ISSUE TITLE
heatmap: option to set extent (similar to plt.imshow)

### ISSUE THREAD

**Issue by pushkarnimkar** [mwaskom/seaborn#2406]
I am trying to draw certain shapes on a heatmap created using `sns.heatmap`. The data frame I've passed has a `pd.Float64Index` for columns as well as rows. Although the heatmap function gives the labels correctly, I can not use the same coordinate reference for drawing other shapes on top of the heatmap.

To be precise, here's what I am trying to do:
```python
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from matplotlib.patches import Ellipse

c = np.random.normal(size=(10, 10))
x = np.linspace(-10, 8, 10)
y = np.linspace(100, 190, 10)
df = pd.DataFrame(c, index=x, columns=y)

fig, ax = plt.subplots()
ellipse = Ellipse((130, 3), width=20, height=1.5, angle=0)
sns.heatmap(df, ax=ax, cmap='RdYlGn_r')
ax.add_artist(ellipse)
ellipse.set_facecolor('black')
```
The ellipse is plotted as per the coordinates of the image, while I expect it to be plotted by the data coordinate. The following code achieves the desired output:
```python
fig, ax = plt.subplots()
ellipse = Ellipse((130, 3), width=20, height=1.5, angle=0)

xs = df.index
xs_margin = (xs[1] - xs[0]) / 2
xs = np.append(xs - xs_margin, xs[-1] + xs_margin)

ys = df.columns
ys_margin = (ys[1] - ys[0]) / 2
ys = np.append(ys - ys_margin, ys[-1] + ys_margin)

ax.pcolormesh(ys, xs, df.values, cmap='RdYlGn_r')
ax.invert_yaxis()
ax.add_artist(ellipse)
ellipse.set_facecolor('black')
```
I understand that it's not possible to use any data frame with `pd.Float64Index` to set the axes limits as the indexing does not ensure monotonicity implicitly. But, there should be a provision to specify the xs and ys arrays explicitly (of size rows + 1, and columns + 1), especially given that the underlying `plt.pcolormesh` function supports these arguments. An even more effective way would be to provide a flag to set x and y coordinates according to the data frame indices.

Please let me know if I am missing out on an existing implementation for doing this.

**Comment by mwaskom** [comment]
Yes something like this is probably on the roadmap, but in the meantime why not just use `plt.pcolormesh`directly? What `sns.heatmap` adds is easier handling of categorical axis labels (maybe not even true anymore now that matplotlib has direct categorical support).

**Comment by mwaskom** [comment]
Relevant issue for tracking a more flexible heatmap data specification API is here: https://github.com/mwaskom/seaborn/issues/2054
