### ISSUE TITLE
Need better approach for handing log scales internally

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#2409]
The `comp_data` property will produce log-scale x/y data when the corresponding axis is log scaled. That's useful because statistics will be computed in log space. But then the variables need to be converted back to the original domain before plotting.

There needs to be a general solution for this. e.g. the approach now in `lineplot` is something like:

```python
            for var in ["x", "y"]:
                if self._log_scaled(var):
                    for col in sub_data.filter(regex=f"^{var}"):
                        sub_data[col] = np.power(10, sub_data[col])
```

Complicating matters:

- The computation can add variables (e.g. `_min`, `_max` when error bars are produced)
- The distribution computations don't (currently) produce an output data with `x`, `y` columns (but they probably should

**Comment by mwaskom** [comment]
Also we really should handle this sort of thing using the matplotlib `Transform` objects (which should usually or always -- need to check -- have inverses)

**Comment by mwaskom** [comment]
Closing as there is WIP on this, it will only gradually role out to functions in the `seaborn` namespace, but it is not an external feature so it does not need to be tracked.

**Comment by jlumpe** [comment]
> Also we really should handle this sort of thing using the matplotlib `Transform` objects (which should usually or always -- need to check -- have inverses)

Has there been any progress extending this to use arbitrary `Transform` objects?
