### ISSUE TITLE
Seaborn should intelligently label datetime axes

### ISSUE THREAD

**Issue by shoyer** [mwaskom/seaborn#242]
I'm often interested in plotting data indexed with a `pandas.DatetimeIndex` object / `datetime64` array. It would be nice if seaborn could recognize when the values along an axis are given by dates and provide sensible labels (like pandas).

**Comment by laurieskelly** [comment]
my god @shoyer, i hope you eventually let that poor subject out of the scanner...

**Comment by clarkfitzg** [comment]
@clearf @shoyer `fig.autofmt_xdate()` is pretty handy. http://matplotlib.org/users/recipes.html#fixing-common-date-annoyances

**Comment by foobarbecue** [comment]
Wow, this is still open? Seaborn timeseries plots don't support time axis labels?

**Comment by mwaskom** [comment]
There, now it's closed. Official answer: seaborn is not going to support time axis labels in `tsplot`, and @foobarbecue is blocked from the repository for being obnoxious.

**Comment by joseortiz3** [comment]
I think its not difficult to extract the methods pandas uses to make such nice date axes. I was looking at it yesterday, the machinery can be tracked down and extracted.

**Comment by szeitlin** [comment]
@joseortiz3 It would be great if you would open a PR with a fix for this, or at least outline the steps in detail if it's really that straightforward, so someone else can contribute a fix.

**Comment by mwaskom** [comment]
This is an issue about a deprecated function so I am locking it.
