### ISSUE TITLE
add parameter explanation on pairplot tutorial

### ISSUE THREAD

**Issue by sohyunwriter** [mwaskom/seaborn#2421]
[pairplot tutorial](https://seaborn.pydata.org/generated/seaborn.pairplot.html) 

Above tutorial, it does not mention about parameter 'size', so it's confusing whether the size means dot size or facet size, or anything else. When I checked it on juypter notebook, I knew that the 'size' has been renamed to 'height', so those two words are same. 
So, I think it's better to add explanation on tutorial for those who may be confused when reading tutorial.

size: scala
Height of each facet. Size parameter has been renamed to 'height'.

**Comment by mwaskom** [comment]
The backwards compatibility for `size` will be removed in the current release cycle, so I don't think it's worth updating the docs now. Current practice is to keep deprecated parameters in the docstring with a note on their deprecation.
