### ISSUE TITLE
Lineplot central tendency

### ISSUE THREAD

**Issue by darrencl** [mwaskom/seaborn#2422]
Hi, I would like to use lineplot and am wondering on what is the default central tendency?

As per the [documentation](https://seaborn.pydata.org/generated/seaborn.lineplot.html#seaborn-lineplot):

> By default, the plot aggregates over multiple y values at each value of x and shows an estimate of the central tendency and a confidence interval for that estimate.

Also further down in the example:

> Passing the entire dataset in long-form mode will aggregate over repeated values (each year) to show the mean and 95% confidence interval:

Based on those, I assume the 'central tendency' is defined as mean? Is there any option to change this behavior, e.g. using median for central tendency?

Thanks!

**Comment by mwaskom** [comment]
Yes, from that page

> estimator: name of pandas method or callable or None
>>    Method for aggregating across multiple observations of the y variable at the same x level. If None, all observations will be drawn.
