### ISSUE TITLE
seaborn heatmap's colorbar is generating random ticks

### ISSUE THREAD

**Issue by rikdhar** [mwaskom/seaborn#2430]
I am trying to make a heatmap with logarithmic colorbar. But it keeps generating it's own ticks and ticklabels. 

```python
import numpy as np
import seaborn as sns
from matplotlib.colors import LogNorm
import matplotlib.ticker as tkr

matrix = np.random.rand(10, 10)/0.4
vmax=2
vmin=0.5

cbar_ticks = [0.5, 0.75, 1, 1.33, 2]
formatter = tkr.ScalarFormatter(useMathText=True)
formatter.set_scientific(False)

log_norm = LogNorm(vmin=vmin, vmax=vmax)
ax = sns.heatmap(matrix, square=True, vmax=vmax, vmin=vmin, norm=log_norm, cbar_kws={"ticks": cbar_ticks, "format": formatter})
```

![image](https://user-images.githubusercontent.com/53090717/104248299-dabd4d00-542e-11eb-8c0a-6dffb6ebf143.png)

**Comment by mwaskom** [comment]
I think this is an instance of this matplotlib bug: https://github.com/matplotlib/matplotlib/issues/12503

A pure matplotlib example that reproduces the issue is

```python
import numpy as np
import seaborn as sns
from matplotlib.colors import LogNorm
import matplotlib.ticker as tkr

matrix = np.random.rand(10, 10)/0.4
vmax=2
vmin=0.5

cbar_ticks = [0.5, 0.75, 1, 1.33, 2]
formatter = tkr.ScalarFormatter(useMathText=True)
formatter.set_scientific(False)

log_norm = LogNorm(vmin=vmin, vmax=vmax)

f, ax = plt.subplots()
mesh = ax.pcolormesh(matrix, norm=log_norm)
cbar = f.colorbar(mesh, ticks=cbar_ticks, format=formatter)
```

**Comment by mwaskom** [comment]
Ah, what you're seeing there is a minor ticklabel. You can make it go away by extending the original example with:

```python
cax = ax.figure.axes[-1]
cax.set_yticklabels([], minor=True)
```

(this assumes you don't have any other axes in the figure)

**Comment by rikdhar** [comment]
Both the above solution and the work around mentioned in the matplotlib forum helps in removing the tick label. But the ticks still remain. Is there a way to remove the additional ticks as well?

Workaround from matplotlib forum that works with above example:
```python
from matplotlib.ticker import LogFormatterSciNotation
class MF(LogFormatterSciNotation):
    def set_locs(self, locs=None):
        self._sublabels = set([1,2,5,10])
cbar = ax.collections[0].colorbar
cbar.ax.yaxis.set_minor_formatter(MF())
```

[update graph](https://i.imgur.com/wqWdbYm.png)

**Comment by rikdhar** [comment]
The following completely removes the ticks and the label.
```python
ax.collections[0].colorbar.ax.yaxis.set_ticks([], minor=True)
```

**Comment by mwaskom** [comment]
That `ax.collections[0].colorbar.ax` object is the same as the `cax` object in my code, fyi.
