### ISSUE TITLE
Heatmap with column names on all axes

### ISSUE THREAD

**Issue by larryzhang95** [mwaskom/seaborn#2433]
I'm trying to produce a heatmap by replicating the axes column names on each side, right now using the twinx/twiny functionality of matplotlib. However, it does not scale properly like it does when plotting the original x,y axes column names. 

In this case, the heatmap is very large, hence it would be a nice-to-have. Wasn't able to find any resolutions online, so I wonder if there may be a simple way to perform this as the alignment is probably much nicer than the replication of axes.

**Comment by mwaskom** [comment]
I'm sorry but I'm not able to understand this from your description. Please provide a reproducible example of what you're trying to do and what you think is going wrong.

**Comment by mwaskom** [comment]
Also you'll probably get a faster answer at StackOverflow, which is where I would prefer [these questions](http://seaborn.pydata.org/installing.html#getting-help) go.

**Comment by larryzhang95** [comment]
Noted -- I initially started with going to StackOverFlow to try to get an answer, and will publish the question in both places with code. I have to alter some of the code as the data is private, so for making for example, I will use randomly generated data. 

`
data = np.random.rand(30,20)
col_names = ['col' + str(i) for i in range(20)]
data = pd.DataFrame(data,columns=col_names)
size = len(data.columns)
f,ax = plt.subplots(figsize=(size, size))
sns.heatmap(data.corr().abs(), annot=True, linewidths=.5, fmt= '.2f',ax=ax)
ax3 = ax.twiny()
ax3.set_aspect("equal")
print(ax.get_xlim())
ax3.set_xlim([0,ax.get_xlim()[1]])
ax3.set_xticks(ax.get_xticks())
ax3.set_xticklabels(data.columns.tolist())
ax3.tick_params(top=True)
ax3.spines['top'].set_visible(False)
ax3.spines['right'].set_visible(False)
ax3.spines['bottom'].set_visible(False)
ax3.spines['left'].set_visible(False)
`

The code produces the following heatmap. 
![heatmap](https://user-images.githubusercontent.com/29720526/104498155-2a675a00-5590-11eb-9040-4be7ce9e9359.png)

In this case, I am trying to produce the same column names as that of the bottom; however you can see that the tick points and column names are shifted, by which I assume there may be code in seaborn that autoscales the ticks to the size of the figure I may not be aware of. 

I was hoping to get the same bottom axis labels and ticks on the top, as sometimes it may be hard to interpret very large heatmaps if column names are only on the bottom.

I'll update here if the question gets answered on stackoverflow and close!

**Comment by mwaskom** [comment]
FYI if you want to put multiple lines of formatted code you need to do it between three backticks.

**Comment by mwaskom** [comment]
Remove `ax3.set_aspect("equal")` and you'll get the result you're looking for.

**Comment by milosheskad** [comment]
and how can you change column names, lets say, from col0 to first_column. If you have them as a list?
