### ISSUE TITLE
Unable to import on Apple M1: Misaligned address error

### ISSUE THREAD

**Issue by TonyWu20** [mwaskom/seaborn#2437]
When the arm64 arch python3 trying to import seaborn, an error message shows up:`"python3" terminated by signal SIGBUS (Misaligned address error). If switch to the x86_64 python, the import runs smoothly.

**Comment by mwaskom** [comment]
Can you please show the full exception trace? Seaborn is pure Python so I would be surprised if the incompatability is in seaborn per se vs one of its compiled dependencies (numpy, scipy, pandas, or matplotlib).

**Comment by TonyWu20** [comment]
```
$python3
Python 3.9.1 (default, Dec 25 2020, 13:14:21)
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import seaborn
fish: “python3” terminated by signal SIGBUS (Misaligned address error)
```
This is the only message shown.

**Comment by mwaskom** [comment]
Hm in that case you'll need to manually see if you can import `numpy`, `matplotlib.pyplot`, `scipy.stats`, `pandas`, etc. and figure out which library is causing the problem.

**Comment by TonyWu20** [comment]
It is `scipy.stats` that goes wrong. I think it is due to the incomplete Apple M1 support of my installed scipy.
