### ISSUE TITLE
Get data from seaborn without plotting the graph

### ISSUE THREAD

**Issue by jankaWIS** [mwaskom/seaborn#2438]
Hi, I have a strange issue -- I do not want seaborn to plot :). More accurately, if I use the following lines in my code:
```
import seaborn

penguins = sns.load_dataset("penguins")
x,y = sns.histplot(data=penguins, x="flipper_length_mm", kde=True, stat="probability", color="r", label="probabilities").get_lines()[0].get_data()
```
it always plots the underlying distribution and histograms. How do I turn it off? What I mean is that it creates the instance so whenever later in the code (or in Jupyter cell) I call `plt.show()`, it plots all those accumulated graphs. I would care only about the data, about the numbers.
Thanks.

**Comment by mwaskom** [comment]
Hi, seaborn is a visualization library; I think you should use `np.histogram` or `scipy.stats.gaussian_kde` if you want to compute a histogram or kernel density estimate and don't want a plot. I guess you could explicitly close the matplotlib figure before calling `plt.show` (why call `plt.show` if you don't want a plot?) but it's a very roundabout way of doing things and you'll very likely have a better time using the computational tools directly.

**Comment by jankaWIS** [comment]
> Hi, seaborn is a visualization library; I think you should use `np.histogram` or `scipy.stats.gaussian_kde` if you want to compute a histogram or kernel density estimate and don't want a plot. I guess you could explicitly close the matplotlib figure before calling `plt.show` (why call `plt.show` if you don't want a plot?) but it's a very roundabout way of doing things and you'll very likely have a better time using the computational tools directly.

I still think there is a value in the question despite your answer. The reason for `plt.show` is unrelated to this part, ie. if I plot something else later in the code, I would need to call it and then all the previous saved figures will pop-up, more importantly, they'll be plotted into the same figure.
About `np.histogram` (alternatively also `matplotlib` gives the same) or `scipy`, well, yes, but then I have to do all the follow-up work myself, all the work which has been done by you :).

**Comment by mwaskom** [comment]
You are of course welcome to hack together a solution; in this case you'll need to do what I said (explicitly close the figure that seaborn creates before plotting something else).
