### ISSUE TITLE
Improving violin plots

### ISSUE THREAD

**Issue by PierreBdR** [mwaskom/seaborn#244]
I have recently offered a pull request about allowing user-defined KDE for violin plots. This is an important feature for me as I often work with dataset on bounded domains, that require specific methods for estimating their pdf.

It was mentioned that the violin plots was in need of refactoring. I am offering to try doing it. I would like to know though what would be expected from the refactoring. I looked at the other functions in the library and they are structure in very much the same way as the violin plots.

My thoughts are:
  - factor the presentation of the KDE computation and share it among the various KDE/using plots. I would like to support three types of KDE:
      1. Default (i.e. using scipy or statsmodel KDE)
      2. user-provided function estimating the pdf on a given set of points
      3. user-provided evaluations of the pdf given as two vectors: the evaluation points, and the pdf on these points
  - factor for re-use the way to present the data (box, points or sticks)
  - instead of using strings for every configuration element, we could use objects implementing them. I find two advantages to this approach: users can provide their own and you get completion from within your IDE / shell.

**Comment by mwaskom** [comment]
Closing with #410
