### ISSUE TITLE
sns.FacetGrid plot missing components in legend when passing custom plot functions.

### ISSUE THREAD

**Issue by LIC-cjc** [mwaskom/seaborn#2444]
Given the example dataset:
```
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

date_today= datetime.now()
tips = sns.load_dataset("tips")
days = pd.date_range(date_today, date_today + timedelta(tips.shape[0]-1), freq='D')
tips['date'] = days
```
Then using a custom plotting function `twin_lineplot` with the following code:

```
def twin_lineplot(x,y,color,**kwargs):
    ax = plt.twinx()
    sns.lineplot(x=x,y=y,color=color,**kwargs, ax=ax)

g = sns.FacetGrid(tips, row='smoker', col='time')
g.map(sns.lineplot, 'date', 'tip', color='b', label='label1')
g.map(twin_lineplot, 'date', 'total_bill', color='g', label='label2')
g.add_legend()
g.fig.autofmt_xdate()
plt.show()
```

The blue line and the green line will be displayed in separate legends which is annoying, when the green line `label2` should just be shown with the blue line `label1` on the right. 

```
>>> seaborn.__version__
'0.11.0'
```

**Comment by mwaskom** [comment]
FacetGrid doesn't support dual y axes, so you're going to need to work out a solution where you either extend your custom function identify the artists that you want to represent in the legend or create proxy artists and then pass them directly to the `add_legend` call. I expect that if you ask on stackoverflow, someone clever will help you figure it out.
