### ISSUE TITLE
pip install seaborn successfully ，but can not import

### ISSUE THREAD

**Issue by Janewlovewt** [mwaskom/seaborn#2445]
using pip install seaborn（v 0.11.1， matplotlib  v3.1.2）  successfully，but cannot import it，when import it， it raise **sementation fault** 

> any one encounter this issue ，help ，，，，， thx

**Comment by mwaskom** [comment]
seaborn is pure python so likely what has happened is that there is a problem with the installation of one of its dependent libraries that have compiled components. I would suggest trying to figure out which one is causing the problem by trying to import them directly. True `numpy`, `pandas`, matplotlib.pyplot`, and `scipy.stats` for starters.

**Comment by Janewlovewt** [comment]
> seaborn is pure python so likely what has happened is that there is a problem with the installation of one of its dependent libraries that have compiled components. I would suggest trying to figure out which one is causing the problem by trying to import them directly. Try `numpy`, `pandas`,` matplotlib.pyplot`, and `scipy.stats` for starters.

 import   `numpy`, `pandas`  normally ,but  import ` matplotlib.pyplot`, and `scipy.stats` will  have  sementation fault; But when installing them, it shows that they were successfully installed

**Comment by Janewlovewt** [comment]
[python issue.docx](https://github.com/mwaskom/seaborn/files/5854812/python.issue.docx)

**Comment by mwaskom** [comment]
As this appears to be a problem with the installation of other libraries and not seaborn itself, I'm afraid I'm unable to help further. You'll need to read through the installation docs for those libraries to see if they have any specific information about your system and if not, follow up by opening an issue. You'll want to provide them with as much information as you can provide about your operating system, hardware, how you installed the libraries, exactly what you see etc.
