### ISSUE TITLE
Matching x axis when ploting lines over bars.

### ISSUE THREAD

**Issue by lgmsantos** [mwaskom/seaborn#2459]
When using `lineplot` after a `barplot` x-axis points doesn't match.

A quick example:

```python3 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

df = pd.DataFrame({
    'x' : [1, 2, 3],
    'y1': [1, 2, 3],
    'y2': [1, 4, 9]
})

sns.barplot(x='x', y='y1', data=df) 
sns.lineplot(x='x', y='y2', color='red', data=df)

plt.show()
```

result:
![image](https://user-images.githubusercontent.com/652535/106391390-df40aa00-63cb-11eb-9430-18edd7a8818a.png)

Sorry, could not find a solution for this that worked.

**Comment by mwaskom** [comment]
This is expected in the current version. As the [barplot docs](http://seaborn.pydata.org/generated/seaborn.barplot.html) say:

> This function always treats one of the variables as categorical and draws data at ordinal positions (0, 1, … n) on the relevant axis, even when the data has a numeric or date type.

You could force your lineplot to behave similarly by doing

```python
sns.lineplot(x='x', y='y2', color='red', data=df.assign(x=df["x"].astype(str)))
```

And keep an eye on this issue: https://github.com/mwaskom/seaborn/issues/2429, especially 

> ## New features
> - Mixing functions from the categorical module with other functions in the same Axes will have fewer surprising results, as the functions will use the same ordering rules on the categorical axis
