### ISSUE TITLE
Segmentation fault/bus error on Apple Silicon M1 [python3.8] [macports-py39]

### ISSUE THREAD

**Issue by platipodium** [mwaskom/seaborn#2463]
Independent of python version (tested py39, py39) and installation method (condo, pip, macports), importing seaborn leads to a segmentation fault on arm64

```
$ python
Python 3.8.7 (default, Dec 24 2020, 16:30:03)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import seaborn
[1]    59953 segmentation fault  python
```

Log attached [segfault.log](https://github.com/mwaskom/seaborn/files/5909616/segfault.log)

**Comment by platipodium** [comment]
Trying again with conda and py39, and updating all dependent libraries, I now get it to work with conda only 

```
Python 3.9.1 | packaged by conda-forge | (default, Dec 21 2020, 22:08:11)
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import seaborn
>>>
```

Macports python39 reports a "bus error"

```
 /opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
Python 3.9.1 (default, Dec  8 2020, 10:49:23)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import seaborn
[1]    76509 bus error  /opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
```

**Comment by mwaskom** [comment]
seaborn is pure python and should work anywhere Python does, but it’s dependent libraries with compiled components are still working on full support for apple silicon (e.g. see #2446 which links to upstream issues). 

Debugging segfaults is annoying, to figure out which library is the culprit I’d try to import `numpy`, `pandas`, `scipy.stats`, `matplotlib.pyplot`, and `statsmodels.api` (if you have it installed). That should narrow it down...

**Comment by platipodium** [comment]
I am aware this is an upstream issue, so you may close this as not an issue with seaborn. 

Thought it is of help if document here though as people (like me) stumble with this issue first when trying to use seaborn; in fact, with your hints I could narrow it down to `SciPy.stats`:

```
Python 3.8.7 (default, Dec 24 2020, 16:30:03)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.stats
[1]    35720 segmentation fault  python
```

```
Python 3.9.1 (default, Dec  8 2020, 10:49:23)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.stats
[1]    35842 bus error  /opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
```

**Comment by mwaskom** [comment]
Thanks  — helpful indeed. Closing as upstream issue.

Of note, the next version of seaborn will have scipy as an optional dependency (#2398).
