### ISSUE TITLE
Lineplot or barplot confidence interval support callable

### ISSUE THREAD

**Issue by darrencl** [mwaskom/seaborn#2464]
Hi, I would like to perform `lineplot` and `barplot` with central tendency median (using `np.median`). 

Thus, standard deviation (the current supported method with `ci="sd"`) is not suitable and I would like to use median absolute deviation (`scipy.stats.median_absolute_deviation`). I think it would be great to make this argument to support callable, similar to central tendency.

I am happy to implement this if maintainer would like to have this. Please advise the best way to implement this.

**Comment by mwaskom** [comment]
Feel free to try out the master branch and open an issue if you run into any problems. Be mindful of the work tracked in https://github.com/mwaskom/seaborn/issues/2429; I would not suggest using the master branch for any production code right now.

**Comment by darrencl** [comment]
@mwaskom Hi, thanks for this! I just checked #2407 and tried master. I can see that this `errorbar` arg is only in `lineplot`, could this also be added to `barplot`? 

Thanks.

**Comment by mwaskom** [comment]
Please see #https://github.com/mwaskom/seaborn/issues/2429

**Comment by darrencl** [comment]
@mwaskom I see, so that's still todo. Thanks for referring to that!

Anyway, is there any quick workaround for this current version?
