### ISSUE TITLE
bivariate displot with kind="hist" ignores common_norm=False if hue is not assigned

### ISSUE THREAD

**Issue by mgab** [mwaskom/seaborn#2465]
Somehow similar to #2377, but for `kind='hist'` and with `common_norm=False` being ignored.

If I understand it well, passing `common_norm=False` to `sns.distplot` should produce plots with independent "z" scale. While this is the behaviour for kde plots, it seems to be ignored for bivariate histograms unless hue is also specified.

Test case:
```python
x, y = np.random.randn(2, 200)
z = [0] * 150 + [1] * 50
sns.displot(x=x, y=y, col=z, kind="hist", cbar=True, common_norm=False)
sns.displot(x=x, y=y, col=z, hue=z, kind="hist", cbar=True, common_norm=False)
```

Running seaborn version 0.11.1
(I tried to look for other (open or closed) related issues, hope not duplicating them)

**Comment by mgab** [comment]
Uhm... it seems to come from line https://github.com/mwaskom/seaborn/blob/master/seaborn/distributions.py#L743

Should it be something like this?
```python
common_color_norm = not set(self.variables) - {"x", "y"} or common_norm
```
Similar to what it's done here https://github.com/mwaskom/seaborn/blob/master/seaborn/distributions.py#L723

**Comment by mwaskom** [comment]
Hm, yes, seems like the inverse of the problem in #2377
