### ISSUE TITLE
Pointplot multiplot does not plot x-axis correctly

### ISSUE THREAD

**Issue by G-kodes** [mwaskom/seaborn#2469]
When generating a pyplot subplot for a publication, I noticed that Seaborn's plots do not use the same set of axis. I am not sure if this is a misunderstanding on my part, but I was trying to create a series of subplots for each category (Overlay a scatterplot on top of a bar plot for each axis (1 per category). I would like to add significance markers to some but not all bars based on the value of another column, i.e. pandas filter/query) when I noticed that when I plot the scatterplot, it does not necessarily honor the x-axis demarcations already laid down by the previous Bar Plot. In effect, the first few markers line up perfectly, but after encountering a value that is missing from the scatterplot data subset, it shifts all the scatterplot points over by one (and so on so forth) instead of leaving an empty space and lining the markers up to where the bars fall.

It seems to me that scatterr plot is plotting onto the correct axis instance but plotting according to its own virtual set of axis-ticks instead of honoring ticks that already exist. Is this intended functionality?

> As a side note, the only reason I am doing this like this (roundabout manner) is because I have yet to find a particularly comprehensive annotation system/package for graphs. These are for Journal Articles so I need to add fairly tailored annotations like this. If anyone has any suggestions, you will make my day! XD

## Example pictures:
[right.pdf](https://github.com/mwaskom/seaborn/files/5923830/right.pdf)
[brokeen.pdf](https://github.com/mwaskom/seaborn/files/5923831/brokeen.pdf)

## Example Code (Seaborn Titanic Example)
```python
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

data = sns.load_dataset('titanic')
data = data[data['fare'] >= 60].reset_index()
data['index'] = data['index'].astype(str)


fig, ax = plt.subplots(len(data["class"].unique()), figsize=(25,10*len(data["class"].unique())), sharex=True, sharey=True)
plt.style.use("ggplot")

for index, i in enumerate(ax):
    sns.barplot(x='index', y='fare', hue='class', dodge=False, data=data, ax=i)
    sns.scatterplot(x='index', y='fare', data=data.query("age >= 25"), zorder=10, color='red', markers=["*"], ax=i)
    
```

**Comment by mwaskom** [comment]
This is behavior in the current version. As the [barplot docs](http://seaborn.pydata.org/generated/seaborn.barplot.html) say:

> This function always treats one of the variables as categorical and draws data at ordinal positions (0, 1, … n) on the relevant axis, even when the data has a numeric or date type.

You could force your scatterplot to behave similarly by coercing the x variable to a string type before plotting.

And keep an eye on this issue: https://github.com/mwaskom/seaborn/issues/2429, especially 

> ## New features
> - Mixing functions from the categorical module with other functions in the same Axes will have fewer surprising results, as the functions will use the same ordering rules on the categorical axis
