### ISSUE TITLE
Fixed alignment for barplot dispaces bars when used with JointGrid as marginal plot

### ISSUE THREAD

**Issue by rudevel** [mwaskom/seaborn#2475]
When using a barplot for the marginal part (custom data) the barplots are misaligned as align="center" is **hardcoded twice in categorical.py: line 1564 and 1582**).
The kwargs fail as there is no dictionary update and thus the kwargs provide a second named argument when trying to override - so the plot fails with error.

I'd recommend either removing this option or do a dictionary update with kwargs to allow overriding this option.
(removing solved it for me so far)

python 3.9
seaborn 0.11.0 (and current master)
matplotlib 3.3.4

**Comment by mwaskom** [comment]
can you please add a reproducible example and the [other information](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs) requested in the bug report guidelines? thanks.

**Comment by rudevel** [comment]
Code for reproduction:
(it's all about ALIGN)

```
data = sns.load_dataset('tips')
pivot = data.pivot_table(index='sex', columns='smoker', values='tip', aggfunc=np.mean)

def heatmap(x,y, **kwargs): 
  sns.heatmap(data=pivot, cbar=False)

def heatbars(x, **kwargs):
  #in reality calc mean or sum of tips...
  if x.name == 'sex':
    xy = {'orient': 'h', 
             'y': [3,9],
             'x': [2,3]}
  else:
    xy = {'orient': 'v', 
             'x': [0,1],
             'y': [3,9]}

  ALIGN = True
  if ALIGN:
    #fails due to dupplicate parameter name:
    sns.barplot(**xy, color='skyblue', align='edge')
  else:
    #works but misaligned:
    sns.barplot(**xy, color='skyblue')

g = sns.JointGrid(data=pivot.index)
g.plot(heatmap, heatbars)
```

**Comment by mwaskom** [comment]
I get an error when I run your code, with or without `ALIGN`. The three other things the contribution guidelines ask for are

- The output that you are seeing (an image of a plot, or the error message)
- A clear explanation of why you think something is wrong
- The specific versions of seaborn and matplotlib that you are working with

They're there to save time and effort for everyone...

**Comment by rudevel** [comment]
If you look at the file and lines I mentioned in my first post you'll immediately get the hang.
Alternativley you search for "align" in categorical.py and get the very same two rows.
That was my idea of saving time and effort for everyone.

It appears in your master branch of the project so it's still valid in your most recent version.
As the align- parameter cannot be overridden this way the matplot version is of no concern.

I fully appreciate your work and do not need this to be fixed.
But you might want to.
