### ISSUE TITLE
Colorbar ticks + limits not showing up correctly

### ISSUE THREAD

**Issue by Geet-George** [mwaskom/seaborn#2478]
## Issue

Upon specifiying the lower and upper limits for colorbar as `vmin` and `vmax` respectively, the colorbar changes the color scheme, but the limits shown are still between minimum and maximum value from the data, and not specified `vmin` and `vmax`. Hence, the ticks are also unable to show up correctly. (e.g. The `0` tick is missing in the colorbar in the MWE below)

This issue wasn't there before I had updated to Seaborn's `v0.11.1` around an hour ago. I am happy to help out, but couldn't figure out where exactly the issue arose from.

## MWE

**Input**
```
import seaborn as sns

penguins = sns.load_dataset("penguins")

sns.kdeplot(data=penguins,x="bill_length_mm", y="bill_depth_mm",shade=True,cbar=True,cbar_kws={'ticks':[0,0.01]},vmin=0,vmax=0.01)
```
**Output**

![seaborn_issue_mwe_output](https://user-images.githubusercontent.com/46085279/107550538-12075100-6bc9-11eb-99e1-1673deafc41c.png)

**Versions:**
Matplotlib: 3.2.1
Seaborn: 0.11.1

**Comment by mwaskom** [comment]
I think you want to add `thresh=0` as well, otherwise no values at that extreme will be colormapped.

**Comment by Geet-George** [comment]
Yes, correct. But even then, why isn't the upper limit of the colorbar at 0.01, as I mentioned in the `vmax`? Sorry, this might just be something silly from my end, but cannot manage to figure it out.

**Comment by mwaskom** [comment]
It's a little confusing ... `thresh`/`levels` control the actual contours, and they are in units of proportion of the density (so `thresh=.2` means the filled in contours cover the highest 80%  of the density. `vmin` and `vmax` (which are just passed through to matplotlib) set the normalization of the colormap for the contours, and they are in density units. But you vmin could be below the lowest density level shown, or your vmax could not be equal to the highest density level shown, in which case they will correctly normalize the colormap but not correspond to the extremes of the colorbar itself.

**Comment by mwaskom** [comment]
I'm going to close this issue as everything is working as documented, even if the behavior is a little bit hard to understand at first. I do think the colormap/legend for 2D kdeplots can be improved, but that is likely downstream of the more general planned legend enhancements.
