### ISSUE TITLE
Improve docstrings for `set_context` and `set_style` to make links to matplotlib rc entries clearer

### ISSUE THREAD

**Issue by felixvuo** [mwaskom/seaborn#2481]
@mwaskom suggested it would be good to improve the docstrings for `set_context` and `set_style` in response to [this stackoverflow question](https://stackoverflow.com/questions/66206522/how-can-i-cleanly-achieve-a-consistent-style-for-seaborn-plots-from-different-py).

**Comment by mwaskom** [comment]
Also while poking around the docs I realized that the intro page links to an outdated version of the matplotlib rcParams docs and should be updated to go here: https://matplotlib.org/stable/tutorials/introductory/customizing.html

**Comment by mwaskom** [comment]
Also while doing this, should improve the docstring examples for this functions; they're a little inscrutable.
