### ISSUE TITLE
Error when combining PairGrid with kdeplot

### ISSUE THREAD

**Issue by KSuljic** [mwaskom/seaborn#2483]
Hello everybody,

first of all, thank you for this amazing package!

I encountered this Error by using PairGrid with kdeplot:

```
g = sns.PairGrid(data=df)

g.map_diag(sns.histplot)
g.map_lower(sns.kdeplot)
```

![Error](https://user-images.githubusercontent.com/39726795/108340938-703fbf80-71d9-11eb-9dd3-210a9f3df8b6.png)

The DataFrame has no NaNs.
It works with:

```

g = sns.PairGrid(data=df)

g.map_diag(sns.histplot)
g.map_lower(sns.histplot, kde=True)
```

Thanks in advance.

**Comment by mwaskom** [comment]
Hi, I think you'll need to share the dataset, or construct a simulated version with similar properties that produces the error, otherwise it's very difficult to help.

**Comment by mwaskom** [comment]
Closing for lack of information, but will open if a reproducible example can be provided.
