### ISSUE TITLE
Default alignment y tick labels of sns.heatmap

### ISSUE THREAD

**Issue by jhncls** [mwaskom/seaborn#2484]
The vertical alignment of the y tick labels of a heatmap always look top-aligned. It seems more natural to have them vertically centered.
```
import numpy as np
import seaborn as sns

m = ['January', 'February', 'March']
sns.heatmap(data=np.random.rand(3, 3), yticklabels=m, xticklabels=m)
```

**Comment by mwaskom** [comment]
I can reproduce this, but browsing through the archived versions of the docs, it seems this was not the case at some point in the past.

Please share the versions of matplotlib and seaborn you're using to help track it down (as mentioned in the [contributed guidelines](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs)).

**Comment by mwaskom** [comment]
Note that I can reproduce this using matplotlib directly

```python
import matplotlib.pyplot as plt
f, ax = plt.subplots()
ax.pcolormesh(np.random.randn(3, 3))
ax.set_yticks([.5, 1.5, 2.5])
ax.set_yticklabels(['January', 'February', 'March'], rotation=90)
```
![image](https://user-images.githubusercontent.com/315810/108566476-7e263b00-72d4-11eb-8c21-f105a1a4d940.png)

Although it may be the case that seaborn needs to manually change the alignment variables after rotating the labels. I have a dim sense that this changed recently in matplotlib.

**Comment by mwaskom** [comment]
Interestingly, if you do

```python
print(ax.get_yticklabels()[0].get_verticalalignment())
```

you see that it is `center_baseline`, and what's happening is that the labels are not top-aligned vertically but rather right-aligned horizontally and then rotated 90 degrees.

But ... to work around the issue, one needs to modify the horizontal alignment property:

```python
plt.setp(ax.get_yticklabels(), va="center")
```

**Comment by jhncls** [comment]
I tested this with Seaborn 0.11.1 and matplotlib 3.3.4,  but also tried a few older versions (till seaborn 0.9 and matplotlib 3.1.0) all having the problem.  So probably this is a matplotlib problem and `center_baseline` should look like centered when rotated 90 degrees.
There are two open issues: [matplotlib issue 13044](https://github.com/matplotlib/matplotlib/issues/13044).
And  [matplotlib issue 14865](https://github.com/matplotlib/matplotlib/issues/14865) which indicates the details can be tricky.
For seaborn a solution could be adding `va="center"` at the same moment as the rotation.

**Comment by mwaskom** [comment]
Thanks for checking the matplotlib issues. I agree that seaborn setting the alignment at the time it sets the rotation makes sense.
