### ISSUE TITLE
Add FacetGrid-level tick_params method

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#2491]
Add a method like [this](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.tick_params.html) on the Grid object, internally loop over Axes and call it on each one.

Probably also makes sense on `PairGrid` too, although handling the marginal axes might add a small amount of complexity.

**Comment by stefmolin** [comment]
If you haven't started on this, I'll work on it for the v0.13.0 release.

**Comment by mwaskom** [comment]
Hi @stefmolin, that would be great

**Comment by stefmolin** [comment]
> Probably also makes sense on `PairGrid` too, although handling the marginal axes might add a small amount of complexity.

Do you mean the `JointGrid`? If so, do we want to support different styling on the marginal versus joint axes?

**Comment by mwaskom** [comment]
No I did mean `PairGrid` here (where the "marginal" axes are on the diagonal) although thinking a little more, those axes are actually hidden so perhaps it's not really an issue.

**Comment by stefmolin** [comment]
Can you clarify what you mean by "hidden"? Right now, I'm going over all the axes and calling `tick_params()`:

```python
import seaborn as sns

penguins = sns.load_dataset('penguins')

g = sns.PairGrid(penguins)
g.map(sns.scatterplot)
g.tick_params(direction='in', length=6, width=2, color='blue')
```
<img width="679" alt="Screen Shot 2022-08-06 at 5 11 52 PM" src="https://user-images.githubusercontent.com/24376333/183266172-e060cc29-4a2f-4c27-a7c0-0a8e3b341bf8.png">

**Comment by mwaskom** [comment]
> Can you clarify what you mean by "hidden"? Right now, I'm going over all the axes and calling `tick_params()`:

I mean the axes when you show a marginal plot on the diagonal:

https://github.com/mwaskom/seaborn/blob/9771eae42a802f898f95c6b062f036bd7940e6b4/seaborn/axisgrid.py#L1428-L1433

> Also, to confirm: we don't want to add `tick_params()` to `JointGrid`?

Yeah I think it's fine not to add that right now.

**Comment by stefmolin** [comment]
Gotcha. Looping over the axes doesn't affect an axis that has been hidden:

```python
import seaborn as sns

penguins = sns.load_dataset('penguins')

g = sns.PairGrid(penguins, diag_sharey=False, corner=True)
g.map_lower(sns.scatterplot)
g.map_diag(sns.kdeplot)
g.tick_params(direction='in', length=6, width=2, color='blue')
```
<img width="673" alt="Screen Shot 2022-08-06 at 8 47 55 PM" src="https://user-images.githubusercontent.com/24376333/183270428-560914a3-08bf-4e82-b245-5b5dc48d26f6.png">
