### ISSUE TITLE
Suggestion: allow a dictionary as input to boxplot

### ISSUE THREAD

**Issue by jhncls** [mwaskom/seaborn#2494]
(Tested with Seaborn 0.11.1)
Some functions, e.g. `lineplot` allow a dictionary as input:
```
import seaborn as sns
import numpy as np

a = np.random.randn(100)
b = np.random.randn(120)
data_dict = {'a': a, 'b':b}
sns.lineplot(data=data_dict)
```
This does not work with e.g. `sns.boxplot(data_dict)` which gives "KeyError: 0". Converting the dictionary to a list, or in case all arrays have the same length, converting to a dataframe generates the expected plot.
```
ax = sns.boxplot(data=[v for v in data_dict.values()])
ax.set_xticklabels([k for k in data_dict.keys()])
```
Something similar could work for stripplot, swarmplot, violinplot and barplot. (It already works for scatterplot and kdeplot).

**Comment by mwaskom** [comment]
That's (part of) what https://github.com/mwaskom/seaborn/issues/2429 is all about.

`boxplot` hasn't been refactored yet, but `stripplot` and `swarmplot` have:

```
# Requires 0.12.0.dev0
sns.swarmplot(data=data_dict)
```
![image](https://user-images.githubusercontent.com/315810/109694932-526b4680-7b59-11eb-98bb-64c2e34ad418.png)
