### ISSUE TITLE
Pairplot is missing second curve on the diagonal

### ISSUE THREAD

**Issue by paddyroddy** [mwaskom/seaborn#2497]
This first plot I think must have been run on an old version of `seaborn`?
![image (9)](https://user-images.githubusercontent.com/15052188/110098570-428d7580-7d98-11eb-93fb-c0e8365a1f7c.png)

This is what happens when I run it now with `seaborn==0.11.1`
![image (10)](https://user-images.githubusercontent.com/15052188/110098584-44573900-7d98-11eb-839f-09c116d9b0e7.png)

I've copied the example code from our coursework:
```
from astroML.datasets import fetch_rrlyrae_combined
import pandas as pd
import seaborn as sns

X, y = fetch_rrlyrae_combined()
cols=['u-g', 'g-r', 'r-i', 'i-z']
X_pd = pd.DataFrame(X, columns=cols)
y_pd = pd.Series(y)
y_df = pd.DataFrame(y_pd, columns=['target'])
X_pd_all = pd.concat([X_pd, y_df], axis = 'columns')
description_df = pd.DataFrame({'target': [0.0, 1.0], 
                               'target description': ['Background', 'RR Lyrae']}, 
                              columns=['target', 'target description'])
X_pd_merge = pd.merge(X_pd_all, description_df)
sns.pairplot(X_pd_merge, vars=cols, hue='target description', markers='.', height=2.0)
```

**Comment by mwaskom** [comment]
Try `sns.pairplot(..., diag_kws={"common_norm": False})`

**Comment by paddyroddy** [comment]
> Try `sns.pairplot(..., diag_kws={"common_norm": False})`

yep that works

**Comment by mwaskom** [comment]
The other curve is there, but the base rate of your two classes is very different and so it's hard to see when the KDE is jointly normalized.

Which representation is better for your dataset is a question you'll need to ask yourself.

**Comment by paddyroddy** [comment]
Okay, thanks. But did the default behaviour change between versions? The point of the question is about class imbalance. The solutions must be with an older version, and as far as I'm aware the data hasn't changed.

**Comment by mwaskom** [comment]
Yes.

**Comment by paddyroddy** [comment]
Okay, thank you. I didn't write this coursework so wasn't sure. I'll close this issue.
