### ISSUE TITLE
Something similar to relplot and displot for plotting boxplot with Seaborn

### ISSUE THREAD

**Issue by balandongiv** [mwaskom/seaborn#2498]
In Seaborn [relplot][1] and [displot][2], there are setting called `col_wrap` that  enable multiple axes arrayed in a grid of rows and columns that correspond to levels of variable.

While the `relplot` having the option to `plot` `scatter` and `line`, the `displot` have the option to plot `hist`, `kde`, `ecdf`.

Currently, I have to rely on the following code to plot grid of rows and columns that correspond to levels of variable

    import matplotlib.pyplot as plt
    
    import seaborn as sns
    sns.set(style="ticks")
    tips = sns.load_dataset("tips")
    plt.figure(figsize=(15,10))
    variables=['Lunch','Dinner']
    for i, c in enumerate(variables, 1):
        filter_ch = tips ["time"].isin ( [c] )
        dv = tips [filter_ch].reset_index ( drop=True )
        plt.subplot(2,1,i)
        g = sns.boxplot(x='sex', y="total_bill",hue='day',data=dv)
    
    
    plt.show()

I have search the net for something similar `relplot` and `displot`, but to no avail. Should such approach exist, really appreciate if someone can direct me to the appropriate material.

  [1]: https://seaborn.pydata.org/generated/seaborn.relplot.html
  [2]: https://seaborn.pydata.org/generated/seaborn.displot.html

**Comment by mwaskom** [comment]
I believe you are looking for [`catplot`](https://seaborn.pydata.org/generated/seaborn.catplot.html):

```python
sns.catplot(data=tips, x="sex", y="total_bill", hue="day", col="time", kind="box")
```
![image](https://user-images.githubusercontent.com/315810/110144088-f21d1480-7da5-11eb-8c34-a4cb578fe5c8.png)

**Comment by balandongiv** [comment]
Great,
