### ISSUE TITLE
Supress Warnings in library

### ISSUE THREAD

**Issue by lingpri** [mwaskom/seaborn#2499]
Thanks for a great library. please suppress the warnings below. 

**Example :** 

`sns.pairplot(df_centroids, hue="CUST_ID_NEW",palette="bright", height=2, aspect=1)`

seaborn version : 0.11.1
matplotlib:3.2.2

```
/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.7/dist-packages/seaborn/distributions.py:306: UserWarning: Dataset has 0 variance; skipping density estimate.
  warnings.warn(msg, UserWarning)
```

**Comment by mwaskom** [comment]
These warnings are being issued by seaborn, because the alternative is that the kdeplot would have a missing dataset with no explanation. I also find warnings a bit annoying and wish that Python gave more control over them, but I think silence would cause more confusion on balance.

**Comment by mwaskom** [comment]
Your issue does not provide any other context about what you are doing, but if you have mostly single observations for each level of your hue variable, you may want to add `diag_kws={"hue": None, "color": ".2"}` so that the diagonal plot are not broken down by hue.

**Comment by mwaskom** [comment]
I would probably be open to a `warn_singular` option in kdeplot, with a default of `True`, and *maybe* open to making the default `False` in a `pairplot` context.

**Comment by mwaskom** [comment]
Another option would be to make the kdeplot warning an instance of a more specific class and then have pairplot ensure that it's issued only once per call.

**Comment by lingpri** [comment]
> These warnings are being issued by seaborn, because the alternative is that the kdeplot would have a missing dataset with no explanation. I also find warnings a bit annoying and wish that Python gave more control over them, but I think silence would cause more confusion on balance.

`The WARN level is the level that should be active in production systems by default`. 
Ref: https://reflectoring.io/logging-levels/#warn.

**Comment by mwaskom** [comment]
That's true when using the Python `logging` module, but the standard practice in the PyData library ecosystem is to use the `warnings` module for sub-exception-level user feedback. That's class-based and so in some ways more flexible than logging, but it's still hard to ignore specific warnings that you don't care about if they don't have a unique warning class.

**Comment by Haoping-Xiao** [comment]
> Your issue does not provide any other context about what you are doing, but if you have mostly single observations for each level of your hue variable, you may want to add `diag_kws={"hue": None, "color": ".2"}` so that the diagonal plot are not broken down by hue.

![image](https://user-images.githubusercontent.com/25631347/116129694-11179300-a6d3-11eb-84fb-73fd9236bbd7.png)
I have similar issue. But what if I would like to show three univariate distribution on the diagonal

**Comment by mwaskom** [comment]
How are you planning to define the "three univariate distributions"? Your `t` variable looks likes like a continuous numeric value that likely has unique values for each observation.

**Comment by Haoping-Xiao** [comment]
> How are you planning to define the "three univariate distributions"? Your `t` variable looks likes like a continuous numeric value that likely has unique values for each observation.
> 
> (PS Please don't post screenshots of code).

Thanks for reminding me. What I want to show is, diagonal images shows three univariate distribution 'x','y','z'. And off-diagonal images should display two variables as coordinate combinations and use t as color.

**Comment by mwaskom** [comment]
> Diagonal images shows three univariate distribution 'x','y','z'. And off-diagonal images should display two variables as coordinate combinations and use t as color.

I would say that is what you are getting in the first plot you showed. Are you expecting each plot on the diagonal of the grid to show *all* of the variables? That is not what is happening in the example from the documentation that you shared.

**Comment by Haoping-Xiao** [comment]
Thanks. Now I understand.

**Comment by mwaskom** [comment]
I guess you could make the plot you want by doing something like this:

```python
penguins = sns.load_dataset("penguins")
g = sns.pairplot(penguins, hue="body_mass_g", diag_kws=dict(hue=None))

diag_cols = ["bill_length_mm", "bill_depth_mm", "flipper_length_mm"]
for ax in g.diag_axes:
    ax.clear()
    sns.kdeplot(data=penguins[diag_cols], legend=False, ax=ax)
    ax.set_axis_off()
```
![image](https://user-images.githubusercontent.com/315810/116135720-6fc31980-a69f-11eb-8ede-1cc8cb5fbf5d.png)


I'm not sure it makes much sense, though...

**Comment by Haoping-Xiao** [comment]
No. I misunderstood the diagonal images. Actually, what I need is one distribution. In the example image from documentation, it has 3 classes and thus it is able to plot three distributions. But since I have a unique 't', what I need is one distribution.
