### ISSUE TITLE
regplot label doesn't seem to work?

### ISSUE THREAD

**Issue by songololo** [mwaskom/seaborn#250]
The API reference shows that the regplot function can plot a label. However, I can't seem to get the label to appear, whether the regression line is shown or not. Not sure if I'm doing something wrong or if this is a bug?

sns.regplot(x, y, ax=ax, dropna=True, label='label')

**Comment by eamanu** [comment]
I think that the solution  `ax.legend(loc="best")` must be automatic. I lost lot of time searchin the solution of this problem.
