### ISSUE TITLE
Can you provide context for  sns.set_theme?

### ISSUE THREAD

**Issue by CatNofishing** [mwaskom/seaborn#2505]
It is not convenient for to set theme for local axes.
![image](https://user-images.githubusercontent.com/33288114/111060687-c30b4f00-84d9-11eb-9c89-f709983b29d4.png)

**Comment by mwaskom** [comment]
You can stack context managers as such:

```python
with sns.axes_style("white"), sns.color_palette("pastel"):
    sns.scatterplot(data=penguins, x="bill_length_mm", y="bill_depth_mm", hue="species")
```
![image](https://user-images.githubusercontent.com/315810/111068292-971ea800-849e-11eb-9779-9581a8828aae.png)

The main request here is tracked at #2254, so I will close.
