### ISSUE TITLE
 lmplot(sharey=False) not working

### ISSUE THREAD

**Issue by JanHomann** [mwaskom/seaborn#2509]
The following code behaves as if `sharey=True`.
(edit: actually, it does not behave the same, but it is still not rescaling the plots individually the way it should)

```
df=pd.DataFrame({'x':[1,2,3,1,2,3], 'y':[4,5,2,400,500,200], 't':[1,1,1,2,2,2]}) 
sns.lmplot(data=df, x='x', y='y', col='t', sharey=False);
```

If you do this, it suddenly works:
```
sns.lmplot(data=df, x='x', y='y', col='t', sharex=False, sharey=False);
```

Versions of seaborn and matplotlib:
```
sns.__version__ 
'0.11.1'

matplotlib.__version__
'3.3.1'
```

![image](https://user-images.githubusercontent.com/35338267/111419598-2525a900-86c0-11eb-9f22-8f0afb2f5007.png)

**Comment by mwaskom** [comment]
Worth noting: the y axes are not shared in the "wrong" plot, however the y axis autoscaling is off.

My suspicion is that this line is the culprit: https://github.com/mwaskom/seaborn/blob/master/seaborn/regression.py#L611-L616

**Comment by JanHomann** [comment]
"the y axes are not shared in the "wrong" plot"

You are right, the scales aren't actually identical. I didn't notice that.

**Comment by mwaskom** [comment]
It's fortunate as it makes the workaround (setting the ylim explicitly) a lot easier to accomplish than "unsharing" the axes, which is pretty difficult in matplotlib IIRC.
