### ISSUE TITLE
suggestion: set current ax to g.ax_joint at end of jointplot

### ISSUE THREAD

**Issue by jhncls** [mwaskom/seaborn#2511]
Tested with seaborn 0.11.1

`jointplot` (or JointGrid in general) leaves `ax_marg_y` as current axis. Some people try to use `plt.xlim()` or similar and are changing the marginal subplot instead of the main one. It could be nice to automatically set `plt.sca(g.ax_joint)` when finishing the jointplot.

Example code:
```
import matplotlib.pyplot as plt
import seaborn as sns

tips = sns.load_dataset('tips')
g = sns.jointplot(data=tips, x='total_bill', y='tip')
# plt.sca(g.ax_joint)
plt.axhline(tips['tip'].mean(), ls='--', c='r')
plt.axhspan(tips['tip'].quantile(.25), tips['tip'].quantile(.75), color='y', alpha=.3)
plt.show()
```

**Comment by mwaskom** [comment]
I think this is a good idea!

**Comment by mwaskom** [comment]
@jhncls would you like to do a PR? Should be a simple code change, but it would be good to have a small test and a mention in the release notes.

**Comment by jhncls** [comment]
OK, I'll look into it.  At first sight the only code change would be either setting `plt.sca()` at the end of JointGrid's `__init__`. Or simply change the order in which the three axes are created (and share  in the opposite direction: `ax_joint = f.add_subplot(gs[1:, :-1], sharex=ax_marg_x, sharey=ax_marg_y)`).  Just changing the order might be the simplest.

Should the function `plot_marginals` also save the current axis and set it back? By the way, a simple test of a non-seaborn function called with `plot_marginals` isn't trivial.  Also, there don't seem to be a lot of practical use cases.

**Comment by mwaskom** [comment]
I think the easiest change would be to do it at the end of `jointplot` . People who are using `JointGrid` directly are probably less likely to get bitten by this. That said, calling `plt.gca` at the end of the `JointGrid` constructor is probably fine too;  but I would worry about the unintended consequences of changing the direction of axis sharing so I'd be -1 on the second proposal.

> By the way, a simple test of a non-seaborn function called with plot_marginals isn't trivial.

A simple case would be:

    g = sns.JointGrid(data=penguins, x="bill_length_mm", y="bill_depth_mm")
    g.plot_marginals(plt.hist)

But yes, without an established API pattern for "which axis to draw the distribution on", it's harder to be generic in that function.

**Comment by jhncls** [comment]
It probably would make sense to do the same for `ax_heatmap` of `sns.clustermap`.  That way e.g. `plt.xlabel('features')` would affect the main subplot instead of the colorbar.
