### ISSUE TITLE
Pass `data` thru to axis level functions of `JointGrid`?

### ISSUE THREAD

**Issue by ivirshup** [mwaskom/seaborn#2512]
Hi, I'm wondering if it would be reasonable to pass `data` through (or at least, allow resolving values for `kwargs`) to the axis level plotting functions in `JointGrid`? Essentially, I was expecting something like this to work:

```python
import seaborn as sns
penguins = sns.load_dataset("penguins")

sns.jointplot(data=penguins, x="bill_length_mm", y="bill_depth_mm", joint_kws=dict(hue="body_mass_g"))
```

Which errors with 

```pytb
ValueError: Could not interpret value `body_mass_g` for parameter `hue`
```

This can be worked around with: `joint_kws=dict(hue=penguins["body_mass_g"])`, but I think it could be a bit more elegant.

What do you think?

**Comment by mwaskom** [comment]
I'm not sure if there would be unanticipated consequences to worry about, and the workaround (passing as a vector) is only a little bit cumbersome, but I think this is probably fine?

**Comment by mwaskom** [comment]
I think this is only slightly more complicated:

```python
sns.jointplot(
    data=penguins,
    x="bill_length_mm", y="bill_depth_mm",
    joint_kws=dict(hue=penguins["body_mass_g"])
)
```

I'm going to close for now. Injecting `data` may or may not be a good idea and this seems like it has a pretty easy workaround.
