### ISSUE TITLE
histplot with small bins becames black by cluttering of rectangle edges when using x axis in log scale

### ISSUE THREAD

**Issue by mgab** [mwaskom/seaborn#2513]
### Description
When increasing the number of values on a 1D histogram, the number of bins increase and they become smaller. In general, when that happens the rectangle edges disappear so that the distribution preserves the colour of the rectangles.

When using logarithmic scale for the x axis, however, the rectangle edges are maintained and the distribution ends up appearing black.

### Versions
seaborn 0.11.1
matplotlib 3.3.3

### Example

```python
fig, axs = plt.subplots(ncols=3, nrows=2, figsize=(12,6))

vals = np.random.randn(1000)
sns.histplot(x=vals, log_scale=(False, False), ax=axs[0, 0])
sns.histplot(x=10**vals, log_scale=(True, False), ax=axs[1, 0])

vals = np.random.randn(10000)
sns.histplot(x=vals, log_scale=(False, False), ax=axs[0, 1])
sns.histplot(x=10**vals, log_scale=(True, False), ax=axs[1, 1])

vals = np.random.randn(1000000)
sns.histplot(x=vals, log_scale=(False, False), ax=axs[0, 2])
sns.histplot(x=10**vals, log_scale=(True, False), ax=axs[1, 2])

plt.tight_layout()
```

![histplot_black](https://user-images.githubusercontent.com/6085431/111771649-3af7c180-88ac-11eb-9028-9c4fa6fe6ddf.png)

**Comment by mwaskom** [comment]
Note that you can work around this by forcing the `linewidth` parameter to a specific value.

My guess is that the auto linewidth code is working with the data in the log domain...

**Comment by mwaskom** [comment]
BTW you don't need to specify `log_scale=(True, False)` for univariate histograms ... if you just write `log_scale=True` it will know you mean to log scale the data axis. (It doesn't hurt anything to explicitly specify both, just more typing for you).
