### ISSUE TITLE
Using dataframe with duplicate index raises ValueError: cannot reindex from a duplicate axis

### ISSUE THREAD

**Issue by jhncls** [mwaskom/seaborn#2515]
Tested with seaborn's latest dev version, pandas 1.2.3.

Dataframes can have indices with repeated entries. For example, `df.explode` which converts lists in cells into separate rows, keeps the original indices.  Some seaborn functions generate an error `ValueError: cannot reindex from a duplicate axis` with such dataframes.  `lineplot`, `stripplot`, `swarmplot` give such error.  `pointplot`, `barplot` and `boxplot` work without problem.

Calling `.reset_index()` makes the problem go away.
```
import` pandas as pd
import seaborn as sns

df = pd.DataFrame({'x': [1, 2],
                   'val': [[3, 4, 5], [6, 7]] })
sns.stripplot(data=df.explode('val'), x='x', y='val')
```
In seaborn 0.11.1 this same problem doesn't seem to exist. 

PS: `sns.violinplot(data=df.explode('val').reset_index(), x='x', y='val')` gives a complete different error, although something similar to `boxplot` would be expected (`TypeError: No loop matching the specified signature and casting was found for ufunc add`, during a call to `gaussian_kde`, numpy version `1.20.1`, scipy `1.5.2`).

**Comment by mwaskom** [comment]
Full traceback :

<details>

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-8277e14c43f9> in <module>
      4 df = pd.DataFrame({'x': [1, 2],
      5                    'val': [[3, 4, 5], [6, 7]] })
----> 6 sns.stripplot(data=df.explode('val'), x='x', y='val')

~/code/seaborn/seaborn/_decorators.py in inner_f(*args, **kwargs)
     44             )
     45         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 46         return f(**kwargs)
     47     return inner_f
     48 

~/code/seaborn/seaborn/categorical.py in stripplot(x, y, hue, data, order, hue_order, jitter, dodge, orient, color, palette, size, edgecolor, linewidth, ax, hue_norm, fixed_scale, formatter, **kwargs)
   2795     )
   2796 
-> 2797     p.plot_strips(
   2798         jitter=jitter,
   2799         dodge=dodge,

~/code/seaborn/seaborn/categorical.py in plot_strips(self, jitter, dodge, color, edgecolor, plot_kws)
    225     ):
    226 
--> 227         width = .8 * self._native_width
    228         offsets = self._nested_offsets(width, dodge)
    229 

~/code/seaborn/seaborn/categorical.py in _native_width(self)
    191     def _native_width(self):
    192         """Return unit of width separating categories on native numeric scale."""
--> 193         unique_values = np.unique(self.comp_data[self.cat_axis])
    194         if len(unique_values) > 1:
    195             native_width = np.nanmin(np.diff(unique_values))

~/code/seaborn/seaborn/_core.py in comp_data(self)
   1099                     if converter.get_scale() == "log":
   1100                         comp = np.log10(comp)
-> 1101                     comp_col.loc[orig.index] = comp
   1102 
   1103                 comp_data.insert(0, var, comp_col)

~/miniconda3/envs/seaborn-py38-latest/lib/python3.8/site-packages/pandas/core/indexing.py in __setitem__(self, key, value)
    668 
    669         iloc = self if self.name == "iloc" else self.obj.iloc
--> 670         iloc._setitem_with_indexer(indexer, value)
    671 
    672     def _validate_key(self, key, axis: int):

~/miniconda3/envs/seaborn-py38-latest/lib/python3.8/site-packages/pandas/core/indexing.py in _setitem_with_indexer(self, indexer, value)
   1790                 # setting for extensionarrays that store dicts. Need to decide
   1791                 # if it's worth supporting that.
-> 1792                 value = self._align_series(indexer, Series(value))
   1793 
   1794             elif isinstance(value, ABCDataFrame):

~/miniconda3/envs/seaborn-py38-latest/lib/python3.8/site-packages/pandas/core/indexing.py in _align_series(self, indexer, ser, multiindex_indexer)
   1909             # series, so need to broadcast (see GH5206)
   1910             if sum_aligners == self.ndim and all(is_sequence(_) for _ in indexer):
-> 1911                 ser = ser.reindex(obj.axes[0][indexer[0]], copy=True)._values
   1912 
   1913                 # single indexer

~/miniconda3/envs/seaborn-py38-latest/lib/python3.8/site-packages/pandas/core/series.py in reindex(self, index, **kwargs)
   4397     )
   4398     def reindex(self, index=None, **kwargs):
-> 4399         return super().reindex(index=index, **kwargs)
   4400 
   4401     def drop(

~/miniconda3/envs/seaborn-py38-latest/lib/python3.8/site-packages/pandas/core/generic.py in reindex(self, *args, **kwargs)
   4450 
   4451         # perform the reindex on the axes
-> 4452         return self._reindex_axes(
   4453             axes, level, limit, tolerance, method, fill_value, copy
   4454         ).__finalize__(self, method="reindex")

~/miniconda3/envs/seaborn-py38-latest/lib/python3.8/site-packages/pandas/core/generic.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   4470 
   4471             axis = self._get_axis_number(a)
-> 4472             obj = obj._reindex_with_indexers(
   4473                 {axis: [new_index, indexer]},
   4474                 fill_value=fill_value,

~/miniconda3/envs/seaborn-py38-latest/lib/python3.8/site-packages/pandas/core/generic.py in _reindex_with_indexers(self, reindexers, fill_value, copy, allow_dups)
   4513 
   4514             # TODO: speed up on homogeneous DataFrame objects
-> 4515             new_data = new_data.reindex_indexer(
   4516                 index,
   4517                 indexer,

~/miniconda3/envs/seaborn-py38-latest/lib/python3.8/site-packages/pandas/core/internals/managers.py in reindex_indexer(self, new_axis, indexer, axis, fill_value, allow_dups, copy, consolidate)
   1274         # some axes don't allow reindexing with dups
   1275         if not allow_dups:
-> 1276             self.axes[axis]._can_reindex(indexer)
   1277 
   1278         if axis >= self.ndim:

~/miniconda3/envs/seaborn-py38-latest/lib/python3.8/site-packages/pandas/core/indexes/base.py in _can_reindex(self, indexer)
   3281         # trying to reindex on an axis with duplicates
   3282         if not self.is_unique and len(indexer):
-> 3283             raise ValueError("cannot reindex from a duplicate axis")
   3284 
   3285     def reindex(self, target, method=None, level=None, limit=None, tolerance=None):

ValueError: cannot reindex from a duplicate axis
```

</details>

**Comment by jhncls** [comment]
Some more testing shows that the main problem is that `df.explode('val')`  creates a column of type "object" (because originally it was of that type). Converting to numeric solves the problem.  It is strange that some seaborn functions do this conversion automatically and others don't. So, in reality things can go wrong with pandas series of type "object" which happen to contain only numbers.  Not sure whether you want to convert them, or give a warning.

**Comment by mwaskom** [comment]
By "the main problem" do you mean the duplicate axis error or the ufunc add error?

**Comment by jhncls** [comment]
Well, converting the exploded column to numeric solves both problems. The repeated index isn't a problem. So the title of the issue should be: can seaborn automatically convert pandas series of type object but with only numeric values automatically to a numeric dtype? Or at least give a suitable error message?

So, this works fine(without `.astype(float)` weird error messages appear for both):
```python
import pandas as pd
import seaborn as sns

df = pd.DataFrame({'x': ['A', 'B'],
                   'val': [[3, 4, 5], [6, 7]]})
dfe = df.explode('val')
dfe['val'] = dfe['val'].astype(float)
sns.lineplot(data=dfe, x='x', y='val')
sns.violinplot(data=dfe, x='x', y='val')
```

**Comment by mwaskom** [comment]
I'm not replicating it working fine on master; I get the traceback that I quoted earlier even if the `"val"` column is explicitly encoded as float.

**Comment by mwaskom** [comment]
By the way the traceback is actually originating from the code that is ensuring that data is converted to float before doing math on it ... but I think that's entirely coincidental.

The forward-looking issue is how to handle data with a duplicated index.

FWIW `df.explode` behavior here feels slightly broken, as the pandas index is meant to act like a primary key. So while it's possible to do user operations that cause a duplicated index, it's weird to have that happen as the default output of a dataframe method.

**Comment by jhncls** [comment]
Oops, I was testing with a wrong version.  Converting to float solves the problem with violinplot, but the lineplot etc. still doesn't like the repeated index. I'll change the title back to the original.  The problem with violinplot would be a different issue. 

`pd.explode` is just one way of getting a repeated index, there might be other ways someone unknowingly ends up with such an index.

Here is an example with `melt(ignore_index=False)` with the same crash:
```
import pandas as pd
import seaborn as sns
df = pd.DataFrame({'A': [3, 4, 5],
                   'B': [6, 7, 8]},
                  index=[100, 200, 300]).melt(ignore_index=False)
sns.lineplot(data=df, x='variable', y='value')
```

**Comment by mwaskom** [comment]
Agreed, it's certainly possible to end up with them: but in that case you are explicitly asking for them, which seems different from the default behavior creating them. (Though `pandas.concat` creates duplicates by default in normal workflows too).

In any case, whether or not this method is behaving well, certainly they exist.

The ["official" pandas position]( https://pandas.pydata.org/pandas-docs/stable/user_guide/duplicates.html) on duplicates is that they are allowed in the index because pandas is meant to be used for cleaning "messy" data and messy data often has duplicates where there shouldn't be any.

So the question is whether seaborn needs to work around duplicates if present, or if it's ok for seaborn to consider a dataframe with index duplicates "non-tidy" and refuse to work with it. Although, in that case, there should be explicit detection and a clear error raised by seaborn.

**Comment by JamesRaynor67** [comment]
I still encounter this issue in 0.12.2. I resolved it by downgrade seaborn package version to 0.11 without changing any code.
