### ISSUE TITLE
Multiple categorical function calls set categorical axis limits incorrectly

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#2516]
This pertains to the "new" categorical behavior (i.e. the updates to `stripplot` and `swarmplot` post v0.11.1 release).

```python
ax = sns.stripplot(x=["A", "B", "C"], y=[1, 3, 2])
ax = sns.stripplot(x=["E", "F"], y=[5, 2])
ax.set_xlim(-.5, 4.5)  # Should not be needed
```

Without setting the `xlim` explicitly, it shows only the first two categorical positions.

Note that the data and labels are correct – unlike with the old cateogorical plots. But the default axis limits are wrong.

**Comment by jhncls** [comment]
Maybe in `_CategoricalPlotterNew._adjust_cat_axis`: 
```
ax.set_xlim(-.5, len(ax.xaxis.units._mapping) - .5, auto=None)
```

**Comment by mwaskom** [comment]
Can't use the private attribute, unfortunately. The basic idea is right, but it will be a little trickier.

**Comment by jhncls** [comment]
So, maybe
```
ax.set_xlim(-.5, max(ax.xaxis.converter.convert(order, ax.xaxis.units, ax)) + .5, auto=None)
```
or just
```
ax.set_xlim(-.5, ax.xaxis.converter.convert(order[-1], ax.xaxis.units, ax) + .5, auto=None)
```

**Comment by jhncls** [comment]
It seems `ax.xaxis.converter` can be None with a shared x-axis (as in a `catplot`). These things get complicated quite quickly.

**Comment by mwaskom** [comment]
Yeah there's some tricky business where the actual axis object that is relevant for each axes in a potential facet grid context gets tracked: https://github.com/mwaskom/seaborn/blob/master/seaborn/_core.py#L1182

**Comment by mwaskom** [comment]
The problem with the other suggestion is that the second call defines `order` for itself, but it doesn't know about the `order` that the original call used, so you sort of end up in the same place.

**Comment by jhncls** [comment]
`stripplot` also seems to have no own influence on the limits, e.g. (with dev version):
```python
fig, axs = plt.subplots(1,2,figsize=(12,3))
for ax in axs:
    sns.stripplot(x=["A", "B", "C"], y=[1, 3, 2], ax=ax)
    sns.lineplot(x=["A", "B", "C"], y=[2.5, 2.5, 2.5], color='r', ls='--', ax=ax)
axs[1].set_ylim(0, 4)
```
Gives:
![image](https://user-images.githubusercontent.com/19649483/114328273-5ddc6500-9b3c-11eb-8e31-f054a1d03586.png)

A trick could be to add some invisible rectangle behind the stripplot to enforce these limits? Or maybe such rectangles have other drawbacks, such as popping up in vector file exports?

Or maybe there is another way to tell matplotlib to take into account the bounding box of the PathCollection?
