### ISSUE TITLE
Allow xlim as parameter for lmplot

### ISSUE THREAD

**Issue by jhncls** [mwaskom/seaborn#2518]
Seaborn versions: latest dev version and 0.11.1

`lmplot` doesn't seem to accept the `xlim=` parameter, although FacetGrid does.

Use case: when `truncate=False`, the regression lines are extrapolated until they touch the current xlims.  If one afterwards want to extend these xlims, the regression lines are floating again.  A workaround is either to call FacetGrid and regplot separately, or to set very wide xmargins via the rcParams.

Example code.
```
import seaborn as sns
import matplotlib as mpl

tips = sns.load_dataset('tips')
# mpl.rcParams['axes.xmargin'] = 0.5  # set very wide margins: 50% of the actual range
g = sns.lmplot(x="total_bill", y="tip", col="smoker", data=tips, truncate=False, xlim=(0, 80))
# mpl.rcParams['axes.xmargin'] = 0.05 # set the margins back to the default
g.set(xlim=(0, 80))
```

**Comment by mwaskom** [comment]
What should really happen is that `lmplot` should accept a `facet_kws` dictionary that it passes to `FacetGrid` to set it up. Also then some of the parameters of lmplot that are passed directly should be deprecated with the instruction that they should be packaged in `facet_kws` (not all of them, but less-often-used ones).

Unfortunately I have not been especially consistent across the figure-level functions with which `FacetGrid` parameters do or do not end up i the figure-level function signature. This would probably be good to standardize, but that might involve a lot of annoying deprecation.
