### ISSUE TITLE
Citing seaborn

### ISSUE THREAD

**Issue by diego0020** [mwaskom/seaborn#252]
Do you have any paper that could be cited when writing about a project that uses seaborn?

**Comment by caryan** [comment]
Just in case someone else finds this issue through a search: you can now cite Seaborn through this [DOI](http://dx.doi.org/10.5072/zenodo.12710).

**Comment by weiHelloWorld** [comment]
@caryan @mwaskom   Is there any formal bibtex entry for seaborn?

**Comment by caryan** [comment]
@weiHelloWorld you should point to Seaborn 0.8.1 at [Zenodo](https://zenodo.org/record/883859#.WepZ2nBlCV4). At the bottom right on that page in the  "Export" section  you'll find a link to a  Bibtex entry.

**Comment by weiHelloWorld** [comment]
@caryan Thank you!

**Comment by tsherwen** [comment]
I found this thread whilst trying to find a .bib entry for Seaborn and wanted to add what I found useful:

The DOI has been updated [see zenodo page linked here](https://zenodo.org/record/883859#.Wp0boBfeAWo) 

This summary page on the scipy website on: ["Citing packages in the SciPy ecosystem"](https://www.scipy.org/citing.html#citing-packages-in-the-scipy-ecosystem)

**Comment by rmukaila** [comment]
@tsherwen  thanks man!
