### ISSUE TITLE
stat_func not recognized in jointplot()

### ISSUE THREAD

**Issue by cpdboper** [mwaskom/seaborn#2520]
When trying to use stat_func in jointplot() in version 0.11.1 (matplotlib 3.3.4), the below code returns the error:

    AttributeError: 'PathCollection' object has no property 'stat_func'

Code to replicate:

    import pandas as pd
    from pandas import Series,DataFrame
    import numpy as np
    import scipy.stats as stats
    import matplotlib.pyplot as plt
    import seaborn as sns
    from pandas_datareader import DataReader
    from datetime import datetime
    
    tickers = ['AAPL','MSFT']
    end = datetime.now()
    start = datetime(end.year-1,end.month,end.day)
    tickers_df = DataReader(tickers,'yahoo',start,end)['Adj Close']
        
    sns.jointplot(x='AAPL',y='MSFT',data=tickers_df,kind='scatter',stat_func=stats.pearsonr)

Plot returned in 0.11.1 after the error:
![image](https://user-images.githubusercontent.com/79300080/112236919-ee97e300-8c17-11eb-9005-664ca350f877.png)

Plot returned in 0.10.1:
![image](https://user-images.githubusercontent.com/79300080/112237580-56026280-8c19-11eb-91f5-1099f65039ff.png)

The 0.10.1 plot also gives the following warning:

    UserWarning: JointGrid annotation is deprecated and will be removed in a future release.
      warnings.warn(UserWarning(msg))

I read the release notes for 0.11.0 and 0.11.1, but I couldn't find anything regarding changes to stat_func.  Was stat_func intentionally deprecated alongside the .annotate() method?  If so, what is the alternative to this?

**Comment by mwaskom** [comment]
Yes, `stat_func` is one of the "related parameters" mention in this release note bullet:

> API Final removal of the previously-deprecated annotate method on JointGrid, along with related parameters.

Sorry that isn't more clear; though there was the deprecation warning you mention.

The alternative is to add whatever text you want to the axes with (if `g` is the variable name for the object that `jointplot` returns) `g.ax_joint.text`.

**Comment by cpdboper** [comment]
Thanks Michael!

**Comment by cpdboper** [comment]
For anyone who finds this and is wondering, the below code gets me the desired result in 0.11.1 in my specific example (x and y coords are based on the axes so the offsets will depend on your axis values, I do not know how to change this).

    import pandas as pd
    from pandas import Series,DataFrame
    import numpy as np
    import scipy.stats as stats
    import matplotlib.pyplot as plt
    import seaborn as sns
    from pandas_datareader import DataReader
    from datetime import datetime
    
    tickers = ['AAPL','MSFT']
    end = datetime.now()
    start = datetime(end.year-1,end.month,end.day)
    tickers_df = DataReader(tickers,'yahoo',start,end)['Adj Close']
        
    pearson,p = stats.pearsonr(tickers_df['AAPL'].dropna(),tickers_df['MSFT'].dropna())
    pearson = round(pearson,2)
    p = '{:.2e}'.format(p)
    sns.jointplot(x='AAPL',y='MSFT',data=tickers_df,kind='scatter').ax_joint.text(
        s=f' pearsonr = {pearson}; p = {p} ',ha='left',va='top',x=55,y=245,
        bbox={'boxstyle':'round','pad':0.25,'facecolor':'white','edgecolor':'gray'})

![image](https://user-images.githubusercontent.com/79300080/112246009-61a95580-8c28-11eb-9d3f-c96c0ba7d4d3.png)

**Comment by mwaskom** [comment]
you can pass `transform=ax.transAxes` to `ax.text` and it will interpret the coordinates as a normalized position within the axes, i.e. (0, 0) is lower left, (1, 1) is upper right, etc.

**Comment by cpdboper** [comment]
Thanks Michael, below code returns the result independent of axis values now.  I appreciate all the help!

    import pandas as pd
    from pandas import Series,DataFrame
    import numpy as np
    import scipy.stats as stats
    import matplotlib.pyplot as plt
    import seaborn as sns
    from pandas_datareader import DataReader
    from datetime import datetime
    
    tickers = ['AAPL','MSFT']
    end = datetime.now()
    start = datetime(end.year-1,end.month,end.day)
    tickers_df = DataReader(tickers,'yahoo',start,end)['Adj Close']
    
    pearson,p = stats.pearsonr(tickers_df['AAPL'].dropna(),tickers_df['MSFT'].dropna())
    pearson = round(pearson,2)
    p = '{:.2e}'.format(p)
    g = sns.jointplot(x='AAPL',y='MSFT',data=tickers_df,kind='scatter')
    g.ax_joint.text(
        s=f' pearsonr = {pearson}; p = {p} ',x=.05,y=.95,transform=g.ax_joint.transAxes,
        bbox={'boxstyle':'round','pad':0.25,'facecolor':'white','edgecolor':'gray'})

![image](https://user-images.githubusercontent.com/79300080/112248318-1b55f580-8c2c-11eb-9a05-c9b99470cc25.png)
