### ISSUE TITLE
importerror: cannot import name 'qual_palettes'

### ISSUE THREAD

**Issue by wjrforcyber** [mwaskom/seaborn#2521]
**When I use Anaconda JupyterNotebook, I import this seaborn but there are something wrong with this 'QUAL_PALETTES',  I tried install palettes but it still doesn't work. There was little solution when I googled.**

```
ImportError                               Traceback (most recent call last)
<ipython-input-108-c7666d0a9133> in <module>()
     46 from sklearn.linear_model import LassoCV
     47 
---> 48 import seaborn as sns
     49 
     50 import mglearn

D:\anaconda\envs\tensorflow\lib\site-packages\seaborn\__init__.py in <module>()
      3 from .utils import *  # noqa: F401,F403
      4 from .palettes import *  # noqa: F401,F403
----> 5 from .relational import *  # noqa: F401,F403
      6 from .regression import *  # noqa: F401,F403
      7 from .categorical import *  # noqa: F401,F403

D:\anaconda\envs\tensorflow\lib\site-packages\seaborn\relational.py in <module>()
      6 import matplotlib.pyplot as plt
      7 
----> 8 from ._core import (
      9     VectorPlotter,
     10 )

D:\anaconda\envs\tensorflow\lib\site-packages\seaborn\_core.py in <module>()
     15     share_init_params_with_map,
     16 )
---> 17 from .palettes import (
     18     QUAL_PALETTES,
     19     color_palette,

ImportError: cannot import name 'QUAL_PALETTES'
```

**Comment by mwaskom** [comment]
What version of seaborn do you have installed? How did you install it?

**Comment by wjrforcyber** [comment]
> What version of seaborn do you have installed? How did you install  @mwaskom 
Thanks for your reply.
I tried both in conda terminal:
```
pip install seaborn
conda install seaborn
```
They didn't work...
These are some info about my env:
```
(tensorflow) C:\Users\dell>conda -V
conda 4.5.4
(tensorflow) C:\Users\dell>python --version
Python 3.6.12 :: Anaconda, Inc.
(tensorflow) C:\Users\dell>conda list seaborn
# packages in environment at D:\anaconda\envs\tensorflow:
#
# Name                    Version                   Build  Channel
seaborn                   0.11.1                    <pip>
seaborn                   0.8                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free


```

**Comment by mwaskom** [comment]
By using both conda and pip, it looks like you've ended up with multiple installs of seaborn in the same environment. That will cause problems. I would definitely remove version 0.8 (looks like conda installed that, so `conda remove seaborn`). It might make sense to run `conda remove seaborn` and `pip remove seaborn` iteratively until both report that seaborn is not installed. Then do a fresh install (but just once!).

**Comment by wjrforcyber** [comment]
> By using both conda and pip, it looks like you've ended up with multiple installs of seaborn in the same environment. That will cause problems. I would definitely remove version 0.8 (looks like conda installed that, so `conda remove seaborn`). It might make sense to run `conda remove seaborn` and `pip remove seaborn` iteratively until both report that seaborn is not installed. Then do a fresh install (but just once!).

I have removed both of them and installed once and once only in `pip install seaborn`
But it still shows the same error `ImportError: cannot import name 'QUAL_PALETTES'`

My env:
```
(tensorflow) C:\Users\dell>conda list seaborn
# packages in environment at D:\anaconda\envs\tensorflow:
#
# Name                    Version                   Build  Channel
seaborn                   0.11.1                    <pip>
```

**Comment by mwaskom** [comment]
Did you restart your kernel?

**Comment by wjrforcyber** [comment]
> Did you restart your kernel?

Thanks! After I restart the kernal it works fine now!
