### ISSUE TITLE
Can't set log scale for integer values.

### ISSUE THREAD

**Issue by Josef-Vonasek** [mwaskom/seaborn#2524]
Using log scale on integer columns

```python
plt.yscale('log')
snt.lineplot(data, x='X', y='Y')
```

throws `'int' object has no attribute 'log10'` exception.

**Comment by mwaskom** [comment]
Hi, please provide a fully runnable example and information about versions, etc., as requested [here](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs). Thanks!

**Comment by jhncls** [comment]
This problem doesn't seem reproducible with current versions of Seaborn. Logscale seems to work perfectly fine also with integer data, as long as everything is are strictly positive.

**Comment by mwaskom** [comment]
I'm going to close this as having insufficient information, but please ping if you can make a reproducible example demonstrating the problem with the current version of seaborn.
