### ISSUE TITLE
Look into using new "subfigure" concept in matplotlib for combining figure-level plots

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#2525]
https://matplotlib.org/devdocs/gallery/subplots_axes_and_figures/subfigures.html

This is a new feature in matplotlib and may smooth the path for embedding the output of a figure-level function in a larger figure.

There would still be some challenges with, e.g., putting the legend outside of the plot. But it seems better than previous proposals that fundamentally rely on hacks.

**Comment by tdy** [comment]
What was the final verdict on this? I assume it wasn't positive since this got closed, but just curious what the overall conclusions were.
