### ISSUE TITLE
Function to plot the residual of the partial regression

### ISSUE THREAD

**Issue by giupardeb** [mwaskom/seaborn#2526]
Hi guys, In your library I found this [function](https://seaborn.pydata.org/generated/seaborn.residplot.html), it allow me to plot the residuals of a linear regression. I'm looking for a function that allow me to plot the residual of the partial regression. Can you help me?

Thank you!

**Comment by mwaskom** [comment]
Hi, it's not exactly clear what you're asking for. Also this might be a [better question for StackOverflow](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#general-support)?

**Comment by giupardeb** [comment]
Yes, maybe it's better if I ask on the stackoverflow. I'm sorry, and thank you so much for your time.

**Comment by giupardeb** [comment]
I posted on the stack [overflow](https://stackoverflow.com/questions/66818492/plotting-the-residual-of-the-partial-regression-in-python)  I hope I have been clearer.
