### ISSUE TITLE
Quickstart commands fail

### ISSUE THREAD

**Issue by XavierAudier** [mwaskom/seaborn#2530]
Hi,
I installed the library through the pip install as described here: https://seaborn.pydata.org/installing.html
I ran the Quickstart command lines:

`import seaborn as sns`
`df = sns.load_dataset("penguins")`
`sns.pairplot(df, hue="species")`

The code threw a ValueError: 

`>>> sns.pairplot(df, hue="species")`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "C:\Python37\lib\site-packages\seaborn\axisgrid.py", line 2111, in pairplot`
`    grid.map_diag(kdeplot, **diag_kws)`
[...]
`  File "C:\Users\xaudier3\AppData\Roaming\Python\Python37\site-packages\numpy\lib\function_base.py", line 498, in asarray_chkfinite`
`    "array must not contain infs or NaNs")`
`ValueError: array must not contain infs or NaNs`

It's not that big of a deal, but I thought I'd report it.
Maybe someone can run the same lines on their install to confirm that it's not just faulty on my end ?
Cheers

ps: the data loads fine, and indeed has Nans

`>>> df.head()`
`  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g     sex`
`0  Adelie  Torgersen            39.1           18.7              181.0       3750.0    MALE`
`1  Adelie  Torgersen            39.5           17.4              186.0       3800.0  FEMALE`
`2  Adelie  Torgersen            40.3           18.0              195.0       3250.0  FEMALE`
`3  Adelie  Torgersen             NaN            NaN                NaN          NaN     NaN`
`4  Adelie  Torgersen            36.7           19.3              193.0       3450.0  FEMALE`

**Comment by mwaskom** [comment]
What version of seaborn? What version of matplotlib? What version of numpy?

**Comment by mwaskom** [comment]
Just confirmed that this runs fine for me in this environment:

```
$ conda list 'numpy|scipy|pandas|matplotlib|seaborn'
# packages in environment at /Users/mwaskom/miniconda3/envs/mpl34_test:
#
# Name                    Version                   Build  Channel
matplotlib                3.4.0                    pypi_0    pypi
numpy                     1.19.2           py38h456fd55_0
numpy-base                1.19.2           py38hcfb5961_0
pandas                    1.2.2            py38hb2f4e1b_0
scipy                     1.6.0            py38h2515648_0
seaborn                   0.12.0.dev0               dev_0    <develop>
```

**Comment by XavierAudier** [comment]
Tried another uninstall reinstall.
Problem solved.
Not sure what happened !
Thank you for your responsiveness regardless !
