### ISSUE TITLE
Colorbar doesn't shrink in clustermap

### ISSUE THREAD

**Issue by michaelsilverstein** [mwaskom/seaborn#2534]
While passing `cbar_kws={'shrink': .5}` to `sns.heatmap()` works, it does not change the colorbar size in clustermap. Using version 0.11.1:

```python
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

np.random.seed(123)
data = np.random.randn(50, 50)
sns.heatmap(data)
plt.show()
sns.heatmap(data, cbar_kws={'shrink': .5})
plt.show()
sns.clustermap(data)
plt.show()
sns.clustermap(data, cbar_kws={'shrink': .5})
plt.show()
```
![image](https://user-images.githubusercontent.com/22639569/113174552-7d0ff400-9218-11eb-8ddd-24cd56af1fb3.png)
![image](https://user-images.githubusercontent.com/22639569/113174591-8600c580-9218-11eb-85b5-9f6d72af7a5a.png)
![image](https://user-images.githubusercontent.com/22639569/113174607-8ac57980-9218-11eb-8627-3321ce0024f8.png)
![image](https://user-images.githubusercontent.com/22639569/113174620-8ef19700-9218-11eb-97c5-5b57c995b54a.png)

**Comment by mwaskom** [comment]
You'll want to control this with the `cbar_pos` parameter:

> cbar_pos :  tuple of (left, bottom, width, height), optional
>     Position of the colorbar axes in the figure. Setting to None will disable the colorbar.

It's demonstrated in one of the examples here: https://seaborn.pydata.org/generated/seaborn.clustermap.html

**Comment by alrichardbollans** [comment]
I was having issues with using `cbar_pos` as these settings seemed to be overridden by `plt.tight_layout()`. I resolved this by removing the call to `tight_layout` and instead set `bbox_inches='tight'` in `plt.savefig`.
