### ISSUE TITLE
Lineplot: Barely visible confidence band if neighboring points have no uncertainty

### ISSUE THREAD

**Issue by Jonas-Jaeger** [mwaskom/seaborn#2537]
Hello all,

I recently noticed some surprising behavior of the confidence interval bands of a lineplot:
When having multiple values y-values assigned to the same x-value while the neighboring point has only a single y-value, the error band is barely visible (which led to the fact that I had completely overlooked it at first).

This behavior can be reproduced with this code:
```python
import matplotlib.pyplot as plt
import seaborn as sns

sns.lineplot([0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.25, 0.5], [99.2, 99.2, 10.0, 99.2, 10.0, 54.0, 9.98, 9.98])
plt.show()
```
where multiple y-values are present at x=0 in the data, while the other x-values have only a single y-value assigned.

The plot will look as follows
![Figure_1](https://user-images.githubusercontent.com/34666257/113354661-cad34c00-933f-11eb-855b-1675ce232ec4.png)

I wonder if such behavior is intended? Shouldn't the band decrease linearly between the two points?
So that the bands would look like this:
![Figure_1_corrected](https://user-images.githubusercontent.com/34666257/113355129-9b710f00-9340-11eb-9d30-cc31d4fa6b60.png)

I am uncertain if this is really a bug or such a common/reasonable scenario, but I think that important information could be overlooked because of that.

I am using python 3.8, seaborn 0.11.1, and matplotlib 3.3.3 on macOS 10.15.7.

Best wishes,
Jonas

**Comment by mwaskom** [comment]
seaborn considers confidence intervals to be undefined when you have a single data value (which, although seaborn uses bootstrapping, tracks with what you'd get from the equation for a parametric standard error, where you'd have a 0 in your denominator). Then matplotlib draws `fill_between` segments the way you see when a neighboring point has nan values for the y range. It does draw what you expect if the neighboring point has 0 delta between ymin and ymax.

So, philosophical question: is the standard error here 0 or undefined?

Then, secondly, is the linear interpolation that you're expecting valid to show? It may or may not be true that your uncertainty decreases like that. But then again, lineplot does plot a linear interpolation of the estimate value, which might also not be correct!

If you are aware of this behavior and want to represent the error for the point where you have multiple observations such, you can switch to `err_style="bars"`. But that will give you a more-interpretable version of the current plot, not the one you want.

**Comment by mwaskom** [comment]
Maybe also relevant, here's what happens if you have multiple observations but no variance:

```python
sns.lineplot(x=[0, 0, 1, 1], y=[-1, 1, 0, 0])
```
![image](https://user-images.githubusercontent.com/315810/113414356-d304a900-938a-11eb-8537-7489af20b7ba.png)

**Comment by jhncls** [comment]
Possibly also relevant here:
```
ax = sns.lineplot(x=[0, 0, 1, 1], y=[0, 0, 1, 1])
ax.lines[0].remove()
```
shows that a tiny confidence band has been drawn.
```
ax = sns.lineplot(x=[0, 1], y=[0, 1])
ax.lines[0].remove()
```
is without confidence band. So, having an undefined confidence interval when there is only one y-value for a given x seems to be a consistent approach.

**Comment by mwaskom** [comment]
@Jonas-Jaeger I'm inclined to close here as this is internally consistent and at least arguably correct. Always drawing a confidence band even where it doesn't make sense (due to single observations) can cause problems, e.g. it will be visible behind a dashed line in a way that is confusing.

**Comment by mwaskom** [comment]
Closing but feel free to continue the discussion if you think I'm overlooking something important.
