### ISSUE TITLE
lmplot/regplot can't set alpha of x_estimator

### ISSUE THREAD

**Issue by milo-trujillo** [mwaskom/seaborn#2538]
lmplot and regplot both allow setting transparency for either scatterplot points or fit lines, through `scatter_kws` and `line_kws`, respectively. However, if `x_estimator` is set (for example to `np.mean`), then the scatterplot is replaced by confidence bars and a point at the estimated value. There is currently no way to set the transparency of these confidence bars.

For example:

```
sns.lmplot(data=example, x="x", y="y", hue="source", x_estimator=np.mean, scatter_kws={'s':20,'alpha':0.3}, line_kws={'alpha':0.3})
```

Creates an image like:

![Opaque confidence bars](https://i.imgur.com/pp1RJzn.png)

Since the two distributions I'm plotting stomp all over one another, I'd really like to make those estimation bars semi-transparent.

I believe the problem comes from the following lines: https://github.com/mwaskom/seaborn/blob/0f538fb40ad04174a9298f9403783308f9bbb370/seaborn/regression.py#L398-L407

If `x_estimator` is set, then scatterplot creates a new set of keywords, `c_kws`, which inherits the _color_ from the user-specified `kws`, but no other values like _alpha_.

It seems reasonable to me that the confidence bars and scatterplot should share an alpha value, but if there's a compelling reason to keep those values distinct then it would be great if there were another way to specify the alpha values of those bars.

**Comment by jhncls** [comment]
Here is an attempt to a reproducible example:
```
import seaborn as sns
import numpy as np
import pandas as pd

example = pd.DataFrame({"x": np.repeat(np.linspace(1, 6, 20), 10),
                        "y": np.random.randn(200),
                        "source": np.tile([1, 2], 100)})
sns.lmplot(data=example, x="x", y="y", hue="source", x_estimator=np.mean,
           scatter_kws={'s': 20, 'alpha': 0.3}, line_kws={'alpha': 0.3}, legend=False)
```
Even the trick to put the transparency into the palette doesn't lead to transparent bars (`palette=[to_rgba('C0', 0.3), to_rgba('C1', 0.3)]`).

**Comment by mwaskom** [comment]
seaborn doesn't as a rule use the alpha channel of values in a color palette, often because alpha is getting set elsewhere.

Matching the error bar alpha to the scatter point alpha seems reasonable.

You can also modify the alpha value by doing something like `plt.setp(g.ax.lines, alpha=.3)`. The presence of the regression lines makes that a bit trickier, though; you are lowering their alpha in your example but I'm not sure if you want that outcome or are just demonstrating that it doesn't produce the effect you want.

**Comment by jimouris** [comment]
I face a very similar problem with lineplots. Here's what I have:
```python
ax = sns.lineplot(
  x='x', y='y', hue='source', style='source', markers=True, data=df_bits, 
  err_style="bars", err_kws={ 'elinewidth':2, 'capsize':5, 'capthick':2, }
)
```
If I add 'alpha' in the `err_kws` then I get:
```
TypeError: matplotlib.axes._axes.Axes.errorbar() got multiple values for keyword argument 'alpha'
```
