### ISSUE TITLE
AttributeError: module 'seaborn' has no attribute 'Implot'

### ISSUE THREAD

**Issue by FelipeGarson** [mwaskom/seaborn#2543]
res_df = pd.DataFrame({
    'fittedvalues': house1.fittedvalues,
    'resid_deviance': house1.resid_deviance,
    'boro': housing['boro']
})
fig = sns.Implot(x='fittedvalues', y='resid_deviance',
                data=res_df, hue='boro', fit_reg=False)
plt.show()
fig.savefig('p5-ch-model_diagnostics/figures/resid_boros')

AttributeError                            Traceback (most recent call last)
<ipython-input-7-e3033539eab5> in <module>
      7     'boro': housing['boro']
      8 })
----> 9 fig = sns.Implot(x='fittedvalues', y='resid_deviance',
     10                 data=res_df, hue='boro', fit_reg=False)
     11 plt.show()

AttributeError: o módulo 'seaborn' não tem o atributo 'Implot'

Estou fazendo os exercícios do livro: Análise de dados com Python e Pandas do Daniel Y. Chen capítulo 14 e 
aparece essa mensagem de erro quando vou plotar o gráfico Implot.

**Comment by mwaskom** [comment]
You either have a problem with your seaborn installation, or you are picking up something else when you do `import seaborn as sns`.  That might happen if you have a script named `seaborn.py` in your local directory. I don’t have enough information to speculate further.  I would need a complete example and details about your installation process.

**Comment by mwaskom** [comment]
Closing as this is very likely an idiosyncratic environment/installation problem, but will reopen if you can provide evidence that it is a problem in seaborn.
