### ISSUE TITLE
`lineplot` confidence intervals are slow (seemingly non-responsive) with dense data

### ISSUE THREAD

**Issue by ethanabrooks** [mwaskom/seaborn#2547]
[This line](https://github.com/mwaskom/seaborn/blob/576db3ccc52175557e5fc904764e429aa0172077/seaborn/_core.py#L1101) hangs for me indefinitely. 

```
ipdb> len(comp_col)
3381
ipdb> len(orig.index)
3377
ipdb> comp_col.loc[orig.index].shape
(2855492,)
ipdb> comp.shape
(3377,)
```
I don't think there is anything special about my data, but here it is:
[returns.csv.gz](https://github.com/mwaskom/seaborn/files/6275078/returns.csv.gz)
The command to reproduce was
```python
sns.lineplot(x="step", y="Episode return", data=df)
```

**Comment by mwaskom** [comment]
What version of seaborn?

**Comment by jhncls** [comment]
Tested the given csv with the latest dev version, and also with 0.11.1.

It takes about 30 seconds and produces this plot:
![image](https://user-images.githubusercontent.com/19649483/114023911-b9280200-9873-11eb-98ca-d8ed8ddd00f2.png)

The "step" column has 4062 integer values, unsorted, 1050 unique.

Here is an easier to reproduce example which takes 4 minutes, while the scatterplot only takes a few seconds:
```
x = np.tile(np.arange(10000), 4)
y = np.random.randn(40000).cumsum()
sns.lineplot(x=x, y=y)
```

**Comment by mwaskom** [comment]
Takes 30 seconds with both versions? The line that you linked to as being the problem doesn't exist in the latest release, only in the dev version.

**Comment by mwaskom** [comment]
If the issue is "lineplot is slow with densely sampled data" that's not altogether surprising because it computes CIs using bootstrapping by default and that will not be instantaneous. In the dev version you can show parametric confidence intervals with `errorbar=("se", 2)`, which will be faster. Would be good to know if the originally-implicated pandas operation actually hangs at some point, though.

**Comment by ethanabrooks** [comment]
Yes it looks like it takes about 30 seconds. Perhaps I was not waiting long enough originally. With `errorbar=("se", 2)` it takes only about 2 seconds.

**Comment by mwaskom** [comment]
Now that we have parametric CIs, I think it would be reasonable to issue a warning when bootstrapping is likely to take a long time without anything obviously happening.

**Comment by mwaskom** [comment]
Alas, predicting when lineplot will be slow (and defining "slow") for that matter is complicated and at least partially machine-dependent. So I am going to withdraw my suggestion about adding a warning for now.

The next release will have a tutorial page specifically about [error bars](https://github.com/mwaskom/seaborn/blob/master/doc/tutorial/error_bars.ipynb), which will at least increase the salience of the bootstrap default, and it includes a little blurb specifically mentioning the computational cost:

>  "On the other hand, the bootstrap procedure is much more computationally-intensive. For large datasets, bootstrap intervals can be expensive to compute. But because uncertainty decreases with sample size, it may be more informative in that case to use an error bar that represents data spread."

**Comment by reinderien** [comment]
I was bit by this too. Would be nice to have a warning and/or documentation on workarounds. As-is, the execution time for what should be a reasonable data set is quite painful.
