### ISSUE TITLE
`hue` in `scatterplot()` alters the y axis scale

### ISSUE THREAD

**Issue by lSulkhanl** [mwaskom/seaborn#2549]
- `seaborn 0.10.1`
- `python 3.8`

If you reproduce these lines of code:

```
import seaborn as sns

df = sns.load_dataset(name='planets')

sns.scatterplot(x='year', y='distance', data=df, hue='mass')
sns.scatterplot(x='year', y='distance', data=df)
```

it will produce the following output:

![result](https://user-images.githubusercontent.com/81778721/114607177-7a8fae80-9c9c-11eb-916f-b1ff4c426f85.png)

you could see how the **hue parameter changes the distribution of the points and the scale of the `y-axis` is not the same**.

Is it a normal behaviour of seaborn? Or is there some detail that I missed?

**Comment by mwaskom** [comment]
I think the explanation is that some planets with large distance values have missing data about their mass, so they don't end up in the final plot, and the y axis ends up being different.

**Comment by mwaskom** [comment]
You can see this if you plot them on the same axes, with the hue-mapped plot over the simple x/y one:

![image](https://user-images.githubusercontent.com/315810/114620334-7900bf00-9c79-11eb-93ac-dbdb5c750eea.png)

**Comment by mwaskom** [comment]
I am going to close as this is expected behavior / nothing is wrong. I do think it would be nice to have more control over what happens with observations where x/y data is present but one or more of the semantic mapping variables are missing, but that would be a major project and not a priority right now.
