### ISSUE TITLE
Missing x/hue pairs in data results in ValueError when using pointplot

### ISSUE THREAD

**Issue by QuentinAndre** [mwaskom/seaborn#2552]
Hi,

First of all, thank you for a great library that I'm using almost daily. I have recently updated seaborn to the latest version, and I'm now facing a bug that I did not have before. When a dataset is missing x/hue pairs, using pointplot will throw a ValueError. See minimal example below:

```python
cols = ["Judgment", "Target", "WTP"]
vals = np.array([
       ['Certain (Separate)', '$100 Gift Card', 72],
       ['Certain (Separate)', '$50 Gift Card', 39],
       ['Uncertain (In Lottery)', '$100 Gift Card', 42],
       ['Uncertain (In Lottery)', '$50 Gift Card', 21],
       ['Uncertain (In Lottery)', '50/50 Lottery', 28], # This "Target" value does not exist for other "Judgments"
       ['Uncertain (Separate)', '$100 Gift Card', 61],
       ['Uncertain (Separate)', '$50 Gift Card', 33]
])

data = pd.DataFrame(vals, columns=cols).astype({'WTP': 'float32'})
sns.pointplot(
    x="Judgment",
    y="WTP",
    hue="Target",
    data=data
)
```
Throws: ValueError: Invalid RGBA argument: 0.6274509803921569

My intuition is that Seaborn expects a "balanced" dataset in which all x/hue pairs exists, but I'm not sure how to fix it.

**Comment by mwaskom** [comment]
I think this is a duplicate of https://github.com/mwaskom/seaborn/issues/2373, which is ultimately a bug in matplotlib 3.3. I was able to replicate with matplotlib 3.3.2 but with matplotlib 3.4.1 I get:

![image](https://user-images.githubusercontent.com/315810/114760538-66e05880-9d2d-11eb-8711-0184d7c561cc.png)

which is what I think you want?

**Comment by QuentinAndre** [comment]
Yes, absolutely a duplicate of #2373! Sorry for missing it. Updating matplotlib to 3.4.1 solved the problem. Thank you for your quick response!
