### ISSUE TITLE
displot ignores sharex=False

### ISSUE THREAD

**Issue by wjaskowski** [mwaskom/seaborn#2553]
`sharex=False` works as expected:
```python
titanic = sns.load_dataset("titanic")
titanic = titanic.assign(deck=titanic.deck.astype(object)).sort_values("deck")
g = sns.FacetGrid(titanic, col="sex", sharex=False, sharey=False)
g.map(sns.histplot, "age");
```
![image](https://user-images.githubusercontent.com/4952605/114877916-08d07580-9e00-11eb-99b4-c4ecf888443b.png)

but is ignored when using displot:
```python
sns.displot(titanic, x='age', col='sex', facet_kws=dict(sharex=False, sharey=False));
```
![image](https://user-images.githubusercontent.com/4952605/114877934-0bcb6600-9e00-11eb-90c2-c5cc93181fd1.png)

Versions:
```bash
matplotlib                3.4.1                    pypi_0    pypi
seaborn                   0.11.1                   pypi_0    pypi
```

**Comment by mwaskom** [comment]
Duplicate of https://github.com/mwaskom/seaborn/issues/2472 I believe

**Comment by wjaskowski** [comment]
Indeed, it works with `common_bins=False`. Now, when I think about it, it makes sense although quite hard to understand without asking for help.

**Comment by mwaskom** [comment]
If you want to add an example to the API documentation, I think I'd be in favor.
