### ISSUE TITLE
Displaying colorbars for row_colors or col_colors in clustermap

### ISSUE THREAD

**Issue by bricoletc** [mwaskom/seaborn#2554]
Hello, thanks for this great library.

Is there any easy way to display colorbars for row_colors or col_colors, much like the colorbar for the heatmap in a clustermap is displayed by default?

If not, is there a half-easy way to add manually defined colorbars using the relevant axes?

**Comment by mwaskom** [comment]
This is something you'd need to add manually ... a partially relevant example would probably be https://stackoverflow.com/questions/27988846/how-to-express-classes-on-the-axis-of-a-heatmap-in-seaborn/27992943#27992943

Note that some aspects of that answer are easier nowadays (e.g. you can set up the plot with a the heatmap colorbar in the right place).
