### ISSUE TITLE
linewidth calculation slow for histograms

### ISSUE THREAD

**Issue by ivirshup** [mwaskom/seaborn#2555]
## Example

```python
import pandas as pd
import seaborn as sns

diamonds = sns.load_dataset("diamonds")
```

```python
%%timeit
sns.displot(diamonds, x="price", row="cut", col="color")
# 5.85 s ± 157 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

```python
%%timeit
sns.displot(diamonds, x="price", row="cut", col="color", linewidth=0.1)
# 4.37 s ± 81.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

## Description

Setting the linewidth here is taking about ~25% of the computation time. I would note that in the case where I caught this, passing `linewidth` cut plot time in half. I believe the issue is due to an inefficiencies here: https://github.com/mwaskom/seaborn/blob/66b478390c20089de7f9644ba9965ce5d4f973ff/seaborn/distributions.py#L638-L684

One cause is that line widths are being set multiple times on each object. In the loop linked above, line widths are calculated, and then set for all subplots (not just the subplot corresponding for this subset). We can see this is the case since all the rectangles have the same linewidth in the end:

```python
from itertools import chain
import matplotlib as mpl

snsfig = sns.displot(diamonds, x="price", row="cut", col="color")

children = chain.from_iterable(ax.get_children() for ax in snsfig.axes.flat)
rects = filter(lambda x: isinstance(x, mpl.patches.Rectangle), children)

{rect.get_linewidth() for rect in rects}
```

```
{0.0, 0.37466112012984926}
```

Something a little more dataset dependent is this expression:

https://github.com/mwaskom/seaborn/blob/66b478390c20089de7f9644ba9965ce5d4f973ff/seaborn/distributions.py#L647-L650

Where `index.to_frame()` can take a very long time in some circumstances. I'm not sure exactly what these are, but for my own data [`%%snakeviz`](https://jiffyclub.github.io/snakeviz/) noted a lot of time spend doing this. But I believe `hist_metadata` should be the same for each iterations of `sub_vars`, so this could probably just be moved outside the loop.

## Version info

This is using seaborn at commit 66b478390c20089de7f9644ba9965ce5d4f973ff, though I'd initially noticed this using the last release.

<details>
<summary> sinfo report </summary>

```
-----
matplotlib          3.4.1
pandas              1.2.4
seaborn             0.12.0.dev0
sinfo               0.3.1
vega_datasets       0.9.0
-----
PIL                 8.2.0
appnope             0.1.2
backcall            0.2.0
cffi                1.14.5
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.1
decorator           4.4.2
ipykernel           5.3.4
ipython_genutils    0.2.0
jedi                0.17.0
kiwisolver          1.3.1
matplotlib          3.4.1
mpl_toolkits        NA
numexpr             2.7.3
numpy               1.20.2
pandas              1.2.4
parso               0.8.2
pexpect             4.8.0
pickleshare         0.7.5
prompt_toolkit      3.0.17
ptyprocess          0.7.0
pygments            2.8.1
pyparsing           2.4.7
pytz                2021.1
scipy               1.6.2
seaborn             0.12.0.dev0
sinfo               0.3.1
six                 1.15.0
snakeviz            2.1.0
statsmodels         0.12.2
storemagic          NA
tornado             6.1
traitlets           5.0.5
vega_datasets       0.9.0
wcwidth             0.2.5
zmq                 20.0.0
-----
IPython             7.22.0
jupyter_client      6.1.12
jupyter_core        4.7.1
notebook            6.3.0
-----
Python 3.8.8 (default, Apr 13 2021, 12:59:45) [Clang 10.0.0 ]
macOS-10.15.7-x86_64-i386-64bit
16 logical CPU cores, i386
-----
Session information updated at 2021-04-16 16:25
```

</details>

**Comment by mwaskom** [comment]
I'm not sure I understand everything here, but if you see a way to make this more efficient, feel free to submit a patch. It will require a lot of manual testing though. While this logic does get hit by the automated tests, they don't assert that the automatic linewidths "look right" across the full combination of outcomes you can get.

IIRC this code was originally written in an axes-specific context and faceting was grafted onto it, so it wouldn't surprise me if it could be improved a lot with a refactor that takes the possibility of multiple subplots into account.

It does seem right that the minimum barwidth computation can probably be moved outside the loop.

I understand this point less:

> One cause is that line widths are being set multiple times on each object. In the loop linked above, line widths are calculated, and then set for all subplots (not just the subplot corresponding for this subset). We can see this is the case since all the rectangles have the same linewidth in the end:

Setting the linewidth is cheap. If there's a cost here, it comes from the fact that doing so will *eventually* trigger a re-draw. Whether or not that happens inside the loop depends on what else is going on (I think `autoscale_view` is probably the culprit).

BTW a useful matplotlib helper method is

```python
g = sns.displot(diamonds, x="price", row="cut", col="color")
rects = g.fig.findobj(mpl.patches.Rectangle)
```

**Comment by ivirshup** [comment]
> I'm not sure I understand everything here, but if you see a way to make this more efficient, feel free to submit a patch.

Alright, draft patch incoming.

> It will require a lot of manual testing though. While this logic does get hit by the automated tests, they don't assert that the automatic linewidths "look right" across the full combination of outcomes you can get.

Right now I can show (at least for my example cases), that the line widths are the same to what they were without the patch. It'd be good to see if this holds for edge cases, could you could suggest some to check for?

> Setting the linewidth is cheap. If there's a cost here, it comes from the fact that doing so will eventually trigger a re-draw. 

I looked into this a bit more and found something interesting. It seems dataset dependent which operations dominate time spent. For a larger plot `snakeviz` is showing quite a bit of time being spent during `set_linewidth`, though for the `diamonds` dataset most of the time for this loop is being spent in `to_frame` and `concat`. Here's the breakdown of time spent for this other dataset:

![image](https://user-images.githubusercontent.com/8238804/115177827-5bb57000-a113-11eb-855f-89efa1eb3a10.png)

<details>
<summary>And here's the code to reproduce</summary>

```python
%load_ext snakeviz
import seaborn as sns
import vega_datasets
import pandas as pd

flights = vega_datasets.data.flights_3m()

# Take top ten origins and destinations to subset
top_dest = flights["destination"].value_counts()[:10].index
top_orig = flights["origin"].value_counts()[:10].index
mask = flights["destination"].isin(top_dest) & flights["origin"].isin(top_orig)
flights_subset = flights.loc[mask]

%%snakeviz
sns.displot(flights_subset, x="delay", col="destination", row="origin")
```

</details>

> BTW a useful matplotlib helper method is

That is useful, thanks!

**Comment by mwaskom** [comment]
I'm skeptical of that only because there's so little to the `set_linewidth` [method](https://matplotlib.org/stable/_modules/matplotlib/patches.html#Patch.set_linewidth). I do think it's right that setting the linewidth implicitly slows things down, because it marks the artist as stale and eventually triggers a re-draw, but I'm confused about why it's reporting that time is being spent *inside* the method. (Unless you have some kind of auto-draw set?)

**Comment by ivirshup** [comment]
> I'm skeptical of that only because there's so little to the set_linewidth

It looks like at least `.stale` is a property with a callback on setting, but it doesn't look to me like it's doing anything besides setting `.stale` on the parent object.

> Unless you have some kind of auto-draw set?

I'm not sure what this would entail. I don't think this is the case, but maybe there is a way to check?

**Comment by ivirshup** [comment]
Minor update on performance with histograms, using `element="step"` or `element="poly"` is significantly faster than `"bar"` for these use cases. I'm getting about a 4x speed up on the larger `flights` example (from 40s to 10s).

**Comment by mwaskom** [comment]
Yea, I think that's mostly a matplotlib thing. Adding/drawing one polycollection is a lot faster than adding/drawing a bunch of patches.

**Comment by ivirshup** [comment]
Do you know if there's a reason `Axes.bar` adds each bar individually rather than use a `PatchCollection`? It seems like some of the `_update_patch_limits` time could be avoided.

**Comment by mwaskom** [comment]
I don't.

I do think that using `element="step"` is good practice for dense histograms ... it will be faster and there are diminishing returns of segmented bars for (relatively) small binwidths.

**Comment by ivirshup** [comment]
> I don't.

It seems a lot faster, and doesn't seem to break much. I'll look into this https://github.com/matplotlib/matplotlib/pull/20092.

> I do think that using element="step" is good practice for dense histograms

I'd agree, but will still forget to pass it sometimes – and the current time to plot can be quite punishing.

**Comment by mwaskom** [comment]
I think the biggest bottleneck for large data seaborn histograms is #2550; it could be helpful to have some comparison metrics like I gave there but also accounting for the matplotlib contributions.

Pursing the use of a collection within `ax.bar` also sounds like a great idea.
