### ISSUE TITLE
xlim does not work with sns.barplot

### ISSUE THREAD

**Issue by erlebach** [mwaskom/seaborn#2564]
Hi, 

I spent much time getting set_xlim to work with sns.barplot (it does work with scattergrams). Here is a minimal working example to demonstrate. Any insight is appreciated. Seems like a bug because funcationality should be identical to `sns.scatterplot`. Thanks.

```
mport matplotlib.pyplot as plt
import seaborn as sns

x = [10,11,12]
y = [20,25,30]
ax = sns.barplot(x=x, y=y)
ax.set_xlim(0, 20)

plt.show()
```

**Comment by mwaskom** [comment]
Hi, `barplot` is a categorical function and its functionality is explicitly *not* like that of `scatterplot`; note the key line from the [docs](http://seaborn.pydata.org/generated/seaborn.barplot.html):

> This function always treats one of the variables as categorical and draws data at ordinal positions (0, 1, … n) on the relevant axis, even when the data has a numeric or date type.

That said, in the next release there will be a new parameter `fixed_scale` that you can set to `False` to get the behavior you are expecting. But this is not yet implemented.

Closing as not a bug.

**Comment by erlebach** [comment]
Thank you, Michael. I solved the problem with the reindex function.

  Gordon
