### ISSUE TITLE
Unexpected behavior of `histplot` `probability` stat with hues

### ISSUE THREAD

**Issue by npeschke** [mwaskom/seaborn#2565]
I am trying to plot a distribution using `sns.histplot` and the `stat="probability"` which works fine and how I would expect it to reading the documentation.
However, when using `hue` additionally, I would expect the bar height for each hue to be normalized separately but instead they get normalized as if the hue is not there.

Setup for a minimum working example:
```python
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("darkgrid")

data = pd.DataFrame({
    "x": [1, 1, 1, 2, 2, 2, 3, 3, 3],
    "hue": [1, 1, 1, 2, 2, 2, 3, 3, 3]
})
```
**Expected behavior when not using hue**
```python
sns.histplot(x="x", data=data, stat="probability")
```
![image](https://user-images.githubusercontent.com/37580463/116079137-bf054c00-a697-11eb-8718-1f709670de7c.png)

***Unexpected* behavior when using hue**
![image](https://user-images.githubusercontent.com/37580463/116077935-52d61880-a696-11eb-97f6-eceffd906cde.png)
I would expect that the normalization would be done separately for each category/hue, resulting in three bars each at 1.0 probability instead of at 0.33 probability.

In the case that this behavior is intentional, I would kindly request the possibility to do the normalization independently for each hue as a new feature.

**Package versions**
python 3.8.3
matplotlib 3.3.1
seaborn 0.11.0

**Comment by mwaskom** [comment]
I believe you are looking for ``common_norm=False`](https://seaborn.pydata.org/generated/seaborn.histplot.html).

**Comment by npeschke** [comment]
Thank you very much for the quick reply and the great package! Indeed that was what I was looking for!
