### ISSUE TITLE
Enhancement: enable catplot to support the combination of multiple kinds of plots

### ISSUE THREAD

**Issue by normanius** [mwaskom/seaborn#2568]
**Problem**

It would be great if `catplot` is able to plot categorical distribution plots AND scatterplots. I think this is a common enough use case to be supported. Currently, one has to resort to `FacetGrid` with a custom plotting function that combines multiple axis-level plotting functions (e.g. `sns.boxplot` and `sns.stripplot`) to accomplish this.

**Suggestion**

Just accepting a list of strings for argument `kind` is probably not the right way to go, since one wants to set the aesthetics for boxplots and scatterplots independently.

Instead, I suggest to permit plotting into the same figure by passing the `FacetGrid` from a previous call. 

```python
g1 = sns.catplot(..., kind="box")
g2 = sns.catplot(..., kind="strip", grid=g1)
```

I'm not familiar enough with seaborn to judge if this makes sense at all. In the unlikely case it does, and if the suggested edit does not interfere with the ongoing refactoring (#2429), I can try to create a PR.

**Comment by normanius** [comment]
Just after submitting this issue, I've had the following idea:

```python
import seaborn as sns 
import matplotlib.pyplot as plt
tips = sns.load_dataset("tips")
g = sns.catplot(x="sex", y="total_bill",
                hue="smoker", col="time",
                palette="pastel",
                data=tips, kind="box",
                height=4, aspect=.7);
g.map_dataframe(sns.stripplot, x="sex", y="total_bill", 
                hue="smoker", palette=["#404040"], 
                alpha=0.6, dodge=True)
plt.show()
```

<img width="616" alt="image" src="https://user-images.githubusercontent.com/11406002/116486178-45cf4a00-a88d-11eb-86d3-3ea530426edd.png">



This works pretty fine. Because this is simple enough, I suggest closing this issue.

**Comment by normanius** [comment]
You may want to use the above example in the example section of the [`catplot()`](https://seaborn.pydata.org/generated/seaborn.catplot.html) documentation.

**Comment by mwaskom** [comment]
This has an open issue with another suggestion: #1484 

Using `map_dataframe` is also a good idea.

Probably -1 on the proposal in the initial issue.
