### ISSUE TITLE
Modes of fitted KDEs

### ISSUE THREAD

**Issue by iiSeymour** [mwaskom/seaborn#2584]
Hello Developers, thanks for the great library.

Often when using `kdeplot`, `displot`, ect I also want to annotate the mode of the fitted KDE and end up eyeballing it and adding a `plt.axvline(99.9, color='red', ls=':')` or similar. Is there a better way to handle this situation?

**Comment by mwaskom** [comment]
Hi, there's nothing built in, so this would be a better question for StackOverflow. Thanks!
