### ISSUE TITLE
Requirement of row/col_colors in clustermap

### ISSUE THREAD

**Issue by hsiaoyi0504** [mwaskom/seaborn#2587]
Hi there, thanks for providing such a great library. I have tried to add col_colors into my clustermap.
However, I find it a little weird that I can successfully plot `col_colors` using the default list, but can't get it to work for a Pandas DataFrame (Series). For example,

This works:
```
col_colors = [sns.color_palette("vlag").as_hex()[0]] * df_cluster_map.shape[1]
sns.set(rc={'figure.figsize':(100,100)})
g = sns.clustermap(df_cluster_map.corr(), row_linkage=row_linkage, col_linkage=row_linkage, center=0, cmap="vlag",
                   col_colors=col_colors,
                   dendrogram_ratio=(.1, .2),
                   cbar_pos=(0.9, 0.9, .03, .2),
                   linewidths=.75, figsize=(100, 100))
```

This doesn't work (an empty white row appears):
```
col_colors = pd.DataFrame(data=[sns.color_palette("vlag").as_hex()[0]] * df_cluster_map.shape[1], columns=['Sample Type'])
g = sns.clustermap(df_cluster_map.corr(), row_linkage=row_linkage, col_linkage=row_linkage, center=0, cmap="vlag",
                   col_colors=col_colors,
                   dendrogram_ratio=(.1, .2),
                   cbar_pos=(0.9, 0.9, .03, .2),
                   linewidths=.75, figsize=(100, 100))
```

It seems to me that the only difference between these two methods is the data structure only, but doesn't get an idea for fixing the latter one (Pandas DataFrame).

**Comment by mwaskom** [comment]
I'm afraid that it's not possible to answer without more information. Please provide a fully [reproducible issue](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs). Thank you!

**Comment by jhncls** [comment]
Yes, it seems interesting to also allow a column from a dataframe (pandas calls this a `Series`) to be used for the `col_colors`. Unfortunately, `sns.clustermap`  doesn't allow this (yet?).  However, you can convert the column to a list and then give it to `col_colors`.
```
g = sns.clustermap(...., col_colors=col_colors['Sample Type'].to_list())
```
PS: An interesting feature of using a `Series` would be that it also sets a now for the row. (Now `clustermap` uses the Series' name, but not the data).

Here is an example adapted from seaborn's docs:
```
import seaborn as sns
import pandas as pd

col_colors = pd.DataFrame(data=sns.color_palette("vlag", iris.shape[1]).as_hex(), columns=['Sample Type'])
# g = sns.clustermap(iris, col_colors=col_colors['Sample Type']) # uses the Series' name, but not its data
g = sns.clustermap(iris, col_colors=col_colors['Sample Type'].to_list()) # this works (but doesn't show the Series' name)
```
@mwaskom I think this could be interpreted as a feature request to accept a Series for `row_colors` and `col_colors`.

**Comment by mwaskom** [comment]
> I think this could be interpreted as a feature request to accept a Series for row_colors and col_colors.

Not sure what you mean here.

``` python
x = pd.DataFrame(np.random.uniform(0, 1, (10, 10)))
colors = pd.Series(sns.color_palette("crest", 10).as_hex())
sns.clustermap(x, col_colors=colors)
```

![image](https://user-images.githubusercontent.com/315810/118495630-6141ae00-b6f1-11eb-8b35-074f63901c08.png)

**Comment by jhncls** [comment]
Sorry about forgetting to add the data (it comes from the `clustermap` docs, it is iris without the species column, I edited the example). It was a bit weird that your test worked apparently without problems. After more testing, the difference comes from the index of the Series.  Seaborn (correctly) uses the index of the Series to decide which column gets which color.

So, the corrected example now is
```python
import seaborn as sns
import pandas as pd

iris = sns.load_dataset('iris')
species = iris.pop('species')
col_colors = pd.DataFrame(sns.color_palette("crest", iris.shape[1]).as_hex(), columns=[''Sample Type''], index=iris.columns)
sns.clustermap(iris, col_colors=col_colors[''Sample Type''])
```
which does generate the desired column colors.  Seaborn's deep features really keep amazing. 

A possible feature could be to issue a warning when col_colors is a Series and its index doesn't match the cluster's dataframe columns. (And maybe in that case interpret the Series as if it were a list?)

@hsiaoyi0504 You can't give a complete dataframe for `col_colors`, but you can use a column of a DataFrame. The column needs as index the names of the columns of `df_cluster_map`. Or, you could convert the column to a list with `sns.clustermap(..., col_colors=col_colors['Sample Type'].to_list()`.

**Comment by mwaskom** [comment]
(Ah, yes, this is documented](http://seaborn.pydata.org/generated/seaborn.clustermap.html#seaborn.clustermap):

> DataFrame/Series colors are also matched to the data by their index, ensuring colors are drawn in the correct order.

But that does not highlight what happens if there is a complete mismatch.

I think a warning [here](https://github.com/mwaskom/seaborn/blob/fc50d08cac8e99dd41452411412efbc69fc7908b/seaborn/matrix.py#L895) when colors is all NA would be fine. I am -1 on treating it like a list at that point, however.

**Comment by hsiaoyi0504** [comment]
Thanks @mwaskom and @jhncls.
Yes, I didn't realize the index need to be matched.
I need to do something like this to make it work.
```
col_colors = pd.DataFrame(data=[sns.color_palette("vlag").as_hex()[0]] * df_cluster_map.shape[1], columns=['Sample Type'])
col_colors.index = df_cluster_map.T.index
```
Isn't it possible to check that the indexes are matched or not?

**Comment by mwaskom** [comment]
It's not that the indexes "have to be matched" it's that it aligns the data *on the indexes*, and if there's no correspondence between them, you'll get all nans (which show up as white).

**Comment by hsiaoyi0504** [comment]
That makes sense. Thanks.

**Comment by jhncls** [comment]
@mwaskom Would it be useful to also allow a dictionary instead of a list or a series?
