### ISSUE TITLE
Unable to style errorbars in parplot when specifying yerr or xerr argument

### ISSUE THREAD

**Issue by gaardhus** [mwaskom/seaborn#2594]
I'm trying to add and style the error bars in the following way

```
sns.barplot(x=['a','b','c'], y=[2,4,5], yerr=[1,2,3], capsize=5, errwidth=0.1)
```
![image](https://user-images.githubusercontent.com/46934916/120608960-08447a80-c452-11eb-8d7b-737e2b11777c.png)

However, the `capsize` and `errwidth` argument seem to have no effect, and I couldn't find any description of this issue or how to work around it anywhere.

**Comment by mwaskom** [comment]
A bit confusing but `capsize` and `errwidth` are seaborn parameters — they style the error bars that seaborn computes and adds on top of the bars — whereas `yerr` is a matplotlib parameter. It's passed through to `plt.bar` and seaborn doesn't really know if it's there or not. So you'd need to use matplotlib's `error_kw` parameter.

**Comment by gaardhus** [comment]
Thanks for the quick answer! That makes sense.

I was able to produce my desired output by adding arguments to the `error_kw` parameter as you suggested.

`sns.barplot(x=['a','b','c'], y=[2,4,5], yerr=[1,2,3], error_kw={'capsize':10, 'linewidth':1})`
![image](https://user-images.githubusercontent.com/46934916/120691012-3784d700-c4a6-11eb-813c-aed8d30bc2e1.png)
