### ISSUE TITLE
histplot discrete=False inconsistent behavior

### ISSUE THREAD

**Issue by JeffHCross** [mwaskom/seaborn#2595]
This is my first time contributing an issue to a public project, so apologies for any naïve mistakes.

I didn't realize at first that the options for discrete are None/True, instead of True/False. When using False, I noticed that the binwidth appeared to be getting changed. 

I don't know the right terminology to describe what I'm seeing, but from what I could determine for non-numeric data types discrete=False matched the look of neither discrete=None or discrete=True.  This is namely what threw me because I thought the default was False so I couldn't understand why the look of my charts changed. For numeric data types, discrete=False matched discrete=None.

A quick solution, I think, would be for the docs to more clearly indicate that the expected values are None/True.

EDIT:
matplotlib version: 3.3.1
seaborn version: 0.11.1

**Comment by mwaskom** [comment]
Hi, can you please provide an example using one of the sample datasets? See [here](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs) for more about what makes a bug report possible to answer. Thanks!

**Comment by JeffHCross** [comment]
Sure thing!

The code is pretty simple, just flipping through different types of columns (integer vs categorical) and the different values of discrete.
tips = sns.load_dataset("tips")
sns.histplot(data=tips, x="size", discrete=None);
sns.histplot(data=tips, x="size", discrete=False);
sns.histplot(data=tips, x="size", discrete=True);
sns.histplot(data=tips, x='day', discrete=None);
sns.histplot(data=tips, x='day', discrete=False);
sns.histplot(data=tips, x='day', discrete=True);

I've attached screenshots for both.
![seaborn_hist_categorical](https://user-images.githubusercontent.com/7269201/120703344-caa81780-c47a-11eb-8832-3153cdd3b50c.png)
![seaborn_hist_numeric](https://user-images.githubusercontent.com/7269201/120703353-cda30800-c47a-11eb-8f78-b6032d6a5211.png)

**Comment by JeffHCross** [comment]
I've also updated my original post with version numbers.

**Comment by mwaskom** [comment]
Thanks for the update. This looks like correct and expected behavior to me. Discrete binning is used when `discrete=True` and not used when `discrete=False`. When `discrete=None` it means (like many parameters in seaborn) to use some kind of default rule: here whether or not discrete bins are used by default depends on whether the data are categorical in nature or not.

I'm going to close as this is working as expected from my perspective but feel free to continue the discussion...

**Comment by JeffHCross** [comment]
Ah, thank you for the explanation! I was expecting False to look more like None, but your explanation makes sense. Appreciate the education!
