### ISSUE TITLE
Boxplot ignores 'hue' if no 'x' given

### ISSUE THREAD

**Issue by bluss** [mwaskom/seaborn#2597]
In the following, the `hue` has no effect (seaborn 0.11.1 as well as current master)

```python
tips = sns.load_dataset("tips")
sns.boxplot(data=tips, y='tip', hue='smoker')
```

It takes effect if something like `x='sex'` is added.

Thanks for creating a great package.

**Comment by mwaskom** [comment]
Duplicate of https://github.com/mwaskom/seaborn/issues/2340, probably a few others, but that has a workaround.
