### ISSUE TITLE
Rugplot sometimes reuses the previous colour and sometimes uses new for the same data

### ISSUE THREAD

**Issue by jankaWIS** [mwaskom/seaborn#2599]
In the rugplot [docs](https://seaborn.pydata.org/generated/seaborn.rugplot.html) one can see the issue. Why does the rugplot have in the case of scatter plot the same colour as the scatter and in the case of kdeplot not? In the case of kdeplot it looks like it is a new graph and seaborn sees it as new data.

How can one have the same colour without the need to manually specify `color`?

![image](https://user-images.githubusercontent.com/54404810/122400221-31055d80-cf84-11eb-8636-2fde6c6da9ad.png)

**Comment by mwaskom** [comment]
Basically, this is a matplotlib thing. They have different color cycles for different types of artists, and seaborn's default in the absence of a specified color or mapped hue is to try and match matplotlib's color cycle defaults.

**Comment by jankaWIS** [comment]
Hi @mwaskom and thanks for your answer. But why does `sns.scatterplot` behave differently from `sns.kdeplot`? Why for one the colour is the same and for the other it is different?

**Comment by mwaskom** [comment]
Because they produce different matplotlib artists, so they change the state of different color cycles.
