### ISSUE TITLE
hi,how to pain heatmap like this ,triangle

### ISSUE THREAD

**Issue by tomuGo** [mwaskom/seaborn#2600]
![image](https://user-images.githubusercontent.com/24789356/122564778-55426680-d078-11eb-9edc-917d97b001de.png)
i see the example is all rectangle,but i want triangle,every rectangle has ABD,ACD

**Comment by mwaskom** [comment]
Hi, please [ask usage questions](https://github.com/mwaskom/seaborn#development) on stackoverflow, so the issue tracker stays high signal for bug reports. Thanks!
