### ISSUE TITLE
g.map_dataframe.add_legend() does not add legend

### ISSUE THREAD

**Issue by BirkoRuzicka** [mwaskom/seaborn#2607]
```
g = sns.FacetGrid(df_all, col="query", col_wrap=3)
g.map_dataframe(sns.kdeplot, x="week", hue="is_pos",)
g.add_legend()
```
the above code produces the correct FacetGrid of kdeplots, but no legend is added. I've researched the issue extensively and `add_legend()` appears to only work with `g.map()`, but not `g.map_dataframe()`.

sns.__version__ : '0.11.1'
matplotlib.__version__ : '3.4.0'

**Comment by mwaskom** [comment]
Please provide a fully reproducible example, otherwise it's impossible to help. Thanks!

**Comment by mwaskom** [comment]
Also I would (and do, in the docs) strongly advise using `displot` unless you have a really compelling need to use `FacetGrid` directly.

**Comment by BirkoRuzicka** [comment]
Thank you, I plotted my data successfully using `displot`, and the legend shows up just fine there.
