### ISSUE TITLE
Heatplot top and bottom boxes are cut off again

### ISSUE THREAD

**Issue by leweex95** [mwaskom/seaborn#2610]
It seems [an old issue](https://github.com/mwaskom/seaborn/issues/1773) that had already been resolved and closed down back then, is back again. When plotting heatmaps with seaborn, I came across the exact same issue, i.e. half of the top and bottom rows are cut off:

![image](https://user-images.githubusercontent.com/74991597/124466083-861fdc80-dd96-11eb-8f30-f0f00f23f728.png)

`matplotlib` version: 3.1.2
`seaborn` version: 0.11.1
Environment: Jupyter notebook

Code I used:
```
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

np.random.seed(42)
sns.heatmap(np.random.random((10, 10)))
```

**Comment by mwaskom** [comment]
Hi, the original issue was a bug in matplotlib. Do you have any evidence that this recurrence is a seaborn problem?

Also matplotlib 3.1.2 is pretty old ... their current stable release is 3.4.2.

**Comment by leweex95** [comment]
@mwaskom , you are totally right. It was actually a matplotlib error which I experienced even with the newer versions. Turned out there was an error with the matplotlib installation which resulted in residual invalid folder names starting with a `~` in the `python37\lib\site-packages` folder which caused matplotlib to misbehave.
