### ISSUE TITLE
Legend showing non-existent value

### ISSUE THREAD

**Issue by EzicJ** [mwaskom/seaborn#2611]
Hi,

I am sorry for posting this, but I couldn't find the answer elsewhere online although I searched for hours.
How to solve the bug of seaborn showing non-existent value (in my case 1). I tried changing the column to string, and it didn't help. I checked ofc, there are only 3 unique values in the column.

here the screenshot with the code and plot:
Thank you.

![Screenshot 2021-07-08 131449](https://user-images.githubusercontent.com/58070077/124921110-5bcd5980-dff8-11eb-97f8-78facc4480df.png)

**Comment by mwaskom** [comment]
Hi, please see the [guidelines](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs) for reporting bugs; I'm afraid this doesn't provide me with enough information to be able to help. Thanks!

**Comment by EzicJ** [comment]
Thank you for you answer,

since I am new to python and don't know how to share my notebook, I've uploaded it together with the dataframe I use to this link:
https://we.tl/t-Bqx2GcDgPr

I would appreciate you taking a look, it will not take more then a few minutes.

Thank you!

**Comment by mwaskom** [comment]
I have a policy of not downloading/opening file transfers for security reasons. I would suggest finding the smallest amount of your data that reproduces the issue (i.e. `umap_df.head(n)`) and then you can just paste that directly into a github comment. Please also see the fourth guideline, about versions.
