### ISSUE TITLE
displot() causes resizing with plt.figure to fail.

### ISSUE THREAD

**Issue by edkrueger** [mwaskom/seaborn#2613]
When using `displot` as follows, `plt.figure` sizing doesn't work.

```
plt.figure(figsize=(width, height), dpi=dpi)

sns.displot(
        data=df,
        x="x",
        hue="hue",
        kind="hist", # same issue with "ecdf", and "kde"
)

plt.show()
```

However, when replacing `displot` with `histplot`, `kdeplot` or `ecdfplot` and removing the `kind` kwarg the figure is resized as intended.

I'm assuming that somehow the matplotlib canvas is being reinitialized in `displot`, but not in the other functions.

**Comment by mwaskom** [comment]
Hi, this expected (if initially confusing) behavior, in fact there is even [a whole chapter](http://seaborn.pydata.org/tutorial/function_overview.html#specifying-figure-sizes) in the user guide about it.
