### ISSUE TITLE
Bret Victor's dynamic data visualisations

### ISSUE THREAD

**Issue by Lovkush-A** [mwaskom/seaborn#2615]
First, apologies if this is inappropriate - if so, feel free to delete this.

Short version: Is there anything I can do to make Bret Victor's amazing dynamic data viz ideas/program become a reality?

Long version: I recently watched Bret Victor's talk https://vimeo.com/66085662 on 'dynamic drawings' for data visualisation. As far as I can tell, there has been no progress on the project since then (presumably because Bret has too many amazing ideas and cant work on all of them...). The closest thing I have found is this Github repo where somebody else tried coding it up, but it hasn't been changed since 2018: https://github.com/laszlokorte/reform-swift.

My question is: do any of you have any thoughts on how to make this program/idea a reality, and more widely used and known about? If this is not a good place to ask, then any tips on better places to ask would be appreciated.

Thanks!

**Comment by mwaskom** [comment]
I'm afraid I don't have much insight here. There's been a lot of development in the general "dashboard tooling" space since then, so maybe look into those tools? This is definitely outside the scope of seaborn, though, so I'm going to close.
