### ISSUE TITLE
Mass-lineplot in relation to a parameter

### ISSUE THREAD

**Issue by Seneo1** [mwaskom/seaborn#2616]
One dataframe contains the percentage change of several nerve amplitudes at the corresponding measurement points and a second their respective diameters.
```
>>> amp.head()
   Timepoint 1  Timepoint 2  Timepoint 3  Timepoint 4  Timepoint 5  Timepoint 6
0     1.277778     0.944444     0.444444          0.0          0.0          0.0
1     0.941176     0.705882     0.352941          0.0          0.0          0.0
2     0.818182     0.490909     0.309091          0.0          0.0          0.0
3     1.000000     0.658537     0.414634          0.0          0.0          0.0
4     0.588235     0.455882     0.323529          0.0          0.0          0.0

>>> dia.head()
0    1.3
1    1.1
2    1.2
3    1.5
4    1.6
```
I would like to plot the amplitudes in relation to their diameter, as `hue='insert column here'` does in many Seaborn plots. 
```py
def plot_rows(df, color="xkcd:red"):
    # Reference: https://stackoverflow.com/questions/32105817/plot-entire-row-on-pandas

    number = df.shape[0]
    rows = range(number)
    fig, ax = plt.subplots(figsize=(8, 8))
    plt.show()
```
Although this function does plot the amplitudes row by row, it doesn't show their diameter. Would it be possible to include something like this into the seaborn library, especially with the option of the setting the`hue` parameter as an external pandas series?

**Comment by mwaskom** [comment]
Hi, I'm afraid it's a little difficult to help here because your example code just makes a blank figure, so I can't tell what you have tried and found not to work. My general answer is that it's possible to pass a series object to `hue` in `lineplot`. I would suggest asking this question on StackOverflow because I think what you're trying to do is probably already possible, but you may need some help reshaping your data. (Be sure to clarify how you want the plot to look and what you've tried!)

**Comment by Seneo1** [comment]
Hello,

 

thank you for your fast answer. I did ask it on stackoverflow resulting in the following code:



import matplotlib.ticker as mtick
from matplotlib.collections import LineCollection

def multi_lineplot(df, data, cmap="plasma", title=None, xlabel=None, ylabel=None, **kwargs):
    """
    - Creates a line plot of all values provided in 'df' and colors them according to their corresponding
    'data' value
    - Requires the rows of 'df' and 'data' to be related and to have the same '.shape[0]' size
    df: Pandas Dataframe
    data: Pandas Series
    """
    fig, ax = plt.subplots(figsize=(12, 8))

    xs = [np.arange(len(df.columns))] * df.shape[0]
    ys = df.values
    segments = [np.column_stack([x, y]) for x, y in zip(xs, ys)]
    lines = LineCollection(segments, cmap=cmap, **kwargs)
    lines.set_array(data)

    # plot lines and scale axis
    ax.add_collection(lines)
    ax.autoscale()

    # add colorbar
    ax_cb = fig.colorbar(lines)
    ax_cb.set_label(f"\n{data.name}", size=12)

    # styling
    ax.yaxis.set_major_formatter(mtick.PercentFormatter(xmax=1, decimals=None, symbol='%'))
    hide_spines = [ax.spines[s].set_visible(False) for s in ['top', 'right']]
    tic_params = ax.tick_params(axis='both', labelsize=14, bottom=True, left=False)
    x_ticks = ax.set_xticks(np.arange(len(df.columns)))
    tick_labels = ax.set_xticklabels(df.columns)
    ax.set_title(f'{title} vs {data.name}\n', **kwargs)
    ax.set_xlabel(f"\n{xlabel}", **kwargs)
    ax.set_ylabel(f"{ylabel}\n", **kwargs)
    plt.tight_layout()


 

An example output is included in the attachment. It is a plot of all rows from the dataframe passed to it, which then is colored according to the 'data' variable much like 'hue=' would do in many seaborn plots. Would it be possible to include that in a future version upgrade but with all the great features seaborn has to offer?

 

Have a nice day :)

 

 


Gesendet: Freitag, 16. Juli 2021 um 15:16 Uhr
Von: "Michael Waskom" ***@***.***>
An: "mwaskom/seaborn" ***@***.***>
Cc: "Seneo1" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [mwaskom/seaborn] Mass-lineplot in relation to a parameter (#2616)


 

Hi, I'm afraid it's a little difficult to help here because your example code just makes a blank figure, so I can't tell what you have tried and found not to work. My general answer is that it's possible to pass a series object to hue in lineplot. I would suggest asking this question on StackOverflow because I think what you're trying to do is probably already possible, but you may need some help reshaping your data. (Be sure to clarify how you want the plot to look and what you've tried!)

**Comment by Seneo1** [comment]
Hello,

thank you for your fast answer. I did ask it on [stackoverflow](https://stackoverflow.com/questions/68400290/multiple-lineplots-with-a-dependency-variable) resulting in the following code:

```py
import matplotlib.ticker as mtick
from matplotlib.collections import LineCollection

def multi_lineplot(df, data, cmap="plasma", title=None, xlabel=None, ylabel=None, **kwargs):
    """
    - Creates a line plot of all values provided in 'df' and colors them according to their corresponding
    'data' value
    - Requires the rows of 'df' and 'data' to be related and to have the same '.shape[0]' size
    df: Pandas Dataframe
    data: Pandas Series
    """
    fig, ax = plt.subplots(figsize=(12, 8))

    xs = [np.arange(len(df.columns))] * df.shape[0]
    ys = df.values
    segments = [np.column_stack([x, y]) for x, y in zip(xs, ys)]
    lines = LineCollection(segments, cmap=cmap, **kwargs)
    lines.set_array(data)

    # plot lines and scale axis
    ax.add_collection(lines)
    ax.autoscale()

    # add colorbar
    ax_cb = fig.colorbar(lines)
    ax_cb.set_label(f"\n{data.name}", size=12)

    # styling
    ax.yaxis.set_major_formatter(mtick.PercentFormatter(xmax=1, decimals=None, symbol='%'))
    hide_spines = [ax.spines[s].set_visible(False) for s in ['top', 'right']]
    tic_params = ax.tick_params(axis='both', labelsize=14, bottom=True, left=False)
    x_ticks = ax.set_xticks(np.arange(len(df.columns)))
    tick_labels = ax.set_xticklabels(df.columns)
    ax.set_title(f'{title} vs {data.name}\n', **kwargs)
    ax.set_xlabel(f"\n{xlabel}", **kwargs)
    ax.set_ylabel(f"{ylabel}\n", **kwargs)
    plt.tight_layout()
   ```


 

Here is an example output.

![example](https://user-images.githubusercontent.com/25407654/125961734-7e044432-e353-4e5e-a074-1978a007259f.png)

It is a plot of all rows from the dataframe passed to it, which is then colored according to the `data` variable similar to `hue=` in many seaborn plots. Would it be possible to include that in a future seaborn version including all the great features seaborn has to offer?

Have a nice day :)
