### ISSUE TITLE
Pairplot "corner plot" with upper triangular 

### ISSUE THREAD

**Issue by guillermo-jimenez** [mwaskom/seaborn#2618]
Hi all,

First of all, thanks for your amazing work with this project, really a life saver!

I was wondering whether you'd see fit to have an extra input _kwarg_ for the pairplot (and other plots that have a "corner" argument) so that the lower triangular axes are removed instead of the upper triangular. I know it's rather picky but it can affect data visualization. It'd simply consist in giving the chance of setting `np.tril_indices_from(axes, -1)` [here](https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L1199) and maybe display the label names in the diagonal [here](https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L1554):

![image](https://user-images.githubusercontent.com/18657641/125929841-842d8521-cfcd-4d19-8730-f2d4a49f1f8d.png)

Anyway, in case someone stumbles upon this issue from google, an alternative to do so is something like this:

```python
g = sn.PairGrid(data)
g.map_upper(sn.scatterplot); g.map_diag(sn.kdeplot, shade=True)
[g.axes[i,j].remove() for i,j in zip(*np.tril_indices_from(g.axes, -1))]
[g.axes[i,i].set_xlabel(f"Dim. {i+1}") for i,k in enumerate(data.keys())]
[g.axes[i,i].set_ylabel(f"Dim. {i+1}") for i,k in enumerate(data.keys())]
```

Thanks

**Comment by mwaskom** [comment]
Hi, thanks for the suggestion. I think I'm -1 on it, though. Adding a new parameter and complexity to the code doesn't seem worth the benefit here.

First, the implementation will be more complicated than you've suggested. It's not just about setting up the grid, you'll also need to revisit the upper/lower logic during the actual plotting. And you may note that your plot doesn't have visible tick labels on the axes that are "interior" to a normal pair plot. Those are important!

Sorting that all out would not be especially difficult, but I'm not persuaded it's worth it. You say it "can affect data visualization" but don't specify exactly what you have in mind. It's true that the same pairwise relationships appear a little differently in the upper and lower triangles, but

a) if it really matters in your usecase, you should probably be showing both?
b) you can get the same effect in the lower triangle by reversing the order of the y variables
c) as you show, if you really need an upper triangular grid, you can get it to work through user-space manipulations
