### ISSUE TITLE
lmplot with scatter_kws or relplot with s: ValueError: s must be a scalar, or float array-like with the same size as x and y

### ISSUE THREAD

**Issue by trenton3983** [mwaskom/seaborn#2621]
- Seaborn 0.11.1 and matplotlib 3.4.2
- Attempting to adjust the size of the marker with a parameter (`s`) results in `ValueError: s must be a scalar, or float array-like with the same size as x and y`
-  Based on the example in this [excerpt][1], this used to work.

```python
import seaborn as sns

tips = sns.load_dataset('tips')

# choose 1 to plot
sns.relplot(kind='scatter', x='total_bill', y='tip', data=tips, hue='sex', s='size')

# choose 1 to plot
sns.lmplot( x='total_bill', y='tip', data=tips, fit_reg=False, hue='sex', scatter_kws={'s': tips['size']})
```

- `.scatterplot` works as expected with `hue` and `size`
```python
sns.scatterplot(data=tips, x="total_bill", y="tip", hue="size", size='size')
```
![image](https://user-images.githubusercontent.com/12875240/126362335-e6dbeb81-1f97-47eb-b54d-fdb0419b3112.png)

- `.lmplot` works without `hue`
```python
sns.lmplot( x='total_bill', y='tip', data=tips, fit_reg=False, scatter_kws={'s': tips['size'].mul(10)})
```
![image](https://user-images.githubusercontent.com/12875240/126363072-c5c0eb72-9965-4877-a3f3-cd257581a9e2.png)

  [1]: https://www.google.com/books/edition/Pandas_for_Everyone/7zhDDwAAQBAJ?hl=en&gbpv=1&dq=Pandas+for+everyone%22+(3.4.3.2+Size+and+Shape&pg=PT138&printsec=frontcover

**Comment by mwaskom** [comment]
I don't think this ever actually "worked" (alarmed that it's in that book!)

`lmplot` draws separate scatterplots for each level of `hue`, but the matplotlib kwargs are just passed straight through to `scatter`, so those vectors are going to have different lengths. I believe the reason it stopped "working" is that matplotlib added some input validation to catch cases like this.

In any case, `scatterplot`/`relplot` are the modern way to make such a plot in seaborn. If you see people recommending `lmplot(..., fit_reg=False)`, please urge them to update their materials!

**Comment by trenton3983** [comment]
Thanks for the FYI, Michael. Also, just to be clear, `sns.relplot(kind='scatter', x='total_bill', y='tip', data=tips, hue='sex', s='size')` results in the same error as `lmplot`. So only `scatterplot` works.

**Comment by mwaskom** [comment]
It's the same error in the sense the matplotlib is rejecting a value that doesn't make sense, but the nature of what's going wrong is different ... in this case the string `"size"` is getting passed through to matplotlib, which is different from the `lmplot` case in the OP where there is a vector of numbers with a different length from `x` and `y`.

What *does* work in `relplot` (provided you are not faceting) would be 

```python
sns.relplot(data=tips, x='total_bill', y='tip', hue='sex', s=tips['size'] * 20)
```

because unlike `lmplot` it is only internally calling `ax.scatter` once with the full x/y data, and so passing in a matched vector of `s` values does what you would expect.
