### ISSUE TITLE
histplot option stack does not work with logarithmic y-axis

### ISSUE THREAD

**Issue by Khris777** [mwaskom/seaborn#2627]
It doesn't seem to be possible to create a stacked histplot with logarithmic y-axis.

Neither
```
sns.histplot(df[df, x="...", hue="...", bins=200, multiple="stack", log_scale=(False, True))
```
nor
```
sns.histplot(df[df, x="...", hue="...", bins=200, multiple="stack").set_yscale("log")`
```
works.

Seaborn 0.11.1
Matplotlib 3.4.2
Python 3.7.10

**Comment by mwaskom** [comment]
Hi, can you please provide a fully reproducible example and error trace or example of what you are seeing (per the bug report guidelines https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs)? I do not seem to have any issue using the tips dataset:

```python
sns.histplot(tips, x="total_bill", hue="sex", multiple="stack", log_scale=(False, True))
```

but it's impossible to know what is happening on your end.

As an aside, I'm not sure it makes much sense to stack a histogram with a log counts axis. But there's nothing in seaborn stopping you from doing it.

**Comment by mwaskom** [comment]
Closing for lack of information.
