### ISSUE TITLE
Warning related to wayland

### ISSUE THREAD

**Issue by jazarija** [mwaskom/seaborn#2628]
I am using seaborn 0.11.1. Recently I've noticed that all my scripts and programs issue the following warning when they're run

`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`

Isolating the issue I've noticed that it happens when I import seaborn:

```
foo@bar:~$ ipython3
Python 3.9.5 (default, May 11 2021, 08:20:37) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import seaborn

In [2]: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
In [2]: 

```

Note that the same warning persists if I follow the tip in the warning and setting QT_QPA_PLATFORM=wayland

```
foo@bar:~$ export QT_QPA_PLATFORM=wayland 
foo@bar:~$ ipython3 
Python 3.9.5 (default, May 11 2021, 08:20:37) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import seaborn

In [2]: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
In [2]: 
```

I've been googling for a solution, but unfortunately all instances of this issue are not applicable to this case. Any idea what's causing this warning and how to (properly) fix it?

**Comment by mwaskom** [comment]
I'm afraid I don't have any particular insight here. Looks like a weird interaction between your linux windowing application and Qt, the GUI backend that your matplotlib is using. Seaborn is completely agnostic to the matplotlib backend so it's not doing anything that would be causing this error directly.

Were I debugging this, I'd first confirm that importing `matplotlib.pyplot` triggers the warning. Then I would use switch to a non-Qt backend and see if it goes away. Then I guess you'd have to decide how much of a problem it actually is? In my experience with linux, the signal-to-noise ratio of warnings related to graphics is pretty low....

**Comment by mwaskom** [comment]
Closing as I don't think there's anything seaborn can do here, but ping if you investigations turn something up.

**Comment by mwaskom** [comment]
(Some) more information here: https://discourse.matplotlib.org/t/warnings-when-on-wayland/21071
