### ISSUE TITLE
Clustermap method/metric limitation

### ISSUE THREAD

**Issue by PingYunOu** [mwaskom/seaborn#2630]
Since the function used in the _calculate_linkage_scipy function was scipy.cluster.hierarchy.linkage, certain combinations of distance metrics and clustering methods are not allowed, e.g. ward method requires the euclidean metric.
Thus I suggest to separate this function into two steps:
from scipy.spatial.distance import pdist
which calculates the distance matrix, then
from scipy.cluster.hierarchy import f'{method}'
which use the specific method for clustering

**Comment by mwaskom** [comment]
Can you please provide a reproducible example of the problem you're having, along with your versions of seaborn and scipy? Thanks.

**Comment by PingYunOu** [comment]
The versions of seaborn and scipy are both the latest, I suppose.
Use the tutorial dataset iris as a demonstration:
`import seaborn as sns; sns.set_theme(color_codes=True)
iris = sns.load_dataset("iris")
species = iris.pop("species")
g = sns.clustermap(iris,metric='correlation',method='ward')`

the following error message would pop up due to the limitations of scipy.cluster.hierarchy.linkage():
ValueError: Method 'ward' requires the distance metric to be Euclidean

But my current work would like the distance metric to be in correlation, which limits the clustering methods that could be used.

**Comment by mwaskom** [comment]
If you look at the traceback, the error message is being raised from scipy:

```python-traceback
~/miniconda3/envs/py39/lib/python3.9/site-packages/scipy/cluster/hierarchy.py in linkage(y, method, metric, optimal_ordering)
   1051     elif y.ndim == 2:
   1052         if method in _EUCLIDEAN_METHODS and metric != 'euclidean':
-> 1053             raise ValueError("Method '{0}' requires the distance metric "
   1054                              "to be Euclidean".format(method))
   1055         if y.shape[0] == y.shape[1] and np.allclose(np.diag(y), 0):

ValueError: Method 'ward' requires the distance metric to be Euclidean
```

and the [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html) say:

> Methods ‘centroid’, ‘median’, and ‘ward’ are correctly defined only if Euclidean pairwise metric is used. If y is passed as precomputed pairwise distances, then it is the user’s responsibility to assure that these distances are in fact Euclidean, otherwise the produced result will be incorrect.

Why do you think there is something seaborn can do differently here?

PS

> The versions of seaborn and scipy are both the latest, I suppose.

You can check with `import seaborn; print seaborn.__version__`, and likewise with scipy.

**Comment by PingYunOu** [comment]
I recognize this is due to the limitation of the scipy function scipy.cluster.hierarchy.linkage.
Which could be traced back to the adoption of the linkage function in the matrix.py:
```
    def _calculate_linkage_scipy(self):
        linkage = hierarchy.linkage(self.array, method=self.method,
                                    metric=self.metric)
        return linkage
```

Thus, I was hoping if the current version could be changed into a combination of other functions.


Specifically:
`from scipy.spatial.distance import pdist`
`dist_matrix = pdist(matrix,metric)` which obtains a distance matrix
`from scipy.cluster.hierarchy import f'{method}'` which imports the specified clustering method, e.g. ward
`linkage = ward(dist_matrix)` which obtains the linkage matrix which the same as the output of the linkage function.

I've made a very scuffed version using the built-in exec() function to make this concept work, and I'm hesitating if I should make a pull request for further examination since I have very little faith in my own work.
The adoption I made is like the following:
```
    def _calculate_linkage_scipy(self):
        from scipy.spatial.distance import pdist
        dist = pdist(self.array, metric=self.metric)
        lo = locals()
        dummy='link'
        exec(f'from scipy.cluster.hierarchy import {self.method}',{},lo)
        exec(f'dummy = {self.method}(dist)',{},lo)
        linkage=lo['dummy']
        return linkage
```
I've tested it in my own work, and it somehow functioned, I'm not sure if it's reliable enough though.

**Comment by mwaskom** [comment]
But, again, the scipy docs say

> If y is passed as precomputed pairwise distances, then it is the user’s responsibility to assure that these distances are in fact Euclidean, **otherwise the produced result will be incorrect.**

This isn't an oversight in the scipy code, it's actively preventing you from doing something that doesn't make sense.

You can pass a precomputed linkage matrix to `clustermap`, so if you're absolutely determined to accomplish this for some reason, that is what you could do. But I don't think seaborn should hack its way around valid constraints in scipy.

**Comment by PingYunOu** [comment]
Thanks for the answering my question, I guess I should review the scipy document more thoroughly to better understand the method that I'm using.
