### ISSUE TITLE
Feature request: visualize continuous variable in categorical scatter plot

### ISSUE THREAD

**Issue by eremingt** [mwaskom/seaborn#2631]
It would be great to be able to simultaneously represent continuous and categorical variables in the same scatter plot, for example a swarm plot with categorical/integer factor along the x-axis and a continuous variable represented by color (with a continuous color bar). Seems the closest I can get is to discretize the categorical variable.

Note sure, but this may be related to (or duplicate) https://github.com/mwaskom/seaborn/issues/2172

**Comment by mwaskom** [comment]
Hi, see https://github.com/mwaskom/seaborn/issues/2429

**Comment by eremingt** [comment]
Oh, great!
