### ISSUE TITLE
facetgrid points consolidated

### ISSUE THREAD

**Issue by stopwind93** [mwaskom/seaborn#2641]
I am having problem if I have more than 90 plots in a facetgrid
![image](https://user-images.githubusercontent.com/54277944/129303902-42066cd8-02bf-4844-8eca-87199a5439b4.png)

If less than 90 seems to be working fine
![image](https://user-images.githubusercontent.com/54277944/129304173-2b080c85-3dc7-4178-bb13-355e7ca34a95.png)

**Comment by stopwind93** [comment]
[df.csv](https://github.com/mwaskom/seaborn/files/6980241/df.csv)

my code:
```
df = df[df['TOOLS'].isin(['DC8800Q-0006'])]
unique_strips = df.groupby(by=['STRIP_ID',bintype]).size().unstack().reset_index()
unique_strips = unique_strips.fillna(value=0)
unique_strips = unique_strips[~unique_strips[querysbin].isin([0])]['STRIP_ID']
df = df.groupby(by=['D_LOCX','D_LOCY','STRIP_ID','PROCESS','TOOLS',bintype]).size().unstack().reset_index()
df1 = df.fillna(value=0)

print(len(unique_strips))
unique_strips=unique_strips[:90]
a = df1[df1.TOOLS.isin(['DC8800Q-0006'])]
a = a[a.STRIP_ID.isin(unique_strips)]

vmin = a[querysbin].min()
vmax = a[querysbin].max()

cmap1 = sns.blend_palette(['#00b500','#FFFF00','#FF0000'], as_cmap=True)
cmap = sns.blend_palette(['#00b500','#FFFF00','#FF0000'],as_cmap=True)
g = sns.FacetGrid(a, col='STRIP_ID',col_wrap=6, height=2, sharey='col', sharex='row', aspect=2)
g.map_dataframe(draw_heatmap, 'D_LOCX', 'D_LOCY', querysbin, cbar=False, square = True, cmap=cmap, vmin=vmin, vmax=vmax, linewidths=.5)
g.fig.gca().invert_xaxis()
g.fig.subplots_adjust(wspace=.02, hspace=.02)
g.set_titles("{col_name}",size=10)
g.set_xticklabels(fontsize = 6)
g.fig.subplots_adjust(right=.92)
cax = g.fig.add_axes([.94, .25, .02, .6])
points = plt.scatter([], [], c=[], vmin=vmin, vmax=vmax, cmap=cmap1)
g.fig.colorbar(points, cax=cax)
g.fig.tight_layout()
```

**Comment by mwaskom** [comment]
> I am having problem if I have more than 90 plots in a facetgrid

Sorry, but can you explain more about what the problem is? I don't know what you expect the plot to look like, so I can't diagnose the problem just by seeing the current output. And thanks for sharing your data and script, but it's quite a complicated example. It's *much* easier to provide support with a [minimal example](https://blog.dask.org/2018/02/28/minimal-bug-reports), because without knowing what you are trying to do, it's very difficult for someone to know what is/essential to your desired output.

**Comment by stopwind93** [comment]
hi, sorry that it is complicated, cause I am using this library for work.

Essentially, I would like the plot to display every point like the 2nd image (6x14). 

If I adjust to more than 90 images in a facetgtrid, seems like the points are consolidated together (3x4).
`unique_strips=unique_strips[:90]`

**Comment by stopwind93** [comment]
hi @mwaskom,

[df.csv](https://github.com/mwaskom/seaborn/files/7004790/df.csv)

I tried to shorten the whole thing.
[sample.pdf](https://github.com/mwaskom/seaborn/files/7004788/sample.pdf)

From output[15], can be observed if there are more than 90 plots, the result came out to be 3x4 per plot.
From output[23], can be observed if there are only 2 plots, the result came out to be 6x18 per plot (which is the desired output).

Let me know if you have any enquiries.
Thanks.

**Comment by mwaskom** [comment]
I will try to take a look but my advice for debugging this is that any time you encounter a "magic number" like "it stops working for more than 90 plots" you should think: "is there really something special about 90?" Occasionally the specific number matters (especially if it's a power of 2), but I would try things like, "what if I use `[10:100]` instead of `[0:90]`?" "What if I use `[80:100]`?" "What if I directly compare `[90]` and `[91]`?

**Comment by mwaskom** [comment]
I'm also still not quite sure what you mean by the points being "consolidated" ... being especially clear/precise about understanding what the problem *is* can often help clarify its cause.

**Comment by stopwind93** [comment]
> I will try to take a look but my advice for debugging this is that any time you encounter a "magic number" like "it stops working for more than 90 plots" you should think: "is there really something special about 90?" Occasionally the specific number matters (especially if it's a power of 2), but I would try things like, "what if I use `[10:100]` instead of `[0:90]`?" "What if I use `[80:100]`?" "What if I directly compare `[90]` and `[91]`?

okay, I will try your advice tomorrow.

**Comment by stopwind93** [comment]
> I'm also still not quite sure what you mean by the points being "consolidated" ... being especially clear/precise about understanding what the problem _is_ can often help clarify its cause.

okay, probably not consolidated. The plots just came out weird and not as expected.

**Comment by jhncls** [comment]
Here is some standalone test code:
```python
import seaborn as sns
import pandas as pd
import numpy as np

def draw_heatmap(*args, **kwargs):
    data = kwargs.pop('data')
    d = data.pivot(index=args[1], columns=args[0], values=args[2])
    sns.heatmap(d, **kwargs)

N = 90  # number of "strips"
R = 6  # number of rows 
C = 18  # number of columns
df = pd.DataFrame({'strip': np.repeat(np.arange(N), R * C),
                   'x': np.tile(np.repeat(np.arange(1, C + 1), R), N),
                   'y': np.tile(np.tile(np.arange(1, R + 1), C), N),
                   'PassFail': np.random.randint(0, 2, R * C * N)})
g = sns.FacetGrid(df, col='strip', col_wrap=6, height=2, sharey='col', sharex='row', aspect=2)
g.map_dataframe(draw_heatmap, 'x', 'y', 'PassFail', cbar=False, square=True, linewidth=0.5)
```
In my environment, the output still contains 6x18 cells in the heatmaps.  However, it takes more than 10 minutes to render. Also, the titles and the tick labels get pushed away.  Probably, depending on the backend, there is a maximum figsize, and matplotlib automatically reduces the sizes of the subplots. Maybe seaborn could issue a warning in that case?

For this example, a cleaner approach would be to not generate all the strips together, but only one subset at a time. For example, having maximum 60 strips per matplotlib figure. It also could help to set smaller text sizes.

**Comment by mwaskom** [comment]
> Probably, depending on the backend, there is a maximum figsize, and matplotlib automatically reduces the sizes of the subplots. Maybe seaborn could issue a warning in that case?

I very much doubt that's the case. matplotlib *does* have a maximum figsize, but it raises if you ask for it:

```python
plt.subplots(figsize=(2 ** 17, 2 ** 17))
plt.show()
```
```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/seaborn-py37-pinned/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~/miniconda3/envs/seaborn-py37-pinned/lib/python3.7/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~/miniconda3/envs/seaborn-py37-pinned/lib/python3.7/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

~/miniconda3/envs/seaborn-py37-pinned/lib/python3.7/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2063                         orientation=orientation,
   2064                         dryrun=True,
-> 2065                         **kwargs)
   2066                     renderer = self.figure._cachedRenderer
   2067                     bbox_artists = kwargs.pop("bbox_extra_artists", None)

~/miniconda3/envs/seaborn-py37-pinned/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args, **kwargs)
    525 
    526         else:
--> 527             FigureCanvasAgg.draw(self)
    528             renderer = self.get_renderer()
    529             with cbook._setattr_cm(renderer, dpi=self.figure.dpi), \

~/miniconda3/envs/seaborn-py37-pinned/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    384         Draw the figure using the renderer.
    385         """
--> 386         self.renderer = self.get_renderer(cleared=True)
    387         with RendererAgg.lock:
    388             self.figure.draw(self.renderer)

~/miniconda3/envs/seaborn-py37-pinned/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in get_renderer(self, cleared)
    397                           and getattr(self, "_lastKey", None) == key)
    398         if not reuse_renderer:
--> 399             self.renderer = RendererAgg(w, h, self.figure.dpi)
    400             self._lastKey = key
    401         elif cleared:

~/miniconda3/envs/seaborn-py37-pinned/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in __init__(self, width, height, dpi)
     84         self.width = width
     85         self.height = height
---> 86         self._renderer = _RendererAgg(int(width), int(height), dpi)
     87         self._filter_renderers = []
     88 

ValueError: Image size of 9437184x9437184 pixels is too large. It must be less than 2^16 in each direction.
```

**Comment by jhncls** [comment]
Or, the backend might reduce the size when fitting the plot into a window (or into a Jupyter cell)?

[This post](https://stackoverflow.com/questions/55566198/setting-figure-size-to-be-larger-than-screen-size-in-matplotlib) suggests changing the backend (`matplotlib.use('Agg')`) and save to file.

**Comment by stopwind93** [comment]
[df2.csv](https://github.com/mwaskom/seaborn/files/7028573/df2.csv)

Hi @mwaskom,

Thanks for the guidance.
I checked further and found that if there are two plots with different dimensions, it will give error.

For example,
strip A having 6x16 dimension while strip B having 1x2 dimension.
The resulting facetgrid will plot 1x2 dimension.

`import pandas as pd
import seaborn as sns
df = pd.read_csv('df2.csv')
print(df)

def draw_heatmap(*args, **kwargs):
    data = kwargs.pop('data')
    d = data.pivot(index=args[1], columns=args[0], values=args[2])
    sns.heatmap(d, **kwargs)
    
# df = df[df.strip.isin(['RH6213093000-4001'])]
# df = df[df.strip.isin(['RH6213093000-3708'])]

cmap = sns.blend_palette(['#00b500','#FFFF00','#FF0000'],as_cmap=True)
g = sns.FacetGrid(df, col='strip',col_wrap=6, height=2, sharey='col', sharex='row', aspect=2)
g.map_dataframe(draw_heatmap, 'x', 'y', 'PassFail',cbar=False, square = True, cmap=cmap, linewidths=.5)`

**Comment by jhncls** [comment]
So, probably you'd prefer `g = sns.FacetGrid(..., sharey=False, sharex=False)`

**Comment by mwaskom** [comment]
Well what you want to do is ensure that the data frame you’re passing to heatmap has the same rows and columns in every plot.

**Comment by stopwind93** [comment]
Is it possible that if it is empty, I would like it to be empty instead of 1 or 0.
I believe if it is empty, the facetgrid will give error right?

**Comment by mwaskom** [comment]
I’m not sure what you mean. What is “it”? What does “empty” mean?

**Comment by stopwind93** [comment]
For example:
![image](https://user-images.githubusercontent.com/54277944/130448122-6ff551b4-f7b7-47e2-8af1-5d09a313b1d4.png)
1,1 is neither 1 or 0. It is empty.

**Comment by mwaskom** [comment]
I'm still not following. Doesn't your initial plot have lots of facets with "empty" cells? What is the issue?

**Comment by stopwind93** [comment]
If they are with "empty cells", how do I ensure that the data frame I am passing to heatmap has the same rows and columns in every plot?

**Comment by mwaskom** [comment]
I suppose there's a few different ways; the first one that comes to mind would be to store lists of all the x/y values you want and reindex after pivoting:

```python
d = (
    data
    .pivot(index=args[1], columns=args[0], values=args[2])
    .reindex(index=full_index, columns=full_columns)
)
```

**Comment by stopwind93** [comment]
> So, probably you'd prefer `g = sns.FacetGrid(..., sharey=False, sharex=False)`

Thanks @jhncls, it seemed to work!

**Comment by stopwind93** [comment]
Thanks @mwaskom! That solved my issue.
