### ISSUE TITLE
The scale of plot is not accurate using parameters log_scale in displot( )

### ISSUE THREAD

**Issue by kv235711** [mwaskom/seaborn#2642]
In **_the official tutorial：Visualizing distributions of data_**，when I try to plot one discrete and one continuous variable in one bivariate histogram with the following code，I find that **the scale of the generated plot is not accurate**.
`sns.displot(x="price", y="clarity", data=diamonds, log_scale=(True, False))`
![image](https://user-images.githubusercontent.com/76828138/129315351-e868a6ba-6473-44a8-b493-679da4b728e8.png)

Because my English is really poor, so I'll make it short. If we don't use parameters log_scale, the original value of the variable price is this. You know, log10(17,500)  is too far to ten to the forth.
 `sns.displot(x='price', y='clarity', data=diamonds)`
![image](https://user-images.githubusercontent.com/76828138/129435827-0c666d52-bc1b-4cd1-b529-70bf3bad421f.png)
To find out why,  I take the log of the continuous variable first，and we're going to get something like this. The difference between these two pictures is their x-coordinates. You will see,  ten to the third and  ten to the forth in the x-coordinate of the first plot should **actually be three × ten to the zero and four × ten to the zero**. 
` diamonds['price'] = np.log10(diamonds['price'])`
 `sns.displot(x='price', y='clarity', data=diamonds)`
![image](https://user-images.githubusercontent.com/76828138/129320148-6d009cfc-1391-425a-a4ff-ac1b602e1e00.png)
Honestly, I'm not that good, okay？I'm not sure whose problem it is, but I'm sure there's a problem.
Maybe you can give me an answer. Thanks.

**Comment by mwaskom** [comment]
Maybe this will help clarify what's happening:

```python
import seaborn as sns, matplotlib as mpl, matplotlib.pyplot as plt

f, axs = plt.subplots(4, tight_layout=True)

# Plot the original data
sns.scatterplot(x=x, y=0, ax=axs[0])

# Log transform the data, then plot
sns.scatterplot(x=np.log10(x), y=0, ax=axs[1])

# Plot the data on a log scale
axs[2].set_xscale("log")
sns.scatterplot(x=x, y=0, ax=axs[2])

# Plot the data on a log scale with scalar-formatted ticks
axs[3].set_xscale("log")
axs[3].xaxis.set_major_formatter(mpl.ticker.ScalarFormatter())
sns.scatterplot(x=x, y=0, ax=axs[3])
```
![image](https://user-images.githubusercontent.com/315810/129445891-13b64c51-5da8-49ef-a905-333ebcd37865.png)

The log scale affects the distance between points in visual space. Matplotlib also writes the tick labels as `base ^ log(val)` to make the scaling more obvious.

It is different from log-transforming the data and plotting on a linear scale. But it give the same visual result. Only the ticks are different.

Does that make sense?

**Comment by mwaskom** [comment]
Closing as this is working as expected, as far as I can tell.

**Comment by kv235711** [comment]
Even though I still don't quite understand your last operation(# Plot the data on a log scale with scalar-formatted ticks), I think I know what you said is what mean. 

The purpose of using parameter log_scale can be said to **prefer to change the distance between the data points, rather than the data itself.** For positive skew data, after taking logarithm, smaller data will become scattered and larger data will become compact, which may make the distribution of data more symmetrical. The point is that there is no change in the relative position or size of the data. I have to say this is a pretty nice operation. **So the abscissa scale of the generated plot with parameter log_scale set (True, False)  should correspond to the original data.**

What I was saying is really not a problem once I know what's going on, right? Thank you for explaining it to me.
