### ISSUE TITLE
Pass list of strings to pairplot() to rename data-frame column names on-the-fly

### ISSUE THREAD

**Issue by NikosAlexandris** [mwaskom/seaborn#2646]
It would be useful and convenient to have an option to pass a list of variable names (column names in the input data-frame) directly to `pairplot()`. This way, instead of having the actual column names (which may look like `flipper_length_mm` and `bill_length_mm`), a user can _prettify_ the names on-the-spot, passing something like `Flipper length (mm)`). Much like other options exist in other functions.

**Comment by mwaskom** [comment]
As mentioned on gitter, I think this is easily handled through existing functionality. Given a mapping of column names to preferred labels:

```python
sns.pairplot(df.rename(columns=mapping))
```

Which accomplishes which you want without create an intermediate variable.

It's not possible to pass a list here, as you suggest. I think that passing a list in this sort of situation is an antipattern; if the column order changes for some reason, you'll get a plot that is incorrect (but not necessarily obviously so). But if you are completely sure your list is in the correct order, you can do

```python
sns.pairplot(df.rename(columns=dict(zip(df.columns, labels))))
```

or if that feels too complex

```python
mapping = dict(zip(df.columns, labels))
sns.pairplot(df.rename(columns=mapping))
```

**Comment by NikosAlexandris** [comment]
> ```python
> mapping = dict(zip(df.columns, labels))
> sns.pairplot(df.rename(columns=mapping))
> ```

Great. So one has to take care about the correspondence of columns vs labels in `zip(df.columns, labels)`.
