### ISSUE TITLE
How to silence 'seaborn.axisgrid.PairGrid at 0x...' when calling pairplot() in Jupyter Notebooks?

### ISSUE THREAD

**Issue by NikosAlexandris** [mwaskom/seaborn#2647]
A `pairplot()` call like
```python
In [4]:
sns.pairplot(df, kind = 'scatter',diag_kind='kde')
```
will print out (before the plot) a message like
```python
Out[4]:
seaborn.axisgrid.PairGrid at 0x...
```

I have many local examples of this. See also for example the same in [some notebook on the web](https://notebook.community/jbliss1234/ML/o).

How can this message be silenced?

**Comment by mwaskom** [comment]
This is a REPL output.

If you don't want to see it, you can either:

1) assign the output to a variable
2) end the line in a semicolon
3) add a no-return function like `plt.show` (which is not necessary in a notebook, but also has no bad side effects) at the end of the cell

Please use StackOverflow or discourse for usage questions, though — they're more visible than github issues.

**Comment by mwaskom** [comment]
I guess you could also do

```python
sns.axisgrid.Grid.__repr__ = lambda self: ""
```

at the top of your notebook.

**Comment by NikosAlexandris** [comment]
> This is a REPL output.
> 
> If you don't want to see it, you can either:
> 
>     1. assign the output to a variable
> 
>     2. end the line in a semicolon
> 
>     3. add a no-return function like `plt.show` (which is not necessary in a notebook, but also has no bad side effects) at the end of the cell
> 

1. Works. In practice, adding a title or else instructions in the same cell, there is still some output (not a pairplot()'s one).

2. Works best so far.

3. Works, is more visible than a `;` -- maybe too much.

4. The `sns.axisgrid.Grid.__repr__ = lambda self: ""` will produce an empty output cell (without any of the above tricks). While it's one line, I don't think it's nice to have empty output cells when the goal is to compile a nice output from a notebook.

Thank you :pray:

**Comment by mwaskom** [comment]
> Works. In practice, adding a title or else instructions in the same cell, there is still some output (not a pairplot()'s one).

Yeah, like I said it has nothing to do with seaborn specifically. If the last line in your cell has a return value, it will appear in the cell output.

**Comment by NikosAlexandris** [comment]
> Please use StackOverflow or discourse for usage questions, though — they're more visible than github issues.

(Maybe I should take some time to expose this Q&A in SO.)
