### ISSUE TITLE
barplot: cannot pass align="edge" using kwargs

### ISSUE THREAD

**Issue by boeleman** [mwaskom/seaborn#2648]
Hello Michael,

I would like to align my barplot on the edge, but this is not working. Here is a minimal working example:
```
import seaborn as sns

kwargs = {"align":"edge"}
sns.set_theme(style="whitegrid")
tips = sns.load_dataset("tips")
ax = sns.barplot(x="day", y="total_bill", data=tips, **kwargs)
```
However, I get the error message:
```
TypeError: matplotlib.axes._axes.Axes.bar() got multiple values for keyword argument 'align'
```
I would expect that align passed as a kwarg would override the seaborn default.

Thanks,

Arnout

**Comment by mwaskom** [comment]
Can I ask what the practical usecase would be here? I don't think of `align=` in `ax.bar` as a parameter you'd typically need to tweak; rather it exists to support drawing bars on a numeric axis with the kind of data encoding you'd have if you were making a histogram.

**Comment by boeleman** [comment]
"rather it exists to support drawing bars on a numeric axis with the kind
of data encoding you'd have if you were making a histogram."

That is exactly the use case. I have some pre-computed histogram data that
I would like to plot. If align="edge" were supported, a barplot would be
the easiest way to plot this histogram data and make it look like histplot.

Thanks,

Arnout

**Comment by mwaskom** [comment]
I don't think that's going to work the way you're hoping, because the barplot axis is always categorical.

**Comment by boeleman** [comment]
Using matplotlib.pyplot.bar this worked well. However, since I used seaborn
for my other plots it does not look consistent (colors, column width, etc).

**Comment by mwaskom** [comment]
I'm not sure what your other plots look like, but seaborn is (as I'm sure you know) just generating matplotlib plots and if you activate one of its styles, that will change the appearance of plots made by directly interacting with the matplotlib objects.

**Comment by boeleman** [comment]
I was just able to get the matplotlib bar plot to look like my seaborn
plot, so at this point having the align="edge" option would just be to get
rid of an error message.

**Comment by mwaskom** [comment]
Great. Given that barplot currently doesn't support interval data and I can't think of a reason you'd want to align on the edges otherwise, I'm going to close for now. Things may change in the future.
