### ISSUE TITLE
boxplot: usermedians parameter is not compatible with matplotlib

### ISSUE THREAD

**Issue by cristobaltapia** [mwaskom/seaborn#2657]
Hi, I think there is a problem with the `boxplot` function. In matplotlib, the boxplot function accepts the `usermedians` parameter, which should have the same length as the number of boxplots shown. A simple example would be this:

```python
import matplotlib.pyplot as plt

data = [[3.1, 3.5, 2.4], [6.5, 6.4, 4.5]]

fig = plt.figure(figsize=(2.8, 2.0))
ax = fig.add_subplot(111)
ax.boxplot(x=data, usermedians=[4, 5])
plt.show()

```

However, this does not work when plotting with seaborn. For example, the following example gives the error:

```
ValueError: 'usermedians' and 'x' have different lengths
```

```python
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame(data={
    "x": [1, 1, 1, 2, 2, 2],
    "y": [3.1, 3.5, 2.4, 6.5, 6.4, 4.5],
})

fig = plt.figure(figsize=(2.8, 2.0))
ax = fig.add_subplot(111)
sns.boxplot(data=df, x="x", y="y", usermedians=[4, 5], ax=ax)
plt.show()
```

**Comment by mwaskom** [comment]
seaborn calls `ax.boxplot` separately for each group internally, so this can't work the way you'd want.

What's the usecase here? It seems out of scope for a boxplot function imo.

**Comment by cristobaltapia** [comment]
@mwaskom my use case is to have the mean value instead of the median. I know there is an extra option to show the mean values, but then they are drawn as a marker. If seaborn calls `ax.boxplot` for each group and the `**kwargs` are passed to it directly, then the `usermedians` parameter would need to be further processed to give the corresponding value to each boxplot call. I would understand, however, if you consider this out of scope.

**Comment by mwaskom** [comment]
If the issue is that you want a horizontal line instead of a marker, then I think you're looking for

```python
sns.boxplot(
    data=tips, x="day", y="total_bill", color="w",
    showmeans=True, meanline=True, meanprops=dict(ls="-"),
)
```
![image](https://user-images.githubusercontent.com/315810/132598504-0233dafe-4e58-41b4-a0f3-368137df5d6a.png)

?

**Comment by cristobaltapia** [comment]
Oh, I wasn't aware of that parameter! Thanks! I think that would work for me.
