### ISSUE TITLE
feature request: ability to add vertical lines in distplot e.g., to mark mean or 95th pctile

### ISSUE THREAD

**Issue by maartenmennes** [mwaskom/seaborn#266]
Hello,

would it be a possibility to add the ability to kde or distplot that would allow adding vertical lines at any point along the distribution. Lines would start at the x-axis and stop when reaching the distribution.

In the attached example I added median (50th percentile) lines to two distributions. Implemented through various calls (not hand-drawn!). Having that implemented with one call would be awesome.

![image](https://cloud.githubusercontent.com/assets/1139180/4088361/56b785aa-2f5c-11e4-890b-0fe7f05df7e9.png)

needed:
- point along distribution where line needs to be drawn, can be any value along x or something calculated from distribution (e.g., percentiles)
- line properties
- potential to fill area under the curve left or right (or both) of line

What do you think?

**Comment by mwaskom** [comment]
Ah, right. So when I looked into this, it was clear that it wouldn't work in `distplot`, which is just a thin wrapper on `kdeplot`, `rugplot`, etc. and doesn't have access to the underlying density. It's possible something like this could work in `kdeplot`, (this is related to #316), which I hope to revisit soon.

**Comment by maartenmennes** [comment]
Great to hear it's still in the works! Here's how I solved it for the figure above.

I have a range of histograms. Then within each histogram I find the point where the hist bin - the value that I want to plot (xav_female) is between 0 and 1. That gives me the x-value to plot at, corresponding to the hist bin that it closest to the value I'm requesting. Then I simply determine the y-value for that corresponding bin. This is not 'exact', but close enough to be 'correct' given the figure.

```
for p in range(len(female_hist_sizes[1])):
        if 0 <= female_hist_sizes[1][p] - xav_female <= 1:
            y_max = female_hist_sizes[0][n][p]/float(ax2_ylim_max)
    myax.axvline(x=x_pos_female, ymin=0, ymax=y_max-0.01, linewidth=3, color = mycolor, linestyle='dotted')
```

**Comment by joelostblom** [comment]
I like this suggestion and I think an option to plot the mean/median as a dot above the histogram together with an errorbar of choice (descriptive/inferential) would be useful. For example, it would be neat for comparing maybe up to three distributions with small differences, where it is clearer to overlay them than to create side by side violins. It saves you one extra plot by comparing averages and distribution shapes in the same figure =)

I made the below as an example by combining seaborn's distplot and matplotlib's errorplot (in the right fig, the distributions are *very* long tailed, hence the seemingly incorrect offset of the means).

![histograms + errorplots](http://snag.gy/BWMia.jpg)

**Comment by joelostblom** [comment]
I just stumbled upon the seaborn 0.6 documentation, and apart from it looking amazing (I have always wanted example plots under each function documentation, and all the new plotting options, wow!), I noticed that we will be able to generate horizontal `pointplots`. This will make the kind of plot I am suggesting much easier to make manually and a special option for that under `distplot` might be unnecessary.

**Comment by jorijnsmit** [comment]
Couple of versions later but no mention of this feature in the docs. What is the current best way to display these lines? Just a mean line would already be great.

**Comment by jorijnsmit** [comment]
That's not a very helpful response @mwaskom.

I managed to get a vertical line at the mean using `matplotlib`'s [`.axvline()`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.axvline.html):
```python
ax = sns.distplot(series)
ax.axvline(series.mean())
plt.show()
```

**Comment by mm909** [comment]
Any work being done on this feature?

**Comment by mm909** [comment]
This answer from JohanC works. https://stackoverflow.com/questions/63307440/how-to-plot-a-mean-line-on-a-distplot-between-0-and-the-y-value-of-the-mean
