### ISSUE TITLE
Seaborn.lineplot() sizes not working

### ISSUE THREAD

**Issue by mkkubins** [mwaskom/seaborn#2660]
Hi! 
I have just experienced something strange when I am trying to pass "sizes"argument to sns.lineplot() nothing changes.

`palette=['k','k','c','c', 'm','m','y','y','b','b']
line=[0.25,2,0.25,2,0.25,2,0.25,2,0.25,2]
pal=[{TREATMENT_NAMES[i]:palette[i]} for i in range(len(TREATMENT_NAMES))]
palette=dict(ChainMap(*pal))
s=[{TREATMENT_NAMES[i]:line[i]} for i in range(len(TREATMENT_NAMES))]
size=dict(ChainMap(*s))
print(size)

sns.lineplot(data=df_total, x="Freq", y="PSD",hue='Treatment_names',palette=palette,sizes=size)
`
With palette everything works correctly. 

![image](https://user-images.githubusercontent.com/71726312/132864081-ee8a4d84-be1e-4bc4-a4e5-8a9d35cc3eab.png)

I woudl like to have something like that but all lines on the plot have the same width.

Do you have any idea where is the problem?

Best

**Comment by mwaskom** [comment]
> sizes : list, dict, or tuple
>> An object that determines how sizes are chosen when size is used. It can always be a list of size values or a dict mapping levels of the size variable to sizes. When size is numeric, it can also be a tuple specifying the minimum and maximum size to use such that other values are normalized within this range.

(from https://seaborn.pydata.org/generated/seaborn.lineplot.html)

You need to tell it what variable to map the sizes with, much like how you have `hue` -> `palette`.
