### ISSUE TITLE
Logistic=True doesn't work/seaborn

### ISSUE THREAD

**Issue by EDQOMASTER** [mwaskom/seaborn#2665]
Hello everybody! I hpe all of you have an excellent tiime.

I need some help, well, I need a lot of help, I'm new in database and I'm trying to make the regression of a dataframe using seaborn.lmplot, but when I try to have the graphic with the logistic regression I only see a constant horizontal line, I hope someone knows how to solve it

https://github.com/EDQOMASTER/-n
In this link you can see the data and a picture of the problem
Please help :c

Psdt: I'm using pycharm

import numpy
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy import stats
import statsmodels as stat
import statsmodels.api as sm
import statsmodels.formula.api as smf

df = pd.read_csv('tesisee.csv')
Comp_Am = pd.read_csv('Compuesto_Aceitemineral.csv')

print(df.describe())

info = df.info()

describe = df.describe()

plt.rcParams['figure.figsize'] = (70, 55)

propiedad_variables =['Cake (x/32 pulgada)', 'Densidad (Lpg)',
                       'HPHT 300°F y 500 psi (ml)', 'Resistencia Gel 10 minutos (Lb/100 ft^2)',
                       'Resistencia Gel 10 segundos (Lb/100 ft^2)']
compuestos_Aceitemineral = ['Emulsificante primario (Lb/bbl)', 'Emulsificante secundario (Lb/bbl)',
                            'Viscosificante primario (Lb/bbl)', 'Viscosificante secundario (Lb/bbl)',
                            'Controlador de filtrado (Lb/bbl)']

for i in propiedad_variables:
    sns.lmplot(x=i, y='Emulsificante primario (Lb/bbl)',
            fit_reg=True, data=Comp_Am,   logistic=True)

**Comment by mwaskom** [comment]
Hi, logistic regression is only possible when your y variable is binary (i.e. is either 0 or 1). That doesn't look like the case in your plot.

**Comment by EDQOMASTER** [comment]
Ooooh auch! is there another way to graph data and find automatically the best regression line?

**Comment by EDQOMASTER** [comment]
> Hi, logistic regression is only possible when your y variable is binary (i.e. is either 0 or 1). That doesn't look like the case in your plot.

Ooooh auch! is there another way to graph data and find automatically the best regression line?

**Comment by mwaskom** [comment]
Why are you putting `logistic=True`? Doesn't it work if you leave that out?

**Comment by EDQOMASTER** [comment]
> Why are you putting `logistic=True`? Doesn't it work if you leave that out?

It only does linear regressions and I have a lot of graphs and I have to look for the best equation to describe that behavior.

I upload another picture (820f1e7e-da40-453f-b574-c1451eb91d) as example without logistic=True in this link= https://github.com/EDQOMASTER/-n

I'm trying to simplify this work because I have to graph approximately 50 plots :_c

**Comment by mwaskom** [comment]
Either way, you can't use logistic regression with the kind of data you have.

I'd recommend reading through the [regression plots tutorial](https://seaborn.pydata.org/tutorial/regression.html). I think this is otherwise outside the scope of the sort of help I can provide in this forum, since there's no issue with seaborn.

**Comment by EDQOMASTER** [comment]
> Either way, you can't use logistic regression with the kind of data you have.
> 
> I'd recommend reading through the [regression plots tutorial](https://seaborn.pydata.org/tutorial/regression.html). I think this is otherwise outside the scope of the sort of help I can provide in this forum, since there's no issue with seaborn.

Thankl you for your help man!
