### ISSUE TITLE
Violinplot causes a TypeError with Pandas new nullable (integer and float) types

### ISSUE THREAD

**Issue by evertrol** [mwaskom/seaborn#2668]
The following code causes a `TypeError`:
```
import pandas as pd
import seaborn as sns
df = pd.DataFrame({'x': ['a', 'a', 'a', 'a', 'a'], 'y': [1, 2, 2, 3, 3]})
df = df.convert_dtypes()
sns.violinplot(x='x', y='y', data=df)
```
with dypes of `string` and `Int64` after conversion (the same error occurs for `Float64`). These are Pandas new (version 1.3) nullable types.

From the traceback, appended below, I suspect it's SciPy's `stats.gaussian_kde` that can't handle the new types.

A simple workaround is 
```
sns.violinplot(x='x', y='y', data=df.astype({'y': int})
```

Since I don't expect SciPy and NumPy to provide or handle a nullable type very soon, I wonder if it's worth providing a workaround in Seaborn itself, before the call to `stats.gaussian_kde`. If so (and it's deemed this is indeed the cause of the error), I'm happy to try and provide a pull request.

I haven't looked for other plot types that fail. Most plots that use some kind of KDE work, such as `histplot` (with kde=True), `jointplot` or even `kdeplot`. Presumably because these rely on counting statistics, not the actual Series input values.

----
Versions:
* Python==3.9.7
* Seaborn==0.11.2
* Pandas==1.3.3
* SciPy==1.7.1
* NumPy==1.20.3
* (Jupyter/-client/-core/==1.0.0/7.0.3/4.81)

(I have also tried with the git master branches for Seaborn and Pandas, with the same result.)

Traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_72631/2655522714.py in <module>
      1 df = df.convert_dtypes()
----> 2 sns.violinplot(x='x', y='y', data=df)
      3 #sns.violinplot(x='x', y='y', data=df.astype({'y': int}))
      4 df.dtypes

~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/seaborn/_decorators.py in inner_f(*args, **kwargs)
     44             )
     45         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 46         return f(**kwargs)
     47     return inner_f
     48 

~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/seaborn/categorical.py in violinplot(x, y, hue, data, order, hue_order, bw, cut, scale, scale_hue, gridsize, width, inner, split, dodge, orient, linewidth, color, palette, saturation, ax, **kwargs)
   2398 ):
   2399 
-> 2400     plotter = _ViolinPlotter(x, y, hue, data, order, hue_order,
   2401                              bw, cut, scale, scale_hue, gridsize,
   2402                              width, inner, split, dodge, orient, linewidth,

~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/seaborn/categorical.py in __init__(self, x, y, hue, data, order, hue_order, bw, cut, scale, scale_hue, gridsize, width, inner, split, dodge, orient, linewidth, color, palette, saturation)
    522         self.establish_variables(x, y, hue, data, orient, order, hue_order)
    523         self.establish_colors(color, palette, saturation)
--> 524         self.estimate_densities(bw, cut, scale, scale_hue, gridsize)
    525 
    526         self.gridsize = gridsize

~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/seaborn/categorical.py in estimate_densities(self, bw, cut, scale, scale_hue, gridsize)
    588 
    589                 # Fit the KDE and get the used bandwidth size
--> 590                 kde, bw_used = self.fit_kde(kde_data, bw)
    591 
    592                 # Determine the support grid and get the density over it

~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/seaborn/categorical.py in fit_kde(self, x, bw)
    673     def fit_kde(self, x, bw):
    674         """Estimate a KDE for a vector of data with flexible bandwidth."""
--> 675         kde = stats.gaussian_kde(x, bw)
    676 
    677         # Extract the numeric bandwidth from the KDE object

~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/scipy/stats/kde.py in __init__(self, dataset, bw_method, weights)
    204             self._neff = 1/sum(self._weights**2)
    205 
--> 206         self.set_bandwidth(bw_method=bw_method)
    207 
    208     def evaluate(self, points):

~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/scipy/stats/kde.py in set_bandwidth(self, bw_method)
    552             raise ValueError(msg)
    553 
--> 554         self._compute_covariance()
    555 
    556     def _compute_covariance(self):

~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/scipy/stats/kde.py in _compute_covariance(self)
    561         # Cache covariance and inverse covariance of the data
    562         if not hasattr(self, '_data_inv_cov'):
--> 563             self._data_covariance = atleast_2d(cov(self.dataset, rowvar=1,
    564                                                bias=False,
    565                                                aweights=self.weights))

<__array_function__ internals> in cov(*args, **kwargs)

~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/numpy/lib/function_base.py in cov(m, y, rowvar, bias, ddof, fweights, aweights, dtype)
   2467             w *= aweights
   2468 
-> 2469     avg, w_sum = average(X, axis=1, weights=w, returned=True)
   2470     w_sum = w_sum[0]
   2471 

<__array_function__ internals> in average(*args, **kwargs)

~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/numpy/lib/function_base.py in average(a, axis, weights, returned)
    405             wgt = wgt.swapaxes(-1, axis)
    406 
--> 407         scl = wgt.sum(axis=axis, dtype=result_dtype)
    408         if np.any(scl == 0.0):
    409             raise ZeroDivisionError(

~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/numpy/core/_methods.py in _sum(a, axis, dtype, out, keepdims, initial, where)
     45 def _sum(a, axis=None, dtype=None, out=None, keepdims=False,
     46          initial=_NoValue, where=True):
---> 47     return umr_sum(a, axis, dtype, out, keepdims, initial, where)
     48 
     49 def _prod(a, axis=None, dtype=None, out=None, keepdims=False,

TypeError: No loop matching the specified signature and casting was found for ufunc add

**Comment by mwaskom** [comment]
See https://github.com/mwaskom/seaborn/issues/2429. This isn't something that should be made as an ad hoc change for the KDE computation in violinplot. But the core code that is shared by newer modules does convert pandas nullable types to floats before handing off to numpy/scipy (e.g. you'll see that `sns.kdeplot(data=df, y="y")` works with your test df.

**Comment by evertrol** [comment]
Great, thanks.
I'm happy to live with the work-around while waiting for a proper refactoring.
I guess this issue can serve as a pointer for people that run into the same error in the meantime.
