### ISSUE TITLE
Remove legend title from histplot

### ISSUE THREAD

**Issue by RMeli** [mwaskom/seaborn#2669]
Apologise if I'm missing something very obvious here, but when I try to remove the legend title from a `histplot`, nothing I tried seems to work as expected. Using `ax.legend().set_title("")` (and similar) to try to remove the legend results in `No handles with labels found to put in legend.` and the whole legend disappearing from the plot. I only managed to use `ax.legend().set_title("")` by switching to `countplot`.

What is the correct/recommended way for removing a title from the legend on `histplots` (if any)?

---

MWE:
* `f0.png` has a legend with title `sex`
* `f5.png` is what I wanted to achieve in the first place with `histplot`

```python
import seaborn as sns
from matplotlib import pyplot as plt

tips = sns.load_dataset("tips")

# Legend shows with title "sex"
_ = sns.histplot(data=tips, x="day", hue="sex", multiple="dodge", shrink=.8)
plt.savefig("f0.png")

# How to remove the legend title?
# The following print out "No handles with labels found to put in legend."

ax = sns.histplot(data=tips, x="day", hue="sex", multiple="dodge", shrink=.8)
ax.legend().set_title("")
plt.savefig("f1.png")

ax = sns.histplot(data=tips, x="day", hue="sex", multiple="dodge", shrink=.8)
ax.legend(title="")
plt.savefig("f2.png")

ax = sns.histplot(data=tips, x="day", hue="sex", multiple="dodge", shrink=.8)
plt.gca().legend().set_title("")
plt.savefig("f3.png")

_, ax = plt.subplots()
sns.histplot(data=tips, x="day", hue="sex", multiple="dodge", shrink=.8, ax=ax)
ax.legend().set_title("")
plt.savefig("f4.png")

# This works as expected
ax = sns.countplot(data=tips, x="day", hue="sex")
ax.legend().set_title("")
plt.savefig("f5.png")
```

**Comment by mwaskom** [comment]
`ax.legend()` removes the existing legend and creates a new one. You want `ax.get_legend()`, which gives you a reference to the existing legend object. Then this works:

```python
ax = sns.histplot(data=tips, x="day", hue="sex", multiple="dodge", shrink=.8)
ax.get_legend().set_title("")
```

BTW these sort of "how do I do X" questions are best suited for stackoverflow, where they can serve as a reference for others.

**Comment by RMeli** [comment]
Thanks! Will post on StackOverflow next time, but in this case I thought there might be some kind of issue given the different behaviour experienced with `histplot` and `catplot` (where `ax.legend().set_title("")` seems to work).
