### ISSUE TITLE
Feature request: boxplot option in pairplot "diag_kind"

### ISSUE THREAD

**Issue by tmerrittsmith** [mwaskom/seaborn#2670]
I would like to use a boxplot for "diag_kind" rather than a histogram or kde - particularly when comparing two variables using hue.

**Comment by mwaskom** [comment]
Hi, you can use boxplots on the diagonal if you use `PairGrid` directly:

```python
g = sns.PairGrid(tips, hue="sex")
g.map_offdiag(sns.scatterplot)
g.map_diag(sns.boxplot
```

boxplot does not directly support hue without a grouping variable (#2429) so it's not as straightforward, but you can get a pretty workable plot with a small hack:

```python
g = sns.PairGrid(tips, hue="sex")
g.map_offdiag(sns.scatterplot)
g.map_diag(sns.boxplot, y=tips["sex"], dodge=False)
g.add_legend()
```

![image](https://user-images.githubusercontent.com/315810/134894475-625f2e50-c8f2-47e8-b668-3fd79908647d.png)

Once #2429 goes in the question of adding a `diag_kind="box"` to `pairplot` may get revisited.
