### ISSUE TITLE
Frequently asked questions (FAQs)

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#2672]
The purpose of this issue is to highlight the [FAQ page](https://github.com/mwaskom/seaborn/wiki/Frequently-Asked-Questions-(FAQs)) I am currently building.

I expect this will ultimately be moved into the documentation at some point, but having it in a wiki allows for more pre-release visibility and faster iteration.

If you check this page before opening a new issue, you may find a quick answer to your question. And please feel free to make suggestions about content that would be good to cover, or answers that you find confusing / insufficient.

**Comment by IsNotMyIP** [comment]
Adding an index at the top could be helpful for people to navigate through it.

**Comment by mwaskom** [comment]
thanks @IsNotMyIP. on my view, I see a table of contents off to the right:

![image](https://user-images.githubusercontent.com/315810/144106285-6d97e629-dec5-48dd-92ae-b8d1c42917e8.png)

does it appear differently for you?

**Comment by IsNotMyIP** [comment]
You are right! I checked it from my mobile and it didn't show up. It's well done enough to surf through the FAQs

**Comment by mwaskom** [comment]
Closing as this has now been moved to the main docs: https://seaborn.pydata.org/faq
