### ISSUE TITLE
violinplot not separating into groups when there's only one metric to plot, despite 'hue' being specified

### ISSUE THREAD

**Issue by smeisler** [mwaskom/seaborn#2676]
Hello,

I am trying to make a violin plot of one metric displayed between two groups, where all relevant variables are column names in a single data frame.

I know the hue I specified works because it separates into groups when running `regplot`. However, the `violinplot` only returns a single colored symmetric plot, suggesting group was not taken into account, even though the same hue was specified. See the picture below:

![image](https://user-images.githubusercontent.com/27028726/136496193-e0b62d48-7997-4234-8438-d54601211be6.png)

The last thing I need to do for this figure is to fix the violinplot to represent group metrics. Can you think of anyway that I can do this?

Thanks,
Steven

**Comment by mwaskom** [comment]
`violinplot` cannot be split with `hue` when you only specify one of `x` or `y`; this is a known limitation and you'll definitely find other issues if you search. Without seeing any code, I can't suggest the easiest workaround but there are some that I'm certain you'll find on stackoverflow.
