### ISSUE TITLE
Process finished with exit code -107374181

### ISSUE THREAD

**Issue by FancyBrush** [mwaskom/seaborn#2687]
OS: windows 10
IDE: pycharm 2019.2

I came across "Process finished with exit code -107374181", when I tried example:
`import seaborn as sns
from scipy.io import loadmat
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")
ax = sns.violinplot(x='day',y='total_bill',data=tips)`

Did I make a mistake?

**Comment by mwaskom** [comment]
Hi, very hard to say without more information. Was `"Process finished with exit code -107374181"` the only output you saw?

My guess would be that one of the libraries you're trying to import [is not properly installed](https://github.com/mwaskom/seaborn/wiki/Frequently-Asked-Questions-(FAQs)#i-cant-import-seaborn-even-though-its-definitely-installed). I would suggest trying to figure out exactly which import is failing (do them one by one, and bear in mind that some of the libraries import each other). If you're able to import everything, try and see if you can make a plot just using matplotlib, and if not maybe try using a different [matplotlib backend](https://matplotlib.org/stable/tutorials/introductory/usage.html#backends).

I'm afraid I can't provide much more advice on personal setups than that. I'm going to close this issue for now, but please follow up if you determine that there is a specific issue in seaborn.
