### ISSUE TITLE
compatibility with Matplotlib-3.5.0 ?

### ISSUE THREAD

**Issue by stonebig** [mwaskom/seaborn#2689]
Matplotlib -3.5.0 will remove a deprecated keyword used per seaborn on savefig: Orientation, ...

![image](https://user-images.githubusercontent.com/4312421/139594577-ebfc7882-17eb-4791-a392-26957ab57ca6.png)

**Comment by mwaskom** [comment]
Calling `sns.pairplot` does not save a figure by default. But the IPython "inline" backend does call `savefig`, I think, so you'd need to report this to them.

**Comment by mwaskom** [comment]
(For things like this please check whether you can reproduce the error with a simple matplotlib plot before reporting to seaborn).

**Comment by stonebig** [comment]
ok, sorry.  I didn't  imagine %inline was doing something.
