### ISSUE TITLE
pointplot() raises ValueError: Invalid RGBA argument when order is length 3

### ISSUE THREAD

**Issue by alexpiet** [mwaskom/seaborn#2692]
I am trying to use point plot and color each x value a different color. In doing so, when the number of x values is 3, and only 3, I get a value error. Otherwise, it works fine:

```
import pandas as pd
import seaborn as sns
df=pd.DataFrame()
df['category'] = ['a','b','c']
df['y']=[1,2,3]
sns.pointplot(
   data = df,
   x='category',
   y='y',
   hue='category',
   hue_order=['a','b','c'],
   order=['a','b','c'],
   )
```
ValueError: Invalid RGBA argument: 0.12156862745098039

However, both of the following work as expected:
```
sns.pointplot(
   data = df,
   x='category',
   y='y',
   hue='category',
   hue_order=['a','b','c'],
   order=['a','b','c','dummy'],
   )
```
or 

```
sns.pointplot(
   data = df,
   x='category',
   y='y',
   hue='category',
   hue_order=['a','b','c'],
   order=['a','b'],
   )
```

As a work around I have been using `order=['a','b','c',dummy']` and then clipping the xaxis to avoid the empty whitespace. 

matplotlib: 3.3.3
seaborn: 0.11.2

**Comment by mwaskom** [comment]
Hey Alex! I think you've hit https://github.com/mwaskom/seaborn/issues/2373, which is a bug in matplotlib 3.3.3. 
Upgrading should fix it.

**Comment by alexpiet** [comment]
Ah, thanks.
