### ISSUE TITLE
Bug: FacetGrid.set_titles() does not work if FacetGrid.map() is called afterwards

### ISSUE THREAD

**Issue by Denbergvanthijs** [mwaskom/seaborn#2702]
First of all, thank you for this amazing library!

When the following code is executed, the titles of the subplots do not change. I did expect the titles to change however.

```python
import matplotlib.pylab as plt
import seaborn as sns
import pandas as pd
import numpy as np

data = pd.DataFrame(np.arange(0, 20).reshape(10, 2), columns=["X", "Y"])
data["split"] = ["left", "right"] * 5

facet_grid = sns.relplot(data=data, x="X", y="Y", col="split")

facet_grid.set_titles("This text from facet_grid.set_titles should be visible")
facet_grid.map(plt.text, x=5, y=5, s="Text from facet_grid.map")

plt.show()
```
![bug1](https://user-images.githubusercontent.com/43202049/143426505-3e71fa94-4bc5-46d3-968f-b15b80dad32d.png)

When changing the order of calls to `facet_grid.set_titles()` and `facet_grid.map()`, the titles of the subplots do change:

```python
import matplotlib.pylab as plt
import seaborn as sns
import pandas as pd
import numpy as np

data = pd.DataFrame(np.arange(0, 20).reshape(10, 2), columns=["X", "Y"])
data["split"] = ["left", "right"] * 5

facet_grid = sns.relplot(data=data, x="X", y="Y", col="split")

facet_grid.map(plt.text, x=5, y=5, s="Text from facet_grid.map")
facet_grid.set_titles("This text from facet_grid.set_titles should be visible")

plt.show()
```
![bug2](https://user-images.githubusercontent.com/43202049/143426550-88fc0de1-0253-4a65-83fa-ea64950e332d.png)

The same behavior happens when using other calls to map like: `facet_grid.map(plt.axhline, y=5)`.

------

I've scrolled to all other open issues mentioning FacetGrid but did not came across the same bug as presented above. I am using 
matplotlib 3.5.0 with seaborn 0.11.2 on Python 3.9.9.

**Comment by mwaskom** [comment]
Hi, this is expected behavior (relevant code here https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L708).

Is there a reason in your application that you need to call `set_titles` before `map`?

**Comment by mwaskom** [comment]
Thinking more about this, I'm not sure there's a reason the titles need to be updated in `.map` rather than have the defaults set in the constructor. It would be a change in behavior ... but probably an innocuous one? This code is very old so there may have been a reason at some point ... but also maybe not.

**Comment by Denbergvanthijs** [comment]
> Is there a reason in your application that you need to call set_titles before map?

No not really, I was just a bit surprised that the order of those two lines matters.

> I'm not sure there's a reason the titles need to be updated in .map rather than have the defaults set in the constructor.

I can't think of any reason either, maybe _finalize_grid() is needed to update the axis labels and titles if other arguments are provided to .map() like: `facet_grid.map(sns.scatterplot, "total_bill", "tip")`

**Comment by mwaskom** [comment]
> No not really, I was just a bit surprised that the order of those two lines matters.

`FacetGrid` is not declarative (like ggplot) — when you call a method, it changes the underlying figure.

> maybe _finalize_grid() is needed to update the axis labels and titles 

Axis labels — yes. Those are sourced from the `map` call. But the default title information should be known at time of class instantiation.

**Comment by Denbergvanthijs** [comment]
> But the default title information should be known at time of class instantiation.

Yes, I definitely agree with you!

Moving the following line to the end of the constructor of FacetGrid seems to be working on my plots.

https://github.com/mwaskom/seaborn/blob/d4aa367015e9ec2b27260e05676341af8da1728f/seaborn/axisgrid.py#L809

But just as you said earlier, I'm also very much interested what the reason behind this was.

**Comment by mwaskom** [comment]
I think you'd want to call it before `.tight_layout`?

**Comment by Denbergvanthijs** [comment]
Yeah definitely, my bad
