### ISSUE TITLE
Stripplot does not allow the usage of hue

### ISSUE THREAD

**Issue by nfoecking** [mwaskom/seaborn#2707]
Hello,

I am interested in coloring different elements in a stripplot. The following code snippet (taken from https://seaborn.pydata.org/generated/seaborn.stripplot.html) works fine:
```python
import seaborn as sns
tips = sns.load_dataset("tips")
sns.stripplot(x="sex", y="total_bill", hue="day", data=tips)
```

However, I am only interested in plotting one dimensional data. Therefore, I try to use the following lines of code:
```python
tips = sns.load_dataset("tips")
sns.stripplot(x="total_bill", hue="day", data=tips)
```
However, the `hue`-parameter seems to be ignored in this case resulting in a plot where each element has the same color. Is this a known bug or have I any mistake in my code?

Best,
Niklas

**Comment by mwaskom** [comment]
Hi, this is a well known limitation; you can find several issues about it if you search.

**Comment by diego898** [comment]
I just ran into this issue right now as well. It might be worth explaining this in the documentation
