### ISSUE TITLE
Distplot don't work with fig.set_title()

### ISSUE THREAD

**Issue by xpcosmos** [mwaskom/seaborn#2708]
I'm using <code>ax.set_titles()</code> to change my figure title but it's not working!
<br>

## My code:

<pre>ax = sns.displot(df, x='log_valor')
ax.figure.set_size_inches(15, 7)
ax.set_xlabels('Valores', fontsize=15)
ax.set_titles('Distribuição')
plt.show()</pre>

### My plot:

![2ac4ec09-f4ca-449a-a8ea-3ee5a6fb7795](https://user-images.githubusercontent.com/85235525/144690759-d584f2ba-4ef2-40b6-854b-dea34514b4e3.png)

**Comment by mwaskom** [comment]
Hi, please ask "how do I do x" questions on StackOverflow. Thanks!
