### ISSUE TITLE
Same data but different plots

### ISSUE THREAD

**Issue by zyh3826** [mwaskom/seaborn#2711]
I have some vectors in a directory, I use a 'for' to iterate them and plot scatter figures and save them, code like this:
`
def main(data_path: str, save_root: str):

    print('Current pid: {}'.format(os.getpid()))
    files = glob.glob(data_path)
    for file in files[:100]:
        fig_name = file.split('/')[-1].split('.')[0] + '.png'
        save_path = os.path.join(save_root, fig_name)
        plot_tsne(file, save_path=save_path)
def plot_tsne(data_path: str, save_path: str, label_path: str = None):

    vector = np.load(data_path)
    if label_path:
        labels = np.load(label_path)
        palette = sns.color_palette('bright', len(set(labels)))
    else:
        labels = None
        palette = sns.color_palette('bright', 1)
    sns.set(rc={'figure.figsize': (20, 20)})
    fig = sns.scatterplot(x=vector[:, 0], y=vector[:, 1], legend='full', palette=palette, hue=labels)
    scatter_fig = fig.get_figure()
    scatter_fig.savefig(save_path)
`
when the program finished, I check one of  the figure like this:
![微信图片_20211213104728](https://user-images.githubusercontent.com/31238754/145745918-dc953d69-0abc-4060-ac3b-f5afb454c208.png)

But when I select the same vector and plot it alone, it looks like this：
![微信图片_20211213104733](https://user-images.githubusercontent.com/31238754/145745926-fd9439d3-f974-4a6e-9ea1-acec5e86708f.png)

I'm so confuse what happened and why this happened, anyone can help me? Thank you

**Comment by mwaskom** [comment]
Hi, I'd encourage you to turn this into a fully reproducible example and ask on StackOverflow if you're still stuck. I'm guessing this is not a problem in seaborn, but we can reopen if it turns out to be.
