### ISSUE TITLE
Unnecessary y-label in relplot

### ISSUE THREAD

**Issue by MarcoGorelli** [mwaskom/seaborn#2712]
In this example from the docs:
```python
flights_wide = sns.load_dataset("flights").pivot("year", "month", "passengers")
sns.relplot(data=flights_wide, kind="line")
```

the plot shows

![image](https://user-images.githubusercontent.com/33491632/145822634-4d38a987-6034-41be-9e84-f12ac313b73c.png)

The y-label shows `_y`, even though that's not part of the dataset.

IMO here it'd be clearer if there was no ylabel at all here.

Would a PR be welcome to remove the y-label in this case?

**Comment by mwaskom** [comment]
Yes, this is an internal column name bubbling up when it shouldn’t. Not sure how simple the fix will be, but feel free to look into it.

**Comment by MarcoGorelli** [comment]
Sure, I'll look into it

Related, `May` appears as the y-label in this example:

![image](https://user-images.githubusercontent.com/33491632/146067002-7cdcfa86-b0a8-4d6b-90e3-89f59f02ff4f.png)

**Comment by mwaskom** [comment]
That is intentional.

**Comment by jhncls** [comment]
@MarcoGorelli With which seaborn version did you test this?

**Comment by MarcoGorelli** [comment]
> That is intentional.

ah, sorry for the false report then

> @MarcoGorelli With which seaborn version did you test this?

'0.11.2'
