### ISSUE TITLE
Customization of fliers in boxenplot (letter-value plot)

### ISSUE THREAD

**Issue by mlldantas** [mwaskom/seaborn#2713]
Hi there!

I was trying to tweak the fliers (outliers) of a letter-value plot I am generating with seaborn (e.g. using properties of matplotlib for the traditional boxplot -- for instance: https://matplotlib.org/2.0.2/examples/statistics/boxplot_demo.html), but without success.

I have a huge plot with several boxenplots side-by-side and I wanted to change the face color of my outliers so they match the body of the boxenplot. Since they are pretty tucked together, sometimes it's hard to differentiate which outliers belong to which distribution.

Please, let me know if there is an obvious solution for this that I am not catching.

Thanks so much!

**Comment by mwaskom** [comment]
This came up recently (https://github.com/mwaskom/seaborn/issues/2701). There are a few suggestions for workaround suggestions there. I'm also in favor of expanding api to allow control over this. Going to close here as duplicate, but feel free to check in on the other issue and see if you'd like to work on that as a contribution.
