### ISSUE TITLE
Clarifying the logic of kdeplot levels (vector arg)

### ISSUE THREAD

**Issue by mandeldm** [mwaskom/seaborn#2715]
The description of `levels` argument of `kdeplot` reads, in part:
> Levels correspond to iso-proportions of the density: e.g., 20% of the probability mass will lie below the contour drawn for 0.2.

I'd like to make sure I understand this correctly. Which of the following 2 interpretations is right?

**Interpretation 1**
This means that 20% of the probability mass will lie **at density levels** that are below **those at** the contour drawn for 0.2.  
Another way of saying this: 20% of the probability mass will lie **outside of** the contour drawn for 0.2.

**Interpretation 2**
This means that if we draw a 2D horizontal plane through the contour, slicing off and removing the "mountaintop", the probability mass remaining below this plane is 20% of the probability mass. (The remaining 80% will be in the "mountaintop".)
Unlike the first interpretation, this literal reading of the word "_below_" includes in the 20% the volume of the probability "cylinder" whose base is the contour and whose height is the probability density at the contour.

Feels like Interpretation 1 must be correct, but the detailed reading of the arg's description made me question that. I would appreciate your guidance.

**Comment by mwaskom** [comment]
Interpretation (1) is correct. I see how the language could be ambiguous, but I don't think there's a mathematical/statistical meaning to the operation you propose in interpretation (2)?

**Comment by mandeldm** [comment]
Thank you.
I also found it hard to come up with an intuition to support interpretation 2, but I didn't want to dismiss the possibility outright.
