### ISSUE TITLE
Organize multiple FacetGrid into 1 figure

### ISSUE THREAD

**Issue by Vincent-wq** [mwaskom/seaborn#2719]
Dear developers,
Thanks for this nice visualziation tool, the designs are really fantastic!
I have been trying to put 2 or more facetGrid (different types of data and visualization, not easy to put them in one FacetGrid) into one, but still not successful, do you have any suggestions? Not sure whether subfigure will help, I believe this functionality will be very useful for automatize/standardize the figures generation for scientific publications.
The second thing I have found is that: parsing one opeartion to 1 of the facetGrid axes will result in the changes to all the axes in the facetGrid. I just want to confirm with you in case I am missing any important functions to customize FacetGrid for more unsymmetric designs.
Happy new year!
Cheers,
Vincent (Qing Wang)

**Comment by mwaskom** [comment]
Hi, to the first question, you are correct that it's not currently possible to put two facet grids into one figure. There is a popular hack on StackOverflow that should be easy to find (iirc it may be about jointplot, but same principle).

I'm not sure I can understand the second question with a reproducible code example.
