### ISSUE TITLE
Seaborn histplot with one element gives "`bins` must be positive" error

### ISSUE THREAD

**Issue by AnavSood** [mwaskom/seaborn#2721]
For certain values of x and y > 0, if I run ```sns.histplot([x], binwidth=y)``` I get ```ValueError: `bins` must be positive, when an integer```.  For example, run ```sns.histplot([0.49928], binwidth=0.03)```. 

See here for discussion: https://stackoverflow.com/questions/70553730/seaborn-histplot-with-one-element-gives-bins-must-be-positive-error

**Comment by mwaskom** [comment]
Hi, your link doesn't go anywhere. Please provide a reproducible example in the issue, thanks.

**Comment by AnavSood** [comment]
> Hi, your link doesn't go anywhere. Please provide a reproducible example in the issue, thanks.

Apologies! Updated on both accounts.

**Comment by Vandinimodi1595** [comment]
Hey @AnavSood, I am new to github and would like to make a contribution to this issue.

**Comment by sajozsattila** [comment]
I have the same problem. Example code:

```
sns.histplot([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                     stat="probability", binwidth=0.05)
```

**Comment by cmayer** [comment]
#2785 and #2721 have in common that data point(s) are not counted even though they are there.
In the one case this produces an error message, in the other case an output that omits points.
