### ISSUE TITLE
partially initialized module 'seaborn' has no attribute 'set_style' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Mrpool720** [mwaskom/seaborn#2723]
import seaborn as sns
sns.set_theme("ticks")
tips = sns.load_dataset("tips")
sns.relplot(
    data=tips,
    x="total_bill", y="tip", col="time",
    hue="smoker", style="smoker", size="size",
)

AttributeError                            Traceback (most recent call last)
<ipython-input-14-97ec293c7419> in <module>
----> 1 import seaborn as sns
      2 sns.set_theme("ticks")
      3 tips = sns.load_dataset("tips")
      4 sns.relplot(
      5     data=tips,

~/Desktop/MLProjects/seaborn.py in <module>
      9 import matplotlib.pyplot as plt
     10 
---> 11 sns.set_style("ticks")
     12 
     13 diamonds = sns.load_dataset("diamonds")

AttributeError: partially initialized module 'seaborn' has no attribute 'set_style' (most likely due to a circular import)

![Screen Shot 2022-01-04 at 4 28 57 PM](https://user-images.githubusercontent.com/72791295/148049471-4281d66d-7085-45bd-b0d0-3b8c4f30d6a9.png)

**Comment by MarcoGorelli** [comment]
looks like you have a file called `seaborn.py` - can you try renaming it?

**Comment by Mrpool720** [comment]
> looks like you have a file called `seaborn.py` - can you try renaming it?

thanks it worked...

**Comment by mwaskom** [comment]
Yes this is a Python gotcha, don’t name local files after modules you plan to (or will indirectly) import.
