### ISSUE TITLE
Stacked barplot with specified hue issue

### ISSUE THREAD

**Issue by Tomer9w** [mwaskom/seaborn#2725]
Hi
Trying to figure out how to create stacked barplot with seaborn on a netflix data I have.
years (x-axis), count (y-axis) and color by type (hue).
I want to show the sum on the y-axis, stacked, so I used the estimator=np.sum argument.

The issue is that I couldn't make a stacked barplot with 'hue' variable and counts on y-axis.

For example, If I choose "dodge = False" - the data is correctly represented in y-axis (first figure attached)
If I choose "dodge = True", because I want it to be stacked bar plot, then the values changed and the graph no longer makes sense (second figure attached) - value for 2017 bar is 65 which is not correct.

![image](https://user-images.githubusercontent.com/76811813/149740636-e2bc6c46-9e7a-4919-9c03-dab5970d6a85.png)
![image](https://user-images.githubusercontent.com/76811813/149740676-3ec31fb8-41a2-4734-9ccb-bbfa8d3828bd.png)

data frame below:
{'type': {1940: 'G',
  1976: 'G',
  1978: 'PG',
  1982: 'PG',
  1986: 'G',
  1987: 'PG',
  1989: 'PG',
  1990: 'TV-Y7',
  1991: 'G',
  1992: 'G',
  1993: 'PG',
  1994: 'PG',
  1995: 'G',
  1996: 'TV-Y7-FV',
  1997: 'TV-Y7-FV',
  1998: 'TV-Y7',
  1999: 'PG-13',
  2000: 'G',
  2001: 'PG',
  2002: 'TV-Y',
  2003: 'G',
  2004: 'R',
  2005: 'PG',
  2006: 'TV-G',
  2007: 'TV-G',
  2008: 'TV-Y7-FV',
  2009: 'G',
  2010: 'TV-Y7-FV',
  2011: 'R',
  2012: 'R',
  2013: 'NR',
  2014: 'TV-14',
  2015: 'TV-G',
  2016: 'TV-14',
  2017: 'TV-Y7-FV'},
 'title': {1940: 3,
  1976: 4,
  1978: 2,
  1982: 3,
  1986: 4,
  1987: 2,
  1989: 1,
  1990: 4,
  1991: 5,
  1992: 2,
  1993: 7,
  1994: 6,
  1995: 5,
  1996: 1,
  1997: 2,
  1998: 2,
  1999: 1,
  2000: 11,
  2001: 3,
  2002: 2,
  2003: 5,
  2004: 1,
  2005: 3,
  2006: 1,
  2007: 2,
  2008: 1,
  2009: 2,
  2010: 2,
  2011: 1,
  2012: 1,
  2013: 2,
  2014: 10,
  2015: 7,
  2016: 111,
  2017: 12}}

code below:
`CountTypesPerYear = Netflix_data.groupby(['release year', 'type']).count().reset_index()
CountTypesPerYear = CountTypesPerYear.set_index('release year')
CountTypesPerYear = CountTypesPerYear.drop(columns=['ratingLevel', 'ratingDescription', 'user rating score', 'user rating size'])
CountTypesPerYear = CountTypesPerYear.sort_index(level=['release year','type'])

plt.figure(figsize=(5,3))
sns.barplot(data = CountTypesPerYear,x = CountTypesPerYear.index, y = 'title', hue = 'type', order = range(2016,2018), dodge= True, ci = None, estimator=np.sum)
plot4.set_xticklabels(plot4.get_xticklabels(), rotation=300)`

**Comment by mwaskom** [comment]
Hi, `barplot` does not support stacking (but `histplot` does).
