### ISSUE TITLE
Use alternate clustering for Seaborn Clustermap

### ISSUE THREAD

**Issue by andhamel** [mwaskom/seaborn#2730]
I am trying to make a heatmap using seaborn.clustermap.

In the documentation, it uses scipy.cluster.hierarchy.linkage.

Instead, if I wanted to use agglomerative clustering from sklearn.cluster.AgglomerativeClustering (https://scikit-learn.org/stable/modules/generated/sklearn.cluster.AgglomerativeClustering.html), is that possible?

Or would I just take my matrix and pre-compute the distances and then add the dendrograms to heatmap like in this post?

https://stackoverflow.com/questions/38705359/how-to-give-sns-clustermap-a-precomputed-distance-matrix

Thanks in advance!

**Comment by mwaskom** [comment]
You can pass a pre-computed linkage matrix into the function so if you can get scikit-learn to give you that in the format scipy expects, then I guess it would work. But scipy clustering is agglomerative so I'm not sure the results should be too different?

**Comment by andhamel** [comment]
Oh, I see. I thought it was different than agglomerative. Thanks!
