### ISSUE TITLE
displot unnecessarily slow compared to calling FacetGrid.map with histplot(np.array(...))

### ISSUE THREAD

**Issue by BlackHC** [mwaskom/seaborn#2733]
Setup:
```
samples = 1

df = pd.DataFrame()

for batch_size in range(31):
  samples = samples/(1+scipy.stats.expon.rvs(loc=0, scale=1/1000, size=10000))
  df = df.append(dict(batch_size=batch_size, samples=samples), ignore_index=True)

exploded_df = df.explode("samples")
```

The following:
```
sns.displot(data=exploded_df[exploded_df.batch_size % 10 == 0], col="batch_size", x="samples", kind="hist")
```
takes forever (aborted after a minute or so), while
```
g = sns.FacetGrid(data=exploded_df[exploded_df.batch_size % 10 == 0], col="batch_size", sharey=False)

def plot_histplot(metric, color, data):
  sns.histplot(x=np.array(data[metric]), color=color)

g.map_dataframe(plot_histplot, "samples")
```
works right away. (g.map_dataframe(sns.histplot, "samples") also takes ages, so it might be the call to np.array that speeds things up?)

The first version seems to spend most of its time in:
```
comp_data()->__setitem__()->_get_setitem_indexer()->_convert_to_indexer()->_get_listlike_indexer()->_reindex_non_unique()->get_indexer_non_unique()->resize()
```

---

Confounder:

If I recreate explode_df using dummy data:
```
exploded_df = pd.DataFrame(dict(batch_size=np.random.choice(31, 10000*31), samples=np.random.normal(size=10000*31)))
```
both are fast. So it might seem there is something about the DataFrame that makes it slow?

---

seaborn                       0.11.2
pandas                        1.1.5
pandas-datareader             0.9.0
pandas-gbq                    0.13.3
pandas-profiling              1.4.1
sklearn-pandas                1.8.0

---

Thanks,
 Andreas

**Comment by BlackHC** [comment]
Thank you, you're right!

Apologies for the duplicate. I did a quick search but didn't find anything
and got a big deadline coming up so couldn't debug/look further.

Best wishes,
Andreas

**Comment by mwaskom** [comment]
Cool, the simple workaround is to reset your index before giving the data to seaborn.
