### ISSUE TITLE
Displot and FacetGrid behaves differently when stat is 'percent'

### ISSUE THREAD

**Issue by oacar** [mwaskom/seaborn#2735]
Hi, I was trying to plot histograms using displot with y axis being percent and facet variable and noticed something strange. When using displot, the percentages are calculated by division of the number of all data points in the dataframe, whereas FacetGrid mapped to histplot calculates percentages with respect to number of data in the corresponding facetting variable. I am not sure if this was expected and didn't see anything in the documentation. My expectation would be the latter. 

Here is a toy example:
```python
import numpy as np
import pandas as pd
import seaborn as sns
# random data
np.random.seed(1001)
value_col = np.random.randint(100, size=200)
facet_col = np.repeat(['cat1','cat2'],100)
df = pd.DataFrame({'value':value_col, 'facet_col':facet_col})

#use displot 
sns.displot(data=df,
            x='value',
            row='facet_col', stat='percent', binwidth=50)

#use FacetGrid 
g = sns.FacetGrid(df,row='facet_col')
g.map_dataframe(sns.histplot, x="value",  stat='percent', binwidth=50)
```

displot output has bar heights around 25% which means percentages were calculated by division of n=200, while FacetGrid output shows it around 50% which means percentages were calculated with n=100. 

![displot_example](https://user-images.githubusercontent.com/13300870/151467523-ac1e1f4b-d738-4549-8f65-e9164a305b25.png)

![facetgrid_example](https://user-images.githubusercontent.com/13300870/151467517-9082fdd3-0054-4e24-a3ef-14a949bfebd0.png)

matplotlib version : '3.5.1'
seaborn version: '0.11.2'

**Comment by mwaskom** [comment]
This is not unexpected. When using `FacetGrid` directly, each facet sees only a slice of the dataset.

**Comment by oacar** [comment]
While I see that's the reason, I don't understand why `displot` behaves differently.
`distplot` was documented as `Figure-level interface for drawing distribution plots onto a FacetGrid.` So I'd expect they plot same thing.

**Comment by mwaskom** [comment]
That documentation is correct. `displot` uses a `FacetGrid` to set up the figure and hence is a figure-level function (can’t be directed onto existing axes), but it does not use `FacetGrid.map` internally because the fact that each facet sees only a slice of the data makes it very cumbersome to do useful things like use the same bins across facets or normalize with respect to the entire dataset, which is the distinction you are seeing.

**Comment by oacar** [comment]
I see thanks for the clarification. Since this was expected behavior, closing the issue.

**Comment by PRFina** [comment]
>`displot` uses a `FacetGrid` to set up the figure and hence is a figure-level function (can’t be directed onto existing axes), but it does not use `FacetGrid.map` internally because the fact that each facet sees only a slice of the data makes it very cumbersome to do useful things like use the same bins across facets or normalize with respect to the entire dataset, which is the distinction you are seeing.

I ran in the same issue, maybe add this remark to the documentation of `sns.displot` could help to catch this subtlety
