### ISSUE TITLE
Plot does not show up with plot_joint()

### ISSUE THREAD

**Issue by ghost** [mwaskom/seaborn#2737]
Seaborn version 0.11.2
Matplotlib version 3.4.3

The `plot_join()` does not behave like how it is in the documentation. It instead output `<seaborn.axisgrid.JointGrid at 0x1d0195585b0>` in lieu to it showing the plot. The plot does not show unless `figure` is called.
![1](https://user-images.githubusercontent.com/87014674/152111977-89e2019b-e6e6-4550-b9e6-04325b2baeb8.png)
![2](https://user-images.githubusercontent.com/87014674/152111981-3e6555c7-c25e-4ed2-81ea-8ed90f38a64c.png)

**Comment by mwaskom** [comment]
Hi, this is an observation about how the "inline backend" in a jupyter notebook works, not anything to do with seaborn. If will capture and show any figures that are *created* within a cell, and it does not track if you do anything else with those figures in subsequent cells. But you can show the figure again by either having the last line in the cell return it (i.e. so the figure object is an "output" of the cell) or by calling `display(figure`).

There's nothing seaborn can do to make this work differently.

**Comment by hyoaru** [comment]
Alright, thanks for all the hard work!
