### ISSUE TITLE
histplot function raise an error with parameter kde=True and kde_kws={"color": "k", "lw": 3}

### ISSUE THREAD

**Issue by weiwei2021** [mwaskom/seaborn#2740]
Hi，I want to get bold lines by passing the kde_kws parameter to the histplot function, but the histplot raise an error. The parameter is available in the distplot function, so this may be a parameter parsing error in histplot function.

error log
Traceback (most recent call last):
  ***
    sns.histplot(x=data, stat='proportion', kde=True,kde_kws=kde_kws, color='g')
  File "/home/weiwei/.local/lib/python3.8/site-packages/seaborn/distributions.py", line 1462, in histplot
    p.plot_univariate_histogram(
  File "/home/weiwei/.local/lib/python3.8/site-packages/seaborn/distributions.py", line 418, in plot_univariate_histogram
    densities = self._compute_univariate_density(
  File "/home/weiwei/.local/lib/python3.8/site-packages/seaborn/distributions.py", line 290, in _compute_univariate_density
    estimator = KDE(**estimate_kws)
TypeError: __init__() got an unexpected keyword argument 'color'

seaborn version: 0.11.2

**Comment by mwaskom** [comment]
The [documentation](https://seaborn.pydata.org/generated/seaborn.histplot.html) is a little vague huere, but it says

> kde_kws: dict
> Parameters that control the KDE computation, as in [kdeplot()]
> (https://seaborn.pydata.org/generated/seaborn.kdeplot.html#seaborn.kdeplot).

> line_kws: dict
> Parameters that control the KDE visualization, passed to [matplotlib.axes.Axes.plot()]
> (https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.plot.html#matplotlib.axes.Axes.plot).

So in `histplot`, the `kde_kws` does not accept all parameters for `kdeplot`, just the ones that parameterize the actual density estimation (bandwith, etc.), whereas you can control some aspects of what the density curve *looks* like with `line_kws`. But, internally, the bar plot and density curve are one "unit" in `histplot` and cannot be assigned different colors.

**Comment by weiwei2021** [comment]
Thanks @mwaskom, the `line_kws` parameter is exactly what I need. 
`sns.histplot(data,stat='proportion',kde=True,line_kws={'linewidth':3},color='k')` works fine.
