### ISSUE TITLE
seaborn violinplot does not work right for 'inner=points' and 'inner=box' options 

### ISSUE THREAD

**Issue by MR-T77** [mwaskom/seaborn#2742]
When plotting a violinplot I can't get the inner='points' and inner='box' options work for the left part (Hue='Before').
![points](https://user-images.githubusercontent.com/6062179/153753897-3c4e36b3-149e-4d6b-80d5-7ab7897e5100.png)
![box](https://user-images.githubusercontent.com/6062179/153753900-11015208-b2fd-47b5-9df5-bacf39af96a8.png)

Nevertheless, for inner='quartile' and inner='stick' this works well.
![quartile](https://user-images.githubusercontent.com/6062179/153753908-a77874c7-438c-4c79-9fa3-33318bfd52f8.png)
![stick](https://user-images.githubusercontent.com/6062179/153753914-40e4d356-d715-47eb-bacf-d87b2eec44c5.png)

Here goes the code used to reproduce it:

    
    N = 30
    np.random.seed(3)
    data = np.random.normal(size=(N,))
    df = pd.DataFrame({'Before': data,
                       'After': data + 1})
    df_long = pd.melt(df, value_vars=['Before', 'After'])
    sns.violinplot(x='variable', y='value', data=df_long, hue='variable', split=True, inner='box', cut=1)

I'm using seaborn 0.11.2.

**Comment by mwaskom** [comment]
Those represent the subsets, so they are drawn independently.

**Comment by MR-T77** [comment]
But the different inner options are just different ways of representing the same thing, so I don't understand why they have different behaviours. 
Thanks anyway.

**Comment by mwaskom** [comment]
> the different inner options are just different ways of representing the same thing

but they aren't, in the case of a split violin. with `inner="box"`, there is only one boxplot, representing the combined distribution. there are not two boxes, like there are two sets of quartiles.

**Comment by MR-T77** [comment]
Probably I'm missing something here (feel free to send me a pointer to other info), as I don't understand the rationale of considering `inner='box'` fundamentally different than `inner='quartile'`. In my understanding, they're just 2 different graphical ways to represent the same thing. Or is there something I'm missing here?

**Comment by mwaskom** [comment]
The rationale is that the box is drawn in the center of the violin so if there were two of them they would overlap and be useless.

**Comment by MR-T77** [comment]
You did not answer to my question (i.e. the rationale of considering `inner='box'` fundamentally different than `inner='quartile'`). It seems obvious to me that the 4 options for `inner` should be implemented in the same way as they represent the same thing: a distribution.
With this implementation, some visualisations for repeated measurements are being left out of seaborn.

**Comment by mwaskom** [comment]
Feel free to look at the code and propose a specific change; at this point I really don’t understand how to provide an answer that would satisfy you, so I’m going to disengage from this back and forth.

**Comment by jhncls** [comment]
@MR-T77 For your use case, with  `hue` and `x` using the same variable for a split violinplot, a workaround could be to draw the boxplots separately. For example:
```python
import seaborn as sns
import pandas as pd
import numpy as np

N = 30
np.random.seed(3)
data = np.random.normal(size=(N,))
df = pd.DataFrame({'Before': data,
                   'After': data + 1})
df_long = pd.melt(df, value_vars=['Before', 'After'])
ax = sns.violinplot(x='variable', y='value', data=df_long, hue='variable', split=True, inner=None, cut=1)
sns.boxplot(x='variable', y='value', data=df_long, color='gray', width=0.05, boxprops={'zorder': 2}, ax=ax)
```
![image](https://user-images.githubusercontent.com/19649483/154382916-e99a2b1c-cfdb-4317-bbd0-496ada6c83d0.png)

**Comment by jhncls** [comment]
@mwaskom The unexpected output happens whenever the right half of a violin is empty or contains only one element. It happens with the tips dataset using `hue="time"` (with the default hue_order, Thursday has only 1 Dinner; changing the hue_order, the weekend has no Lunches):
```python
tips = sns.load_dataset('tips')
sns.violinplot(x="day", y="total_bill", hue="time", hue_order=["Dinner", "Lunch"], data=tips, split=True)
```
![image](https://user-images.githubusercontent.com/19649483/154422560-aa1ebe25-92d5-4451-8291-b76b53c83d29.png)

We could change a few lines in 'categorical.py' the behavior seems to be as desired, hopefully without introducing a new problem. At [line 1222](https://github.com/mwaskom/seaborn/blob/069d53a3dd29a965987705c823883a93700bbe5e/seaborn/categorical.py#L1222) which starts with `if not j: continue`, change to:
```python
                        # if not j: continue # removed

                        # Get the whole vector for this group level
                        violin_data_both = remove_na(group_data)

                        if j == 1 or len(violin_data_both) <= len(violin_data) + 1:
                            # Draw box and whisker information
                            if self.inner.startswith("box"):
                                self.draw_box_lines(ax, violin_data_both,
                                                    support, density, i)

                            # Draw point observations
                            elif self.inner.startswith("point"):
                                self.draw_points(ax, violin_data_both, i)
```
(Probably the parameters `support` and `density` should be removed from `draw_box_lines`, as they aren't used and are only calculated for one half of the violin.)

![image](https://user-images.githubusercontent.com/19649483/154423625-b073d078-9bf2-464f-8118-4e65e20ea133.png)

@MR-T77 About the "why" question:  The "box" option for a split violin needs to follow a different logic, as it represents both halves together (half a box would look weird). The "quartile" and "stick" options need to be applied to both halves separately. The "point" option can go either way.

Seaborn is a complex library that takes a huge amount of combinable options into account. Most of this wonderful piece of software is written by one man, mainly after-hours. Friendly bug reports are very welcome.

**Comment by MR-T77** [comment]
@jhncls thank you so much for your attention. I had opted to draw the boxplots separately.
Regarding Seaborn, I can only be extremely grateful (particularly to @mwaskom) as I have used it countless times. I submitted this issue in the most friendly way (and I really thought I had found a bug), but as I wasn't understanding the provided answers I continued the questioning a little too much, I recognize.
Please do keep up with the good work!

**Comment by mwaskom** [comment]
Ah, thanks @jhncls, that does look like a bug!
