### ISSUE TITLE
kedplot not showing legend

### ISSUE THREAD

**Issue by alternativebug** [mwaskom/seaborn#2743]
df = pd.read_csv('iris.csv')
    for i, label in enumerate(df['variety'].drop_duplicates().values):
        df.loc[df['variety'] == label, 'c'] = i
        sns.kdeplot(
            df.loc[(df['variety'] == label), 'sepal.length'],
            shade=True,
            label=label,
            legend=True,
        )
    plt.xlabel('Sepal Length')
    plt.ylabel('Probability Density')
    plt.show()

Here's the result which is exactly the opposite of what I'm expecting:

![xyz](https://user-images.githubusercontent.com/58062537/154081041-8a9db879-9ea8-40c6-97d3-aa0099155fd9.jpg)

It seems `label` and `legend` are useless arguments.

**Comment by mwaskom** [comment]
You are mixing ways of doing things. `legend` controls whether seaborn adds a legend for the groups that it creates (i.e. using `hue`). Adding a `label` (which just gets passed through) to a matplotlib plot will allow it to appear automatically when you call `plt.legend` but you need to do that manually.

**Comment by alternativebug** [comment]
So, how can I show a legend?

**Comment by mwaskom** [comment]
Try the command in my previous response. Otherwise you’ll need to seek help elsewhere.

**Comment by nipunbatra** [comment]
Just thought to mention the full working example here in case someone finds it useful.

#### 1d example

```python
import seaborn as sns
iris = sns.load_dataset("iris")
sns.kdeplot(iris['sepal_length'], hue = iris['species'])
```
![Unknown](https://user-images.githubusercontent.com/60985/154836192-5b8a0ed5-98cb-418f-b909-da12f4768194.png)


#### 2d example
```python
import seaborn as sns
geyser = sns.load_dataset("geyser")
sns.kdeplot(x=geyser["waiting"], y=geyser["duration"], hue=geyser['kind'])
```

![Unknown](https://user-images.githubusercontent.com/60985/154836072-e3747eb4-78c6-4534-b6a7-cbd0dbc56583.png)
