### ISSUE TITLE
Pointplot does not pass through clip_on

### ISSUE THREAD

**Issue by gaellericher** [mwaskom/seaborn#2745]
Hello ! I am trying to pass the `clip_on=False` argument to pointplots to avoid clipping on both points and error bars on the border of the plot. Compared to barplot for instance, pointplot does not seem to allow to pass any arguments to the underlying scatter function and passing clip_on=False does not seem to work, at least on markers.

I imagine the work-around from #2142 can help to disable clipping on error bars but I wonder if there is something similar for markers.

**Comment by mwaskom** [comment]
Hi, that's right, because a pointplot is constructed from a few different calls to matplotlib functions extra kwargs are not picked up by all of the artists. Modifying their properties as in the linked issue should work, though.

**Comment by mwaskom** [comment]
This will remain the status quo for now, but `pointplot` is drawn this way to work around some bugs in `ax.errorbar` that have finally been fixed, so it's possible that it will transition to using that as the underlying matplotlib function and then there will be one target for additional kwargs.
