### ISSUE TITLE
`histplot` is showing wrong counts.

### ISSUE THREAD

**Issue by matteosantama** [mwaskom/seaborn#2746]
I'm working with a dataset, and when I try to use `sns.histplot` the results are demonstrably wrong.

[issue.csv](https://github.com/mwaskom/seaborn/files/8110666/issue.csv)

```python
data = pd.read_csv("issue.csv", index_col=0, dtype={"collection_name": "category"})

plt.figure(figsize=(12, 10))

sns.histplot(
    y="centroid",
    hue="collection_name",
    data=data,
    multiple="stack",
    shrink=0.7,
    palette="muted",
)
```

which yields

<img width="740" alt="Screen Shot 2022-02-21 at 8 07 31 AM" src="https://user-images.githubusercontent.com/13473688/154991149-0cf3d4e9-37d7-45d5-a72c-018b10f9fa70.png">

but these counts aren't correct. For example,

```python
data[data.centroid == 0].collection_name.value_counts()
```

gives

```
Parallel Alpha                  1044
0N1 Force                          0
Loot (for Adventurers)             0
VeeFriends                         0
The Sandbox                        0
SuperRare                          0
Rarible                            0
Pudgy Penguins                     0
PUNKS Comic                        0
Mutant Ape Yacht Club              0
MekaVerse                          0
Meebits                            0
Fidenza by Tyler Hobbs             0
Azuki                              0
Doodles                            0
CyberKongz                         0
CryptoPunks                        0
CrypToadz by GREMPLIN              0
Creature World                     0
Cool Cats NFT                      0
Chromie Squiggle by Snowfro        0
CLONE X - X TAKASHI MURAKAMI       0
Bored Ape Yacht Club               0
Bored Ape Kennel Club              0
World of Women                     0
Name: collection_name, dtype: int64
```

Also notice that the histogram counts are way too large. I'm using `seaborn`: v0.11.2 and `pandas`: v1.4.1

**Comment by mwaskom** [comment]
Based on the evidence you give for the "demonstrably wrong" behavior, I think you are expecting a separate bar for each value of `centroid`? If so, you need to control that behavior (i.e. by setting `discrete=True` or making the centroid column categorical). Otherwise the default way to draw a histogram with numeric data is to bin the values.

**Comment by matteosantama** [comment]
Oh duh! There aren't 250 bars shown. Yes, I was expecting a bar per value. I guess my only comment is that I wouldn't have thought to use the `discrete` keyword given the docs. Perhaps a better docstring would be "If True, set `binwidth=1`. This forces a single bar per `x` or `y` value along the axis. ..."

**Comment by matteosantama** [comment]
Thanks for speedy response. Please consider this issue resolved and feel free to close!

**Comment by mwaskom** [comment]
> This forces a single bar per x or y value along the axis. ..."

This wouldn't be quite accurate because if your data aren't integral, it will still bin them.
