### ISSUE TITLE
violinplot has hardcoded edge color 

### ISSUE THREAD

**Issue by benlongo** [mwaskom/seaborn#2752]
violinplot has the edge color hardcoded https://github.com/mwaskom/seaborn/blob/ad0240a867bb1622c79abac850e1dc30cb4b3be1/seaborn/categorical.py#L1104

**Comment by mwaskom** [comment]
Yes, it does.

**Comment by mwaskom** [comment]
I would review a complete pull request that proposed a different behavior but as this is not a bug I do not think it needs an issue to track it.
