### ISSUE TITLE
stripplot :  s must be a scalar, or float array-like with the same size as x and y

### ISSUE THREAD

**Issue by NabeelNajjar** [mwaskom/seaborn#2759]
```
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/mpg_ggplot2.csv")
df_select = df.loc[df.cyl.isin([4,8]), :]
df_counts = df.groupby(['hwy', 'cty']).size().reset_index(name='counts')
df_counts['sqrt2']=1.0*df_counts['counts']**2
sns.stripplot(x=df_counts['cty'], y=df_counts['hwy'], ax=ax, size= df_counts['sqrt2'])
```

even I gave him a SERIES  in the main code => it takes  a SINGLE value for x  in line   [4378]
[3.9.6\lib\site-packages\matplotlib\axes\_axes.py]

code should be edited ,  I think

**Comment by mwaskom** [comment]
Hi, the `size` parameter is documented as 

> size : float, optional
    Radius of the markers, in points.

so this behavior is not surprising or incorrect.

If you need additional help, I would recommend making a reproducible example and asking on StackOverflow.

**Comment by NabeelNajjar** [comment]
[s must be a scalar, or float  **array-like** with the same size as x and y]()
