### ISSUE TITLE
Suggestion: Add option for non-square plots to JointGrid

### ISSUE THREAD

**Issue by joha1** [mwaskom/seaborn#2760]
I'm using [`JointGrid`](https://seaborn.pydata.org/generated/seaborn.JointGrid.html#seaborn.JointGrid) for a scatterplot with a KDE on the margins. Simple most MWE would be straight from the documentation:

    penguins = sns.load_dataset('penguins')
    g = sns.JointGrid()
    x, y = penguins["bill_length_mm"], penguins["bill_depth_mm"]
    sns.scatterplot(x=x, y=y, ec="b", fc="none", s=100, linewidth=1.5, ax=g.ax_joint)
    sns.kdeplot(x=x, fill=False, linewidth=2, ax=g.ax_marg_x)
    sns.kdeplot(y=y, linewidth=2, ax=g.ax_marg_y)

Now, for this example, the square scatterplot works perfectly fine (x and y both in mm, with a similar range

However, when working with stable isotopes of water, where the y axis (Deuterium) tends to span in the range from -250 to 0 and the x axis (d18O) is between -30 and 0 and thus, most publications on this subject have their scatterplots in a non-square aspect ratio (see e.g. [this wikipedia article](https://en.wikipedia.org/wiki/Global_meteoric_water_line)).

I can get a non-square plot with pure `sns.scatterplot` (and I can do a lot of great things with `hue`, `style` and so on...) but additionally having the KDE on the margins as `JointGrid` easily allows me to do is really helpful, but when every isotope plot I know about isn't square, mine probably shouldn't be either...

The documentation states 

> The figure will always be square (unless you resize it at the matplotlib layer)

but doesn't give specifics, and I'm probably not the only one who's using seaborn to somewhat avoid the *matplotlib layer*. Searching for it produces some solutions, e.g. [here](https://stackoverflow.com/questions/29909515/how-to-plot-non-square-seaborn-jointplot-or-jointgrid) or [there](https://www.tutorialspoint.com/how-to-plot-a-non-square-seaborn-jointplot-or-jointgrid-matplotlib), but adding it to the MWE appears to do nothing, so they're apparently outdated:

    #plt.rcParams["figure.figsize"] = [20, 10]
    #plt.rcParams["figure.autolayout"] = True
    g = sns.JointGrid()
    g.fig.set_figwidth=(20)
    g.fig.set_figheight=(10)
    x, y = penguins["bill_length_mm"], penguins["bill_depth_mm"]
    sns.scatterplot(x=x, y=y, ec="b", fc="none", s=100, linewidth=1.5, ax=g.ax_joint)
    sns.kdeplot(x=x, fill=False, linewidth=2, ax=g.ax_marg_x)
    sns.kdeplot(y=y, linewidth=2, ax=g.ax_marg_y)
    #plt.show()

(same result when uncommenting the additions from the second link)

**So is it possible to add an option for non-square plots into `JointGrid` or to add some more info to the documentation?**

**Comment by mwaskom** [comment]
Hi, your issue here 
```
g.fig.set_figwidth=(20)
g.fig.set_figheight=(10)
```

Is the equals sign ... you are overwriting these methods with a number rather than calling them.

So it should work if you fix that bug, but here is how I would make the plot:

```python
g = sns.JointGrid(data=penguins, x="bill_length_mm", y="bill_depth_mm")
g.plot_joint(sns.scatterplot)
g.plot_marginals(sns.kdeplot)
g.figure.set_size_inches(6, 3)
```

> I'm probably not the only one who's using seaborn to somewhat avoid the *matplotlib layer*

I'm typically not persuaded by this argument because it feels like it misses the point. If seaborn exposed all of matplotlib's flexibility, it would no cease being simpler / easier to use than matplotlib.

**Comment by joha1** [comment]
How the hell did the `=` get in there? I double checked my MWE, on two machines with different versions of anaconda and sns before deciding to open an issue, because the easily findable guides obviously didn't work anymore... Without the `=` works and your `g.figure.set_size_inches(6, 3)` also works (and is more compact).

Sorry to bother you!

>If seaborn exposed all of matplotlib's flexibility, it would no cease being simpler / easier to use than matplotlib.

You're right, that definitely is an issue and I guess that's your call to make. I'm probably biased on this particular `JointGrid`/`scatterplot` issue, since I feel like this particular seaborn method is perfectly suited to working with isotopes, in fact, it seems like it was tailor made for this workflow, apart from the square defaults, so it seems like an obvious oversight to me. But if the other uses of this plot always use a square and my use is the outlier, that's perfectly fine by me.
