### ISSUE TITLE
Seaborn kdeplot does not allow user to customize legend

### ISSUE THREAD

**Issue by arojas314** [mwaskom/seaborn#2761]
Seaborn kdeplot does not return handles or labels from legend, and it does not allow any customization whatsoever of legend.
Try for yourself with the iris flower dataset using the kdeplot function with the hue set by species.

Here is my simple code:
```
sns.kdeplot(data=afrisar_df_ha, x="Ndens, hue="Site", ax=ax[0])
ax[0].legend(loc="upper left", title=None)
```
Error message returned is:
"No handles with labels found to put in legend."

Thanks,
Alex

**Comment by mwaskom** [comment]
Hi, searching the error message here would surface several relevant issues, including [this one](https://github.com/mwaskom/seaborn/issues/2231), which is currently pinned immediately above the "New issue" button...

**Comment by mwaskom** [comment]
Closing as a duplicate.
