### ISSUE TITLE
Why not put hue function to regplot and ax function to lmplot

### ISSUE THREAD

**Issue by lch99310** [mwaskom/seaborn#2770]
As title
I am a newbie to seaborn. 
lmplot and regplot are the two plots I use a lot. But Why not put hue function to regplot and ax function to lmplot so that both of them can have more powerful applications.

**Comment by mwaskom** [comment]
Hi, thanks for your question; I believe it is answered in this chapter of the tutorial: https://seaborn.pydata.org/tutorial/function_overview.html
