### ISSUE TITLE
Histplot's hue parameter puts more different color bars than are on the legend

### ISSUE THREAD

**Issue by rtavasso1** [mwaskom/seaborn#2771]
e.g. with a hue vector with 3 unique values, there are more than 3 different colored bars on in the plot that correspond to seemingly nothing. ![miscolored bars](https://user-images.githubusercontent.com/83459472/160413069-c916c1b6-4d41-4cf7-ab04-abf944e2566b.PNG)

**Comment by rtavasso1** [comment]
Looked into it more and found it to be related to the way colors mix with parameter multiple='layer'.

**Comment by mwaskom** [comment]
Yes. This is working as expected.
