### ISSUE TITLE
Missing axis label in pairplot

### ISSUE THREAD

**Issue by maximelucas** [mwaskom/seaborn#2772]
Running 
```python
import numpy as np
import pandas as pd
import seaborn as sb

data = np.random.random(size=(100, 3))
df = pd.DataFrame(data, columns=['x', 'y', 'z'])

sb.pairplot(df, diag_kind=None, corner=True)
```
yields:
<img src="https://user-images.githubusercontent.com/7493360/160799688-8d6c6539-9bf8-4d22-8962-6a8e6e6ad1d9.png" width="300" height="300">

which misses 'x' as the `ylabel` on the top left axis.  

I understand that when `diag_kind` has another value, this behaviour is expected because the y-axis does not show 'x' on the diagonal. But when, `diag_kind=None` like here, it should be there.

Of course this can be fixed manually
```python
grid = sb.pairplot(df, diag_kind=None, corner=True)
grid.axes[0,0].set_ylabel('x')
```

**Comment by mwaskom** [comment]
I am curious about whether you have a particular use for `diag_kind=None`?

**Comment by maximelucas** [comment]
I'm in a case where I use a `hue = cluster_labels` and I don't have that many data points.

I guess I could also use `diag_kind = 'kde'`. But seeing as I don't have many points, I like to see the actual data points rather than the smoothed out distributions from 'kde'.

Another minor thing is that with `diag_kind = None` the figure can be inspected both vertically and horizontally. With `diag_kind = 'kde'`, for the bottom right diagonal Axis `z`, it's harder to visually compare it with the non-diagonal Axis including `z` because you have to compare horizontally with the other Axes in the row, but the vertical scales don't match.  

In any case, since the case `diag_kind = None` is supported and documented, I guess it should have the right axis labels.

**Comment by mwaskom** [comment]
I see, you're using it as sort of a rugplot projected onto line of equality. Makes sense. This is a pretty low priority issue from my perspective but also should be a simple fix so feel free to submit a PR...
