### ISSUE TITLE
Option to visualize entire range with vertical line in barplot

### ISSUE THREAD

**Issue by cirnod** [mwaskom/seaborn#2777]
[Feature request]

With seaborn [barplots](https://seaborn.pydata.org/generated/seaborn.barplot.html), in addition to the bars, vertical lines (aka error bars) can be plotted to indicate the confidence interval (ci). 

I have a use case where I would like to use the error bars to visualize the entire range spanned by the samples, i.e. the min and the max of the data. For boxplot, this is possible by specifying `whis=(0, 100)` which apparently is passed to the matplotlib. However, it seems that this is not possible with barplot with the current version of seaborn (0.11.2). 

I see 2 options to add this to seaborn:
* Proposal 1: Add a custom option for `ci`, e.g. `er` (for "entire range") similar to the already existing option `sd`.
* Proposal 2: Add an option to disable bootstrapping for determining the confidence interval. In this case, one should be able to disable bootstrapping and use `ci=100` to get the entire range. 

I locally tried out proposal 1 and it seems to work fine. However, I'm not sure about potential negative side effects. Here is my small extension (relative to v0.11.2, line [1535](https://github.com/mwaskom/seaborn/blob/v0.11.2/seaborn/categorical.py#L1535)):
```
elif ci == 'er':
    minVal = np.min(stat_data)
    maxVal = np.max(stat_data)
    confint[i].append((minVal, maxVal))
```

**Comment by mwaskom** [comment]
Hi, see here: https://github.com/mwaskom/seaborn/pull/2407

It hasn't rolled out to `barplot` yet but will at some point be possible to do `barplot(..., errorbar=("pi", 100))` to get what you are looking for.

In the meantime, you could use the dev version and hack something together like

![image](https://user-images.githubusercontent.com/315810/161849382-0a3d981a-bc76-4e17-ad8f-f56269bb4f73.png)
