### ISSUE TITLE
Modify marker's size in stripplot() according to value

### ISSUE THREAD

**Issue by antoinedoury** [mwaskom/seaborn#2778]
Hi, 

I have an error with stripplot when I try to change the the marker's size according to a value. 

For exemple: 
A=['A','B','C']*10
B=np.random.rand(30)
sn.stripplot(x=A,y=B,s=B)

returns : 
'ValueError: s must be a scalar, or the same size as x and y'

Could you help me with that?

Thanks

**Comment by jhncls** [comment]
`sns.stripplot` currently doesn't have an option to change the dot sizes. A workaround could be to first create a `sns.scatterplot` and then move the dots a bit (the distance needs to be smaller if `hue` and `dodge` are involved):
```python
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

A = ['A', 'B', 'C'] * 10
B = np.random.rand(30)
ax = sns.scatterplot(x=A, y=B, s=B * 100, hue=A, legend=False)

for dots in ax.collections:
    xy = dots.get_offsets()
    xy += np.c_[np.random.uniform(-.4, .4, len(xy)), np.zeros(len(xy))]
    dots.set_offsets(xy)
ax.set_xlim(-.5, len(ax.get_xticks()) - .5) # add some more space
```
![image](https://user-images.githubusercontent.com/19649483/162804423-82fc4078-abd7-49b6-bcdc-731f3d5257e4.png)

**Comment by antoinedoury** [comment]
Hi!  

I could not understand the returned error, I see now that it was just not implemented. 

Thanks, you're solution seems to make it.
