### ISSUE TITLE
Small issue with lineplot documentation 

### ISSUE THREAD

**Issue by arnodunstatter** [mwaskom/seaborn#2781]
I believe there may be a small error with your [lineplot documentation](https://seaborn.pydata.org/generated/seaborn.lineplot.html). The parameter "markers" is shown and described, but from my use it appears as though the correct parameter is actually called "marker".

**Comment by mwaskom** [comment]
`marker` is the name of a matplotlib parameter that can be used because `lineplot` passes keyword arguments through to `ax.plot`. `markers` is the name of a seaborn parameter that applies when using `style`. This is not an error.
