### ISSUE TITLE
No simple way to access statistics of central tendency and bootstrap confidence intervals from e.g., catplot, lineplot

### ISSUE THREAD

**Issue by Riley16** [mwaskom/seaborn#2782]
I wasn't able to find a way to access the resulting statistics of central tendency and confidence intervals in catplot, lineplot etc. These results should be accessible. If I'm going to report a confidence interval or a p-value for a statistical test, I'd prefer to show the confidence intervals from the same bootstrap samples in the plot as were used in the reported test as opposed to recomputing the bootstraps outside of seaborn, which would result in stochastically (though slightly if a proper number of bootstrap samples are used) different confidence intervals for the test and the plot. This also eliminates a lot of the convenience of having these confidence intervals being computed in seaborn since we'd have to go to the trouble of recomputing them anyways.

**Comment by mwaskom** [comment]
Thanks for the suggestions but there are several issues about this question already that you can find if you search.
