### ISSUE TITLE
Unable to plot barplot

### ISSUE THREAD

**Issue by Shantanu-Ghumatkar** [mwaskom/seaborn#2786]
[day1.zip](https://github.com/mwaskom/seaborn/files/8595526/day1.zip)
---------------------------------------------------------------------------
# import matplotlib
# sns.set()
sns.barpolt(x="Aggregate rating",y="Rating Count",data=ratings)

AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_12000/412728375.py in <module>
      1 # import matplotlib
      2 # sns.set()
----> 3 sns.barpolt(x="Aggregate rating",y="Rating Count",data=ratings)

AttributeError: module 'seaborn' has no attribute 'barpolt'

**Comment by takoika** [comment]
Is "barpolt" a typo for "barplot"?

**Comment by mwaskom** [comment]
Thanks @takoika that's what it looks like is happening here.
