### ISSUE TITLE
Boxplot does not align with tick labels

### ISSUE THREAD

**Issue by AdityaAsopa** [mwaskom/seaborn#2790]
I have the categorical array:  [22, 23, 24...32] against which I am plotting a bunch of numbers in catplot (kind = 'box'). The boxes are not aligning with the category labels. Could someone check why?

Following the sample from dataframe with labels and the code to plot:

![image](https://user-images.githubusercontent.com/11498989/166914315-3eee1148-b2a3-4f49-b5e1-c653fc8e7cae.png)

`

    def is_IR_stable(datadf):

      df = datadf.iloc[:,[0,1,11]]

      df = df.loc[df['exptID']!=0]

      df.sort_values(by=['exptID','sweep'])

      plt.figure()

      sns.catplot(data=df, hue='exptID', y='InputRes', x='exptID', kind='box')

      plt.show()

    is_IR_stable(cell.data)
`

Thanks in advance

**Comment by mwaskom** [comment]
Hi, I think you want `dodge=False`.

**Comment by AdityaAsopa** [comment]
Thanks a lot. Works!
