### ISSUE TITLE
UserWarning: ``square=True`` ignored in clustermap

### ISSUE THREAD

**Issue by Zethson** [mwaskom/seaborn#2791]
Hi,

Whenever I run 

```
sb.clustermap(
        master_table_top_10_pearson.transpose(),
        square=True
)
```

for my DataFrame which looks like a perfectly normal DataFrame
![image](https://user-images.githubusercontent.com/21954664/167393412-de87bd8b-a374-42c8-96d9-28e2b9e5695c.png)

I get `UserWarning: ``square=True`` ignored in clustermap  warnings.warn(msg)`. However, I need the squares in my plot. I cannot see a reason why the parameter gets ignored.

Thank you very much!

**Comment by mwaskom** [comment]
> However, I need the squares in my plot. I cannot see a reason why the parameter gets ignored.

If you change the aspect ratio on the main heatmap, it will not affect the dendrogram axes and so the dendrograms will no longer align. Matplotlib does not provide a simple mechanism for synchronizing multiple subplots in this way. Of course, you can always work out the figure size and subplot ratios that will make the heatmap cells (more or less) square and set those.
