### ISSUE TITLE
Non-filled markers do not render in stripplot

### ISSUE THREAD

**Issue by jwdebelius** [mwaskom/seaborn#2793]
Hi!

I'm trying to match data between 1d categorical plots and 2d scatter plots. I have data with two levels that I'm indicating with a color and a marker. I'd like to be consistent in my color/marker combo across my figure. As a hack, I've determined I can plot each strip plot for a marker separately, using the marker argument from matplotlib.

Based on the defaults in seaborn scatter, I've been using a circle (`'o'`) and x (`'x`') as my default markers. However, stripplot doesn't support the unfilled marker (`x`).

As a minimal example:
```python
import matplotlib.pypplt as plt
import numpy as np
import pandas as pd
import seaborn 

data = pd.DataFrame(
    np.vstack([np.hstack([np.ones(6) * i for i in range(2)]),
               np.hstack([np.random.normal(size=6) + i for i in range(2)])
              ]).T,
    columns=['group', 'value'],
)

fig, axes = plt.subplots(1, 2, sharex=True, sharey=True)
sn.stripplot(ax=axes[0], x='group', y='value', data=data, marker='o')
sn.stripplot(ax=axes[1], x='group', y='value', data=data, marker='+')
```
I get an error message for the plot with an unfilled marker:
```
UserWarning: You passed a edgecolor/edgecolors ('#3f3f3f') for an unfilled marker ('+').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
```
And, the data doesn't show up in the output plot:

![The output strip plot. The left panel shows a strip plot with circle markers. The righ tpanel shows an empty plot](https://user-images.githubusercontent.com/5534846/167698346-2ce69955-eb56-43df-bddb-5ecccce677b8.png)

I'm hoping that the marker issue might dovetail existing refactor plans, if its of interest, let me know if I could help.

**Comment by mwaskom** [comment]
The gotcha here is that the default parameters have`linewidth=0`. You can make the unfilled markers visible by changing that:

```python
sns.stripplot(ax=axes[1], x='group', y='value', data=data, marker='+', linewidth=1, s=10)
```
![image](https://user-images.githubusercontent.com/315810/167722512-28a9c23d-39e1-449d-9f36-adb32e36ef78.png)

The warning from matplotlib is innocuous in this case. The facecolor/edgecolor dance with filled/unfilled markers is a little annoying ... I am not sure exactly where they are going to land but at least on the dev seaborn I can suppress the warning by passing `edgecolor="face"`. (Doesn't seem to work on 0.11.2).

**Comment by jwdebelius** [comment]
That is super helpful, thank you so much!
