### ISSUE TITLE
[Feature request] Add style and size options to stripplot

### ISSUE THREAD

**Issue by renatobellotti** [mwaskom/seaborn#2798]
I'd love to combine the benefits of stripplot (i. e. non-overlapping dots) with the flexibility provided by ``sns.replot()``. Having different sizes and markers would allow to visualise two additional dimensions.

**Comment by mwaskom** [comment]
Hi, please see the relevant issues on categorical plot refactoring.

Generally, if there's an obvious feature that you think a library should have, the problem is not that nobody else has thought of it, but that there are technical limitations to implementing it.
