### ISSUE TITLE
legend shows wrong if giving my own label name on windows.

### ISSUE THREAD

**Issue by whynpt** [mwaskom/seaborn#2802]
I got problem with `plt.legend`.  for example, my code is `plt.legend(loc='best', labels=['a', 'b', 'c', 'd'], fontsize=30)`. some labels show wrong like this.
![image](https://user-images.githubusercontent.com/54671694/168303140-84d84a0b-9dd3-490d-9310-1869a115f569.png)
But it works fine without my own label name. i change my code to `    plt.legend(loc='best', labels=None, fontsize=30)`.the picture turns to be like this.
![image](https://user-images.githubusercontent.com/54671694/168304605-a2a0951c-9baa-438b-832a-7672cda82048.png)
'dense HER' and 'dense DDPG' are contend of `hue`  in my .csv file. by the way, the code  `plt.legend(loc='best', labels=['a', 'b', 'c', 'd'], fontsize=30)` works fine in ubuntu20

**Comment by mwaskom** [comment]
Hi, this is not a reproducible example so I can't really provide much advice but I suggest searching on Stackoveflow for questions about how to customize a matplotlib legend.
