### ISSUE TITLE
kdeplot log normalization

### ISSUE THREAD

**Issue by witherscp** [mwaskom/seaborn#2811]
Is it possible to apply a log normalization to a bivariate density plot? I only see the `log_scale` parameter which can apply a log scale to either one or both of the variables,  but I want to scale the density values. With Matplotlib.pyplot.hist2d there is a norm parameter to which I can pass `norm=matplotlib.colors.LogNorm()` to apply a log normalization. Is this functionality available for kdeplot?

**Comment by mwaskom** [comment]
Have you tried passing `norm=mpl.colors.LogNorm()` to `kdeplot`?

**Comment by witherscp** [comment]
Yes, that worked. Brilliant idea... how did I not think of that? :)
