### ISSUE TITLE
seaborn.residplot(..., lowess=True) raises a statsmodels ImportError when installed without the setuptools extra

### ISSUE THREAD

**Issue by Julian** [mwaskom/seaborn#2815]
Running `python3.10 -m venv venv; venv/bin/python -m pip install --quiet seaborn; venv/bin/python -c 'from seaborn import residplot; residplot(x=[1, 2, 3], y=[4, 5, 6], lowess=True)'` produces:

```
⊙  python3.10 -m venv venv; venv/bin/python -m pip install --quiet seaborn; venv/bin/python -c 'from seaborn import residplot; residplot(x=[1, 2, 3], y=[4, 5, 6], lowess=True)'                                                                                                                                   julian@Airm
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/julian/Desktop/venv/lib/python3.10/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/Users/julian/Desktop/venv/lib/python3.10/site-packages/seaborn/regression.py", line 1120, in residplot
    plotter.plot(ax, scatter_kws, line_kws)
  File "/Users/julian/Desktop/venv/lib/python3.10/site-packages/seaborn/regression.py", line 370, in plot
    self.lineplot(ax, line_kws)
  File "/Users/julian/Desktop/venv/lib/python3.10/site-packages/seaborn/regression.py", line 413, in lineplot
    grid, yhat, err_bands = self.fit_regression(ax)
  File "/Users/julian/Desktop/venv/lib/python3.10/site-packages/seaborn/regression.py", line 214, in fit_regression
    grid, yhat = self.fit_lowess()
  File "/Users/julian/Desktop/venv/lib/python3.10/site-packages/seaborn/regression.py", line 294, in fit_lowess
    from statsmodels.nonparametric.smoothers_lowess import lowess
ModuleNotFoundError: No module named 'statsmodels'
```

#2398 made `statsmodels` an optional dependency, so the mistake in the above is not installing `seaborn[all]`, but it still seems a bit nonideal that one can't really tell that statsmodels is a mandatory dependency for `lowess=True`.

There are various ways to handle this, not sure which if any are appetizing to you, but perhaps either of:

* adding a note to [the residplot docs](https://seaborn.pydata.org/generated/seaborn.residplot.html#seaborn.residplot) under `lowess` saying it requires the `all` setuptools extra
* catching the `ModuleNotFoundError` and re-reraising one saying that `seaborn` needs to be installed with the `all` extra to use this option, so it's clear to an end-user that seaborn hasn't just forgotten to declare its dependency

are things you might be up for.

And thanks for the library, obviously it's well loved :)

**Comment by mwaskom** [comment]
+1 on making this more clear. I'm not certain whether function-level docs/errors should specify the `pip` invocation (it seems easy for those to get out of sync, and I don't think it's relevant for `conda`/`mamba` installations.

Note that the dependencies docs do say

> Installation requires [numpy](https://numpy.org/), [pandas](https://pandas.pydata.org/), and [matplotlib](https://matplotlib.org/). Some functions will optionally use [scipy](https://www.scipy.org/) and/or [statsmodels](https://www.statsmodels.org/) if they are available.

**Comment by Julian** [comment]
I saw that line in the docs, but if anything I got the opposite out of it :D!

It sounded to me like it meant "if they're available, they're optionally used, but if they're not, stuff works another way". Whereas here it really means "some functions need statsmodels to be used".

**Comment by mwaskom** [comment]
That's reasonable! That language may actually date back to when `kdeplot` would use statsmodels' FFT-accelerated KDE computation or otherwise fall back to scipy.

I think the lowest hanging fruit here would be updating the `residplot` (and `regplot`) parameter documentation to say "(requires statsmodels)" or "(requires statsmodels to be installed)". Clarifying the dependency documentation would be good too. Perhaps "some advanced features require scipy and/or statsmodels to be installed as well"?
