### ISSUE TITLE
Logarithmic hist plot with multi='dodge': unequal bar width

### ISSUE THREAD

**Issue by infosec-it-init** [mwaskom/seaborn#2820]
Using a hist plot with logarithmic x-axis results in unequal bar width.

Fix PR is provided in #2819

**Comment by mwaskom** [comment]
Thank you for taking the initiative to suggest a fix, but please provide a reproducible example of the bug so I can understand what the problem is an whether your PR fixes it.

**Comment by infosec-it-init** [comment]
Reproducible example:
```python
np.random.seed(0)
df = pd.DataFrame({'hue': ['A'] * 1000 + ['B'] * 1000 + ['C'] * 1000, 'value': np.power(10, np.random.random(size=3000) * 10)})
sns.histplot(data=df, x='value', hue='hue', multiple='dodge', bins=20, log_scale=True)
```

Histogram without the fix (unequal bar width):
![fig1](https://user-images.githubusercontent.com/50730463/170931352-998f3660-972f-4e7a-9883-6857f194a622.png)


Histogram with the fix (equal bar width):
![fig2](https://user-images.githubusercontent.com/50730463/170931228-e0419803-5d0d-45b2-89ac-0cb99843f9da.png)

**Comment by mwaskom** [comment]
Thanks!
