### ISSUE TITLE
Violin  plotting with seaborn raises ValueError: object arrays are not supported

### ISSUE THREAD

**Issue by xexeo** [mwaskom/seaborn#2824]
I just checked this error with an artificial dataset and realized that some forms of creating Panda's DataFrames using ints make the column type be an object and not an int, and this is probably causing problems with violin diagram in Seaborn.

It is probably the same error described in #2668, but it shows how to bypass it in a logical way.

Using Colab, the following example shows why one plot works and other not. The "trick" is to convert the Data Frame to a dict and back to a Data Frame. I believe there is an explanation here for how it works.

```
import pandas as pd
import seaborn as sbs
import random 
import matplotlib.pyplot as plt

column_names = ["x","y"]
random_set = ['A','B']
df = pd.DataFrame(columns = column_names)

# not the better way of creating a DF, but possible
for i in range(100):
  d_util = {"x" : random.choice(random_set),
            "y" : random.randint(1,100)}
  df = df.append(d_util, ignore_index = True)

# See the types...
print("Original Types: ",df.dtypes)

# Now the "magic"
fix = pd.DataFrame(df.to_dict()) #what? What was wrong with the DataFrame?
print("New Types: ",fix.dtypes)

# This works
sbs.violinplot(x='x', y='y', data=fix)

#this not
sbs.violinplot(x='x', y='y', data=df)
```

The output is:

```
Original Types:  x    object
y    object
dtype: object
New Types:  x    object
y     int64
dtype: object
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-d8663aa8f635> in <module>()
     25 
     26 #this not
---> 27 sbs.violinplot(x='x', y='y', data=df)

9 frames
/usr/local/lib/python3.7/dist-packages/scipy/_lib/_util.py in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    247     if not objects_ok:
    248         if a.dtype is np.dtype('O'):
--> 249             raise ValueError('object arrays are not supported')
    250     if as_inexact:
    251         if not np.issubdtype(a.dtype, np.inexact):

ValueError: object arrays are not supported
```
[![Figure when it works][1]][1]

The next example, creating the Data Frames with correct types, also works.

```
# Another option when creating the dataframe 

import pandas as pd
import seaborn as sbs
import random 
import matplotlib.pyplot as plt


random_set = ['A','B']

dfw = pd.DataFrame({'x' : pd.Series(dtype='str'),
                   'y' : pd.Series(dtype='int')})


for i in range(100):
  d_util = {"x" : random.choice(random_set),
            "y" : random.randint(1,100)}
  dfw = dfw.append(d_util, ignore_index = True)

print("Original Types: ",dfw.dtypes)

x = sbs.violinplot(x='x', y='y', data=dfw)
```

You can check it in [https://colab.research.google.com/drive/1uc_wr7zsjdfkX9cdFI943trVQR-_nWx0?usp=sharing][2]

  [1]: https://i.stack.imgur.com/vnJbW.png
  [2]: https://colab.research.google.com/drive/1uc_wr7zsjdfkX9cdFI943trVQR-_nWx0?usp=sharing

**Comment by mwaskom** [comment]
>  The "trick" is to convert the Data Frame to a dict and back to a Data Frame.

As I understand it, the issue is with the dtype of the `y` variable (and is getting raised from scipy), so this suggested workaround is overkill, you would just need `df = df.astype({y: float})`.

Or rather, if you're building you dataframes this way, start with `pd.DataFrame(columns=["a", "b"], dtype=float)`.

**Comment by mwaskom** [comment]
There's a gradual process of refactoring the various functions to use a common codepath that ensures data are represented as floats before doing any stats on them. That will eventually help this work as expected, but I'm going to defer any changes until that point.
