### ISSUE TITLE
next gen version (0.12.0a1) bug: StopIteration when doing relplot with kind='box'

### ISSUE THREAD

**Issue by whlinaa** [mwaskom/seaborn#2838]
version: 0.12.0a1
The following code will produce StopIteration error, but works fine in stable version (e.g., 0.11.2)

```python
import seaborn as sns
import pandas as pd
tips = sns.load_dataset('tips')
sns.catplot(data=tips, y='tip', kind='box') # error in version: 0.12.0a1, but ok in 0.11.2
```
btw, really thank you for your hard work in creating next gen seaborn! I can see this version has lots of potential! Really love your work!

**Comment by mwaskom** [comment]
Thanks fort testing out the alpha and for the reproducible bug report!
