### ISSUE TITLE
Seaborn objects log/symlog scales - default ticks

### ISSUE THREAD

**Issue by MaozGelbart** [mwaskom/seaborn#2840]
I experimented a little bit with the objects interface. My use case involves plotting large numbers using log/symlog scaled y-axis. I noticed that the default selection of tick locators/formatters in the objects interface differs from the corresponding (log/symlog) scale's matplotlib default. This is most prominent when dealing with large numbers. Consider the following code:
```python
import seaborn as sns; import seaborn.objects as so
import matplotlib.pyplot as plt

outfile_prefix="so"
diamonds = sns.load_dataset("diamonds")
diamonds["price"] = diamonds["price"] * 10**3

for scale in ["log", "symlog"]:
    fig, (ax1, ax2) = plt.subplots(1, 2)
    fig.suptitle(f"Scale={scale}")
    (
        so.Plot(
            diamonds, "carat", "price",
        )
        .on(ax2)
        .add(so.Scatter())    
        .scale(y=scale)
        .plot()
    )
    ax1.set_yscale(scale)
    sns.scatterplot(data=diamonds, x="carat", y="price", ax=ax1)
    ax1.set_title("Seaborn classic")
    ax2.set_title("Seaborn objects")
    savepath=f"{outfile_prefix}_diamonds_{scale}.png"
    plt.savefig(savepath, dpi=300)
```
The log-scaled plot uses a similar locator, but a different formatter:
![so_diamonds_log](https://user-images.githubusercontent.com/13831112/172336252-af5d38b2-63b4-4e30-90c4-0184070f5352.png)

While the symlog-scaled plot differ uses a different locator and a different formatter:
![so_diamonds_symlog](https://user-images.githubusercontent.com/13831112/172336461-83f632b5-39a9-4d42-836d-111f2f3c62c6.png)

Adding the following lines right after the plotting command restores the matplotlib default formatting:
```python
    from matplotlib.ticker import LogFormatterSciNotation, LogLocator, SymmetricalLogLocator
    ax2.yaxis.set_major_locator(SymmetricalLogLocator(base=10, linthresh=10) if scale=="symlog" else LogLocator(base=10))
    ax2.yaxis.set_major_formatter(LogFormatterSciNotation(base=10))
```
I could not find a straightforward way to change the formatting using the objects API (while I appreciate that `Scale` objects accept ticks input). To me, the default matplotlib selection of locators/formatters is the desired behavior. I suggest this should be the default behavior for the objects interface (when using log/symlog scales).

**Comment by mwaskom** [comment]
Hi @MaozGelbart nice to hear from you and thanks for testing out the alpha!

Yes, tick formatting (including defaults) is still a WIP. For configuration, the plan is to define a method similar to `Continuous.tick`. It's incomplete because this corner of the interface is very hard and I don't like working on it 😂.

Namewise, the possibilities are `Continuous.format` or `Continuous.label`. If we have, e.g. `scale.tick(every=..., between=...)` then it reads a little better to me to have e.g. `scale.label(base=10)` than `scale.format(base=10)`, but that's maybe idiosyncratic and I worry it's confusing to have `.label` consumer parameters whereas in matplotlib it tends to consume the labels themselves.

Anyway, TBD ... happy to hear any suggestions you have.

**Comment by MaozGelbart** [comment]
Hi @mwaskom, thanks! I'm still around, happy to see the new API in action and test it😃.
 
As for the API method, I noticed that `Continuous.format` method exists but it is not documented. Perhaps it is reserved for the tick formatting? If not `.label` may be selected to avoid confusion.

**Comment by mwaskom** [comment]
Thanks for feedback here, see #2877 

With your test cases:

![image](https://user-images.githubusercontent.com/315810/175823341-0c4661eb-5ba7-491d-b3a6-18bb6a3489c5.png)

![image](https://user-images.githubusercontent.com/315810/175823347-c5964fc2-85d2-4e82-81ad-008c5f3626cd.png)

Imagine I'll continue to tweak the customization API a little bit so feel free to weigh in with any thoughts there.
