### ISSUE TITLE
Adding mask as a argument within the seaborn heatmap

### ISSUE THREAD

**Issue by krishnaduttPanchagnula** [mwaskom/seaborn#2843]
### Feature improvement to heatmap in seaborm

![image](https://user-images.githubusercontent.com/84926220/172834417-a156aded-9794-48f7-96d2-7dcd61ab807b.png)

In the above image when we create a correlation, we get the same data twice. This causes bit confusion to the end-users.So usually we add a mask manually and pass it as a argument to mask parameter.

We can simplify this by modifying mask argument to be a boolean argument, which when given true will apply mask as given in the right diagram.

import seaborn as sns

matrix = data.corr()

sns.heatmap(matrix, mask =true) // the result will be the right diagram

**Comment by mwaskom** [comment]
Hi, thanks for the suggestion but I am :-1: on `mask=True` meaning "mask the upper triangle of a square matrix." It's too magical, and its proper behavior is undefined for other cases. You'd also naturally invite people saying "`mask=True` generates a lower-triangular matrix, but I want an upper triangular matrix".

In any case, this is straightforward to achieve as is:

```python
X = diamonds.iloc[:, 4:].corr()
sns.heatmap(X, mask=np.triu(X), square=True, center=0)
```
![image](https://user-images.githubusercontent.com/315810/172839082-3c9655aa-41a6-437f-94e9-281d3684d4fe.png)
