### ISSUE TITLE
fillstyle='none' in lineplot but legend is still filled

### ISSUE THREAD

**Issue by whlinaa** [mwaskom/seaborn#2852]
When plotting a `lineplot` with no filling for the markers (i.e., `fillstyle='none'`), the legend still has filled legend, although the markers are not filled in the figure. The following illustrates the problem:

```python
import seaborn as sns
tips = sns.load_dataset('tips')
ax = sns.lineplot(
                data=tips,
                x='size',
                y='tip',
                hue='sex',
                ci=None,
                style='sex',
                markers=True,
                fillstyle='none',
                markeredgecolor=None,
                markersize=10,
            )
```
![output_sns](https://user-images.githubusercontent.com/59403078/173210123-b15cc937-f90e-4a11-b22e-88c32f92d298.png)

**Comment by mwaskom** [comment]
Hi, generally speaking the legends that seaborn creates do not get passed the extra keyword dictionary; they are meant to represent only the features that directly map to data values. There are a couple issues about this I think; https://github.com/mwaskom/seaborn/issues/1763 comes to mind. It's not ideal, but quite difficult to change given the way things currently work in these functions.

Note that this _does_ work the way one probably expects in the objects interface:

```python
(
    Plot(tips, "size", "tip", color="sex", marker="sex", linestyle="sex")
    .add(Line(pointsize=10, fillcolor=(0, 0, 0, 0), edgewidth=1.5), Agg())
)
```
![image](https://user-images.githubusercontent.com/315810/173210651-0d3ba0d2-08bb-4af9-b970-9fc804255e79.png)

I think it's unlikely that anything will be done to remedy the situation with the current backend for these functions, but it should resolve once they're refactored to use the objects behind the scenes.

**Comment by whlinaa** [comment]
Really thank you for your explanation! Can't thank you enough for creating seaborn. It completely changed the way I worked. Looking forward to the next gen seaborn official release! Thank you for your hard work on it

**Comment by mwaskom** [comment]
Aggregating in #2861 and closing here.
