### ISSUE TITLE
kdeplot cmap legend no color

### ISSUE THREAD

**Issue by yihuajack** [mwaskom/seaborn#2857]
```
sns.kdeplot(x=casual_workday, y=registered_workday, cmap="Reds")
sns.kdeplot(x=casual_non_workday, y=registered_non_workday, cmap="Blues")
plt.legend(["Workday", "Non-Workday"])
```
or
```
sns.kdeplot(x=casual_workday, y=registered_workday, cmap="Reds", label="Workday")
sns.kdeplot(x=casual_non_workday, y=registered_non_workday, cmap="Blues", label="Non-Workday")
plt.legend()
```
![image](https://user-images.githubusercontent.com/23608500/173558693-f8cc7fe2-e4b8-45cc-b209-470c870a1044.png)
It turns out that the line color of the legend is none. However, the expected behavior is:
![image](https://user-images.githubusercontent.com/23608500/173558020-2b6e8c48-3111-47f4-89c3-84e89b61b789.png)
where the line color of the legend corresponds to the lightest line color of the plot.

**Comment by mwaskom** [comment]
Please ask usage questions on Stackoverflow; there are a number of questions there about how to customize legends. Thanks!
