### ISSUE TITLE
strange scatterplot 

### ISSUE THREAD

**Issue by iiiir** [mwaskom/seaborn#2874]
Hi,
Can you help me understand **why** the scatterplot look random if dataframe columns (at least one) were not converted to some type of vector? Both columns are "dtype: float64"

**incorrect plot**

`sns.scatterplot(data['purity'],data_trans["purity"])`
![image](https://user-images.githubusercontent.com/4137873/175312390-8bb2f9f2-1c91-4900-89a2-9656750f2c93.png)

**correct plot**

`sns.scatterplot(data['purity'],data_trans["purity"].to_list())`
or
`sns.scatterplot(data['purity'].to_numpy(),data_trans["purity"])`

![image](https://user-images.githubusercontent.com/4137873/175312689-174777cd-82c7-4402-b511-d4a983edb0ad.png)

Thanks!
Shuoguo

**Comment by mwaskom** [comment]
@iiiir please provide a reproducible example of your problem or else it's not possible to help.

**Comment by mwaskom** [comment]
Closing as non-reproducible; feel free to ping with a reproducible example.
