### ISSUE TITLE
`catplot` throws error when `data` arg not provided

### ISSUE THREAD

**Issue by davidgilbertson** [mwaskom/seaborn#2876]
With most sns plotting functions, I can pass Pandas series to `x` and `y` and it behaves as expected, but with `sns.catplot`, it errors.
```py
df = pd.DataFrame(
    {
        "Age": [40, 20, 20, 40, 50, 40],
        "Height": [143, 123, 189, 203, 187, 147],
    }
)

sns.relplot(x=df.Age, y=df.Height)  # This is OK
sns.swarmplot(x=df.Age, y=df.Height)  # This is OK
sns.catplot(x=df.Age, y=df.Height)  # This errors
```

Because `FacetGrid` is expecting `data`, so fails on this line: https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L349

The axes-level category charts (box, violin, etc) all work fine without the `data` arg, it's just `catplot` that fails.

(FWIW, the reason I do `x=df.Age` instead of strings is so I get auto-complete, type checking, it's one less arg to pass, and I can rename a feature and have it update everywhere, which doesn't always work with strings.)

**Comment by mwaskom** [comment]
Yes, this is known: https://seaborn.pydata.org/tutorial/data_structure.html

![image](https://user-images.githubusercontent.com/315810/175449997-b7055be0-09c1-4f6b-b461-659347241177.png)

**Comment by davidgilbertson** [comment]
Cool, thanks for the quick reply. I had read that, but clearly it didn't sink in :).

**Comment by mwaskom** [comment]
Closing as known issue, see #2429
