### ISSUE TITLE
Scatterplot y-axis inverts when column has None (object type)

### ISSUE THREAD

**Issue by loodvn** [mwaskom/seaborn#2883]
Similar to https://stackoverflow.com/q/65206970/10447904:

(searched through GH issues with terms "None y axis inverted" as well as throwing in a "None"/"object" term in there, before opening this issue)

The simplest reproducing example I could find was:
```python
df = pd.DataFrame({'x': [0.0, 0.0, 0.3], 'y': [0.0, None, 0.5]}, dtype='object')
sns.scatterplot(x='x', y='y', data=df)  # y-axis inverted
```
![sns.scatter y inverted](https://user-images.githubusercontent.com/13983198/176271810-597c2777-b2a6-4ee6-931f-e56d8f326bfc.png)
^y axis upside down

Comparing with plt.scatter (expected, no inverting of y-axis):
```python
plt.scatter(x=df['x'], y=df['y'])
```
![matplotlib expected](https://user-images.githubusercontent.com/13983198/176271946-bde8c259-98f2-481d-b0e9-f591c1c88673.png)

According to the stackoverflow post, the problem stems from the **y-axis containing Nones** (and of dtype `object`).
In my original dataframe, only y is of `dtype object` (because of the `None`s, I should have had it as `float64`), but for this reproducing example I had to cast both to `object` (in first line) to get it to work - I am confident I can find a reproducing example where x is `float64` and y `object` though if necessary.

Is this expected behaviour? Given that matplotlib doesn't flip the y axis.
In this case I forgot to cast my column to `float64` (or to use `np.nan`s) but I figured `None`s would be okay (/more or less equivalent) at the time :)

**Comment by mwaskom** [comment]
I think this is basically the same story as https://github.com/mwaskom/seaborn/issues/2686 (where the offending element was `pd.NA`, not `None`).

**Comment by mwaskom** [comment]
Closing as duplicate.
