### ISSUE TITLE
Overlap area between two distplots ?

### ISSUE THREAD

**Issue by Abhranta** [mwaskom/seaborn#2892]
Hey !!
I am trying to find the overlapping area between 2 distplots. I plotted these 2 plots using 2 lists and I want to find the overlapping area between them. How can i do that ??

**Comment by mwaskom** [comment]
Hi, this sounds like a good question for stackoverflow — make sure you put together a clear example of what you're trying to do (it's not possible to answer the question as you've posed it here).
