### ISSUE TITLE
Unexpected behaviour of ticks in next gen Seaborn

### ISSUE THREAD

**Issue by aeturrell** [mwaskom/seaborn#2908]
Hello,

Just found a potential bug in the next gen version of **seaborn**.

Expected behaviour: create a histogram with y-axis limits that go from 0 to 50.
Actual behaviour: limits of y-axis do not change.
Other possible reasons for this: I may be confused between the syntax for ticks and for axes limits here, but the ticks do not appear to change either.

Reprex:

```python

import pandas as pd
import seaborn.objects as so

diamonds = pd.read_csv(
    "https://github.com/mwaskom/seaborn-data/raw/master/diamonds.csv"
)
(
    so.Plot(diamonds, x="y")
    .add(so.Bar(), so.Hist(binwidth=0.5))
    .scale(y=so.Continuous(trans=None).tick(at=[0, 50]))
)
```

System info:
Python implementation: CPython
Python version       : 3.9.12
IPython version      : 8.3.0

Compiler    : Clang 12.0.1 
OS          : Darwin
Release     : 19.6.0
Machine     : x86_64
Processor   : i386
CPU cores   : 4
Architecture: 64bit

seaborn          : 0.12.0b1
matplotlib       : 3.5.2
matplotlib_inline: 0.1.3
sys              : 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:23:20) 
[Clang 12.0.1 ]
pandas           : 1.4.2

Thanks for all the work on this amazing package!

**Comment by mwaskom** [comment]
Hi @aeturrell thanks so much for providing feedback on the beta! This is indeed a bug; I believe it's the same basic issue as in #2885
