### ISSUE TITLE
Scale has no effect for Pair plots in next-gen interface

### ISSUE THREAD

**Issue by eringrant** [mwaskom/seaborn#2910]
The `objects` interface looks great, in particular the ability to have combination pair and facet plots. However, I ran into a bug when attempting to log-scale an axis for a `pair`ed plot with `seaborn==0.12.0b2`.

**Expected behavior** (no log-scaling where none applied):
```python
import seaborn as sns
import seaborn.objects as so
diamonds = sns.load_dataset("diamonds")

(
    so.Plot(
        diamonds, 
        x="carat", 
    )
    .pair(y=(
        "price", 
        "price", 
    ))
    .add(so.Scatter())
)
```
![image](https://user-images.githubusercontent.com/6835724/179394391-3d20b7e3-0b02-4b38-bae4-7ee0cb154f7e.png)

**Unexpected behavior** (no log-scaling even when calling `scale(y="log")`):

```python
import seaborn as sns
import seaborn.objects as so
diamonds = sns.load_dataset("diamonds")

(
    so.Plot(
        diamonds, 
        x="carat", 
    )
    .pair(y=(
        "price", 
        "price", 
    ))
    .scale(y="log")
    .add(so.Scatter())
)
```
![image](https://user-images.githubusercontent.com/6835724/179394381-897e9b5e-957a-4a52-b56d-7f953a4ece65.png)

**Expected behavior** (log-scaling works without `pair`ing):

```python
import seaborn as sns
import seaborn.objects as so
diamonds = sns.load_dataset("diamonds")

(
    so.Plot(
        diamonds, 
        x="carat", 
        y="price"
    )
    .scale(y="log")
    .add(so.Scatter())
)
```
![image](https://user-images.githubusercontent.com/6835724/179394515-ec87e88f-c11a-4f45-abbb-b377405ac0c7.png)

**Comment by mwaskom** [comment]
Hi @eringrant thank you so much for testing out the beta!

This might not be documented (yet), but individual variables in a paired plot can be scaled (and otherwise modified in `Plot.limit`, `Plot.label`, etc.) with `{var}{idx}`, i.e.:

```
(
    so.Plot(
        diamonds, 
        x="carat", 
    )
    .pair(y=(
        "price", 
        "price", 
    ))
    .add(so.Scatter())
    .scale(y1="log")
)
```

![image](https://user-images.githubusercontent.com/315810/179396942-abf68b37-a7c7-4a9e-9dcd-2721d7b48aef.png)

Then there's a separate question of "if there are multiple y axes, should doing `.scale(y="log")` set a log scale on _all_ of them?" I could imagine that being useful! Is that what you were expecting here?

**Comment by eringrant** [comment]
Thanks, @mwaskom—being able to independently scale the y-axes by indexing them in this way is great. I didn't see that in the documentation, but perhaps I missed it.

Yes, I'd expect `.scale(y="log")` to scale all the axes! (And for that to be incompatible with scaling them independently as `y1="log"`, etc.)

**Comment by beyarkay** [comment]
Chiming in to say I got confused by this behaviour as well, but the solution (`y1="log"`) works well for me
