### ISSUE TITLE
catplot not being display in streamlit based page

### ISSUE THREAD

**Issue by j-alex-vindel** [mwaskom/seaborn#2913]
I have been having an issue with sns.catplot. The graph is not plotted on my streamlit app it does not show however, the graph is plotted when I run the same line with the same data on my local computer. Is there a reason behind this? I already checked with streamlit support. I have tried with different sns plots and they run (are plotted) but for some reason sns.catplot is not

**Comment by mwaskom** [comment]
Hi, it's really impossible to provide any help without a reproducible example. Please read the [guidelines on making an actionable bug report](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs).

If you've already sought streamlit support, please also link to that conversation; my initial reaction would be "if it works without streamlit but doesn't work with streamlit, then it's a streamlit problem", so it would be helpful to have the context that brought you here.

**Comment by j-alex-vindel** [comment]
Hi! This is an example of the issue. I am including the data I am using. 
Here's the conversation I had with streamlit support
me:
> Hi, I have an issue, maybe you could share some light on it. I have a page with multiple containers on each container I want to graph some data. There are currently seven graphs and a table. When I try to plot one more the graph is not displayed. I am not sure if there's a limit on the number of graphs a single page can display. 

streamlit support:
>Is it the graph on line 37 that isn't appearing for you?

me:
>Yes, the graph on line 37

streamlit support:
> Thanks for clarifying. I've played around with the code and it seems to be an issue with the Seaborn catplot function, as I'm able to graph the same data with other Seaborn functions, and it looks like that graph that isn't appearing is your only usage of this function. I would recommend reaching out to Seaborn support to double check that the way you're using the catplot "boxen" graph is correct.
 Hope this helps  

[BAFA_By_team_2019.txt](https://github.com/mwaskom/seaborn/files/9140615/BAFA_By_team_2019.txt)
```
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


newmaster = pd.read_csv('BAFA_By_team_2019.txt',index_col=False)

col_a, col_b = st.columns([2,2])
with col_a:
    st.markdown('#### Boxplot')
    fig0 = plt.figure()
    sns.boxplot(x="Score", y="Division",
            data=newmaster)
    st.pyplot(fig0)
with col_b:
    st.markdown('#### Catplot')
    fig_score = plt.figure()

    sns.catplot(x="Score", y="Division", kind="boxen",
            data=newmaster)
    
    st.pyplot(fig_score)

col_c, col_d = st.columns([2,2])
with col_c:
    st.markdown('#### Stripplot')
    fig_strip = plt.figure()
    sns.stripplot(x="Score", y="Division", hue='Team_Status',
            data=newmaster)
    st.pyplot(fig_strip)

with col_d:
    st.markdown('#### Catplot')
    fig = plt.figure()
    sns.catplot(x="Score", y="Division", hue='Team_Status',col='Game_Status', 
        data=newmaster)
    st.pyplot(fig)
```
Since then I tried to include different sns graphs and they are plotted just the catplot for some reason is not. Even in my main project where I have several graphs they all display. 

[Here](https://j-alex-vindel-bafa-2019-app-hello-t0nfj1.streamlitapp.com/Findings) is the link to my main project as well

**Comment by mwaskom** [comment]
Thanks, I think this section of the docs should answer your question: https://seaborn.pydata.org/tutorial/function_overview.html#figure-level-vs-axes-level-functions

**Comment by mwaskom** [comment]
Closing as expected behavior. Hopefully the docs make this clear but the solution is to do

```python

    grid_score = sns.catplot(x="Score", y="Division", kind="boxen", data=newmaster)
    st.pyplot(grid_score.figure)
```

Or use `boxenplot` instead. I would probably try to consistently use either the axes-level or figure-level interface within a single app.
