### ISSUE TITLE
facetgrid: when hue value doesn't appear in all graphs the legend appears to be misannotated

### ISSUE THREAD

**Issue by bengroves** [mwaskom/seaborn#2916]
**Problem:**
The same color is assigned to two different values in the legend.

**The code to reproduce:**

```
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt


sna = pd.DataFrame(
    {
        'x' : np.tile(range(10), 5), 
        'y' : list(range(10)) + list(range(2,12)) + list(range(4, 14)) + list(range(6, 16)) + list(range(8, 18)),
        'id_for_hue' : ['foo']*10 + ['bar']*10 + ['baz']*10 + ['bar']*10 + ['baz']*10,
        'id_for_graph' : ['a']*30 + ['b']*20
    }                                
)

g = sns.FacetGrid(sna, col='id_for_graph')
g.map_dataframe(
    sns.lineplot,
    x = 'x',
    y = 'y',
    hue = 'id_for_hue'
)

g.add_legend()
```

**Output in jupyterlab:**
![image](https://user-images.githubusercontent.com/30849701/180108642-fe9c6345-c8d1-4cf6-a173-e37aada57984.png)

**Versions:**
seaborn: 0.11.2
matplotlib: 3.5.2
pandas: 1.3.4
numpy: 1.21.6
python: 3.7.6

Thanks for taking a look!

**Comment by bengroves** [comment]
on the other hand, if we sort so that the values that appear in the second plot appear at the top of the dataframe, the problem is resolved.
```
g = sns.FacetGrid(sna.sort_values(['id_for_hue']), col='id_for_graph')
g.map_dataframe(
    sns.lineplot,
    x = 'x',
    y = 'y',
    hue = 'id_for_hue'
)

g.add_legend()
```
![image](https://user-images.githubusercontent.com/30849701/180110906-9f8ab9d3-30ba-42ed-9295-84ecf7a7b803.png)

**Comment by bengroves** [comment]
maybe unsurprisingly, I should have read the documentation more closely. As mentioned in the lineplot documentation "Using [relplot()](https://seaborn.pydata.org/generated/seaborn.relplot.html#seaborn.relplot) is safer than using [FacetGrid](https://seaborn.pydata.org/generated/seaborn.FacetGrid.html#seaborn.FacetGrid) directly, as it ensures synchronization of the semantic mappings across facets"

I'll close the issue.

**Comment by mwaskom** [comment]
This is a super clear bug report but I am glad you able to unblock yourself. The situation is not ideal, but yes this is exactly the kind of situation that the warning in the FacetGrid docstring is about:

![image](https://user-images.githubusercontent.com/315810/180330287-a2c33e44-1164-4c01-a093-da397b28090b.png)

`relplot` is the recommended approach here; if you really needed to make your plot by initializing the facet grid (and couldn't just tweak the object that `relplot` returns), you would have a few options:

- set a categorical dtype on your `hue` variable
- pass `hue_order` to `lineplot
- pass a dict of colors to `palette`

**Comment by bengroves** [comment]
No worries and thanks for getting back to me, @mwaskom. The additional information is helpful.
