### ISSUE TITLE
map_offdiag custom func

### ISSUE THREAD

**Issue by NousMei** [mwaskom/seaborn#2918]
Hi, I want to annotate the linear regression equation in PairGrid (I mean `g.map_offdiag(sns.regplot)`). I tried to create a function by referring to [this link](https://stackoverflow.com/questions/45902739/seaborn-annotate-the-linear-regression-equation), but failed : (

I would be grateful if someone could help me😀

```
x_vars = ["A", "B", "C", "D", "E", "F"]
y_vars = ["C", "D", "F"]
g = sns.PairGrid(data=df, x_vars=x_vars, y_vars=y_vars)
g.map_diag(sns.histplot, color=".3")
g.map_offdiag(sns.regplot)
g.add_legend()
```
![image](https://user-images.githubusercontent.com/84954535/180586273-f81eabf6-af78-4294-9126-9760584e0065.png)

**Comment by mwaskom** [comment]
Hi, please ask usage questions on StackOverflow, where you will likely get a faster response. In this case I expect your question might be already answered here: https://stackoverflow.com/questions/66893103/pairgrid-use-upper-triangle-for-correlations-access-full-data

**Comment by NousMei** [comment]
Many thanks.
