### ISSUE TITLE
scipy links in documentation are broken

### ISSUE THREAD

**Issue by joha1** [mwaskom/seaborn#2923]
I have been looking into the documentation for [`seaborn.clustermap`](https://seaborn.pydata.org/generated/seaborn.clustermap.html#seaborn.clustermap) since I need to understand some details of that, and it appears that the links to the underlying scipy methods are broken. I can't find the documentation here on github, so I'm reporting it as a general issue.

https://docs.scipy.org/doc/scipy/reference/reference/generated/scipy.cluster.hierarchy.linkage.html#scipy.cluster.hierarchy.linkage  (and the other link to scipy) fails with a 404. 

https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html#scipy.cluster.hierarchy.linkage works. It appears that `reference` got doubled in the original links! According to a quick google, only [`kdeplot`](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) has such a scipy reference too, and that too is broken in the same way (`/reference/reference/` instead of a single `/reference/`).

**Comment by mwaskom** [comment]
Thanks for reporting. This works for me in a build of the development docs, so I gather this has been fixed on one side or the other.

**Comment by MaozGelbart** [comment]
Hi, commit eff82127670233e97f4fd04139f32bff3d07395b resolved the scipy intersphinx change.

**Comment by mwaskom** [comment]
Thanks @MaozGelbart!
