### ISSUE TITLE
next gen usage question

### ISSUE THREAD

**Issue by bdch1234** [mwaskom/seaborn#2924]
How can I plot all (or a subset of) the columns of a pandas dataframe, using the index as x-axis, with the new object-based interface?

**Comment by mwaskom** [comment]
Hi, I’m not sure I understand the question, can you make it more concrete with an actual example (maybe how you’d currently do it with seaborn/meatplotlib?)

**Comment by bdch1234** [comment]
So if DF is a pandas dataframe with index dates, and has two variables x and y with random data. Then I'm looking for the equivalent of 

```python
import seaborn as sns

sns.lineplot(data=DF)
```

which would plot two lines, x and y, and x-axis would show the dates.

I realize that old API will still be available, but I wan't to integrate the new API to an existing codebase. This will also enable very nice things such as finding best plot sizes by iteration of .configure(...) and so on.

On the topic of sizing btw, I was also wondering if the new API and its integrated jupyter rendering will be equipped with interactive features such as those in ipympl at some point? Or will that only be possible when actually drawing the charts with pyplot?

**Comment by mwaskom** [comment]
Ah, got it. In seaborn parlance this would be ["wide-form data"](https://seaborn.pydata.org/tutorial/data_structure.html#long-form-vs-wide-form-data).  It's not currently supported in the new interface. This text from that page gives some idea why:

> The absence of explicit variable assignments also means that each plot type needs to define a fixed mapping between the dimensions of the wide-form data and the roles in the plot. Because the natural mapping may vary across plot types, the results are less predictable when using wide-form data.

With the type-specific functions, you can know how to map the dataframe structure to plot variables before you need to do it. But that's not the case with the objects interface, where there is a cleaner separation between the data pipeline and the mark types.

Wide-form data can be convenient so maybe there will be some way to support it in the future, but for now, not doing so makes everything substantially simpler.

> I was also wondering if the new API and its integrated jupyter rendering will be equipped with interactive features such as those in ipympl at some point? Or will that only be possible when actually drawing the charts with pyplot?

I'm not sure I understand this way of articulating the question since `ipympl` _is_ (a backend for) `pyplot`. I can never keep it reliably working on my machine and it isn't right now, but I think if you do `Plot().show()` with that backend enabled you should get an interactive figure embedded in the notebook?

**Comment by bdch1234** [comment]
> Ah, got it. In seaborn parlance this would be ["wide-form data"](https://seaborn.pydata.org/tutorial/data_structure.html#long-form-vs-wide-form-data). It's not currently supported in the new interface. This text from that page gives some idea why:
> 
> > The absence of explicit variable assignments also means that each plot type needs to define a fixed mapping between the dimensions of the wide-form data and the roles in the plot. Because the natural mapping may vary across plot types, the results are less predictable when using wide-form data.
> 
> With the type-specific functions, you can know how to map the dataframe structure to plot variables before you need to do it. But that's not the case with the objects interface, where there is a cleaner separation between the data pipeline and the mark types.
> 
> Wide-form data can be convenient so maybe there will be some way to support it in the future, but for now, not doing so makes everything substantially simpler.

Understood, thanks for clarifying.

> > I was also wondering if the new API and its integrated jupyter rendering will be equipped with interactive features such as those in ipympl at some point? Or will that only be possible when actually drawing the charts with pyplot?
> 
> I'm not sure I understand this way of articulating the question since `ipympl` _is_ (a backend for) `pyplot`. I can never keep it reliably working on my machine and it isn't right now, but I think if you do `Plot().show()` with that backend enabled you should get an interactive figure embedded in the notebook?

Sorry, reading my question again I agree that I was not very clear. What I meant to ask was basically if there at some point will be interactive features embedded in the renderings coming from the new API, similar to those found in ipympl?

Reason for asking is that I think the new way of showing plots is super nice, and I would love to not have to fall back to pyplot/ipympl when there is a need for interactivity in the plot.

**Comment by mwaskom** [comment]
> What I meant to ask was basically if there at some point will be interactive features embedded in the renderings coming from the new API, similar to those found in ipympl?

At the moment, the jupyter integration is just "render a static png and display it". Interactivity will always require some kind of runtime, and pyplot is very likely to remain the best or most fully-featured option.

That said I agree that thinking of Plot display in terms of creating a web element (or at least a jupyter widget) does open up the space of possibilities. I think there will be some potential for lightweight interactivity, e.g. render svg with a little javascript to do hover popups. It will be interesting to see how PyScript develops and whether it makes that easier. It's also theoretically possible to translate (simple, at least) plot specs into vegalite, which presents another option for interactive display (though a more radical one, and one that is unlikely to provide a fully consistent user experience).

This is definitely an interesting space to ideate in, but all a bit down the road from getting the basic set of functionality released.

**Comment by bdch1234** [comment]
Got it. Well in any case thanks for making a fantastic plotting package, and looking forward to follow the development of the new api!
