### ISSUE TITLE
documentation is not reachable

### ISSUE THREAD

**Issue by dryguz** [mwaskom/seaborn#2937]
"NET::ERR_CERT_COMMON_NAME_INVALID"

**Comment by mwaskom** [comment]
What page are you trying to access? http://seaborn.pydata.org/ works for me.

**Comment by BenGale93** [comment]
If you google "seaborn" the top link is https://seaborn.pydata.org/ and doesn't work for me either.

**Comment by mwaskom** [comment]
Thanks for flagging ... I don't control the DNS and am not sure what happened exactly, but github pages' debugging info suggested removing and then re-adding the CNMAE file to pick up DNS config changes, which seemed to work. I can see the https version of the site now.

**Comment by mwaskom** [comment]
Closing as I believe this is resolved but ping if that is not the case on your end. Thanks again for the heads up.
