### ISSUE TITLE
Feature Req: Face heatmap

### ISSUE THREAD

**Issue by rushic24** [mwaskom/seaborn#2938]
Hello,
I was recently working on face verification and I wanted something like a correlation matrix for faces. I couldn't find any, so I made a script for that. I think this will be useful for others so I was wondering if I could add it here in seaborn under heatmap ?
We do have sns.heatmap, but that doesn't take images as name/labels. 

This is how it looks.
![image](https://user-images.githubusercontent.com/6279035/183140485-54f9babc-ecd2-42b5-8932-8e1e286cca72.png)

**Comment by mwaskom** [comment]
Hi, thanks for the suggestion but I think this is a bit outside the core focus of seaborn. It's unlikely that I'd add any new plot types that don't consume tidy tabular data. I also don't think there's any particular reason such a utility would need to be in seaborn to work well; aside from using a seaborn colormap, this wouldn't appear to depend on anything in seaborn. So I'd encourage you to develop it as a standalone library and add it to matploltib's third-party tooling docs.
