### ISSUE TITLE
Regression: `pointplot` and `barplot` raise when using a custom estimator

### ISSUE THREAD

**Issue by MaozGelbart** [mwaskom/seaborn#2943]
This may be related to #2866 . According to `pointplot` (and `barplot`) documentation, the `estimator` can be any callable that maps vector to scalar. However, the following example raises with `'0.12.0.dev0'` on my Windows and Mac machines (and doesn't raise with `'0.11.2'`):
```python
import seaborn as sns
import numpy as np
tips = sns.load_dataset("tips")

def custom_min(x):
    return float(np.asarray(x).min())

ax = sns.pointplot(x="day", y="tip", data=tips, estimator=custom_min)
```

<details><summary>Exception</summary>

```
C:\Users\admin\seaborn\seaborn\categorical.py:1491: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self.statistic = np.array(statistic)
Traceback (most recent call last):
  File "C:\Users\admin\miniconda3\lib\site-packages\pandas\core\series.py", line 191, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'float'>
```

</details>

It does work, however, when changing the `custom_min` function to use the builtin `min` func:
```python
import seaborn as sns
import numpy as np
tips = sns.load_dataset("tips")

def custom_min(x):
    return float(min(x))

ax = sns.pointplot(x="day", y="tip", data=tips, estimator=custom_min)
```

The same error is raised when changing the example code to use `barplot`, or when using a different numpy aggregator within the custom function.

**Comment by mwaskom** [comment]
Thanks for reporting, I can reproduce. This is a weird one!

**Comment by mwaskom** [comment]
I think this is the fundamental issue, and I do not understand what pandas as doing here:

```python
def custom_min(x):
    return np.asarray(x).min()
tips["tip"].agg(custom_min)
```
```
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64
```

**Comment by mwaskom** [comment]
OK I think I kind of understand, but also wtf. I gather that `Series.agg(f)` first tries `Series.apply(f)`. That passes numbers into the function so, if you're calling a numeric method, it fails. But `np.asarray(x).min()` where x is a scalar will produce a 0-dimensional array and then call `.min()` on it, which is valid. So `.agg` doesn't actually reduce, which then blows up downstream.

Argh.

**Comment by MaozGelbart** [comment]
I think we ran into https://github.com/pandas-dev/pandas/issues/46581 , as seaborn does `Series.agg` here: https://github.com/mwaskom/seaborn/blob/9771eae42a802f898f95c6b062f036bd7940e6b4/seaborn/_statistics.py#L481
This explains the change from 0.11.2 which was calling the estimator with the series as input:
https://github.com/mwaskom/seaborn/blob/10fc8d74e7686ead56e6f621413926114d470daa/seaborn/categorical.py#L1520

**Comment by mwaskom** [comment]
Yep the intention of that change was to support `estimator: str` in a clean way. I guess we can change it to something like

```python
if callable(self.estimator):
    estimate = self.estimator(vals)
else:
    estimate = vals.agg(self.estimator)
```
