### ISSUE TITLE
Pre-commit hook for flake8 and mypy?

### ISSUE THREAD

**Issue by stefmolin** [mwaskom/seaborn#2950]
I noticed that there isn't a pre-commit hook set up for the repo. Rather than manually running flake8 and mypy on the code before committing, have you considered using a pre-commit hook so you only commit what will pass linting checks?  It's quite easy to set up &ndash; I'd be happy to provide a config file for the setup and update any contributor docs if you are interested in incorporating this.

**Comment by mwaskom** [comment]
I've had some mildly annoying experiences with pre-commit in my day job (it's no fun to be blocked on committing something because your pre-commit is out of date, whereas I've never once found myself asking what version of make I had locally), but probably wouldn't be opposed for this limited set of checks.

**Comment by mwaskom** [comment]
If adding any more development utilities, I'd probably want to set up a `seaborn[dev]` extra in `pyproject.toml` to simplify environment setup.

**Comment by stefmolin** [comment]
I was thinking of a lightweight setup: add a `.pre-commit-config.yaml` file to the repo and then people who want to use it can `pip install pre-commit` and `pre-commit install` to get set up. The config for the individual checks is already in `setup.cfg`, and there's always the option to tack on `--no-verify` to skip the checks. This would give people the option to use [pre-commit](https://pre-commit.com/) or `make` as they see fit.

**Comment by mwaskom** [comment]
Sounds cool, feel free to put up a PR.

**Comment by stefmolin** [comment]
Great &ndash; I'll work on it this week.

**Comment by mwaskom** [comment]
Closed with #2963
