### ISSUE TITLE
Logo doesn't change for darkmode in the nextgen docs

### ISSUE THREAD

**Issue by beyarkay** [mwaskom/seaborn#2957]
Darkmode in the nextgen docs looks amazing. Thanks! But I noticed that the seaborn logo doesn't contrast as nicely against the dark background as it does against the light background. Probably a bug?:
<img width="225" alt="Screenshot 2022-08-15 at 12 49 10" src="https://user-images.githubusercontent.com/33420535/184622679-f488cc40-7263-4a6d-a0a0-a4a6af376f6c.png">

<img width="204" alt="Screenshot 2022-08-15 at 12 50 39" src="https://user-images.githubusercontent.com/33420535/184622851-6fb55023-dd2e-46f3-b5a8-092b9765c9c8.png">

**Comment by mwaskom** [comment]
The nextgen demo site is built with a very minimal configuration, this content will get folded into the main docs before release.
