### ISSUE TITLE
Controlling hue order in 'ridge plot'?

### ISSUE THREAD

**Issue by KunFang93** [mwaskom/seaborn#2962]
Hi,

Thanks for providing this wonderful tool! I wondered how I can control the order when plot ridge-plot?
I adapted code from tutorial but the hue_order seems not work here.
```
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="white", rc={"axes.facecolor": (0, 0, 0, 0)})

# Create the data
rs = np.random.RandomState(1979)
x = rs.randn(500)
g = np.tile(list("ABCDEFGHIJ"), 50)
df = pd.DataFrame(dict(x=x, g=g))
m = df.g.map(ord)
df["x"] += m

# Initialize the FacetGrid object
pal = sns.cubehelix_palette(10, rot=-.25, light=.7)
g = sns.FacetGrid(df, row="g", hue="g", hue_order=['B','A','D','C','E','F','G','J','H','I'],
                                aspect=15, height=.5, palette=pal)

# Draw the densities in a few steps
g.map(sns.kdeplot, "x",
      bw_adjust=.5, clip_on=False,
      fill=True, alpha=1, linewidth=1.5)
g.map(sns.kdeplot, "x", clip_on=False, color="w", lw=2, bw_adjust=.5)

# passing color=None to refline() uses the hue mapping
g.refline(y=0, linewidth=2, linestyle="-", color=None, clip_on=False)


# Define and use a simple function to label the plot in axes coordinates
def label(x, color, label):
    ax = plt.gca()
    ax.text(0, .2, label, fontweight="bold", color=color,
            ha="left", va="center", transform=ax.transAxes)


g.map(label, "x")

# Set the subplots to overlap
g.figure.subplots_adjust(hspace=-.25)

# Remove axes details that don't play well with overlap
g.set_titles("")
g.set(yticks=[], ylabel="")
g.despine(bottom=True, left=True)
```
Thanks in advance!

Kun

**Comment by mwaskom** [comment]
Hi, this may be a better question for stackoverflow. But you'd want to specify what you mean by "does not seem to work". When I copy-paste your code, the hue gradient matches the requested `hue_order` (i.e., `B` is the lightest category and `I` is the darkest).

I'm going to close as this is a usage question not a bug report.

**Comment by jhncls** [comment]
Hi, Kun.

This is how the plot looks (on my PC):

![image](https://user-images.githubusercontent.com/19649483/185763233-7f0cf97b-5cd9-4c61-a495-0eb176f9d365.png)

The hue_order only controls in which order the colors are applied. So, `B` gets the first (lightest) color, `A` the next one, then `D`etc.  If I guess correctly, you want to change the order of the rows.  To achieve that, you can use the `row_order` of the `FacetGrid`.  Alternatively, you can force an ordering on the `g` column via `df["g"] = pd.Categorical(df["g"], categories=['B', 'A', 'D', 'C', 'E', 'F', 'G', 'J', 'H', 'I'])`.

**Comment by KunFang93** [comment]
> Hi, Kun.
> 
> This is how the plot looks (on my PC):
> 
> ![image](https://user-images.githubusercontent.com/19649483/185763233-7f0cf97b-5cd9-4c61-a495-0eb176f9d365.png)
> 
> The hue_order only controls in which order the colors are applied. So, `B` gets the first (lightest) color, `A` the next one, then `D`etc. If I guess correctly, you want to change the order of the rows. To achieve that, you can use the `row_order` of the `FacetGrid`. Alternatively, you can force an ordering on the `g` column via `df["g"] = pd.Categorical(df["g"], categories=['B', 'A', 'D', 'C', 'E', 'F', 'G', 'J', 'H', 'I'])`.

Thanks for your detailed explanation! Yes, I would like to change the order of the rows. And it works with row_order parameters!

**Comment by KunFang93** [comment]
> Hi, this may be a better question for stackoverflow. But you'd want to specify what you mean by "does not seem to work". When I copy-paste your code, the hue gradient matches the requested `hue_order` (i.e., `B` is the lightest category and `I` is the darkest).
> 
> I'm going to close as this is a usage question not a bug report.

Got it, thanks for your reply!
