### ISSUE TITLE
How to rotate the xticks label in the next-generation seaborn interface?

### ISSUE THREAD

**Issue by liuzj039** [mwaskom/seaborn#2977]
The new generation of interfaces largely reduces the need to manipulate figure at the matplotlib level.
But I'm not sure how I should do about rotating the ticks labels.

For example:
```python
import seaborn.objects as so
from seaborn import load_dataset
tips = load_dataset("tips")
so.Plot(tips, x="total_bill", y="tip").add(so.Dots()).theme(sns.axes_style('ticks'))
```
![image](https://user-images.githubusercontent.com/55271666/186811547-93d6a859-d7a1-4809-a283-4f9adb8da829.png)

Expected:
```python
ax = plt.gca()
so.Plot(tips, x="total_bill", y="tip").add(so.Dots()).on(ax).plot()
plt.xticks(rotation=-30, ha='left')
plt.show()
```
![image](https://user-images.githubusercontent.com/55271666/186812630-ed308d1d-60d9-49ef-b508-b8cefaf018cd.png)

Maybe [tweak](https://github.com/mwaskom/seaborn/issues/2927#issue-1323308491) can accomplish this thing?
Besides, will you consider adding box plot, violin plot, heat map, cluster map in the new interface?

Thanks again to the developers for the convenience of seaborn.

**Comment by liuzj039** [comment]
Also, is there a convenient way to control legend?
I am using the following method to control the legend, but this method can only modify the first legend (for example, when both color and pointsize are specified, only the color legend can be controlled), and cannot modify ncol.

```python
g = (so.Plot(...))
fig = g.plot()._figure
leg = fig.legends[0]
leg.set(...)
```

**Comment by mwaskom** [comment]
Hi, no dedicated API yet for either task and it doesn't look like these can be controlled by matplotlib rcparams (a little surprisingly). I definitely expect legend control to improve over time and it will probably be possible to control ticklabel properties down to the orientation (although, personally, I generally think that rotated tick labels are ugly and make a plot hard to read).

To answer the other question, yes, you should expect additional marks to be introduced in future releases, although there may not be 100% parity with the function interface (e.g. I don't expect to implement clustermap through objects).

**Comment by liuzj039** [comment]
Very much looking forward to the subsequent updates. The new interface is really amazing.
