### ISSUE TITLE
swarmplot change point maximum displacement from center

### ISSUE THREAD

**Issue by ohickl** [mwaskom/seaborn#2986]
Hi,
I am trying to plot a `violinplot` + `swarmplot` combination for with multiple hues and many points and am struggling to get the optimal clarity with as few points as possible overlapping. I tried both `swarmplot` and `stripplot`, with and without `dodge`.
Since i have multiple categories on  the y-axis , I have also played around with the figure size, setting it to large height values. It helps to improve the clarity of the violin plots but the swarm/strip plots remain unchanged and crowded with massive overlap. I know that there will always be overlap with many points sharing the same/similar x-values, but i would like to maximize the use of space available between y-values for the swarms. Is there a way i can increase the maximum displacement from center for the swarm plots? With the `stripplot` `jitter` i can disperese the point, but they tend to overlap randomly quite a bit still and also start to move over into other violin plots.

Tried with Seaborn versions: `0.11.2` and `0.12.0rc0 `

I attached a partial plot, as the original is quite large:
```
...
sns.set_theme()
sns.set(rc={"figure.figsize": (6, 18)})

...

PROPS = {'boxprops': {'edgecolor': 'black'}, 
         'medianprops': {'color': 'black'},
         'whiskerprops': {'color': 'black'},
         'capprops': {'color': 'black'}}

ax = sns.violinplot(x=stat2show, y=y_cat, data=data_df, width=1.7, fliersize=0,
                    linewidth=0.75, order=y_order, palette=qual_colors,
                    scale="count", inner="quartile", **PROPS)

sns.swarmplot(x=stat2show, y=y_cat, data=data_df, size=5.2, color='white',
              linewidth=0.5, hue="Data Set", edgecolor='black',
              palette=data_set_palette, order=y_order, dodge=False,
              hue_order=data_set_hue_order)
...
```
![violin_swarm_sns_part](https://user-images.githubusercontent.com/49027995/187406077-46db0cd8-7ebc-4758-bf94-3a5523b0a952.png)

Thanks for any help!

**Comment by mwaskom** [comment]
No, sorry, the swarms are prevented from extending outside of their "zone" and that is not a parameter. But you could reduce the size of the dots to reduce overlap.

**Comment by ohickl** [comment]
Ok, thanks for the swift reply!

Could that be a parameter in the future? I tried reducing the point size but at the size where there's no/little overlap the hues become too hard to properly identify.
Is there a way to access the points and try to redistribute them manually?

**Comment by mwaskom** [comment]
I think probably not, the algorithm is already pretty complicated. Swarm plot is a pretty specialized plot type and it might not work in all cases — that's ok.

**Comment by ohickl** [comment]
Understandable.
