### ISSUE TITLE
Fix documentation of size parameter in catplot / stripplot

### ISSUE THREAD

**Issue by e-pet** [mwaskom/seaborn#3007]
To control marker size in a catplot with `kind="strip"`, one needs to pass `s=...` instead of `size=...` (as one would expect based on the stripplot documentation). This is currently not apparent from the documentation of catplot. (Also see [this SO issue](https://stackoverflow.com/questions/58548261/how-to-change-marker-size-in-seaborn-catplot).)

**Comment by mwaskom** [comment]
`size=` works in `catplot` for me, probably as of v0.12.0:

```python
sns.catplot(tips, x="day", y="tip", size=20, alpha=.2)
```
![image](https://user-images.githubusercontent.com/315810/189490551-115eff37-a268-40e5-aa23-122d0c493dab.png)

**Comment by e-pet** [comment]
Indeed, sorry for the unnecessary issue and great that this works now! :-)
