### ISSUE TITLE
Seaborn Objects: Horizontal line

### ISSUE THREAD

**Issue by JanPalasek** [mwaskom/seaborn#3008]
Hello.

Firstly, thanks for the addition of seaborn objects. It seems really powerful and easy to use. Awesome!

Secondly, I'd like to ask, whether a functionality is available in the new API. I'd like to draw a horizontal line together with a line derived from data.

For example:

```python
import seaborn.objects as so
from datetime import datetime
import pandas as pd

data = pd.DataFrame({
    "date": [datetime(2018, 1, 1), datetime(2018, 2, 1), datetime(2018, 3, 1)],
    "count": [250, 130, 300]
})

(
    so.Plot(data=data, x="date", y="count")
    .add(so.Line())
    .add(so.Line(color="grey"), so.Agg())
)

```

I'd like the second so.Line() to draw a horizontal line that is made out of mean of all values in "count" column. It however averages over automatic groups from "date" column.
This functionality (if it isn't possible already) would be very useful in time-related data, where you would e.g. like to display a yearly average.

It would generally be useful to draw any constant horizontal (or vertical line). Currently the best option that occurs to me is to switch to matplotlib's axhline.

**Comment by mwaskom** [comment]
I do plan to add a `Rule` mark but it hasn't happened yet. In the meantime, a little clumsy, but something like this might do?

```python
(
    so.Plot(data=data, x="date", y="count")
    .add(so.Line(), x=[data["date"].min(), data["date"].max()], y=150, data={})
    .add(so.Line(color="grey"), so.Agg())
)
```
![image](https://user-images.githubusercontent.com/315810/189542891-c8f02716-77ab-4eef-be2e-59e82ec544e4.png)

**Comment by JanPalasek** [comment]
Thanks for the response. I think that covers it! Much more "seaborn objects-like" than switching to "axhline".

**Comment by mwaskom** [comment]
Great. I'm going to close this issue as this is definitely on the roadmap (which unfortunately is not a public document at the moment). Slightly TBD on what to expect but I think it will look something like this:

```python
(
    so.Plot(data=data, x="date", y="count")
    .add(so.Rule(y=200))
    .add(so.Line())
)
```

The part I haven't quite figured out yet is how to support, e.g., "draw a horizontal line at the average y value across all x values" which I expect is something you'd want. At the moment `so.Agg()` always groups within levels of the orient variable, and I'm not certain how best to make that optional.

**Comment by JanPalasek** [comment]
Maybe “by” parameter for Agg class? And possible also “level”, for aggregating over index. This is an API that pandas use.
If by or level would be specified, then orient could be ignored for this aggregation.

Just a suggestion what would be okay for me. I don’t have your knowledge of the internals though.

**Comment by mwaskom** [comment]
The problem with `by` is that the operation you want is "drop {orient} from the groupers", otherwise to drop the grouping variable from a more complex plot, you'd have to do

```python
so.Plot(data, x=..., y=..., color=..., linewidth=...)
.add(so.Rule(), so.Agg(by=["color", "linewidth"]))
```

which is kind of annoying. And it doesn't really make sense to otherwise choose whether to group by the semantic variable (color, etc.) since you can already drop them by passing `None` in the layer definition.
