### ISSUE TITLE
pairplot example broken?

### ISSUE THREAD

**Issue by polishhammer9** [mwaskom/seaborn#301]
The pairplot example doesn't seem to be working (nor do any other pairplot tests I try). The subplots are all blank. I'm using seaborn v 0.4.0, matplotlib 1.3.1rc2, scipy 0.13.0b1, pandas 0.14.1 and python win64 2.7.5

**Comment by stared** [comment]
@mwaskom Is it possible to open this issue?

**Comment by thoppe** [comment]
@stared I also had this issue, thanks for solution. @mwaskom it would be nice if this was in the requirements.

**Comment by mazurkin** [comment]
Had the same issue. Unfortunately matplotlib 1.3 is default version on Ubuntu 14.04
