### ISSUE TITLE
Objects do not respect `sns.set_style`

### ISSUE THREAD

**Issue by dangom** [mwaskom/seaborn#3017]
Currently, so.Plot() does not respect sns.set_style.

To set a style manually, one can use `.theme({**matplotlib.style.library["seaborn-white"]})`, but is there an alternative way to set the style globally?

Also, thanks for all the effort in this project.

**Comment by mwaskom** [comment]
Please see #3002.

**Comment by mwaskom** [comment]
p.s. if you have seaborn installed prefer using seaborn's style functions over the stylesheets that matplotlib ships, which are outdated and have some problems.
