### ISSUE TITLE
Can we get error bar statistics?

### ISSUE THREAD

**Issue by HelloTanyaTang** [mwaskom/seaborn#3021]
Hi - Did some search but no luck. Is there anyway to retrieve the statistics of the plots, such as mean, error bar lower bound, error bar upper bound from seaborn.relplot on aggregated data? 

for example, [this](https://seaborn.pydata.org/tutorial/relational.html#aggregation-and-representing-uncertainty) plot

```
fmri = sns.load_dataset("fmri")
sns.relplot(data=fmri, x="timepoint", y="signal", kind="line")
```

**Comment by mwaskom** [comment]
http://seaborn.pydata.org/faq.html#can-i-access-the-results-of-seaborn-s-statistical-transformations
