### ISSUE TITLE
Boxplot Bug

### ISSUE THREAD

**Issue by tac628** [mwaskom/seaborn#3025]
Hi
The issue happens when use sns.boxplot for quartiles. In terms of the quartile Wikipedia with links (https://en.wikipedia.org/wiki/Quartile), Q1, Q2(median), and Q3 are all mean but in the different subsets. If that is the case, in the list containing elements - -6,-3,1,4,5,8, Q1 is -3, median for 2.5, and Q3 for 5. However, when running the method, sns.boxplot, I find Q1 shows at the edge of the blue box is -2. Hence, I think this is bug. 

In order to facilitate your inquiry, I paste both source code and plot, which are shown below.
![image](https://user-images.githubusercontent.com/88801972/190229474-0cdd96db-5cbb-4f0f-9276-928fce6b90f7.png)
![image](https://user-images.githubusercontent.com/88801972/190229537-2b278fa2-aba7-4e41-b3be-196a3f4826c5.png)

**Comment by mwaskom** [comment]
Your issue is with numpy:

```python
np.percentile([-6, -3, 1, 4, 5, 8], [0, 25, 50, 75, 100])
```
```
array([-6.  , -2.  ,  2.5 ,  4.75,  8.  ])
```

As the wikipedia page you link says,

> For discrete distributions, there is no universal agreement on selecting the quartile values

So I don't think this is a bug.
