### ISSUE TITLE
rectangular cells of heatmap

### ISSUE THREAD

**Issue by zjq1011** [mwaskom/seaborn#3026]
Hello.
I wonder whether there are any ways to
make the heatmap cells rectangular,
or in other words, suitable for showing the number (after specifying annot = True).
Thanks in advance.

**Comment by mwaskom** [comment]
Hi, please ask usage questions on stackoverflow. Also you'll want to be more clear about what you are trying to do — I don't understand what you asking here (heatmap cells are always rectangular).
