### ISSUE TITLE
JointGrid can't rotation the xticks

### ISSUE THREAD

**Issue by duckbill** [mwaskom/seaborn#3027]
![image](https://user-images.githubusercontent.com/16680297/190435902-18469428-44f0-4bf4-808e-fa5bcc978a2a.png)

## How to rotation the xticks like the picture above ?

``` python
plt.figure(figsize = (10,8))   
g = sns.JointGrid(x='u',y='t',data = tdata)
g.plot(sns.scatterplot, sns.histplot)
plt.show()
```
And  "plt.figure"   also can't work on "JoinGrid"

**Comment by mwaskom** [comment]
Please ask usage questions on stackoverflow, thanks.
