### ISSUE TITLE
univariate histograms fail due to data indexing

### ISSUE THREAD

**Issue by maciejskorski** [mwaskom/seaborn#3029]
**Issue**
Seaborn fails to generate histograms on data frames with certain indexes (duplicated). 

This is wrong because the histogram is a function of a 1-D column and most not depend on frame indexes (and btw, nonunique indexes are legitimate and appear in data science tasks).

**Reproduce** 

Under `seaborn== 0.11.2` and `pandas==1.4.3` do:

```
import seaborn as sns
import pandas as pd

df = pd.DataFrame({'id':[1,1,2,2],'values':[1.0,1.0,2.0,3.0]})
df.set_index('id',inplace=True) # NOTE: this line is causing problems
sns.histplot(data=df,x='values')
```
This generates the following error
```
ValueError: cannot reindex on an axis with duplicate labels
```

**Comment by mwaskom** [comment]
You need to update your seaborn.

**Comment by mwaskom** [comment]
(That said, while pandas does make it easy to introduce a duplicate index, other pandas operations require the index to be unique. You really ought to consider unique-ifying the index as a necessary step in your data cleaning lest you encounter limited functionality, or — worse — subtle bugs).

**Comment by maciejskorski** [comment]
Non-unique indexes also have their use-cases and I don't want to enter this discussion as it distracts from the bug repored.

Like I outlined above, `hist` is a 1-D operation (density estimation) not supposed to interfere with other data frame properties. 

I am glad that it got fixed, thanks for the hint on upgrading seaborn.

**Comment by mwaskom** [comment]
> Non-unique indexes also have their use-cases and I don't want to enter this discussion as it distracts from the bug repored.

well then you should not have included this bit in your bug report:

> This is wrong because the histogram is a function of a 1-D column and most not depend on frame indexes (and btw, nonunique indexes are legitimate and appear in data science tasks).

it's a simple fact that pandas functionality is limited when you have a duplicate index and that they explicitly define duplicate indices as a property of "messy" data: https://pandas.pydata.org/docs/user_guide/duplicates.html. seaborn cannot do anything about this and can only actively work around issues when users provide degenerate inputs.

> Like I outlined, hist is a 1-D operation (density estimation) not supposed to interfere with other data frame properties.

please do not lecture maintainers about how their software is supposed to work when you do not know what you are talking about. whether a histogram is a 1-D operation is completely irrelevant to this issue.

**Comment by maciejskorski** [comment]
Hi @mwaskom, please choose your words carefully.
Like I said, it is mathematically not appropriate that the histogram operation depends on the way the data is indexed. 
This behaviour has changed in the recent release, and that's the valuable information I expected from you, the maintainer (+)
For future, just be vocal about assumptions you make (for instance, in the docs) or at least explain this more patiently before closing the issue. Here you could improve a bit.
