### ISSUE TITLE
Factorplot margin_titles end up outside/overlapping with the legend

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#303]

**Comment by fbrundu** [comment]
Is this the same problem of the legend overlapping the plot also using `legend_out`? Because I am experiencing such issue:

![fplot](https://cloud.githubusercontent.com/assets/697622/6886647/cb75e2e4-d644-11e4-864e-897a8719cf01.png)

Should I open a different issue instead?

**Comment by mwaskom** [comment]
Hard to say without seeing your code...

**Comment by fbrundu** [comment]
g = sns.factorplot(x="Classification", y="value", hue="variable",
                       data=results_fplot, kind="box", palette="PRGn",
                       aspect=3, size=8, legend_out=True)

`results_fplot` is in the form:

        index	variable	value       Classification
    0	index0	entity0     value0     class1
    1	index1	entity0     value1     class2
    ...
    n	index0	entity1     valuen     class1
    n+1 index1	entity1     value(n+1) class1

Hope it is clear. In case tell me..

**Comment by mwaskom** [comment]
I'm unable to reproduce this behavior on v0.5.1 or current master, using one of the sample datasets (`tips`). Some more information about the versions of seaborn and matplotlib you have, and how you got to this exact plot (is this a screenshot from a notebook? Is it a file you made with `savefig`) might help. It would be best if you could try to reproduce this behavior using the sample datasets or share your data, otherwise I am not sure how helpful I can be.

However this is different from the behavior described in this issue.

**Comment by fbrundu** [comment]
Ok, so I am going to open another issue:

![prova_example](https://cloud.githubusercontent.com/assets/697622/6893040/c85f234c-d6c9-11e4-80e4-a94eecc89273.png)

It is a plot obtained using the example from [here][1] using `pyplot.savefig()`.

[1]: http://stanford.edu/~mwaskom/software/seaborn/examples/grouped_boxplot.html

**Comment by ajnelson-nist** [comment]
Hi,

I was about to file an Issue on the exact same example @fbrundu last supplied in this thread (I didn't see a related Issue filed).  I added `g.savefig("grouped_boxplot.pdf", format="pdf")` to the end of that example code and have just reproduced the same overlap.

The same issue arises with the example code [here](http://stanford.edu/~mwaskom/software/seaborn/examples/pointplot_anova.html) with `sns.plt.savefig(__file__ + ".pdf")` appended to the end.

Installed seaborn: MacPorts' packaged version, installed minutes ago.  `seaborn.__version__` reports `'0.5.1'`.

**Comment by mwaskom** [comment]
I think this was resolved as an issue with the matplotlib macosx backend in #494, for future reference; it does not appear to be linked here

**Comment by ajnelson-nist** [comment]
Ah ha!  That does fix it.  Thank you very much.
