### ISSUE TITLE
displot() with kind='kde' but y-axis with percentage rather than density

### ISSUE THREAD

**Issue by YojanaGadiya** [mwaskom/seaborn#3047]
Dear team,

I have been trying to create a distribution plot with kde as follows:
```
displot(data=joined_df, x='molecular_weight',
    kind="kde",
    hue='dataset',
    common_norm=False,
    height=4,
    aspect=1.5,)
```
This works fine..but I was wondering if there is possibility to have the y-axis as percentage rather than the density value.

I have been trying to make use of the `stat='percentage'`, `kde=True`, `fill=False`, but it doesn't seem to work as expected as I still see histogram bars (as shown [here](https://stackoverflow.com/questions/69897646/how-to-show-the-y-axis-of-seaborn-displot-as-percentage)). Any pointers for me to achieve this?

Thank You.

**Comment by mwaskom** [comment]
Hi, it really does not make any sense to plot only a KDE curve with "percent" as the y axis. You can scale the y axis to show basically any range you want by changing the binwidth parameter; but if you don't have the histogram to ground what it means, you'll be either confusing or actively misleading your audience.
