### ISSUE TITLE
Seaborn0.12 stripplot() Newly added parameters 'formatter'

### ISSUE THREAD

**Issue by jianghui1229** [mwaskom/seaborn#3049]
Mr Waskom :
   The "stripplot()"  Newly added parameters 'formatter'  
   What does this parameters do ？ 
   Can you give me an example ？

**Comment by mwaskom** [comment]
Hi, please ask usage question on stackoverflow; github issues are for bug reports not personalized support.

**Comment by jianghui1229** [comment]
Thank you！





------------------ Original ------------------
From: Michael Waskom ***@***.***&gt;
Date: Tue,Sep 27,2022 8:32 PM
To: mwaskom/seaborn ***@***.***&gt;
Cc: 姜辉 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [mwaskom/seaborn] Seaborn0.12 stripplot() Newly added parameters 'formatter' (Issue #3049)





 
Hi, please ask usage question on stackoverflow; github issues are for bug reports not personalized support.
