### ISSUE TITLE
pointplot for data on non-categorical scale

### ISSUE THREAD

**Issue by apleonhardt** [mwaskom/seaborn#305]
I did my best looking for an existing issue or a comment referring to this feature, but to no avail. A lot of the summarising point plots I generate have independent variables on scales that aren't limited to categories; e.g., a contrast tuning curve for the response of visual nerve cells, or similar. `facetplot` (or, more correctly, the underlying `pointplot`) does this job quite nicely but obviously doesn't recognise that the measured points have a meaningful relationship.

![screen shot 2014-09-26 at 14 45 05](https://cloud.githubusercontent.com/assets/406239/4420558/0250819e-457b-11e4-85f3-37f3dfdd65c4.png)

In a sense, I'm abusing the semantics of `pointplot`. However, I love its convenience (DFs as inputs, automatic generation of CIs, estimation of group means, nice formatting, etc.).

Have you ever considered making `pointplot` scale-aware if the categories present in the data set allow it? It would make room for nifty stuff like log-scaling of the x-axis etc. If I'm being dense and the functionality is either already there or can be implemented in a couple of lines, do let me know.

Happy user here, by the way. Thanks for the hard work.

**Comment by RylanSchaeffer** [comment]
> It occurs to me that it may not be obvious that if you pass x_estimator=np.mean, or some other function, you'll get means and bootstrapped error bars instead of a scatterplot

@mwaskom it wasn't obvious to me at all.

**Comment by RylanSchaeffer** [comment]
I also don't want a line of best fit. It's very counter-intuitive to thus seek out `lmplot`

**Comment by RylanSchaeffer** [comment]
`lmplot` is also a figure level function, meaning I can't use it because I need to modify each axis uniquely.
