### ISSUE TITLE
histplot() does not give correct count

### ISSUE THREAD

**Issue by nicolasshu** [mwaskom/seaborn#3050]
Hisplot is not giving the correct number of counts. 

Let us use the following data:
[data.csv](https://github.com/mwaskom/seaborn/files/9679393/data.csv)

When I run the following:
```
import seaborn as sns
import pandas as pd

df = pd.read_csv("data.csv", index_col=0)
sns.histplot(df,x="number")
```
I get the following plot:

![output](https://user-images.githubusercontent.com/12994607/193153078-c0e38082-cde1-436b-af0e-6a170241b231.png)

Now, when we actually do the actual count, we get:
```
import matplotlib.pyplot as plt
D = df.value_counts().sort_index()

plt.plot(D.to_numpy())
```
![output2](https://user-images.githubusercontent.com/12994607/193153506-c342fd0b-f404-4255-9f71-ead9710671e8.png)

**Comment by mwaskom** [comment]
Histograms bin datapoints before counting.
