### ISSUE TITLE
Chang ylabel and ytick at the same time

### ISSUE THREAD

**Issue by kebuAAA** [mwaskom/seaborn#3054]
I am a beginner in Seaborn. I meet some problems when I want to change the ylabel and yticks at the same time. I have known that I can  change the ylabel by passing `y=so.Continuous().label` to `so.Plot.scale` and change the yticks  by passing `y=so.Continuous().tick(every=1)` to `so.Plot.scale`. From this point, it seems impossible to change the ylabel and ytick at the same time. I have read the tutorial of seaborn but I still don't know how to solve this problem. I will be grateful if someone can lend me a hand:cry:

**Comment by mwaskom** [comment]
Hi, I'm not completely sure I follow — in [matplotlib lingo](https://matplotlib.org/stable/_images/sphx_glr_anatomy_001_2_0x.png) the "ylabel" is the label for the axis, not each tick. But I think the answer to your question is to call both methods in sequence?

```
(
    so.Plot([1, 4], [1, 4])
    .add(so.Line())
    .scale(y=so.Continuous().tick(every=.5).label(like=".2f"))
)
```
<img width=400 src="https://user-images.githubusercontent.com/315810/193800721-12ffa27f-0a58-4c42-8027-46e50a699a74.png" />

**Comment by kebuAAA** [comment]
! That's exactly what I wanted, thank you so much for your help. 


> Hi, I'm not completely sure I follow — in [matplotlib lingo](https://matplotlib.org/stable/_images/sphx_glr_anatomy_001_2_0x.png) the "ylabel" is the label for the axis, not each tick. But I think the answer to your question is to call both methods in sequence?
> 
> ```
> (
>     so.Plot([1, 4], [1, 4])
>     .add(so.Line())
>     .scale(y=so.Continuous().tick(every=.5).label(like=".2f"))
> )
> ```
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/315810/193800721-12ffa27f-0a58-4c42-8027-46e50a699a74.png">
