### ISSUE TITLE
kdeplot weights bug in v0.12.0

### ISSUE THREAD

**Issue by antonvorobets** [mwaskom/seaborn#3061]
I use kdeplot with weights parameter (a scenario probability vector with strictly positive elements summing to one) in this example:

https://github.com/fortitudo-tech/fortitudo.tech/blob/main/examples/5_DerivativesFramework.ipynb

It works nicely in v0.11.2, but I get the following message in v0.12.0 (matplotlib version 3.5.3 in both cases):

ValueError: The following variable cannot be assigned with wide-form data: `weights`

I've tried various things using, e.g., numpy vectors in both cases and not mix with pandas series, but I continue to get the same error.

I hope this is a bug and not an intentional change in the way the weights parameter should be used because it's a nice feature in v0.11.2

**Comment by mwaskom** [comment]
Can you please supply a minimal, reproducible example? Thanks.

**Comment by antonvorobets** [comment]
Sure. The code below triggers the error:

import numpy as np
from seaborn import kdeplot

np.random.seed(0)
num_samples = 1000
data = np.random.normal(5, 10, num_samples)
randints = np.random.randint(0, num_samples)
weights = randints / np.sum(randints)
kdeplot(data, weights=weights)

**Comment by mwaskom** [comment]
Thanks. This works on v0.12.0 if you change the last line to 

```python
kdeplot(x=data, weights=weights)
```

The mistake here was in v0.11.2; the previous invocation should have warned (as other functions did — I imagine you've seen it), about needing to add an explicit keyword for the `x` argument. While it's true that `kdeplot(data)` has the same outcome on v0.11.2 and v0.12.0, it's more complicated when you want to add other variables (`hue` or `weights`).

In any case, rougher transition than would have been ideal, but simple adaptation.

**Comment by antonvorobets** [comment]
Thank you for the quick reply. It's indeed no big deal to be explicit about the x parameter.

I don’t know if you want to leave this issue open or close it. I’ll let you decide :-)

**Comment by mwaskom** [comment]
I don't think there's really an action item here since there won't be any more releases in the v0.11.x series, but thanks for reporting. Hopefully this will turn up when people search the error message and help them solve the problem quicker.
