### ISSUE TITLE
Handle order in legend changes when labels are renamed

### ISSUE THREAD

**Issue by JoschaJ** [mwaskom/seaborn#3079]
Here is a minimal example. In the second and third example the legend handles are reversed, which I think is unwanted behaviour:
```python
penguins = sns.load_dataset("penguins")
ax = sns.histplot(data=penguins, x="flipper_length_mm", hue="species")
```
![issue0](https://user-images.githubusercontent.com/49990506/195336548-0be477c8-6199-4538-b6ac-b0451b7b1592.png)
```python
ax = sns.histplot(data=penguins, x="flipper_length_mm", hue="species")
ax.legend(["Adelie", "Chinstrap", "Gentoo"])
```
![issue1](https://user-images.githubusercontent.com/49990506/195336552-552918ad-6824-4ec9-9bef-7e4df4ae1438.png)
```python
ax = sns.histplot(data=penguins, x="flipper_length_mm", hue="species")
sns.move_legend(ax, 'best', labels=["Adelie", "Chinstrap", "Gentoo"])
```
![issue2](https://user-images.githubusercontent.com/49990506/195336554-560167cb-e718-48f4-a417-10fcc8fb5b3b.png)
My workaround inspired by https://github.com/mwaskom/seaborn/issues/2280 is to also give the handles
```python
ax = sns.histplot(data=penguins, x="flipper_length_mm", hue="species")
sns.move_legend(ax, 'best', handles=ax.legend_.legendHandles, labels=["Adelie", "Chinstrap", "Gentoo"])
```
I don't understand why this works as `sns.move_legend` according to  https://github.com/mwaskom/seaborn/issues/2280 does exactly the same. 
I could reproduce the same also with `sns.scatterplot`, so it must be a general problem. 
I could only test this on version 11.2

**Comment by mwaskom** [comment]
I don't have an immediate insight but I am also unclear about what exactly your objective is here. Isn't this something you could use `hue_order` for?

**Comment by JoschaJ** [comment]
I think this behaviour is somewhat "dangerous", as I didn't notice at first that the handles are wrongly labeled. Second, it is not straight forward to solve as the default way to get the handles vie `ax.get_legend_handles_labels` only returns an empty list (this is the same for pandas plotting routines).

`hue_order` will only change the order in the plot, not in the legend. This gives another example to the problem, if you give the same `hue_order` and `labels` the legend entries will generally be labeld wrong
```python
ax = sns.histplot(data=penguins, x="flipper_length_mm", hue="species", hue_order=["Chinstrap", "Adelie", "Gentoo"])
ax.legend(["Chinstrap", "Adelie", "Gentoo"])
```
![issue1](https://user-images.githubusercontent.com/49990506/195541333-913cfb8b-6236-4d5a-9163-60fe64ebd2e2.png)

**Comment by mwaskom** [comment]
Sorry but I'm still a little confused about what you're trying to accomplish. Why are you passing labels to `move_legend`?

**Comment by mwaskom** [comment]
Also FWIW when I run your code I get a warning:

> /Users/mwaskom/code/seaborn/seaborn/utils.py:478: UserWarning: You have mixed positional and keyword arguments, some input may be discarded.
  new_legend = legend_func(handles, labels, loc=loc, **props)

**Comment by JoschaJ** [comment]
In the above examples it is not very clear. I want to give different labels, let's say shorter ones
`ax.legend(["Adel", "Chin", "Gen"])`, but I don't want to rename the DataFrame columns.
In this case, "Adel" will stand at the handle of "Gentoo" instead of "Adelie". 

Do you want the full real life example? I really just want to have different labels than in the data frame.

(The Warning is new in v0.12 and is because the original labels are given as positional, and the new ones as kwargs. Maybe this was already clear to you.)

**Comment by aufildelanuit** [comment]
@JoschaJ Maybe you already found a solution to your problem. However, one suggestion I can think about: why not pass to seaborn a *copy* of your dataframe with renamed columns?

Something like: 

```python
ax = sns.histplot(data=penguins.rename(columns={"Adelie": "Adel", "Gentoo": "Gen", "Chinstrap": "Chin"}), x="flipper_length_mm", hue="species", hue_order=["Chin", "Adel", "Gen"])
```

In this way, your DataFrame in memory remains untouched, but the DataFrame that seaborn uses is labeled in any way you want it, and without any trouble with the legend?

Just a guess, sorry if I misunderstood.

**Comment by tvanyo** [comment]
I've seen this exact behavior as well and it is very dangerous. Maybe my code is a bit clear description of what is being seen.

[seaborn_issue.pdf](https://github.com/mwaskom/seaborn/files/10798444/seaborn_issue.pdf)

I've added the python code as well.
[seaborn_legend_issue_code.zip](https://github.com/mwaskom/seaborn/files/10798459/seaborn_legend_issue_code.zip)

While it's always true that I can't blindly change the legend labels, this behavior is 180° from what I'd expect.

**Comment by mwaskom** [comment]
> Manually setting the legend via plt.legend should work intuitively and not unexpectedly reverse order!
> It would be great to see this fixed in the future.

Manually setting the legend with `plt.legend` by passing *handles and labels* will work properly. Calling `plt.legend` only with labels is simply **cannot be guaranteed** to "work intuitively" because it automatically grabs the first n artists attached to the plot and maps them to those labels. Unless you added those artists yourselves and know exactly the order you added them in, you can't expect a correct result. I **strongly discourage** calling `plt.legend` after making a plot with seaborn because of this, but there's really nothing seaborn can do to stop you from trying.

**Comment by v4hn** [comment]
Thanks for the insight! With that explanation I'm wondering whether the observed behavior to map `plt.legend` parameters to hues *in reverse* is consistent across the seaborn API.
