### ISSUE TITLE
regplot does not align input series

### ISSUE THREAD

**Issue by SilasK** [mwaskom/seaborn#3080]
It seams that regplot does not align the input data when given as 2 seperate Series as does scatterplot

`sns.scatterplot(x=df.A, y= df2.B)` plots a nice data that is correlated. 

`sns.regplot(x=df.A, y= df2.B)` shows not aligned data. 

Fixes the problem.
`sns.scatterplot(x=df.A, y= df2.loc[df.index].B)`

**Comment by mwaskom** [comment]
That's correct, `regplot` is a quite old function at this point and seaborn was less pandas-oriented when it was written. This is called out (somewhat generally, but relevant here) [in the docs](https://seaborn.pydata.org/tutorial/data_structure.html):

<img width="665" alt="image" src="https://user-images.githubusercontent.com/315810/195577278-aa99d420-6a4f-45e5-a7fa-580c8aad6b1a.png">
