### ISSUE TITLE
future warning - iteritems - when using FacetGrid.refline

### ISSUE THREAD

**Issue by liorpol** [mwaskom/seaborn#3093]
When calling `FacetGrid.refline`, the following warning appears: 

Input: 
```
g = sns.catplot(data = [my_data], x = [x_value],
                        y = [y_value])

g.refline(y =[some_y])
```

Output: 

```
iteritems is deprecated and will be removed in a future version. Use .items instead.
```

Seaborn version: 0.12.0
Python versino: 3.10.7

**Comment by mwaskom** [comment]
Thanks I am aware of this but have yet to receive a clear answer from pandas on what the correct way to adapt to this deprecation is https://github.com/pandas-dev/pandas/issues/48673

**Comment by mwaskom** [comment]
Closing as this had been fixed with https://github.com/mwaskom/seaborn/pull/3038
