### ISSUE TITLE
Typo in Seaborn Documentation

### ISSUE THREAD

**Issue by msharara1998** [mwaskom/seaborn#3105]
There is a small typo in the following [page](https://seaborn.pydata.org/generated/seaborn.pairplot.html) of documentation. The typo is in this section at the top of the page:

> By default, this function will create a grid of Axes such that each numeric variable in data will **by** shared across the y-axes across a single row and the x-axes across a single column. The diagonal plots are treated differently: a univariate distribution plot is drawn to show the marginal distribution of the data in each column.

**Comment by mwaskom** [comment]
Thanks, you can submit typo fixes directly as PRs.
