### ISSUE TITLE
feature request: colorbar for kdeplot

### ISSUE THREAD

**Issue by graylunarmake** [mwaskom/seaborn#312]
I'd like to get a better sense for what the densities are in a given region when plotting scatter data using kdeplot. Is there some way of displaying a colorbar along with the figure, similar to the first response to this question: http://stackoverflow.com/questions/21006490/scatter-plot-with-density-in-matlab?

**Comment by CommonClimate** [comment]
If that can help tip the scales, I too would be extremely interested in a colorbar feature for kdeplot. Seaborn is a truly wonderful package, but the function of figure aesthetics should be to support the analysis of data, not obscure them. kdeplot is great for a qualitative appraisal of joint relationships, and turning it into a quantitative appraisal seems like it would just need a colorbar (or perhaps contour labeling). Easier said than done, I know...

**Comment by tritemio** [comment]
Is there a matplotlib issue on this?

**Comment by hbsmith** [comment]
Can this be reopened? The contours are useless for scientific presentation unless it's obvious what they actually correspond to.

**Comment by tritemio** [comment]
In matplotlib there is the possibility to add a colorbar to contour plots:

http://matplotlib.org/examples/pylab_examples/contourf_demo.html

what additional functionality would be needed?

**Comment by benavente** [comment]
+1 for reopening this.

**Comment by benavente** [comment]
+1 for reopening this.

**Comment by mdhurst1** [comment]
+1 This would be really useful :)

**Comment by lidakanari** [comment]
+1 kdeplot can produce amazing figures that are of much higher quality compared to other tools. However, since the colorbar is important for quantitative comparison, those figures cannot be used for the official presentation of results. It would be very useful if the option of a colorbar was added to this functionality :) Thanks in any case!
