### ISSUE TITLE
Legend position gets overwritten / can not be set

### ISSUE THREAD

**Issue by jalsti** [mwaskom/seaborn#3130]
When plotting with the new `seaborn.objects` Plot method including a legend (like `.add(Line(), legend=True)`), the position of the legend gets hardcoded to specific positions (https://github.com/mwaskom/seaborn/blob/master/seaborn/_core/plot.py#L1612-L1624), which differ depending on the usage of pyplot (legend gets pulled on top of the right side over the graph's content) or not (e.g. in a Jupyter notebook, or on `.save()` ,the legend gets place to the right side outside of the plot graph area).

If the users want a different position of the legend (possible especially in the case of pyplot usage, where the legend may easily be generated over important data points), they have no possibility to move it to another place. The old (=not `seaborn.objects`) method [`move_legend()`](https://seaborn.pydata.org/generated/seaborn.move_legend.html) does not work for `Plot` objects, neither can the seaborn objects `.theme()` approach be used, with setting matplotlib rc params (which would be [`legend.loc`](https://matplotlib.org/stable/tutorials/introductory/customizing.html#:~:text=legend.loc) in conjunction with `bbox_to_anchor` of the [matplotlib legend](https://matplotlib.org/stable/api/legend_api.html#matplotlib.legend.Legend)), because the `loc` is hardcoded, and will such be overwritten, additionally there is no possibility at all for the users to set `bbox_to_anchor` for the legend.

The PR https://github.com/mwaskom/seaborn/pull/3128 solves this issue, through staying at the current default behavior, if no additional parameters are given, but respecting the matplotlib rc params  entry for `legend.loc` if it is given like `.theme({"legend.loc": "upper left"})`. 
Additionally it gives the new possibility to set the `bbox_to_anchor` of the legend, like `.theme({"legend_loc__bbox_to_anchor": (0.1, 0.95)})` (where the kind this is implemented might not be ideal). 

This gives the users full control over the legend position.

**Comment by mwaskom** [comment]
> which differ depending on the usage of plotly

? plotly and seaborn have nothing to do with each other

**Comment by jalsti** [comment]
Sorry, thinking-typo, fixed to 'pyplot'

**Comment by mwaskom** [comment]
Thanks for this additional explanation.

Legend control in the objects interface is definitely a WIP and a proper API for it is on the roadmap, but IMO the suggested changes are too much of a hack and give a poor user experience.

A few thoughts:

I'm 👎 on adding new parameters to the dictionary that `Plot.theme` accepts; that will remain a dictionary of matplotlib rc parameters only, and any other configuration will have to happen in other APIs. Mixing matplotlib rcParams and magical seaborn ones is too special.

It's unfortunate that `legend.loc` only applies to axes legends and so it gets ignored by the figure legend that seaborn creates. But matplotlib makes it really hard to get a legend outside of the plot through normal configuration. And when I tried a simple example on your branch

```python
(
    so.Plot(tips, x="total_bill", y="tip", color="time")
    .theme({"legend.loc": "upper right"})
    .add(so.Dots())
)
```
I get a very surprising result:
![image](https://user-images.githubusercontent.com/315810/200602283-20c86295-2538-4706-b62a-8745db0d9585.png)

I understand what's happening here because I know what's going on internally, but this is something the average user (a) would try and (b) would not be able to diagnose.

Additionally, the way the PR is implemented, I get the `UserWarning: Automatic legend placement (loc='best') not implemented for figure legend` on every plot unless I pass `legend.loc` to `Plot.theme`.

So I appreciate that the current situation is not ideal, but I'd rather take the time to design a clean API for controlling where the legend goes than to hack together a partial solution.

**Comment by jalsti** [comment]
I understand what you are saying, especially about the "hacky" part, and that the UserWarning I created may be irritating, if not into the topic (and only appears if the matplolib rc is set to use 'best' as default, which admitted probably is the case for most people), still it could easily be taken out again (or be shown only if 'best' is passed by the user, noted in the code by an additional flag showing the default legend location changed). 

That the legend in your example above appears surprising would get fixed with a proper `bbox_to_anchor` default value (`(0,0,1,1)`), as soon as `legend.loc` gets passed in (maybe again through the additional flag), instead of the current hardcoded one, which is the cause. Both used in conjunction work fine, the only problem are the hardcoded values, which make it impossible to tell matplotlib via the rc params which kind of legend position for the figure it shall use, like it normally would work. With a default value `bbox_to_anchor = (0,0,1,1)` the `legend.loc` works like expected instantly, I just did not change the current default value to not break the current behavior.

Although the PR is not a very clean approach (but more a nightly quick-fix), I think it can be a practicable in-between solution, so that people can use the legend, without having data hidden, or loosing it while saving the image, until the longer work for a clean API is finished. 
That the implementations will still change is already a known fact, and hints to the according legend documentation are already present in the change.

**Comment by mwaskom** [comment]
> That the implementations will still change is already a known fact, and hints to the according legend documentation are already present in the change.

Yes, but there is an important difference between changing implementations and changing API, and I prefer not to have to maintain a "nightly hack".

A better thing to focus on is why `move_legend` doesn't work. IIRC from briefly looking into it, it might require using a private matplotlib API when the legend gets defined, but I'm not certain.

**Comment by jalsti** [comment]
I also had a look into `move_legend `, but it got my into an quite endless journey, which ended for the `objects` again at the single problem point, that the legend position and bounding box just get hardcoded set. 
As long as these currently present both hardcoded things exist, no one has a chance to set the legend position correctly, as I found it, no matter with which method, but instead have to live with some data potentially behind the legend, and the saved images without legend.

I can accept, that the existing position has been a good first idea, to just set the legend somewhere, but enhancing this behavior (pre-solving that fault) with another (*not worse*) implementation which gives more freedom for the users, until a proper API has been developed, would be worth a short merge. Especially as this does not enlarge maintenance in any way (at least as far as I could realistically imagine), because the default behavior is no other, and the changes are just quite directly utilizing matplotlib behavior, for the usage of more skillful programmers.

Better would be of course, saying again, to fix the hardcoded bbox, and only catch the for `Figure`s not working 'best' position, with additional throwing out the hardcoded `loc`, and everything would also be fine, with a still again needed additional possibility to set the bbox, similar to what the PR suggests.


Just saying … it does not worsen the current situation, and is faster merged, than reasoned via typing…

**Comment by mwaskom** [comment]
You're not going to get anywhere with this approach.

**Comment by jalsti** [comment]
NP, your welcome :-)
