### ISSUE TITLE
Add flag to jointplot: perform "copula like" plot by using empirical probability integral transform on X and Y variables

### ISSUE THREAD

**Issue by jerabaul29** [mwaskom/seaborn#3131]
As far as I understand, performing a jointplot for looking at the relation between 2 random variables can be a bit deceptive depending on the context, as the 2D density plot obtained is then a mixture of the effect of the marginal distributions and the effect of the relation between the variables. A way to get a more clear / unbiased view of the relation between 2 variables can be to apply the probability integral transform (PIT) on the 2 variables to compare, so that they have both uniform distribution on [0, 1]. This way, performing a jointplot of the PIT-transformed variables really only shows the effect of the relation between these, and takes away the effect of the marginal distributions on how the plot looks like.

As far as I understand, this is the core idea behind the copula approach.

I do not think that there is a way to get this out of the box with the ```joinplot``` command at the moment? Would it be of interest to provide a parameter flag to the ```joinplot``` command, for example ```probability_integral_transform=False``` (by default ```False``` to not change the current behavior), in order to provide a turn key approach for this?

**Comment by jerabaul29** [comment]
A snippet of how this can be achieved, in the case this is of interest:

```python
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

import pandas as pd

import seaborn as sns

from icecream import ic

ic.configureOutput(prefix='', outputFunction=print)


############################################################


def self_probability_integral_transform(sample_array_in):
    """Given the sample_array_in empirical samples, get
    the probability integral transform applied on the
    same samples.

    sample_array_in: numpy array, shape (n_samples,)"""

    assert len(sample_array_in.shape) == 1

    n_samples = len(sample_array_in)

    # argsort provides the indexes_sorting such that:
    # sample_array_in[indexes_sorting] is sorted
    # however, what we want to perform the PIT is the index each entry
    # would have when the array gets sorted; this is obtained by applying
    # the inverse permutation to the arange of indexes
    indexes_sorting = np.argsort(sample_array_in)
    inverse_indexes_sorting = np.empty_like(indexes_sorting)
    inverse_indexes_sorting[indexes_sorting] = np.arange(n_samples)
    pit_transformed = np.arange(1, n_samples+1, 1)[inverse_indexes_sorting] / n_samples

    ic(np.min(pit_transformed))
    ic(np.max(pit_transformed))

    return pit_transformed

############################################################

mvnorm = stats.multivariate_normal(mean=[0, 0], cov=[[1., 0.7],
                                                     [0.7, 1.]])
x = mvnorm.rvs(1000)

############################################################
# vanilla jointplot by setting the x and y arrays explicitly
# sns.jointplot(x=x[:, 0], y=x[:, 1], kind='kde')

############################################################
# vanilla jointplot by setting the x and y arrays be pd name
dataframe_2d = pd.DataFrame(data=x, columns=["x0", "x1"])

sns.jointplot(data=dataframe_2d, x="x0", y="x1", kind="kde")

############################################################
# view as a copula like PIT-transformed jointplot

# compute the data PIT transformed so that marginals are uniform
for crrt_column in ["x0", "x1"]:
    crrt_data = dataframe_2d.loc[:, crrt_column].to_numpy(dtype=np.float32)
    crrt_data_pit_transformed = self_probability_integral_transform(crrt_data)
    new_column_name = crrt_column + "_uniformized"
    dataframe_2d[new_column_name] = crrt_data_pit_transformed

ic(dataframe_2d)

sns.jointplot(data=dataframe_2d, x="x0_uniformized", y="x1_uniformized", kind="kde", xlim=(0.0, 1.0), ylim=(0.0, 1.0))

############################################################
plt.show()
```

which results in the plots:

- "usual" jointplot:

![jointplot](https://user-images.githubusercontent.com/8382834/200676008-1dbddd1f-22d8-4a5e-8d47-be383998daf1.png)

- "copula-like" jointplot:

![copula_jointplot](https://user-images.githubusercontent.com/8382834/200676029-285863c1-7bb4-439a-9614-d62811c0cb83.png)

**Comment by jerabaul29** [comment]
A few notes on the appearance of the "copula like" plot:

- I personally like the level lines best (i.e. I like best style kde instead of hex); however, it is a bit annoying that the level lines are allowed to "go out of [0, 1] x [0, 1]; any way to fix that?
- the marginals seem to "go down" at the extremities, but this is only an effect of smoothing, the marginals are well "close to uniform"

See the illustration under for the copula style plot using hex style instead of kde; I think I would prefer to have kde style joint plot and hex style marginals plot, on the same jointplot (not sure if this is doable):

![copula_jointplot_hex](https://user-images.githubusercontent.com/8382834/200676968-1a2522a6-83ee-4fc0-a354-829c6ca6504f.png)

**Comment by jerabaul29** [comment]
Reference for copula: https://en.wikipedia.org/wiki/Copula_(probability_theory) , and see the correspondance with the bivariate gaussian copula rho=0.5 plot (I use 0.7 in my plots, see the snippet).

**Comment by mwaskom** [comment]
Thanks, this is interesting, but it seems a little esoteric and something handled fine as an upstream transform rather then a feature of `jointplot`. But to answer a question:

>  I think I would prefer to have kde style joint plot and hex style marginals plot, on the same jointplot (not sure if this is doable)

use `JointGrid` directly to accomplish this.
