### ISSUE TITLE
[BUG] The issues with bar plots setting width 

### ISSUE THREAD

**Issue by DylanWake** [mwaskom/seaborn#3137]
If we directly add width parameter in `seaborn.barplot(..., width = {width})`, then the function would blow up:
```
TypeError: Axes.bar() got multiple values for argument 'width'
```

The reason causing this is the definition in line 1604 of `categorical.py`， function `draw_bars(ax, kws)` where:

```python
     # Draw the bars
            barfunc(barpos, self.statistic, self.width,
                    color=self.colors, align="center", **kws)
```

The additional width parameter passed in with **kws will conflict with `self.width`

The current workaround for this issue is to add this line before plot anything in your code to set width:
```python
    sns.categorical._BarPlotter.width = {width}
```

Please fix this issue, this problem is extremely confusing!

**Comment by DylanWake** [comment]
To help people encountering the same problem and not patient enough to read the description:
The current workaround for this issue is to add this line before plot anything in your code to set width:
```python
    sns.categorical._BarPlotter.width = {width}
```

**Comment by mwaskom** [comment]
Reproducible example?

**Comment by gty111** [comment]
example like 
```
import seaborn as sns
df = sns.load_dataset("penguins")
sns.barplot(data=df, x="island", y="body_mass_g",width=0.5)
```

**Comment by gty111** [comment]
I find `TypeError: bar() got multiple values for argument 'width'` when I use py-seaborn `0.11.2`  built by spack. 
There is no problem when changing to py-seaborn `0.12.0`.

**Comment by mwaskom** [comment]
Correct: https://seaborn.pydata.org/whatsnew/v0.12.0.html#other-updates
