### ISSUE TITLE
Display Chinese character when using Seaborn.objects

### ISSUE THREAD

**Issue by kebuAAA** [mwaskom/seaborn#3140]
Can `Seaborn.objects.Plot()` display Chinese characters? I can use `sns.set_style("darkgrid", {"font.sans-serif": ['simhei', 'Arial']})
` to display the Chinese chararcters when I use Seaborn without using ` seaborn.objects` . This method doesn't work when I use ` seaborn.objects`, I have searched many solutions on Google but in vains? Maybe I need some help.

**Comment by kebuAAA** [comment]
One more question for this issue： How can I draw a stacked barPlot without using `seaborn.objects`. The picture I wanted would look like the following picture( The boxes in the figure cannot be displayed because they are Chinese characters. ):
![output](https://user-images.githubusercontent.com/96560962/201677385-d7d32d13-daee-403d-9026-411c4b87e975.png)

The code I use is like `so.Plot(new_data, x="year", y="amount", color="product").add(so.Bars(),so.Stack())`,I can't finish this plot after I referred the `seaborn.histplot`.

**Comment by mwaskom** [comment]
See https://github.com/mwaskom/seaborn/discussions/3005 for a conversation about global themes in the objects interface.

I _think_ you just need to add `.theme({"font.sans-serif": ['simhei', 'Arial']})` to your plot definition. Unfortunately, right now, you will need to add that to every plot. This will change in the future.

**Comment by kebuAAA** [comment]
> See #3005 for a conversation about global themes in the objects interface.
> 
> I _think_ you just need to add `.theme({"font.sans-serif": ['simhei', 'Arial']})` to your plot definition. Unfortunately, right now, you will need to add that to every plot. This will change in the future.

Yeah， this method solves my problem indeed. Thanks for your help.
One more question that may need your help: Is it possible to draw such a stacked histplot without using `seaborn.objects`?

**Comment by mwaskom** [comment]
I don’t understand the other question. What is the issue you are having with histplot?

**Comment by kebuAAA** [comment]
> I don’t understand the other question. What is the issue you are having with histplot?

Sorry， I guess I'm probably mixing up the bar chart and the histogram. 
My question is that I don't know how to "stack" the bars in the bar-plot drawed by `seaborn.barplot()`. This function seems to give me a parameter to do this(`dodge=False` will overlay some bars, this isn't what I want to see)
So sorry to continue to bother you

**Comment by mwaskom** [comment]
That's right, `barplot` does not have a stacking option, but `histplot` does.
