### ISSUE TITLE
Suggestion: Regplot returning the fit results in a dict in the FG object

### ISSUE THREAD

**Issue by mrektor** [mwaskom/seaborn#3143]
Hi!

Would be great for analysis workflow if the parameters of the fit done by Regplot would be accessible programmatically for further analysis

in other words I'm talking about seeing the regression scalars of linear fit (when `order` is one)

**Comment by mwaskom** [comment]
https://seaborn.pydata.org/faq.html#can-i-access-the-results-of-seaborn-s-statistical-transformations
