### ISSUE TITLE
Cannot import seaborn.objects  (Python 3.8.10)

### ISSUE THREAD

**Issue by GeorgiaA** [mwaskom/seaborn#3144]
When I run the below line of code
`import seaborn.objects` or `from seaborn import objects`
I receive the following error:

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> Input In [16], in <cell line: 1>()
> ----> 1 import seaborn.objects
> 
> File ~/.virtualenvs/snn/lib/python3.8/site-packages/seaborn/objects.py:29, in <module>
>       1 """
>       2 A declarative, object-oriented interface for creating statistical graphics.
>       3 
>    (...)
>      27 
>      28 """
> ---> 29 from seaborn._core.plot import Plot  # noqa: F401
>      31 from seaborn._marks.base import Mark  # noqa: F401
>      32 from seaborn._marks.area import Area, Band  # noqa: F401
> 
> ModuleNotFoundError: No module named 'seaborn._core.plot'; 'seaborn._core' is not a package

Setup:
- Opertating System: Ubunutu 20.04
- Python version: 3.8.10
- seaborn version: 0.12.1

I can successfully import `seaborn.objects` on my other machine which is running macOS Monterey and python 3.7.

**Comment by mwaskom** [comment]
This suggests an incomplete or corrupted install. Unfortunately, I can't help much — the reason is almost certainly something idiosyncratic to your system or workflow. I suggest uninstalling all the way and then reinstalling.
