### ISSUE TITLE
Legend subtitles should not use hardcoded colors

### ISSUE THREAD

**Issue by nikhilxb** [mwaskom/seaborn#3145]
Currently, in order to generate legend subtitles for multiple semantic types (i.e. hue, size, style),  the relational plotter creates invisible legend entries and uses the labels as subtitles. If there is only one semantic type, then the actual "legend title" is used rather than these "hacked legend labels". See https://github.com/mwaskom/seaborn/pull/1483 and these lines:
https://github.com/mwaskom/seaborn/blob/bf4695466d742f301f361b8d0c8168c5c4bdf889/seaborn/relational.py#L205-L212

The "legend title" exhibits desirable behavior by reflecting `rcParams['text.color']` (changed to `'red'` below).

<img width="101" alt="image" src="https://user-images.githubusercontent.com/16842594/202290921-60495374-44c0-4a09-86b1-a50a2120e48e.png">

However, the "hacked legend labels" exhibit undesirable behavior:

<img width="120" alt="image" src="https://user-images.githubusercontent.com/16842594/202290817-64db8886-44e8-411b-9143-dcd3295963dc.png">

1) When `rcParams['legend.labelcolor'] = 'linecolor'`, the subtitles show up as white because the invisible handles are hardcoded to white ("w"). --> Should reflect `rcParams['text.color']` instead.

https://github.com/mwaskom/seaborn/blob/bf4695466d742f301f361b8d0c8168c5c4bdf889/seaborn/relational.py#L218-L220

2) Size and style labels are hardcoded to gray ("0.2"). --> Should reflect `rcParams['legend.labelcolor']` instead.

https://github.com/mwaskom/seaborn/blob/bf4695466d742f301f361b8d0c8168c5c4bdf889/seaborn/relational.py#L330

I'm not too familiar with this codebase, so there may be other places that also need de-hardcoding (to maintain consistency with these changes).

**Comment by mwaskom** [comment]
This seems reasonable but I'm confused by some of the examples, which lack context. Why are the subtitles turning white when you set the text color default to red? Can you make them reproducible please?

**Comment by mwaskom** [comment]
Closing for now but would be open to this with a more clear demonstration of the current / expected behavior.
