### ISSUE TITLE
Feature: `regplot(truncate='both)` to clip both axes by data range

### ISSUE THREAD

**Issue by Demetrio92** [mwaskom/seaborn#3152]
## Overview
`regplot` `truncate` argument only applies  to the x-axis. With real-world data it is possible to obtain a bad linear fit and obtain and an undesirable visual result. When using `regplot` in combination with a `PairGrid` or `FacetGrid`, controlling individual plots can be tricky, as such an option to truncate both axes by default can be useful. 

## Demonstation
```python
import seaborn as sns
import pandas as pd
import numpy as np

# set up for a terrible linear fit
np.random.seed(41)
N = 10
oversample_start = 20
xs = np.concatenate([np.random.uniform(1, 2, N*oversample_start), np.random.uniform(2, 4, N)])
ys = 10 / xs**2 + 2*np.random.uniform(0, 0.2, N*(oversample_start+1))
df = pd.DataFrame({'x': xs, 'y': ys})
```
```python
# use regplot with the usual `truncate=True`
g = sns.regplot(
    x='x', y='y', data=df,
    truncate=True,
    scatter_kws={'s': 70}, line_kws={'color': 'orange'}
)
g.figure.set_size_inches((10, 10))
g.figure.show()
```
<img src="https://user-images.githubusercontent.com/22682408/203613079-1c105eb5-0a98-4414-bf87-57773bb8d8a9.png" width="300" height="300">

## Fix: `truncate='both'`
```python
g = sns.regplot(
    x='x', y='y', data=df,
    truncate='both',  # this is new
    scatter_kws={'s': 70}, line_kws={'color': 'orange'}
)
g.figure.set_size_inches((10, 10))
g.figure.show()
```
<img src="https://user-images.githubusercontent.com/22682408/203613305-55a794d1-0490-46fc-bb3c-8f55ee62855c.png" width="300" height="300">

## Implementation
I already add this fix locally -- just a few lines had to be changed. Let me know if this is worth a PR

If yes, should it be `truncate='x'`, `truncate='y'`, and `truncate='both'`?

**Comment by mwaskom** [comment]
Can't you accomplish this by setting the `ylim` of the resulting axes?

**Comment by mwaskom** [comment]
I'm -1 on this because your proposed `truncate="x"` and `truncate="y"` aren't symmetric. If the latter behaved like the former, the line would be extended left until `\hat y` = `max(y)`, but that's not what you wan't either.
