### ISSUE TITLE
Seaborn objects seem to ignore set_theme

### ISSUE THREAD

**Issue by FirefoxMetzger** [mwaskom/seaborn#3175]
I want to create figures via the objects API that use the same style as some existing figures that I created with the functional API a while back. However, objects don't seem to respect the global theme or style options. Is this a bug, or am I doing something wrong?

```python
import sys
import seaborn as sns
import seaborn.objects as so

print(f"Python: {sys.version}")
print(f"Seaborn: {sns.__version__}")
sns.set_theme("talk", style="whitegrid")

(
    sns.load_dataset("iris")
    .pipe(so.Plot, color="species")
    .add(so.Dot(), x="sepal_length", y="sepal_width")
)
```

```
Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
Seaborn: 0.12.0
c:\Users\Sebastian\AppData\Local\Programs\Python\Python38\lib\_collections_abc.py:832: MatplotlibDeprecationWarning: 
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  self[key] = other[key]
c:\Users\Sebastian\AppData\Local\Programs\Python\Python38\lib\_collections_abc.py:832: MatplotlibDeprecationWarning: 
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  self[key] = other[key]
```
![d0089080-4c62-4301-91dd-8e3efa71192c](https://user-images.githubusercontent.com/4402489/205569108-891aa5a0-59d9-4b5a-a5cf-8d4ac6a5d60b.png)

And for comparison:

```python
df = sns.load_dataset("iris")
sns.scatterplot(df, x="sepal_length", y="sepal_width", hue="species")
```
![3f6f77c5-df63-440d-b785-1cbc3fb0620f](https://user-images.githubusercontent.com/4402489/205569244-65fa453b-8ea2-4a2a-88e9-43e9403d4cdf.png)

**Comment by mwaskom** [comment]
Correct: https://github.com/mwaskom/seaborn/discussions/3005

**Comment by FirefoxMetzger** [comment]
Thanks for the reference @mwaskom ! So the way to do this is:

```python
import sys
import seaborn as sns
import seaborn.objects as so
from matplotlib import style

print(f"Python: {sys.version}")
print(f"Seaborn: {sns.__version__}")
sns.set_theme("talk", style="whitegrid")

(
    sns.load_dataset("iris")
    .pipe(so.Plot, color="species")
    .add(so.Dot(), x="sepal_length", y="sepal_width")
    # first set theme="talk" then style="whitegrid"
    .theme(style.library["seaborn-talk"])
    .theme(style.library["seaborn-whitegrid"])
)
```
![f88bec4b-a239-4ffa-8aee-76886f468996](https://user-images.githubusercontent.com/4402489/205658755-6c5d2e8d-1752-4ec0-8cfc-ac664c088ea3.png)

Excellent! Closing :)

**Comment by mwaskom** [comment]
No, because those seaborn “style sheets” that matplotlib ships are out of date and deprecated. The recommended approach is to pass the parameter dicts that you can get from the relevant seaborn functions, or to set the global theme and then pass in the rcParam dict explicitly.
