### ISSUE TITLE
Overlapping labels in relplot with seaborn 0.12

### ISSUE THREAD

**Issue by sorenwacker** [mwaskom/seaborn#3179]
```
import seaborn as sns

sns.set_context("paper")
sns.set_style("white")

data = (sns.load_dataset('iris').set_index('species')*1e7).reset_index()
g = sns.relplot(data=data, x='sepal_length', y='sepal_width', col='species', 
                col_wrap=2, height=2.5)
g.set_titles(row_template="{row_name}", col_template="SOMEWHATLONG-{col_name}")
for axes in g.axes.flat:
    axes.ticklabel_format(axis='both', style='scientific', scilimits=(0, 0))
```

```
import seaborn as sns

sns.set_context("paper")
sns.set_style("white")

data = (sns.load_dataset('iris').set_index('species')*1e7).reset_index()
g = sns.relplot(data=data, x='sepal_length', y='sepal_width', col='species', 
                col_wrap=2, height=2.5, facet_kws=dict(sharex=False, sharey=False))
g.set_titles(row_template="{row_name}", col_template="SOMEWHATLONG-{col_name}")
for axes in g.axes.flat:
    axes.ticklabel_format(axis='both', style='scientific', scilimits=(0, 0))
```

## seaborn 11.2:

![image](https://user-images.githubusercontent.com/3391614/206537961-35d4cb07-f052-43cf-90cf-c882d824330c.png)
![image](https://user-images.githubusercontent.com/3391614/206537975-52349cfb-89dc-4b1e-b9d5-fa539a29ce8b.png)

## seaborn 12.1:
 
![image](https://user-images.githubusercontent.com/3391614/206538146-e10032d3-7aa7-4c57-a79e-971b883f90bc.png)
![image](https://user-images.githubusercontent.com/3391614/206538221-37ef81ac-728a-40a0-8797-4d9737010f81.png)y

**Comment by sorenwacker** [comment]
Is there a way to turn the xlabels off again or to increase the spacing between the xaxis labels and the figure titles?

**Comment by mwaskom** [comment]
Please turn this into a reproducible example, thanks.

**Comment by sorenwacker** [comment]
Here is an reproducible example.

**Comment by sorenwacker** [comment]
data = (sns.load_dataset('iris').set_index('species')*1e7).reset_index()
g = sns.relplot(data=data, x='sepal_length', y='sepal_width', col='species', 
                col_wrap=2, height=2.5, facet_kws=dict(sharex=False, sharey=False))
g.set_titles(row_template="{row_name}", col_template="SOMEWHATLONG-{col_name}")
for axes in g.axes.flat:
    axes.ticklabel_format(axis='both', style='scientific', scilimits=(0, 0))

![image](https://user-images.githubusercontent.com/3391614/206541914-79e01cd2-1dbf-4df7-82a3-b2bc26716c1b.png)

Also seaborn 0.12.1.

**Comment by mwaskom** [comment]
Thanks, see #3180

**Comment by sorenwacker** [comment]
Is there a way to remove the x-axis labels for plots which are not on the bottom? In my example, only the upper left plot?
As a workaround.

**Comment by sorenwacker** [comment]
I think, I will just use 11.2 until 12.2 is out.
Thank for your great work!

**Comment by mwaskom** [comment]
Yes, you can easily clean up the figure using the matplotlib api
