### ISSUE TITLE
Support for Pola.rs DF

### ISSUE THREAD

**Issue by garcialn** [mwaskom/seaborn#3188]
I've been working more and more with [Pola.rs](https://www.pola.rs/) DF, instead of Pandas DF for better efficiency and agility. But i've always used seaborn for dtviz (prettier and faster visualization), wich is not compatible with Pola.rs DF, and i've seen myself using more Plotly.Ex when the data is too big (which is usually the case). But seaborn is much better for my use.
From such a big difference of efficiency between Pandas and Pola.rs, i believe that more and more Pola.rs will be choice for Data wrangling. The thing is that Pola.rs uses Arrow2 implementation of Apache Arrow Array, instead of Numpy. But i believe it is very much possible to make it happen, and i hope to be able to work on it in the future.

**Comment by mwaskom** [comment]
It looks like polars has a [`DataFrame.to_pandas`](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.to_pandas.html) method that you can call for interoperability.

**Comment by garcialn** [comment]
Indeed! And i do used when the data volume ins't that big. But with some bigger sizes, it gets little time consuming to make the transformations only for plotting.
But it is, for sure, a way to keep seaborn without headache 😄

**Comment by mwaskom** [comment]
For many EDA applications it is sufficient to sample a large dataset for visualization.

In any case, there is no short or medium term plan to move away from pandas to polars, despite polars having many (overly) enthusiastic fans on the internet.
