### ISSUE TITLE
Boxplot rcparams not working in seaborn

### ISSUE THREAD

**Issue by GiuseppeMinardiWisee** [mwaskom/seaborn#3204]
I'm trying to create a custom style for my plots. In order to do so I'm modifying the rcParameters in order to have a uniform style while using matplotlib or seaborn. I created a style that satisfies me but when I use it with seaborn specific parameters are ignored. Example:
```
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df_penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
from cycler import cycler

ex = {
    "axes.spines.right": False,
    "axes.spines.top": False,
    "figure.dpi": 150,
    "axes.prop_cycle": cycler(
        "color",
        [
            "#6900D8",
            "#00E2A7",
            "#D095FF",
            "#00AF78",
            "#0047E5",
            "#DB004F",
            "#FF7F00",
        ],
    ),
    "boxplot.boxprops.color": "darkgrey",
    "boxplot.whiskerprops.color": "darkgrey",
    "boxplot.capprops.color": "darkgrey",
    "boxplot.medianprops.color": "C6",
    "boxplot.notch": True,
    "axes.axisbelow": True,
    "axes.grid": True,
    "grid.color": "#A4A5AE",
    "grid.alpha": 0.5,
    "grid.linestyle": "--",
    "axes.grid.which": "major",
    "legend.shadow": True,
    "legend.facecolor": "inherit",
    "legend.framealpha": 0.95,
    "savefig.dpi": 320,
    "savefig.bbox": "tight",
    "scatter.edgecolors": "#343E3D",
    "hist.bins": "auto",
    "figure.constrained_layout.use": True,
}
sns.set_theme(rc=ex)
fig, (ax1, ax2) = plt.subplots(
    ncols=2, 
    sharey=True,
    figsize=plt.figaspect(0.5)
)
sns.boxplot(data=df_penguins, y="body_mass_g", ax=ax1)

ax2.boxplot(df_penguins.body_mass_g.dropna())
```
Here there's the output:

![download](https://user-images.githubusercontent.com/108257672/209946096-91b5ac1f-0586-42fc-a9b6-3fcfc88aceb2.png)

As you can see the colors of the boxprops, whiskerprops, capprops, and medianprops are not the ones I specified in the dictionary. Is this behavior expected?

**Comment by mwaskom** [comment]
Yes, it's expected. Seaborn boxplots are styled differently from matplotlib boxplots.

**Comment by mwaskom** [comment]
To elaborate slightly: the "defaults" for some of these parameters in seaborn boxplots are dynamic in way that can't be satisfied by the static rcParams, for example the line color adjusts to a gray value that provides adequate contrast with the face of the boxplot.

I also think these rc parameters just didn't exist when the function was originally written (back in 2013 or so).
