### ISSUE TITLE
Better support for faceted plots with plt.hexbin and plt.hist2d

### ISSUE THREAD

**Issue by shoyer** [mwaskom/seaborn#321]
Just to add two more items to my seaborn wish-list: It would great if `FacetGrid` and `PairGrid` worked well with hexbin and/or hist2d plots.
## Hexbin

`plt.hexbin` works, but the defaults are so bad that you can barely tell:

``` python
import seaborn as sns
df = sns.load_dataset('iris')
g = sns.FacetGrid(df, col='species', hue='species')
g.map(plt.hexbin, 'sepal_length', 'petal_length')
```

![image](https://cloud.githubusercontent.com/assets/1217238/4517881/6e915170-4c61-11e4-987b-364495d2f1a1.png)

Notice that by default `edgecolor` is controlled by the `hue` argument, which looks rather strange.

Tweaking some options makes a big difference (also solves the aesthetic issues in #271):

``` python
g.map(plt.hexbin, 'sepal_length', 'petal_length', gridsize=20, extent=[4, 8, 1, 7], edgecolor='none', mincnt=1)
```

![image](https://cloud.githubusercontent.com/assets/1217238/4517961/523f440a-4c66-11e4-809f-efbacf314ccd.png)
## Hist2D

``` python
g = sns.FacetGrid(df, col='species')
g.map(plt.hist2d, 'sepal_length', 'petal_length')
```

Nope!

```
AttributeError: Unknown property color
```

The culprit (also for the inability to control edgecolor with hexbin) is this line:
https://github.com/mwaskom/seaborn/blob/v0.4.0/seaborn/axisgrid.py#L418

If we move that statement inside the conditional on the next line (`if self._hue_var is not None`), then that solves the color issues with `hexbin` and I can get `hist2d` working. Again, the defaults are terrible:
![image](https://cloud.githubusercontent.com/assets/1217238/4517914/dda4063c-4c63-11e4-8f2a-c88b6478bba7.png)

When tweaked, it looks OK:

``` python
g = sns.FacetGrid(df, col='species')
g.map(plt.hist2d, 'sepal_length', 'petal_length', range=[[4, 8], [1, 7]], bins=[8, 6], cmin=1)
```

![image](https://cloud.githubusercontent.com/assets/1217238/4517917/4d5e586a-4c64-11e4-8ed4-46553f877df9.png)

(Yes, matplotlib uses totally different keyword arguments in `hexbin` and `hist2d` for all the control nobs, even if they are basically equivalent.)
## Action items
1. Can we safely apply my suggested patch? I'm guessing it breaks something else but I haven't run it through the test-suite yet.
2. How do you feel about tweaking defaults parameters based on the type of plot passed to `FacetGrid.map`? Perhaps the clearer solution is to write `sns.binplot` (mirroring `sns.kdeplot`) to provide a unified API with better defaults, which we could also use in `sns.jointplot`?
3. Ideally FacetGrid should have some sort of logic to set the `range`/`extent` argument for all these plots together based on the shared x and y limits.
4. Both these sorts of plots call for adding colorbar legends (see also #312, #313).
5. In any case, I would love to add a few examples to show off these kinds of plots in the Seaborn gallery (it's not obvious they can be done now).

**Comment by moritz-lotze** [comment]
Hi, has there been any developement on this? I've been running into the same issues.

Is there a preferred workaround other than the fix described above?

**Comment by mwaskom** [comment]
With #2125:

```python
g = sns.FacetGrid(penguins, col="species", hue="species")
g.map_dataframe(sns.histplot, x="culmen_length_mm", y="culmen_depth_mm")
g.set_axis_labels("Culmen length", "Culmen depth")
```
![image](https://user-images.githubusercontent.com/315810/84579382-57098800-ad9b-11ea-8cef-e848aeb19890.png)

It doesn't do hexbin. I think that will be a different (new) function.

**Comment by shoyer** [comment]
Gorgeous! Nice work @mwaskom !

**Comment by mwaskom** [comment]
Also should note: that plot will soon be easier to make by doing something like

```python
sns.distplot(
    data=penguins, x="culmen_length_mm", y="culmen_depth_mm",
    hue="species", col="species",
)
```

But that remains to be implemented.
