### ISSUE TITLE
so.Continuous().label(like = callable) provides two arguments

### ISSUE THREAD

**Issue by NickCH-K** [mwaskom/seaborn#3213]
Hi there, I'm loving `seaborn.objects`!

The docs for `so.Continuous().label()` say that it can accept a callable that consumes a number and returns a string. However, `so.Continuous()` appears to provide not just a number to this function, but also an index. This means that single-argument formatting functions can't be used (see `label_func3` below), and multi-argument formatting functions must be built with a second argument capable of taking an index. I can imagine that some formatting functions might like to get the index, so I can see why it might be done this way. But if it's not intended, maybe get rid of that second argument, or maybe just update the docs.

```python
import seaborn.objects as so
import pandas as pd

def label_func(x, decimals=0):
	basestr = '{:,.'+str(decimals)+'f}'
	return(basestr.format(x))
def label_func2(x, buffer = 0, decimals=0):
	basestr = '{:,.'+str(decimals)+'f}'
	return(basestr.format(x))
def label_func3(x):
	basestr = '{:,.1f}'
	return(basestr.format(x))

df = pd.DataFrame({'x':['a','b'],
				   'y':[3,4]})

# see first graph below; the index number appears to be fed in as the second argument
(so.Plot(df, x = 'x', y = 'y')
 .add(so.Bar())
 .scale(y = so.Continuous().label(like = label_func)))

# Second graph, this one works properly
(so.Plot(df, x = 'x', y = 'y')
 .add(so.Bar())
 .scale(y = so.Continuous().label(like = label_func2)))

# Error: label_func3() takes 1 positional argument but 2 were given
(so.Plot(df, x = 'x', y = 'y')
 .add(so.Bar())
 .scale(y = so.Continuous().label(like = label_func3)))
```

From `label_func`:
![Bar graph with more decimal places in the y-axis labels as we go up](https://user-images.githubusercontent.com/44816781/210895243-cd87c759-a881-4c4a-927c-9500b0645cac.png)

From `label_func2`:
![Bar graph with consistent decimal placement](https://user-images.githubusercontent.com/44816781/210895306-8e3d1641-53e9-441f-bc95-5ebd13a0c5ef.png)

**Comment by mwaskom** [comment]
Good catch on the incorrect documentation. As you've surmised, the expected signature for the callable is `f(value: float, pos: int) -> str`. Why? This is just a thin wrapper around [`matplotlib.ticker.FuncFormatter`](https://matplotlib.org/stable/api/ticker_api.html#matplotlib.ticker.FuncFormatter) which calls the provided function that way. I agree this is a little unintuitive and _perhaps_ seaborn could use `inspect` to wrap functions with a single parameter to throw away the `pos` argument. What about your `label_func` example through? That's a little trickier. 

Either way, the documentation should be fixed.
