### ISSUE TITLE
A violinplot in a FacetGrid can ignore the `split` argument

### ISSUE THREAD

**Issue by fabianegli** [mwaskom/seaborn#3219]
I try to produce a FacetGrid containing violin plots with the argument `split=True` but the violins are not split. See the following example:

```python
import numpy as np
import pandas as pd
import seaborn as sns
np.random.seed(42)
df = pd.DataFrame(
    {
        "value": np.random.rand(20),
        "condition": ["true", "false"]*10,
        "category": ["right"]*10 + ["wrong"]*10,
    }
)
g = sns.FacetGrid(data=df, col="category", hue="condition", col_wrap=5)
g.map(
    sns.violinplot,
    "value",
    split=True,  # it is irrelevant if this is present or not the violin plots are never split.
);
```

Plots can be seen here: https://stackoverflow.com/q/74617402/6018688

**Comment by jhncls** [comment]
Well, what happens is that `hue` is ignored when only `x` or `y` is given. This also happens with other categorical plots, also for single plots, e.g. `sns.boxplot(data=df, x="value", hue="category")` ignores the `hue`. It is unrelated to being part of a `FacetGrid` or not.  For a boxplot, one can just use `y=` instead of `hue=`, but not for a split violin plot.

**Comment by jhncls** [comment]
Related to #2676

**Comment by mwaskom** [comment]
That's not exactly right, the main problem here is that `hue` is being passed to the `FacetGrid`, but as the docs note:

> When hue is set on the [FacetGrid](https://seaborn.pydata.org/generated/seaborn.FacetGrid.html#seaborn.FacetGrid), however, a separate plot is drawn for each level of the variable. If the plotting function understands hue, it is better to let it handle that logic. But it is important to ensure that each facet will use the same hue mapping. In the sample tips data, the sex column has a categorical datatype, which ensures this. Otherwise, you may want to use the hue_order or similar parameter.

The `split` logic in `violinplot` depends on it knowing about the `hue` variable, which isn't the case the way it's being used here.

Although you're correct that `violinplot` also requires both `x` and `y` to be defined to use `hue`.

Anyway it looks like there's a nice solution in the linked stackoverflow example (use `catplot` and supply a constant `y` variable) so I'm going to close here.

**Comment by fabianegli** [comment]
Thank you all for the explanations and help! 💐
