### ISSUE TITLE
Log y-axis incorrectly labeled on boxplot

### ISSUE THREAD

**Issue by coreywoodruff** [mwaskom/seaborn#3222]
The two plots below are created with identical data. However, in one plot, the first labeled y tick is labeled 0, whereas in the second, it is labeled 2^(-1), which equals 1/2. None of the values in the table are less than zero.

The relevant code is:
```
f, ax = plt.subplots()
boxplot = sns.boxplot(x='geo_', y='values', hue='mde_ratio',  data=melt_mde)
plt.yscale('log', base=2)
ax.yaxis.set_major_formatter(mpl.ticker.ScalarFormatter())
```

<img width="686" alt="Screen Shot 2023-01-12 at 5 41 29 PM" src="https://user-images.githubusercontent.com/11283426/212210919-a65c1d7d-470e-4279-aa6d-12fb1cc3b904.png">
<img width="664" alt="Screen Shot 2023-01-12 at 5 39 17 PM" src="https://user-images.githubusercontent.com/11283426/212210656-1ae3b9c5-cca2-42be-a850-518fbf4b5958.png">

**Comment by mwaskom** [comment]
Please make this a reproducible example, otherwise I cannot help. You're also determining the ticklabel format through the matplotlib API, so I'm not sure why you are reporting this to seaborn.

**Comment by mwaskom** [comment]
Closing as not reproducible; I don't see any evidence that this is a seaborn issue.
