### ISSUE TITLE
weights not described in the `displot` documentation

### ISSUE THREAD

**Issue by zerothi** [mwaskom/seaborn#3226]
In https://seaborn.pydata.org/generated/seaborn.displot.html#seaborn.displot I cannot see exactly what arguments the `weights` argument will accept.

It is missing in the `Parameters` section.

**Comment by sarajcev** [comment]
I suppose that the `weights` parameter is used for sample weighting, which is pretty standard. 

When it is propagated to the `histplot` function, it is defined as follows:
```
weights : vector or key in data

    If provided, weight the contribution of the corresponding data points towards the count in each bin by these factors.
```
However, when it is propagated to the `kdeplot` function, it is defined as follows:
```
weights : vector or key in data

    If provided, weight the kernel density estimation using these values.
```
It might be useful to describe this argument in the docs of the `displot` function?
