### ISSUE TITLE
Subplot axis labels get lost when using set_xticklabels

### ISSUE THREAD

**Issue by santiagollaberia** [mwaskom/seaborn#3235]
Hi! I am working in a function to create multiple subplots to compare features distributions  based on the target class (classification model). I came across an issue when trying to set different characteristic to the x-axis from each subplot. 

The problem was that the x axis label got lost (could be retrieved by the corresponding method (`get_xticklabels()`). I was forced to to a workaround in order to solve it. I guess this might have been a problem for many more than myself.

This s the solution I used based on an StackOverFlow post.
``` python
figure, axes = plt.subplots(1, 2, sharex=True, figsize=(10, 5))

figure.suptitle('Graphs for X variable... WIP')

#####################
###  First Plot   ### --> Histogram of each distribution according to the class they belong to.
#####################

sns.histplot(data=df, x=col, hue='venta', bins=50, stat='density', common_norm=False, ax=axes[0])
axes[0].set_title('Histogram')
axes[0].set_xticklabels(df[col].unique().tolist())
axes[0].set_xticklabels([item.get_text() for item in axes[0].get_xticklabels()], rotation='vertical' if any(df[col].astype('str').str.len() > 6) else 'horizontal',
                        horizontalalignment='right')
axes[1].set_title('second chart with no data')

plt.show()
```

This is how it should work "normally" ( or at least what I would expect based on docs)

``` python

figure, axes = plt.subplots(1, 2, sharex=True, figsize=(10, 5))

figure.suptitle('Graphs for X variable... WIP')

#####################
###  First Plot   ### --> Histogram of each distribution according to the class they belong to.
#####################

sns.histplot(data=df, x=col, hue='venta', bins=50, stat='density', common_norm=False, ax=axes[0])
axes[0].set_title('Histogram')
axes[0].set_xticklabels(z.get_xticklabels(), rotation=45, horizontalalignment='right')
axes[1].set_title('second chart with no data')

plt.show()
```

I hope this ends up being useful to fix the issue or ,if I am assumptions were wrong, to clarify the documentation.

**Comment by mwaskom** [comment]
Hi, I am confused about the context here; `ax.set_xticklabels` is a matplotlib API. Why are you reporting this to seaborn?

**Comment by santiagollaberia** [comment]
Hi, I apologize if this was unrelated to seaborn. I must have misunderstood the interaction between matplotlib and yours. U will bring this up in their forum.

**Comment by santiagollaberia** [comment]
I will*
