### ISSUE TITLE
[Feature Request] sns.histplot() automatically supports discreted axis labeling.

### ISSUE THREAD

**Issue by kaimo455** [mwaskom/seaborn#3239]
# Background / related function desc
As the doc saids:
When both x and y are assigned, a bivariate histogram is computed and shown as a heatmap:
```python
sns.histplot(penguins, x="bill_depth_mm", y="body_mass_g")
```
![image](https://user-images.githubusercontent.com/23258141/215312148-a51a8e14-0640-4224-af42-96105436238f.png)
---

# The requested feature is that

**If the provided `x=` was a `Pandas Categorical DType`, well cause It's a cat dtype, so what I expected `seaborn` could treat it as discrete variable instead of continuous variable.**
Recalls that the `Pandas Categorical DType` it could be a `numeric cat` like `Categories (5, int64): [1 < 10 < 100 < 1000 < 10000]`, or `str cat` like `Categories (3, object): ['0', '10ms', '20ms', '30ms']`.
- If it's `str cat`, the `histplot` gives the expected result.
![image](https://user-images.githubusercontent.com/23258141/215312742-ee2d395b-f87e-4221-95b4-04582c9939b6.png)
- However, if `num cat`, and it just follows the numberic axis labeling.
![image](https://user-images.githubusercontent.com/23258141/215312764-f78046f4-5a31-4f90-9738-90350f0ae1b3.png)
Indeed, may be we can work around by using `log_scale=(True)`, but what if the `num cat` is not log-scale cat? Like `[1 < 200 < 1000< 1200]`.

# Currently best workaround I found
For those `num cat` dtype columns in dataframe, just convert to `str cat` first then apply histplot().
```python
df[col] = df[col].astype(str).astype('category')
sns.histplot(df, x=x, y=col)
```

**Comment by mwaskom** [comment]
I'm a little confused by this issue because I don't think it has anything to do specifically with _bivariate_ histograms and also you don't provide a reproducible example. (Are you claiming that when you have numerical categories the plot is empty? I cannot replicate that.)

Ultimately seaborn needs to put its data through matplotlib, which considers "categorical" to be identical to "string typed". To support what you are asking for, seaborn would need to modify the underlying data with a categorical dtype to always cast it to a string. That may work fine for integer values, but it could not do what you want/expect with floats or datetimes.

It's unlikely that a parameter-less solution would work and I don't think that each function should gain new parameter(s) to control this. On the other hand, the user-space solution is straightforward: convert your values to strings when you turn them into a categorical.

**Comment by jhncls** [comment]
I don't know whether it would be easy or adequate to change seaborn's behavior here.  Anyway, here is a reproducible example (using powers of 3, as powers of 10 cause too much emptiness):
```python
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

df = pd.DataFrame({'x': pd.Categorical(np.repeat([1, 3, 9, 27, 81], 200)),
                   'y': np.random.randn(1000).cumsum()})

fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(15, 5))
sns.histplot(data=df, x='x', y='y', ax=ax1)
ax1.set_title('Categorical and numerical')

df['x'].cat.categories = df['x'].cat.categories.astype('str')
sns.histplot(data=df, x='x', y='y', ax=ax2)
ax2.set_title('Categorical and string')

plt.show()
```
![image](https://user-images.githubusercontent.com/19649483/216450389-0c753baa-7762-4a05-abd6-0fd44bd7d1c3.png)

**Comment by mwaskom** [comment]
Thanks @jhncls that looks closer to what I was seeing when playing around. Would be more concerning if the plot were empty; here I think you can at least understand what's happening even if it's not the desired behavior.

For the function interface I'd probably lean towards not changing this, at least for now. Note that in the objects interface you'd be able to explicitly assign a `Nominal` scale and that *would* coerce to strings and hence use a categorical axis (also, the format of the conversion can be specified). That said, there's not currently support for bivariate histograms in the object interface.

**Comment by kaimo455** [comment]
@mwaskom @jhncls Thanks for your replies, and sorry about the ambiguous request.

Thanks to @jhncls made the "feture request" clearer, It's almost excatly what I mean, but without meationing the `pandas.Categorical DType`, I expect seaborn could take(detect) the `Categorical DType`, once a variable is defined as categotical, we always expect that variable behavors as discrete variable(like convert as `str` dtype then plot).

But whatever, _"feature request is easy, but coding is suffering :smile:"_. I agree with @mwaskom that It's better to keep the current interface, as you metioned above, convert it into `str` dtype by user is a better solution.

Belows are codes that repoduces the issue.

---

## Work Normally Case
```python
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

def create_data():
    return pd.DataFrame(columns=['x', 'y'],
                  data=[[1, 'a'],[2, 'a'],[1, 'a'],[3, 'a'],[4, 'a'],[5, 'a'],[1, 'b'],[2, 'b'],[2, 'b'],[3, 'b'],[4, 'b'],[5, 'b'],[1, 'c'],[2, 'c'],[2, 'c'],[3, 'c'],[4, 'c'],[5, 'c'],[5, 'c'],]
                  )
df = create_data()
plt.figure(figsize=(4,2))
sns.histplot(df, x='x', y='y', discrete=(True, True))
```
**Here the x-axis ranges from [1, 5], while y-axis contains {'a', 'b', 'c'}**. Notice tha I also use `discrete=(True, True) to make seaborn takes them as discrete variables.`
![image](https://user-images.githubusercontent.com/23258141/217034247-7aa671cd-001a-47c1-93f5-d099cf65d703.png)

---

## Not Work Well Case

```python
def append_data(df):
    return pd.concat([df, pd.DataFrame(columns=['x', 'y'],
                                 data=[[100, 'a'],[110, 'a'],[100, 'c'],[100, 'c'],[500, 'a'],[500, 'b'],
                                 ])], axis=0, ignore_index=True)
df = create_data()
df = append_data(df)
plt.figure(figsize=(4,2))
sns.histplot(df, x='x', y='y', discrete=(True, True))
```
![image](https://user-images.githubusercontent.com/23258141/217038094-2d3b1eb3-d796-42cb-9b8c-239024837cd7.png)
**As @jhncls metioned, we can use `log` to handle this but not always the logarithm case.**

---

**However, when I encountered this issue at the first time, I read the histplot doc, tried setting `discrete=(True,...)` but not work, then I tried to convert the 'x' column data into `Pandas.Categorical DType`, but still. Finally I resolve it by converting to `str DType`.**

## Work Around Solution
```python
df = create_data()
df = append_data(df)
df['x'] = df['x'].astype(str)
plt.figure(figsize=(4,2))
sns.histplot(df, x='x', y='y', discrete=(True, True))
```
![image](https://user-images.githubusercontent.com/23258141/217039498-c70290c3-7684-4323-b057-fee19a514923.png)

---

#### To conclusion, the feature reqeust here is that: wishing seaborn could take the `Pandas.Categorical DType` like `str` to plot :smile:
