### ISSUE TITLE
sns.histplot has a mystery/ghost patch, new with update from 0.11.2--> 0.12.2

### ISSUE THREAD

**Issue by PhillipMaire** [mwaskom/seaborn#3241]
the problem is outlined here in this colab notebook 
https://colab.research.google.com/drive/1i69qTX1SPSPKogUBa2tMUmjC3cHO_VPn?usp=sharing

sns.__version__, mpl.__version__
('0.11.2', '3.2.2')
displot and histplot display correct patched when finding the patched plotted as a hist (used for key) 
<img width="446" alt="image" src="https://user-images.githubusercontent.com/19584564/216197437-d795dc89-93ab-48a1-b469-6c89e86171f7.png">

sns.__version__, mpl.__version__
('0.12.2', '3.6.3')
there is a blue patch somewhere only for histplot but not for displot

<img width="435" alt="image" src="https://user-images.githubusercontent.com/19584564/216197516-74cfe9ec-eaf8-4640-996d-85c46fa1d505.png">

**Comment by mwaskom** [comment]
Please convert this to a reproducible example.

**Comment by PhillipMaire** [comment]
```
colors_in = ['y', 'r']
tmp1 = pd.DataFrame([[  1.,   1.],
[  1.,   0.],
[  9.,   7.],
[-10.,   1.],
[  5.,   2.],
[  0.,   0.],
[  0.,   0.]])

sns.histplot(data=tmp1, kde=True, multiple='layer', palette=colors_in, alpha=.5)
plt.legend(['KDE_1', 'KDE_2', 'name_1', 'name_2'], loc='upper right', bbox_to_anchor=(.7, .5, 0.5, 0.5), fontsize = 18)  
```
<img width="463" alt="image" src="https://user-images.githubusercontent.com/19584564/216199563-7a6a0298-a37d-4d26-8920-77f91aa0d755.png">

**Comment by PhillipMaire** [comment]
or I guess this is even simpler 
```
colors_in = ['y', 'r']
tmp1 = pd.DataFrame([[  1.,   1.],
[  1.,   0.],
[  9.,   7.],
[-10.,   1.],
[  5.,   2.],
[  0.,   0.],
[  0.,   0.]])

sns.histplot(data=tmp1, multiple='layer', palette=colors_in)
plt.legend(['name_1', 'name_2'])
```
<img width="400" alt="image" src="https://user-images.githubusercontent.com/19584564/216199991-99b980be-f8f0-46fb-aa14-1c5c408b0d85.png">

My guess is that blue is the default value and somehow even when passing in another color, it uses blue instead. for example  either a hard code issue that was meant to be temporary? just a guess

**Comment by mwaskom** [comment]
Calling `plt.legend` like that is not supported behavior (or a good idea); you're making assumptions about the existence and order of labeled artists attached to the axes.

**Comment by jhncls** [comment]
As Seaborn creates rather complicated plots with many options, and tries to have legends with compact information, legends are build up from custom elements. Matplotlib's default legend, on the other hand, searches for labeled graphical elements in the plot. Or, when only given labels are provided, matplotlib searches for all suitable elements.

A real best practice doesn't exist for what you want to achieve. Below is an approach that works with the current Seaborn/matplotlib versions, but still depends on where in the `ax` the elements happen to be.
```python
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

colors_in = ['y', 'r']
tmp1 = pd.DataFrame([[1., 1.], [1., 0.], [9., 7.], [-10., 1.], [5., 2.], [0., 0.], [0., 0.]],
                    columns=['name_1', 'name_2'])
ax = sns.histplot(data=tmp1, kde=True, multiple='layer', palette=colors_in, alpha=.5)

ax.lines[0].set_label('KDE 1')  # leave this out if it's not needed in the legend
ax.lines[1].set_label('KDE 2')
for bar in ax.containers[1]:
    bar.set_hatch('//')
ax.containers[1].set_label('name_1')
ax.containers[2].set_label('name_2')

ax.legend(loc='upper right', bbox_to_anchor=(1, 1), fontsize=12)
plt.show()
```
![image](https://user-images.githubusercontent.com/19649483/216443641-a617108c-5fe0-40e1-bde6-a37e96eeea93.png)

**Comment by PhillipMaire** [comment]
Okay makes sense! thanks you so much, I didn't even know about `ax.containers`. That makes it much easier to work with the sets of bars. I was stuck trying to set hatches based on `ax.patches` combined with number of patches (bins) for each color, which isn't clean at all. 

thank you both for your help, I'll close the issue now.

**Comment by mwaskom** [comment]
I'd actually suggest a slightly different approach which would be to add artists to hatches based on their color and to modify the legend handles themselves directly:

```python
from matplotlib.colors import same_color, to_rgb

tmp1 = pd.DataFrame([[  1.,   1.],
[  1.,   0.],
[  9.,   7.],
[-10.,   1.],
[  5.,   2.],
[  0.,   0.],
[  0.,   0.]])

colors_in = ['y', 'r']
hatch_color = colors_in[-1]

ax = sns.histplot(data=tmp1, palette=colors_in)

for patch in ax.patches:
    if same_color(to_rgb(patch.get_facecolor()), hatch_color):
        patch.set_hatch("//")

legend = ax.get_legend()
for h in legend.legend_handles:
    if isinstance(h, mpl.patches.Rectangle) and same_color(to_rgb(h.get_facecolor()), hatch_color):
        h.set_hatch("//")
```

![image](https://user-images.githubusercontent.com/315810/216968898-381f3183-76b8-4be6-8682-fd8c62d2a75c.png)

This way you're not making any assumptions about artist order and will ensure that the hatching information represents the same variable as the color information.

BTW the underlying issue here is something that we can address (https://github.com/mwaskom/seaborn/pull/3246) but I'd still strongly recommend learning how to make any post-hoc manipulations like this explicit rather than implicit, because otherwise you're bound to get yourself into trouble at some point.

**Comment by PhillipMaire** [comment]
Thanks for the the detailed approach! I see your point and will be careful to not make that assumption again, much appreciated!
