### ISSUE TITLE
ipywidgets should not be imported for non-IPython users

### ISSUE THREAD

**Issue by davidgilbertson** [mwaskom/seaborn#3242]
On this line: https://github.com/mwaskom/seaborn/blob/master/seaborn/widgets.py#L6 `ipywidgets` is imported without first checking if the user is running in an environment that supports them. In theory this should be harmless but in reality it causes an error in PyCharm (when not using IPython):
```
Matplotlib support failed
Traceback (most recent call last):
  File "/mnt/c/Users/david/AppData/Local/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 25, in do_import
    succeeded = activate_func()
  File "/mnt/c/Users/david/AppData/Local/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/plugins/python/helpers/pydev/pydev_ipython/matplotlibtools.py", line 156, in activate_pylab
    pylab = sys.modules['pylab']
KeyError: 'pylab'
```

[PyCharm issue is here](https://youtrack.jetbrains.com/issue/PY-49631/PyCharm-tries-to-sys.modulatespylab-but-pylab-has-not-been-imported-yet)

This is not really a fault of Seaborn, but I think it would be good practice regardless to not spend time importing IPython things when not required.

**Comment by mwaskom** [comment]
Why do you think this has something to with `IPython`? `pylab` is a matplotlib construct. I'm able to import `ipywidgets` without issue in a base Python interpreter.

How do you propose seaborn detect whether someone is an "IPython-user"? (I do think that one can import IPython and find some state that would tell you, but I'm skeptical that doing so would be lighter-weight than simply importing the ipywidgets library).

**Comment by davidgilbertson** [comment]
The reason I assumed IPython is because when seaborn is imported, a side effect is that PyCharm goes into some branch of it's code in a file `pydev_ipython/matplotlibtools.py`, this gets triggered at the line where Seaborn imports ipywidgets. In short, `ipywidgets` loads a bunch of stuff, including a module called `pydev` that PyCharm tries to patch with some dodgy logic and that fails.

As for how to detect, I'm not sure. I was assuming something like `if 'get_ipython' in globals():` but I'm sure there are some traps, and differences between versions. Also that detects IPython not Jupyter notebook specifically, so I guess it depends on what the widgets are for.

**Comment by mwaskom** [comment]
How are you diagnosing it as being triggered by the ipywidgets import? I don’t see seaborn anywhere in the stacktrack you show.

**Comment by davidgilbertson** [comment]
It's triggered by any import of `ipywidgets`, you can create an empty file with nothing but either `import seaborn` or `import ipywidgets` and get the error. And there would be the same issue if any other package imported `ipywidgets` for non-IPython users.

I found that it was `seaborn` importing `ipywidgets` by putting a pdb breakpoint in the PyCharm source and stepping backward.

**Comment by mwaskom** [comment]
I appreciate that the pycharm error is annoying but i'm hesitant to assume that the widgets would only ever be used "in an ipython session" (as defined by checking for that global variable). If nothing else, seems that would make it impossible to test them (although to be fair I do not believe that they are currently well tested!)

Aside from getting the underlying pycharm issue fixed, if you're regularly working in pycharm without using ipython, seems that you could define an environment that does not include ipywidgets, in which case the import statement should pass?

**Comment by davidgilbertson** [comment]
Good point about the testing, although you could always just load IPython. But yeah, it does seem like trying to resolve this in Seaborn might be a bit hackish.

I default to using IPython, but some libraries don't play nice (e.g. Hugging Face datasets with multiprocessing fails in IPython) so in those cases I revert to the vanilla interpreter.
