### ISSUE TITLE
Seaborn PairGrid Error - AttributeError: module 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by claysmyth** [mwaskom/seaborn#3243]
Hi, I believe PairGrid is calling a a deprecated attribute from numpy (for recent version of numpy >= 1.23.5)

![Screen Shot 2023-02-01 at 10 10 21 PM](https://user-images.githubusercontent.com/39106407/216245643-c621d6de-acd6-4a38-9cc3-065106e75376.png)

**Comment by mwaskom** [comment]
Please provide a reproducible example.

**Comment by claysmyth** [comment]
@mwaskom 
Thanks for looking into this!

With package versions:
numpy = 1.24.1
seaborn = 0.10.1
pandas = 1.5.3

the following code yields the following error:

`import seaborn as sns
import pandas as pd
import numpy as np
print("numpy version: " + np.version.version)
print("seaborn version: " + sns.__version__)
print("pandas version: " + pd.__version__)

df = pd.DataFrame({"A": np.arange(10), 'B': np.arange(10,20), 'C': np.arange(100,200,10)})

g = sns.PairGrid(df)
g.map(sns.scatterplot)`

<img width="1256" alt="Screen Shot 2023-02-03 at 10 13 36 AM" src="https://user-images.githubusercontent.com/39106407/216676853-0e1fcceb-e284-4fad-be59-c262004fdf51.png">

**Comment by mwaskom** [comment]
Seaborn 0.10.1 is several versions old.

**Comment by mwaskom** [comment]
Closing as this is not currently reproducible and the report comes from a very old version.
