### ISSUE TITLE
Feature request: supporting stacked bars in barplot() and catplot()

### ISSUE THREAD

**Issue by ekcomputer** [mwaskom/seaborn#3244]
Hello,

Although MPL allows a `height` argument to `plt.bar`, `sns.barplot` and `sns.catplot` don't easily support stacked bars. There are workarounds such as described [here](https://www.python-graph-gallery.com/stacked-and-percent-stacked-barplot) that require many lines of code to "hack" a stacked bar plot.

This functionality is present in `sns.displot` which allows a `multiple=stacked` argument. I expect the community would appreciate this option in the other barplot-style plots.

Thanks for all your great work maintaining this package!

-Ethan

**Comment by thuiop** [comment]
You can easily do it with the objects API.

**Comment by ekcomputer** [comment]
And so I can- thanks for the tip! For those like me who aren't familiar with the new `seaborn.objects` API, the following example code produced the stacked bar plot I was trying to make:

```python
from seaborn import objects as so
so.Plot(df, x="Categorical_variable_1",  y="value",  color='Categorical_variable_2').add(so.Bar(), so.Agg(), so.Stack())
```
where `Bar`, `Agg`, and `stack` signify plotting stacked bars aggregated by the mean of each grouping.
