### ISSUE TITLE
Several test failures due to matplotlib no longer auto-flattening inputs to pcolormesh

### ISSUE THREAD

**Issue by IAlibay** [mwaskom/seaborn#3245]
Context: We noticed some seaborn failures downstream when testing on the nightly matplotlib wheels.

It turns out that a recent change in matplotlib's dev branch (https://github.com/matplotlib/matplotlib/pull/24638) is causing `matrix._HeatMapper._annotate_heatmap` to fail because calls to pcolormesh are no longer flattened and by consequence changes the return value of `get_facecolor`.

There are also various test failures in `test_matrix` and `test_distribution` which fail due to comparisions between flattened & non-flatttened arrays.

**Comment by mwaskom** [comment]
If this is not something matplotlib has overtly deprecated can you please put together a (seaborn-less) reprex and flag to them?

**Comment by mwaskom** [comment]
Also not being familiar with your test suite do you think that you could link more specifically to the failing test or provide a reprex here? I don't really understand exactly what the issue is from your description what the implications of "auto-flattening" would be.

**Comment by IAlibay** [comment]
> Also not being familiar with your test suite

@mwaskom I think there might be a misunderstanding here, the failures I'm outlining above are in the seaborn testsuite.

My understanding of https://github.com/matplotlib/matplotlib/pull/24638 is that matplotlib is fixing what they consider to be undesirable behaviour with the way matplotlib's pcolormesh worked. I don't have a particular disagreement with that change, unfortunately all I can do is advise that seaborn as-is does would fail under the latest nightly build with matplotlib.

**Comment by IAlibay** [comment]
>  I don't really understand exactly what the issue is from your description what the implications of "auto-flattening" would be.

I would be happy to add a new set of CI tests that checks against nightly builds of numpy/pandas/matplotlib/scipy if this help?

**Comment by mwaskom** [comment]
That wasn't clear; I just clicked through to the PR on your repository ...

Maybe you could upload the test logs as a txt file?

**Comment by IAlibay** [comment]
> Maybe you could upload the test logs as a txt file?

@mwaskom Please see attached.
[seaborn-matplotlib-nightly.txt](https://github.com/mwaskom/seaborn/files/10628384/seaborn-matplotlib-nightly.txt)

**Comment by IAlibay** [comment]
[seaborn-matplotlib-nightly.txt](https://github.com/mwaskom/seaborn/files/10630112/seaborn-matplotlib-nightly.txt)
@mwaskom please see attached (apologies about the previous ping, I accidentally copied test results with the non-dev version of matplotlib).

**Comment by mwaskom** [comment]
Thanks!

**Comment by mwaskom** [comment]
Based on https://github.com/matplotlib/matplotlib/issues/25162, matplotlib is going to roll back this change and make quadmesh facecolor flattening an opt-in operation at access time. I think the implications are that this will unbreak heatmap, and seaborn won't need to do anything (but we can consider accessing the non-flattened array in the future if it will simplify our code).

**Comment by mwaskom** [comment]
This has been addressed upstream.
