### ISSUE TITLE
 common_norm for kdeplot with multiple="stack" 

### ISSUE THREAD

**Issue by perinom** [mwaskom/seaborn#3248]
I just noticed that in in `kdeplot` when `multiple=stack` the setting of `common_norm` is ignored, and always considered True.

when setting `multiple=layer`  everything works as expected and `common_norm=False` results in independently normalised densities. 

I see that this might depend on the fact that stacking distributions without transparencies might mask some of the lower ones and proper visualization can happen only with common normalization, but if this behaviour is intentional a warning/error and a mention in the documentation would be very helpful

**Comment by mwaskom** [comment]
Please provide reproducible example.

**Comment by perinom** [comment]
code-wise
``` 
fig, axs = plt.subplots(nrows = 1 , ncols = 3, figsize = (14, 4))
axs      = axs.ravel()
palette  = {"V5_PB":"#969696","V5_NC14":"#525252", "KO_PB":"#41ab5d", "KO_NC14":"#006d2c"}

ax= axs[0]    
sns.kdeplot(data = df, x="score", hue = "name", multiple="stack", bw_adjust=.25, ax = ax, palette = palette, common_norm = True)
ax.set_title("multiple = stack common_norm = True", fontsize = 12)

ax= axs[1]    
sns.kdeplot(data = df, x="score", hue = "name", multiple="stack", bw_adjust=.25, ax = ax, palette = palette, common_norm = False)
ax.set_title("multiple = stack common_norm = False", fontsize = 12)

ax= axs[2]    
sns.kdeplot(data = df, x="score", hue = "name", multiple="layer", bw_adjust=.25, ax = ax, palette = palette, common_norm = False)
ax.set_title("multiple = layer common_norm = False", fontsize = 12)
plt.tight_layout()
```

df looks like this, it's big but I'm happy to share it if you have a favourite way

```
   chrom  start  end  name  score  strand
chr2L  4882  5082  V5_NC14  77.819647  .
chr2L  4882  5082  V5_PB  69.782085  .
chr2L  5032  5232  KO_NC14  57.674357  .
chr2L  5032  5232  KO_PB  57.206011  .
chr2L  5117  5317  V5_NC14  55.852888  .
```
![snskdeplot](https://user-images.githubusercontent.com/44227478/217540234-43daf875-5395-4509-a665-122d39b677e7.png)

**Comment by mwaskom** [comment]
This isn’t reproducible. Please read the contribution guidelines for steps on how to make an actionable bug report.

**Comment by mwaskom** [comment]
However, just looking at your plot, I do not understand why you think common norm is being ignored in the stacked version. The y axis scale is completely different?

**Comment by perinom** [comment]
I have a couple of deadlines coming up and I can't play to make an artificial dataset that reproduces. I can share the actual if of interest.

RE: your second comment
Shouldn't the area under each curve be 1 with independent normalization? The area under each curve in plot #2 is clearly different form the others, as they are contained within each other.
Also, the scale is different between plots #2 and #3 where theoretically only the visualization should be different

**Comment by mwaskom** [comment]
I think it’s possible that you’re just not understanding the purpose of common norm. I don’t see evidence of a bug here, so I am going to close. Feel free to ask on stackoverflow if you need more support. 

Please appreciate that the person you are asking for help from also has deadlines and other obligations; vague and non-actionable issues waste time that is better spent on more productive development tasks. (Also, had you read the contribution guidelines, you would note that example datasets are provided to make it easier to generate reproducible bug reports).
