### ISSUE TITLE
Figure level plot BUG

### ISSUE THREAD

**Issue by ryrl9703** [mwaskom/seaborn#3252]
When I set the fontdict in g.set_yticklabels(fontdict={'fontsize': 16, 'fontweight': 'bold'}) ,  the labels of the y tick will loss while g.set_xticklabels(fontdict={'fontsize': 16, 'fontweight': 'bold'}) will not. Is this a BUG?
![Xnip2023-02-09_09-17-27](https://user-images.githubusercontent.com/87462884/217689981-367d8d0a-592b-4daa-a807-7c24d90a7d8b.jpg)

**Comment by mwaskom** [comment]
I don't know if it's a BUG. This is not a reproducible example so it is impossible to comment.

**Comment by mwaskom** [comment]
Closing for lack of response.

Happy to reopen with a reproducible example demonstrating a problem.
