### ISSUE TITLE
How to add stripplot under boxplot

### ISSUE THREAD

**Issue by teanijarv** [mwaskom/seaborn#3256]
It seems that stripplot (or swarmplot) are automatically always added on top of boxplot even if I call one function in front of the other.

Am I missing something here? How to add stripplot behind the boxplot?

I am actually only using boxplots to use the 'mean' with diamond marker.
<img width="568" alt="Screenshot 2023-02-12 at 11 41 54 am" src="https://user-images.githubusercontent.com/24492129/218288513-26c7950d-ee66-49a0-a563-4dcdd614ba1d.png">

**Comment by mwaskom** [comment]
Please ask [usage questions on stackoverflow](https://github.com/mwaskom/seaborn/blob/c44bce1035ee6f004ffc73a41d7d9e8e2b9a1cd8/.github/CONTRIBUTING.md#general-support) (and I reccommend including a reproducible example when you do so that people can help you). Thanks!
