### ISSUE TITLE
Legends include extraneous entries for categorical variables

### ISSUE THREAD

**Issue by jonahpearl** [mwaskom/seaborn#3258]
(I understand that legends are a can of worms, and if the answer to this particular question is, we thought about it and it's a mess, that's ok, but thought I'd bring it up just in case.)

When you pass in a column with a restricted set of values to something like `hue`, only the categories used in the view of the data make it into the legend:
```
from seaborn import scatterplot
import numpy as np 

tmp = pd.DataFrame({
    'x': np.tile(np.arange(10), 3),
    'y': np.repeat(np.arange(10), 3),
    'catg': np.random.choice(['a', 'b', 'c'], size=30)
})
scatterplot(data=tmp.loc[tmp.catg=='a', :], x='x', y='y', hue='catg')
```
![image](https://user-images.githubusercontent.com/68478436/218569595-2be7c702-96a0-4094-a37f-2c1dffe2987c.png)
that is to say, 'b' and 'c' aren't in the legend.

However, if you cast to categorical type, then you get extra legend entries:
```
tmp = tmp.astype({'catg': 'category'})
scatterplot(data=tmp.loc[tmp.catg=='a', :], x='x', y='y', hue='catg')
```
![image](https://user-images.githubusercontent.com/68478436/218569930-b1ac0bd2-fca7-4d13-9fd7-aac830b91b07.png)

I imagine this is because even when you subset the original df, the list of categories stays with the column, and seaborn takes that list as the set of values to be used in the legend.

This would be convenient / efficient in the case where there are huge numbers of categories and you don't want to check which ones are used in the data. However, my guess is that that's an edge case, and the more common case is that there are 5-10 categories, and the user wants to plot 0-a few of them. I would expect default behavior to only show the ones used, and maybe have a kwarg for showing them all.

The only way around this I see, given seaborn's current behavior, is to cast the column to a string just before plotting, or make a copy of the df, neither of which is particularly desirable. Let me know if I'm missing something obvious. Thanks!

**Comment by mwaskom** [comment]
This is definitely the way it was designed to work; if you search I think you’ll find a thread with a lot of back and forth about it. 

I think pandas categoricals might have a method to drop unobserved categories?

**Comment by jonahpearl** [comment]
Cool, TIL: https://pandas.pydata.org/docs/reference/api/pandas.Series.cat.remove_unused_categories.html#pandas.Series.cat.remove_unused_categories

Thanks!

**Comment by jonahpearl** [comment]
For anyone wondering later:

```
tmp = tmp.astype({'catg': 'category'})

# works but prob slow due to conversion
scatterplot(data=tmp.loc[tmp.catg=='a', :].astype({'catg': str}), x='x', y='y', hue='catg')  

# presumably still O(n) but no dtype conversion. not sure there's any easy one-line way since the remove_unused_categories operates on Series.
view = tmp.loc[tmp.catg=='a', :]
tmp_cats = view.catg.cat.remove_unused_categories()  
scatterplot(data=view, x='x', y='y', hue=tmp_cats)
```
