### ISSUE TITLE
lineplot misplots data with matching x value with sort=false

### ISSUE THREAD

**Issue by jazzlw** [mwaskom/seaborn#3262]
When plotting data using `sns.lineplot` and  `sort=false`, if two of the x values are equal, the y value for one of the points is misplotted and a discontinuity is added to the plot that is not in the data.

An example is show below, where two x values are made equal and the plot breaks, though scatterplot still  works fine.  One of the x values is then moved by a very small amount and the plot comes out as it should.

MWE:
```
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

# here the x values are all unique, and the plot works fine.
ys = np.linspace(0,7,100)
xs = np.sin(ys)
sns.lineplot(x=xs, y=ys, sort=False)

#make two x values the same and you break the lineplot, but not the scatterplot
plt.figure()
xs[6] = xs[95]
sns.lineplot(x=xs, y=ys, sort=False)
sns.scatterplot(x=xs, y=ys)

# Make the x value very slightly different and it's fixed.
plt.figure()
xs[6] += 0.0001
sns.lineplot(x=xs, y=ys, sort=False)
```
<img width="378" alt="Screen Shot 2023-02-15 at 4 16 44 PM" src="https://user-images.githubusercontent.com/20934382/219167560-ffacf9b2-e3b2-42b6-a9ef-18756af3c5c6.png">

**Comment by mwaskom** [comment]
What version of seaborn? This sounds like a dupe of a fixed issue

**Comment by jazzlw** [comment]
Above was with  0.12.2

**Comment by mwaskom** [comment]
Oh wait, looking more closely this is expected; you also need to set `estimator=None`.

**Comment by jazzlw** [comment]
oh, wow, of course. 
thanks a bunch, that was driving me crazy!
