### ISSUE TITLE
Color not changing

### ISSUE THREAD

**Issue by pablotucu** [mwaskom/seaborn#3263]
Hi! I'm trying to change colors in seaborn but it's having no effect?
<img width="706" alt="Captura de pantalla 2023-02-15 a la(s) 21 53 02" src="https://user-images.githubusercontent.com/119420090/219230518-91d40820-51b1-4d11-b724-408e0b5525e1.png">

**Comment by mwaskom** [comment]
I'm not sure what you're expecting to happen here. I suggest making a reproducible example and asking on StackOverflow.
