### ISSUE TITLE
Wrong ylim using pairplot

### ISSUE THREAD

**Issue by kebuAAA** [mwaskom/seaborn#3268]
`pairplot` seems not to support `sharey=True` like `FacetGrid`. This may cause unnecessary problems if I have a draw a plot with different ylims using `pairplot`. Just take the iris dataset for an example.
```python
import matplotlib.pyplot as plt

import seaborn as sns
iris = sns.load_dataset('iris')

# pairplot() example
g = sns.pairplot(iris, kind='scatter', diag_kind='hist', grid_kws=dict('sepal_length'))
plt.show()
```
![image](https://user-images.githubusercontent.com/96560962/219926017-bc390076-e2be-4f59-884f-83f34002b8d5.png)
Though passing `'sepal_length'` to the function, the ylim of histogram is not the right value I want. If I use `sns.hisplot` to draw the histogram of sepal_length in iris dataset, the ylim is (0,25).
```pthon
sns.histplot(iris,x='sepal_length')
```
![image](https://user-images.githubusercontent.com/96560962/219927545-5ba87c86-91c6-4854-9cfd-2069e211b64c.png)

**Comment by kebuAAA** [comment]
So sorry to paste the wrong code. The right code using `pairplot` is shown as below：
```python
import matplotlib.pyplot as plt

import seaborn as sns
iris = sns.load_dataset('iris')

# pairplot() example
g = sns.pairplot(iris, kind='scatter', diag_kind='hist',
                 grid_kws=dict(diag_sharey=False))
plt.show()
```
![image](https://user-images.githubusercontent.com/96560962/219953909-8e328f29-0204-436d-90b0-557eafc89642.png)

My problem is that I am not quite sure about the meaing of y-value in histogram of the above picture. Comparing the histogram rendered in the above picture with the picture rendered by `sns.histplot(iris,x='sepal_length')`, you can obviously find that  the y value is quite different. 
![image](https://user-images.githubusercontent.com/96560962/219954020-92e02649-858f-412d-bf60-eef8913efd07.png)
It seems that the histogram rendered by `sns.pairplot`  isn't the true frequency of  sepal_length, which is what I expect to get.

**Comment by mwaskom** [comment]
The y axis corresponds to the scatter plots, as in the other rows.

Closing as this is working as expected. If you're trying to do something specific, I suggest making a reproducible example and asking on StackOverflow.
