### ISSUE TITLE
Using color breaks so.Line when there is only one row per class

### ISSUE THREAD

**Issue by joeyo** [mwaskom/seaborn#3274]
Using this data:
```
data = pd.DataFrame(
    {
        "category": ["A", "B", "C", "D", "E"],
        "x": [450, 610, 4160, 9662, 127000],
        "y": [500, 152.26, 54.76, 40.42, 0.8]
    }
)
```

I can plot the individual points using `so.Dot` and/or `so.Line`:

```
so.Plot(data=data, x="x", y="y").add(so.Dot()).add(so.Line())
```
![foo](https://user-images.githubusercontent.com/372147/220770999-f81efeb7-cac3-4a01-a380-577e5452cd7b.png)

However, coloring the points by category breaks `so.Line` (`so.Dot` still works):
```
so.Plot(data=data, x="x", y="y", color="category").add(so.Dot()).add(so.Line())
```
![bar](https://user-images.githubusercontent.com/372147/220771350-5422bc86-50b2-48a8-96c1-623ca8b6d77d.png)

Forcing `so.Line` to have a fixed color does not rescue the chart:
```
so.Plot(data=data, x="x", y="y", color="category").add(so.Dot()).add(so.Line(color="k"))
```
![aaa](https://user-images.githubusercontent.com/372147/220772604-19faf5fd-8bb9-46ff-b1a1-82e7f7b716d2.png)

Presumably this is because seaborn cannnot plot a line with a single point, and there is only one row for each category. Here is an example with one of the standard datasets which have multiple elements per class that works as I would expect:
```
healthexp = sns.load_dataset("healthexp")
so.Plot(healthexp, x="Year", y="Life_Expectancy", color="Country").add(so.Dot()).add(so.Line())
```
![baz](https://user-images.githubusercontent.com/372147/220771854-1bcf5e29-2152-4e28-b8ee-8593f4a96999.png)

I don't quite see a way to layer the charts using the objects interface. My workaround is to make the line chart directly using matplotlib directly and then using `p.on(ax)` to draw the colored points on top, but it would be nice to do everything from within seaborn.

Python 3.10.10
Seaborn 0.12.0

**Comment by mwaskom** [comment]
I’m not sure I understand what you expect to happen here. How do you draw a line with a single observation?

**Comment by joeyo** [comment]
Ah, after experimenting, I find that I can get the behavior I want with `color=None` within the call to add():
```
so.Plot(data=data, x="x", y="y", color="category").add(so.Dot()).add(so.Line(), color=None)
```
![foobar](https://user-images.githubusercontent.com/372147/220802829-a5fb5692-1be2-4ed6-83b8-34aaf9c833f6.png)

**Comment by mwaskom** [comment]
Oh I see. Yes, either that or only pass `color="category"` in the `Dot` layer.

https://seaborn.pydata.org/tutorial/objects_interface.html#layer-specific-mappings
