### ISSUE TITLE
Please provide more information for: The condensed distance matrix must contain only finite values.

### ISSUE THREAD

**Issue by dorkylever** [mwaskom/seaborn#3280]
This printout is useless because: 

1) I don't know the exact formula to reproduce distance matixes.

2) It's caused by multiple issues and it's not a simple fix. 

3) It should provide an alternative method

**Comment by dorkylever** [comment]
For example - the following dataset was caused by the row-wise Z-normalisation creating NaNs for a partiular row. 

url= "https://raw.githubusercontent.com/dorkylever/LAMA/master/lama/tests/clustermap_data.csv"
    X = pd.read_csv(url, index_col=0)
    X.fillna(1, inplace=True)
    # replace missing values with 1


    print("Missing values:", X.isnull().sum().sum())
    print("Infinite values:", np.isposinf(X).sum().sum()+np.isneginf(X).sum().sum())


    X=X.apply(zscore, axis=1)
    print(X)
   
   # Z normalisation results in NAs.
    X.dropna(inplace=True)

    cg = sns.clustermap(X,
                        metric="euclidean",
                        cmap=sns.diverging_palette(250, 15, l=70, s=400, sep=40, n=512, center="light",
                                                   as_cmap=True),
                        center=0,
                        cbar_kws={'label': 'mean volume ratio'}, square=True,
                        figsize=[30, len(X) * 0.3])

**Comment by dorkylever** [comment]
Missing values: 0
Infinite values: 0
                                                    211219_Ku_C3H_56_e5_het  ...  220319_C3H_Ku_74_e4_het
radiomic_name                                                                ...                         
original shape SurfaceVolumeRatio bladder wall                     2.884197  ...                -0.261776
original shape SurfaceVolumeRatio brain lateral...                 1.309123  ...                -0.438608
original shape Sphericity bladder wall                            -3.487585  ...                 0.210400
original shape LeastAxisLength brain lateral ve...                -1.634777  ...                 0.553511
original shape MinorAxisLength left lung                           5.385165  ...                -0.185695
                                                                     ...  ...                      ...
original shape SurfaceArea foregut                                      NaN  ...                      NaN
original shape Flatness rectum                                    -0.028705  ...                -0.028705
original shape MinorAxisLength brain lateral ve...                 0.325469  ...                 0.325469
original shape Sphericity pons                                     0.330900  ...                -3.395906
original shape Sphericity mid hindgut                              0.301025  ...                 0.301025
[330 rows x 30 columns]

**Comment by mwaskom** [comment]
Please provide a reproducible example that depends on seaborn. Your code imports `from lama.stats.heatmap import clustermap`. I have no idea what that is.

But assuming that you're the person who posted [this Stackoverflow question](https://stackoverflow.com/questions/75571522/seaborn-clustermap-euclidean-metric-gives-infinite-values-error-but-dataset), that error message is being raised from scipy, not seaborn.

**Comment by mwaskom** [comment]
I'm going to close because your Stackoverflow post is rude and I don't feel like helping you any further.
