### ISSUE TITLE
seaborn issue

### ISSUE THREAD

**Issue by dorkylever** [mwaskom/seaborn#3281]
No offence dude but
 i)  you were just going to ignore the issue anyway(hence you negative voting on the question and closing the stack exchange without feedback). I would have provided more code if asked

 ii) I solved the issue myself (z_score=0, gave nan values for a row, hence error). 
 
 I look forward to unfortunately referencing this package in future publications and feel sorry for anyone using python based plotting

**Comment by mwaskom** [comment]
Closing as invalid.
