### ISSUE TITLE
pointplot doesn't take argument 'label' in 0.12.2

### ISSUE THREAD

**Issue by kushinm** [mwaskom/seaborn#3283]
The documentation seems to indicate that sns.pointplot() should be able to accept the 'label' argument in the absence of 'hue'.
However, I get thrown an error.
![image](https://user-images.githubusercontent.com/23156771/221682339-7c881731-1d51-4ada-acbb-fdea601c1e25.png)

**Comment by mwaskom** [comment]
I cannot replicate
<img width="519" alt="image" src="https://user-images.githubusercontent.com/315810/221720668-20a90e32-de0f-448c-9581-b76ba407154d.png">

Please heed the [guidelines](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs) on what constitutes an actionable bug report.

**Comment by kushinm** [comment]
Thanks for the super quick reply @mwaskom (and for maintaining this project generally) and sorry about not using a reproducible dataset. 
I tried again with the tips dataset and it still doesn't seem to be showing the legend when I use the label argument. 
Happy to cross-check with other libraries in my system that might be throwing things off. Any ideas

<img width="496" alt="image" src="https://user-images.githubusercontent.com/23156771/221936216-b0b0bfd5-f14f-4df9-bc3e-daf93a9ce14a.png">

**Comment by mwaskom** [comment]
Closing as this is not reproducible and in all likelihood explained by your environment not running 0.12; can reopen if you are able to demonstrate otherwise.
