### ISSUE TITLE
Wrong legend color when using histplot multiple times

### ISSUE THREAD

**Issue by nevubm** [mwaskom/seaborn#3292]
```
sns.histplot([1,2,3])
sns.histplot([4,5,6])
sns.histplot([7,8,9])
sns.histplot([10,11,12])
plt.legend(labels=["A", "B", "C", "D"])
```
![image](https://user-images.githubusercontent.com/14833020/224363975-cc4d8975-bf3f-4044-80d7-b8d1e3d77b38.png)
Seaborn 0.12.2, matplotlib 3.6.2
This may be related to https://github.com/mwaskom/seaborn/issues/3115 but is not the same issue, since histplot is used multiple times

**Comment by mwaskom** [comment]
It is the same underlying issue and this works fine on master.

That said, I _strongly_ recommend using explicit the label parameters rather than relying on implicit artist ordering.

```python
sns.histplot([1,2,3], label="A")
sns.histplot([4,5,6], label="B")
sns.histplot([7,8,9], label="C")
sns.histplot([10,11,12], label="D")
plt.legend()
```
