### ISSUE TITLE
seaborn.objects.Band - Examples not working as expected

### ISSUE THREAD

**Issue by trenton3983** [mwaskom/seaborn#3293]
This is in reference to the examples on [`seaborn.objects.Band`](https://seaborn.pydata.org/generated/seaborn.objects.Band.html).

**Tested in `python 3.11`, `pandas 1.5.3`, `matplotlib 3.7.0`, `seaborn 0.12.2`**

1. The examples don't work without the imported data being specified (e.g. `seaice = sns.load_dataset('seaice')`)
2. `p = so.Plot(seaice, x="Day", ymin="1980", ymax="2019")` doesn't work. 
    - Needs `seaice['Day'] = seaice.Date.dt.day_of_year` because `'Day'` isn't in the data
    - ValueError: Could not interpret value `1980` for `ymin`. An entry with this name does not appear in `data`.

### Working Example

```python
import seaborn.objects as so

seaice = sns.load_dataset('seaice')

seaice['Day'] = seaice.Date.dt.day_of_year

p = so.Plot(seaice, x="Day", y='Extent')
p.add(so.Band())
```

---

The following code doesn't produce the plot shown on the Example page.

```python
fmri = sns.load_dataset('fmri')

(
    so.Plot(fmri, x="timepoint", y="signal", color="event")
    .add(so.Line(linewidth=.5), group="subject")
    .add(so.Band())
)
```

### Result

![image](https://user-images.githubusercontent.com/12875240/224444234-107f7cc3-afea-46b7-a04d-4b9247c9e235.png)

**Comment by mwaskom** [comment]
Yes, the data undergoes some additional preprocessing. It is suppressed from the examples because they are examples demonstrating how to plot data, not how to preprocess it.
