### ISSUE TITLE
Heatmap set color palatte label mistakenly include NaN value 

### ISSUE THREAD

**Issue by yxwucq** [mwaskom/seaborn#3295]
I have a wide dataframe with some NaN values in it. When I want to generate heatmap with: 
```
sns.heatmap(merged_df_wide, cmap='Set3', mask=merged_df_wide.isna())
```
The NaN value is shown as grey squares in the main graph. However, The number of color label is n+1 for n discrete value because it mistakenly takes NaN into account.

**Comment by mwaskom** [comment]
Please provide a reproducible example.

**Comment by yxwucq** [comment]
Sorry for my mistake, by default color label will display all the color in the palatte. In my case(Set3) is 12, after sepcifying number of color types it worked smoothly:
```
cmap = sns.color_palette("Set3", 11) 
```
