### ISSUE TITLE
Scale issue when plotting on top of sns.pairplot diagonal

### ISSUE THREAD

**Issue by caph1993** [mwaskom/seaborn#3296]
I am plotting some red theoretical curves (ellipses and density functions) on top of the blue scatterplots and histograms produced by `sns.pairplot`.

As you can see in the image, the ellipses work well, but not the diagonal plots because it seems that they are shifted and scaled internally and automatically by `pairplot` to match the shared y axis. Therefore, my plots start at the zero of the scatter plots instead of the virtual zero of the diagonal plots.

Is it possible to change this behavior or at least to access the shift and scaling constants used by pairplot to do the shift and scaling manually?

Details: I am using `g.axes.diagonal()` to access the diagonal axes and `ax.plot(x,y)` to plot the densities. I tried also with `g = sns.PairGrid(df, diag_sharey=False)` without any difference in the scale.

![2](https://user-images.githubusercontent.com/5473460/225046053-3b7d7d6b-598b-485e-bbad-6fbe63f37371.png)

**Comment by mwaskom** [comment]
Please ask usage questions on Stackoverflow. You'll want to be sure to include a reproducible example so that it's possible to help you. Thanks!
