### ISSUE TITLE
Swarmplots fail with numpy v1.22 for dataframes with repeating indices

### ISSUE THREAD

**Issue by uri-t** [mwaskom/seaborn#3299]
With numpy v1.22, swarmplots fail when the index of the dataframe has repeating elements (works for 1.23+): 
(I'm using seaborn 0.12.1 and matplotlib 3.7.1)
```
File "/[]/seaborn/categorical.py", line 346, in plot_swarms
    dodge_move = offsets[sub_data["hue"].map(self._hue_map.levels.index)]
  File "[]/pandas/core/series.py", line 981, in __getitem__
    return self._get_value(key)
  File "[]/pandas/core/series.py", line 1089, in _get_value
    loc = self.index.get_loc(label)
  File "/[]/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 1
```
(I'm guessing it's not best practices to have repeating values in the index but it's probably not just me).
Here's a minimal example that gives the error:
```python
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

df = sns.load_dataset('exercise')
df.index = [1, *range(0,89)]

sns.swarmplot(data = df, x = 'diet', y = 'pulse', hue = 'kind',
        dodge = True)
plt.show()
```

I think this an issue with how numpy is interpreting the Pandas series as an index in [this line](https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L453); I tried casting `sub_data["hue"]...` to a list in this line and it seemed to solve the problem.

**Comment by mwaskom** [comment]
Thanks for the clear example. I don't have an obvious hypothesis why this would be dependent on numpy version as this is all pandas operations, but this works for me on current versions so I'm not sure there's much that can be done.
