### ISSUE TITLE
`kdeplot(levels)` seems to be interpreted across `hue`s rather than within

### ISSUE THREAD

**Issue by nicolaskruchten** [mwaskom/seaborn#3302]
I'm trying to visualize the 2d distributions of multiple categories and looking for just a single curve around the 50% iso-proportion, per category. The code below is a rough equivalent for what I'm trying to do:

```python
import seaborn as sns
import numpy as np
import pandas as pd

narrow = np.random.multivariate_normal((1,1), ((9,11),(8,12)), 1000).T
wide = np.random.multivariate_normal((30,30), ((31,29),(28,32)), 1000).T
both = np.concatenate((narrow, wide), axis=1)
df_ex = pd.DataFrame(dict(x=both[0], y=both[1], c=["a"]*1000 + ["b"]*1000))
sns.kdeplot(df_ex, x="x", y="y", hue="c", levels=[0.5])
```

![output](https://user-images.githubusercontent.com/203523/226985114-02165496-6af4-45f9-9128-794b7d5d331b.png)

I only get a curve for the narrow distribution (I assume because the iso-proportion contour is being computed across the whole input, not per-hue), but I was hoping to get an output more like the following (with the automatic legend etc):

```python
ax = sns.kdeplot(x=narrow[0], y=narrow[1], levels=[0.5])
sns.kdeplot(x=wide[0], y=wide[1], levels=[0.5], ax=ax)
```

![output](https://user-images.githubusercontent.com/203523/226985547-57927731-fd6c-4d8e-bb5c-28b13f40453f.png)

Is there some way to make the second figure (say with a few more categories) in a single `sns.kdeplot` call? Either way, if my interpretation is correct, would it be worth adding a note to this effect to the documentation?

**Comment by mwaskom** [comment]
I think you want `common_norm=False`?

```python
sns.kdeplot(df_ex, x="x", y="y", hue="c", levels=[0.5], common_norm=False)
```

<img width=400 src=https://user-images.githubusercontent.com/315810/227062651-22c8f204-b84f-475a-be21-1ac9b74078dd.png />

**Comment by nicolaskruchten** [comment]
Ah, yes, indeed I do! I swear I looked through what felt like all the options but didn't connect the dots. Thanks! :)
