### ISSUE TITLE
Bug: seaborn doesn't handle values correctly from pandas.Timestamp.isocalendar

### ISSUE THREAD

**Issue by netostr** [mwaskom/seaborn#3304]
This is an unfixed bug - https://github.com/mwaskom/seaborn/issues/2327

In the _oldcore.py file, there are lines starting from 282:
            if not norm.scaled():
                norm(np.asarray(data.dropna()))

pandas.core.series.Series is passed to np.asarray() without a 'dtype' parameter. Because of this, data with type 'UInt32' is converted type 'object' and causes the error described in the closed issue.
Could you add passing 'dtype' by data type?

**Comment by mwaskom** [comment]
Did you read the other issue? This is something that needs to be handled in upstream libraries.

**Comment by netostr** [comment]
Yes, I did. May you explicitly specify the data types, so as not to wait for the bug to be fixed in upstream libraries?

**Comment by mwaskom** [comment]
I don't understand what you are proposing (or even what you are doing to trigger the exception).
