### ISSUE TITLE
seaborn/distributions.py (line 499/500) FutureWarning

### ISSUE THREAD

**Issue by nkuehnle** [mwaskom/seaborn#3306]
With Pandas 1.5.3:

`FutureWarning:  The Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)`

This originates in distributions.py lines 499 and 500
```
index = pd.MultiIndex.from_arrays([
    pd.Index(edges, name="edges"),
    pd.Index(widths, name="widths"),
])
```

This can be fixed by specifying the datatype explicitly, i.e.

```
index = pd.MultiIndex.from_arrays([
    pd.Index(edges, name="edges", dtype="float64"),
    pd.Index(widths, name="widths", dtype="float64"),
])
```

Not sure if float64 is a necessary precision or if it's plausible that somebody would create large enough plots for the difference in memory allocation to really be appreciable.

**Comment by mwaskom** [comment]
Do you have a reproducible example of what you are doing when you get this warning? I am not seeing it in the test logs and in fact when I change the code to print the dtype of `edges`/`widths` they have `float64` not `object` for a simple examples (`sns.histplot(tips["total_bill"]`)

**Comment by mwaskom** [comment]
Closing as not reproducible.
