### ISSUE TITLE
The end of life for seaborn 0.12.2

### ISSUE THREAD

**Issue by kakiuchis** [mwaskom/seaborn#3307]
Can you tell me when the end of life for seaborn 0.12.2 will be? 
If it has not been decided, I would appreciate it if you could let me know that it is undecided.

**Comment by mwaskom** [comment]
Hi, not sure what you’re asking here?

**Comment by mwaskom** [comment]
Seaborn does not release on any particular schedule. You can look at the milestone for the next release to get a sense of progress towards it.

I'm not sure the other question make sense. Once a version (e.g. 0.12.2) is released, there are no further changes pushed to it.

Hope that helps.
