### ISSUE TITLE
implot error in seaborn

### ISSUE THREAD

**Issue by Uppalur-Srividya** [mwaskom/seaborn#3315]
![image](https://user-images.githubusercontent.com/127139915/230560065-bee1a8a7-e10e-44d1-b1e1-a3a75d4e7262.png)
![implot error in seaborn](https://user-images.githubusercontent.com/127139915/230560172-b2b86ad3-e252-46e0-9571-76cb78febbf4.png)

Hi,

Can someone help to resolve it. I tried many times and even my friend too facing same error.

**Comment by mwaskom** [comment]
It is an l as in “linear” not an i

**Comment by Uppalur-Srividya** [comment]
Thank you mwaskom for your support. Actually i am new to this and learning now.
