### ISSUE TITLE
Is there a way to set tick label rotations using the objects interface?

### ISSUE THREAD

**Issue by frfeng** [mwaskom/seaborn#3338]
In the new objects interface, is there a way to set, say, the xticklabel rotation? I read the [seaborn.objects.Plot.theme](https://seaborn.pydata.org/generated/seaborn.objects.Plot.theme.html#) and am not sure if it belongs here and is not implemented yet. Thank you.

**Comment by mwaskom** [comment]
I believe there is a Discussion about this if you search

**Comment by mwaskom** [comment]
Yes I expect it will be added.
