### ISSUE TITLE
Parameter `layout_rect` for PairGrid() 

### ISSUE THREAD

**Issue by leoluecken** [mwaskom/seaborn#3339]
In some situations axis labels disappear outside the figure when using PairGrid().
Like this: 
![image](https://user-images.githubusercontent.com/6482401/234065552-6672811d-1e37-4d2a-8270-7c60f7ab19a6.png)

I think, this could be fixed by adding a parameter `layout_rect` (in the fashion of the existing parameter `layout_pad`) to the constructor, which is then passed on as `rect` parameter to `tight_layout`.

**Comment by mwaskom** [comment]
Can you just call tight_layout again passing this value?

**Comment by leoluecken** [comment]
I checked a little closer now and found that this happens, because my display resizes the figure automatically, after calling pyplot.show(). If I save the figure as a png before that call, the resulting png-image looks fine, but is larger than my screen dimension.
So, I guess, this is not really a seaborn related issue. Please feel free to close it. Thanks for looking at it!
