### ISSUE TITLE
sns.pairplot() fails with ValueError: output array is read-only

### ISSUE THREAD

**Issue by FlorinAndrei** [mwaskom/seaborn#3346]
Dataset:

[train.csv](https://github.com/mwaskom/seaborn/files/11337012/train.csv)

Code:

```python
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

train_df = pd.read_csv("train.csv")

train_df["CryoSleep"] = train_df["CryoSleep"].astype(bool)
train_df["VIP"] = train_df["VIP"].astype(bool)
train_df["CryoSleep"] = train_df["CryoSleep"].astype(int)
train_df["VIP"] = train_df["VIP"].astype(int)
train_df["Transported"] = train_df["Transported"].astype(int)
train_df["HomePlanet"] = train_df["HomePlanet"].astype("category")
train_df["Destination"] = train_df["Destination"].astype("category")
_ = train_df.drop(columns=["PassengerId", "Cabin", "Name"]).copy(deep=True)

sns.pairplot(_.dropna())
```

No matter what, I cannot make it work on this dataset. Even if you skip the type conversion block and apply it to the original `train_df` it still fails. Even without `dropna()` it still fails.

Complete error message:

https://gist.github.com/FlorinAndrei/f84c68a3efdab40968ffd84687e5e343

Python 3.11.3
Pandas 2.0.0
Numpy 1.24.2
Seaborn 0.12.2
Jupyter Notebook

**Comment by thuiop** [comment]
Possibly related to #3331 ? What happens if you add `pd.set_option("mode.copy_on_write", False)` ?
As a side note, why do you have a variable named _ ?

**Comment by FlorinAndrei** [comment]
> What happens if you add pd.set_option("mode.copy_on_write", False) ?

That was it. I actually had `pd.options.mode.copy_on_write = True` in my code, and forgot to paste it into the sample code above. Setting it to `False` fixed the problem.

> As a side note, why do you have a variable named _ ?

I just copied a bit of test code from my notebook and did not change the name of that variable.

**Comment by mwaskom** [comment]
Closing as duplicate.

Always a good idea to ensure that your reprex does the expected thing on a fresh kernel before posting.
