### ISSUE TITLE
Adding cosine similarity to corrplot/heatmap

### ISSUE THREAD

**Issue by randyzwitch** [mwaskom/seaborn#335]
Michael - 

Based on your recommendation from Twitter, I explored using MPL for plotting the cosine similarity for k-means clusters. Here's my code:

``` python

import scipy
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import cm

clus20 = pd.read_csv(r"C:\Users\rzwitc200\Desktop\k20_cosine_calc.txt", sep = "\t")
Y20 = scipy.spatial.distance.pdist(clus20[clus20.columns[1:9]], 'cosine')
A = pd.DataFrame(scipy.spatial.distance.squareform(Y20))
mask =  np.tri(A.shape[0], k=-1)
A = np.ma.array(A, mask=mask.T) #Mask upper triangle

sns.set_context({"figure.figsize": (12, 12)})
sns.set_style("white")

fig = plt.figure()
ax1 = fig.add_subplot(111)
cmap = cm.get_cmap('Blues', 20)
cmap.set_bad('w') # default value is 'k'
ax1.imshow(A, cmap=cmap )
plt.ylabel("Cluster", size = 16)
plt.xlabel("Cluster", size = 16)
sns.despine()
plt.colorbar(ax1.matshow(A, cmap=cmap, vmin=0, vmax=1), shrink=.75)

ax1.xaxis.set_label_position('bottom')
ax1.xaxis.set_ticks_position('bottom')
plt.xticks(range(0,20,1), size = 16)
plt.yticks(range(0,20,1), size = 16)

plt.savefig(r'C:\cosine_similarity.jpg', dpi=220, bbox_inches='tight')
```

It feels like a small distance to incorporating this into the corrplot function under the 'method' keyword. However, before I started anything, I wanted to get your thoughts.

One of the most obvious differences here is that you're adding in p-value options for the upper triangle, which my code doesn't do. I'm not sure that makes sense in my case. 

Would this be something you are interested in getting a PR for? Or is it too far away from your original intent for the function?

![cosine_similarity](https://cloud.githubusercontent.com/assets/2762787/4705305/5f155b7c-587a-11e4-9851-b298dfabaaa1.jpg)

**Comment by mjkhf** [comment]
This was very helpful, thank you for putting it.
