### ISSUE TITLE
displot map function error

### ISSUE THREAD

**Issue by racng** [mwaskom/seaborn#3360]
I was following this [tutorial](https://seaborn.pydata.org/examples/kde_ridgeplot) on making a ridgeplot with FacetGrid. I could reproduce the plot using FacetGrid. However, if I try to replace the code with sns.displot which should initialize a FacetGrid object, the labeling function breaks.

```
# Create the data
rs = np.random.RandomState(1979)
x = rs.randn(500)
g = np.tile(list("ABCDEFGHIJ"), 50)
df = pd.DataFrame(dict(x=x, g=g))
m = df.g.map(ord)
df["x"] += m

def label(x, color, label):
	ax = plt.gca()
	ax.text(0, .2, label, fontweight="bold", color=color,
			ha="left", va="center", transform=ax.transAxes)
			
g = sns.displot(df, kind='kde',  x="x" ,row="g", hue="g", 
	common_norm=False, aspect=15, height=.5, fill=True, 
	alpha=1, bw_adjust=0.5)
g.map(label, "x")
# Set the subplots to overlap
g.figure.subplots_adjust(hspace=-.25)

# Remove axes details that don't play well with overlap
g.set_titles("")
g.set(yticks=[], ylabel="")
g.despine(bottom=True, left=True)
g.set(facecolor=(0,0,0,0))
```
 The following error happens
TypeError: label() missing 1 required positional argument: 'label'

**Comment by racng** [comment]
I noticed under [seaborn/distributions.py](https://github.com/mwaskom/seaborn/blob/master/seaborn/distributions.py) at line 2161, `hue` is not passed as an argument when initializing FacetGrid. 

``` python
    g = FacetGrid(
        data=grid_data, row=row_name, col=col_name,
        col_wrap=col_wrap, row_order=row_order,
        col_order=col_order, height=height,
        aspect=aspect,
        **facet_kws,
    )
```

I could now get g.map(label, "x") to work by changing the `displot` command to 

```python
g = sns.displot(df, kind='kde',  x="x" ,row="g", hue="g", 
	common_norm=False, aspect=15, height=.5, fill=True, 
	alpha=1, bw_adjust=0.5, facet_kws={'hue':'g'})
```

**Comment by thuiop** [comment]
I believe this is intended as FacetGrid handles the hue argument differently than the axes level function, which is why it is handled by those when making a displot.

**Comment by mwaskom** [comment]
Yes that's right — I don't consider this a bug in seaborn, but thanks for sharing the workaround you figured out!
