### ISSUE TITLE
Change in Behavior for Python 3.12 for TestRegressionPlotter

### ISSUE THREAD

**Issue by notatallshaw** [mwaskom/seaborn#3365]
Hi Team,

I would like to bring to your attention there is an expected change in behavior of of how variables are scoped inside comprehensions inside a class scope, details are here: https://discuss.python.org/t/pep-709-one-behavior-change-that-was-missed-in-the-pep

It has been identified in that thread (thanks to the work of Hugo van Kemenade and Carl Meyer) that [this line](https://github.com/mwaskom/seaborn/blob/v0.12.2/tests/test_regression.py#L122) in TestRegressionPlotter is affected by this behavioral change:

```python
df["c"] = [rs.binomial(1, p_i) for p_i in p]
```

Currently `rs` is sourced from the global scope and in Python 3.12 it will instead source it from the class scope. 

Reading the context of the code it seems like sourcing from the class scope is actually the intended behavior but I thought I'd raise this issue just to inform you anyway. Please feel free to close this issue if this is actually the intended behavior.

**Comment by mwaskom** [comment]
Thanks for flagging. I don't expect any issues to arise from this; nothing is assumed about the specific values of the random test data. This code will probably get refactored to use pytest fixtures at some point, also.
