### ISSUE TITLE
Unable to find seaborn's setup.py file

### ISSUE THREAD

**Issue by Shalmalee15** [mwaskom/seaborn#3370]
Hi 
Really stupid question, but I am unable to find setup.py for seaborn. Is it available somewhere else? Or am I missing something here? 
Thanks in advance

**Comment by mwaskom** [comment]
Seaborn doesn't have a `setup.py`, it has a [`pyproject.toml`](https://github.com/mwaskom/seaborn/blob/master/pyproject.toml) (documented [here](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/)).
