### ISSUE TITLE
Differences between sns or sb in Seaborn

### ISSUE THREAD

**Issue by Killpit** [mwaskom/seaborn#3372]
Hi, 

I occasionally use Seaborn and there are two ways you can import Seaborn: import seaborn as sns or import seaborn as sb. But whenever I use sns, it states that the package was deprecated and it's better to use sb. However, the documentation shows to use sns to create visualisations.

**Comment by Killpit** [comment]
When I say sb for Seaborn while importing, I can create visuals with sb. . And when I use sns, there was a time it stated that the package was deprecated. But both aliases work.

**Comment by mwaskom** [comment]
The alias that you assign a module to has no bearing on the module's behavior; it's just a variable name, like it doesn't change what's in a pandas dataframe if you call it `df` or `data`. It's not possible for a library to "deprecate" the alias that you use; it's a pure matter of convention and entirely up to you. You must have been seeing an unrelated deprecation warning. I'm going to close as there's no action for seaborn here.
