### ISSUE TITLE
Incorrect error bar offset in barplots

### ISSUE THREAD

**Issue by schmittlema** [mwaskom/seaborn#3380]
In whitegrid style, I've noticed the error bars in seaborn are plotted offset to the true end of the colored bar when using barplots (see images). This is caused by the default style parameter `'patch.edgecolor': 'w'` which makes a invisible border that the error bar is truely centered on (see offset.png). I like the white border but it would be great if the error bars would be centered on the true bar and not the white border particularly in whitegrid style.

To reproduce:
```
import numpy as np
import seaborn as sns
import random
import matplotlib.pyplot as plt                                                                      

# Data simulation
rng = np.random.RandomState(0)                                                                       
variable = rng.normal(20, 1, size = 50)                                                              
random.seed(0)
group = random.choices(["G1", "G2", "G3"], k = 50)                                                   
df = {'variable': variable, 'group': group}                                                          
sns.set_style("whitegrid", {"patch.edgecolor": "none"})                                             

# Correct error bars no whitespace                                                                   
sns.barplot(x = group, y = variable, errorbar="se", capsize = 0.1, errwidth=1.5)
fname = "test_errorbar_correct.pdf"
plt.savefig(fname, bbox_inches="tight")

# Offset error bars no whitespace
sns.set_style("whitegrid")
sns.barplot(x = group, y = variable, errorbar="se", capsize = 0.1, errwidth=1.5)                     
fname = "test_errorbar_offset.pdf"
plt.savefig(fname, bbox_inches="tight")

```
Correct
![correct](https://github.com/mwaskom/seaborn/assets/14075048/472f2d3c-3961-4cde-ae4b-edb9a0cf010b)
Offset
![offset](https://github.com/mwaskom/seaborn/assets/14075048/fc1b86c2-b2bb-49a0-9f17-1e25cc3f1090)

**Comment by mwaskom** [comment]
The error bar is in the exact same location in both plots. Seaborn can’t do anything about the white edge causing the artifact that you note.

**Comment by schmittlema** [comment]
Thanks for the quick response! You are right it is in the same location, but visually it looks not centered on the bar because of the white edge. Is it not possible to add a y offset to the creation of the error bars equal to the width of the line? Or does seaborn not internally use [errorbar()](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.errorbar.html) and can't specify x,y locations for errorbars

**Comment by mwaskom** [comment]
Seaborn does not use `errorbar` internally for these bars but I don't agree with the proposed remedy in any case: the error bars are in the right place, and the visual artifact is in on the bar itself.
