### ISSUE TITLE
sns.scatterplot

### ISSUE THREAD

**Issue by gavinjzg** [mwaskom/seaborn#3382]
**_**hello，sir！
i find a question,When I customized the color range, I found through Searbon that it didn't follow my custom colors，the legend shows color is wrong
codeing：
merged_df1= pd.read_csv("C:\\Users\\Administrator\\Desktop\\data.csv") 
plt.figure(figsize=(8.5, 8))
thresholds = [5,50,100,200]
colors = ['darkslategrey','skyblue', 'deepskyblue', 'white','orange']
legend_patches = [
    mpatches.Patch(color=colors[0], label=f'<{thresholds[0]}'),
    mpatches.Patch(color=colors[1], label=f'{thresholds[0]} - {thresholds[1]}'),
    mpatches.Patch(color=colors[2], label=f'{thresholds[1]}- {thresholds[2]}'),
    mpatches.Patch(color=colors[3], label=f'{thresholds[2]}- {thresholds[3]}'),
    mpatches.Patch(color=colors[4], label=f'>{thresholds[3]}')
]
conditions = [
    (merged_df1['logpvalue'] < thresholds[0]),
    (merged_df1['logpvalue'] >= thresholds[0]) & (merged_df1['logpvalue'] < thresholds[1]),
    (merged_df1['logpvalue'] >= thresholds[1]) & (merged_df1['logpvalue'] < thresholds[2]),
    (merged_df1['logpvalue'] >= thresholds[2]) & (merged_df1['logpvalue'] < thresholds[3]),
    (merged_df1['logpvalue'] >= thresholds[3])
]
color_array = np.select(conditions, colors)
cmap=sns.color_palette(colors, as_cmap=True)

sns.scatterplot(x=merged_df1['group'], y=merged_df1['gene'], hue=color_array,size=merged_df1['tpm'], sizes=(5, 250),legend='auto',palette=cmap,edgecolor='black')

plt.title('Bubble Chart')
plt.xlabel('tissue')
plt.ylabel('motif')
sizes = [30, 100, 200]  
legend_sizes = [plt.scatter([], [], s=size, color='grey', alpha=0.6) for size in sizes]
legend_labels = [f'TPM: {size}' for size in sizes]
a=plt.legend(loc='upper right', bbox_to_anchor=(1.2,1),prop={'size': 10},handles=legend_patches, title='-log pvalue')
plt.legend(legend_sizes, legend_labels, title='Size', loc='upper right',bbox_to_anchor=(1.2, 0.75),prop={'size': 10})
plt.gca().add_artist(a)
![image](https://github.com/mwaskom/seaborn/assets/52107940/7e3aad32-8a83-496c-bf63-40a539b91b49)
![image](https://github.com/mwaskom/seaborn/assets/52107940/3f44a2ca-c723-44e5-8221-12a7af72ecc4)
![image](https://github.com/mwaskom/seaborn/assets/52107940/d4c35fa4-e1cf-443c-8ecd-862ab53e0f29)

**Comment by thuiop** [comment]
You should use the `hue_order=colors` parameter to specify the order of the colors.
