### ISSUE TITLE
Docu: Missing code reference

### ISSUE THREAD

**Issue by buhtz** [mwaskom/seaborn#3384]
It seems the API docu is very strict in its meaning and only that parts are documented there are intended to be API.

It is not a **complete** code reference.

For example `class Grid` has docstring but is missing in the API docu generated by Sphinx.
Sphinx is for API docu not for code references.

My request is to add a full code docu like PyDoctor, Doxygen, etc would generate it.

**Comment by mwaskom** [comment]
As stated in the other issue #3383, `Grid` is not a user-facing class. the public methods that it defines are included in the documentation for the public classes that inherit them. It doesn't really help anyone IMO to have the "API" reference feature objects that are not part of the API and cannot be used directly.
