### ISSUE TITLE
DOC: warning-text of old documentation mentions link to new version but there is none

### ISSUE THREAD

**Issue by julian-goettingen** [mwaskom/seaborn#3387]
At https://seaborn.pydata.org/archive/0.11/generated/seaborn.scatterplot.html there is supposed to be a clickable link in the red box, but I can't find anything.

I believe the link should point to https://seaborn.pydata.org/generated/seaborn.scatterplot.html

**Comment by mwaskom** [comment]
You can't click the text?

<img width="1045" alt="image" src="https://github.com/mwaskom/seaborn/assets/315810/3ce0bc98-f5bf-40de-827b-86e1bb50565c">

In any case, it just links back to the homepage.

**Comment by julian-goettingen** [comment]
No, I can not click it, and the text is not underlined. I have tried with  clean browser too to ensure it is not an extension causing this problem on my side.

![image](https://github.com/mwaskom/seaborn/assets/58942047/4bd3420a-cfe0-4a16-a174-004c53266f4d)
![image](https://github.com/mwaskom/seaborn/assets/58942047/0a59b407-bdbd-4207-b130-f0581cb6137f)

I think it must be a css-issue, because the link exists in the html.
Interestingly, when I modify the the html so that the a-element with the link is outside of the red box, it actually becomes clickable.
![image](https://github.com/mwaskom/seaborn/assets/58942047/df279a8c-7b00-4042-8f7c-fcad4e577dda)

My frontend-skills are not high enough to understand what is going on here.

**Comment by mwaskom** [comment]
Weird! Pretty low priority IMO, but thanks for reporting.

**Comment by mwaskom** [comment]
@julian-goettingen I still can't replicate your issue on my end but curious if [the new archive page for 0.12](https://seaborn.pydata.org/archive/0.12/index.html) works any better for you?

**Comment by julian-goettingen** [comment]
@mwaskom yes, that link works perfectly, but that is the index-page, it also works for 0.11 - The link I posted in the question still does not work.

The 0.12-version of the link I posted would be https://seaborn.pydata.org/archive/0.12/generated/seaborn.scatterplot.html and it is working fine.

**Comment by mwaskom** [comment]
Got it, thanks for checking. Hopefully this works better going forward but doesn't seem like a good use of time to debug the pre-0.12 archive further (since I don't have any real hypotheses). Thanks for reporting!
