### ISSUE TITLE
Seaborn FacetGrid/Barplot Inconsistencies 

### ISSUE THREAD

**Issue by rikithreddy** [mwaskom/seaborn#3389]
I was doing some EDA, and I observed the following behavior with Seaborn.

**Seaborn version**: `0.12.2`
**Matplotlib version**: `3.7.1`

**Input data**

```
Class	count	greek_char	value
0	509	Alpha	A
1	61	Alpha	B
1	18	Alpha	D
1	29	Alpha	G
1	8	Beta	A
0	148	Beta	B
1	54	Beta	B
0	361	Beta	C
1	46	Beta	C
```

**Code**
```python
fig = sns.FacetGrid(data=tdf, col="greek_char", hue="Class")
_ = fig.map_dataframe(sns.barplot, x="value", y="count", dodge=True)
```
I obtained the following graph:

![](https://www.googleapis.com/download/storage/v1/b/kaggle-forum-message-attachments/o/inbox%2F8035862%2F87fe8adc182b5e78ed4cb58f68649fc7%2FScreenshot%202023-06-17%20at%2010.48.40%20PM.png?generation=1687022351744267&alt=media)

Here are some inconsistencies:

* Notice that Alpha doesn't have C in the dataset, but it appears in the graph.
* Alpha A has only Class 0, however, I see both classes in the graph.
* Class G and D are missing in the graph.

I would appreciate any help in determining whether this behaviour is a bug, expected behavior, or if I am missing something.

Thanks in advance

**Comment by mwaskom** [comment]
This is surprising, but "expected" behavior. Note the warning in the `[FacetGrid` docs](https://seaborn.pydata.org/generated/seaborn.FacetGrid.html):

> *Warning*
> When using seaborn functions that infer semantic mappings from a dataset, care must be taken to synchronize those mappings across facets (e.g., by defining the hue mapping with a palette dict or setting the data type of the variables to category). In most cases, it will be better to use a figure-level function (e.g. [relplot()](https://seaborn.pydata.org/generated/seaborn.relplot.html#seaborn.relplot) or [catplot()](https://seaborn.pydata.org/generated/seaborn.catplot.html#seaborn.catplot)) than to use [FacetGrid](https://seaborn.pydata.org/generated/seaborn.FacetGrid.html#seaborn.FacetGrid) directly.

Note that things have improved for (unreleased) 0.13.0dev0:

<img width="473" alt="image" src="https://github.com/mwaskom/seaborn/assets/315810/c9167bfe-abdf-4a03-a1ba-c7828704434f">

But the result isn't still exactly what you asked for because the bars aren't dodged. I would also recommend using `catplot` to make that happen automatically, but otherwise you need to modify your code to pass `hue` to `map_dataframe` rather than the constructor.

**Comment by rikithreddy** [comment]
@mwaskom thanks for the quick response. I will explore `catplot` as you suggested, and definitely will way for `0.13` to see some improvements. 

Also since `Alpha` did not have `C` would there be a way to not show it in the plot with the fix? The reason being I just gave a small sample of the exact code I am trying to run.

I can have multiple greek_letters Alpha, Beta, Gamma, Delta, Epsilon each with a different set of values. Hence making most of the x axis bars empty.

**Comment by mwaskom** [comment]
> Also since Alpha did not have C would there be a way to not show it in the plot with the fix? 

Try `sharex=False`
