### ISSUE TITLE
Swarmplot and markers

### ISSUE THREAD

**Issue by enryH** [mwaskom/seaborn#3392]
I am exploring the `swarmplot` functionality provided by seaborn. I tried to follow [stackoverflow suggestions](https://stackoverflow.com/questions/52878845/swarmplot-with-hue-affecting-marker-beyond-color) on changing the default marker for groups, but without success.

Looking at the documentation of the functionality provided by `swarmplot`, it says "additional parameters are passed to the `scatter` functions giving as an example:

```python
import seaborn as sns
tips = sns.load_dataset("tips")
sns.swarmplot(
    data=tips, x="total_bill", y="day",
    marker="x", linewidth=1,
)
``` 
 
 However, combining this with e.g. `hue`, does not give the expected result (and I found a hint in #1595 that it is also not possible:
 
 ```python
 sns.swarmplot(
    data=tips, x="total_bill", y="day",
    marker="x", linewidth=1,
    hue='sex'
)
 ```

![image](https://github.com/mwaskom/seaborn/assets/2833836/9a600955-4e83-43d3-bd28-e07618c4da9d)

I would have expected that the crosses are now in blue and orange, but this is not the case. Happy to have a look at the code or update the documentation, but a hint where to start would be great.

**Comment by mwaskom** [comment]
You need one other bit of matplotlib arcana:

```python
sns.swarmplot(
   data=tips, x="total_bill", y="day",
   marker="x", linewidth=1,
   edgecolor="face",  # <-----  Add this
   hue='sex'
)
```
![image](https://github.com/mwaskom/seaborn/assets/315810/8cb50391-6eb0-4175-9bb4-e24d26c34a4f)

**Comment by enryH** [comment]
Thanks! These "tricks" (specificities) are really hard to find! How complicated would it be to change to allow markers to be set differently for each group (displaying one more layer categories)? Ideally I would add another categorical column to the `DataFrame` in long format specifying the added grouping to be visualised by different markers.

**Comment by mwaskom** [comment]
> How complicated would it be to change to allow markers to be set differently for each group 

medium-high 

Closing as the main question here has been answered.

**Comment by enryH** [comment]
Just for documentation: My starting point would be the scatter function

https://github.com/mwaskom/seaborn/blob/9276e22a424fe2c834eff85231d0c916e293d613/seaborn/categorical.py#L452
