### ISSUE TITLE
Why is seaborn's drawing inconsistent with the experimental data

### ISSUE THREAD

**Issue by Marxvans** [mwaskom/seaborn#3395]
Hi, seaborn drew two different random seed experiments of the same group of experiments. The data drawn separately was correct, but the shadow interval was inconsistent with the experimental data when drawing the mean value of the two experiments together. The version of seaborn I use is 0.12.2.

This is the result of two separate plots of distributions with a maximum of 2,000 data.
![3333](https://github.com/mwaskom/seaborn/assets/38270020/ca760f24-0d6b-497e-821a-58a02135975c)
![44444](https://github.com/mwaskom/seaborn/assets/38270020/2f1c607b-4c93-4d3f-9918-8646c3ad4f96)
However, when I draw the upper and lower sections of the two curves, the shadow exceeds 2,000.
![222](https://github.com/mwaskom/seaborn/assets/38270020/6edb8fd5-a9ee-452e-af23-99a3f5b0b92b)
When I used seaborn==0.8.1 to draw, I got the correct result again, feel confused and need help!
![111](https://github.com/mwaskom/seaborn/assets/38270020/bf9c6027-7e1b-4cbb-ae09-f12b7c6dd8e1)

**Comment by mwaskom** [comment]
Without seeing any code it is impossible to say. Please provide a reproducible example.

**Comment by mwaskom** [comment]
Can't do anything with this report but happy to reopen with a reproducible demonstration of a bug.
