### ISSUE TITLE
In jointplot, How to show only the markers and not the names in the legend?

### ISSUE THREAD

**Issue by 1zzt** [mwaskom/seaborn#3397]
For example I don't want to display "size" in the image below
![image](https://github.com/mwaskom/seaborn/assets/22312961/97b54f3f-e0d9-451b-b639-0cad0fb3e660)
![image](https://github.com/mwaskom/seaborn/assets/22312961/92fe1d37-27bf-45af-8b1f-4ac15fb42bd4)

**Comment by mwaskom** [comment]
Please ask usage questions on stackoverflow and be sure to provide a reproducible example when you do, thanks!
