### ISSUE TITLE
regplot color line default value

### ISSUE THREAD

**Issue by lcrmorin** [mwaskom/seaborn#3402]
I reckon this might not be the biggest problem of the year. Seaborn regplot has been my go to solution for basic visualisation for a while now. One thing that slightly bother me, that I have to redo every time and could be helpfull to change as default is the default colors of the plot. 

By default the line and the dots are of the same color, which render the graphic difficult to read. 
Would you consider making the default value of colors for dots and line different ? Exemple of what I mean below. 
the default is blue on blue and for question of readability I always have to change this. It might not be intuitive (line_kws as a dictionnary) for python debutant.

![image](https://github.com/mwaskom/seaborn/assets/4086709/80f600d1-fe41-4621-8964-7eae878df379)

Hence my small issue: would you consider changing the base colors of the plot to make them more in contrast ?

**Comment by thuiop** [comment]
See #3266 about the default aesthetics. I think it also makes more sense to me for them to be the same color as they represent the same data ? If you had multiple datasets (typically using `hue` in `lmplot`), the lines would have to be the same color as the dots. (as a sidenote, I do not find the first plot especially hard to read)

**Comment by lcrmorin** [comment]
oh ok well if I am the only one facing this value, i'll keep specifying line_kws args.
