### ISSUE TITLE
Allow violinplot areas to be scaled by count

### ISSUE THREAD

**Issue by Matt-Schmitz** [mwaskom/seaborn#3405]
Currently there are 3 methods to scale a violinplot:

> scale : _{“area”, “count”, “width”}, optional_
> The method used to scale the width of each violin. If `area`, each violin will have the same area. If `count`, the **width** of the violins will be scaled by the number of observations in that bin. If `width`, each violin will have the same width.

The count option is only able to scale the **width** by number of observations, but cannot scale the area by the number of observations. This means that if you have 3 violins, where the first two violins have 10 datapoints each and the 3rd violin has all 20 datapoints contained in the first two violins, you cannot make the area of the third violin equal to the sum of the area of the first two violins. Instead, using count will make the third violin double as wide as a 10 point violin, as is explained in the violinplot documentation.

In the following code, you can see that count scales the width, but I would like a version of count that can scale the area.
```python
import matplotlib.pyplot as plt
import seaborn as sns

one = [0.01*i for i in range(10)]
two = [0.3+0.03*i for i in range(10)]

data = [one, two, one+two]

fig = sns.violinplot(data=data, scale="count")
fig.set_xticklabels(['10 datapoints', 'another 10 datapoints\n(area should be equal\nto first violin)', '20 datapoints\n(area should be sum\nof first two violins)'])

plt.title('Violin Plot')
plt.show()
```
![violin](https://github.com/mwaskom/seaborn/assets/34464190/ee9f138e-6c11-4fa0-88d0-d0611f27085d)

Here is the seaborn code:
```python
    if np.isnan(peak_density):
        span = 1
    elif density_norm == "area":
        span = data["density"] / max_density[norm_key]
    elif density_norm == "count":
        count = len(violin["observations"])
        span = data["density"] / peak_density * (count / max_count[norm_key])
    elif density_norm == "width":
        span = data["density"] / peak_density
```
I would like it to be changed to something like:
<pre>
    if np.isnan(peak_density):
        span = 1
    elif density_norm == "area":
        span = data["density"] / max_density[norm_key]
</pre>
```diff
+    elif density_norm == "count_area":
+        count = len(violin["observations"])
+        span = data["density"] / max_density[norm_key] * (count / max_count[norm_key])
```
<pre>
    elif density_norm == "width":
        span = data["density"] / peak_density
    elif density_norm == "count" or density_norm == "count_width":
        count = len(violin["observations"])
        span = data["density"] / peak_density * (count / max_count[norm_key])
</pre>

Also, the old "count" could be changed to "count_width". You could leave in  "count" for backwards compatibility.

**Comment by jenholmberg** [comment]
I would also love this functionality. Thanks!

**Comment by J-Schea29** [comment]
What is the status of this? This would be very useful!

**Comment by mwaskom** [comment]
Not planning any changes to the API here, thanks!
