### ISSUE TITLE
seaborn.objects so.Line() linestyle='none' ignored

### ISSUE THREAD

**Issue by subsurfaceiodev** [mwaskom/seaborn#3411]
so.Line() linestyle='none' keeps drawing a line between points. We know so.Dot() is meant for scatter plots but it would also be convenient to handle linestyle = 'none' for plotting lines and scatters in one command. Expected behavior would be for 'g2' group to show no line between points which should also be reflected in the legend.

```
import pandas as pd
import seaborn.objects as so

dataset = pd.DataFrame(dict(
    x=[1, 2, 3, 4],
    y=[1, 2, 3, 4],
    group=['g1', 'g1', 'g2', 'g2'],
))

p = (
    so.Plot(dataset,
            x='x',
            y='y',
            marker='group',
            linestyle='group',
            )
    .add(so.Line())
    .scale(
        linestyle=so.Nominal({'g1': 'dashed', 'g2': 'none'}),
    )
)

p.show()
```

![Figure_1](https://github.com/mwaskom/seaborn/assets/109676812/21769b5d-f3bb-44ad-a548-645d62feb844)

**Comment by mwaskom** [comment]
I don't remember if this was deliberate or not — it's interesting that `linestyle="none"` doesn't raise a `ValueError` like e.g. `linestyle="x"` does — but I think I'm generally :-1: on making it possible to draw a "Line mark" that does not show a line.

**Comment by mwaskom** [comment]
See #3412 for some broader thoughts on the design principles here. For the time being I think it's better to keep distinct marks clearly differentiated, and it doesn't make a tremendous amount of since to support a `Line` mark that doesn't actually draw lines.
