### ISSUE TITLE
seaborn.objects so.Plot() accept drawstyle argument

### ISSUE THREAD

**Issue by subsurfaceiodev** [mwaskom/seaborn#3412]
Currently there seems to be no way to do something like:

```
import pandas as pd
import seaborn.objects as so

dataset = pd.DataFrame(dict(
    x=[1, 2, 3, 4],
    y=[1, 2, 3, 4],
    group=['g1', 'g1', 'g2', 'g2'],
))

p = (
    so.Plot(dataset,
            x='x',
            y='y',
            drawstyle='group',
            )
    .add(so.Line())
    .scale(drawstyle=so.Nominal({'g1': 'default', 'g2': 'steps'}))
)

p.show()
```

We get:
TypeError: Plot() got unexpected keyword argument(s): drawstyle

**Comment by mwaskom** [comment]
I do anticipate adding a `Step` mark but don't see a case for adding `drawstyle` as a mappable property of the `Line` mark. In general you seem to be expecting `Line` to expose the full API of `plt.plot` which is not a goal (if anything it's an anti-goal). But while your issues are clear in the sense that they have a nice reproducible example (thanks!) they don't really motivate *why* this would be helpful or solve a problem, so it's hard to say...

**Comment by subsurfaceiodev** [comment]
It is very common in geotechnical engineering to mix scatter data (as measured data) with correlated data (as correlated data) and, in some cases, modeled data or measured shear wave velocity data as step charts. See following image from https://www.marchetti-dmt.it/wp-content/uploads/bibliografia/totani_2009_SDMT_impenetrable_alessandria.pdf:

![image](https://github.com/mwaskom/seaborn/assets/109676812/8f6a41fb-b9ad-4926-8fec-43c325014b07)

Also, faceting and color / marker grouping (which is already implemented by seaborn) is very useful for figures like:

![image](https://github.com/mwaskom/seaborn/assets/109676812/d34a900c-02da-42bb-9663-a87752b38ab2)

![image](https://github.com/mwaskom/seaborn/assets/109676812/e7514723-4005-4d15-937d-6cfcd3f6fadf)
