### ISSUE TITLE
Seaborn 0.12.2 and NumPy 1.24.3 causing Python crash upon Ctrl+C (reproduces across multiple Windows PCs)

### ISSUE THREAD

**Issue by peterdsharpe** [mwaskom/seaborn#3428]
# Overview

Ok, here's a really puzzling and interesting bug:

With the latest Seaborn version, if the NumPy version is 1.24.3: **At any time after importing Seaborn into Python, pressing CTRL+C *reproducibly* causes the Python process to forcibly terminate.** 

# Observed and Expected Behaviors

Below is a minimum reproducible example. Observed behavior:
```
Microsoft Windows [Version 10.0.22621.2070]
(c) Microsoft Corporation. All rights reserved.

C:\Users\peter>python
Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import seaborn
>>> (Note: user presses CTRL+C here)
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source      
libifcoremd.dll    00007FFE8EA9DF54  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFF6CF86E57  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFF6E9A26AD  Unknown               Unknown  Unknown
ntdll.dll          00007FFF6F70AA68  Unknown               Unknown  Unknown

C:\Users\peter>
```

Expected behavior, as seen if only Seaborn's dependencies are imported:
```
C:\Users\peter>python
Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy, scipy, matplotlib
>>> (Note: user presses CTRL+C here)
KeyboardInterrupt
>>>
```

-----

This reproducibly occurs across multiple tested Windows 11 PCs if Seaborn 0.12.2 (latest) and NumPy 1.24.3 are both installed. It occurs both in the Python interpreter as well as IPython. The Python version seems not to matter (the bug reproduces on Python 3.9 and 3.11). NumPy 1.25.0 and higher do not result in a crash (on any of the tested machines). No other Seaborn versions have been tested. It is unknown if lower NumPy versions exhibit the same behavior with the latest Seaborn version. It appears to happen on Windows 11 PCs, but not on Ubuntu PCs (even with the same Seaborn/NumPy version).

While this bug might appear to be purely a NumPy bug, it's hard to be believe that it is, since importing NumPy alone and then pressing CTRL+C doesn't cause a crash. The bug is due to something about how Seaborn and NumPy are interacting, but only on these specific versions of each package.

# Version Info
- Microsoft Windows 11
- Python 3.11.4 (Anaconda distribution)
- Seaborn 0.12.2 (latest)
- NumPy 1.24.3
- SciPy 1.10.1
- Matplotlib 3.7.1

**Comment by mwaskom** [comment]
I would suspect that this is really something going on with matplotlib. To rule that out, I think you need to at least import `matplotlib.pyplot`; `matplotlib` itself is pretty lightweight.

There are a couple other seaborn import side effects relating to matplotlib, e.g.
```
# Capture the original matplotlib rcParams
import matplotlib as mpl
_orig_rc_params = mpl.rcParams.copy()
```

I don't have access to a windows machine to do any testing.

I agree that it not happening with just numpy suggests it's not a "pure" numpy bug, but it not happening on numpy 1.25 does suggest its an issue on their end that's been addressed?

**Comment by peterdsharpe** [comment]
Hi @mwaskom , thanks for the quick reply.

It seems that this bug is not linked to `matplotlib.pyplot`, and seems to be linked to `seaborn`:

```
C:\Users\peter>python
Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy, scipy, matplotlib.pyplot
>>> (Note: user presses CTRL+C here)
KeyboardInterrupt
>>> import matplotlib as mpl
>>> _orig_rc_params = mpl.rcParams.copy()
>>> (Note: user presses CTRL+C here)
KeyboardInterrupt
>>> import seaborn
>>> (Note: user presses CTRL+C here)
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source      
libifcoremd.dll    00007FFF40C9DF54  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFF6CF86E57  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFF6E9A26AD  Unknown               Unknown  Unknown
ntdll.dll          00007FFF6F70AA68  Unknown               Unknown  Unknown

C:\Users\peter>
```

**Comment by mwaskom** [comment]
I'm not sure. There's not really anything seaborn does to mess with numpy at the "sub-Python" layer that generates a hypothesis about the cause here. Feel free to dig further on your own but since this is, as you say, working fine with the latest version of numpy, I don't think there's any action to take on the seaborn side right now.
