### ISSUE TITLE
narrow gaps in 2d kernel density diagram

### ISSUE THREAD

**Issue by merry200603** [mwaskom/seaborn#3434]
Hi there!

When I plot a 2d kernel density diagram, there are narrow gaps between  the adjacent contours (not white lines).

I am wondering if there is anyway to fill these gaps, thanks!

![1](https://github.com/mwaskom/seaborn/assets/2960864/0cd69bb5-0ba4-414a-a886-d71a8452785f)

**Comment by mwaskom** [comment]
Please make a reproducible example and ask on StackOveflow. Thanks!
