### ISSUE TITLE
Seaborn Heatmap Documentation

### ISSUE THREAD

**Issue by jukent** [mwaskom/seaborn#3437]
Hi all I was looking at your [heatmap example](https://seaborn.pydata.org/examples/spreadsheet_heatmap.html) and found that the `pandasDataframe.pivot()` function does not work locally as called.

I had to change 
`flights = flights_long.pivot("month", "year", "passengers")` 
to 
`flights = flights_long.pivot(index="month", columns="year", values="passengers")`, specifying the kwargs.

I'm working through this because I am making an Advanced Visualization Cookbook for [Project Pythia](https://projectpythia.org/) and trying to provide an overview of all the different plotting libraries scientific python programmers have ever asked me about during plotting tutorials. If you'd like input or feedback on how your project is summarized or if you'd like a workflow to be featured in our interactive plotting chapter please let me know.

**Comment by mwaskom** [comment]
This is specifically a change in pandas 2.0 that required keyword arguments.

The source script has [already been updated](https://github.com/mwaskom/seaborn/blob/master/examples/spreadsheet_heatmap.py) and the online docs will update on the next release + rebuild.

There's no issue in seaborn itself, just in the way the example script uses pandas.

Thanks!
