### ISSUE TITLE
so.plot not working in version 0.12.2

### ISSUE THREAD

**Issue by RSelvaratnam** [mwaskom/seaborn#3439]
The following code does to display the intended graph, just a blank white space.

```
import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt

import seaborn as sns
import seaborn.objects as so

dataLi = pd.read_csv("lithium_data.csv")
dataLi

(
  so.Plot(dataLi,
              x = "CV",
              y = "Mean")
)

plt.show()
```

In contrast the code below does provide a graph.  Why does the code above not work?

```
dataLi = pd.read_csv("lithium_data.csv")

g = sns.relplot(data = dataLi,
                x = "CV",
                y = "Mean")
g.set_axis_labels("%CV", "Mean [Lithium], mmol/L")  

plt.show()
plt.close
```

`

**Comment by thuiop** [comment]
You need to assign your Plot to a variable and call p.show() or p.plot() for it to work (or just chain it directly). Also, you did not add anything in your plot so it will be empty even after that ; refer to the documentation on how the objects interface work.

**Comment by RSelvaratnam** [comment]
@thuiop I have tried adding a layer to the plot.  Consider this example below, which does not result in any visible graph.

```
supercars = pd.read_csv('https://learn.sharpsightlabs.com/datasets/pdm/supercars.csv')

supercars

(so.Plot(data = supercars
         ,x = 'horsepower'
         ,y = 'top_speed'
         )
   .add(so.Dot())
 )
 
plt.show()
```

I have tried plt.plot() and plt.show() but does not produce the intended graph. Why would this be?
