### ISSUE TITLE
Data is not showing on matplotlib 1.4.2

### ISSUE THREAD

**Issue by mgalardini** [mwaskom/seaborn#344]
Hi,

thanks for this wonderful library; I noticed a weird behaviour when using seaborn with the latest matplotlib (1.4.2, with python 2.7 on linux64). A simple plot like this:

```
plot(range(10), range(10), 'bo')
```

which works fine using just matplotlib, appears completely blank after importing seaborn. I did some tests and it seems that the 'dots' marker don't work anymore. From what I've seen it used to work with a previous version of matplotlib (1.3.1). 

Thanks for your help,
Marco

**Comment by tritemio** [comment]
I was just bitten by this bug doing in mpl 1.4.2 and seaborn 0.5.1

    plt.plot(range(10), range(10), '+')

The workaround of setting `lines.markeredgewidth` works.

**Comment by histed** [comment]
I still see this bug with mpl 1.4.3 and seaborn 0.5.1.

I had to set lines.markeredgewidth to 1.0 to make 'x' and '+' visible.

**Comment by mwaskom** [comment]
That is a different issue than the one reported here. See https://github.com/matplotlib/matplotlib/issues/4679

**Comment by histed** [comment]
OK.  Just to make sure we're on the same page:
If I do not explicitly set lines.mew, using mpl 1.4.3 and seaborn 0.5.1, nothing is visible when markers are set to 'x', '+', or '.'.  Setting lines.mew to 0.1 makes them barely visible.  Setting it to 1.0 makes them look good.

**Comment by mwaskom** [comment]
yes but you can do it in the function call too

**Comment by patricksurry** [comment]
I ran into this same problem with mpl 1.4.2 and the 'mew' fix works - thanks!  I also found that switching to the svg backend in the notebook makes the markers appear.

    %config InlineBackend.figure_format = 'svg'

**Comment by mwaskom** [comment]
FWIW, matplotlib 1.4.2 is pretty old now and there's been both a bugfix release (1.4.3) and a new feature release (1.5) since then.

**Comment by mizzao** [comment]
I'm still setting this issue with seaborn 0.6.0. Is setting `markeredgewidth` still the right workaround or is it a different problem now?

**Comment by mmagnuski** [comment]
@mizzao As stated above - use matplotlib 1.4.3 or later.

**Comment by mwaskom** [comment]
> I'm still setting this issue with seaborn 0.6.0. Is setting markeredgewidth still the right workaround or is it a different problem now?

Be more specific about what "this issue" is. People have discussed multiple issues in this thread, and besides, who knows what you're actually seeing.

Also as @mmagnuski notes, the most relevant piece of information would be the version of matplotlib that you are using.

**Comment by mizzao** [comment]
Sorry I wasn't being clear. In my case I wasn't seeing markers for `x` and `+`, etc, and I was using matplotlib 1.4.3 and seaborn 0.6.0.

It was worked around with `sns.set_context(rc={'lines.markeredgewidth': 1})`. Weird that it was still necessary since I was using the right version.
