### ISSUE TITLE
Plotting over clustermap

### ISSUE THREAD

**Issue by lm-jkominek** [mwaskom/seaborn#3441]
Hi, I was wondering if there is a way to highlight a portion of the heatmap (e.g. a specific column) from the clustermap by plotting, say, a standard rectangle shape over the heatmap itself? I know that there is no native highlighting capability, but maybe there is a way to do that using other means, by manipulating the underlying figure structures or some such? Thanks in advance!

**Comment by mwaskom** [comment]
I [suggest](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#general-support) making a reproducible example and asking on StackOverflow where is a larger audience for Q&A. Thanks!
