### ISSUE TITLE
Creating the boxplots using the stats (min, max, Q1, Q3 and median) directly

### ISSUE THREAD

**Issue by SriMun16** [mwaskom/seaborn#3442]
I have a usecase for generating the box plot for huge data which involves creating hues and that need to be updated once a month. And I have the stats needed for the box plots computed. that is Q1, Q3, min, max and median. I dont need fliers. Can we expand the seaborn's boxplot to support passing the stats function similar to matplotlib's bxp function. Thank you so much.!

 https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.bxp.html#matplotlib.axes.Axes.bxp

**Comment by mwaskom** [comment]
Hi, I don't think this would work well with seaborn's expected data input representation, but as you know there is a matplotlib function that will work for you so I'd recommend using that.
