### ISSUE TITLE
regplot bug: If x equals y for all data points, plotted x_bins points do not have x=y for all points

### ISSUE THREAD

**Issue by alexmoehring** [mwaskom/seaborn#3461]
Thank you to the maintainers for this amazing package! 

In the regplot function with `x_bins` and `x_estimator=np.mean`, my understanding is that the function plots points (x,y) where x is the mean of the x-values within a bin and y is the mean of the y-values within a bin. If this is the case, the following example where x == y for all data points, we should have every point on the 45 degree line. This is not the case as can be seen in the simple example below. 

```
import pandas as pd
import seaborn as sns
import numpy as np

df = pd.DataFrame()
df['x'] = np.random.randn(1000)
df['y'] = df.x
assert np.all(df['x'] == df['y'])
sns.regplot(data=df, x='x', y='y', x_bins=10)
```

![image](https://github.com/mwaskom/seaborn/assets/21027730/ee049f0f-0ce8-45f3-9884-57554b3bd66d)

**Comment by alexmoehring** [comment]
Update: I figured out the issue and think this may be expected behavior. The function is plotting quantiles of the marginal distribution of x as the x-values and then the average y among points whose x is closest to each point. The quantile of a random variable is not equal to the mean conditional on the RV being closest to the quantile which explains this discrepancy.

Modifying the `bin_predictor` function below adjusts the location of a points along the x-axis to the mean within the bin. I suspect this choice was by design. Is there any appetite to include an argument that, when passed, normalizes the x locations?

```
    def bin_predictor(self, bins):
        """Discretize a predictor by assigning value to closest bin."""
        x = np.asarray(self.x)
        if np.isscalar(bins):
            percentiles = np.linspace(0, 100, bins + 2)[1:-1]
            bins = np.percentile(x, percentiles)
        else:
            bins = np.ravel(bins)

        dist = np.abs(np.subtract.outer(x, bins))
        x_binned = bins[np.argmin(dist, axis=1)].ravel()

        unique_vals = np.unique(x_binned)
        for val in unique_vals:
            _x = x[x_binned == val]
            new_x = np.mean(_x)
            x_binned[x_binned == val] = new_x

        return x_binned, bins
```

**Comment by mwaskom** [comment]
I'm not sure I exactly understand the desired behavior here but you can also supply specific bin locations. Anything more complicated than that should probably be handled upstream of seaborn in data prep.

**Comment by alexmoehring** [comment]
Thank you for the response and the work developing and maintaining the package! 

To clarify, my use case is to use regplot to visualize the conditional mean function, which I think is correct given the docs. It seems to be plotting something slightly different from this, which the example illustrates. I.e. in the example we know $E[y|x]=x$. The points clearly deviate from this, and the confidence intervals suggest we can reject the true null quite confidently. You are correct that this can be addressed by passing bin locations. That said, I suspect my use case is common so it could be worthwhile including as an optional argument (which I'd be happy to help with). Of course free disposal, feel free to close the issue if this is not something you'd like to pursue!

**Comment by mwaskom** [comment]
I'm not aware of anywhere in the docs claiming that regplot shows a conditional mean function. Happy to update the docs if they're actively incorrect.

This function is very old and not really in keeping with the current approach to API design in seaborn — it already has way too much in it. (I.e. why does the "regplot" function even have all of this logic about binning the independent variable? It's not relevant to the regression model?) So probably disinclined to add additional features, especially if the desired behavior can already be accomplished slightly more effortfully with existing API.

**Comment by alexmoehring** [comment]
Fair enough! I suspect there is demand for a canned function that both plots a parametric regression function and a non-parametric version such as a binscatter, but understand if this is not a direction seaborn wants to head. Again, I appreciate your engagement and support for this amazing package. I'll go ahead and close this issue.
