### ISSUE TITLE
FutureWarning: is_categorical_dtype is deprecated

### ISSUE THREAD

**Issue by trenton3983** [mwaskom/seaborn#3463]
Using `pandas v2.1.0` and `seaborn v0.12.2`

This is more of an FYI of coming changes in pandas

```
import pandas as pd
import seaborn as sns

tips = sns.load_dataset('tips')
sns.scatterplot(data=tips, x='total_bill', y='tip', hue='time')
```
Plots without issue, but also now results in the following warning

```
C:\Users\trenton\anaconda3\envs\py11\Lib\site-packages\seaborn\_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
```

## Resolution

It looks like there are changes in the repo that already resolve the issue, but it's not yet on an Anaconda channel

```
# Name                    Version                   Build  Channel
seaborn                   0.12.2          py311haa95532_0
```

Changing line 1498 in `_oldcore.py` from `if pd.api.types.is_categorical_dtype(vector):` to `if isinstance(vector, pd.CategoricalDtype):` seems to resolve the issue.

**Comment by stefanks** [comment]
Yes, I am getting the same error. Is there a way to make a release with this code merged in? Thank you!

**Comment by mwaskom** [comment]
This is just a warning, not an error, and it has already been addressed in master. Please search existing issues before opening new ones.

**Comment by trenton3983** [comment]
Sorry, I only looked in the **Open** issues.
