### ISSUE TITLE
Address deprecations shown with pandas 2.1.0

### ISSUE THREAD

**Issue by km2023-4** [mwaskom/seaborn#3466]
Hi Michael,

Not sure if this is already being addressed...there seem to be a few deprecation warnings with the latest version of pandas (https://pandas.pydata.org/docs/whatsnew/v2.1.0.html#backwards-incompatible-api-changes):

```text
.../venv/lib/python3.9/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
.../venv/lib/python3.9/site-packages/seaborn/_oldcore.py:1119: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
```

I am also seeing a few different deprecated calls in _oldcore.py. Seems though as if these are easy fixes. 

Are you planning to address these?

Many thanks,
Karsten

**Comment by mwaskom** [comment]
These are addressed on master already please search before opening an issue.
