### ISSUE TITLE
sns.lmplot x_estimator / logistic estimation speed

### ISSUE THREAD

**Issue by tomwallis** [mwaskom/seaborn#347]
I'm a long-time `ggplot2` (R) user switching over to Python. Seaborn is lovely, but I've noticed that at least for me, its x_estimator or logistic regression estimators are very slow compared to R.

[You can see more details on my blog here](http://tomwallis.info/2014/10/29/high-level-plotting-in-python/), but the short story is: plotting a summary of binomial data, with summarised x values, some logistic regression lines, and a facet_wrap by subject (`col='subject'`) takes 3 seconds in R and 2 minutes in Seaborn. Test data [here](https://github.com/tomwallis/blog_stuff/blob/master/out/contrast_data.csv). Seaborn code here:

```
# do imports
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import ggplot

dat = pd.read_csv('contrast_data.csv')

# make a log contrast variable (because Seaborn can't auto-log an axis like ggplot):
dat['log_contrast'] = np.log(dat['contrast'])

# set some styles we like:
sns.set_style("white")
sns.set_style("ticks")
pal = sns.cubehelix_palette(5, start=2, rot=0, dark=0.1, light=.8, reverse=True)

%%timeit
fig = sns.lmplot("log_contrast", "correct", dat,
                 x_estimator=np.mean, 
                 col="subject", 
                 hue='sf',
                 col_wrap=3,
                 logistic=True,
                 palette=pal,
                 ci=True);
```

I'm afraid I haven't done extensive testing so I can't tell you what specifically is slow (bootstrapping? logistic model fitting?). I wanted to raise it here because I couldn't see anyone talking about this on SO or here. 

Are there plans to optimise the backend you're using? If someone wanted to help, where would they start?

**Comment by mirekphd** [comment]
> Changing to `ci=False` [should be `ci=None` actually:) now takes 6.7 seconds in the example I posted instead of 2 minutes.

Thank you @mwaskom for this awesome trick! Switching confidence intervals shortened plotting times for my lmplots from 1m20s (on 32 CPU server cores!) to just 1.7 seconds. 

IMO this bootstrapped confidence intervals feature is such a drag on performance should be off by default...

**Comment by mirekphd** [comment]
IMO this bootstrapped confidence intervals feature is such a drag on performance that it should be off by default...
