### ISSUE TITLE
Background theme color not changing from dark 

### ISSUE THREAD

**Issue by abinayreddy** [mwaskom/seaborn#3470]
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so
from matplotlib import style

sns.set_theme(style="whitegrid")
sns.set_style("whitegrid")
sns.set(font_scale=1.4)
g = sns.catplot(x="SSL", hue="Model", y= "Percentage", col="Dataset",
                data=titanic,
                kind="bar", height=5, aspect=.8, palette='Set1')

g.set_titles(template='{col_name}')

for ax in g.axes.flat[1:]:
    sns.despine(ax=ax, left=True)
for ax in g.axes.flat:
    ax.set_xlabel(ax.get_title())
    ax.set_title('')
    
    ax.margins(x=0.1) # slightly more margin as a separation
plt.subplots_adjust(wspace=0, bottom=0.18, left=0.06)
plt.show()
plt.savefig("output.png",dpi=500)

This is still producing dark grid

**Comment by mwaskom** [comment]
I suggest making a reproducible example (I can't run this code) and positing on stackoverflow. Thanks!
