### ISSUE TITLE
I am trying to align labels in a histogram using seaborn though it not happening, the same graph in excel is properly aligned with labels, how can i do the same using seaborn

### ISSUE THREAD

**Issue by Utsav-2301** [mwaskom/seaborn#3474]
![temp](https://github.com/mwaskom/seaborn/assets/70055612/c00a95b9-ca5e-4203-9400-7f756eb75d75)

**Comment by mwaskom** [comment]
I suggest making a reproducible example and asking on Stackoverflow; it's not possible to help you without seeing any code. Thanks!
