### ISSUE TITLE
Fonts appear bigger in exported PDF

### ISSUE THREAD

**Issue by mvukov** [mwaskom/seaborn#348]
I use the following snippet to configure seaborn:

``` python
import seaborn as sns
fontSize = 8
sns.set_context("paper", font_scale=1.0, rc={'lines.linewidth': 0.75,
                                             'axes.linewidth': 0.75,
                                             'font.size': fontSize,
                                             'axes.labelsize': fontSize,
                                             'xtick.labelsize': fontSize,
                                             'ytick.labelsize': fontSize,
                                             'legend.fontsize': fontSize,
                                             'text.usetex': True
                                             })
sns.set_style("whitegrid", {'font.family': 'serif',
                            'font.serif': ['Palatino']})
```

Later I create a figure and save it with matplotlib's `plt.savefig(...)`. The Latex document where I use my figure uses 11pt font size. When I set above `fontSize=11` the text in the exported figure's PDF looks _huge_. So I had to decrease the font to to 8pt. BTW, this is not influenced by the font type, e.g. Palatino is not the culprit, IMO.

I don't have a clue what I am doing wrong... Any thoughts?

I tried this on OSX 10.7 and Ubuntu 12.04.

**Comment by michaelerule** [comment]
This bug is still present as of January 2016. It is not only the fonts that are wrong, but the entire scaling of the PDF output. It should not be necessary to use the PGF backend to get Matplotlib to export correctly scaled PDFs.
