### ISSUE TITLE
How to show all x-tick labels with seaborn.objects?

### ISSUE THREAD

**Issue by anya-ji** [mwaskom/seaborn#3484]
How do I make it so that it shows all x ticks from 0 to 9?
```
import pandas as pd
import seaborn.objects as so

diff_df = pd.DataFrame({'bin': [0,1,9,3,4,2,3,4,7,5,6,7,8,9], 'diff': [1,0,1,1,1,3,2,4,1,2,3,0,2,1]})
(
    so.Plot(x='bin', y='diff', data=diff_df) 
    .theme({**axes_style("whitegrid"), "grid.linestyle": ":"})
    .add(so.Dots())
    .add(so.Range(color='orange'), so.Est())
    .add(so.Dot(color='orange'), so.Agg())
    .add(so.Line(color='orange'), so.Agg())
    .label(
        x="Image Similarity Bin", y="Difference",
        color=str.capitalize,
    )
)
```

I tried to set xticks in .label, but it doesn't do anything.

SO: https://stackoverflow.com/questions/77137092/how-to-show-all-x-tick-labels-with-seaborn-objects

**Comment by mwaskom** [comment]
Can you please convert your reprex into something that can be easily copy-pasted and built open? Thanks.

**Comment by anya-ji** [comment]
Sorry, just updated the original comment. Thanks!

**Comment by thuiop** [comment]
Add `.scale(x=so.Continuous().tick(every=1))`

**Comment by anya-ji** [comment]
That's perfect, thank you!

**Comment by mwaskom** [comment]
You could also do `.scale(x=so.Nominal())`, which will have a slightly different defaults for the grid and margins:

![image](https://github.com/mwaskom/seaborn/assets/315810/58192a21-1e06-4354-a9eb-0c3302ff7d25)
