### ISSUE TITLE
seaborn\_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead

### ISSUE THREAD

**Issue by kiasar** [mwaskom/seaborn#3485]
I get this warning all the time in every plot I do with a panda data frame. I use Seaborn 0.12.2

`seaborn\_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead`

**Comment by thuiop** [comment]
This is a pandas 2.0 deprecation warning ; it is already adressed on the master branch (#3355). Either upgrade seaborn to the github version or downgrade pandas if this warning bothers you. (by the way, you could have used the search function before posting, this is literally the 5th issue being opened about this)
