### ISSUE TITLE
FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version

### ISSUE THREAD

**Issue by rgoubet** [mwaskom/seaborn#3486]
With pandas 2.1, generating a simple histplot raises the following warning:

```
FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
```

**Comment by kartiksubbarao** [comment]
Looks like this has been fixed in #3355

**Comment by FlorinAndrei** [comment]
What is the timeline for having the fix in a stable Seaborn release? Seaborn is basically unusable with pandas-2.1 right now.

**Comment by mwaskom** [comment]
Please search before opening issues!

**Comment by FlorinAndrei** [comment]
@mwaskom Perhaps the multiple issues are a sign that this is a problem that is annoying to a lot of users?

Downgrading pandas to 2.0 is not a good option since 2.1 brings very substantial speed gains to certain workloads.

When does seaborn plan to release a fix for this annoying bug?

**Comment by pintergreg** [comment]
@FlorinAndrei As a workaround, you can suppress the warnings until the fix is released.

```python
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)
```
