### ISSUE TITLE
Inconsistcy between x= and y= args of stripplot function

### ISSUE THREAD

**Issue by ivanistheone** [mwaskom/seaborn#3514]
I ran into a strange API inconsistency while trying to plot a "horizontal" strip plot. When I represent the categorical variable on the x-axis and numerical on y-axis is works as expected, but when I put the numerical variable on the x-axis and the categorical on the y-axis it messes up the x-axis somehow.

Here is the dataset:

```Python
import pandas as pd
players = pd.read_csv("https://nobsstats.com/datasets/players.csv")
players
#    username country  age  ezlvl    time  points  finished
# 0      mary      us   38      0  124.94     418         0
# 1      jane      ca   21      0  331.64    1149         1
# 2      emil      fr   52      1  324.61    1321         1
# 3      ivan      ca   50      1   39.51     226         0
# 4     hasan      tr   26      1  253.19     815         0
# 5    jordan      us   45      0   28.49     206         0
# 6    sanjay      ca   27      1  350.00    1401         1
# 7      lena      uk   23      0  408.76    1745         1
# 8      shuo      cn   24      1  194.77    1043         0
# 9     r0byn      us   59      0  255.55    1102         0
# 10     anna      pl   18      0  303.66    1209         1
# 11     joro      bg   22      1  381.97    1491         1
```

My intention is to show a stripllot of the raw data in the ezlvl=1 and ezlvl=0 groups + diamond markers for the mean in each groups, which are located at:

```Python
avg_ezlvl0 = players[players["ezlvl"]==0]["time"].mean()
avg_ezlvl1 = players[players["ezlvl"]==1]["time"].mean()
avg_ezlvl0, avg_ezlvl1
# (242.17333333333332, 257.34166666666664)
```

When I use the following code with categorical-x and numeric-y it works:

```Python
import seaborn as sns
ax = sns.stripplot(x="ezlvl", y="time", hue="ezlvl", data=players)
sns.scatterplot(x=[0], y=[avg_ezlvl0], marker="D", ax=ax)
sns.scatterplot(x=[1], y=[avg_ezlvl1], marker="D", ax=ax)
```

<img width="562" alt="Screen Shot 2023-10-06 at 11 23 03 AM" src="https://github.com/mwaskom/seaborn/assets/163966/6659c7ba-e183-4852-b107-b163b8c170d8">

When I use the simlar code with categorical-y and numeric-x it produces a weird result where the diamond markers appear in the wrong place:

```Python
ax = sns.stripplot(x="time", y="ezlvl", hue="ezlvl", data=players)
sns.scatterplot(x=[avg_ezlvl0], y=[0], marker="D", ax=ax)
sns.scatterplot(x=[avg_ezlvl1], y=[1], marker="D", ax=ax)
```
<img width="547" alt="Screen Shot 2023-10-06 at 11 23 11 AM" src="https://github.com/mwaskom/seaborn/assets/163966/f8b28fe2-5be8-4fca-b21f-320d0fc78183">

Clearly some step of the plotting process  in this case reset the x-axis "scale" but I don't know what exactly is going on.

I found a workaround for my use case to use `sns.scatterplot(x="time", y="ezlvl", hue="ezlvl", data=players)` which works as expected, but wanted to flag the issue for potential fix to `stripplots` to make it consistent under x= y= swaps.

**Comment by mwaskom** [comment]
I think you need `orient=“h”` in your second example since both variables are numeric.

**Comment by ivanistheone** [comment]
> I think you need `orient=“h”` in your second example since both variables are numeric.

Yep, that was it! Adding the `orient="h"` makes it do the right thing:

```Python
means = players.groupby("ezlvl")["time"].mean()

ax = sns.stripplot(x="time", y="ezlvl", hue="ezlvl", orient="h", data=players)
sns.scatterplot(x=[means[1]], y=[1], marker="D", color="r", ax=ax)
sns.scatterplot(x=[means[0]], y=[0], marker="D", color="b", ax=ax)
```

<img width="439" alt="Screen Shot 2023-10-07 at 3 32 31 AM" src="https://github.com/mwaskom/seaborn/assets/163966/7af5d32e-ef4b-4227-8bb2-8fcbcc16d68c">


I didn't know about the `orient` option. Thx for the pointer.
