### ISSUE TITLE
Unexpected behavior with palettes

### ISSUE THREAD

**Issue by hamdanal** [mwaskom/seaborn#3515]
While working on https://github.com/python/typeshed/pull/10721 I found two issues with color palettes behavior in seaborn:

1. Docs of functions in the _distributions_ and _relational_ APIs say they accept `string, list, dict, or matplotlib.colors.Colormap` for `palette` but in reality using a colormap generates an error.
   ```python
   import seaborn as sns
   
   tips = sns.load_dataset("tips")
   
   p = sns.color_palette("inferno", as_cmap=True)
   print(type(p))
   
   sns.histplot(
       tips,
       x="total_bill",
       y="tip",
       hue="smoker",
       multiple="stack",
       palette=p,
   )
   ```
   This generates the following error:
   ```pytb
   <class 'matplotlib.colors.ListedColormap'>
   Traceback (most recent call last):
     File "/tmp/error.py", line 8, in <module>
       sns.histplot(
     File "/tmp/.venv/lib/python3.12/site-packages/seaborn/distributions.py", line 1384, in histplot
       p.map_hue(palette=palette, order=hue_order, norm=hue_norm)
     File "/tmp/.venv/lib/python3.12/site-packages/seaborn/_base.py", line 838, in map_hue
       mapping = HueMapping(self, palette, order, norm, saturation)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/tmp/.venv/lib/python3.12/site-packages/seaborn/_base.py", line 150, in __init__
       levels, lookup_table = self.categorical_mapping(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/tmp/.venv/lib/python3.12/site-packages/seaborn/_base.py", line 248, in categorical_mapping
       colors = color_palette(palette, n_colors)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/tmp/.venv/lib/python3.12/site-packages/seaborn/palettes.py", line 245, in color_palette
       pal_cycle = cycle(palette)
                   ^^^^^^^^^^^^^^
   TypeError: 'ListedColormap' object is not iterable
   ```
   Note that other parts of the functional API do not claim support for `palette` to be passed as a `Colormap`. Maybe the docs of the _distributions_ and _relational_ APIs need to be updated to remove mention of colormap?
2. `sns.color_palette(..., as_cmap=True)` behaves differently with seaborn palettes compared to other palettes
   ```python
   import seaborn as sns

   # Does not work
   sns_palette = sns.color_palette("dark", as_cmap=True)
   print(type(sns_palette))  # prints <class 'list'>
   # Works
   other_palette = sns.color_palette("Dark2", as_cmap=True)
   print(type(other_palette))  # prints <class 'matplotlib.colors.ListedColormap'>
   ```

**Comment by mwaskom** [comment]
These are both currently “expected” behavior. 

For the first one, the valid types depend on whether a continuous or categorical mapping is being used.

The second one should probably at least raise (or maybe even work, but matplotlib color maps don’t generally do what you expect with categorical palettes) but I think there is already an issue about it.

**Comment by hamdanal** [comment]
> These are both currently “expected” behavior.
> 
> For the first one, the valid types depend on whether a continuous or categorical mapping is being used.

Thank you for the response. I read the docs before posting this, not sure how I missed this.

> The second one should probably at least raise (or maybe even work, but matplotlib color maps don’t generally do what you expect with categorical palettes) but I think there is already an issue about it.

Yeah I think raising in this case is better. With an error the user will at least know they are doing something wrong.

Anyway thanks for the great project and sorry for the noise.
