### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by david-waterworth** [mwaskom/seaborn#3518]
This isn't a big deal as it is well documented that if you want to plot i.e. a lowess line you need to install the optional stats dependency (i.e. `pip install seaborn[stats]` but the error message is slightly confusing as it implies the optional dependency is `statsmodels` not `stats`. I know the optional dependency `stats` triggers installation of `statsmodels` but based only on the error message I assumed `pip install seaborn[statsmodels]` 

RuntimeError: `lowess=True` requires statsmodels, an optional dependency, to be installed.

**Comment by mwaskom** [comment]
Statsmodels is the name of the specific library that you need for this feature. Running `pip install seaborn[stats]`will install several additional statistical libraries. But `stats` is not the name of the library you need, and as a seaborn “extra” it is pip-specific.

**Comment by david-waterworth** [comment]
Yeah I understand that, my point is that when I see “optional dependency” I assume that specifically refers to pip optional dependency’s but the message refers to a specific package. I’ve found it’s generally a bad practice to manually install optional dependencies (ie pip install statsmodels vs pip install seaborn[stats]) as you often end up with version mismatches.

It would be clearer if the message says “ lowess=True requires the statsmodels library, installed using the optional dependency stats.”

**Comment by mwaskom** [comment]
I appreciate that there is some room for confusion here but I’m very confident that suggested error message will lead to more people running “pip install stats” than the mistake you made.

Also in pip terminology, a “dependency” is a package, and an “extra” is a set of dependencies. But I don’t want to call out the (a) pip specific way of installing the dependency in this error message because lots of people use conda or some other approach and conda install seaborn[stats] does not work.

**Comment by mwaskom** [comment]
I'm going to close here: while the existing error message is maybe not perfect, I don't agree that it's actively misleading based on the generally-accepted definition of "dependency" in a pip context.

Given that there are many different ways to install things in Python, I don't think that including just the pip-specific approach in this kind of error message is ideal (e.g., someone who is working in a conda environment could potentially get themselves into trouble when running that command). 

If one googles "seaborn optional dependencies" it will take them to the installing page which includes the `pip install seaborn[stats]` invocation (which uses that terminology), so the language is consistent in that sense.

Thanks for the feedback though, always interested in ways to make error messages more helpful.
