### ISSUE TITLE
PDF plots are huge

### ISSUE THREAD

**Issue by domoritz** [mwaskom/seaborn#352]
``` python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
# import seaborn as sns

np.random.seed(sum(map(ord, "aesthetics")))

def sinplot(flip=1):
    x = np.linspace(0, 14, 100)
    for i in range(1, 7):
        plt.plot(x, np.sin(x + i * .5) * (7 - i) * flip)

sinplot()
plt.savefig('test.pdf', format='pdf')
```

The pdf file has a size of 13KB. The same program with seaborn imported (uncomment the import) produces a pdf with 437KB!

This is a problem when using plots as figures in a paper with limited file size. Is there a way to get smaller files? I want to avoid having to render an image.

**Comment by pradeep-ponduri** [comment]
In the code what is 'flip',unable to understand its use

**Comment by mmagnuski** [comment]
@pradeep-ponduri flip does not seem crucial for the example, but I assume it is just to use `flip=-1` which would flip the sin upside down.
