### ISSUE TITLE
kdeplot(..., label='name') does not work with plt.legend()

### ISSUE THREAD

**Issue by lzlarryli** [mwaskom/seaborn#3523]
The following way using a dataframe and hue works
```
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

d1 = pd.DataFrame({'x': np.random.randn(1000), 'y': np.random.randn(1000)})
d1['name'] = 'd1'
d2 = pd.DataFrame({'x': np.random.randn(1000) + 0.2, 'y': np.random.randn(1000) - 0.5})
d2['name'] = 'd2'
data = pd.concat([d1, d2])
sns.kdeplot(data, x='x', y='y', hue='name')
```
Result:
![image](https://github.com/mwaskom/seaborn/assets/8211938/21b28c0b-e25a-4d29-bc00-37cf59d30be6)

But if I plot these individually, it fails.
```
sns.kdeplot(d1, x='x', y='y', label='d1')
sns.kdeplot(d2, x='x', y='y', label='d2')
plt.legend()
```
Result:
![image](https://github.com/mwaskom/seaborn/assets/8211938/7cd309f4-a728-41a3-a308-610babb478de)

In particular, the line markers are missing. In my full usecase I am comparing different density plots with different settings along with a scatter plot in a for loop. In the legend, I want to show markers for the scatter plot and lines from the kdeplots. This is not possible using the dataframe approach.

**Comment by mwaskom** [comment]
`label` in seaborn functions is simply passed through to the underlying matplotlib artist and the contour artists used here don't use it:

```python
data = np.random.randn(40, 50)
plt.contour(data, colors="b", label="contour")
plt.legend()
```
```
/var/folders/qk/cdrdfhfn5g554pnb30pp4ylr0000gn/T/ipykernel_5578/65557694.py:2: UserWarning: The following kwargs were not used by contour: 'label'
  plt.contour(data, colors="b", label="contour")
WARNING:matplotlib.legend:No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
```
![image](https://github.com/mwaskom/seaborn/assets/315810/114d2cd2-dbab-41f9-9e58-6fc49ba76b39)

There would need to be a change in matplotlib for this to work.

**Comment by mwaskom** [comment]
Closing as upstream issue. If matplotlib did add this, there would need to be a small change in seaborn because we currently withhod `label` from the artist_kws to avoid triggering the warning you see above. So feel free to follow up if something changes on their end.

**Comment by lzlarryli** [comment]
@mwaskom Thank you~

For reference matplotlib/matplotlib#11134 is the upstream issue. It was closed because drawing contours with the same color is deemed too rare a case to warrant a special handling.

A workaround is to manually make the legend.
```
plot_data = [
  ('d1', d1, 'b'),
  ('d2', d2, 'r'),
]
for _, data, color in plot_data:
  sns.kdeplot(data, x='x', y='y', color=color)
handles = [lines.Line2D([0], [0], color=color) for _, _, color in plot_data]
labels = [name for name, _, _ in plot_data]
plt.legend(handles, labels)
```
![image](https://github.com/mwaskom/seaborn/assets/8211938/d0600088-7904-4fc8-b4f4-227ada078523)

**Comment by mwaskom** [comment]
Appreciate the complexities, but a little frustrating on their part IMO. Other artists (e.g. LineCollection) that can have mixed properties still allow a functional "base case" legend. In any case, yeah, you can always fake a lenged with proxy artists, or stick your data together and use `hue` in seaborn.
