### ISSUE TITLE
Enhancement: Expose the "truncate_mode" parameter of scipy.cluster.hierarchy.dendrogram() in seaborn.matrix.clustermap()

### ISSUE THREAD

**Issue by YuanfengZhang** [mwaskom/seaborn#3525]
1. The dendrogram is usually hard to read when the dataframe to draw the linkage is large, or it's too complex to show in the limited figure space sometime.
2. The workaround of preparing own linkage for the clustermap is kind of exhilarating and frustrating for users.

It would be very helpful for users drawing sns.clustermap with this parameter.
Thanks for your devotion and help.

Excepted: 
```python
sns.clustermap(*, truncate_mode: Optional[str] =None)
```

Todo:
1.  add "self.truncate_mode" property at
https://github.com/mwaskom/seaborn/blob/2c2c84e8c5d8fe8ef6b00da5bd47a54c8f5f08da/seaborn/matrix.py#L463
 2. add "self.truncate_mode" paramter at
 https://github.com/mwaskom/seaborn/blob/2c2c84e8c5d8fe8ef6b00da5bd47a54c8f5f08da/seaborn/matrix.py#L577
 3. add "self.truncate_mode" paramter at
 https://github.com/mwaskom/seaborn/blob/2c2c84e8c5d8fe8ef6b00da5bd47a54c8f5f08da/seaborn/matrix.py#L642
 https://github.com/mwaskom/seaborn/blob/2c2c84e8c5d8fe8ef6b00da5bd47a54c8f5f08da/seaborn/matrix.py#L687
 https://github.com/mwaskom/seaborn/blob/2c2c84e8c5d8fe8ef6b00da5bd47a54c8f5f08da/seaborn/matrix.py#L970
 https://github.com/mwaskom/seaborn/blob/2c2c84e8c5d8fe8ef6b00da5bd47a54c8f5f08da/seaborn/matrix.py#L974
 https://github.com/mwaskom/seaborn/blob/2c2c84e8c5d8fe8ef6b00da5bd47a54c8f5f08da/seaborn/matrix.py#L984
 https://github.com/mwaskom/seaborn/blob/2c2c84e8c5d8fe8ef6b00da5bd47a54c8f5f08da/seaborn/matrix.py#L1117
 https://github.com/mwaskom/seaborn/blob/2c2c84e8c5d8fe8ef6b00da5bd47a54c8f5f08da/seaborn/matrix.py#L1129
 https://github.com/mwaskom/seaborn/blob/2c2c84e8c5d8fe8ef6b00da5bd47a54c8f5f08da/seaborn/matrix.py#L1146
 https://github.com/mwaskom/seaborn/blob/2c2c84e8c5d8fe8ef6b00da5bd47a54c8f5f08da/seaborn/matrix.py#L1152

**Comment by mwaskom** [comment]
I am probably -1 on exposing individual parameters like this but don't immediately see why it wouldn't be possible to pass along a dictionary of such parameters. I feel like this has certainly been discussed before and I am actually a little surprised that this is not supported already which makes me think I'm missing something about why it would be complicated. Note that there would need to be two separate parameters for the row / col clustering to align with the rest of the interface.

Note that my real preference w/r/t `clustermap` is spinning it out of seaborn altogether as I don't think it fits well with the current direction of the library / API. But I've not found maintainers to adopt it.

**Comment by YuanfengZhang** [comment]
> I am probably -1 on exposing individual parameters like this but don't immediately see why it wouldn't be possible to pass along a dictionary of such parameters. I feel like this has certainly been discussed before and I am actually a little surprised that this is not supported already which makes me think I'm missing something about why it would be complicated. Note that there would need to be two separate parameters for the row / col clustering to align with the rest of the interface.
> 
> Note that my real preference w/r/t `clustermap` is spinning it out of seaborn altogether as I don't think it fits well with the current direction of the library / API. But I've not found maintainers to adopt it.

Thanks for the clarification. I understand it and 'm closing this issue.
