### ISSUE TITLE
TypeError: seaborn.matrix.heatmap() got multiple values for keyword argument 'ax'

### ISSUE THREAD

**Issue by sq-shuqian** [mwaskom/seaborn#3527]
While I wanted to draw a fig to combine several clustermap into 1 picture, I used 'plt.subplots' and add ax = axes in 'sns.clustermap' it shows multiple values, but this not happend when i try to combine heatmap. So I want to know whether clustermap have more than 1 values so it can not transfer to ax well.

Here are the part of my codes:

`for i in order:
    df = data[data.group == i ]
    group = df.pop('group')
    r_color = group.map(lut)

    g = sns.clustermap(
        data = df,
        col_cluster = False,
        cmap = 'bwr',
        vmax = 2.2,
        vmin = -2.2,
        row_colors = r_color,
        #cbar_kws=None,
        #cbar = True,
        ax = axes[n]
    )

    n += 1`

`for i in group_used:
    df = data_cut[data_cut['group'] == i]
    print(df)
    group = df.pop('group')
    g = sns.heatmap(
        data = df,
        cmap = 'bwr',
        vmax=1.2,
        vmin=-1.2,
        ax = my_grid[n],
    )
    g.set_title(f'{i}')

    n += 1`

the only difference is the kind of the picture,

**Comment by mwaskom** [comment]
clustermap is a [figure-level function](https://seaborn.pydata.org/faq.html#what-do-figure-level-and-axes-level-mean). The plot that it produces comprises multiple axes, so it is not possible to provide it with a single axes to use.

**Comment by sq-shuqian** [comment]
Thanks for your reply! I know there are too many values while used clustermap. I wonder if it is possible to split values so the dendrogram can get its own site of axes and I can combined the clustermaps together.



发自我的iPhone


------------------ Original ------------------
From: Michael Waskom ***@***.***&gt;
Date: Wed,Oct 18,2023 9:03 PM
To: mwaskom/seaborn ***@***.***&gt;
Cc: sq-shuqian ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [mwaskom/seaborn] TypeError: seaborn.matrix.heatmap() gotmultiple values for keyword argument 'ax' (Issue #3527)





 
clustermap is a figure-level function. The plot that it produces comprises multiple axes, so it is not possible to provide it with a single axes to use.

**Comment by BHM-Bob** [comment]
> clustermap is a [figure-level function](https://seaborn.pydata.org/faq.html#what-do-figure-level-and-axes-level-mean). The plot that it produces comprises multiple axes, so it is not possible to provide it with a single axes to use.

In the seaborn API reference for version 0.13.2, seaborn.clustermap's kwargs says

> All other keyword arguments are passed to heatmap().

However, seaborn.heatmap's keyword arguments do include `ax`, should the docs to be update?
