### ISSUE TITLE
How can I move the legend in seaborn 0.13

### ISSUE THREAD

**Issue by z626093820** [mwaskom/seaborn#3528]
![image](https://github.com/mwaskom/seaborn/assets/37371455/ee3ccad3-5a0a-45d5-87a1-4638af89a84f)
import seaborn.objects as so
import seaborn as sns
from seaborn import axes_style,plotting_context
so.Plot.config.theme.update(plotting_context('paper')|axes_style("ticks",rc={'axes.spines.top':False, 'axes.spines.right':False}))
data = sns.load_dataset('penguins')
((so.Plot(data, x="bill_length_mm", y="bill_depth_mm").layout(size=(3, 3))
 .add(so.Dot(), color="species").label(x="a", y="b",title="c")
 .add(so.Line(color="black"),so.PolyFit(), y="bill_depth_mm", label="depth"))
 .save(r'E:\下载\1.svg'))

thank you!

**Comment by mwaskom** [comment]
Please see prior discussion here https://github.com/mwaskom/seaborn/issues/2994
