### ISSUE TITLE
On the future deprecation of palette without hue

### ISSUE THREAD

**Issue by ReHoss** [mwaskom/seaborn#3536]
Hi,

Regarding https://seaborn.pydata.org/whatsnew/v0.12.0.html and a recent _"FutureWarning: Passing `palette` without assigning `hue` is deprecated"._ message, assigning  the same variable to `x` or `y` and `hue` would apply a color palette.

However, by doing so, the figures objects become very stretched and it becomes much less readable. See the example below:

with some variable assigned to `x` and none to `hue`:
![image](https://github.com/mwaskom/seaborn/assets/41160498/13e156c9-76bc-48d4-a7c3-6d62335c9737)

with the same variable assigned to `x` **and** `hue`:
![image](https://github.com/mwaskom/seaborn/assets/41160498/ef04f517-ac7f-4bb1-b929-f528ec371bd6)

What is the solution to keep the first behavior while providing both arguments `hue` and `x` ?

Here is the _seaborn_ function call used to produce such behavior:

```python
for kind in ["box", "violin", "bar", "strip"]:
    g = sns.catplot(
        data=df_sns[(df_sns["component"] == "weight")],
        kind=kind,
        x="ent_coef",
        y="value",
        # hue="ent_coef",
        col="norm",
        row="neural_network",
        errorbar="sd",
        palette=sns_palette,
        sharey=False)
```

Thanks for your support,

**Comment by mwaskom** [comment]
Please provide a fully reproducible example, thanks.

**Comment by mwaskom** [comment]
@ReHoss I am unable to replicate what you are seeing using an example dataset:

```python
import seaborn as sns
print(sns.__version__)
tips = sns.loadataset("tips")
sns.catplot(
    tips, x="day", y="total_bill",
    hue="day", palette="coolwarm",
    col="sex", row="smoker",
    kind="box", height=3,
)
```
0.13.0
<img width=500 src=https://github.com/mwaskom/seaborn/assets/315810/285a9e4a-173d-462f-8d48-250e85400837/>

(There is a small bug where an empty legend is drawn which is #3537; thanks for helping to surface that. You can set `legend=False` to avoid it).

I do recognize what is happening in your plot. Prior to v0.13, when using `hue` elements would be "dodged" by default, which narrows them and shifts them along the categorical axis. It is possible to disable this behavior by setting `dodge=False`. In v0.13, the default for dodge changed to `"auto"` which avoids dodging when the categorical and hue variables are redundant. v0.13 is also when the warning about passing `palette` without explicitly assigning `hue` was introduced.

My best guess is that you've gotten your versions mixed up, and maybe you saw the warning in an environment where you were running v0.13 but then changed the code in an environment where you are running v0.12. In any case, I can't help further without an example that I can use to reproduce the problem, so I am going to close the issue for now. Please feel free to share an example and we can re-open the issue if there is a bug here. And in the future, please include a reproducible example in the initial issue to save everyone some time...

**Comment by ReHoss** [comment]
@mwaskom thanks for your answer, let me check the configuration from my side to validate your hypothesis:)

**Comment by LOYINuts** [comment]
I met the exactly same problem. I need to set `dodge=False` to make figures normal. Im using seaborn 0.13.2
