### ISSUE TITLE
catplot with redundant hue assignment creates empty legend with title

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#3537]
```python
sns.catplot(tips, x="day", y="total_bill", hue="day", col="sex", row="smoker", kind="box", height=3)
```
![image](https://github.com/mwaskom/seaborn/assets/315810/53b0af1e-e133-46bb-92bd-78c91db0221b)

Set `legend=False` to workaround, but with default `legend='auto'` this should be disabled due to the redundancy.

**Comment by abdulwaheedsoudagar** [comment]
After updating the code output will be 
`sns.catplot(tips, x="day", y="total_bill", hue="day", col="sex", row="smoker", kind="box", height=3)`

![image](https://github.com/mwaskom/seaborn/assets/20552376/9ee433ea-35a7-4cb4-b170-546676888715)
