### ISSUE TITLE
FacetGrid with `size=` argument?

### ISSUE THREAD

**Issue by kwhkim** [mwaskom/seaborn#3541]
I don't know about the details of the implementation of `FacetGrid.map()`.

  But in essence it must be splitting the data frame.

  Splitting the data frame and gathering the resulting individual plots (naively) 

  seems to have problems since it does not incorporate the global features of the data.

  Using `sns.FacetGrid()` I had the hard time finding how to incorporate the size into

  `sns.scatterplot()` and I found from the tutorial that `hue=` should be specified in 

  `sns.FacetGrid()` and it looks reasonable because in the other case, the legend for the hue 

   would be in the every individual plot. And I guess It should be the same for the size!

  Unfortunately `sns.FacetGrid()` does not support `size` parameter.

  Here is my work-around 

```
import seaborn as sns
import statsmodels.api as sm

mtcars = sm.datasets.get_rdataset('mtcars').data

mtcars.head()

import math
dat = mtcars
ax_nx = 3; 
ax_ny = 2  
# ax_ny = math.ceil(dat[x_cat].nunique()/ax_nx)
x_cat = 'carb'; y_con = 'hp'; z_con = 'qsec'
w_cat = 'am'
a_con = 'hp'
fig_h = 3; fig_w = 7

g = sns.FacetGrid(dat, col=x_cat,
                                 hue = w_cat,
                                 #size = a_con,
                                 col_wrap = ax_nx,                                 
                                 height = fig_h/ax_ny, aspect = fig_w/(fig_h/ax_ny)/ax_nx) 
g.map(sns.scatterplot, y_con, z_con, w_cat, a_con)
g.add_legend()
```

Somehow `g.map(sns.scatterplot, a, b, c, d)` calls like 
`sns.scatterplot(dat_splitted, x = a, y = b, hue = c, size = d)`, 
and I don't know how to get it work like doing 
`g.map(sns.scatterplot, x=a, y=b, size = d)`, I had to specify the hue twice in `FacetGrid` and in `g.map()`. 

The final plot looks okay but I am worried that the size must be normalized to individual data splitted and there is no global legend for the size.

Is there any way to specify the size for individual plots and at the same, adding the common legend for all plots?

**Comment by mwaskom** [comment]
Yes, just as you say, `hue` in `FacetGrid` is fairly naive, basically just a group-by around independent calls to the plotting function.

The official recommendation in the docs is to use figure-level functions when you want faceted plots:

> The [figure-level](https://seaborn.pydata.org/tutorial/function_overview.html) functions are built on top of the objects discussed in this chapter of the tutorial. In most cases, you will want to work with those functions. They take care of some important bookkeeping that synchronizes the multiple plots in each grid. This chapter explains how the underlying objects work, which may be useful for advanced applications.

There is also some information about this on the `FacetGrid` API page:

> When using seaborn functions that infer semantic mappings from a dataset, care must be taken to synchronize those mappings across facets (e.g., by defining the hue mapping with a palette dict or setting the data type of the variables to category). In most cases, it will be better to use a figure-level function (e.g. [relplot()](https://seaborn.pydata.org/generated/seaborn.relplot.html#seaborn.relplot) or [catplot()](https://seaborn.pydata.org/generated/seaborn.catplot.html#seaborn.catplot)) than to use [FacetGrid](https://seaborn.pydata.org/generated/seaborn.FacetGrid.html#seaborn.FacetGrid) directly.

Unlike with `hue` (and `color=`), there is not a generic matplotlib keyword argument that controls the "size" of an artist, so it's not possible to implement a generic `size` faceting operation.
