### ISSUE TITLE
[BUG] Edge color with `catplot` with `kind=bar`

### ISSUE THREAD

**Issue by prabhuteja12** [mwaskom/seaborn#3542]
Hello, 

When passing `edgecolor` to catplot for a bar, the argument doesn't reach the underlying `p.plot_bars` to generate the required output. 

Currently there is a line 
`edgecolor = p._complement_color(kwargs.pop("edgecolor", default), color, p._hue_map)`

is _not_ passed into the block `elif kind=="bar"`.  A local "hack" I implemented is to add a `kwargs["edgecolor"] = edgecolor` before `p.plot_bars` call. Let me know if I should provide more details. 

This is on version `0.13.0`.

**Comment by mwaskom** [comment]
Can you provide a full reproducible example using one of the sample datasets? Thanks!

**Comment by prabhuteja12** [comment]
The default example shows this: 

```import seaborn as sns
df = sns.load_dataset("titanic")
g = sns.catplot(
       data=df, x="who", y="survived", col="class",
        kind="bar", height=4, aspect=.6, edgecolor="r")
g.set_axis_labels("", "Survival  Rate")
g.set_xticklabels(["Men", "Women", "Children"])
g.set_titles("{col_name} {col_var}")
g.set(ylim=(0, 1))
g.despine(left=True)
```


The output is
<img width="718" alt="image" src="https://github.com/mwaskom/seaborn/assets/11191577/be3407c7-ac0e-4271-90de-a8679930c5ad">

I see that this works as intended in 0.12.2 but not in 0.13.0.

**Comment by mwaskom** [comment]
Thanks, let's simplify even further...

```python
df = sns.load_dataset("titanic")
sns.catplot(data=df, x="who", y="survived", kind="bar", edgecolor="r")
```
![image](https://github.com/mwaskom/seaborn/assets/315810/4b099dde-078d-438f-a1ec-665583347e28)

**Comment by mwaskom** [comment]
Interestingly this works with the short-form parameter (which is why it passes the test that checks it):

```
sns.catplot(data=df, x="who", y="survived", kind="bar", ec="r")
```
<img width=400 src=https://github.com/mwaskom/seaborn/assets/315810/db511da3-0d92-44cd-ad3d-742a2fceb431/>

**Comment by prabhuteja12** [comment]
Awesome! Thank you for fixing it!
