### ISSUE TITLE
`CategoricalPlotter` broke statannotations

### ISSUE THREAD

**Issue by sjg2203** [mwaskom/seaborn#3544]
Hi,
I am using [`statannotations`](https://github.com/trevismd/statannotations) toolbox to perform statistics and add p<sub>value</sub> on a violin plot but it stopped working with `seaborn v0.13`. 

Here is the issue faced:
`statannotations` relies on `seabon v0.11`, you can push up to `v0.12.2` but not `v0.13` as this last version introduced quite some significant changes. The error message given by the package is the following [Categorical issue seaborn #133](https://github.com/trevismd/statannotations/issues/133).
Here is the code that isn't working with `seaborn v0.13`:
```python
plotter = sns.categorical._ViolinPlotter(x, y, hue, data, order, hue_order,
                bw = plot_params.get("bw", "scott"),
                cut = plot_params.get("cut", 2),
                scale = plot_params.get("scale", "area"),
                scale_hue = plot_params.get("scale_hue", True),
                gridsize = plot_params.get("gridsize", 100),
                width = plot_params.get("width", 0.8),
                inner = plot_params.get("inner", None),
                split = plot_params.get("split", False),
                dodge = True, orient=plot_params.get("orient"),
                linewidth = plot_params.get("linewidth"),
                color = None, palette = None, saturation = .75)
```

Now I tried to make it work with `seaborn v0.13`, without success:
```python
plotter = sns.categorical._CategoricalPlotter.plot_violins(self = sns.categorical._CategoricalPlotter(),
                    dodge = True, common_norm = True,
                    density_norm = "area", inner = None,
                    inner_kws = True, kde_kws = True,
                    plot_kws = True, fill = False, split = True,
                    linewidth = .5, linecolor = "black",
                    color = 'palette', gap = True, width = 0.8)
```

If anyone could help me with this, or if anyone has another method to perform a statistical test (t-test and ANOVA) and then add the p<sub>value</sub> on a violin plot, I'ld take it!

Thank you

**Comment by mwaskom** [comment]
`sns.categorical._ViolinPlotter` is a private object and no third-party code should be accessing it (unless they are fine with things breaking unexpectedly on an update). That's a very strong convention in Python and I'm afraid there's nothing I can do if downstream libraries choose not to follow it.

**Comment by mwaskom** [comment]
I'm going to close as there's no action for seaborn to take here, it's unfortunate that `statannot` got broken by the recent refactor but they should not have been reaching into seaborn's internal classes like this; I hope they're able to adapt in a more robust way going forward.

**Comment by mxposed** [comment]
@mwaskom can you please briefly outline which seaborn API way would be a more robust way? The primary need for `statannot` is to find coordinates for categorical axes with/without hue offsets.

**Comment by getzze** [comment]
What would be great is to have a better separation of concerns in `seaborn`. There could be functions that preprocess the data and functions that only plot (given the preprocessed data and coordinates).

Like how it is done in `matplotlib`, a [function that takes input data](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.violinplot.html) that first calls [a function to compute the coordinates and kernel density](https://matplotlib.org/stable/api/cbook_api.html#matplotlib.cbook.violin_stats) and then it calls [a downstream function](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.violin.html#matplotlib.axes.Axes.violin) that plots this preprocessed data.

And the same separation of concerns would be great for grouping the data. I'm thinking of a function that just split the input data into a list of dicts holding the information (data, coordinates, group name, color... ) of each subgroup. Then this list of dicts is fed to a plotting function like the one I described in the previous paragraph (preproces function + pure plotting function).

With these, dependent packages could get access to all the useful information about `seaborn` plots.

PS: I worked on making `statannotations` compatible with `seaborn v0.13`.

**Comment by mwaskom** [comment]
I don't agree that the problem is "separation of concerns". Concerns can be separated, but still *private*. Limiting public API is important for keeping a package focused and maintainable. I simple have no interest in maintaining a general purpose package for data transformation AND statistical estimation AND plotting. Seaborn is a plotting library.
