### ISSUE TITLE
Interest in seaborn.objects API contributions?

### ISSUE THREAD

**Issue by nickeubank** [mwaskom/seaborn#3546]
I've seen a few contributions floating around for the seaborn.objects API (e.g., #3320). Sounds like there's a reluctance to move too fast while the API is settling, but I happen to have a very good student looking to do some work, and I'd _love_ to see the objects API have better integration with modelling tools (especially adding SEs to `PolyFit` and adding lowess (with SEs, ideally). 

That a kind of proposal that would be welcomed?

**Comment by thuiop** [comment]
This is something that has already been discussed [here](https://github.com/mwaskom/seaborn/discussions/3133 ). In short, as the API is not stable yet, this probably will need to wait. You are free to make and share any custom made objects though ; this is only an issue about officially supporting them.

**Comment by nickeubank** [comment]
Thanks, closing in favour of that issue.
