### ISSUE TITLE
Add correlation values in the figure in version 0.13

### ISSUE THREAD

**Issue by z626093820** [mwaskom/seaborn#3549]
I want to add the correlation values of the x, y data, but when I use So.text, it shows the data of the point. How can I add the relevant values alone? Thank you

![image](https://github.com/mwaskom/seaborn/assets/37371455/b2ff596f-a263-47ae-bfe2-2139226d04f7)
![image](https://github.com/mwaskom/seaborn/assets/37371455/3208b75c-3beb-4874-9b03-fa5d73f28c66)

**Comment by z626093820** [comment]
I have calculated the correlation number 0.89, I want to add the number 0.09 separately

**Comment by JanPalasek** [comment]
@z626093820 `so.Text` attaches the value to the point. If you just want to print one number, prepare new column "text" to the dataframe. Have it empty for all points except for one that you want to attach it to. You can for example attach it to the right-most and the top-most point and color is with "aqua".

**Comment by mwaskom** [comment]
Or pass layer-specific data

```python
tips = sns.load_dataset("tips")

(
    so.Plot(tips, x="total_bill", y="tip")
    .add(so.Dots())
    .add(so.Text(text="r = 0.67"), data={}, x=[15], y=[9])
)
```
![image](https://github.com/mwaskom/seaborn/assets/315810/8b59358b-03b7-4a1b-adde-383465452524)
