### ISSUE TITLE
Seaborn 0.13 version draws the lower corner label display problem

### ISSUE THREAD

**Issue by z626093820** [mwaskom/seaborn#3550]
When I want to get 12 bids, use $ _ {12} $, but only the number 1 is set to the bid，Is this my problem or a bug, thank you
![image](https://github.com/mwaskom/seaborn/assets/37371455/b0672f9b-7106-44aa-83ca-ae3110df9f6e)
![image](https://github.com/mwaskom/seaborn/assets/37371455/9c3a5337-0cc7-4425-b1ac-bb53584cda64)

**Comment by thuiop** [comment]
This is not a seaborn issue ; as you are using an f-string, the curly braces around the "12" are being evaluated. You should use double curly braces `{{ }}` in this case I believe.

**Comment by mwaskom** [comment]
Thanks @thuiop

@z626093820 in the future please provide reproducible examples when asking questions, i.e. provide code as text and use one of the example datasets so that others can copy-paste your example and run it.
