### ISSUE TITLE
Error on example plots: Horizontal boxplot with observations

### ISSUE THREAD

**Issue by nirsun** [mwaskom/seaborn#3555]
Hi, 
I am just starting to use seaborn. I am trying to plot the 'Horizontal boxplot with observations" from https://seaborn.pydata.org/examples/horizontal_boxplot.html

This is what my plot looks (with the same exact example code shown in the link). It is different to what I find in the documentation.
![image](https://github.com/mwaskom/seaborn/assets/121650838/2059db5b-5831-4e6c-b52c-eaba1bd0f222)

There're also multiple (similar) warning messages as below:

lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):

Can you please let me know what went wrong?

Few details:
jupyter notebook or Spyder 5.4.3
python 3.11.5
macOS 13.6
 
Best,
SN

**Comment by mwaskom** [comment]
You need to update your seaborn.

**Comment by nirsun** [comment]
Thank you! The latest version (0.13.0) worked.

**Comment by mwaskom** [comment]
(For posterity, the reason is that the default value for `dodge=` has changed from `True` (always dodge) to `"auto"` (dodge unless the categorical and hue variable are redundant).
