### ISSUE TITLE
UFuncTypeError when trying to use histplot's shrink parameter with integer data

### ISSUE THREAD

**Issue by lovasoa** [mwaskom/seaborn#3565]
Hello and thank you for this great library.

I am representing a histogram of integer data, and would like to leave a small space between consecutive bars

```py
sns.histplot(np.array([1,1,1,2]), bins=[0,1,2,3], shrink=0.5)
```

this results in the following error

```
UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

![image](https://github.com/mwaskom/seaborn/assets/552629/f10aaa51-7229-4620-b83a-618084483da7)

The following works:

```py
sns.histplot(np.array([1,1,1,2]), bins=[0.,1,2,3], shrink=0.5)
```

Maybe seaborn should convert the x axis to floating point before making this multiplication ?

**Comment by mwaskom** [comment]
I can't replicate:
<img width="497" alt="image" src="https://github.com/mwaskom/seaborn/assets/315810/64d14ea0-83c2-4e2b-9158-5c9d45420345">

What version of seaborn are you using? Please take note of the contributing guidelines which contain a list of information that a bug report requires to be actionable

**Comment by mwaskom** [comment]
PS without knowing exactly what you are doing, I am guessing that rather than `bins=[0, 1, 2, 3]` (which defines the bin edges or "breaks"), you may want to be using `discrete=True`, which creates unit width bins _centered_ on whole numbers.

**Comment by lovasoa** [comment]
I was using the default version installed on google colab, which I assumed was the latest, but indeed is not. Sorry for the noise, and thank you for the suggestion !

![image](https://github.com/mwaskom/seaborn/assets/552629/bc89e650-07df-409d-a814-1126f6d18e2b)
