### ISSUE TITLE
`seaborn.histplot` with `log_scale=True` doesn't match Matplotlib's `hist`

### ISSUE THREAD

**Issue by ma-sadeghi** [mwaskom/seaborn#3579]
Two issues:

1. Matplotlib's lognorm histogram and Seaborns's equivalent normal histogram both peak at ~10, but when using `log_scale=True` with the original lognormal data, Seaborn's `histplot` peaks at ~20. Why?
2. [Minor and probably expected behaviour] When using `stat="density"` with `log_scale=True` the area sums to 1, only if done on a log-transformmed x-axis, was this intended?

Thanks! 

Here's how to reproduce:

```python
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy.stats import lognorm, norm

mu = 25
samples = lognorm.rvs(s=1, loc=0, scale=mu, size=100000)
shape, loc, scale = lognorm.fit(samples)

fig, ax = plt.subplots()
ax.set_xscale("log")
bins = np.logspace(-1, 3)
ax.hist(samples, bins=bins, density=True)
xs_lognorm = np.logspace(-1, 3, 1000)
ys_lognorm = lognorm.pdf(xs_lognorm, s=shape, loc=loc, scale=scale)
ax.plot(xs_lognorm, ys_lognorm, "r-")
ax.set_title("matplotlib.pyplot.hist")

fig, ax = plt.subplots()
sns.histplot(np.log(samples), bins=50, stat="density", ax=ax)
xs_norm = np.linspace(-1, 7, 1000)
ys_norm = norm.pdf(xs_norm, loc=np.log(mu), scale=shape)
ax.plot(xs_norm, ys_norm, "r-")
ax.set_title("seaborn.histplot")

fig, ax = plt.subplots()
sns.histplot(samples, bins=50, stat="density", ax=ax, log_scale=True)
ax.plot(xs_lognorm, ys_lognorm, "r-")
ax.set_title("seaborn.histplot with log_scale=True")
```

<img src="https://github.com/mwaskom/seaborn/assets/14086031/db1b29a2-c2b0-40dc-911a-b87e5afe8dfe" width="500">
<img src="https://github.com/mwaskom/seaborn/assets/14086031/7eb29953-207b-46b9-856a-28814bebe378" width="500">
<img src="https://github.com/mwaskom/seaborn/assets/14086031/78dfc6b6-d0c1-4e15-980d-9dbf530d2b06" width="500">

**Comment by ma-sadeghi** [comment]
Upon further looking, I think I know what's happening:

- Matplotlib's hist with `density=True` takes the non-uniform `dx` into account, and so it peaks at a different value.
- Seaborn's histplot with `stat="density"` doesn't consider non-uniform `dx`, and so passing `stat="density"` doesn't shift the peak value.

Now, the question is which makes more sense? I like Seaborn's approach better, particularly because I wasn't expecting the peak value to shift depending on which `stat` to use, so it's more intuitive to me.

I'd appreciate if others could chime in, especially the devs. Thanks!

<img src="https://github.com/mwaskom/seaborn/assets/14086031/d5495ad1-2db7-4435-813b-64211e59a41d" width="500">
<img src="https://github.com/mwaskom/seaborn/assets/14086031/ad645ed9-da53-4036-b42c-3ec7da5bf787" width="500">

**Comment by mwaskom** [comment]
I think that is close but not exactly the way I would articulate it. With `log_scale=True`, seaborn log transforms the data and then does all the statistical operations in log space: it identifies evenly spaced bins, counts observations, and normalizes to get a density. In contrast, all the statistics in matplotlib happen in linear space, using the varying-width bins that you provided, and then setting the axis scale just changes how the resulting rectangles are drawn.

You can also get the same result as you are getting in matplotlib from seaborn by passing the varying-width bins, omitting `log_scale` in the call to `histplot` but then changing the axis scale using the matplotlib API after seaborn adds the artists to it.

**Comment by ma-sadeghi** [comment]
I like your explanation, it's much simpler.

I find it a bit misleading that setting `density=True` shifts the peak in matplotlib; it's expected behaviour, that I understand, but the implication is a bit strange: it's like saying that that the data are most probable in the (0.1 - 0.2) range if you consider frequency, and (0.04 - 0.08) if you consider density. Basically, IMHO I think the shift in peak value is a numerical artifact (rather than one of physical significance) when dealing with log-normal distributions.

**Comment by mwaskom** [comment]
I agree! There's a reason that seaborn goes to the trouble to compute the stats in the appropriate space :)

**Comment by ma-sadeghi** [comment]
I'm closing this issue then, thanks for creating this amazing piece of software!

**Comment by mdhaber** [comment]
@ma-sadeghi you asked me to comment, so I was looking into this. I still think there is room for a documentation improvement.

> it identifies evenly spaced bins, counts observations, and normalizes to get a density

How is the normalization done? I'm not sure I understand the sense in which it is a density. IIUC correctly, the integral under the histogram should be 1, but I don't think that's the case.

**Comment by mwaskom** [comment]
I'm not sure I follow. The first plot in the issue is the "pure matplotlib" approach. Is your question about that, or about what seaborn is doing?

**Comment by mdhaber** [comment]
Sorry about that. The main point was that I don't understand how seaborn's plot is a "density" plot. I was showing that the pure matplotlib plot *is* a density plot. This was my way of showing that seaborn's plot can't be a "density" plot in the same sense because the area under the seaborn plot is clearly much greater.

**Comment by mwaskom** [comment]
The seaborn analogue would be

```
samples = lognorm.rvs(s=1, loc=0, scale=mu, size=10000)
bins = np.linspace(10 ** -1, 10 ** 3)
m, _ = np.histogram(np.log10(samples), bins=bins, density=True)
print(np.diff(bins) @ m)
```
```
1.0
```

**Comment by mdhaber** [comment]
OK, I get it now. I think your explanation in https://github.com/mwaskom/seaborn/issues/3579#issuecomment-1836571537 makes sense when I read it without considering what I'd expect based on the docstring. Is the the note in `log_space` that "Numeric values are interpreted as the desired base (default 10)" intended to suggest that the normalization of counts is performed based on the log of the data? Anyway, thanks; I've summed this up in @ma-sadeghi's original stackoverflow issue: "If the log-scaled axis were replaced by a linear-scaled axis with log-transformed labels, then the area under the curve would be 1.0."

**Comment by mwaskom** [comment]
> Is the the note in log_space that "Numeric values are interpreted as the desired base (default 10)" intended to mean that the normalization is performed based on the log of the data? 

No, that just means that you can pass e.g. `log_space=2`.
