### ISSUE TITLE
stripplot has misaligned x axis when mapped to barplot with hue and set width

### ISSUE THREAD

**Issue by jonpedros** [mwaskom/seaborn#3581]
```python
import seaborn as sns

sns.set_theme(style="whitegrid")
tips = sns.load_dataset("tips")
g = sns.catplot(data=tips, kind="bar", x='sex', y='total_bill', hue='smoker', col='time', width=0.35)
g.map_dataframe(sns.stripplot, x='sex', y='total_bill', hue='smoker', palette=sns.color_palette()[:2], dodge=True, jitter=False, linewidth=1)
```

![output](https://github.com/mwaskom/seaborn/assets/85462635/0a8d2311-cf0e-46a4-9c13-78600fd5d7b7)

If hue is not set:

```python
import seaborn as sns

sns.set_theme(style="whitegrid")
tips = sns.load_dataset("tips")
g = sns.catplot(data=tips, kind="bar", x='sex', y='total_bill', col='time', width=0.35)
g.map_dataframe(sns.stripplot, x='sex', y='total_bill', jitter=False, linewidth=1)
```

![output](https://github.com/mwaskom/seaborn/assets/85462635/453c3d9e-88a0-4667-b1a3-1e0e9cff0697)

**Comment by jonpedros** [comment]
I see. Plotting bars with observations as dots is quite ubiquitous in many field, so I thought it could be helpful either as a feature for `barplot` or somehow for mapping `stripplot` to an existing axis.

**Comment by mwaskom** [comment]
Sure, though of course seaborn already supports that with the default bar width. (Tbh I kind of think they look better off to the side, you can see the CI better)!

IMO adding “width” as an option in stripplot feels fairly confusing given the interaction with the existing jitter parameter so I am not sure about it.
