### ISSUE TITLE
Add 'markers' parameter to seaborn.swarmplot()

### ISSUE THREAD

**Issue by jeiglsperger** [mwaskom/seaborn#3587]
I have the following example data called `test.csv`:
```
r2_score,featureset,retailer
0.7055950484,c,S
0.942584686,c,K
0.8651950609,c,B
0.9051873402,c,H
0.5877088336,c,P
0.7944303127,c,O
0.6370605237,fc,S
0.9755270173,fc,K
0.9065356558,fc,B
0.921142567,fc,H
0.5798048892,fc,P
0.6580349995,fc,O
0.7217345443,f,S
0.9755270173,f,K
0.8839177116,f,B
0.921142567,f,H
0.5070612616,f,P
0.6580349995,f,O
0.5678318495,s,S
0.9637899061,s,K
0.9369641498,s,B
0.9297479733,s,H
0.5029283363,s,P
0.6580349995,s,O
0.5678318495,sc,S
0.9729308458,sc,K
0.8471079755,sc,B
0.9297479733,sc,H
0.497615548,sc,P
0.6580349995,sc,O
0.6624239947,w,S
0.889206858,w,K
0.7810312601,w,B
0.8562172874,w,H
0.4446346851,w,P
0.6580349995,w,O
```
And the following code:
```
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
plt.rcParams['figure.figsize'] = [15, 12]

test = pd.read_csv('test.csv')

# Calculate mean and standard deviation
mean_data = test.groupby('featureset')['r2_score'].mean().values
std_data = test.groupby('featureset')['r2_score'].std().values
colorlist = ['olivedrab', 'seagreen', 'lightseagreen', 'steelblue', 'royalblue', 'slateblue']

p = sns.stripplot(x="featureset",
                  y="r2_score",
                  hue="retailer",
                  data=test,
                  marker='^',
                  size=8,
                  palette=colorlist
                  )

for i, feature in enumerate(featuresets):
    plt.errorbar(x=feature, y=mean_data[i], yerr=std_data[i], color='black', fmt='_', capsize=3)
    
plt.legend(title='Retailer')
sns.move_legend(p, loc="upper left", bbox_to_anchor=(1, 1))

p.set(xlabel='Featureset', ylabel='R2 Score')
```
With this, I got the following plot:
![Plot](https://github.com/mwaskom/seaborn/assets/36689688/55af5998-4108-47b7-922c-9a839e9c6a9e)

I want the markers to be different for each retailer, to be more precisely, I want the markers to be the letter of the retailer. E.g. seaborn.swarmplot hast the markers parameter, to which I could pass the list with my markers. seaborn.stripplot does not have this parameter but it would be super useful, as all other methods do not produce the wanted results. For example does using a for loop lead to an overlapping of the markers and the errorbar:
```
ordered_list=['S', 'K', 'B', 'H', 'P', 'O']
retailer_list = ['A', 'B', 'C', 'D', 'E', 'F']
colorlist = ['olivedrab', 'seagreen', 'lightseagreen', 'steelblue', 'royalblue', 'slateblue']
for i in range(len(ordered_list)):    
        p = sns.stripplot(x=x_axis,
                          y="r2_score",
                          hue=hue,
                          data=test.loc[test[hue] == ordered_list[i]],
                          marker='$' + retailer_list[i] + '$',
                          size=20,
                          palette=[colorlist[i]])
```
![Plot_2](https://github.com/mwaskom/seaborn/assets/36689688/37608f9f-f446-44b5-9efc-11c3d4610475)

**Comment by mwaskom** [comment]
There has been some discussion on adding an additional marker dimension to the categorical scatterplots (you can search older issues) but for now it is out of scope and there are no plans to add it.

Note that in the objects interface you can both map the markers property and add jitter, or just use the Text mark to put letters on the plot. Your question is a little confusing as the tittle is about swarmplot but the examples use stripplot. In any case, there's not currently a corresponding set of tools to create a swarmplot in the objects interface, but there will be at some point.

Closing as the main question here has been extensively discussed elsewhere.
