### ISSUE TITLE
velocity_pseudotime: from scv.tl.latent_time vs scv.tl.velocity_pseudotime

### ISSUE THREAD

**Issue by savagyan00** [mwaskom/seaborn#3588]
I am running the basic pipeline (scvelo 0.3.1), starting from an AnnData object:

- Preprocessing

```
scv.pp.filter_and_normalize(
    adata_maca_10x, min_shared_counts=20, n_top_genes=2000, subset_highly_variable=False
)

sc.tl.pca(adata_maca_10x)
sc.pp.neighbors(adata_maca_10x, n_pcs=30, n_neighbors=30, random_state=0)
scv.pp.moments(adata_maca_10x, n_pcs=None, n_neighbors=None)
```

- run velocity
```
scv.tl.recover_dynamics(adata_maca_smartseq, n_jobs=8)
scv.tl.velocity(adata_maca_10x, mode="dynamical")
```

after this step I take one two ways 

1.  run latent_time : this generates a column "velocity pseudotime" in obs
```
scv.tl.latent_time(adata_maca_10x)

```
(when I run velocity_pseudotime after this step without velocity_graph, also different values are generated)

2. run velocity pseudotime: this also generates a column "velocity pseudotime" in obs
```
scv.tl.velocity_graph(adata_maca_10x)
scv.tl.velocity_pseudotime(adata_maca_10x)
```

But the values from these two are completely different, which I am unsure how to interpret. Can you please explain or point to documentation where I can find descriptions for these two value outputs? 

Thanks!

**Comment by mwaskom** [comment]
I think you filed this in the wrong repository?

**Comment by savagyan00** [comment]
So sorry, I confused the repository.
