### ISSUE TITLE
question about the hue option?

### ISSUE THREAD

**Issue by zdlspace0528** [mwaskom/seaborn#3589]
```
import seaborn as sns
import matplotlib.pyplot as plt


diamonds = sns.load_dataset("diamonds")
diamonds = diamonds[
    diamonds.cut.isin(['Premium', 'Good']) &
    diamonds.color.isin(['D', 'F', 'J'])
]
diamonds = diamonds.sample(n=100, random_state=20, ignore_index=True)

sns.scatterplot(data=diamonds,
                x='carat', y='price',
                hue='cut')
plt.show()
```

I have selected the cut values in ['Premium', 'Good'],  but in the graph, cut still have 5 values when I use hue=cut.

<img width="450" alt="image" src="https://github.com/mwaskom/seaborn/assets/75175622/9bf517d6-9346-434b-8253-8177953a98bd">

**Comment by mwaskom** [comment]
The `cut` column in the build-in diamonds dataset has a categorical dtype. By default, un-observed categories are included in the categorical scale. You can drop un-observed categories from your data or use `hue_order` to remove them from the plot.

**Comment by zdlspace0528** [comment]
> The `cut` column in the build-in diamonds dataset has a categorical dtype. By default, un-observed categories are included in the categorical scale. You can drop un-observed categories from your data or use `hue_order` to remove them from the plot.

Thanks so much for your help.
