### ISSUE TITLE
Heatmap doees not display all entries

### ISSUE THREAD

**Issue by dansteiert** [mwaskom/seaborn#3591]
Hi all,

I have an issue with my heatmap.
I generated a dataframe with 30k columns and here I set some of the values to a non-nan value (2k of them) (some might be double hits but that is beside the point). The values I fill the dataframe with are values between 0-1 to tell the function how to color each sample

When I plot this, I only get a low amount of hits displayed and wondered why this is.

In my real case example what is shown is even less (more rows, less non-nan's) as in this example.
Am I doing something wrong here?

python=3.12; seaborn=0.12; matplotlib=3.8.2; pandas=2.1.4 (Ubuntu=22.04)

```
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import os
import pandas as pd
    
new_dict = {}
for k in ["a", "b", "c", "d"]:
    v = {str(idx): None for idx in range(30000)}
    rand_ints = [np.random.randint(low=0, high=30000) for i in range(2000)]
    for v_hits in rand_ints:
        v[str(v_hits)] = v_hits/30000
    new_dict[k] = v

df_heatmap_hits = pd.DataFrame(new_dict).transpose()
sns.heatmap(df_heatmap_hits)
plt.show()
```

**Comment by mwaskom** [comment]
I'm not sure I understand what the problem is here. This is what I see when I run your code:

![image](https://github.com/mwaskom/seaborn/assets/315810/7ee8fcf0-9dca-4708-86d1-83c68f064278)

Your rows are ≈93% NaN. Why wouldn't you expect the resulting heatmap to be fairly sparse?

**Comment by dansteiert** [comment]
![image](https://github.com/mwaskom/seaborn/assets/37142166/b44dd9a8-2f14-4360-adc7-3c29c88c39c5)
Oh your Image looks more like what I would expect, but mine is quite a bit sparse - maybe about 20 hits.

Is there a difference in how Linux vs Windows vs Mac could behave?

**Comment by dansteiert** [comment]
To remove the randomness, I select now a specific poistion in all four groups.
I selected 300 elements to be shown in regular intervals, but only a couple are shown

`import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import os
import pandas as pd

new_dict = {}
for k in ["a", "b", "c", "d"]:
    v = {str(idx): None for idx in range(30000)}
    rand_ints = [int(i) for i in np.linspace(0, 30000, 300)] # CHANGE HERE
    for v_hits in rand_ints:
        v[str(v_hits)] = v_hits / 30000
    new_dict[k] = v

df_heatmap_hits = pd.DataFrame(new_dict).transpose()
sns.heatmap(df_heatmap_hits)
plt.show()`

![Figure_1](https://github.com/mwaskom/seaborn/assets/37142166/66f428f6-e8ef-4ac2-ba4d-ee2c4de29356)

**Comment by mwaskom** [comment]
The difference in our results is probably that I have "Retina" scaling turned on in the notebook where I made the plot.

When you render a plot to a raster image, there's going to be a limit on the resolution that you can show. e.g. if you are making a 72 dpi figure with a 4 inch width, you only have 288 pixel columns. That's requires some lossy downsampling if you're trying to plot a matrix with tens of thousands of columns.

If you're curious about the details, this is a question that comes up occasionally on the matplotlib issue tracker, so you could search there fore context / tips. But I don't think there is anything seaborn can do to avoid it.

**Comment by dansteiert** [comment]
Thank you for your quick responses and your insights into the matplotlib universe!

That meant for me the solution is just increasing the dpi
e.g. with either of the two lines where i is the required dpi number:
`        plt.rcParams['figure.dpi'] = i
        plt.rcParams['savefig.dpi'] = i`

I attached some images showing this effect on 100, 300, and 600 dpi

![figure_test_100](https://github.com/mwaskom/seaborn/assets/37142166/0e146720-457e-45b2-bb76-0007e495819a)
![figure_test_300](https://github.com/mwaskom/seaborn/assets/37142166/3f3e3719-641a-4fb9-99d5-165597665600)
![figure_test_600](https://github.com/mwaskom/seaborn/assets/37142166/8fb28735-119a-4e5b-984f-0d3b4fc1740a)
