### ISSUE TITLE
Add more detailed errorbar type (ci, pi, se, sd) description to the documentation

### ISSUE THREAD

**Issue by rk-exxec** [mwaskom/seaborn#3592]
I propose adding a short explanation of the options ci, pi, sd, and se to every function description that uses the errorbar keyword.
Like a link to the tutorial section for example, since that page never shows up in my search queries.

Showing the equations used behind the different types woul also be a benefit, as it might be unclear if the SDEV is calculated with n or n-1.

**Comment by mwaskom** [comment]
Thanks. Good suggestion.
