### ISSUE TITLE
DOC: seaborn.set_context should note that it sets the global defaults for all plots using the matplotlib rcParams system

### ISSUE THREAD

**Issue by rootsmusic** [mwaskom/seaborn#3598]
Unless I'm mistaken, the doc for [`seaborn.set_context`](https://seaborn.pydata.org/generated/seaborn.set_context.html) should note that it sets the global defaults for all plots using the matplotlib `rcParams` system.

**Comment by mwaskom** [comment]
This is called out in a few places including the [Intro page](https://seaborn.pydata.org/tutorial/introduction.html), [aesthetics tutorial](https://seaborn.pydata.org/tutorial/aesthetics.html), and in the docs for the main [set_theme](https://seaborn.pydata.org/generated/seaborn.set_theme.html) function:

> This function changes the global defaults for all plots using the matplotlib rcParams system. The themeing is decomposed into several distinct sets of parameter values.

Always hard to know when it becomes counterproductive to redundantly explain basic principles (which I'd consider this) on more focused documentation pages...

**Comment by mwaskom** [comment]
Additionally, the page you link says

> This affects things like the size of the labels, lines, and other elements of the plot, but not the overall style. This is accomplished using the matplotlib rcParams system.

So I am not sure how much additional explanation to add here? The matplotlib <> seaborn interaction can be a little bit confusing but I'd think that this is conveying the relevant information.

**Comment by rootsmusic** [comment]
> Additionally, the page you link says
> > This affects things like the size of the labels, lines, and other elements of the plot, but not the overall style. This is accomplished using the matplotlib rcParams system.

When I read the quoted sentences above, I interpreted "this" to be referencing `seaborn.set_context`.  So my understanding is that they're explaining how this function works.  My understanding isn't that this function sets the global defaults for all plots using the rcParams system.

Indeed, the doc for [`set_theme`](https://seaborn.pydata.org/generated/seaborn.set_theme.html) does note that "function changes the global defaults for all plots using the matplotlib rcParams system".  Since I'm not familiar with rcParams, I'm looking up the doc for `set_context` to learn if it requires `set_theme` to also be explicitly called in conjunction.

**Comment by mwaskom** [comment]
> I'm looking up the doc for set_context to learn if it requires set_theme to also be explicitly called in conjunction.

It does not. `set_theme` changes multiple parameter groups in one call. `set_context` changes only a subset of those parameters. Mostly you'll want to be calling `set_theme`. Probably I wouldn't have added separate `set_context`, `set_style` functions these days, but they've been around basically forever.

**Comment by rootsmusic** [comment]
> This is called out in a few places including the [Intro page](https://seaborn.pydata.org/tutorial/introduction.html), [aesthetics tutorial](https://seaborn.pydata.org/tutorial/aesthetics.html), and in the docs for the main [set_theme](https://seaborn.pydata.org/generated/seaborn.set_theme.html) function:

Because I directly referenced the API docs, I didn't come across the tutorials.  "Controlling figure aesthetics" is a helpful tutorial.  It's linked in the doc for [`set_style`](https://seaborn.pydata.org/generated/seaborn.set_style.htm), which similarly explained: "The style parameters control properties like the color of the background and whether a grid is enabled by default. This is accomplished using the matplotlib rcParams system."  (You can close this issue.  Thanks for clarifying!)

**Comment by mwaskom** [comment]
Good point that this docstring should cross-reference to the tutorial page. Thanks!
