### ISSUE TITLE
seaborn issue

### ISSUE THREAD

**Issue by ponishadevi** [mwaskom/seaborn#3609]
dataset are not load in seaborn library

**Comment by jhncls** [comment]
@ponishadevi Your post doesn't contain enough information to understand what kind of problem you encountered, and is missing error traces and version information. Maybe [this stackoverflow question](https://stackoverflow.com/questions/55711159/pandas-read-csv-from-url-and-include-request-header/55711425) is related?

**Comment by mwaskom** [comment]
Closing as not reproducible, happy to repoen if someone can provide some code demonstrating a problem.
