### ISSUE TITLE
Seaborn should respect categorical order when sorting pd.Categorical objects

### ISSUE THREAD

**Issue by shoyer** [mwaskom/seaborn#361]
For example, this adaption of the "Grouped boxplots" example should work (if using pandas 0.15 or higher) even without specifying `x_order`:
```python
import seaborn as sns
sns.set(style="ticks")

tips = sns.load_dataset("tips")
days = ["Thur", "Fri", "Sat", "Sun"]
tips['days'] = pd.Categorical(tips['day'], days)

g = sns.factorplot("day", "total_bill", "sex", tips, kind="box",
                   palette="PRGn", aspect=1.25)
g.despine(offset=10, trim=True)
g.set_axis_labels("Day", "Total Bill")
```

If you using a pandas method to do the sorting, then this is a pandas bug.

**Comment by mwaskom** [comment]
The strange behavior of unordered pandas categoricals sort of defeats the utility of relying on `.unique()`, @shoyer, cf this issue thread: https://github.com/pydata/pandas/issues/9148

**Comment by JanSchulz** [comment]
IMO if categorical variables (dtype "category") are to be plotted, the categroies should be used directly instead of `unique()`. E.g. I would expect that if I plot a lickert scale via bar plots, I expect that the complete scale is shown, not only the categories which are used. That was also once upon the time the reasoning why unique returned (all) categories (but this was changed in  https://github.com/pydata/pandas/issues/8559#issuecomment-64189570).

**Comment by mwaskom** [comment]
Interesting, I think that's a reasonable point @JanSchulz

**Comment by mwaskom** [comment]
So to make explicit what we want to happen on a categorical axis:

- For objects with ordered categorical datatype, show all categories in the correct category order
- For objects with unordered categorical datatype, show all categories in the order they appear in the Series
- Otherwise, show all unique values in the order they appear in the Series/array/list

Also this has to happen by inspecting the object attributes, not with any special pandas functions, because seaborn has to run on pandas < 0.15.

Does that sound right? If so, smarter pandas folk, what is the cleanest way to go about doing this?

**Comment by shoyer** [comment]
@mwaskom Here is my suggested implementation:

```python
def get_categories(values):
    if hasattr(values, 'categories'):
        # values is a pd.Categorical
        return np.asarray(values.categories)
    else:
        return pd.unique(values)
```

This satisfies your conditions 1 and 3, but not 2: unordered Categoricals will still display values in the order of the categories. It's definitely possible to fix that case, but it's also trickier and the order is somewhat ambiguous if not all categories appear in the data (I guess those could go to the end?). Might not be worth worrying about.

**Comment by mwaskom** [comment]
I guess it would be good to be consistent with Pandas, but I think it's better to use the DataFrame order and drop categories with no observations than the reverse (exactly for the reason you say: where to put them is undefined).

**Comment by shoyer** [comment]
So I've been playing with plotting categorical numeric data today (pretty easy when combined with `hue` on `FacetGrid`), and I do agree pretty strongly with @JanSchulz that all categories should be plotted.

Here's my example:

```python
import pandas as pd
import numpy as np
import seaborn as sns

def cut_diverging(array, n=9):
    mag = max(-array.min(), array.max())
    return pd.cut(array, np.linspace(-mag, mag, num=(n + 1)))

rs = np.random.RandomState(0)
df = pd.DataFrame({'x': rs.rand(100),
                   'y': rs.rand(100),
                   'z': 1 + rs.randn(100)})
df['z_cat'] = cut_diverging(df.z, 9)

categories = df.z_cat.cat.categories
palette = sns.color_palette('RdBu_r', 9)

g = sns.FacetGrid(df, hue='z_cat', hue_order=categories,
                  palette=palette, aspect=1.3, size=3)
g.map(plt.scatter, 'x', 'y', s=50)
g.add_legend()
```
![image](https://cloud.githubusercontent.com/assets/1217238/5869012/0dfd885e-a267-11e4-89c5-a0a449f73efc.png)

Two issues are evident in this plot:

1. The labels in the legend are wrong (notice that distribution should be mostly positive numbers). This is because I'm using labels in hue_order that don't appear in the data. (There should probably fail more loudly, but that's a separate issue).
2. Even though I went to the trouble of obtaining centered divergent categories, the color map is not centered because not every category is found.

Plotting all categories (but not bothering to order them) would solve each of these problems.

**Comment by mwaskom** [comment]
I think this is actually just a bug in `FacetGrid.add_lagend` and isn't specifically related to the category issue.

**Comment by mwaskom** [comment]
("just" a bug :fearful:)

**Comment by mwaskom** [comment]
Well, it's a bug but, it's also masked by the fact that `Legend` doesn't raise when it gets lists of different length for `handles` and `legends`, it `zip`s them, which I would not say is the best thing in the world to do.

**Comment by JanSchulz** [comment]
I'm with @shoyer: please plot all categories like they come from the categorical. If someone took the trouble to convert to categorical, the categories have a meaning (if changed manually) or are almost what you want (just converted, where the categories only have the included ones, but are AFAIK sorted lexiographical)

**Comment by mwaskom** [comment]
I agree completely about ordered categoricals, @JanSchulz. But part of the changes desired are to not sort object dtype categoricals by default, but instead to plot in order of appeareance. If unordered categoricals are plotted in lexical sort order, then we have three different things that can happen, which is going to make it harder to predict what's gonna happen from a user perspective. 

I suppose we could ditch the plan of removing the sort on non-Categorical levels, which would provide some consistency (so things will always be sorted unless they're ordered categoricals), but that's come up quite a few times as behavior that people find confusing and I think it would be beneficial to make that change.

**Comment by shoyer** [comment]
For context, my frustration with automatic sorting was because it was automatically sorting data that I really intended to be an "ordered categorical" (e.g., from `pd.cut`). So either way this change should fix that.

I agree that three cases is too many. My suggestion would be to consider treating categorical data (ordered or unordered) all the same, by simply using `values.categories` if possible and otherwise taking the unique (unsorted) values. This is exactly my `get_categories` function above. I wouldn't try to sort unordered categoricals in lex sort order (let `pd.Categorical` handle that), but just in the order in which the values appear.

**Comment by mwaskom** [comment]
> For context, my frustration with automatic sorting was because it was automatically sorting data that I really intended to be an "ordered categorical" (e.g., from pd.cut). So either way this change should fix that.

Yep, no argument here.

> I agree that three cases is too many. My suggestion would be to consider treating categorical data (ordered or unordered) all the same, by simply using values.categories if possible and otherwise taking the unique (unsorted) values. This is exactly my get_categories function above. I wouldn't try to sort unordered categoricals in lex sort order (let pd.Categorical handle that), but just in the order in which the values appear.

Won't unordered `.categories` be lex sorted? Or have I lost track of what's going on in your pandas PR?

I think your proposal makes sense in that it is reasonably easy to communicate and then to predict what's going to happen based on knowledge of the dataset.

**Comment by shoyer** [comment]
> Won't unordered `.categories` be lex sorted? Or have I lost track of what's going on in your pandas PR?

It does appear so, even if `ordered=False`:
```
In [4]: pd.Categorical(['c', 'b', 'a'], ordered=False).categories
Out[4]: Index([u'a', u'b', u'c'], dtype='object')
```

This surprised me, and we might want change it on the pandas side to not even try to sort if `ordered=False`:

**Comment by JanSchulz** [comment]
IMO the problem is that pandas `unique()` outputs unsorted (or "in order of appearance") values. AFAIK unique makes no guarantee that `unique()` outputs data in any particular order, so this could change (the docstring doesn't mention any order). This implementation is different to `np.unique()`, which does sort the values lexicographical.

IMO seaborn should not rely on any behaviour but simple add a way to change the sorting, e.g. via a kword.

Regarding categorical: If you input a categorical, you have in most cases manually declared that this variable is of categorical data, so you "know what you are doing" and if seaborn (or any other lib which want's to support categorical) declares that "to change the order of categorical data, use `cat.reorder_categories()`" this is IMO enough. In most cases you would use `c = s.astype("category")` followed by a `c.cat.ordered = False` where you would anyway have to sort the cats because during creation time they were expected to be ordered.

@shoyer the change you mention is easy enough: in https://github.com/pydata/pandas/blob/master/pandas/core/categorical.py#L271 simple `s/True/order/` :-)

**Comment by mwaskom** [comment]
> IMO the problem is that pandas unique() outputs unsorted (or "in order of appearance") values. AFAIK unique makes no guarantee that unique() outputs data in any particular order, so this could change (the docstring doesn't mention any order). This implementation is different to np.unique(), which does sort the values lexicographical.

There are two separate issues: whether `unique()` returns values in any "particular" order vs. the order of appearance, and whether the behavior of `unique()` might change. The former actually seems to be what a lot of people expect, so I wouldn't call that a problem. The second might be a problem.

> IMO seaborn should not rely on any behaviour but simple add a way to change the sorting, e.g. via a kword.

This already exists anyway, there are `x_order`, `hue_order`, etc. arguments and those won't go away. (But a lot of people seem not to read the docstrings and don't know about them...)

> Regarding categorical: If you input a categorical, you have in most cases manually declared that this variable is of categorical data, so you "know what you are doing" and if seaborn (or any other lib which want's to support categorical) declares that "to change the order of categorical data, use cat.reorder_categories()" this is IMO enough. In most cases you would use c = s.astype("category") followed by a c.cat.ordered = False where you would anyway have to sort the cats because during creation time they were expected to be ordered.

I am starting to feel like pandas categorical objects are less helpful than I was originally hoping... Though as long as `strings_as_categories=True` doesn't get added to `read_csv`, I think it's ok :)

**Comment by JanSchulz** [comment]
@mwaskom Not sure what you expected, but IMO these are the main advantages for plotting (and maybe statistical libs):
* I can easily change the order of displayed categorical data (e.g. try to order a variable with values like "one", "two", "three" -> already possible with kwords) 
* I can include empty categories at the right place (not sure if thats possible in seaborn yet).
* In ggplot I was also looking forward to using it for facets: instead of passing around the full labels (which would need an additional "context" or so), each facet would simple take this information from the the categories. This would then solve the up-to-now problem in ggplot, that displaying a categorical variable in a faceted plot would omit bars in some facets, where they were not present in the groupby dataframe.

**Comment by mwaskom** [comment]
Sure, I mean I get that. Like I said, I'm excited about them! I think my reservations have to do with the distinction between ordered and unordered categoricals, which seems to add a fair amount of complexity and confusion (I guess mostly I don't understand the point of unordered categoricals -- all of the examples you mention have to do with the ordered kind).

**Comment by shoyer** [comment]
> AFAIK unique makes no guarantee that `unique()` outputs data in any particular order, so this could change (the docstring doesn't mention any order).

Let's fix this: https://github.com/pydata/pandas/issues/9346

**Comment by mwaskom** [comment]
Maybe what's confusing is that "unordered" categoricals aren't really unordered, they're just default (lex sort) ordered.

**Comment by JanSchulz** [comment]
I will prepare the change discussed above (e.g if one constructs a categorical with `order=False` the categories are not ordered), but I suspect that we understand something different by "a categorical is ordered": The only thing what this means is that values are sortable (according to the order specified in the categories), not anything about the ordere in the categories. More like that there is an order on int (e.g. 1 < 2) and if you could take this away (odere=False), `1 < 2` would throw a exception like it does for comparing two objects.

What will IMO never happen is that if you have a ordered categorical and take away the order, the categories will be sorted "as appearing", as this would mean that the categoricals have to be computed on the fly wach tome they are acces depending on the current order of the rows.

**Comment by JanSchulz** [comment]
IMO the docs should read something like this:

The categories are either ordered like "var.unique()" or, in case the variable is of dtype "category", in the same order as the categories ("var.cat.categories"). You can change the order by resorting (all but dtype category), by changing the order of the categories variable of dtype category (var.cat.reorder_categories([....neworder...]) or by supplying [... kword args...].

**Comment by JanSchulz** [comment]
Just something I wrote in one of the linked bugreports: I think that "order of apearance" doesn't make sense as a default for plotting categoricals: I can't see many cases where the "order of appearance" of a variable has any logical meaning apart when one has explicitly sorted that var (in which case it is easier to sort the unique values) or for teh date case below:

* If it is sorted by the categorical variable, then that ordere has a meaning, but I could have done that much cheaper by sorting the unique values itself or supplying a custom ordering by kwargs
* If the frame is "unsorted" (or by some ID/Timestamp), the order of (almost) any other var including the categorical one is random and has no meaning in a categorical plot.
* The only case is when you sort by date and have a categorical "month", which has the month as a name ("Jan","Apr",...). But that would be much better handled by converting to a `Categorical`, where the order of the categories has a defined meaning. 

IMO the last is much less often the case than the "it's random" case above

So, this would be my vote: for all cases where a categorical variable is expected:
* If it is dtype `category`, take the categories and plot "as is" (order and including unused)
* if it is a string/int: take unique and sort it, [maybe convert to categorical for easier codepaths?,] then plot it. Add a warning that string was converted to categorical and one can do that by hand and change the order there.
* If one supplies a ordered list of values, overwrite both cases.

**Comment by mwaskom** [comment]
For the record here's the function I ended up using to determine a list of category levels from an arbitrary vector object:

```python
def categorical_order(values, order=None):
    """Return a list of unique data values.

    Determine an ordered list of levels in ``values``.

    Parameters
    ----------
    values : list, array, Categorical, or Series
        Vector of "categorical" values
    order : list-like, optional
        Desired order of category levels to override the order determined
        from the ``values`` object.

    Returns
    -------
    order : list
        Ordered list of category levels

    """
    if order is None:
        if hasattr(values, "categories"):
            order = values.categories
        else:
            try:
                order = values.cat.categories
            except (TypeError, AttributeError):
                try:
                    order = values.unique()
                except AttributeError:
                    order = pd.unique(values)

    return list(order)
```

IMHO there has to be a lot of complexity in this little function to handle the various options and failure  modes of working with pandas "categorical" data, but it appears to get the job done...

**Comment by shoyer** [comment]
This is indeed a helpful reference -- thanks @mwaskom!

On my TODO list is cleaning that up a little bit, at least removing that last `try`/`except` clause -- `pd.unique` should be able to handle pandas categoricals directly.

**Comment by mwaskom** [comment]
The thing I got stuck on for a while was figuring out that `obj.cat` raises `TypeError` if `obj` is a `Series` but `AttributeError` otherwise (and apparently that distinction only takes effect on Python 3). Streamlining that might be helpful to others.

**Comment by mwaskom** [comment]
Or maybe it was that `hasattr(obj, "cat")` raises a `TypeError` only on Python 3 -- anyway, "determine if `obj` has categories"` remains a bit fraught.

**Comment by shoyer** [comment]
I will double check, but I'm pretty sure this is at least consistent now between Python 2 and 3 on master. Any invalid use should now raise TypeError. I suppose there is a reasonable case that that should be AttributeError instead.

**Comment by mwaskom** [comment]
Sorry, took a little bit, but I've reproduced the issue. The following code returns `False` on Python 2.7 but raises `TypeError` on Python 3.4:

```python
import pandas as pd
x = ["a", "c", "c", "b", "a", "d"]
hasattr(pd.Series(x), "cat")
```

**Comment by mwaskom** [comment]
Alright with #548 I think categorical variables in seaborn should work as articulated in this thread and uniformly across the package.

Please open an issue if you find something that does not behave as expected.
