### ISSUE TITLE
Parameter fix in violinplot documentation

### ISSUE THREAD

**Issue by HussamCheema** [mwaskom/seaborn#3610]
Kindly fix "orient" parameter in the documentation. It is set to "y" in the documentation but it only accepts "h" or "v" as parameter.

`sns.violinplot(seaice, x="Extent", y="Decade", orient="y", fill=False)`

to

`sns.violinplot(seaice, x="Extent", y="Decade", orient="h", fill=False)`

Ref: https://seaborn.pydata.org/examples/simple_violinplots.html

**Comment by mwaskom** [comment]
"x" and "y" were added as options for `orient` in v0.13.0: https://seaborn.pydata.org/whatsnew/v0.13.0.html#other-features-enhancements-and-changes
