### ISSUE TITLE
linecolor for boxplot

### ISSUE THREAD

**Issue by phoey04** [mwaskom/seaborn#3612]
Currently, one can only pass a 'color' for the linecolor argument for sns.boxplot. 

How much work would be involved to update this parameter so a list of colours can be passed?

It would be great if my self.palette can be used as an argument for palette and linecolor.

**Comment by mwaskom** [comment]
It's unlikely that this would get added in the function interface. Although depending on what exactly you are trying to do, you may be able to get the result you want with `fill=False`. I recommend asking on stackoverflow with a clear description of how you'd like the plot to look.

**Comment by clysto** [comment]
![image](https://github.com/user-attachments/assets/57c3a584-8470-46dc-8856-080834da3652)
I think we just want to get a figure like this that controls the line colors of different groups
