### ISSUE TITLE
load_dataset cannot find example datasets

### ISSUE THREAD

**Issue by maxcoblenz** [mwaskom/seaborn#3613]
Hi all,

The load_dataset command is not working for me. I set up a new Notebook on Colab and run the following commands:
```
import seaborn as sns
data = sns.load_dataset('mpg')
```

which yields the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-4-311fb11aad21>] in <cell line: 1>()
----> 1 data = sns.load_dataset('mpg')

[/usr/local/lib/python3.10/dist-packages/seaborn/utils.py] in load_dataset(name, cache, data_home, **kws)
    585         if not os.path.exists(cache_path):
    586             if name not in get_dataset_names():
--> 587                 raise ValueError(f"'{name}' is not one of the example datasets.")
    588             urlretrieve(url, cache_path)
    589         full_path = cache_path

ValueError: 'mpg' is not one of the example datasets.
```

Also, `sns.get_dataset_names()` returns an empty list.

Colab settings:
Python version: 3.10.12
seaborn version: 0.12.2

Additionally, I managed to reproduce the error locally with a data set I have never loaded before. My local settings are different from Colab, so I don't think it has anything to do with the Python or seaborn version. 

Kind regards

Max

**Comment by mwaskom** [comment]
This does not reproduce for me on the current release of seaborn (v0.13.1) but I can reproduce prior to [this commit](https://github.com/mwaskom/seaborn/commit/e336f11eb3bdb12ee7ddcd108a4651132c123267), which changed the way that the dataset names are surfaced.

Sounds like something changed on the GitHub side of things that broke the old way of doing it? Unfortunate but not sure there's much seaborn can do about old versions.

**Comment by mwaskom** [comment]
You could update your seaborn to fix it but bear in mind that `load_dataset` is just a convenience function and not critical for normal usage of the library.

**Comment by mwaskom** [comment]
GitHub also appears to be having some issues today so it might just be related to that https://www.githubstatus.com/incidents/pxg3dz4yg7lp

**Comment by maxcoblenz** [comment]
I installed the current release and the data sets load as usual. So yes, apparently something changed somewhere else.

Thanks a lot!
