### ISSUE TITLE
In Seaborn version 0.13, how to set the legend background to transparent and the legend title to empty？

### ISSUE THREAD

**Issue by z626093820** [mwaskom/seaborn#3616]
In Seaborn version 0.13, how to set the legend background to transparent and the legend title to empty？

THANK YOU!!

**Comment by jhncls** [comment]
Is your question referencing to every possible legend of every possible seaborn function? Both with the traditional and with the object interface?

With most traditional functions, `sns.move_legend(ax, loc='best', title='', facecolor='none')` could be a way to achieve a legend with transparent background and without title.

**Comment by mwaskom** [comment]
Yes, this isn't specific enough to provide much help. Additionally, [we request](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#general-support) that "how do I..." type questions be posted on StackOverflow to keep the issue tracker free for actionable development items. I suggest putting together an example of what you're trying to do and asking there. Thanks!

**Comment by z626093820** [comment]
> Is your question referencing to every possible legend of every possible seaborn function? Both with the traditional and with the object interface?
> 
> With most traditional functions, `sns.move_legend(ax, loc='best', title='', facecolor='none')` could be a way to achieve a legend with transparent background and without title.

I want to implement this functionality within seaborn.objects.Bar. It seems that sns.move_legend(ax, loc='best', title='', facecolor='none') cannot be used in seaborn.objects.

**Comment by z626093820** [comment]
> Yes, this isn't specific enough to provide much help. Additionally, [we request](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#general-support) that "how do I..." type questions be posted on StackOverflow to keep the issue tracker free for actionable development items. I suggest putting together an example of what you're trying to do and asking there. Thanks!

I want to implement this functionality within seaborn.objects.Bar. It seems that sns.move_legend(ax, loc='best', title='', facecolor='none') cannot be used in seaborn.objects.
