### ISSUE TITLE
seaborn scatterplot hue= datetime bug

### ISSUE THREAD

**Issue by juanjuanlovelearning** [mwaskom/seaborn#3617]
### my issue is: why 2023 can appear in the below figure's legend?

**Please see below codes.**
```
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

df = pd.DataFrame(
                {"Time_str": ["2024,10,1", "2024,11,1"],
                 "x": [1, 2],
                 "y": [10, 20]
                 })
df["Datetime"] = pd.to_datetime(df["Time_str"])
df["year"] = df["Datetime"].dt.year

fig, ax = plt.subplots(figsize=(14, 8))
sns.scatterplot(data=df, x="x", y="y", hue="year")
```

 
![Figure_1](https://github.com/mwaskom/seaborn/assets/147300950/41dcc611-f856-422e-903e-598b3412d49c)

>

**Comment by mwaskom** [comment]
Than's for the self-contained example — this is what I see when I run your code

![image](https://github.com/mwaskom/seaborn/assets/315810/ff300e5c-d52f-4994-9bf0-86841a9a9239)

Your example plot can't have come from your example script — the size isn't right.

Additionally, you don't provide information about versions ([see here](https://github.com/mwaskom/seaborn/blob/a3cb0f1b33551eb25fed1907d0abdd0237fac215/.github/CONTRIBUTING.md#reporting-bugs) for what is requested).

So, hard to answer your question.

**Comment by juanjuanlovelearning** [comment]
> Than's for the self-contained example — this is what I see when I run your code
> 
> ![image](https://private-user-images.githubusercontent.com/315810/297035022-ff300e5c-d52f-4994-9bf0-86841a9a9239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTM4NzgsIm5iZiI6MTcwNTQ1MzU3OCwicGF0aCI6Ii8zMTU4MTAvMjk3MDM1MDIyLWZmMzAwZTVjLWQ1MmYtNDk5NC05YmYwLTg2ODQxYTlhOTIzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwMTA2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2Q5MDNlYzBhOGViNmIzNDUwN2FmNmJjZDE0M2YwY2I0ZThlZGNlMDY3MTEyZmNhNWVlOGYwODM5Y2Y1YzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.scC7d81jOFEmhROtjG7YhR7WBm32-7NgD-JBUoED0lY)
> 
> Your example plot can't have come from your example script — the size isn't right.
> 
> Additionally, you don't provide information about versions ([see here](https://github.com/mwaskom/seaborn/blob/a3cb0f1b33551eb25fed1907d0abdd0237fac215/.github/CONTRIBUTING.md#reporting-bugs) for what is requested).
> 
> So, hard to answer your question.

The version number list:
pandas V1.1.5
seaborn V0.9.0
matplotlib V3.0.0

**Comment by mwaskom** [comment]
Those are very old versions (seaborn v0.9.0 was released in July 2018). I'm going to close as this isn't reproducible on a more modern version. Happy to reopen if someone can demonstrate otherwise..
