### ISSUE TITLE
Resolve pandas 2.2 warnings

### ISSUE THREAD

**Issue by EwoutH** [mwaskom/seaborn#3618]
When using seaborn with the new [2.2.0rc0](https://github.com/pandas-dev/pandas/releases/tag/v2.2.0rc0) release candidate, it throws two FutureWarnings:

> C:\Users\Ewout\.virtualenvs\Py312\Lib\site-packages\seaborn\_base.py:949: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
>   data_subset = grouped_data.get_group(pd_key)

> C:\Users\Ewout\.virtualenvs\Py312\Lib\site-packages\seaborn\relational.py:293: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
>   sub_data = grouped.apply(agg, other).reset_index()

**Comment by mwaskom** [comment]
I am aware (based on [this test](https://github.com/mwaskom/seaborn/pull/3615)).

I don't know why pandas has started deprecating behavior without a period where it issues DeprecationWarning so downstream libraries can adapt before FutureWarning starts propagating out to end-user code. It's really annoying!

**Comment by EwoutH** [comment]
Thanks for working on it!

Agreed, it's not best practice. But it will only get actually removed with 3.0 right, not 2.2 already?

**Comment by lux-orc** [comment]
I got the first warning using the input of `polars.DataFrame` other than `pandas.DataFrame`

```py
import polars as pl
import seaborn as sb
import seaborn.objects as so

tips = sb.load_dataset('tips').pipe(pl.DataFrame)

p = (
    so.Plot(tips, x='total_bill', y='tip', color='time')
    .add(so.Dots())
    .add(so.Line(), so.PolyFit())
)

p.show()
```

**Comment by mwaskom** [comment]
These should be resolved on master now. I’ll try to get a release out soon.
