### ISSUE TITLE
Performance Issue: Seaborn Lineplot Execution Time Discrepancy with and without Timezones

### ISSUE THREAD

**Issue by HarryCollins2** [mwaskom/seaborn#3627]
**Issue Description:**

Hello. I encountered a notable performance difference when using Seaborn's `lineplot` function to visualize time series data, particularly when comparing plots with and without timezones. 

**Code and Observation:**

```python
import seaborn as sns

data = np.random.randn(n)

# Prepare DataFrames
dates_no_tz = pd.date_range('2019-01-01', periods=n, freq='T')
dates_with_tz = pd.date_range('2019-01-01', periods=n, freq='T', tz='UTC')
df_no_tz = pd.DataFrame({'Time': dates_no_tz, 'Value': data})
df_with_tz = pd.DataFrame({'Time': dates_with_tz, 'Value': data})

# Plot Time Series without timezone using Seaborn
%time sns.lineplot(x='Time', y='Value', data=df_no_tz).set_title('No Timezone')

# Plot Time Series with timezone using Seaborn
%time sns.lineplot(x='Time', y='Value', data=df_with_tz).set_title('With UTC Timezone')

CPU times: user 782 ms, sys: 101 ms, total: 884 ms
Wall time: 898 ms
CPU times: user 6.93 s, sys: 437 ms, total: 7.37 s
Wall time: 6.89 s
```
This represents approximately a 10-fold performance difference. Would you kindly consider conducting an analysis? 

Thank you!

**Additional Info**

matplotlib == 3.8.0
seaborn == 0.12.2
pandas == 2.1.4

**Comment by mwaskom** [comment]
Hi, I can reproduce a pretty similar difference in performance using matplotlib directly, (i.e. doing `plt.plot(df_no_tz["Time"], df_no_tz["Value"])`).

For `n=1_000_000`,

no_tz: 62.4 ms
with_tz: 5.09 s

Seems to be in the unit conversion; `plt.gca().xaxis.convert_units(df_with_tz["Time"])` takes 8.52 s (not sure why that's even longer than the plot itself takes).

So not sure there's anything seaborn can do here?

**Comment by mwaskom** [comment]
PS I just checked your profile and noticed that you have also determined that and opened a matplotlib issue about it. Would have been useful to mention here as it would have saved me the time of doing the measurement myself...

**Comment by HarryCollins2** [comment]
> PS I just checked your profile and noticed that you have also determined that and opened a matplotlib issue about it. Would have been useful to mention here as it would have saved me the time of doing the measurement myself...
Thanks for your response. My apologies... I'm relatively new to GitHub, so I wasn't aware of these rules. I'll make sure to keep them in mind going forward.

**Comment by mwaskom** [comment]
Lots of interesting discussion in the linked matplotlib issue. I'm going to close here. -1 on a warning; this is fully upstream of seaborn, only noticeable with large datasets, and a relatively niche issue.
