### ISSUE TITLE
sns.barplot(index ="index", x=" data_column1", y="data_column2") creates error due to whitespace before column name in x, y parameters

### ISSUE THREAD

**Issue by AshirMehmood** [mwaskom/seaborn#3628]
`# x: Luminousity # y: Radius
sns.barplot(star_dt, x="Radius(R/Ro)", y="Luminosity(L/Lo)")
# star_plot = star_dt.pivot(index = "Star type", columns="Luminosity(L/Lo)", values="Radius(R/Ro)")  ValueError: Index contains duplicate entries, cannot reshape
# sns.barplot(star_plot)`

please assign me this issue, thanks

**Comment by thuiop** [comment]
This issue is incomprehensible due to bad formatting and lack of reproducible example.
