### ISSUE TITLE
sns.lineplot `hue`param will make wrong number of classes when it pass a field whose dtype is not `category`

### ISSUE THREAD

**Issue by fzx401** [mwaskom/seaborn#3640]
For example, I have a dataframe which has `series_id`,`date`,`purchases` three columns and I have never changed these columns' dtype. If I use the method sns.lineplot and pass `series_id` to `hue`, the result will be wrong clearly as showed bellow:
![nQViLFTPyO](https://github.com/mwaskom/seaborn/assets/32862893/80e8c90e-9987-4ad3-8495-dfc366ea7221)
![img_v3_028e_86e05a6d-1ec3-4082-ade7-ccb541f4d2ag](https://github.com/mwaskom/seaborn/assets/32862893/3087ef15-4223-4305-9225-73d8b466b764)

**Comment by mwaskom** [comment]
This is expected behavior; please check the parameter description for `legend`
