### ISSUE TITLE
histogram with fixed binwidth - unexpected results for last column

### ISSUE THREAD

**Issue by KathSe1984** [mwaskom/seaborn#3644]
When creating a simple histogram with binwidth of 1, I was surprised that the last two numbers were merged in a single column. 

`fig = sns.histplot([0,1,1,1,3,4,6,7], binwidth=1)`

![grafik](https://github.com/mwaskom/seaborn/assets/42874724/e6b43a52-069b-40a5-a3e9-3c70ce72fc04)

Similarly, the last bar in the other example is placed directly adjacent to the previous one although I would expect a gap here:

`fig = sns.histplot([0,1,1,1,3,4,6], binwidth=1)`

![grafik](https://github.com/mwaskom/seaborn/assets/42874724/5060671c-9e0e-45fe-8151-4803e557a411)

Is this a bug or is there an explanation for this?

**Comment by mwaskom** [comment]
What version of seaborn?

**Comment by jhncls** [comment]
@KathSe1984 Maybe you want to consider `sns.histplot(..., discrete=True)`? In general, histograms work with floats, and typically the last value goes into the last bin, even if theoretically it should fall just outside. For integer input, `discrete=True` makes sure each value has its own bin.

Here is how `sns.histplot([0, 1, 1, 1, 3, 4, 6], discrete=True)` looks like. 
![image](https://github.com/mwaskom/seaborn/assets/19649483/0cabaa8a-55b8-4867-a917-8c54339bbb9a)

@mwaskom The plot shown with `binwidth=1` (without `discrete=True`) merges the two last bins, both with seaborn 0.13.2 as with the current dev version.

Personally, I don't know what the least-surprising implementation would be.  Floats can be really pesky. And typical inputs can be integers, or floats rounded to a fixed precision.

As an example, an input of `[0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1]` with `binwidth=.2`. One could stretch the binwidth by an epsilon, but then the first bin would have 3 values.  Or one could shorten the binwidth by an epsilon, and either create a weird extra bin, or make the last bin extra wide. Each approach looks strange in its own way.

The current dev version (as well as 0.13.2) for `sns.histplot([0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1], binwidth=.2)` look like 
![image](https://github.com/mwaskom/seaborn/assets/19649483/7f2e8902-6c95-44b2-953f-95cc9b6fd54d)

**Comment by mwaskom** [comment]
Agreed that `discrete=True` is probably what you want here.

**Comment by mwaskom** [comment]
I'm going to close as there's no evidence that seaborn is doing something wrong here. Thanks!
