### ISSUE TITLE
Docu: Reference to root package missing in object.inv file

### ISSUE THREAD

**Issue by buhtz** [mwaskom/seaborn#3645]
As diagnosed [here at pydocotor](https://github.com/twisted/pydoctor/issues/763#issuecomment-1971662348) it seems that the object.inv file from seaborn miss a so called "reference to the root package".

That occur the problem that using pydoctor as API doc generator I am not able to reference "seaborn" as a package. I can reference seaborn objects (functions, methods, classes) without problems. But the package itself I can not.

**Comment by mwaskom** [comment]
What is `object.inv`? There is not a file with that name in the repository.

**Comment by buhtz** [comment]
> There is not a file with that name in the repository.

Don't have to be. It is auto generated by your doc systems (e.g. Sphinx). Here it is (binary): https://seaborn.pydata.org/objects.inv

> What is `object.inv`?

It is a file generated by your doc system. It can be used by other doc systems so that one doc can link to another doc just by naming the object (e.g. a class or method) instead of using a full URL.
You do use that feature yourself. See the last lines in your `docs/conf.py`:

```
intersphinx_mapping = {
    'numpy': ('https://numpy.org/doc/stable/', None),
    'scipy': ('https://docs.scipy.org/doc/scipy/', None),
    'matplotlib': ('https://matplotlib.org/stable', None),
    'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
    'statsmodels': ('https://www.statsmodels.org/stable/', None)
}
```

Your Sphinx machine do look for a object.inv file in this URLs.

Reference about objects.inv: https://sphobjinv.readthedocs.io/en/stable/syntax.html

You as "seaborn" do offer an objects.inv. But it lacks of a root package reference. Other docus can use seaborn objects in there docstrings but not the package name itself. I don't know how to configure sphinx to achiev this.

**Comment by mwaskom** [comment]
Feel free to look into it. I'll accept a simple fix to the docs configuration if you can come up with one.

**Comment by buhtz** [comment]
Sorry, no expertise in that and also no resources for Sphinx.

**Comment by mwaskom** [comment]
OK, I'm going to close then. I don't consider this a bug in seaborn; third-party sites that want a reference for "seaborn" can link to the doc homepage, which makes more sense anyway.

**Comment by buhtz** [comment]
You are a maintainer and it is up to you of course. Compared to other packages (python, matplotlib, pandas, numpy, webcolors, openpyxl, PIL, ...) it is unusual not to have such a root reference in the objects.inv.
