### ISSUE TITLE
can jointplot visualize different classes?

### ISSUE THREAD

**Issue by hdmetor** [mwaskom/seaborn#365]
Is it possible to have different color for different classes in joinplot? Something like

```
df = pd.DataFrame(np.random.randn(100, 4), columns=list('ABCD'))
df['category'] = np.random.randint(0, high  = 5, size = 100)
sns.jointplot('B','A', data = df, color='category')
```

where a different color is used for each different value in the category column. Even better, would be possible to have a color for each value after a function is mapped to the column?
In my example, assume I would like to have a color for odd values, and another one for even values of the column, i.e.

```
sns.jointplot('B','A', data = df, color='category', map = (lambda x: x % 2))
```

**Comment by ruxi** [comment]
I wrote a gist on how to do this:

https://gist.github.com/ruxi/ff0e9255d74a3c187667627214e1f5fa

**Comment by efharkin** [comment]
@mwaskom would you consider a PR to add support for `hue` in `jointplot` and/or `JointGrid`, or at least some changes to `JointGrid.plot_{joint,marginals}` to support some of the categorical plotters? (As of now, `joint_grid.plot_marginals(sns.boxplot, hue=whatever)` raises an error about an unexpected keyword argument used to set the orientation. Seems like an easy fix and I'd be happy to work on this.)

It seems like there's a lot of demand for increased support for visualizing the distributions of categorical data (https://github.com/mwaskom/seaborn/issues/861, https://github.com/mwaskom/seaborn/issues/1486, this question). @ruxi's gist is a nice solution, but it would be great to have this behaviour or something similar directly in `jointplot`/`JointGrid`. A potential drawback of folding this behaviour directly into `JointGrid` is that the joint axis might not look very good if we use certain styles (eg hex), but I think this could be solved by raising an error.

Let me know if this fits with how you'd like to see `jointplot` and `JointGrid` used and I can work on a PR.
