### ISSUE TITLE
Doubts about using two types of graphics to draw simultaneously

### ISSUE THREAD

**Issue by z626093820** [mwaskom/seaborn#3650]
When I use two different functions to plot, using the same data, different functions result in different graphs. May I ask why? Thank you in advance！I use seaborn 0.13

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so
sns.set('paper','ticks',font_scale=1.8,font='Arial',palette=sns.color_palette('tab10'),rc=({'svg.fonttype':'none'}))
fig,ax=plt.subplots(figsize=(4,4))
sns.despine()
sns.pointplot(dfstand,x='A',y='B',ax=ax)
sns.scatterplot(dfu3,x='GC3',y='Nc',ax=ax)
![image](https://github.com/mwaskom/seaborn/assets/37371455/2d9851c3-1652-4e84-83d9-523e7009880b)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so
sns.set('paper','ticks',font_scale=1.8,font='Arial',palette=sns.color_palette('tab10'),rc=({'svg.fonttype':'none'}))
fig,ax=plt.subplots(figsize=(4,4))
sns.despine()
sns.lineplot(dfstand,x='A',y='B',ax=ax)
sns.scatterplot(dfu3,x='GC3',y='Nc',ax=ax)
![image](https://github.com/mwaskom/seaborn/assets/37371455/64dc6ba5-006a-4efb-a5cd-dcc525987430)

**Comment by thuiop** [comment]
First, please provide a reproducible example. The data you are using is unavailable here, and the code is not even formatted as code.
Second, `pointplot` is intended to be used with categorical data and thus interprets your data as such, hence the unusable plot. If you only want to represent the points for your curve, you should use a `scatterplot` instead.

**Comment by jhncls** [comment]
Since Seaborn 0.13.0, `sns.pointplot` has an extra option: `native_scale`. By default, `sns.pointplot` uses a categorical x-axis. With `native_scale=True` a numeric axis will be used instead. If you just want to show points, `sns.scatterplot` is recommended.
