### ISSUE TITLE
Refactor row_colors/col_colors from clustermap to heatmap

### ISSUE THREAD

**Issue by FedericoV** [mwaskom/seaborn#366]
Hi,

Not a huge deal, but row_colors/col_colors are generally useful when plotting a heatmap.  They are also undocumented in the API of clustermap:

http://web.stanford.edu/~mwaskom/software/seaborn/generated/seaborn.clustermap.html

I can work on a PR if @olgabot is ok with it, since it was her (awesome) work originally.

**Comment by mwaskom** [comment]
Doing some tidying and going to close this as I don't think it's going to get added to `heatmap`, but it can be accomplished through creative uses of `clustermap` or `JointGrid` + `heatmap`.
