### ISSUE TITLE
How to customize Palette in so.plot

### ISSUE THREAD

**Issue by z626093820** [mwaskom/seaborn#3673]
The following is my code, I want to customize the COLOR_PALETTE, how should I modify the following two code and thank you in advance！

import seaborn.objects as so
import seaborn as sns
from seaborn import axes_style,plotting_context
so.Plot.config.theme.update(plotting_context('paper',font_scale=1.4)|axes_style("ticks",rc={'axes.spines.top':False, 'axes.spines.right':False}))
sns.set_palette(palette='Set1')
p = so.Plot(dfupcub, 'AA', 'Fraction F',color="Codon").layout(size=(3, 3))
p.add(so.Bar(edgewidth=1), so.Stack())

When I use SNS.SET, it doesn't seem to work

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so
sns.set('paper','ticks',font_scale=1.8,font='Arial',palette=sns.color_palette('Accent'),rc=({'svg.fonttype':'none'}))
fig,ax=plt.subplots(figsize=(4,4))
sns.despine()
p = so.Plot(dfupcub, 'AA', 'Fraction F',color="Codon")
p.add(so.Bar(), so.Stack()).on(ax).plot()

**Comment by thuiop** [comment]
You need to use the [`.scale` ](https://seaborn.pydata.org/generated/seaborn.objects.Plot.scale.html#seaborn.objects.Plot.scale )method. For the rest of the configuration it should be with [`.theme`](https://seaborn.pydata.org/generated/seaborn.objects.Plot.theme.html).

**Comment by stewmehr** [comment]
@thuiop I am trying to create an exact clone of `sns.scatterplot()` via `so.Plot`, including usage of the default color palette. Is there a more elegant alternative to my attempt below to use a color palette **even if nothing has been assigned to the `color` keyword in the `Plot` call**, i.e. all I want is the beautiful seaborn shade of blue?

```python
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so

fig = plt.figure(figsize=(8,4.5))
p = (
    so.Plot(x=[1,2,3,4,5,4,3,2,1],
            y=[5,2,3,7,1,4,2,4,1])
    .on(fig)
    .add(so.Dot(edgecolor="w",
                color=sns.color_palette()[0] # <-- works but feels a bit hacky
    ))
    .layout(engine="tight")
    .plot()
)
```

Manually assigning the first element of the default palette inside `so.Dot` works but feels a bit hacky, since I may decide to use a color var later. For now, using `.scale(color=...)` in the example above fails.

**Comment by stewmehr** [comment]
Thank you, that was so helpful! I must say, the fine details of when and how matplotlib overrules seaborn continue to cause a bit of confusion on my end. Ideally, I would like to use `so` syntax exclusively. Based on #2994, repositioning the legend of `so` plots still seems to work only in combination with `.on()`, right?

**Comment by mwaskom** [comment]
Yes, `.on()` is probably more necessary than was originally intended / hoped.
