### ISSUE TITLE
Defining plot size in seaborn objects ?

### ISSUE THREAD

**Issue by mat-ej** [mwaskom/seaborn#3675]
Hi seaborn community 

I could not find the setting of the size in seaborn objects API tutorials and documentation 

I want to set plot size in a plot in a nice concise manner that works with seaborn objects: 

Example: 

`lineplop.facet('shift', wrap = 3).share(x= True, y = False)`

I can only do so as follows 

`lineplop.facet('shift', wrap = 3).share(x= True, y = False).on(mpl.Figure(figsize=(20, 10)))`

Is this the way I am supposed to be setting size in e.g. facet grid plots that do have many subplots, which are by default tiny, or there is some proper solution using .scale ?

**Comment by MaozGelbart** [comment]
Hi @mat-ej , you probably want to use [.layout](https://seaborn.pydata.org/generated/seaborn.objects.Plot.layout.html) when you want to change the default figure size.
