### ISSUE TITLE
Future deprecation of palette without hue - the proposed solution does not yield the same result

### ISSUE THREAD

**Issue by jankaWIS** [mwaskom/seaborn#3689]
Hi, 

I have a comment on the proposed change and on the Future warning that seaborn started providing:
```python
/var/folders/bx/tb4883l53hdd3zp2y0nyy_4m0000gp/T/ipykernel_19815/3866600701.py:9: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(x='day', y='total_bill', data=tips, edgecolor='k', palette=cmap, ax=axs[0])
```

I'd like to illustrate on an example that the proposed solution yields substantially different results. The code to reproduce it is the following:
```python
import seaborn as sns
print(sns.__version__)
tips = sns.load_dataset("tips")

cmap = sns.color_palette('Greys', n_colors=4)

fig, axs = plt.subplots(1,2, figsize=(10,5))

sns.barplot(x='day', y='total_bill', data=tips, edgecolor='k', palette=cmap, ax=axs[0])

sns.barplot(hue='day', y='total_bill', data=tips, edgecolor='k', palette=cmap, legend=False, ax=axs[1])

plt.show()
```

and the result looks like this:
![image](https://github.com/mwaskom/seaborn/assets/54404810/fb7c2f18-bc63-472b-958d-eea4dd39cb0d)

As you can see, there are a few differences and issues. The major one is that the x-axis in the old version contains 4 datapoints while in the new only 1 as there is only one point on the x-axis. This leads to the visual issues. You now cannot label the x-axis like before unless you start playing with it manually. The bars are squeezed without any space between them. Again, you may play with it manually, but the beauty is in simplicity and this change makes you work twice as hard.

I guess that you might object to the fact that either the colour or the x-axis tick labels are redundant as they convey the same information. That is, however, not true. You may want to preserve the colours because you have another plot where the exact same categories appear because it is more visual, or for other reasons. Even if this is the argument for the change, the warning doesn't give instructions on visually reproducing the same plot.

Related (but different) issue:
https://github.com/mwaskom/seaborn/issues/3536

**Comment by mwaskom** [comment]
The remediation is to *additionally* assign `hue`, not the *re*-assign `x`:

```
sns.barplot(x='day', hue='day', y='total_bill', data=tips, edgecolor='k', palette=cmap, legend=False, ax=axs[1])
```

![image](https://github.com/mwaskom/seaborn/assets/315810/4d7b25fa-2a21-44e9-98a7-1ca16bc633b9)

**Comment by jankaWIS** [comment]
Ah, ok, that was not clear from the warning. Thanks!

**Comment by jankaWIS** [comment]
Sorry, I have one more question, how can I access the legend? The regular:

```
axs[1].legend()
```

gives 
```
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
```
The legend is there if you use only the hue:
```
sns.barplot(hue='day', y='total_bill', data=tips, edgecolor='k', palette=cmap)
```
but that is not what I want.

**Comment by mwaskom** [comment]
You would need to add labeled artists.

**Comment by jsgounot** [comment]
Hi, may I suggest editing the warning message to reflect what has been said here? The current warning is confusing and I had to come here to confirm how to fix my plots.
