### ISSUE TITLE
Expose error estimators and other statistical summary measures used for plots which perform aggregation and error estimates

### ISSUE THREAD

**Issue by gmonkman** [mwaskom/seaborn#3698]
Would be a time saver and extremely useful if seaborn could expose statistical summary measures and error estimates that seaborn uses to create some plots.

And example is a barplot which potentially (obviously) uses a categorical x, plus a second fixed factor (hue) and a custom bootstrap to estimate confidence intervals. To be able to dump that data out would be incredibly useful.

thanks for an absolutely wonderful package.

**Comment by mwaskom** [comment]
Hi, sorry but this is considered out of scope and that is very unlikely to change: https://seaborn.pydata.org/faq.html#statistical-inquiries
