### ISSUE TITLE
Overlaying Plots

### ISSUE THREAD

**Issue by LJDrakeley** [mwaskom/seaborn#3708]
I'm experiencing an issue with overlaying both a boxplot and lineplot on the same axis. 
The data consists of three columns: Side, Dose, Volume.

[dvhTestData.csv](https://github.com/user-attachments/files/15776809/dvhTestData.csv)

Side: ['ipsilateral', 'contralateral'] (These are my hue)
Dose: range from 0-6000 in 1000 increments.
Volume: Percentage ranging from 0-100%

```

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df = pd.read_csv('dvhTestData.csv')

hue_order = ['ipsilateral', 'contralateral']
palette = 'bright'

# Calculate the average for each side
average_df = df.groupby(['Side','Dose',])['Volume'].mean().reset_index()

fig, ax = plt.subplots()
sns.boxplot(data=df, x='Dose', y='Volume', hue='Side',
             hue_order=hue_order, palette=palette, fill=False, ax=ax)
sns.lineplot(data=average_df, x='Dose', y='Volume', hue='Side', 
             hue_order=hue_order, palette=palette, ax=ax)

```
![output](https://github.com/mwaskom/seaborn/assets/103962997/8735cb2d-ac92-408b-92ea-eeb66e3f4cc5)

However, if I limit the x-axis to [0,7] we get the following output:

```

fig, ax = plt.subplots()
sns.boxplot(data=df, x='Dose', y='Volume', hue='Side',
             hue_order=hue_order, palette=palette, fill=False)
sns.lineplot(data=average_df, x='Dose', y='Volume', hue='Side', 
             hue_order=hue_order, palette=palette)
ax.set_xlim(0, 7)

```

![output2](https://github.com/mwaskom/seaborn/assets/103962997/8dcdd18d-3317-4efb-abdb-ff413e694c7e)

It seems as though the boxplot is being plotted in the range [0,6] rather than [0, 6000] as expected. If anyone could help explain if I'm incorrectly overlaying plots, or if there is an easy work-around, I would greatly appreciate it. 

Best,
Lewis

**Comment by mwaskom** [comment]
> It seems as though the boxplot is being plotted in the range [0,6]

Indeed: https://seaborn.pydata.org/generated/seaborn.boxplot.html

<img width="619" alt="image" src="https://github.com/mwaskom/seaborn/assets/315810/042b818f-c7e8-41b4-ac46-975b1f63954d">

**Comment by mwaskom** [comment]
Closing as documented behavior
