### ISSUE TITLE
Add a second legend in a strip plot within FacetGrid. Is it possible?

### ISSUE THREAD

**Issue by ihouses** [mwaskom/seaborn#3709]
Hello, I need to generate a strip like in the picture where I added the second legend (partname) as an example. The markers that the arrow is pointing are examples as well. The rest is generated with a striplot within a FacetGrid.

Is that possible?

<img width="826" alt="Screenshot 2024-06-10 at 23 18 47" src="https://github.com/mwaskom/seaborn/assets/5103057/e21b981b-7452-4e07-bebd-8cdaca6e09d5">

**Comment by mwaskom** [comment]
Hi, I suggest creating a minimal example and asking on StackOverflow. Thanks!
