### ISSUE TITLE
AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'

### ISSUE THREAD

**Issue by Shravan-aero** [mwaskom/seaborn#3711]
I ran Seaborn earlier, and it was working well. After a month, I ran the same code, which showed the following error:
AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'. I try installing the Seaborn package and some more updates. It's not working with the same error. The error occurs explicitly while importing the seaborn library, not for matplotlib (matplot is working for other codes), but the same error occurs for another library (i.e. pingouin, etc.).

![Capture](https://github.com/mwaskom/seaborn/assets/172484443/c1fb2d44-7213-47a6-b76e-4f233867d882)

**Comment by mwaskom** [comment]
Looks like you are not using the latest version of seaborn, which handles this API change in matplotlib: https://github.com/mwaskom/seaborn/blob/master/seaborn/_compat.py#L67
