### ISSUE TITLE
set_hatch not work in boxplot

### ISSUE THREAD

**Issue by eeeXun** [mwaskom/seaborn#3716]
Hi, I just follow [this code](https://github.com/mwaskom/seaborn/issues/1456#issuecomment-399002203) to use the `set_hatch` in `boxplot`. But it doesn't seem to work for me.

```python
from itertools import cycle

from matplotlib import pyplot as plt
import seaborn as sns; sns.set()

# Load dataset
tips = sns.load_dataset('tips')

# Define some hatches
hatches = cycle(['///', 'x'])

# Boxplot
ax = sns.boxplot(x="day", y="total_bill", hue="sex", data=tips)
for i, patch in enumerate(ax.artists):
    # Boxes from left to right
    hatch = next(hatches)
    patch.set_hatch(hatch)

ax.legend(loc='best')
plt.show()
```

![download](https://github.com/mwaskom/seaborn/assets/58657914/8102d4dc-753e-4cf7-9b24-6fe011300622)

My `python` version is `3.10.12`. `seaborn` version is `0.13.2`. `matplotlib` version is `3.9.0`. Is there any change in the `set_hatch` or it just break by `matplotlib`?

**Comment by mwaskom** [comment]
It's possible that matplotlib changed the underlying data model as `ax.artists` is empty in your example script. But you can access the box patches more directly at `ax.patches`. Also seaborn v0.13 started packaging the boxplot artists in a container and storing it at `ax.containers` which is another way of making your post-processing a bit more explicit.

**Comment by eeeXun** [comment]
Thanks. Changing `ax.artists` to `ax.patches` works for me.

```python
from itertools import cycle

from matplotlib import pyplot as plt
import seaborn as sns; sns.set()

# Load dataset
tips = sns.load_dataset('tips')

# Define some hatches
hatches = cycle(['///', 'x'])

# Boxplot
ax = sns.boxplot(x="day", y="total_bill", hue="sex", data=tips)
for i, patch in enumerate(ax.patches):
    # Boxes from left to right
    hatch = next(hatches)
    patch.set_hatch(hatch)

ax.legend()
plt.show()
```

But what do you mean `ax.containers`? Changing `ax.artists` to `ax.containers` gives the error that `BoxPlotContainer` has no attribute `set_hatch`. Do I call it the wrong way?

**Comment by mwaskom** [comment]
> Do I call it the wrong way?

Yes — do e.g.

```python
bxp = ax.containers[0]
bxp.boxes
```
```
[<matplotlib.patches.PathPatch at 0x12b095a50>,
 <matplotlib.patches.PathPatch at 0x12b0a4950>,
 <matplotlib.patches.PathPatch at 0x12b0602d0>,
 <matplotlib.patches.PathPatch at 0x12b0636d0>]
```

**Comment by eeeXun** [comment]
Hi @mwaskom, after trying again. `ax.containers` is exactly what I want.

```python
from matplotlib import pyplot as plt
import seaborn as sns; sns.set()

# Load dataset
tips = sns.load_dataset('tips')

# Define some hatches
hatches = ['///', 'x']

# Boxplot
ax = sns.boxplot(x="day", y="total_bill", hue="sex", data=tips)
for i in range(2):
    for box in ax.containers[i].boxes:
        box.set_hatch(hatches[i % len(hatches)])

ax.legend()
plt.show()
```
![download](https://github.com/mwaskom/seaborn/assets/58657914/11a003b3-0bbd-4131-9b23-906a86d91e11)

But the legend did not get the hatch style. Is there any way to do that?

**Comment by mwaskom** [comment]
You can modify those artists too, i think it's something like `ax.get_legend().legend_handles`

**Comment by eeeXun** [comment]
```python
from matplotlib import pyplot as plt
import seaborn as sns; sns.set()

# Load dataset
tips = sns.load_dataset('tips')

# Define some hatches
hatches = ['///', 'x']

# Boxplot
ax = sns.boxplot(x="day", y="total_bill", hue="sex", data=tips)
ax.legend()
for i in range(2):
    for box in ax.containers[i].boxes:
        box.set_hatch(hatches[i % len(hatches)])
    ax.get_legend().legend_handles[i].set_hatch(hatches[i % len(hatches)])

plt.show()
```
![download](https://github.com/mwaskom/seaborn/assets/58657914/82f5d056-43d3-42dc-98b8-2e636cfcd013)

Thank you again for your help!
