### ISSUE TITLE
feature request: style conditioning variable in displot like in relplot

### ISSUE THREAD

**Issue by PaulLerner** [mwaskom/seaborn#3717]
Hi, thanks for the great library!

`relplot` provides a great option to condition the style of the scatter plot on some column of the dataframe:

`sns.relplot(results, y="Fertility",x="Deriv - Base", hue="Morph", style="seg",alpha=0.1)`
![image](https://github.com/mwaskom/seaborn/assets/25532159/33c586c3-bfc2-442e-8ccb-1af780505438)

Can we have the same for `displot`?

`sns.displot(results, x="Deriv - Base", hue="Morph", discrete=True,style="seg")`

Something that would look like

![image](https://github.com/mwaskom/seaborn/assets/25532159/23188316-cd24-4643-ac49-5e99b4db5ee7)

(rough matplotlib code)

```py
plt.hist(results[(results["Morph"]=="Prefix") & (results["seg"] == "BPE")]["Deriv - Base"], bins=bins,histtype='step',label="Prefix-BPE",alpha=0.5,color="tab:orange")
plt.hist(results[(results["Morph"]=="Suffix") & (results["seg"] == "BPE")]["Deriv - Base"], bins=bins,histtype='step',label="Suffix-BPE",alpha=0.5,color="tab:blue")
plt.hist(results[(results["Morph"]=="Prefix") & (results["seg"] == "morph")]["Deriv - Base"], bins=bins,label="Prefix-Morph",alpha=0.5,color="tab:orange")
plt.hist(results[(results["Morph"]=="Suffix") & (results["seg"] == "morph")]["Deriv - Base"], bins=bins,label="Suffix-Morph",alpha=0.5,color="tab:blue")
plt.legend()
```

**Comment by mwaskom** [comment]
Unfortunately this would require some fairly deep changes so it's unlikely to happen. But you can use the objects interface if you want more mapping flexibility.

**Comment by PaulLerner** [comment]
Ok, thanks for the quick answer, I'll look into it (http://seaborn.pydata.org/tutorial/objects_interface)
