### ISSUE TITLE
The way to change the size of title in so.plot.label(title="...")

### ISSUE THREAD

**Issue by ngvananh2508** [mwaskom/seaborn#3718]
Hi,
Thank you for wonderful library.
I have a wonder that whether any way to change the size of title in so.plot.label(title= "..."). I referred you documentation and I did not find any information related to this. 
Thank you for helping me!

**Comment by mwaskom** [comment]
You can use `.theme `for this.

**Comment by ngvananh2508** [comment]
I am sorry but when I use .theme({"axes.titlesize"}: 'large}) or "figure.titlesize". There are not any change in the size of the title.
