### ISSUE TITLE
Feature Request: Move x-axis labels to the top in PairGrid

### ISSUE THREAD

**Issue by guillepaez53** [mwaskom/seaborn#3725]
Description:
I would like to request the ability to move x-axis labels to the top in a Seaborn PairGrid. 

From my point of view, pairplots with x-axis labels at the top will be more readable because the first variable on the y-axis would be next to the same variable on the x-axis, and so on.

Proposed Solution:
Implement a method or parameter in PairGrid that allows users to easily move the x-axis labels to the top. This could be similar to the functionality available in Matplotlib's Axes where methods like tick_top() and set_label_position('top') are used.

Thank you for considering this feature request!

![image](https://github.com/mwaskom/seaborn/assets/84234378/e89ad672-de49-4d91-82f0-cbe4ec975fd8)

**Comment by mwaskom** [comment]
> This could be similar to the functionality available in Matplotlib's Axes where methods like tick_top() and set_label_position('top') are used.

You can call these methods on the axes that `PairGrid` exposes to you; no need for new seaborn API here imo

**Comment by guillepaez53** [comment]
Thanks for the answer! Actually, I've tried with the existing methods but it didn't work, even asking and iterating with ChatGPT many times, and searching in StackOverflow.

In some cases, nothing happened. In other cases, only the x ticks were moved to the top of the PairGrid, but not the x labels. In other cases, some x labels were moved, but only to the top of plots in the last row, not to the top of the PairGrid.

Here are two of several blocks of code I've tried. Maybe it's me making some mistake, I'm not so good.


1. 

import matplotlib.pyplot as plt
import seaborn as sns

g = sns.PairGrid(df[['meses_antig', 'edad', 'cuota_mensual', 'abandono_etiqueta']], hue='abandono_etiqueta')

g.map_diag(sns.kdeplot)
g.map_offdiag(sns.scatterplot)

for ax in g.axes[0, :]:
    ax.xaxis.set_label_position('top')
    ax.xaxis.tick_top()

g.fig.set_size_inches(8, 4)

plt.show()

![image](https://github.com/mwaskom/seaborn/assets/84234378/2bf84524-026a-4085-b82f-0c385a57b8f2)


2.

import matplotlib.pyplot as plt
import seaborn as sns

g = sns.pairplot(data=df[['meses_antig', 'edad', 'cuota_mensual', 'abandono_etiqueta']], hue='abandono_etiqueta')

g.axes[0,0].xaxis.tick_top()
g.axes[0,0].xaxis.set_label_position("top")
g.axes[0,1].xaxis.tick_top()
g.axes[0,1].xaxis.set_label_position("top")
g.axes[0,2].xaxis.tick_top()
g.axes[0,2].xaxis.set_label_position("top")

g.fig.set_size_inches(8, 4)

plt.show()

![image](https://github.com/mwaskom/seaborn/assets/84234378/250f9e7e-d66c-416c-b6bc-bc9d8786ad23)

**Comment by guillepaez53** [comment]
Well, I've been struggling a little, and I could move the `xlabels` to the top, but I couldn't move the `xticklabels`. Better said, I could move them, but with weird formats (inside lists, and not placed correctly).

_I still think it would be very useful to have a parameter in the `pairplot`, or a method in the `PairGrid`, to move the `xlabels` and the `xticklabels` to the top more straightfoward_. It will increase a lot the readability, because the first variable on the y-axis would be next to the same variable on the x-axis, and so on. Otherwise,  when you have lots and lots of variables, it's very tedious to look at the below.

This is my new code:

```
g = sns.pairplot(data=df, hue='abandono_etiqueta')

for i, ax in enumerate(g.axes[0, :]):
    xlabel = g.axes[-1, i].get_xlabel()
    ax.set_xlabel(xlabel)
    g.fig.text(ax.get_position().x0 + ax.get_position().width / 2, 
            ax.get_position().y1 + 0.03, 
            xlabel, ha='center', va='bottom') 

for i in range(g.axes.shape[1]):
    g.axes[-1, i].set_xlabel('')

g.fig.set_size_inches(8, 4)

plt.show()
```

And this is my result (with the xticklabels still below):

![image](https://github.com/mwaskom/seaborn/assets/84234378/6bf3dd2b-f4b9-4af9-b3d3-cfa055b76803)

Thanks a lot for considering it. If not, thanks for reading and answering anyway.
