### ISSUE TITLE
Kwargs can't be passed from seaborn to matplotlib

### ISSUE THREAD

**Issue by nspiller** [mwaskom/seaborn#3726]
Hi,

I wanted to modify the ranges of the color bar in a scatterplot with `vmin`:
```
import seaborn as sns

x = [1, 2, 3, 4, 5]
y = [2, 3, 4, 5, 6]
z = [1, 2, 3, 4, 5]

sns.scatterplot(x=x, y=y, hue=z, palette='coolwarm', vmin=0)
```

The [scatterplot documentation ](https://seaborn.pydata.org/generated/seaborn.scatterplot.html) states that I can pass additional keyword arguments down to [`matplotlib.axes.Axes.scatter`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.scatter.html#matplotlib.axes.Axes.scatter). However, I am getting an error when I include `vmin=0`. 

Am I reading the documentation wrong? Which keywords can be used here?
> kwargs: key, value mappings
> Other keyword arguments are passed down to [matplotlib.axes.Axes.scatter()](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.scatter.html#matplotlib.axes.Axes.scatter).

Looking into the seaborn code, I can see that while the keyword is [correctly handed to the `ax.scatter` method](https://github.com/mwaskom/seaborn/blob/09195d4c314d9477866ba4bd5cb650c3a7c01e41/seaborn/relational.py#L438), it is also passed later to `mpl.lines.Line2D` in [`self._scatter_legend_artist()`](https://github.com/mwaskom/seaborn/blob/09195d4c314d9477866ba4bd5cb650c3a7c01e41/seaborn/utils.py#L859C33-L859C34), 
which then raises the error shown below. 

seaborn 0.13.2

Part of the error in seaborn:
```
File c:\Users\user\miniforge3\envs\seaborn\Lib\site-packages\seaborn\relational.py:636, in scatterplot(data, x, y, hue, size, style, palette, hue_order, hue_norm, sizes, size_order, size_norm, markers, style_order, legend, ax, **kwargs)
    633 color = kwargs.pop("color", None)
    634 kwargs["color"] = _default_color(ax.scatter, hue, color, kwargs)
--> 636 p.plot(ax, kwargs)
    638 return ax

File c:\Users\user\miniforge3\envs\seaborn\Lib\site-packages\seaborn\relational.py:464, in _ScatterPlotter.plot(self, ax, kws)
    462 if self.legend:
    463     attrs = {"hue": "color", "size": "s", "style": None}
--> 464     self.add_legend_data(ax, _scatter_legend_artist, kws, attrs)
    465     handles, _ = ax.get_legend_handles_labels()
    466     if handles:

File c:\Users\user\miniforge3\envs\seaborn\Lib\site-packages\seaborn\_base.py:1267, in VectorPlotter.add_legend_data(self, ax, func, common_kws, attrs, semantic_kws)
   1265     if attr in kws:
   1266         level_kws[attr] = kws[attr]
-> 1267 artist = func(label=label, **{"color": ".2", **common_kws, **level_kws})
   1268 if _version_predates(mpl, "3.5.0"):
   1269     if isinstance(artist, mpl.lines.Line2D):

File c:\Users\user\miniforge3\envs\seaborn\Lib\site-packages\seaborn\utils.py:880, in _scatter_legend_artist(**kws)
    877     else:
    878         line_kws["markeredgecolor"] = edgecolor
--> 880 return mpl.lines.Line2D([], [], **line_kws)
```

**Comment by mwaskom** [comment]
If you're using `hue` then seaborn is controlling the coloring of the scatterplot points and you need to use seaborn parameters to further customize (e.g. `hue_norm`).
