### ISSUE TITLE
Adding plot type metadata to support textual figure descriptions

### ISSUE THREAD

**Issue by psychemedia** [mwaskom/seaborn#3729]
The `.get_X()` methods support the retrieval of a wide range of information about a chart axes object that can be useful when generating textual descriptions a chart (for example, the chart title, axis labels, axis limits, etc.). Such descriptions can help improve the accessibility of chart objects, and provide a more exact and deterministic way of providing a written description of a chart than passing a chart image to a multimodal LLM and asking it to describe the chart type it sees.

It would be useful if the axes object also had metadata regarding the chart type, which would allow for simpler parsing of axes object properties when trying to identify and describe various chart types.

**Comment by mwaskom** [comment]
Not totally sure what the request is here, but the `get_X` methods are part of matplotlib not seaborn.
