### ISSUE TITLE
Consider adding mpl.Figure as an optional argument to subplot functions / classes.

### ISSUE THREAD

**Issue by colm-brandon-ul** [mwaskom/seaborn#3734]
I've recently be working on an interactive visualisation tool and several seaborn fn's generate the mpl figure internally. When doing interactive plots with ipython you ideally have a single figure and redraw it, which is incompatible with a lot of seaborn's plotting fn's that contain subplots (e.g. FacetGrid).

Not sure if this use-case is overly niche or if there's a reason I've overlooked for not faciliating this functionality, but if that isn't the case a solution may be to allow a figure to be passed as an argument (shown below).

```python
class FacetGrid(Grid):

  def __init__(
          self, data, *,
          row=None, col=None, hue=None, col_wrap=None,
          sharex=True, sharey=True, height=3, aspect=1, palette=None,
          row_order=None, col_order=None, hue_order=None, hue_kws=None,
          dropna=False, legend_out=True, despine=True,
          margin_titles=False, xlim=None, ylim=None, subplot_kws=None,
          gridspec_kws=None, fig=None
      ):
    ...
    if fig:
      ...
    else:
      with _disable_autolayout():
        fig = plt.figure(figsize=figsize)
    ...
```

**Comment by mwaskom** [comment]
Hi — this has been discussed a few times if you search!
