### ISSUE TITLE
Customizing context or style as in seaborn as in matplotlib?

### ISSUE THREAD

**Issue by disadone** [mwaskom/seaborn#3737]
I need to unify the format, dpi ... for my figures.
I use a [program](https://github.com/disadone/pyperplot) for matplotlib, and all the seaborn command that can have an `ax` parameter.
However, some plot cannot have an `ax` parameter, such as `relplot`,`pairplot`,...

Just wonder how can I quickly unify these figures format self-defined?
There is a customizing tutorial in matplotlib, https://matplotlib.org/stable/users/explain/customizing.html.
Is there any tutorial helping customize context? Or is there any way that matplotlib format could control `relplot`,`pairplot`,...

Thanks!

**Comment by mwaskom** [comment]
Seaborn uses matplotlib, so its figures can be customized with the same rc parameters.
