### ISSUE TITLE
Adding precomputed errorbars to pointplot

### ISSUE THREAD

**Issue by e-pet** [mwaskom/seaborn#3740]
Hi, 

I have a pandas dataframe with precomputed statistics of the form `pd.DataFrame({'group': ['A', 'B', C'], 'med': [1.0, 2.0, 3.0], 'lower': [0.5, 1.5, 1.5], 'upper': [5.0, 4.0, 3.5]})`. I would like to create a pointplot with errorbars from this. I know that pointplot currently does not natively support this. (I for one would appreciate it if it did.) Previously, I was using [this workaround](https://stackoverflow.com/a/46811162/2207840), but it seems to have broken recently for some reason. Is there any way I can currently achieve this?

**Comment by mwaskom** [comment]
Hi, seaborn's plotting functions don't support pre-supplied error bars, sorry; I recommend you use matplotlib for that. The linked Stackoverflow question is 7 years old so any number of things could have changed in the meantime!
