### ISSUE TITLE
ModuleNotFoundError: No module named 'seaborn'

### ISSUE THREAD

**Issue by Arbaz-39** [mwaskom/seaborn#3752]
Hi,
I am trying to import `seaborn` module but getting an error.
ModuleNotFoundError: No module named 'seaborn'. 

Tried by installing seaborn in jupyter notebook's cell by command:
!pip install seaborn but getting  an error,
OSError: Not available 

How to fix this error. Please suggest. 
![IMG20240825114626](https://github.com/user-attachments/assets/899f37bb-e5d8-4e80-9bdd-fed9320f5504)

**Comment by mwaskom** [comment]
Hi, this sounds like an issue with your personal setup; unfortunately I am unable to provide support.
