### ISSUE TITLE
`so.Range()` cannot be "overplotted" by an additional mark added with so.Plot.add()

### ISSUE THREAD

**Issue by noboss93** [mwaskom/seaborn#3753]
As far as I understood seaborn.objects correctly, marks that get added later should overplot previous marks. However, it seems like that the `so.Range()` mark allways stays on top of later added marks.

```
import seaborn.objects as so

y = range(1,100)
x = range(1,100)

(
    so.Plot(x=x, y=y)
    .add(so.Range(linewidth=5, color="#A20013"), so.Est(errorbar=("pi", 50)), y=[50]*99, orient="y")
    .add(so.Dot(pointsize=30, color="Blue"), so.Agg(func="median"), y=[50]*99, orient="y")
    .add(so.Dot(pointsize=20, color="Green"), so.Agg(func="median"), y=[50]*99, orient="y")

)
```

![image](https://github.com/user-attachments/assets/1a4f465d-1160-4eb1-8073-f04a35a697d6)

**Comment by mwaskom** [comment]
You can pass `zorder` in `artist_kws`.
