### ISSUE TITLE
seaborn objects directly specifying color

### ISSUE THREAD

**Issue by SamKG** [mwaskom/seaborn#3759]
I'm wondering if there's any way to directly specify the color of every single datapoint via seaborn objects. Currently, specifying the `color` variable groups the values and assigning a separate color to each group

I was wondering if instead there was a way to manually assign colors, e.g. via a list of the same size as the input data.

**Comment by mwaskom** [comment]
It sounds like you are looking for

> Or pass None to use an “identity” scale, which treats data values as literally encoding visual properties.

From https://seaborn.pydata.org/generated/seaborn.objects.Plot.scale.html

**Comment by SamKG** [comment]
Thanks! 
Can you help me understand what is going wrong in this example?
```
df = pd.DataFrame({
    "x":[1,2,3,4],
    "y":[1,2,3,4],
    "colors":["w", "r", "g", "b"]
})
```
plot = so.Plot(df, x="x", y="y").scale(color=list(df["colors"])).add(so.Bar()).plot()
display(plot)


![image](https://github.com/user-attachments/assets/99f41439-3fba-4af9-b215-fab02bf5d826)
