### ISSUE TITLE
sns.pairplot in same code, but show different result in different version.

### ISSUE THREAD

**Issue by nk7260ynpa** [mwaskom/seaborn#3768]
Hello I found a problem between 0.11.0 version and 0.13.2.

In the same code, there are different results.

```Python
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="white")
tips = sns.load_dataset("tips")

sns.pairplot(data=tips) 
```

0.11.0 version result
![0 11 0](https://github.com/user-attachments/assets/56c6a465-1ee4-4da5-aa6c-a124fe07dd9e)
0.13.2 version result
![0 13 2](https://github.com/user-attachments/assets/b0518657-811e-49c6-b0e2-1986fd295bca)

Could you fix the problem?

Thank you.

**Comment by mwaskom** [comment]
What is the problem>

**Comment by nk7260ynpa** [comment]
In the same data. 
"total_bill" and "tips" hist show different result in different version.
## 0.11.0 version
![0 11 0](https://github.com/user-attachments/assets/fe392ade-52e4-4d38-a02d-35138f161609)
## 0.13.2 version
![0 13 2](https://github.com/user-attachments/assets/1746cab6-8715-4573-9f6e-bbe2d66d6367)
