### ISSUE TITLE
No mouseover "x=,y=" for `sns.heatmap` (works only on its colorbar), as if its `ax.format_coords()` was not set

### ISSUE THREAD

**Issue by MestreLion** [mwaskom/seaborn#3771]
This is much better explained in this SO question: [Interactive sns.heatmap displays x, y only hovering over the colorbar](https://stackoverflow.com/questions/76458890/interactive-sns-heatmap-displays-x-y-only-hovering-over-the-colorbar)

The comments suggest this is easy to implement, but I was unable to do so.

It does work fine if you replace the seaborn `heatmap()` call with direct calls to Matplotlib's `pcolormesh()` + `colorbar()`, i.e, instead of:
```
sns.heatmap(data, ...)
```
Use this
```
heat = plt.pcolormesh(data)
plt.colorbar(heat)
```

So _something_ in Seaborn's usage or customization of Matplotlib's `pcolormesh` is "unsetting" its default `format_coords`, which I believe is a bug

**Comment by mwaskom** [comment]
I don't think this is expected to work, sorry!

**Comment by MestreLion** [comment]
Preliminary findings:
- This is related to Matplotlib's default behavior when `xticklabels`/`yticklabels` are set for `pcolormesh`: the underlying `format_xdata()` ends up calling the major tick value formatter, which returns `""` for values that are not in the tick labels dictionary.
- Seaborn, by design _always_ populates the tick labels with sensible values, so the mouseover info is always the empty `x= y=`
- `imshow` suffers the same problem as `pcolormesh`, _however_ it sets its artists in a way (`mouseover=True` perhaps?) that they are queried for additional info, hence the additional `[123..]` shown on mouseover. But unfortunately Seaborn does not use `imshow`

Some workarounds that Seaborn could adopt:
- Set `ax.fmt_xdata` / `ax.fmt_ydata`, which are `None` by default, to prevent `ax.format_xdata()` from falling back to the tick formatter
