### ISSUE TITLE
Feature request: Dumbell plots

### ISSUE THREAD

**Issue by mflova** [mwaskom/seaborn#3778]
![image](https://github.com/user-attachments/assets/d3cdb53e-83c9-41fd-80b5-954133abf81d)

These can be quite common in politics or sociology in order to represent not only the data itself but also the difference between two groups. Although this kind of plot can be built by using `matplotlib` and `seaborn` combined, having a dedicated method that simplifies this work could be helpful. If this feature is interesting for more people, I can contributing into this future (both interface and implementation itself). 

More examples: https://datavizcatalogue.com/blog/chart-snapshot-dumbbell-plot/

**Comment by mwaskom** [comment]
This is probably too specific for a dedicated seaborn function. It should be pretty easy to make with the objects interface, though, and relatively easy to make with a combination of `scatterplot` and `lineplot` in the classic interface.
