### ISSUE TITLE
Heatmap twinx problem when square is True 

### ISSUE THREAD

**Issue by the-pawel-wojcik** [mwaskom/seaborn#3779]
Hello!

Thank for building seaborn. It's plots are very pretty and quick to make.

I got myself into a problem when trying to add a second y axis to the heatmap. See this 
```python
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbs

rng = np.random.default_rng(seed=1)
data = rng.standard_normal(size=(25, 5))
fig, ax = plt.subplots()
sbs.heatmap(data, ax=ax)  # All good
# sbs.heatmap(data, ax=ax, square=True)  # Problem
tax = ax.twinx()
plt.show()
```
See attached figures. When I set the `square=True` option. The addition of the second ax breaks the display:
![square_twinx](https://github.com/user-attachments/assets/ed252fba-b790-4c86-96e6-22a92f01aaad)
![square_no_twinx](https://github.com/user-attachments/assets/7fe5560e-2201-498d-8084-11bd6c8021d4)

What I would like to get by adding the second ax is to keep the setup as you get when you only set `square=True` but with the chance to modify the ticks on the right. Something of the kind that you get when you use twinx but without using the `square=True` option:
![no_square_twinx](https://github.com/user-attachments/assets/5b7b914b-550c-4c17-b54c-b07de6bdd8a0)

Thanks
Pawel

**Comment by mwaskom** [comment]
I'm not quite sure I understand exactly what you're trying to do, but all `square=True` does is call `ax.set_aspect("equal")` on your axes. This is probably something you can make work using the matplotlib API directly before or after plotting with seaborn.
