### ISSUE TITLE
Allow setting other scales in log_scale

### ISSUE THREAD

**Issue by mbhall88** [mwaskom/seaborn#3780]
The addition of `log_scale` has been great. Especially for violins. I know you can get the base using a number, but would it possible to allow setting a different scale? For example, I use `symlog` and `logit` quite a bit in my work.

**Comment by mwaskom** [comment]
Probably won't add this to the various plotting functions, but the objects interface has more scale flexibility currently.

Note that seaborn will also use whatever scale is currently set if you provide it an existing axes, so you should be able to make that work for you.

**Comment by mbhall88** [comment]
> Note that seaborn will also use whatever scale is currently set if you provide it an existing axes, so you should be able to make that work for you.

Ah cool! Moving `ax.set_yscale("symlog")` *above* the call to seaborn's violinplot worked a charm. Thanks!

> the objects interface has more scale flexibility currently.

A reminder that I need to get up to date and learn to use this interface.
