### ISSUE TITLE
[Feature Request] style parameter in `displot`, `catplot` and `lmplot` similar to `relplot`

### ISSUE THREAD

**Issue by hguturu** [mwaskom/seaborn#3784]
Currently, `relplot` has `style` parameter that provides an additional way to "facet" the data beyond col, row and hue using `linestyle`. It would be nice if this was extended to the other figure plot types. This would also lead to a more consistent API across the different facet grid plots.

- `displot` - kdeplot and ecdfplot would change `linestyle`, histplot would change patch `hatching`.
- `catplot` - stripplot, swarmplot would change `linestyle`; boxplot, violinplot, boxenplot, barplot and countplot would change `hatching`, pointplot would change `linestyle` and `marker`
- `lmplot` - would change `marker` and `linestyle`

References for supporting in underlying matplotlib.
https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html
https://matplotlib.org/stable/gallery/lines_bars_and_markers/marker_reference.html
https://matplotlib.org/stable/gallery/shapes_and_collections/hatch_style_reference.html

**Comment by mwaskom** [comment]
Thanks for the suggestion. It's unlikely that this will be added any point soon, but the objects interface provides a much wider range of mappable properties.

**Comment by hguturu** [comment]
Can you clarify the object interface? That would involve manual modification of the the plot similar to using matplotlib objects directly?

**Comment by mwaskom** [comment]
https://seaborn.pydata.org/tutorial/objects_interface.html

**Comment by hguturu** [comment]
Oh interesting. I wasn't aware of this, this is similar to the plotly object interface. Thanks.
