### ISSUE TITLE
change kde line color in histplot function doesn't work

### ISSUE THREAD

**Issue by JiyangChang** [mwaskom/seaborn#3787]
Hi,

Thanks for the great tools.

I'm trying to change the KDE line color in sns.hisplot() function but it doesn't work.

```
data = [1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 5, 5, 6, 7]

sns.histplot(data, kde=True, line_kws={'color': 'red'})  

plt.show()
```
![download](https://github.com/user-attachments/assets/0e15f43b-4276-4dad-9602-00dfa4f8b13b)

**Comment by mwaskom** [comment]
Duplicate of https://github.com/mwaskom/seaborn/issues/3414
