### ISSUE TITLE
[FEATURE REQUEST] New Colour Palettes

### ISSUE THREAD

**Issue by OWissett** [mwaskom/seaborn#3788]
I have a few nice colour palettes, and want to get them included in seaborn.

'synthwave'

![image](https://github.com/user-attachments/assets/eb860131-662b-48fb-ade0-918cb7522f67)

**Comment by mwaskom** [comment]
Hi, it's not necessary to add new colormaps to seaborn to use them, you can simple pass the list of colors to any seaborn function.
