### ISSUE TITLE
Question about abstraction

### ISSUE THREAD

**Issue by refack** [mwaskom/seaborn#3794]
https://github.com/mwaskom/seaborn/blob/b4e5f8d261d6d5524a00b7dd35e00a40e4855872/seaborn/distributions.py#L1449

Is there an architectural reason you don't expose the stats data? (i.e. something like `ax.p = p`)
Most academic publications want to see the number behind the plots.

**Comment by mwaskom** [comment]
Pretty sure there is a faq on this, otherwise it’s been discussed elsewhere. Issues are for tracking bugs.
