### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by safaksekin** [mwaskom/seaborn#3796]
Hi, when im trying to run “import seaborn” command i get an error called “DLL load failed while importing _multiarray_umath”. I have tried to do as much as i can. Uninstalled seaborn, install seaborn etc. but still get this error. Pls could you help?

**Comment by mwaskom** [comment]
https://seaborn.pydata.org/faq.html#i-can-t-import-seaborn-even-though-it-s-definitely-installed
