### ISSUE TITLE
`density_norm` ignored when using `hue` in `sns.violinplot`

### ISSUE THREAD

**Issue by JuanTejedor** [mwaskom/seaborn#3799]
When using the `hue` parameter in `sns.violinplot`, the specified `density_norm` option appears to be ignored. Instead, it defaults to `density_norm="width"`, regardless of the value explicitly provided.

### Steps to Reproduce
To highlight this issue, the `iris` dataset was filtered to create noticeable differences in counts between species, making it easier to observe how `density_norm` should affect the plots. Specifically, 40 random observations were removed from the `setosa` species to break the natural balance between species counts in the dataset.

```python
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Load dataset and filter
p = sns.load_dataset("iris")
np.random.seed(123)
setosa_to_drop = p[p["species"] == "setosa"].sample(40).index
p.drop(index=setosa_to_drop, inplace=True)

# Create violin plots
fig, axes = plt.subplots(2, 3, figsize=(12, 8))
axes = axes.flatten()

# Plot 1: density_norm="count" without hue
sns.violinplot(data=p, x="species", y="sepal_width", density_norm="count", ax=axes[0])
axes[0].set_title('density_norm="count"')

# Plot 2: density_norm="area" without hue
sns.violinplot(data=p, x="species", y="sepal_width", density_norm="area", ax=axes[1])
axes[1].set_title('density_norm="area"')

# Plot 3: density_norm="width" without hue
sns.violinplot(data=p, x="species", y="sepal_width", density_norm="width", ax=axes[2])
axes[2].set_title('density_norm="width"')

# Plot 4: density_norm="count" with hue
sns.violinplot(data=p, x="species", y="sepal_width", density_norm="count", hue="species", ax=axes[3])
axes[3].set_title('density_norm="count" (hue)')

# Plot 5: density_norm="area" with hue
sns.violinplot(data=p, x="species", y="sepal_width", density_norm="area", hue="species", ax=axes[4])
axes[4].set_title('density_norm="area" (hue)')

# Plot 6: density_norm="width" with hue
sns.violinplot(data=p, x="species", y="sepal_width", density_norm="width", hue="species", ax=axes[5])
axes[5].set_title('density_norm="width" (hue)')

plt.tight_layout()
plt.show()
```
![output](https://github.com/user-attachments/assets/14c3277f-f2c0-4e89-87ef-c07fcdfc26d3)

### Observed Behavior
- Without `hue`, the `density_norm` parameter behaves as expected (Plots 1–3).
- When `hue` is applied (Plots 4–6), the normalization defaults to `density_norm="width"`, ignoring the specified `density_norm` value.

### Environment
- **Seaborn version:** `0.13.2`
- **Python version:** `3.13.0`
- **Matplotlib version:** `3.9.2`

**Comment by mwaskom** [comment]
Did you try

> common_norm: bool
>     When True, normalize the density across all violins.

**Comment by JuanTejedor** [comment]
That resolves the issue! Thank you for the quick reply, and apologies for overlooking that 😅. I wasn’t aware that this argument served that purpose.
