### ISSUE TITLE
residplot doesn't allow to change color of lowess line.

### ISSUE THREAD

**Issue by cbonnett** [mwaskom/seaborn#388]
residplot doesn't allow to change color of lowess line.
When there are many points, you cannot see the line as it has the same color.  

![screen shot 2014-12-02 at 9 28 37 am](https://cloud.githubusercontent.com/assets/4085850/5259757/b0b07500-7a05-11e4-8a3a-bc413fbd80d2.png)

**Comment by hannavw** [comment]
line_kws={'color': 'red', 'lw': 2, 'alpha': 0.7} works!
