### ISSUE TITLE
Support stacked bars in hue FacetGrid histograms

### ISSUE THREAD

**Issue by andrebalg** [mwaskom/seaborn#391]
At the moment, it seems that FacetGrid does not support histtype='barstacked' when using FacetGrids based on hue. For example:

``` python
df = sns.load_dataset("iris")
g = sns.FacetGrid(df, hue="species", size=4, aspect=1.3)
g.map(plt.hist, "sepal_length", histtype='barstacked', stacked=True);
plt.legend();
```

yields:
![screen shot 2014-12-08 at 15 53 34](https://cloud.githubusercontent.com/assets/4387479/5341997/75082a74-7ef2-11e4-9fee-ca8472ad5d22.png)
 When the user specifies:

``` python
histtype='barstacked'
```

It should rather yield something like:
![screen shot 2014-12-08 at 15 57 58](https://cloud.githubusercontent.com/assets/4387479/5342076/01828b34-7ef3-11e4-8adc-b43dfb8af4c1.png)

I know this specific case is handled by default for hue plt.hist in PairGrid, but I would be happy to implement it in FacetGrid as well.
I think it would be nice to have for complex FacetGrids involving both hue and col/row.

Is this something you are interested in merging?

**Comment by rasbt** [comment]
Sorry for the follow-up on this rather old issue, but how do you create the stacked histograms in the pairplot (scatterplot matrix) then? E.g., 

![screen shot 2016-06-10 at 9 40 58 pm](https://cloud.githubusercontent.com/assets/5618407/15982395/2f1b70de-2f54-11e6-9037-28e52c8de6e6.png)

**Comment by Oufattole** [comment]
Something like this should do the trick:

```
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

n_values = 1000
df_melted = pd.DataFrame.from_dict({
    'column': ['a']*n_values + ['b']*n_values,
    'hue': [0]*(n_values//2) + [1]*(n_values//2) + [0]*(n_values//2) + [1]*(n_values//2),
    'value': np.random.uniform(size=n_values*2),
})
g = sns.FacetGrid(df_melted, col='column', col_wrap=4, sharex=False, sharey=False, aspect=2)
def stackhist(x, y, **kws):
    df = pd.DataFrame.from_dict({'x': x, 'y': y})
    data = []
    for each in np.unique(y):
        data.append(df[df['y'] == each]['x'])
    plt.hist(data, histtype="bar", bins=20, stacked=True)
g.map(stackhist, 'value', 'hue')
```

In this example I just did it with a 2 column grid and got this output:

![950e21b0-193a-4515-9524-28e953bbb978](https://user-images.githubusercontent.com/29084395/210950188-d251571e-7ade-4b11-b341-7db8a53cecb0.png)
