### ISSUE TITLE
kdeplot "shade" background does not match normal background 

### ISSUE THREAD

**Issue by cbienpourtoi** [mwaskom/seaborn#393]
If kdeplot is used with "shade = True", and inside a larger plot, the backgrounds do not match.

Example with a kdeplot inside a simple pyplot:

    import seaborn as sns
    import numpy as np
    import matplotlib.pyplot as plt

    plt.plot([-3, 3],[0,60])

    points = np.random.multivariate_normal([0, 0], [[1, 2], [2, 20]], size=1000)
    sns.kdeplot(points, shade=True)

    plt.show()

![test_kde](https://cloud.githubusercontent.com/assets/6683983/5357651/5190b954-7f91-11e4-9cad-3fcd560f8ce8.png)

On the image, we have 2 backgrounds: the upper one is the normal background, and the lower background is the color for the lowest densities of the kdeplot.

I can see 2 eventual solutions (?):
- make the first shade (for lowest densities) of kdeplot transparent.
- have a way to extend the kdeplot to the whole surface of the plot (I tried with clip, thinking it might work to enlarge the area, but it does not work that way).

Good luck and thank you for developping this very cool package!

**Comment by cbienpourtoi** [comment]
Thanks for the update on the subject!

**Comment by mwaskom** [comment]
Just an update that it's actually pretty easy to workaround this externally to seaborn:

```python
ax = sns.kdeplot(x, y, shade=True)
ax.set(xlim=(None, 6), aspect="equal")
ax.collections[0].set_alpha(0)
```
![screenshot 2015-01-10 18 55 58](https://cloud.githubusercontent.com/assets/315810/5694164/64ff37b8-98fa-11e4-8224-9469f7b20e52.png)

**Comment by cbienpourtoi** [comment]
Wow, great! Thank you very much. I hope I wasn't too much trouble!

**Comment by Phlya** [comment]
Just a tip for those having two (or more?) kdeplots together. This worked for me:

    ax = sns.kdeplot(df1, cmap='Reds', cut=0, shade=True, alpha=0.5)
    ax.collections[0].set_alpha(0)
    sns.kdeplot(df2, cmap='Blues', cut=0, shade=True, ax=ax, alpha=0.5)
    ax.collections[10].set_alpha(0)

**Comment by mwaskom** [comment]
Good call, I've added an example on this to the new API docs for `kdeplot`.

**Comment by mwaskom** [comment]
Actually there is a bit of weird indeterminacy in the number of levels that actually get drawn, so that approach is not robust. I think this may be a matplotlib bug; see here: https://github.com/matplotlib/matplotlib/issues/4537

**Comment by Phlya** [comment]
I guess something like this should be robust to this problem, but haven't tested it:

    ax = sns.kdeplot(df1, cmap='Reds', cut=0, shade=True, alpha=0.5)
    ax.collections[0].set_alpha(0)
    i = len(ax.collections)
    sns.kdeplot(df2, cmap='Blues', cut=0, shade=True, ax=ax, alpha=0.5)
    ax.collections[i].set_alpha(0)

**Comment by mwaskom** [comment]
Yup, a bit more annoying but that will do the trick.

**Comment by mwaskom** [comment]
I decided to add a `shade_lowest` keyword argument to `kdeplot`, which handles this logic inside the function where it is easier to find the right collection to make invisible.

It's currently wrapped up in #566, but it will hit master when that merges so I'm going to close this issue.

**Comment by Phlya** [comment]
Great, I was gonna ask if it might be indeed easier this way. Thanks!
19 Июн 2015 г. 17:28 пользователь "Michael Waskom" <notifications@github.com>
написал:

**Comment by mwaskom** [comment]
It's not completely ideal in that I couldn't find a great way to enable automatic legend support, so it will be up to the user to either annotate the plot with text or add proxy artists and a legend themselves. But it makes the core plotting possible and easy.

**Comment by Phlya** [comment]
I see... Well, then it may be a good idea to make an example with how to set up a legend there.

**Comment by mwaskom** [comment]
If I were personally making such a plot I would add colored text labels with the names of the categories near the relevant densities; this kind of thing looks best but it can be hard to do programmatically.
