### ISSUE TITLE
sns.lmplot doesn't handle ax keyword correctly

### ISSUE THREAD

**Issue by thoppe** [mwaskom/seaborn#406]
```python
import pandas as pd

import pylab as plt
import seaborn as sns
print sns.__version__   # 0.5.1

df = pd.DataFrame({"A":[1,2,3],
                   "B":[4,5,7]})
fig, ax = plt.subplots(1,1)
sns.lmplot("A","B",df,ax=ax)
#sns.regplot("A","B",df,ax=ax) # regplot works as intended
plt.show()
```

The output with version `0.5.1` looks like:

![screenshot from 2014-12-21 15 12 12](https://cloud.githubusercontent.com/assets/2707106/5519482/3e765fd0-8924-11e4-8f30-4a8b28aebf61.png)

**Comment by EmanuelGoncalves** [comment]
This feature is would very useful. 

I wanted to use the `hue` function from `lmplot` to build a grid of plots and I couldn't. Also `regplot` doesn't support the hue argument.

And to be fair, `lmplot` does take the `ax` arg from the `regplot` arguments.

**Comment by mwaskom** [comment]
Closed with #566

**Comment by ferreiraleo** [comment]
How can I plot any seaborn scatter plot that supports subplots and hue????

**Comment by gibsondanield** [comment]
From the documentation

>  it draws directly onto an axes (either the currently active axes or the one provided by the ax parameter)
