### ISSUE TITLE
PairGrid and missing values? 

### ISSUE THREAD

**Issue by jseabold** [mwaskom/seaborn#407]
Should the dropna argument work for this and do pairwise dropping?

``` python
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

dta = pd.util.testing.makeMissingDataframe()
g = sns.PairGrid(dta)
g.map_diag(plt.hist)
```

**Comment by DizietAsahi** [comment]
this still does not work. Am I missing how dropna works?

> from matplotlib import pyplot as plt
> import numpy as np
> import pandas as pd
> import seaborn as sns
> sns.__version__
'0.7.dev'
# generate an example DataFrame
> a = pd.DataFrame(data={
    'a': np.random.normal(size=(100,)),
    'b': np.random.lognormal(size=(100,)),
    'c': np.random.exponential(size=(100,))})
> sns.pairplot(a) # this works as expected
(...)
> b = a.copy()
> b.iloc[5,2] = np.nan # replace one value in col 'c' by a NaN
> sns.pairplot(b) # this fails with error 
                  # "AttributeError: max must be larger than min in range parameter."
                  # in histogram(a, bins, range, normed, weights, density)"
> sns.pairplot(b, dropna=True) # same error as above

**Comment by wehlutyk** [comment]
Any news on this or where it's going? 0.7.0 still has the same behaviour.

**Comment by Alsanis** [comment]
Is any progress on the problem?

**Comment by cbrnr** [comment]
In fact, the `dropna` argument seems to be misleading (or at least I haven't really figured out what it is supposed to do). IMO the expected behavior should be equivalent to the following line in the example by @DizietAsahi above:

```Python
sns.pairplot(b.dropna())
```

**Comment by DizietAsahi** [comment]
The problem with using
`sns.pairplot(b.dropna())`
is that b.dropna() drops the whole line, even though there are some pairs of values that _could_ be plotted. NaNs should only be dropped at the level of each pair of values IMHO.

**Comment by cbrnr** [comment]
I agree. Or it might even be useful to specify the dropping strategy with the argument `dropna` (such as implemented in R, e.g. complete cases, pairwise, ...). In any case, the current implementation of `dropna` simply does not work at all with the default settings of having histograms on the diagonal (it does work with kdes though).
