### ISSUE TITLE
seaborn install error (RuntimeError: Cannot get window extent w/o renderer)

### ISSUE THREAD

**Issue by deeplearnx** [mwaskom/seaborn#408]
I've be struggling to get seaborn running all night. I've installed it using (ana)conda. When running this example (http://stanford.edu/~mwaskom/software/seaborn/examples/network_correlations.html) I get the following. I haven't been able to find any solutions. I've tried reinstalling Anaconda as well as installing matplotlib and seaborn separately to no avail...

Traceback (most recent call last):
  File "heatmap.py", line 9, in <module>
    sns.heatmap(corrmat, vmax=.8, linewidths=0, square=True)
  File "/Users/ssingh/anaconda/lib/python2.7/site-packages/seaborn/matrix.py", line 292, in heatmap
    plotter.plot(ax, cbar_ax, kwargs)
  File "/Users/ssingh/anaconda/lib/python2.7/site-packages/seaborn/matrix.py", line 177, in plot
    if axis_ticklabels_overlap(xtl):
  File "/Users/ssingh/anaconda/lib/python2.7/site-packages/seaborn/utils.py", line 374, in axis_ticklabels_overlap
    bboxes = [l.get_window_extent() for l in labels]
  File "/Users/ssingh/anaconda/lib/python2.7/site-packages/matplotlib/text.py", line 739, in get_window_extent
    raise RuntimeError('Cannot get window extent w/o renderer')
RuntimeError: Cannot get window extent w/o renderer

**Comment by cel4** [comment]
Sorry to jump in here. There seems to be a problem with the `MacOSX` backend. I have seen it on SO http://stackoverflow.com/questions/27868865/runtimeerror-cannot-get-window-extent-w-o-renderer-with-seaborn?noredirect=1#comment44142319_27868865 and can reproduce it.
Switching the backend is a workaround. I don't understand this issue, but I think it needs fixing. Maybe we should cross-link it to `matplotlib`?

**Comment by mwaskom** [comment]
I guess it could catch the error and just set the ticklabels outward so they are guaranteed not to overlap, but that seems kinda lame.

**Comment by cel4** [comment]
Still weird, that it works with other packages, but not with `MacOSX`. Seems suspicious.

**Comment by mwaskom** [comment]
Seems similar (though not exactly the same error) as #231. I guess I just have a lower bar for surprise at matplotlib backend jankiness than you :)

**Comment by cel4** [comment]
This could be related as well, not quite sure: https://github.com/matplotlib/matplotlib/issues/2654

**Comment by mwaskom** [comment]
Yeah, that's the underlying issue in #231

**Comment by scls19fr** [comment]
I'm also facing a similar issue with Anaconda Python under Mac OS X.

With IPython

    In [1]: import pandas as pd

    In [2]: df=pd.DataFrame([[1,2,0],[3,1,0]])

    In [3]: df
    Out[3]:
       0  1  2
    0  1  2  0
    1  3  1  0

    In [4]: import seaborn as sns

    In [5]: sns.heatmap(df)
    ---------------------------------------------------------------------------
    RuntimeError                              Traceback (most recent call last)
    <ipython-input-5-4d96bd9052a7> in <module>()
    ----> 1 sns.heatmap(df)

    //anaconda/lib/python2.7/site-packages/seaborn/matrix.pyc in heatmap(data, vmin, vmax, cmap, center, robust, annot, fmt, annot_kws, linewidths, linecolor, cbar, cbar_kws, cbar_ax, square, ax, xticklabels, yticklabels, mask, **kwargs)
        290     if square:
        291         ax.set_aspect("equal")
    --> 292     plotter.plot(ax, cbar_ax, kwargs)
        293     return ax
        294

    //anaconda/lib/python2.7/site-packages/seaborn/matrix.pyc in plot(self, ax, cax, kws)
        175         # Possibly rotate them if they overlap
        176         plt.draw()
    --> 177         if axis_ticklabels_overlap(xtl):
        178             plt.setp(xtl, rotation="vertical")
        179         if axis_ticklabels_overlap(ytl):

    //anaconda/lib/python2.7/site-packages/seaborn/utils.pyc in axis_ticklabels_overlap(labels)
        372
        373     """
    --> 374     bboxes = [l.get_window_extent() for l in labels]
        375     overlaps = [b.count_overlaps(bboxes) for b in bboxes]
        376     return max(overlaps) > 1

    //anaconda/lib/python2.7/site-packages/matplotlib/text.pyc in get_window_extent(self, renderer, dpi)
        794             self._renderer = renderer
        795         if self._renderer is None:
    --> 796             raise RuntimeError('Cannot get window extent w/o renderer')
        797
        798         bbox, info, descent = self._get_layout(self._renderer)

    RuntimeError: Cannot get window extent w/o renderer

    In [6]: sns.plt.show()

despite error message I can see heatmap with IPython interactive console but a similar script

    import pandas as pd
    import seaborn as sns
    df = pd.DataFrame([[1,2,0],[3,1,0]])
    sns.heatmap(df)
    sns.plt.show()

raises error and heatmap is never displayed.

pc:~ scls$ python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    sns.heatmap(df)
  File "//anaconda/lib/python2.7/site-packages/seaborn/matrix.py", line 292, in heatmap
    plotter.plot(ax, cbar_ax, kwargs)
  File "//anaconda/lib/python2.7/site-packages/seaborn/matrix.py", line 177, in plot
    if axis_ticklabels_overlap(xtl):
  File "//anaconda/lib/python2.7/site-packages/seaborn/utils.py", line 374, in axis_ticklabels_overlap
    bboxes = [l.get_window_extent() for l in labels]
  File "//anaconda/lib/python2.7/site-packages/matplotlib/text.py", line 796, in get_window_extent
    raise RuntimeError('Cannot get window extent w/o renderer')
RuntimeError: Cannot get window extent w/o renderer

**Comment by erinshellman** [comment]
Which plotting backend do you recommend?  When I try to create a clustermap using iPython with no specified backend I get this error:
```
RuntimeError: Cannot get window extent w/o renderer
```
When I run identical code using the matplotlib backend I instead get this error:
```
RuntimeError: CGContextRef is NULL
```

**Comment by mwaskom** [comment]
I do 99.99% of my plotting in the notebook with the inline backend, so I don't have great firsthand experience which the various gui options. However, my understanding is that the error you're seeing there is specifically an issue with the MacOSX backend.

**Comment by mtaptich** [comment]
FYI, There is a fix for this issue <a href='http://stackoverflow.com/questions/30138026/seaborn-matplotlib-cannot-get-window-extent-w-o-renderer-runtimeerror'>here.

**Comment by SriramNY** [comment]
One simple way to install Seaborn is, download the package from the github on your local machine. from the terminal/command prompt go to that particular directory and type python setup.py install

before you do that make sure you have the setup file in that directory. this worked for me :-)
