### ISSUE TITLE
Showing the regression equation on linear plots?

### ISSUE THREAD

**Issue by queryous** [mwaskom/seaborn#411]
Is this possible to add?  I don't have access to the regression function through regplot or lmplot (unless I rummage around in the original libraries).

**Comment by hyamanieu** [comment]
Could think of reopening this suggestion, it was asked several times (e.g. https://stackoverflow.com/questions/33490833/display-regression-equation-in-seaborn-regplot).
As the regression is done once for the linear plot, I think it should be easy to at least return the coefficients. Perhaps add a boolean input variable called `return_coeff`. The user could later display them through `plt.text()`.
Thank you!

**Comment by mwaskom** [comment]
No. This will never be added to seaborn.

**Comment by mwaskom** [comment]
No. This has been definitively answered: https://stackoverflow.com/a/22852265

**Comment by hyamanieu** [comment]
Great, it's good to suggest the `statsmodel ` library. Thanks again for your great work (and rapid response!).

**Comment by fralligator** [comment]
seaborn seam to be made for the general public not people who know math :/ or can code for that matter use scipy
