### ISSUE TITLE
Seaborn installation as a dependency

### ISSUE THREAD

**Issue by tritemio** [mwaskom/seaborn#412]
Hi,

I recently added seaborn as a dependency in my software but now the installation on TravisCI fails with an error during seaborn installation:

```
Searching for seaborn
Reading https://pypi.python.org/simple/seaborn/
Best match: seaborn 0.5.1
Downloading https://pypi.python.org/packages/source/s/seaborn/seaborn-0.5.1.tar.gz#md5=2ce6ea7d3c67858c0b1f5793fa2043b8
Processing seaborn-0.5.1.tar.gz
Writing /tmp/easy_install-BwklO4/seaborn-0.5.1/setup.cfg
Running seaborn-0.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BwklO4/seaborn-0.5.1/egg-dist-tmp-flZJiz
error: SandboxViolation: mkdir(u'/home/travis/.config', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.
This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand. Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

You can find the full message [here](https://travis-ci.org/tritemio/FRETBursts/builds/45744877).

**Comment by tritemio** [comment]
As an additional info, adding `pip install seaborn` as pre-installation command fixes the error. So the error occurs only when seaborn is installed automatically by pip as a dependency.

**Comment by mwaskom** [comment]
I think this was fixed by #397

**Comment by mwaskom** [comment]
But I thought that problem was only seen with easy_install.

**Comment by tritemio** [comment]
Thanks for the fix!

Apparently pip executes the following command when installing the requirements (from previous log):

    Running seaborn-0.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BwklO4/seaborn-0.5.1/egg-dist-tmp-flZJiz
