### ISSUE TITLE
Seaborn interferes with nbagg backend in ipython notebooks

### ISSUE THREAD

**Issue by golobor** [mwaskom/seaborn#413]
Hi,

recently ipython notebooks enabled the interactive backend "nbagg", which allows users to shift and zoom figures right in the browser. It seems that seaborn interferes with this backend and forces nbagg to exit the interactive mode and show only a static figure in the notebook.

I am using python 2.7.6, ipython 2.2.0, matplotlib 1.4.2, seaborn 0.5.1.
Anton.

**Comment by mwaskom** [comment]
I'm unable to reproduce this locally, I'll need some more information about what specifically you are trying to do.

**Comment by golobor** [comment]
I apologize for a false alert, the issue was caused by notebooks settings that I used in parallel with seaborn. Thank you for your time!

**Comment by mwaskom** [comment]
no problem, glad to hear it works

**Comment by freddygv** [comment]
@golobor what were the settings that interfered? I'm having the same issue.
