### ISSUE TITLE
coefplot() Raises "The `coefplot` function requires statsmodels" when the package is installed and imports

### ISSUE THREAD

**Issue by wmgilmor** [mwaskom/seaborn#418]

**Comment by mwaskom** [comment]
I think that's related to this: https://github.com/statsmodels/statsmodels/issues/2184

Basically, seaborn tries to import statsmodels and looks for an `ImportError` to determine whether statsmodels is present. But with scipy 0.15 and stastmodels 0.6.1, an `ImportError` gets raised even though it's installed.
