### ISSUE TITLE
PairGrid combining {x,y}_vars and map_{diag,offdiag}

### ISSUE THREAD

**Issue by mathieu1** [mwaskom/seaborn#420]
I would like to be able to plot only certain rows (or columns) of a `PairGrid` plot. This works fine as long as I map the same plotting function to all axes, using the `{x,y}_vars` parameters to choose the rows/columns. However, the current implementation does not allow to use a different plotting function on and off the diagonal (which admittedly is not quite a diagonal anymore).

Is that a feature worthy of implementing? (it would be a matter of tweaking `diag_axes` to return the axes which have the same variable labels coming from the row and column)

In code : 

* The following works:

iris = sns.load_dataset("iris")
g = sns.PairGrid(iris, hue="species",y_vars=['sepal_width','sepal_length'],x_vars = ['sepal_width','sepal_length','petal_width','petal_length'])
g.map(plt.scatter)
    
* So does this:

g = sns.PairGrid(iris, hue="species",y_vars=['sepal_width','sepal_length'],x_vars =['sepal_width','sepal_length'])
g.map_diag(sns.kdeplot)
g.map_offdiag(plt.scatter)

* But this doesn't

g = sns.PairGrid(iris, hue="species",y_vars=['sepal_width','sepal_length'],x_vars = ['sepal_width','sepal_length','petal_width','petal_length'])
g.map_diag(sns.kdeplot)
g.map_offdiag(plt.scatter)

* By the way, this doesn't work either (notice the switched `x` and `y_vars`)

g = sns.PairGrid(iris, hue="species",y_vars=['sepal_length','sepal_width'],x_vars = ['sepal_width','sepal_length'])
g.map_diag(sns.kdeplot)
g.map_offdiag(plt.scatter)

**Comment by mwaskom** [comment]
I think this might end up being harder than you think because the methods are currently written expecting the particular geometry of a square grid. This would be feasible, but I'm not sure exactly how much work it would be.
