### ISSUE TITLE
distplot kde/hist not normalized to one

### ISSUE THREAD

**Issue by erasmusthereformer** [mwaskom/seaborn#421]
I am having some trouble visualizing a distribution as a frequency of the total. In [this gist](https://gist.github.com/erasmusthereformer/875c52939f4555086594), I import some data and then use distplot to generate a figure. However, the y-axis goes above one; if it's frequency, shouldn't it always be less than one? 

![test](https://cloud.githubusercontent.com/assets/9327641/5795288/b5df9b6c-9f5a-11e4-8f37-edc4a3572582.png)

**Comment by erasmusthereformer** [comment]
P.S. a publication may or may not be hinging on this... so no sweat? =)

**Comment by mathieu1** [comment]
The curve and the box height indicate *density*, and can be more than 1. The (relative) frequency here is the area of each blue bar, which is indeed less than 1. The total area of the bars equals 1, and so does the area under the blue curve. Does that help?

**Comment by erasmusthereformer** [comment]
I see, thanks for clarifying! I should have read the numpy.histogram documentation first. So y-axis is density.
