### ISSUE TITLE
Add tutorial and gallery examples for boxplot/violinplot/stripplot

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#423]
These are being left out of #410 because I want to get it merged, but this needs to be finished before 0.6

**Comment by phobson** [comment]
What do you have in mind for this? I think the existing docs (e.g., http://stanford.edu/~mwaskom/software/seaborn-dev/generated/seaborn.stripplot.html) are great.

My only suggestion would be to explicitly specify the `x`, `y`, and `hue` arguments.

**Comment by TomAugspurger** [comment]
Agreed with @phobson for naming the arguments. I accidentally plotted a continuous variable on the x-axis for a boxplot after I checked out that branch. I was thinking, man the performance on this is really bad! And then I had a few hundred boxes trying to draw...

**Comment by mwaskom** [comment]
Closed with #423
