### ISSUE TITLE
Strange behavior with Arial font

### ISSUE THREAD

**Issue by arnaldorusso** [mwaskom/seaborn#426]
I have to use Arial font to perform a fancy plot, using TeX to render a table and using greek letters in Arial type as well.

Both configuration using *plt.rcParams.update* or *sns.axes_style* I can't get what I want.
The example code is [here](https://gist.github.com/bd954144ad6150c9a64c.git). Even if I comment lines [21:34] trying to force seaborn use the preset Arial, the font used on axis label and tick label are not Arial.
![help_arial](https://cloud.githubusercontent.com/assets/1857142/5820716/1298c3f2-a0ae-11e4-93f2-429ea0882d58.png)

The number `1` in Arial type does not have a underscore. It should be like [this](https://www1.ethz.ch/hk/docs/corporate_design/buero/arial_font.png?hires): 

Am I doing something wrong?
How can I obtain an full plot with Arial font?

Thanks.

**Comment by mwaskom** [comment]
I'm not completely sure, but skimming your code, you have `mathtext.fontset: 'stixsans'` in your rc params, and you're rendering the exponent using tex, so it's gonna be in stix sans instead of Ariel.

**Comment by arnaldorusso** [comment]
Hi @mwaskom . Thanks for your reply.

As I have already said, even if I comment the lines [21 : 34]

    rc('font',**{'family':'sans-serif','sans-serif':['Arial']})
    
    plt.rcParams.update({
                    'font.family' : 'sans-serif',
                    'font.sans-serif' : 'Arial',
                    'font.style' : 'normal',
                    'xtick.labelsize' : 9,
                    'ytick.labelsize' : 9,
                    'axes.labelsize' : 9,
                    'mathtext.fontset' : 'stixsans',
                    'mathtext.default': 'regular',
                    'text.usetex' : True,
                    'text.latex.unicode' : True
                    })

My plot does not render Arial font as well.

**Comment by mwaskom** [comment]
Right, but the mathtext font is set independently of the main font. So when you don't set it, it will be whatever the default is (probably computer modern?) And I see now you have the `rc('text', usetex=True)` line, which will render *all* of the text with latex, not just that fenced by '$'s. So the behavior you're seeing makes sense.

You'll need to figure out how to get latex to use arial, which I think is nontrivial (and outside of anything seaborn does). Take a look [here](http://matplotlib.org/users/customizing.html) (ctrl-f for "latex customizations"), which should get you started.

Sorry I can't be of more help.

**Comment by arnaldorusso** [comment]
Ok...
But something strange happens here!
Even if I comment this line too (let all matplotlib stuff commented (e.g. lines [20 : 34])), I get the same result on fonts... but without rendering my table.
What is wrong here @mwaskom ?
![help_arial](https://cloud.githubusercontent.com/assets/1857142/5822069/fa4cc4ec-a0b7-11e4-921c-8c0ef281c2f0.png)

Tks.

**Comment by mwaskom** [comment]
Dunno. Sorry. I'd asked on StackOverflow where you might get more people who know about the intricacies of matplotlib font sutff.

**Comment by arnaldorusso** [comment]
I asked here, beacause I found [This](http://stackoverflow.com/questions/23207516/matplotlib-not-listening-to-font-choices/23229638#23229638).
Generally normal plots can use Arial by default inside Seaborn?
I have a lot of other plots (whitout TeX rendering) that I can't figure out how to use Arial fonts.
Fonts inside matplotlib are painful!! =/

    import matplotlib.pyplot as plt
    import seaborn as sns
    sns.set_context(rc={'lines.markeredgewidth': 0.1}) # deal with mpl markers

    sns.set_style("whitegrid")
    sea_color = sns.dark_palette("skyblue", 8, reverse=True)
    sns.axes_style({'font.family': ['sans-serif'],
        'font.sans-serif': ['Arial']
        })

    plt.plot([1,2,3,4,5,], '*')
    plt.ylabel(r'1, 2, 3, 8, 9 6 11 Testing Label')
    plt.show()

This simple plot using only seaborn does not render Arial settings (inside Seaborn).


![help_arial_seaborn_only](https://cloud.githubusercontent.com/assets/1857142/5822529/0dd4ebf8-a0bc-11e4-9295-916ee5d764cc.png)

**Comment by mwaskom** [comment]
Works fine on my system:

```python
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")
plt.plot([1,2,3,4,5,], '*')
t = plt.ylabel(r'1, 2, 3, 8, 9 6 11 Testing Label')
print(t.get_fontname())
```
this prints
```python
Arial
```

Perhaps your Arial is not installed properly.

**Comment by arnaldorusso** [comment]
Yes.
Something is wrong here!
my output print is `Liberation Sans`
I have ttf instaled on Linux by the package `ttf-mscorefonts-installer`
and my Arial fonts are here:

    /usr/share/fonts/truetype/msttcorefonts/Arial_Bold_Italic.ttf
    /usr/share/fonts/truetype/msttcorefonts/arialbi.ttf
    /usr/share/fonts/truetype/msttcorefonts/Arial_Bold.ttf
    /usr/share/fonts/truetype/msttcorefonts/arial.ttf
    /usr/share/fonts/truetype/msttcorefonts/ariali.ttf
    /usr/share/fonts/truetype/msttcorefonts/arialbd.ttf
    /usr/share/fonts/truetype/msttcorefonts/Arial.ttf
    /usr/share/fonts/truetype/msttcorefonts/Arial_Italic.ttf
    /usr/share/fonts/truetype/msttcorefonts/Arial_Black.ttf
    /usr/share/xbmc/media/Fonts/arial.ttf
    /usr/local/share/texmf/fonts/tfm/urw/arial
    /usr/local/share/texmf/fonts/afm/urw/arial
    /usr/local/share/texmf/fonts/vf/urw/arial
    /usr/local/share/texmf/fonts/type1/urw/arial

Where I have to change this configuration inside Seaborn to reflect correct font?
Thanks

**Comment by mwaskom** [comment]
There's no configuration "inside seaborn", seaborn just tells matplotlib to be configured a certain way. By default seaborn tells matplotlib to use Arial, so perhaps matplotlib cannot find Arial, but it's not a seaborn issue.

**Comment by arnaldorusso** [comment]
thanks!
