### ISSUE TITLE
Write italic words on axis label

### ISSUE THREAD

**Issue by arnaldorusso** [mwaskom/seaborn#428]
Hi,

Is there a properly way to acquire italic words on `ax.set_ylabel`?
In my case I have something like:
`ylabel(r'Chlorphyll $a$ (mg m$^{-3}$)')`

The `a` of Chlorophyll must be in italic, but the superscript not!
Fonts are setted to Arial (as default by seaborn). How it should be done?
Thanks.

    import matplotlib.pyplot as plt
    import seaborn as sns    

    plt.plot([1,2,3])
    plt.xlabel('Days')
    plt.ylabel('Chlorophyll a (mg m$^{-3}$)')
    plt.show()

**Comment by mwaskom** [comment]
The choice of fonts and other aspects of how mathematical text is displaying in matplotlib is handled completely independently from any of the settings that seaborn touches. I don't know exactly off the top of my head, but I think you'll want to use `\mathsf` to render latex in sans-serif font. There's much more information [here](http://matplotlib.org/users/mathtext.html).
