### ISSUE TITLE
boxplot doctest fails

### ISSUE THREAD

**Issue by timmie** [mwaskom/seaborn#429]
```
seaborn.tests.test_utils.test_ticklabels_overlap ... ok

======================================================================
FAIL: Doctest: seaborn.distributions.boxplot
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for seaborn.distributions.boxplot
  File "/build/buildd/seaborn-0.6.0~ppa3~revno/.pybuild/pythonX.Y_2.7/build/seaborn/distributions.py", line 1275, in boxplot

----------------------------------------------------------------------
File "/build/buildd/seaborn-0.6.0~ppa3~revno/.pybuild/pythonX.Y_2.7/build/seaborn/distributions.py", line 1360, in seaborn.distributions.boxplot
Failed example:
    tips = sns.load_dataset("tips")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
```
https://launchpadlibrarian.net/195539509/buildlog_ubuntu-utopic-i386.seaborn_0.6.0~ppa3~revno-444~ubuntu14.10.1_FAILEDTOBUILD.txt.gz

**Comment by mwaskom** [comment]
Can you give me a little more information about what this is? I don't see this failures on Travis or the Debian buildbot...

**Comment by timmie** [comment]
It's from the daily builds for Ubuntu.

As you can see, they fail since 3 days:
https://code.launchpad.net/~pythonxy/+recipe/pythonxy-seaborn-daily

**Comment by mwaskom** [comment]
I don't really have time to dig through a gigantic wall of text at the moment but on a very quick glance it looks like it's failing because the doctest code can't download the sample data. Can your build machine see the internet?

**Comment by timmie** [comment]
yes.

**Comment by mwaskom** [comment]
Then I'm not sure! Let me know if you figure it out.

**Comment by timmie** [comment]
mmh. must be something with the statsmodels.
Let's see what happens after they'd have fixed their code.
