### ISSUE TITLE
heatmap annotation font size

### ISSUE THREAD

**Issue by radaniba** [mwaskom/seaborn#430]
I am creating a heatmap with sns.heatmap() but couldn't find a way to set the size of the labels inside the boxes when we set `annot=True`, is it possible to make the font smaller ?

Thanks

**Comment by mwaskom** [comment]
Use the `annot_kws` parameter, e.g.

```python
sns.heatmap(x, annot=True, annot_kws={"size": 20})
```

**Comment by radaniba** [comment]
of course !

Thanks

**Comment by stevencollinscn** [comment]
Is there any simple way to make the those columns' name on both axes bigger and rotate those on the x-axis?

**Comment by saurabhbidwai** [comment]
sns.set(font_scale=1.8) woked thanks

**Comment by siddhant-doshi** [comment]
Can we have different colours for the xticklabels?

**Comment by StevenLi-DS** [comment]
@siddhant-doshi 
```
import numpy as np; np.random.seed(0)
import seaborn as sns; sns.set_theme()
uniform_data = np.random.rand(10, 12)
ax = sns.heatmap(uniform_data)

ax.tick_params(axis='x', colors='red')
```

**Comment by shayan911** [comment]
Is there a way to increase a certain ticklabel inorder to make it prominent?

**Comment by StevenLi-DS** [comment]
@shayan911 each of the ticklabel is also an object and you can use `.set_fontsize()` method for it. Make sure you have `set_ticklabels()` first.
```python
import matplotlib.pyplot as plt
x = [1, 2, 3]
y = [2, 4.5, 4]

fig, ax = plt.subplots()
ax.plot(x, y)

ax.set_xticks(x)
ax.set_xticklabels(x)

for label in ax.xaxis.get_ticklabels():
    if label.get_text() == '2':
        label.set_fontsize(20)
```
![image](https://user-images.githubusercontent.com/33796896/194730715-ba387fe2-fb09-4921-9c71-0adf81c0743f.png)
