### ISSUE TITLE
Choosing robust optimization in jointplot

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [mwaskom/seaborn#439]
Is there any way to ask `jointplot` to use a robust regression instead?

E.g. consider:
```
ax  = sns.jointplot(col0, col1, data=data_df, kind="reg",
                    xlim=(0, 120), ylim=(-20, 20), color=color, size=7)
```
From what I can tell,  `regplot` [seems to support the option `robust`](http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.regplot.html?highlight=reg#seaborn.regplot). Is there any way to pass down a similar option through `jointplot`?

Looking at [`jointplot`'s documentation](http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.jointplot.html?highlight=reg) I see that one can use `kws` dictionaries. Any way I could use one of them for this?

> `{joint, marginal, annot}_kws` : dicts
> Additional keyword arguments for the plot components.

**Comment by amelio-vazquez-reina** [comment]
Nevermind. One answer is to just go lower level and use `JointGrid` with `plot_marginals` and `plot_joint`

**Comment by mwaskom** [comment]
Yep, if you want to do it at the high level you'd need to pass `dict(robust=True)` to the `joint_kws` parameter. But I do agree that using `JointGrid` directly can yield code that is more straightforward when you want to do substantial customization of the plots.

**Comment by amelio-vazquez-reina** [comment]
Thanks @mwaskom . Great to know.
