### ISSUE TITLE
factorplot/barplot's x_order can't be a pandas Series

### ISSUE THREAD

**Issue by mbatchkarov** [mwaskom/seaborn#448]
When plotting the following data frame without an explicit `x_order` argument things look great.

```
df = pd.DataFrame({'name': list('abcde'), 'score' : [3,2,1,5,4]})
sns.factorplot(x='name', y='score', data=df, kind='bar');
```

If I wanted to order the bars by height, the labels of the x axis in the following bar chart are wrong (should be `c b a e d`, because `c` has a value of `1` in the data frame and a value of `3` in the figure).

```
order = df.name[df.score.argsort()]
sns.barplot(x=df.name, y=df.score, x_order=order)
```

![wrong](https://cloud.githubusercontent.com/assets/937114/6153634/e525e20c-b21d-11e4-987c-17db81a39c75.png)

If I convert the label to a python `list` or a numpy `ndarray` things also look correct:

```
order = df.name[df.score.argsort()].tolist()
sns.factorplot(x='name', y='score', data=df, kind='bar', x_order=order);
```

```
order = df.name[df.score.argsort()].values
sns.factorplot(x='name', y='score', data=df, kind='bar', x_order=order);
```

The same happens if I use `sns.barplot` directly. The docs says `x_order` should be list-like, and I think `pd.Series` falls in that category.

**Comment by mwaskom** [comment]
This code is currently getting overhauled to use the same underlying implementation as the new boxplot/violinplot code so I think this issue will disappear (but keep an eye out for the pull request and bug me there if that isn't true).

**Comment by mwaskom** [comment]
Closing #448 via #466
