### ISSUE TITLE
Extend tsplot to plot observation quantiles?

### ISSUE THREAD

**Issue by shoyer** [mwaskom/seaborn#450]
We often like to plot time-series almost exactly like this example from tsplot:
![image](https://cloud.githubusercontent.com/assets/1217238/6197735/be036856-b39f-11e4-840b-0278b934bd71.png)

...but with the plot showing quantiles of the measurement distribution, not CI bands for the mean/median.

We could call this `err_style='unit_band'`, which would make sense, though controlling it with the argument `ci` would be a little strange.

**Comment by mwaskom** [comment]
I think this is basically what #56 is. `tsplot` could use a lot of work...

**Comment by jetheurer** [comment]
Is this supported now?

**Comment by shoyer** [comment]
@jetheurer  Nope... this still needs someone to put in the work :).

**Comment by jetheurer** [comment]
@shoyer Do you have a example code of what you like to do?  I'd be interested in building off of it.

**Comment by mwaskom** [comment]
Unfortunately, the tsplot internals are poorly implemented and untested, so any enhancement is probably going to have to wait until it can be refactored. 



—

**Comment by shoyer** [comment]
@jetheurer Not that I can share publicly, I'm afraid...

All the computation is handled by the `pandas.DataFrame.quantile` method, though.

**Comment by mwaskom** [comment]
Closing with deprecation of `tsplot`.
