### ISSUE TITLE
sns.color_palette doesn't restore palette cycle count

### ISSUE THREAD

**Issue by wavexx** [mwaskom/seaborn#452]
```
sns.set_palette(sns.color_palette('Set1', 9), 9)
with sns.color_palette(...):
    pass
# palette cycle count is now back to 6
```

**Comment by mwaskom** [comment]
Mm this is a particularly egregious example of the weird behavior introduced by having a default palette size, discussed further in #314

**Comment by wavexx** [comment]
On 02/18/2015 02:33 AM, Michael Waskom wrote:
> Mm this is a particularly egregious example of the weird behavior
> introduced by having a default palette size, discussed further in
> #314

I didn't want to bring this issue up, but the default palette size is a
bad idea IMHO. It was totally unexpected for me when I stumbled upon it
at the beginning, and it's still un-useful now that I know the behavior.

**Comment by mwaskom** [comment]
i agree
