### ISSUE TITLE
skip test if no internet connection

### ISSUE THREAD

**Issue by timmie** [mwaskom/seaborn#453]
we are building the daily packages of seaborn for Ubuntu over at Launchpad:
https://code.launchpad.net/~pythonxy/+recipe/pythonxy-seaborn-daily

Since recently, the builds fail because test data is being pulled from the internet:
```
      File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
        context=self._context)
      File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
        raise URLError(err)
    URLError: <urlopen error [Errno 111] Connection refused>
----------------------------------------------------------------------
File "/build/buildd/seaborn-0.6.0~ppa6~revno/.pybuild/pythonX.Y_2.7/build/seaborn/distributions.py", line 1362, in seaborn.distributions.boxplot
```
https://launchpadlibrarian.net/197764497/buildlog_ubuntu-vivid-amd64.seaborn_0.6.0~ppa6~revno-448~ubuntu15.04.1_FAILEDTOBUILD.txt.gz

Please have a look at statsmodel and how this was solved there:
https://github.com/statsmodels/statsmodels/issues/2233#issuecomment-73553009

Thanks.

**Comment by mwaskom** [comment]
Just don't run the doctests.

**Comment by mwaskom** [comment]
Does this mean I can close #429?

**Comment by timmie** [comment]
yes.
http://bazaar.launchpad.net/~pythonxy/pythonxy-upstream-debian/python-seaborn_debian/revision/6#rules
