### ISSUE TITLE
KDE Plot Tutorial bandwidth rule-of-thumb question

### ISSUE THREAD

**Issue by jmportilla** [mwaskom/seaborn#456]
In the tutorial the Silverman rule-of-thumb options for the kde plot are:

Compute the bandwidth of the kernel using a rule-of-thumb

bandwidth = ((4 * data.std() ** 5) / (3 * len(data))) ** .2
bandwidth = len(data) ** (-1. / 5)

Is the second one correct? Why is it not:

bandwidth = (1.06 * len(data) * data.std )** (-1./5)

http://en.wikipedia.org/wiki/Kernel_density_estimation#Practical_estimation_of_the_bandwidth

**Comment by mwaskom** [comment]
I think the tutorial uses scott's factor, which is the default in scipy/statsmodels and hence seaborn.

**Comment by jmportilla** [comment]
Ah okay. Thanks for the info!

**Comment by mwaskom** [comment]
Actually that code definitely looks wrong; I missed the reassignment originally (though the fact that it's trying to implement Scott's and not Silverman's is true). It doesn't really matter -- it's just for making the plot that shows how the KDE is constructed. But should be fixed.

**Comment by mwaskom** [comment]
Closed with #566
