### ISSUE TITLE
Complication arises using the factorplot with col_wrap

### ISSUE THREAD

**Issue by jamesppeng** [mwaskom/seaborn#464]
The returned axes is 1D (instead of 2D) array when using factorplot with col_wrap. This causes a few methods fail. Peeking into the source code. I think it is because those methods address individual subplot by the syntax self.axes[i,j] but should be just self.axes[n]

**Comment by mwaskom** [comment]
That makes sense but can you be more specific about what methods fail?

(Also technically this would be a problem with `FacetGrid` and not `factorplot`)

**Comment by jamesppeng** [comment]
An example is:
'''
C:\Python27\lib\site-packages\seaborn-0.6.dev-py2.7.egg\seaborn\axisgrid.pyc in set_xticklabels(self, labels, step, **kwargs)
    585     def set_xticklabels(self, labels=None, step=None, **kwargs):
    586         """Set x axis tick labels on the bottom row of the grid."""
--> 587         for ax in self.axes[-1, :]:
    588             if labels is None:
    589                 labels = [l.get_text() for l in ax.get_xticklabels()]
IndexError: too many indices
'''

by the way, thanks for this super package.

**Comment by jamesppeng** [comment]
Thanks Michael

Seaborn is a great package
