### ISSUE TITLE
How to use different arguments for distplots in plot_marginals?

### ISSUE THREAD

**Issue by timalthoff** [mwaskom/seaborn#469]
Thanks for this fantastic library! I find a lot of use for the hexbin joint plots as in:
sns.jointplot("total_bill", "tip", tips, kind="hex", color="#8855AA");

However, the binning for the x and y histograms is "off" (grouping values in suboptimal way). I would like to manually specify the bins (or number of bins). However, I would have to do that separately for x and y.
g.plot_marginals(sns.distplot, kde=False, bins=1000) # how to do that separately for x and y?

Thanks!

Side note: g.plot_joint(plt.hexbin, gridsize=20)
The plot is gray instead of the default blue. Why am I not getting the default blue color here? Do I have to override color manually?

**Comment by mwaskom** [comment]
Question 1: You'll have to call `distplot` directly (twice) and pass it `g.ax_marg_{x,y}` to use different non-reference-rule bins.

Question 2: You need to set the `cmap` argument; `JointGrid` passes `color=` but that isn't interpreted correctly by `plt.hexbin`.

**Comment by timalthoff** [comment]
Thanks for the quick response! Unfortunately, I'm still having some trouble to get it to work. Here are the details:

This is what I'm starting with:
`sns.jointplot(temp[x], temp[y], kind="hex", size=10, joint_kws={'gridsize':20})`
![image](https://cloud.githubusercontent.com/assets/1224484/6693441/35c28788-cc90-11e4-9d34-dcf668f0b868.png)
You can see weird binning behavior on the right y-axis histogram. Most likely they occur because this data is integer-valued and because of unfortunate binning.

I'm trying to reconstruct the exact same plot using the "long form" and then use different binning strategies.

```python
g = sns.JointGrid(temp[x], temp[y], size=10)
g.plot_marginals(sns.distplot, kde=False, bins=np.linspace(0,12000, num=51), ax=g.ax_marg_x)
g.plot_marginals(sns.distplot, kde=False, bins=np.linspace(0,101, num=51), ax=g.ax_marg_y, vertical=True)
g.plot_joint(plt.hexbin, gridsize=20, cmap=ListedColormap(sns.color_palette("Blues")))
g.annotate(stats.spearmanr, template="{stat} = {val:.3f} (p = {p:.3g})");
```

I seem to be doing something wrong here...
![image](https://cloud.githubusercontent.com/assets/1224484/6693541/e6f4857e-cc90-11e4-9bb6-5eb8f0a1d205.png)

Also, I'm probably also making a mistake with the cmap thing:
``` python
g = sns.JointGrid(temp[x], temp[y], size=10)
g.plot_marginals(sns.distplot, kde=False) #, bins=np.linspace(0,12000, num=101), ax=g.ax_marg_x)
g.plot_marginals(sns.distplot, kde=False) #, bins=np.linspace(0,101, num=101), ax=g.ax_marg_y, vertical=True)
g.plot_joint(plt.hexbin, gridsize=20, cmap=ListedColormap(sns.color_palette("Blues")))
g.annotate(stats.spearmanr, template="{stat} = {val:.3f} (p = {p:.3g})");
```

![image](https://cloud.githubusercontent.com/assets/1224484/6693559/06bf4b28-cc91-11e4-94aa-9a29e7c367f7.png)
Here, the colors are quite different.

It would be awesome if anyone could help me understand what I'm missing. Thanks!

**Comment by mwaskom** [comment]
It would probably be best to do something like this:

```python
g = sns.JointGrid(x, y)
g.ax_marg_x.hist(x, bins=np.arange(0, 60))
g.ax_marg_y.hist(y, bins=np.arange(0, 1000, 10), orientation="horizontal")
g.plot_joint(plt.hexbin, gridsize=25, extent=[0, 60, 0, 1000], cmap="Blues")
g.fig.savefig("/Users/mwaskom/Desktop/jointgrid.png", bbox_inches="tight")
```

![jointgrid](https://cloud.githubusercontent.com/assets/315810/6739717/e48e8caa-ce37-11e4-93cd-7208ad6d1b52.png)

The reason you're seeing weird colors the way you're doing it is that `plot_marginals` is still going to call the plotting function twice. The `ax` kwarg makes sure both times it is plotted on the correct Axes, but you're getting a mixture of blue and green bars.

If you want to use one of the matplotlib colormaps you can generally just pass the name, as I did above. The problem you're seeing with the way you're trying to use the `Blues` map is that `color_palette` is returning a discrete list of only 6 colors, and so there is much less variation in the resulting colormap.

By the way, `jointplot` does something a little more complicated to get a colormap based off the input color, which is also why "Blues" isn't giving you exactly what you might expect:

```python
colors = [sns.set_hls_values(color, l=l) for l in np.linspace(1, 0, 12)]
cmap = sns.blend_palette(colors, as_cmap=True)
```

**Comment by mwaskom** [comment]
By the way, these kind of "how do I" questions are generally a little bit more at home on StackOverflow, where it will be seen by other people who might have a good answer, and by others who might have the same question in the future.

**Comment by souvikita** [comment]
Thanks a lot for this @mwaskom ! I was looking all over the internet for a semi-log joint grid plot. I managed to do a log-log plot but a semi-log with jointgrid appeared very tricky to me. Thanks a lot. My plot is attached (exactly the way I wanted it to be!) 
<img width="448" alt="Screenshot 2020-06-05 14 58 50" src="https://user-images.githubusercontent.com/31192984/83860656-2b542580-a73d-11ea-9445-74a2441c6164.png">
