### ISSUE TITLE
saving regplot with savefig cuts off part of the saved plot

### ISSUE THREAD

**Issue by Teodormz** [mwaskom/seaborn#470]
Even though this bug was closed, https://github.com/mwaskom/seaborn/issues/114, 
the workaround doesn't work for my complex graph:
g = sns.FacetGrid(df, row='a', col='b', sharey = False, margin_titles=True)
bins = np.linspace(0, 1, 50)
g.map(plt.hist, 'c', bins=bins, lw=0.5, alpha=0.6)
I have a grid of 11x11 graphs, and the description of the rows on the right of the graphs doesn't sho up when I do savefig

**Comment by Teodormz** [comment]
Using bbox_inches='tight' helped

**Comment by dhimmel** [comment]
+1 `bbox_inches='tight' ` did the trick for me.

**Comment by ca-scribner** [comment]
Same, although I wouldn't say this should be closed.  The expected behaviour would be that this work without the bbox_inches, right?  Seems like a good bug to fix
