### ISSUE TITLE
markers kw arg to does not work together with hue_order

### ISSUE THREAD

**Issue by ahjulstad** [mwaskom/seaborn#472]
The `pairplot` function does not arrange markers according to hue_order

```
sns.pairplot(vars=['R','T','W',], 
             hue="Category", 
             hue_order=["Uncategorised", "C", "F", "S"],
             markers=['.','o','o','o'],
             data=d)
```
gives the small dots to the C category.  (I wanted the small dots for the uncategorised data.)

This is with current 0.6dev ( 9a1db37 )

**Comment by mwaskom** [comment]
I think actually the problem here is that `hue_order` doesn't work properly.

**Comment by mwaskom** [comment]
Sorry about the delay; thanks for reporting this.
