### ISSUE TITLE
Statistical methodology in pairwise correlation?

### ISSUE THREAD

**Issue by patwater** [mwaskom/seaborn#476]
What's the statistical methodology for the searborn corrplot?  Pearson, spearman, ...?  http://stanford.edu/~mwaskom/software/seaborn/index.html

Not clear from the documentation.

**Comment by mwaskom** [comment]
The default is pearson, or more accurately, it delegates to the default function that `DataFrame.corr` uses. The `method` kwarg is passed through and can be used to estimate correlations with spearman or kendall metrics.

PS `corrplot` is probably going to be deprecated in favor of using `heatmap` and computing the correlation matrix yourself.
