### ISSUE TITLE
CI bands not showing in tsplot

### ISSUE THREAD

**Issue by SeanWhipple** [mwaskom/seaborn#478]
I'm not sure if I'm doing something wrong here or if this is a bug...

I have a dataframe that has some time series data and I'd like to plot with confidence intervals.  When I plot in with err_style=unit_traces I can see the data (some of the data is disjoint but I hoped it would interpolate between them).

When I do err_style=ci_band I don't see any output.

The pickle of the dataframe can be found here:
https://www.dropbox.com/s/d9ublo17h8lundl/test.pickle?dl=0

The two lines I execute are:
sns.tsplot(data=df.sort('time', ascending=True), time='time', unit='entity', condition='prior_type', value='perf', err_style='unit_traces')

and 

sns.tsplot(data=df.sort('time', ascending=True), time='time', unit='entity', condition='prior_type', value='perf')

**Comment by mwaskom** [comment]
I assume you have some missing observations? You'll need to use `estimator=stats.nanmean` (this is non-obvious, I know).

**Comment by mwaskom** [comment]
I think this is related to [this SO question](http://stackoverflow.com/questions/29156464/seaborn-tsplot-not-showing-ci-bands) that I answered so I'm gonna close.
