### ISSUE TITLE
"ValueError: width and height must each be below 32768" in heatmap() using python3.4

### ISSUE THREAD

**Issue by fbrundu** [mwaskom/seaborn#481]
Hi all,
I got this error:

    20.0 71.2
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-15-76bb77175c6d> in <module>()
          3 print(act/5, samples/5)
          4 plt.figure(1, figsize=[samples/5, act/5])
    ----> 5 sns.heatmap(results_anova)
          6 plt.savefig("heatmap_anova.svg", bbox_inches="tight")
          7 plt.savefig("heatmap_anova.pdf", bbox_inches="tight")
    
    /usr/local/lib/python3.4/dist-packages/seaborn/matrix.py in heatmap(data, vmin, vmax, cmap, center, robust, annot, fmt, annot_kws, linewidths, linecolor, cbar, cbar_kws, cbar_ax, square, ax, xticklabels, yticklabels, mask, **kwargs)
        290     if square:
        291         ax.set_aspect("equal")
    --> 292     plotter.plot(ax, cbar_ax, kwargs)
        293     return ax
        294 
    
    /usr/local/lib/python3.4/dist-packages/seaborn/matrix.py in plot(self, ax, cax, kws)
        174 
        175         # Possibly rotate them if they overlap
    --> 176         plt.draw()
        177         if axis_ticklabels_overlap(xtl):
        178             plt.setp(xtl, rotation="vertical")
    
    /usr/local/lib/python3.4/dist-packages/matplotlib/pyplot.py in draw()
        569 
        570     """
    --> 571     get_current_fig_manager().canvas.draw()
        572 
        573 
    
    /usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_qt5agg.py in draw(self)
        146         # causes problems with code that uses the result of the
        147         # draw() to update plot elements.
    --> 148         FigureCanvasAgg.draw(self)
        149         self._priv_update()
        150 
    
    /usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_agg.py in draw(self)
        462         if __debug__: verbose.report('FigureCanvasAgg.draw', 'debug-annoying')
        463 
    --> 464         self.renderer = self.get_renderer(cleared=True)
        465         # acquire a lock on the shared font cache
        466         RendererAgg.lock.acquire()
    
    /usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_agg.py in get_renderer(self, cleared)
        479 
        480         if need_new_renderer:
    --> 481             self.renderer = RendererAgg(w, h, self.figure.dpi)
        482             self._lastKey = key
        483         elif cleared:
    
    /usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_agg.py in __init__(self, width, height, dpi)
         92         self.height = height
         93         if __debug__: verbose.report('RendererAgg.__init__ width=%s, height=%s'%(width, height), 'debug-annoying')
    ---> 94         self._renderer = _RendererAgg(int(width), int(height), dpi, debug=False)
         95         self._filter_renderers = []
         96 
    
    ValueError: width and height must each be below 32768

The first two number are the size for the figure, passed to `plt.figure() figsize` parameter. My matplotlib backend is `Qt5Agg`. I am using `seaborn 0.5.1` with `ipython 3.0.0` on Ubuntu 14.04.

Am I doing anything wrong?

Thanks

**Comment by mwaskom** [comment]
Those values are in inches, it sounds like you're trying to make a figure that is larger than matplotlib can draw?

**Comment by fbrundu** [comment]
You're right.

I thought that using `plt.figure(1, figsize=[samples/<n>, act/<n>])` would be enough to produce correctly a figure. Maybe it is ignored, because reducing the input data instead makes the call save a pdf and a svg as I wanted.

Thanks anyway.
