### ISSUE TITLE
Additional Documentation on Colorblind Accessibility

### ISSUE THREAD

**Issue by jzf2101** [mwaskom/seaborn#485]
#218 references [colorblind pallettes] (http://web.stanford.edu/~mwaskom/software/seaborn/tutorial/color_palettes.html) for inidivuals with color blindness

Given the ease of setting color blind palettes, additional lanugage on creating accessbile plots would be useful.  For example, [colorbrewer](http://colorbrewer2.org/) gives some clear hints on picking colorblind accessible themes. Passing a colorblind accessible theme into a plot method is another way one can ensure a plot is accessible.

**Comment by mwaskom** [comment]
Do you have something specific in mind?

**Comment by jzf2101** [comment]
Sure. I was thinking something along the lines of guides to set one's parameters as being color-blind accessible, both for individual plots and for one's overall settings.  Also useful would be references to specific color palettes that are color blind friendly.
