### ISSUE TITLE
Control boxplot-specific keywords from factorplot

### ISSUE THREAD

**Issue by jackjackk** [mwaskom/seaborn#489]
`factorplot` creates nice grouped boxplots w/ different hues, but I am not able to pass through `boxplot`-specific keyword arguments, like `showfliers`.
On the other hand, I have such control with `FacetGrid.map`, but the boxplots w/ different hues are stacked, not juxtaposed.
What could I do to have both things, i.e. grouped boxplots with control on `showfliers`)?

**Comment by mwaskom** [comment]
It sounds like you're using a released version of seabon. The next version (and the current master branch on github) addresses this issue in two ways. First, `factorplot` will pass additional keyword arguments through to the underlying plotting function. Second, `boxplot` itself allows for grouped boxplots with different hues much like `factorplot`, but in a way that can be plotted onto a specific Axes.

Note that these enhancements involved some substantial API changes, so make sure you check understand those before upgrading any kind of production environment. Best place to do that would be reading the [github pull request](https://github.com/mwaskom/seaborn/pull/410) (and the related one that addresses [`factorplot`](https://github.com/mwaskom/seaborn/pull/466) or looking at the [release notes](http://stanford.edu/~mwaskom/software/seaborn-dev/whatsnew.html) in the current development docs.
