### ISSUE TITLE
Bar ordering with barplot

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [mwaskom/seaborn#493]
Is there any way to specify the ordering of the bars in a bar plot?

For example, consider the following dataframe:

``` python
                       Type  Count
0  Spend hitting day budget     20
1                     Total     32
2      With true day budget     26
```

And then the following command:
`sns.barplot('Type', 'Count', data = nf, ci=None, palette="deep", hline=.1, ax=ax)`

which gives the following result:

![screen shot 2015-03-26 at 3 39 24 pm](https://cloud.githubusercontent.com/assets/1993919/6855773/85d37352-d3d1-11e4-84d1-f1c0f5ca6c45.png)

Is there any way to specify/control the order (left to right) of the bars in the bar pot?

**Comment by mwaskom** [comment]
For seaborn < 0.6, use the `x_order` kwarg.

For seaborn > 0.6, use the `order` kwarg or give the variable a `category` datatype with and ordered list of categories.

**Comment by amelio-vazquez-reina** [comment]
Great. Thank you @mwaskom !
