### ISSUE TITLE
Overlapping legend in factorplot example

### ISSUE THREAD

**Issue by fbrundu** [mwaskom/seaborn#494]
I am trying the example from [here][1]. However the legend is overlapping the figure:

![prova_example](https://cloud.githubusercontent.com/assets/697622/6893109/68710026-d6ca-11e4-9309-41229b5125bc.png)

During the call `sns.factorplot()` I get this warning:

    /usr/local/lib/python3.4/site-packages/matplotlib/tight_layout.py:225: UserWarning: tight_layout : falling back to Agg renderer
      warnings.warn("tight_layout : falling back to Agg renderer")

I am on Mac OS X 10.10.2.
ipython version: 3.0.0
seaborn version: 0.5.1

[1]: http://stanford.edu/~mwaskom/software/seaborn/examples/grouped_boxplot.html

**Comment by mwaskom** [comment]
What  matplotlib version?

**Comment by fbrundu** [comment]
Matplotlib 1.4.3

**Comment by fbrundu** [comment]
Maybe it's useful, the used backend for matplotlib is "MacOSX"

**Comment by fbrundu** [comment]
I can confirm that using "TkAgg" backend it is working better, if not OK. See image. So the problem is with "MacOSX" backend I think.

![figure_1](https://cloud.githubusercontent.com/assets/697622/6915080/730c25de-d791-11e4-8c90-d2ada9c3b340.png)

**Comment by mwaskom** [comment]
Ah yes, the backend, good thought. The MacOSX backend has some known problems, actually usually the issue I see is that it just crashes, so maybe there have been some improvements. But still. Looks like everything works fine with the TkAgg backend so I think it's fair to say this is a (known) matplotlib issue and nothing that can be changed in seaborn.

**Comment by fbrundu** [comment]
Ok thanks for your time :)

**Comment by fredcallaway** [comment]
In case anyone else lands here, I fixed the problem by inserting the following line right after my `sns.set()` line:

`sns.plt.switch_backend('TkAgg')`

This is assuming you use sns.plt rather than matplotlib.pyplot

**Comment by asalt** [comment]
For future people I just want to add that I had to use `Agg` instead of `TkAgg` on Linux (Debain based).  So you may have to play around a bit to figure out what setting works for you.
