### ISSUE TITLE
Timetstamp locators and formatters for boxplots

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [mwaskom/seaborn#498]
Consider the following dataframe:
```
> to_plot.head(10)
   timestamp           value
0 2015-03-26       13.742770
1 2015-03-27       75.620200
2 2015-03-28       75.428619
3 2015-03-29       74.682519
4 2015-03-30       34.170050
5 2015-03-31       43.305406
6 2015-04-01       74.524555
7 2015-03-26       81.176429
8 2015-03-27      110.281429
9 2015-03-28      105.403571
```
with `dtypes`:
```
> to_plot.dtypes
timestamp              datetime64[ns]
value           float64
dtype: object
```
Doing a `boxplot` works:
```
> sns.boxplot(ax=ax, data=to_plot, x='date', y='forward_pacing', color=boxplot_color)
```
![screen shot 2015-04-03 at 1 27 57 pm](https://cloud.githubusercontent.com/assets/1993919/6985819/3f38e370-da05-11e4-8f72-4067cb562069.png)

but if I try to change locators or formatters, it doesn't, e.g:

```
ax.xaxis.set_major_locator(matplotlib.dates.DayLocator(interval=2))
```
shows no ticks:

![screen shot 2015-04-03 at 1 28 38 pm](https://cloud.githubusercontent.com/assets/1993919/6985826/5a27d6e6-da05-11e4-9907-ef3ab6c7f0ce.png)

Why? How can I control the locators and formatters of a boxplot created by seaborn?

This is all with the latest version of master from April 3rd.

In case it helps: 
```
abstract-rendering==0.5.1
appnope==0.1.0
argcomplete==0.8.1
arrow==0.4.4
astropy==0.4.2
bcolz==0.8.0
beautifulsoup4==4.3.2
binstar==0.10.1
bitarray==0.8.1
blaze==0.7.2
blz==0.6.2
bokeh==0.8.2
boto==2.36.0
cffi==0.8.6
click==3.3
clyent==0.3.2
colorama==0.3.3
configobj==5.0.6
cryptography==0.5.4
Cython==0.22
cytoolz==0.7.1
DataShape==0.4.4
decorator==3.4.0
docopt==0.6.2
docutils==0.12
dulwich==0.9.7
fastcache==1.0.1
flake8==2.3.0
Flask==0.10.1
folium==0.1.3
funky==0.0.2
future==0.14.3
gitdb==0.6.4
GitPython==0.3.6
gittle==0.5.0
greenlet==0.4.5
h5py==2.4.0
importmagic==0.1.3
into==0.2.2
ipython==3.0.0
itsdangerous==0.24
jdcal==1.0
jedi==0.8.1
Jinja2==2.7.3
joblib==0.8.3.post1
llvmlite===0.2.2-1-gbcb15be
llvmpy==0.12.7
lpsolve55==5.5.2.0
lxml==3.4.0
MarkupSafe==0.23
matplotlib==1.4.3
mccabe==0.3
mock==1.0.1
multipledispatch==0.4.7
multiuserblazeserver==0.2
networkx==1.9.1
nltk==3.0.0
nose==1.3.4
numba==0.17.0
numexpr==2.3.1
numpy==1.9.2
odo==0.3.1
openpyxl==1.8.5
pandas==0.16.0
paramiko==1.10.0
parse==1.6.4
patsy==0.3.0
pdb==0.1
pep8==1.6.2
pgcli==0.16.0
Pillow==2.5.1
ply==3.4
prompt-toolkit==0.26
psutil==2.2.0
psycopg2==2.6
py==1.4.25
pycosat==0.6.1
pycparser==2.10
pycrypto==2.6
pycurl==7.19.5.1
pyflakes==0.8.1
Pygments==2.0.2
pymc==2.3.5
pymongo==2.8
pyOpenSSL==0.14
pyparsing==2.0.3
pytest==2.6.3
python-dateutil==2.4.1
python-gnupg==0.3.7
pytz==2014.10
PyYAML==3.11
pyzmq==14.5.0
qds-sdk==1.4.3
redis==2.9.1
requests==2.6.0
rope-py3k==0.9.4.post1
runipy==0.1.1
scikit-image==0.10.1
scikit-learn==0.15.2
scipy==0.15.1
seaborn==0.6.dev0
Shapely==1.5.2
six==1.9.0
smmap==0.9.0
sockjs-tornado==1.0.1
Sphinx==1.2.3
spyder==2.3.2
SQLAlchemy==0.9.8
sqlparse==0.1.14
statsmodels==0.6.1
sympy==0.7.6
tables==3.1.1
Theano==0.6.0
toolz==0.7.1
tornado==4.1
ujson==1.33
urllib3==1.10.2
vincent==0.4.4
wcwidth==0.1.4
Werkzeug==0.10.1
xlrd==0.9.3
XlsxWriter==0.5.7
```

**Comment by mwaskom** [comment]
I'm not sure exactly -- I don't really do any work with datetime data, but as far as I know getting everything to work correctly between numpy, pandas, and matplotlib is cumbersome.

As far as I can tell, matplotlib is able to format dates correctly when it detects that the input *data* for the plot are datetimes. The seaborn categorical plots just place objects at integer values on the categorical axes and then modify the ticklabels with the category labels. That means that at the time you get a reference to the `Axes` object back, the ticklabels have lost their datetime object information and are just strings.

There may be a way around this, but it is not clear what it would be. It doesn't seem possible to place matplotlb boxplots at specific datetime data coordinates anyway, and I can't get pandas plotting to give me a boxplot with correct date labels. (But as I've said, I'm fairly ignorant about what you have to do to get dates to work correctly in all these packages). Someone who understands this stuff better might be able to get the Axis objects to have the right formatters before adding the date labels inside boxplot, in which case your code should work. However, as far as I can tell, that's all tied into the representation of the plot data and the transforms on it that matploltlib implements, so I am at a loss.

For now, this is what I was able to put together to get a reasonable plot with datetime categories:

```python
dates = np.repeat(pd.date_range("March 1 2015", "March 6 2015"), 10)
df = pd.DataFrame(dict(date=dates, value=np.random.randn(60)))
order = df.date.unique().astype("datetime64[D]")
sns.boxplot(x="date", y="value", data=df, order=order)
```

![dates](https://cloud.githubusercontent.com/assets/315810/6994165/a4451a2c-dac3-11e4-95e4-2c493bed3595.png)

There's probably a better way, but this seems to work...

**Comment by TomAugspurger** [comment]
pandas only does special datetime handling for line plots. Bar plots and line plots both get labels similar to the original post.

**Comment by amelio-vazquez-reina** [comment]
Thanks. I am somewhat confused about what package does what, in what cases and why this fails. 

The locators and formatters I used in the OP seem to be provided by `matplotlib` (i.e `matplotlib.dates.*Locator` and `matploblib.dates.*Formatter`. Why would the type of plot matter for this? Does Pandas / seaborn handle boxplots in a manner different from other plots?

**Comment by mwaskom** [comment]
It's just a distinction between plotting dates as data vs. using dates as labels. For categorical plots like boxplots, the latter is happening. So the date objects used on the ticks are just strings, and the matplotlib date formatter doesn't know what to do with them.

**Comment by matuwuhou** [comment]
this is what worked for me:
1. transform variable with desired format:
df[:, var] = df.var.dt.strftime('%Y %m')
2. don't forget to sort after that
df = df.sort_values(var)
3. split var into year and month to be able to change numbers to labels, i.e. 01 -> Jan
4. run sns.boxplot
5. apply auto format, so labels are rotated if it's needed
fig.autofmt_xdate()

**Comment by drjigna1305** [comment]
how to plot boxplot with dtypes objects and having special character $M,$K
