### ISSUE TITLE
Issue with map_diag in PairGrid

### ISSUE THREAD

**Issue by woutergins** [mwaskom/seaborn#501]
Calling the map_diag twice for the same PairGrid throws a TypeError since self.diag_axes is set to None in line 937 of axisgrid.py
I encountered this bug when I tried to pass the diagonals again to generate titles.
This can be fixed by leaving the else-clause empty.

**Comment by mwaskom** [comment]
Not sure what you mean can you please provide a reproducible example using the example data?

**Comment by woutergins** [comment]
Certainly. A very simple example is:

    import matplotlib.pyplot as plt
    import seaborn as sns

    df = sns.load_dataset('iris')

    g = sns.PairGrid(df, diag_sharey=False)
    g.map_lower(sns.kdeplot, cmap="Blues_d")
    g.map_upper(plt.scatter)
    g.map_diag(sns.kdeplot, lw=3)
    g.map_diag(sns.kdeplot, lw=3)
    plt.show()
This is exactly the same code as the example, except the map_diag is repeated. This raises a TypeError:

    Traceback (most recent call last):
      File "C:\Users\Wouter\Documents\Python Scripts\seabornTest.py", line 10, in <module>
        g.map_diag(sns.kdeplot, lw=3)
      File "C:\Anaconda\lib\site-packages\seaborn\axisgrid.py", line 941, in map_diag
        ax = self.diag_axes[i]
    TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by mwaskom** [comment]
Easy fix; thanks!
