### ISSUE TITLE
pairGrid variable scatter marker's size

### ISSUE THREAD

**Issue by massich** [mwaskom/seaborn#502]
I'm trying to add a new data dimension by modifying the marker's size in a scatter plot. i.e: to encode an error measure. Here is a minimum working example:

```
import pandas as pd
import seaborn as sns

n_points = 5
s = [(x+1)*100 for x in range(n_points)]
df = pd.DataFrame({'a' : range(n_points),
                   'b' : range(n_points),
                   'label' : range(n_points),
                   'size' : s})

g = sns.PairGrid(df, hue="label", size=2.5)
g.map_offdiag(plt.scatter, s=s)
g.map_diag(plt.hist)
```
![screenshot](http://s15.postimg.org/6grvg4bh7/4abfb91d543e540d817defaa1cf6b75444ad1e0ef1e53118.png)

I guess that this should be addressed by interpreting the ```**keywords``` in ```map_upper(self, func, **kwargs)``` and  ```map_lower``` functions. Similarly as it is done with the ```color``` parameter:

```
 color = self.palette[k] if kw_color is None else kw_color
 func(data_k[x_var], data_k[y_var], label=label_k,
                     color=color, **kwargs)
```

Despite the fact that ```s``` parameter is passed through the different calls, is only interpreted after this call and therefore all the elements are printed with the first element of the ```s``` list.

Shall I modify this function to iterate over ```s``` similarly as iterates over ```color``` or is there any other work-around that I missed to achieve this goal?

**Comment by mwaskom** [comment]
I don't think `scatter` should be special-cased here. An alternative would be to pass a vector of colors to scatter rather than using `hue` in `PairGrid`. That won't quite solve the problem of getting a legend, which you're not using here, but I assume probably want.

**Comment by massich** [comment]
You are right, only scatter has this particularity.  I'm using color for mapping my Ground Truth. So my need is more specific than I thought. The easiest way would be to inherent from PairGrid class an then change the behavior. 

Thanks a lot.

**Comment by mwaskom** [comment]
I should also mention that depending on what exactly you're doing, it can also be possible to reformat your dataframe so that you can use `FacetGrid` rather than `PairGrid`. In that case, because `s` is the third positional argument of `plt.scatter`, it should be possible to set the size based on another variable directly through the API.
