### ISSUE TITLE
MemoryError caused by jointplot

### ISSUE THREAD

**Issue by lucashtnguyen** [mwaskom/seaborn#503]
The following example causes either a MemoryError, or the program will cause the system to crawl by using excessive amounts of RAM forcing a manual restart of the kernel.

    import sys
    if sys.version_info[0] < 3:
        from StringIO import StringIO
    else:
        from io import StringIO

    import pandas as pd
    import seaborn as sns

    datastr = u'''model   res
    2467.012731   210
    2467.231481   340
    2467.089120   820
    25861.313657   490
    2467.000000  2400
    2467.089120   710
    2466.996528   475
    2467.188657   340
    2467.303241   180
    2467.493056   490
    2467.019676   220
    2467.351852   410
    6792.978009  1400
    2467.030093   210
    2467.004630   550
    2467.312500   330
    2467.244213   150
    2467.416667   310
    2467.127315   300
    2467.443287   600
    14270.891204   440
    2467.575231   410
    2467.503472   220
    2467.145833   470
    2487.700231   340
    2467.083333   290
    2467.190972   330
    5745.777778   510
    2467.133102   100
    2467.214120   920
    2467.111111   250
    2467.157407   200
    2466.958333   160
    2467.000000   270'''

    x = pd.read_csv(StringIO(datastr), sep='\s+')
    sns.jointplot('model', 'res', x)

Thus, far I've tested this issue on two machines running two different conda environments. Let me know if you need anymore info to diagnose the issue. 

Cheers, L

    In [1]:
        print(sys.version_info)
        print(pd.version.version)
        print(sns.__version__)

    Out[1]:
        sys.version_info(major=2, minor=7, micro=5, releaselevel='final', serial=0)
        0.16.0
        0.5.1

**Comment by mwaskom** [comment]
The reference rule used in `distplot` to determine the number of histogram bins for the `model` variable in your dataset returns 107700. You're likely running out of memory when matplotlib tries to draw a histogram with 107700 bars.

The reference rule isn't always going to work properly, and there is a catch for certain types of datasets where it obviously fails (returns inf). Your dataset seems close to that, but not quite.

I suppose one solution would be to put a ceiling on the number of bars that distplot could try to draw. It's rarely useful to have a histogram with more than ~50 bars anyway...

In the meantime I can get your dataset to work by passing a specific number of bins for the marginal histograms:

```python
sns.jointplot('model', 'res', x, marginal_kws={"bins": 30})
```

**Comment by mwaskom** [comment]
PS thanks for the complete/clear bug report.

**Comment by phobson** [comment]
thanks for getting back to us so fast, @mwaskom. This is a big help.

**Comment by lucashtnguyen** [comment]
Oh, that totally makes sense. Thanks! 

I'm not sure putting a ceiling on the number of bars is the correct path. This dataset is a little tricky just because we won't know how tight the distribution will be a priori, as this snippet of code if part of a tool used for model calibration.  Anyways, thanks for your help.
