### ISSUE TITLE
Stacked and grouped barplot

### ISSUE THREAD

**Issue by dubourg** [mwaskom/seaborn#505]
Any plan on enhancing the `barplot` function so that it handles multiple `y`'s in a stacked way?
I've been googling around but only found hacks...
For instance, [he](https://gist.github.com/ctokheim/6435202a1a880cfecd71) got back to the good old matplotlib placing bars and handling spaces.
Maybe you guys already have a hack around the present `barplot` implementation.
Cheers!

**Comment by mwaskom** [comment]
No, primarily because I think stacked bar plots are (in most cases) a really bad approach to visualization, and also because barplot has to support bars + confidence intervals which don't really make sense in a stacked configuration.
