### ISSUE TITLE
seaborn.tsplot and matplotlib's "Curve lines and axes parameters" editor

### ISSUE THREAD

**Issue by anntzer** [mwaskom/seaborn#508]
Currently, trying to edit curve lines and axes parameters (the checkbox with a green tick on the matplotlib toolbar) for a `seaborn.tsplot` fails with the following traceback:
```
$ ipython --pylab
Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
romUsing matplotlib backend: Qt5Agg
Using matplotlib backend: Qt5Agg
 se
In [1]: from seaborn import *; tsplot([1, 2])
Out[1]: <matplotlib.axes._subplots.AxesSubplot at 0x7f0262043d30>
# <------ click on green tick
In [2]: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/matplotlib/backends/backend_qt5.py", line 653, in edit_parameters
    figureoptions.figure_edit(axes, self)
  File "/usr/lib/python3.4/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 146, in figure_edit
    apply=apply_callback)
  File "/usr/lib/python3.4/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 510, in fedit
    dialog = FormDialog(data, title, comment, icon, parent, apply)
  File "/usr/lib/python3.4/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 416, in __init__
    parent=self)
  File "/usr/lib/python3.4/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 389, in __init__
    if len(data[0]) == 3:
IndexError: list index out of range

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

It is not clear to me whether the issue is on matplotlib's side or on seaborn's side, so this is crossposted as matplotlib/matplotlib#4323.

[Edit: Added full invocation trace, per @mwaskom comment below.]

**Comment by mwaskom** [comment]
In general there is no guarantee that seaborn will produce graphs that can work with the matplotlib interactive tools. But if it's something that's easy to fix, that would be good to know.

**Comment by mwaskom** [comment]
Also you didn't provide any info about how you're actually calling seaborn (i.e. example data and the code you actually used) so it is somewhat hard to understand what the problem might actually be...

**Comment by mwaskom** [comment]
Closing as I think the issue here will get sorted on the matplotlib side and then if there is something specific seaborn needs to change we can address that when it's clear.

**Comment by anntzer** [comment]
After some investigation I'm blaming this on the use of the private `_nolegend_` feature (see report on matplotlib side).  This should be easy to fix by matplotlib, but even if they do so I'd suggest changing the labels of the plots from `_nolegend_` to `_line{0,1,2,...}` (as matplotlib does by default): this way, the lines will appear on the figure property editor as expected, while keeping the legend invisible.

**Comment by mwaskom** [comment]
Nice sleuthing. I think it's not the lines that are being surprised from the legend, but the confidence bands, right?

**Comment by anntzer** [comment]
No, even using the PR code, `tsplot([1, 2])` leads to the line not appearing in the parameter manager, whereas `tsplot([1, 2], condition="_line0")` keeps the legend hidden but lets the line properties be edited.
