### ISSUE TITLE
contourf + grid : How do I see the grid without alpha?

### ISSUE THREAD

**Issue by JoyMonteiro** [mwaskom/seaborn#510]
Hello,

I'm using seaborn to set default parameters for my contourf plot.
However, as soon as the contourf is done, the gridlines disappear.
They appear only when I use alpha=0.6 (or something else) in the
contourf. Looks like contourf is being put above the grids. This
is also the behaviour I noticed in one of the examples:
http://stanford.edu/~mwaskom/software/seaborn/tutorial/quantitative_linear_models.html

I also tried passing the zorder parameter to both contourf and grid, but to no avail.
Is there some way for me to put the grid on top of contourf, as is the default in
matplotlib?

TIA,
Joy

**Comment by mwaskom** [comment]
You didn't say exactly what you tried, but I am able to to plot filled contours under a grid by doing `plt.contourf(x, zorder=0)`. Does this not work for you?

**Comment by JoyMonteiro** [comment]
It works, thanks! I was trying zorder=1 for contourf and zorder=10/100 for grid, and somehow this does not seem to work. Probably stems from my lack of understanding of zorder.

**Comment by mwaskom** [comment]
Great, glad it works.
