### ISSUE TITLE
Corrplot significance not shown when method explicitely given as pearson

### ISSUE THREAD

**Issue by HHammond** [mwaskom/seaborn#511]
The documentation specifies significance will not be computed for non-default methods, but when given 'pearson' as the method significance is not computed. 

Changing https://github.com/mwaskom/seaborn/blob/master/seaborn/linearmodels.py#L958 from:
```python
if annot and sig_stars and method is None:
```

to: 
```python
if annot and sig_stars and method != 'pearson':
```

would be a quick fix. If this is something that should actually be fixed, I would be happy to put in a PR.  

---

##### Desired output from `corrplot(df, method='pearson')`:
![out1](https://cloud.githubusercontent.com/assets/3064019/7119222/3ea62f56-e1d2-11e4-86d1-f21de574f8bf.png)

##### Actual output from `corrplot(df, method='pearson')`:
![out2](https://cloud.githubusercontent.com/assets/3064019/7119223/3ea8665e-e1d2-11e4-8ae9-15828d7d6ac2.png)

**Comment by mwaskom** [comment]
I feel like there was some reason for this but it's not coming to mind at the moment .In any case, `corrplot` is being deprecated and so it's probably not worth putting in the effort to fix it.

**Comment by HHammond** [comment]
Thanks, I'm closing this issue then.
