### ISSUE TITLE
Default colormap for heatmap and clusteredheatmap

### ISSUE THREAD

**Issue by mlovci** [mwaskom/seaborn#513]
Is Purples the right default for these functions? IMO Greys or Bone might be better ... saves color ink on printouts and color page costs in journals.

**Comment by mwaskom** [comment]
It's not Purples, it's a cubehelix variant. But if people who don't want to pay color figure charges can't be bothered to use the convenient `cmap` argument and use a grayscale colormap, that sounds like their problem...

**Comment by mlovci** [comment]
forcefully put.
