### ISSUE TITLE
Real-valued hue

### ISSUE THREAD

**Issue by jnothman** [mwaskom/seaborn#514]
It would be nice to perform, for example, `pairplot` with a hue column that has real values (as in a heatmap) with a heatmap-style legend shown. The code currently performs operations inappropriate for real values, such as `np.unique` and displaying a discrete legend.

**Comment by mwaskom** [comment]
With pairplot you should be able to pass a vector of scalar values to the `c` parameter in the `.map` method call.

**Comment by mwaskom** [comment]
Sorry just to clarify I mean use `PairGrid` directly. See [here](https://github.com/mwaskom/seaborn/issues/313) for an example.

**Comment by jnothman** [comment]
Okay, thanks. Still, I don't see why this should not be handled by `pairplot`, especially since passing such a column to `hue` results in unnecessarily slow processing to produce undesirable output.
