### ISSUE TITLE
0.6.dev version of violinplot misses join_rm option

### ISSUE THREAD

**Issue by maartenmennes** [mwaskom/seaborn#517]
It looks like the development version of violinplot misses the join_rm option. Is this on purpose?

**Comment by mwaskom** [comment]
Yes, give the other changes it was not feasible to include this option (Which I've also come to think of as not that helpful of a visualization). It should be possible to do a pointplot on top of the violins to get the same effect though.

**Comment by maartenmennes** [comment]
Cool, thanks  for the heads up. We were using this particular feature to visualize distributions of as well as individual trajectories of change in scores across two measurements. On to something better it is (within seaborn, no worries :) )



—
Maarten Mennes, PhD
postdoctoral research fellow
Donders Institute for Brain, Cognition and Behaviour
Nijmegen, The Netherlands

**Comment by mwaskom** [comment]
Here's the basic idea:

```python
exercise = sns.load_dataset("exercise").query("kind == 'running' and diet == 'low fat'")
sns.violinplot(x="time", y="pulse", inner=None, color=".5", data=exercise)
sns.pointplot(x="time", y="pulse", hue="id", palette="Reds_d", data=exercise)
```

![wglfezlt2oyjaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/315810/7236772/f42f99e2-e764-11e4-8c66-7c009ef75abf.png)

**Comment by maartenmennes** [comment]
Awesome, thanks! Are you visiting HBM this year? I definitely owe you a couple of drinks already!



—
Maarten Mennes, PhD
postdoctoral research fellow
Donders Institute for Brain, Cognition and Behaviour
Nijmegen, The Netherlands

**Comment by mwaskom** [comment]
Ah, no sadly. HBM sounds fun but I always seem to have blown my yearly conference budget before the time to submit comes around.

**Comment by maartenmennes** [comment]
You might want to save up at some point. HBM is an excellent conference for those interested in applied methodology. A good mix between pure methods and pure applications. Cheers!



—
Maarten Mennes, PhD
postdoctoral research fellow
Donders Institute for Brain, Cognition and Behaviour
Nijmegen, The Netherlands

**Comment by chrisfilo** [comment]
I miss join_rm as well. It was the best way for visualising longitudinal data I know of. Is there aa way to make pointplot plot every single value instead of mean estimates?

**Comment by mwaskom** [comment]
Sure, just pass whatever variable identifies subjects to `hue`.
