### ISSUE TITLE
Invalid rgb arg "Blues_r" error in online dev documentation

### ISSUE THREAD

**Issue by mmagnuski** [mwaskom/seaborn#518]
In case it was not noticed before:
[this part of documentation](http://stanford.edu/~mwaskom/software/seaborn-dev/tutorial/quantitative_linear_models.html#plotting-simple-regression-with-regplot) gives an error which causes all remaining code cells not to produce figures/results.

**Comment by mwaskom** [comment]
Yep as noted elsewhere (somewhere...) the tutorials haven't yet been updated to reflect the changes in 0.6.

**Comment by mmagnuski** [comment]
OK. BTW - lovely package!
Whenever I switch from matlab to python I find myself enchanted by seaborn's graphical grace. :smiley:
