### ISSUE TITLE
kdeplot inaccurate tails

### ISSUE THREAD

**Issue by IamGianluca** [mwaskom/seaborn#521]
Hi, I've noticed that the `kdeplot()` function in Seaborn doesn't perfectly plot the tails of the distributions. 
For instance, the following plot is showing the number of impressions a cookie saw before completing a conversion event. There are no cookies exposed to 0 or negative values of impressions. However, the graph seems to suggest something different.

![Fig 1: Wrong left tail](http://s27.postimg.org/jw9fcfttf/Screen_Shot_2015_04_21_at_18_50_18.png)

This is the code I've used to produce the plot:
```
sns.kdeplot(frame.cnt, shade=True, cumulative=True, legend=False)
sns.axlabel(xlabel="Impressions per cookie", ylabel="% of conversions")
plt.title("Number of impressions seen by a buyer before the conversion event")
```

This is an example of the dataset:
![Fig 2: Dataset example](http://s17.postimg.org/amd3zxfqn/Screen_Shot_2015_04_21_at_19_36_30.png)

**Comment by mwaskom** [comment]
This is perfectly normal behavior. The KDE procedure doesn't know anything about what is or isn't an invalid value for your dataset. Each observation is represented as a gaussian, and then those kernels are summed and normalized, yielding nonzero density below and above your maximum values. You can set `cut=0` to not draw the density past the extremes, but note that the curve will still be *fit* as if the data are unbounded.
