### ISSUE TITLE
UserWarning: No labelled objects found.

### ISSUE THREAD

**Issue by Eh2406** [mwaskom/seaborn#527]
I tried to follow the example at
http://stanford.edu/~mwaskom/software/seaborn/examples/pair_grid_with_kde.html

however I get the error 

          >>> g.map_diag(sns.kdeplot, lw=3)
          C:\Python27\virtual\data\lib\site-packages\matplotlib-1.4.3-py2.7-    win32.egg\matplotlib\axes\_axes.py:475: UserWarning: No labelled objects found. Use label='...' kwarg     on individual plots.
            warnings.warn("No labelled objects found. "  

running win7 64bit with 2.7.8 and a virtualenv with 
numpy 1.9.2
matplotlib 1.4.3
pandas 0.16.0
seaborn 0.5.1

any help?

**Comment by mwaskom** [comment]
It's a benign warning — `kdeplot` wants to draw a legend, but it isn't getting any label data, so matplotlib fires a warning.
