### ISSUE TITLE
1,2,3 sigma contours 2-d kde-plot ? 

### ISSUE THREAD

**Issue by cbonnett** [mwaskom/seaborn#529]
Is there an easy way to show the 1,2,3 sigma in 2-d  kdeplot ?
or to know at what values  the levels are shown ?

**Comment by mwaskom** [comment]
Not sure what you mean.

**Comment by hbsmith** [comment]
He means where 1 sigma (68%) of the data falls, 2 sigma (95%) of the data falls, 3 sigma (99.7%) of the data falls away from wherever the mean of the data is. The contours need SOME kind of corresponding legend or meaningful way to interpret them quantitatively.

**Comment by cbonnett** [comment]
I never replied to this, but yes, i mean exactly what @hbsmith  wrote.
