### ISSUE TITLE
cluster on subset of columns?

### ISSUE THREAD

**Issue by dkoppstein** [mwaskom/seaborn#533]
I was wondering whether there is a way to compute a clustermap based on a subset of the DataFrame's columns, yet still graph the entire DataFrame? I guess there might be a way to do it manually using col_linkage, but it's not intuitive to me how to cluster manually.

**Comment by mwaskom** [comment]
I don't think so, but @olgabot would know better. I assume you mean cluster the rows by computing the similarity using only some of the columns?

**Comment by dkoppstein** [comment]
Yes, that's what I meant. No worries, not a big concern, I'll close.

**Comment by mwaskom** [comment]
It's not possible through the standard API but I guess you could do something like:

1) call `clustermap` with a reduced version of your matrix and `col_cluster=False`, which returns a `ClusterGrid` object, call it `cg`.
2) use the `cg.row_dendrogram.reordered_ind` to reorganize the full matrix
3) call `heatmap` with `ax=cg.ax_heatmap` to plot the reorganized full matrix next to the row dendrogram.

Untested and might require some more tweaking, but I think this could get you what you want.
