### ISSUE TITLE
matplotlib style file?

### ISSUE THREAD

**Issue by roger-** [mwaskom/seaborn#534]
Can style files be added to the repo so you can do:

```python
import matplotlib.pyplot as plt
plt.style.use('seaborn')
```

**Comment by mwaskom** [comment]
I think for that to work it would have to be added to matplotlib itself right? A few people have mentioned this so it might have actually happened already.

PS while "darkgrid" is the seaborn default it's definitely not only seaborn style.

**Comment by roger-** [comment]
Yeah matplotlib recently added  [support for style files](http://matplotlib.org/users/style_sheets.html).

Would be great if darkgrid, et al could be used independently of seaborn.

**Comment by mwaskom** [comment]
I understand.

I am saying that to just say `plt.style.use('seaborn')` requires adding a file to *matplotlib*.

**Comment by roger-** [comment]
You can specify a local file or even a URL, unless you mean the seaborn style requires changes to matplotlib?

**Comment by mwaskom** [comment]
Sure, but it does not seem very convenient to have to do `plt.style.use(<long url>)`.

**Comment by roger-** [comment]
Maybe, but some people might prefer it over installing seaborn  if they only want the style :)

**Comment by petebachant** [comment]
@roger-, you could look at all the rc parameters seaborn changes and put them into a `seaborn.mplstyle` file. I just started working on a [collection of matplotlib stylesheets](https://github.com/petebachant/mplstyles) that would be copied into a user's matplotlib config directory, and would be accessible by the method you describe.

**Comment by mwaskom** [comment]
Yep that sounds like a better solution.

**Comment by roger-** [comment]
@petebachant

That works, but my intention was just to have the style somewhere other people could easily get it.
