### ISSUE TITLE
Using markers and hue to plot 2 different dimensions

### ISSUE THREAD

**Issue by MadDataScience** [mwaskom/seaborn#535]
It looks like the only way to have a data-aware grid change the marker style is to have it change with the hue (such as the following example from the [tutorial](http://stanford.edu/~mwaskom/software/seaborn/tutorial/axis_grids.html)): 
```python
g = sns.FacetGrid(tips, hue="sex", palette="Set1", size=5, hue_kws={"marker": ["^", "v"]})
g.map(plt.scatter, "total_bill", "tip", s=100, linewidth=.5, edgecolor="white")
g.add_legend();
```
What if I want to use hue to represent one dimension and markers to represent a different dimension? Something like:
```
colors = {1: 'red', 2: 'green', 3: 'blue'}
markers = ['d', '^']
for m in salary.M.unique():
    for e in salary.E.unique():
        df = salary[(salary.M == m) & (salary.E == e)]
        plt.scatter(df.X, df.S, s=50, c = colors[e], marker=markers[m])
```
only in a more data-aware fashion? Is that possible? If not, can it be made possible?

**Comment by mwaskom** [comment]
Nope, sorry, not possible.
