### ISSUE TITLE
boxplot overwrites user-provided flierprops and sym kwargs

### ISSUE THREAD

**Issue by cgevans** [mwaskom/seaborn#536]
If a call to boxplot has kwargs with `flierprops` or `sym` in it, boxplot ignores these and overwrites them. This prevents the modification of flier styles: see [here](http://stackoverflow.com/questions/29647145/setting-flier-outlier-style-in-seaborn-boxplot-is-ignored/30009353#30009353) for example.

It seems like a reasonable solution to this would be to only set sym if sym isn't already provided, and to set flierprops by updating the base dict in boxplot with the user-provided dict. This would be relatively easy to implement, and I can do so soon.

**Comment by mwaskom** [comment]
Yep, sure, that seems reasonable.

**Comment by mwaskom** [comment]
I vaguely remember there being some issue with `flierprops` being broken in matplotlib, but I think that might have been early in the 1.4 series and thus not too worrisome. But good to keep in mind.

**Comment by cgevans** [comment]
I believe that was the [annoying bug in 1.4.0](https://github.com/matplotlib/matplotlib/issues/3459/) that was fixed in 1.4.1.

**Comment by mwaskom** [comment]
Closed with #538
