### ISSUE TITLE
Invisible crosses

### ISSUE THREAD

**Issue by anntzer** [mwaskom/seaborn#540]
Crosses ("+" and "x" styles) become invisible when seaborn is loaded:
```
import matplotlib.pyplot as plt, seaborn
plt.plot([1, 2, 3], "+"); plt.show() # same with "x"
```
results in an empty axes.

**Comment by mwaskom** [comment]
Yep, this is a consequence of the seaborn style settings and how matplotlib draws certain markers. You'll need to set the `markeredgewidth` or `mew` parameter to a nonzero value.
