### ISSUE TITLE
Whiskers' convention on factorplot "box"

### ISSUE THREAD

**Issue by fbrundu** [mwaskom/seaborn#542]
Hi,
I am using the factorplot feature with `kind="box"`. May I ask you which is the convention used for drawing the whiskers? Because I get whiskers of different length and also outliers.
Maybe I misread but I could not find anything in the documentation.

Thanks

![fplot_1_10_nfkb](https://cloud.githubusercontent.com/assets/697622/7473787/e1373590-f33d-11e4-8356-7145d8319032.png)

**Comment by mwaskom** [comment]
The rule is that whiskers extend to points *n* * IQR past the lower or upper quartile, and then observations outside this range are marked as flyers (or outliers). *n* is controlled by the `whis` parameter, which is the same as in matplotlib and has a default of 1.5.

**Comment by fbrundu** [comment]
Maybe it is a dumb question but..
If the whiskers extend to 1.5*IQR past the lower or upper quartile, shouldn't the whiskers have the same length within each box (given that the IQR is one for each box)?
Thanks

**Comment by mwaskom** [comment]
No it's just a subtle distinction. They don't extend to 1.5 * IQR, they extend to *the farthest point that is within 1.5 * IQR*. Does that help?

**Comment by fbrundu** [comment]
Yes, thanks :)
