### ISSUE TITLE
Long axis titles causes `FacetGrid` xaxis to become narrow and eventually change direction

### ISSUE THREAD

**Issue by joelostblom** [mwaskom/seaborn#543]
Too many characters in the axis title causes some unexpected behavior for the xaxis of `FacetGrid`. It becomes progressively narrower and changes direction. See [this example notebook](http://nbviewer.ipython.org/github/joelostblom/test_ipynbs/blob/master/seaborn_long_titles.ipynb) for details.

Not sure how common it is too have this long axis titles, so might not be the highest priority to fix. Maybe there should be a warning at least that the axis title is to long an it might affect the plot's appearance?

**Comment by mwaskom** [comment]
I don't think this is specific to seaborn, I'm pretty sure you could reproduce the same behavior with a simple set of matplotlib subplots.

**Comment by joelostblom** [comment]
I added a matplotlib example above, it behaves slightly differently. The subplots are still close together, even if the entire figure is shrinking. The x-axes never change direction.

As I said before, I don't think this is especially important and it's easy for the user to to adjust. I was just confused initially when my plots changed direction on the axis and didn't immediately relate it to the title length.

**Comment by mwaskom** [comment]
Try calling `f.tight_layout()` on the matplotlib figures; I bet that is the culprit.

**Comment by joelostblom** [comment]
You're right, I reported it to the matplotlib issue tracker instead.
