### ISSUE TITLE
Incorrect ymax when passing `hist_kws={'histtype':'stepfilled'}` to `distplot` in a `FacetGrid` with the `hue`  parameter

### ISSUE THREAD

**Issue by joelostblom** [mwaskom/seaborn#544]
An example that cuts of the axis when passing `hist_kws={'histtype':'stepfilled'}`
```python
g = sns.FacetGrid(data=iris, hue='species', size = 3)
g.map(sns.distplot, 'petal_length', hist_kws={'histtype':'stepfilled'})
```
![image](https://cloud.githubusercontent.com/assets/4560057/7520877/f9b75e62-f4b7-11e4-9504-f8ec2e8e80b4.png)

Passing different `hist_kws` seem to work
```python
g = sns.FacetGrid(data=iris, hue='species', size = 3)
g.map(sns.distplot, 'petal_length', hist_kws={'linewidth':0})
```
![image](https://cloud.githubusercontent.com/assets/4560057/7520886/0d1ea26c-f4b8-11e4-81ca-92650c0049fa.png)

In the upper plot, it looks like ymax is set according to the red distribution. This seems to be specific to `FacetGrid`s using the `hue` parameter. I couldn't reproduce it without `hue` or with `distplot` directly (although I didn't test this extensively).

**Comment by joelostblom** [comment]
I tested a few additional examples, it seems to be related to the normalization of the histogram in combination with the `histtype` parameter.

```python
g = sns.FacetGrid(data=iris, hue='species', size = 3)
g.map(sns.distplot, 'petal_length', kde=False, hist_kws={'histtype':'stepfilled'})
```
![image](https://cloud.githubusercontent.com/assets/4560057/7521134/7d917154-f4b9-11e4-8045-9a43f0f9475e.png)

```python
g = sns.FacetGrid(data=iris, hue='species', size = 3)
g.map(sns.distplot, 'petal_length', kde=False, norm_hist=True, hist_kws={'histtype':'stepfilled'})
```
![image](https://cloud.githubusercontent.com/assets/4560057/7521140/8f28bd46-f4b9-11e4-864a-ed2d0203cd89.png)

```python
g = sns.FacetGrid(data=iris, hue='species', size = 3)
g.map(sns.distplot, 'petal_length', kde=False, norm_hist=True, hist_kws={'linewidth':0})
```
![image](https://cloud.githubusercontent.com/assets/4560057/7521148/a3c74402-f4b9-11e4-998d-e88821ac3b1a.png)

**Comment by mwaskom** [comment]
Is this `FacetGrid` specific or does it happen when using `distplot` directly?

**Comment by joelostblom** [comment]
I couldn't reproduce it without `hue` or with `distplot` directly (although I didn't test this extensively).

I think the reason for this behavior is that `ymax` seems to be calculated for the last species distribution in alphabetic order rather than the distribution with the highest `ymax`. I did some quick testing that supports this.
```python
g = sns.FacetGrid(data=iris, hue='species', size = 3)
g.map(sns.distplot, 'petal_length', hist_kws={'histtype':'stepfilled'})
g.add_legend()
```
![image](https://cloud.githubusercontent.com/assets/4560057/7523481/0d8e6022-f4ca-11e4-9c7c-f614f6aec990.png)

Changing the species 'setosa' to 'wsetosa' sets the ymax in respect to this distribution instead.
```python
iris.loc[iris.species == 'setosa', 'species'] = 'wsetosa'
g = sns.FacetGrid(data=iris, hue='species', size = 3)
g.map(sns.distplot, 'petal_length', hist_kws={'histtype':'stepfilled'})
g.add_legend()
```
![image](https://cloud.githubusercontent.com/assets/4560057/7523518/40cdf966-f4ca-11e4-9e88-b35bcf8c75af.png)

**Comment by mwaskom** [comment]
That is weird. However, it also is possible to reproduce without seaborn per se:

```python
df = sns.load_dataset("iris")
for species, species_df in df.groupby("species"):
    plt.hist(species_df["petal_length"].values, normed=True, histtype="stepfilled")
```
![hz8kpxqmv18naaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/315810/7524220/46d5ee14-f4b5-11e4-9390-37cce4b13976.png)


Sorry to make it seem like I'm responding to all of your issues by kicking you over to the matplotlib repo, but this at least doesn't seem to be about any scaling that `distplot` or `FacetGrid` are doing.

**Comment by mwaskom** [comment]
Also note the `FacetGrid.set` method which at least will make it easy to reset the y axis limits to something sensible after this happens.

**Comment by joelostblom** [comment]
No worries, for the last one they were already working on title wrapping so it was good that you pointed me in the right direction. I [filed an issue for this one](https://github.com/matplotlib/matplotlib/issues/4414) as well. I will try to make sure I test the corresponding matplotlib calls before reporting more issues here, thanks for responding quickly!

**Comment by mwaskom** [comment]
Great, and no worries, your reports have been clear and have made it easy to track down the issue.
