### ISSUE TITLE
'hex' jointplot with bin size selection

### ISSUE THREAD

**Issue by drapadubok** [mwaskom/seaborn#555]
I would like to add an option to change the method for estimating bin number / edge for histograms in jointplot. Currently I can see that it is done with _freedman_diaconis_bins function, but I would like to add something based on bayesian blocks conception: http://www.astroml.org/user_guide/density_estimation.html#bayesian-blocks-histograms-the-right-way

I can see that _freedman_diaconis_bins returns the number of bins, while bayesian_blocks function returns bin edges. I'm not sure how are the histograms constructed later in the seaborn, will it be complicated to implement this way of estimating bin edges?

**Comment by mwaskom** [comment]
You can always pass the number of bins you want down to the joint and marginal plotting functions with the `joint_kws` and `marginal_kws` dicts, or you can use `JointGrid` directly. `jointplot` is meant to be a quick and easy way to draw the plot.

**Comment by drapadubok** [comment]
Thank you, got it!
