### ISSUE TITLE
descrication warning about scipy.linalg.calc_lwork with scipy 0.15.1

### ISSUE THREAD

**Issue by kain88-de** [mwaskom/seaborn#556]
When I import seaborn I get the following deprecation warning.

```
/home/max/.local/lib/python2.7/site-packages/numpy/lib/utils.py:95: DeprecationWarning: `scipy.linalg.calc_lwork` is deprecated!

calc_lwork was an internal module in Scipy and has been removed.

Several functions in scipy.linalg.lapack have *_lwork variants
that perform the lwork calculation (from Scipy >= 0.15.0), or
allow passing in LWORK=-1 argument to perform the computation.


  warnings.warn(depdoc, DeprecationWarning)
```

Numpy-version: 1.9.2
Scipy-version: 0.15.1
seaborn-version: 0.5.1

**Comment by mwaskom** [comment]
Can you do

```python
import warnings
warnings.simplefilter("error")
```

And let me know where this is actually getting raised from?

**Comment by kain88-de** [comment]
funny thing when I do this the deprecation warning is not raised. But I found out the issue is realted to statsmodels. I can also trigger the warning with `import statsmodels.api` and it only happens if I load the [mdtraj](https://github.com/mdtraj/mdtraj) package first. I'll post the problem to the packages that are causing the error.
