### ISSUE TITLE
inner parameter for violinplot does not raise on invalid input

### ISSUE THREAD

**Issue by shoyer** [mwaskom/seaborn#558]
Instead, it simply ignores the parameter:
```
%matplotlib inline
import seaborn as sns
sns.set_style("whitegrid")
tips = sns.load_dataset("tips")
ax = sns.violinplot(x=tips["total_bill"], inner='foo')
```

It would make for a better user experience to raise `ValueError`.

I'm running Seaborn master.

**Comment by mwaskom** [comment]
Had to maintain *some* backwards compatibility :)
