### ISSUE TITLE
Documentation for Newbies

### ISSUE THREAD

**Issue by MinchinWeb** [mwaskom/seaborn#559]
Hi!

I'd heard of `seaborn` before, but it wasn't until today that I actually need to make a chart using Python. `seaborn` I thought would be a good option, so I read through the documentation, but couldn't quite figure out how to get started. Eventually I gave up, decided to start with `matplotlib`, and then eventually figured out that you use they two together. (I hadn't had the need to use either `seaborn` or `matplotlib` before today.) In the end, I got a nice graph, but I have the following suggestions:

 - in the documentation, make it (more) clear the `seaborn` builds on `matplotlib` rather than replaces it.
 - on the [Installing and getting started](https://web.stanford.edu/~mwaskom/software/seaborn-dev/installing.html) page, add a simple example that takes you as far as basic (line?) graph. This has the advantage of showing the various `import`s needed to get up and running, and would make the above item more obvious.
 - a link somewhere to a good `matplotlib` tutorial would be helpful

And why is seaborn imported as `sns`?

Thanks for doing your part to make more beautiful graphs!

**Comment by mwaskom** [comment]
Perhaps have you read the [introduction to seaborn](https://web.stanford.edu/~mwaskom/software/seaborn/introduction.html) page or looked at any of the many scripts in the [example gallery](https://web.stanford.edu/~mwaskom/software/seaborn/examples/index.html)?

**Comment by MinchinWeb** [comment]
I did look at both. I think I was thrown by this statement on the intro page:

> ...It is built on top of matplotlib...

which I took to mean it was a replacement for `matplotlib`. Perhaps the intro from [here](https://beta.oreilly.com/learning/data-visualization-with-seaborn) is a little more clear:

> Seaborn provides an API on top of matplotlib, which uses sane plot and color defaults and simple functions for common statistical plot types.

The example gallery is beautiful, but all more complicated than what I was after (a line graph). As well, of the two examples closest to what I was after ([1](https://web.stanford.edu/~mwaskom/software/seaborn/examples/anscombes_quartet.html) and [2](https://web.stanford.edu/~mwaskom/software/seaborn/examples/timeseries_from_dataframe.html)), neither touch `matplotlib`, so they we're giving me hints to look there.

**Comment by MinchinWeb** [comment]
If it would be helpful, I would be glad to offer my final product. If you want, I would be happy to put together a pull request. Here is my code:

```py
#   This generated the graph show the comparision between the RRO and our
#   floating rate.
#   This graph is displayed on https://www.burstenergy.ca/rates/floating/


def make_graph():
    import os
    from pathlib import Path

    import matplotlib.pyplot as plt
    import matplotlib.dates as mdates
    from pylab import savefig
    from datetime import datetime
    # for nicer colours, importing is enough
    import seaborn as sns

    Months = ['2014-11', '2014-12', '2015-01', '2015-02', '2015-03', '2015-04']

    RRO = [7.127, 7.545, 7.302, 6.583, 5.431, 5.832]

    Floating = [5.378, 4.049, 5.001, 4.831, 3.294, 3.282]

    """Convert *Months* to numbers"""
    for i in range(len(Months)):
        year, month = map(int, Months[i].split('-'))
        Months[i] = mdates.date2num(datetime(year, month, 1))

    """Now let's plot!"""
    # make the final image 800px wide
    fig = plt.figure(dpi=72, figsize=(800/72/1.19, (800*1/2)/72/1.19))
    graph = fig.add_subplot(111)
    # Plot the two lines
    line1 = graph.plot(Months, RRO, sns.xkcd_rgb["pale red"], label="RRO")
    line2 = graph.plot(Months, Floating, sns.xkcd_rgb["medium green"], label="Burst Energy")
    # x axis -- list the months on the 1st
    graph.set_xticks(Months)
    graph.set_xticklabels([mdates.num2date(date).strftime("%b '%y") for date in Months])
    # y axis -- min is 0, label
    plt.ylim(ymin=0)
    plt.ylabel("\u00A2 / kWh, for Edmonton")
    # add legend in default location (upper right)
    graph.legend()

    # current file location (this script file)
    p = Path(os.path.realpath(__file__))
    # drop script file name
    p = p.parents[0]
    # location of where we want to save the graph
    p = p / "images" / "floating-rate-vs-rro.png"

    savefig(str(p), bbox_inches='tight')
    # plt.show()

if __name__ == "__main__":
    make_graph()
```

And the resulting graph:

![floating-rate-vs-rro](https://cloud.githubusercontent.com/assets/1548809/7603403/c733beb8-f8ef-11e4-948a-d9097ff95cd3.png)
