### ISSUE TITLE
Importing future division under python 3 (!?) changes colors

### ISSUE THREAD

**Issue by tritemio** [mwaskom/seaborn#565]
In a notebook with python 3 kernel, the following code:

```
from __future__ import division
import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

a = np.random.rand(10)
b = np.random.rand(10) + 0.5
d = pd.DataFrame(dict(a=a, b=b))
sns.violinplot(d)
```
produces:

![image](https://cloud.githubusercontent.com/assets/4156237/7664937/0066db8a-fb56-11e4-8ce3-f08dda2ffb99.png)

note the edges with wrong colors.

The funny thing is that removing the future import (that should not have any effect on python 3) results in correct colors.

Under python 2.7, the plot is correct with or without the future division import.

Sorry if it's not a seaborn issue, but it bites seaborn too.

System info: windows 7 64x with anaconda.

**Comment by mwaskom** [comment]
Ah this just popped up in #564, though Python 3 and `from __future__ import division` didn't appear to be an issue there. Did you try this multiple times? In #564 it sounds like it was pretty random, so the association here might be an artifact. Or, it could be a clue.

I still suspect that this has to do with the root matplotlib issue in #519

**Comment by tritemio** [comment]
You are right, the future division import was only a coincidence.

Anyway I've been using seaborn 0.5.1 and matplotlib 1.4.3 with python2 for a several months and never had the problem. But on python 3 the issue shows up quite often (~50% of times or more).

As mentioned in the other issues it can be something related to a non-deterministic dictionary ordering.

BTW: I reproduced this issue under linux too.

**Comment by mwaskom** [comment]
Well, as I mention in #564, if this is a bug in the seaborn `violinplot` code, that code is completely different now so it should disappear when 0.6 goes out.

In the meantime as a workaround I think you could do something like `plt.setp(ax.lines, color=".3")`.
