### ISSUE TITLE
distplot crashes when called on a constant vector

### ISSUE THREAD

**Issue by endisway** [mwaskom/seaborn#567]
Test case:
```python
>>> import seaborn
>>> a = [10, 10, 10, 10]
>>> seaborn.distplot(a)

  File "C:\Anaconda\lib\site-packages\numpy\core\function_base.py", line 84, in linspace
    num = int(num)
ValueError: cannot convert float NaN to integer
```

This happens because `iqr(a) == 0` (which is accurate), and `_freedman_diaconis_bins(a)` divides by `iqr(a)`, which, since it happens between numpy objects, does not raise `ZeroDivisionError` immediately but returns `np.NaN` as the number of bins for the distribution plot. 
How to fix it? For a constant vector of x, I think you should draw at least three bins, depicting [not x, x, not x]. But this is just my opinion. However, the constant vector case should definitely be handled and not cause a crash.

**Comment by mwaskom** [comment]
> For a constant vector of x, I think you should draw at least three bins, depicting [not x, x, not x].

Wouldn't that cover the entire domain of real numbers?

In any case this has already been addressed in the development version.

**Comment by endisway** [comment]
you're right... i did not mean literally! i meant providing at least one additional empty bin below the constant and one above, in order to make the plot look like a single bar instead of a completely filled screen :)
also, i'm sorry for not checking the online source before reporting. Thanks for the fix.
