### ISSUE TITLE
despine() does not remove minor ticks

### ISSUE THREAD

**Issue by c-wilson** [mwaskom/seaborn#568]
Using the sns.despine function with an axis with minor ticks does not remove these minor ticks on the left spine. This is really only an issue (in my experience) when working with axes in log scale. I can fix and submit pull request if desired. So

**Comment by phobson** [comment]
Current behavior seems correct and consistent to me:

```python
fig, ax = plt.subplots()
ax.set_yscale('log')
ax.set_xscale('log')
sns.despine(ax=ax)
```
![download](https://cloud.githubusercontent.com/assets/1163939/7825212/e3dca532-03be-11e5-8a2f-c542474230fe.png)

```python
fig, ax = plt.subplots()
ax.set_xticks(np.arange(0, 1, 0.05), minor=True)
sns.despine(ax=ax)
```
![download](https://cloud.githubusercontent.com/assets/1163939/7825226/3552f830-03bf-11e5-8dae-15d6df29df0a.png)

**Comment by c-wilson** [comment]
Sorry it took so long to get back to you on this. My issue was with the bottom and left axes. 


fig, ax = plt.subplots()
ax.plot([1e-2, 1e3])
sns.set_style('ticks')
ax.set_yscale('log')
ax.set_yticks([])
ax.set_xticks([])
sns.despine(ax=ax, bottom=True, left=True)

![unknown](https://cloud.githubusercontent.com/assets/5377850/7825917/ac4f19f2-03e0-11e5-8000-39a7fa694c12.png)

**Comment by phobson** [comment]
The error is that you're not removing the minor ticks -- that's something you have to do yourself (`ax.set_yticks([], minor=True)`). As you see, `seaborn.despine` never removes ticks:

```python
fig, ax = plt.subplots()
ax.set_xticks(np.arange(0, 1, 0.05), minor=True)
sns.despine(ax=ax, bottom=True)
```

![download](https://cloud.githubusercontent.com/assets/1163939/7825956/11681708-03c8-11e5-939a-59b7c60166d6.png)

**Comment by c-wilson** [comment]
Ah, I see. And linear scales don't have automatically generated minor ticks. Got it. Thanks
