### ISSUE TITLE
sns.PairGrid.addlegend() raises max() arg is an empty sequence

### ISSUE THREAD

**Issue by scls19fr** [mwaskom/seaborn#570]
Hello,

This code

    import pandas as pd
    import matplotlib.pyplot as plt
    import seaborn as sns

    movie_user_preferences={'Jill': {'Avenger: Age of Ultron': 7.0,
      'Django Unchained': 6.5,
      'Gone Girl': 9.0,
      'Kill the Messenger': 8.0},
     'Julia': {'Avenger: Age of Ultron': 10.0,
      'Django Unchained': 6.0,
      'Gone Girl': 6.5,
      'Kill the Messenger': 6.0,
      'Zoolander': 6.5},
     'Max': {'Avenger: Age of Ultron': 7.0,
      'Django Unchained': 7.0,
      'Gone Girl': 10.0,
      'Horrible Bosses 2': 6.0,
      'Kill the Messenger': 5.0,
      'Zoolander': 10.0},
     'Robert': {'Avenger: Age of Ultron': 8.0,
      'Django Unchained': 7.0,
      'Horrible Bosses 2': 5.0,
      'Kill the Messenger': 9.0,
      'Zoolander': 9.0},
     'Sam': {'Avenger: Age of Ultron': 10.0,
      'Django Unchained': 7.5,
      'Gone Girl': 6.0,
      'Horrible Bosses 2': 3.0,
      'Kill the Messenger': 5.5,
      'Zoolander': 7.0},
     'Toby': {'Avenger: Age of Ultron': 8.5,
      'Django Unchained': 9.0,
      'Zoolander': 2.0},
     'William': {'Avenger: Age of Ultron': 6.0,
      'Django Unchained': 8.0,
      'Gone Girl': 7.0,
      'Horrible Bosses 2': 4.0,
      'Kill the Messenger': 6.5,
      'Zoolander': 4.0}}

    df_movie_user_preferences = pd.DataFrame(movie_user_preferences)
    df_movie_user_preferences.index.name = "Movie"
    df_movie_user_preferences.columns.name = "User"
    print df_movie_user_preferences

    df_ratings = df_movie_user_preferences.transpose().reset_index()
    df_ratings.columns.name = None

    g = sns.PairGrid(df_ratings, hue="User")
    g.map_diag(plt.hist)
    g.map_offdiag(plt.scatter)
    g.add_legend()
    plt.show()

prints

          User  Avenger: Age of Ultron  Django Unchained  Gone Girl  \
    0     Jill                     7.0               6.5        9.0
    1    Julia                    10.0               6.0        6.5
    2      Max                     7.0               7.0       10.0
    3   Robert                     8.0               7.0        NaN
    4      Sam                    10.0               7.5        6.0
    5     Toby                     8.5               9.0        NaN
    6  William                     6.0               8.0        7.0

       Horrible Bosses 2  Kill the Messenger  Zoolander
    0                NaN                 8.0        NaN
    1                NaN                 6.0        6.5
    2                  6                 5.0       10.0
    3                  5                 9.0        9.0
    4                  3                 5.5        7.0
    5                NaN                 NaN        2.0
    6                  4                 6.5        4.0

but raises `max() arg is an empty sequence`

so I can't see legend

Any idea ?

Kind regards

**Comment by mwaskom** [comment]
Seems related to how `plt.scatter` handles empty arrays. It seems to work for me with `plt.plot`

```python
g = sns.PairGrid(df_ratings, hue="User")
g.map_offdiag(plt.plot, marker="o", ls="", markersize=12)
g.map_diag(plt.hist)
g.add_legend()
```

**Comment by scls19fr** [comment]
So it's more a Matplotlib issue ?

**Comment by mwaskom** [comment]
I don't think it's that simple, because this works:

```python
points = plt.scatter([], [])
plt.figlegend([points], "label", "center right")
```

There is some magic in `PairGrid` to get the legend to properly correspond with data that might be distributed across the axes. But it doesn't just generically fail on data with missing hue levels (or it won't after I push an unrelated fix to the master branch). Using an example from the tests:

```python
rs = np.random.RandomState(sum(map(ord, "PairGrid")))
df = pd.DataFrame(dict(x=rs.normal(size=80),
                       y=rs.randint(0, 4, size=(80)),
                       z=rs.gamma(3, size=80),
                       a=np.repeat(list("abcd"), 20))

g = sns.PairGrid(df, hue="a", hue_order=list("abcde"))
g.map(plt.scatter)
g.add_legend()
```

So it's some strange interaction with your particular data. I looked into it and didn't see anything obvious, but it sounds like it works fine to just use `plt.plot`.

**Comment by mwaskom** [comment]
Closing as this seems to run on matplotlib 1.5.
