### ISSUE TITLE
typos in seaborn.kdeplot doc

### ISSUE THREAD

**Issue by JasonTam** [mwaskom/seaborn#573]
http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.kdeplot.html?highlight=optoinal
`legend : bool, optoinal` --> optional

also (under cumulative : bool), 

`If draw, draw the cumulative distribution estimated by the kde.` --> If True

and for consistency's sake (under shade : bool, optional),
`If true` --> If True

**Comment by mwaskom** [comment]
thanks...

**Comment by JasonTam** [comment]
I hate to be that guy... 
but in 1b424869311c79a57de7141d73fc44d2dc1f343f `optinal` is still a typo haha.

**Comment by mwaskom** [comment]
....
