### ISSUE TITLE
clustermap row_colors does not appear to work with vmax

### ISSUE THREAD

**Issue by tavinathanson** [mwaskom/seaborn#574]
Hello,

I just ran into an issue with `vmax` + `row_colors` in `clustermap`. See the following:

With:

```
import pandas as pd
import seaborn as sb
flights = sb.load_dataset("flights")
flights_rect = flights.pivot("month", "year", "passengers")
green = sb.color_palette('Greens', n_colors=3)[1]
red = sb.color_palette('Reds', n_colors=3)[1]
sb.clustermap(flights_rect, vmax=300, row_colors=[green, red] * 6)
```

I get:

![image](https://cloud.githubusercontent.com/assets/322932/7824039/f55587ac-03cd-11e5-8d58-48a9eb5a0518.png)

However, if I remove `vmax`:

```
sb.clustermap(flights_rect, row_colors=[green, red] * 6)
```

I get:

![image](https://cloud.githubusercontent.com/assets/322932/7824053/0c0cf0e8-03ce-11e5-99aa-e6c0fe9ee810.png)

**Comment by mwaskom** [comment]
What version of seaborn?

**Comment by mwaskom** [comment]
If this is on the stable version, it sounds like  #415

**Comment by tavinathanson** [comment]
Ah, yes, it's `0.5.1`: looks like #415 is it!

**Comment by mwaskom** [comment]
Great, then that's already fixed.

Make sure to check out the [release notes](http://stanford.edu/~mwaskom/software/seaborn-dev/whatsnew.html) if you plan on switching to the dev version, as there have been some changes to the API.
