### ISSUE TITLE
coefplot with many/long variable names - vertical plot? vertical labels?

### ISSUE THREAD

**Issue by jona-sassenhagen** [mwaskom/seaborn#576]
When using coefplot with many variables and/or long variable names, x axis labels begin to overlap. Possible solutions:
* option for a vertical plot
* option for vertical labels

I think the first option would be preferable IMO. I could even see myself attempting to do it, although I'm pretty bad at matplotlib.

**Comment by mwaskom** [comment]
If you want vertical labels just do this after plotting

```python
ax = plt.gca()
plt.setp(ax.get_xticklabels(), rotation=90)
```
