### ISSUE TITLE
Clustermap returned values

### ISSUE THREAD

**Issue by alvinwt** [mwaskom/seaborn#581]
Hi, 

I am trying to retrieve the index of samples after clustering using a the clustermap function. Can the order of the rows be obtained after clustering? If not, this would be a useful feature to have, especially when carrying out analysis after clustering.

**Comment by mwaskom** [comment]
Yep, from the API docs:

To access the reordered row indices, use: ``clustergrid.dendrogram_row.reordered_ind``
To access the reordered column indices, use:  ``clustergrid.dendrogram_col.reordered_ind``
