### ISSUE TITLE
Colorbar in FacetGrid

### ISSUE THREAD

**Issue by demianw** [mwaskom/seaborn#582]
Hi! I've used the great FacetGrid class to plot a series of 2D plots (e.g. contourf). 
However, I have not found a way to activate the colorbars such as those existing in matplotlib's AxesGrid toolkit (http://matplotlib.org/mpl_toolkits/axes_grid/users/overview.html).

Is there a way to do this that I'm missing, do you have a recommendation? 

Thanks!

**Comment by mwaskom** [comment]
Can you show an example of how you're using `FacetGird` for this? It's not straightforward to begin with so that would be helpful.

**Comment by demianw** [comment]
Here you have an example. I could probably do a pull request to add a map_<something> method that extends the FacetGrid functionality (I will let you pick the right <something> to put in)

```python
import numpy as np
import pandas
import seaborn as sns

x, y = np.meshgrid(np.linspace(0, 100), np.linspace(0, 100))

df = pandas.DataFrame(dict(
       x=r_[x.ravel(), x.ravel()],
       y=r_[y.ravel(), y.ravel()],
       s=r_[
           np.ones_like(x.ravel()),
           np.ones_like(x.ravel()) * 10
       ]
))

df['value'] = (
   df.x *
   exp(-((df.x - df.y) ** 2 / df.s ** 2))
)

g = sns.FacetGrid(df, col='s')

def data_frame_to_matrix(fn):
   def dummy(*args, **kwargs):
       data_ = kwargs['data']
       kwargs_ = kwargs.copy()
       del kwargs_['data']
       del kwargs_['color']
       data_ = data_.pivot(args[1], args[0])[args[2]]
       X, Y = meshgrid(data_.columns, data_.index)
       return fn(X, Y, data_, *args[3:], **kwargs_)
   return dummy

g.map_dataframe(
   data_frame_to_matrix(contourf),
   'x', 'y', 'value', 5,
)
'''

**Comment by mwaskom** [comment]
Interestingly, just putting `plt.colorbar` at the end of your code actually does a nice job: (I also added `vmin` and `vmax` in `map` to ensure that the colorbar limits are valid for all facets:

![a18oxuceaoutaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/315810/8133445/3c3affc8-10dd-11e5-8153-78e1fd8b1478.png)

Though I doubt this will generally work for all functions that could use a colorbar.

I wonder why `fig._gci()` is a private method; that's what `plt.colorbar` is using to find the most sensible thing to draw a colorbar for, and it would be useful for seaborn to take advantage of, but it's private.

**Comment by mwaskom** [comment]
See also https://github.com/matplotlib/matplotlib/issues/4517

**Comment by mwaskom** [comment]
Unfortunately I've gotten a *completely* unhelpful response from matplotlib core (no surprise there) so it doesn't look like this is going to go anywhere...

**Comment by demianw** [comment]
Thanks! What I wanted was one colorbar per grid plot that's why the plt.colorbar was not a feasible solution. Sorry if I didn't express this well. Probably mimicking some of the work on matplotlib axesgrid. But I don't know how compatible this is with your gridding method and it might be better strategy to wrap their axesgrid with some code that generates the grid using data frame info

--
Demian Wassermann, PhD
demian.wassermann@inria.fr
Research Scientist
Athena Project Team
INRIA Sophia Antipolis - Méditerranée
2004 route des lucioles - FR-06902

**Comment by mwaskom** [comment]
Oh, that's actually somewhat easier. Here's what I would do:

```python
g = sns.FacetGrid(df, col='s')

def contourplot(*args, **kwargs):

    data = kwargs.pop("data").pivot(args[1], args[0])[args[2]]
    X, Y = np.meshgrid(data.columns, data.index)
    ax = plt.gca()
    mappable = ax.contourf(X, Y, data, *args[3:], **kwargs)
    ax.figure.colorbar(mappable)

g.map_dataframe(contourplot, 'x', 'y', 'value', 5)
```
![znwmegosjcaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/315810/8134610/63f4df18-10e5-11e5-9c9c-90f7807adeb7.png)

**Comment by demianw** [comment]
Great! It was the ax.figure bit that I was missing! Thanks 

--
Demian Wassermann, PhD
demian.wassermann@inria.fr
Research Scientist
Athena Project Team
INRIA Sophia Antipolis - Méditerranée
2004 route des lucioles - FR-06902

**Comment by mwaskom** [comment]
Glad it works!
