### ISSUE TITLE
Row margin title bad formatting

### ISSUE THREAD

**Issue by yoavram** [mwaskom/seaborn#586]
When calling `g.set_titles(row_template='{row_name'})` the titles are not formatted well and look bad.
See this [notebook](http://nbviewer.ipython.org/gist/yoavram/745367fa6d25f5ad7f9e) for an example.

Python 2.7, seaborn 0.5.1, matplotlib 1.4.3

**Comment by mwaskom** [comment]
This is basically the same issue as https://github.com/mwaskom/seaborn/issues/509, unfortunately there's not a whole lot that can be done about it in seaborn itself.

**Comment by yoavram** [comment]
Would the same hack work here? Or another hack?

**Comment by mwaskom** [comment]
Yep
