### ISSUE TITLE
distplot being very slow

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [mwaskom/seaborn#587]
I noticed that sometimes, depending on the data, KDE fitting takes a quite a bit to run (~ 3 minutes per plot). Are there any options that could limit, perhaps, the number of iterations, or still alternatively simplify the fitting process at the expense of accuracy?

**Comment by mwaskom** [comment]
Do you have statsmodels installed? I think if you do seaborn will use its FFT-based algorithm, which should be faster. Otherwise not really, although you could randomly subsample your own data.

**Comment by amelio-vazquez-reina** [comment]
Thank you @mwaskom. I have `statsmodels` installed, and I am actually noticing that distplot takes a long time even with `rug=False`, `kde=False`, and `norm_hist=False`. No idea what's to blame. 

* Here is [pip freeze](https://gist.github.com/amelio-vazquez-reina/6ff44ff941e7a1c526a7)
* Here is [the array](https://gist.github.com/amelio-vazquez-reina/bb05cbc8f7ddaf8fc9b0)
* And below is the code:
```
  f, ax = plt.subplots(figsize=(6,6))
  sns.distplot(change_df.dropna(subset=['diff'])['diff'].values, rug=False, kde=False, norm_hist=False)
```

**Comment by mwaskom** [comment]
If you have a huge dataset, it may just be drawing a large number of bins. In that case the delay is probably just matplotlib drawing all the bars.




It's probably not that useful to draw more than ~50 bins anyway, and in 0.6.dev the automatic calculation is capped at that value to avoid this. 



—

**Comment by amelio-vazquez-reina** [comment]
Totally correct. Thank you @mwaskom Should have thought about that!
