### ISSUE TITLE
vmax in clustermap messing up col_colors and row_colors

### ISSUE THREAD

**Issue by michael-imbeault** [mwaskom/seaborn#588]
For some reason in clustermap, when you set up vmax (and maybe vmin?), the colors that were set for col_colors and row_colors get completely wrong.

In my case I was calling vmax=100, the actual palette chosen for the col_ and row_ colors didn`t matter, but I did notice that the larger the value of vmax, the worse was the effect.

**Comment by mwaskom** [comment]
Hi, thanks for reporting -- this has already been fixed (in #415).
