### ISSUE TITLE
clustermap - easy option to change colorbar location?

### ISSUE THREAD

**Issue by michael-imbeault** [mwaskom/seaborn#589]
With very large clustermap (and figsize), the colorbar in the corner gets so tiny it is completely useless as a visual aide - it would be nice if you could say colorbar='location' (right, left, top, bottom) to put it in the more standard full scale on a side of the plot.

**Comment by mwaskom** [comment]
No easy way to do it at present. Some work in #441 but that stalled out — it is tricky because there are textual labels over there too and it is hard to predict how large they will be.

**Comment by iromeo** [comment]
+1 by default colorbar may look awful for large clustermap plots

**Comment by soumitrakp** [comment]
+1

**Comment by YubinXie** [comment]
it would be great to have the option to move colorbar in different position!

**Comment by mcolic** [comment]
Yes to having a kws 'location' for cbar in clustermaps!

**Comment by LIZW2019** [comment]
There seems to have a parameter in clustermap function but it works badly.  I don't know whether I have used it in a proper way.

> **cbar_pos**  tuple of (left, bottom, width, height), optional
> Position of the colorbar axes in the figure. Setting to None will disable the colorbar.

I just create a new colorbar based on no map to deal with this problem. 

first, remove the colorbar by setting cbar_pos = None.

and creat a colorbar like this:

`#setting the scale`
`cbnorm = Normalize(vmin=0-0.5,vmax=5+0.5,clip=False) #setting the scale` 
`cb = plt.colorbar(cm.ScalarMappable(norm=cbnorm, cmap=newcmp),fraction=1,ax=ax_color,ticks=np.arange(6))`
