### ISSUE TITLE
timeseries.py throws UnboundLocalError

### ISSUE THREAD

**Issue by nbehnam** [mwaskom/seaborn#590]
UnboundLocalError                         Traceback (most recent call last)
    <ipython-input-38-755cdb0a75e5> in <module>()
        1 instance = 'i-f7296608'
        2 instance_data = pandas.DataFrame(df2[df2.instance == instance])
    ----> 3 sns.tsplot(data=instance_data, time='orig_time', value='offset', interpolate=False, err_style=None)

     /.virtualenv/lib/python2.7/site-packages/seaborn/timeseries.pyc in tsplot(data, time, unit, condition, value, err_style, ci, interpolate, color, estimator, n_boot, err_palette, err_kws, legend, ax, **kwargs)
        253 
        254     # Pad the sides of the plot only when not interpolating
    --> 255     ax.set_xlim(x.min(), x.max())
        256     x_diff = x[1] - x[0]
        257     if not interpolate:

    UnboundLocalError: local variable 'x' referenced before assignment

**Comment by mwaskom** [comment]
This isn't a helpful bug report....

**Comment by jonathanng** [comment]
I'm getting the same error. I'm entering a simple df.

                                  Strategy  S&P 500
        2015-03-02 16:30:00-05:00 100.0000 100.0000
        2015-03-03 16:30:00-05:00  99.9753  99.4835
        2015-03-04 16:30:00-05:00  99.8790  99.1052
        2015-03-05 16:30:00-05:00  99.9543  99.2734
        2015-03-06 16:30:00-05:00  99.7182  97.9466
        2015-03-09 16:30:00-04:00  99.7883  98.2039

        sns.tsplot(data=df)
