### ISSUE TITLE
Removing yaxis gridlines

### ISSUE THREAD

**Issue by drapadubok** [mwaskom/seaborn#591]
Hi,
I'm trying to draw gridlines with custom parameters, for example:

ax = sns.tsplot(biopacdf, time="timevec", unit="subject", value="valence", ci=95)
ax1.set_xticks(np.arange(0,1015,29)) # I want to have xaxis gridlines to appear in prespecified intervals
plt.grid(True, color='w', linestyle='-', linewidth=2)

Then I get both horizontal and vertical gridlines, and I'd like to get rid of horizontal ones.

I try:
ax1.yaxis.grid(False)
plt.show()
But nothing changes.

I think my question has quite a simple answer, but I couldn't find a way that would have worked for me.
Thank you in advance for suggestions!

**Comment by mwaskom** [comment]
Not sure, sorry; that code works perfectly fine for me.

**Comment by drapadubok** [comment]
Alright, I'm not sure what is the mechanism, but after I minimized the figure and restored it - the horizontal lines disappeared. Should have tried saving the figure to make sure it really didn't work.
Thank you, issue resolved!
