### ISSUE TITLE
Unsupport Unicode Characters?

### ISSUE THREAD

**Issue by StonerYan** [mwaskom/seaborn#592]
Before I comment the seaborn import, the unicode characters display ok. When I import the seaborn, the unicode characters show boxes.
Before import seaborn:
![figure_1](https://cloud.githubusercontent.com/assets/11803097/8059480/c92c3e5c-0ef2-11e5-9be5-6d6d2606856f.png)
After import seaborn:
![figure_1](https://cloud.githubusercontent.com/assets/11803097/8059498/e051505e-0ef2-11e5-947d-f26c2db6c617.jpeg)

Source code:

#coding: utf-8

import matplotlib.pyplot as plt
import numpy as np
#import seaborn as sns

x = np.linspace(-1,1,10)
y = x**2
fig = plt.figure(figsize=(8,4))
ax = plt.subplot(111)
plt.plot(x,y)
for i, (_x, _y) in enumerate(zip(x, y)):
  plt.text(_x, _y, str(i), color="red", fontsize=i+10) #{1}
plt.text(0.5, 0.8, u"子图坐标系中的文字", color="blue", ha="center", transform=ax.transAxes) #{2}
plt.figtext(0.1, 0.92, u"图表坐标系中的文字", color="green") #{3}

plt.show()

**Comment by mwaskom** [comment]
Sot sure, sorry. seaborn changes the default font that is used, maybe that's it?

**Comment by staticor** [comment]
Why i both got the square case ( 2nd plot)... 

I am stuck into the Chinese Characters plot. Though I have some half-methods to figure it out.

**Comment by kongscn** [comment]
@mwaskom I met this issue too and the reason is, as you pointed out, that seaborn override default fonts specified in matplotlibrc configs. I wonder if this is a good practice, because font is not purely a aesthetic setting, as one font may not be able to display some specific unicode characters. Also it may be nice to provide a config file for saving a willing style, like matplotlibrc do, which will not be override at runtime.

**Comment by dofine** [comment]
Same problem here...

**Comment by viblo** [comment]
I also have this issue. (And the solution in #1009 doesnt work since Im on Python 3). I think it would be great if the default font supported Chinese character (and other languages as well).

**Comment by cqcn1991** [comment]
@viblo just post some code at https://github.com/mwaskom/seaborn/issues/1009
It works fine for me under Python 3 and Win 7.

**Comment by aloctavodia** [comment]
I have the same problem with the unicode Greek letter "epsilon" (and varepsilon).

**Comment by stepankuzmin** [comment]
Same problem with cyrillic

**Comment by mikkokotila** [comment]
It would be great to have some clarity on how to resolve this as supporting Unicode is kind of a "must have" in the world of computers ; ) @mwaskom any suggestions / need for help?
