### ISSUE TITLE
about boxplot(vert=False) ,the order of names. some mistakes in doc tutorial

### ISSUE THREAD

**Issue by staticor** [mwaskom/seaborn#593]
hi, I am new learner of seaborn. 
visualization distribution (http://web.stanford.edu/~mwaskom/software/seaborn/tutorial/plotting_distributions.html)

I used names = [up, down] to specify two groups, and found the order is from downside to upside.

by the way, the doc showed same name (names=[group1, group1]) , maybe a typo.

**Comment by mwaskom** [comment]
This has been changed in the current development version.
