### ISSUE TITLE
subplots issues: 

### ISSUE THREAD

**Issue by staticor** [mwaskom/seaborn#602]
I want to make subplots matrix
 
* subplot(xxx) 
* subplot2grid( (M,N), (r,c))

these two forms both work well, when I test these code:

```
styles = [ [None, 'white', 'whitegrid'], ['dark', 'darkgrid', 'ticks']]

fig = plt.figure(figsize=(16, 10))
       
for r in range(2):
    for c in range(3):
        ax = plt.subplot2grid((2, 3), (r, c))
        sns.set_style(styles[r][c])
        plt.xlabel(str(styles[r][c]))
        data = np.random.normal(size=(400, 6)) + np.arange(6) / 2
        sns.boxplot(data)


```

However, when I come close to the **lmplot**, and want to explore its hue parameter, I meet something stuck me in : 

```
cates = ['smoker',  'day'   ,'time']
axs = [0,0,0]
with plt.xkcd():
    for i in range(3):
        #plt.subplot(int('13'+str(i+1)))
        ax = plt.subplot2grid((3, 1), (i, 0))
        plt.xlabel('hue='+cates[i])
        sns.lmplot('total_bill', 'tip', data=tips, hue=cates[i])
```

If I replace sns.lmplot using plt.plot or other plotting, It worked well.

So what reasons lead to this somehow?

Thanks to bear my poor expressions, and I respect this work.

**Comment by mwaskom** [comment]
This [question and answer](http://stackoverflow.com/questions/23969619/plotting-with-seaborn-using-the-matplotlib-object-oriented-interface) on stackoverflow might help you out.

**Comment by staticor** [comment]
Thanks a lot,  sorry for my lack of *ST* work. 

It figures out.

**Comment by mwaskom** [comment]
No worries; a tricky issue and one that I'm working on better main docs for.
