### ISSUE TITLE
Boxplot colors appear a bit darker than in barplot

### ISSUE THREAD

**Issue by cachitas** [mwaskom/seaborn#604]
I have a custom legend and colors aren't matching well. 
Is there a workaround? Is this intended?

**Comment by cachitas** [comment]
Oh sorry, I completely missed this in the docs.

> saturation : float, 0-1
Saturation relative to the fully-saturated color. Large patches tend to look better at lower saturations, so this dims the palette colors a bit by default.

So I had to set it to 1. 
As a suggestion, it would be great if the docs included the default values used.

**Comment by mwaskom** [comment]
> As a suggestion, it would be great if the docs included the default values used.

In IPython help (and in the online API docs) the default values are in the function signature; it's considered good practice not to duplicate them in the parameters docs because that provides an opportunity for them to get out of sync, and wrong docs are worse than no docs.

**Comment by cachitas** [comment]
You are absolutely right. I need a break ;)
