### ISSUE TITLE
Ability to set kernels in Violinplot

### ISSUE THREAD

**Issue by wenhaosun** [mwaskom/seaborn#605]
Thank you Michael for the very beautiful Seaborn package. 

I use the ViolinPlots feature, and it would be nice to be able to change the Kernel type for the Violinplot. I do not believe this is possible at the moment, even in the developer version. 

It would also be nice if you could include an exponential Kernel, of the form: 

exp(-abs(x-C)^2 / bandwidth). 

(Table 1d in the following)
http://jmlr.csail.mit.edu/papers/volume2/genton01a/genton01a.pdf

These kernels are fairly successful at modeling heavily tail-distributed data, like as described in this particular problem:

http://stats.stackexchange.com/questions/65866/good-methods-for-density-plots-of-non-negative-variables-in-r?lq=1

**Comment by mwaskom** [comment]
Sorry for the delay. seaborn itself doesn't actually do any of the kernel density computation, that is handled by scipy (and sometimes statsmodels). So to get this kind of flexibility, it would have to be present in the underlying statistical libraries.
