### ISSUE TITLE
Bandwith option for lowess in seaborn.regplot

### ISSUE THREAD

**Issue by dhimmel** [mwaskom/seaborn#607]
Is there any way to set the bandwidth ([smoothing parameter](https://en.wikipedia.org/wiki/Local_regression#Localized_subsets_of_data)) that is used when `lowess=True`?

If not, consider this feature requested.

**Comment by mwaskom** [comment]
No, but there are plans for a more general `seaborn.lowessplot` function which will expose some more flexibility. The regplot interface is currently too busy to really add any.

**Comment by dhimmel** [comment]
Okay, great to know. I will close this issue.

**Comment by Phlya** [comment]
I recently had the same question, but concerning `seaborn.lineplot`, so was just wondering whether this is planned for that function?

**Comment by ck37** [comment]
Yeah, the bandwidth is too large for my data :(
