### ISSUE TITLE
factorplot with numerical x-data

### ISSUE THREAD

**Issue by chubukov** [mwaskom/seaborn#608]
It would be really useful to be able to use factorplot (with kind='point') and have numerical x data correctly plotted along the axis instead of just treating it as categorical. I don't see an easy way to do this currently. Any chance this a planned feature?

P.S. I love seaborn, it's excellent

**Comment by mwaskom** [comment]
I'm not sure what you mean by "correctly plotted", do you have an example of behavior you want to avoid?

**Comment by chubukov** [comment]
Sure, this is what I mean. Maybe I'm missing how to do it currently?

Current:
![image](https://cloud.githubusercontent.com/assets/13080968/8394255/31a2c79a-1ce4-11e5-8695-f26b70f9a880.png)

Desired:
![image](https://cloud.githubusercontent.com/assets/13080968/8394252/02bd038c-1ce4-11e5-835f-200489ab550a.png)

**Comment by mwaskom** [comment]
Ah I see.

`factorplot` is by design intended to work with categorical data. There are some tricks you could with the `order` parameter that could work, but those are a pain.

In general I would recommend making this kind of plot with `regplot`/`lmplot` using the `x_estimator` parameter. That won't give you the linear interpolation between points, which is easy enough to get with pandas plotting. But I also generally advise against linear interpolation when the x variable is quantitative anyway.

**Comment by chubukov** [comment]
Thanks Michael. `lmplot` isn't quite what I want either, because there's no reason to think the data is linear. But your reply made me dig a bit deeper into the implementation and I realized it's more straightforward than I thought to just make a `FacetGrid` and call `map_dataframe` with my own modified `pointplot` function. 

It does seem like this would be a common usage though (plot grouped numerical data without any fitting). If you don't like the idea of linear interpolation between points, then what about some spline fit just for visualization? (or maybe that's even worse in your mind?)

**Comment by mwaskom** [comment]
You can call `lmplot` with `fit_reg=False` and then it won't draw the linear fit. This will return a `FacetGrid` instance, which you can then map a function onto to connect the lines however you want. In general, I think the best approach is to show the data and then add the predictions from a model fit to the data (in your case some kind of exponential decay?), but outside of linear models it's hard to say what is best without knowing anything about the domain — knowing what kind of model to fit is often the whole point!

**Comment by chubukov** [comment]
I see what you're saying. My point was that just for visualization, a line of some sort can help draw attention to differences more sharply than just points. But you would fairly point out that if there's no underlying model, then who's to say that my bottom graph is any more quantitative than my top one. I don't have a good answer to that, other than that it intuitively feels like a better representation :)

Anyway thanks very much again for the tips.

**Comment by mwaskom** [comment]
You're completely right that a continuous plot element connecting the observations helps the visualization a lot. The question is just what it should represent. The linear interpolation implies a model that is piecewise linear between the points, which is probably not a correct model. But context matters, so maybe it's fine for your purposes. In that case, it's quite easy to add using `lmplot`:

```python
x = np.repeat([.1, .25, .5, 1, 2, 5, 10], 40)
g = np.tile(list("ab"), 140)
y = np.exp(-x) + np.random.randn(7 * 40) * .2 + (g == "b") * .2
df = pd.DataFrame(dict(x=x, y=y, g=g))

def connect_dots(x, y, color, **kws):
    y.groupby(x).mean().plot(color=color)

g = sns.lmplot(x="x", y="y", hue="g", data=df,
               x_estimator=np.mean, fit_reg=False, legend=False) 
g.map(connect_dots, "x", "y")
g.add_legend()
```

![b bq6zlnzpjeaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/315810/8397220/13a8ac88-1d79-11e5-8397-0c00a3725d13.png)

But I do think it's better, if you have a model that you're analyzing the data with, to try and use that model in the visualization. Here's a simple (and unrealistic, on the model-fitting side) example of what that would look like for the example dataset I generated:

```python
from scipy import optimize
def plot_fit(x, y, color, **kws):

    def fit(coefs):
        offset, = coefs
        return y - (np.exp(-x) + offset)

    fit_offset, _ = optimize.leastsq(fit, [0])
    xx = np.linspace(0, 10, 100)
    plt.plot(xx, np.exp(-xx) + fit_offset, color=color)

g = sns.lmplot(x="x", y="y", hue="g", data=df,
               x_estimator=np.mean, fit_reg=False, legend=False) 
g.map(plot_fit, "x", "y")
g.set(xlim=(-.5, 10.5))
g.add_legend()
```
![dw5yjhv3pib9aaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/315810/8397254/72e240aa-1d7a-11e5-8ed6-8fda39789314.png)

**Comment by chubukov** [comment]
Thanks. My code was a few lines longer -- yours is more elegant and I think it'll be helpful to have this example up. Completely agree with you on the rest.
