### ISSUE TITLE
kdeplot should account for prior proportions when drawing multiple densities

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#61]
Currently, if plotting separate densities for the levels of some factor, the distributions are not scaled by the prior proporition

**Comment by selous123** [comment]
did you means that?

![selection_021](https://user-images.githubusercontent.com/23351749/29852889-401924ba-8d6f-11e7-8439-e0ffc686a199.jpg)

with the mutli-graph,it can not display full.


any suggestion to solve it ??

**Comment by david-macleod** [comment]
I believe this issue is fixed here? https://github.com/mwaskom/seaborn/pull/1272

**Comment by mwaskom** [comment]
Nope

**Comment by mwaskom** [comment]
Closed in #2104 with the addition of `hue` and `common_norm` to `kdeplot`.
