### ISSUE TITLE
DOC: error aesthetics tutorial with color="deep"

### ISSUE THREAD

**Issue by jorisvandenbossche** [mwaskom/seaborn#616]
There is an error in the aesthetics tutorial: http://stanford.edu/~mwaskom/software/seaborn/tutorial/aesthetics.html#removing-spines-with-despine (third code block after that title)

``sns.boxplot(data=data, color="deep")`` gives `ValueError: to_rgb: Invalid rgb arg "deep"`

**Comment by jorisvandenbossche** [comment]
I suppose this has to be `palette="deep"` instead of `color=`?

**Comment by mwaskom** [comment]
Oops, yep, thanks.

**Comment by mwaskom** [comment]
Current tools for converting the ipynb source in the docs don't have a way to raise errors during the conversion but it looks like that it changing, fortunately: https://github.com/jupyter/nbconvert/pull/33
