### ISSUE TITLE
alpha does not work with violinplot

### ISSUE THREAD

**Issue by mgx2** [mwaskom/seaborn#622]
In seaborn 0.6.0, alpha parameter no longer works with violinplot. Used to work fine with 0.5.1

Example to duplicate:

import seaborn as sns
import matplotlib.pyplot as plt
fig = plt.figure()
sns.set_style("whitegrid")
tips = sns.load_dataset("tips")
ax = sns.violinplot(x=tips["total_bill"], alpha=0.1)
plt.show()

**Comment by mwaskom** [comment]
Yes, that parameter has been removed. Sorry if it didn't make it into the release notes.

**Comment by mgx2** [comment]
In my application, I'm plotting one violinplot over another to see the degree of overlap. Hence, it would be nice if the ability to control the opacity of the plot is restored.

**Comment by mwaskom** [comment]
You can always set the alpha on the PolyCollections objects that are attached to the axes object after plotting.

**Comment by mgx2** [comment]
I will try that and let you know! Thanks

**Comment by mgx2** [comment]
That worked. Thanks. Anyway, it could be added to the next sub-release?

**Comment by mpschr** [comment]
I'd like this argument as well - any reason why this was removed?

**Comment by Luk0r** [comment]
I also need this alpha parameter, or at least a code snippet how to set the alpha for the PolyCollections object (didn't find anything on the web)

**Comment by jfberrio** [comment]
Hello Michael, any chance you could show us a sample of code to change alpha after violinplots have been created using your method (making changes in PolyCollections)?
(p.s. it would be great if alpha is included back again in the arguments)
Thanks

**Comment by nilesh-patil** [comment]
Has anyone been successsful in doing this?
I am not able to figueout how to use PolyCollections with violinplot - and there's still no description in the documentation.

**Comment by niemasd** [comment]
Hi, I am also having trouble finding out how to access the PolyCollections object given the axes object. Would you be able to provide a snippet of example code?

**Comment by mwaskom** [comment]
`ax.collections`

**Comment by niemasd** [comment]
I ended up doing this:

```
def setAlpha(ax,a):
    for art in ax.get_children():
        if isinstance(art, PolyCollection):
            art.set_alpha(a)
```

**Comment by naught101** [comment]
you can just do
`plt.setp(ax.collections, alpha=.3)`

I'd also like to be able to set this from the violin call..

**Comment by JulianKlug** [comment]
Is there a way to change the alpha of juste de face color, without affecting the edges?
