### ISSUE TITLE
tsplot error

### ISSUE THREAD

**Issue by zhuzelong** [mwaskom/seaborn#625]
I have a pandas DataFrame where the first column `Date`  is `datetime.datetime` and the second column `Value` is a `int` metric. The date format is `yyyy-mm-dd`.

I tried to use tsplot to draw a time series plot:

```python
sns.tsplot(data=data, time='Date', value='Value')
```

But value error was raised: `ValueError: could not convert string to float: '2012-12-31'`. I could not see the reason why `tsplot` tries to convert the date to a float?

**Comment by mwaskom** [comment]
In general tsplot doesn't really work with dates but also it's not going to work with your dataset anyway for reasons explained in the docstring and elaborated on here: http://stackoverflow.com/questions/22795348/plotting-time-series-data-with-seaborn/22798911#22798911
