### ISSUE TITLE
Add number of observations and statistical testing in categorical plots?

### ISSUE THREAD

**Issue by Phlya** [mwaskom/seaborn#628]
I think an important feature in categorical plotting is missing - annotation of each category with the number of observations in it.
Another feature which would be desired by many users I think, is a possibility to perform statistical tests under the hood and label the significant differences automatically (e.g. with asterisks). I'm not a fan of this, but it's very popular to do so.

**Comment by mwaskom** [comment]
> I think an important feature in categorical plotting is missing - annotation of each category with the number of observations in it.

Not sure what you mean.

> Another feature which would be desired by many users I think, is a possibility to perform statistical tests under the hood and label the significant differences automatically (e.g. with asterisks). I'm not a fan of this, but it's very popular to do so.

There is essentially no chance that this will get added to seaborn.

**Comment by Phlya** [comment]
I mean this (although in different style, maybe just a number on top of each box/bar/etc): http://stackoverflow.com/questions/15720545/use-stat-summary-to-annotate-plot-with-number-of-observations
