### ISSUE TITLE
Roundoff error in kdeplot

### ISSUE THREAD

**Issue by zhuzelong** [mwaskom/seaborn#633]
I have a  pandas Series of length 950 and values among `[1, 2, 3]` (int). I tried to plot the CDF of the Series by:

```python
# x is the Series
sns.kdeplot(data=x, cumulative=True)
```

An error was raised: 
`The occurrence of roundoff error is detected, which prevents the requested tolerance from being achieved.  The error may be underestimated.`  
and no CDF curve was plotted.

If I turned off `cumulative`, the KDE curve was displayed. Another similar Series of the same values but of different length had no such problem.

I searched the error message on Google but could not figure out where the problem lied. Would anyone give me a hint to pinpoint the error?

**Comment by mwaskom** [comment]
Hm, all the computation is in statsmodels, so that might be a better place to ask. Though why are you fitting a gaussian KDE to a small set of discrete values? I wouldn't really expect that to work..
