### ISSUE TITLE
Add interact argument to FacetGrid?

### ISSUE THREAD

**Issue by shoyer** [mwaskom/seaborn#634]
The idea would be to add an optional keyword argument `interact` to `FacetGrid` (and possibly the related convenience functions) that would create an IPython interactive widget (the drop down) to allow for plotting subsets. This would be similar to the existing `row`, `col` and `hue` arguments.

Consider [this FacetGrid example from the Seaborn docs](http://stanford.edu/~mwaskom/software/seaborn/examples/faceted_histogram.html).
The following would a dropdown labeled `"sex"` with the two values `"Male"` and `"Female`" instead of faceting across rows:

```
g = sns.FacetGrid(tips, interact="sex", col="time", margin_titles=True)
```

We could even supply multiple arguments to `interact`, which would simply create stacked dropdowns:

```
g = sns.FacetGrid(tips, interact=["sex", "time"], margin_titles=True)
```

I think this could be a nice addition to facilitate interactive visualization. Thoughts?

**Comment by mwaskom** [comment]
Yeah I've thought about something similar, but I hadn't really thought of it as an argument to `FacetGrid`,  but a separate function. I think the IPython widget stuff is enough of a moving target that it's good to keep it somewhat segregated from the main codebase -- also I have yet to figure out how to test code that touches it. But the general idea seems cool.

**Comment by mwaskom** [comment]
Closing as out of scope.
