### ISSUE TITLE
Every point on x-label

### ISSUE THREAD

**Issue by MorrisCasper** [mwaskom/seaborn#636]
![figure_1](https://cloud.githubusercontent.com/assets/12054549/8570743/d8fa7bcc-2582-11e5-992f-dcef6f3171e8.png)
As you can see, the x-axis is flooded with every point from a data frame.
To reproduce:
Replace paste_here with http://pastebin.com/zdvCEEEu

    import matplotlib.pyplot as plt
    import seaborn as sns
    import pickle

    df = pickle.loads(paste_here)

    sns.pointplot("Date", "Value", data = df)
    plt.show()

**Comment by mwaskom** [comment]
What would you like to have happen?

**Comment by mbatchkarov** [comment]
I prefer to see only some of the labels, e.g. the first, last and every `n`-th inbetween. I often use this hack:

```python
def sparsify_axis_labels(ax, n=2):
    """
    Sparsify tick labels on the given matplotlib axis, keeping only those whose index is divisible by n
    """
    for idx, label in enumerate(ax.xaxis.get_ticklabels()):
        if idx % n != 0:
            label.set_visible(False)
```

**Comment by mwaskom** [comment]
Why are you not just doing df.plot(x="Date", y="Value")? That will handle this case better. Seaborn isn't adding anything here and a categorical plot isn't really the right tool for a dense timeseries anyway.

**Comment by mwaskom** [comment]
Alternatively just do `ax.set_xticks(ax.get_xticks()[::2])`

**Comment by MorrisCasper** [comment]
Thanks, using df.plot() now
