### ISSUE TITLE
scatter_kws marker issue

### ISSUE THREAD

**Issue by jmportilla** [mwaskom/seaborn#637]
####
Running this code:

import seaborn as sns
tips = sns.load_dataset("tips")

sns.lmplot("total_bill", "tip", tips, scatter_kws={"marker": "o", "color": "indianred"})

####

If you try to change the 'marker' argument with the scatter_kws dictionary, the marker doesn't change. In fact you can pass any string and the plot will still work and post marker 'o'. 

I'm not sure if this is an issue on seaborn side or matplotlib side?

**Comment by mwaskom** [comment]
`lmplot` takes a `markers` keyowrd argument directly.

**Comment by mwaskom** [comment]
See the third example here http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.lmplot.html

**Comment by jmportilla** [comment]
Got it! Thanks!
