### ISSUE TITLE
boxplot: warning when specifying multiple colors?

### ISSUE THREAD

**Issue by mathause** [mwaskom/seaborn#639]
When assigning colors manually, a error occurs. 

    import numpy as np
    import seaborn as sns

    data = np.random.rand(10, 2)
    sns.boxplot(data=data, color=('k', 'g'))

I assume `sns.boxplot(data=a, palette=('k', 'g'))` is the new syntax? Maybe throw an error when multiple colors are specified?

**Comment by mwaskom** [comment]
It can be somewhat tricky to figure out what "not a color" is because there are so many ways to specify them in matplotlib but you got an error raised from color conversion code so presumably you figured it out?

**Comment by mathause** [comment]
That is true - I was mainly confused because it broke my code and the error message looked like a bug and not a feature ;)
