### ISSUE TITLE
boxplot: non-black edgecolor with color='0.9' (gray)

### ISSUE THREAD

**Issue by mathause** [mwaskom/seaborn#640]
When using a gray color for a boxplot, the edgecolor is also gray, unless used in conjunction with another color. See example. 

    import numpy as np
    import seaborn as sns

    sns.set(style='white')

    data1 = np.random.rand(10, 1)
    data2 = np.random.rand(10, 2)

    f, ax = plt.subplots(1, 4)

    g='0.9'
    sns.boxplot(data=data1, color=g, ax=ax[0])
    sns.boxplot(data=data1, color='g', ax=ax[1])
    sns.boxplot(data=data2, palette=(g, g), ax=ax[2])
    sns.boxplot(data=data2, palette=(g, 'g'), ax=ax[3])

    plt.show()

**Comment by mwaskom** [comment]
This is expected behavior. Were you expecting something else?

**Comment by mathause** [comment]
Is this expected behavior on matplotlib or on seaborn side? Why for gray colors only? Well I find it strange that the edgecolor depends on whether you specify a second color or not. And I found no easy way to change the edgecolor - is there one? 

If that is how it is supposed to be then it's fine, I guess.

Background: I used to plot two boxplots above each other with a `position=(1, 1)` argument. As this no longer works I need two calls to boxplot.

**Comment by mwaskom** [comment]
> Is this expected behavior on matplotlib or on seaborn side? Why for gray colors only? Well I find it strange that the edgecolor depends on whether you specify a second color or not.

The edges are always "gray", just always a gray that is some proportion of the lightness of the darkest fill color in the palette. So if you have a very light fillcolor, it will be more noticeably "gray", but the color is always changing.

> And I found no easy way to change the edgecolor - is there one?

```python
ax = sns.boxplot(...)
plt.setp(ax.lines, color=".1")
```

**Comment by mwaskom** [comment]
Relevant code is here https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L298

**Comment by mathause** [comment]
Thanks.
