### ISSUE TITLE
Can not add vertical line marker in seaborn.

### ISSUE THREAD

**Issue by orena1** [mwaskom/seaborn#644]
Hi?
Is there any reason why this is not working?
```python
figure()
plot([1,2],[2,3],'|')
```
while this is working
```python
figure()
plot([1,2],[2,3],'*')
```

Thanks,
Oren.

**Comment by mwaskom** [comment]
http://stanford.edu/~mwaskom/software/seaborn/installing.html#known-issues

"An unfortunate consequence of how the matplotlib marker styles work is that line-art markers (e.g. "+") or markers with facecolor set to "none" will be invisible when the default seaborn style is in effect. This can be changed by using a different `markeredgewidth` (aliased to `mew`) either in the function call or globally in the rcParams."
