### ISSUE TITLE
Excessive distplot memory usage

### ISSUE THREAD

**Issue by cviner** [mwaskom/seaborn#645]
```sns.distplot``` uses very large amounts of memory when attempting to plot a large dataset. An attempt to plot a dataset composed of a single vector of 19 591 561 elements (of type float64, all values between 0 and 1, with no NA elements), failed after exceeding 250 GB of memory (using the ```Agg``` backend, on Python 2.7.8, with the latest version of all packages obtained from pip). A conventional Pandas histogram, via ```hist```, works fine, without using exorbitant amounts of memory.

**Comment by mwaskom** [comment]
Nothing I can do about that really; I don't control the code that fits the kernel density estimate.

**Comment by cviner** [comment]
The issue appears to occur even if ```kde=False```. Perhaps the automatic bin determination is also an issue? Would you be able to direct my report to the appropriate party if it isn't due to Seaborn? I would have suspected a StatsModels issue if disabling the KDE plot worked, but that doesn't seem to be the case.

**Comment by mwaskom** [comment]
What happens when you specify a number of bins



—

**Comment by cviner** [comment]
I've now tested this more carefully (apologies for not doing so before) and it appears that the issue is actually the rugplot. Specification of bins does reduce the memory footprint, as does setting ```kde=False```. However, with bins not specified and ```hist=True, kde=True, rug=False```, I am able to create the plot within a 5 GB memory footprint. Any combination (irrespective of specifying the number of bins) with ```rug=True``` causes the memory usage to climb substantially, and I eventually run out.

**Comment by mwaskom** [comment]
Oh, that would be a matplotlib issue then, but I can't imagine that a rugplot with 10e7 observations is going to be very useful.

**Comment by cviner** [comment]
I agree that a rugplot is unlikely to be useful in this case and don't really need it (I was just trying out the various options). I'll report this issue to matplotlib. Thank you.

**Comment by cviner** [comment]
It appears that some of the memory issues [may be due to Seaborn](https://github.com/matplotlib/matplotlib/issues/4695#issuecomment-121306730).

**Comment by mwaskom** [comment]
IMO this works fine for any reasonable number of observations that it is reasonable to draw a rug plot for so it is not worth changing the code.

**Comment by cviner** [comment]
Okay, however it should likely detect that there are too many points to draw a rugplot and error (i.e. fail-fast). Attempting to make a plot, however inadvisable it is in such a case to attempt a rugplot, and be faced with a program growing to over 250 GB of memory usage is quite a problem, in my view.

**Comment by shoyer** [comment]
We added `df.sample` to pandas for exactly this sort of usecase -- it works very nicely with seaborn and matplotlib in my experience.
