### ISSUE TITLE
Custom reorder of rows/cols in clustermap

### ISSUE THREAD

**Issue by michael-imbeault** [mwaskom/seaborn#646]
I'm using clustermap and would like to reorder the clusters generated with MOLO (see http://cran.r-project.org/web/packages/dendsort/vignettes/example_figures.html).

I have two 1D arrays of the new orders for columns and rows, but can't change ClusterGrid.dendrogram_row.reordered_ind. Is there a way to reorder the rows/cols and the corresponding dendrograms?

Thanks,
Michael

**Comment by mwaskom** [comment]
I believe the dendrogram itself is drawn by code that lives in scipy and thus isn't something we are able to manipulate, but you could at least reorder your matrix and plot the heatmap.

**Comment by michael-imbeault** [comment]
Yeah that is what I'm doing right now - I guess the other options is to modify the linkage matrix itself, I'll try that. Thanks!

**Comment by markak** [comment]
I'd be interested in helping to implement something like this - have hacked together a notebook showing the difference optimal leaf ordering makes to clustermap (dendrogram reordering not present yet) - http://nbviewer.ipython.org/url/stanford.edu/~markak/2015-09-02%20-%20Optimal%20leaf%20ordering%20for%20hierarchical%20clustering.ipynb#

**Comment by mwaskom** [comment]
If there are improvements that can be made to the clustering algorithms, they should be committed upstream to scipy and/or fastcluster.
