### ISSUE TITLE
Request to resuscitate `corrplot`

### ISSUE THREAD

**Issue by pberkes** [mwaskom/seaborn#648]
While I realize that `heatmap` is more flexible, making a correlation plot is a common operation, and replacing a single `corrplot` call at the moment requires several lines of code.

What is the feeling about un-deprecating `corrplot` (possibly re-implementing it on top of `heatmap`)?

For instance, it is quite impressive that with a simple `corrplot(df)` I can get this plot:
![image](https://cloud.githubusercontent.com/assets/314633/8702780/d5428d6e-2b11-11e5-8faf-b8f1afaea166.png)

It would be nice to be able to keep the same level of simplicity!

**Comment by mwaskom** [comment]
What about that plot are you specifically interested in that you can't get from

```python
sns.heatmap(df.corr(), annot=True)
```

?

**Comment by pberkes** [comment]
Oh well, I didn't manage to get to that one-liner, thanks for pointing it out. (It might be useful to emphasize that replacement in the release notes, I failed to find it in the docs yesterday.)

The final result is
![image](https://cloud.githubusercontent.com/assets/314633/8718191/3fd72530-2b9a-11e5-8958-bbdd96daca68.png)

Thank you! Closing the issue...

**Comment by mwaskom** [comment]
Oh right you'll want square=True as well



—
