### ISSUE TITLE
Different fits on two different machines

### ISSUE THREAD

**Issue by dhbachh** [mwaskom/seaborn#651]
Hi there,
I've been recently using seaborn to plot the distribution of my data. 
now surprisingly so, I noticed that running the fit on two different machines with the exact same spicy and seaborn version and parameters(default values: I simply uses seaborn.displot(data) ) gave me two different fits.

(first fit):
![1](https://cloud.githubusercontent.com/assets/12612251/8763429/abc814a8-2d92-11e5-92f0-a2b58dcdf47a.png)

(zoom of the first fit):
![3](https://cloud.githubusercontent.com/assets/12612251/8763437/11b5ccce-2d93-11e5-9a35-e17dc413c933.png)

(Second fit):
![2](https://cloud.githubusercontent.com/assets/12612251/8763433/db2cfde4-2d92-11e5-8d72-37bac9d953c1.png)

As you might notice the histogram values are identical but the fit isn't, why would you think might be causing this?

Cheers!

**Comment by mwaskom** [comment]
It is very hard to speculate without knowing more details...
