### ISSUE TITLE
Set space between boxes in Python Graphs generated nested box plots

### ISSUE THREAD

**Issue by kevin-snippet** [mwaskom/seaborn#652]
I am trying to set a space between the subplots (between the green and orange boxes). Can't find a way to do that, anyone could find a way (code attached)?

![Seaborn Boxplots][1]

    import numpy as np
    import pandas as pd
    import matplotlib as mpl
    import matplotlib.pyplot as plt
    import seaborn as sns
    tips = sns.load_dataset("tips")
    sns.set(style="ticks", palette='Set2', font='Roboto Condensed')
    sns.set_context("paper", font_scale=1.1, rc={"lines.linewidth": 1.1})
    g=sns.factorplot(x="time", y="total_bill", hue="smoker",
                   col="day", data=tips, kind="box", size=4, aspect=0.5,
                     width=0.8,fliersize=2.5,linewidth=1.1, notch=False,orient="v")
    sns.despine(trim=True)
    g.savefig('test6.png', format='png', dpi=600)

  [1]: http://i.stack.imgur.com/RdctR.png

**Comment by mwaskom** [comment]
Nope, that's how they get drawn.

**Comment by audeoudh** [comment]
Well.  I still need to get a tiny space in between them.  As seaborn is not able to do that at all (after that decided answer of mwaskom), I tried to modify matplotlib directly, a posteriori.  Here are a code snippet.  It may have to be tweaked a little to adapt to your situation.

    ax = plt.gca()  # Or get the axis another way

    def _reduce_box_width(artist, factor=.5):
        vertices = artist.get_path().vertices
        artist_width = vertices[1, 0] - vertices[0, 0]
        vertices[0, 0] += artist_width * (factor/2)
        vertices[1, 0] -= artist_width * (factor/2)
        vertices[2, 0] -= artist_width * (factor/2)
        vertices[3, 0] += artist_width * (factor/2)
        vertices[4, 0] += artist_width * (factor/2)

    for artist in ax.artists:
        _reduce_box_width(artist, factor=.5)

    def _reduce_horizontal_line_width(artist, factor=.5):
        vertices = artist.get_path().vertices
        artist_width = vertices[1, 0] - vertices[0, 0]
        vertices[0, 0] += artist_width * (factor/2)
        vertices[1, 0] -= artist_width * (factor/2)

    horizontal_lines = [l for l in ax.lines
                        if len(l.get_path().vertices) != 0 and
                           l.get_path().vertices[0, 1] = = l.get_path().vertices[1, 1]]
    for line in horizontal_lines:
        _reduce_horizontal_line_width(line)

    ax.redraw_in_frame()
