### ISSUE TITLE
countplot orient not working

### ISSUE THREAD

**Issue by guma44** [mwaskom/seaborn#654]
Hi,
The code in IPython notebook:
```
%matplotlib inline
import pandas as pd
import seaborn as sns
df = pd.DataFrame([[2], [2], [1], [1], [1], [3]])
sns.countplot(x=0, data=df, orient='v')
sns.countplot(x=0, data=df, orient='h')
```

produces exactly the same output plots. This means that the option for orienting is not working.

**Comment by mwaskom** [comment]
You have to do 

```python
sns.countplot(y=0, data=df, orient='h')
```

(that is, `y=0` instead of `x=0`. When plotting with long-form data, the assignment of variables in the dataframe to plot axes supersedes the `orient` keyword argument.

**Comment by guma44** [comment]
Thanks a lot, I did not expected :).

**Comment by FaizaanS** [comment]
Hey, thanks a lot. It helped me today!

**Comment by prasanth-ntu** [comment]
Worked like a charm! Thanks :)

**Comment by dhananjai-kp** [comment]
helped me too...... THANKS.... :)
