### ISSUE TITLE
context/font_scale does affects size of some but not all text

### ISSUE THREAD

**Issue by williamsmj** [mwaskom/seaborn#656]
My understanding is `set_context` (and its `font_scale` keyword) are intended to scale plot elements. It scales the title of an `Axes` title, `legend` or `ticklabels`. But it does not affect `Figure`'s `suptitle` or `ax.text()`. This [notebook](https://gist.github.com/williamsmj/5b6107c36362e6048cd3) demonstrates my confusion. Note that `suptitle` and `text` stay the same size.

Is there any documentation that explains what is going on here? (If it's on [this page](http://stanford.edu/~mwaskom/software/seaborn/tutorial/aesthetics.html) then I'd be very grateful for pointers to the exact paragraph!)

And assuming this is not a bug, what's the right way to rescale _all_ text to match the size of the text seaborn does resize? Right now I'm resorting to constants I figure out by trial and error, in calls to, e.g. `fig.suptitle()` and `ax.text()`. I have to change these numbers depending on what `sns.set_context()` I am in.

**Comment by mwaskom** [comment]
I think this was fixed in #642

**Comment by williamsmj** [comment]
Indeed it was. I've updated [the example notebook](https://gist.github.com/williamsmj/5b6107c36362e6048cd3) with the current master branch (7394ebd451619f5264d4e025b73b382a5112254c). Works perfectly! Thanks!
