### ISSUE TITLE
In IPython session, Seaborn plot in new figure needs refresh to display

### ISSUE THREAD

**Issue by pberkes** [mwaskom/seaborn#657]
In an IPython session with `matplotlib` mode set to `qt` (and possibly in other modes, as well), a Seaborn plot in a new `figure` is not displayed until the user resizes the window, or explicitly calls `draw`. With regular matplotlib plots, the plot is displayed immediately.

For example, consider this session:

```
↳ ipython
Python 2.7.9 | 64-bit | (default, Jun 30 2015, 19:41:21) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %matplotlib qt

In [2]: import matplotlib

In [3]: from matplotlib import pyplot as plt

In [4]: import seaborn as sns

In [5]: sns.__version__
Out[5]: '0.6.0'

In [6]: matplotlib.__version__
Out[6]: '1.4.3'

In [7]: plt.figure()
Out[7]: <matplotlib.figure.Figure at 0x119aef990>

In [8]: sns.countplot([0, 1, 0, 0, 1, 1, 1, 2, 0, 2])
Out[8]: <matplotlib.axes._subplots.AxesSubplot at 0x119b0e810>
```

This is the state of the window at the end of the sequence of commands:
![screen shot 2015-07-28 at 09 21 32](https://cloud.githubusercontent.com/assets/314633/8926798/94740134-350a-11e5-91d0-47429a0bb175.png)

After resizing, or calling `plt.draw()`:
![screen shot 2015-07-28 at 09 21 49](https://cloud.githubusercontent.com/assets/314633/8926805/9d46bb9e-350a-11e5-860e-f870c07bc8b4.png)

**Comment by mwaskom** [comment]
I dunno, but it doesn't happen if you don't call `plt.figure()` first, which isn't necessary (at least in this example).

**Comment by mwaskom** [comment]
Here's another example that produces the same behavior without seaborn:

```python
[mwaskom]|17> plt.figure()
         |17> <matplotlib.figure.Figure at 0x112233350>
[mwaskom]|18> ax = plt.gca()
[mwaskom]|19> ax.plot([0, 1, 2], [0, 2, 1])
         |19> [<matplotlib.lines.Line2D at 0x105915410>]
```

After line 19, the figure remains empty. (This is basically how seaborn plots are made).

**Comment by pberkes** [comment]
I should give a little bit of context: I was teaching how to use Seaborn in a data science class, and students were expecting to be able to do interactive plotting the way they do in matplotlib. They were creating multiple figures (hence the `plt.figure()` command), then running a Seaborn plot, but the plot was not showing up they way it usually does for high-level commands in matplotlib

You are correct that your example will not draw the plot, but if you use `plt.plot` directly (or other high-level commands like `plt.hist`, `plt.scatter`, etc), it will.

Looking at the code of `plot` in matplotlib, they are explicitly calling a function called `draw_if_interactive()`:

```
plt.plot??
Type:        function
String form: <function plot at 0x111b729b0>
File:        /Users/pberkes/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/pyplot.py
Definition:  plt.plot(*args, **kwargs)
Source:
@_autogen_docstring(Axes.plot)
def plot(*args, **kwargs):
    ax = gca()
    # allow callers to override the hold state by passing hold=True|False
    washold = ax.ishold()
    hold = kwargs.pop('hold', None)
    if hold is not None:
        ax.hold(hold)
    try:
        ret = ax.plot(*args, **kwargs)
        draw_if_interactive()
    finally:
        ax.hold(washold)

    return ret
```

**Comment by mwaskom** [comment]
Right, but the seaborn functions are more closely tied to the object-oriented interface than to the state machine one (though they do kind of work in the state machine style).

ps you should teach plotting in the notebook, not in the terminal!

**Comment by pberkes** [comment]
Would you not consider adding a call to `draw_if_interactive` or a 'post-execute' hook for IPython, as matplotlib does? It fixes a realistic use case, at a very small cost.

I normally teach Seaborn in a notebook, but for the exercises students are free to use what they prefer.

**Comment by mwaskom** [comment]
But it's not clear that there is a very small cost. For instance, a lot of seaborn functions, like `lmplot`, `factorplot`, `pairplot`, etc. involve a higher-level application of a plotting function that gets called many times. Forcing a redraw within the lower-level functions could substantially slow those functions.

Also there are various issues in matplotlib that forcing a draw in the middle of plotting a figure seems to run into. For instance, there was an issue in heatmap where the figure would get drawn to check whether the ticklabels were overlapping so they could be rotated, but this code would crash with the OSX backend. In general, this kind of thing runs into dark corners of matplotlib that I would like to avoid.

It also just kicks the can of confusion down the road. What I mean is that the advocated style for doing any customization of the seaborn functions is something like

```python
ax = sns.countplot(x)
ax.set(ylabel="a different y label")
```

This kind of thing is all over the docs. If `countplot` does a draw, you're just going to end up with users who are confused by the fact that after you run this code, the y label isn't changing.

I realize that the state-machine, run everything line-be-line in the REPL through `pyplot` usecase is something that exists, but I also think it just is an unavoidable path to confusion so I'm not eager to go out of my way to support it.

**Comment by pberkes** [comment]
Understood. Let me have a look at the IPython hook before closing the issue.

**Comment by pberkes** [comment]
It looks like the `draw_if_interactive` function has been removed in most places:
https://github.com/matplotlib/matplotlib/commit/b2fbae76c738d5c24e559b98ed494e9b146c16aa

On master (1.5.dev1), matplotlib relies on the IPython hook:
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/pyplot.py#L114

I tested it locally, and the problem appears to have been solved already!

Closing as solved (in the near future).

**Comment by mwaskom** [comment]
Great!

**Comment by mwaskom** [comment]
Nice!
