### ISSUE TITLE
Can't reproduce PairGrid examples

### ISSUE THREAD

**Issue by MichelleLochner** [mwaskom/seaborn#664]
I'm having problems reproducing examples involving PairGrid. I'm running Ubuntu 14.04 with Python 2.7.4.

If I run the example code, for example, 
```
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="white")

df = sns.load_dataset("iris")

g = sns.PairGrid(df, diag_sharey=False)
g.map_lower(sns.kdeplot, cmap="Blues_d")
g.map_upper(plt.scatter)
g.map_diag(sns.kdeplot, lw=3)
```

I get a plot that looks like this:

![figure_1](https://cloud.githubusercontent.com/assets/6876163/9011725/02dc51b4-37a7-11e5-980b-aa81f1e3a405.png)

I should note that ```g.map(plt.scatter)```  works perfectly but not ```g.map_lower(plt.scatter)``` or ```g.map_upper(plt.scatter)``` (produces the same empty plot).

I get the same plot regardless of whether I use ipython notebook or the command line or if I change from inline to qt backends.

**Comment by mwaskom** [comment]
I think this is a bug on a relatively old version of matplotlib, maybe < 1.4 or < 1.3. What version are you using?
