### ISSUE TITLE
v0.6 unexpected violinplot behavior with mpld3

### ISSUE THREAD

**Issue by jlmcgehee21** [mwaskom/seaborn#671]
Not sure if mpld3 is something you intended to support (or vice versa), but v0.5 worked excellently with mpld3, v0.6 seems to cause mpld3 to render the "inner" elements erratically (seems to be a problem with the z order).  I'm creating a similar issue on the mpld3 repo as well.

**Comment by mwaskom** [comment]
Can you give me more information about the "erratic" rendering? In other words, some code I could run, and ideally a screenshot describing the issue?

**Comment by jlmcgehee21** [comment]
I'll have to wait until this afternoon.  In the mean time, if it helps, some of the "inner" points on the violin plot are not visible (for a whole "violin"), the behavior seems to be erratic in the sense that this only occurs on a few (seemingly random) violins.  I noticed this on an iPython notebook that has 5 violin plots in total, haven't tested the problem in any other environment.

I'll try to give you a screen shot and some code of regular matplotlib output vs mpld3 when I get the chance.
