### ISSUE TITLE
adding commas to FacetGrid tick labels

### ISSUE THREAD

**Issue by dpeck-cmu** [mwaskom/seaborn#675]
I cannot figure out a way to format my axis labels when plotting using the FacetGrid in seaborn to have thousand-comma-separator aside from setting the axis manually. Is this possible? If not, can it be? Thanks!

**Comment by mwaskom** [comment]
I don't know off the top of my head how to do this, but it would be a matter of using matplotlib properly, not seaborn.

**Comment by mwaskom** [comment]
e.g. something like http://stackoverflow.com/questions/8271564/matplotlib-comma-separated-number-format-for-axis

**Comment by paulwasit** [comment]
I know this is old, but I had the same question today. One way is to loop over the axes:

```
import matplotlib.pyplot as plt
import matplotlib.ticker as tkr
import seaborn as sns

g = sns.FacetGrid(...)
g = g.map(plt.hist, ...)

for ax in g.axes[0]:
    ax.xaxis.set_major_formatter(
        tkr.FuncFormatter(lambda x, p: "{:,}".format(int(x))))
```
