### ISSUE TITLE
Default colour scheme repeats

### ISSUE THREAD

**Issue by naught101** [mwaskom/seaborn#680]
The default colour scheme for a line plot loops through 7 colours. That means if you have more than 7 colours, you get at least one pair of lines that is totally indistinguishable on the legend:

```{python}
import pandas as pd
import seaborn as sns

pd.DataFrame({s:[random.random()+int(s) for i in range(10)] for s in '12345678'}).plot()
```
produces:

![figure_1](https://cloud.githubusercontent.com/assets/167164/9384032/a5f980bc-4790-11e5-8341-6cecdb56033b.png)

It's reasonably common to have a line plot with more than 7 lines, so it would be better if the colours were always unique. Probably the easiest would be an auto-generated scheme along the lines of ggplot, like: 

```{python}
colours = [mpl.colours.rgb2hex(mpl.colours.hsv_to_rgb([l, 0.8, 0.8]))
           for l in np.linspace(0,1,n_lines+1,endpoint=False)]
```

**Comment by jonross** [comment]
If there were a way to have it automatically switch to a different, configurable line style each time it cycled through the color list, that would also be very helpful.  I have a couple tall plots with 20 lines each and although I manually reorder the legend to match the max value of each series, you still have to squint at it.

thanks,
Jon

**Comment by mwaskom** [comment]
http://stanford.edu/~mwaskom/software/seaborn/tutorial/color_palettes.html

**Comment by mwaskom** [comment]
Cycling by line styles is something matplotlib is adding for the next release, check their github to see how it's going.

**Comment by naught101** [comment]
Yes, I know you manually add colours. I'm talking about the default colours.

On 21 August 2015 1:04:37 am AEST, Michael Waskom <notifications@github.com> wrote:
>http://stanford.edu/~mwaskom/software/seaborn/tutorial/color_palettes.html
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mwaskom/seaborn/issues/680#issuecomment-133042739

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
