### ISSUE TITLE
Wrong categorization in PairGrid with hue option and stripplot

### ISSUE THREAD

**Issue by vilhub** [mwaskom/seaborn#684]
Hi,

Using PairGrid with categorical data on the x axis and hue option and plotting using stripplot gives wrong output categories on the plot.

Here's a minimal example which highlights this.
```python
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd

data = {'category' : ['a','b'],
        'type' : ['moose', 'piglet'],
        'output' : [1,2]}
df = pd.DataFrame(data)
g = sns.PairGrid(df,x_vars='category',y_vars='output', hue='type')
g.map(sns.stripplot)
g = g.add_legend()
plt.show()
```

We get the following output  
![image](https://cloud.githubusercontent.com/assets/10402864/9471765/2ec1a342-4b52-11e5-933e-77386ad14aa6.png)
which obviously wrongly categorizes the moose as from category 'b'.

This doesn't happen if we disable the hue option.

I haven't seen examples of GridPlot being used for categorical data so I'm not sure it's supposed to be used like that but since it yields functioning but wrong visualizations, it should either be rendered non-functioning or non-wrong.

PS : Thanks for the great visualization package, it works like a charm for exploring parameter spaces in Computational Fluid Dynamics!

**Comment by mwaskom** [comment]
You need to either make your `"category"` variable a pandas categorical datatype with declared levels, or you need to pass `order=["a", "b"]` to `PairGrid.map`

**Comment by vilhub** [comment]
Alright, thanks. I had Pandas 14.1 and I now updated to 16.2, it now works even without making it a categorical datatype.
