### ISSUE TITLE
feature request: violinplot like plot using histograms instead of kde

### ISSUE THREAD

**Issue by cpaulik** [mwaskom/seaborn#688]
I would find it very useful to have a option in the violinplots to use histograms instead of the kde. Or if it would not fit in the violinplot then maybe a new plot type could be introduced.

If it is not clear what I mean then there is an example at the end of [this stackoverflow post](http://stackoverflow.com/a/15893422/1314882).

Thanks for considering this. I would be happy to contribute if you think this would be useful.

**Comment by sauliusl** [comment]
#661 seems to be doing something similar. Is this what you are looking for?

**Comment by cpaulik** [comment]
Yes that looks very much like the same thing. I just did not find it since I was unfamiliar with the name. Thanks.
