### ISSUE TITLE
pip install fails with six.PY2 -- module has no attribute 'PY2'

### ISSUE THREAD

**Issue by uhjish** [mwaskom/seaborn#689]
It's being used in [seaborn.doc.sphinxext.plot_directive](https://github.com/mwaskom/seaborn/blob/04ad1470f8a22273ca2d9aa9a0d3d97232553a0f/doc/sphinxext/plot_directive.py#L134)

This leads to pip install problems when the system installed six library is older and does not have the six.PY2 flag.

**Comment by mwaskom** [comment]
Building the docs (and more generally developing seaborn) involves a number of dependencies that aren't declared in setup.py. In what case is this actually an issue?

**Comment by mwaskom** [comment]
(seaborn.doc.sphinxext.plot_directive) isn't actually part of the seaborn library, it's not like you could import it, unless you're doing something really weird.

**Comment by uhjish** [comment]
When I try to pip install seaborn on an older centos distribution, the install fails, saying that module has no attribute six.PY2. Seems to be similar to this issue on SO: http://stackoverflow.com/questions/24081043/module-object-has-no-attribute-py2

If six is already being pulled in in external/ why rely on the system six just in this module?  

--  
Ajish George
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by mwaskom** [comment]
I don't think I understand how that could possibly be happening, because the docs aren't even included in the tarball pip gets from pypi. I think your issue might be something else...can you please include a full example of what you are doing and the error you see?

**Comment by mwaskom** [comment]
And again, because this isn't really a "seaborn module", it's just part of the doc build infrastructure, which includes other things (sphinx, numpydoc, etc.) that aren't technically seaborn dependencies.

**Comment by uhjish** [comment]
Hrmm, it seems to actually be coming from matplotlib.
Here’s the stack trace.

Installing collected packages: singledispatch, rpy2, enum34, numpy, scipy, python-dateutil, pytz, pandas, scikit-learn, sklearn, patsy, statsmodels, brewer2mpl, funcsigs, pbr, mock, matplotlib, ggplot, seaborn, rnaseq-services
  Running setup.py install for rpy2
  Running setup.py install for enum34
  Found existing installation: numpy 1.7.1
    Uninstalling numpy-1.7.1:
      Successfully uninstalled numpy-1.7.1
  Running setup.py install for numpy
  Found existing installation: scipy 0.12.1
    Uninstalling scipy-0.12.1:
      Successfully uninstalled scipy-0.12.1
  Running setup.py install for scipy
  Running setup.py install for pandas
  Running setup.py install for scikit-learn
  Running setup.py install for sklearn
  Running setup.py install for statsmodels
  Running setup.py install for matplotlib
  Running setup.py install for ggplot
  Running setup.py install for seaborn
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-fYB741/seaborn/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0Aw6kM-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fYB741/seaborn/setup.py", line 66, in <module>
        install_requires = check_dependencies()
      File "/tmp/pip-build-fYB741/seaborn/setup.py", line 54, in check_dependencies
        import matplotlib
      File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 1100, in <module>
        rcParams = rc_params()
      File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 947, in rc_params
        fname = matplotlib_fname()
      File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 753, in matplotlib_fname
        if six.PY2:
    AttributeError: 'module' object has no attribute 'PY2'
     
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-fYB741/seaborn/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0Aw6kM-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-fYB741/seaborn



--  
Ajish George
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by uhjish** [comment]
system six is Version: 1.3.0
os is centos 7

**Comment by mwaskom** [comment]
Yep, looks like a matplotlib issue that you're just seeing when seaborn gets installed because it tries to import matplotlib to see whether it needs to declare it as a dependency (this is a workaround for some very annoying behavior in pip)

**Comment by uhjish** [comment]
Render unto matplotlib the bugs which are matplotlib's... closing.
