### ISSUE TITLE
Broken link in the colormap tutorial on the webpage

### ISSUE THREAD

**Issue by joelostblom** [mwaskom/seaborn#693]
Just a heads up that the link to the _more technical paper_ in the [colormap tutorial](http://stanford.edu/~mwaskom/software/seaborn/tutorial/color_palettes.html) is broken. Is [this](https://cfwebprod.sandia.gov/cfdocs/CompResearch/docs/ColorMapsExpanded.pdf) the same paper?

**Comment by mwaskom** [comment]
Yep that's what that should go to.
