### ISSUE TITLE
Use teardown methods for tests

### ISSUE THREAD

**Issue by clarkfitzg** [mwaskom/seaborn#694]
```
~/dev/seaborn/seaborn/tests $ grep "plt.close" *.py | wc
     241     482   10404
```
That's a lot of closing going on. This could be reduced through the use of [teardown methods](http://nose.readthedocs.org/en/latest/writing_tests.html).

Just define this class and have everything inherit from it.
```
class SeabornTestCase(object):
    def tearDown(self):
        plt.close('all')
```

@mwaskom let me know if you're interested and I can send a PR. Should be simple.

**Comment by mwaskom** [comment]
I think teardown methods execute at the class level right? Figures need to be closed after each test.

**Comment by clarkfitzg** [comment]
They run after each method. You're thinking of `tearDownClass`.

> Like unittest.TestCase subclasses, other test classes can define setUp and tearDown methods that will be run before and after each test method. Test classes that do not descend from unittest.TestCase may also include generator methods and class-level fixtures. Class-level setup fixtures may be named setup_class, setupClass, setUpClass, setupAll or setUpAll; teardown fixtures may be named teardown_class, teardownClass, tearDownClass, teardownAll or tearDownAll. Class-level setup and teardown fixtures must be class methods.

**Comment by mwaskom** [comment]
ok, cool
