### ISSUE TITLE
import seaborn.apionly breaks %matplotlib inline

### ISSUE THREAD

**Issue by shoyer** [mwaskom/seaborn#695]
See this gist for an example:
https://gist.github.com/shoyer/31e308a90c9882324f31

In contrast, if the `import seaborn.apionly` line is commented out, a plot is produced. If it matters, I'm using the conda matplotlib (1.4.3) on OS X.

I believe this is the same issue @dubourg described in this comment:
https://github.com/mwaskom/seaborn/pull/126#issuecomment-134592134

`import seaborn.apionly` also appears to be somehow responsible for some strange styling issues we're having with xray plotting in the notebook (I'm not entirely sure because I haven't succeeded yet in making a minimal reproducible example):
https://gist.github.com/shoyer/0233061ba31e3ec71009

**Comment by mwaskom** [comment]
I have noticed a little weirdness too, but I have been suspecting it's been a change in IPython and the way they do some rc changes in the inline backend -- this didn't use to be an issue.

**Comment by mwaskom** [comment]
For the record (as you may know), `seaborn.apionly` is just calling `seaborn.reset_orig()`, which itself is just doing `mpl.rcParams.update(mpl.rcParamsOrig)`.

**Comment by mdengler** [comment]
Would you consider a PR to remove the call to reset_orig()?  I've just run into this issue.

**Comment by mdengler** [comment]
Opened PR https://github.com/mwaskom/seaborn/pull/887 in case it's acceptable.
