### ISSUE TITLE
choose_colorbrewer_palette error with ipython 4 and jupyter

### ISSUE THREAD

**Issue by ababino** [mwaskom/seaborn#699]
Dear all,

if I run this code

```python
import seaborn as sns
sns.choose_colorbrewer_palette('qualitative')
```

it returns this error

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-b05cf0dd3d2a> in <module>()
      1 import seaborn as sns
----> 2 sns.choose_colorbrewer_palette('qualitative')

/usr/local/lib/python2.7/dist-packages/seaborn/palettes.py in choose_colorbrewer_palette(data_type, as_cmap)
   1011 
   1012     """
-> 1013     from IPython.html.widgets import interact, FloatSliderWidget
   1014 
   1015     if data_type.startswith("q") and as_cmap:

ImportError: cannot import name FloatSliderWidget 
```

this happened just after updating to the new IPython 4 and Jupyter. 

I understand that the IPython.html.widgets have been moved to the new package ipywidgets.
I installed it and I got the same error. Then I replaced all "FloatSliderWidget" in "palettes.py" for "FloatSlider" and it worked!

I hope this is helpful

Regards

**Comment by anntzer** [comment]
The same issue happens with `choose_cubehelix_palette`.

**Comment by emilydolson** [comment]
I'm having the same problems. Making the changes described above allows me to run choose_color_brewer_palette() without errors, but it just gives me an array of numbers and sliders that don't do anything. I'm assuming this is not the intended behavior.
