### ISSUE TITLE
hist(..., histtype="step") is barely visible

### ISSUE THREAD

**Issue by anntzer** [mwaskom/seaborn#704]
`hist(..., histtype="step")` gives a barely visible plot under the seaborn default style, because it uses `patch.linewidth` instead of `lines.linewidth`.  An intuitive way to fix it would be for `plt.hist` to use `ax.step` to do the plotting in that case instead than by constructing a `Patch`, but this was approach was (reasonably) shot down in matplotlib/matplotlib#4065.

**Comment by mwaskom** [comment]
What is the proposed change here.

**Comment by anntzer** [comment]
Not so easy, but perhaps seaborn can monkey-patch Axes.hist to locally change `patch.linewidth` to `lines.linewidth`?

**Comment by mwaskom** [comment]
I'd be strongly :-1: on that kind of behavior.

**Comment by anntzer** [comment]
Fair enough, feel free to close this.

**Comment by mwaskom** [comment]
Sorry. At least it is easy to work around with `ax.step` or by passing a linewidth to `hist`.
