### ISSUE TITLE
Problem using FacetGrid title templates: {row_var} <space> {row_name} instead of only {row_name}

### ISSUE THREAD

**Issue by cviner** [mwaskom/seaborn#706]
I am attempting to use row margin titles, with only the row name in a [`FacetGrid`](http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.FacetGrid.html). I do the following:

    g.set_titles(row_template="{row_name}", col_template="")

However, this leads to `{row_var} {row_name}`. Notably, a space is present, instead of the usual `=`. However, the `{row_var}` should not be present at all.

The [standard hack](https://github.com/mwaskom/seaborn/issues/440#issuecomment-73185015) to fix issues of this nature (i.e. using `plt.setp(g.fig.texts, text="")` prior to the above) does not resolve this issue, but does appear to fix some overlapping labels that would occur otherwise (which is odd, since I am only mapping onto the `FacetGrid` once). Perhaps that's not surprising given the changes in pull request #612, but is there some alternative means of fixing this? Is there some easy way for me to fix this at the level of the [`axis`](http://matplotlib.org/api/axes_api.html) object (i.e. can I retroactively get, modify, and then set these textual fields)?

However, when attempting to reproduce this on standard datasets, the issue is not present (i.e. the row name appears correctly). As far as I can tell, my `DataFrame` being provided to the `FacetGrid` is correct and does not contain the column header anywhere within its columnar data. I realize that in the absence of a proper MWE this might not be feasible to address, but I was wondering if you might have seen this before or have some idea as to what could cause this. 

(This issue appears to be similar to issue #440.)

**Comment by mwaskom** [comment]
The basic idea of the previous hack will work, but the title texts are now properties of the Axes not the figures.

**Comment by cviner** [comment]
@mwaskom Thank you; that's very good to know (and thanks for responding so quickly!). It's not really clear to me which [`axis`](http://matplotlib.org/api/axis_api.html) attribute I should access or perhaps pass to `plt.setp`. Could you direct me to some documentation or code to which these text objects now belong?

Would it perhaps be (similar to the [objects used in testing](https://github.com/mwaskom/seaborn/blob/master/seaborn/tests/test_axisgrid.py#L448) since pull request #612):

    plt.setp(g.axes[0, 1].texts[0], text="")
    plt.setp(g.axes[0, 1].texts[0], text="")

I'm not that familiar with how to access axis annotations after their creation. Any more explicit description would be much appreciated.

**Comment by mwaskom** [comment]
Something like

```
for ax in g.axes.flat:
    plt.setp(ax.texts, text="")
```

should do it.

**Comment by cviner** [comment]
@mwaskom That makes sense.

I can confirm that using that solved my problem.

Thank you!!

**Comment by mwaskom** [comment]
Thinking about this a bit more, `FacetGrid` could probably track the text objects that make up the row "titles" and clear them before adding new titles. That would make life easier.

**Comment by cviner** [comment]
That sounds like a great idea and would be a welcome enhancement!
