### ISSUE TITLE
Ensure unique colours for different legend items within distinct FactorGrid rows

### ISSUE THREAD

**Issue by cviner** [mwaskom/seaborn#707]
Colouring with custom [`color_palette`s](http://stanford.edu/~mwaskom/software/seaborn/tutorial/color_palettes.html) generally works very well, however I can't figure out how to still condition upon a variable via colour (i.e. upon three variables using `col`, `row`, and `hue` in a [`FacetGrid`](http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.FacetGrid.html)), but also ensure that colours never repeat for different legend items (i.e. different data in the `hue` condition). In particular, colours are correct *within* a row, but always cycle *between rows*, even if the palette contains a sufficient number of colours to allow for no colours to need to be repeated.

This looks like the intended behaviour and admittedly might usually be desirable. Nonetheless, is there some way to disable this and ensure that no colours are ever reused for distinctly `hue`'ed items?

**Comment by mwaskom** [comment]
I don't think I fully understand. But the factors are expected to be crossed, not nested.

**Comment by cviner** [comment]
I'm not certain what you mean by "crossed".

Basically, my `hue` column is composed of many categories (i.e. a number of strings, from a finite set). However, these hue values are not completely shared between different rows of my plot. Therefore, when making the legend (which I manually make on a per-row basis via `figlegend`, I want the label colours (and their corresponding points in the plots within that row) to use different colours than the row before it (i.e. they should have disjoint palettes). Perhaps there is some way to assign a different palette on a per-row basis, via the `axis` object?

Sorry if this still isn't clear. I can try to create an example, if needed.

**Comment by cviner** [comment]
I think the main issue at present is that the colours are drawn sequentially from the provided colour map, but this occurs even if the label pertaining to some data element(s) differs from the previous label assigned to that colour, due to that label previously appearing (in a previous row), but not appearing in the current row. This causes the same colour to be assigned to a distinct element.

I realize this is likely the intended and correct behaviour, but I still would like to find a way to ensure that distinct `hue` elements, have distinct colours, across the entire `FacetGrid`.

**Comment by mwaskom** [comment]
Sorry, I'm really not sure what behavior you are describing. I think you'll need to show an example. 



—

**Comment by cviner** [comment]
Okay, I'll try to create one. Thanks for your quick replies!

**Comment by cviner** [comment]
Upon further inspection, this issue turned out to be an artifact of an error in my code, upon creating legends manually via `figlegend`. I managed to switch back to the `add_legend` Seaborn method and everything is now working fine! Sorry for the confusion and thanks again for being so responsive.
