### ISSUE TITLE
Typo in pairgrid dotplot page/code

### ISSUE THREAD

**Issue by julienschroder** [mwaskom/seaborn#710]
Hi,
I was reproducing your example for pairgrid dotplot,then notice that the plot produced have the last columns with a different orientation of grid as shown in this image : 

![figure_10](https://cloud.githubusercontent.com/assets/12923598/10096194/0ac11c7a-631c-11e5-90a1-9f9145fe23d1.png)

Not too sure why...

	import matplotlib.pyplot as plt
	import seaborn as sns

	sns.set(style="whitegrid")

	# Load the dataset
	crashes = sns.load_dataset("car_crashes")

	# Make the PairGrid
	g = sns.PairGrid(crashes.sort("total", ascending=False),
	                 x_vars=crashes.columns[:-3], y_vars=["abbrev"],
	                 size=10, aspect=.25)

	# Draw a dot plot using the stripplot function
	g.map(sns.stripplot, size=10, orient="h",
	      palette="Reds_r", edgecolor="gray")

	# Use the same x axis limits on all columns and add better labels
	g.set(xlim=(0, 25), xlabel="Crashes", ylabel="")

	# Use semantically meaningful titles for the columns
	titles = ["Total crashes", "Speeding crashes", "Alcohol crashes",
	          "Not distracted crashes", "No previous crashes"]

	for ax, title in zip(g.axes.flat, titles):

	    # Set a different title for each axes
	    ax.set(title=title)

	    # Make the grid horizontal instead of vertical
	    ax.xaxis.grid(False)
	    ax.yaxis.grid(True)

	sns.despine(left=True, bottom=True)
	plt.show()

**Comment by mwaskom** [comment]
Where's the typo?

**Comment by julienschroder** [comment]
I don't have the skill to know why but if you look at the plot I attached,  the last column display a different grid orientation. Is it just on my side?

**Comment by mwaskom** [comment]
I can't reproduce your issue on my system using either the inline notebook backend, the QT backend, or the default OSX backend. Also the examples in the docs are generated by running the code that you see.

I'm not sure what your issue is, unfortunately, and it's impossible for me to speculate any further without knowing the details of your system or how you are trying to execute the code...
