### ISSUE TITLE
Use of markers in the hue_kws FacetGrid parameter may only use the first provided marker style

### ISSUE THREAD

**Issue by cviner** [mwaskom/seaborn#715]
When markers are passed via the `hue_kws` parameter to [`FacetGrid`](http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.FacetGrid.html), sometimes only the first provided marker is used for all of the hue levels.

For example, providing `hue_kws={'markers': ['D', 's', 'D', 's', 'D']}` to [`sns.FacetGrid`](http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.FacetGrid.html), results in all markers being only diamonds (i.e. `'D'`).

This may have to do with not passing exactly one marker per hue level, but instead passing fewer (perhaps including providing the number of unique hue levels or legend items). Is my assumption that each legend item defines exactly one hue level not correct? What is the expected behaviour for the presence of fewer markers than hue levels? I would expect it to work for a number of markers equal to the number of legend items and to cycle if fewer are provided (like the palette does).

**Comment by mwaskom** [comment]
I'm not sure I understand exactly what you mean. Can you show a full example?

In general the relevant code is here https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L707

**Comment by cviner** [comment]
Thanks for that pointer.

The issue is that setting markers, as described above, does not work and *only selects the first provided marker in the list*. This is depicted below ("Lunch" erroneously has a triangular, instead of a diamond, marker):

    g = sns.FacetGrid(tips, col="sex", hue_kws=dict(markers=["^", "D"]))

    g = (g.map(sns.pointplot, "total_bill", "tip", "time", palette="hls").add_legend())

![image](https://cloud.githubusercontent.com/assets/10501947/10174288/0aac4b08-66b7-11e5-9932-6abe5c0d50c2.png)

**Comment by mwaskom** [comment]
Both `FacetGrid` and `pointplot` show subsets with `hue`, but totally independently. If you were letting `FacetGrid` do the faceting, then what you did there would have worked. But because you're handing hue through `pointplot` (in general, the better approach), you have to pass `markers` in the call to `map`.

**Comment by cviner** [comment]
That does make sense and I was initially passing `markers` in the `map` call. However, the issue is that the markers get assigned to hue items in a difficult to discern order. Perhaps the use of `hue_order`, as you previously suggested will fix this. Thanks.

**Comment by Cazforshort** [comment]
What about if I want to adjust the marker size? Where would that go in here:

```
fg = (
    seaborn.FacetGrid(data=iris, hue='species', aspect=2)
        .map(probscale.probplot, 'sepal_length')
        .set_axis_labels(x_var='Probability', y_var='Sepal Length')
        .add_legend()
)
```
