### ISSUE TITLE
color_code undefined

### ISSUE THREAD

**Issue by bolau** [mwaskom/seaborn#716]
Hi, 
I've installed seaborn 0.6.0 via pip. I would like to use color_codes to adapt the default plotting colors to the seaborn palette using this:
http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.set_color_codes.html#seaborn.set_color_codes

However, the related functions are undefined:
sns.set(palette='deep', color_code=True)
--> set() got an unexpected keyword argument 'color_code'

sns.set_color_codes()
--> 'module' object has no attribute 'set_color_codes'

The other properties work fine for me, for example:
sns.set(context='talk', style='ticks', palette='deep', font='sans-serif', font_scale=1)
--> all good

Did I do something wrong? Is there a workaround?

Thanks for any help
Boris

**Comment by mwaskom** [comment]
I'm guessing your update did not succeed.

**Comment by bolau** [comment]
I've reinstalled it, now it works. Probably just some weirdness. Thanks a lot for making me try again :)
