### ISSUE TITLE
Controlling legends in boxplots

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [mwaskom/seaborn#720]
Is there a way to control where legends may appear in a boxplot? 

Similarly, is there a way to turn them off, or, even better, have the legend show outside of the plot? I have tried with `legend_out=True`, something that works in `factor_plot` without luck.

Thanks.

**Comment by mwaskom** [comment]
You can just call `ax.legend` and supply a `loc=` parameter as you would with any normal matplotlib plot. It will move the legend, not add a second one.

**Comment by amelio-vazquez-reina** [comment]
Thanks @mwaskom That makes sense. Any way to avoid creating the legend in first place when calling `boxplot`?

**Comment by mwaskom** [comment]
No, but it's always easy to remove...

**Comment by mdastro** [comment]
I have the same problem. I created a figure like this:

![boxplots](https://user-images.githubusercontent.com/10452764/33082160-3adce302-cec3-11e7-9df3-f99d4048a08b.png)

The code is the following:

```
plot01 = sns.boxplot(x=z_cut, y='MAG_ABS_R', hue='UV_class', notch=True, data=bxplt, palette='PRGn')
plt.xlim(0,bins[[ratio_uvup_redseq!=0]].size)
plt.ylabel("M$_r$", fontsize=20)
plt.xlabel("maximum redshift", fontsize=20)
plt.tick_params('both', labelsize='15')
plt.gca().invert_yaxis()
plt.show()
```

And I would like to remove the underline parts of the legend. I tried forcing it, but it didn't really work well (no colors appeared):

![boxplots_legend](https://user-images.githubusercontent.com/10452764/33082188-4ec5d590-cec3-11e7-8f47-233570562c40.png)

The code I forced is the following:

```
legend = ["UV Weak", "UV Upturn"]
plot01 = sns.boxplot(x=z_cut, y='MAG_ABS_R', hue='UV_class', notch=True, data=bxplt, palette='PRGn')
plt.xlim(0,bins[[ratio_uvup_redseq!=0]].size)
plt.ylabel("M$_r$", fontsize=20)
plt.xlabel("maximum redshift", fontsize=20)
plt.tick_params('both', labelsize='15')
plt.legend(legend)
plt.gca().invert_yaxis()
plt.show()
```

If you could help me change this, it would be highly helpful, thanks!

**Comment by mwaskom** [comment]
You need to pass the right handles, here's an example you can generalize.

```python
tips = sns.load_dataset("tips")
ax = sns.boxplot(x="day", y="total_bill", hue="sex", data=tips)
handles, _ = ax.get_legend_handles_labels()
ax.legend(handles, ["Man", "Woman"])
```

**Comment by mdastro** [comment]
Thank you very much, it worked perfectly!

**Comment by wyhfrank** [comment]
Thanks @mwaskom, this works like a charm! But I have a question: how do you know that `Man` comes before `Woman`? And how does this apply to other categorical data? Thanks!

**Comment by zgormez** [comment]
> Thanks @mwaskom, this works like a charm! But I have a question: how do you know that `Man` comes before `Woman`? And how does this apply to other categorical data? Thanks!

what about this code: 
legend_texts=df[hue].unique()
