### ISSUE TITLE
FacetGrid and tsplot incompatibility

### ISSUE THREAD

**Issue by ababino** [mwaskom/seaborn#721]
Dear all,
first of all thanks for this marvelous package. I was trying to use FacetGrid with tsplot and I  got this error:

```
/usr/local/lib/python2.7/dist-packages/seaborn/axisgrid.pyc in map_dataframe(self, func, *args, **kwargs)
    790 
    791             # Draw the plot
--> 792             self._facet_plot(func, ax, args, kwargs)
    793 
    794         # Finalize the annotations and layout

/usr/local/lib/python2.7/dist-packages/seaborn/axisgrid.pyc in _facet_plot(self, func, ax, plot_args, plot_kwargs)
    808 
    809         # Draw the plot
--> 810         func(*plot_args, **plot_kwargs)
    811 
    812         # Sort out the supporting information

/usr/local/lib/python2.7/dist-packages/seaborn/timeseries.pyc in tsplot(data, time, unit, condition, value, err_style, ci, interpolate, color, estimator, n_boot, err_palette, err_kws, legend, ax, **kwargs)
    324         kwargs.setdefault("linestyle", ls)
    325         label = cond if legend else "_nolegend_"
--> 326         ax.plot(x, central_data, color=color, label=label, **kwargs)
    327 
    328     # Pad the sides of the plot only when not interpolating

TypeError: plot() got multiple values for keyword argument 'label'
```

I think that the problem is that tsplot doesn't accept label as keyword argument. I fixed this adding label=None to the arguments of tsplot an then I changed this lines in timeseries.py:

```
325        if label is None:
326            label = cond if legend else "_nolegend_"
```

Now my plots works perfectly but I'm not sure if my solution is appropriate.

I hope this to be useful

**Comment by mwaskom** [comment]
Are you using a `hue` level in `FacetGrid`, or are you passing a `condition` variable to `tsplot`. They'd both do the same thing, but I would think maybe you'd see the error one way or not the other way. I forget which, though I have made faceted tsplots successfully before.

**Comment by ababino** [comment]
I've try the tree alternatives --one, the other and both. I got the same error. Strange... sorry for not supplying data for reproducing the error. I will try to reproduce it with the example dataset.

**Comment by ababino** [comment]
Ok, if I run this

```
import seaborn as sns
from matplotlib import pyplot as plt
g = sns.FacetGrid(gammas)
g = sns.FacetGrid(gammas, hue='ROI')
g.map_dataframe(sns.tsplot, time="timepoint", unit="subject", value="BOLD signal")
```

I got the "TypeError: plot() got multiple values for keyword argument 'label'" and I got this figure:

![figure_1](https://cloud.githubusercontent.com/assets/5031592/10235744/9b8d6552-6875-11e5-8edd-8235958e7aa3.png)


If I run this:

```
import seaborn as sns
from matplotlib import pyplot as plt
g = sns.FacetGrid(gammas)
g.map_dataframe(sns.tsplot, time="timepoint", unit="subject", value="BOLD signal", condition="ROI")
plt.show()
```

I got this image

![figure_2](https://cloud.githubusercontent.com/assets/5031592/10235751/aed8ac70-6875-11e5-9206-0de129d7e7b3.png)

Which is beter but doesn't have the right colors.

With my solution I get this image

![figure_3](https://cloud.githubusercontent.com/assets/5031592/10235868/9fb7a3b2-6876-11e5-9261-e6140c164844.png)

Which has the correct colors but it is cut at timepoint 3, I don't know why. Also, this last figure lacks of labels.

**Comment by mwaskom** [comment]
Only thing you're missing is that you have to specify a color palette to override the fact that `FacetGrid` is specifying a color:

```
g = sns.FacetGrid(gammas)
g.map_dataframe(sns.tsplot, time="timepoint", unit="subject",
                value="BOLD signal", condition="ROI", color="deep") 
```

**Comment by ababino** [comment]
Oh, thanks! 
Any way, it was not obvious for me how to solve it. You could consider implement my solution (or a similar one) or add a warning that help us how to deal with this. 

An other problem (or missing feature) that I found with sns.tsplot is that I couldn't find how to set the hue order. Is it possible? That is something that is implemented in FacetGrid.

Thanks a lot!

**Comment by mwaskom** [comment]
No, sorry.
