### ISSUE TITLE
Violin plot: warning with matplotlib 1.4.3

### ISSUE THREAD

**Issue by mhooreman** [mwaskom/seaborn#723]
Hello,

Since the weekly upgrade of my python libraries, I get the following warning when building violin plots:

    /usr/local/lib/python3.4/dist-packages/matplotlib/collections.py:590:
        FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
            if self._edgecolors == str('face'):

I was expecting this to come from an upgrade of matplolib, but it was not upgraded. So, I don't really know from which upgrade it comes. Here are the upgrades I've made:
- Pillow: 2.9.0 -> 3.0.0
- XlsxWriter: 0.7.3 -> 0.7.5
- numpy: 1.9.3 -> 1.10.0
- path.py: 8.1.1 -> 8.1.2
- pexpect: 3.3 -> 4.0.1
- psutil: 3.2.1 -> 3.2.2
- requests: 2.7.0 -> 2.8.0

The following code can reproduce the issue (ipython):

    import numpy as np
    import pandas as pd
    import seaborn as sns
    %matplotlib inline
    data = pd.DataFrame({
        'v': np.random.normal(size=1000),
        'g': np.repeat(('a', 'a', 'b', 'b'), 250),
        'h': np.repeat(('A', 'B'), 500)
    })
    sns.violinplot(data=data, x='g', y='v', hue='h')

Best regards.

**Comment by mwaskom** [comment]
I think it's a warning raised by numpy, but in either case, the code itself seems to be in matplotlib?

**Comment by mhooreman** [comment]
Indeed, you're right.

To be honnest, I tought it was raised from matplotlib, and then I had to update the ticket when I've discovered that mpl was not upgraded. That's why the ticket title is not 100% accurate...

Best regards.

**Comment by mwaskom** [comment]
I suppose my point is that it's not clear what the action is on the seaborn side of things..

**Comment by mhooreman** [comment]
True.

I've tried to debug it, but ...

**Comment by mwaskom** [comment]
There's nothing to debug, there's just some code in matplotlib that is triggering a warning in numpy 1.10. It's easy to see that it happens when using matplotlib directly:

```
import matplotlib.pyplot as plt
plt.fill_between([0, 1], [0, 1])

<matplotlib.collections.PolyCollection at 0x106a304a8>
/Users/mwaskom/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):
```

**Comment by mhooreman** [comment]
Thanks.
