### ISSUE TITLE
Option for not plotting top right corner of pair plot

### ISSUE THREAD

**Issue by orianac** [mwaskom/seaborn#725]
It isn't clear in the documentation whether it possible to not plot the top right corner of a pair plot (see example below). If it is possible can we clarify? And if it's not possible, how hard would it be to add that feature?

![scatter_plot_matrix](https://cloud.githubusercontent.com/assets/5796208/10354131/ee6089f8-6d11-11e5-86f2-940e571a9465.png)

**Comment by mwaskom** [comment]
Not possible; moderately hard.

**Comment by mwaskom** [comment]
Technically that's the upper triangle, not the upper "corner", which suggests just the axes at (0, -1)

**Comment by orianac** [comment]
Is that a feature you would be open to adding to seaborn?

**Comment by mwaskom** [comment]
It is not something I am opposed to, but it is not a priority.
