### ISSUE TITLE
FacetGrid fails to plot single column plots

### ISSUE THREAD

**Issue by clintval** [mwaskom/seaborn#728]
I often have data with many categories and need wide subplots (think barplots with a lot of categorical information). I would love to then plot a single column FacetGrid yet whenever I specify col_wrap=1 the data is only plotted in the top first subplot (and sometimes, randomly with error bars on the plotted data and no x-labels on ONLY the top first subplot). Here is a simple example:

    import seaborn as sns
    import matplotlib.pyplot as plt
    tips = sns.load_dataset("anscombe")
    grid = sns.FacetGrid(tips, col="dataset", col_wrap=1)
    grid = grid.map(sns.regplot, "x", "y")
    plt.savefig("test.png", format="png")

![test](https://cloud.githubusercontent.com/assets/4634699/10408944/276ba99c-6edb-11e5-9aac-d179be893d1d.png)

I am not familiar enough with the seaborn backend to suggest a fix, just wondering if the team is aware of this. Here is an example of my data showing up with a few of the other odd behaviours:

    grid = sns.FacetGrid(spectrums, col="Name", col_wrap=1)
    grid.map(sns.barplot, "Trinucleotide", "Proportion")
    plt.savefig("test.png", format="png")

![test](https://cloud.githubusercontent.com/assets/4634699/10408983/4da3e740-6edc-11e5-8251-477d4266bdc5.png)

**Comment by mwaskom** [comment]
That is weird behavior, I'm not sure what's going on.

However, to accomplish what you want, you should use `row=dataset`.
