### ISSUE TITLE
pairplot legend - matplotlib 1.5.0.rc2

### ISSUE THREAD

**Issue by thomas-haslwanter** [mwaskom/seaborn#729]
The legend in the pairplot is now plotted inside/on top of  the axes, not besides it:

    df = sns.load_dataset("iris")
    sns.pairplot(df, hue="species", size=2.5)    

This problem only happens with matplotlib 1.5.0.rc2, but I don't know if it is a seaborn problem or one by matplotlib.

![pairplot_problem](https://cloud.githubusercontent.com/assets/1530437/10416312/a71ad478-7012-11e5-892d-32f153696841.png)

**Comment by stonebig** [comment]
I don't have this issue with matplotlib 1.5.rc2, and recent seaborn
![seaborn07_matplotlib15rc2](https://cloud.githubusercontent.com/assets/4312421/10416420/377c437c-7017-11e5-8a49-0032a5295ca2.GIF)

**Comment by mwaskom** [comment]
I think this is an issue with the Mac OSX backend. I'd suggest trying a different one.

**Comment by thomas-haslwanter** [comment]
I have tested it again, and it only seems to happen when I run the code within my IDE (I am using Wing). It plots correctly when I run it in ipython, or when I execute the standalone script.
I therefore assume it is a problem with Wing, and close the issue. (I will report it to the Wing dev-team if it persists with the release version of matplotlib 1.5.0)

**Comment by Phlya** [comment]
Just want to raise this issue again. With Seaborn 0.6, matplotlib 1.5 on Ubuntu 14.04 I get this problem with multiple backends. `inline` backend is unaffected, but all other ones that I tried - are. I run python 2.7 in Jupyter notebook. Let me know if you need more information.

**Comment by thomas-haslwanter** [comment]
I want to confirm Phyla's comment: the same problem as described originally also happens on my system, on multiple backends (png-files, qt).
Win 10, matplotlib 1.5.0, seaborn 0.6.0, Python 3.5.1

**Comment by Phlya** [comment]
Thank you for reopening and confirming, @thomas-haslwanter!

**Comment by mwaskom** [comment]
OK, but variable behavior across matplotlib backends means that it's still a matplotlib issue.

**Comment by Phlya** [comment]
@mwaskom ageed, but could you please report it as such to matplotlib devs then?

**Comment by nlacombe** [comment]
This is actually a lot easier than you'd think it is. It's simply a default setting in the actual matplot output. Just go to the configure subplot button at the top of your output window, and lower your right border upper limit a little and it'll be fixed.

![example](https://cloud.githubusercontent.com/assets/16618405/20775740/70fc33d6-b72a-11e6-9712-03c1e075f994.png)
