### ISSUE TITLE
add the ability to set projections on JointGrid

### ISSUE THREAD

**Issue by a86c6f7964** [mwaskom/seaborn#734]
I have lat/lng values that I would like to be able to plot into a JointGrid. It would be awesome if I could set a projection for it. I can plot a scatter like
```
ax = plt.axes(projection=ccrs.Mercator())
ax.scatter(input.longitude, input.latitude, transform=ccrs.PlateCarree())
```
and it will plot the points correctly. but when I try
```
ax = plt.axes(projection=ccrs.Mercator())
g = sns.JointGrid(x='longitude', y='latitude', data=input)
g.plot_joint(plt.scatter, transform=ccrs.PlateCarree())
```
I get
```
ValueError: Axes should be an instance of GeoAxes, got <class 'matplotlib.axes._subplots.AxesSubplot'>
```

I assume it is because I need to be able to pass the projection param to https://github.com/mwaskom/seaborn/blob/v0.6/seaborn/axisgrid.py#L1605

**Comment by mwaskom** [comment]
For the marginal plots, presumably the projection would only be applied to one of the two axes? Does matplotlib know how to handle that?

**Comment by mwaskom** [comment]
ps it is obnoxious to phrase a feature request as an imperative

**Comment by a86c6f7964** [comment]
@mwaskom yes it would need to apply the projection to only 1 axis. I am not entirely positive if matplotlib can do that. 

for your ps, are you talking about the subject line? I don't mean to be obnoxious sorry, what is a more reasonable way to phrase it. I was trying to make it short and concise. Would it be better to say "potentially add the ability to ..."

**Comment by shoyer** [comment]
It's not clear to me how you can correctly calculate the marginal plots from the projection. Does cartopy support this? Perhaps @pelson could clarify.
