### ISSUE TITLE
sns.distplot breaks with many zeros

### ISSUE THREAD

**Issue by twiecki** [mwaskom/seaborn#735]
```python
sns.distplot(np.concatenate([np.zeros(100), np.ones(10)]))
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-9543570a22a7> in <module>()
----> 1 sns.distplot(np.concatenate([np.zeros(100), np.ones(10)]))

/home/wiecki/miniconda3/lib/python3.4/site-packages/seaborn/distributions.py in distplot(a, bins, hist, kde, rug, fit, hist_kws, kde_kws, rug_kws, fit_kws, color, vertical, norm_hist, axlabel, label, ax)
    210         hist_color = hist_kws.pop("color", color)
    211         ax.hist(a, bins, orientation=orientation,
--> 212                 color=hist_color, **hist_kws)
    213         if hist_color != color:
    214             hist_kws["color"] = hist_color

/home/wiecki/miniconda3/lib/python3.4/site-packages/matplotlib/axes/_axes.py in hist(self, x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, **kwargs)
   5676             # this will automatically overwrite bins,
   5677             # so that each histogram uses the same bins
-> 5678             m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
   5679             m = m.astype(float)  # causes problems later if it's an int
   5680             if mlast is None:

/home/wiecki/miniconda3/lib/python3.4/site-packages/numpy/lib/function_base.py in histogram(a, bins, range, normed, weights, density)
    247                 n.imag += np.bincount(indices, weights=tmp_w.imag, minlength=bins)
    248             else:
--> 249                 n += np.bincount(indices, weights=tmp_w, minlength=bins).astype(ntype)
    250 
    251         # We now compute the bin edges since these are returned

ValueError: operands could not be broadcast together with shapes (10,) (11,) (10,) 

> /home/wiecki/miniconda3/lib/python3.4/site-packages/numpy/lib/function_base.py(249)histogram()
    248             else:
--> 249                 n += np.bincount(indices, weights=tmp_w, minlength=bins).astype(ntype)
    250 
```

**Comment by mwaskom** [comment]
Looks like numpy breaks with many zeros :)

**Comment by stavskal** [comment]
I have also encountered this problem as well. Is there any way to work around it?

**Comment by mwaskom** [comment]
I actually can't reproduce this issue. I tried on the Python 3 environment at tmpnb.org. Does someone want to share the version of numpy they are using?

**Comment by stavskal** [comment]
I am using python 2.7. Will post detailed code to reproduce tomorrow.

**Comment by mwaskom** [comment]
I can't reproduce it on Python 2 either. Again, as the error is raised from numpy, the version of that library is probably the most relevant piece of information.

**Comment by stavskal** [comment]
I am using numpy : 1.10.1

**Comment by stavskal** [comment]
The following script produces the aforementioned error:

import matplotlib.pyplot as pyp
import numpy as np
import seaborn as sns

sns.set_style('darkgrid')
sns.set(color_codes=True)

testOnes = np.ones(100)
testZeros = np.zeros(5)

con = np.concatenate((testZeros,testOnes), axis=0)
x=[0,1]
xtic=['zero', 'one']

ax = sns.distplot(con, kde=False)
fig = ax.get_figure()	
fig.savefig('ttttt.png')

**Comment by stavskal** [comment]
File "/home/tabrianos/Desktop/Thesis/Database/venv/local/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5678, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/home/tabrianos/Desktop/Thesis/Database/venv/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 249, in histogram
    n += np.bincount(indices, weights=tmp_w, minlength=bins).astype(ntype)
ValueError: operands could not be broadcast together with shapes (10,) (11,) (10,)

**Comment by mwaskom** [comment]
Again, I can't replicate this behavior. I tried your script exactly and got

![image](https://cloud.githubusercontent.com/assets/315810/11094123/d1a2da4a-8842-11e5-9945-57658960c331.png)

which is what I think we want.

Can you also please check that it is an issue in seaborn by trying to plot with matplotlib directly? i.e. in your script, `plt.hist(con)`.

**Comment by stavskal** [comment]
![tttt123](https://cloud.githubusercontent.com/assets/11562404/11094292/33e8626e-888f-11e5-915d-9e81369da110.png)

**Comment by stavskal** [comment]
this is what I get with plt.hist(con) when replacing sns.distplot on above code

**Comment by mwaskom** [comment]
OK, what version of seaborn are you using.

**Comment by stavskal** [comment]
0.16.1

**Comment by mwaskom** [comment]
That doesn't sound right.

**Comment by stavskal** [comment]
I once encountered someone saying on stackoverflow that pip installation of matplotlib is problematic. Maybe that's the real problem?

**Comment by stavskal** [comment]
For example plot.show() does not work for me. Maybe these two are somehow related

**Comment by mwaskom** [comment]
I think #771 fixes this.

**Comment by msto** [comment]
Hi,

Despite the closure of the issues, I'm actually encountering the same problem as @twiecki and @stavskal. I hit a "could not be broadcast together with shapes (43,) (44,) (43,)" error in some of my own data and found this thread. 

I duplicated the error after running the command @twiecki originally posted. I'm on OS X 10.10.5, running Python 3.5.1 with Numpy 1.10.2 and Seaborn 0.6.0. As far as I can tell, I'm up to date across the board, yet I'm still getting the error. Any ideas on what's going on or suggestions for further tests I can run? Not sure what the root cause is, but looks like something is creating an off-by-one error based on the sizes of the three shapes.

    In [7]: sns.distplot(np.concatenate([np.zeros(100), np.ones(10)]))
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-7-9543570a22a7> in <module>()
    ----> 1 sns.distplot(np.concatenate([np.zeros(100), np.ones(10)]))
    
    /usr/local/bin/miniconda3/lib/python3.5/site-packages/seaborn/distributions.py in distplot(a, bins, hist, kde, rug, fit, hist_kws, kde_kws, rug_kws, fit_kws, color, vertical, norm_hist, axlabel, label, ax)
        210         hist_color = hist_kws.pop("color", color)
        211         ax.hist(a, bins, orientation=orientation,
    --> 212                 color=hist_color, **hist_kws)
        213         if hist_color != color:
        214             hist_kws["color"] = hist_color
    
    /usr/local/bin/miniconda3/lib/python3.5/site-packages/matplotlib/axes/_axes.py in hist(self, x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, **kwargs)
       5676             # this will automatically overwrite bins,
       5677             # so that each histogram uses the same bins
    -> 5678             m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
       5679             m = m.astype(float)  # causes problems later if it's an int
       5680             if mlast is None:
    
    /usr/local/bin/miniconda3/lib/python3.5/site-packages/numpy/lib/function_base.py in histogram(a, bins, range, normed, weights, density)
        247                 n.imag += np.bincount(indices, weights=tmp_w.imag, minlength=bins)
        248             else:
    --> 249                 n += np.bincount(indices, weights=tmp_w, minlength=bins).astype(ntype)
        250
        251         # We now compute the bin edges since these are returned
    
    ValueError: operands could not be broadcast together with shapes (10,) (11,) (10,)
    In [8]: 2016-01-07 18:07:24.703 python[47908:6630882] setCanCycle: is deprecated.  Please use setCollectionBehavior instead

**Comment by msto** [comment]
I'm attaching the data in which I'm encountering the error.

[test_freq.txt](https://github.com/mwaskom/seaborn/files/81885/test_freq.txt)

**Comment by mwaskom** [comment]
> I duplicated the error after running the command @twiecki originally posted. I'm on OS X 10.10.5, running Python 3.5.1 with Numpy 1.10.2 and Seaborn 0.6.0. As far as I can tell, I'm up to date across the board, yet I'm still getting the error. 

Seaborn 0.6.0 predates the fix; you need to use master to avoid it (or just specify a number of bins)...
