### ISSUE TITLE
How to speed up heatmap or clustermap function when I have a large data set?

### ISSUE THREAD

**Issue by BioNinja** [mwaskom/seaborn#736]
I love heatmap and clustermap function. They're pretty awsome. However, these two function are quite slow when I have large data sets (e.g. a data set with 8000 rows and 14 columns, it cost almost 4 mins ). And these function is quite slower than R.

**see here**
![1](https://cloud.githubusercontent.com/assets/5889336/10599206/4a1d7fa6-7732-11e5-80f3-8c1c6faee42e.PNG)

Is there any good way to speed up? (For example, implement a method to use multi-cores of CPU)
Thanks

**Comment by mwaskom** [comment]
I think some recent PRs into master make the plotting faster. (Though with 8000 rows, you realize that you're getting an inaccurate representation of your data, right?)

**Comment by lukauskas** [comment]
Yup, @BioNinja  try running the same code with the most-recent changes in master.
Particularly, #683,  #685, and #690 in combination should speed things up significantly.

**Comment by BioNinja** [comment]
Cool, thanks for your great work, mwaskom and Iukauskas.

**Comment by dcontris** [comment]
@mwaskom 
I, too, really love this function. Thanks so much!

My only question is what do you mean exactly by the quote below?:

> (Though with 8000 rows, you realize that you're getting an inaccurate representation of your data, right?)

**Comment by mwaskom** [comment]
How many pixels do you have?

**Comment by dcontris** [comment]
@mwaskom 
Ahh... I see where you're going with this.
If I make the length of the plot 8000 pixels, and then scroll through it, it should be represented accurately, correct?

**Comment by mwaskom** [comment]
In general, yes.

**Comment by dcontris** [comment]
Thanks again for all you do!
