### ISSUE TITLE
KDE for cyclic endpoints

### ISSUE THREAD

**Issue by DamienIrving** [mwaskom/seaborn#737]
I've got some data that has cyclic end points (the x-axis is longitude and hence 0 and 360 are the same point), but as far as I can tell `seaborn.kdeplot` doesn't have an option to specify cyclic end points. Could this be a possible enhancement in future releases?

**Comment by mwaskom** [comment]
It would have to be available in the underlying libraries that actually compute the density estimate. Seaborn just plots it.
