### ISSUE TITLE
Pointplot location with specified hue is inconsistent with other factorplots

### ISSUE THREAD

**Issue by Phlya** [mwaskom/seaborn#738]
Position of points in pointplot are inconsistent with position of points of stripplot or boxes of boxplot. See example:
![bug](https://cloud.githubusercontent.com/assets/2895034/10677394/012a9fb2-7904-11e5-9f8f-99331033c7d1.png)

Code:
```python
sns.pointplot(x='Day', y='Value', hue='Condition', data=data, dodge=True, join=False)
sns.stripplot(x='Day', y='Value', hue='Condition', data=data, jitter=True)
plt.show()
```

(Data doesn't matter)

I use python 2.7.6, matplotlib 1.4.3 and seaborn 0.6.

Any advice on how to make stripplot overlayed with median and errorbars is appreciated.

**Comment by mwaskom** [comment]
`dodge` also accepts a scalar value.

**Comment by Phlya** [comment]
OK, thanks! Should I just find and optimal number by hand?

**Comment by mwaskom** [comment]
Probably — you can look in the code to see how the offset value for the stripplots is chosen and then use that. It's just a simple function of the number of categories.

**Comment by Phlya** [comment]
OK. And you don't think this requires fixing in seaborn itself?

**Comment by Phlya** [comment]
OK... Can't stop thinking "There has to be a better way", but have to live with this for now, I guess.
