### ISSUE TITLE
Strange behavior while interacting with Pairgrids

### ISSUE THREAD

**Issue by isomerase** [mwaskom/seaborn#743]
Here's my pairgrid:

    g = sns.PairGrid(df)
    g.map_upper(plt.scatter)
    g.map_lower(sns.kdeplot)
    g.map_diag(sns.kdeplot)
    plt.subplots_adjust(top=0.9)
    g.set(xlim=(-0.8, 0.8), ylim=(-0.8, 0.8))

Result:
![Unzoomed](https://cloud.githubusercontent.com/assets/5415776/10777981/4b8ef980-7cde-11e5-9ee1-f5df089c52f8.png)

Figure after zooming:
![zoomed](https://cloud.githubusercontent.com/assets/5415776/10777980/4b6ffbca-7cde-11e5-9c7d-9fc922058974.png)

The left column updates as I expect, the far right+center figure updates, but the top+center figure remains unchanged.

Similarly, zooming into the top+center figure doesn't properly update the top left or center left figures:
![zoom topcenter](https://cloud.githubusercontent.com/assets/5415776/10778059/f8f635c0-7cde-11e5-957b-90d157d736fa.png)

**Comment by mwaskom** [comment]
Getting the diagonal axes to have a different y axis involves adding additional axes objects that problem break interactivity. I'd try it without using `map_diag`.

**Comment by isomerase** [comment]
Oh, they do have a separate axes object. Separate discussion, but is it possible then to have a different y-axis label for the diagonal?

**Comment by mwaskom** [comment]
No, sorry.
