### ISSUE TITLE
Add support for beeswarm

### ISSUE THREAD

**Issue by DizietAsahi** [mwaskom/seaborn#744]
there is a feature that I find useful in R called beeswarm that allows to plot a scatterplot with jitter, but where the jitter is not random, but instead depends on the density of points. It gives a nice visual representation of the distribution of the data.

It is a different and complementary way to represent the data in addition to boxplots and violinplot. They could also be combined advantageously. For example, in violinplots there is a way to plot the datapoints with inner='points' but they often end up overlapping. Adding a inner='beeswarm' for example would allow plotting the points on top of the violinplot and preventing their overlap.

![image](https://cloud.githubusercontent.com/assets/13396853/10815357/cd54db76-7e2b-11e5-9922-b3e0ac154c57.png)

**Comment by DizietAsahi** [comment]
PS:
There is a python package to plot beeswarms in matplotlib: https://github.com/mgymrek/pybeeswarm

**Comment by mwaskom** [comment]
Working on it.
