### ISSUE TITLE
tsplot legend doesn't show line color/style

### ISSUE THREAD

**Issue by ph0o** [mwaskom/seaborn#745]
Hi everyone,

i encountered a problem with the legend of a tsplot. The following code produces a output, where the legend doesn't contain any information about the the unterlying line.
        
        fig, ax = plt.subplots()
        ax1 = ax.twinx()
        ax1.grid(b=False)

        #respone-time
        data_matrix_rt = np.zeros((160, len(self.data)))
        for id, frame in enumerate(self.data):
            data_matrix_rt[:, id] = frame['responsetime'].values[10:170]/1e6

        ax.grid(b=False)
        ax.set_ylabel('responsetime (ms)')
        hax = sns.tsplot(data=data_matrix_rt, ax=ax, time=[4, 8, 12, 16, 20, 24, 32, 40], ci=[95, 99],
                   err_style=['ci_band', "ci_bars"], color=c1, linestyle='-')

        #throughput
        data_matrix_tp = np.zeros((160, len(self.data)))
        for id, frame in enumerate(self.data):
            data_matrix_tp[:, id] = frame['responsetime'].resample('1S', how='size').values[10:170]

        ax1.set_ylabel('throughput msg/s')
        hax1 = sns.tsplot(data=data_matrix_tp, ax=ax1, time=[4, 8, 12, 16, 20, 24, 32, 40], ci=[95, 99],
                   err_style=['ci_band', "ci_bars"], color=c2, linestyle='--')

        sns.plt.legend([hax, hax1], labels=["responsetime", "throughput"])
        sns.plt.show()

This code produces following result. Did i something wrong, or is there a bug?

Thanks in advance!

![throughput](https://cloud.githubusercontent.com/assets/400331/10846267/a379f3b6-7f0e-11e5-88d6-2320f9df1c90.png)

**Comment by mwaskom** [comment]
`tsplot` returns an `Axes` object.

**Comment by ph0o** [comment]
Hm, so i'm sorry :). But how can i set then the legend? if i use 'condition' in both cases:

         sns.tsplot(data=data_matrix_tp, condition='throughput', ax=ax1, time=[4, 8, 12, 16, 20, 24, 32, 40], ci=[95, 99],err_style=['ci_band', "ci_bars"], color=c2, linestyle='--')

i get following results:
![throughput](https://cloud.githubusercontent.com/assets/400331/10850414/ce372152-7f25-11e5-9820-8ddcc65e9caa.png)

**Comment by mwaskom** [comment]
Just draw the legends for the two twinned axes in different places.

**Comment by mwaskom** [comment]
PS this kind of question is really better suited for stackoverflow

**Comment by ph0o** [comment]
Thanks for the hint! Yeah, next time i will post it on stackoverflow - sorry. Keep up the good work!
