### ISSUE TITLE
aspect argument to FacetGrid uses the opposite convention from matplotlib

### ISSUE THREAD

**Issue by shoyer** [mwaskom/seaborn#746]
This is somewhat unfortunate. I'm not entirely sure what we should do about it, though.

matplotlib
-------------

```
plt.imshow([[0]], aspect=2)
```
![image](https://cloud.githubusercontent.com/assets/1217238/10860467/c74fc722-7f25-11e5-92ac-ac1c52df1079.png)

or 
```
plt.plot()
plt.gca().set_aspect(2)
```
![image](https://cloud.githubusercontent.com/assets/1217238/10860496/31ebae7a-7f26-11e5-886d-aa97ddde60a1.png)

seaborn
---------
```
sns.FacetGrid({}, aspect=2)
```
![image](https://cloud.githubusercontent.com/assets/1217238/10860484/f7a546d6-7f25-11e5-9090-332238e37248.png)

**Comment by mwaskom** [comment]
Eek. Is the matplotlib aspect in figure or data coordinates, by the way?

**Comment by shoyer** [comment]
It's an axis level setting so I think it has to be data coordinates. (Which I think is the intent with FacetGrid, but not exactly the case due to matplotlib's messiness.)

**Comment by mwaskom** [comment]
No, the FacetGrid aspect is just size of the thing in inches, it's invariant to the scale of the data being plotted. So at least they are doing different things?

**Comment by mwaskom** [comment]
FWIW I think the implementation in seaborn is "correct", assuming people correctly interpret `aspect=a` as giving an aspect ratio of a:1.
