### ISSUE TITLE
Asymetric Violin Plot Bugged

### ISSUE THREAD

**Issue by mdastro** [mwaskom/seaborn#749]
I have tested over and over again the example grouped_violinplots.py . I have used as input my own data and the example tips.csv.
Seaborn does not read my file at all. There is a problem with the command "sns.load_dataset("bla")" which ONLY reads "bla"=="tips" -- even when I erase the tips.csv file from my machine.
It would be really kind if you checked this problem, because I really need to create an asymetric violin plot ASAP. Otherwise, I will be forced to use other packages/programming languages.
Thank you!

**Comment by mmagnuski** [comment]
`load_dataset` is meant to read just some example datasets, not any dataset. If you want to read your data as a DataFrame, use pandas:
```python
import pandas as pd
df = pd.read_csv('your_file.csv')
```
Take a look at pandas [documentation](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html)

**Comment by mdastro** [comment]
Hi @mmagnuski , this looks really strange because:
1) this is not document in the seaborn package;
2) if you use "sns.load_dataset(file_name)" it only reads the embedded example tips.csv. I know this because even when you delete it from your directory, the example still works. So, it must be calling an internal file "tips.csv". 
3) I have tried to do this by defining the variables by calling the file using numpy.loadtxt and it still does not work.

I wonder if the embedded example is not creating a problem with whatever dataset you want to read.

**Comment by mwaskom** [comment]
The docstring for `load_dataset` reads:

```
def load_dataset(name, cache=True, data_home=None, **kws):

    Load a dataset from the online repository (requires internet).
    
    Parameters
    ----------
    name : str
        Name of the dataset (`name`.csv on
        https://github.com/mwaskom/seaborn-data).  You can obtain list of
        available datasets using :func:`get_dataset_names`
    cache : boolean, optional
        If True, then cache data locally and use the cache on subsequent calls
    data_home : string, optional
        The directory in which to cache data. By default, uses ~/seaborn_data/
    kws : dict, optional
        Passed to pandas.read_csv
```

It is not a generic function for reading data from disk. I would recommend you read @mmagnuski's helpful link on how to read data using Pandas.

**Comment by mdastro** [comment]
Hi @mmagnuski, I don't want to be annoying, but it seems to me that you are not really paying attention to the problem. I have tried to use a similar file in terms of data, but it does not work. When I use your default example, it works like magic. However, it still works even when I suppress the data file named tips.csv. Therefore, when I compile the program, it still works -- and shouldn't, right? The documentation does not leave it clear. In the webpage, I have tried to understand how seaborn works and it wasn't even clear that it was supposed to be a .csv file. I had to scoop the examples in github. I have been using the online platform getdatajoy.com and it has been working fine over there (I have installed all the required packages, including seaborn, successfully). If you wish to check what has been my problem, I would be more than willing to share my file with you.

**Comment by mmagnuski** [comment]
Dear Maria, I am not engaged in seaborn, development, @mwaskom is the developer of this great package.
I must say I do not really understand what your problem is now. `load_dataset` downloads the example data from the internet, you never need to use it for your own data. If you are referring to `pandas.read_csv` - the name suggests it is for reading csv files. If read_csv is not working for you - you can post an issue on pandas github repo.

**Comment by mwaskom** [comment]
> Hi @mmagnuski, I don't want to be annoying, but it seems to me that you are not really paying attention to the problem. I have tried to use a similar file in terms of data, but it does not work.

You can't just say "it does not work" and expect someone to understand what issue you are having. You need to give the exact code that you are running and the exact output you see. With that said, from what you have described so far, it sounds like you are still trying to use `seaborn.load_dataset` to load you own data. As we have now said several times, that is not expected to work.

**Comment by mdastro** [comment]
Thank you guys, I understood the problem. I have seen the examples that use the command    `seaborn.load_dataset` and it took me a while to really understand that I should use the pandas load command. It seems to me a bit strange that all the examples use the `seaborn.load_dataset` load command instead of the pandas load command. Anyway, I didn't say it just wasn't working; I explicitly described the problem as a loading problem. But no worries. I completely understood it now. Thanks.
