### ISSUE TITLE
spicy will (probably) change call signature of hierarchy.dendrogram

### ISSUE THREAD

**Issue by fredrikw** [mwaskom/seaborn#750]
Scipy is planning to remove the keyword color_list from hierarchy.dendrogram in 0.17 which is making seaboard.clustermap() fail with TypeError: dendrogram() got an unexpected keyword argument 'color_list'. See commit https://github.com/rgommers/scipy/commit/4e7d2410d7d8f03eb1f014d12418836b761fcd62
As far as I can tell, the color_list isn't really used anyway so it shouldn't pose big problems...

**Comment by mwaskom** [comment]
Thanks for the heads up. Even though it was not used, annoying that they are simply removing it so that dependent code breaks, instead of raising a warning for a release or two.

**Comment by mwaskom** [comment]
Closed with #758
