### ISSUE TITLE
Question: how to call categorical plots with list of arrays

### ISSUE THREAD

**Issue by tritemio** [mwaskom/seaborn#751]
I have a list of arrays (one element per category) that I was plotting with violin plots in seaborn < 0.6. Each category (i.e. array) has different number of elements, and elements inside each arrays are independent, so I would not know how to put this dataset in a pandas.DataFrame (there is no "natural" index).

With the new 0.6 API I cannot find a way to plot the dataset.

Example:

```
data = [np.random.randn(10), np.random.randn(7)]
names = ['a', 'b']
```

How can I plot a violin plot with 2 categories 'a' and 'b'?

**Comment by mwaskom** [comment]
`sns.boxplot(data=data)`

**Comment by tritemio** [comment]
Great, thanks! And how do I assign the labels?

**Comment by mwaskom** [comment]
```
ax = sns.boxplot(data=data)
ax.set(xticklabels=names)
```

**Comment by tritemio** [comment]
Ah ok, I was trying to use `x` or `y` in place of the old `names` keyword. But this will do.

I was also using the keyword `colors=['#2ca02c', '#E41A1C']` which does not seem to work anymore. Is it deliberate?

**Comment by mwaskom** [comment]
`palette=['#2ca02c', '#E41A1C']`

**Comment by tritemio** [comment]
You made my day :)

**Comment by tritemio** [comment]
@mwaskom sorry, one last thing, what's the keyword for patch edge width in violin plots? For some reason the line around the patch edge is not displayed anymore in violin plots (python 3.4, matplotlib 1.4.3).

```
a = [np.random.randn(10), np.random.randn(7)]
sns.violinplot(data=a, inner='sticks')
```
![index](https://cloud.githubusercontent.com/assets/4156237/10986236/225f9b4a-83dd-11e5-91cf-c00f76e91cfc.png)

**Comment by mwaskom** [comment]
Pretty sure that's https://github.com/mwaskom/seaborn/issues/678 which is a Python3-specific matplotlib bug.
