### ISSUE TITLE
FutureWarning since matplotlib 1.5.0

### ISSUE THREAD

**Issue by mhooreman** [mwaskom/seaborn#752]
Hello,

Since I have upgraded to matplotlib 1.5.0, I get a future warning while importing seaborn 0.6.0

I guess you already know that, but I didn't found exactly that in the pending issues.

Best regards.

    In [1]: import seaborn as sns
    /usr/local/lib/python3.4/dist-packages/matplotlib/__init__.py:872: UserWarning:
    axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
    warnings.warn(self.msg_depr % (key, alt_key))
    In [2]: import matplotlib as mpl
    In [3]: mpl.__version__
    Out[3]: '1.5.0'
    In [4]: sns.__version__
    Out[4]: '0.6.0'

**Comment by mwaskom** [comment]
That's because it's already been addressed in #739

**Comment by mhooreman** [comment]
Thanks a lot, and sorry for the duplicate.
