### ISSUE TITLE
Bug in timeseries.py

### ISSUE THREAD

**Issue by denniskl** [mwaskom/seaborn#754]
Hi,

there is a bug in the seaborn/timeseries.py starting at line 329:

    # Pad the sides of the plot only when not interpolating
    ax.set_xlim(x.min(), x.max())
    x_diff = x[1] - x[0]
    if not interpolate:
        ax.set_xlim(x.min() - x_diff, x.max() + x_diff)

UnboundLocalError: local variable 'x' referenced before assignment

Cheers,

Dennis

**Comment by mwaskom** [comment]
You did not show your code, but this is probably not a bug, just an unhelpful failure mode when you specify the input data incorrectly.

**Comment by denniskl** [comment]
:) Did you have a look at the timeseries.py? 

I didn't check in detail, but for me it looks like that there are just a few tabs missing ...
