### ISSUE TITLE
Please support markeredges and alpha. 

### ISSUE THREAD

**Issue by soerendip42** [mwaskom/seaborn#757]
Seaborn by default does not add edges to markers e.g. in scatter plots. However, sometimes I find it much more convenient  to plot only the marker edges with transparent face colors. Especially with dense data I find it better because the marker overlap and the sense of the actual density gets lost. 

As a feature request, I would like to ask you to consider to support this feature in future versions.
E.g. add the keywords `markeredgewidth` to functions like `seaborn.lmplot()`.

Also the keyword `alpha` for control of the marker transparency apparently is not supported.

**Comment by mwaskom** [comment]
Use the `scatter_kws` parameter...

**Comment by soerendip42** [comment]
just found it ;-)

**Comment by nbara** [comment]
@mwaskom That would not work with `pointplot`, would it? I'm desperately trying to change marker edge color...
