### ISSUE TITLE
Stacked area plot shows line even if value is zero

### ISSUE THREAD

**Issue by bbirand** [mwaskom/seaborn#759]
I'm plotting a graph with three columns using `dat.plot(kind='area', stacked = True)`. The result is shown here:

![screen shot 2015-11-10 at 6 44 18 pm](https://cloud.githubusercontent.com/assets/334435/11070286/2c680c92-87db-11e5-9de3-4c8ab3565691.png)

The red columns are positive towards the middle of the graph, and are shown appropriately. Yet the red is even shown when the corresponding value is 0 (or NaN). For instance, in the entire second half of this plot, there shouldn't be any red at all. 

Not sure if this is a configurable feature, but at any rate, it's impossible to tell whether the values exist and are small, or they are nonexistent.

**Comment by mwaskom** [comment]
This looks like a question for pandas, not seaborn?
