### ISSUE TITLE
Consider adding an rgb cube plot in addition to palplot

### ISSUE THREAD

**Issue by cheyneh** [mwaskom/seaborn#760]
I've been using [a simple 3d cmap visualization](https://github.com/cheyneh/colorcube) when picking color palettes, and found it useful particularly when dealing with a potentially color deficient audience. It might be nice to add this alongside the current palplot function. Would be relatively simple to implement.

**Comment by mwaskom** [comment]
IMO the [viscm](https://github.com/matplotlib/viscm) package is very nice and comprehensive for this sort of thing.

**Comment by cheyneh** [comment]
Agreed, but viscm seems like overkill for simple palette viewing. I use the cube alongside palplot for taking a quick look at a palette (especially as palplot doesn't support cmaps), and thought others might be interested.

**Comment by mwaskom** [comment]
I wouldn't be in favor of adding an rgb cube because the dimensions of the rgb space (and distances measured within it) aren't very relevant for understanding the perceptual properties of a colormap. I would encourage people to use a tool like viscm which provides a better representation.
