### ISSUE TITLE
lmplot palette not set when hue=None

### ISSUE THREAD

**Issue by qbilius** [mwaskom/seaborn#761]
Minimal example:

```python
import seaborn as sns
tips = sns.load_dataset('tips')
sns.lmplot(x='total_bill', y='tip', data=tips, palette='Set2')
sns.plt.show()
```
![seaborn_bad](https://cloud.githubusercontent.com/assets/1251889/11088962/7c57b2c6-8866-11e5-986d-07727e461757.png)

Expected behavior can be seen when `sns.set_palette('Set2')` is used:
![seaborn_good](https://cloud.githubusercontent.com/assets/1251889/11088974/87fd5c02-8866-11e5-956f-ef79698ac580.png)

Also works fine if hue is not None.

Seaborn version 0.6.0.

**Comment by mwaskom** [comment]
Yes, this makes sense.
