### ISSUE TITLE
[Feature Request] Tableplots

### ISSUE THREAD

**Issue by zachmayer** [mwaskom/seaborn#762]
I love the [tabplot::tableplot](http://www.inside-r.org/packages/cran/tabplot/docs/tableplot) function in R, and have tried in vain to find something similar in python.  Theres a [package vignette here](https://cran.r-project.org/web/packages/tabplot/vignettes/tabplot-vignette.html), and a scientific [paper about the visualization here (pdf)](http://www.jds-online.com/file_download/379/jds-1108.pdf).

It's basically a bunch of vertically stacked bar charts, but it's a useful way to get an overview of a dataset:
![image](https://cloud.githubusercontent.com/assets/581590/11119614/c9ac4296-8918-11e5-89ce-3c5f0138e2c6.png)

I have no idea if it's appropriate to ask, but I thought tableplots might be a cool data visualization to add to seaborn.  They complement the correlation matrix heatmap, in a way.

**Comment by mwaskom** [comment]
I suspect that whoever invented this really enjoyed playing with sand art as a child.

![image](https://cloud.githubusercontent.com/assets/315810/11124891/08fb452a-891c-11e5-8549-7c9c7ee0e59b.png)

**Comment by zachmayer** [comment]
hahah yes!  That's a spot-on image.

**Comment by mwaskom** [comment]
I can see how this would be useful, but I don't think it's a good fit for seaborn. I would encourage you to develop it as a standalone matplotlib extension package.
