### ISSUE TITLE
[Feature Request] Show SD in seaborn.tsplot() instead of SEM

### ISSUE THREAD

**Issue by cachitas** [mwaskom/seaborn#763]
This issue follows a question posted previously [in stackoverflow](http://stackoverflow.com/questions/33696588/how-to-show-sd-in-seaborn-tsplot-instead-of-sem?noredirect=1#comment55169589_33696588).

Do you think it is possible to implement it in the future? In #450, you say:

> tsplot internals are poorly implemented and untested, so any enhancement is probably going to have to wait until it can be refactored

Could it be done having this feature in mind? How can I help?

**Comment by mwaskom** [comment]
Closed with #1208
