### ISSUE TITLE
tsplot cannot use variables in a DataFrame index

### ISSUE THREAD

**Issue by laprice** [mwaskom/seaborn#77]
Here is a [notebook](http://nbviewer.ipython.org/gist/laprice/8345358) that illustrates the issue.

It appears that if one passes a dataframe with a date based index and no condition; one goes down the [first branch](https://github.com/mwaskom/seaborn/blob/master/seaborn/timeseries.py#L99) in tsplot() in timeseries.py

As near as I can tell, constructing an x near line 99 of timeseries.py would make this work. Trying to determine exactly what goes into that line

```
df.index.values.astype(np.float) 
```

doesn't work, but something near it should. ( or I just need to convert dates to? )

**Comment by shobhitverma** [comment]
Well this happened to me today.
