### ISSUE TITLE
Can't import seaborn

### ISSUE THREAD

**Issue by Meyenhofer** [mwaskom/seaborn#770]
System:
```
MacOsX 10.11.1 (15B42)
Anaconda 2.7 distribution
conda 3.18.5
```

Steps:
```
conda install seaborn
ipython
import seaborn
```

Yield:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-085c0287ecb5> in <module>()
----> 1 import seaborn

//anaconda/lib/python2.7/site-packages/seaborn/__init__.py in <module>()
----> 1 from .rcmod import *
      2 from .utils import *
      3 from .palettes import *
      4 from .linearmodels import *
      5 from .categorical import *

//anaconda/lib/python2.7/site-packages/seaborn/rcmod.py in <module>()
      1 """Functions that alter the matplotlib rc dictionary on the fly."""
      2 import numpy as np
----> 3 import matplotlib as mpl
      4 
      5 from . import palettes

//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py in <module>()
   1129 
   1130 # this is the instance used by the matplotlib classes
-> 1131 rcParams = rc_params()
   1132 
   1133 if rcParams['examples.directory']:

//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py in rc_params(fail_on_error)
    973         return ret
    974 
--> 975     return rc_params_from_file(fname, fail_on_error)
    976 
    977 

//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py in rc_params_from_file(fname, fail_on_error, use_default_template)
   1098         parameters specified in the file. (Useful for updating dicts.)
   1099     """
-> 1100     config_from_file = _rc_params_in_file(fname, fail_on_error)
   1101 
   1102     if not use_default_template:

//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py in _rc_params_in_file(fname, fail_on_error)
   1016     cnt = 0
   1017     rc_temp = {}
-> 1018     with _open_file_or_url(fname) as fd:
   1019         try:
   1020             for line in fd:

//anaconda/lib/python2.7/contextlib.pyc in __enter__(self)
     15     def __enter__(self):
     16         try:
---> 17             return self.gen.next()
     18         except StopIteration:
     19             raise RuntimeError("generator didn't yield")

//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py in _open_file_or_url(fname)
    998     else:
    999         fname = os.path.expanduser(fname)
-> 1000         encoding = locale.getdefaultlocale()[1]
   1001         if encoding is None:
   1002             encoding = "utf-8"

//anaconda/lib/python2.7/locale.pyc in getdefaultlocale(envvars)
    541     else:
    542         localename = 'C'
--> 543     return _parse_localename(localename)
    544 
    545 

//anaconda/lib/python2.7/locale.pyc in _parse_localename(localename)
    473     elif code == 'C':
    474         return None, None
--> 475     raise ValueError, 'unknown locale: %s' % localename
    476 
    477 def _build_localename(localetuple):

ValueError: unknown locale: UTF-8

```

**Comment by Meyenhofer** [comment]
```
echo $UTF-8
-8
```

**Comment by mwaskom** [comment]
It looks to me like the error is getting raised when seaborn tries to import matplotlib.

Can you import matplotlib by itself?

**Comment by jeanodoux** [comment]
Same issue here. I can import matplotlib alone, but seaborn fails when trying to do so.

System
```
Windows 7 x64
Anaconda 2.7 distribution (64 bits)
conda 3.18.5
```

Steps
```
conda install seaborn
python > import seaborn
```

**Comment by mwaskom** [comment]
Weird!

What happens if you import matplotlib first?

**Comment by jeanodoux** [comment]
Actually, my issue was solved after doing `conda install pandas`, which as far as I remember updated my python from 2.7.10.0 to 2.7.10.4. I know it sounds weird but I'm pretty sure that's the only info that showed up after that command line.
Happy to help if I can provide further details.

**Comment by Meyenhofer** [comment]
when I try to import matplotlib

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-82be63b7783c> in <module>()
----> 1 import matplotlib

//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py in <module>()
   1129 
   1130 # this is the instance used by the matplotlib classes
-> 1131 rcParams = rc_params()
   1132 
   1133 if rcParams['examples.directory']:

//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py in rc_params(fail_on_error)
    973         return ret
    974 
--> 975     return rc_params_from_file(fname, fail_on_error)
    976 
    977 

//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py in rc_params_from_file(fname, fail_on_error, use_default_template)
   1098         parameters specified in the file. (Useful for updating dicts.)
   1099     """
-> 1100     config_from_file = _rc_params_in_file(fname, fail_on_error)
   1101 
   1102     if not use_default_template:

//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py in _rc_params_in_file(fname, fail_on_error)
   1016     cnt = 0
   1017     rc_temp = {}
-> 1018     with _open_file_or_url(fname) as fd:
   1019         try:
   1020             for line in fd:

//anaconda/lib/python2.7/contextlib.pyc in __enter__(self)
     15     def __enter__(self):
     16         try:
---> 17             return self.gen.next()
     18         except StopIteration:
     19             raise RuntimeError("generator didn't yield")

//anaconda/lib/python2.7/site-packages/matplotlib/__init__.py in _open_file_or_url(fname)
    998     else:
    999         fname = os.path.expanduser(fname)
-> 1000         encoding = locale.getdefaultlocale()[1]
   1001         if encoding is None:
   1002             encoding = "utf-8"

//anaconda/lib/python2.7/locale.pyc in getdefaultlocale(envvars)
    541     else:
    542         localename = 'C'
--> 543     return _parse_localename(localename)
    544 
    545 

//anaconda/lib/python2.7/locale.pyc in _parse_localename(localename)
    473     elif code == 'C':
    474         return None, None
--> 475     raise ValueError, 'unknown locale: %s' % localename
    476 
    477 def _build_localename(localetuple):

ValueError: unknown locale: UTF-8
```

**Comment by szeitlin** [comment]
I'm having a problem importing seaborn, too, but my situation is a bit different (pip instead of conda, and it's a different error). Should I open a separate issue, or put the details here?

**Comment by mwaskom** [comment]
As seaborn is pure python I would be surprised if it is really an issue importing seaborn, and not one of its dependencies. But seeing the traceback would help pin that down.

**Comment by szeitlin** [comment]
so I think the problem is that pip is refusing to install scipy. I didn't remember scipy being a dependency of seaborn before? Anyway the problem with scipy seems to be a problem with numpy: `numpy.distutils.system_info.NotFoundError: no lapack/blas resources found`

It will take me a bit to track back which version(s) of those will let me install scipy so I can try installing seaborn again. 

numpy==1.9.1
pandas==0.16.2
matplotlib==1.3.1
 
   ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-12-085c0287ecb5> in <module>()
----> 1 import seaborn

/home/vagrant/venv/lib/python3.4/site-packages/seaborn/__init__.py in <module>()
----> 1 from .rcmod import *
      2 from .utils import *
      3 from .palettes import *
      4 from .linearmodels import *
      5 from .categorical import *

/home/vagrant/venv/lib/python3.4/site-packages/seaborn/rcmod.py in <module>()
      3 import matplotlib as mpl
      4 
----> 5 from . import palettes
      6 
      7 

/home/vagrant/venv/lib/python3.4/site-packages/seaborn/palettes.py in <module>()
     12 from .external.six.moves import range
     13 
---> 14 from .utils import desaturate, set_hls_values
     15 from .xkcd_rgb import xkcd_rgb
     16 from .crayons import crayons

/home/vagrant/venv/lib/python3.4/site-packages/seaborn/utils.py in <module>()
      6 
      7 import numpy as np
----> 8 from scipy import stats
      9 import pandas as pd
     10 import matplotlib.colors as mplcol

ImportError: No module named 'scipy'

**Comment by szeitlin** [comment]
update: 

had to install blas and lapack in order to get scipy to install with pip: http://stackoverflow.com/questions/11114225/installing-scipy-and-numpy-using-pip

and then scipy installation still failed. which may be a bug, or I may have to compile from source. or it may be because I'm using python 3.4 (?). 

so I guess my question for you is, do you really want seaborn to be dependent on scipy, which is dependent on fortran?

**Comment by mwaskom** [comment]
Yes, seaborn needs scipy for statistical routines. Installing scipy from source can be tricky with on a mac, but there are plenty of other options these days, like using conda or pip wheels.

**Comment by szeitlin** [comment]
yeah in my case conda is not an option since we use pip for development and deployment. The problems I'm having have nothing to do with being on a mac, I'm running ubuntu on vagrant and that's failing to install scipy. I will try making a wheel. thanks anyway.

**Comment by peterkaniu** [comment]
> so I think the problem is that pip is refusing to install scipy. I didn't remember scipy being a dependency of seaborn before? Anyway the problem with scipy seems to be a problem with numpy: `numpy.distutils.system_info.NotFoundError: no lapack/blas resources found`
> 
> It will take me a bit to track back which version(s) of those will let me install scipy so I can try installing seaborn again.
> 
> numpy==1.9.1
> pandas==0.16.2
> matplotlib==1.3.1
> 
> ImportError Traceback (most recent call last)
> in ()
> ----> 1 import seaborn
> 
> /home/vagrant/venv/lib/python3.4/site-packages/seaborn/**init**.py in ()
> ----> 1 from .rcmod import *
> 2 from .utils import *
> 3 from .palettes import *
> 4 from .linearmodels import *
> 5 from .categorical import *
> 
> /home/vagrant/venv/lib/python3.4/site-packages/seaborn/rcmod.py in ()
> 3 import matplotlib as mpl
> 4
> ----> 5 from . import palettes
> 6
> 7
> 
> /home/vagrant/venv/lib/python3.4/site-packages/seaborn/palettes.py in ()
> 12 from .external.six.moves import range
> 13
> ---> 14 from .utils import desaturate, set_hls_values
> 15 from .xkcd_rgb import xkcd_rgb
> 16 from .crayons import crayons
> 
> /home/vagrant/venv/lib/python3.4/site-packages/seaborn/utils.py in ()
> 6
> 7 import numpy as np
> ----> 8 from scipy import stats
> 9 import pandas as pd
> 10 import matplotlib.colors as mplcol
> 
> ImportError: No module named 'scipy'

Anyone with same error on Windows environment?
