### ISSUE TITLE
distplot weirdness

### ISSUE THREAD

**Issue by wfbradley** [mwaskom/seaborn#772]
I usually have no difficulty using "distplot", but the following data seemed to cause a problem:
```
import seaborn as sns
sns.distplot([1,1,1,1,2])
```
It throws the exception:
```
ValueError: operands could not be broadcast together with shapes (2,) (3,) (2,) 
```

It works if you change pretty much any of the values.

**Comment by mwaskom** [comment]
That is weird, but of course it would be more helpful to see the full stack trace so that I can see where the error is actually getting raised from.

**Comment by wfbradley** [comment]
Dear Michael,

Oh, sorry!  Here you go:
```
In [1]: import seaborn as sns
sns.distplot([1,1,1,1,2])

In [2]: sns.distplot([1,1,1,1,2])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-c573cc175546> in <module>()
----> 1 sns.distplot([1,1,1,1,2])

//anaconda/lib/python2.7/site-packages/seaborn/distributions.pyc in distplot(a, bins, hist, kde, rug, fit, hist_kws, kde_kws, rug_kws, fit_kws, color, vertical, norm_hist, axlabel, label, ax)
    210         hist_color = hist_kws.pop("color", color)
    211         ax.hist(a, bins, orientation=orientation,
--> 212                 color=hist_color, **hist_kws)
    213         if hist_color != color:
    214             hist_kws["color"] = hist_color

//anaconda/lib/python2.7/site-packages/matplotlib/axes/_axes.pyc in hist(self, x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, **kwargs)
   5676             # this will automatically overwrite bins,
   5677             # so that each histogram uses the same bins
-> 5678             m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
   5679             m = m.astype(float)  # causes problems later if it's an int
   5680             if mlast is None:

//anaconda/lib/python2.7/site-packages/numpy/lib/function_base.pyc in histogram(a, bins, range, normed, weights, density)
    247                 n.imag += np.bincount(indices, weights=tmp_w.imag, minlength=bins)
    248             else:
--> 249                 n += np.bincount(indices, weights=tmp_w, minlength=bins).astype(ntype)
    250 
    251         # We now compute the bin edges since these are returned

ValueError: operands could not be broadcast together with shapes (2,) (3,) (2,) 
```

**Comment by mwaskom** [comment]
OK thanks, this looks like the same issue as #735.

Can you say what versions of seaborn, numpy, and matplotlib you are using?

**Comment by wfbradley** [comment]
Seaborn version 0.6.0
Numpy version 1.10.1
Matplotlib version 1.4.3

**Comment by mwaskom** [comment]
Thanks. As in the other issue, this works fine for me with seaborn 0.7.dev, numpy 1.9.2, and matplotlib 1.4.3. So I guess it's either something that has been fixed in seaborn or something that has broken in numpy.

**Comment by mwaskom** [comment]
It also seems to work fine on tmpnb.org, which has the same numpy but seaborn 0.6. So I am guessing it's some change in numpy.

**Comment by wfbradley** [comment]
Hrm.  Poking around, the issue seems to be that in certain unusual cases, the _freedman_diaconis_bins() from seaborn/distributions.py, version 0.6.0 can return a non-integer (in my example, it returns sqrt(5)=2.236...); in the 0.7.dev branch, you've wrapped the output in int(), so that no longer happens.

Adding in int() or np.ceil() to the output of _freedman_diaconis_bins() fixes the problem (or one could fix it on the numpy side).

**Comment by mwaskom** [comment]
I think #771 fixes this.
