### ISSUE TITLE
Make linecolor apply only only the squares in the mask?

### ISSUE THREAD

**Issue by tlnagy** [mwaskom/seaborn#780]
Is it possible to make linecolor apply only to the cells that are True in the mask? I want to use this highlight specific cells as being different than the others. I'm open to other suggestions for how to highlight specific cells in a graphical way.

**Comment by mwaskom** [comment]
I'm not sure what you're asking about?

**Comment by tlnagy** [comment]
Sorry I wasn't clear enough. I'll try an example. Say I have the following code:

```python
import numpy as np
import seaborn as sns

np.random.seed(0)
data = np.random.randn(10, 10)
mask = data > 1.5

sns.heatmap(data)
sns.heatmap(data, mask=mask, cbar=False, linecolor="k", linewidths=0.5)
```
which looks like:

![index](https://cloud.githubusercontent.com/assets/1661487/11328410/e5b1e80a-913e-11e5-89ff-356cf833de16.png)

Is there any way to highlight only the cells that are True in the `mask` 2d array? I want to show which cells are in the mask versus outside it.

**Comment by tlnagy** [comment]
This example is quite contrived, because the mask isn't giving you any extra information, but in my use-case the mask is derived from another data column

**Comment by martijnvermaat** [comment]
I would like to do the same thing. My use case is a calendar like the following:

![calendar](https://cloud.githubusercontent.com/assets/623509/11379654/b5e27c2a-92f1-11e5-8984-c351e70090fc.png)

(In this example line color is white and axis backgroud is grey so you can see both.)

The first and last three days in this heatmap are actually not in 2015 and therefore masked. However, I would also like to hide the lines around these NaN cells (click the image to see the white lines around them). Looking at the heatmap code (it uses pcolormesh) I don't think this is possible.

Better would be to draw the lines in the same color as the axis background color, but I think that is fragile (breaks when the axis background color is changed later).

Perhaps it is possible to implement the lines not by drawing them but by having a small padding for the cells, effectively having 'transparent' lines?

**Comment by mwaskom** [comment]
Sorry, the lines are implemented at the matplotlib layer and I think they are just lines around each cell in the quadmesh, so I don't think you'll be able to use that parameter to do what you want.
