### ISSUE TITLE
Weighted (bivariate) histograms (feature request)

### ISSUE THREAD

**Issue by wfbradley** [mwaskom/seaborn#783]
I have weighted samples from a bivariate distribution.  I'd like to view it with jointplot or jointgrid.  Apparently that is not currently supported (per, e.g., [this post](http://stackoverflow.com/questions/31703149/weights-option-for-seaborn-distplot)).  Would it be possible to enable this?

It is always possible to "unweight" a histogram by converting it into a corresponding number of uniform samples, but in my case, this would increase the data size by about 100,000x.

Thank you!

**Comment by mwaskom** [comment]
Probably not, sorry, seaborn just uses matplotlib to draw histograms and doesn't have code to do that itself.
