### ISSUE TITLE
Standardization in z_score formula might be wrong

### ISSUE THREAD

**Issue by MMCMA** [mwaskom/seaborn#784]
In seaborn version '0.5.1', I find in matrix.py -> z_score the formula (x-mean(x))/var(x) (`(z_scored - z_scored.mean()) / z_scored.var())`, this might be wrong. usually you devide over the standard deviation and not the variance to obtain a random variable with variance one. The code should then be `(z_scored - z_scored.mean()) / z_scored.std()`

**Comment by michael-imbeault** [comment]
Related: https://github.com/mwaskom/seaborn/issues/649

**Comment by MMCMA** [comment]
thanks. had not seen thos. sorry.

**Comment by michael-imbeault** [comment]
Make sure it's exactly the same issue before closing, it might be separate areas in the code I didn't check, I just know I had the same kind of issue fixed in clustermap (which probably calls the same function, but someone should verify).

**Comment by michael-imbeault** [comment]
I just checked, looks like the same issue in matrix.py, so this should be working properly in 6.0

**Comment by MMCMA** [comment]
It is corrected.
