### ISSUE TITLE
Seaborn fails at import time on OSX in a virtualenv

### ISSUE THREAD

**Issue by adzuci** [mwaskom/seaborn#790]
Let me know if I'm barking up the wrong tree, but I couldn't find an acceptable work around for this & found myself wishing seaborn didn't call out to so many things at import time:

On OSX running
```
import seaborn as sns
```
Results in:
```
Traceback (most recent call last):
  File "/Users/adzuci/Documents/code/pyfolio/pyfolio/plotting.py", line 20, in <module>
    import seaborn as sns
  File "/Users/adzuci/.virtualenvs/pyfolio/lib/python2.7/site-packages/seaborn/__init__.py", line 1, in <module>
    from .rcmod import *
  File "/Users/adzuci/.virtualenvs/pyfolio/lib/python2.7/site-packages/seaborn/rcmod.py", line 5, in <module>
    from . import palettes
  File "/Users/adzuci/.virtualenvs/pyfolio/lib/python2.7/site-packages/seaborn/palettes.py", line 7, in <module>
    import matplotlib.pyplot as plt
  File "/Users/adzuci/.virtualenvs/pyfolio/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/adzuci/.virtualenvs/pyfolio/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/adzuci/.virtualenvs/pyfolio/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

I'm using these versions:
```
pip freeze | grep "seaborn\|matplotlib"
matplotlib==1.5.0
seaborn==0.6.0
```

There are a few work arounds for similar issues involving adding a hook or monkey patching things: 
http://matplotlib.org/faq/virtualenv_faq.html but none of them are very good.  Is there any way to have seaborn not call this at import time?

We only use osx for local dev, so I can specify the backend (i.e `matplotlib.use('Agg')`) during the imports in the tests, but I don't want to specify the backend for the whole module.

**Comment by mwaskom** [comment]
It looks like your matplotlib installation is broken. I don't think this has anything to do with seaborn.

**Comment by adzuci** [comment]
@mwaskom Sorry if I posted this issue in the wrong place.  

I know that with my current matplotlib installation this issue only occurs in a virtualenv, so I'm not sure if I would fault matplotlib or virtualenv on osx, but I thought that one solution would be to use a different backend for code that runs into the issue.  Unfortunately since seaborn is imported in the `__init__.py` of the project I'm working with (https://github.com/quantopian/pyfolio/issues/225#issuecomment-160886192) pyplot throws the error first thing.  Unless I could get seaborn to call out to pyplot/matplotlib more lazily then I have to change the backend before any code is actually run.

The OSX workaround I found was to change my backend everywhere, but I'm not sure if it's the right solution?

http://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python
`echo "backend: TkAgg" > ~/.matplotlib/matplotlibrc`

Do you think that is the best option in this case?  I hate to make editing local config files a prereq to run unit tests, but it might be the only way.

**Comment by mwaskom** [comment]
If pyfolio happened to import matplotlib before it imported seaborn (currently it does so in the reverse order), it would fail there instead of on the seaborn import. So the problem doesn't have anything to do with seaborn.

I don't know what the right answer for your particular case is, although I would point out that you can put matplotlibrc files in places other than `~/.matplotlib` and they will have more local effects.

**Comment by deehzee** [comment]
I found the following work around at
http://stackoverflow.com/questions/29433824/unable-to-import-matplotlib-pyplot-as-plt-in-virtualenv

Put the following line in `~/.matplotlib/matplotlibrc`:
```
backend: TkAgg
```
