### ISSUE TITLE
Issues with Seaborn FacetGrid and Matplotlib errorbar

### ISSUE THREAD

**Issue by mlgill** [mwaskom/seaborn#791]
I'm having an issue with a fresh install of Seaborn and Matplotlib that had to be done due to hard drive issues. The installation does involve an upgrade of Matplotlib from 1.4.3 to 1.5.0, but I'm not entirely sure it's version related since a fresh install of 1.4.3 also fails for me.

I do suspect this is more Matplotlib related than Seaborn related, but I've found a [workaround](https://github.com/mlgill/seaborn) in Seaborn and thought I'd see if you have other suggestions or are interested in converting this into a pull request since there's only one line of code to change.

The problem is described in an IPython notebook (with sample data) here:
https://gist.github.com/mlgill/4d1987d650b32329e4ee

System information:
Mac OS X 10.11.1
Matplotlib backend: MacOSX
Python 2.7.10 (all libraries from Conda, except those cloned directly from GitHub)
Matplotlib: 1.5.0
Seaborn: 0.6.0 (and latest from GitHub master)

Thank you!

**Comment by mlgill** [comment]
I've also tried subclassing Seaborn's FacetGrid class so that it's possible to change the data attribute. This would in theory allow the regression line to be contained in a separate dataframe from the experimental data and then the appropriate data could be swapped before plotting. 

As can be seen from the IPython notebook, the data swapping does work and no error is produced, but I can't get the plot contents to update after the second plot (experimental data).

**Comment by mlgill** [comment]
I now have the subclassing trick working, but it's a little ugly. Thoughts welcome on how best to deal with this issue.

**Comment by mwaskom** [comment]
My flight is delayed so I had time to take a quick look. I don't think I'll fully understand the issue until I run your notebook and debug things, but I'd suggest that in general an easier solution might be to write a little wrapper function for `plt.errorbar` that fails more gracefully on empty data, and then pass that to `FacetGrid.map`.

**Comment by mwaskom** [comment]
PS is the whole point of this just to troll me about how powerful your magnets are?

**Comment by mlgill** [comment]
Just seeing this--I must have inadvertently shut off GitHub email notifications. Oops.

I wondered about fixing plt.errorbar since I think that is the real issue. I hesitated because I don't understand the matplotlib code as well. (And it's a lot more complicated that yours.) I didn't think of writing a wrapper, but that makes sense since `map` doesn't care if it gets an actual matplotlib function or not. 

I won't get time to work on it until later this week, but I'll report back. 

I love my magnets. This data was collected in NYC, but the magnets here are just as awesome. :)

**Comment by mwaskom** [comment]
> I didn't think of writing a wrapper, but that makes sense since map doesn't care if it gets an actual matplotlib function or not.

Yep it's my usual approach in these weird corner cases. If I understand your issue properly, something simple like

```python
def safe_errorbar(x, y, yerr, **kwargs):
    if yerr.size:
        plt.errorbar(x, y, yerr, **kwargs)
```

should do the trick.

**Comment by mlgill** [comment]
Well, if you're going to reply instantly and make it that easy, how can I not test it right now? 

I made this modification to catch any cases where there is x/y data but no errorbars:
```
def safe_errorbar(x, y, yerr, **kwargs):
    if yerr.size:
        plt.errorbar(x, y, yerr, **kwargs)
    else:
        plt.errorbar(x, y, **kwargs)
        
    return
``

And it works fine. I will close this issue.
