### ISSUE TITLE
kwargs to bar from countplot not working?

### ISSUE THREAD

**Issue by michael-imbeault** [mwaskom/seaborn#792]
I'm trying to pass kwargs to countplot to change the width of the bars, for example:

g = sns.countplot(x="Name", data=nodes, hue="Class", width=1)

But I get "TypeError: bar() got multiple values for keyword argument 'width'"

What's the correct way to do it?

**Comment by mwaskom** [comment]
The bar width is hardcoded because otherwise the logic of nesting the bars gets too tricky.

**Comment by michael-imbeault** [comment]
That's unfortunate, its producing in my (simple, non nested case) tiny bars (it's a big graph) that I would have loved to adjust, along some other parameters that seem to be hardcoded too (same error).

**Comment by mwaskom** [comment]
Sorry ... if you need a lot of customization, you should use `pyplot.bar` directly.
