### ISSUE TITLE
Wrong hue colors in factorplot with kind='strip'

### ISSUE THREAD

**Issue by kelphil** [mwaskom/seaborn#795]
Hi,

The factorplot hue colors show colors outside the defined palette. I noticed this behavior when the dataset sample size is relatively small.

```
import seaborn as sns

titanic = sns.load_dataset("titanic")
trimmed_data = titanic.ix[:50,:]

g = sns.factorplot(data=trimmed_data,
                   x='pclass',
                   y='age',
                   col='survived',
                   hue='who',
                   palette={'man':'red','woman':'green','child':'blue'},
                   kind='strip',
                   jitter=True
                   )
```

As shown below, black and grey dots appear on the plot while red, green and blue are the only colors defined in the color palette dict: `palette={'man':'red','woman':'green','child':'blue'}` Please help.

![figure_1](https://cloud.githubusercontent.com/assets/16230838/11699431/286a2ab2-9e79-11e5-9d0f-2a962c5f1aee.png)

**Comment by mwaskom** [comment]
I think this is the same problem as https://github.com/mwaskom/seaborn/issues/753

**Comment by kelphil** [comment]
I tried the workaround you suggested in #753 `palette=sns.color_palette("bright",3).as_hex()` But the plot still has the grey/black points.

```
import seaborn as sns

titanic = sns.load_dataset("titanic")
trimmed_data = titanic.ix[:50,:]

g = sns.factorplot(data=trimmed_data,
                   x='pclass',
                   y='age',
                   col='survived',
                   hue='who',
                   # palette={'man':'red','woman':'green','child':'blue'},
                   palette=sns.color_palette("bright",3).as_hex(),
                   kind='strip',
                   jitter=True
                   )
```

Here is the new output:

![figure_2](https://cloud.githubusercontent.com/assets/16230838/11700757/9050d8a4-9e80-11e5-8ba4-3e9fb4cc6c76.png)

**Comment by mwaskom** [comment]
Yes, as noted in that thread, it's a workaround that needs to be implemented within seaborn, not in user-space. Closing as an issue already exists to track this problem.

**Comment by kelphil** [comment]
Thanks for the update. Great job with the library by the way!
