### ISSUE TITLE
Make test fails with the following output.

### ISSUE THREAD

**Issue by abrrba** [mwaskom/seaborn#799]
```
cp testing/matplotlibrc .
nosetests --with-doctest
/usr/local/lib/python2.7/dist-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
/home/rishi/seaborn/seaborn/axisgrid.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./usr/lib/pymodules/python2.7/matplotlib/pyplot.py:412: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_num_figures`).
  max_open_warning, RuntimeWarning)
../home/rishi/seaborn/seaborn/categorical.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./home/rishi/seaborn/seaborn/categorical.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
.../home/rishi/seaborn/seaborn/categorical.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./home/rishi/seaborn/seaborn/categorical.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./home/rishi/seaborn/seaborn/categorical.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./home/rishi/seaborn/seaborn/categorical.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
......F../usr/lib/pymodules/python2.7/matplotlib/colorbar.py:211: UserWarning: Use the colorbar set_ticks() method instead.
  warnings.warn("Use the colorbar set_ticks() method instead.")
F..........................................SS..................................SS..SS....SSSS.......................................................................................................................SSS..................S......SSS....SSS..S.................................SS....................................................................../usr/lib/pymodules/python2.7/matplotlib/__init__.py:817: UserWarning: savefig.extension is deprecated and replaced with savefig.format; please use the latter.
  warnings.warn(self.msg_depr % (key, alt))
......S/usr/lib/pymodules/python2.7/matplotlib/font_manager.py:1236: UserWarning: findfont: Font family ['Verdana'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
/usr/lib/pymodules/python2.7/matplotlib/font_manager.py:1246: UserWarning: findfont: Could not match :family=Bitstream Vera Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=11.0. Returning /usr/share/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
  UserWarning)
/usr/lib/pymodules/python2.7/matplotlib/font_manager.py:1246: UserWarning: findfont: Could not match :family=Verdana:style=normal:variant=normal:weight=normal:stretch=normal:size=12. Returning /usr/share/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
  UserWarning)
/usr/lib/pymodules/python2.7/matplotlib/font_manager.py:1246: UserWarning: findfont: Could not match :family=very\_unlikely\_to\_exist1234:style=normal:variant=normal:weight=normal:stretch=normal:size=12. Returning /usr/share/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
  UserWarning)
S.............................SSS
======================================================================
FAIL: Doctest: seaborn.linearmodels.regplot
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for seaborn.linearmodels.regplot
  File "/home/rishi/seaborn/seaborn/linearmodels.py", line 835, in regplot

----------------------------------------------------------------------
File "/home/rishi/seaborn/seaborn/linearmodels.py", line 1054, in seaborn.linearmodels.regplot
Failed example:
    ax = sns.regplot(x="x", y="y", data=ans.loc[ans.dataset == "III"],
                     scatter_kws={"s": 80},
                     robust=True, ci=None)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest seaborn.linearmodels.regplot[16]>", line 3, in <module>
        robust=True, ci=None)
      File "/home/rishi/seaborn/seaborn/linearmodels.py", line 771, in regplot
        plotter.plot(ax, scatter_kws, line_kws)
      File "/home/rishi/seaborn/seaborn/linearmodels.py", line 324, in plot
        self.lineplot(ax, line_kws)
      File "/home/rishi/seaborn/seaborn/linearmodels.py", line 369, in lineplot
        grid, yhat, err_bands = self.fit_regression(ax)
      File "/home/rishi/seaborn/seaborn/linearmodels.py", line 199, in fit_regression
        from statsmodels.robust.robust_linear_model import RLM
    ImportError: No module named statsmodels.robust.robust_linear_model
----------------------------------------------------------------------
File "/home/rishi/seaborn/seaborn/linearmodels.py", line 1065, in seaborn.linearmodels.regplot
Failed example:
    ax = sns.regplot(x="total_bill", y="big_tip", data=tips,
                     logistic=True, n_boot=500, y_jitter=.03)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest seaborn.linearmodels.regplot[18]>", line 2, in <module>
        logistic=True, n_boot=500, y_jitter=.03)
      File "/home/rishi/seaborn/seaborn/linearmodels.py", line 771, in regplot
        plotter.plot(ax, scatter_kws, line_kws)
      File "/home/rishi/seaborn/seaborn/linearmodels.py", line 324, in plot
        self.lineplot(ax, line_kws)
      File "/home/rishi/seaborn/seaborn/linearmodels.py", line 369, in lineplot
        grid, yhat, err_bands = self.fit_regression(ax)
      File "/home/rishi/seaborn/seaborn/linearmodels.py", line 191, in fit_regression
        from statsmodels.genmod.generalized_linear_model import GLM
    ImportError: No module named statsmodels.genmod.generalized_linear_model


======================================================================
FAIL: Doctest: seaborn.matrix.heatmap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for seaborn.matrix.heatmap
  File "/home/rishi/seaborn/seaborn/matrix.py", line 268, in heatmap

----------------------------------------------------------------------
File "/home/rishi/seaborn/seaborn/matrix.py", line 430, in seaborn.matrix.heatmap
Failed example:
    f, (ax, cbar_ax) = plt.subplots(2, gridspec_kw=grid_kws)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest seaborn.matrix.heatmap[18]>", line 1, in <module>
        f, (ax, cbar_ax) = plt.subplots(2, gridspec_kw=grid_kws)
      File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 1046, in subplots
        fig = figure(**fig_kw)
      File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 423, in figure
        **kwargs)
      File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 409, in new_figure_manager
        thisFig = FigureClass(*args, **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'gridspec_kw'
----------------------------------------------------------------------
File "/home/rishi/seaborn/seaborn/matrix.py", line 431, in seaborn.matrix.heatmap
Failed example:
    ax = sns.heatmap(flights, ax=ax,
                     cbar_ax=cbar_ax,
                     cbar_kws={"orientation": "horizontal"})
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest seaborn.matrix.heatmap[19]>", line 2, in <module>
        cbar_ax=cbar_ax,
    NameError: name 'cbar_ax' is not defined


----------------------------------------------------------------------
Ran 417 tests in 154.090s

FAILED (SKIP=28, failures=2)
make: *** [test] Error 1
```

**Comment by mwaskom** [comment]
Currently the build is passing on Travis, so this likely has something to do with your particular setup. Based on the output, I would guess that you have an older version of matplotlib and do not have statsmodels installed. However, without more information, it is very difficult to speculate.

**Comment by abrrba** [comment]
Which version of python is supported/used for seaborn. (2.7 or 3.4).

I have attached the listing of the installed packages.


[pip_list2.7.txt](https://github.com/mwaskom/seaborn/files/62072/pip_list2.7.txt)
[pip_list3.4.txt](https://github.com/mwaskom/seaborn/files/62071/pip_list3.4.txt)

**Comment by mwaskom** [comment]
Have you read the [dependencies information](http://stanford.edu/~mwaskom/software/seaborn/installing.html#dependencies)?

**Comment by abrrba** [comment]
Yes, I have installed the dependencies using pip and then ran the make test
command.

This is the current output of the make test command.


cp testing/matplotlibrc .
nosetests --with-doctest
/usr/local/lib/python2.7/dist-packages/IPython/html.py:14: ShimWarning: The
`IPython.html` package has been deprecated. You should import from
`notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
/home/rishi/seaborn/seaborn/axisgrid.py:1: FutureWarning:
sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./usr/lib/pymodules/python2.7/matplotlib/pyplot.py:412: RuntimeWarning:
More than 20 figures have been opened. Figures created through the pyplot
interface (`matplotlib.pyplot.figure`) are retained until explicitly closed
and may consume too much memory. (To control this warning, see the rcParam
`figure.max_num_figures`).
  max_open_warning, RuntimeWarning)
../home/rishi/seaborn/seaborn/categorical.py:1: FutureWarning:
sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./home/rishi/seaborn/seaborn/categorical.py:1: FutureWarning:
sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
.../home/rishi/seaborn/seaborn/categorical.py:1: FutureWarning:
sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./home/rishi/seaborn/seaborn/categorical.py:1: FutureWarning:
sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./home/rishi/seaborn/seaborn/categorical.py:1: FutureWarning:
sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./home/rishi/seaborn/seaborn/categorical.py:1: FutureWarning:
sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
........./usr/lib/pymodules/python2.7/matplotlib/colorbar.py:211:
UserWarning: Use the colorbar set_ticks() method instead.
  warnings.warn("Use the colorbar set_ticks() method instead.")
F..........................................SS..................................SS..SS....SSSS..................................................................................................................................................................................................SS....................................................................../usr/lib/pymodules/python2.7/matplotlib/__init__.py:817:
UserWarning: savefig.extension is deprecated and replaced with
savefig.format; please use the latter.
  warnings.warn(self.msg_depr % (key, alt))
......S/usr/lib/pymodules/python2.7/matplotlib/font_manager.py:1236:
UserWarning: findfont: Font family ['Verdana'] not found. Falling back to
Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
/usr/lib/pymodules/python2.7/matplotlib/font_manager.py:1246: UserWarning:
findfont: Could not match :family=Bitstream Vera
Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=11.0.
Returning /usr/share/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
  UserWarning)
/usr/lib/pymodules/python2.7/matplotlib/font_manager.py:1246: UserWarning:
findfont: Could not match
:family=Verdana:style=normal:variant=normal:weight=normal:stretch=normal:size=12.
Returning /usr/share/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
  UserWarning)
/usr/lib/pymodules/python2.7/matplotlib/font_manager.py:1246: UserWarning:
findfont: Could not match
:family=very\_unlikely\_to\_exist1234:style=normal:variant=normal:weight=normal:stretch=normal:size=12.
Returning /usr/share/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
  UserWarning)
S.............................SSS
======================================================================
FAIL: Doctest: seaborn.matrix.heatmap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for seaborn.matrix.heatmap
  File "/home/rishi/seaborn/seaborn/matrix.py", line 268, in heatmap

----------------------------------------------------------------------
File "/home/rishi/seaborn/seaborn/matrix.py", line 430, in
seaborn.matrix.heatmap
Failed example:
    f, (ax, cbar_ax) = plt.subplots(2, gridspec_kw=grid_kws)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest seaborn.matrix.heatmap[18]>", line 1, in <module>
        f, (ax, cbar_ax) = plt.subplots(2, gridspec_kw=grid_kws)
      File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 1046,
in subplots
        fig = figure(**fig_kw)
      File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 423,
in figure
        **kwargs)
      File
"/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line
409, in new_figure_manager
        thisFig = FigureClass(*args, **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'gridspec_kw'
----------------------------------------------------------------------
File "/home/rishi/seaborn/seaborn/matrix.py", line 431, in
seaborn.matrix.heatmap
Failed example:
    ax = sns.heatmap(flights, ax=ax,
                     cbar_ax=cbar_ax,
                     cbar_kws={"orientation": "horizontal"})
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest seaborn.matrix.heatmap[19]>", line 2, in <module>
        cbar_ax=cbar_ax,
    NameError: name 'cbar_ax' is not defined


----------------------------------------------------------------------
Ran 418 tests in 129.255s

FAILED (SKIP=17, failures=1)
make: *** [test] Error 1


On Tue, Dec 15, 2015 at 10:00 AM, Michael Waskom <notifications@github.com>
wrote:

> Have you read the dependencies information
> <http://stanford.edu/%7Emwaskom/software/seaborn/installing.html#dependencies>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mwaskom/seaborn/issues/799#issuecomment-164642520>.
>



-- 
Regards,
Rishi Agrawal

A simple act of caring creates an endless ripple.
Be the change that you wish to see in the world.
Be thoroughly used up when you die, for the harder you work, the more you
live.

**Comment by mwaskom** [comment]
As I said before, you have an older matplotlib.
