### ISSUE TITLE
legend_out=True is not working consistently

### ISSUE THREAD

**Issue by philmorefield** [mwaskom/seaborn#800]
I'm calling `seaborn.lmplot()` and I'm unable to consistently get the legend moved outside of the plot. `legend_out=True` is the default behavior, and it does in fact work correctly in Jupyter. But it doesn't work in WingIDE and Spyder. 

    import seaborn as sns
    tips = sns.load_dataset('tips')
    sns.lmplot('total_bill', 'tip', tips, hue='smoker', legend_out=True)
![figure_1](https://cloud.githubusercontent.com/assets/9205728/11847311/c993df66-a3ea-11e5-8a01-88888f3ae93a.png)

Seaborn = 0.6.0
Matplotlib = 1.5.0 (cycling through different backends during troubleshooting)
Spyder = 2.3.8
WingIDE = 5.1.8-1
Python = 2.7.11

**Comment by mwaskom** [comment]
Yes, this is a known issue with some matplotlib backends. Unfortunately you'll just have to find one that works.

**Comment by mwaskom** [comment]
Closing as this is documented in other issues.

**Comment by FlorianFranzen** [comment]
@mwaskom: It would be helpful to document the "good" backends somewhere, as the variety of backends available create enough confusion already and at first it always looks like seaborn is to blame.
