### ISSUE TITLE
Categorical plot examples should emphasize factorplot over direct FacetGrid usage

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#805]
Otherwise it is not obvious how important it is to pass `order` and `hue_order` to avoid problems.

**Comment by philipp-germann** [comment]
I would suggest to also add a comment on the importance of these two parameters in the documentation for `FacetGrid` or make them non-optional as there can really weird happen:

![image](https://cloud.githubusercontent.com/assets/8821566/21179094/c656a104-c1f2-11e6-94e1-fabd3a7751b7.png)

I just lost some hours and beers over this ;-)
