### ISSUE TITLE
Possible to add color labels like with clustermap, but to bar charts?

### ISSUE THREAD

**Issue by michael-imbeault** [mwaskom/seaborn#808]
Hello,

I was wondering if it could be possible to add the row_label / color_label functionality to other plots, such as bar. The idea would be to put metadata information underneath each bar, color coded (with multiple rows possible). The functionality currently exists in clustermap and is very useful; is there a way to extend it to bar charts?

Thanks,
Michael

**Comment by mwaskom** [comment]
Probably not, because in the clustermap those colors are drawn onto a separate axes (`clustermap` is a figure-level function), but `barplot` is an axes-level function. Doesn't stop the user from doing it themselves with a subplot grid, of course.
