### ISSUE TITLE
clustermap - overlapping row labels

### ISSUE THREAD

**Issue by fblamanna** [mwaskom/seaborn#809]
I'm on Mac OS 10.10.2, Python 2.7.11, Seaborn 0.6.0, pandas 0.17.1, matplotlib 1.5.0.

My code is the following:

```
import pandas as pd
import random
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.DataFrame()

df['x'] = random.sample(range(1, 100), 25)
df['y'] = random.sample(range(1, 100), 25)

L = []
for i in range(25):
	L.append('longlonglabel' + str(i))

df.index = L
sns.clustermap(df)
plt.show()
```

which returns:

![figure_1](https://cloud.githubusercontent.com/assets/15954672/12065108/d1ab6046-afd1-11e5-8a7a-ca97fb41332a.png)

So in case of long labels they're overlapping on the row side. I did several attempts to rotate the labels through matplotlib but it didn't work. I think that the default mode should return the row labels horizontally, such as the ones on the columns.

**Comment by mwaskom** [comment]
```
g = sns.clustermap(df)
plt.setp(g.ax_heatmap.get_yticklabels(), rotation=0)
```
