### ISSUE TITLE
iPython: "ImportError: No module named seaborn"

### ISSUE THREAD

**Issue by chef1075** [mwaskom/seaborn#813]
This might be a duplicate of #801 but I don't think so.

I'm trying to import seaborn into iPython, however I get this error:

```
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn;
from sklearn.linear_model import LinearRegression
from scipy import stats
import pylab as pl
```
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-e3d40abd657b> in <module>()
      2 import numpy as np
      3 import matplotlib.pyplot as plt
----> 4 import seaborn;
      5 from sklearn.linear_model import LinearRegression
      6 from scipy import stats

ImportError: No module named seaborn
```

I can import seaborn into my python shell, but not into iPython.

Suggestions?

**Comment by mwaskom** [comment]
My guess would be that your `ipython` binary is not pointing at the same python installation as `python` (and `pip`, or however you installed seaborn).

**Comment by chef1075** [comment]
Thanks! I'm just getting into learning how to use iPython (Jupyter).

Would you have any advice on how to point it to the same python installation?

**Comment by mwaskom** [comment]
On unix systems you can check where commands like `python` and `ipython` are pointing with `which python`, `which ipython`. They should be in the same binary directory. However, questions about setting up your environment are probably better directed to people who manage your Python distribution, i.e. Anaconda, EPD, Linux distribution, etc., as they'll be able to provide better advice.

**Comment by chef1075** [comment]
Thanks. This is a good start for me to figure this out.

**Comment by mboyanna** [comment]
Im having the same issue with Jupyter. And my python, ipython and seaborn are all coming from the same directory, check this out. This seems so far like it's something else:
$ which python
/usr/local/anaconda3/bin/python
$ which ipython
/usr/local/anaconda3/bin/ipython
$ which jupyter
/usr/local/anaconda3/bin/jupyter
$ which pip
/usr/local/anaconda3/bin/pip
$ find $ANACONDA_HOME -name seaborn* -print
/usr/local/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/seaborn-bright.mplstyle
/usr/local/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/seaborn-colorblind.mplstyle
...
/usr/local/anaconda3/pkgs/matplotlib-1.5.1-np110py35_0/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/seaborn-bright.mplstyle
/usr/local/anaconda3/pkgs/matplotlib-1.5.1-np110py35_0/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/seaborn-colorblind.mplstyle
...
Now Ill admit to having tried to install IScala kernel to ipython/jupyter but backed out to the executable for jupyter only. Any further suggestions?

**Comment by mwaskom** [comment]
You haven't said what your problem is.

**Comment by mboyanna** [comment]
Sorry, I got the same error as the previous poster. Here's the code, and the stacktrace
--------------
%matplotlib inline
​
import pandas as pd
import numpy as np
import matplotlib
​
from matplotlib import pyplot as plt
import seaborn as sns
​
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts = ts.cumsum()
​
df = pd.DataFrame(np.random.randn(1000, 4), index=ts.index,
                  columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure(); df.plot(); plt.legend(loc='best')
​
​
​
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-fc39ee322045> in <module>()
      6 
      7 from matplotlib import pyplot as plt
----> 8 import seaborn as sns
      9 
     10 ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))

ImportError: No module named 'seaborn'

In [ ]:

**Comment by mwaskom** [comment]
Based on what you posted in the previous comment, you do not have seaborn installed. Why do you think that you do?

**Comment by avishapiro** [comment]
I had the same problem as @mboyanna and @chef1075, possible with a different cause. Here are some things to try. The problem may be isolated to a particular conda environment so I would try to `import seaborn` in a Jupyter notebook started from a different environment.

@mboyanna mentioned a different kernel had been installed. This was the cause of my situation. I had to downgrade `ipykernel` from 4.3.1 to 4.1.1 using Python 3.5. Problem seems fixed.

**Comment by kjmbote** [comment]
ImportError                               Traceback (most recent call last)
<ipython-input-1-ed9806ce3570> in <module>()
----> 1 import seaborn as sns

ImportError: No module named 'seaborn'
I get the error above even after running `conda install seaborn` in jupyter terminal 

Im using Windows 10

**Comment by kjmbote** [comment]
ImportError                               Traceback (most recent call last)
<ipython-input-1-ed9806ce3570> in <module>()
----> 1 import seaborn as sns

ImportError: No module named 'seaborn'
I get the error above even after running `conda install seaborn` in jupyter terminal 

Im using Windows  10

**Comment by VaShu** [comment]
Jupyter Code-Cell:
~~~
%%bash
pip install seaborn
~~~

**Comment by rahulgagrani** [comment]
I had to 
1. unistall miniconda (delete the directory ~/miniconda3), 
2. removed the PATH entry from ~/.bash_profile file. 
3. Reinstall seaborn 
and viola it worked fine.

**Comment by faizan1990** [comment]
This might help: https://github.com/slundberg/shap/issues/382#issuecomment-502883188

**Comment by tejas-2232** [comment]
bgvfc

**Comment by tejas-2232** [comment]
I'm facing the issue with importing seaborn in jupyter notebook.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a84c0541e888> in <module>
----> 1 import seaborn as sns

ImportError: No module named 'seaborn'

However I have installed it and it runs in terminal.
-------------------------------------------------------------------
Some modules are installed in..

(virt_pythree) sam@captain:~$ which jupyter
/home/sam/.local/bin/jupyter
(virt_pythree) sam@captain:~$ which ipython
/home/sam/.local/bin/ipython
(virt_pythree) sam@captain:~$ which python
/home/sam/virt_pythree/bin/python
(virt_pythree) sam@captain:~$ which pip
/home/sam/virt_pythree/bin/pip

If anyone knows it. Give the solution as soon as possible

**Comment by mwaskom** [comment]
I'm locking this thread because there are no seaborn-specific issues here. Anyone who is having trouble matching python library installation and execution environment is likely to get faster help elsewhere, without me getting pinged with a notification about it.
