### ISSUE TITLE
tsplot: Bug or feature - request for documentation

### ISSUE THREAD

**Issue by shobhitverma** [mwaskom/seaborn#815]
I just wanted to plot various percentiles to understand the variance of my data over time and I used 
sns.tsplot(W,time=t,  ci = [68,95,99], n_boot=200)
The resulting plot is this 
![image](https://cloud.githubusercontent.com/assets/5643690/12118819/7b271cec-b396-11e5-8ba4-c20876eadca3.png)
I incorrectly assumed that the 99th percentile is less than .2, this is clearly not true as this is the real distribution-
![image](https://cloud.githubusercontent.com/assets/5643690/12118731/1896c906-b396-11e5-872f-188cab0a05d6.png)
Note that the 99 percentile is probably more than 2 (1000% different).
I now know that this happens because numpy.mean is used as a standard aggregator statistic and so the 99 percentile that I want to see is actually for the sample mean of n_boot samples. Currently there seems to be no way to use this just to plot percentiles over time.
This seems to be a feature, but I had to spend an obscene amount of time to understand this as I really wanted to leverage seaborn to do the plotting instead of rewriting for myself.
Great job!

**Comment by mwaskom** [comment]
Right, the `ci_band` error style shows confidence intervals, not percentiles.

**Comment by shobhitverma** [comment]
For what it is worth. Purely for academic reasons, I went ahead and plotted percentiles using tsplot anyways. This is way more computationally intensive than it needs to be, but theoretically I could pass a random sampling function as the estimator function and the resulting ```ci_band``` becomes similar to percentiles. 

This was actual data 
![image](https://cloud.githubusercontent.com/assets/5643690/12146188/50f38512-b460-11e5-9be6-c66fcaefe615.png)

These were the confidence intervals (for mean by default)
![image](https://cloud.githubusercontent.com/assets/5643690/12146226/8301cfaa-b460-11e5-8b30-b16f63e7bb40.png)

But after defining the estimator function as follows
```python
def estimator(a, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False):
    import numpy as np
    return np.squeeze(np.percentile(a, np.random.random(1)*100, axis=axis, out=out, overwrite_input=overwrite_input, interpolation=interpolation, keepdims=keepdims).T)
```

The ```ci_band``` becomes approximately similar to percentiles!
![image](https://cloud.githubusercontent.com/assets/5643690/12146320/1834d5d6-b461-11e5-9436-cc9894a67da6.png)

"Approximately" because bootstrap estimates work without adjustment for a statistic which measures of central tendency, but need to be adjusted based on sample size etc. to make them unbiased when the statistic is "non-linear".
