### ISSUE TITLE
Heatmap annotation no longer works

### ISSUE THREAD

**Issue by pbreach** [mwaskom/seaborn#816]
Seems like there is something preventing heatmap annotation but I'm not sure what. To reproduce this just run the example [here](http://stanford.edu/~mwaskom/software/seaborn/examples/heatmap_annotation.html?highlight=heatmap).

This is what I get:

![image](https://cloud.githubusercontent.com/assets/8889265/12174877/35b63cf4-b52d-11e5-8e03-4c59fddc666d.png)

I'm using the most up to date version of seaborn on conda (0.6.0).

Also in the example the ticklabels are horizontal. For some reason I have to rotate them 360 degrees to get them back horizontal.

**Comment by mwaskom** [comment]
Duplicate of #619
