### ISSUE TITLE
eps savefig issues

### ISSUE THREAD

**Issue by MMCMA** [mwaskom/seaborn#818]
I am still facing issues with accessing eps-figures (png, jpg etc. work all without problem) when using seaborn as already discussed in closed issue #781 (sorry, i couldn't reopen the original issue). Moreover, I run the same code with python 3.4 on ux and win7 without issues. The eps created on different machines are also perfectly accessible from the win8.1 environment where locally created eps files with seaborn are inaccessible. Anyone any idea, what else I could try to solve the problem.

**Comment by mwaskom** [comment]
I'm not sure, but I would suggest asking on StackOverflow.

I can't really help with debugging as I cannot reproduce the issue, but I would suggest going through the rcParams that seaborn changes one by one to figure out which one is causing the issue.

**Comment by MMCMA** [comment]
FYI: I have located the eps problem in the rcParams. Opened issue on
matplotlib, I suppose there is the root of the problem. See
https://github.com/matplotlib/matplotlib/issues/6160
