### ISSUE TITLE
stripplot changes colors of points

### ISSUE THREAD

**Issue by cardosan** [mwaskom/seaborn#819]
Hi there,

I did a striplot with:
```sns.stripplot(x="Sp_gr_code", y="Rotation", data=rotation,jitter=True)```

using this dataset
[stripplot.csv.zip](https://github.com/mwaskom/seaborn/files/90248/stripplot.csv.zip)

and it returns this image:
![download](https://cloud.githubusercontent.com/assets/11156305/12322358/d447654c-bab3-11e5-8708-5870b9fed05e.png)

But for the last two categories it does not show all the three points of the dataframe  for Sp_gr_code but only two (for M_C is missing Rotation  17 while for M_E is missing Rotation 7 as below)

Sp_gr_code	| Rotation
------------ | -------------
M_C | 20
M_C | 16
M_C | 17

Sp_gr_code	| Rotation
------------ | -------------
M_E | 7
M_E | 32
M_E | 30

Is it a bug or I made any mistake?
Fruthermore, is it normal that the last two categories are black?
Thanks!

Python 2.7.11
Pandas 0.17.1
matplotlib 1.5.1
seaborn 0.6.0

**UPDATE**
I realized that the point are showed but of a different colours
![download 1](https://cloud.githubusercontent.com/assets/11156305/12322658/c22c7134-bab5-11e5-9e52-1eb100f3b667.png)
I think this is related to issue #753, need to updated to development version or there is a workaround?

**Comment by mwaskom** [comment]
Same issue as #753 and fixed in #798
