### ISSUE TITLE
Wrong colors for bar plots with matplotlib 1.5 and pandas 0.17

### ISSUE THREAD

**Issue by foebu** [mwaskom/seaborn#820]
Hi,
since matplotlib was updated I started having some troubles with colors. Using pandas plotting tools, in particular DataFrame.plot(kind='bar') I get matplotlib default colors and not seaborn ones.

This doesn't happen for other kind of plots (scatter, line, area etc..)

Is it a seaborn issue or pandas?

**Comment by TomAugspurger** [comment]
pandas, checkout https://github.com/pydata/pandas/issues/12029

Should be fixed in the master version of pandas if you're able to install that.

**Comment by mwaskom** [comment]
Closing as a pandas issue.

By the way, I think you can work around this in seaborn by calling `sns.set_color_codes()`, which forces matplotlib to interpret `"b", "g", "r"`, etc. as seaborn colors. I haven't tested this, but based on quickly looking at the code I think it will avoid this problem. (And, it might be generally useful to know about for other packages that hardcode colors).
