### ISSUE TITLE
set_axis_labels not drawing axis labels

### ISSUE THREAD

**Issue by fonnesbeck** [mwaskom/seaborn#821]
Running Seaborn 0.6.0 and MPL 1.3.1 on Ubuntu and Python 3.5, I encounter an issue where it seems impossible to draw axis labels explicitly. For example:

![screenshot](http://fonnesbeck-dropshare.s3.amazonaws.com/Screen-Shot-2016-01-14-17-40-36.png)

`set_xlabel` and `set_ylabel` behave similarly. Unfortunately, there is no warning or error to provide additional clues.

**Comment by mwaskom** [comment]
I can't reproduce on seaborn master + matplotlib 1.5 using the example data:

```python
tips = sns.load_dataset("tips")
g = sns.factorplot("day", "tip", "time", tips, kind="box")
sns.despine(trim=True, offset=10)
g.set_axis_labels("Day", "Tip")
```
![image](https://cloud.githubusercontent.com/assets/315810/12342513/cc6b6662-badf-11e5-8a7f-578d971246f5.png)

Not sure how or why it would be data dependent, but can you try that code on your setup to see if it works?

**Comment by fonnesbeck** [comment]
I think I figured it out. My Matplotlib on this Linux machine did not have the freetype libs it needed. thanks.
