### ISSUE TITLE
hist_kws={"weights":wgt} not working

### ISSUE THREAD

**Issue by fjaviersanchez** [mwaskom/seaborn#823]
Hello,

I have been trying to include weights in 1d and 2d histograms using seaborn and I am not able to make them work.

```
def banana_distribution(N=10000):
    theta = np.random.normal(0, np.pi / 8, 10000)
    theta[theta >= np.pi / 4] /= 2
    theta[theta <= -np.pi / 4] /= 2
    r = np.sqrt(1. / abs(np.cos(theta) ** 2 - np.sin(theta) ** 2))
    r += np.random.normal(0, 0.08, size=10000)
    x = r * np.cos(theta + np.pi / 4)
    y = r * np.sin(theta + np.pi / 4)
    return x,y

x,y = banana_distribution()

data = (x,y)
data = np.array(data)
data = data.T
df = pd.DataFrame(data, columns=["x", "y"])
g = sns.jointplot(x="x", y="y",data=df, kind="hex", marginal_kws={"bins":41*41/2}, gridsize=41*41/2, xlim=(0,2), ylim=(0,2))
weights = np.ones(10000)*1./10000.
cond1 = (y>=0.5-2./41.) & (y<=0.5+2./41.)
cond2 = (y>=1.0-2./41.) & (y<=1.0+2./41.)
cond3 = (y>=1.5-2./41.) & (y<=1.5+2./41.)

g1 = sns.distplot(x[cond1],hist=True, color='cyan', hist_kws={'weights':weights[cond1]})
g2 = sns.distplot(x[cond2],hist=True, color='green', hist_kws={'weights':weights[cond2]})
g3 = sns.distplot(x[cond3],hist=True, color='red', hist_kws={'weights':weights[cond3]})
```

However it seems to ignore the weights. I have also tried to use joint_kws={"weights":weights} to include the weights in the joint plot but it didn't work either.

Thanks,

Javier

![not_working_hist](https://cloud.githubusercontent.com/assets/13971732/12381119/38430fc0-bd38-11e5-88d5-b3de2bcaf727.png)

**Comment by mwaskom** [comment]
I'm not sure what you are expecting to happen, given that all of the weights appear have the same value? Could you maybe reduce the complexity of the example and show what you are expecting using matplotlib directly?

**Comment by fjaviersanchez** [comment]
Sure!

There it goes. I expect to fill the histogram with certain weight each time I fill certain entry instead filling it with a one. There it goes my example:

```
x = np.random.random_integers(1,3,size=10000)
plt.hist(x,weights=np.ones(10000)*1./10000.)
plt.figure()
sns.distplot(x, hist_kws={'weights':np.ones(10000)*1./10000.})
```

![matplotlib](https://cloud.githubusercontent.com/assets/13971732/12382074/c4572638-bd4a-11e5-8400-b6ea3f5d26d6.png)
![sns](https://cloud.githubusercontent.com/assets/13971732/12382075/c76e2ace-bd4a-11e5-8b51-dab2a0146c30.png)

The plot above is what I want seaborn to obtain and the plot below is what I obtain

Thanks!

**Comment by mwaskom** [comment]
Yes, the histogram is normalized when it's drawn with a density curve, otherwise the plot would make no sense.

**Comment by fjaviersanchez** [comment]
I solved my problem--it was that it doesn't use weights unless you deactivate the default kde option.

```
sns.distplot(x, hist_kws={'weights':np.ones(10000)*1./10000.}, kde=False)
```

**Comment by mwaskom** [comment]
More accurately: it uses the weights, but it normalizes them, so if every observation has the same weight there will be no apparent effect.
