### ISSUE TITLE
Barplot does not allow bar width to be set.

### ISSUE THREAD

**Issue by sjoerdvansteenkiste** [mwaskom/seaborn#824]
The `width` argument can not be passed in `barplot` to specify the bar width. Since this is possible for `boxplot` I assume this was not intended.

**Comment by TomAugspurger** [comment]
Do you have an example?

```python

In [26]: s = pd.Series([1, 2, 3])

In [27]: s.plot.bar(width=.1)
Out[27]: <matplotlib.axes._subplots.AxesSubplot at 0x1127b07f0>

In [28]: plt.figure()
Out[28]: <matplotlib.figure.Figure at 0x11a777390>

In [29]: s.plot.bar(width=.9)
Out[29]: <matplotlib.axes._subplots.AxesSubplot at 0x11a781128>
```

![narrow](https://cloud.githubusercontent.com/assets/1312546/12420165/91c6859c-be80-11e5-94d9-71d29971cfdd.png)

![wide](https://cloud.githubusercontent.com/assets/1312546/12420166/940bf788-be80-11e5-8cc3-11ebcb9ad25f.png)

**Comment by sjoerdvansteenkiste** [comment]
tips = sns.load_dataset("tips")
ax = sns.barplot(x="day", y="total_bill", hue="sex", data=tips, width=.3)

**Comment by mwaskom** [comment]
It is intended.

**Comment by brevans** [comment]
This becomes a larger problem, especially on larger plots when hue is chosen. Please see:
http://stackoverflow.com/questions/36092363/seaborn-boxplots-changes-narrows-width-of-boxes-when-a-hue-is-chosen-how-migh

It forces you to choose between having tiny boxes (or violins, etc) or generating your own color palette and then having to create a legend from scratch.

**Comment by alexpetralia** [comment]
Was @brevans issue ever looked at? I'm having this same issue as well on barplots. If you put in the `hue`, you get thin bars.

**Comment by HannesHolste** [comment]
Agreed with @alexpetralia, this does seem to unintended behavior when specifying `hue` and `palette`.

**Comment by mullenkamp** [comment]
I'm still confused on why this "is intended" as @mwaskom very briefly said. 
I see little explanation on why in this issue and the Seaborn docs also do not clarify this.
