### ISSUE TITLE
Regression plot with additional variable to control size

### ISSUE THREAD

**Issue by pls256** [mwaskom/seaborn#825]
I reference to the smoking lunch vs dinner example here:
https://stanford.edu/~mwaskom/software/seaborn/tutorial/regression.html#regression-tutorial

I would like to combine these two plots into one but still differentiate between lunch and dinner by varying the point size. Is this possible? Combination of a scatter and bubble plot. I would then want to plot the 4 regressions on 1 plot.

**Comment by mwaskom** [comment]
No, sorry. (And I don't think that would be an effective visualization).
