### ISSUE TITLE
feature: statistical significant asterisks in bar plot

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [mwaskom/seaborn#828]
It'd be nice to be able to run some sort of statistic (e.g. Mann-Whithney) to determine group differences in bar plots when hue is provided.  When significant (p<0.05) an asterisks can be added above those groups.
![download](https://cloud.githubusercontent.com/assets/8518288/12456390/302d0834-bf65-11e5-84fd-6e32e120d1d5.png)

**Comment by mwaskom** [comment]
Nope, never adding this, sorry.

**Comment by chethanjjj** [comment]
@ConstantinoSchillebeeckx Agreed, atleast if you have a column of significance stars, is there a way to add this to a bar chart?

**Comment by iromeo** [comment]
@mwaskom Could you share your opinion on the question above? Using stars to show which result is significant is quite widespread practice, I'd like to show them if I have significance info as a column in dataset or any other format.

**Comment by mmagnuski** [comment]
@iromeo and others: you may use https://github.com/webermarcolivier/statannot if you really need this, but I agree with @mwaskom that it should not be in seaborn.
