### ISSUE TITLE
how can i show chinese in plot

### ISSUE THREAD

**Issue by wyj2046** [mwaskom/seaborn#829]
hi, seaborn developers.

i'm using seaborn for data visualization, it's awesome.

but i'm in trouble when i want show chinese word in plot

python will report this issue: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

after google, i add this line, it will pass, but the word now become squae like this. 
import sys
reload(sys)
sys.setdefaultencoding('utf8')

![sex_day](https://cloud.githubusercontent.com/assets/1501757/12476139/5f03dbe4-c062-11e5-9c4b-f5354f48a5a7.png)

my environment is mac os10.10.3, python2.7.10, seaborn0.6.0

any suggestion will thanks

**Comment by Phlya** [comment]
Try puttin u in fron of your Chinese strings: `u'blabla'` instead of `'blabla'`

**Comment by wyj2046** [comment]
hi, Phlya
I try this way before, but it doesn't help, the word still show like square:(

**Comment by mwaskom** [comment]
please show a reproducible example of what you are trying to do, otherwise it will be impossible to help.

**Comment by wyj2046** [comment]
```python
# -*- coding: utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf8')
import seaborn as sns
import matplotlib.pyplot as plt


fig, ax = plt.subplots()
ax.set_title(u"哈哈")
# plt.show()
plt.savefig("/tmp/temp.png")
```

hi, mwaskom
this code snippet show this problem, i found that 'temp.png' title is still like square, 
but plt.show() is correct, it can show chinese word

**Comment by mwaskom** [comment]
I'm not sure, sorry, but I found that I reproduce the problem without importing seaborn:

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.set_title(u"哈哈")
fig.savefig("/tmp/temp.png")
```

![chinese](https://cloud.githubusercontent.com/assets/315810/12585640/c3a25150-c401-11e5-8d72-536ded5624ee.png)

Perhaps you should try asking on Stackoverflow.

**Comment by mwaskom** [comment]
Closing as not a seaborn issue.

**Comment by wyj2046** [comment]
ok, thanks mwaskom
