### ISSUE TITLE
loss of outliers in boxplot

### ISSUE THREAD

**Issue by simonm3** [mwaskom/seaborn#832]
If I import seaborn and then use pandas.boxplot then no outliers are shown even if these are explicitly set in parameters. It seems to me that just importing seaborn should not change the behaviour of plots made outside the seaborn package.

Not sure if this is intended behaviour or maybe there is a workaround.

For example:

    import pandas as pd
    import matplotlib.pyplot as plt 
    %matplotlib inline 
    url = 'https://raw.githubusercontent.com/cs109/2014_data/master/diamonds.csv'
    diamonds = pd.read_csv(url, sep = ',', index_col=0)
    plt.figure()
    ##### outliers are shown
    diamonds.boxplot('price', by = 'color', showfliers=True)
    import seaborn
    ##### now no outliers are shown
    plt.figure()
    diamonds.boxplot('price', by = 'color',  showfliers=True)

**Comment by mwaskom** [comment]
This is discussed in a few places, e.g. here http://stanford.edu/~mwaskom/software/seaborn/installing.html#known-issues

I believe it is fixed in matplotlib 2.0.
