### ISSUE TITLE
Max facets feature request

### ISSUE THREAD

**Issue by rgpdx** [mwaskom/seaborn#833]
I generate reports for my work and use Seaborn extensively along with reportlab. Within Seaborn specifically, I use the Facetgrid and Factorplot features often. Many times, however, the number of facets I have are quite large. To keep the text readable, I can't really shrink each individual facet below a certain size. 

is it possible to have a max_facets argument that can be passed as part of Facetgrid or Factorplot where if the number of facets goes above a certain value, then it breaks up the FacetGrid image into two separate images?

I currently do this manually by splitting up the pandas dataframe, but it would be nice to have this built into seaborn.

**Comment by mwaskom** [comment]
I don't think I'd be in favor of adding that, but have you tried `facet_wrap`?

**Comment by rgpdx** [comment]
I don't see facet_wrap anywhere in the seaborn documentation. Do you have a link or an example code block I can look at?

**Comment by mwaskom** [comment]
Sorry, I meant `col_wrap`: http://stanford.edu/~mwaskom/software/seaborn/examples/many_facets.html

**Comment by rgpdx** [comment]
Yes, I use col_wrap currently. The problem is that if I shrink my facets below a certain size, the information starts becoming hard to read.

The problem is such that if you have something like 24 facets, and each of them has to be 2.5" in size for readability and you use a col_wrap of 4  then the image is 10" x 16" which doesn't fit on a standard letter sized paper without scaling the image further

I currently accomplish this by adding another column in the dataframe, doing a groupby with that column and then plotting 2 separate images. It would be nice to do this automatically in seaborn, but I can see that this could be an application for one user only...

**Comment by mwaskom** [comment]
Yes, splitting up the DataFrame and making two figures is going to have to be up to the user.
