### ISSUE TITLE
axes.color_cycle is deprecated warning

### ISSUE THREAD

**Issue by marcomayer** [mwaskom/seaborn#835]
I get this warning with matplotlib 1.5.1 running with latest anaconda python 3.5 on OS X:

import seaborn

UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.

**Comment by stonebig** [comment]
yes, you may use the current git version of seaborn, that is pretty much as stable as a release

**Comment by marcomayer** [comment]
allright, thanks! I'll wait for the next release though since I'm using seaborn in a productive environment. Hope it's coming soon! :-)
