### ISSUE TITLE
Feature Request: Plotting Bootstrap Flexibility

### ISSUE THREAD

**Issue by dstuck** [mwaskom/seaborn#839]
I'm interested in calculating confidence intervals for barplot with smooth bootstrap, ideally with the ability to set the kde bw_method (I want to plot bootstrap medians with many zero values). Would exposing this to barplot be something that would be generally useful if I implemented it?

**Comment by mwaskom** [comment]
I would generally be opposed. Given the current way bootstrapping is done, this would require adding several additional parameters to each function that uses it.

There has been a little discussion of making more abstract objects for doing uncertainty estimation. This kind of thing would fit better within that framework. But that is a large project and not likely to happen any time soon, sorry.
