### ISSUE TITLE
Linear Regression Line on Facet Grid with Logarithmic Y axis

### ISSUE THREAD

**Issue by pls256** [mwaskom/seaborn#841]
I have this code working exactly as I want except I cannot workout how to get a linear regression line to plot.

This plots 2 colored datasets TypeA and TypeB on 3 plots separated by the value Divison with a Logarithmic Axes for Y only.

pal = dict(TypeA="seagreen", TypeB="gray")
g = sns.FacetGrid(df, hue="Source", col='Division', palette=pal, size=5)
g.map(plt.scatter, "X_Data", "Y_LogData")
g.add_legend();
g.set(yscale="log")

**Comment by mwaskom** [comment]
This is a better question for StackOverflow.
