### ISSUE TITLE
Seaborn plot of a time series random data and the ci doesn't represent the real confidence interval

### ISSUE THREAD

**Issue by sty1882** [mwaskom/seaborn#842]
![image](https://cloud.githubusercontent.com/assets/15190421/12669661/42755958-c69d-11e5-8883-d4a6fea5741a.png)
Several time series from 1990 to 2000, each year there are many random values (with index 0 to 19, actually more than 19, doesn't matter)

How to make a seaborn times series plot for Value1, Value2 and Value3 in the same time? I actually tried:
Data1 = pd.read_csv('WB_Sediments.csv', header=False, sep=',') #WB_Sediments.csv is the data I showed.
Data1=Data1.transpose()
ax = sns.tsplot(data=Data1.values,ci=70,estimator=np.mean, color='m',legend=True) # only for value1

It somehow worked, but the ci=70 is clearly not correct, it is much narrow than it should be, I don't know why..see below:
the actually Q15 and Q85 should have a factor 3 difference.
![figure_1](https://cloud.githubusercontent.com/assets/15190421/12669836/8a60cd46-c69e-11e5-81c4-1a36daa7a769.png)
Thanks~

**Comment by mwaskom** [comment]
What is your reasoning for saying the ci is wrong?

**Comment by sty1882** [comment]
Because my inverval is somehow around factor 2 or 3 of the mean value, say a example Q15 is 10, then mean is 25, Q185 is 75. The ci from plot is much narrower than what actually it is....

The data:
https://www.dropbox.com/sh/x9i7ffmaef97rm3/AACgE4uxzy4VZlpvyX_cZp5oa?dl=0

Basically I need to make a sns.tsplot for A,B,C,D,E,F in the same plot with different colors.

**Comment by mwaskom** [comment]
I think you should read up on what a [confidence interval](https://en.wikipedia.org/wiki/Confidence_interval) actually shows.

**Comment by sty1882** [comment]
First of all, many thanks Micheal for responsing me. And do you think is it possible to show percentile X and percentile Y, say percentile 15% and percentile 85% of the distribution of sampling instead of CI in the sns.tsplot()?
make it short, instead of ci=70 for example, here I would like to use 15% percentile and 85% percentile to show the bounds of the range.
if yes, how to do it?

**Comment by TomAugspurger** [comment]
You might have more luck asking on Stackoverflow with the seaborn and matplotlib tags. More people will see it that way.

**Comment by mwaskom** [comment]
> And do you think is it possible to show percentile X and percentile Y, say percentile 15% and percentile 85% of the distribution of sampling instead of CI in the sns.tsplot()?

No, sorry.
