### ISSUE TITLE
Passing argument from factorplot to hue_kws

### ISSUE THREAD

**Issue by SESmodeller** [mwaskom/seaborn#843]
Using seaborn for quite some time now and like it a lot! What I didn't understand yet how to debug if passing of arguments to lower functions does not work. See the recent open question on [stackoverflow](http://stackoverflow.com/questions/34702626/change-marker-size-in-seaborn-factorplot).

Would you mind answering this? I have trouble with the same issue but cannot upvote questions yet ...
In my similar example
```python

g = sns.factorplot(x="year", y="nutrients", hue="nutrCrit", data=myd, size=6, aspect = 1.5,
                   facet_kws = {"hue_kws" : {"marker": ['o', 'x', 's']}},
                   color = 'b')

```
I tried to encapsulate the hue_kws dictionary but it has no effect on the figure. Any suggestions?

**Comment by mwaskom** [comment]
`factorplot` doesn't use the hue faceting in `FacetGrid`. But `pointplot` has a `marker` argument so just pass the marker 

```
g = sns.factorplot(x="year", y="nutrients", hue="nutrCrit", data=myd, 
                   size=6, aspect=1.5, marker"=['o', 'x', 's'])
```

**Comment by SESmodeller** [comment]
Thanks for the quick reply! I tried the simpler marker argument before but it did not work.
