### ISSUE TITLE
old matplotlib version break PairGrid.map_upper and similar off diagonal calls

### ISSUE THREAD

**Issue by micheleAlberto** [mwaskom/seaborn#846]
I am sorry not to be able to provide decent insights on how to reproduce the bug. 
This is what i got:

``` python
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
%matplotlib inline
iris = sns.load_dataset("iris")
g = sns.PairGrid(iris)
g.add_legend()
g.map_diag(plt.hist)
g.map_upper(plt.scatter)
plt.show()
```

would produce a matrix of empty graphs. Curiosly this happened using in the plot functions such as:
map_upper
map_lower
map_offdiag
while map and map_diag would not cause the problem

i tried using as callbacks something like 
```python
def my_offdiag(x,y,**kwargs):
    plt.scatter(x,y)
    print 'mix :'
    #print x,y
    print kwargs
    
def my_diag(x,**kwargs):
    plt.hist(x)
    print 'diagonal :'
    #print x
    print kwargs

 ```
with that i could see the printed proofs that the callback got actually called but still no drawing on the graph

Here comes the good news (that IMHO makes this issue low priority ):
updating packages solved the issue

pip install seaborn --upgrade
pip install matplotlib --upgrade

**Comment by mwaskom** [comment]
This is a known issue. It was a bug in matplotlib that was fixed several releases ago.
