### ISSUE TITLE
Jointplot kde bug

### ISSUE THREAD

**Issue by jbwhit** [mwaskom/seaborn#849]
I was using jointplot to plot some data and kde was failing for a rather small dataset. Strangely, the other 'kind's appear to work. I have a full example: https://gist.github.com/jbwhit/ced729e87f59ed4408dd

**Comment by mwaskom** [comment]
The reference rules that is used to choose the default bandwidth for the KDE have various assumptions, which generally involve gaussian data. Your data are highly non-gaussian so I would assume those are failing (but I am not sure exactly what's happening with the plot).

Given the discrete nature of your data, I wouldn't think that a KDE is the right way to plot it anyway...
