### ISSUE TITLE
seaborn jointplt not working with subplot environment

### ISSUE THREAD

**Issue by jsudheer** [mwaskom/seaborn#850]
Hi,
          I am sorry if I am not posting this in correct group. 
         Is there a way to plot seaborn.jointplot in subplot environment so that multiple jointplots can me made in similar fashion as facegrid? I tried using ax=ax1 method but jointplot do not accept that.
Please help.
with best regards,
Sudheer

**Comment by mwaskom** [comment]
No. This is explained in depth [here](http://stackoverflow.com/questions/23969619/plotting-with-seaborn-using-the-matplotlib-object-oriented-interface).

**Comment by jsudheer** [comment]
Thank you for the link,

However when I try to use the same method for joint plot in below script
it gives an error

########
ERROR
########
/usr/local/lib/python2.7/dist-packages/matplotlib/artist.pyc in
update(self, props)
    737             func = getattr(self, 'set_' + k, None)
    738             if func is None or not callable(func):
--> 739                 raise AttributeError('Unknown property %s' % k)
    740             func(v)
    741             changed = True

AttributeError: Unknown property ax

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
TEST SCRIPT
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
import seaborn as sn
import numpy as np
import pylab as plt
xx=np.random.uniform(-1, 1, size=50)
yy=np.random.uniform(-1, 1, size=50)
f, (ax1, ax2) = plt.subplots(2)
sn.regplot(xx, yy, ax=ax1)
sn.jointplot(xx,yy,ax=ax2)
plt.show()


with best regards

Sudheer

**********************************************************************************
Dr. Sudheer Joseph

Scientist,

INCOIS, MoES, Govt. of India.
"OCEAN VALLEY" , Pragathi Nagar (BO), Nizampet SO,  Telangana, India. PIN-
500 090.
Tel:+91-9440832534(Mobile) Tel:+91-40-23886047(O),Fax:+91-40-23892910(O)
E-mail: sjo.India@gmail.com;  sjo@incois.gov.in.
-------------------* --------------------
"The ultimate measure of a man is not where he stands in moments of
comfort and convenience, but where he stands at times of challenge and
controversy."
                        Martin Luther King, Jr.
***********************************************************************************
