### ISSUE TITLE
color_palette() broken using matplotlib >=1.5

### ISSUE THREAD

**Issue by cfperez** [mwaskom/seaborn#851]
Python 3.4
Matplob >=1.5
Numpy 1.10.4
Seaborn 0.7.0

Simply running `color_palette()' throws the following error. This issue does not appear in Matplotlib 1.4.3.

ValueError                                Traceback (most recent call last)
site-packages/matplotlib/colors.py in to_rgb(self, arg)
    321                 raise ValueError(
--> 322                     'cannot convert argument to rgb sequence')
    323 

ValueError: cannot convert argument to rgb sequence

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
site-packages/seaborn/palettes.py in color_palette(palette, n_colors, desat)
    184         palette = map(mpl.colors.colorConverter.to_rgb, palette)
--> 185         palette = _ColorPalette(palette)
    186     except ValueError:

site-packages/matplotlib/colors.py in to_rgb(self, arg)
    327             raise ValueError(
--> 328                 'to_rgb: Invalid rgb arg "%s"\n%s' % (str(arg), exc))
    329             # Error messages could be improved by handling TypeError

ValueError: to_rgb: Invalid rgb arg "None"
cannot convert argument to rgb sequence

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-4-ec201e064c0e> in <module>()
----> 1 colors = sns.color_palette(n_colors=len(stations))

site-packages/seaborn/palettes.py in color_palette(palette, n_colors, desat)
    185         palette = _ColorPalette(palette)
    186     except ValueError:
--> 187         raise ValueError("Could not generate a palette for %s" % str(palette))
    188 
    189     return palette

ValueError: Could not generate a palette for <map object at 0x11476ac88>

**Comment by mwaskom** [comment]
I can't reproduce on my system, but I would need to see the actual code you are running, and also it looks like you have cut off the end of the traceback.

**Comment by cfperez** [comment]
The traceback just went on to print the ValueError message in line 187. I am only passing an integer to color_palette via n_colors e.g. `sns.color_palette(n_colors=22)`, though it also fails for me when I call with no arguments.

I'll try testing in a brand new conda environment.

**Comment by mmagnuski** [comment]
I can't reproduce too, I just pip updated seborn to 0.7 and `color_palette` still works.

My system:
```
windows 8
python 3.5.1
numpy 1.10.4
matplotlib 1.5.1
seaborn 0.7.0
```

**Comment by mwaskom** [comment]
I will also note that getting colors from the default palette happens a lot behind the scenes in seaborn, with any function that takes a `palette` argument, so if this functionality were broken I would expect to have run into it/heard about it at some point.

**Comment by cfperez** [comment]
Everything seems to work with matplotlib 1.5 in a fresh conda environment, so the likely explanation (despite the expectation that conda will prevent it) is that something got out of whack. If I can't reproduce in a few attempts e.g. by adding other packages, seems safe to assume it's just a fluke.

**Comment by zhoujli** [comment]
I got the same error running 'color_palette()'.

System info:
windows 7
python 3.5
numpy 1.10.4
matplotlib 1.5.1
seaborn 0.7.0

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
D:\Anaconda3\lib\site-packages\matplotlib\colors.py in to_rgb(self, arg)
    321                 raise ValueError(
--> 322                     'cannot convert argument to rgb sequence')
    323 

ValueError: cannot convert argument to rgb sequence

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
D:\Anaconda3\lib\site-packages\seaborn\palettes.py in color_palette(palette, n_colors, desat)
    184         palette = map(mpl.colors.colorConverter.to_rgb, palette)
--> 185         palette = _ColorPalette(palette)
    186     except ValueError:

D:\Anaconda3\lib\site-packages\matplotlib\colors.py in to_rgb(self, arg)
    327             raise ValueError(
--> 328                 'to_rgb: Invalid rgb arg "%s"\n%s' % (str(arg), exc))
    329             # Error messages could be improved by handling TypeError

ValueError: to_rgb: Invalid rgb arg "None"
cannot convert argument to rgb sequence

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-5-b00f8184f6f0> in <module>()
----> 1 sns.color_palette()

D:\Anaconda3\lib\site-packages\seaborn\palettes.py in color_palette(palette, n_colors, desat)
    185         palette = _ColorPalette(palette)
    186     except ValueError:
--> 187         raise ValueError("Could not generate a palette for %s" % str(palette))
    188 
    189     return palette

ValueError: Could not generate a palette for <map object at 0x000000000BBC1D68>`

**Comment by eontwosixt** [comment]
Yes, I get the same error  Could not generate a palette for  bla bla  ...
