### ISSUE TITLE
Automatic linewidth in swarmplots

### ISSUE THREAD

**Issue by rchurt** [mwaskom/seaborn#852]
I'm new to python, so I'm not sure if this can be done, but it would be helpful to have the "linewidth" argument in the swarmplot command automatically set to a default value if the "edgecolor" argument is passed, and vice versa. As it is, entering either argument by itself won't actually give you a line around the edge, which arguably it should.

**Comment by mwaskom** [comment]
Except the edgecolor has a default value, so it's not obvious when it has been "passed". It could default to `None`, and then trigger a nonzero linewidth if it is set to some valid color, but what is the behavior when `linewidth > 0` but `edgecolor is None`? That means there is complicated logic that is buried in the code and not obvious to the caller what is going to happen when a set of arguments are passed.

I would prefer to avoid that kind of complexity at the cost of somewhat more verbosity when the user wants non-default-colored edges.
