### ISSUE TITLE
Allows passing user-registers colormaps to color_palette

### ISSUE THREAD

**Issue by tritemio** [mwaskom/seaborn#855]
Currently, `color_palette()` does not recognize user-defined colormaps that have been registered with [`matplotlib.cm.register_colormap`](http://matplotlib.org/api/cm_api.html#matplotlib.cm.register_cmap).

Looking at the [code](https://github.com/mwaskom/seaborn/blob/master/seaborn/palettes.py#L168) seems like the culprit is the test `palette in dir(mpl.cm)` to check if the palette exists.
Seems that matplotlib has no function to retrieve the list of registered colormaps. However that test could be rewritten calling [matplotlib.cm.get_cmap](http://matplotlib.org/api/cm_api.html#matplotlib.cm.get_cmap) within a `try ... except`, so that custom names will be recognized.

There is a security issue though. This feature, if implemented, could allow a malicious user to circumvent the ban of the jet colormap in seaborn ;).

**Comment by mmagnuski** [comment]
Ouch, the Return of the Jet(i) ... :)

**Comment by mwaskom** [comment]
Fixed in #1217
