### ISSUE TITLE
Gracefully handling `np.nan`?

### ISSUE THREAD

**Issue by diego898** [mwaskom/seaborn#856]
I am trying to show a `pairplot` on a pandas dataframe, but it fails with the following error when there are `np.nan` present: `AttributeError: max must be larger than min in range parameter.`

In order to get it to work, I have to replace all of the `np.nan` with `0`. This seems strange, as other standard tools (eg: pandas), can deal with `np.nan` gracefully, ignoring them when calculating things like descriptive statistics.

**Comment by mwaskom** [comment]
`df.dropna()`

**Comment by diego898** [comment]
uh...ok... guess we can close this...

**Comment by pjadzinsky** [comment]
Hi,

Thanks for an awesome package. 

Although pairplot has dropna=True set up as default it is not working properly. Just execute the code below. I understand that we can dropna before calling pairplot but the parameter is already in the API and not working as expected.

`df = pd.DataFrame(np.random.randn(10,2))`
`df.loc[2,0] = np.nan`
`sns.pairplot(df)`

Thanks again

**Comment by anntzer** [comment]
Additionally, `dropna` ignores any row where any entry is `nan`, but a lot of other columns may still provide useful data for such rows.
