### ISSUE TITLE
Can't use load_dataset with Python 3.4.3

### ISSUE THREAD

**Issue by rowanv** [mwaskom/seaborn#857]
When attempting to load an included dataset using `sns.load_dataset('tips')` within a virtualenv in an iPython notebook, I get the trace I've included below. I've tried running the same notebook with the Python 2 kernel and it is able to load the data set just fine, it is only with the Python 3 kernel that the data set will not load. This worked for numerous other included data sets that I tried, not just `tips`. Python version is 3.4.3.

Input:

    import seaborn as sns
    %matplotlib inline
    sns.load_dataset('tips')

 And the traceback:

    IndexError                           
     Traceback (most recent call last)
    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/IPython/core/formatters.py in __call__(self, obj)
        695                 type_pprinters=self.type_printers,
        696                 deferred_pprinters=self.deferred_printers)
    --> 697             printer.pretty(obj)
        698             printer.flush()
        699             return stream.getvalue()

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/IPython/lib/pretty.py in pretty(self, obj)
        381                             if callable(meth):
        382                                 return meth(obj, self, cycle)
    --> 383             return _default_pprint(obj, self, cycle)
        384         finally:
        385             self.end_group()

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/IPython/lib/pretty.py in _default_pprint(obj, p, cycle)
        501     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
        502         # A user-provided repr. Find newlines and replace them with p.break_()
    --> 503         _repr_pprint(obj, p, cycle)
        504         return
        505     p.begin_group(1, '<')

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
        683     """A pprint that just redirects to the normal repr function."""
        684     # Find newlines and replace them with p.break_()
    --> 685     output = repr(obj)
        686     for idx,output_line in enumerate(output.splitlines()):
        687         if idx:

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/base.py in __repr__(self)
         62         Yields Bytestring in Py2, Unicode String in py3.
         63         """
    ---> 64         return str(self)
         65 
         66 

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/base.py in __str__(self)
         41 
         42         if compat.PY3:
    ---> 43             return self.__unicode__()
         44         return self.__bytes__()
         45 

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/frame.py in __unicode__(self)
        507             width = None
        508         self.to_string(buf=buf, max_rows=max_rows, max_cols=max_cols,
    --> 509                        line_width=width, show_dimensions=show_dimensions)
        510 
        511         return buf.getvalue()

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/frame.py in to_string(self, buf, columns, col_space, colSpace, header, index, na_rep, formatters, float_format, sparsify, index_names, justify, line_width, max_rows, max_cols, show_dimensions)
       1340                                            max_rows=max_rows,
       1341                                            max_cols=max_cols,
    -> 1342                                            show_dimensions=show_dimensions)
       1343         formatter.to_string()
       1344 

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/format.py in __init__(self, frame, buf, columns, col_space, header, index, na_rep, formatters, justify, float_format, sparsify, index_names, line_width, max_rows, max_cols, show_dimensions, **kwds)
        345             self.columns = frame.columns
        346 
    --> 347         self._chk_truncate()
        348 
        349     def _chk_truncate(self):

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/format.py in _chk_truncate(self)
        410             else:
        411                 row_num = max_rows_adj // 2
    --> 412                 frame = concat((frame.iloc[:row_num, :], frame.iloc[-row_num:, :]))
        413             self.tr_row_num = row_num
        414 

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/tools/merge.py in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, copy)
        753                        verify_integrity=verify_integrity,
        754                        copy=copy)
    --> 755     return op.get_result()
        756 
        757 

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/tools/merge.py in get_result(self)
        924 
        925             new_data = concatenate_block_managers(
    --> 926                 mgrs_indexers, self.new_axes, concat_axis=self.axis, copy=self.copy)
        927             if not self.copy:
        928                 new_data._consolidate_inplace()

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/internals.py in concatenate_block_managers(mgrs_indexers, axes, concat_axis, copy)
       4061                                                 copy=copy),
       4062                          placement=placement)
    -> 4063               for placement, join_units in concat_plan]
       4064 
       4065     return BlockManager(blocks, axes)

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/internals.py in <listcomp>(.0)
       4061                                                 copy=copy),
       4062                          placement=placement)
    -> 4063               for placement, join_units in concat_plan]
       4064 
       4065     return BlockManager(blocks, axes)

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/internals.py in concatenate_join_units(join_units, concat_axis, copy)
       4162             concat_values = concat_values.copy()
       4163     else:
    -> 4164         concat_values = com._concat_compat(to_concat, axis=concat_axis)
       4165 
       4166     return concat_values

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/common.py in _concat_compat(to_concat, axis)
       2998     elif 'category' in typs:
       2999         from pandas.core.categorical import _concat_compat
    -> 3000         return _concat_compat(to_concat, axis=axis)
       3001 
       3002     if not nonempty:

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/categorical.py in _concat_compat(to_concat, axis)
       1762 
       1763     # concat them
    -> 1764     return Categorical(np.concatenate([ convert_categorical(x) for x in to_concat ],axis=axis), categories=categories)

    IndexError: axis 1 out of bounds [0, 1)

    ---------------------------------------------------------------------------
    IndexError                                Traceback (most recent call last)
    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/IPython/core/formatters.py in __call__(self, obj)
        339             method = _safe_get_formatter_method(obj, self.print_method)
        340             if method is not None:
    --> 341                 return method()
        342             return None
        343         else:

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/frame.py in _repr_html_(self)
        541             return self.to_html(max_rows=max_rows, max_cols=max_cols,
        542                                 show_dimensions=show_dimensions,
    --> 543                                 notebook=True)
        544         else:
        545             return None

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/frame.py in to_html(self, buf, columns, col_space, colSpace, header, index, na_rep, formatters, float_format, sparsify, index_names, justify, bold_rows, classes, escape, max_rows, max_cols, show_dimensions, notebook)
       1391                                            max_rows=max_rows,
       1392                                            max_cols=max_cols,
    -> 1393                                            show_dimensions=show_dimensions)
       1394         formatter.to_html(classes=classes, notebook=notebook)
       1395 

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/format.py in __init__(self, frame, buf, columns, col_space, header, index, na_rep, formatters, justify, float_format, sparsify, index_names, line_width, max_rows, max_cols, show_dimensions, **kwds)
        345             self.columns = frame.columns
        346 
    --> 347         self._chk_truncate()
        348 
        349     def _chk_truncate(self):

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/format.py in _chk_truncate(self)
        410             else:
        411                 row_num = max_rows_adj // 2
    --> 412                 frame = concat((frame.iloc[:row_num, :], frame.iloc[-row_num:, :]))
        413             self.tr_row_num = row_num
        414 

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/tools/merge.py in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, copy)
        753                        verify_integrity=verify_integrity,
        754                        copy=copy)
    --> 755     return op.get_result()
        756 
        757 

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/tools/merge.py in get_result(self)
        924 
        925             new_data = concatenate_block_managers(
    --> 926                 mgrs_indexers, self.new_axes, concat_axis=self.axis, copy=self.copy)
        927             if not self.copy:
        928                 new_data._consolidate_inplace()

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/internals.py in concatenate_block_managers(mgrs_indexers, axes, concat_axis, copy)
       4061                                                 copy=copy),
       4062                          placement=placement)
    -> 4063               for placement, join_units in concat_plan]
       4064 
       4065     return BlockManager(blocks, axes)

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/internals.py in <listcomp>(.0)
       4061                                                 copy=copy),
       4062                          placement=placement)
    -> 4063               for placement, join_units in concat_plan]
       4064 
       4065     return BlockManager(blocks, axes)

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/internals.py in concatenate_join_units(join_units, concat_axis, copy)
       4162             concat_values = concat_values.copy()
       4163     else:
    -> 4164         concat_values = com._concat_compat(to_concat, axis=concat_axis)
       4165 
       4166     return concat_values

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/common.py in _concat_compat(to_concat, axis)
       2998     elif 'category' in typs:
       2999         from pandas.core.categorical import _concat_compat
    -> 3000         return _concat_compat(to_concat, axis=axis)
       3001 
       3002     if not nonempty:

    /Users/rowan/virtualenvs/r/bin/python3venv/lib/python3.4/site-packages/pandas/core/categorical.py in _concat_compat(to_concat, axis)
       1762 
       1763     # concat them
    -> 1764     return Categorical(np.concatenate([ convert_categorical(x) for x in to_concat ],axis=axis), categories=categories)

    IndexError: axis 1 out of bounds [0, 1)

**Comment by TomAugspurger** [comment]
What version of pandas do you have in that environment? Try upgrading that to a more recent version.

**Comment by mwaskom** [comment]
Yes, your Pandas version is the most relevant information.

The doctests (which use `tips` extensively) are tested on Python 3.4: https://github.com/mwaskom/seaborn/blob/master/.travis.yml

So it's not a generic problem with that version of Python.

**Comment by rowanv** [comment]
Ah hah, had pandas==0.16.2, upgraded to pandas==0.17.1 and it now works, thanks!
