### ISSUE TITLE
Discrete colormap for colorbar - heatmap

### ISSUE THREAD

**Issue by scls19fr** [mwaskom/seaborn#858]
Hello,

I'm plotting a heatmap like this

![capture d ecran 2016-02-11 a 20 22 54](https://cloud.githubusercontent.com/assets/109167/12987711/922b2332-d0fd-11e5-9a9a-ab79e876ea02.png)

This DataFrame contains only integers.

It will be nice (if in such a case ie integers values) - colorbar was a discrete colormap.

Kind regards

**Comment by mwaskom** [comment]
You can use a `ListedColormap`, that' all in the matplotlib layer though.

**Comment by scls19fr** [comment]
Maybe it could be automatic (and add on Seaborn side).
Detecting integers should automatically turn to a `ListedColormap`

**Comment by scls19fr** [comment]
Here is a discretized colorbar.

![capture d ecran 2016-02-12 a 07 56 02](https://cloud.githubusercontent.com/assets/109167/13000729/42a4cc3a-d15e-11e5-9606-ab1f1407dee2.png)

I have use this function https://scipy.github.io/old-wiki/pages/Cookbook/Matplotlib/ColormapTransformations.html

```python
def cmap_discretize(cmap, N):
    """Return a discrete colormap from the continuous colormap cmap.
    
        cmap: colormap instance, eg. cm.jet. 
        N: number of colors.
    
    Example
        x = resize(arange(100), (5,100))
        djet = cmap_discretize(cm.jet, 5)
        imshow(x, cmap=djet)
    """
    
    if type(cmap) == str:
        cmap = get_cmap(cmap)
    colors_i = concatenate((linspace(0, 1., N), (0.,0.,0.,0.)))
    colors_rgba = cmap(colors_i)
    indices = linspace(0, 1., N+1)
    cdict = {}
    for ki,key in enumerate(('red','green','blue')):
        cdict[key] = [ (indices[i], colors_rgba[i-1,ki], colors_rgba[i,ki]) for i in xrange(N+1) ]
    # Return colormap object.
    return matplotlib.colors.LinearSegmentedColormap(cmap.name + "_%d"%N, cdict, 1024)
```

I'm using it this way

```python
    N = df.max().max() - df.min().min() + 1
    cmap = cmap_discretize(cmap, N)
    ax = sns.heatmap(df, ax=ax, cmap=cmap, annot=True)
```


But I'm still facing an issue with numbers on colorbar (they should be integers and should be centered).


Any idea ?
