### ISSUE TITLE
Allow specifying of x position for categorical plots.

### ISSUE THREAD

**Issue by jrderuiter** [mwaskom/seaborn#859]
For some plots I am working on, I would like to be able to specify the x position of categorical plots such as the boxplot, the barplot and the violinplot. Current behaviour is to draw each x sequentially adjacent to one another. However, I would like to have x positions that reflect the true value of x (if numeric).

I know this can be currently be simulated by using order, however for large values of x this gives an  unreasonable overhead. Ideally (for sample), for the boxplots, seaborn would allow me to pass positions directly to plt.boxplot, thereby allowing me to directly specify the position of the boxes.

What do you think of this?

**Comment by mwaskom** [comment]
I would be against this.

**Comment by joelostblom** [comment]
I think this would be an useful feature for combining several plots on top of each other and combining with for example `plt.boxplot`. Another useful scenario would be when using polar plots in matplotlib. They currently do not allow for changing the x/theta limits, so instead I need to spread my points/bars evenly over 2 * pi.

**Comment by PabloBotas** [comment]
Hi! I was also trying to use this feature before realizing it's not supported. From my point of view, it would be very useful. Why is it that this would be such a bad idea? Are there technical reasons for it?

**Comment by michaelaye** [comment]
For boxplot specifically, I'm really surprised why it's not of a more general interest? If measurements are taken irregularly over time, but at each time spot a whole array of numbers with varying distributions, a boxplot that allows me to place the boxes according to their timestamp seems to be the best way to plot this?
