### ISSUE TITLE
lmplot doesn't adjust axes for small values

### ISSUE THREAD

**Issue by ariekahn** [mwaskom/seaborn#862]
lmplot doesn't properly adjust its axes for small data values (e.g. < 0.001)

Here's a simple example:
Expected behavior is what I see in regplot. Scaling both the x and y axes by a constant factor makes no difference to the overall chart appearance.

Scaling both x and y in lmplot hits a limit at x-tick marks of -0.008, -0.006, etc leading to all the points clustering in the center of the graph.

```
test = pd.DataFrame()
test['x'] = [0.0001, 0.0002, 0.0003, 0.0004]
test['y'] = [0,2,2.5,5]
```

```
sns.regplot(data=test,x='x',y='y')
sns.regplot(data=test*100,x='x',y='y')
```
![ex3](https://cloud.githubusercontent.com/assets/54182/13022525/2b033c22-d1b0-11e5-856f-78b973fd8000.png)
![ex4](https://cloud.githubusercontent.com/assets/54182/13022528/2d2b5fde-d1b0-11e5-88fb-fc7f25b8d35a.png)
```
sns.lmplot(data=test,x='x',y='y')
sns.lmplot(data=test*100,x='x',y='y')
```
![ex1](https://cloud.githubusercontent.com/assets/54182/13022521/266ada62-d1b0-11e5-91e9-3a4d8c9f1205.png)
![ex2](https://cloud.githubusercontent.com/assets/54182/13022524/29483202-d1b0-11e5-83fe-2b33766150c4.png)

```
sns.__version__
Out[171]: '0.7.0'

matplotlib.__version__
Out[161]: '1.5.1'

sys.version
Out[174]: '3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55) \n[GCC 4.2.1 (Apple Inc. build 5577)]'
```

**Comment by mwaskom** [comment]
`lmplot` isn't doing any scaling, that's all handled at the matplotlib level. I'm not sure what's causing the behavior you're seeing (but matplotlib is about to change their default scaling, so who knows).

**Comment by ariekahn** [comment]
Ok, yep, seems to be an issue with scatterplot itself, I'm getting the same behavior when using it directly.
