### ISSUE TITLE
Undocumented FacetGrid share{x,y}={'row', 'col'} option

### ISSUE THREAD

**Issue by jbradt** [mwaskom/seaborn#864]
When plotting with plain Matplotlib subplots, one can use, say, `sharey='row'` to share the y axis ticks across individual rows without making the y axis the same for every row. I tried this with FacetGrid and it worked as expected, but the docs only say

> **share{x,y}** : bool, optional
> If true, the facets will share y axes across columns and/or x axes across rows.

Perhaps this should also describe the 'row' and 'col' options like the docs for `plt.subplots`:

> **sharey** : string or bool
> If True, the Y axis will be shared amongst all subplots. If True and you have multiple columns, the y tick labels on all but the first column of plots will have visible set to False If a string must be one of “row”, “col”, “all”, or “none”. “all” has the same effect as True, “none” has the same effect as False. If “row”, each subplot row will share a Y axis and the y tick labels on all but the first column will have visible set to False. If “col”, each subplot column will share a Y axis.

**Comment by mwaskom** [comment]
Good catch, although for this kind of thing I would probably rather just mention that these are passed to `plt.subplots` so it's not necessary to keep up with any changes made upstream.
