### ISSUE TITLE
Rotating xtick labels in Seaborn FacetGrid plots

### ISSUE THREAD

**Issue by rgpdx** [mwaskom/seaborn#867]
Is there a way to rotate tick labels for individual facets in a FacetGrid? I have  a case where I need to use sharex = False switch in FacetGrid. My xticklabels are rather long and start to overlap. I would like to rotate all the xticklabels to 90 degree rotation. I'm currently using the g.set_xticklabels(rotation = 90) but this only rotates the tick labels for the lowest facets. Is there a way to apply to all facets?

The example below is for illustration purposes only- I realize that there is no need for rotating tick labels in the facets below. I'm only intending to highlight what I want to do.

![image](https://cloud.githubusercontent.com/assets/12300013/13094598/935bf170-d4c0-11e5-8b27-7f635c59df08.png)

**Comment by mwaskom** [comment]
Probably a bug in `g.set_xticklabels` that doesn't account for unshared axes (doing so can be a little tricky).

If you want to do it in a one-liner, you can do

`[plt.setp(ax.get_xticklabels(), rotation=90) for ax in g.axes.flat]`

**Comment by rgpdx** [comment]
Worked with a small modification to your suggestion. Not sure if I mis-interpreted your suggestion or just couldn't make it work, Either way, I was able to get what I wanted. Thanks for the help. Please close the issue.

![image](https://cloud.githubusercontent.com/assets/12300013/13188734/278e14b0-d708-11e5-9781-7149ad6e15b7.png)

**Comment by fernanhid** [comment]
I can honestly hug you guys! I've been trying to figure this out for a while!!!!!

**Comment by smdabdoub** [comment]
For future visitors, the above code snippet in text form:

```
for ax in g.axes.flat:
    for label in ax.get_yticklabels():
        label.set_rotation(0)
```

**Comment by cvanoli** [comment]
corrected the pasted code (y for x)

for ax in g.axes.flat:
    for label in ax.get_xticklabels():
        label.set_rotation(0)

**Comment by alienzj** [comment]
good answer!

**Comment by michaelsilverstein** [comment]
I find the following to be easiest:
```
for ax in g.axes.ravel():
    ax.set_xticklabels(ax.get_xticklabels(), rotation=90)
```

**Comment by sorenwacker** [comment]
Would be great to have something like:

    g = sns.relplot(...)
    g.xticks(rotation=90)
