### ISSUE TITLE
Taylor Diagram

### ISSUE THREAD

**Issue by jhamman** [mwaskom/seaborn#872]
Would there be interest in adding a Taylor Diagram (example shown below) to the seaborn api? I have a class that I'd be happy to put into a pull request if it would be accepted.  

![taylor prc_water_3](https://cloud.githubusercontent.com/assets/2443309/13365563/9e14e780-dc8a-11e5-803d-0f6f24b631db.png)

**Comment by mwaskom** [comment]
This is an interesting plot, but it doesn't really seem to fit will with the rest of what is currently in seaborn. At the moment I am less open to adding in a lot of one-off chart types that can't leverage the other tools (i.e. the `Grid` objects) or directly build on the established abstract APIs like in the categorical plots.

Additionally, my bandwidth is severely constrained for the foreseeable future, and I won't be able to spend any time reviewing an addition of this magnitude. So even if I'm wrong about point 1, it's not likely to actually land in seaborn any time soon.

**Comment by jhamman** [comment]
Okay, I get the bandwidth reasoning. Not so much on the API development or the receptiveness to outside contributions.  In any event, feel free to close this.
