### ISSUE TITLE
Drawing defects?

### ISSUE THREAD

**Issue by oligilo** [mwaskom/seaborn#878]
My _heatmap_ plots tend to exhibit drawing defects as can be seen in [this example](http://s23.postimg.org/rij88wgkr/adst_weighted_001.png); as if the _linewidth_ argument is not respected everywhere. They seem to repeat themselves in the same places in other plots. I am using a .5 line width with versions 0.7.0 of Seaborn 1.4.1 of Matplotlib.

I would appreciate if you would point me in the right direction.

**Comment by mwaskom** [comment]
I can't say without seeing what you're actually doing.

I'd recommend making a reproducible example and posting to StackOverflow.

**Comment by oligilo** [comment]
Thank you, I posted my question [here](http://stackoverflow.com/questions/35736350/potential-drawing-defect-in-seaborns-heatmap).
