### ISSUE TITLE
Diverging dataset and override of vmin/vmax

### ISSUE THREAD

**Issue by oligilo** [mwaskom/seaborn#879]
I am working with a set of matrices with elements between zero and one and I am using _clustermap_ with _vmin_ and _vmax_ keywords inherited from _heatmap_ so I guess this is an issue in both. I am not clear what exactly constitutes a "diverging dataset" but I would very much need a way to enforce the _vmin_ (=0) and _vmax_(=1) values in order to obtain consistent plots across the set of such matrices; otherwise one cannot compare two plots by their colors alone and needs to perform an additional transformation from one color scale/palette to the other (in their mind, to be able to compare these plots) which defeats the purpose of 'plotting' in this case.

Is there a way to harden _vmin_ and _vmax_ so that they are not overridden by seaborn?

**Comment by mwaskom** [comment]
I'm afraid I really can't offer much insight without seeing exactly what you are trying to do.

**Comment by oligilo** [comment]
I think I solved my problem; in this particular case it was a partial oversight on my part in the sense that I was still feeding the vmin and vmax values from matrix elements rather than explicitly setting them to 0 and 1 respectively. But even in this case, using the vmin and vmax values from the distance matrix, seaborn tends to choose a color scale in which the always-present maximum (1), is near the middle of color bar and so the matrix elements tend to receive the same color even though on a 0-1 scale they shouldn't.

And this is not specific to this case, I appreciate the aesthetics (and convenience) and so seaborn is my go-to package for plotting. My matrices are generally normalized for the [0,1] interval and I have seen this override to happen before: I use the vmin and vmax based on minimum and maximum of off-diagonal matrix elements and in some cases the override kicks in and paints most of the elements the same color. I still don't know what it means for a dataset to be diverging but if I'm going to make a wild guess it should be signaled by the presence of extreme outliers somehow.
