### ISSUE TITLE
seaborn.set breaks discrete points plotting with matplotlib

### ISSUE THREAD

**Issue by Phyks** [mwaskom/seaborn#881]
Hi,

```python
%matplotlib notebook
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="ticks")
fig, ax = plt.subplots()
ax.plot(range(10), "+")
fig.show()
```

renders
![a](https://cloud.githubusercontent.com/assets/3856586/13531372/7a0b360e-e226-11e5-80fd-0fc03ecfeb6a.png)

Whereas without the call to `seaborn.set`, we get the correct plot:
```python
%matplotlib notebook
import matplotlib.pyplot as plt
import seaborn as sns
sns.reset_orig()
fig, ax = plt.subplots()
ax.plot(range(10), "+")
fig.show()
```
![b](https://cloud.githubusercontent.com/assets/3856586/13531390/9fc26b56-e226-11e5-9b95-b775d70fce35.png)

Not sure if it is expected and I missed something or a real bug though.

Thanks!

**Comment by mwaskom** [comment]
See https://github.com/matplotlib/matplotlib/issues/4679 and various seaborn issues.

**Comment by Phyks** [comment]
@mwaskom Thanks for the pointers. I may have missed some points, but I do not get why I am still getting the issue (and the mew workaround works fine) although the pointed issues are closed both in `matplotlib` and `seaborn`.

Especially since (https://github.com/mwaskom/seaborn/issues/344#issuecomment-64088485):
> This workaround should now be in master and I'm going to release a 0.5.1 soon so that this is less of a hassle.

I am using seaborn 0.7.0 and matplotlib 1.5.1.

**Comment by mwaskom** [comment]
#344 is a different issue...

**Comment by Phyks** [comment]
I was talking about [this issue](https://github.com/mwaskom/seaborn/issues/344#issuecomment-73821955) which indeed is a different one from the original issue #344…

Still, I must admit I am a bit lost in all those issues. As far as I know, I am experiencing the issue same issue as [this one](https://github.com/mwaskom/seaborn/issues/344#issuecomment-73821955), which, fwiw, is not subsequently referenced in a separate and up to date issue on seaborn side, and the only place where it is referred to is a closed issue.

The described workaround for the original issue of #344 work exactly the same for my particular issue, and is implemented in https://github.com/mwaskom/seaborn/commit/e0d98c372b330c25417b536eccbec41d0e93a884, although for matplotlib 1.4.2 only, leaving this issue open for matplotlib 1.5.1.

The issue of reference on matplotlib side seems to be https://github.com/matplotlib/matplotlib/issues/4679, which is also marked as closed (and closed by a commit, not "won't resolve").

**Comment by mwaskom** [comment]
Please carefully read the links that I have already referenced. I do not have time to re-type information that is already available there.

**Comment by Phyks** [comment]
Ok, either I completely missed something, or we are really talking about different issues. I am not a seaborn guru, neither am I a matplotlib one, and I am just trying to understand the issue I have.

So, first things first, I am using up to date version of both `seaborn` and `matplotlib`, so there should not be any problem of issues solved in further versions.

Going back to my issue, it is exactly matched by [this comment](https://github.com/mwaskom/seaborn/issues/344#issuecomment-73821955). Reading on the same issue, I come across:

> That is a different issue than the one reported here. See matplotlib/matplotlib#4679

 And refering to https://github.com/matplotlib/matplotlib/issues/4679, I see it is closed by [this commit](https://github.com/matplotlib/matplotlib/commit/de7bc9331c19ce378df3a3c066cbf1b87fceb58a). I do not understand the lengthy details of the diff, but I guess I can trust it to solve the issue, as the issue remained closed afterwards. So, I tend to think it is indeed a closed issue on matplotlib side.

Going further in the issue, there is the `lines.mew` workaround (and another workaround), which works in my case, but are ugly workaround (in my opinion), especially if it is the user responsibility to handle them.

Then, continuing reading the issue, I come across:

> FWIW, matplotlib 1.4.2 is pretty old now and there's been both a bugfix release (1.4.3) and a new feature release (1.5) since then.

Which implicitly says that matplotlib 1.5.1 should no longer be affected by the issue discussed. Which is further confirmed in next message.

> @mizzao As stated above - use matplotlib 1.4.3 or later.

and finally, @mizzao seems to be in the same situation as me, still having to deal with the workaround, while we would have expected it to be integrated in Seaborn, from the discussion above.

Thanks

**Comment by mwaskom** [comment]
> I am not a seaborn guru, neither am I a matplotlib one, and I am just trying to understand the issue I have.

That's fine, but I took a quick look at your github profile and I noticed that the readme for [this project](https://github.com/Phyks/replot) is rather disparaging of matplotlib. I'm not particularly interested in providing free tech support to people who are so casually dismissive of others' hard work, particularly when it is clear that they have not put any effort into actually understanding the tools themselves.
