### ISSUE TITLE
ValueError on calling sns.reset_defaults()

### ISSUE THREAD

**Issue by DSLituiev** [mwaskom/seaborn#882]
I am trying to reset style to default after setting `sns.set(style="whitegrid", color_codes=True)`. I could not find the name of the default colour style in documentation, so I am using ` sns.reset_defaults()`.

I run ` sns.reset_defaults()` in Jupyter notebook, Python3.4, Ubuntu 14, seaborn 0.6.0

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.4/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    335                 pass
    336             else:
--> 337                 return printer(obj)
    338             # Finally look for special method names
    339             method = _safe_get_formatter_method(obj, self.print_method)

/usr/local/lib/python3.4/dist-packages/IPython/core/pylabtools.py in <lambda>(fig)
    205 
    206     if 'png' in formats:
--> 207         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    208     if 'retina' in formats or 'png2x' in formats:
    209         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

/usr/local/lib/python3.4/dist-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    115 
    116     bytes_io = BytesIO()
--> 117     fig.canvas.print_figure(bytes_io, **kw)
    118     data = bytes_io.getvalue()
    119     if fmt == 'svg':

/usr/local/lib/python3.4/dist-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2149         origedgecolor = self.figure.get_edgecolor()
   2150 
-> 2151         self.figure.dpi = dpi
   2152         self.figure.set_facecolor(facecolor)
   2153         self.figure.set_edgecolor(edgecolor)

/usr/local/lib/python3.4/dist-packages/matplotlib/figure.py in _set_dpi(self, dpi)
    409     def _set_dpi(self, dpi):
    410         self._dpi = dpi
--> 411         self.dpi_scale_trans.clear().scale(dpi, dpi)
    412         self.callbacks.process('dpi_changed', self)
    413     dpi = property(_get_dpi, _set_dpi)

/usr/local/lib/python3.4/dist-packages/matplotlib/transforms.py in scale(self, sx, sy)
   1993         scale_mtx = np.array(
   1994             [[sx, 0.0, 0.0], [0.0, sy, 0.0], [0.0, 0.0, 1.0]],
-> 1995             np.float_)
   1996         self._mtx = np.dot(scale_mtx, self._mtx)
   1997         self.invalidate()

ValueError: could not convert string to float: 'figure'

<matplotlib.figure.Figure at 0x7f7ef94a2198>
```

**Comment by mwaskom** [comment]
I am unable to reproduce this error.

To be helpful I'd need some more information. Specifically, what version of matplotlib are you using, and what matplotlib backend are you using?

If you look at the source code for `sns.reset_defaults`, all it is doing is:

```
def reset_defaults():
    """Restore all RC params to default settings."""
    mpl.rcParams.update(mpl.rcParamsDefault)
```

where `mpl` is `matplotlib`. It would be helpful to know what happens if you run that line directly in a fresh kernel, doing everything you were doing where you saw the error, but without importing or using seaborn.

PS the default palette is called `deep`, which you can see in the function signature for `sns.set` and other places.

**Comment by mwaskom** [comment]
I am also confused because the traceback starts with IPython code...you might need to be more clear about exactly what you are doing when you get the error.

**Comment by DSLituiev** [comment]
So I figured out that the error happens when I call the `sns.jointplot` after resetting the style.

Matplotlib version:

{'dirty': False,
 'error': None,
 'full-revisionid': 'c0728d23ca5adbff6b79cda3153d0d36bff12c55',
 'version': '1.5.1+1304.gc0728d2'}

**Comment by mwaskom** [comment]
Perhaps you could make a notebook that demonstrates the error and link to a gist of it? It's really hard to provide support when I have to guess at various aspects of what you're doing.

**Comment by DSLituiev** [comment]
This is indeed confusing. Could it be that seaborn catches and recast errors?
 
What I figured out:

The problem arises when I try to move the legend to a blank space in the figure and then call `reset_defaults`.  This is a minimal example:

```
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
tips = sns.load_dataset("tips")
g = sns.jointplot("total_bill", "tip",  data = tips[["total_bill", "tip"]].applymap(lambda x : -np.log10(x)))

## PLACE FIGURE IN THE OPTIMAL POSITION (automatic positioning does not work :-< )
legend = g.ax_joint.get_legend()
labels = (x.get_text() for x in legend.get_texts())
g.ax_joint.legend(legend.legendHandles, labels, loc='lower right')


## RESET
sns.reset_defaults()

## CALL PLOTTING AGAIN
g = sns.jointplot("total_bill", "tip",  data = tips[["total_bill", "tip"]] )

## ERROR 
...
```

**Comment by mwaskom** [comment]
I'm still unable to reproduce: https://gist.github.com/mwaskom/521f5935f854857cb690

Seaborn does not catch and recast errors. The error you showed me above is coming from IPython, probably when it tries to render the figure (i.e. after seaborn is done plotting it).

What happens when you do what I asked above, trying to plot without seaborn?

**Comment by DSLituiev** [comment]
The problem is with matplotlib as I see from this example

```
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
tips = sns.load_dataset("tips")

plt.scatter(tips["total_bill"], tips["tip"], label = "tips")
plt.legend()
ax = plt.gca()
legend = ax.get_legend()
labels = (x.get_text() for x in legend.get_texts())
## MOVE LEGEND
ax.legend(legend.legendHandles, labels, loc='lower right')
##RESET
plt.matplotlib.rcParams.update(plt.matplotlib.rcParamsDefault)
## PLOT
plt.plot([0,1], [0,1])

##ERROR
```

**Comment by mwaskom** [comment]
Try it without importing seaborn at all, though?

**Comment by DSLituiev** [comment]
same
I suggest to close. Upstream bug

**Comment by DSLituiev** [comment]
Opened Issue [#6113 in matplotlib](https://github.com/matplotlib/matplotlib/issues/6113)
