### ISSUE TITLE
Python Seaborn - No cell generated

### ISSUE THREAD

**Issue by datomnurdin** [mwaskom/seaborn#884]
I got no error messages but there are no cell generated after I execute my python script. I'm using EI-Capitan and python 2.7.

    import pandas as pd
    import warnings
    import seaborn as sns
    import matplotlib.pyplot as plt
    sns.set(style="white", color_codes=True)
    adult = pd.read_csv("data.csv")
    adult.head()

Please advice. Thank you.

**Comment by TomAugspurger** [comment]
That seems to have nothing to do with seaborn, right? `adult` is a pandas DataFrame, and you're presumably running this in a Jupyter notebook. Perhaps try stackoverflow.

**Comment by datomnurdin** [comment]
Sorry. I close this issue.
