### ISSUE TITLE
Mesh covers inward facing ticks

### ISSUE THREAD

**Issue by HaMF** [mwaskom/seaborn#889]
When using seaborn.set_style("ticks", {"xtick.direction": "in", "ytick.direction": "in"}) to have inward facing ticks, a mesh object (possibly others as well) in the plot covers the ticks.
Standard matplotlib behaviour is that the ticks are visible regardless of the plot contents. This makes much more sense I think. ("I'm asking for ticks, I want ticks.")

Reproduced by the following code (uncomment importing seaborn). See images below.
```
import matplotlib.pyplot as plt
import numpy as np
#import seaborn as sns
#sns.set_style('ticks', {"xtick.direction": "in", "ytick.direction": "in"})

dx, dy = 0.05, 0.05
y, x = np.mgrid[slice(1, 5 + dy, dy),
                slice(1, 5 + dx, dx)]
z = np.sin(x)**10 + np.cos(10 + y*x) * np.cos(x)

plt.pcolormesh(x, y, z, cmap="Greys")
```
![figure_1_sns](https://cloud.githubusercontent.com/assets/66372/13842479/ac8c948a-ec2e-11e5-8b22-1c3ce788174c.png)
![figure_1_mpl](https://cloud.githubusercontent.com/assets/66372/13842480/ac8db248-ec2e-11e5-86ee-1294f97c155c.png)

**Comment by mwaskom** [comment]
Try setting `"axes.axisbelow": False`.

**Comment by HaMF** [comment]
Thanks for the quick reply. I wasn't aware of that option. Solved it, thanks!
