### ISSUE TITLE
FacetGrid shows only first plot, when cols are set and the col_wrap=1

### ISSUE THREAD

**Issue by sw1010** [mwaskom/seaborn#890]
I have encountered a problem with FacetGrid which shows only first plot, when the col_wrap=1. I use these versions of tools:
seaborn 0.7.0
matplotlib 1.5.1
python 2.7.6
 
Exemplary code:
```
import matplotlib.pyplot as pyplot
import pandas
improt seaborn

df = pandas.DataFrame.from_dict({"a" : {"x" : 1, "y": 2, "type":"one"}, "b" : {"x": 6, "y" : 7, "type": "two"}, "c" : {"x":53, "y":54, "type":"one"}, "d" : {"x":43, "y":16, "type": "two"}}, orient="index")

grid = seaborn.FacetGrid(df, col="type", col_wrap=1)
grid.map(pyplot.scatter, "x", "y")
pyplot.show()
```

The plot for type=="two" does not appear. Obviously, this could be replaced by using row instead col when instantiating FacetGrid, but rather such result indicates a corner-case problem in FacetGrid's calculations.

**Comment by mwaskom** [comment]
I am aware of this issue, although I don't know what the cause is. Given that it is easily avoided, finding out is not a priority.

**Comment by mwaskom** [comment]
Fixed with https://github.com/mwaskom/seaborn/pull/1453
