### ISSUE TITLE
FYI: newest version of iPython results in deprecated imports for seaborn

### ISSUE THREAD

**Issue by Auerilas** [mwaskom/seaborn#892]
I updated iPython to the newest version. When I import seaborn (whether in standard python or in iPython), I get the warning:

    import seaborn as sns
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
      "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)

Just a heads up

**Comment by mwaskom** [comment]
This is because seaborn tries to import the widgets from all the places they could possibly live, and you do not have the newest iteration (`ipywidgets`).

**Comment by yoavram** [comment]
How about wrapping the old import (from `IPython.html`) with a [warnings context manager](https://docs.python.org/2/library/warnings.html#temporarily-suppressing-warnings) and filter out the warnings?

```py
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    from IPython.html import ...
```
Will you support this solution?
