### ISSUE TITLE
fix tick label alignment with data points

### ISSUE THREAD

**Issue by szeitlin** [mwaskom/seaborn#895]
sns.__version__ '0.7.0'
mpl.__version__'1.5.1'

Could be user error, feel free to correct me if my usage is wrong. 

What I'd like to do is a linear regression plot with categorical labels for the 'timepoints' along the x-axis. I'm making the plot using integers initially, and then adding the text labels. I expected the text labels to just replace the integers, but that doesn't seem to be all that's happening. 

Initially, only half the labels were showing, so I tried turning on a different Locator option to see if I could get more labels to appear. That sort of worked, but essentially it's very difficult (if not impossible?) to get text labels aligned with the correct data points. Seems like the x-axis is either shifted left or the right-hand side gets truncated. 

![screen shot 2016-03-28 at 4 55 54 pm](https://cloud.githubusercontent.com/assets/5185401/14093860/fde6a52a-f505-11e5-9b67-7c41a7576e23.png)

![screen shot 2016-03-28 at 4 57 01 pm](https://cloud.githubusercontent.com/assets/5185401/14093888/2cbe9c4a-f506-11e5-900a-cea3b4e918c6.png)

![screen shot 2016-03-28 at 4 59 37 pm](https://cloud.githubusercontent.com/assets/5185401/14093931/8e9a1bec-f506-11e5-88d7-71811b0eb6de.png)

**Comment by mwaskom** [comment]
You could try `ax.set(xticks=range(names), xticklabels=names)` I think?

**Comment by szeitlin** [comment]
that worked for aligned the labels, but now the regression line is gone. :disappointed:  I'm having lots of problems that I never had before - presumably due to changes in matplotlib (?).

**Comment by mwaskom** [comment]
This seems to work for me?

```python
import numpy as np
import seaborn as sns
x, y = np.random.uniform(1, 6, (2, 100))
ax = sns.regplot(x, y, lowess=True)
ax.set(xticks=range(1, 7), xticklabels=list("abcdef"))
```
![image](https://cloud.githubusercontent.com/assets/315810/14322949/77704f30-fbd3-11e5-9d2e-9c7e5a2cd17c.png)

**Comment by szeitlin** [comment]
I had to do it without lowess, and then add it back, then it worked. I don't know why that would be. 

I'm having missing label issues with heatmap:

`subset.head()` looks like this:
![screen shot 2016-04-06 at 4 25 03 pm](https://cloud.githubusercontent.com/assets/5185401/14335947/3c9b48f6-fc14-11e5-9d1a-fdfdb1633723.png)


```python
    corr = subset.corr() 
    mask = np.zeros_like(corr, dtype=np.bool) 
    mask[np.triu_indices_from(mask)] = True
    f, ax = plt.subplots(figsize=(11, 9))
    cmap = sns.diverging_palette(220, 10, as_cmap=True)
    sns.heatmap(corr, mask=mask, cmap=cmap, 
            square=True, xticklabels=5, yticklabels=5,
            linewidths=.5, cbar_kws={"shrink": .5}, ax=ax)
```

do I need to rotate the labels or something? I don't remember having this problem before. It looks like there's enough space, I would have expected it to cram everything or more labels, anyway, in there, even if it's overlapping, not drop them?

![screen shot 2016-04-06 at 4 27 14 pm](https://cloud.githubusercontent.com/assets/5185401/14335976/87cd1f52-fc14-11e5-8b3b-865f8fa6be74.png)

**Comment by mwaskom** [comment]
`xticklabels=5` means "plot every 5th x tick label"

**Comment by szeitlin** [comment]
aha, thanks. I was just blindly following the example in the docs.

**Comment by szeitlin** [comment]
so tell me why it seems like the figure size isn't changing no matter what I do with this?

```python
    sns.set_style("whitegrid")
    sns.set_context("poster")
    sns.set_context("talk")
    plt.figure(figsize=(8, 6))
    sns.factorplot(x='team', y='estimated_points', hue='ticket_type', data=points_by_team, kind='bar')
```

Presumably I have to manually change the size of the xaxis? But the defaults used to just work?

![screen shot 2016-04-06 at 5 06 41 pm](https://cloud.githubusercontent.com/assets/5185401/14336553/0247543c-fc1a-11e5-8673-662492059e56.png)

**Comment by szeitlin** [comment]
oh, nevermind. I found this issue. Would be happy to help update docs if that would help save people like me from pestering you with questions like this. 

http://stackoverflow.com/questions/26163702/how-to-change-figuresize-using-seaborn-factorplot
