### ISSUE TITLE
Change linewidth and markersize independently in factorplot/pointplot? 

### ISSUE THREAD

**Issue by kevincha** [mwaskom/seaborn#899]
I realize that in the current code, the markersize is proportional to the linewidth. Is there a way to override this and set the markersize using `lines.markersize` or some other arguments?

```python
        # Get the size of the plot elements
        lw = mpl.rcParams["lines.linewidth"] * 1.8 * self.scale
        mew = lw * .75
        markersize = np.pi * np.square(lw) * 2
```

**Comment by mwaskom** [comment]
You can change the sizes of the points after plotting:

```
x = np.random.randn(20, 3)
ax = sns.pointplot(data=x)
plt.setp(ax.collections, sizes=[100])
```

**Comment by kevincha** [comment]
How do I scale the marker size in the legend to be the same as the markersize after `plt.setp(ax.collections, sizes=[100])`? The markersize in the legend is proportional to linewidth.
