### ISSUE TITLE
width parameter for bar plots?

### ISSUE THREAD

**Issue by amelio-dx** [mwaskom/seaborn#901]
I presume the answer is no, but is there any way to specify the width of bars in a bar plot through kw? 

If I try to do:
```
  sns.barplot(x='treatment', y='value', data=to_plot, palette="deep", ax=ax, order=ordered_x, width=0.35)
```
I end up with:

`TypeError: bar() got multiple values for argument 'width'`

**Comment by mwaskom** [comment]
Your presumption is correct, the answer is no, unfortunately.
