### ISSUE TITLE
log-scale-intensity kde

### ISSUE THREAD

**Issue by wfbradley** [mwaskom/seaborn#902]
If I am viewing a bivariate distribution with jointplot(), the most common events may overshadow the tails.  To address that, I can logarithmically scale the bin counts, by using jointplot(...,kind='hex',bins='log').

I'd like to do the same thing with a kernel density estimate (kind='kde').

If this is currently impossible to do, may I put in a feature request?  And if it's possible, how would I do it?

Thank you.

**Comment by mwaskom** [comment]
The bivariate KDE is drawn with `pyplot.contour{f}`. Some combination of the `levels` parameter and a logarithmic norm for the colormap will probably get you what you want (though it's not totally clear from the question).
