### ISSUE TITLE
Twin Y axis in Facetgrid

### ISSUE THREAD

**Issue by rgpdx** [mwaskom/seaborn#903]
Hello, I'm trying to do the following. I'd like to have a set of subplots where I have a bar plot and a pointplot plotting two quantities Q1 and Q2 in a Facetgrid overlaid on top of each other. I'd like to have the barplot referenced on the left Y axis and the pointplot referenced by the right Y-axis in each facet. Here is my code so far -

![image](https://cloud.githubusercontent.com/assets/12300013/14545041/e6bae610-0250-11e6-96e5-ced863c153ea.png)

![image](https://cloud.githubusercontent.com/assets/12300013/14545048/f7d4adf0-0250-11e6-957b-658166a535aa.png)

I'm most of the way there. However, I'd like to have ylable = Q1 displayed on the left and Q2 displayed on the right of each Facet. 
Matplotlib has an option to do this using the ax2 = ax1.twinx() option. How do I excercise that in this seaborn plot?

**Comment by mwaskom** [comment]
You'll have to use the list of axes at `FacetGrid.axes` to add the twins, and I wouldn't expect it to really work all that well in the context of the FacetGrid. As you may know, twin y axes are typically considered a visualization anti-pattern, as they can be very misleading. But given that matplotlib supports them, I'm sure it's possible to hack together a solution.
