### ISSUE TITLE
Clustermap TypeError after updating several packages

### ISSUE THREAD

**Issue by ilyavs** [mwaskom/seaborn#906]
Hi,
I updated matplotlib to version 1.5.1 and scipi to version 0.17. Now whenever I run the clustermap function I get the following  error:
TypeError: dendrogram() got an unexpected keyword argument 'color_list'

Example code to reproduce the error (from the seaborn examples in the docs):
import seaborn as sns; sns.set()
flights = sns.load_dataset("flights")
flights = flights.pivot("month", "year", "passengers")
g = sns.clustermap(flights)

Please fix this as soon as possible.

Thanks,
Ilya.

**Comment by mwaskom** [comment]
https://github.com/mwaskom/seaborn/pull/845

**Comment by WolfLo** [comment]
I am still being thrown this TypeError by clustermap, even after updating scipy to version 1.1.0. Any advice please?

**Comment by WolfLo** [comment]
> I am still being thrown this TypeError by clustermap, even after updating scipy to version 1.1.0. Any advice please?

Just solved the issue by `pip3 install --upgrade seaborn`
