### ISSUE TITLE
Seg fault when importing module

### ISSUE THREAD

**Issue by j-andrews7** [mwaskom/seaborn#907]
This is a strange one. Whenever I try to `import seaborn` I get a `segmentation fault (core dumped)` error, both with 0.7 and 0.8dev. I have no problems importing anything else. I'm using python3.4.4, numpy 1.11.0, pandas 0.18.0, matplotlib 1.5.1, and scipy 0.17.0 (all of which can be imported and used) in a conda virtualenv running the anaconda3-2.3.0 distribution.  

I also tried installing with pip, conda, and from source, but still have the same problem. Attempting to run the tests either with `make test` or `nosetests` both fail with a seg fault. I've really got no clue what my issue is, was hoping someone may have run into a similar problem at some point. Let me know if any other info is needed.

**Comment by mwaskom** [comment]
That is quite strange. My suggestion would be to try setting the matplotlib rcparams that are set as part of the process of importing seaborn and see if that triggers it. Maybe something about the fonts? I think font-related compilation is often a pain point in installing matplotlib, and seaborn changes the default font.

Were the dependencies installed with conda or did you compile them yourself?

**Comment by j-andrews7** [comment]
They were installed with conda. I tried it on another machine and it worked
fine. The issues I have are on a cluster. I'll try making a new virtualenv
and just installing from scratch. I haven't been able to get any errors to
throw when messing with the matplotlib rcParams:

```Python
>>> import matplotlib as mpl
>>> mpl.rcParams['font.family'] = 'serif'
>>> mpl.rcParams['font.size'] = 8
>>> mpl.rcParams['font.serif'] = 'Utopia'
>>> mpl.rcParams['font.family'] = 'fantasy'
>>> mpl.rcParams['font.fantasy'] = 'Charcoal'

```

**Comment by mwaskom** [comment]
Well I think the most useful test would be with the specific fonts that seaborn is trying to set.

**Comment by j-andrews7** [comment]
I'm closing this and chalking it up to our cluster's Anaconda install being quite old. I messed with changing the matplotlib fonts and such to no end and couldn't pinpoint what was going on.

**Comment by manugarri** [comment]
Old thread, but I am experiencing the same error in Ubuntu 18.04 using a conda environment

**Comment by manugarri** [comment]
FYI, I uninstalled seaborn and matplotlib and reinstalled seaborn only via pip. When importing it I get this warning:

```
>>> import seaborn
/home/manugarril/anaconda3/envs/testing/lib/python3.6/site-packages/matplotlib/font_manager.py:229: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. 
```
After that warning, everything looks ok.


So i agree with you regarding the font cache issue

**Comment by grzadr** [comment]
I am using Docker image based on jupyter/datascience-notebook:latest. Trick with installing seaborn with pip doesn't work. Importing seaborn still gives Segmentation fault.

**Comment by grzadr** [comment]
After little investigation problem lies in matplotlib. Importing matplotlib.pyplot also results in Segmentation fault. Deleting ~/.matplotlib and following https://support.enthought.com/hc/en-us/articles/207291386-Matplotlib-1-5-1-Font-Cache-Warning instructions doesn't seem to work. Also downgrading matplotlib is not a way to go.

**Comment by grzadr** [comment]
After digging and experimenting with conda in Docker image I managed to find the source of the problem. At some point during building my image I executed 'conda update --all --yes'. This messed up my conda environment. After removing this line, rebuilding Docker image and manually updating matplotlib and seaborn to their newest releases everything works fine.

**Comment by scaleoutsean** [comment]
`pip3 install --user --upgrade pyqt5==5.13.2` fixed it for me with seaborn v0.9.0 and matplotlib v3.1.2

**Comment by Hadrien-Cornier** [comment]
I experienced the same bug and I managed to fix it without understanding HOW I fixed it .

In my case the segmentation fault happens when I import seaborn AFTER a module that is inside my project but when I change the order of the imports and I put seaborn first, the problem goes away.

What is even stranger is that the problem happens when I run the program within a conda env that is a copy from a yaml file of an orginal conda env but weirdly does not happen with the original conda env. 

I have no idea why.

I was running seabon version 0.10.1

**Comment by megies** [comment]
I get segmentation faults when trying to `import seaborn` later on in a script nested into a routine that does violin plots after making some other matplotlib plots before. Goes away when importing seaborn at the start of the script after all other imports.
