### ISSUE TITLE
Installation issue under Visual Studio 2015 Update 2

### ISSUE THREAD

**Issue by baqwas** [mwaskom/seaborn#908]
Cannot install **seaborn** under Visual Studio 2015 Update 2 (Windows 10) or Ubuntu MATE (Desktop 1.8.2). Fully understand the recommendation about Anaconda and perhaps will go that route as a last resort.

Wading through the dependencies but I have installed all the pre-requisites mentioned at the web site.

Regards.

**Comment by mwaskom** [comment]
It's impossible for me to do anything without any actual details about what the problem is..
