### ISSUE TITLE
Error estimation at CategoricalStatPlotter

### ISSUE THREAD

**Issue by hajifkd** [mwaskom/seaborn#910]
Hi,

Sometimes, in particular in natural science, the data itself have intrinsic errors from the calibration of detectors or something like that.
Now, in seaborn.categorical.*plot, errors are estimated only using the estimator like np.mean.
It seems to me that there is no alternative way to include an independent error, so I raise this issue.
If you agreed with me, I could implement it. How do you think?

Last but not least, thank you very much for this great library!

**Comment by mwaskom** [comment]
There are methods in matplotlib for plotting error bars from error values you provide. Doing so is outside the current scope of seaborn.
