### ISSUE TITLE
axes_style() should not over-ride user's font list

### ISSUE THREAD

**Issue by miketrumpis** [mwaskom/seaborn#913]
Great project, this has revolutionized my plotting!  I just ran into a minor annoyance.  The axes_style method sets default font style to "sans-serif" (fine).  Then the sans-serif font list is set to a hard-coded list (not cool!).  I see that this could be over-ruled by keyword args.  But I don't think the font-list should be set, unless no sans-serif font is specified in the default params.

Here's a commit that changes the behavior:  f3bbdb0

**Comment by mwaskom** [comment]
I'm not sure what the complaint is here? `seaborn` changes the font as part of its default style.

**Comment by miketrumpis** [comment]
I think changing the font style to sans-serif is valid.  But suppose I have a preferred sans-serif font (say Helvetica) with priority in 'font.sans-serif'.  Then I'm surprised to see 'font.sans-serif' get set to a new list of fonts after a call to set_style.

**Comment by mwaskom** [comment]
`sns.set_style(rc={"font.famly": "Helvetica"}`
