### ISSUE TITLE
FacetGrid with boxplot: unexpected keyword argument 'label'

### ISSUE THREAD

**Issue by cachitas** [mwaskom/seaborn#915]
Mapping a boxplot in a FacetGrid

```
import matplotlib.pyplot as plt
import seaborn as sns

tips = sns.load_dataset("tips")

g = sns.FacetGrid(tips, col="time", hue="sex", margin_titles=True)
g.map(plt.boxplot, "total_bill")
```
raises 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-32b48da75c8a> in <module>()
      5 
      6 g = sns.FacetGrid(tips, col="time", hue="sex", margin_titles=True)
----> 7 g.map(plt.boxplot, "total_bill")

/home/.../python3.4/site-packages/seaborn/axisgrid.py in map(self, func, *args, **kwargs)
    725 
    726             # Draw the plot
--> 727             self._facet_plot(func, ax, plot_args, kwargs)
    728 
    729         # Finalize the annotations and layout

/home/.../python3.4/site-packages/seaborn/axisgrid.py in _facet_plot(self, func, ax, plot_args, plot_kwargs)
    809 
    810         # Draw the plot
--> 811         func(*plot_args, **plot_kwargs)
    812 
    813         # Sort out the supporting information

TypeError: boxplot() got an unexpected keyword argument 'label'
```

I believe this happens because [the keyword in maptlotlib changed to `labels`](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.boxplot).

```
matplotlib==1.5.1
seaborn==0.7.0
```

**Comment by mwaskom** [comment]
Nothing I can do about that, then. `FacetGrid` requires that the function to be mapped accept and understand a `label` kwarg. Unfortunate that matplotlib is breaking what was otherwise a very consistent API. Fortunate that `seaborn.boxplot` exists.

**Comment by MrKriss** [comment]
Looks like this is still an issue in `seaborn 0.7.1` with `matplotlib 1.5.1` 

Just tried with the seaborn version of boxplot, but looks like it is passing the `label` kw variables through to matplotlibs boxplot.

https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L460 

Full example below. 

```
import seaborn as sns
tips = sns.load_dataset("tips")

g = sns.FacetGrid(tips, col='day', hue='sex')
g = g.map(sns.boxplot, "time", "total_bill")
```

**Comment by mwaskom** [comment]
You should put `hue` in the call to `map` not to `FacetGrid` and better yet you should use `factorplot` or else you risk running into some very tricky issues.

**Comment by karthik1024** [comment]
One reason to use `FacetGrid` instead of `factorplot` is if we want to do swarm plots on top of boxplots as shown in the boxplot tutorials. I don't think we can do that with `factorplot`.

**Comment by phineas-pta** [comment]
Now with the version 0.9.0, you can try the function [`catplot`](https://seaborn.pydata.org/whatsnew.html#api-changes)

**Comment by SachitNayak** [comment]
> Looks like this is still an issue in `seaborn 0.7.1` with `matplotlib 1.5.1`
> 
> Just tried with the seaborn version of boxplot, but looks like it is passing the `label` kw variables through to matplotlibs boxplot.
> 
> https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L460
> 
> Full example below.
> 
> ```
> import seaborn as sns
> tips = sns.load_dataset("tips")
> 
> g = sns.FacetGrid(tips, col='day', hue='sex')
> g = g.map(sns.boxplot, "time", "total_bill")
> ```

Yeah this still is an issue... I'm facing the same error still... haven't tried catplot yet...

**Comment by max-lv** [comment]
I had this problem today. Here is a workaround:
```python
import seaborn as sns
tips = sns.load_dataset("tips")

def fixed_boxplot(*args, label=None, **kwargs):
    sns.boxplot(*args, **kwargs, labels=[label])

g = sns.FacetGrid(tips, col='day', hue='smoker')
g.map(fixed_boxplot, 'smoker', 'total_bill')
# And you can do swarmplot on top
g.map(sns.swarmplot, 'smoker', 'total_bill', color='0.25', order=['Yes','No'])
```

**Comment by mwaskom** [comment]
That workaround is not necessary:

```python
tips = sns.load_dataset("tips")
order = ["Yes", "No"]
g = sns.catplot(x="smoker", y="total_bill", col="day", kind="box", order=order, data=tips)
g.map(sns.swarmplot, 'smoker', 'total_bill', color='0.25', order=order)
```

**Comment by soerendip** [comment]
With seaborn.boxplot this happens: 

    TypeError: boxplot() got an unexpected keyword argument 'label'

**Comment by pomkos** [comment]
The workaround worked great on my end. Using sns.catplot seemed more complicated, as the boxplots were not centered on the x-axis ticks. Rather than look around for that issue, the workaround allowed for a 2 line code fix. Thank you!

> I had this problem today. Here is a workaround:
> 
> ```python
> import seaborn as sns
> tips = sns.load_dataset("tips")
> 
> def fixed_boxplot(*args, label=None, **kwargs):
>     sns.boxplot(*args, **kwargs, labels=[label])
> 
> g = sns.FacetGrid(tips, col='day', hue='smoker')
> g.map(fixed_boxplot, 'smoker', 'total_bill')
> # And you can do swarmplot on top
> g.map(sns.swarmplot, 'smoker', 'total_bill', color='0.25', order=['Yes','No'])
> ```

**Comment by RonKG** [comment]
The **max-lv** solution works. Thanks

**Comment by RonKG** [comment]
> I had this problem today. Here is a workaround:
> 
> ```python
> import seaborn as sns
> tips = sns.load_dataset("tips")
> 
> def fixed_boxplot(*args, label=None, **kwargs):
>     sns.boxplot(*args, **kwargs, labels=[label])
> 
> g = sns.FacetGrid(tips, col='day', hue='smoker')
> g.map(fixed_boxplot, 'smoker', 'total_bill')
> # And you can do swarmplot on top
> g.map(sns.swarmplot, 'smoker', 'total_bill', color='0.25', order=['Yes','No'])
> ```

The max-lv solution works. Thanks

**Comment by tmsincomb** [comment]
There is a warning now using the max-lv solution. 
```python 
FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation
```

To fix this you just have to modify the fix_boxplot function to use the x, y params directly. Cheers 🍺
```python
import seaborn as sns
tips = sns.load_dataset("tips")

def fixed_boxplot(x, y, *args, label=None, **kwargs):
    sns.boxplot(x=x, y=y, *args, **kwargs, labels=[label])

g = sns.FacetGrid(tips, col='day', hue='smoker')
g.map(fixed_boxplot, 'smoker', 'total_bill')
# And you can do swarmplot on top
g.map(sns.swarmplot, 'smoker', 'total_bill', color='0.25', order=['Yes','No'])
```

**Comment by nbecker** [comment]
With seaborn 0.13.2 I need this:
    def fixed_boxplot(x, y, *args, label=None, **kwargs):
        sns.boxplot(x=x, y=y, *args, **kwargs, boxprops={'label' : label})

**Comment by LJNolan** [comment]
I run into a similar error with seaborn 0.13.2:

```Python
TypeError: Axes.bxp() got an unexpected keyword argument 'label'
```

and this is solved by the max-lv solution edited by nbecker:

```Python
def fixed_boxplot(x, y, *args, label=None, **kwargs):
    sns.boxplot(x=x, y=y, *args, **kwargs, boxprops={'label' : label})
```
