### ISSUE TITLE
Stripplot within a JointGrid shifts the x-axis

### ISSUE THREAD

**Issue by fredrike** [mwaskom/seaborn#916]
When using `sns.stripplot` within a JointGrid the x-axis is shifted one to the right.

Using the following example one can see that the `plt.scatter` is shifted to the right. You can also see it on the top histogram.

```python
g = sns.JointGrid(y="Support", x="Length", data=d)

g = g.plot_joint(sns.stripplot, jitter=True, color="red")
g = g.plot_joint(plt.scatter)

_ = g.ax_marg_y.hist(d["Support"], orientation="horizontal", bins=np.arange(1, 140, 5))
_ = g.ax_marg_x.hist(d["Length"], bins=np.arange(0.5, 6, 1))
```

![ex](https://cloud.githubusercontent.com/assets/676999/14980039/69b8ef7e-1126-11e6-95f5-27700bf99e80.png)

With the `sns.stripplot`-line and the red points removed the figure looks correct.
```python
g = sns.JointGrid(y="Support", x="Length", data=d)

g = g.plot_joint(plt.scatter)

_ = g.ax_marg_y.hist(d["Support"], orientation="horizontal", bins=np.arange(1, 140, 5))
_ = g.ax_marg_x.hist(d["Length"], bins=np.arange(0.5, 6, 1))
```
![ex1](https://cloud.githubusercontent.com/assets/676999/14979987/1d86eeee-1126-11e6-9322-b36f1ffdc2a0.png)

**Comment by mwaskom** [comment]
This is expected behavior. `stripplot` is a categorical plot (without any special-casing for when the "categories" are numeric) and wouldn't be expected to work in the context of a `JointGrid`.

**Comment by fredrike** [comment]
Found a workaround when you like to use categorical plots in a `JointGrid`context.

```python
g = sns.JointGrid(y="Support", x="Length", data=d)

g = g.plot_joint(sns.stripplot, jitter=True, color="red", order=np.arange(0, max(d.Length)+1,1))
g = g.plot_joint(plt.scatter)

_ = g.ax_marg_y.hist(d["Support"], orientation="horizontal", bins=np.arange(1, 140, 5))
_ = g.ax_marg_x.hist(d["Length"], bins=np.arange(0.5, 8, 1))
g.ax_marg_x.set_xlim(left=0.1)
savefig('ex2.png', bbox_inches='tight', transparent = True, facecolor='none', edgecolor='none')
```

I'm defining the order starting from 0 and setting the margin to 0.1 to hide the 0 point. Resulting in this figure (as desired).

![ex2](https://cloud.githubusercontent.com/assets/676999/15109944/4ceae4e4-15de-11e6-807e-ae063d18bc5d.png)

**Comment by mwaskom** [comment]
That plot does not look correct.
