### ISSUE TITLE
Pairplot seems to exclude categorical variables

### ISSUE THREAD

**Issue by cammil** [mwaskom/seaborn#919]
It seems pairplot excludes categorical variables.

I would expect:

1. cat vs scalar: strip / box / violin plot
2. scalar vs cat: above but rotated
3. cat vs cat: some kind of heat map.

Is it possible to include categorical variables in a pairplot?

**Comment by mwaskom** [comment]
No, sorry.

**Comment by cammil** [comment]
I completely accept your decision. I am just curious what the reasons were for it?

**Comment by rohan-shah** [comment]
Well, that was a waste of an hour. 
1. Please document that pairplot ignores categorical variables.
2. Please document that it excludes categorical variables on the basis of an astype call, meaning that if your factorial variables has numeric labels, it will be treated as a numeric variable. This is particularly annoying if you try and use a factorial variable with numeric labels as the "hue" vaiable in pairplots.
