### ISSUE TITLE
Clustermap or heatmap col_colors/row_colors height_ratios/width_ratios as arguments

### ISSUE THREAD

**Issue by EmanuelGoncalves** [mwaskom/seaborn#921]
Hi,

The new heatmap/clustermap functions in the master branch look great. I think it would be important though to have the height_ratios and width_ratios as an argument of the functions, because in the event of having many col or rows annotations they are not correctly displayed:

![Clustermap](https://cloud.githubusercontent.com/assets/3500746/15208875/f719d2e2-1825-11e6-8ec0-e19f1fb6b601.png)

This was the output by hard-coding customised ratios:

`width_ratios = self.dim_ratios(self.row_colors,
                                       figsize=figsize,
                                       axis=1, side_colors_ratio=.6)`

`height_ratios = self.dim_ratios(self.col_colors,
                                        figsize=figsize,
                                        axis=0, side_colors_ratio=.05)`

![Clustermap customised ratios](https://cloud.githubusercontent.com/assets/3500746/15208924/3132ae54-1826-11e6-9814-86252298c139.png)

This enhancement was discussed here in the forum awhile back but I don't think it made up to the development version currently in the master branch.

Cheers,

**Comment by mwaskom** [comment]
I think thats what #891 does?

**Comment by EmanuelGoncalves** [comment]
Oh there's a col_ratios argument that will be merged?

`col_ratios={'side_colors': 0.2, 'dendrogram': 0.5}`

Ok yes I agree if there is such an argument, it will solve this problem.

**Comment by mwaskom** [comment]
If that pull request is relevant to you it would be helpful for you to check it out and test it.

**Comment by mwaskom** [comment]
Closing here, you can continue the discussion on that thread.

**Comment by liyun831229** [comment]
Can col_ratios={'side_colors': 0.2, 'dendrogram': 0.5} works now? I still can not find it in clustermap.
