### ISSUE TITLE
Timeseries plot to show distribution of multi-model / multi-scenario overlapping outputs

### ISSUE THREAD

**Issue by pbreach** [mwaskom/seaborn#923]
I am doing a Monte Carlo simulation of a dynamic model and I think it would be great if seaborn could produce plots to show the distribution of multi-model ensembles / scenarios over time. The software I am using produces this:

![image](https://cloud.githubusercontent.com/assets/8889265/15267089/d0437158-1985-11e6-94a1-42ecb7b6d9fe.png)

for 200 overlapping simulations with varying parameter sets. Would something like this be useful to have in seaborn? The plot above shows ranges for 50%, 75%, 95%, and 100%, but in seaborn even if one of these ranges could be created they could easily be stacked onto one another. What do you think?   I'd be happy to work on a PR for this unless there is something I've missed in seaborn already.

**Comment by mwaskom** [comment]
This would be easy to make in matplotlib with `plt.fill_between`.

**Comment by pbreach** [comment]
Fair enough. Only ended up taking a few lines in mpl.
