### ISSUE TITLE
boxplot not accepting 2D data

### ISSUE THREAD

**Issue by maartenmennes** [mwaskom/seaborn#925]
Hello Michael,

I'm running into problems lately with violinplot and boxplot. I've not switched to pandas dataframes, but the functions now seem to preferentially like them? I'm not succeeding in getting it to accept lists or numpy arrays.

Example is the line below. Y is a 122x2 array, which I want to plot at x=1 and x=2. The line below is giving me a 'data must be 1-dimensional' exception. Not specifying x will just plot on box or violin..

`sns.boxplot(x=np.array([1,2]), y=np.column_stack((A,B)), orient='v')`

Best,
Maarten

**Comment by mwaskom** [comment]
If you have wide-form data (which is essentially what column-stacked arrays are), you need to pass them to `data=`. `x=` and `y=` always take vectors (or references to vectors in a `DataFrame` passed to`data=`

**Comment by maartenmennes** [comment]
Ah, didn't try that, obviously. Thanks for the clarification!
