### ISSUE TITLE
Pairplot is empty - defaulting to limited axes ranges?

### ISSUE THREAD

**Issue by CatherineH** [mwaskom/seaborn#934]
My generated pairplots are empty. For example, the code:

```
import seaborn as sns; sns.set(style="ticks", color_codes=True)
iris = sns.load_dataset("iris")
g = sns.pairplot(iris)
g.savefig('output.png')
```
Results in the file:
![output](https://cloud.githubusercontent.com/assets/1953328/15511058/d13549f4-218e-11e6-9ac7-f58f5cddf55d.png)

I am using:

Python 2.7.6
matplotlib Version: 1.3.1 
seaborn Version: 0.7.0
Ubuntu 14.04.4 LTS

It seems like the axes limits are incorrect: the data exists in the dataframe but all values are outside of the -0.06:0.06 limits chosen. I've tried a few other datasets, and they all have the same limits.

**Comment by mwaskom** [comment]
This is a bug on matplotlib 1.3; you'll have to upgrade, or manually set the axis limits.
