### ISSUE TITLE
sns.heatmap annotation 

### ISSUE THREAD

**Issue by jeiros** [mwaskom/seaborn#937]
Hi there!

I just discovered that in the dev version you can annotate a heat map with the contents of another matrix (wohoo!). I've google around (with no success) to see if you can do two things:

- Conditional annotation. In my case, I've got a big matrix with a lot of 0.0 values, and those are boring. I'd like to annotate only those cells whose value is != 0. Is that possible?

- Annotate every cell even if `xticklabels` and `yticklabels` are set to something other than `True`. I've noticed that if I change them (to avoid text cluttering in the x and y labels), the annotations on the map are also displayed with an offset. Is it possible to turn that off?

Thanks for any comments and keep up prettyfing matplotlib! 😄

**Comment by jeiros** [comment]
Just found out how to do the first thing:
```
    mask : boolean array or DataFrame, optional
        If passed, data will not be shown in cells where ``mask`` is True.
        Cells with missing values are automatically masked.
```

**Comment by mwaskom** [comment]
The first thing can be handled with a mask, as you note, the second is a bug and was reported here #837 837

**Comment by MartinHjelm** [comment]
Question: with the mask the annotation and values are not shown if cell is true. Is it possible to just keep the values an remove the annotation? I have a matrix where I want to annotate the n largest values for each row.

**Comment by diallobakary4** [comment]
I want to do the exact as above @MartinHjelm 
Any solution. It will also be great if we could point to the cell with arrow and have the annotation outside.

**Comment by jeiros** [comment]
If I understood, correctly, you want to display the n largest values of each row in the array, but *not* annotate the numerical value.
Something like this?
```python
import numpy as np
import seaborn as sns
np.random.seed(4)
mat = np.random.rand(3, 3)
mat
>>> array([[ 0.96702984,  0.54723225,  0.97268436],
           [ 0.71481599,  0.69772882,  0.2160895 ],
           [ 0.97627445,  0.00623026,  0.25298236]])
mask = mat < mat.max(1).reshape(3, 1)  # bool array 
sns.heatmap(
    data=mat,
    mask=mask
)
```
Gives the following figure:
![github-issue](https://user-images.githubusercontent.com/10696140/45212390-afd5f380-b28c-11e8-87aa-85303ee4ce0f.png)

As for pointing to the cells with an arrow and have annotations outside, I'm not sure that seaborn can do this in an automatted way. But you could try to do it with matplotlib's [annotation](https://matplotlib.org/users/annotations.html)

Hope that helps,

Juan

**Comment by diallobakary4** [comment]
Thank you @jeiros . I want something similar.
I have seen another solution: to access the text object and modify it.
```
for text in sns_clustermap.texts:
    text.set_size(14)
    if text.get_text() == '2': # conditional for cells one would like to highlight. This can then be changed to the highest value...
        text.set_size(25)
        text.set_weight('bold')
        text.set_style('italic')
```
