### ISSUE TITLE
swarmplot doesn't recognize `hue` when either the `x` or `y` parameter is omitted

### ISSUE THREAD

**Issue by izaakm** [mwaskom/seaborn#941]
Similar to [the example for `swarmplot`](https://web.stanford.edu/~mwaskom/software/seaborn/generated/seaborn.swarmplot.html#seaborn.swarmplot), I would expect the following to color points by the "sex" column:

    tips = sns.load_dataset("tips")
    ax = sns.swarmplot(y="total_bill", hue="sex", data=tips)

But all points are the same color.

**Comment by mwaskom** [comment]
No, it doesn't, sorry.

**Comment by izaakm** [comment]
This seemed like a bug to me; is this the expected/intended behavior? 

If this is the intended behavior, could you help me understand why this happens (so that I can try to figure out how to get the behavior that I want)? Any help would be appreciated.

**Comment by greg-pf** [comment]
@izaakm 

I ran into this quirk as well and solved it by omitting the `data` parameter in favor of directly supplying `x`, `y`, and `hue` with one of `x`, `y` being populated with dummy data.

``` python
# `hue` is ignored
tips = sns.load_dataset("tips")
sns.swarmplot(y="total_bill", hue="sex", data=tips)
plt.show()
```

``` python
# `hue` is shown
tips = sns.load_dataset("tips")
sns.swarmplot(y=tips["total_bill"], hue=tips["sex"], x=[""]*len(tips))
plt.show()
```

**Comment by mwaskom** [comment]
Yes that will, work, though actually you don't have to omit `data`; you should be able to mix and match specifying variables with vectors or references to `data`.

**Comment by izaakm** [comment]
Thanks @greg-pf, nice work-around!

**Comment by sverchkov** [comment]
Even though you don't consider it to be a bug, would you consider a pull request to fix this?

**Comment by davidevaleriani** [comment]
This is still happening. Any plan to fix it in the future?

**Comment by mwaskom** [comment]
No.
