### ISSUE TITLE
Requst: Expose "despine" keyword parameter in pairplot()

### ISSUE THREAD

**Issue by tkanmae** [mwaskom/seaborn#942]
With "whitegrid" style, `pairplot()` leaves the top, right or both edges of each axes missing.  This issue can be reproduced by the following code:

```python
import seaborn as sns
tips = sns.load_dataset('tips')
with sns.axes_style('whitegrid'):
    sns.pairplot(tips, hue='sex')
```

I understand that passing `pairplot()` keyword argument `grid_kws={'despine': False}` fixes the issue. But I found this is a bit cumbersome, and, if I'm not mistaken, `despine` is the only valid key for `grid_kws`. It seems to me that having `despine` parameter in `pairplot()` is more user-friendly.

In addition, it would be nice if `PairGrid` class have `despine()` method.

**Comment by mwaskom** [comment]
You can just call `despine`.
