### ISSUE TITLE
Xaxis label and Bar of Hist is not aligned perfectly when bins are used on plot

### ISSUE THREAD

**Issue by albadrln** [mwaskom/seaborn#943]
![image](https://cloud.githubusercontent.com/assets/19450571/15959595/74313118-2f36-11e6-895f-5ef14e799faf.png)
I am not sure whether this is a seaborn bug or not. But as shown in the image above, when we used bins on plotting, the xlabel is placed directly below the grid. However, somehow the bar is a little bit displaced to the right. As a result, the label and bar is not aligned perfectly. And it is quite hard to read the resulting plot.

How to reproduce:
`rs=np.random.RandomState(1000)`
`data=pd.DataFrame(data=rs.normal(size=(1000,1)))`
`data.plot(kind="hist",bins=10)`

P.S. Image is taken from [user:Namirian notebooks on Kaggle, Kobe Bryant dataset](https://www.kaggle.com/narimiran/kobe-bryant-shot-selection/beginners-first-time/comments). The bug is confirmed consistent in another execution.

P.S2: I am new to seaborn, panda, python, etc. I am not even sure whether this behavior is as expected or not.

**Comment by mwaskom** [comment]
This is not a seaborn issue, but that looks like correct behavior to me.
