### ISSUE TITLE
sns.regplot ignoring 'edgecolors' in scatter_kws

### ISSUE THREAD

**Issue by msto** [mwaskom/seaborn#945]
Hi,

I'm having trouble getting `sns.regplot` to recognize the `edgecolors` scatter keyword, but it correctly uses other keywords. Minimum code necessary to replicate attached, I'm running python 3.5.1, matplotlib 1.5.1, and seaborn 0.7.0. Any idea what might be causing this?

Thanks!

    x = np.random.randint(0, 1000, 100)
    y = np.random.randint(0, 1000, 100)
    
    sns.regplot(data=data, x=x, y=y, scatter_kws={'c': sns.xkcd_rgb['lime green'], 
                                                  'edgecolors': sns.xkcd_rgb['black'], 
                                                  's': 70})
    
    plt.scatter(x, y, c=sns.xkcd_rgb['lime green'], edgecolors=sns.xkcd_rgb['black'], s=70)

![screen shot 2016-06-14 at 4 18 40 pm](https://cloud.githubusercontent.com/assets/55061/16058289/cbd189b4-324b-11e6-81a9-501b78bcc5cd.png)

**Comment by mwaskom** [comment]
You also need to set the `linewidth` scatter parameter to something larger than 0.
