### ISSUE TITLE
plot_generator not Python3 compatible

### ISSUE THREAD

**Issue by fonnesbeck** [mwaskom/seaborn#947]
Trying to make the docs (`make html`) under Python 3.5 and Sphinx 1.4.1 fails with:

```python

Exception occurred:
  File "/Users/fonnescj/Repositories/seaborn/doc/sphinxext/plot_generator.py", line 238, in extract_docstring
    tokens = tokenize.generate_tokens(lines.__iter__().next)
AttributeError: 'list_iterator' object has no attribute 'next'
```

Looks like a Python 3 compatibility issue?

**Comment by mwaskom** [comment]
I actually just borrowed that extension from matplotlib when 1.5 was still in development. Now that it's been released we can probably just import from matplotlib. Not sure whether the current matplotlib version is Python 3 compliant though.

**Comment by fonnesbeck** [comment]
That particular extension does not seem to be in matplotlib anymore. Easy enough to fix though.
