### ISSUE TITLE
It report there is no ft2build.h when install seaborn, while I do install it 

### ISSUE THREAD

**Issue by FrankYu** [mwaskom/seaborn#951]
Hi

I'm trying install seaborn on smartos(open solaris like system). But failed with with error which report the freetype is not installed. 
while the truth I do install freetype.

#find / -name ft2build.h
/opt/local/include/freetype2/ft2build.h

#pkgin list|grep freetype
freetype-1.5         FreeType libraries and utilities
freetype-lib-1.5nb1  TrueType font rendering engine and library API
freetype-utils-1.5nb1 Utilities for manipulating TrueType fonts
freetype2-2.6.2nb1   Font rendering engine and library API

#pip install git+git://github.com/mwaskom/seaborn.git#egg=seaborn
Collecting seaborn from git+git://github.com/mwaskom/seaborn.git#egg=seaborn
  Cloning git://github.com/mwaskom/seaborn.git to /tmp/pip-build-AewlOC/seaborn
Collecting matplotlib (from seaborn)
  Using cached matplotlib-1.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    IMPORTANT WARNING:
        pkg-config is not installed.
        matplotlib may not be able to find some of its dependencies
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [1.5.1]
                    python: yes [2.7.11 (default, May  3 2016, 16:18:40)  [GCC
                            4.9.3]]
                  platform: yes [sunos5]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.11.0]
                  dateutil: yes [using dateutil version 2.4.0]
                      pytz: yes [using pytz version 2014.10]
                    cycler: yes [cycler was not found. pip will attempt to
                            install it after matplotlib.]
                   tornado: yes [tornado was not found. It is required for the
                            WebAgg backend. pip/easy_install may attempt to
                            install it after matplotlib.]
                 pyparsing: yes [using pyparsing version 2.1.0]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
.....
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype

**Comment by TomAugspurger** [comment]
You should make sure you can install and import [matplotlib](http://matplotlib.org/users/installing.html) before trying to install seaborn

**Comment by mwaskom** [comment]
Agree with @TomAugspurger that this is a matplotlib install issue. Please read the error message that you get carefully before making a github issue.
