### ISSUE TITLE
DeprecationWarning when using distplot

### ISSUE THREAD

**Issue by beojan** [mwaskom/seaborn#953]
Using distplot produces the warning

```
/usr/lib/python3.5/site-packages/statsmodels/nonparametric/kdetools.py:20: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j
```

**Comment by mwaskom** [comment]
Looks like that is a numpy warning getting raise from a statsmodels module, not seaborn code itself?

**Comment by themrmax** [comment]
this is fixed in https://github.com/statsmodels/statsmodels/commit/570604b3a8f044a89627c71494c8e324ed37cf85 but this isn't in the latest stable release yet
