### ISSUE TITLE
reversal of x-axis and y-axis offset when using FacetGrid 

### ISSUE THREAD

**Issue by dkoppstein** [mwaskom/seaborn#955]
When using FacetGrid in the following way, despite calling `xlim=(1,4)`, the resulting subplots have the x-axis reversed for unclear reasons (it also does it this way without the xlim call). Further, the y-axis seems to be offset into the body of the graph. Do you know why this is and how I might correct it?  

```
sns.set_context("notebook", font_scale=0.35)
g = sns.FacetGrid(final_df, col_wrap=4, col='COMBINED', size=1, xlim=(1,4))
g = g.map(plt.plot, "SUBJECT", "value", marker="o", ms=4)
g.set_titles("{col_name}")
```

Here is one cell of output: 

![screen shot 2016-06-22 at 1 28 30 pm](https://cloud.githubusercontent.com/assets/10901251/16282500/d8306580-387d-11e6-94c7-377a97945da6.png)

**Comment by mwaskom** [comment]
Sorry for missing this. Hopefully you figured it out. I'm not sure what's going on here but I'd need to be able to reproduce the issue locally to be able to help.

**Comment by KeithWM** [comment]
I am suffering from the same issue. If this issue isn't known to be resolved, I have attached my dataframe and the code that causes the error is:

[hist_errors.pkl.zip](https://github.com/mwaskom/seaborn/files/599597/hist_errors.pkl.zip)

    hist_errors = pandas.read_pickle('hist_errors.pkl')
    g = sns.FacetGrid(hist_errors, row='jumpstyle', col='matching', size=1.5, xlim=(0, K))
    g = g.map(plt.plot, "K", 'error')
    g.fig.get_axes()[0].set_yscale('log')`

I've now discovered that removing the `size=1.5` fixes the issue for me, after I thought I would remove it to make the minimal example more minimal. Hope this helps in localizing the issue. 

Keith

**Comment by rudolfbyker** [comment]
Same problem here! Minimum **not**-Working Example with code and DataFrame attached: 
[20180305_mwe.zip](https://github.com/mwaskom/seaborn/files/1782313/20180305_mwe.zip)

Screenshot:
![bildschirmfoto vom 2018-03-05 21-36-31](https://user-images.githubusercontent.com/10025342/36995723-82354cd4-20bd-11e8-828c-db3656974d0b.png)

Not only are the axes reversed, but the datapoints on the plot are not in the same order as in the dataframe, causing a non-monotonic line.

Versions:

- seaborn 0.8.0
- pandas 0.20.3
- numpy 1.13.3
