### ISSUE TITLE
Find new home for docs

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#958]
My Stanford website will be deactivated sometime in the fall. Need to find a new home and set up appropriate redirects.

**Comment by yarmenti** [comment]
Right, the site is now out.

**Comment by anoroozian** [comment]
Could you temporarily make the documentation available as a compressed file on Github for offline use?

**Comment by TomAugspurger** [comment]
@mwaskom want me to grab the `seaborn` Github name and throw the HTML docs up at `seaborn.github.io`? Should only take a few minutes.

**Comment by mwaskom** [comment]
Irritatingly, the `seaborn` user/org name is already taken on github, even though https://github.com/seaborn doesn't exist.

**Comment by TomAugspurger** [comment]
Oh... that is irritating.

**Comment by mwaskom** [comment]
Maybe I'll ask Stanford to set up redirect to https://altair-viz.github.io/ :)

**Comment by japborst** [comment]
I use seaborn for plots in my thesis, which is due rather soon. I don't have a Linux machine available, so cannot run the makefile myself unfortunately and don't have much experience with Sphinx, I'm afraid. Anyone can help me get the docs in some form?

Ps. why not host the the docs in this repo through `gh-pages` ?

**Comment by TomAugspurger** [comment]
https://www.dropbox.com/s/2xbf7ou8ccsyplr/sb.tar.gz?dl=0

**Comment by japborst** [comment]
@TomAugspurger awesome! Thanks a ton

**Comment by mwaskom** [comment]
Notwithstanding my trolling about this on Twitter, the serious answer here is that I actually think Stanford deactivating my website was a mistake (I have an approved request for account extension, but the original expiry was last night) and am trying to sort that out with Stanford ID. But in the medium term the plan is to move to pydata.org.

**Comment by nils-werner** [comment]
Why not readthedocs?

**Comment by pmadhikar** [comment]
As a short term work around, I found a snapshot on archive.org [here](http://web.archive.org/web/20160804163120/https://stanford.edu/~mwaskom/software/seaborn/)
It was made on Aug. 8 though so it might be slightly out of date.

**Comment by TomAugspurger** [comment]
> Why not readthedocs? It will take 3 minutes to set up.
 
The build process for seaborn's docs is a bit more exotic than RTD can handle.

**Comment by rasbt** [comment]
> Irritatingly, the seaborn user/org name is already taken on github, even though https://github.com/seaborn doesn't exist.

Hm, too bad. Alternatively, you could go with https://mwaskom.github.io/seaborn however that becomes problematic if maintainers may switch in far future :P. However, unless you delete your github account, you could always setup a redirect to whatever future site you may end up using

**Comment by jaypeedevlin** [comment]
Mac users can download dash and use the user-contributed seaborn docset, if that's easier than building the docs locally...

**Comment by nils-werner** [comment]
Judging from glancing at <http://seaborn2.readthedocs.io/en/latest/> it seems to build fine on RTD with just two lines changed in `devel_requirements_py2.txt`.

**Comment by jaypeedevlin** [comment]
Looks like the tutorial page didn't build: http://seaborn2.readthedocs.io/en/latest/tutorial.html

**Comment by mwaskom** [comment]
OK folks calm down there is a github pages version of the site live at https://seaborn.github.io/

**Comment by wvangeit** [comment]
@mwaskom Maybe in the mean time you could change the link to the docs on https://github.com/mwaskom/seaborn to point to new github.io pages ?
(Took me quite some time to find the docs, until I saw a post on Reddit about this issue)

**Comment by nateGeorge** [comment]
Yeah I'm just submitting a PR for that #1052

**Comment by gforsyth** [comment]
Until the pydata hosting is sorted, you might find https://github.com/drdoctr/doctr useful for building docs on travis and deploying them to github pages (if you get sick of doing it manually).

**Comment by mwaskom** [comment]
New docs are now at seaborn.pydata.org (and also seaborn.github.io, where they are actually hosted).

**Comment by mwaskom** [comment]
@nils-werner Can you please take down the http://seaborn2.readthedocs.io/ page? It is confusing google.

**Comment by nils-werner** [comment]
It's gone.

**Comment by mwaskom** [comment]
Thanks!

**Comment by szeitlin** [comment]
The pydata page with the docs is not loading. :( I can probably get by with the wayback machine version just to jog my memory, but you might want to check into this if you haven't already.

**Comment by mwaskom** [comment]
Looks like pydata.org itself is down.
