### ISSUE TITLE
seaborn error message!!

### ISSUE THREAD

**Issue by neuronphysics** [mwaskom/seaborn#96]
Python 2.6.5 (r265:79063, Sep 26 2013, 18:48:04) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import seaborn
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "seaborn/**init**.py", line 1, in <module>
> > >     from .rcmod import *
> > >   File "seaborn/rcmod.py", line 35
> > >     if not {"darkgrid", "whitegrid", "nogrid", "ticks"} & {style}:
> > >                               ^
> > > SyntaxError: invalid syntax
> > > I am getting the above error message after successfully installing seaborn! any idea what has caused the problem?

**Comment by AnmolJalan** [comment]
I  am getting the same error with python 3.8

**Comment by zstauber-NMENV** [comment]
Also seeing this error in Python 3.8 with Jupyter Notebooks

```
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns sns.set(style="darkgrid")

```
  Cell In[1], line 4
    import seaborn as sns sns.set(style="darkgrid")
                          ^
SyntaxError: invalid syntax
