### ISSUE TITLE
jointplot plot hangs for certain combination of values

### ISSUE THREAD

**Issue by odoublewen** [mwaskom/seaborn#960]
Using joinplot( type = 'hex' ) to make hexbin plot.

The function call hangs (never comes back, with 100% CPU usage) when I tried to do it with my data (variables a and b)

The same plot works for randomly generated data (variables x and y)

This Jupyter notebook provides data for both working and buggy behavior.  https://github.com/odoublewen/seaborn_bug/blob/master/seaborn_test.ipynb

Cheers

**Comment by odoublewen** [comment]
I should also add, this is seaborn 0.7.1

I reproduced this behavior on both linux and mac systems.

**Comment by Pierian-Data** [comment]
It looks like you have a lot of stacked/duplicate values in those columns, although matplotlib's own hexbin was able to work, given the dataframe you linked to as df

**plt.hexbin(df['a'],df['b'],gridsize=25)**

worked fine. So I'm no quite sure why seaborn's hex call was taking so long.

**Comment by mwaskom** [comment]
seaborn uses a reference rule to calculate the gridsize whereas matplotlib's uses a fixed value. If you have highly non-gaussian data, it might try to draw too many cells and get bogged down. You can pass a gridsize through the `joint_kws` to verify/control. In distplot there is a ceiling on the automatic number of bins to avoid this situation, but it might be downstream from the core function that is determining the bin size and thus not used in jointplot.

**Comment by Pierian-Data** [comment]
Thanks for the info!
