### ISSUE TITLE
Negative sign not showing in pdf output

### ISSUE THREAD

**Issue by mszep** [mwaskom/seaborn#963]
When I make a plot and save to pdf, negative tick labels do not have the negative sign showing.

Script I'm using:

```
import matplotlib.pyplot as plt
import seaborn as sns

import numpy as np

x = np.linspace(-2.0, 4.0, 500)
a = 5*np.sin(x)

plt.plot(x, a)
plt.legend()
plt.ylim((-5, 10))
plt.xlim((-2, 4))
plt.savefig('test.pdf')
```

(Using matplotlib 1.5.1 and Seaborn 0.7.0)

This produces the following output for me:
[test.pdf](https://github.com/mwaskom/seaborn/files/344663/test.pdf)

This problem does not occur when using vanilla matplotlib, or when saving to png.

Someone else seems to have previously come across this problem [here](http://stackoverflow.com/questions/33906962/sign-in-y-ticks-label-are-not-written-in-seaborn) (although they don't mention whether they are saving to pdf). The poster says it's a fonts issue, but I don't know how to fix that or even work around it.

**Comment by mwaskom** [comment]
Try using a different font.

**Comment by mszep** [comment]
I added the following lines, but that had no effect (nor did using 'Helvetica'). Is that the correct way to change font?

```from matplotlib import rcParams
rcParams['font.family'] = 'sans-serif'
rcParams['font.sans-serif'] = ['Tahoma']```

**Comment by mwaskom** [comment]
Yes. did it looks like the font changed? I would also try looking at it in a different pdf reader.
