### ISSUE TITLE
ENH: Add ability to produce violin-like plots with actual histograms (not just KDE's)

### ISSUE THREAD

**Issue by 8one6** [mwaskom/seaborn#964]
The `violinplot` function is great.  Really great.  Perhaps too great?  

Intellectually, it has 3 steps: 1) group data; 2) compute KDE's; 3) make awesome visualization.  I believe the function is pretty integrally set up so that step 2 involves computing those KDE's.  But would anyone else appreciate the ability to compute a simple histogram instead?  So that instead of having smooth violins (which do really look great and faithfully represent the data when N is large), one could have the option to view "mirrored histograms" (which a user-specifiable number of bins) instead?  (Or, in the case of paired data, non-mirrored...)

Particularly in cases where the number of data points is small, I think this could be quite useful.

Thoughts?

**Comment by mwaskom** [comment]
It's an interesting suggestion, but I'm going to pass on this.

**Comment by 8one6** [comment]
Wow, that was a bit more definitive than I was expecting!

Is it that you don't want the feature in the package, or that you don't want to take the time to code it?  I was thinking I might be able to take a swing at it if I found some free time, and wanted to get a sense if anyone else would find it useful.

**Comment by mwaskom** [comment]
Sorry, but I have very little time to devote to seaborn right now and it requires me to be decisive about this kind of issue.
