### ISSUE TITLE
Axes line width does not scale with context

### ISSUE THREAD

**Issue by tkanmae** [mwaskom/seaborn#965]
Hi Mark

I found that `axes.linewidth` does not scale with context. The following code and output show the issue.

```python
sns.set(style='ticks', context='poster')
fig, ax = plt.subplots()
ax.plot(np.random.random(100))
```
![axes-lineswidth-does-not-scale](https://cloud.githubusercontent.com/assets/305196/16551135/4a16e9f6-41ef-11e6-82a4-e573a97cc9db.png)

As you can see, line widths of ticks are scaled but those of axes are not. This happens because `plotting_context()` does not handle `axes.linewidth`. A possible solution would be to introduce a global variable that keeps track of the current style and scale `axes.linewidth` acocrdingly in `plotting_context()`.

I'm using matplotlib==1.5.1 and seaborn 0.7.1.

Thanks,

Takeshi

**Comment by mwaskom** [comment]
Unfortunately it cannot, as it has to be part of the `axes_style` parameters to set the linewidth to 0 for `dark` and `darkgrid`.

**Comment by tkanmae** [comment]
Let me clarify my idea:

1. Have a global variable that keeps track of the current style. Let it call `_curr_style`.
2. Inside `plotting_context()`, if `_curr_style` is not "dark" or "darkgrid", then scale `axes.linewidth` accordingly.

To make this work, you need to change the order of `set_context()` and `set_style()` in `set()`. You may not want to introduce the global variable, though. This is a possible remedy for the issue that I can think of.

**Comment by mwaskom** [comment]
Yes I would like to avoid global variables.

**Comment by tkanmae** [comment]
Got it, thanks.
