### ISSUE TITLE
Hueorder in factorplot not working as expected

### ISSUE THREAD

**Issue by mortonjt** [mwaskom/seaborn#967]
I'm generating some factorplots, and I'm trying to reorder the hue.  However, it doesn't seem like the `hueorder` parameter is changing anything.  

There is some code to reproduce the issue.
```python
import pandas as pd
import seaborn as sns

df = pd.DataFrame({
        'A': ['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c'],
        'B': ['1', '2', '3', '1', '2', '3', '1', '2', '3'],
        'C': [1, 2, 3, 5, 6, 7, 10, 11, 12]
    })

grid = sns.factorplot(x="B", y="C", hue='A', data=df, palette="brg") 
```
![image](https://cloud.githubusercontent.com/assets/4184797/16699277/17fe6e64-4508-11e6-8c0a-7dea480332bb.png)

Now the the following will generate the exact same plot, even though I specify a different hue ordering.
```python
grid = sns.factorplot(x="B", y="C", hue='A', data=df, palette="brg", hueorder=['b', 'a', 'c']) 
```

This is an actual bug, or am I doing something wrong?  

Thanks!

**Comment by mwaskom** [comment]
The parameter is `hue_order`.

**Comment by mortonjt** [comment]
Perfect.  Thanks!
