### ISSUE TITLE
FacetGrid legend with 7 boxplots getting squished into plots

### ISSUE THREAD

**Issue by mcchong** [mwaskom/seaborn#968]
Hi,

Seaborn is pretty shiny, but I'm having a couple of issues and the docs aren't super helpful on this.

Right now, I'm trying to create a facetgrid with 7 boxplots, each with two sets of 4 'boxes' each, however, the legend is getting squished into my plots, and I can't for the life of me figure out how to make it not do that.  I'm on a crunch at the moment, so don't have a lot of time to add my code to reproduce, but maybe if you check in again in about a month I can do that.

Thanks.

**Comment by mwaskom** [comment]
I can't help you without a reproducible issue but maybe if you ask on StackOverflow someone will be able to.
