### ISSUE TITLE
Using the "hue" attribute makes plots with bars thin

### ISSUE THREAD

**Issue by alexpetralia** [mwaskom/seaborn#970]
This is an issue related to #824 and [this](http://stackoverflow.com/questions/36092363/seaborn-boxplots-changes-narrows-width-of-boxes-when-a-hue-is-chosen-how-migh) StackOverflow question.

To copy the example in the previous issue:
```
tips = sns.load_dataset("tips")
sns.barplot(x="day", y="total_bill", hue="sex", data=tips, width=.3)
```

This works fine using the `x` and `y` attributes, but adding the `hue` attribute makes the bars thin. Is there a workaround?

**Comment by mwaskom** [comment]
Yes, this is by design #871

**Comment by alexpetralia** [comment]
@mwaskom Is there perhaps documentation I'm missing to use hue and not have thin bars? Or is the StackOverflow response the only relevant documentation?

**Comment by srinivas365** [comment]
tips = sns.load_dataset("tips")
sns.barplot(x="day", y="total_bill", hue="sex", data=tips,dodge=False)

Add attribute dodge=False
Instead of creating different bar for single value. Adding dodge=False shows the data in single bar per variable.
