### ISSUE TITLE
Kernel Crash iPython 2.7 Clustermap

### ISSUE THREAD

**Issue by dantaki** [mwaskom/seaborn#971]
```
df=pd.read_csv("data")
mat=df.pivot("1","2","X")
mat=mat.fillna(0.0)
sns.heatmap(mat,cmap=plt.cm.viridis,) #works fine
g=sns.clustermap(mat,cmap=plt.cm.inferno,figsize(8,8),xticklabels=True,metric='seuclidean',method='average')
plt.setp(g.ax_heatmap.yaxis.get_majorticklabels(), rotation=0)
```

Now the kernel crashes. I'm not sure what's happening.

**Comment by mwaskom** [comment]
I am not able to provide any assistance without a complete and reproducible example of the issue.

**Comment by dantaki** [comment]
I don't know how to send a private message on github, but I am willing to send you the data for you to replicate the error.

However I found that omitting the `method=average` option solved the problem. So it's probably an error to that function and not clustermap.

Thanks for the response.
