### ISSUE TITLE
heatmap with asymmetry

### ISSUE THREAD

**Issue by BadWizard** [mwaskom/seaborn#972]
Is it possible to make a heatmap with diverging colormap such that the center is not the midpoint between vmin and vmax (e.g. vmin = -0.5, vmax = 10 and center = 0)?

**Comment by mwaskom** [comment]
It's possible to modify the colormap, but not easy. Search on Stackoverflow — I think I've seen a good Q/A about this on there before.

**Comment by BadWizard** [comment]
Thanks for answering.
