### ISSUE TITLE
Meaning of whiskers in factorplot boxplot

### ISSUE THREAD

**Issue by fbrundu** [mwaskom/seaborn#973]
Hi,
I have a question: do the whiskers in the factorplot boxplot define the confidence interval? I.e. with 95% confidence interval, is 95% of samples within the whiskers?

![bplot](https://cloud.githubusercontent.com/assets/697622/16801849/570b3b98-48fd-11e6-8c21-85352b1fc0b9.png)

Thanks,
Francesco

**Comment by mwaskom** [comment]
From http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.boxplot.html

> The box shows the quartiles of the dataset while the whiskers extend to show the rest of the distribution, except for points that are determined to be “outliers” using a method that is a function of the inter-quartile range.

Specifically the default is to draw the whiskers to observations that lie within 1.5 * IQR of the closest quartile.
