### ISSUE TITLE
DOI for release 0.7.1

### ISSUE THREAD

**Issue by dcgemperline** [mwaskom/seaborn#975]
Hello,

I'd like to cite Seaborn in my dissertation and for a publication that I am working on and wanted to get a new DOI for the newer June 0.7.1 release so that I can accurately reflect the state of the repository as used.

Thanks!

David

**Comment by mwaskom** [comment]
Sorry for missing this. Hopefully you figured this out on your own, but the zenodo dois are actually generated automatically when a release is tagged on github and the part I forgot to do is to copy the new one into the readme. There's a 0.7.1. doi here: https://zenodo.org/record/54844?ln=en#.V8w_sj4rK2w
