### ISSUE TITLE
Gtk-WARNING

### ISSUE THREAD

**Issue by JLCCI** [mwaskom/seaborn#977]
Thanks for the great package!

I keep getting an error that I can't seem to remove no matter what I comment out.

:21954): Gtk-WARNING **: Theme parsing error: gtk.css:67:29: The style property GtkStatusbar:s
hadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version

Is there something within seaborn that causes it? I just to a simple boxplots.

Many thanks for your help.

**Comment by mwaskom** [comment]
Please provide a full example of code that produces the error.

**Comment by JLCCI** [comment]
Apologies, turns out it's an matplotlib issue, not seaborn.
