### ISSUE TITLE
Does boxplot support alpha / transparency?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [mwaskom/seaborn#979]
The following:

```python
sns.boxplot(data, x='foo', y='bar', alpha=0.3)
```

Fails with:

``` python
TypeError: boxplot() got an unexpected keyword argument 'alpha'
```

I presume boxplots don't support alpha or transparency? Or is there any other way of getting it?

**Comment by amelio-vazquez-reina** [comment]
The above is using `0.7.0` on `Python 3.5.2` (conda install on the default channel)

**Comment by mwaskom** [comment]
It's not supported through the API but it's not too hard to do posthoc, e.g.

```python
ax = sns.boxplot(x='day', y='tip', data=tips)
plt.setp(ax.artists, alpha=.3)
```

But this also sets the alpha on the edges of the boxes, which I find aesthetically displeasing. A more roundabout way to just change the alpha of the box fills is:

```python
ax = sns.boxplot(x='day', y='tip', data=tips)
for patch in ax.artists:
    r, g, b, a = patch.get_facecolor()
    patch.set_facecolor((r, g, b, .3))
```

there may be a more direct but less obvious way to do that, usually is in matplotlib.

**Comment by amelio-vazquez-reina** [comment]
Fantastic. Thanks @mwaskom !

**Comment by mwaskom** [comment]
Specifically, that is a change in matplotlib 3.5.0. If you are using an older matplotlib in 2022, you should still do it the other way :)
