### ISSUE TITLE
Bug in FacetGrid

### ISSUE THREAD

**Issue by acraig78** [mwaskom/seaborn#980]
I found an error when using facet grids which I could reproduce using this minimal example. The error is in the first facet, where the values plotted for X and Y are switched around compared to the data frame.

```python
import pandas as pd
import seaborn as sns
%matplotlib inline

T = pd.DataFrame({"K": ["A", "A", "B", "B", "C", "C"],\
                  "O": ["Y", "X", "X", "Y", "X", "Y"],\
                  "S": [3.0, 1.0, 2.0, 6.0, 3.0, 9.0]})

with sns.plotting_context("poster"):
    g = sns.FacetGrid(data=T, col="K")
    g.map(sns.stripplot, "O", "S", size=10)
```

Here is the chart that the code produced
![image](https://cloud.githubusercontent.com/assets/18251598/17135189/68166c22-5326-11e6-9e6d-ecf8335f8a0d.png)

Versions:
matplotlib 1.5.1
seaborn 0.7

matplotlib backend module://ipykernel.pylab.backend_inline

**Comment by mwaskom** [comment]
As noted in the documentation, the default behavior for `stripplot` is to plot the categories in the order they appear in the DataFrame, but the `FacetGrid` labeling doesn't know about that. (This may be improved when matplotlib has first-class support for categorical axes). Solutions include:

A. Supplying the `order` argument to `stripplot`
B. Setting a category order on the `O` column in the `DataFrame`
C. Using `factorplot`, which takes care of (A) for you
