### ISSUE TITLE
heatmap annotation

### ISSUE THREAD

**Issue by leizing** [mwaskom/seaborn#981]
The latest version v.0.7.1 allows passing rectangular dataset to "annot". However, the following error message keeps showing up:

> The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Original code:

`data = np.array([[0.000000,0.000000],[-0.231049,0.000000],[-0.231049,0.000000]])`
`labels =  np.array([['A','B'],['C','D'],['E','F']])`
`fig, ax = plt.subplots()`
`ax = sns.heatmap(data, annot = labels, fmt = '')`

>anaconda/lib/python2.7/site-packages/seaborn/matrix.pyc in heatmap(data, vmin, vmax, cmap, center, robust, annot, fmt, annot_kws, linewidths, linecolor, cbar, cbar_kws, cbar_ax, square, ax, xticklabels, yticklabels, mask, **kwargs)
    461         :context: close-figs
    462 
--> 463         >>> grid_kws = {"height_ratios": (.9, .05), "hspace": .3}
    464         >>> f, (ax, cbar_ax) = plt.subplots(2, gridspec_kw=grid_kws)
    465         >>> ax = sns.heatmap(flights, ax=ax,

>anaconda/lib/python2.7/site-packages/seaborn/matrix.pyc in plot(self, ax, cax, kws)
    246                 l = relative_luminance(color)
    247                 text_color = ".15" if l > .408 else "w"
--> 248                 annotation = ("{:" + self.fmt + "}").format(val)
    249                 text_kwargs = dict(color=text_color, ha="center", va="center")
    250                 text_kwargs.update(self.annot_kws)

> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by mwaskom** [comment]
Please provide an example script that produces this error. i.e. something I can copy and paste to run on my machine. Also please provide the full traceback text. Thanks.

**Comment by leizing** [comment]
updated the original post.

**Comment by mwaskom** [comment]
Are you sure you're on v0.7.1? When I run this code on that version I cannot reproduce your problem, but I do see it on 0.7.0.

PS in the future it's better when making an example script to include all the imports so that I can literally just copy and paste. You are asking for free tech support; the least you can do is minimize the amount of additional effort I need to put in to help you.

**Comment by leizing** [comment]
Thanks. It's odd that `seaborn.__version__' showed '0.7.1' in my current Jupyter notebook and it did not work. However it did work when I started a new Jupyter notebook. 

Therefore not an issue. Please close this. Sorry for bothering...
