### ISSUE TITLE
Pass weights to a histogram in a PairGrid

### ISSUE THREAD

**Issue by tdoughty1** [mwaskom/seaborn#982]
I'm working on making a pairplot for a set of functions and it seemed that a pair grid might work somewhat better due to the need to pass in weights for the values.  I wrote up the following code to try to accomplish the same organization as a pairplot. 

```
g = sns.PairGrid(df[['qrpartOF_zhalf_dev', 'qzpartOF', 'qsummaxOF','ytNF', 'Type', 'weight']], 
                hue='Type', hue_order=['WIMP', 'Surface 1', 'Surface 2', 'Gamma'], palette=palette,
                vars=['qrpartOF_zhalf_dev', 'qzpartOF', 'qsummaxOF','ytNF'])
g.map_upper(plt.scatter, s=250*df['weight'])
g.map_lower(plt.scatter, s=250*df['weight'])
g.map_diag(plt.hist, weights=df['weight'])
g.add_legend()
g.set(alpha=0.5)
```

When I ran it, however, I run into the following error

```
ValueError                                Traceback (most recent call last)
<ipython-input-72-96c624867403> in <module>()
      7 g.map_upper(plt.scatter, s=250*df['weight'])
      8 g.map_lower(plt.scatter, s=250*df['weight'])
----> 9 g.map_diag(plt.hist, weights=df['weight'])
     10 g.add_legend()
     11 g.set(alpha=0.5)

/home/tdoughty1/.envs/HT/local/lib/python2.7/site-packages/seaborn/axisgrid.pyc in map_diag(self, func, **kwargs)
   1346                 else:
   1347                     func(vals, color=self.palette, histtype="barstacked",
-> 1348                          **kwargs)
   1349             else:
   1350                 for k, label_k in enumerate(self.hue_names):

/home/tdoughty1/.envs/HT/local/lib/python2.7/site-packages/matplotlib/pyplot.pyc in hist(x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, hold, data, **kwargs)
   2956                       histtype=histtype, align=align, orientation=orientation,
   2957                       rwidth=rwidth, log=log, color=color, label=label,
-> 2958                       stacked=stacked, data=data, **kwargs)
   2959     finally:
   2960         ax.hold(washold)

/home/tdoughty1/.envs/HT/local/lib/python2.7/site-packages/matplotlib/__init__.pyc in inner(ax, *args, **kwargs)
   1810                     warnings.warn(msg % (label_namer, func.__name__),
   1811                                   RuntimeWarning, stacklevel=2)
-> 1812             return func(ax, *args, **kwargs)
   1813         pre_doc = inner.__doc__
   1814         if pre_doc is None:

/home/tdoughty1/.envs/HT/local/lib/python2.7/site-packages/matplotlib/axes/_axes.pyc in hist(self, x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, **kwargs)
   5968 
   5969         if len(w) != nx:
-> 5970             raise ValueError('weights should have the same shape as x')
   5971 
   5972         for xi, wi in zip(x, w):

ValueError: weights should have the same shape as x
```

I spent a little while searching for an answer and I found this similar problem where the solution is given for FacetGrid.  However, when I tried to use it to guide my answer, I quickly run into the issue that map_diags only takes a single input and I'm not sure how to tweak the solution for a PairGrid.

http://stackoverflow.com/questions/31301810/how-to-pass-weights-to-a-seaborn-facetgrid

Is there anyway to pass the weights to a PairGrid?  Thanks for your time.  And sorry if this isn't what you would consider and issue.

**Comment by mwaskom** [comment]
It's possible it might just not work. I'll think if I can come up with a way around it. But you can always use `PairGrid` methods to make most of the plot and then write a for loop around the `g.diag_axes` list to plot the histograms directly on them (as you'd have to do anyway if were just using `subplots`).

With that said, I feel like this should be working, though it's hard to tell just from looking at the traceback exactly what's happening. It would be helpful if you can try to recreate what you are doing with one of the example datasets and then I can play with it to see if I can get it to work.
