### ISSUE TITLE
Custom heatmap labels not working with `annot` method

### ISSUE THREAD

**Issue by jolespin** [mwaskom/seaborn#983]
**How can I use the `annot` method of `sns.heatmap` to give it a custom naming scheme?** 

Essentially, I want to drop all the labels that are lower than my threshold (0 in this case).  I tried doing what @ojy said in http://stackoverflow.com/questions/33158075/custom-annotation-seaborn-heatmap but I'm getting the following error. I saw an example where somebody iterated through every cell, is that the only way to do it? 

    Seaborn documentation:
    annot : bool or rectangular dataset, optional
    If True, write the data value in each cell. If an array-like with the same shape as data, then use this to annotate the heatmap instead of the raw data.

So I tried the following:

```
    # Load Datasets
    from sklearn.datasets import load_iris
    iris = load_iris()
    DF_X = pd.DataFrame(iris.data, index = ["%d_%d"%(i,c) for i,c in zip(range(X.shape[0]), iris.target)], columns=iris.feature_names)
    
    # Correlation
    DF_corr = DF_X.corr()
    
    # Figure
    fig, ax= plt.subplots(ncols=2, figsize=(16,6))
    sns.heatmap(DF_corr, annot=True, ax=ax[0])
    
    # Masked Figure
    threshold = 0
    DF_mask = DF_corr.copy()
    DF_mask[DF_mask < threshold] = 0
    sns.heatmap(DF_mask, annot=True, ax=ax[1])
    
    # Annotating
    Ar_annotation = DF_mask.as_matrix()
    Ar_annotation[Ar_annotation == 0] = None
    Ar_annotation
    # array([[ 1.        ,         nan,  0.87175416,  0.81795363],
    #        [        nan,  1.        ,         nan,         nan],
    #        [ 0.87175416,         nan,  1.        ,  0.9627571 ],
    #        [ 0.81795363,         nan,  0.9627571 ,  1.        ]])
    print(DF_mask.shape, Ar_annotation.shape)
    # (4, 4) (4, 4)
    
    sns.heatmap(DF_mask, annot=Ar_annotation, fmt="")
    
    # ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
![screen shot 2016-08-02 at 10 17 35 am](https://cloud.githubusercontent.com/assets/9061708/17338913/5bd5c2b4-589e-11e6-9733-5cef2edce7ad.png)

Before mask (left), after mask (right)

**Comment by asalt** [comment]
What is your seaborn version? I had this same problem on version 0.7 but the ability to send your own array as the annotation was added in 0.7.1. I had the same error before I updated.

**Comment by jolespin** [comment]
I saw that yesterday in a stackoverflow answer so I tried updating with conda but they only have 0.7.0. I used pip to get 0.7.1 but it still didn't work when I reimported sns .  I didn't restart my Jupyter kernel but usually I can just reimport the module.

**Comment by asalt** [comment]
Try restarting the kernel. Your post looks very similar to this :
https://github.com/mwaskom/seaborn/issues/981

I'm on mobile and haven't had time to try your code but I bet your kernel still has the 0.7.0 version loaded.

**Comment by jolespin** [comment]
Is the usage correct? Give it an array of labels?

**Comment by jolespin** [comment]
Hey you can close this. you're right it worked now!
