### ISSUE TITLE
Rotating tick labels on countplot does not align

### ISSUE THREAD

**Issue by josepablog** [mwaskom/seaborn#985]
Hello,

I am trying to rotate the labels of a bar plot.  Unfortunately, when I do this, the labels do not align anymore. 

This is roughly the code:

```
import seaborn as sns
import pandas as pd

df = pd.read_csv("text.csv")
sns.countplot(x="column", data=df, order=order)
plt.xticks(rotation=-45)

```

And this is the output:

![image](https://cloud.githubusercontent.com/assets/1832193/17421073/caaac45a-5a5b-11e6-9f08-38f36fd291fa.png)

Notice that some labels are cluttered together, and there is some gaps. Any thoughts of how can I fix this?

**Comment by mwaskom** [comment]
This is a matplotlib question and will be best answered on StackOverflow.
