### ISSUE TITLE
add jitter option in pairplot?

### ISSUE THREAD

**Issue by agamemnonc** [mwaskom/seaborn#988]
Perhaps it would be useful to add the jitter option provided in stripplot also for the pairplot function?

**Comment by mwaskom** [comment]
I think you're looking for the `dodge` argument.

**Comment by agamemnonc** [comment]
But `dodge` is not available in `pairplot`, is it? 

Am I missing something?

**Comment by mwaskom** [comment]
Oh sorry I read that as `pointplot`. But asking for `jitter` in `pairplot` doesn't make a whole lot of sense because it is drawing scatterplots of continuous data, where you don't want to add jitter. Jitter only makes sense along a categorical axis.

**Comment by agamemnonc** [comment]
I guess you are right, but it might be useful in order to visualise
discrete-valued non-categorical data (coming from a Poisson distribution
for instance).

Of course the Poisson distribution is discrete and it wouldn't really make
sense to have continuous values, but it would help visualisation a bit
exactly in the same way that the jitter option does in stripplot.

(Hope that makes sense, if not I can come back with a numerical example).

**Comment by mwaskom** [comment]
IMO if you want to add jitter to continuous data you should do so yourself, rather than having the plotting function do it.

**Comment by agamemnonc** [comment]
Agreed, but I talked about discrete numerical data, not continuous (neither categorical). I hope we agree that these are three different things.
http://stats.stackexchange.com/questions/206/what-is-the-difference-between-discrete-data-and-continuous-data

I just thought it would be a nice addition to seaborn -which I love and use very often and many thanks for that-, and would also be happy to implement it myself if need be, but it seems like you are not really keen, so fair enough.
