### ISSUE TITLE
split attribute means different things for violinplot and stripplot

### ISSUE THREAD

**Issue by TheChymera** [mwaskom/seaborn#992]
To overlay my data on violinplots, I would have to use:

```
sns.violinplot(... split=False)
sns.stripplot(... split=True)
```

I guess this is because for the violin plot the split attribute is meant to split the violin, whereas for stripplots is means the hue attribute should be split.
I think such confusion can be avoided by calling the attribute `split_hue`.

Ofc I know about `sns.violinplot(... inner="points")` but it is not equivalent in appearance.

**Comment by mwaskom** [comment]
Yes, it's confusing. Oh well.

**Comment by TheChymera** [comment]
@mwaskom you wouldn't pull a PR that fixes the naming, then?

**Comment by mwaskom** [comment]
No.
