### ISSUE TITLE
importing seaborn breaks matplotlib ginput

### ISSUE THREAD

**Issue by nerduno** [mwaskom/seaborn#993]
Using Anaconda on MacOSX, the following code works fine:
```
import matplotlib.pyplot as plt
plt.plot([0,1],[0,1])
plt.ginput(0)
```

However if I import seaborn, then clicks for ginput no longer appear as small red crosshairs in the figure.  All graphical feedback disappears, though ginput still returns the selected points.

```
import seaborn
import matplotlib.pyplot as plt
plt.plot([0,1],[0,1])
plt.ginput(0)
```

**Comment by mwaskom** [comment]
If it's supposed to draw small crosses you probably need to set `markeredgewidth > 0`
