### ISSUE TITLE
FacetGrid with pd.Categorical data plots also empty categories

### ISSUE THREAD

**Issue by tritemio** [mwaskom/seaborn#997]
FacetGrid computes the number of axis by looking a the number of categories is the DataFrame column used as key is of type `pd.Categorical`.

If the passed DataFrame has no data for some categories the axis for this category is still created (and ends up being empty). This is a problem when passing a DataFrame which has been filtered from a bigger DataFrame and therefore has many "empty" categories.

This logic is implemented in `utils.categorical_order`:

https://github.com/mwaskom/seaborn/blob/master/seaborn/utils.py#L498

There seems to be much more try-except condition than necessary in that function, but I don't know if they are supposed to cover corner-cases or not.

A solution would be simplify `utils.categorical_order` and use `value.unique()` even for categorical Series (instead of getting the order from the category list).

**Comment by mwaskom** [comment]
Completely by design: https://github.com/mwaskom/seaborn/issues/361

**Comment by TomAugspurger** [comment]
I'd suggest using `remove_unused_categories` on your dataframe before plotting.
