### ISSUE TITLE
heatmap axes value show

### ISSUE THREAD

**Issue by XiaolinZHONG** [mwaskom/seaborn#999]
How should i do to show the axes value (data frame's columns name) vertically? 
following is my code, it will display the columns name horizontally.

`
corr=df.corr()# df is an DataFrame

sns.heatmap(corr, mask=mask, cmap=cmap, vmax=1,linewidths=.5,
            cbar_kws={"shrink": .6},annot=True,annot_kws={"size":8})
plt.show()`

**Comment by mwaskom** [comment]
This question belongs on stackoverflow, but make sure you come up with a fully reproducible example first.
